### ISSUE TITLE
Broccoli compiler doesn't refresh cache

### ISSUE THREAD

**Issue by jacovc86** [angular/angular-cli#1001]
New Project, created by the cli.

After changing the name of the component, (I've changed it also in index.ts, main.ts, spec.ts), but the cache just doesn't update the index.ts, hence the error

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  C:/angular2/MyApp/tmp/broccoli_type_script_compiler-input_base_path-LnI0wMec.tmp/0/src/app/MyApp.spec.ts (8, 10): Mo
dule '"C:/angular2/MyApp/tmp/broccoli_type_script_compiler-input_base_path-LnI0wMec.tmp/0/src/app/MyApp"' has no expor
ted mng 'MyApp'.
  C:/angular2/MyApp/tmp/broccoli_type_script_compiler-input_base_path-LnI0wMec.tmp/0/src/main.ts (3, 10): Module '"C:/a
ngular2/MyApp/tmp/broccoli_type_script_compiler-input_base_path-LnI0wMec.tmp/0/src/app/index"' has no exported mng 'Mya
pp'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\angular2\MyApp\node_modules\angular-cli\lib\broccoli\broccoli
-typescript.js:115:19)
    at BroccoliTypeScriptCompiler.build (C:\angular2\MyApp\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js
:43:10)
    at C:\angular2\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\angular2\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\no
de_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\angular2\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-wri
ter\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\angular2\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\nod
e_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\angular2\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modul
es\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\angular2\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writ
er\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\angular2\MyApp\node_modules\angular-cli\node_modul
es\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\angular2\MyApp\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:26:49
)
    at Angular2App._getTsTree (C:\angular2\MyApp\node_modules\angular-cli\lib\broccoli\angular2-app.js:321:18)
    at Angular2App._buildTree (C:\angular2\MyApp\node_modules\angular-cli\lib\broccoli\angular2-app.js:116:23)
    at new Angular2App (C:\angular2\MyApp\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\angular2\MyApp\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\angular2\MyApp\node_modules\angular-cli\node_modules\a
ngular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\angular2\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\m
odels\builder.js:89:10)
    at new Class (C:\angular2\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-obj
ect.js:18:12)
    at Class.module.exports.Task.extend.run (C:\angular2\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\ta
sks\serve.js:15:19)
    at C:\angular2\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\angular2\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_modules\r
svp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\angular2\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_mod
ules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\angular2\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_modules\rs
vp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\angular2\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist
\rsvp.js:1198:9)

My versions:

angular-cli: 1.0.0-beta.5
node: 5.10.0
os: win32 x64

**Comment by filipesilva** [comment]
Issue made obsolete by #1455.
