### ISSUE TITLE
ng test --single-run doesn't terminate the browser and causes timeout when there are compile time errors.

### ISSUE THREAD

**Issue by sgkazakov** [angular/angular-cli#10015]
### Versions
```
Angular CLI: 1.7.3
Node: 8.9.3
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps
1. Run **ng new xxx**.
2. **Add a script to the scripts property in angular.cli.json**
```
      "scripts": [
        "./sample.js"
      ],
```
The content of sample.js is not significant.
3. Make an error in a file in the app folder, so that the application don't compile.
4. Run **ng test --single-run**

### Observed behavior
There is an error in the console, but the browser is started and remains opened until it times out.

```
Error: src/app/app.component.ts(8,7): error TS1146: Declaration expected.
src/app/app.component.ts(8,17): error TS1005: ';' expected.
src/app/app.component.ts(8,30): error TS1005: ';' expected.

    at Compiler.compiler.plugin (C:\dev\sandbox\node_modules\@angular\cli\plugins\karma-webpack-throw-error.js:10:23)
    at Compiler.applyPlugins (C:\dev\sandbox\node_modules\tapable\lib\Tapable.js:61:14)
    at Watching._done (C:\dev\sandbox\node_modules\webpack\lib\Compiler.js:105:17)
    at onCompiled (C:\dev\sandbox\node_modules\webpack\lib\Compiler.js:55:18)
    at applyPluginsAsync.err (C:\dev\sandbox\node_modules\webpack\lib\Compiler.js:510:14)
    at next (C:\dev\sandbox\node_modules\tapable\lib\Tapable.js:202:11)
    at Compiler.<anonymous> (C:\dev\sandbox\node_modules\webpack\lib\CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (C:\dev\sandbox\node_modules\tapable\lib\Tapable.js:206:13)
    at compilation.seal.err (C:\dev\sandbox\node_modules\webpack\lib\Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (C:\dev\sandbox\node_modules\tapable\lib\Tapable.js:195:46)
    at applyPluginsAsync.err (C:\dev\sandbox\node_modules\webpack\lib\Compilation.js:677:19)
    at next (C:\dev\sandbox\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.compilation.plugin (C:\dev\sandbox\node_modules\webpack\lib\ProgressPlugin.js:123:6)
    at Compilation.applyPluginsAsyncSeries (C:\dev\sandbox\node_modules\tapable\lib\Tapable.js:206:13)
    at applyPluginsAsync.err (C:\dev\sandbox\node_modules\webpack\lib\Compilation.js:668:11)
    at next (C:\dev\sandbox\node_modules\tapable\lib\Tapable.js:202:11)
20 03 2018 02:00:04.036:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
20 03 2018 02:00:04.175:INFO [launcher]: Trying to start Chrome again (1/2).
```

### Desired behavior
If there are compile time errors, running ng test --single-run should always terminate the browser and not wait until it disconnects.

### Mention any other details that might be useful (optional)

Note that this is working properly in @angular/cli 1.4.9

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
