### ISSUE TITLE
Error: Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by syedmuhammadabid** [angular/angular-cli#10017]
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* ng new Project_Name
* ng serve

### Observed behavior
```
Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (PATH\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

### Desired behavior
```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-03-20T07:18:52.392Z
Hash: de7567d6a43ff6ecf4d5
Time: 10338ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 19.6 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 553 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 34.9 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 7.43 MB [initial] [rendered]

webpack: Compiled successfully.
```

### Mention any other details that might be useful (optional)
Angular CLI do not install '@angular-devkit/core' module by default we have to explicitly download this.
Please fix this issue.

**Comment by dominique-mueller** [comment]
I think this got fixed in newer version, try upgrading to the latest 1.6.x or even 1.7.x!
