### ISSUE TITLE
Error during build on scandir() at CliFilesystem.syncList

### ISSUE THREAD

**Issue by Tom4U** [angular/angular-cli#10085]
### Versions
```
Angular CLI: 1.7.3
Node: 6.11.5
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

* Activate the service worker on Windows for an existing Angular 5 app as described in the [Getting Started Guide](https://angular.io/guide/service-worker-getting-started)
* Run the build command: `ng build --prod`
* After creation of chunks the error occurs

### Observed behavior
Stack trace of the error:
```
An error occured during the build:
Error: ENOENT: no such file or directory, scandir '[DRIVELETTER]\[PROJECT]\src\app\dist\client'
    at Error (native)
    at Object.fs.readdirSync (fs.js:953:18)
    at CliFilesystem.syncList ([DRIVELETTER]\[PROJECT]\node_modules\@angular\cli\utilities\service-worker\index.js:19:28)
    at CliFilesystem.list ([DRIVELETTER]\[PROJECT]\node_modules\@angular\cli\utilities\service-worker\index.js:15:37)
    at Generator.<anonymous> ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.
js:257:66)
    at step ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:71:23)
    at Object.next ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:52:53)
    at [DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:45:71
    at __awaiter ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:41:12)
    at [DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:249:108
    at Array.map (native)
    at Generator.<anonymous> ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.
js:249:78)
    at step ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:71:23)
    at Object.next ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:52:53)
    at [DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:45:71
    at __awaiter ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:41:12)
ENOENT: no such file or directory, scandir '[DRIVELETTER]\[PROJECT]\src\app\dist\client'
Error: ENOENT: no such file or directory, scandir '[DRIVELETTER]\[PROJECT]\src\app\dist\client'
    at Error (native)
    at Object.fs.readdirSync (fs.js:953:18)
    at CliFilesystem.syncList ([DRIVELETTER]\[PROJECT]\node_modules\@angular\cli\utilities\service-worker\index.js:19:28)
    at CliFilesystem.list ([DRIVELETTER]\[PROJECT]\node_modules\@angular\cli\utilities\service-worker\index.js:15:37)
    at Generator.<anonymous> ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.
js:257:66)
    at step ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:71:23)
    at Object.next ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:52:53)
    at [DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:45:71
    at __awaiter ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:41:12)
    at [DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:249:108
    at Array.map (native)
    at Generator.<anonymous> ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.
js:249:78)
    at step ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:71:23)
    at Object.next ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:52:53)
    at [DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:45:71
    at __awaiter ([DRIVELETTER]\[PROJECT]\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:41:12)
```

### Desired behavior
Getting the production build running successfully.

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by Tom4U** [comment]
No, now it works with latest versions:

`Angular CLI: 7.1.4
Node: 8.11.3
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/pwa                      0.11.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1`
