### ISSUE TITLE
Should e2e --element-explorer work?

### ISSUE THREAD

**Issue by chadbr** [angular/angular-cli#10084]
### Versions
```
    
Angular CLI: 1.7.3
Node: 9.7.1
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps
ng new testapp --style=scss --prefix=damn --routing=true
cd testapp
ng e2e --element-explorer

### Observed behavior
```
ng e2e --element-explorer
** NG Live Development Server is listening on localhost:49152, open your browser on http://localhost:49152/ **
Date: 2018-03-27T16:47:18.242Z                                                - Hash: c787d77a88f6d298d3b2
Time: 5608ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 3.89 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 10 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 202 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 14.7 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.15 MB [initial] [rendered]
(node:59475) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

webpack: Compiled successfully.
[11:47:18] I/file_manager - creating folder /Users/chadbr/dev/tmp/testapp/node_modules/webdriver-manager/selenium
[11:47:19] I/update - chromedriver: unzipping chromedriver_2.37.zip
[11:47:19] I/update - chromedriver: setting permissions to 0755 for /Users/chadbr/dev/tmp/testWithPrefix/node_modules/webdriver-manager/selenium/chromedriver_2.37
[11:47:19] I/direct - Using ChromeDriver directly...
[11:47:20] I/protractor -
[11:47:20] I/protractor - ------- Element Explorer -------
[11:47:20] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.com/angular/protractor
[11:47:20] I/protractor -
[11:47:20] I/protractor - Type <tab> to see a list of locator strategies.
[11:47:20] I/protractor - Use the `list` helper function to find elements by strategy:
[11:47:20] I/protractor -   e.g., list(by.binding('')) gets all bindings.
[11:47:20] I/protractor -
module.js:559
    throw err;
    ^

Error: Cannot find module '_debugger'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chadbr/dev/tmp/testapp/node_modules/protractor/built/debugger/debuggerCommons.js:1:82)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)

```

### Desired behavior
Expected it to work...

Thanks - Chad

**Comment by markgoho-EDT** [comment]
Nope https://github.com/angular/protractor/issues/4307

**Comment by chadbr** [comment]
Thanks, I'll go ahead and close this... it's bummer what a mess that is!

**Comment by intellix** [comment]
Actually, maybe this is worth re-opening as I think the `--element-explorer` tag should be removed as they plan to remove it: https://github.com/angular/protractor/issues/4307#issuecomment-387307254
