### ISSUE TITLE
errors on v6.0.0-beta.8

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#10104]
### Versions
```
Angular CLI: 6.0.0-beta.8
Node: 8.9.3
OS: win32 x64
Angular: 6.0.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
@angular/cdk: 5.2.4
@angular/cli: 6.0.0-beta.8
@angular/material: 5.2.4
@angular-devkit/architect: 0.0.9
@angular-devkit/core: 0.4.8
@angular-devkit/schematics: 0.4.8
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.4.8
@schematics/update: 0.4.8
typescript: 2.7.2
webpack: error
```

### Repro steps
a) ng update --next 
b) remove global cli && yarn add@angular/cli@next -g again

### issue 1
After `ng -v` I realize webpack is not installed I do `yarn add webpack --dev` installed 4.3.0
### issue 2 
`ng s || ng build` get me: 
```
Cannot read property 'host' of null
TypeError: Cannot read property 'host' of null
    at Architect._loadJsonFile (C:\...\@angular-devkit\architect\src\architect.js:200:32)
    at Architect.loadArchitect (C:\...\@angular-devkit\architect\src\architect.js:68:45)
    at MergeMapSubscriber.workspaceLoader.loadWorkspace.pipe.operators_1.concatMap.workspace [as project] (C:\...\@angular\cli\models\architect-command.js:150:184)
    at MergeMapSubscriber._tryNext (C:\...\@angular\cli\node_modules\rxjs\operators\mergeMap.js:122:27)
    at MergeMapSubscriber._next (C:\...\@angular\cli\node_modules\rxjs\operators\mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (C:\...\@angular\cli\node_modules\rxjs\Subscriber.js:93:18)
    at DoSubscriber._next (C:\...\@angular\cli\node_modules\rxjs\operators\tap.js:88:30)
    at DoSubscriber.Subscriber.next (C:\...\@angular\cli\node_modules\rxjs\Subscriber.js:93:18)
    at MergeMapSubscriber.notifyNext (C:\...\@angular\cli\node_modules\rxjs\operators\mergeMap.js:145:30)
    at InnerSubscriber._next (C:\...\@angular\cli\node_modules\rxjs\InnerSubscriber.js:23:21)
```

**Comment by robertbaker** [comment]
You need to do a diff compare with a newly generated project. The project structure changed.

I upgraded fine.

**Comment by istiti** [comment]
@robertbaker where can I read about theses changements, changelog? or you just compare green project?  coz effectively lots things changed

Someone can link something about new structure?

**Comment by dottodot** [comment]
Might be helpful if some info was added to the release, even if it's just to indicate there has been a complete change to the project structure and angular-cli.json / angular.json looks fairly different too. It would at least help reduced the amount of issues being raised.

**Comment by robertbaker** [comment]
You're running a beta, probably shouldn't do that unless you're willing to deal with breaking changes and lack of docs.

What you do is open your project folder in a diff tool like BeyondCompare and a newly generated project with the same settings. Then just merge the changes into yours. You'll need to move your src files into the new directories to make the diff compare easier. Then delete files that are no longer needed, like typings.d.ts and angular-cli.json

**Comment by dominikg** [comment]
you can use angular-cli-diff to get a quick overview of structural changes.

https://github.com/cexbrayat/angular-cli-diff
https://github.com/cexbrayat/angular-cli-diff/compare/1.7.3...6.0.0-beta.8

maybe something like the [angular update guide](https://angular-update-guide.firebaseapp.com/),  would be a good idea for angular-cli aswell?

**Comment by istiti** [comment]
@dominikg  angular-cli-diff out of scope to me, but I had same idea this morning same update guid as angular would be awesome :)

**Comment by sandangel** [comment]
I generate a new project from cli beta 8 and have this error after set enableIvy: true.

**Comment by leo6104** [comment]
I made `.angular-cli.json -> angular.json converter` for my projects. 
https://gist.github.com/leo6104/b4a2da0863d3c5b1877860d62464c706 

If you want to test angular-cli >=6.0.0-beta.6, let's try this converter to create angular.json file :)

**Comment by splincode** [comment]
duplicate https://github.com/angular/angular-cli/issues/10113
