### ISSUE TITLE
ng build -prod failing 

### ISSUE THREAD

**Issue by kuldeepkeshwar** [angular/angular-cli#1012]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS : Mac OSX (El Capitan)
2. KuldeepMac:webapp kuldeepkeshwar$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 0.0.39
node: 4.2.2
os: darwin x64

**Logs**
KuldeepMac:webapp kuldeepkeshwar$ ng build -prod
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Build failed.
The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for main.js at file:///Users/kuldeepkeshwar/ui_workspace/webapp/tmp/bundle_plugin-input_base_path-x7xzuzQ1.tmp/0/main.js
        Error: ENOENT: no such file or directory, open '/Users/kuldeepkeshwar/ui_workspace/webapp/tmp/bundle_plugin-input_base_path-x7xzuzQ1.tmp/0/main.js.map'
    at Error (native)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BundlePlugin (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/lib/broccoli/angular-broccoli-bundle.js:11:10)
    at Angular2App._getBundleTree (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/lib/broccoli/angular2-app.js:375:55)
    at Angular2App._buildTree (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/lib/broccoli/angular2-app.js:137:21)
    at new Angular2App (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/lib/broccoli/angular2-app.js:42:23)
    at module.exports (/Users/kuldeepkeshwar/ui_workspace/webapp/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at /Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/angular-cli/lib/commands/build.js:32:24
    at lib$rsvp$$internal$$tryCatch (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

KuldeepMac:webapp kuldeepkeshwar$

**Comment by neilhem** [comment]
Update to the latest version global & local angular-cli `npm install --global angular-cli@1.0.0-beta.5` & `npm install angular-cli@1.0.0-beta.5 --save-dev`

**Comment by kuldeepkeshwar** [comment]
I have updated the clid but it's still breaking 

**logs**

Build error

The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for main.js at file:///Users/kuldeepkeshwar/ui_workspace/webapp/tmp/bundle_plugin-input_base_path-AcmWDZDo.tmp/0/main.js
	Error: ENOENT: no such file or directory, open '/Users/kuldeepkeshwar/ui_workspace/webapp/tmp/bundle_plugin-input_base_path-AcmWDZDo.tmp/0/Users/kuldeepkeshwar/ui_workspace/webapp/tmp/broccoli_type_script_compiler-input_base_path-vnmUxBQL.tmp/0/main.js.map'
    at Error (native)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BundlePlugin (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/lib/broccoli/angular-broccoli-bundle.js:11:10)
    at Angular2App._getBundleTree (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/lib/broccoli/angular2-app.js:421:22)
    at Angular2App._buildTree (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/lib/broccoli/angular2-app.js:159:21)
    at new Angular2App (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/kuldeepkeshwar/ui_workspace/webapp/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/kuldeepkeshwar/ui_workspace/webapp/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

**Comment by hmrc87** [comment]
In the recent BETA-Upgrades they added importsettings to angular-cli-build.js. I think you created the project with an older version so that the new importsettings are missing. 

Have a look here: https://github.com/angular/angular-cli/blob/9a7bfe0d564938b265c3166aa6917cf7231e83a2/addon/ng2/blueprints/ng2/files/angular-cli-build.js

**Comment by kuldeepkeshwar** [comment]
@hmrc87 i have updated the angular-cli-build.js
still getting same error.

plus tsconfig.json

`{
  "ambientDevDependencies": {
    "angular-protractor": "registry:dt/angular-protractor#1.5.0+20160425143459",
    "jasmine": "registry:dt/jasmine#2.2.0+20160412134438",
    "selenium-webdriver": "registry:dt/selenium-webdriver#2.44.0+20160317120654"
  },
  "ambientDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654"
  }
}
`

**Comment by neilhem** [comment]
try to remove dist and tmp folders, then run `ng build -prod` again

**Comment by kuldeepkeshwar** [comment]
still same

**Comment by iloveyo123u1** [comment]
show your   **system-config.ts**

**Comment by kuldeepkeshwar** [comment]
created new project and now it's working fine
