### ISSUE TITLE
ERROR in : TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by rightisleft** [angular/angular-cli#10131]
### Versions
```
Angular CLI: 1.7.3
Node: 8.9.4
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps
* run `npm run buildprod`
* executed `ng build --prod --no-progress`

### Observed behavior
```
> ng build --prod --no-progress

Date: 2018-04-02T16:41:41.522Z
Hash: 64264ac9729ed922bc6d
Time: 22248ms
chunk {scripts} scripts.7f8b770a5f080be06e69.bundle.js (scripts) 159 kB [initial] [rendered]
chunk {0} styles.e3d827b8848de46fb3a2.bundle.css (styles) 1.23 MB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in : TypeError: Cannot read property 'kind' of undefined
    at nodeCanBeDecorated (/app/node_modules/typescript/lib/typescript.js:7934:36)
    at nodeIsDecorated (/app/node_modules/typescript/lib/typescript.js:7954:16)
    at Object.nodeOrChildIsDecorated (/app/node_modules/typescript/lib/typescript.js:7958:16)
    at isDecoratedClassElement (/app/node_modules/typescript/lib/typescript.js:52074:23)
    at isInstanceDecoratedClassElement (/app/node_modules/typescript/lib/typescript.js:52065:20)
    at Object.filter (/app/node_modules/typescript/lib/typescript.js:1639:31)
    at getDecoratedClassElements (/app/node_modules/typescript/lib/typescript.js:52047:23)
    at generateClassElementDecorationExpressions (/app/node_modules/typescript/lib/typescript.js:52221:27)
    at addClassElementDecorationStatements (/app/node_modules/typescript/lib/typescript.js:52210:44)
    at visitClassDeclaration (/app/node_modules/typescript/lib/typescript.js:51535:13)
    at visitTypeScript (/app/node_modules/typescript/lib/typescript.js:51376:28)
    at visitorWorker (/app/node_modules/typescript/lib/typescript.js:51189:24)
    at sourceElementVisitorWorker (/app/node_modules/typescript/lib/typescript.js:51221:28)
    at saveStateAndInvoke (/app/node_modules/typescript/lib/typescript.js:51133:27)
    at sourceElementVisitor (/app/node_modules/typescript/lib/typescript.js:51203:20)
    at visitNodes (/app/node_modules/typescript/lib/typescript.js:49517:48)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.0.0 buildprod: `ng build --prod --no-progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web@0.0.0 buildprod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-02T16_41_41_613Z-debug.log
/app #
/app # ng --version

```

### Desired behavior
Should be able to use AOT

applying --aot=false fixes the issue

### Mention any other details that might be useful (optional)

This was working on older version of angular 4.0

**Comment by splincode** [comment]
https://github.com/typestack/class-transformer/issues/108

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by alan-agius4** [comment]
Closing as no further feedback was provided by the reporter.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by manjitha-teshara** [comment]
this not solution for me


ERROR in : TypeError: Cannot read property 'kind' of undefined
    at checkNestedBlockScopedBinding
