### ISSUE TITLE
Migrate failed, couldn't find configuration file

### ISSUE THREAD

**Issue by markgoho-EDT** [angular/angular-cli#10147]
### Versions
``` bash
Angular CLI: 6.0.0-rc.0
Node: 9.5.0
OS: win32 x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-rc.0
@angular-devkit/architect: 0.5.0
@angular-devkit/build-angular: 0.0.9
@angular-devkit/build-optimizer: 0.4.8
@angular-devkit/core: 0.5.0
@angular-devkit/schematics: 0.5.0
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.5.0
@schematics/update: 0.5.0
typescript: 2.7.2
webpack-bundle-analyzer: 2.11.1
webpack: 4.1.0
```

### Repro steps
* `ng serve`
* Got the migrate message:
``` bash
An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
Error: An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
at WorkspaceLoader._assertUpdatedWorkspace (C:\Users\mark.goho\Documents\GitHub\app-copa-ng6\node_modules\@angular\cli\models\workspace-loader.js:73:19)
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\mark.goho\Documents\GitHub\app-copa-ng6\node_modules\@angular\cli\models\workspace-loader.js:29:14)
    at WorkspaceLoader.loadWorkspace (C:\Users\mark.goho\Documents\GitHub\app-copa-ng6\node_modules\@angular\cli\models\workspace-loader.js:25:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\mark.goho\Documents\GitHub\app-copa-ng6\node_modules\@angular\cli\models\architect-command.js:151:32)
    at ServeCommand.<anonymous> (C:\Users\mark.goho\Documents\GitHub\app-copa-ng6\node_modules\@angular\cli\models\architect-command.js:45:25)
    at Generator.next (<anonymous>)
    at C:\Users\mark.goho\Documents\GitHub\app-copa-ng6\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mark.goho\Documents\GitHub\app-copa-ng6\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\Users\mark.goho\Documents\GitHub\app-copa-ng6\node_modules\@angular\cli\models\architect-command.js:44:16)
```
* Ran the suggested command

### Observed behavior
``` bash
Could not find configuration file
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c ng update @angular/cli --migrate-only --from=1.7.1
```

### Desired behavior
I'm not sure what I expect, but probably a restructured project.

**Comment by MattMorrisDev** [comment]
Same issue for me. Migrated, tried to serve the app, and it says it still needs to be upgraded. It already created `angular.json` and touched package.json, karma.conf.js, tsconfig.spec.json etc though.

**Comment by MattMorrisDev** [comment]
I tried updating the global installation also - same result. The `Could not find configuration file` error happens when you try to do an `ng update` a second time.

Other random info: I'm using yarn, and it appears that the upgrade process is using npm. I also have husky git hooks. Here's my output:

`ng update @angular/cli --migrate-only --from=1.7.3`
```Updating karma configuration
Updating configuration
Removing old config file (.angular-cli.json)
Writing config file (angular.json)

> husky@0.14.3 uninstall /Users/my-user-name/my-app/ui/node_modules/husky
> node ./bin/uninstall.js

husky
uninstalling Git hooks
done

npm WARN gentlyRm not removing /Users/my-user-name/my-app/ui/node_modules/.bin/uuid as it wasn't installed by /Users/my-user-name/my-app/ui/node_modules/uuid
npm WARN gentlyRm not removing /Users/my-user-name/my-app/ui/node_modules/.bin/semver as it wasn't installed by /Users/my-user-name/my-app/ui/node_modules/semver
npm WARN gentlyRm not removing /Users/my-user-name/my-app/ui/node_modules/.bin/mime as it wasn't installed by /Users/my-user-name/my-app/ui/node_modules/mime
npm WARN gentlyRm not removing /Users/my-user-name/my-app/ui/node_modules/fsevents/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/my-user-name/my-app/ui/node_modules/fsevents/node_modules/node-pre-gyp

> fsevents@1.1.3 install /Users/my-user-name/my-app/ui/node_modules/fsevents
> node install

[
  fsevents
] Success: "/Users/my-user-name/my-app/ui/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uws@9.14.0 install /Users/my-user-name/my-app/ui/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@4.8.3 install /Users/my-user-name/my-app/ui/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/my-user-name/.npm/node-sass/4.8.3/darwin-x64-57_binding.node

> husky@0.14.3 install /Users/my-user-name/my-app/ui/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
done


> node-sass@4.8.3 postinstall /Users/my-user-name/my-app/ui/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/my-user-name/my-app/ui/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
added 657 packages, removed 81 packages and updated 898 packages in 53.651s
DELETE .angular-cli.json
CREATE angular.json (4992 bytes)
UPDATE karma.conf.js (1222 bytes)
UPDATE src/tsconfig.spec.json (323 bytes)
UPDATE package.json (4316 bytes)
```

`[my-user-name@~/my-app/ui]: $ npm start`
```> my-app@0.0.0 start /Users/my-user-name/my-app/ui
> ng serve --proxy-config proxy.conf.json --no-delete-output-path --base-href '/'

An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

ng update @angular/cli --migrate-only --from=1.7.1
npm i
Error: An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

ng update @angular/cli --migrate-only --from=1.7.1
npm i
at WorkspaceLoader._assertUpdatedWorkspace (/Users/my-user-name/my-app/ui/node_modules/@angular/cli/models/workspace-loader.js: 73: 19)
at WorkspaceLoader._getProjectWorkspaceFilePath (/Users/my-user-name/my-app/ui/node_modules/@angular/cli/models/workspace-loader.js: 29: 14)
at WorkspaceLoader.loadWorkspace (/Users/my-user-name/my-app/ui/node_modules/@angular/cli/models/workspace-loader.js:25: 21)
at ServeCommand._loadWorkspaceAndArchitect (/Users/my-user-name/my-app/ui/node_modules/@angular/cli/models/architect-command.js: 151: 32)
at ServeCommand.<anonymous> (/Users/my-user-name/my-app/ui/node_modules/@angular/cli/models/architect-command.js: 45: 25)
at Generator.next (<anonymous>)
at /Users/my-user-name/my-app/ui/node_modules/@angular/cli/models/architect-command.js: 7: 71
at new Promise (<anonymous>)
at __awaiter (/Users/my-user-name/my-app/ui/node_modules/@angular/cli/models/architect-command.js: 3: 12)
at ServeCommand.initialize (/Users/my-user-name/my-app/ui/node_modules/@angular/cli/models/architect-command.js: 44: 16)
```

`[my-user-name@~/my-app/ui]:$ ng update @angular/cli --migrate-only --from=1.7.3`
```
Could not find configuration file
```

**Comment by lacolaco** [comment]
I was in the same situation and I found `~/.angular-cli.json`. After removing it,  this error does not happen! ...but another error does.

**Comment by hansl** [comment]
This should be fixed with `rc.1`. Please try and file a new issue if it's not fixed yet. Thanks.
