### ISSUE TITLE
`ng generate` does not show update message

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#10156]
When using `6.0.0-rc.0` on a 1.7 project, running `ng generate component my-comp` will show

```
kamik@RED-X1C6 MINGW64 /d/sandbox/1.7-project (master)
$ ng generate component my-comp
Invalid project: missing workspace file.
Error: Invalid project: missing workspace file.
    at verifyWorkspace (D:\sandbox\1.7-project\node_modules\@angular\cli\models\command-runner.js:187:15)
    at D:\sandbox\1.7-project\node_modules\@angular\cli\models\command-runner.js:66:17
    at Generator.next (<anonymous>)
    at fulfilled (D:\sandbox\1.7-project\node_modules\@angular\cli\models\command-runner.js:4:58)
    at <anonymous>
```

But instead it should show a message prompting the user to update like `ng build`:

```
kamik@RED-X1C6 MINGW64 /d/sandbox/1.7-project (master)
$ ng build
An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
Error: An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
    at WorkspaceLoader._assertUpdatedWorkspace (D:\sandbox\1.7-project\node_modules\@angular\cli\models\workspace-loader.js:73:19)
    at WorkspaceLoader._getProjectWorkspaceFilePath (D:\sandbox\1.7-project\node_modules\@angular\cli\models\workspace-loader.js:29:14)
    at WorkspaceLoader.loadWorkspace (D:\sandbox\1.7-project\node_modules\@angular\cli\models\workspace-loader.js:25:21)
    at BuildCommand._loadWorkspaceAndArchitect (D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:151:32)
    at BuildCommand.<anonymous> (D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:45:25)
    at Generator.next (<anonymous>)
    at D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:3:12)
    at BuildCommand.initialize (D:\sandbox\1.7-project\node_modules\@angular\cli\models\architect-command.js:44:16)
```

**Comment by clydin** [comment]
Fixed via https://github.com/angular/angular-cli/pull/10162
