### ISSUE TITLE
cli@rc.0 fails to create new project and serve it

### ISSUE THREAD

**Issue by rokerkony** [angular/angular-cli#10163]
### Versions
```
Angular CLI: 6.0.0-rc.0
Node: 9.10.1
OS: darwin x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-rc.0
@angular-devkit/architect: 0.0.10
@angular-devkit/build-angular: 0.0.10
@angular-devkit/build-optimizer: 0.4.9
@angular-devkit/core: 0.4.9
@angular-devkit/schematics: 0.5.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-beta.9
@schematics/angular: 0.5.0
@schematics/update: 0.5.0
typescript: 2.7.2
webpack: 4.1.0
```

### Repro steps
When I ran "ng new ..." I already got a warning:
```
ng new -S --style=scss frontend
(node:96293) UnhandledPromiseRejectionWarning: Error: An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
    at WorkspaceLoader._assertUpdatedWorkspace (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:73:19)
    at WorkspaceLoader._getProjectWorkspaceFilePath (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:29:14)
    at WorkspaceLoader.loadWorkspace (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:25:21)
    at NewCommand._loadWorkspace (/usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:255:29)
    at NewCommand.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:53:18)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:3:12)
    at NewCommand.initialize (/usr/local/lib/node_modules/@angular/cli/models/schematic-command.js:52:16)
(node:96293) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
...
...
added 1285 packages in 75.174s
    Directory is already under version control. Skipping initialization of git.
CREATE frontend/README.md (1034 bytes)
...
```

and ng serve fails on similar error:
```
npm start

> frontend@0.0.0 start /Users/konradcerny/Sites/Erento/frontend
> ng serve

An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
Error: An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
...
```

I didn't have this problem with version `6.0.0-beta.8`

**Comment by rokerkony** [comment]
the change appears already in `6.0.0-beta.9`

**Comment by filipesilva** [comment]
Heya @rokerkony, I think what's happening is that you have a `.angular-cli.json` file in one of the folders above your project and we incorrectly detect the current project to have not been migrated. This is something we will fix.

**Comment by rokerkony** [comment]
@filipesilva I just tried to verify your statement... but I got even more "interesting" output:
(created folder in root - MacOS@10.13.3)

```
➜  / sudo mkdir __temp
➜  / cd __temp
➜  /__temp ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 6.0.0-rc.0
Node: 9.10.1
OS: darwin x64
Angular:
...
➜  /__temp ng new -S --style=scss frontend

(node:99304) UnhandledPromiseRejectionWarning: Error: Local workspace file ('angular.json') could not be found.
```

but maybe it is related to what you wrote because it cannot find `angular.json` file

**Comment by wpcfan** [comment]
yes, I ran into this too. 

```
Angular CLI: 6.0.0-rc.0
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-rc.0
@angular-devkit/architect: 0.0.10
@angular-devkit/build-angular: 0.0.10
@angular-devkit/build-optimizer: 0.4.9
@angular-devkit/core: 0.4.9
@angular-devkit/schematics: 0.5.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-beta.9
@schematics/angular: 0.5.0
@schematics/update: 0.5.0
typescript: 2.7.2
webpack: 4.1.0

```

**Comment by clydin** [comment]
Fixed via https://github.com/angular/angular-cli/pull/10162

**Comment by lyudmilpetrov** [comment]
I run into the same issue upgrading to v. 6

**Comment by nhhockeyplayer** [comment]
cannot upgrade here either

```
Angular CLI: 6.0.0-rc.7
Node: 9.3.0
OS: win32 x64
Angular: 6.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.10
@angular-devkit/build-angular     0.5.10
@angular-devkit/build-optimizer   0.5.10
@angular-devkit/core              0.5.10
@angular-devkit/schematics        0.5.10
@angular/cdk                      6.0.0-rc.13
@angular/cli                      6.0.0-rc.7
@angular/flex-layout              5.0.0-beta.14
@angular/material                 6.0.0-rc.13
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.8
@schematics/angular               0.5.10
@schematics/update                0.5.10
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.6.0

```


```
C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api>npm run build-dev

> api@1.0.0 build-dev C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api
> ng build --output-path=dist/ --target=development --environment=dev

Project 'development' could not be found in workspace.
Error: Project 'development' could not be found in workspace.
    at Workspace.getProject (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\@angular-devkit\core\src\workspace\workspace.js:83:19)
    at Architect.getBuilderConfiguration (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\@angular-devkit\architect\src\architect.js:96:41)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\@ang
ular\cli\models\architect-command.js:77:55)
    at MergeMapSubscriber._tryNext (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\rxjs\internal\operators\mergeMap.js:122:27)
    at MergeMapSubscriber._next (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\rxjs\internal\operators\mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\rxjs\internal\Subscriber.js:103:18)
    at TapSubscriber._next (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\rxjs\internal\operators\tap.js:109:26)
    at TapSubscriber.Subscriber.next (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\rxjs\internal\Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\rxjs\internal\operators\mergeMap.js:141:26)
    at InnerSubscriber._next (C:\apache-tomcat-9.0.0.M17\webapps\ROOT\api\node_modules\rxjs\internal\InnerSubscriber.js:30:21)
```

**Comment by pratul1** [comment]
I am stuck at the same place.
I have the latest angular-cli version (6.0.3) on my system, and have undertaken a older project to make some changes in it. This project has cli(1.2.6-> as per package.json) and when I run the command ng --serve, it throws the error : Local workspace file ('angular.json') could not be found.

Any Advice on what all I will need to do to make this project run on my system?

**Comment by ogarvey** [comment]
@pratul1 The command ng update @angular/cli will delete the angular.cli.json and create an angular.json file for you.

Just be sure to make a backup of the original file first :)

**Comment by hfakouri** [comment]
I started from scratch by installing Node and Angular CLI. Still have the same issue.

`Angular CLI: 6.0.8`
`Node: 8.11.2`
`OS: win32 x64`
`Angular: 6.0.3`
`... animations, common, compiler, compiler-cli, core, forms`
`... http, language-service, platform-browser`
`... platform-browser-dynamic, router`

`Package                           Version`
`-----------------------------------------------------------`
`@angular-devkit/architect         0.6.8`
`@angular-devkit/build-angular     0.6.8`
`@angular-devkit/build-optimizer   0.6.8`
`@angular-devkit/core              0.6.8`
`@angular-devkit/schematics        0.6.8`
`@angular/cli                      6.0.8`
`@ngtools/webpack                  6.0.8`
`@schematics/angular               0.6.8`
`@schematics/update                0.6.8`
`rxjs                              6.2.0`
`typescript                        2.7.2`
`webpack                           4.8.3`

When I run:

`ng serve --open`

I get this error:

`Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:180:32)
    at ServeCommand.<anonymous> (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:46:16)
    at Object.<anonymous> (C:\Users\[username]\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:87:23)`

**Comment by Pieter-1337** [comment]
How can I fix this when I did not backup the original angular.cli.json file... This is really confusing for beginners

**Comment by Bushan11** [comment]
I upgraded the angular CLI using below command 

npm install @angular/cli@latest

then i got below error when run the command = ng update @angular/cli
![angular_issue](https://user-images.githubusercontent.com/31878643/41462153-84fdbcb6-70af-11e8-9033-8cb0e0f65c7e.PNG)

**Comment by molcik** [comment]
For people googling this error. It’s probably because your global **@angular/cli** version and **@angular/compiler-cli** are differentf  **[here is how to fix it (my blog)](https://filipmolcik.com/error-local-workspace-file-angular-json-could-not-be-found/)**.
