### ISSUE TITLE
Problems with --mobile and app-shell

### ISSUE THREAD

**Issue by colindevs** [angular/angular-cli#1016]
*(I am on OSX El Capitan, running `angular-cli: 0.1.0 node: 4.2.3 os: darwin x64`)*

I recently decided to try out Angular Mobile, and so I created an app through the CLI in mobile mode:
```
ng new example --mobile
```

I then proceeded to install some `@angular-material2` components and started making an app shell.
But when I tried to `ng serve`, it failed, telling me that it couldn't find `@angular/app-shell` which I imported along with some Material elements in `example.component.ts`

So then I looked in my `package.json` and system js setup, and angular cli build file, and found that `@angular/app-shell` and service worker aren't even saved and installed! So then I looked at the "puppy-love" example app from Google I/O and in their package.json they are listed.

So, to recreate the problem, I started a mobile app from scratch and here are the resulting files:

Here are the exact steps I took:
```
Colins-MacBook-Pro:Desktop colin$ ng new mobile --mobile
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing ng2
  create .clang-format
  create .editorconfig
  create src/app/mobile.component.css
  create src/app/mobile.component.html
  create src/app/mobile.component.spec.ts
  create src/app/mobile.component.ts
  create src/app/environment.ts
  create src/app/index.ts
  create src/app/shared/index.ts
  create src/favicon.ico
  create src/icon.png
  create src/index.html
  create src/main.ts
  create src/manifest.webapp
  create src/system-config.ts
  create src/tsconfig.json
  create src/typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config/environment.dev.ts
  create config/environment.js
  create config/environment.prod.ts
  create config/karma-test-shim.js
  create config/karma.conf.js
  create config/protractor.conf.js
  create e2e/app.e2e.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create .gitignore
  create package.json
  create public/.npmignore
  create tslint.json
  create typings.json
Successfully initialized git.
⠧ Installing packages for tooling via npm
├── es6-shim (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

Installed packages for tooling via npm.
Colins-MacBook-Pro:Desktop colin$ cd mobile
Colins-MacBook-Pro:mobile colin$ cat package.json
{
  "name": "mobile",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng server",
    "postinstall": "typings install",
    "lint": "tslint \"src/**/*.ts\"",
    "format": "clang-format -i -style=file --glob=src/**/*.ts",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "angular-cli": "0.0.*",
    "clang-format": "^1.0.35",
    "codelyzer": "0.0.14",
    "ember-cli-inject-live-reload": "^1.4.0",
    "jasmine-core": "^2.4.1",
    "jasmine-spec-reporter": "^2.4.0",
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.3",
    "karma-jasmine": "^0.3.8",
    "protractor": "^3.3.0",
    "ts-node": "^0.5.5",
    "tslint": "^3.6.0",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  }
}
Colins-MacBook-Pro:mobile colin$ 
Colins-MacBook-Pro:mobile colin$ cat angular-cli-build.js
/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js'
    ]
  });
};
Colins-MacBook-Pro:mobile colin$ cat src/system-config.ts
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
};

/** User packages configuration. */
const packages: any = {
};

////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
const barrels: string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/http',
  '@angular/router',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',

  // Thirdparty barrels.
  'rxjs',

  // App specific barrels.
  'app',
  'app/shared',
  /** @cli-barrel */
];

const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});

/** Type declaration for ambient System. */
declare var System: any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js'
  },
  packages: cliSystemConfigPackages
});

// Apply the user's configuration.
System.config({ map, packages });
Colins-MacBook-Pro:mobile colin$ 
```

So there are the three main files, printed out in my terminal: `package.json`, `angular-cli-build.js`, and `system-config.ts`.

Now let's compare them to the files from the `puppy-love` Google I/O example app:

**puppy-love-io/package.json:**
```
{
  "name": "puppy-love-io",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng server",
    "postinstall": "typings install",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "@angular/platform-server": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/service-worker": "^0.2.0",
    "@angular/app-shell": "^0.0.0",
    "angular2-broccoli-prerender": "^0.11.0",
    "angular2-universal":"^0.100.3",
    "angular2-universal-polyfills": "^0.4.1",
    "preboot": "^2.0.10",
    "angular-cli": "^1.0.0-beta.4",
    "codelyzer": "0.0.19",
    "ember-cli-inject-live-reload": "^1.4.0",
    "jasmine-core": "^2.4.1",
    "jasmine-spec-reporter": "^2.4.0",
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.3",
    "karma-jasmine": "^0.3.8",
    "protractor": "^3.3.0",
    "ts-node": "^0.5.5",
    "tslint": "^3.6.0",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  }
}
```
 
**puppy-love-io/angular-cli-build.js:**
```
/* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      '@angular2-material/**/*',
      'angularfire2/**/*',
      'firebase/lib/*.js'
    ]
  });
};
```

**puppy-love-io/src/system-config.ts:**
```
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map:any = {
  '@angular2-material': 'vendor/@angular2-material',
  'angularfire2': 'vendor/angularfire2',
  'firebase': 'vendor/firebase'
};

/** User packages configuration. */
const packages:any = {
  'angularfire2': {main: 'angularfire2.js'},
  'firebase': {main: 'lib/firebase-web.js'}
};

const materialPkgs:string[] = [
  'core',
  'toolbar',
  'icon',
  'button',
  'sidenav',
  'list',
  'card',
  'input',
];

materialPkgs.forEach((pkg) => {
  packages[`@angular2-material/${pkg}`] = {main: `${pkg}.js`};
});

////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
const barrels:string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/http',
  '@angular/router-deprecated',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',
  '@angular/app-shell',

  // Thirdparty barrels.
  'rxjs',

  // App specific barrels.
  'app',
  'app/shared',
    'app/+dogs'
/** @cli-barrel */
];

const cliSystemConfigPackages:any = {};
barrels.forEach((barrelName:string) => {
  cliSystemConfigPackages[barrelName] = {main: 'index'};
});

/** Type declaration for ambient System. */
declare var System:any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js'
  },
  packages: cliSystemConfigPackages
});

// Apply the user's configuration.
System.config({map, packages});
```

As you can see, there are several differences:

The `package.json` in `puppy-love` is different than mine. It requires several additional packages, including:

```
    "@angular/platform-server": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/service-worker": "^0.2.0",
    "@angular/app-shell": "^0.0.0",
    "angular2-broccoli-prerender": "^0.11.0",
    "angular2-universal":"^0.100.3",
    "angular2-universal-polyfills": "^0.4.1",
    "preboot": "^2.0.10",
``` 

Note `"@angular/app-shell"`, the package that was missing and caused my `serve` failure.

The same thing goes for the two different `system-config.ts` files. Mine is different than `puppy-love`'s, omitting `@angular/app-shell',` from `const barrels:string[]`. 

So I kind of see where my problem is, and I could probably fix it by manually requiring these files. But my real question is why these files weren't included, even though I used the `--mobile` flag at `ng new`. Did I do something wrong, or is there a problem with the CLI? 

Thanks for reviewing my issue, and I hope you guys have some feedback for me!

Colin Pirillo
<a href="twitter.com/colindevs" target="blank">@colindevs</a>

**Comment by filipesilva** [comment]
Your generated project came with `"angular-cli": "0.0.*",` on it's `package.json`, which makes me thing it's kinda old. That changed on may 7th (https://github.com/angular/angular-cli/commit/02073ae7c662ecebc37f511f7d7291a3e544690c).

Can you run `ng version` *outside* of your project and tell me what you get?

**Comment by colindevs** [comment]
`ng --version` in Desktop:

![screen shot 2016-06-05 at 4 42 20 pm](https://cloud.githubusercontent.com/assets/12850952/15808092/87af8184-2b3c-11e6-9332-f8e2ecfe1522.png)

(`0.1.0`)

**Comment by colindevs** [comment]
@filipesilva by the way, I ran `sudo npm i -g angular-cli` today before trying all of this.

**Comment by filipesilva** [comment]
Ah I believe that to be the problem. The commit that added that specific dependency (https://github.com/angular/angular-cli/commit/e7d7ed89934a2452ecfcc5db524011df6ba7e95e) got in at May 18th, and was released in `1.0.0-beta.3`.

Can you do `npm install i -g angular-cli@latest`?

**Comment by colindevs** [comment]
Yeah, and then I'll print out all the files again, will post.

**Comment by colindevs** [comment]
It worked! Now all the proper packages are included:

```
Colins-MacBook-Pro:Desktop colin$ cd example
Colins-MacBook-Pro:example colin$ cat package.json 
{
  "name": "example",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng server",
    "postinstall": "typings install",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "@angular/platform-server": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/service-worker": "^0.2.0",
    "@angular/app-shell": "^0.0.0",
    "angular2-broccoli-prerender": "^0.11.0",
    "angular2-universal":"^0.100.3",
    "angular2-universal-polyfills": "^0.4.1",
    "preboot": "^2.0.10",
    "angular-cli": "^1.0.0-beta.5",
    "codelyzer": "0.0.19",
    "ember-cli-inject-live-reload": "^1.4.0",
    "jasmine-core": "^2.4.1",
    "jasmine-spec-reporter": "^2.4.0",
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.3",
    "karma-jasmine": "^0.3.8",
    "protractor": "^3.3.0",
    "ts-node": "^0.5.5",
    "tslint": "^3.6.0",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  }
}
```
And:
```
Colins-MacBook-Pro:example colin$ cat src/system-config.ts
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
};

/** User packages configuration. */
const packages: any = {
};

////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
const barrels: string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/http',
  '@angular/router',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',
  '@angular/app-shell',

  // Thirdparty barrels.
  'rxjs',

  // App specific barrels.
  'app',
  'app/shared',
  /** @cli-barrel */
];

const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});

/** Type declaration for ambient System. */
declare var System: any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js'
  },
  packages: cliSystemConfigPackages
});

// Apply the user's configuration.
System.config({ map, packages });
Colins-MacBook-Pro:example colin$ 

```

**Comment by colindevs** [comment]
But, new problems have arose, and it still won't `ng serve`. Error log at `ng serve`:
```
Colins-MacBook-Pro:example colin$ ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: Command failed: /bin/sh -c node /Users/colin/Desktop/example/node_modules/angular2-broccoli-prerender/dist/child_proc.js  --sourceHtml=/Users/colin/Desktop/example/tmp/app_shell_plugin-input_base_path-Gu8MgoO7.tmp/0/index.html --optionsPath=/Users/colin/Desktop/example/tmp/app_shell_plugin-input_base_path-Gu8MgoO7.tmp/0/main-app-shell --outputIndexPath=/Users/colin/Desktop/example/tmp/app_shell_plugin-output_path-8sIl4OA7.tmp/index.html

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

The broccoli plugin was instantiated at: 
    at AppShellPlugin.Plugin (/Users/colin/Desktop/example/node_modules/angular2-broccoli-prerender/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (/Users/colin/Desktop/example/node_modules/angular2-broccoli-prerender/node_modules/broccoli-caching-writer/index.js:21:10)
    at new AppShellPlugin (/Users/colin/Desktop/example/node_modules/angular2-broccoli-prerender/dist/prerender.js:15:16)
    at Angular2App._buildTree (/Users/colin/Desktop/example/node_modules/angular-cli/lib/broccoli/angular2-app.js:153:48)
    at new Angular2App (/Users/colin/Desktop/example/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/colin/Desktop/example/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/colin/Desktop/example/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/colin/Desktop/example/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/colin/Desktop/example/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/colin/Desktop/example/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/colin/Desktop/example/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/colin/Desktop/example/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/colin/Desktop/example/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/colin/Desktop/example/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/colin/Desktop/example/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:419:9)



```

**Comment by colindevs** [comment]
The comment above is an error shown after running `ng serve`, as soon as `ng new --mobile` finished. No steps in between. But I forgot the error log I got at `ng new`, before the one above:

```
Colins-MacBook-Pro:Desktop colin$ ng new example --mobile
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing ng2
  create .clang-format
  create .editorconfig
  create src/app/example.component.spec.ts
  create src/app/example.component.ts
  create src/app/environment.ts
  create src/app/index.ts
  create src/app/shared/index.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/system-config.ts
  create src/tsconfig.json
  create src/typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config/environment.dev.ts
  create config/environment.js
  create config/environment.prod.ts
  create config/karma-test-shim.js
  create config/karma.conf.js
  create config/protractor.conf.js
  create e2e/app.e2e.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create .gitignore
  create package.json
  create public/.npmignore
  create tslint.json
  create typings.json
installing mobile
  create src/icons/android-chrome-144x144.png
  create src/icons/android-chrome-192x192.png
  create src/icons/android-chrome-36x36.png
  create src/icons/android-chrome-48x48.png
  create src/icons/android-chrome-72x72.png
  create src/icons/android-chrome-96x96.png
  create src/icons/apple-touch-icon-114x114.png
  create src/icons/apple-touch-icon-120x120.png
  create src/icons/apple-touch-icon-144x144.png
  create src/icons/apple-touch-icon-152x152.png
  create src/icons/apple-touch-icon-180x180.png
  create src/icons/apple-touch-icon-57x57.png
  create src/icons/apple-touch-icon-60x60.png
  create src/icons/apple-touch-icon-72x72.png
  create src/icons/apple-touch-icon-76x76.png
  create src/icons/apple-touch-icon-precomposed.png
  create src/icons/apple-touch-icon.png
  create src/icons/favicon-16x16.png
  create src/icons/favicon-32x32.png
  create src/icons/favicon-96x96.png
  create src/icons/icon.png
  create src/icons/mstile-144x144.png
  create src/icons/mstile-150x150.png
  create src/icons/mstile-310x150.png
  create src/icons/mstile-310x310.png
  create src/icons/mstile-70x70.png
  create src/icons/safari-pinned-tab.svg
  create src/main-app-shell.ts
  create src/manifest.webapp
  create src/system-import.js
Successfully initialized git.
⠦ Installing packages for tooling via npm
├── es6-shim (ambient)
├── node (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

The package angular2-universal@0.100.5 does not satisfy its siblings' peerDependencies requirements!
Error: The package angular2-universal@0.100.5 does not satisfy its siblings' peerDependencies requirements!
    at /usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/lib/install.js:125:32
    at /usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/lib/install.js:268:7
    at /usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
    at /usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:263:14

```

**Comment by colindevs** [comment]
And all of this is done right after I installed `angular-cli@latest`

**Comment by filipesilva** [comment]
That, unfortunately, is a very real problem and already reported in another issue: https://github.com/angular/angular-cli/issues/958

This is the one @jeffbcross mentioned that someone was working on a fix, but I don't know much more about it at this moment. It should be fixed soon and included in the next beta, since it's prioritized as critical.

I'm going to close this issue for now as the original problem was solved, and the followup problem is a duplicate.

**Comment by colindevs** [comment]
@filipesilva great, thanks a lot for helping out on this one! I'll stay tuned on the other issue, but thanks again for taking the time to help me.

**Comment by filipesilva** [comment]
No bother at all :D
