### ISSUE TITLE
[Feature Request] support dynamically import the bootstrap logic

### ISSUE THREAD

**Issue by scott-ho** [angular/angular-cli#10166]
### Versions
not related

### Repro steps
```ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { KeycloakService } from 'xxx';

import { environment } from './environments/environment';

import './rxjs-operators';

if (environment.production) {
  enableProdMode();
}

const keycloakJsonFile = `${environment.baseHref}assets/${environment.env === 'prod' ? 'keycloak-prod.json' : 'keycloak.json'}`;

KeycloakService.init(keycloakJsonFile, {
  onLoad: 'login-required',
  checkLoginIframe: false
}).then(() => {
  KeycloakService.keycloakAuth.onAuthRefreshError = () => {
    KeycloakService.keycloakAuth.logout();
  }

  return import('./app/app.module').then((mod: { AppModule: any}) => {
    const { AppModule } = mod
    platformBrowserDynamic().bootstrapModule(AppModule);
  })
});

```

### Observed behavior
```
Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
    at Object.resolveEntryModuleFromMain (\test\node_modules\@ngtools\webpack\src\entry_resolver.js:131:11)
    at AotPlugin._setupOptions (\test\node_modules\@ngtools\webpack\src\plugin.js:187:50)
    at new AotPlugin (\test\node_modules\@ngtools\webpack\src\plugin.js:31:14)
    at _createAotPlugin (\test\node_modules\@angular\cli\models\webpack-configs\typescript.js:92:16)
    at Object.getNonAotConfig (\test\node_modules\@angular\cli\models\webpack-configs\typescript.js:100:19)
    at NgCliWebpackConfig.buildConfig (\test\node_modules\@angular\cli\models\webpack-config.js:37:37)
    at Class.run (\test\node_modules\@angular\cli\tasks\serve.js:71:98)
    at check_port_1.checkPort.then.port (\test\node_modules\@angular\cli\commands\serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

see https://github.com/angular/devkit/blob/master/packages/ngtools/webpack/src/entry_resolver.ts#L91

The `_symbolImportLookup` only find `ImportDeclaration` but not `ImportCall`, so it can't be analyzed.

### Desired behavior
Angular-cli support dynamic import of `AppModule`

**Comment by scott-ho** [comment]
related issue #3540 #6930

**Comment by mgechev** [comment]
Let us keep this outside of the CLI for now. You can look into Angular Elements, if you need to bootstrap only part of your page with Angular.
