### ISSUE TITLE
No filename or line number is mentioned with the error message

### ISSUE THREAD

**Issue by balteo** [angular/angular-cli#10174]
### Versions
```
Angular CLI: 6.0.0-rc.0
Node: 8.10.0
OS: darwin x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 6.0.0-rc.0
@angular/cli: 6.0.0-rc.0
@angular/material: 6.0.0-rc.0
@angular-devkit/architect: 0.5.0
@angular-devkit/build-angular: 0.0.9
@angular-devkit/build-optimizer: 0.4.8
@angular-devkit/core: 0.5.0
@angular-devkit/schematics: 0.5.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-beta.8
@schematics/angular: 0.5.0
@schematics/update: 0.5.0
typescript: 2.7.2
webpack: 4.1.0
```

### Repro steps

I ran `ng build` on an application I am porting to ng 6

### Observed behavior

I get the following output with no reference whatsoever to file name or line number:

```
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/util/subscribeTo.js:42:15)
    at Object.subscribeToResult (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/util/subscribeToResult.js:7:26)
    at MergeMapSubscriber._innerSub (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/operators/map.js:92:26)
    at MapSubscriber.Subscriber.next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/operators/map.js:92:26)
    at MapSubscriber.Subscriber.next (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/julien/Documents/projects/pro-stack/app/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
```

### Desired behavior

I was expecting the file name and line number to be printed together with the error.

**Comment by balteo** [comment]
This issue seems to be resolved by using node 9. See below:

```
Angular CLI: 6.0.0-rc.0
Node: 9.10.1
OS: darwin x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-rc.0
@angular-devkit/architect: 0.0.10
@angular-devkit/build-angular: 0.0.10
@angular-devkit/build-optimizer: 0.4.9
@angular-devkit/core: 0.4.9
@angular-devkit/schematics: 0.5.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-beta.9
@schematics/angular: 0.5.0
@schematics/update: 0.5.0
typescript: 2.7.2
webpack: 4.1.0
```
