### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:

### ISSUE THREAD

**Issue by skurt23** [angular/angular-cli#1019]
1. OS - Mac OS El Capitan

2. Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.2-mobile.4
node: 4.4.4
os: darwin x64

3. Nothing, ng server started but when I added a Service, it crash.

4. Log:
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/tmp/broccoli_type_script_compiler-input_base_path-WzQDwKgP.tmp/0/src/app/services/category.service.ts (19, 47): Property 'toPromise' does not exist on type 'Observable<Response>'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:115:19)
    at BroccoliTypeScriptCompiler.build (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/lib/broccoli/angular2-app.js:321:18)
    at Angular2App._buildTree (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/lib/broccoli/angular2-app.js:116:23)
    at new Angular2App (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/Pepe/Documents/Programación/AngularJS/ModuloBootcamp/PracticaFinal/Whatapop/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

5- I have tried with 'sudo ng server' and 'ng init' but i have the same issue

**Comment by filipesilva** [comment]
This seems to be just a typescript error, instead of a CLI error:

> (19, 47): Property 'toPromise' does not exist on type 'Observable'.

You might need to import that operator as described in https://angular.io/docs/ts/latest/guide/server-communication.html#!#rxjs-library.
