### ISSUE TITLE
ng serve -o error

### ISSUE THREAD

**Issue by darknesshotdog** [angular/angular-cli#10196]
### Versions
```
Angular CLI: 6.0.0-rc.1
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0-rc.1
```

### Repro steps

* Start a project with ```ng serve -o``` in ```Angular CLI: 6.0.0-rc.1```

### Observed behavior
```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties (o).
Error: Schema validation failed with the following errors:
  Data path "" should NOT have additional properties (o).
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (C:\ltiisWeb\client-angular6\node_modules\@angular-devkit\core\src\workspace\workspace.js:145:42)
    at MergeMapSubscriber._tryNext (C:\ltiisWeb\client-angular6\node_modules\rxjs\internal\operators\mergeMap.js:122:27)
    at MergeMapSubscriber._next (C:\ltiisWeb\client-angular6\node_modules\rxjs\internal\operators\mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (C:\ltiisWeb\client-angular6\node_modules\rxjs\internal\Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (C:\ltiisWeb\client-angular6\node_modules\rxjs\internal\operators\mergeMap.js:141:26)
    at InnerSubscriber._next (C:\ltiisWeb\client-angular6\node_modules\rxjs\internal\InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (C:\ltiisWeb\client-angular6\node_modules\rxjs\internal\Subscriber.js:103:18)
    at MapSubscriber._next (C:\ltiisWeb\client-angular6\node_modules\rxjs\internal\operators\map.js:92:26)
    at MapSubscriber.Subscriber.next (C:\ltiisWeb\client-angular6\node_modules\rxjs\internal\Subscriber.js:103:18)
    at SwitchMapSubscriber.notifyNext (C:\ltiisWeb\client-angular6\node_modules\rxjs\internal\operators\switchMap.js:122:26)
```

### Desired behavior
It should build and start

### Other details
* Recently updated from ```v1.7.3```
* ```ng serve --open``` works fine

**Comment by DasTormati** [comment]
;;;;;;;;;;;;;;;;;
