### ISSUE TITLE
ng build --prod  (Cannot read property 'moduleType' of undefined)

### ISSUE THREAD

**Issue by RyanDrx** [angular/angular-cli#10205]
### Versions
```
Angular CLI: 1.7.4
Node: 8.10.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.4
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

### Repro steps
ng build --prod


### Observed behavior
main.11e65f6692fbcf5b0320.bundle.js:1 Uncaught TypeError: Cannot read property 'moduleType' of undefined
    at main.11e65f6692fbcf5b0320.bundle.js:1
    at t.invoke (polyfills.85eccb247fdae4568b8c.bundle.js:1)
    at Object.onInvoke (main.11e65f6692fbcf5b0320.bundle.js:1)
    at t.invoke (polyfills.85eccb247fdae4568b8c.bundle.js:1)
    at e.run (polyfills.85eccb247fdae4568b8c.bundle.js:1)
    at t.run (main.11e65f6692fbcf5b0320.bundle.js:1)
    at t.bootstrapModuleFactory (main.11e65f6692fbcf5b0320.bundle.js:1)
    at Object.x35b (main.11e65f6692fbcf5b0320.bundle.js:1)
    at t (inline.318b50c57b4eba3d437b.bundle.js:1)
    at Object.0 (main.11e65f6692fbcf5b0320.bundle.js:1)
    at t (inline.318b50c57b4eba3d437b.bundle.js:1)
    at window.webpackJsonp (inline.318b50c57b4eba3d437b.bundle.js:1)
    at main.11e65f6692fbcf5b0320.bundle.js:1

### Desired behavior
The application runs

**Comment by RyanDrx** [comment]
ng build without the --prod flag result in a warking application when hosted in an S3 bucket as a static website. 

The same result occurs when running 
ng build --prod --aot
ng build --aot

**Comment by robertbaker** [comment]
Update to latest stable cli (remember to update global + project).

Generate a new project with ng new. Use a diff tool to compare the generated project with your own. There's something off in your project, likely from a incomplete upgrade.

**Comment by RyanDrx** [comment]
Turns out i had a duplication of 
platformBrowserDynamic().bootstrapModule(AppModule);

**Comment by MrPardeep** [comment]
@RyanDrx Can you please post your `server.ts` file here, I am facing the same issue unable to sort out the same problem.

error showing is :

> Cannot read property 'moduleType' of undefined

and I assume there is error in while importing `AppServerModuleNgFactory`, I am importing like this now

> const {  AppServerModuleNgFactory } = (module as any).exports;
instead of
> import { AppServerModuleNgFactory } from '../dist/ngfactory/src/app/app.server.module.ngfactory'

**Comment by RyanDrx** [comment]
I assume you are working on rendering from the server?

Your import should be 

`import { AppServerModuleNgFactory } from './src/app.server.module.ngfactory'`

Here is the full server.ts
`
import 'zone.js/dist/zone-node';
import { renderModuleFactory } from '@angular/platform-server'
import { enableProdMode } from '@angular/core'
import { AppServerModuleNgFactory } from './src/app.server.module.ngfactory'

enableProdMode();
const args = process.argv.slice(2);
if (args.length != 1) {
    process.stdout.write("Usage: node dist/main.js <url>");
    process.exit();
}
renderModuleFactory(AppServerModuleNgFactory, {
    document: `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>NgUniversalDemystified</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root>Loading...</app-root>
</body>
</html>`,
    url: args[0]
}).then(string => process.stdout.write(string));
`

**Comment by RicardoVaranda** [comment]
Hi guys, I'm facing a similar issue just wondering if you could give me a hand, I'm following the example on Universal-starter

In the last step when running the following file:
https://github.com/angular/universal-starter/blob/master/prerender.ts

I get this issue:
```
Unhandled Promise rejection: Cannot read property 'moduleType' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'moduleType' of undefined
    at /Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:5996:135
    at ZoneDelegate.invoke (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:157532:26)
    at Object.onInvoke (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:5255:33)
    at ZoneDelegate.invoke (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:157531:32)
    at Zone.run (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:157282:43)
    at NgZone.run (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:5072:69)
    at PlatformRef.bootstrapModuleFactory (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:5995:23)
    at Object.renderModuleFactory (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:119067:39)
    at /Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:238678:82
    at ZoneDelegate.invoke (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:157532:26) TypeError: Cannot read property 'moduleType' of undefined
    at /Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:5996:135
    at ZoneDelegate.invoke (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:157532:26)
    at Object.onInvoke (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:5255:33)
    at ZoneDelegate.invoke (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:157531:32)
    at Zone.run (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:157282:43)
    at NgZone.run (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:5072:69)
    at PlatformRef.bootstrapModuleFactory (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:5995:23)
    at Object.renderModuleFactory (/Users/ricardo_varanda/Projects/product-cloud/dist/apps/trial-cloud/prerender.js:119067:39)
```

This is what my prerender.ts looks like:
```
// Load zone.js for the server.
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import {readFileSync, writeFileSync, existsSync, mkdirSync} from 'fs';
import {join} from 'path';

import {enableProdMode} from '@angular/core';
// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();

// Import module map for lazy loading
import {provideModuleMap} from '@nguniversal/module-map-ngfactory-loader';
import {renderModuleFactory} from '@angular/platform-server';
import {ROUTES} from './tc-static.paths';

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const {AppServerModuleNgFactory, LAZY_MODULE_MAP} = require('./dist/apps/trial-cloud/server/main.bundle');

const BROWSER_FOLDER = join(process.cwd(), 'browser');

// Load the index.html file containing referances to your application bundle.
const index = readFileSync(join('browser', 'index.html'), 'utf8');

let previousRender = Promise.resolve();

// Iterate each route path
ROUTES.forEach(route => {
  const fullPath = join(BROWSER_FOLDER, route);

  // Make sure the directory structure is there
  if(!existsSync(fullPath)){
    mkdirSync(fullPath);
  }

  // Writes rendered HTML to index.html, replacing the file if it already exists.
  previousRender = previousRender.then(_ => renderModuleFactory(AppServerModuleNgFactory, {
    document: index,
    url: route,
    extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP)
    ]
  })).then(html => writeFileSync(join(fullPath, 'index.html'), html));
});

```

Also here is server.ts:
```
// These are important and needed before anything else
import 'zone.js/dist/zone-node';
import 'reflect-metadata';

import { renderModuleFactory } from '@angular/platform-server';
import { enableProdMode } from '@angular/core';
import { ngExpressEngine } from '@nguniversal/express-engine';

import * as express from 'express';
import { join } from 'path';
import { readFileSync } from 'fs';

// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();

// Express server
const app = express();

const PORT = process.env.PORT || 80;
const DIST_FOLDER = join(process.cwd(), 'dist/apps/trial-cloud');

// Our index.html we'll use as our template
const template = readFileSync(join(DIST_FOLDER, 'browser', 'index.html')).toString();

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist/apps/trial-cloud/server/main.bundle');

const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');

app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
}));

app.set('view engine', 'html');
app.set('views', join(DIST_FOLDER, 'browser'));

// Server static files from /browser
app.get('*.*', express.static(join(DIST_FOLDER, 'browser')));

// All regular routes use the Universal engine
app.get('*', (req, res) => {
  res.sendFile(join(DIST_FOLDER, 'browser', 'index.html'));
});

// Start up the Node server
app.listen(PORT, () => {
  console.log(`Node server listening on http://localhost:${PORT}`);
});

```

**Comment by FelipeLujan** [comment]
i'm having the same issue as @RicardoVaranda my server.ts and prerender.ts are pretty much the same (except for routes), not sure how to implement @MrPardeep 's solution.
My project compiles successfully, both server and --prod aot versions.
server.js and prerender.js seem to be generated successfully too but when i try to generate prerender im getting.

```
Unhandled Promise rejection: Cannot read property 'moduleType' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'moduleType' of undefined
    at /home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:7041:135
    at ZoneDelegate.invoke (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:92259:26)
    at Object.onInvoke (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:6300:33)
    at ZoneDelegate.invoke (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:92258:32)
    at Zone.run (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:92009:43)
    at NgZone.run (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:6117:69)
    at PlatformRef.bootstrapModuleFactory (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:7040:23)
    at Object.renderModuleFactory (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:98219:39)
    at /home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:114808:82
    at ZoneDelegate.invoke (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:92259:26) TypeError: Cannot read property 'moduleType' of undefined
    at /home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:7041:135
    at ZoneDelegate.invoke (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:92259:26)
    at Object.onInvoke (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:6300:33)
    at ZoneDelegate.invoke (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:92258:32)
    at Zone.run (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:92009:43)
    at NgZone.run (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:6117:69)
    at PlatformRef.bootstrapModuleFactory (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:7040:23)
    at Object.renderModuleFactory (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:98219:39)
    at /home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:114808:82
    at ZoneDelegate.invoke (/home/pipe/Documents/coding/Angular/RemodelacionesLujan/dist/prerender.js:92259:26)
```
this is my package.json
```

{
  "name": "bs4starter",
  "version": "0.0.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/angular/universal-starter.git"
  },

  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build:prerender": "npm run build:client-and-server-bundles && npm run webpack:server && npm run generate:prerender",
    "build:client-and-server-bundles": "ng build --prod --aot && ng build --prod --aot  --app 1 --output-hashing=false",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "generate:prerender": "cd dist && node prerender",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:prerender": "cd dist/browser && http-server",
    "serve:ssr": "node dist/server",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ng-bootstrap/ng-bootstrap": "^1.1.2",
    "@nguniversal/common": "^5.0.0-beta.8",
    "@nguniversal/express-engine": "^5.0.0-beta.8",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.8",
    "angular-font-awesome": "^3.1.2",
    "angularfire2": "^5.0.0-rc.6.0",
    "bootstrap": "4.1.0",
    "core-js": "^2.4.1",
    "express": "^4.16.3",
    "firebase": "4.12.1",
    "font-awesome": "^4.7.0",
    "http-server": "^0.11.1",
    "node-sass": "4.8.3",
    "rxjs": "^5.5.6",
    "ts-loader": "3.5.0",
    "webpack": "^3.11.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@angular/platform-server": "^5.2.10",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3",
    "webpack-cli": "^2.0.15"
  }
}

```

    
```
Angular CLI: 1.7.4
Node: 9.11.1
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular/platform-server: 5.2.10
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack-cli: 2.0.15
webpack: 3.11.0
```

**Comment by PremapriyaT** [comment]
I'm having the same issue... when I take build without --prod its working fine.
I tried some solutions as mentioned above but I can't fix.....

Here is an issue,

Uncaught TypeError: Cannot read property 'moduleType' of undefined
    at main.fddf181efaf4acf0e6be.js:1
    at e.invoke (polyfills.9d3a8743be9f041e6ba8.js:1)
    at Object.onInvoke (main.fddf181efaf4acf0e6be.js:1)
    at e.invoke (polyfills.9d3a8743be9f041e6ba8.js:1)
    at t.run (polyfills.9d3a8743be9f041e6ba8.js:1)
    at t.run (main.fddf181efaf4acf0e6be.js:1)
    at t.bootstrapModuleFactory (main.fddf181efaf4acf0e6be.js:1)
    at Module.zUnb (main.fddf181efaf4acf0e6be.js:1)
    at f (runtime.ec2944dd8b20ec099bf3.js:1)
    at Object.0 (main.fddf181efaf4acf0e6be.js:1)

**Comment by prakasa-tkpd** [comment]
Have same error using angular 5.2.11:

```
Cannot read property 'moduleType' of undefined
TypeError: Cannot read property 'moduleType' of undefined
    at http://localhost/build/vendor.js:1:38889
    at t.invoke (http://localhost/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost/build/vendor.js:1:34757)
    at t.invoke (http://localhost/build/polyfills.js:3:14916)
    at r.run (http://localhost/build/polyfills.js:3:10143)
    at t.run (http://localhost/build/vendor.js:1:35479)
    at t.bootstrapModuleFactory (http://localhost/build/vendor.js:1:38820)
    at HTMLDocument.<anonymous> (http://localhost/build/main.js:1:371)
```

No duplicate code or server side rendering. Its pure client side apps. But getting error above when build --prod. But running well when build non `--prod`

**Comment by servrox** [comment]
Just to leave the info here! I stumbled upon this error message as I tried to get my nx workspace with a seperated nest app for ssr to work (-> [Demo+Explanation](https://github.com/servrox/nx-ng-nest-universal))

The problem that caused the above error message was that in the _app.module.ts_ of the nest server the path to the bundle was wrong. Corrected path you can see [here](https://github.com/servrox/nx-ng-nest-universal/blob/28b4f23a6a4d717d371e68f252095743370be77b/apps/nest-test-app/src/app/app.module.ts#L15). Maybe that helps someone, it drove me crazy...

**Comment by TaiJinYuan** [comment]
> Turns out I had a duplication of the following in my app.module
> `platformBrowserDynamic().bootstrapModule(AppModule);`
> 
> Thanks.

Thank you, @RyanDrx.
It solved the problem.
**platformBrowserDynamic** has been duplicated in both files  - _main.ts and app.module.ts_
