### ISSUE TITLE
Angular CLI rc.0:  ng serve -prod error

### ISSUE THREAD

**Issue by yfain** [angular/angular-cli#10233]
Generated a new project with Angular CLI 6.0.0-rc.0 (I use MAC OS). Running `ng serve` works fine but running `ng serve -prod` returns the following error:

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties (p).
Error: Schema validation failed with the following errors:
  Data path "" should NOT have additional properties (p).
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/yfain11/hello6rc0/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/workspace.js:145:42)
    at MergeMapSubscriber._tryNext (/Users/yfain11/hello6rc0/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/Users/yfain11/hello6rc0/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/yfain11/hello6rc0/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/yfain11/hello6rc0/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/Users/yfain11/hello6rc0/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/Users/yfain11/hello6rc0/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/Users/yfain11/hello6rc0/node_modules/rxjs/internal/operators/map.js:92:26)
    at MapSubscriber.Subscriber.next (/Users/yfain11/hello6rc0/node_modules/rxjs/internal/Subscriber.js:103:18)
    at SwitchMapSubscriber.notifyNext (/Users/yfain11/hello6rc0/node_modules/rxjs/internal/operators/switchMap.js:122:26)

**Comment by julianobrasil** [comment]
Take a look at #10231

**Comment by yfain** [comment]
I didn't migrate any projects but generated a new one.

**Comment by julianobrasil** [comment]
Oh, sorry. Another thing I've noticed in rc.* versions is that `-prod` doesn't work anymore when you're building. You must use `--prod`. It's likely the same with `ng serve`.

**Comment by tomastrajan** [comment]
Have the same problem on newly generated project.

**Comment by julianobrasil** [comment]
I can confirm it works if you use `--prod` (double dashes) instead of `-prod`

**Comment by yfain** [comment]
It worked with double dashes `--prod` but it seems that a single dash generates the stack trace in other cases as well, e.g. `ng serve --prod -port 4300`.  

If single dashes are not allowed anymore (why?), they shouldn't generate a stack trace but provide a more meaningful message.

**Comment by filipesilva** [comment]
We removed single dash support in 6.0 to make way for single dash to be used with multiple flags in the future (`-abcd` would be the same as `-a -b -c -d`). 

I agree using single dashes should error out with a helpful description instead of the current behaviour.

**Comment by clydin** [comment]
Error messages resolved via https://github.com/angular/angular-cli/pull/10245
