### ISSUE TITLE
Schema validation error when using ng serve after udating to 6.0.0-rc.2

### ISSUE THREAD

**Issue by benjamincombes** [angular/angular-cli#10243]
### Versions
```
Angular CLI: 6.0.0-rc.2
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0-rc.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 6.0.0-rc.2
@angular/material: 5.2.4
@angular-devkit/architect: 0.5.4
@angular-devkit/build-angular: 0.5.4
@angular-devkit/build-optimizer: 0.5.4
@angular-devkit/core: 0.5.4
@angular-devkit/schematics: 0.5.4
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.2.4
@schematics/angular: 0.5.4
@schematics/update: 0.5.4
typescript: 2.7.2
webpack: 4.5.0
```

### Repro steps
* Update to latest angular-cli version
* Try running app as usually, with ```ng serve  -e=development --app dashboard```

### Observed behavior

The following error is displayed:
```
$ ng serve  -e=development --app dashboard
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties (e).
Error: Schema validation failed with the following errors:
  Data path "" should NOT have additional properties (e).
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/@angular-devkit/core/src/workspace/workspace.js:145:42)
    at MergeMapSubscriber._tryNext (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/rxjs/internal/operators/map.js:92:26)
    at MapSubscriber.Subscriber.next (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/rxjs/internal/Subscriber.js:103:18)
    at SwitchMapSubscriber.notifyNext (/Users/benjamincombes/Documents/Projects/morpheus-dashboard-web/node_modules/rxjs/internal/operators/switchMap.js:122:26)
```

### Desired behavior
No error should be displayed; or details should be given about what causes the error, so that it is possible to understand what is wrong, and how to fix.

**Comment by filipesilva** [comment]
Part of this issue is https://github.com/angular/angular-cli/issues/10233 (single dashes are not supported anymore).

The other part is that `--app` is not supported anymore. After updating, you can do `ng build dashboard` instead to build that app.

`--environments` are no longer there either and I understand that's not very straightforward to figure out because we haven't yet put out documentation on what changed in the CLI. It is now `fileReplacements` instead, and you should have it in your `angular.json` file.

**Comment by benjamincombes** [comment]
Thanks a lot @filipesilva for answering so fast! Do you have any idea when documentation should be released?
I know it is really a lot of work to make a release, but if I can give a small feedback, it would be really great to have documentation released with first RC. I had the same kind of problems with last few major angular update, where I would have loved to try helping by reporting issues before final release, but couldn't do it as no documentation was available until final release.
Thanks for the great job, can't wait to try Angular & CLI 6!
