### ISSUE TITLE
angular-cli project in github deployment error

### ISSUE THREAD

**Issue by subhashekkaluru** [angular/angular-cli#10242]
E:\2018 handling works\Angular 5\PR01>ngh
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at promptCreds (C:\Users\subhash\AppData\Roaming\npm\node_modules\ngh\bin\ng
h:11:24)
    at Object.<anonymous> (C:\Users\subhash\AppData\Roaming\npm\node_modules\ngh
\bin\ngh:110:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

**Comment by filipesilva** [comment]
I think you're having some weird errors and can't debug it, and so, understandably, you're frustrated. But this is a tracker for bugs and feature requests. If we can we also try to help with support requests. We're very lucky to have awesome community members that also spend time trying to help people here in the issue tracker.

But we can't really help much at all if you don't fill in the issue template. I read your issue and have no idea what's going wrong and how to help you. And when other users search the issue tracker and see your issue, it also doesn't help them.

So I think the best thing to do is to close this issue, and ask you to open a new one. In that new one please fill in the issue template and give us an idea of what's happening and how to reproduce it. That way we'll have a chance to help you.
