### ISSUE TITLE
6.0.0-rc.3 'ng upgrade' does not work due to 'Error: connect ECONNREFUSED 151.101.0.162:80'

### ISSUE THREAD

**Issue by kuncevic** [angular/angular-cli#10293]
### Versions
Angular CLI: 6.0.0-rc.3
Node: 8.9.1
OS: win32 x64
Angular: 6.0.0-rc.3
... animations, cli, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cdk: 6.0.0-rc.2
@angular/compiler-cli: 5.2.9
@angular/flex-layout: 5.0.0-beta.13
@angular/language-service: 5.2.9
@angular/material: 6.0.0-rc.2
@angular-devkit/architect: 0.5.5
@angular-devkit/core: 0.5.5
@angular-devkit/schematics: 0.5.5
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.5.5
@schematics/update: 0.5.5
typescript: 2.6.2
webpack: error

### Repro steps
Upgrade the deps in the current project
run `npm run ng -- upgrade` -  this command need to be run to generate `angular.json` as per release notes https://github.com/angular/angular-cli/releases/tag/v6.0.0-rc.2

### Observed behavior
Giving an error:
```
> ng "update"

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 151.101.0.162:80
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```
### Desired behavior
Should produce the `angular.json`  file

**Comment by hansl** [comment]
That other issue has been closed because this is fixed by adding a `--registry` flag to `ng update`.

This issue is about using a corporate proxy which is not supported. It should be.

**Comment by travis1234** [comment]
I'm having the same issue and also behind a corporate proxy.

Doesn't seem to be using npm to make the connection as I have a proxy setting in my .npmrc file. 

***
registry=http://registry.npmjs.org
proxy=http://127.0.0.1:8888
https-proxy=http://127.0.0.1:8888
http-proxy=http://127.0.0.1:8888
strict-ssl=false
***

**Comment by clydin** [comment]
The current version only supports custom registries.  Proxy support is in progress and should available in the next RC.

**Comment by mail2sandy42** [comment]
+1
We too have a corporate proxy. And the update command fails.

**Comment by kuncevic** [comment]
If I update the to cli 6 and then running `ng update` I am not getting the `anguler.json` 
Thoughts?

**Comment by samithaf** [comment]
Stuck with the same issue and can't update to Angular 6 :(

**Comment by geisslercom** [comment]
+1

**Comment by juri33** [comment]
+1 behind corporate proxy

**Comment by eliellis** [comment]
A short-term solution: install `proxychains`, configure your proxy, and run whatever command you were attempting through that tool. If you're getting DNS errors from `proxychains`, make sure the `proxy_dns` option is commented out in the `/etc/proxychains.conf` file.

**Comment by adityashukla74** [comment]
+1

**Comment by haddadr** [comment]
You can use
 `ng update @angular/cli --registry=http://registry.npmjs.org` 
It will bypass proxy 

Also make sur in your .npmrc to set the proxy settings
