### ISSUE TITLE
Webpack: Failed to compile and font-awesome

### ISSUE THREAD

**Issue by aramiscubillo** [angular/angular-cli#10316]
I recently installed font-awesome on my project and everything was working fine. 
However today I needed to add pagination functionality so I installed [ngx-pagination](https://github.com/michaelbromley/ngx-pagination)

After that, when I run **npm start** I get the following error:

```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_mod
ules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/fon
t-awesome/css/font-awesome.css
Module build failed: Error: Cannot find module 'cuint'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Aramis\Documents\1o1WVC\frontend\src\main\fr
ontend\node_modules\xxhashjs\lib\xxhash.js:7:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Aramis\Documents\1o1WVC\frontend\src\main\fr
ontend\node_modules\xxhashjs\lib\index.js:2:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
 @ ./node_modules/font-awesome/css/font-awesome.css 4:14-124
 @ multi ./src/styles.css ./src/lg-styles.css ./src/md-styles.css ./src/sm-style
s.css ./src/xs-styles.css ./node_modules/font-awesome/css/font-awesome.css

webpack: Failed to compile.
```

If I go to  **.angular-cli.json** and delete  

> **../node_modules/font-awesome/css/font-awesome.css** 

 from the styles array and then try **npm start** everything works:
```
"styles": [
  "styles.css"
]
```

### Versions
```
<!--
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / ? \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.4
Node: 6.11.0
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0

node --version
v6.11.0

npm --version
5.0.3

Windows 8.1
```

### Repro steps

* Step 1
Install [font-awesome](https://github.com/angular/angular-cli/wiki/stories-include-font-awesome)
* Step 2
Install [ngx-pagination](https://github.com/michaelbromley/ngx-pagination)
* Step 3
npm start

### Desired behavior
```

Be able to build the app with **npm start** having font-awesome and ngx-pagination installed
What am I missing here?
```

Thank you!

**Comment by aramiscubillo** [comment]
I fixed the problem. I think is a bug related to npm install, for some reason it deletes other packages on install.
Fix it by updating node to latest version:  8.11.1 and updating npm to 5.6.0
