### ISSUE TITLE
Angular CLI 6.0.0-rc.4 can't run `ng build` on Windows

### ISSUE THREAD

**Issue by doggy8088** [angular/angular-cli#10328]
### Versions
```
Angular CLI: 6.0.0-rc.4
Node: 9.11.1
OS: win32 x64
Angular: 6.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.6
@angular-devkit/build-angular     0.5.6
@angular-devkit/build-optimizer   0.5.6
@angular-devkit/core              0.5.6
@angular-devkit/schematics        0.5.6
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.4
@schematics/angular               0.5.6
@schematics/update                0.5.6
rxjs                              6.0.0-uber-rc.5
typescript                        2.7.2
webpack                           4.5.0
```

### Repro steps
* `npx @angular/cli@next new ng6app`
* `cd ng6app`
* `ng build`

### Observed behavior

**When I run `ng build` in Command Prompt, it failed.**

```
Path "g:/Projects/ng6app" must be absolute.
Error: Path "g:/Projects/ng6app" must be absolute.
    at Object.relative (g:\Projects\ng6app\node_modules\@angular-devkit\core\src\virtual-fs\path.js:112:15)
    at isInside (g:\Projects\ng6app\node_modules\@angular\cli\utilities\config.js:115:42)
    at workspace.listProjectNames.map.sort (g:\Projects\ng6app\node_modules\@angular\cli\utilities\config.js:123:25)
    at Array.sort (native)
    at getProjectByCwd (g:\Projects\ng6app\node_modules\@angular\cli\utilities\config.js:123:10)
    at Object.isWarningEnabled (g:\Projects\ng6app\node_modules\@angular\cli\utilities\config.js:230:25)
    at Function.assertTypescriptVersion (g:\Projects\ng6app\node_modules\@angular\cli\upgrade\version.js:111:23)
    at BuildCommand.validate (g:\Projects\ng6app\node_modules\@angular\cli\commands\build.js:29:27)
    at g:\Projects\ng6app\node_modules\@angular\cli\models\command-runner.js:274:39
    at Generator.next (<anonymous>)
```
![image](https://user-images.githubusercontent.com/88981/38749330-cef5f7f0-3f83-11e8-9951-5bbfd0c8af3e.png)

**When I open this folder and open Terminal to run the same command, it works! **

![image](https://user-images.githubusercontent.com/88981/38749377-fbcf1d2e-3f83-11e8-8868-5c92bb435adb.png)

### Desired behavior

It suppose can run these command both in Command Prompt and in Terminal of VSCode.

### Mention any other details that might be useful (optional)

I tried to output the problem path.  In Command Prompt, the path start with 'G:/'.  In Terminal window of the VSCode, it do start with '/'.  (Why?)

![image](https://user-images.githubusercontent.com/88981/38749441-2fa3d11c-3f84-11e8-9e20-c30e218fa6dd.png)

**Comment by doggy8088** [comment]
@hansl bug fixed.  please check for https://github.com/angular/devkit/pull/697
