### ISSUE TITLE
ETIMEDOUT during ng update

### ISSUE THREAD

**Issue by Aw3same** [angular/angular-cli#10355]
### Versions
```
Angular CLI: 6.0.0-rc.4
Node: 9.11.1
OS: win32 x64
Angular: 6.0.0-rc.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.5.6
@angular-devkit/core         0.5.6
@angular-devkit/schematics   0.5.6
@angular/cli                 6.0.0-rc.4
@ngtools/json-schema         1.1.0
@schematics/angular          0.5.6
@schematics/update           0.5.6
rxjs                         5.5.10
typescript                   2.7.2
```

### Repro steps
* ```npm i @angular/cli@next```
* ```ng s```
```
An old CLI configuration has been detected, which needs to be updated to the latest version.

Please run the following command to update this workspace:
  ng update @angular/cli --migrate-only --from=1
```
* ```ng update @angular/cli --migrate-only --from='1'```

### Observed behaviour
```
events.js:165
      throw er; // Unhandled 'error' event
      ^
Error: connect ETIMEDOUT 151.101.132.162:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:395:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

### Desired behaviour

I look for or solve the ng update command or know that I have to change for the project to work

### Mention any other details that might be useful (optional)
Doing ```ping 151.101.132.162:80``` I don't send or receive any package. Ping cannot found the host.

**Comment by m-farahmand** [comment]
I got this error with this command:
ng update @angular/cli --migrate-only --from=5.0.1

**Comment by hansl** [comment]
You are using a custom NPM registry or are behind a corporate proxy. We are fixing this (in the next RC); see https://github.com/angular/angular-cli/issues/10293
