### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by GoNode5** [angular/angular-cli#10389]
Trying to install Angular Material according to ng-conf demo Angular CDK and Material in 2018 - Jeremy Elbourn

### Versions
```
Windows 10 
Angular CLI: 6.0.0-rc.5
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.7
@angular-devkit/build-angular     0.5.7
@angular-devkit/build-optimizer   0.5.7
@angular-devkit/core              0.5.7
@angular-devkit/schematics        0.5.7
@angular/cdk                      5.2.5
@angular/material                 5.2.5
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.5
@schematics/angular               0.5.7
@schematics/update                0.5.7
rxjs                              6.0.0-uncanny-rc.7
typescript                        2.7.2
webpack                           4.5.0
```

### Repro steps
ng add @angular/material

error:

Installing packages for tooling via npm.
Cannot read property 'startsWith' of undefined
TypeError: Cannot read property 'startsWith' of undefined
    at NodeModulesEngineHost._resolvePath (C:\angular-dev\material-test\mat-test1\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:31:18)

trying manual after installing npm install --save @angular/material @angular/cdk

ng generate @angular/material:materialNav --name=main-nav

Cannot read property 'startsWith' of undefined
TypeError: Cannot read property 'startsWith' of undefined
    at NodeModulesEngineHost._resolvePath (C:\angular-dev\material-test\mat-test1\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:31:18)
    at NodeModulesEngineHost._resolveCollectionPath (C:\angular-dev\material-test\mat-test1\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:69:35)
    at NodeModulesEngineHost.createCollectionDescription (C:\angular-dev\material-test\mat-test1\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:106:27)
    at SchematicEngine._createCollectionDescription (C:\angular-dev\material-test\mat-test1\node_modules\@angular-devkit\schematics\src\engine\engine.js:78:40)

**Comment by GoNode5** [comment]
Installed npm install --save @angular/cdk@6.0.0-rc.12. Now ng generate @angular/material:materialNav --name=main-nav works...
