### ISSUE TITLE
6rc5 smarter console output

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular-cli#10387]
### Versions
```
Angular CLI: 6.0.0-rc.5
```

### Repro steps
`ng g components hello`

### Observed behavior
```
Schematic "components" not found in collection "@schematics/angular".
Error: Schematic "components" not found in collection "@schematics/angular".
    at SchematicEngine.createSchematic (C:\...\node_modules\@angular-devkit\schematics\src\engine\engine.js:155:23)
    at CollectionImpl.createSchematic (C:\...\node_modules\@angular-devkit\schematics\src\engine\collection.js:12:29)
    at Object.getSchematic (C:\...\node_modules\@angular\cli\utilities\schematics.js:36:23)
    at GenerateCommand.getOptions (C:\...\node_modules\@angular\cli\models\schematic-command.js:188:40)
    at GenerateCommand.<anonymous> (C:\...\node_modules\@angular\cli\commands\generate.js:40:53)
    at Generator.next (<anonymous>)
    at C:\...\node_modules\@angular\cli\commands\generate.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\...\node_modules\@angular\cli\commands\generate.js:3:12)
    at GenerateCommand.initialize (C:\...\node_modules\@angular\cli\commands\generate.js:32:16)
```

### Desired behavior

> Angular CLI: 'components' is not in our @schematics/angular collection . See 'ng g --help'.
> The most similar command is 'component'
> Did you mean : ng g component hello ?

### Mention any other details that might be useful (optional)
This could maybe be poor example, but i hope you get essential ^^
In other terms we shouldn't see any code/path of angular cli dist folder in output

**Comment by alan-agius4** [comment]
This issue is solved as we no longer print stacktraces and create error logs files instead.
