### ISSUE TITLE
[FEATURE-REQUEST-NG-UPDATE] add possibility change npm registry behind a proxy

### ISSUE THREAD

**Issue by choucry13** [angular/angular-cli#10433]
### Versions
```
Angular CLI: 6.0.0-rc.5
Node: 9.6.1
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.7
@angular-devkit/build-angular     0.5.0
@angular-devkit/build-optimizer   0.5.0
@angular-devkit/core              0.5.7
@angular-devkit/schematics        0.5.7
@angular/cdk                      5.2.4
@angular/cli                      6.0.0-rc.5
@angular/material                 5.2.4
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.0
@schematics/angular               0.5.7
@schematics/update                0.5.7
rxjs                              5.5.10
typescript                        2.6.2
webpack                           4.1.0

```

### Repro steps
step 1 : `ng update`

step 2: 
```
events.js:112
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 151.101.120.162:80
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1181:14)
```

### Observed behavior
The proxy blocked the request.

### Desired behavior
I would like to add a specific npm registry or use the registry saved in my .npmrc

**Comment by clydin** [comment]
Resolve via angular/devkit#692 and will be in the next release.

**Comment by choucry13** [comment]
thank @clydin
