### ISSUE TITLE
Support ng add with npm tags

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#10468]
### Versions
```
Angular CLI: 6.0.0-rc.6
Node: 9.2.0
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.6
@angular-devkit/build-angular     0.5.6
@angular-devkit/build-optimizer   0.5.6
@angular-devkit/core              0.5.6
@angular-devkit/schematics        0.5.8
@angular/cli                      6.0.0-rc.6
@angular/material                 6.0.0-rc.12
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.4
@schematics/angular               0.5.8
@schematics/update                0.5.8
rxjs                              5.5.10
typescript                        2.5.3
webpack                           4.5.0
```

### Repro steps
ng new my-app
cd my-app
ng add @angular/material@next

### Observed behavior
```
 ng add @angular/material@next
Installing packages for tooling via npm.
npm WARN @angular/material@6.0.0-rc.12 requires a peer of @angular/cdk@6.0.0-rc.12 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@6.0.0-rc.12 requires a peer of @angular/core@>=6.0.0-beta.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@6.0.0-rc.12 requires a peer of @angular/common@>=6.0.0-beta.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @angular/material@6.0.0-rc.12
added 68 packages and removed 1 package in 7.329s
Installed packages for tooling via npm.
Could not find module "@angular/material@next" from "/usr/local/google/home/stephenfluin/workspace/test/my-app".
Error: Could not find module "@angular/material@next" from "/usr/local/google/home/stephenfluin/workspace/test/my-app".
    at Object.resolve (/usr/local/google/home/stephenfluin/workspace/test/my-app/node_modules/@angular-devkit/schematics/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at NodeModulesEngineHost._resolvePackageJson (/usr/local/google/home/stephenfluin/workspace/test/my-app/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:22:21)
    at NodeModulesEngineHost._resolveCollectionPath (/usr/local/google/home/stephenfluin/workspace/test/my-app/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:63:40)
    at NodeModulesEngineHost.createCollectionDescription (/usr/local/google/home/stephenfluin/workspace/test/my-app/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:106:27)
    at SchematicEngine._createCollectionDescription (/usr/local/google/home/stephenfluin/workspace/test/my-app/node_modules/@angular-devkit/schematics/src/engine/engine.js:78:40)
    at SchematicEngine.createCollection (/usr/local/google/home/stephenfluin/workspace/test/my-app/node_modules/@angular-devkit/schematics/src/engine/engine.js:71:43)
    at Object.getCollection (/usr/local/google/home/stephenfluin/workspace/test/my-app/node_modules/@angular/cli/utilities/schematics.js:28:31)
    at AddCommand.getOptions (/usr/local/google/home/stephenfluin/workspace/test/my-app/node_modules/@angular/cli/models/schematic-command.js:187:41)
    at AddCommand.<anonymous> (/usr/local/google/home/stephenfluin/workspace/test/my-app/node_modules/@angular/cli/commands/add.js:29:49)
    at Generator.next (<anonymous>)

```

### Desired behavior
Angular CLI runs the `ng add` schematic on the specific package at the specific tag.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
