### ISSUE TITLE
Angular CLI add service worker error

### ISSUE THREAD

**Issue by kprasad99** [angular/angular-cli#10462]
Trying to add service-worker to angular 6 app. Getting following error.

#### Angular CLI
```sh
$ ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.0-rc.6
Node: 8.11.1
OS: linux x64
Angular: 6.0.0-rc.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.8
@angular-devkit/build-angular     0.5.8
@angular-devkit/build-optimizer   0.5.8
@angular-devkit/core              0.5.8
@angular-devkit/schematics        0.5.8
@angular/cli                      6.0.0-rc.6
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.6
@schematics/angular               0.5.8
@schematics/update                0.5.8
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.6.0

```

### Steps to reproduce error.
* Create new angular project
```sh
$ ng new myweb
```
* Go to directory myweb
```sh
$ cd myweb
```
* Add service worker
```sh
$ ng add service-worker
```
### Observed behavior
```
$ ng add service-worker
Installing packages for tooling via npm.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ service-worker@0.0.0
added 1 package in 20.553s
Installed packages for tooling via npm.
Cannot read property 'startsWith' of undefined
TypeError: Cannot read property 'startsWith' of undefined
    at NodeModulesEngineHost._resolvePath (/home/kprasad/vscworkspace/myweb/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:31:18)
    at NodeModulesEngineHost._resolveCollectionPath (/home/kprasad/vscworkspace/myweb/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:69:35)
    at NodeModulesEngineHost.createCollectionDescription (/home/kprasad/vscworkspace/myweb/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:106:27)
    at SchematicEngine._createCollectionDescription (/home/kprasad/vscworkspace/myweb/node_modules/@angular-devkit/schematics/src/engine/engine.js:78:40)
    at SchematicEngine.createCollection (/home/kprasad/vscworkspace/myweb/node_modules/@angular-devkit/schematics/src/engine/engine.js:71:43)
    at Object.getCollection (/home/kprasad/vscworkspace/myweb/node_modules/@angular/cli/utilities/schematics.js:28:31)
    at AddCommand.getOptions (/home/kprasad/vscworkspace/myweb/node_modules/@angular/cli/models/schematic-command.js:187:41)
    at AddCommand.<anonymous> (/home/kprasad/vscworkspace/myweb/node_modules/@angular/cli/commands/add.js:29:49)
    at Generator.next (<anonymous>)
    at /home/kprasad/vscworkspace/myweb/node_modules/@angular/cli/commands/add.js:7:71
```

**Comment by kprasad99** [comment]
OK, Resolved the issue, I should've used below command.

```sh
 ng generate serviceWorker --project myweb
```
