### ISSUE TITLE
SSR not working with ng

### ISSUE THREAD

**Issue by deebloo** [angular/angular-cli#10635]
### Versions
```
Angular CLI: 6.0.0
Node: 8.11.0
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
* clone repo: https://github.com/deebloo/ng6-ssr-error
* run `./build.sh`
* run server: `node dist/server`
* open app: localhost:4000

### Observed behavior

A 500 errors occurs

```
TypeError: StaticInjectorError[InjectionToken Application Initializer -> InjectionToken DocumentToken]:
  StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]:
    Right-hand side of 'instanceof' is not an object
    at bt (/Users/dannyblue/Documents/projects/foo/dist/server.js:1182:87380)
    at gt (/Users/dannyblue/Documents/projects/foo/dist/server.js:1182:87255)
    at ir (/Users/dannyblue/Documents/projects/foo/dist/server.js:1182:110026)
```

### Desired behavior
App is served correctly

### Mention any other details that might be useful (optional)
This works fine with Angular 6 and Angular CLI 1.7 but fails with Angular 6 and Angular CLI 6.

**Comment by deebloo** [comment]
I saw a couple of other issues but they seem tied to 1.7 where 1.7 was working fine for me. https://github.com/angular/angular-cli/issues/8616

**Comment by deebloo** [comment]
that is what I figured. just wanted to make sure there was a clear easy repro. 1.7 still works fine but bundles will be a bit bigger with rxjs6 and no webpack 4

**Comment by naveedahmed1** [comment]
@deebloo is it also about

`--bundle-dependencies=all`

**Comment by deebloo** [comment]
cool deal thanks @filipesilva

**Comment by paulogr** [comment]
I did solve this issue changing my `webpack.server.config.js` mode to `development` instead of `production`


```
Angular CLI: 6.0.0
Node: 8.9.4
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.7.0
```

**Comment by lukaszzieba** [comment]
For me works just copy webpack.server.config.js from https://angular.io/guide/universal

**Comment by johnzondr** [comment]
Hey guys,

Similar to what @paulogr said, this error occurred for me when webpack minimizes the file (production mode). By turning minimization off, the 500 error no longer occurs.

My webpack config:
https://gist.github.com/johnzondr/3d4a361ffcfe89f7ee5199dcc13bf246

**Comment by glemiere** [comment]
Changing the `mode` to `development` is not the correct way to work around this, as it will force your `NODE_ENV` to be set to `development` as well, which is not a behavior anybody would like to have in production.

Instead, simply remove the `mode` option.

**Comment by HeMinzhang** [comment]
I copy webpack.server.config.js from https://angular.io/guide/universal,Still have problems.
But I copy webpack.server.config.js from https://snipcart.com/blog/angular-seo-universal-server-side-rendering,fix this problems.
