### ISSUE TITLE
After Upgrade to V6, getting 'postCSS' and 'sassLoader' undefined error.

### ISSUE THREAD

**Issue by sureshdotariya** [angular/angular-cli#10679]
Tried Upgrading our application from Angular V5.2.10 to V6. Followed the steps mentioned in upgrade.angular.io

1) **npm install @angular/cli** - Success
2) **ng update @angular/cli** - Success
3) **ng update @angular/core** - returned below warning 

```
Package "@ionic-native/core" has an incompatible peer dependency to "rxjs" (requires "^5.0.1", would install "6.1.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=5.0.0-rc.0 <6.0.0||>=2.3.1 <3.0.0||>=4.0.0-beta <5.0.0", would install "6.0.0").
                  Package "ng2-translate" has an incompatible peer dependency to "@angular/core" (requires ">=3.0.0-rc.0 <4.0.0||>=2.0.0 <3.0.0", would install "6.0.0").
                  Package "ng2-translate" has an incompatible peer dependency to "@angular/http" (requires ">=3.0.0-rc.0 <4.0.0||>=2.0.0 <3.0.0", would install "6.0.0").
Incompatible peer dependencies found. See above
```

4) So tried this command **ng update @angular/core --force**

5) **ng serve -o** command returns below error

```
Could not find module "@angular-devkit/build-angular" 
```

6) did npm install <code>@angular-devkit/build-angular</code> --save-dev

7) did **ng serve -o** again, getting the below error 

```
Module build failed: TypeError: Cannot read property 'postcss' of undefined
    at Object.module.exports (/XXX/node_modules/postcss-loader/index.js:40:32)
ERROR in ./src/app/lib/bootstrap-4.0.0-beta/css/bootstrap.min.css (./node_modules/raw-loader!./node_modules/postcss-loader??embedded!./src/app/lib/bootstrap-4.0.0-beta/css/bootstrap.min.css)
Module build failed: TypeError: Cannot read property 'sassLoader' of undefined
    at getLoaderConfig (/xxx/node_modules/sass-loader/index.js:389:39)
    at Object.module.exports (/xxx/node_modules/sass-loader/index.js:42:23)
ERROR in ./xxx/inputControls.component.scss
```

8) Also tried "npm install sass-loader node-sass --save-dev",  but same error.

Also this error is returning for all component scss files.

## Environment

Angular version: 6.0
ng-bootstrap: 1.1.2

Browser:
- Chrome (desktop) version
For Tooling issues:
- Node version: 8.9.1
- npm: 5.0.3 
- Platform:  Mac

**Comment by hansl** [comment]
Hi @sureshdotariya,

Do you have a project we could clone to try to reproduce this issue?  We cannot reproduce it locally :/

Cheers!

**Comment by sureshdotariya** [comment]
We cannot share the project source code. It's the enterprise Application. 
Regarding SASS, we have configured 'View Encapsulation' as 'encapsulation: ViewEncapsulation.None' in app.component.ts

Also, this error is happening in all  component files with 'styleUrls' property pointing to scss files.

Added package.json file
```

{
  "name": "xxxxx",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "webpack-dev-server --port=4200",
    "build": "webpack",
    "test": "karma start ./karma.conf.js",
    "lint": "ng lint",
    "e2e": "protractor ./protractor.conf.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.0.1",
    "@angular/common": "6.0.1",
    "@angular/compiler": "6.0.1",
    "@angular/core": "6.0.1",
    "@angular/forms": "6.0.1",
    "@angular/http": "6.0.1",
    "@angular/platform-browser": "6.0.1",
    "@angular/platform-browser-dynamic": "6.0.1",
    "@angular/router": "6.0.1",
    "@ionic-native/call-number": "^3.12.1",
    "@ionic-native/camera": "^3.10.3",
    "@ionic-native/contacts": "^3.12.1",
    "@ionic-native/core": "^3.9.2",
    "@ionic-native/device": "^3.12.1",
    "@ionic-native/email-composer": "^3.10.3",
    "@ionic-native/file": "^3.10.3",
    "@ionic-native/file-opener": "^3.10.3",
    "@ionic-native/google-maps": "^3.9.2",
    "@ionic-native/in-app-browser": "^3.10.3",
    "@ionic-native/keyboard": "^3.10.0",
    "@ionic-native/network": "^3.9.2",
    "@ionic-native/photo-library": "4.3.3",
    "@ionic-native/push": "^3.12.1",
    "@ionic-native/screen-orientation": "^3.10.0",
    "@ionic-native/sim": "^3.12.1",
    "@ionic-native/splash-screen": "^3.10.0",
    "@ionic-native/status-bar": "^3.10.0",
    "@ionic-native/toast": "^3.12.1",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.2",
    "@ng-idle/core": "^2.0.0-beta.11",
    "@ng-idle/keepalive": "^2.0.0-beta.11",
    "aframe": "^0.5.0",
    "angular-calendar": "^0.21.2",
    "angular2-moment": "^1.3.3",
    "core-js": "^2.4.1",
    "intl": "^1.2.5",
    "localforage": "^1.5.0",
    "localforage-cordovasqlitedriver": "^1.6.0",
    "lodash": "^4.17.4",
    "moment": "2.18.1",
    "node-sass": "^4.5.2",
    "rxjs": "6.1.0",
    "sass-loader": "^4.1.1",
    "stacktrace-js": "^2.0.0",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.4",
    "enhanced-resolve": "3.3.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.1",
    "@angular/cli": "^6.0.0",
    "@angular/compiler-cli": "6.0.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "angular-ide": "^0.9.19",
    "autoprefixer": "^6.5.3",
    "codelyzer": "~2.0.0",
    "crypto-js": "^3.1.9-1",
    "css-loader": "^0.26.1",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "file-loader": "^0.10.0",
    "hammerjs": "^2.0.8",
    "husky": "^0.14.3",
    "istanbul-instrumenter-loader": "^2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "json-loader": "^0.5.4",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-sourcemap-loader": "^0.3.7",
    "less-loader": "^2.2.3",
    "ng2-translate": "^5.0.0",
    "node-sass": "^4.5.2",
    "postcss-loader": "^0.13.0",
    "postcss-url": "^5.1.2",
    "prettier": "^1.12.0",
    "protractor": "~5.1.0",
    "raw-loader": "^0.5.1",
    "rxjs-tslint": "^0.1.3",
    "sass-loader": "^4.1.1",
    "script-loader": "^0.7.0",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.1",
    "stylus-loader": "^2.4.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "2.7.2",
    "url-loader": "^0.5.7",
    "webpack-dev-server": "~2.3.0"
  }


```

**Comment by sureshdotariya** [comment]
Its been resolved. We updated the sass-loader, node-sass, ts-node, postcss-loader packages to latest version. That solved this issue.
