### ISSUE TITLE
ng build -prod fails to clean up files

### ISSUE THREAD

**Issue by lamaan** [angular/angular-cli#1068]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.5
node: 5.6.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng build works fine but ng build -prod fails giving error below. You can reproduce with my code from https://github.com/lamaan/angular2-salah-times

4. The log given by the failure. Normally this include a stack trace and some
   more information.
C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times>ng build -prod
Cleanup error.
ENOTEMPTY: directory not empty, rmdir 'C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\tmp\broccoli_type_script_compiler-cache_path-973l28
5M.tmp\src\app'
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\tmp\broccoli_type_script_compiler-cache_path
-973l285M.tmp\src\app'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:806:18)
    at rmkidsSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:247:11)
    at rmdirSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:216:26)
    at C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:216:26)
    at C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\quick-temp\node_modules\rimraf\rimraf.js:237:7)
Build failed.
The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for angular2-google-maps/core.js at file:///C:/Users/Lamaan/AAAWork/shariahstandards.org/app/angular2-salah-times/tmp/bundle_plugin-input_base_pa
th-XrdEiDow.tmp/0/angular2-google-maps/core.js
        Loading main.js
        Error: ENOENT: no such file or directory, open 'C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\tmp\bundle_plugin-input_base_path-
XrdEiDow.tmp\0\angular2-google-maps\core.js'
    at Error (native)

The broccoli plugin was instantiated at:
    at BundlePlugin.Plugin (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\broccoli-plugin\index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\broccoli-caching-writer\i
ndex.js:21:10)
    at BundlePlugin (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\angular-cli\lib\broccoli\angular-broccoli-bundle.js:10:3
6)
    at Angular2App._getBundleTree (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\angular-cli\lib\broccoli\angular2-app.js:4
21:22)
    at Angular2App._buildTree (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\angular-cli\lib\broccoli\angular2-app.js:159:2
1)
    at new Angular2App (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\angular-cli-build.js:8:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\angular-cli\lib
\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\angular-cli\lib\models\builder.
js:89:10)
    at new Class (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\angular-cli\lib\tasks\build.js:1
5:19)
    at C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Lamaan\AAAWork\shariahstandards.org\app\angular2-salah-times\node_modules\rsvp\dist\rsvp.js:1198:9)

5. Mention any other details that might be useful.

**Comment by lamaan** [comment]
this may be related:
http://stackoverflow.com/questions/33657172/ember-cli-cleanup-error-when-building

**Comment by lamaan** [comment]
this was just windows not deleting files correctly and some other config errors which have now been resolved

**Comment by Sijan117** [comment]
I know this is closed but I'm facing the very same issue and was wondering how did you resolve this?

**Comment by lamaan** [comment]
Just had to delete the tmp folder manually. Initially, it was quite large. But now, I rarely get the problem. 

-----Original Message-----

**Comment by MrCroft** [comment]
I still get the error. I guess it depends on how large the app is.
On a basic app (just "ng new app") it works.
But, I don't know why, once I have a few components and routes, it gives me the above mentioned error. I tried to delete both "tmp" and "dist" folders before trying `build -prod` or `serve -prod`, but still gives the same error.

**Comment by filipesilva** [comment]
@MrCroft I can't say one way or another if it's a build bug or a code bug, but since we're moving away from SystemJS config in #1455 it might be a good idea to try that before opening an issue. There's no release yet though.

**Comment by MrCroft** [comment]
@filipesilva
Oh, I'm so sad! I was so avoiding webpack :)
Then again, I've got to hating webpack **so so much** simply because more and more examples out there were using it, going "against" the default (systemjs) approach of the cli, which was also the default approach in the angular docs/quickstart.
Now I'm wondering if it will be a quick and painless transition, to move my cli app from systemjs to webpack, once the cli will move away from systemjs and towards webpack.

**Comment by filipesilva** [comment]
I've WIP instructions in https://github.com/angular/angular-cli/pull/1456. Most people seem to think the transition is easy.

**Comment by lamaan** [comment]
Hi,

 

I have now moved the code to the webpack version and am getting the following curious error from webpack trying to resolve a different dependency injection issue:

 



It seems that the Provider is not the correct type of provider?

 

 <https://github.com/lamaan/angular2-salah-times/tree/dictionary-with-injected-routes> https://github.com/lamaan/angular2-salah-times/tree/dictionary-with-injected-routes

 

Lamaan

**Comment by lamaan** [comment]
Hi again,

 

I removed the dependency on angular2-google-maps to get it working.

 

Other problems found using web pack:

 

1.      Files are very big. It creates 5Mb main script file and 5 Mb map file. Which is very large for a small app like this.

2.      The source map cannot be parsed – at least by chrome which makes debugging only possible really with console.log.

3.      I cannot see how to include additional npm components as I did with system.js packages – so for now I have managed with using cdn. 

 

Please can you let me know if and when you have any solutions to these?

 

Lamaan

 

From: Lamaan Ball [mailto:lamaan@lamaan.com] 
Sent: 05 August 2016 07:39
To: 'angular/angular-cli' <reply@reply.github.com>
Subject: RE: [angular/angular-cli] ng build -prod fails to clean up files (#1068)

 

Hi,

 

I have now moved the code to the webpack version and am getting the following curious error from webpack trying to resolve a different dependency injection issue:

 



It seems that the Provider is not the correct type of provider?

 

 <https://github.com/lamaan/angular2-salah-times/tree/dictionary-with-injected-routes> https://github.com/lamaan/angular2-salah-times/tree/dictionary-with-injected-routes

 

Lamaan

**Comment by filipesilva** [comment]
@lamaan can you open a new issue for the issue you're still experiencing?
