### ISSUE TITLE
ng new not working

### ISSUE THREAD

**Issue by djidel** [angular/angular-cli#10691]
### Versions
Angular CLI: 6.0.0
Node: 10.0.0
OS: win32 x64
Angular:
...
Package                      Version
angular-devkit/architect    0.6.0
angular-devkit/core         0.6.0
angular-devkit/schematics   0.6.0
schematics/angular          0.6.0
schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.7.2

### Repro steps
ng new ng-app

### Observed behavior
Commande output:
```
Schematic "ng-new" not found in collection "@schematics/angular".
Error: Schematic "ng-new" not found in collection "@schematics/angular".
    at SchematicEngine.createSchematic (C:\Users\User\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:155:23)
    at CollectionImpl.createSchematic (C:\Users\User\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\collection.js:12:29)
    at NodeWorkflow.execute (C:\Users\User\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\workflow\node-workflow.js:70:38)
    at Promise (C:\Users\User\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:141:22)
    at new Promise (<anonymous>)
    at NewCommand.runSchematic (C:\Users\User\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:140:16)
    at NewCommand.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\@angular\cli\commands\new.js:77:25)
    at Generator.next (<anonymous>)
    at C:\Users\User\AppData\Roaming\npm\node_modules\@angular\cli\commands\new.js:7:71
    at new Promise (<anonymous>)
```

### Desired behavior
Should generate angular app

**Comment by larssn** [comment]
Your install must be broken. It works fine for me.

**Comment by djidel** [comment]
@larssn do you have the same npm and node versions?

**Comment by dev2colours** [comment]
same problem for me

**Comment by djidel** [comment]
@larssn are you in Windows x64?

**Comment by tonmanayo** [comment]
npm install -g npm
npm uninstall -g angular-cli
npm cache clean
npm install -g @angular/cli@lates

**Comment by djidel** [comment]
@tonmanayo I tried your instructions, that doesn't solve the problem for me.

**Comment by djidel** [comment]
I tested in another machine with the same environment and it works!
But I don't know why it still doesn't work in the first machine. I tried uninstalling npm, deleting the `npm` and `npm-cache` folders from `\AppData\Roaming\`, and installing again with no success.

Any thoughts on what could cause the problem?

**Comment by clydin** [comment]
Could you provide the output of both the following commands?
```
npm ls -g @schematics/angular
npm ls @schematics/angular
```

**Comment by djidel** [comment]
@clydin This is the output:
```
> npm ls -g @schematics/angular
C:\Users\User\AppData\Roaming\npm
`-- @angular/cli@6.0.0
  `-- @schematics/angular@0.6.0

> npm ls @schematics/angular
C:\Users\User
+-- @angular/cli@6.0.0
| `-- @schematics/angular@0.6.0  extraneous
`-- @schematics/angular@0.3.2

npm ERR! extraneous: @schematics/angular@0.6.0 C:\Users\User\node_modules\@angular\cli\node_modules\@schematics\angular
```

**Comment by clydin** [comment]
From the output from the second command it appears that there is a node_modules folder (and potentially `package.json`) with both the CLI and an old version of `@schematics/angular` installed locally.  This is most likely the source of the problem and under typical scenarios should not be present.

**Comment by rahulshukla422** [comment]
Awesome man its working fine. Spends hell lot of time to identify the issue but this is really nice.

Thank you so much @clydin

**Comment by FelixKre** [comment]
Hi!

I have the same problem. I don´t understand what folder exactly is to delete?!?! Simply deleting the whole node_module folder under /user/my_username/ doesn´t solve the problem. I can generate a new app but this consists only of the @angular/cli and all other packages are missing.

**Comment by raviranjan0631** [comment]
npm install -g npm
npm uninstall -g @angular/cli
npm uninstall @angular/cli
npm cache clean --force
npm install -g @angular/cli@latest 

check if it's work otherwise just update two more packages

npm i -g @schematics/angular
npm i -g @schematics/angular


npm i  @schematics/angular
npm i  @schematics/angular


This will force to update both local and global package.json file to use all the dependencies of angular 6 



Hope this will work, This approach had worked in my mac

**Comment by vickytechkey** [comment]
npm install g @angular/cli the command global installation create the problem in acessing the c drive so installing tha angular cli in the project folder will not cause ant warning or error
![screenshot_1](https://user-images.githubusercontent.com/31525460/46915529-967e4080-cfca-11e8-9c17-079d3113ce83.png)

**Comment by vickytechkey** [comment]
> same problem for me
npm install g @angular/cli the command global installation create the problem in acessing the c drive so installing tha angular cli in the project folder will not cause ant warning or error
![screenshot_1](https://user-images.githubusercontent.com/31525460/46915550-c62d4880-cfca-11e8-9b57-d4688c919d2b.png)
