### ISSUE TITLE
Errors using any ng update command

### ISSUE THREAD

**Issue by natmegs** [angular/angular-cli#10713]
### Versions
```
Angular CLI: 6.0.0
Node: 8.9.1
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.5.7
@angular-devkit/schematics   0.6.0
@angular/cdk                 5.2.0
@angular/cli                 6.0.0
@angular/material            5.2.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.6.2
```

### Repro steps
```
ng update @angular/cli
```

### Observed behavior
```
TypeError: tools_1.NodeWorkflow is not a constructor
    at UpdateCommand.runSchematic (/pathto/node_modules/@angular/cli/models/schematic-command.js:71:26)
    at UpdateCommand.<anonymous> (/pathto/node_modules/@angular/cli/commands/update.js:70:25)
    at Generator.next (<anonymous>)
    at /pathto/node_modules/@angular/cli/commands/update.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/pathto/node_modules/@angular/cli/commands/update.js:3:12)
    at UpdateCommand.run (/pathto/node_modules/@angular/cli/commands/update.js:69:16)
    at /pathto/node_modules/@angular/cli/models/command-runner.js:278:30
    at Generator.next (<anonymous>)
    at fulfilled (/pathto/node_modules/@angular/cli/models/command-runner.js:4:58)
```

### Desired behavior
Hoping this would just work as expected based on the [instructions for updating Angular](https://update.angular.io/) 

### Mention any other details that might be useful (optional)
Previously, when running the command I was seeing 
```
Unknown error: Error: Cannot find module 'rxjs-compat/observable/from'
```
So I added rxjs-compat via yarn (yarn add rxjs-compat) and now I am getting the above error.
When I try doing other ng update commands (ex ng update @angular/core) I get the same result.

**Comment by clydin** [comment]
The project appears to have an incompatible set of dependency versions.  For example, from the version command above `@angular-devkit/core         0.5.7`.

Could the `package.json` be provided from the project?

**Comment by natmegs** [comment]
@clydin Here are the package.json dependencies:

```
"dependencies": {
    "@angular/animations": "5.2.10",
    "@angular/cdk": "5.2.0",
    "@angular/common": "5.2.10",
    "@angular/compiler": "5.2.10",
    "@angular/core": "5.2.10",
    "@angular/forms": "5.2.10",
    "@angular/http": "5.2.10",
    "@angular/material": "5.2.0",
    "@angular/platform-browser": "5.2.10",
    "@angular/platform-browser-dynamic": "5.2.10",
    "@angular/platform-server": "5.2.10",
    "@angular/router": "5.2.10",
    "core-js": "2.5.3",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "underscore": "1.8.3",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/core": "0.5.7",
    "@angular/cli": "^6.0.0",
    "@angular/compiler-cli": "5.2.10",
    "@angular/language-service": "5.2.10",
    "@types/jasmine": "2.8.6",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "9.4.0",
    "codelyzer": "4.2.1",
    "hammerjs": "2.0.8",
    "jasmine-core": "2.9.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.4.2",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-mocha-reporter": "2.2.5",
    "karma-teamcity-reporter": "1.1.0",
    "node-sass": "4.7.2",
    "protractor": "5.3.0",
    "ts-node": "4.1.0",
    "tslint": "5.9.1",
    "typescript": "2.6.2"
  }
```

**Comment by phl3x0r** [comment]
try updating @angular-devkit/core to 0.6.0

**Comment by natmegs** [comment]
@phl3x0r Awesome that worked, thank you!
