### ISSUE TITLE
Cannot read property 'environment' of undefined at AngularCompilerPlugin

### ISSUE THREAD

**Issue by mrjohnr** [angular/angular-cli#10731]
Hi.
After I've upgraded my Asp core project from Angular 5 to 6 I got TypeError: **Cannot read property 'environment' of undefined** only when I deploy/publish:

```
D:\_dev_\PosWeb\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:581
    compiler.hooks.environment.tap('angular-compiler', () => {
                   ^
TypeError: Cannot read property 'environment' of undefined
    at AngularCompilerPlugin.apply (D:\_dev_\PosWeb\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:581:20)
    at Compiler.apply 
....
D:\_dev_\PosWeb\PosWeb.csproj(62,5): Error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 1.
```
thanks

```
Angular CLI: 6.0.0
Node: 9.11.1
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/language-service         5.0.1
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.8.3
webpack                           2.5.1

```

**Comment by clydin** [comment]
The webpack version appears to be 2.5.1.  CLI v6 depends on webpack 4.3+ and webpack should not generally be installed directly within the project.

**Comment by mrjohnr** [comment]
Hi,can you give me a working solution running  `npm install  webpack@latest `not solving the problem.thanks

**Comment by clydin** [comment]
If webpack is present within the project's `package.json`, try removing it completely.  Then to ensure the packages are installed properly before running `npm install` remove both the `node_modules` folder and the `package-lock.json` file.

**Comment by mrjohnr** [comment]
Hi.thanks for your time.There are 2 day spent trying to update from angular 5 to 6 :(

I think my my asp core project is based on webpack,for example if I update bootstrap I have to run  webpack --config webpack.config.vendor.js 

I've removed and now got  **Cannot find module webpack**:

```
AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'webpack'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
```
