### ISSUE TITLE
if server folder exists ng serve throws error

### ISSUE THREAD

**Issue by slayerfat** [angular/angular-cli#1075]
1. OS? 
Linux ubuntu 16.04

2. Versions. Please run `ng --version`.
angular-cli: 1.0.0-beta.5
node: 6.2.1
os: linux x64

3. Repro steps.
_UPDATED:_ i found the real problem, ng serve throws error if a server folder exist in the root folder.
ng new server-test
mkdir server
ng serve

4. The log given by the failure.
```
Cannot find module '/home/x/Code/server-test/server'
Error: Cannot find module '/home/x/Code/server-test/server'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Project.require (/home/x/Code/server-test/node_modules/angular-cli/node_modules/angular-cli/lib/models/project.js:280:12)
    at Class.module.exports.Task.extend.processAppMiddlewares (/home/x/Code/server-test/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/server/express-server.js:115:33)
    at Class.<anonymous> (/home/x/Code/server-test/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/server/express-server.js:220:21)
    at lib$rsvp$$internal$$tryCatch (/home/x/Code/server-test/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/x/Code/server-test/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/x/Code/server-test/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/x/Code/server-test/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by filipesilva** [comment]
Now *that* is a weird bug.

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.
