### ISSUE TITLE
ng help command produces duplicate and incorrect docs

### ISSUE THREAD

**Issue by Blasz** [angular/angular-cli#1078]
1. OS
   Ubuntu 14.04
2. Versions
   
   ```
   $ ng --version
   (node:5182) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
   Could not start watchman; falling back to NodeWatcher for file system events.
   Visit http://ember-cli.com/user-guide/#watchman for more info.
   angular-cli: 1.0.0-beta.5
   node: 6.2.1
   os: linux x64
   ```
3. Repro steps.

Running `ng help` produces two sets of commands.

```
Available commands in angular-cli:
...
Available commands in ng2:
...
```

There is overlap in the commands shown and the flags/description usually differ. Some commands are only in the first set (build), some only in the second (e2e).
There's no single source of truth making it hard to find the correct command documentation.

This also occurs when running `ng help generate`.

```
$ ng help generate
...
Available blueprints:
  ng2:
    ..
  angular-cli:
    ..
```

All the blueprints from angular-cli that I've tried don't work:

```
$ ng generate component-addon test --dry-run
(node:6399) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Invalid blueprint: component-addon
```

But some of the ng2 blueprints don't work either:

```
$ ng generate service-test test --dry-run
(node:6443) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at Class.module.exports.Task.extend.run (/home/vagrant/ng2-widgets/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/generate-from-blueprint.js:61:7)
    at Class.module.exports.Command.extend.run (/home/vagrant/ng2-widgets/node_modules/angular-cli/node_modules/angular-cli/lib/commands/generate.js:65:17)
    at Class.<anonymous> (/home/vagrant/ng2-widgets/node_modules/angular-cli/node_modules/angular-cli/lib/models/command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (/home/vagrant/ng2-widgets/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/vagrant/ng2-widgets/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/home/vagrant/ng2-widgets/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/home/vagrant/ng2-widgets/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

`ng generate --help` seems to display the correct blueprints however.

Thanks.

**Comment by hansl** [comment]
Closing this as obsolete.
