### ISSUE TITLE
ng g new failing - schematics error

### ISSUE THREAD

**Issue by pnahtanoj** [angular/angular-cli#10792]
### Versions
mac-jprice:~ jprice$ ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.9
node: 8.8.1
os: darwin x64

```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

I'm just running ng new:

mac-jprice:~ jprice$ ng g new cbaexample
Schematic "new" not found in collection "@schematics/angular".
Error: Schematic "new" not found in collection "@schematics/angular".
    at NodeModulesEngineHost.createSchematicDescription (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:137:19)
    at SchematicEngine.createSchematic (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:108:40)
    at CollectionImpl.createSchematic (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/collection.js:11:29)
    at Object.getSchematic (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/utilities/schematics.js:45:23)
    at Class.run (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/tasks/schematic-get-options.js:12:40)
    at Class.beforeRun (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/commands/generate.js:89:31)
    at Promise.resolve.then (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:138:24)
    at <anonymous>

### Observed behavior

mac-jprice:~ jprice$ ng g new cbaexample
Schematic "new" not found in collection "@schematics/angular".
Error: Schematic "new" not found in collection "@schematics/angular".
    at NodeModulesEngineHost.createSchematicDescription (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:137:19)
    at SchematicEngine.createSchematic (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:108:40)
    at CollectionImpl.createSchematic (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/engine/collection.js:11:29)
    at Object.getSchematic (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/utilities/schematics.js:45:23)
    at Class.run (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/tasks/schematic-get-options.js:12:40)
    at Class.beforeRun (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/commands/generate.js:89:31)
    at Promise.resolve.then (/Users/jprice/.nvm/versions/node/v8.8.1/lib/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:138:24)
    at <anonymous>

```
<!-- Normally this includes a stack trace and some more information. -->
```

### Desired behavior
New project created successfully

### Mention any other details that might be useful (optional)
I *think* this started after I tried using latest cli.  Reverting to 1.4.9 doesn't seem to help.

Per https://github.com/angular/angular-cli/issues/10691

mac-jprice:~ jprice$ npm ls -g @schematics/angular
/Users/jprice/.nvm/versions/node/v8.8.1/lib
└─┬ @angular/cli@1.4.9
  └── @schematics/angular@0.0.49 

mac-jprice:~ jprice$ npm ls @schematics/angular
/Users/jprice
└── (empty)

**Comment by clydin** [comment]
If trying to create a new project, the command is `ng new <project-name>` not `ng generate new`.

**Comment by pnahtanoj** [comment]
Wow, stupid oversight.  Sorry about that.
