### ISSUE TITLE
[feature-request] Need supported way to import/require text of arbitrary project files

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/angular-cli#10798]
Although not officially supported versions of Angular CLI prior to 6.0.0 allowed using require('!!raw-loader!/path/to/file') to load the contents of any file in the module paths.

In 6.0.0 this broke for JSON files due to [webpack changes](https://github.com/webpack/webpack/issues/6586#issuecomment-368677035).

```
ERROR in ./src/app/documentation/concepts/offline/update-config.before.json (./node_modules/raw-loader!./src/app/documentation/concepts/offline/update-config.before.json)
Module parse failed: Unexpected token m in JSON at position 0
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
    at JsonParser.parse (C:\snap\ws\sample-md-cli\node_modules\webpack\lib\JsonParser.js:15:21)
    at doBuild.err (C:\snap\ws\sample-md-cli\node_modules\webpack\lib\NormalModule.js:375:32)
    at runLoaders (C:\snap\ws\sample-md-cli\node_modules\webpack\lib\NormalModule.js:272:12)
    at C:\snap\ws\sample-md-cli\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (C:\snap\ws\sample-md-cli\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (C:\snap\ws\sample-md-cli\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at C:\snap\ws\sample-md-cli\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at runSyncOrAsync (C:\snap\ws\sample-md-cli\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\snap\ws\sample-md-cli\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (C:\snap\ws\sample-md-cli\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\snap\ws\sample-md-cli\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at provider (C:\snap\ws\sample-md-cli\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)
    at C:\snap\ws\sample-md-cli\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```
This functionality is very useful, and it would be nice to have a supported way of doing this that worked for all file types, and all CLI backends (Bazel?).

At my job we are using this to:
* Load our code examples to display in our documentation
* Load our schematics collection/schema json to display our schematic documentation
* As a replacement for html2js in a hybrid angularJS app
* To bundle svg icons for use with @angular/material so we don't need a bunch of HTTP request

I'm sure there a plenty of other uses considering most JS module loaders supports this in some form.
https://github.com/requirejs/text
https://github.com/systemjs/plugin-text
https://dojotoolkit.org/reference-guide/1.10/dojo/text.html
https://github.com/JohnPostlethwait/stringify
https://github.com/bclinkinbeard/partialify

**Comment by alan-agius4** [comment]
Hi @james-schwartzkopf,

Thanks for this feature request. However, this doesn't fall in the Angular CLI roadmap.

The above can be achieved by extending the Angular CLI using 3rd party builders such as https://github.com/manfredsteyer/ngx-build-plus

**Note**: Webpack specific feature might break without warning in any Angular CLI version.
