### ISSUE TITLE
"ng e2e --prod" fails

### ISSUE THREAD

**Issue by russon77** [angular/angular-cli#10909]
### Versions
```
Angular CLI: 6.0.3                                                                                                                                          │
Node: 10.0.0                                                                                                                                                │
OS: linux x64                                                                                                                                               │
Angular: 6.0.2                                                                                                                                              │
... animations, common, compiler, compiler-cli, core, forms                                                                                                 │
... http, language-service, platform-browser                                                                                                                │
... platform-browser-dynamic, router                                                                                                                        │
                                                                                                                                                            │
Package                           Version                                                                                                                   │
-----------------------------------------------------------                                                                                                 │
@angular-devkit/architect         0.6.3                                                                                                                     │
@angular-devkit/build-angular     0.6.3                                                                                                                     │
@angular-devkit/build-optimizer   0.6.3                                                                                                                     │
@angular-devkit/core              0.6.3                                                                                                                     │
@angular-devkit/schematics        0.6.3                                                                                                                     │
@angular/cli                      6.0.3                                                                                                                     │
@ngtools/webpack                  6.0.3                                                                                                                     │
@schematics/angular               0.6.3                                                                                                                     │
@schematics/update                0.6.3                                                                                                                     │
rxjs                              6.1.0                                                                                                                     │
typescript                        2.7.2                                                                                                                     │
webpack                           4.8.3                                                                                                                     │
    
```

### Repro steps

* Step 1: create a new app with `ng new its-a-test-app`
* Step 2 run e2e tests normally with `ng e2e`
* Step 3 run e2e tests against production configuration `ng e2e --prod`

### Observed behavior
```
Configuration 'production' could not be found in project 'its-a-test-e2e'.
Error: Configuration 'production' could not be found in project 'its-a-test-e2e'.
    at Architect.getBuilderConfiguration (/tmp/its-a-test/node_modules/@angular-devkit/architect/src/architect.js:102:23)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (/tmp/its-a-test/node_modules/@angular/cli/models/architect-command.js:64:55)
    at MergeMapSubscriber._tryNext (/tmp/its-a-test/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/tmp/its-a-test/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/tmp/its-a-test/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (/tmp/its-a-test/node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (/tmp/its-a-test/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/tmp/its-a-test/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/tmp/its-a-test/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/tmp/its-a-test/node_modules/rxjs/internal/Subscriber.js:103:18)                                                                         

```

### Desired behavior

`ng e2e --prod --aot` should run the e2e tests against the production, AOT-compiled build of the application. I had an issue solely on production/AOT, so I would like to test against this configuration.

**Comment by filipesilva** [comment]
You can add a configuration for e2e that runs against the production dev server:
```
"project-name-e2e": {
  "root": "e2e/",
  "projectType": "application",
  "architect": {
    "e2e": {
      "builder": "@angular-devkit/build-angular:protractor",
      "options": {
        "protractorConfig": "e2e/protractor.conf.js",
        "devServerTarget": "project-name:serve"
      },
      "configurations": {
        "production": {
          "devServerTarget": "project-name:build:production"
        }
      }
    },
```

This question has come up a couple of times so far though. I'll add it to the default schematics.

**Comment by russon77** [comment]
thanks @filipesilva ! just a note, i had to change `"devServerTarget": "project-name:build:production"` to `"devServerTarget": "project-name:serve:production"` (build -> serve).
