### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read at Error (native)

### ISSUE THREAD

**Issue by bokiemon** [angular/angular-cli#1091]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
v5.0.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I followed the steps in the guide all the way to setting up the app-shell and gotten the following error in the log below:
The command I ran was sudo ng serve --prod

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for vendor/@angular/app-shell at file:///Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/tmp/bundle_plugin-input_base_path-SyEvxU7a.tmp/0/vendor/@angular/app-shell
	Loading app/hello-mobile.component.js
	Loading app/index.js
	Loading main.js
	Error: EISDIR: illegal operation on a directory, read
    at Error (native)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BundlePlugin (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/lib/broccoli/angular-broccoli-bundle.js:10:36)
    at Angular2App._getBundleTree (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/lib/broccoli/angular2-app.js:375:55)
    at Angular2App._buildTree (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/lib/broccoli/angular2-app.js:137:21)
    at new Angular2App (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/lib/broccoli/angular2-app.js:42:23)
    at module.exports (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/thyeyeowbok/Downloads/PWA/angular-mobile/hello-mobile/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
I initially thought this might be related to angular-material, so I repeat the steps again skipping over the angular material section but still get the same error. 

Love the idea and would like to share this with developer groups but can't seem to get pass this error. Any help / insights will be very much appreciated! 

> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
What guide is it that you followed?

**Comment by filipesilva** [comment]
Closed as obsolete following #1455.
