### ISSUE TITLE
When running tests on a library, unable to resolve all parameters for a service

### ISSUE THREAD

**Issue by joeattardi** [angular/angular-cli#10919]
### Versions
```
Angular CLI: 6.0.3
Node: 9.11.1
OS: darwin x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.3
@angular-devkit/build-angular      0.6.3
@angular-devkit/build-ng-packagr   0.6.3
@angular-devkit/build-optimizer    0.6.3
@angular-devkit/core               0.6.3
@angular-devkit/schematics         0.6.3
@angular/cli                       6.0.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.3
@schematics/angular                0.6.3
@schematics/update                 0.6.3
ng-packagr                         3.0.0-rc.5
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.8.3
```

### Repro steps

# test.ts
```
import 'zone.js/dist/zone';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

declare const require: any;

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
```

# karma.conf.js
```
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

# Spec file snippet
```
    let effects: ConsoleLoggerEffects;
    let actions: ReplaySubject<any>;

    beforeEach(() => {
      spyOn(console, 'info');

      TestBed.configureTestingModule({
        providers: [
          ConsoleLoggerEffects,
          provideMockActions(() => actions)
        ]
      });

      effects = TestBed.get(ConsoleLoggerEffects);
    });
```

# Service snippet (this is an ngrx Effect)
```
@Injectable()
export class ConsoleLoggerEffects {
  constructor(private actions$: Actions) {}
}
```

### Observed behavior
```
Error: Can't resolve all parameters for ConsoleLoggerEffects: (?).
	    at syntaxError Users/jattardi/code/commerce-cloud-ui/core-services/node_modules/@angular/compiler/fesm5/compiler.js:215:1)
	    at CompileMetadataResolver.push.../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata Users/jattardi/code/commerce-cloud-ui/core-services/node_modules/@angular/compiler/fesm5/compiler.js:10807:1)
	    at CompileMetadataResolver.push.../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata Users/jattardi/code/commerce-cloud-ui/core-services/node_modules/@angular/compiler/fesm5/compiler.js:10700:1)
	    at CompileMetadataResolver.push.../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getInjectableTypeMetadata Users/jattardi/code/commerce-cloud-ui/core-services/node_modules/@angular/compiler/fesm5/compiler.js:10922:1)
	    at CompileMetadataResolver.push.../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getProviderMetadata Users/jattardi/code/commerce-cloud-ui/core-services/node_modules/@angular/compiler/fesm5/compiler.js:10931:1)
	    at http://localhost:9876/_karma_webpack_/webpack:/Users/jattardi/code/commerce-cloud-ui/core-services/node_modules/@angular/compiler/fesm5/compiler.js:10869:1
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver.push.../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getProvidersMetadata Users/jattardi/code/commerce-cloud-ui/core-services/node_modules/@angular/compiler/fesm5/compiler.js:10829:1)
	    at CompileMetadataResolver.push.../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/jattardi/code/commerce-cloud-ui/core-services/node_modules/@angular/compiler/fesm5/compiler.js:10548:1)
	    at JitCompiler.push.../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules Users/jattardi/code/commerce-cloud-ui/core-services/node_modules/@angular/compiler/fesm5/compiler.js:22567:1)
```

The test module is using a helper function from ngrx, `provideMockActions`, to supply a provider for the `Actions` parameter of the `ConsoleLoggerEffects` class. But even if I replace that with just a static object, for example:

`{ provide: Actions, useValue: new BehaviorSubject(1) }`

I get the same error.

### Desired behavior
The dependency is resolved and injected, and the tests pass

### Mention any other details that might be useful (optional)
- This is a library within an Angular CLI 6 project
- The same project previously did not use Angular CLI; in the non-Angular CLI version, the tests run successfully

**Comment by joeattardi** [comment]
@deebloo I tried adding that import, unfortunately I get the same result.

**Comment by joeattardi** [comment]
@deebloo Ignore my previous comment, I added the import to the wrong `test.ts` file. Sorry about that. My tests are passing now. Thanks!
