### ISSUE TITLE
Provider parse errors - Cannot instantiate cyclic dependency

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#10916]
### Versions
```
Angular CLI: 6.0.2
Node: 10.0.0
OS: linux x64
Angular: 6.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.2
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.2
@angular/flex-layout              5.0.0-beta.13
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.2
@schematics/update                0.6.2
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```

### Observed behavior
- was working before upgrading to ng 6 (with ng 5.2)
- now, the app is well served but when I try to build it with `ng build frontend --prod` I've got the following error

```
ERROR in : Error: Provider parse errors:
Cannot instantiate cyclic dependency! AsyncEnvironmentService ("[ERROR ->]"): in NgModule RootServerModule in /home/maxime/Documents/code/frontend/src/root/root.server.module.ts@-1:-1
Cannot instantiate cyclic dependency! AsyncEnvironmentService ("[ERROR ->]"): in NgModule RootServerModule in /home/maxime/Documents/code/frontend/src/root/root.server.module.ts@-1:-1
    at NgModuleProviderAnalyzer.parse (/home/maxime/Documents/code/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:11448:19)
    at NgModuleCompiler.compile (/home/maxime/Documents/code/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:11817:36)
    at AotCompiler._compileModule (/home/maxime/Documents/code/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:20438:32)
    at /home/maxime/Documents/code/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:20357:66
    at Array.forEach (<anonymous>)
    at AotCompiler._compileImplFile (/home/maxime/Documents/code/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:20357:19)
    at /home/maxime/Documents/code/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:20347:70
    at Array.map (<anonymous>)
    at AotCompiler.emitAllImpls (/home/maxime/Documents/code/frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:20347:35)
    at AngularCompilerProgram.generateFilesForEmit (/home/maxime/Documents/code/frontend/node_modules/@angular/compiler-cli/src/transformers/program.js:691:46)
    at AngularCompilerProgram._emitRender2 (/home/maxime/Documents/code/frontend/node_modules/@angular/compiler-cli/src/transformers/program.js:284:27)
    at AngularCompilerProgram.emit (/home/maxime/Documents/code/frontend/node_modules/@angular/compiler-cli/src/transformers/program.js:231:22)
    at AngularCompilerPlugin._emit (/home/maxime/Documents/code/frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:806:49)
    at Promise.resolve.then.then.then (/home/maxime/Documents/code/frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:631:54)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

- if I build it with `ng build frontend --prod=false` is working fine
- weird thing: it's trying to compile the `RootServerModule` which is not supposed to be compiled when I specify `frontend`. If I comment out every file server related, `ng build frontend --prod` is working fine again

### Desired behavior

- Being able to compile my frontend project as usual without trying to compile the server too
- `Cannot instantiate cyclic dependency!` is that even true? I didn't have that problem with ng 5.2 (but maybe it's because there's a mix between the frontend and the server)

### Mention any other details that might be useful (optional)
My `tsconfig.app.json` looks like that:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "skipLibCheck": true
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts",
    "**/*.e2e.ts",
    "server.ts"
  ],
  "angularCompilerOptions": {
    "preserveWhitespaces": false
  }
}
```

I'm explicitely excluding `server.ts`. Is that file still used?
Am I supposed to exclude server.ts from somewhere else?

**Comment by filipesilva** [comment]
Off the top of my head I would say that `server.ts` is being excluded but maybe not other server files like `src/root/root.server.module.ts`. This is triggering an error during AOT compilation.

I think you have to exclude all server files in your `tsconfig.app.json`, not just `server.ts`. Can you try that please?

**Comment by maxime1992** [comment]
Hey @filipesilva that was it! :tada: 

Thanks for the help, in case there's something that might be improved on your side I let the issue opened. Feel free to close it :)

**Comment by filipesilva** [comment]
Yeah it's not imported by the app but is included in the tsconfig compilation. When you don't have a `files` array property in `tsconfig` all files are included by default. You could add a `files` array with `main.ts` and `polyfills.ts` but then you'd also need to add all lazy routes which is bothersome.

Anyway glad to hear it's sorted!
