### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by mmcc1** [angular/angular-cli#10924]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
Node version: v0.12.2
NPM version: 2.7.4

Ng version:
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\XXXX\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

### Repro steps
<!--
Simple steps to reproduce this bug.
Please include: commands run, packages added, related code changes.
A link to a sample repo would help too.
-->
* Step 1
Install latest Node.js from here... https://nodejs.org/en/download/

* Step 2

Run npm install -g @angular/cli

* Step 3

Fail on install


### Observed behavior
```

```

npm\node_modules\@angular\cli\bin\ng-update-message.js:7
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! @angular/cli@6.0.3 postinstall: `node ./bin/ng-update-message.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular/cli@6.0.3 postinstall script 'node ./bin/ng-update-message.js'.
npm ERR! This is most likely a problem with the @angular/cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/ng-update-message.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls @angular/cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\xxxx\npm-debug.log

**Comment by mmcc1** [comment]
This was caused by the default install adding a 32 bit version of Nodejs and NPM.  Removed them and ran an update 'npm install npm@latest -g' and NPM updated to 6.0.1.  Cli seems to be installing fine now.
