### ISSUE TITLE
`ng new` returns "npm ERR! write after end" CLI 6.0.3

### ISSUE THREAD

**Issue by jlouros** [angular/angular-cli#10939]
`ng new` returns _"npm ERR! write after end"_ using CLI version 6.0.3

### Versions
```
Angular CLI: 6.0.3
Node: 8.11.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.1.0
typescript                   2.7.2

Windows 10 Pro, Version 1803, Build 17134.48
```

### Repro steps
* `npm i @angular/cli -g`
* `ng new projName`

### Observed behavior
partial npm error log displayed at the end of this issue

### Desired behavior
Expected new projected created without any errors.

### Mention any other details that might be useful (optional)
![2018-05-21](https://user-images.githubusercontent.com/587250/40302951-d03d9960-5ce8-11e8-8a5c-7349b71c2fa7.png)

**last lines of error log from npm:**
```
15761 silly tarball trying vary@~1.1.2 by hash: sha1-IpnwLG3tMNSllhsLn3RSShj2NPw=
15762 http fetch GET 200 https://registry.npmjs.org/vm-browserify/-/vm-browserify-0.0.4.tgz 155ms
15763 silly extract sockjs@0.3.19 extracted to C:\code\_protos\ngElems\node_modules\.staging\sockjs-3a092044 (1159ms)
15764 silly extract npm-package-arg@6.1.0
15765 silly tarball trying npm-package-arg@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 by hash: sha512-zYbhP2k9DbJhA0Z3HKUePUgdB1x7MfIfKssC+WLPFMKTBZKpZh5m13PgexJjCq6KW7j17r0jHWcCpxEqnnncSA==
15766 silly tarball no local data for vary@~1.1.2. Extracting by manifest.
15767 http fetch GET 200 https://registry.npmjs.org/spdy-transport/-/spdy-transport-2.1.0.tgz 451ms
15768 verbose stack Error: write after end
15768 verbose stack     at writeAfterEnd (_stream_writable.js:236:12)
15768 verbose stack     at PassThrough.Writable.write (_stream_writable.js:287:5)
15768 verbose stack     at PassThrough.Writable.end (_stream_writable.js:563:10)
15768 verbose stack     at ReadEntry.entry.on (C:\Users\jlour\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\extract-stream.js:19:41)
15768 verbose stack     at emitOne (events.js:121:20)
15768 verbose stack     at ReadEntry.emit (events.js:211:7)
15768 verbose stack     at ReadEntry.emit (C:\Users\jlour\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:296:25)
15768 verbose stack     at ReadEntry.[maybeEmitEnd] (C:\Users\jlour\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:249:12)
15768 verbose stack     at ReadEntry.end (C:\Users\jlour\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:162:27)
15768 verbose stack     at Unpack.[consumeBody] (C:\Users\jlour\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:210:13)
15768 verbose stack     at Unpack.[consumeChunkSub] (C:\Users\jlour\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:391:40)
15768 verbose stack     at Unpack.[consumeChunk] (C:\Users\jlour\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:362:30)
15768 verbose stack     at Unzip.(anonymous function).on.chunk (C:\Users\jlour\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:291:59)
15768 verbose stack     at emitOne (events.js:116:13)
15768 verbose stack     at Unzip.emit (events.js:211:7)
15768 verbose stack     at Unzip.emit (C:\Users\jlour\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\minipass\index.js:296:25)
15769 verbose cwd C:\code\_protos\ngElems
15770 verbose Windows_NT 10.0.17134
15771 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jlour\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--quiet"
15772 verbose node v8.11.1
15773 verbose npm  v6.0.1
15774 error write after end
15775 verbose exit [ 1, true ]
```

**Comment by saswatipriyadarshini** [comment]
I was having the same issue. I fixed it by downgrading npm to v5.6.0. I don't know what the issue is, lets hope they fix it.

**Comment by jlouros** [comment]
just tried again, exactly the same cmd `ng new ngElems` (didn't change anything) and now it works.

Looks like it was a issue with Angular dependencies

**Comment by alamgir019** [comment]
I was in same problem. after much try and error, i solved as follows. install yarn.  then run the following code `ng set --global packageManager=yarn`
and then run `ng new project_name`
this way, i solved the problem
