### ISSUE TITLE
Changing default styleExt to scss gives me Value cannot be found

### ISSUE THREAD

**Issue by piernik** [angular/angular-cli#10949]
I've made new project using `angular-cli@6.0.2`.
I want to change defalt style file to scss but command `ng config defaults.styleExt=scss` gives me  `Value cannot be found.`

How to change default style extention?

**Comment by filipesilva** [comment]
Heya, you can see here how to change the default for component generation: https://github.com/angular/angular-cli/wiki/stories-css-preprocessors

**Comment by piernik** [comment]
When I run that command `ng config schematics.@schematics/angular:component.styleext scss` I get error 
```
Invalid JSON character: "s" at 0:0.
Error: Invalid JSON character: "s" at 0:0.
    at _readValue (C:\strony\www\infirma\admin\node_modules\@angular-devkit\core\src\json\parser.js:567:19)
    at parseJsonAst (C:\strony\www\infirma\admin\node_modules\@angular-devkit\core\src\json\parser.js:605:17)
    at Object.parseJson (C:\strony\www\infirma\admin\node_modules\@angular-devkit\core\src\json\parser.js:631:12)
    at normalizeValue (C:\strony\www\infirma\admin\node_modules\@angular\cli\commands\config.js:128:19)
    at ConfigCommand.set (C:\strony\www\infirma\admin\node_modules\@angular\cli\commands\config.js:195:23)
    at ConfigCommand.run (C:\strony\www\infirma\admin\node_modules\@angular\cli\commands\config.js:168:18)
    at C:\strony\www\infirma\admin\node_modules\@angular\cli\models\command-runner.js:278:30
    at Generator.next (<anonymous>)
    at fulfilled (C:\strony\www\infirma\admin\node_modules\@angular\cli\models\command-runner.js:4:58)
    at <anonymous>

```

**Comment by filipesilva** [comment]
Looks like our string processing is broken but we're taking a look at it in https://github.com/angular/angular-cli/pull/10956, sorry for that!

**Comment by piernik** [comment]
No problem

**Comment by n-sikka** [comment]
@filipesilva i'm getting that same error when running that command on `v6.0.5`. The merged PR didnt quite work i guess. Can you confirm?

**Comment by robmass** [comment]
@n-sikka the merge is in the v6.0.7. I had this problem and with that version it is solved.

**Comment by calcerrada** [comment]
The same problem with `v.6.0.8`

**Comment by francovp** [comment]
Why this was closed? I have this problem with v6.0.8.

**Comment by dereklin** [comment]
@piernik When you say put 
```
"schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
```
in every project, where exactly do you put it?  Do you have to put it in all of the projects?

Could you show some context?

**Comment by piernik** [comment]
You have to add in in every project:
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
...
  "projects": {
    "frontend": {
      ...
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss",
        }
      }
}
```

**Comment by msqaddura** [comment]
@sannminwin you need to rename the *.css to *.scss files

**Comment by pfiterman** [comment]
I found the command, in the stackoverflow site:  ng config schematics.@schematics/angular:component.styleext scss. This command will automatically add the "schematics" section halfer mentioned to the angular.json file e generate the next components with scss instead of css

**Comment by ryanki1** [comment]
> I found the command, in the stackoverflow site: ng config schematics.@schematics/angular:component.styleext scss. This command will automatically add the "schematics" section halfer mentioned to the angular.json file e generate the next components with scss instead of css

Didn't work for me with:

Angular CLI: 7.3.6
Node: 8.9.4
OS: darwin x64
Angular: 7.2.9
