### ISSUE TITLE
ng run --help doesn't work and doesn't listen for default project

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#10958]
### Versions
```
Angular CLI: 6.0.3
Node: 10.1.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    <error>
@angular-devkit/core         <error>
@angular-devkit/schematics   <error>
@schematics/angular          <error>
@schematics/update           <error>
rxjs                         <error>
```

### Repro steps
ng new my-app
ng run --help

### Observed behavior
```
Cannot determine project or target for Architect command.
Error: Cannot determine project or target for Architect command.
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (/home/stephenfluin/workspace/test-app/node_modules/@angular/cli/models/architect-command.js:62:27)
    at MergeMapSubscriber._tryNext (/home/stephenfluin/workspace/test-app/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/home/stephenfluin/workspace/test-app/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/home/stephenfluin/workspace/test-app/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (/home/stephenfluin/workspace/test-app/node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (/home/stephenfluin/workspace/test-app/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/home/stephenfluin/workspace/test-app/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/home/stephenfluin/workspace/test-app/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/home/stephenfluin/workspace/test-app/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/home/stephenfluin/workspace/test-app/node_modules/rxjs/internal/operators/map.js:92:26)
```

### Desired behavior
1. help should work even if I don't specify a project
2. ng run should use the defaultProject setting of my project
3. Don't show the confusing RxJS error

**Comment by StephenFluin** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/10955
