### ISSUE TITLE
ng run --help not working

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#10955]
Moved from https://github.com/angular/devkit/issues/955 by @ampgular

---

### Bug Report or Feature Request (mark with an `x`)
- [ X] bug report -> please search issues before submitting
- [ ] feature request

### Area
- [X ] devkit
- [ ] schematics

### Versions
```
Angular CLI: 6.0.0
Node: 10.1.0
NPM: 5.6.0
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/devkit            0.0.0
@angular-devkit/schematics        0.6.3
@angular/platform-server          6.0.2
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
1- ng  new newproject
2 - ng run --help

### The log given by the failure
Cannot determine project or target for Architect command.
Error: Cannot determine project or target for Architect command.
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/@angular/cli/models/architect-command.js:75:27)
    at MergeMapSubscriber._tryNext (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/operators/map.js:92:26)
    at MapSubscriber.Subscriber.next (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/Javier/Documents/NuileaWeb/scheTest/node_modules/rxjs/internal/operators/mergeMap.js:141:26).......

### Desired functionality
Provide the required help

**Comment by filipesilva** [comment]
`ng run` needs a target in the format of `project:target` and is erroring out because of that. But without checking the help for this command it's hard to know that. 

We should show the proper help even if there is no target.

**Comment by eranation** [comment]
I didn't see this mentioned, but the real solution IMHO is to honor the **defaultProject** property in angular.json. This is the easiest and most backward compatible fix. I am pretty sure it was intended to be used as, well, the default, just accidentally shipped without it... Angular folks, please correct me if I'm wrong... (if I'm wrong then what is the use of defaultProject rather than not making you have to explicitly specify a project to the angular CLI?)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
