### ISSUE TITLE
`ng new` failed after installing Angular with the error `npm does not work when run with the Windows Scripting Host`

### ISSUE THREAD

**Issue by moriyas1984** [angular/angular-cli#10950]
### Versions
```
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.3
Node: 8.11.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.2.0
typescript                   2.7.2
```

### Repro steps
* Step 1: @angluar/cli install
```
$ npm install -g @angular/cli

```

### Observed behavior
* create new project
```
$ ng new myApp
CREATE myApp/angular.json (3436 bytes)
CREATE myApp/package.json (1316 bytes)
CREATE myApp/README.md (1027 bytes)
CREATE myApp/tsconfig.json (384 bytes)
CREATE myApp/tslint.json (2805 bytes)
CREATE myApp/.editorconfig (245 bytes)
CREATE myApp/.gitignore (503 bytes)
CREATE myApp/src/environments/environment.prod.ts (51 bytes)
CREATE myApp/src/environments/environment.ts (631 bytes)
CREATE myApp/src/favicon.ico (5430 bytes)
CREATE myApp/src/index.html (297 bytes)
CREATE myApp/src/main.ts (370 bytes)
CREATE myApp/src/polyfills.ts (3194 bytes)
CREATE myApp/src/test.ts (642 bytes)
CREATE myApp/src/assets/.gitkeep (0 bytes)
CREATE myApp/src/styles.css (80 bytes)
CREATE myApp/src/browserslist (375 bytes)
CREATE myApp/src/karma.conf.js (964 bytes)
CREATE myApp/src/tsconfig.app.json (194 bytes)
CREATE myApp/src/tsconfig.spec.json (282 bytes)
CREATE myApp/src/tslint.json (314 bytes)
CREATE myApp/src/app/app.module.ts (314 bytes)
CREATE myApp/src/app/app.component.html (1141 bytes)
CREATE myApp/src/app/app.component.spec.ts (993 bytes)
CREATE myApp/src/app/app.component.ts (207 bytes)
CREATE myApp/src/app/app.component.css (0 bytes)
CREATE myApp/e2e/protractor.conf.js (752 bytes)
CREATE myApp/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE myApp/e2e/src/app.po.ts (208 bytes)
CREATE myApp/e2e/tsconfig.e2e.json (213 bytes)
Package install failed, see above.
```

Before the last line printed, a dialog popped up and says `npm does not work when run with the Windows Scripting Host`.

* `ng serve` command failed.
```
$ ng serve --open
Could not find module "@angular-devkit/build-angular" from "D:\\myApp".
Error: Could not find module "@angular-devkit/build-angular" from "D:\\myApp".
    at Object.resolve (C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\@angular-devkit\core\node\resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect.js:132:40)
    at Observable.subscribe (C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:162:69)
    at DoOperator.call (C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\rxjs\internal\operators\tap.js:71:23)
    at Observable.subscribe (C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:159:22)
    at C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:129:14)
    at MergeMapSubscriber._next (C:\Users\my.user\AppData\Roaming\nvm\v8.11.1\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:112:18)
```

### Desired behavior
`ng new` command will run to the last and `ng server --open` command should be done normally and I will be able to see `app works!` on the page by browser.

### Mention any other details that might be useful (optional)
Windows10 (1703), 64bit

I found the same error when I tried to run `npm install` command via command prompt, but that don't reproduce when I use git-bash.

Did I miss any setting to avoid using WSH to run npm?

**Comment by filipesilva** [comment]
Heya, can you try running `npm install` inside your project?

I don't know what the `npm does not work when run with the Windows Scripting Host.` message means, it's the first time I see it.

**Comment by moriyas1984** [comment]
@filipesilva, I tried `npm install @angular/cli`  in a new project and run `ng new myApp`, but the same error reproduced.

I googled it and found that npm.js (executable of npm commands?) seems to be made as to return this error when it is called by WSH. See line 2 to 11 in `C:\Program Files\nodejs\node_modules\npm\lib\npm.js`.

I don't know well about WSH, so I might be misunderstanding...

**Comment by moriyas1984** [comment]
I tested some commands to investigate this error.

I added a VBS file in my project.
```
$ pwd
/d/myApp

$ cat ./testWSH.vbs
Wscript.Echo("Wscript executed!")

$ cat package.json |grep "scripts" -A 1
  "scripts": {
    "wshtest": "testWSH.vbs",

$ npm run wshtest

> mean-web-app@0.0.0 wshtest D:\meanWebApp
> testWSH.vbs
```
Then, the following dialog popped up.
![image](https://user-images.githubusercontent.com/18719417/40399082-603e170e-5e76-11e8-81f6-a6846c9c0f8b.png)

```
$ ./testWSH.vbs
./testWSH.vbs: line 1: Wscript.Echo: command not found
```
It seems to show that my git-bash is not called from WSH.

```
$ node ./testWSH.vbs D:\meanWebApp\testWSH.vbs:1
(function (exports, require, module, __filename, __dirname) { Wscript.Echo("Wscript executed!")
                                                              ^

ReferenceError: Wscript is not defined
    at Object.<anonymous> (D:\meanWebApp\testWSH.vbs:1:63)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

From this result, I think my npm setting includes something to use WSH.
I will try to identify the cause.

Regards.

**Comment by filipesilva** [comment]
I don't really know anything about WSH myself, but that running `npm install` standalone gives you that error points at some system level thing. I am on win10 using both git bash and the default command prompt and never have seen that warning.

For this reason I think you have some non-default setup. 

Can you try putting the full output of `npm install` in the new project directory here? Maybe there's some hint on the logs.

**Comment by moriyas1984** [comment]
```
$ pwd
/d

$ mkdir angulartest

$ cd angulartest/

$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (angulartest)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to D:\angulartest\package.json:

{
  "name": "angulartest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes)


$ npm install @angular/cli

> @angular/cli@6.0.3 postinstall D:\angulartest\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN angulartest@1.0.0 No description
npm WARN angulartest@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@6.0.3
added 246 packages in 33.189s

$ ng new angularapp
CREATE angularapp/angular.json (3436 bytes)
CREATE angularapp/package.json (1314 bytes)
CREATE angularapp/README.md (1027 bytes)
CREATE angularapp/tsconfig.json (384 bytes)
CREATE angularapp/tslint.json (2805 bytes)
CREATE angularapp/.editorconfig (245 bytes)
CREATE angularapp/.gitignore (503 bytes)
CREATE angularapp/src/environments/environment.prod.ts (51 bytes)
CREATE angularapp/src/environments/environment.ts (631 bytes)
CREATE angularapp/src/favicon.ico (5430 bytes)
CREATE angularapp/src/index.html (297 bytes)
CREATE angularapp/src/main.ts (370 bytes)
CREATE angularapp/src/polyfills.ts (3194 bytes)
CREATE angularapp/src/test.ts (642 bytes)
CREATE angularapp/src/assets/.gitkeep (0 bytes)
CREATE angularapp/src/styles.css (80 bytes)
CREATE angularapp/src/browserslist (375 bytes)
CREATE angularapp/src/karma.conf.js (964 bytes)
CREATE angularapp/src/tsconfig.app.json (194 bytes)
CREATE angularapp/src/tsconfig.spec.json (282 bytes)
CREATE angularapp/src/tslint.json (314 bytes)
CREATE angularapp/src/app/app.module.ts (314 bytes)
CREATE angularapp/src/app/app.component.html (1141 bytes)
CREATE angularapp/src/app/app.component.spec.ts (993 bytes)
CREATE angularapp/src/app/app.component.ts (207 bytes)
CREATE angularapp/src/app/app.component.css (0 bytes)
CREATE angularapp/e2e/protractor.conf.js (752 bytes)
CREATE angularapp/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE angularapp/e2e/src/app.po.ts (208 bytes)
CREATE angularapp/e2e/tsconfig.e2e.json (213 bytes)

// The error dialog same as  I posted popped.

Package install failed, see above.
```

I installed node and npm via nvm.
```
$ nvm --version

Running version 1.1.6.
```

Thanks.

**Comment by filipesilva** [comment]
I'm on the same `nvm` version myself as well.

I shouldn't mention that `@angular/cli` should be installed globally though. I don't know if that's related but and it looks like it was at some point, but thought I should mention it.

To be extra sure, can you follow these exact steps and give me the exact log?

```
# delete angulartest
npm install -g @angular/cli
ng new angulartest2 # just to be sure
# it should fail with that message
cd angulartest2
npm install # I guess it should fail too?
```

**Comment by moriyas1984** [comment]
@filipesilva, 

```
 $ rm -rf angulartest/

$ npm install -g @angular/cli
C:\Program Files\nodejs\ng -> C:\Program Files\nodejs\node_modules\@angular\cli\bin\ng

> @angular/cli@6.0.3 postinstall C:\Program Files\nodejs\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@6.0.3
added 246 packages in 34.53s

$ ng new angulartest2
CREATE angulartest2/angular.json (3452 bytes)
CREATE angulartest2/package.json (1316 bytes)
CREATE angulartest2/README.md (1029 bytes)
CREATE angulartest2/tsconfig.json (384 bytes)
CREATE angulartest2/tslint.json (2805 bytes)
CREATE angulartest2/.editorconfig (245 bytes)
CREATE angulartest2/.gitignore (503 bytes)
CREATE angulartest2/src/environments/environment.prod.ts (51 bytes)
CREATE angulartest2/src/environments/environment.ts (631 bytes)
CREATE angulartest2/src/favicon.ico (5430 bytes)
CREATE angulartest2/src/index.html (299 bytes)
CREATE angulartest2/src/main.ts (370 bytes)
CREATE angulartest2/src/polyfills.ts (3194 bytes)
CREATE angulartest2/src/test.ts (642 bytes)
CREATE angulartest2/src/assets/.gitkeep (0 bytes)
CREATE angulartest2/src/styles.css (80 bytes)
CREATE angulartest2/src/browserslist (375 bytes)
CREATE angulartest2/src/karma.conf.js (964 bytes)
CREATE angulartest2/src/tsconfig.app.json (194 bytes)
CREATE angulartest2/src/tsconfig.spec.json (282 bytes)
CREATE angulartest2/src/tslint.json (314 bytes)
CREATE angulartest2/src/app/app.module.ts (314 bytes)
CREATE angulartest2/src/app/app.component.html (1141 bytes)
CREATE angulartest2/src/app/app.component.spec.ts (995 bytes)
CREATE angulartest2/src/app/app.component.ts (207 bytes)
CREATE angulartest2/src/app/app.component.css (0 bytes)
CREATE angulartest2/e2e/protractor.conf.js (752 bytes)
CREATE angulartest2/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE angulartest2/e2e/src/app.po.ts (208 bytes)
CREATE angulartest2/e2e/tsconfig.e2e.json (213 bytes)
Package install failed, see above.

// Same as before, error prompt popped up between `CREATE angulartest2/e2e/tsconfig.e2e.json (213 bytes)` and `Package install failed, see above.`
$ cd angulartest2/

$ npm install
npm WARN notice [SECURITY] ws has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=ws&version=1.1.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] parsejson has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=parsejson&version=0.0.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> node-sass@4.9.0 install D:\angulartest2\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\myname\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-x64-57_binding.node

> node-sass@4.9.0 postinstall D:\angulartest2\node_modules\node-sass
> node scripts/build.js

Binary found at D:\angulartest2\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine

> @angular/cli@6.0.3 postinstall D:\angulartest2\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1096 packages in 142.655s

$ ls
angular.json  node_modules/  package-lock.json  src/           tslint.json
e2e/          package.json   README.md          tsconfig.json
```

The angular project has been created until the middle same as before.

BTW, I started to develop a new project using Angular on Ubuntu on another PC. So I don't need to solve that problem quickly at this point.
But off course I'd appreciate if I could use Angular on Windows on my desktop because it is easy to test the project through browser, though...

Thanks.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
