### ISSUE TITLE
Schematic for @angular/material:material-table not being executed

### ISSUE THREAD

**Issue by amreshprasad** [angular/angular-cli#10991]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```
ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.3
Node: 9.11.1
OS: linux x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 6.1.0
@angular/cli: 1.5.3
@angular/material: 6.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.6.3
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.8.1
### Repro steps

* Step 1
ng new myproject
* Step 2
npm install --save @angular/material @angular/cdk; npm install --save @angular/animations; npm install --save hammer.js
in project directory
* Step 3
ng generate @angular/material:material-table --name=mytable

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```
ng generate @angular/material:material-table --name=mytable
Schematic "@angular/material:material-table" not found in collection "@schematics/angular".
Error: Schematic "@angular/material:material-table" not found in collection "@schematics/angular".
    at NodeModulesEngineHost.createSchematicDescription (/home/amresh/mattable/mytable/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:137:19)
    at SchematicEngine.createSchematic (/home/amresh/mattable/mytable/node_modules/@angular-devkit/schematics/src/engine/engine.js:108:40)
    at CollectionImpl.createSchematic (/home/amresh/mattable/mytable/node_modules/@angular-devkit/schematics/src/engine/collection.js:11:29)
    at Object.getSchematic (/home/amresh/mattable/mytable/node_modules/@angular/cli/utilities/schematics.js:45:23)
    at Class.run (/home/amresh/mattable/mytable/node_modules/@angular/cli/tasks/schematic-get-options.js:12:40)
    at Class.beforeRun (/home/amresh/mattable/mytable/node_modules/@angular/cli/commands/generate.js:90:31)
    at Promise.resolve.then (/home/amresh/mattable/mytable/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:138:24)
    at <anonymous>

**Comment by amreshprasad** [comment]
Repasting the stack trace as the output above seems off:
Schematic "@angular/material:material-table" not found in collection "@schematics/angular".
Error: Schematic "@angular/material:material-table" not found in collection "@schematics/angular".
    at NodeModulesEngineHost.createSchematicDescription (/home/amresh/mattable/mytable/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:137:19)
    at SchematicEngine.createSchematic (/home/amresh/mattable/mytable/node_modules/@angular-devkit/schematics/src/engine/engine.js:108:40)
    at CollectionImpl.createSchematic (/home/amresh/mattable/mytable/node_modules/@angular-devkit/schematics/src/engine/collection.js:11:29)
    at Object.getSchematic (/home/amresh/mattable/mytable/node_modules/@angular/cli/utilities/schematics.js:45:23)
    at Class.run (/home/amresh/mattable/mytable/node_modules/@angular/cli/tasks/schematic-get-options.js:12:40)
    at Class.beforeRun (/home/amresh/mattable/mytable/node_modules/@angular/cli/commands/generate.js:90:31)
    at Promise.resolve.then (/home/amresh/mattable/mytable/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:138:24)
    at <anonymous>
