### ISSUE TITLE
ng6 update, build fail on AOT, 1.5+ requirement not met but 6.0.3 installed

### ISSUE THREAD

**Issue by jkrth617** [angular/angular-cli#10998]
### Versions
Angular CLI: 6.0.3
Node: 10.2.0
OS: win32 x64
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, upgrade

Package                      Version
------------------------------------------------------
angular-devkit/architect    0.6.3
angular-devkit/core         0.6.3
angular-devkit/schematics   0.6.3
ngtools/webpack             1.10.2
schematics/angular          0.6.3
schematics/update           0.6.3
rxjs                         6.1.0
typescript                   2.7.2
webpack                      3.12.0

### Observed behavior

I am converting my Angular 5 application to angular 6.
I am not using angular cli to transpile my code, I am still using just webpack.
A normal webpack build works, but when I run an AOT build I get two errors: 
```

[1m[31mERROR in ./app/main/main.bootstrap.ts
Module not found: Error: Can't resolve './../../$$_gendir/app/main/main.module.ngfactory' in 'C:\Users\devs\sc\dev\Main\src\Main.Web\app\main'
resolve './../../$$_gendir/app/main/main.module.ngfactory' in 'C:\Users\devs\sc\dev\Main\src\Main.Web\app\main'
  using description file: C:\Users\devs\sc\dev\Main\src\Main.Web\package.json (relative path: ./app/main)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\devs\sc\dev\Main\src\Main.Web\package.json (relative path: ./app/main)
    using description file: C:\Users\devs\sc\dev\Main\src\Main.Web\package.json (relative path: ./$$_gendir/app/main/main.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory doesn't exist
      .webpack.js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.webpack.js doesn't exist
      .web.js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.web.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.tsx doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.json doesn't exist
      as directory
        C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory doesn't exist
[C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory]
[C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.webpack.js]
[C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.web.js]
[C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.ts]
[C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.tsx]
[C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.js]
[C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory.json]
[C:\Users\devs\sc\dev\Main\src\Main.Web\$$_gendir\app\main\main.module.ngfactory]
 @ ./app/main/main.bootstrap.ts 55:31-92[39m[22m

[1m[31mERROR in Error: Please update @angular/cli. Angular 5+ requires at least Angular CLI 1.5+
    at throwNotSupportedError (C:\Users\devs\sc\dev\Main\packages\compiler-cli\src\ngtools_api.ts:132:9)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\Users\devs\sc\dev\Main\packages\compiler-cli\src\ngtools_api.ts:80:11)
    at _donePromise.Promise.resolve.then (C:\Users\devs\sc\dev\Main\src\Main.Web\node_modules\@ngtools\webpack\src\plugin.js:428:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)[39m[22m

```

its my understanding the first error is a generic "something went wrong" error. The second error is the reason I am posting this. It is complaining that I need to upgrade my Angular CLI to something above 1.5 but I am using 6.0.3? 

thank you for any help!

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
