### ISSUE TITLE
ng lint --format stylish by default should apply to main app

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#11005]
### Versions
```

Angular CLI: 6.0.3
Node: 8.11.1
OS: darwin x64
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
    
```

### Repro steps

```
ng new my-dream-app
cd my-dream-app
ng lint --format stylish
```

### Observed behavior
```
▶ng lint --format stylish
Architect commands with multiple targets cannot specify overrides.'lint' would be run on the following projects: my-app,my-app-e2e
Error: Architect commands with multiple targets cannot specify overrides.'lint' would be run on the following projects: my-app,my-app-e2e
    at LintCommand.validate (/Users/papa/_play/my-app/node_modules/@angular/cli/models/architect-command.js:75:23)
    at /Users/papa/_play/my-app/node_modules/@angular/cli/models/command-runner.js:274:39
    at Generator.next (<anonymous>)
    at /Users/papa/_play/my-app/node_modules/@angular/cli/models/command-runner.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/papa/_play/my-app/node_modules/@angular/cli/models/command-runner.js:3:12)
    at validateAndRunCommand (/Users/papa/_play/my-app/node_modules/@angular/cli/models/command-runner.js:273:12)
    at Object.<anonymous> (/Users/papa/_play/my-app/node_modules/@angular/cli/models/command-runner.js:100:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/papa/_play/my-app/node_modules/@angular/cli/models/command-runner.js:4:58)
```

### Desired behavior

By default if no app is specified, it should cover the main app (not the e2e)

**Comment by mikesimmonds** [comment]
For any less-experienced developers like myself coming across this issue:
When passing flags to `ng lint` (eg --fix) you must include the name of the project (found in package.json).
Example:
`ng lint --fix` [doesn't work]
`ng lint app-name --fix` [does work]

**Comment by alan-agius4** [comment]
Fixed via https://github.com/angular/angular-cli/commit/5571d094e5db4062c551fb2a98758c26392ffb43
