### ISSUE TITLE
Module resolution fails with build optimizer and source maps

### ISSUE THREAD

**Issue by tsvetomir** [angular/angular-cli#11055]
### Versions
```
Angular CLI: 6.0.5
Node: 8.11.1
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        0.6.5
@angular/cli                      6.0.5
@ngtools/webpack                  6.0.5
@schematics/angular               0.6.5
@schematics/update                0.6.5
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
* Clone the [sample repo](https://github.com/tsvetomir/ng-build-optimizer-side-effects)
    `git clone https://github.com/tsvetomir/ng-build-optimizer-side-effects.git`
* Run the application in production mode
    `cd ng-build-optimizer-side-effects && npm install`
    `ng serve --prod`

### Observed behavior
Consider the following modules:

`foo/bar.ts`

```ts
export class Bar {
  static baz(): void {}
}
```

`foo/baz.ts`

```ts
import { Bar } from './bar';

Bar.baz = function() {
  alert('Hello');
}
```

`app.component.ts`

```ts
import { Bar } from './foo/bar';
import './foo/baz';

const bar = Bar.baz();
```

When the build optimizer is enabled, the code results in an error - `Bar is not defined`.
Turning either the build optimizer _or_ source maps off resolves the issue.

### Desired behavior
The build optimizer should not have no effect on module imports, even if they contain side-effects.

### Mention any other details that might be useful (optional)
For a "real world" test case, see telerik/kendo-angular#1542

**Comment by marvec** [comment]
I can see the same issue with another library. npm 6.3.0 and @angular/cli 6.1.2 does not work either. Switching buildOptimizer to false, or sourceMaps to false fixes the issue:

```ERROR in ./node_modules/plotly.js/src/lib/polygon.js
Module build failed: Error: Debug Failure. False expression.
    at getJSDocTags (/home/.../node_modules/typescript/lib/typescript.js:13197:22)
    at getFirstJSDocTag (/home/.../node_modules/typescript/lib/typescript.js:13205:24)
    at Object.getJSDocType (/home/.../node_modules/typescript/lib/typescript.js:13173:19)
    at getContextualSignature (/home/.../node_modules/typescript/lib/typescript.js:41002:32)
    at checkFunctionExpressionOrObjectLiteralMethod (/home/.../node_modules/typescript/lib/typescript.js:44621:43)
    at checkExpressionWorker (/home/.../node_modules/typescript/lib/typescript.js:45681:28)
    at checkExpression (/home/.../node_modules/typescript/lib/typescript.js:45609:42)
    at checkBinaryLikeExpression (/home/.../node_modules/typescript/lib/typescript.js:45155:29)
    at checkBinaryExpression (/home/.../node_modules/typescript/lib/typescript.js:45147:20)
    at checkExpressionWorker (/home/.../node_modules/typescript/lib/typescript.js:45702:28)
    at checkExpression (/home/.../node_modules/typescript/lib/typescript.js:45609:42)
    at checkExpressionCached (/home/.../node_modules/typescript/lib/typescript.js:45457:38)
    at getTypeOfExpression (/home/.../node_modules/typescript/lib/typescript.js:45577:28)
    at checkDeclarationInitializer (/home/.../node_modules/typescript/lib/typescript.js:45469:24)
    at getTypeForVariableLikeDeclaration (/home/.../node_modules/typescript/lib/typescript.js:30738:28)
    at getWidenedTypeForVariableLikeDeclaration (/home/.../node_modules/typescript/lib/typescript.js:30961:24)
```

**Comment by alan-agius4** [comment]
Hi I tried to reproduce this with the re-production you provided and I was unable 
```
ng serve --prod
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-10-11T13:58:31.546Z
Hash: 198bda085430504b3651
Time: 16404ms
chunk {0} runtime.a66f828dca56eeb90e02.js, runtime.a66f828dca56eeb90e02.js.map (runtime) 1.11 kB [entry] [rendered]
chunk {1} styles.373a13d9a601d72037d3.css, styles.373a13d9a601d72037d3.css.map (styles) 59 bytes [initial] [rendered]
chunk {2} polyfills.aaaa3d67336bdf0f962a.js, polyfills.aaaa3d67336bdf0f962a.js.map (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.61fbc168e084286f2621.js, main.61fbc168e084286f2621.js.map (main) 314 kB [initial] [rendered]
i ｢wdm｣: Compiled successfully.
```
![image](https://user-images.githubusercontent.com/17563226/46809477-d812af80-cd6e-11e8-8078-9cf5fb3cbc4a.png)


If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
