### ISSUE TITLE
Problem with creating translation for Angular project

### ISSUE THREAD

**Issue by AntonAleksandrov13** [angular/angular-cli#11092]
### Versions
```
Angular CLI: 1.7.2
Node: 10.1.0
OS: darwin x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.2
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

MacOS Sierra 10.12.6
```

### Repro steps

* Run ```ng xi18n --outputPath src/locale```
* Create file messages.ru.xml
* Copy-paste contents from message.xml to messages.ru.xml
* Add target tags with translations
* Run ```ng build --aot --output-path dist/ru --base-href /ru/ --locale ru --i18n-format xlf --i18n-file src/locale/messages.ru.xlf --missing-translation error```

### Observed behavior
```
ERROR in TypeError: Cannot read property 'start' of null
    at XliffParser.visitElement (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:11919:96)
    at Element.visit (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2333:50)
    at visit (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2369:37)
    at /Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2371:42
    at Array.forEach (<anonymous>)
    at visitAll (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2370:11)
    at XliffParser.visitElement (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:11903:25)
    at Element.visit (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2333:50)
    at visit (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2369:37)
    at /Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2371:42
    at Array.forEach (<anonymous>)
    at visitAll (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2370:11)
    at XliffParser.visitElement (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:11934:17)
    at Element.visit (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2333:50)
    at visit (/Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2369:37)
    at /Users/anton/Projects/ecofarm/node_modules/@angular/compiler/bundles/compiler.umd.js:2371:42
```

### Desired behavior
Should build ru version of the web app to the dist folder.

### Mention any other details that might be useful (optional)
Seems like internal error is occurring. It was working perfectly fine couple commits ago (if I revert back to previous translation file, it works fine)

**Comment by AntonAleksandrov13** [comment]
Okay, so it took me five minutes to figure out what could give me mentioned above issue.
In the website, I have div with following text: "Limited liability company "OGUMĀJAS".
i18n probably goes crazy if unusual letters occur in message.xml such as "Ā". I just had to remove translation tag there and voala it works.
