### ISSUE TITLE
Cannot provide any options to ng lint command without specified project

### ISSUE THREAD

**Issue by Neonox31** [angular/angular-cli#11108]
### Versions
```
Angular CLI: 6.0.7
Node: 8.11.2
OS: linux x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.7
@angular-devkit/build-angular      0.6.7
@angular-devkit/build-ng-packagr   0.6.7
@angular-devkit/build-optimizer    0.6.7
@angular-devkit/core               0.6.7
@angular-devkit/schematics         0.6.7
@angular/cli                       6.0.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.7
@schematics/angular                0.6.7
@schematics/update                 0.6.7
ng-packagr                         3.0.1
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
```

### Repro steps
* `ng new foo`
* `cd foo`
* `ng generate lib bar`
* `ng lint --type-check`

### Observed behavior
```
Architect commands with multiple targets cannot specify overrides.'lint' would be run on the following projects: foo,foo-e2e,bar
Error: Architect commands with multiple targets cannot specify overrides.'lint' would be run on the following projects: foo,foo-e2e,bar
    at LintCommand.validate (/tmp/foo/node_modules/@angular/cli/models/architect-command.js:75:23)
    at /tmp/foo/node_modules/@angular/cli/models/command-runner.js:274:39
    at Generator.next (<anonymous>)
    at /tmp/foo/node_modules/@angular/cli/models/command-runner.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/tmp/foo/node_modules/@angular/cli/models/command-runner.js:3:12)
    at validateAndRunCommand (/tmp/foo/node_modules/@angular/cli/models/command-runner.js:273:12)
    at Object.<anonymous> (/tmp/foo/node_modules/@angular/cli/models/command-runner.js:100:26)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/foo/node_modules/@angular/cli/models/command-runner.js:4:58)
```

### Desired behavior
I guess options like `--type-check` should work with no specified project int the `ng lint` command and should apply to all projects.

FYI, the `ng lint` command without specified options and project works with following output :
```
All files pass linting.


All files pass linting.


All files pass linting.
```

/cc @davinkevin

**Comment by filipesilva** [comment]
The current error is by design. Perhaps we should consider changing this behaviour.

But I should highlight that you can set `"typeCheck": true` in the individual lint configs.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
