### ISSUE TITLE
ng command breaks with wrong option names. 

### ISSUE THREAD

**Issue by cRAN-cg** [angular/angular-cli#11186]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
```

### Versions

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: local (v6.1.0-beta.0, branch: issue)
Node: 8.11.2
OS: linux x64
Angular: 6.0.2
... animations, cdk, common, compiler, compiler-cli, core, http
... material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                      Version
------------------------------------------------------
@angular-devkit/architect    <error>
@angular-devkit/core         <error>
@angular-devkit/schematics   <error>
@ngtools/json-schema         1.1.0
@schematics/angular          <error>
@schematics/update           <error>
ng-packagr                   3.0.1
rxjs                         6.0.0
typescript                   2.7.2
webpack                      4.11.1
node Version : v8.11.2
npm version : 6.1.0
```

### Repro steps

```
ng --verion
```
```
The option name should start with a -- or - ; command works perfectly otherwise
```
### The log given by the failure
```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at levenshtein (/home/cran-cg/projects/angular-cli/packages/angular/cli/models/command-runner.ts:30:11)
    at listAllCommandNames.sort (/home/cran-cg/projects/angular-cli/packages/angular/cli/models/command-runner.ts:73:43)
    at Array.sort (native)
    at Object.<anonymous> (/home/cran-cg/projects/angular-cli/packages/angular/cli/models/command-runner.ts:71:65)
    at Generator.next (<anonymous>)
    at /home/cran-cg/projects/angular-cli/packages/angular/cli/models/command-runner.ts:14:71
    at new Promise (<anonymous>)
    at __awaiter (/home/cran-cg/projects/angular-cli/packages/angular/cli/models/command-runner.ts:10:12)
    at Object.runCommand (/home/cran-cg/projects/angular-cli/packages/angular/cli/models/command-runner.ts:46:12)
    at /home/cran-cg/projects/angular-cli/packages/angular/cli/lib/cli/index.ts:67:58
```

### Desired functionality

```
The specified command ("verion") is invalid. For a list of available options,
run "ng help".

Did you mean "version"?
```

**Comment by cRAN-cg** [comment]
I have made a PR, please help me merge it :))
