### ISSUE TITLE
ng update @angular/cli error

### ISSUE THREAD

**Issue by lazebird** [angular/angular-cli#11189]
debian:~/projects/myapp# rm -rf node_modules dist 
debian:~/projects/myapp# cnpm uninstall --save-dev angular-cli
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump

> node-sass@4.9.0 install /root/projects/myapp/node_modules/node-sass
> node scripts/install.js

Cached binary found at /root/.npm/node-sass/4.9.0/linux-ia32-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /root/projects/myapp/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.9.0 postinstall /root/projects/myapp/node_modules/node-sass
> node scripts/build.js

Binary found at /root/projects/myapp/node_modules/node-sass/vendor/linux-ia32-57/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})

added 1182 packages from 1146 contributors in 43.208s
debian:~/projects/myapp# cnpm install --save-dev @angular/cli@latest
⠼ [0/1] Installing json-schema-traverse@^0.3.0platform unsupported @angular/cli@6.0.8 › @angular-devkit/core@0.6.8 › chokidar@2.0.3 › fsevents@^1.1.2 Package require os(darwin) not compatible with your platform(linux)
[fsevents@^1.1.2] optional install error: Package require os(darwin) not compatible with your platform(linux)
✔ Installed 1 packages
✔ Linked 202 latest versions

================================================================================
The Angular CLI configuration format has been changed, and your existing configuration can
be updated automatically by running the following command:

  ng update @angular/cli
================================================================================

✔ Run 1 scripts
Recently updated (since 2018-06-03): 7 packages (detail see file /root/projects/myapp/node_modules/.recently_updates.txt)
✔ All packages installed (226 packages installed from npm registry, used 5s, speed 556.83kB/s, json 203(2.6MB), tarball 0B)
debian:~/projects/myapp#   ng update @angular/cli
schematics_1.HostSink is not a constructor
TypeError: schematics_1.HostSink is not a constructor
    at NodeWorkflow.execute (/root/projects/myapp/node_modules/_@angular-devkit_schematics@0.6.8@@angular-devkit/schematics/tools/workflow/node-workflow.js:75:24)
    at Promise (/root/projects/myapp/node_modules/_@angular_cli@6.0.8@@angular/cli/models/schematic-command.js:140:22)
    at new Promise (<anonymous>)
    at UpdateCommand.runSchematic (/root/projects/myapp/node_modules/_@angular_cli@6.0.8@@angular/cli/models/schematic-command.js:139:16)
    at UpdateCommand.<anonymous> (/root/projects/myapp/node_modules/_@angular_cli@6.0.8@@angular/cli/commands/update.js:70:25)
    at Generator.next (<anonymous>)
    at /root/projects/myapp/node_modules/_@angular_cli@6.0.8@@angular/cli/commands/update.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/projects/myapp/node_modules/_@angular_cli@6.0.8@@angular/cli/commands/update.js:3:12)
    at UpdateCommand.run (/root/projects/myapp/node_modules/_@angular_cli@6.0.8@@angular/cli/commands/update.js:69:16)
debian:~/projects/myapp# 
debian:~/projects/myapp# 
debian:~/projects/myapp# node --version
v8.11.2
debian:~/projects/myapp# npm --version
cnpm@6.0.0 (/usr/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.1.0 (/usr/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@8.11.2 (/usr/local/bin/node)
npminstall@3.7.0 (/usr/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local 
linux ia32 4.9.0-6-686-pae 
registry=https://registry.npm.taobao.org
debian:~/projects/myapp#

**Comment by dpkatre123** [comment]
I checked out Angular5 source code on new machine where latest version of npm installed (6.1.0).
old version was 5.1.0
i am geting same error on executing NPM install
any solution available.?
