### ISSUE TITLE
Upgrading the beta 6: Registry returned 404 for GET on https://registry.npmjs.org/angular-cli-inject-live-reload

### ISSUE THREAD

**Issue by sharpmachine** [angular/angular-cli#1122]
Went through the steps to upgrade from beta 5 to 6. When going through the `ng init` step, I removed the `ember-cli-inject-live-reload` from package.json and replaced it with `"angular-cli-inject-live-reload": "1.4.0"`, as suggested, and also updated my `index.html` to:

```
  {{#unless environment.production}}
  <script src="/angular-cli-live-reload.js"
      type="text/javascript"></script>
  {{/unless}}
```

But when the cli installs all the tooling, it fails with:
`Registry returned 404 for GET on https://registry.npmjs.org/angular-cli-inject-live-reload`

OSX El Capitan 
angular-cli: 1.0.0-beta.6
node: 5.11.1
os: darwin x64

**Comment by nosachamos** [comment]
Interestingly, I'm on alpha 6 and  `ng new` will install `ember-cli-inject-live-reload`, not `angular-cli-inject-live-reload`. It may be that if you just undo this particular change, you'll be fine.

**Comment by sharpmachine** [comment]
@nosachamos. I'm on beta 6....not alpha. It was release a few days ago. I tried that but now when I run `ng-serve` I get:

```
Could not require 'angular-cli-build.js': Unexpected string
SyntaxError: Could not require 'angular-cli-build.js': Unexpected string
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/jessekuntz/Projects/NSG.CMS/NSG.CMS.Client.Web/node_modules/angular-cli/node_modules/angular-cli/lib/utilities/find-build-file.js:21:17)
    at patchedFindBuildFile (/Users/jessekuntz/Projects/NSG.CMS/NSG.CMS.Client.Web/node_modules/angular-cli/lib/cli/index.js:53:42)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/jessekuntz/Projects/NSG.CMS/NSG.CMS.Client.Web/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:49:21)
```
I hope someone on the Angular CLI team gets back to me soon kuz I can't do any work until I fix this.

**Comment by nosachamos** [comment]
Ops, I meant beta 6.

Well, that sucks. I suspect doing a `ng new` and then porting your project to a brand new shell is not an option, right? It's a bit of work, but if you're blocked it's hard to imagine that'd be worst.

**Comment by sharpmachine** [comment]
That's a LOT of work...the issue is that there is no angular-cli-inject-live-reload package in NPM. It doesn't exist. So the only think I can do is try to roll back to beta.5 until someone from the team gets back to me. Usually they respond quickly but they must be on vacation or something.

**Comment by sharpmachine** [comment]
It's weird because if I generate a new project, it uses the ember-cli-livereload.

**Comment by sharpmachine** [comment]
```
? Overwrite src/index.html? Diff
Index: /Users/jessekuntz/Projects/NSG.CMS/NSG.CMS.Client.Web/src/index.html
===================================================================
--- /Users/jessekuntz/Projects/NSG.CMS/NSG.CMS.Client.Web/src/index.html
+++ /Users/jessekuntz/Projects/NSG.CMS/NSG.CMS.Client.Web/src/index.html
@@ -1,70 +1,31 @@
 <!doctype html>
 <html>
-
 <head>
   <meta charset="utf-8">
-  <title>Noble Case Manager</title>
-  <base href="/"> {{#unless environment.production}}
-  <script src="/angular-cli-live-reload.js"
-      type="text/javascript"></script>
+  <title>CaseManager</title>
+  <base href="/">
+
+  {{#unless environment.production}}
+  <script src="/angular-cli-live-reload.js" type="text/javascript"></script>
   {{/unless}}
-  <meta name="viewport"
-      content="width=device-width, initial-scale=1">
-
-  <link rel="stylesheet"
-      type="text/css"
-      href="//cloud.typography.com/7268774/732568/css/fonts.css" />
-
-  <link rel="stylesheet"
-      href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
-
-  <link rel="stylesheet"
-      href="../public/assets/stylesheets/application.css">
-
+  <meta name="viewport" content="width=device-width, initial-scale=1">
+  <link rel="icon" type="image/x-icon" href="favicon.ico">
 </head>
-
 <body>
-  <case-manager-app class="hidden-xs">
-    <div class="prebootstrap center-block text-center">
-      <img src="assets/images/login-logo-blue.svg"
-          alt="Noble Logo"
-          width="215px"
-          height="100%">
-      <i class="fa fa-circle-o-notch fa-spin fa-5x fa-fw"></i>
-      <span class="sr-only">Loading...</span>
-    </div>
-    <p class="prebootstrap-email">Stuck on this screen?
-      <a href="mailto:support@noblesg.com"
-          class="btn btn-sm btn-inverse btn-inverse-primary">Contact Noble Support</a>
-    </p>
-  </case-manager-app>
+  <app-root>Loading...</app-root>

-  <div class="visible-xs-block hidden-print text-center">
-    <div class="container">
-      <img src="assets/images/login-logo-blue.svg"
-          alt="Noble Logo"
-          width="215px"
-          height="100%"
-          class="center-block login-logo">
-      <h1>Not available on smartphones</h1>
-      <p class="lead">Please use either a desktop/laptop computer or a tablet</p>
-    </div>
-  </div>
+

+    {{#each scripts.polyfills}}
+    <script src="{{.}}"></script>
+    {{/each}}
+    <script>
+      System.import('system-config.js').then(function () {
+        System.import('main');
+      }).catch(console.error.bind(console));
+    </script>

-  {{#each scripts.polyfills}}
-  <script src="{{.}}"></script>
-  {{/each}}
-  <script>
-    var apiHostUrl = '{{environment.apiHostUrl}}';
+

-    System.import('system-config.js').then(function() {
-      System.import('main');
-    }).catch(console.error.bind(console));
-  </script>
-
-  <script src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
-
 </body>
-
 </html>
```

**Comment by Splaktar** [comment]
@sharpmachine It needs to be `ember-cli-inject-live-reload`. As stated by @nosachamos, there is no `angular-cli-inject-live-reload`.

> I removed the ember-cli-inject-live-reload from package.json and replaced it with "angular-cli-inject-live-reload": "1.4.0", as suggested

This is not suggested by the docs. You are saying that the diff suggested it and/or the overwrite suggested it? I just did the upgrade and I'm not seeing that behavior on OS X.

**Comment by sharpmachine** [comment]
@Splaktar 

Yes, I'm saying that the diff suggested it. I copied/pasted the output from the `ng init` step of the upgrade. Angular CLI wanted to replace ember-cli-live-reload with angular-cli-live-reload in the package.json and index.html. This was on a current project, not a new one.

**Comment by filipesilva** [comment]
Ugh, this is an unintended side effect of a filter we put in to remove `ember-cli` branding from leaking. There is no `angular-cli-inject-live-reload`, it should be `ember-cli-inject-live-reload` instead.
