### ISSUE TITLE
Error using `ng config cli.packageManager yarn`

### ISSUE THREAD

**Issue by rr20eid10** [angular/angular-cli#11248]
### Bug Report or Feature Request (mark with an `x`)
```X
```
X Feature request #10558

### Versions

NPM:  6.1.0
Angular CLI: 6.0.8
Node: 10.4.0
OS: darwin x64 High Sierra
Yarn: 1.7.0

### Repro steps

**Use Yarn instead of NPM**
Run:
`ng set --global packageManager=yarn`

_Log message returned:_
`get/set have been deprecated in favor of the config command.`

_Run:_
`ng config cli.packageManager yarn`

_Returns the following error:_
`Cannot read property 'value' of null
TypeError: Cannot read property 'value' of null
    at ConfigCommand.set (/usr/local/lib/node_modules/@angular/cli/commands/config.js:207:36)
    at ConfigCommand.run (/usr/local/lib/node_modules/@angular/cli/commands/config.js:181:18)
    at /usr/local/lib/node_modules/@angular/cli/models/command-runner.js:278:30
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@angular/cli/models/command-runner.js:4:58)`

### The log given by the failure

`Cannot read property 'value' of null
TypeError: Cannot read property 'value' of null
    at ConfigCommand.set (/usr/local/lib/node_modules/@angular/cli/commands/config.js:207:36)
    at ConfigCommand.run (/usr/local/lib/node_modules/@angular/cli/commands/config.js:181:18)
    at /usr/local/lib/node_modules/@angular/cli/models/command-runner.js:278:30
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@angular/cli/models/command-runner.js:4:58)`

### Desired functionality

I'm new to using Yarn.  I usually use npm but my team uses yarn instead of NPM, so I need to configure this change. I don't know if this is a bug or something else is wrong based on the error message.

### Mention any other details that might be useful

I found this feature update, but I don't know if anyone else has experienced the issue I am having.
[Issue #10558
](https://github.com/angular/angular-cli/issues/10558)

**Comment by percygolding** [comment]
Just to add to the issue, I am experience the same identical error when attempting to change the packageManager to yarn. 

Versions:
Angular CLI: 6.0.8
Node: 10.4.1
npm: 6.0.8
yarn: 1.7.0

`PS C:\Windows\system32> ng config cli.packageManager yarn`

`Cannot read property 'value' of null
TypeError: Cannot read property 'value' of null
    at ConfigCommand.set (C:\Users\Redirection\goldip2\AppData\npm\node_modules\@angular\cli\commands\config.js:207:36)
    at ConfigCommand.run (C:\Users\Redirection\goldip2\AppData\npm\node_modules\@angular\cli\commands\config.js:181:18)
    at C:\Users\Redirection\goldip2\AppData\npm\node_modules\@angular\cli\models\command-runner.js:278:30
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Redirection\goldip2\AppData\npm\node_modules\@angular\cli\models\command-runner.js:4:58)`

**Comment by clydin** [comment]
Try `ng config --global cli.packageManager yarn`.

Unfortunately, the error message is currently not very useful and error messages in general are in the process of being improved.

**Comment by DanielRuf** [comment]
This does not work with the latest cli.

**Comment by LennrtV** [comment]
This didn’t work with Angular CLI 6.2.1

~ ng config -g cli.packageManager yarn
This command can only be run inside of a CLI project.

**Comment by wibimaster** [comment]
Confirm that, have to create a junk project (ng new junk), let it fails because no NPM, go into "junk" folder newly created, type "ng config -g cli.packageManager yarn", go to parent folder, delete "junk" folder, and now I can use "ng new myProjet" with yarn. Bad.
