### ISSUE TITLE
local schema

### ISSUE THREAD

**Issue by mina-skunk** [angular/angular-cli#11307]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Versions
node --version v8.11.1
npm --version 6.1.0

### Repro steps
    {
      "$schema": "http://json-schema.org/draft-06/schema",
      "title": "My builder schema",
      "type": "object",
      "allOf": [
        {
          "$ref": "file://../../node_modules/@angular-devkit/build-angular/src/browser/schema.json#"
        }
      ],
      "properties": {
        "myProp": {
          "type": "object"
        }
      },
      "additionalProperties": false
    }

or

    {
      "$schema": "http://json-schema.org/draft-06/schema",
      "title": "My builder schema",
      "type": "object",
      "allOf": [
        {
          "$ref": "../../node_modules/@angular-devkit/build-angular/src/browser/schema.json#"
        }
      ],
      "properties": {
        "myProp": {
          "type": "object"
        }
      },
      "additionalProperties": false
    }

### The log given by the failure
> Protocol "file:" not supported. Expected "http:"
Error: Protocol "file:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:131:11)
    at request (http.js:38:10)
    at Object.get (http.js:42:13)
    at Promise (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\src\json\schema\registry.js:74:18)
    at new Promise (<anonymous>)
    at CoreSchemaRegistry._fetch (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\src\json\schema\registry.js:73:16)
    at Object.loadSchema (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\src\json\schema\registry.js:61:39)
    at loadMissingSchema (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\node_modules\ajv\lib\compile\async.js:67:64)
    at _compileAsync (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\node_modules\ajv\lib\compile\async.js:56:48)
    at C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\node_modules\ajv\lib\compile\async.js:32:34

or

> Unable to determine the domain name
Error: Unable to determine the domain name
    at new ClientRequest (_http_client.js:85:13)
    at request (http.js:38:10)
    at Object.get (http.js:42:13)
    at Promise (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\src\json\schema\registry.js:74:18)
    at new Promise (<anonymous>)
    at CoreSchemaRegistry._fetch (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\src\json\schema\registry.js:73:16)
    at Object.loadSchema (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\src\json\schema\registry.js:61:39)
    at loadMissingSchema (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\node_modules\ajv\lib\compile\async.js:67:64)
    at _compileAsync (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\node_modules\ajv\lib\compile\async.js:56:48)
    at C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\node_modules\ajv\lib\compile\async.js:32:34

### Desired functionality
`$ref` relative schemas

**Comment by gatimus** [comment]
With out `file://` you get:

> Unable to determine the domain name
Error: Unable to determine the domain name
    at new ClientRequest (_http_client.js:85:13)
    at request (http.js:38:10)
    at Object.get (http.js:42:13)
    at Promise (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\src\json\schema\registry.js:74:18)
    at new Promise (<anonymous>)
    at CoreSchemaRegistry._fetch (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\src\json\schema\registry.js:73:16)
    at Object.loadSchema (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\src\json\schema\registry.js:61:39)
    at loadMissingSchema (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\node_modules\ajv\lib\compile\async.js:67:64)
    at _compileAsync (C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\node_modules\ajv\lib\compile\async.js:56:48)
    at C:\Users\User\source\repos\AutoFluent-Cloud\autofluent-clients\node_modules\@angular-devkit\core\node_modules\ajv\lib\compile\async.js:32:34

**Comment by gatimus** [comment]
@clydin please reopen as it is still not possible to use relative schema references.

**Comment by gmullerb** [comment]
The current implementation only use http for asynchronous schema compilation using the `loadSchema` option of `ajv`, then we are only able to reference schemas using _http_ (for which there no really extended usefullness, most schema json on the web are available using https), **neither https nor a local file are available**, 
```
       this._ajv = ajv({
            formats: formatsObj,
            loadSchema: (uri) => this._fetch(uri),
            schemaId: 'auto',
            passContext: true,
        });
```
The implementation of the `_fetch` in `registry.js` **should allow to handle `file://`(possibly simply using the `path` module + a `require()`), `http://` (with the `http` module, already implemented), `https://` (with the `https` module)**. This way there will be freedom of choice when build schemas

**Comment by nickbullock** [comment]
Any news?

**Comment by matheo** [comment]
wow, the extension of schemas is quite a big deal and it's just not a priority :thinking:
