### ISSUE TITLE
ng e2e does not connect to dev server

### ISSUE THREAD

**Issue by jorgjanke** [angular/angular-cli#11324]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions

```
Angular CLI: 6.0.8
Node: 10.0.0
OS: darwin x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

npm --version
6.1.0
```
### Repro steps

when running ng e2e, I get
```
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2018-06-21T02:03:04.751Z
Hash: da3cb55e9747cf9cce88
Time: 8210ms
chunk {main} main.js, main.js.map (main) 190 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 226 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 514 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.72 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
[19:03:05] I/update - chromedriver: file exists /Users/jorg/Documents/ADev/p4d/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.40.zip
[19:03:05] I/update - chromedriver: unzipping chromedriver_2.40.zip
[19:03:05] I/update - chromedriver: setting permissions to 0755 for /Users/jorg/Documents/ADev/p4d/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.40
[19:03:05] I/update - chromedriver: chromedriver_2.40 up to date
(node:9514) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[19:03:05] I/launcher - Running 1 instances of WebDriver
[19:03:05] I/direct - Using ChromeDriver directly...
Jasmine started
[19:03:17] E/protractor - Could not find Angular on page http://localhost:4200/ : retries looking for angular exceeded

  p4d App Header
    ✗ should display p4d select
      - Failed: Angular could not be found on the page http://localhost:4200/. If this is not an Angular application, you may need to turn off waiting for Angular.
                                Please see ..
```
The browser window (Chrome is being controlled ...) is empty.
Nevertheless, when I request http://localhost:4200/  in a different browser, I get the apps

### The log given by the failure

                                https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
                                Please see 
                                https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
          at executeAsyncScript_.then (/Users/jorg/Documents/ADev/p4d/node_modules/protractor/built/browser.js:720:27)
          at ManagedPromise.invokeCallback_ (/Users/jorg/Documents/ADev/p4d/node_modules/selenium-webdriver/lib/promise.js:1376:14)
          at TaskQueue.execute_ (/Users/jorg/Documents/ADev/p4d/node_modules/selenium-webdriver/lib/promise.js:3084:14)
          at TaskQueue.executeNext_ (/Users/jorg/Documents/ADev/p4d/node_modules/selenium-webdriver/lib/promise.js:3067:27)
          at asyncRun (/Users/jorg/Documents/ADev/p4d/node_modules/selenium-webdriver/lib/promise.js:2927:27)
          at /Users/jorg/Documents/ADev/p4d/node_modules/selenium-webdriver/lib/promise.js:668:7
          at process._tickCallback (internal/process/next_tick.js:178:7)
      From: Task: Run it("should display p4d select") in control flow
          at UserContext.<anonymous> (/Users/jorg/Documents/ADev/p4d/node_modules/jasminewd2/index.js:94:19)
          at /Users/jorg/Documents/ADev/p4d/node_modules/jasminewd2/index.js:64:48
          at ControlFlow.emit (/Users/jorg/Documents/ADev/p4d/node_modules/selenium-webdriver/lib/events.js:62:21)
          at ControlFlow.shutdown_ (/Users/jorg/Documents/ADev/p4d/node_modules/selenium-webdriver/lib/promise.js:2674:10)
          at shutdownTask_.MicroTask (/Users/jorg/Documents/ADev/p4d/node_modules/selenium-webdriver/lib/promise.js:2599:53)
      From asynchronous test: 
      Error
          at Suite.<anonymous> (/Users/jorg/Documents/ADev/p4d/e2e/src/app.e2e-spec.ts:10:3)
          at Object.<anonymous> (/Users/jorg/Documents/ADev/p4d/e2e/src/app.e2e-spec.ts:3:1)
          at Module._compile (internal/modules/cjs/loader.js:678:30)
          at Module.m._compile (/Users/jorg/Documents/ADev/p4d/node_modules/ts-node/src/index.ts:400:23)
          at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
          at Object.require.extensions.(anonymous function) [as .ts] (/Users/jorg/Documents/ADev/p4d/node_modules/ts-node/src/index.ts:403:12)

### Desired functionality

Now that ng e2e now by default starts a dev server (thanks!), for most projects, everything works fine, just in this one, I get the "Could not find Angular on page http://localhost:4200/ :"

I compared 
- angular.json
- protractor.conf.js
with a test app generated with the current version and ng new - and updated the config files.

The odd thing is that I can connect to the dev server started by ng e2e from another browser window.

How can I debug this?

Note: the wiki
https://github.com/angular/angular-cli/wiki/e2e
still shows the option --serve -- which is discontinued.

### Mention any other details that might be useful

in angular.json, I added for the project-e2e:
```
    "p4d-e2e": {
...
          "configurations": {
            "production": {
              "devServerTarget": "p4d:serve:production"
            }
          }
```
(copied from a newly created project) - it seems this is optional

**Comment by filipesilva** [comment]
I'm not sure what could cause what you are seeing, and I can't reproduce in a new project. Do you have a repro I can follow to see it myself?

**Comment by jorgjanke** [comment]
Turned out that the apps crashed due to a bug - but as no log/console info is displayed the cause was not obvious.
So the issue is that console info is not displayed/available

**Comment by filipesilva** [comment]
You can use Protractor APIs to capture the console logs of the tested app, but it's not something it prints by itself. Glad to hear you found the cause though!
