### ISSUE TITLE
In npm registry under the name `@angular-devkit/build-webpack` another package is published

### ISSUE THREAD

**Issue by Defenderbass** [angular/angular-cli#11340]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
npm: 5.6.0
Angular CLI: 6.0.8
Node: 8.10.0
OS: darwin x64
@angular-devkit/build-webpack: 0.0.8

### Repro steps

In the application created with `ng new`, install
```
npm i @angular-devkit/build-webpack --save-dev
```
Add to `angular.json`
```json
"architect": {
...
        "build-webpack": {
          "builder": "@angular-devkit/build-webpack:webpack",
          "options": {
            "webpackConfig": "webpack.config.js"
          }
        },
...
}
```
And run 
```
ng run app:build-webpack
```
### The log given by the failure

```
$ ng run app:build-webpack
Builder '@angular-devkit/build-webpack:webpack' cannot be resolved.
Error: Builder '@angular-devkit/build-webpack:webpack' cannot be resolved.
    at MergeMapSubscriber._loadJsonFile.pipe.operators_1.concatMap [as project] (/node_modules/@angular-devkit/architect/src/architect.js:148:46)
    at MergeMapSubscriber._tryNext (/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/node_modules/rxjs/internal/Subscriber.js:64:18)
```
### Mention any other details that might be useful

File `node_modules/@angular-devkit/build-webpack/builders.json` from the project
```json

{
  "$schema": "../architect/src/builders-schema.json",
  "builders": {
    "app-shell": {
      "class": "./src/app-shell",
      "schema": "./src/app-shell/schema.json",
      "description": "Build a server app and a browser app, then render the index.html and use it for the browser output."
    },
    "browser": {
      "class": "./src/browser",
      "schema": "./src/browser/schema.json",
      "description": "Build a browser app."
    },
    "dev-server": {
      "class": "./src/dev-server",
      "schema": "./src/dev-server/schema.json",
      "description": "Serve a browser app."
    },
    "extract-i18n": {
      "class": "./src/extract-i18n",
      "schema": "./src/extract-i18n/schema.json",
      "description": "Extract i18n strings from a browser app."
    },
    "karma": {
      "class": "./src/karma",
      "schema": "./src/karma/schema.json",
      "description": "Run Karma unit tests."
    },
    "protractor": {
      "class": "./src/protractor",
      "schema": "./src/protractor/schema.json",
      "description": "Run protractor over a dev server."
    },
    "tslint": {
      "class": "./src/tslint",
      "schema": "./src/tslint/schema.json",
      "description": "Run tslint over a TS project."
    },
    "server": {
      "class": "./src/server",
      "schema": "./src/server/schema.json",
      "description": "Build a server Angular application."
    }
  }
}

```
File in repo https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_webpack/builders.json
```json
{
  "$schema": "../architect/src/builders-schema.json",
  "builders": {
    "webpack": {
      "class": "./src/webpack",
      "schema": "./src/webpack/schema.json",
      "description": "Build a webpack app."
    },
    "webpack-dev-server": {
      "class": "./src/webpack-dev-server",
      "schema": "./src/webpack-dev-server/schema.json",
      "description": "Serve a webpack app."
    }
  }
}
```

In npm registry under the name `@angular-devkit/build-webpack` another package is published

**Comment by clydin** [comment]
https://www.npmjs.com/package/@angular-devkit/build-webpack/v/0.7.0-rc.0

The final version is not released yet.  you'll need to use `@next` if you would like to try it out.
