### ISSUE TITLE
ng build -prod with 2 routes fails

### ISSUE THREAD

**Issue by svenloe** [angular/angular-cli#1135]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Gentoo Linux (up to date)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal:  
angular-cli: 1.0.0-beta.6
node: 4.1.0
os: linux x64

        node --version
v4.1.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
The app was created with angular-cli beta.5

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Error on fetch for app/+lsddetail.js at file:///home/sven1/workspace3/lsdekl/lsdekl-web/src/main/lsdekl/tmp/bundle_plugin-input_base_path-ZfUWd6tE.tmp/0/app/+lsddetail.js
        Loading app/lsdekl.component.js
        Loading app/index.js
        Loading main.js
        Error: ENOENT: no such file or directory, open '/home/sven1/workspace3/lsdekl/lsdekl-web/src/main/lsdekl/tmp/bundle_plugin-input_base_path-ZfUWd6tE.tmp/0/app/+lsddetail.js'
    at Error (native)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (/home/sven1/workspace3/lsdekl/lsdekl-web/src/main/lsdekl/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (/home/sven1/workspace3/lsdekl/lsdekl-web/src/main/lsdekl/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
The file that is not found is in the folder +lsddetail/. Angular-cli seems to look for it in the wrong directory.

**Comment by svenloe** [comment]
Fixed the problem. It was routes in a '+routeDir' after removing the '+' and fixing the imports it worked.
