### ISSUE TITLE
ng update @angular/cli connection refused

### ISSUE THREAD

**Issue by aleskurlovich** [angular/angular-cli#11364]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

node: v8.11.2
npm: 5.6.0
angular/cli: 1.7.4

### Repro steps

Simple Angular 5 application which should be migrated to simple Angular 6 application.
1. npm install -g @angular/cli (updates angular/cli globally)
2. npm install @angular/cli (updates angular/cli locally)
3. ng update @angular/cli (migrates configuration)

### The log given by the failure

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 104.18.97.96:80
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

### Desired functionality

I expected to see migrated configuration.

**Comment by aleskurlovich** [comment]
Sorry. It looks like problem on our side.
