### ISSUE TITLE
Error Running ng new command

### ISSUE THREAD

**Issue by prince1809** [angular/angular-cli#1137]
OS:  Mac OSX El Capitan
node --version
v2.5.0
ng --version produce the same error

Repro steps:

```
sudo npm install -g angular-cli
/usr/local/var/nvm/versions/io.js/v2.5.0/bin/ng -> /usr/local/var/nvm/versions/io.js/v2.5.0/lib/node_modules/angular-cli/bin/ng
/usr/local/var/nvm/versions/io.js/v2.5.0/lib
angular-cli@1.0.0-beta.6 
  ├── assertion-error@1.0.2 
  ├─┬ broccoli@1.0.0-beta.7 
  │ ├─┬ broccoli-kitchen-sink-helpers@0.3.1 
  .
  .
  .
 


xxxxx-MacBook-Pro:angular2 prince$ ng new angular-cli -dir angular-test --prefix ac
/usr/local/var/nvm/versions/io.js/v2.5.0/lib/node_modules/angular-cli/addon/ng2/commands/test.js:51
        run: () => {
              ^
Unexpected token )
/usr/local/var/nvm/versions/io.js/v2.5.0/lib/node_modules/angular-cli/addon/ng2/commands/test.js:51
        run: () => {
              ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Class.module.exports.includedCommands (/usr/local/var/nvm/versions/io.js/v2.5.0/lib/node_modules/angular-cli/addon/ng2/index.js:18:15)
    at /usr/local/var/nvm/versions/io.js/v2.5.0/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)


```

**Comment by prince1809** [comment]
It was node version issue..
