### ISSUE TITLE
@schematics/update test failed on last release

### ISSUE THREAD

**Issue by fmoutawe** [angular/angular-cli#11387]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ x ] schematics
```

### Versions
angular-cli: tag v6.1.0-rc.0
node : v8.11.2
npm : 6.1.0
macOS High Sierra (10.13.3)

### Repro steps

- clone angular/angular-cli : `git clone https://github.com/angular/angular-cli.git`
- checkout to v6.1.0-rc.0 : `git checkout tags/v6.1.0-rc.0`
- run test : `npm run test`

### The log given by the failure

Failures:
Failures:
Failures:
1) @schematics/update updates Angular as compatible with Angular N-1
  Message:
    Failed: Incompatible peer dependencies found. See above.
  Stack:
    Error: Incompatible peer dependencies found. See above.
        at _validateUpdatePackages (\path\to\repo\angular-cli\packages\schematics\update\update\file:\\path\to\repo\angular-cli\packages\schematics\update\update\index.ts:201:11)
        at SwitchMapSubscriber.rxjs_1.from.pipe.operators_1.switchMap.infoMap [as project] (\path\to\repo\angular-cli\packages\schematics\update\update\file:\\path\to\repo\angular-cli\packages\schematics\update\update\index.ts:833:11)
        at SwitchMapSubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\switchMap.ts:103:21)
        at SwitchMapSubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at MapSubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\map.ts:86:22)
        at MapSubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at DefaultIfEmptySubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\defaultIfEmpty.ts:72:22)
        at DefaultIfEmptySubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at TakeLastSubscriber._complete (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\takeLast.ts:105:21)
        at TakeLastSubscriber.Subscriber.complete (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:129:12)

2) @schematics/update updates Angular as compatible with Angular N-1 (2)
  Message:
    Failed: Incompatible peer dependencies found. See above.
  Stack:
    Error: Incompatible peer dependencies found. See above.
        at _validateUpdatePackages (\path\to\repo\angular-cli\packages\schematics\update\update\file:\\path\to\repo\angular-cli\packages\schematics\update\update\index.ts:201:11)
        at SwitchMapSubscriber.rxjs_1.from.pipe.operators_1.switchMap.infoMap [as project] (\path\to\repo\angular-cli\packages\schematics\update\update\file:\\path\to\repo\angular-cli\packages\schematics\update\update\index.ts:833:11)
        at SwitchMapSubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\switchMap.ts:103:21)
        at SwitchMapSubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at MapSubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\map.ts:86:22)
        at MapSubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at DefaultIfEmptySubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\defaultIfEmpty.ts:72:22)
        at DefaultIfEmptySubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at TakeLastSubscriber._complete (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\takeLast.ts:105:21)
        at TakeLastSubscriber.Subscriber.complete (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:129:12)

### Desired functionality
I fork angular/angular-cli to bring some extra features, specific to my needs.

### Mention any other details that might be useful
If you have any clue to fix this, I will put a pull request with pleasure.

**Comment by clydin** [comment]
The tests pass on CI.  They do, however, assume a basic `.npmrc` file (i.e., no custom authentication, etc.).

**Comment by ivelfan** [comment]
Where can I find this .npmrc ?

**Comment by ivelfan** [comment]
I update the question with a fresh `.npmrc`.
I have these errors : 

Failures:
1) @schematics/update updates Angular as compatible with Angular N-1
  Message:
    Failed: Incompatible peer dependencies found. See above.
  Stack:
    Error: Incompatible peer dependencies found. See above.
        at _validateUpdatePackages (\path\to\repo\angular-cli\packages\schematics\update\update\file:\\path\to\repo\angular-cli\packages\schematics\update\update\index.ts:201:11)
        at SwitchMapSubscriber.rxjs_1.from.pipe.operators_1.switchMap.infoMap [as project] (\path\to\repo\angular-cli\packages\schematics\update\update\file:\\path\to\repo\angular-cli\packages\schematics\update\update\index.ts:833:11)
        at SwitchMapSubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\switchMap.ts:103:21)
        at SwitchMapSubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at MapSubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\map.ts:86:22)
        at MapSubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at DefaultIfEmptySubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\defaultIfEmpty.ts:72:22)
        at DefaultIfEmptySubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at TakeLastSubscriber._complete (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\takeLast.ts:105:21)
        at TakeLastSubscriber.Subscriber.complete (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:129:12)

2) @schematics/update updates Angular as compatible with Angular N-1 (2)
  Message:
    Failed: Incompatible peer dependencies found. See above.
  Stack:
    Error: Incompatible peer dependencies found. See above.
        at _validateUpdatePackages (\path\to\repo\angular-cli\packages\schematics\update\update\file:\\path\to\repo\angular-cli\packages\schematics\update\update\index.ts:201:11)
        at SwitchMapSubscriber.rxjs_1.from.pipe.operators_1.switchMap.infoMap [as project] (\path\to\repo\angular-cli\packages\schematics\update\update\file:\\path\to\repo\angular-cli\packages\schematics\update\update\index.ts:833:11)
        at SwitchMapSubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\switchMap.ts:103:21)
        at SwitchMapSubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at MapSubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\map.ts:86:22)
        at MapSubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at DefaultIfEmptySubscriber._next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\defaultIfEmpty.ts:72:22)
        at DefaultIfEmptySubscriber.Subscriber.next (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:102:12)
        at TakeLastSubscriber._complete (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\operators\takeLast.ts:105:21)
        at TakeLastSubscriber.Subscriber.complete (\path\to\repo\angular-cli\node_modules\rxjs\src\internal\Subscriber.ts:129:12)

**Comment by kyliau** [comment]
Closing this, since issue is specific to CLI v6 and only pertains to tests on CI.
