### ISSUE TITLE
ng e2e help throws an error

### ISSUE THREAD

**Issue by fr0** [angular/angular-cli#11411]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
### Versions

```
Angular CLI: 6.0.8
Node: 8.9.4
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

`ng e2e help`

### The log given by the failure

```
> ng e2e help
Project 'help' could not be found in workspace.
Error: Project 'help' could not be found in workspace.
    at Workspace.getProject (/Users/crfrolik/Documents/mirror-dim/web/node_modules/@angular-devkit/core/src/workspace/workspace.js:83:19)
    at Architect.getBuilderConfiguration (/Users/crfrolik/Documents/mirror-dim/web/node_modules/@angular-devkit/architect/src/architect.js:96:41)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (/Users/crfrolik/Documents/mirror-dim/web/node_modules/@angular/cli/models/architect-command.js:64:55)
    at MergeMapSubscriber._tryNext (/Users/crfrolik/Documents/mirror-dim/web/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/Users/crfrolik/Documents/mirror-dim/web/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/crfrolik/Documents/mirror-dim/web/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (/Users/crfrolik/Documents/mirror-dim/web/node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (/Users/crfrolik/Documents/mirror-dim/web/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/crfrolik/Documents/mirror-dim/web/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/Users/crfrolik/Documents/mirror-dim/web/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
```

### Desired functionality

The help documentation should be printed.

**Comment by fr0** [comment]
Whoops -- using `--help` instead works. User error.
