### ISSUE TITLE
"Cannot read property 'match' of undefined" on `ng serve --c local` after updating to 6.0.8

### ISSUE THREAD

**Issue by MasaharuKomuro** [angular/angular-cli#11429]
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
```
Angular CLI: 6.0.8
Node: 8.9.0
OS: darwin x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.0.10
@angular-devkit/build-optimizer   0.4.9
@angular-devkit/core              0.4.9
@angular-devkit/schematics        0.4.9
@angular/cdk                      6.3.1
@angular/cli                      6.0.8
@angular/material                 6.3.1
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-beta.9
@schematics/angular               0.4.9
@schematics/package-update        0.4.9
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.14.0
```

### Repro steps
- update angular/cli 1.7.3 to 6.0.8
- Run ng build -c local

configuration of my angular.json
```
"configurations": {
            "local": {
              "fileReplacements": [
                {
                  "from": "src/environments/environment.local.ts",
                  "to": "dist/environments/environment.local.ts"
                }
              ]
            },
            "dev": {
              "fileReplacements": [
                {
                  "from": "src/environments/environment.ts",
                  "to": "dist/environments/environment.ts"
                }
              ]
            },
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "from": "src/environments/environment.prod.ts",
                  "to": "dist/environments/environment.prod.ts"
                }
              ]
            }
          }
```

### The log given by the failure
```
Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at Object.normalize (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/core/src/virtual-fs/path.js:178:14)
    at options.fileReplacements.forEach (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/src/browser/index.js:99:55)
    at Array.forEach (<anonymous>)
    at BrowserBuilder.buildWebpackConfig (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/src/browser/index.js:98:34)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:36:50)
    at Observable._trySubscribe (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Observable.js:29:22)
    at /Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
    at MergeMapSubscriber._next (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/Users/komuro-m1/workspace/vagrant_work/apps/angular/potaufeu2/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
```

### Mention any other details that might be useful
``` ng serve ``` : no error
``` ng serve -c local``` : error
``` ng build --prod ``` error ( same error )

**Comment by MasaharuKomuro** [comment]
Sorry, I resolved it. It seem to cause of version missmatch. I run command ```ng new``` and confirmed versions bellow.

```
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/material                 6.3.2
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```
I run ```npm install``` and install same version with above in my project, so ```ng serve``` command become has no errors.

So, I close this issue.
