### ISSUE TITLE
ng --build fail with message "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by ido-paz** [angular/angular-cli#11457]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ x] schematics
```

### Versions

Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64 ,windows 10
Angular: 6.0.7
npm 6.1.0

### Repro steps

ng --build 
// in a folder with a newly created project that was created with: 
angular new t4

### The log given by the failure

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at levenshtein (C:\Users\Ido\Downloads\Angular\t4\node_modules\@angular\cli\models\command-runner.js:58:23)
    at listAllCommandNames.sort (C:\Users\Ido\Downloads\Angular\t4\node_modules\@angular\cli\models\command-runner.js:69:43)
    at Array.sort (native)
    at Object.<anonymous> (C:\Users\Ido\Downloads\Angular\t4\node_modules\@angular\cli\models\command-runner.js:67:65)
    at Generator.next (<anonymous>)
    at C:\Users\Ido\Downloads\Angular\t4\node_modules\@angular\cli\models\command-runner.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Ido\Downloads\Angular\t4\node_modules\@angular\cli\models\command-runner.js:3:12)
    at Object.runCommand (C:\Users\Ido\Downloads\Angular\t4\node_modules\@angular\cli\models\command-runner.js:28:12)
    at C:\Users\Ido\Downloads\Angular\t4\node_modules\@angular\cli\lib\cli\index.js:60:58

### Desired functionality

I am trying to learn Angular after installing it

**Comment by alan-agius4** [comment]
`ng --build` is not a valid command, use `ng build` instead.

**Comment by ido-paz** [comment]
ng build produce the same results and does not resolve the issue

**Comment by filipesilva** [comment]
I just tried doing
```
ng new t4
cd t4
ng build
```

And it worked correctly on Angular CLI 6.1 RC.

Please let me know if you're still experiencing this and I will reopen the issue.
