### ISSUE TITLE
ng add  @angular/pwa --project broken in 6.1.0-rc.0

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#11465]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
```

### Area
```
- [ x] devkit
- [x ] schematics
```

### Versions
`node --version
`v8.9.1

`npm --version
`5.5.1

`Windows 10
`
### Repro steps
Generate new project:

`ng new Temp`
add @angular/pwa

`ng add  @angular/pwa --project Temp`

and it will throw the below error:

```
Schematic input does not validate against the Schema: {"project":"Temp","target":"build","configuration":"production","title":"Temp"}
Errors:

  Data path "" should NOT have additional properties(title).
```

### Desired functionality
It should work.

**Comment by tobi-or-not-tobi** [comment]
I can confirm this happens with @angular/cli@6.1.0-rc.1 as well.

**Comment by rrahul14** [comment]
This is also happening with @angular/cli@6.1.0-rc.2

**Comment by bave8672** [comment]
Possibly related: https://github.com/angular/angular-cli/issues/11640

**Comment by adnathanail** [comment]
@gkalpak Tried with the versions you suggested [here](https://github.com/angular/angular-cli/issues/11640#issuecomment-410638864) as well as the ones in the comment above. Again works on local http-server but when on nginx (on https) offline does not function. I have now got ngsw/state to work and I get the following:
<pre><code>
[3m8s4u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://da.redacted.co.uk/)
[2m59s194u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://da.redacted.co.uk/index.html: expected 32ca9784fa783ed51fd1f0e842b281fd951af65f, got fe7e41417229e8b86bdce275e4448d45f388830d (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://da.redacted.co.uk/index.html: expected 32ca9784fa783ed51fd1f0e842b281fd951af65f, got fe7e41417229e8b86bdce275e4448d45f388830d (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://da.redacted.co.uk/ngsw-worker.js:674:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://da.redacted.co.uk/ngsw-worker.js:304:62)) initializeFully for eb9fbe047e132f71917baab3deacdadd3879a015
[1m3s237u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://da.redacted.co.uk/)
[58s203u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://da.redacted.co.uk/ngsw.json?ngsw-cache-bust=0.6084465673480977)
[58s203u] Check for update aborted. (Client or server offline.) 
[1s814u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://da.redacted.co.uk/)
</code></pre>
I believe I have fixed the first error about hashing, I have included it just in case it is relevant

**Comment by gkalpak** [comment]
`@angular/pwa` works find in latest (beta) versions (see https://github.com/angular/angular-cli/issues/11640#issuecomment-410638864).
