### ISSUE TITLE
App shell: Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by LastDragon-ru** [angular/angular-cli#11482]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
```
Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

1. Create a new project with routing `ng new app-shell-test --routing`
2. Add app shell to project `ng g app-shell --universal-project=app-shell-test --client-project=app-shell-test`
3. Run `npm install class-transformer`
4. Update `app-shell-test/src/app/app.component.ts`
   ```
    import {Component} from '@angular/core';
    import {Type} from 'class-transformer';
    
    @Component({
        selector:    'app-root',
        templateUrl: './app.component.html',
        styleUrls:   ['./app.component.css']
    })
    export class AppComponent {
        title = 'app';
    }
    
    export class Test {
        @Type(() => Date)
        public start: Date;
    }
   ```
4. Run `ng run app-shell-test:app-shell` 

### Output
```
Date: 2018-07-06T14:19:21.999Z
Hash: 9ca49bed2000a769e749
Time: 10645ms
chunk {main} main.js, main.js.map (main) 33.5 kB [entry] [rendered]
Date: 2018-07-06T14:19:25.463Z
Hash: 7984246ef0c7f2b316e4
Time: 13989ms
chunk {main} main.js, main.js.map (main) 12.9 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.01 MB [initial] [rendered]
Reflect.getMetadata is not a function
TypeError: Reflect.getMetadata is not a function
    at app-shell-test\node_modules\class-transformer\decorators.js:24:28
    at ./src/app/app.component.ts.__decorate (app-shell-test\dist\app-shell-test-server\main.js:273:110)
    at app-shell-test\dist\app-shell-test-server\main.js:293:5
    at Object../src/app/app.component.ts (app-shell-test\dist\app-shell-test-server\main.js:298:2)
    at __webpack_require__ (app-shell-test\dist\app-shell-test-server\main.js:20:30)
    at Object../src/app/app.server.module.ngfactory.js (app-shell-test\dist\app-shell-test-server\main.js:342:10)
    at __webpack_require__ (app-shell-test\dist\app-shell-test-server\main.js:20:30)
    at Object../src/main.server.ts (app-shell-test\dist\app-shell-test-server\main.js:424:37)
    at __webpack_require__ (app-shell-test\dist\app-shell-test-server\main.js:20:30)
    at Object.0 (app-shell-test\dist\app-shell-test-server\main.js:445:18)
    at __webpack_require__ (app-shell-test\dist\app-shell-test-server\main.js:20:30)
    at ./node_modules/@angular/router/router.ngfactory.js.Object.defineProperty.value (app-shell-test\dist\app-shell-test-server\main.js:69:18)
    at Object.<anonymous> (app-shell-test\dist\app-shell-test-server\main.js:72:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

```

### Desired functionality

App shell should work without manual imports.

### Mention any other details that might be useful

I'm newbie in angular server/app shell but seems cli is not includes `reflect` when builds the app shell. moreover, I can't find any way to include it like browser `polyfills.ts` so I added `import 'core-js/es7/reflect';`  into `src/app/app.server.module.ts`  and `ng run app-shell-test:app-shell` work now.

I'm not sure that this is the right way to do this, maybe cli should use polyfills automatically while generating the app shell?

**Comment by alan-agius4** [comment]
Indeed you need reflect-metadata at server level as well. Please check: https://angular.io/guide/universal#app-server-entry-point

**Comment by alan-agius4** [comment]
Hi, 

`class-transformer` package requires `Reflect` polyfill to work. The CLI will not add this polyfill for the server/app-shell, as it's not needed by default.

In your cases the package you are using does needed and hence you are required to add it manually.

**Comment by LastDragon-ru** [comment]
> In your cases the package you are using does needed and hence you are required to add it manually.

@alan-agius4, Yes. But why `polyfills.ts` is ignored for app shell?

**Comment by alan-agius4** [comment]
You can import this polyfill in `main.server.ts`
