### ISSUE TITLE
Universal Server - SyntaxError: Unexpected string "import 'zone.js/dist/zone-node';"

### ISSUE THREAD

**Issue by MrCroft** [angular/angular-cli#11502]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Area
```
- [ ] devkit
- [ ] schematics
- [x] not sure. It's not schematics, but I don't know if the build has anything to do with devkit either.
```

### Versions
```
Angular CLI: 6.1.0-rc.0
Node: 10.6.0
OS: win32 x64
Angular: 6.0.7
```
It's the same with CLI 6.0.8, I've tried the rc version after having tried with 6.0.8.

### Repro steps
[Clone this repo](https://github.com/MrCroft/ng6-universal)
```
npm i
npm run build:server (ng build --prod --extract-css && ng run univ:server && cp server.ts ./dist/univ/)
npm run serve:ssr (./node_modules/.bin/ts-node ./dist/univ/server)
```

### The log given by the failure
```
C:\www\univ (master -> origin)
λ npm run serve:ssr

> univ@0.0.0 serve:ssr C:\www\univ
> ts-node ./dist/univ/server

C:\www\univ\dist\univ\server.ts:26
import 'zone.js/dist/zone-node';
       ^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module.m._compile (C:\www\univ\node_modules\ts-node\src\index.ts:400:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\www\univ\node_modules\ts-node\src\index.ts:403:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! univ@0.0.0 serve:ssr: `ts-node ./dist/univ/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the univ@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-07-09T14_43_50_322Z-debug.log
```

### Desired functionality
Universal app should work.

**Comment by filipesilva** [comment]
I'm a bit confused with this repro... while `ng build --prod --extract-css` is indeed Angular CLI, your other steps don't really have anything to do with Angular CLI. I'm not sure why it doesn't work but I don't think it's something related to Angular CLI.

Angular CLI does support universal, but you'll need to follow these steps for it to work https://github.com/angular/angular-cli/wiki/stories-universal-rendering.

**Comment by BruneXX** [comment]
I'm experiencing the same issue, what's the problem with that?
