### ISSUE TITLE
HMR. Serve error "Data path "" should NOT have additional properties(fileReplacements)"

### ISSUE THREAD

**Issue by Dok11** [angular/angular-cli#11540]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Area
```
- [x] schematics
```

### Versions
```
node v8.9.4
npm 5.6.0
```

### Repro steps
In making step from https://github.com/angular/angular-cli/wiki/stories-configure-hmr

![image](https://user-images.githubusercontent.com/2697890/42689165-e8451950-86a7-11e8-9d6f-c1e5325268df.png)

I set my angular.json like this:

![image](https://user-images.githubusercontent.com/2697890/42689204-092c3c48-86a8-11e8-85b6-6dbb7ab98a53.png)

### The log given by the failure
```
> ng serve --port 4260 --proxy-config proxy.conf.json --aot --source-map --progress false --configuration hmr

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(fileReplacements).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! main@0.0.0 start-hmr: `ng serve --port 4260 --proxy-config proxy.conf.json --aot --source-map --progress false --configuration hmr`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the main@0.0.0 start-hmr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Bengreen** [comment]
@hansl  Any hints available on how to do this ?

**Comment by Dok11** [comment]
@Bengreen yes, I made little notice about this. See here https://gist.github.com/Dok11/cc30759099376d9263fe4edfd0d13341

**Comment by joker-danta** [comment]
`
Angular CLI: 7.1.3
Node: 10.13.0
Angular: 7.1.3
npm run hmr
`
error
`
Schema validation failed with the following errors:
  Data path "['build']" should NOT have additional properties(hmr).
Error: Schema validation failed with the following errors:
  Data path "['build']" should NOT have additional properties(hmr).
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/Users/work/Desktop/qlouduiframe/new-ui/node_modules/rxjs/internal/operators/switchMap.js:86:26)
`
step is [link](https://github.com/angular/angular-cli/wiki/stories-configure-hmr)

**Comment by hamzazaidi** [comment]
I am getting the following error
Schema validation failed with the following errors:
  Data path "['build']" should NOT have additional properties(hmr).
Error: Schema validation failed with the following errors:
  Data path "['build']" should NOT have additional properties(hmr).
