### ISSUE TITLE
Exception with spdy and lighthouse

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [angular/angular-cli#11581]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [X] devkit
- [X] schematics
```

### Versions
Node: v:9.8.0 NPM: 6.0.1
Windows 10

### Repro steps
Not sure is this issue of CLI or any other google library but maybe you will give me an advice where to start from or where to report:

I have Angular 6 project with SW and SPDY http2 push enabled. Also i got SSR in place with Angular Universal. When clicking around more with hard refreshes and navigating around sometimes i got these errors:

1) and after couple refreshes i got that weired error: 
```
{ AssertionError [ERR_ASSERTION]: false == true
    at PriorityNode.removeChild (C:\git\wearlenses-3-client\web\dist\server.js:130338:3)
    at PriorityNode.remove (C:\git\wearlenses-3-client\web\dist\server.js:130326:15)
    at PriorityTree.add (C:\git\wearlenses-3-client\web\dist\server.js:130427:23)
    at Stream._initPriority (C:\git\wearlenses-3-client\web\dist\server.js:130559:25)
    at new Stream (C:\git\wearlenses-3-client\web\dist\server.js:130534:8)
    at Connection._createStream (C:\git\wearlenses-3-client\web\dist\server.js:131564:16)
    at Connection._handleHeaders (C:\git\wearlenses-3-client\web\dist\server.js:131612:21)
    at Connection._handleFrame (C:\git\wearlenses-3-client\web\dist\server.js:131495:10)
    at Parser.<anonymous> (C:\git\wearlenses-3-client\web\dist\server.js:131332:10)
    at ZoneDelegate.invokeTask (C:\git\wearlenses-3-client\web\dist\server.js:117435:31)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

2) 
```
TypeError: Cannot read property 'getPriority' of null
    at C:\git\wearlenses-3-client\web\dist\server.js:130627:32
    at ZoneDelegate.invokeTask (C:\git\wearlenses-3-client\web\dist\server.js:117435:31)
    at Zone.runTask (C:\git\wearlenses-3-client\web\dist\server.js:117202:47)
    at ZoneTask.invokeTask (C:\git\wearlenses-3-client\web\dist\server.js:117510:34)
    at ZoneTask.invoke (C:\git\wearlenses-3-client\web\dist\server.js:117499:48)
    at data.args.(anonymous function) (C:\git\wearlenses-3-client\web\dist\server.js:118352:25)
    at process._tickCallback (internal/process/next_tick.js:112:11)
```

So not sure if those are related somehow but it would be great if you can help me solve some or redirect me to right place. I have started from here because errors are in zone.

Also i cannot give any reproduction because it is internal project and to reproduce it would take ages.

**Comment by filipesilva** [comment]
I'm not really sure how to get around looking at this either. Can you put up a repro please?

**Comment by vytautas-pranskunas-** [comment]
Actually i was able to minimize places where error comes from. So it comes when i enable push on ssr so code loks like

code:

```
app.get('*', (req: any, res: any) => 
{

    try {
        Promise.all([...config.files]).then((data: any[]) => {
                for (let i = 0; i < config.files.length; i++) {
                    const pushOptions = {
                        status: 200, // optional
                        method: 'GET', // optional
                        request: {
                            accept: '*/*'
                        },
                        response: {
                            'content-type': config.files[i].mimeType,
                            'Cache-Control': 'public, max-age=30672000'
                        }
                    };

                    let contentToSend = data[i];
  
           

                    if (config.files[i].gzip) {
                        pushOptions.response['content-encoding'] = 'gzip';
                        contentToSend = zlib.gzipSync(contentToSend);
                    }

                    const stream = (<any>res).push(`/${config.files[i].name}`, pushOptions);

                    stream.on('error', () => { });

                    stream.end(contentToSend);
                }
            }).catch(error => { });
    } catch (e) {
        console.log(e);
    }


    res.render('index', { req });
});
```

It feels like res.render should be added differently. 

Maybe i have to report it to universal project?

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the nguniversal project or file an issue on their issue tracker.
