### ISSUE TITLE
Upping the stack size of an ng command breaks the build process

### ISSUE THREAD

**Issue by crutchcorn** [angular/angular-cli#11629]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 6.1.0-rc.3
Node: 8.9.1
OS: win32 x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.0-rc.3
@angular/cdk                      6.4.0
@angular/cli                      6.1.0-rc.3
@angular/material                 6.4.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.0-rc.3
@schematics/update                0.7.0-rc.3
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

### Repro steps
```
corbincrutchley@HQ-EMP1 MINGW64 ~/git/linkd-angular-6 (ng-6)
$ node --stack_size="8192" ./node_modules/\@angular/cli/bin/ng build
 10% building modules 3/3 modules 0 active
corbincrutchley@HQ-EMP1 MINGW64 ~/git/linkd-angular-6 (ng-6)
$
```

### The log given by the failure
No errors are thrown by this

### Desired functionality
My project currently has typescript errors when using the normal stack size to compile the app. I need to buff up the stack size to something larger. The larger stack size runs fine with typescript but not with `ng` command. It silently fails after a few seconds of running

**Comment by crutchcorn** [comment]
Something worth noting is that if I run:
```
corbincrutchley@HQ-EMP1 MINGW64 ~/git/linkd-angular-6/src/app (ng-6)
$ tsc **/*.ts --experimentalDecorators --emitDecoratorMetadata --target "es5" --lib "es2017, dom" --moduleResolution "n
ode" --typeRoots ../../node_modules/@types --sourceMap
../../node_modules/@swimlane/ngx-dnd/lib/services/drake-store.service.d.ts(1,35): error TS2307: Cannot find module '@swimlane/dragula'.
../../node_modules/@types/pdf/index.d.ts(476,13): error TS2451: Cannot redeclare block-scoped variable 'PDFJS'.
../../node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.module.d.ts(3,11): error TS2451: Cannot redeclare block-scoped variable 'PDFJS'.
core/browser-upload/browser-upload.service.ts(7,28): error TS2307: Cannot find module '../../../../aws-config.json'.
```

(the options passed to that command were set to match my root `tsconfig` file:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```
)





However, if I run just `tsc` in the same directory, I get this:
```
corbincrutchley@HQ-EMP1 MINGW64 ~/git/linkd-angular-6/src/app (ng-6)
$ tsc
C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:61537
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at checkArrayLiteral (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32286:35)
    at checkExpressionWorker (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35822:28)
    at checkExpression (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35776:42)
    at getTypeOfExpression (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:35761:58)
    at getRegularTypeOfExpression (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39899:48)
    at getTypeOfNode (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:39836:24)
    at getApparentTypeOfContextualType (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32031:46)
    at getContextualTypeForObjectLiteralElement (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:31969:24)
    at getContextualType (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32079:28)
    at getApparentTypeOfContextualType (C:\Users\CorbinCrutchley\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:32018:34)
```

**Comment by crutchcorn** [comment]
Oof, I thought I had closed this issue. Turns out there was a bug in Typescript 2.7 that didn't play nice with some of our typings. Typescript 2.9 fixed the issue, so we've just moved to Angular 6.1
