### ISSUE TITLE
Build production environment Error

### ISSUE THREAD

**Issue by Observablerxjs** [angular/angular-cli#11656]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node version: 8.11.3
npm version: 6.1.0
Angular CLI: 6.0.8
Angular: 6.0.7
Windows 10

### Repro steps

First I tried `ng build --prod` but I got a lot of errors saying that I was using a private property wich was only accesible within the class. After some research I found out that was an AoT very strict warning so I tried the command `ng build --prod --aot false` ( or `ng build --prod --aot=false`) and here I have the following error.

### The log given by the failure

```
The `--build-optimizer` option cannot be used without `--aot`.
Error: The `--build-optimizer` option cannot be used without `--aot`.
    at Observable.rxjs_1.Observable.obs [as _subscribe] (..\node_modules\@angular-devkit\build-angular\src\browser\index.js:31:23)
    at Observable._trySubscribe (..\node_modules\rxjs\internal\Observable.js:43:25)
    at Observable.subscribe (..\node_modules\rxjs\internal\Observable.js:29:22)
    at ..\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (..\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (..\node_modules\rxjs\internal\operators\mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (..\node_modules\rxjs\internal\operators\mergeMap.js:72:14)
    at MergeMapSubscriber._next (..\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (..\node_modules\rxjs\internal\Subscriber.js:64:18)
    at TapSubscriber._next (..\node_modules\rxjs\internal\operators\tap.js:62:26)
    at TapSubscriber.Subscriber.next (..\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (..\node_modules\rxjs\internal\operators\mergeMap.js:84:26)
    at InnerSubscriber._next (..\node_modules\rxjs\internal\InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (..\node_modules\rxjs\internal\Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (..\node_modules\rxjs\internal\observable\forkJoin.js:79:25)
    at InnerSubscriber._complete (..\node_modules\rxjs\internal\InnerSubscriber.js:32:21)
```

### Desired functionality

build in production env.

**Comment by alan-agius4** [comment]
This is not a bug, but a correct error build optimizer can only be used when AOT. 

You can disable build optimizer and AOT for production builds but that is hightly discouraged, i’d recommend  fixing the AOT errors. 

If you want to disable AOT and build optimizer via command line you can use ‘— aot false —build-optimizer false’, you can also disable these via the angular.json file.

**Comment by Observablerxjs** [comment]
Ok, closing this. thanks
