### ISSUE TITLE
Import of @angular-devkit/core in schematic results in "Cannot find module './schema'"

### ISSUE THREAD

**Issue by mattezell** [angular/angular-cli#11728]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
-[X] devkit/core
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node: 8.11.3
NPM: 5.6.0
devkit/core: 0.6.8

### Repro steps

Import @angular-devkit/core as follows (from module schematic):
import { Rule, SchematicContext, Tree, chain, externalSchematic, mergeWith, apply, move, MergeStrategy, url, schematic, noop } from '@angular-devkit/schematics';

Attempt to debug the schematic..

### The log given by the failure

Error: Cannot find module './schema'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\w\Playground\@apex\schematics\node_modules\@angular-devkit\core\src\json\index.js:7:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

### Desired functionality

No errors...

### Mention any other details that might be useful

When I look at my project local node_modules\@angular-devkit\core\src\json\ folder, there is no \schema\ or schema.* present in the NPM installed 0.6.8 package...

**Comment by mattezell** [comment]
Resolved in @angular-devkit/core 0.7.1
