### ISSUE TITLE
integrity checksum failed when using sha1

### ISSUE THREAD

**Issue by miwels** [angular/angular-cli#11734]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node 10.7.0
npm 6.1.0
ng 6.1.1
macOS Sierra 10.12.6

### Repro steps
ng new <project_name>

### The log given by the failure
```CREATE ngrx-tutorial/README.md (1029 bytes)
CREATE ngrx-tutorial/angular.json (3611 bytes)
CREATE ngrx-tutorial/package.json (1318 bytes)
CREATE ngrx-tutorial/tsconfig.json (408 bytes)
CREATE ngrx-tutorial/tslint.json (2805 bytes)
CREATE ngrx-tutorial/.editorconfig (245 bytes)
CREATE ngrx-tutorial/.gitignore (503 bytes)
CREATE ngrx-tutorial/src/favicon.ico (5430 bytes)
CREATE ngrx-tutorial/src/index.html (299 bytes)
CREATE ngrx-tutorial/src/main.ts (370 bytes)
CREATE ngrx-tutorial/src/polyfills.ts (3194 bytes)
CREATE ngrx-tutorial/src/test.ts (642 bytes)
CREATE ngrx-tutorial/src/styles.css (80 bytes)
CREATE ngrx-tutorial/src/browserslist (375 bytes)
CREATE ngrx-tutorial/src/karma.conf.js (964 bytes)
CREATE ngrx-tutorial/src/tsconfig.app.json (170 bytes)
CREATE ngrx-tutorial/src/tsconfig.spec.json (256 bytes)
CREATE ngrx-tutorial/src/tslint.json (314 bytes)
CREATE ngrx-tutorial/src/assets/.gitkeep (0 bytes)
CREATE ngrx-tutorial/src/environments/environment.prod.ts (51 bytes)
CREATE ngrx-tutorial/src/environments/environment.ts (631 bytes)
CREATE ngrx-tutorial/src/app/app.module.ts (314 bytes)
CREATE ngrx-tutorial/src/app/app.component.css (0 bytes)
CREATE ngrx-tutorial/src/app/app.component.html (1141 bytes)
CREATE ngrx-tutorial/src/app/app.component.spec.ts (1016 bytes)
CREATE ngrx-tutorial/src/app/app.component.ts (217 bytes)
CREATE ngrx-tutorial/e2e/protractor.conf.js (752 bytes)
CREATE ngrx-tutorial/e2e/tsconfig.e2e.json (213 bytes)
CREATE ngrx-tutorial/e2e/src/app.e2e-spec.ts (309 bytes)
CREATE ngrx-tutorial/e2e/src/app.po.ts (208 bytes)
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
events.js:167░░░░░░⸩ ⠏ extract:miller-rabin: sill extract media-typer@0.3.0
      throw er; // Unhandled 'error' event
      ^

Error: sha1-iaf92TgmEmcxjq/hT5wy5ZjDaQk= integrity checksum failed when using sha1: wanted sha1-iaf92TgmEmcxjq/hT5wy5ZjDaQk= but got sha512-kJjj+Pl9OA1vwhjwIr6tVjYyiWU6wmBPVCHQ3VeYkdv/h23l3gkFHffnyQWO32FSh2SlAe9gx5Su/5vpT27OlQ== sha1-n85YVY2wat0OAtpXcaw7bNk4gak=. (1814 bytes)
    at Transform.on (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at Transform.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at err (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:191:31)
    at /Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:75:7
    at f (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.<anonymous> (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at WriteStream.f (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.onclose (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/end-of-stream/index.js:48:54)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.destroy (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/flush-write-stream/index.js:53:8)
    at /Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:45:45
    at call (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:72:25
    at f (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.<anonymous> (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at Transform.f (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.onerror (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/end-of-stream/index.js:43:12)
events.js:167░░░░░░⸩ ⠴ extract:image-size: sill extract https-browserify@1.0.0
      throw er; // Unhandled 'error' event
      ^

Error: sha1-iaf92TgmEmcxjq/hT5wy5ZjDaQk= integrity checksum failed when using sha1: wanted sha1-iaf92TgmEmcxjq/hT5wy5ZjDaQk= but got sha512-kJjj+Pl9OA1vwhjwIr6tVjYyiWU6wmBPVCHQ3VeYkdv/h23l3gkFHffnyQWO32FSh2SlAe9gx5Su/5vpT27OlQ== sha1-n85YVY2wat0OAtpXcaw7bNk4gak=. (1814 bytes)
    at Transform.on (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/ssri/index.js:310:19)
    at Transform.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at err (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/make-fetch-happen/cache.js:191:31)
    at /Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:75:7
    at f (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.<anonymous> (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at WriteStream.f (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at WriteStream.onclose (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/end-of-stream/index.js:48:54)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.destroy (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/flush-write-stream/index.js:53:8)
    at /Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:45:45
    at call (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:72:25
    at f (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.<anonymous> (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/pump/index.js:31:21)
    at Transform.f (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Transform.onerror (/Users/xxxx/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/end-of-stream/index.js:43:12)
npm ERR! cancel after 1 retries!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxx/.npm/_logs/2018-08-01T10_33_55_847Z-debug.log
Package install failed, see above.```

NOTE: already checked this thread:
https://github.com/nodejs/node/issues/13635

Tried all the solutions. None of them worked.

**Comment by miwels** [comment]
Solved. Apparently the registry was wrong and pointing to a different server so not related with angular-cli but with the npm configuration
