### ISSUE TITLE
Issues with ng serve

### ISSUE THREAD

**Issue by CaloBM** [angular/angular-cli#11774]
Hello! I'm trying to install Angular/CLI in terminal. It all goes fine, but when I execute `ng serve` I get the following error:
```
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:44:19)
    at WorkspaceLoader.loadWorkspace (/usr/local/lib/node_modules/@angular/cli/models/workspace-loader.js:31:21)
    at ServeCommand._loadWorkspaceAndArchitect (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:189:32)
    at ServeCommand.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:55:25)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@angular/cli/models/architect-command.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:10:12)
    at ServeCommand.initialize (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:54:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/command-runner.js:90:23)
```
I have tried reinstalling Node and restarting my computer but non of this fixed my issue.
~ Thanks, Calo!

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Closing as no reproduction provided.
