### ISSUE TITLE
Error : Invalid JSON character: "\"" at 25:11.

### ISSUE THREAD

**Issue by suraj7777** [angular/angular-cli#11808]
Working with Angular 6 and Node 10.

Getting above error while ng serve on C9 online IDE.

Error: Invalid JSON character: "\"" at 25:11.
    at _token (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:63:19)
    at _readObject (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:426:13)
    at _readValue (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:562:22)
    at _readProperty (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:398:19)
    at _readObject (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:431:30)
    at _readValue (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:562:22)
    at _readProperty (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:398:19)
    at _readObject (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:422:26)
    at _readValue (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:562:22)
    at _readProperty (/home/ec2-user/environment/selltm/frontend/node_modules/@angular-devkit/core/src/json/parser.js:398:19)

**Comment by filipesilva** [comment]
I think you're having some weird errors and can't debug it, and so, understandably, you're frustrated. But this is a tracker for bugs and feature requests. If we can we also try to help with support requests. We're very lucky to have awesome community members that also spend time trying to help people here in the issue tracker.

But we can't really help much at all if you don't fill in the issue template. I read your issue and have no idea what's going wrong and how to help you. And when other users search the issue tracker and see your issue, it also doesn't help them.

So I think the best thing to do is to close this issue, and ask you to open a new one. In that new one please fill in the issue template and give us an idea of what's happening and how to reproduce it. That way we'll have a chance to help you.

**Comment by vivekRath** [comment]
check your angular.json file. just check for conflicts and other issues. Configure it properly.

**Comment by yvesvensonceballos** [comment]
I have encountered this and found the error in angular.json file. I forgot to put comma when i add a styles.

**Comment by shashikanth8639** [comment]
I think you have installed bootstrap and implemented in "styles" array of angular.json file and forget to put a
 comma( , )  in that array between values.
........I think your problems solved..Good luck
