### ISSUE TITLE
Schematics Unit Testing Failing When Running Angular CLI workspace And application

### ISSUE THREAD

**Issue by jonbcampos** [angular/angular-cli#11806]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ X ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [ X ] schematics
```

### Versions
node -v: v9.10.1
npm --version: 6.2.0
ng --version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.1.2
Node: 9.10.1
OS: darwin x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.2
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@angular/cli                 6.1.2
@schematics/angular          0.7.2
@schematics/update           0.7.2
rxjs                         6.2.2
typescript                   2.7.2

### Repro steps
I created a simple schematic, it works, but when I run npm test using examples from angular-cli I get the following stacktrace error. The issue seems to be that the following lines don't produce the actual application structure as expected:
```
let appTree: UnitTestTree;
        beforeEach(() => {
            appTree = schematicRunner.runSchematic('workspace', workspaceOptions);
            appTree = schematicRunner.runSchematic('application', appOptions, appTree);
        });
```

### The log given by the failure
```
Failures:
1) simple-schematic with project works
  Message:
    Error: Invalid rule result: Function().
  Stack:
    Error: Invalid rule result: Function().
        at MergeMapSubscriber.input.pipe.operators_1.mergeMap.inputTree [as project] (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/@angular-devkit/schematics/src/rules/call.js:97:38)
        at MergeMapSubscriber._tryNext (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
        at MergeMapSubscriber._next (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
        at MergeMapSubscriber.Subscriber.next (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/Subscriber.js:64:18)
        at Observable._subscribe (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/observable/scalar.js:6:20)
        at Observable._trySubscribe (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/Observable.js:43:25)
        at Observable.subscribe (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/Observable.js:29:22)
        at MergeMapOperator.call (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/operators/mergeMap.js:35:23)
        at Observable.subscribe (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/Observable.js:24:22)
        at /Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/util/subscribeTo.js:22:31
  Message:
    TypeError: Cannot read property 'sourceRoot' of undefined
  Stack:
    TypeError: Cannot read property 'sourceRoot' of undefined
        at Object.buildDefaultPath (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/@schematics/angular/utility/project.js:8:26)
        at Object.setupOptions (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/src/simple-schematic/setup.js:13:34)
        at /Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/src/simple-schematic/index.js:11:17
        at MergeMapSubscriber.input.pipe.operators_1.mergeMap.inputTree [as project] (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/@angular-devkit/schematics/src/rules/call.js:77:24)
        at MergeMapSubscriber._tryNext (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
        at MergeMapSubscriber._next (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
        at MergeMapSubscriber.Subscriber.next (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/Subscriber.js:64:18)
        at Observable._subscribe (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/observable/scalar.js:6:20)
        at Observable._trySubscribe (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/Observable.js:43:25)
        at Observable.subscribe (/Users/jonathan.campos/Documents/code/blog/schematics/simple-schematic/node_modules/rxjs/internal/Observable.js:29:22)
```

### Desired functionality
Unit testing should work and create the workspace and application

### Mention any other details that might be useful
The link to the current code that is failing: https://github.com/jonbcampos/schematics/tree/master/simple-schematic

**Comment by tinesoft** [comment]
Hi @jonbcampos 
I was haaving the same issue with **v0.6.8** of `{@angular-devkit/core, @angular-devkit/schematics}`, 
Just updated to latest version (**v0.7.3**) and it is working fine now (typescript:2.9.0)

**Comment by jonbcampos** [comment]
@tinesoft you're right. that update fixed it, sadly it *should* work in the older version

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
