### ISSUE TITLE
portfinder options for port < 1024

### ISSUE THREAD

**Issue by Adam-Michalski** [angular/angular-cli#11814]
```
- [x] bug report -> please search issues before submitting
```

### Command
- [x] serve

### Versions
`Angular CLI: 6.1.2
Node: 8.9.4
OS: win32 x64
Angular: 6.1.1`

### Repro steps
`ng serve --port=80`

Cannot run with any port <1024 with or without elevated Administrator rights

### The log given by the failure
`Provided options.startPort(80) is less than 1024, which are cannot be bound.
Error: Provided options.startPort(80) is less than 1024, which are cannot be bound.
    at Object.exports.getPort (E:\Projects\pak-frontend\node_modules\portfinder\lib\portfinder.js:106:13)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (E:\Projects\pak-frontend\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\check-port.js:16:20)
    at Observable._trySubscribe (E:\Projects\pak-frontend\node_modules\rxjs\internal\Observable.js:43:25)
    at Observable.subscribe (E:\Projects\pak-frontend\node_modules\rxjs\internal\Observable.js:29:22)
    at DoOperator.call (E:\Projects\pak-frontend\node_modules\rxjs\internal\operators\tap.js:29:23)
    at Observable.subscribe (E:\Projects\pak-frontend\node_modules\rxjs\internal\Observable.js:24:22)
    at MergeMapOperator.call (E:\Projects\pak-frontend\node_modules\rxjs\internal\operators\mergeMap.js:35:23)
    at Observable.subscribe (E:\Projects\pak-frontend\node_modules\rxjs\internal\Observable.js:24:22)
    at DoOperator.call (E:\Projects\pak-frontend\node_modules\rxjs\internal\operators\tap.js:29:23)
    at Observable.subscribe (E:\Projects\pak-frontend\node_modules\rxjs\internal\Observable.js:24:22)
    at MergeMapOperator.call (E:\Projects\pak-frontend\node_modules\rxjs\internal\operators\mergeMap.js:35:23)
    at Observable.subscribe (E:\Projects\pak-frontend\node_modules\rxjs\internal\Observable.js:24:22)
    at DoOperator.call (E:\Projects\pak-frontend\node_modules\rxjs\internal\operators\tap.js:29:23)
    at Observable.subscribe (E:\Projects\pak-frontend\node_modules\rxjs\internal\Observable.js:24:22)
    at MergeMapOperator.call (E:\Projects\pak-frontend\node_modules\rxjs\internal\operators\mergeMap.js:35:23)
    at Observable.subscribe (E:\Projects\pak-frontend\node_modules\rxjs\internal\Observable.js:24:22)`

### Desired functionality
to run ng serve with ports <1024

### Mention any other details that might be useful
this commit 
https://github.com/indexzero/node-portfinder/commit/5bed64d495c61e2f466cb2b3391d664135fac5bd
with fragment

`  if(!options.startPort) {
    options.startPort = Number(options.port);
    if(options.startPort < 1024) {
      // ports < 1024 are system/well-known ports - need super user privilege to bind to them.
      throw Error('Provided options.startPort(' + options.startPort + ') is less than 1024, which are cannot be bound.');
    }
    if(options.stopPort < options.startPort) {
      throw Error('Provided options.stopPort(' + options.stopPort + 'is less than options.startPort (' + options.startPort + ')');
    }`

**Comment by Adam-Michalski** [comment]
Updating portfinder package to 1.0.16 fixes this isuue
