### ISSUE TITLE
cannot update ng cli with private registry

### ISSUE THREAD

**Issue by RodolpheGohard** [angular/angular-cli#11896]
Hello I have this error:

```
$ ng update @angular/cli
Your global Angular CLI version (6.0.8) is greater than your local
version (1.7.4). The local Angular CLI version is used.
 
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
events.js:183
      throw er; // Unhandled 'error' event
      ^
 
Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

It shoudn't try to reach npmjs because I set a private registry:
```
$ npm config list
; cli configs
user-agent = "npm/3.8.5 node/v8.11.3 win32 ia32"
 
; userconfig C:\Users\redacted\.npmrc
always-auth = false
cafile = "path.to.ca.pem"
email = "redacted@redacted"
init.author.email = " redacted@redacted "
init.author.name = "redacted "
msvs_version = "2015"
prefix = "path.to\\nodist\\bin"
proprietary-attribs = false
registry = "https://internal-redacted/nexus/repository/ext-all-npm-group/"
save-prefix = "~"
scripts-prepend-node-path = true
strict-ssl = false
```

I am behind a corporate proxy and firewall and can't just remove the private registry, as suggested in other related issues. I'm stuck here, can you help or suggest a workaround ?

Also, I tried some options with no success:
```
$ ng config -g cli.warnings.versionMismatch false
Your global Angular CLI version (6.0.8) is greater than your local
version (1.7.4). The local Angular CLI version is used.
 To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The specified command config is invalid. For available options, see `ng help`.
 

$ ng update --registry=https://internal-redacted/nexus/repository/ext-all-npm-group/ @angular/core
Your global Angular CLI version (6.0.8) is greater than your local
version (1.7.4). The local Angular CLI version is used. 
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The option '--registry' is not registered with the update command.Run `ng update --help` for a list of supported options.
events.js:183
      throw er; // Unhandled 'error' event
      ^
 
Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

**Comment by clydin** [comment]
It appears that the project version of the CLI is 1.7.4.  Updating Angular from 1.x to 6.x requires that the project version of the CLI be manually updated first via `npm install @angular/cli@6`.
