### ISSUE TITLE
Angular Universal - EmptyError: no elements in sequence

### ISSUE THREAD

**Issue by fredericojesus** [angular/angular-cli#11890]
Hey,

I've been trying to integrate Angular Universal with my app and it has been a big big struggle. We already fixed a lot of issues but we are already stuck on this one for 2 days now. Any help is really appreciated.

So the build runs fine, the error only occurs when we try to launch the website.
This is the error:

> EmptyError: no elements in sequence
    at new EmptyError (C:\Projects\beatstars-marketplace-v2\dist\server.js:147171:28)
    at C:\Projects\beatstars-marketplace-v2\dist\server.js:147226:518
    at Object.complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:170696:23)
    at TapSubscriber.module.exports.TapSubscriber._complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:125494:31)
    at TapSubscriber.module.exports.Subscriber.complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:59791:18)
    at TakeSubscriber.module.exports.Subscriber._complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:59809:26)
    at TakeSubscriber.module.exports.Subscriber.complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:59791:18)
    at FilterSubscriber.module.exports.Subscriber._complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:59809:26)
    at FilterSubscriber.module.exports.Subscriber.complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:59791:18)
    at DistinctUntilChangedSubscriber.module.exports.Subscriber._complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:59809:26)
    at DistinctUntilChangedSubscriber.module.exports.Subscriber.complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:59791:18)
    at MapSubscriber.module.exports.Subscriber._complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:59809:26)
    at MapSubscriber.module.exports.Subscriber.complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:59791:18)
    at State.module.exports.Subject.complete (C:\Projects\beatstars-marketplace-v2\dist\server.js:55713:21)
    at State.module.exports.State.ngOnDestroy (C:\Projects\beatstars-marketplace-v2\dist\server.js:131851:14)
    at callNgModuleLifecycle (C:\Projects\beatstars-marketplace-v2\dist\server.js:8840:31)
    at NgModuleRef_.module.exports.NgModuleRef_.destroy (C:\Projects\beatstars-marketplace-v2\dist\server.js:9458:9)
    at C:\Projects\beatstars-marketplace-v2\dist\server.js:4766:73
    at Array.forEach (<anonymous>)
    at PlatformRef.module.exports.PlatformRef.destroy (C:\Projects\beatstars-marketplace-v2\dist\server.js:4766:31)
    at C:\Projects\beatstars-marketplace-v2\dist\server.js:170216:22
    at ZoneDelegate.module.exports.ZoneDelegate.invoke (C:\Projects\beatstars-marketplace-v2\dist\server.js:394223:26)
    at Zone.module.exports.Zone.run (C:\Projects\beatstars-marketplace-v2\dist\server.js:393973:43)
    at C:\Projects\beatstars-marketplace-v2\dist\server.js:394707:34
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (C:\Projects\beatstars-marketplace-v2\dist\server.js:394256:31)
    at Zone.module.exports.Zone.runTask (C:\Projects\beatstars-marketplace-v2\dist\server.js:394023:47)
    at drainMicroTaskQueue (C:\Projects\beatstars-marketplace-v2\dist\server.js:394430:35)
    at module.exports.ZoneTask.invokeTask (C:\Projects\beatstars-marketplace-v2\dist\server.js:394335:21)
    at ZoneTask.invoke (C:\Projects\beatstars-marketplace-v2\dist\server.js:394320:48)
    at data.args.(anonymous function) (C:\Projects\beatstars-marketplace-v2\dist\server.js:395173:25)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

We researched a lot already and think is something related to rxjs but really not sure what.
We tried checking all of our first() usages all seemed alright. We tried removing all our canActivate guards, also didn't worked and we also tried adding and removing pathMatch: full from routes. These were the solutions for the problem that we found on the internet and nothing worked.

This is our package.json:

>{
  "name": "beatstars-marketplace-v2.1",
  "version": "0.1.105",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 8888 --disable-host-check",
    "dev": "ng serve",
    "hmr": "ng serve --hmr -e=hmr",
    "local": "ng serve --environment=local",
    "mock-api-dev": "concurrently \"ng serve\" \"node api/api.js\"",
    "build:dev": "node --max_old_space_size=4096 --optimize_for_size --stack_size=4096 ./node_modules/@angular/cli/bin/ng build --aot",
    "build:stage": "node --max_old_space_size=4096 --optimize_for_size --stack_size=4096 ./node_modules/@angular/cli/bin/ng build --prod --configuration stage",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.1.1",
    "@angular/cdk": "^6.4.2",
    "@angular/common": "6.1.1",
    "@angular/compiler": "6.1.1",
    "@angular/core": "6.1.1",
    "@angular/forms": "6.1.1",
    "@angular/http": "6.1.1",
    "@angular/material": "^6.4.2",
    "@angular/platform-browser": "6.1.1",
    "@angular/platform-browser-dynamic": "6.1.1",
    "@angular/platform-server": "6.1.1",
    "@angular/router": "6.1.1",
    "@ngrx/effects": "^6.0.1",
    "@ngrx/store": "^6.0.1",
    "@ngx-share/core": "^6.0.1",
    "@swimlane/ngx-charts": "^9.0.0",
    "@types/algoliasearch": "^3.27.5",
    "algoliasearch": "^3.29.0",
    "canvas-toBlob": "^1.0.0",
    "core-js": "^2.4.1",
    "cropperjs": "^1.0.0-rc",
    "d3": "^4.10.2",
    "dom-autoscroller": "^2.3.3",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.5",
    "ng-lazyload-image": "^4.0.0",
    "ng-pick-datetime": "^5.2.6",
    "ng2-dnd": "^5.0.2",
    "ng2-dragula": "^2.0.2",
    "ng2-file-upload": "^1.2.1",
    "ngrx-store-freeze": "^0.2.0",
    "ngx-clipboard": "^11.1.1",
    "ngx-color-picker": "^6.6.0",
    "ngx-cookie": "^4.0.1",
    "ngx-editor": "3.2.1",
    "ngx-infinite-scroll": "^6.0.1",
    "ngx-page-scroll": "^5.0.0",
    "ngx-slick": "^0.2.0",
    "reselect": "^3.0.0",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.2",
    "@angular/cli": "6.1.2",
    "@angular/compiler-cli": "6.1.1",
    "@angularclass/hmr": "^2.1.3",
    "@types/cropperjs": "^1.1.1",
    "@types/d3": "^4.10.1",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "^2.5.47",
    "@types/lodash": "^4.14.104",
    "@types/node": "^7.0.12",
    "@types/uuid": "^3.4.3",
    "@types/youtube": "^0.0.30",
    "codelyzer": "^4.0.1",
    "concurrently": "^3.5.0",
    "express": "^4.15.4",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "prettier": "1.13.7",
    "protractor": "~5.1.0",
    "ts-node": "^3.0.2",
    "tslint": "^5.7.0",
    "tslint-eslint-rules": "^4.1.1",
    "typescript": "2.9.2"
  }
}

Any help would be very appreciated.

**Comment by alexeagle** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
