### ISSUE TITLE
ng build can't have sourceMaps: true AND extractCss: true

### ISSUE THREAD

**Issue by catull** [angular/angular-cli#11926]
### Bug Report or Feature Request (mark with an `x`)
```
- x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 6.0.4
Node: 10.9.0
OS: linux x64
Angular: 6.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.4
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.4
@angular-devkit/schematics        0.6.4
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.4
@schematics/update                0.6.4
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

### Repro steps
Change this in angular.json:
```json
{
  "projects": {
      "your-project": {
         "architect": {
             "build": {
                "configurations": {
                   "production": {
                        "sourceMap": "true"
                   }
                }
             }
         }
      }
  }
}
```
`ng build --prod` gives you the error below.

If you also change
```json
   "extractCss": false,
```
the error goes away and the build succeeds.

### The log given by the failure
With `sourceMap`: true and `extractCss`: true, the error at build time is:

```log
 92% chunk asset optimization cleancss-webpack-plugin/####/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:298
      throw new Error('Invalid mapping: ' + JSON.stringify({
      ^

Error: Invalid mapping: {"generated":{"line":626,"column":195},"source":"/####/node_modules/@bisnode/ui/build/css/components/_forms.scss","original":{"line":2,"column":-11},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/####/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:298:13)
    at SourceMapGenerator_addMapping [as addMapping] (/####/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
    at /####/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:351:13
    at SourceNode_walk [as walk] (/####/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:230:9)
    at SourceNode_walk [as walk] (/####/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:226:13)
    at SourceNode_walk [as walk] (/####/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:226:13)
    at SourceNode_toStringWithSourceMap [as toStringWithSourceMap] (/####/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:342:8)
    at ConcatSource.proto.sourceAndMap (/####/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:32)
    at CachedSource.sourceAndMap (/####/node_modules/webpack-sources/lib/CachedSource.js:56:31)
    at files.filter.map.file (/####/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.js:52:48)
    at Array.map (<anonymous>)
    at hook (/####/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.js:44:18)
    at compilation.hooks.optimizeChunkAssets.tapPromise (/####/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.js:11:101)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/####/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/####/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/####/node_modules/webpack/lib/Compilation.js:952:36)
error Command failed with exit code 1.
```

### Desired functionality
Not sure, I can live with  `sourceMap`: true and `extractCss`: false.
All I need is better investigation assistance.

My use case is that I am investigating the startup behaviour and I need source maps temporarily switched on.  It won't stay that way.

Is this a known limitation ?

### Mention any other details that might be useful
None.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

I have tried to replicate this by using `scss` and I was able to generate a `sourcemap`
``json
{
	"version": 3,
	"sources": [
		"webpack:///./src/styles.scss"
	],
	"names": [],
	"mappings": "AAEC,QACC",
	"file": "styles.9500dc80ca2ab0fed6b7.css",
	"sourcesContent": [
		"/* You can add global styles to this file, and also import other style files */\r\na {\r\n\t&-hello {\r\n\t\tcolor: red;\t\r\n\t}\r\n}"
	],
	"sourceRoot": ""
}
```

From the above stacktrace it looks like might be something from `/####/node_modules/@bisnode/ui/build/css/components/_forms.scss`

Thanks

**Comment by filipesilva** [comment]
Closing as inactive.

**Comment by catull** [comment]
Actually, I have not reproduced it, upgraded to 6.1.5 there-about and have not seen the problem since.
Also, @bisnode/ui was updated since.
