### ISSUE TITLE
Maximum call stack size exceeded when exporting class with the same name as the parent folder

### ISSUE THREAD

**Issue by DarrenLamb** [angular/angular-cli#11933]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node: v8.11.1
npm: 5.6.0
Angular CLI: 6.1.4
OS: Windows 10

### Repro steps
Created a library with a class named the same as the parent folder and exported in a barrel.
- src
-- lib
--- hero
---- index.ts (export * from './hero'; export * from './hero.service'; )
---- hero.ts
---- hero.service.ts
--- my-lib.module.ts (import { HeroService } from './hero';)

Running `ng build my-lib` results in exception

https://github.com/DarrenLamb/call-stack-error

### The log given by the failure
`Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.normalize (path.js:428:14)
    at Object.join (path.js:549:18)
    at resolveModule (D:\git\personal\bug\demo-app\node_modules\@angular\compiler-cli\src\metadata\bundler.js:582:50)
    at MetadataBundler.exportAll (D:\git\personal\bug\demo-app\node_modules\@angular\compiler-cli\src\metadata\bundler.js:119:42)
    at MetadataBundler.exportAll (D:\git\personal\bug\demo-app\node_modules\@angular\compiler-cli\src\metadata\bundler.js:121:52)
    at MetadataBundler.exportAll (D:\git\personal\bug\demo-app\node_modules\@angular\compiler-cli\src\metadata\bundler.js:121:52)
    at MetadataBundler.exportAll (D:\git\personal\bug\demo-app\node_modules\@angular\compiler-cli\src\metadata\bundler.js:121:52)
    at MetadataBundler.exportAll (D:\git\personal\bug\demo-app\node_modules\@angular\compiler-cli\src\metadata\bundler.js:121:52)
    at MetadataBundler.exportAll (D:\git\personal\bug\demo-app\node_modules\@angular\compiler-cli\src\metadata\bundler.js:121:52)`

### Mention any other details that might be useful

Not sure if this is intended behavior as the angular style guide would suggest naming model classes `hero.model.ts`.

Thanks in advance.

**Comment by alan-agius4** [comment]
There are some issues with barrel files. 

For instance if you change your import to `import { HeroService } from './hero/index';` in my-`lib.module.ts` You will solve the `Maximum call stack size exceeded` and get another error https://github.com/angular/angular/issues/20931

A solution is instead of a barrel file if register your provider directly from using the service file. ex;

```ts
import { HeroService } from './hero/hero.service';
import { NgModule } from '@angular/core';

@NgModule({
  providers: [
    HeroService,
  ]
})
export class MyLibModule { }
```

That said, this issue is falls more under the [angular/angular](https://github.com/angular/angular) rather than the CLI. As it's more of a compiler bug.

**Comment by DarrenLamb** [comment]
Thanks Alan, that's actually the solution I ended up implementing!
Please feel free to close this if you think it doesn't belong.
