### ISSUE TITLE
Error trying to compile my project with this command: ng build -bh  ./ --prod

### ISSUE THREAD

**Issue by rojasjuniore** [angular/angular-cli#11938]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

**macOS :** High Sierra

**node --version**
v9.6.0

**npm --version**
6.1.0

**ng --version**

Angular CLI: 6.1.4
Node: 9.6.0
OS: darwin x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.3
@angular-devkit/build-angular     0.7.3
@angular-devkit/build-optimizer   0.7.3
@angular-devkit/build-webpack     0.7.3
@angular-devkit/core              0.7.3
@angular-devkit/schematics        0.7.4
@angular/cdk                      6.4.5-b9651df
@angular/cli                      6.1.4
@ngtools/webpack                  6.1.3
@schematics/angular               0.7.4
@schematics/update                0.7.4
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.9.2
    

### Repro steps

 **ng build -bh  ./ --prod**      

Project './' could not be found in workspace.
Error: Project './' could not be found in workspace.
    at Workspace.getProject (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/workspace.js:92:19)
    at Architect.getBuilderConfiguration (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:96:41)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/@angular/cli/models/architect-command.js:72:55)
    at MergeMapSubscriber._tryNext (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/rxjs/internal/Subscriber.js:64:18)
    at TapSubscriber._next (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/rxjs/internal/operators/tap.js:62:26)
    at TapSubscriber.Subscriber.next (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/Users/developer/Proyectos/ProyectoBNF/wldc/Frontend-Functions/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
-->

**Comment by hansl** [comment]
Single dash arguments are meant to be single letter (this was a breaking change between 5 and 6).

`-bh` will parsed as the combination of `-b -h`, with `./` being the project name to build. If you want `base-href` there is no shortcuts since 6.0.

Closing this as answered.
