### ISSUE TITLE
Errors during prod build with --source-map

### ISSUE THREAD

**Issue by tarundhillon** [angular/angular-cli#11941]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: v8.11.3
npm: 5.6.0
ng: 6.1.3

### Repro steps

node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng serve --prod --source-map

The above command works fine without --source-map but fails the --source-map flag. I have referred to #10897 but this seems like a different issue

### The log given by the failure

Date: 2018-08-19T06:50:16.563Z - Hash: b54fa1d2a4e800742ee8 - Time: 309023ms
```
1 unchanged chunks
chunk {0} 0.50d56b3d4b24418ee798.js, 0.50d56b3d4b24418ee798.js.map () 1.71 kB  [rendered]
chunk {1} 1.8b5d2545a291c2a45c96.js, 1.8b5d2545a291c2a45c96.js.map () 79.1 kB  [rendered]
chunk {2} 2.1e1308036d9fb129e215.js, 2.1e1308036d9fb129e215.js.map () 2.95 kB  [rendered]
chunk {3} 3.e6b27c4c680e2431dbb3.js, 3.e6b27c4c680e2431dbb3.js.map () 696 bytes  [rendered]
chunk {4} runtime.e6c89c2627446d52f1bf.js, runtime.e6c89c2627446d52f1bf.js.map (runtime) 1.97 kB [entry] [rendered]
chunk {5} styles.48357383ec78e68bc61f.css, styles.48357383ec78e68bc61f.css.map (styles) 398 kB [initial] [rendered]
chunk {6} polyfills.e6b48e9afa5a5e8bab2c.js, polyfills.e6b48e9afa5a5e8bab2c.js.map (polyfills) 59.7 kB [initial] [rendered]
chunk {7} main.ba5a0b15984cbff4777e.js, main.ba5a0b15984cbff4777e.js.map (main) 4.25 MB [initial] [rendered]

ERROR in ./node_modules/graphql/language/source.js
Module build failed: Error: Debug Failure. False expression.
    at getJSDocTags (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:13197:22)
    at getFirstJSDocTag (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:13205:24)
    at Object.getJSDocType (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:13173:19)
    at getContextualSignature (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:41002:32)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:44621:43)
    at checkExpressionWorker (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:45681:28)
    at checkExpression (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:45609:42)
    at checkExpressionCached (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:45457:38)
    at _loop_3 (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:30802:56)
    at getWidenedTypeFromJSSpecialPropertyDeclarations (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:30837:31)
    at getTypeOfVariableOrParameterOrProperty (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:31032:28)
    at getTypeOfSymbol (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:31242:24)
    at checkPropertyAccessExpressionOrQualifiedName (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:42338:53)
    at checkPropertyAccessExpression (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:42293:20)
    at checkExpressionWorker (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:45663:28)
    at checkExpression (/Users/tarun/Documents/Workspace/perspica-web-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:45609:42)

```
### Desired functionality

The build should without errors and generate the source-maps

### Mention any other details that might be useful

Also referred to https://github.com/Microsoft/TypeScript/issues/25067 and have tried to change the typescript version but still not much success. 

Any suggestions, will be much appreciated. 

Thanks

**Comment by tarundhillon** [comment]
Fixed it by rolling back  "@angular-devkit/build-angular": "^0.6.7",

https://github.com/angular/angular-cli/issues/11192
