### ISSUE TITLE
@angular-devkit/build-angular:server emits invalid code at the second and subsequent times when running in the watch mode

### ISSUE THREAD

**Issue by kimamula** [angular/angular-cli#11945]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

npm: 6.4.0
macOS High Sierra

```
Angular CLI: 6.1.4
Node: 8.9.0
OS: darwin x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.4
@angular-devkit/build-angular     0.7.4
@angular-devkit/build-optimizer   0.7.4
@angular-devkit/build-webpack     0.7.4
@angular-devkit/core              0.7.4
@angular-devkit/schematics        0.7.4
@angular/cli                      6.1.4
@ngtools/webpack                  6.1.4
@schematics/angular               0.7.4
@schematics/update                0.7.4
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.9.2
```

### Repro steps

```sh
$ git clone git@github.com:angular/universal-starter.git
$ cd universal-starter
$ ng update --all --force
$ yarn add typescript@2.9.2
$ ng run ng-universal-demo:server
$ wc -l dist/server/main.js
     530 dist/server/main.js
$ npm run compile:server && npm run serve:ssr
# Node Express server starts successfully
# quit with cmd+C
$ ng run ng-universal-demo:server --watch

# in a different tab of the terminal
$ wc -l dist/server/main.js
     530 dist/server/main.js
$ npm run compile:server && npm run serve:ssr
# Node Express server starts successfully
# quit with cmd+C
$ vi src/app/app.component.ts
# remove an empty line inside the AppComponent class and save
# wait for the second build to be completed
$ wc -l dist/server/main.js
     697 dist/server/main.js
$ npm run compile:server && npm run serve:ssr
# "Error: Cannot find module '@angular/router.ngfactory'"
$ vi src/app/app.component.ts
# add an empty line inside the AppComponent class and save
# wait for the third build to be completed
$ wc -l dist/server/main.js
     672 dist/server/main.js
$ npm run compile:server && npm run serve:ssr
# "Error: Cannot find module '@angular/router.ngfactory'"
```

### The log given by the failure

```
Error: Cannot find module '@angular/router.ngfactory'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.@angular/router.ngfactory (/Users/kenji_imamura/src/universal-starter/dist/server/main.js:646:18)
    at __webpack_require__ (/Users/kenji_imamura/src/universal-starter/dist/server/main.js:20:30)
    at Object../src/app/app.server.module.ngfactory.js (/Users/kenji_imamura/src/universal-starter/dist/server/main.js:200:26)
    at __webpack_require__ (/Users/kenji_imamura/src/universal-starter/dist/server/main.js:20:30)
    at Object../src/main.server.ts (/Users/kenji_imamura/src/universal-starter/dist/server/main.js:507:37)
    at __webpack_require__ (/Users/kenji_imamura/src/universal-starter/dist/server/main.js:20:30)
```

The cause of the error is the following line, which does not appear at the first time build.

```js
module.exports = require("@angular/router.ngfactory");
```

### Desired functionality

@angular-devkit/build-angular:server should emit valid code in the watch mode.

**Comment by clydin** [comment]
@zygimantas Thanks.  Yes the underlying issue is indeed the same.
