### ISSUE TITLE
ng g app my-app does not generate a new app

### ISSUE THREAD

**Issue by jdk339** [angular/angular-cli#11957]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
...
- [x] generate
...
```

### Versions

`node v8.11.2`
`macOS High Sierra 10.13.x`

### Repro steps

`ng g app my-app --debug`

### The log given by the failure

```An error occured:
ENOENT: no such file or directory, stat '/Users/user/workspace/node_modules/.bin/in-install'
Error: ENOENT: no such file or directory, stat '/Users/user/workspace/node_modules/.bin/in-install'
    at Object.fs.statSync (fs.js:948:11)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/user/workspace/node_modules/@angular-devkit/core/node/host.js:212:25)
    at Observable._trySubscribe (/Users/user/workspace/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/Users/user/workspace/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:29:22)
    at MapOperator.call (/Users/user/workspace/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:29:23)
    at Observable.subscribe (/Users/user/workspace/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:24:22)
    at SyncDelegateHost._doSyncCall (/Users/user/workspace/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.isDirectory (/Users/user/workspace/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:64:21)
    at recurse (/Users/user/workspace/node_modules/@angular-devkit/schematics/src/tree/filesystem.js:125:26)
    at recurse (/Users/user/workspace/node_modules/@angular-devkit/schematics/src/tree/filesystem.js:126:21)
```

I have run and re-run npm install multiple times after deleting 'node_modules'

### Desired functionality

Successful generation of app

### Mention any other details that might be useful

```
{
  "dependencies": {
    "@angular/animations": "6.0.1",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "6.0.1",
    "@angular/compiler": "6.0.1",
    "@angular/core": "6.0.1",
    "@angular/forms": "6.0.1",
    "@angular/http": "5.2.7",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "6.0.1",
    "@angular/platform-browser-dynamic": "6.0.1",
    "@angular/router": "6.0.1",
    "@angular/service-worker": "^5.2.10",
    "@ngrx/effects": "6.0.1",
    "@ngrx/entity": "^4.1.1",
    "@ngrx/router-store": "6.0.1",
    "@ngrx/store": "6.0.1",
    "@ngrx/store-devtools": "6.0.1",
    "@nrwl/nx": "6.0.2",
    "@okta/okta-angular": "^1.0.2",
    "@swimlane/ngx-datatable": "^11.3.2",
    "core-js": "^2.5.4",
    "moment": "^2.22.1",
    "ng2-file-upload": "^1.3.0",
    "ngx-chips": "^1.8.0",
    "npm": "^5.8.0",
    "rxjs": "6.0.0",
    "web-request": "^1.0.7",
    "zone.js": "^0.8.26",
    "rxjs-compat": "6.0.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.1",
    "@angular/cli": "6.0.1",
    "@angular/compiler-cli": "6.0.1",
    "@angular/language-service": "6.0.1",
    "@nrwl/schematics": "^6.2.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-marbles": "0.3.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngrx-store-freeze": "^0.2.2",
    "prettier": "1.10.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "^2.9.2"
  }
}
```

**Comment by jdk339** [comment]
I removed `node_modules`, reinstalled dependencies, and made some other changes. Now this is my error: `ast_utils_1.insertImport is not a function`

**Comment by jdk339** [comment]
Updated to `"@angular/cli": "^6.1.1"` and `"@ngrx/schematics": "^6.1.0"` and now I get a silent error (no error displayed, but no files generated either)

**Comment by jdk339** [comment]
After many hours of deliberation, I finally figured it out!!! First, I deleted my `node_modules` folder, then I updated each dependency in my `package.json` to match that of [https://github.com/nrwl/nx/blob/master/package.json](nrwl/nx/blob/master/package.json). Now, with the following versions in my `package.json` and after running `npm install`, I finally got `ng g app myapp` to work!!!

```
{
"dependencies": {
    "@angular/animations": "6.1.0",
    "@angular/cdk": "6.4.6",
    "@angular/common": "6.1.0",
    "@angular/compiler": "6.1.0",
    "@angular/core": "6.1.0",
    "@angular/forms": "6.1.0",
    "@angular/http": "^6.1.4",
    "@angular/material": "^6.4.6",
    "@angular/platform-browser": "6.1.0",
    "@angular/platform-browser-dynamic": "6.1.0",
    "@angular/router": "6.1.0",
    "@angular/service-worker": "^6.1.4",
    "@ngrx/effects": "6.0.1",
    "@ngrx/entity": "^4.1.1",
    "@ngrx/router-store": "6.0.1",
    "@ngrx/store": "6.0.1",
    "@ngrx/store-devtools": "6.0.1",
    "@nrwl/nx": "^6.2.1",
    "core-js": "^2.5.4",
    "npm": "^5.8.0",
    "rxjs": "^6.2.2",
    "rxjs-compat": "6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.7.4",
    "@angular/cli": "^6.1.1",
    "@angular/compiler-cli": "6.1.0",
    "@angular/language-service": "6.1.0",
    "@ngrx/schematics": "^6.1.0",
    "@nrwl/schematics": "^6.1.0-beta.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^4.4.4",
    "jasmine-core": "~2.99.1",
    "jasmine-marbles": "0.3.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngrx-store-freeze": "^0.2.2",
    "prettier": "1.10.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "5.11.0",
    "typescript": "~2.7.2"
  }

```
