### ISSUE TITLE
EACCESS error running ng post clean install ember-cli.json

### ISSUE THREAD

**Issue by JavascriptMick** [angular/angular-cli#1198]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Mac OSX Yosemite 10.10.5

2. Versions ( I was able to run after fix below)
bash-3.2$ ng -v
(node:3383) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.8
node: 6.2.2
os: darwin x64

3. Repro steps. 
Clean install of Node (nvm)
npm install -g angular-cli
ng -v...

4. The log given by the failure. Normally this include a stack trace and some
bash-3.2$ ng -v
(node:3373) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/Users/michael/.nvm/versions/node/v6.2.2/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/michael/.config/configstore/ember-cli.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.create.all.get (/Users/michael/.nvm/versions/node/v6.2.2/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/Users/michael/.nvm/versions/node/v6.2.2/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/configstore/index.js:28:44)
    at clientId (/Users/michael/.nvm/versions/node/v6.2.2/lib/node_modules/angular-cli/node_modules/ember-cli/lib/cli/index.js:22:21)
    at module.exports (/Users/michael/.nvm/versions/node/v6.2.2/lib/node_modules/angular-cli/node_modules/ember-cli/lib/cli/index.js:65:19)
    at module.exports (/Users/michael/.nvm/versions/node/v6.2.2/lib/node_modules/angular-cli/lib/cli/index.js:106:10)
    at /Users/michael/.nvm/versions/node/v6.2.2/lib/node_modules/angular-cli/bin/ng:31:5
    at /Users/michael/.nvm/versions/node/v6.2.2/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:46:14

5. Mention any other details that might be useful.
I was able to fix it by running

cd /Users/michael/.config/configstore/
sudo chown -R $(whoami) ember-cli.json
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by burhan** [comment]
You probably ran a command with `sudo` which changed the permissions to root on the directory.

**Comment by filipesilva** [comment]
I agree with @burhan, this is a permissions issue related to using sudo. You seem to have reached the same conclusion as at the end of the issue you mention that you changed permissions on the file.
