### ISSUE TITLE
While making a build of angular-6 application am getting this error how i can resolve this? 

### ISSUE THREAD

**Issue by fahidarif** [angular/angular-cli#12017]
F:\practice\ang-node\frontend>ng build --prod

Date: 2018-08-28T04:08:06.648Z
Hash: 61fab25db19a36ad55ca
Time: 89374ms
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.78fc82606a60ff243473.css (styles) 193 kB [initial] [rendered]
chunk {2} polyfills.7a0e6866a34e280f48e7.js (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.b6f6160fdfad736b2ba4.js (main) 1.18 MB [initial] [rendered]

ERROR in ./node_modules/angular2-jwt/angular2-jwt.js
Module build failed: Error: Debug Failure. False expression.
    at getJSDocTags (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:13197:22)
    at getFirstJSDocTag (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:13205:24)
    at Object.getJSDocTypeTag (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:13154:19)
    at checkParenthesizedExpression (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45628:56)
    at checkExpressionWorker (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45676:28)
    at checkExpression (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45609:42)
    at checkBinaryLikeExpression (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45155:29)
    at checkBinaryExpression (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45147:20)
    at checkExpressionWorker (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45702:28)
    at checkExpression (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45609:42)
    at checkExpressionCached (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45457:38)
    at getTypeOfExpression (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45577:28)
    at checkDeclarationInitializer (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45469:24)
    at getTypeForVariableLikeDeclaration (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:30738:28)
    at getWidenedTypeForVariableLikeDeclaration (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:30961:24)
    at getTypeOfVariableOrParameterOrProperty (F:\practice\ang-node\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:31062:28)

F:\practice\ang-node\frontend>

**Comment by erickchidubem** [comment]
please i have been having this issue for two weeks now, I don't know where to go from here :'(
