### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by EsterBeltrami** [angular/angular-cli#12036]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node v10.7.0
npm 6.4.0
```
                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.28.3
node: 10.7.0
os: darwin x64
@angular/animations: 5.2.0
@angular/common: 5.2.0
@angular/compiler: 5.2.0
@angular/core: 5.2.0
@angular/forms: 5.2.0
@angular/http: 5.2.0
@angular/platform-browser: 5.2.0
@angular/platform-browser-dynamic: 5.2.0
@angular/router: 5.2.0
@angular/cli: 1.7.3
@angular/compiler-cli: 5.2.0
@angular/language-service: 5.2.0
```
macOS High Sierra

### Repro steps
npm test

### The log given by the failure

```
MacBook-Air-di-Ester:webapp Ester$ npm test

> Sing@4.2.0 test /Users/Ester/Projects/webapp
> ng test

The "path" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Promise (/Users/Ester/Projects/webapp/node_modules/@angular/cli/tasks/test.js:25:38)
    at new Promise (<anonymous>)
    at Class.run (/Users/Ester/Projects/webapp/node_modules/@angular/cli/tasks/test.js:23:16)
    at Class.run (/Users/Ester/Projects/webapp/node_modules/@angular/cli/commands/test.js:122:25)
    at resolve (/Users/Ester/Projects/webapp/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (/Users/Ester/Projects/webapp/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/Users/Ester/Projects/webapp/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
npm ERR! Test failed.  See above for more details.
```

### Desired functionality

Test the app

### Mention any other details that might be useful

Attach config files like
package.json 
angular-cli.json 

[Archive.zip](https://github.com/angular/angular-cli/files/2332764/Archive.zip)

**Comment by clydin** [comment]
The latest version of the CLI is 6.1.5.  The version reported above is a 1.0.0-beta.28.3 which is both outdated and a pre-release version.  Please update to a stable release as this version is no longer supported.
