### ISSUE TITLE
angular-cli project generator error

### ISSUE THREAD

**Issue by AbdoulazizMaharou** [angular/angular-cli#12079]
Hello, When i try to generate angular projet using angular-cli(ng new project_name), i get the following error:
`module.js:549
    throw err;
    ^

Error: Cannot find module 'json-schema-traverse'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/ajv/lib/compile/resolve.js:7:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
`
Please help me

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

Please try to remove node_modules and reinstall them.
