### ISSUE TITLE
TypeError: sink._addParentTeardownLogic is not a function upgrading rxjs from 6.2 to 6.3

### ISSUE THREAD

**Issue by skonx** [angular/angular-cli#12072]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
ng version:
Angular CLI: 6.1.5
Node: 8.11.3
OS: darwin x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.7.5
@angular/cdk                       6.4.6
@angular/cli                       6.1.5
@angular/material                  6.4.6
@angular/material-moment-adapter   6.4.6
@ngtools/webpack                   6.0.8
@schematics/angular                0.7.5
@schematics/update                 0.7.5
rxjs                               6.3.1
typescript                         2.9.2
webpack                            4.8.3

### The log given by the failure
ng serve -o will fail with error: 

/mypath/webapp/node_modules/rxjs/internal/Observable.js:27
            sink._addParentTeardownLogic(this.source || (config_1.config.useDeprecatedSynchronousErrorHandling && !sink.syncErrorThrowable) ?
                 ^

TypeError: sink._addParentTeardownLogic is not a function
    at Observable.subscribe (/mypath/webapp/node_modules/rxjs/internal/Observable.js:27:18)
    at MergeMapOperator.call (/mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:35:23)
    at Observable.subscribe (/mypath/webapp/node_modules/rxjs/internal/Observable.js:24:22)
    at MapOperator.call (/mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/map.js:29:23)
    at Observable.subscribe (/mypath/webapp/node_modules/rxjs/internal/Observable.js:24:22)
    at /mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToObservable.js:10:20
    at Object.subscribeToResult (/mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
    at MergeMapSubscriber._next (/mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at TapSubscriber._next (/mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/tap.js:62:26)
    at TapSubscriber.Subscriber.next (/mypath/webapp/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at portfinder.getPort (/mypath/webapp/node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/check-port.js:26:21)
    at /mypath/webapp/node_modules/portfinder/lib/portfinder.js:160:14
    at /mypath/webapp/node_modules/portfinder/node_modules/async/lib/async.js:52:16

### Mention any other details that might be useful
I've checked if there were a standalone declaration (import) of Observables, map() or tap() but nothing at all :(

**Comment by alan-agius4** [comment]
The root cause is from rxjs.

Issue tracked: 
https://github.com/ReactiveX/rxjs/issues/4077

**Comment by skonx** [comment]
Thanks. Keep waiting to be solved ;)

**Comment by skonx** [comment]
Hi @alan-agius4. 
I've cleaned the npm cache, removed the node_modules in order to start on a clean stuff but... the issue remains with rxjs 6.3.2.

Angular CLI: 6.1.5
Node: 8.11.3
OS: darwin x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.7.5
@angular/cdk                       6.4.7
@angular/cli                       6.1.5
@angular/material                  6.4.7
@angular/material-moment-adapter   6.4.7
@ngtools/webpack                   6.0.8
@schematics/angular                0.7.5
@schematics/update                 0.7.5
rxjs                               6.3.2
typescript                         2.9.2
webpack                            4.8.3

**Comment by skonx** [comment]
https://github.com/ReactiveX/rxjs/issues/4070#issuecomment-419041214
