### ISSUE TITLE
AngularCompilerPlugin failing in combination with IgnorePlugin

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12121]
_From @eseliger on April 18, 2018 6:18_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

`node --version v9.11.1`
`npm --version 5.8.0`
`macOS 10.13.4`

### Repro steps
Use the webpack `IgnorePlugin`, in my case, we are using `js-yaml`, which uses esprima for some functionality which we don't use so we have a webpack config with this plugin `new IgnorePlugin(/esprima/)`

### The log given by the failure
```
69% [1] building modules 1537/1540 modules 3 active ...les/js-yaml/lib/js-yaml/type/merge.js
/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:483
                    if (this.done && (request.request.endsWith('.ts')
                                              ^
TypeError: Cannot read property 'request' of undefined
    at NormalModuleFactory.nmf.plugin (/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:483:47)
    at /node_modules/tapable/lib/Tapable.js:270:14
    at Object.resolveWithPaths (/node_modules/@ngtools/webpack/src/paths-plugin.js:9:9)
    at NormalModuleFactory.nmf.plugin (/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:495:32)
    at /node_modules/tapable/lib/Tapable.js:270:14
    at IgnorePlugin.checkIgnore (/node_modules/webpack/lib/IgnorePlugin.js:54:11)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/node_modules/tapable/lib/Tapable.js:272:13)
    at NormalModuleFactory.create (/node_modules/webpack/lib/NormalModuleFactory.js:220:8)
    at semaphore.acquire (/node_modules/webpack/lib/Compilation.js:242:13)
    at process._tickCallback (internal/process/next_tick.js:176:11)
```

### Desired functionality
The build should still pass

### Mention any other details that might be useful
In this particular line, it is assumed request is always a valid request object, but that is not the case for ignored plugins, where it is `undefined`. I recommend just checking for 
```
if (this.done &&* request && *(request.request.endsWith('.ts')
```

_Copied from original issue: angular/devkit#728_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
