### ISSUE TITLE
Unable to RUN ng commands.

### ISSUE THREAD

**Issue by mohitidol** [angular/angular-cli#12173]
I am not able to create the Compnent using ng g c comp_name.

I realised that in my package json I do not have 

"@angular/cli": "^5.0.0",

how ever when I check the version. Atached the screen shot. Need help urgently.

![error](https://user-images.githubusercontent.com/23230112/45072344-31e0e380-b0f8-11e8-8b92-eee9ba31568f.PNG)

**When I run ng g c zippy**

Below is the error

$ ng g c zippy
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\mohit_mathur\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:44:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\mohit_mathur\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:31:21)
    at GenerateCommand._loadWorkspace (C:\Users\mohit_mathur\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:292:29)
    at GenerateCommand.<anonymous> (C:\Users\mohit_mathur\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:57:18)
    at Generator.next (<anonymous>)
    at C:\Users\mohit_mathur\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mohit_mathur\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:10:12)
    at GenerateCommand.initialize (C:\Users\mohit_mathur\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:56:16)
    at GenerateCommand.<anonymous> (C:\Users\mohit_mathur\AppData\Roaming\npm\node_modules\@angular\cli\commands\generate.js:41:40)

**Comment by alan-agius4** [comment]
Does the `angular.json` exist?

**Comment by mohitidol** [comment]
No :(

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by claystation** [comment]
@mohitidol Are you running those commands while inside the project root directory? When i randomly run a `ng generate` command in a non angular project directory (i.e. Linus home directory), i get the same error. Please make sure you run the command in your project root directory. 

You probably do not have `"@angular/cli": "^5.0.0",` because you installed it globally. But your `ng` command works, so no worries there.
