### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with ng serve and ng build giving same error on mac

### ISSUE THREAD

**Issue by hashmee** [angular/angular-cli#1220]
ng serve
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/dispatchtrack/angular123/tmp/broccoli_type_script_compiler-input_base_path-zrvOfcOx.tmp/0/src/typings.d.ts (5, 1): File '/Users/dispatchtrack/angular123/tmp/broccoli_type_script_compiler-input_base_path-zrvOfcOx.tmp/0/typings/browser.d.ts' not found.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/angular2-app.js:321:18)
    at Angular2App._buildTree (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/angular2-app.js:116:23)
    at new Angular2App (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/dispatchtrack/angular123/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

**Comment by hashmee** [comment]
ng -v                                                                                                                                                 1 ↵
angular-cli: 1.0.0-beta.8
node: 4.4.6
os: darwin x64

**Comment by billdwhite** [comment]
same issue here

**Comment by hashmee** [comment]
@billdwhite if you are on mac
go to your iterm 
cd /.config
sudo chmod -R (777 or 666) configstore/
and install ng new app
ng serve
it should work(hopefully)

**Comment by billdwhite** [comment]
Thanks.  I fixed it by just finding a browser.d.ts file and dumping it in the directory mentioned in the stack trace. I was not getting this after creating a new project by the way; instead, I was working in a project that had just had some package.json version updates.
