### ISSUE TITLE
TypeError: sink._addParentTeardownLogic is not a function upgrading cli 6.1.5 -> 6.2.1

### ISSUE THREAD

**Issue by smiera** [angular/angular-cli#12239]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 6.2.1
Node: 10.1.0
OS: darwin x64
Angular: 6.1.7
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.7.5
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.7.5
@angular-devkit/schematics         0.7.5
@angular/cli                       6.2.1
@angular/pwa                       0.7.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.7.5
@schematics/update                 0.8.1
ng-packagr                         3.0.6
rxjs                               6.3.2
typescript                         2.9.2
webpack                            4.8.3

### Repro steps
ng b --prod xcore

### The log given by the failure
Building Angular Package
sink._addParentTeardownLogic is not a function
TypeError: sink._addParentTeardownLogic is not a function
    at Observable.subscribe (./node_modules/rxjs/internal/Observable.js:27:18)
    at ./node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToObservable.js:10:20
    at Object.subscribeToResult (./node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (./node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (./node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
    at MergeMapSubscriber._next (./node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (./node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MapSubscriber._next (./node_modules/@angular/cli/node_modules/rxjs/internal/operators/map.js:52:26)
    at MapSubscriber.Subscriber.next (./node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:64:18)
    at TapSubscriber._next (./node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:62:26)
npm ERR! code ELIFECYCLE

### Mention any other details that might be useful
Build success with rxjs version: 6.2.2

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI and Devkit packages versions. Make sure that you remove any lock file and do a fresh npm installation.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
