### ISSUE TITLE
Warning from ng update

### ISSUE THREAD

**Issue by fluky** [angular/angular-cli#12279]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Node: v10.10.0
NPM 6.4.1

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.2.2
Node: 10.10.0
OS: darwin x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.2
@angular-devkit/build-angular      0.8.2
@angular-devkit/build-ng-packagr   0.8.2
@angular-devkit/build-optimizer    0.8.2
@angular-devkit/build-webpack      0.8.2
@angular-devkit/core               0.8.2
@angular-devkit/schematics         0.8.2
@angular/cli                       6.2.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.2
@schematics/angular                0.8.2
@schematics/update                 0.8.2
ng-packagr                         4.1.1
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.19.0
```

### Repro steps
run ng update

### The log given by the failure
WARNING: This command may not execute successfully. The package/collection may not support the 'targets' field within '/Users/e041115/dev/dispute/ui/angular.json'. This can be corrected by renaming the following 'targets' fields to 'architect':
1) Line: 12; Column: 10
2) Line: 126; Column: 10
3) Line: 155; Column: 10
4) Line: 190; Column: 10

### Desired functionality
Making these changes is causes ng update not to warn but then all other commands fail as the angular.json file no longer conforms to the schema.  Either update the schema or remove this warning.

### Mention any other details that might be useful
Caused by this change: 
https://github.com/angular/angular-cli/commit/9e7391c685e7b296e68e21fedb1cc7989a9405c8#diff-9dfd89ed6a15b8cb93c53b62edc7eb85

**Comment by fluky** [comment]
```
 10          "prefix": "app",
 11          "schematics": {},
 12          "targets": {
 13             "build": {
 14                "builder": "@angular-devkit/build-angular:browser",
```
```
124          "root": "e2e/",
125          "projectType": "application",
126          "targets": {
127             "e2e": {
128                "builder": "@angular-devkit/build-angular:protractor",
```
```
153          "projectType": "library",
154          "prefix": "lib",
155          "targets": {
156             "build": {
157                "builder": "@angular-devkit/build-ng-packagr:build",
```
```
188          "projectType": "library",
189          "prefix": "lib",
190          "targets": {
191             "build": {
192                "builder": "@angular-devkit/build-ng-packagr:build",
193                "options": {
```

**Comment by fluky** [comment]
If I rename all of those "targets" to "architect" the update warning goes away but then, as mentioned, everything else fails because the json no longer validates against the schema.

**Comment by fluky** [comment]
Have you even tried this?  I mean it's not hard to duplicate and I even pointed to the change made 3 days ago that caused it....

```
ng test
Schema validation failed with the following errors:
  Data path "['build']" should have required property 'builder'.
Error: Schema validation failed with the following errors:
  Data path "['build']" should have required property 'builder'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/e041115/dev/dispute/ui/node_modules/@angular-devkit/core/src/workspace/workspace.js:210:42)
    at MergeMapSubscriber._tryNext (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MapSubscriber._next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/map.js:52:26)
    at MapSubscriber.Subscriber.next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/Subscriber.js:64:18)
    at SwitchMapSubscriber.notifyNext (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/switchMap.js:77:26)
```

**Comment by fluky** [comment]
In fact I can duplicate this with brand new everything:

1. npm uninstall -g @angular/cli (to make sure I have the latest version)
2. npm install -g @angular/cli
3. ng new foo
4. cd foo
5. ng test

```
Schema validation failed with the following errors:
  Data path "['build']" should have required property 'builder'.
Error: Schema validation failed with the following errors:
  Data path "['build']" should have required property 'builder'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/e041115/dev/dispute/ui/node_modules/@angular-devkit/core/src/workspace/workspace.js:210:42)
    at MergeMapSubscriber._tryNext (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MapSubscriber._next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/map.js:52:26)
    at MapSubscriber.Subscriber.next (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/Subscriber.js:64:18)
    at SwitchMapSubscriber.notifyNext (/Users/e041115/dev/dispute/ui/node_modules/rxjs/internal/operators/switchMap.js:77:26)
```

**Comment by godcong** [comment]
my angular-cli is updated to 6.2.2 
i changed [targets] to [architect]
fixed this warning

**Comment by mgechev** [comment]
Seems that newer versions of the CLI fix the problem. Let's close the issue for now.
