### ISSUE TITLE
How do I install jQuery and select2 typings so I can build remotely?

### ISSUE THREAD

**Issue by rkralston** [angular/angular-cli#1230]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
win 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.8
node: 6.1.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng buiuld on a fresh clone of repo

4. The log given by the failure. Normally this include a stack trace and some
   more information.
C:\Users\rkr0079\Source\Repos\nrmn-account-test>ng build -prod
(node:14676) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Build failed.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/home/home.component.ts (23, 7): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (57, 7): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (65, 7): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (91, 5): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (92, 18): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (101, 5): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (102, 18): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (111, 5): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (112, 18): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (121, 5): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (122, 18): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (131, 5): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (133, 48): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (135, 5): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (136, 18): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (155, 75): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (157, 7): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (160, 79): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (162, 7): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (165, 68): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (167, 7): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (170, 67): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (172, 7): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (175, 72): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (177, 7): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (180, 73): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/app/profile/profile.component.ts (182, 7): Cannot find name 'jQuery'.
  C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/src/typings.d.ts (2, 1): File 'C:/Users/rkr0079/Source/Repos/nrmn-account-test/tmp/broccoli_type_script_compiler-input_base_path-AugULTz0.tmp/0/typings/tsd.d.ts' not found.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\lib\broccoli\angular2-app.js:321:18)
    at Angular2App._buildTree (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\lib\broccoli\angular2-app.js:116:23)
    at new Angular2App (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\Users\rkr0079\Source\Repos\nrmn-account-test\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\rkr0079\Source\Repos\nrmn-account-test\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------

I had manually installed and configured the typings in my original directory. Not sure how to make that portable.
> > Thanks! We'll be in touch soon.

**Comment by slmyers** [comment]
This issue might be helpful #1204

**Comment by rkralston** [comment]
I do not want to distribute jQuery. I want to include jquery.d.ts & select2.d.ts in my typings and reference both libraries from their CDNs.

I have them installed and configured in my development environment. However, my automated build is not pulling the *.d.ts files.

I think I need to add tsd install to the postinstall. I need to do a bit more research.

**Comment by rkralston** [comment]
Have you guys upgraded to typings 1.3? The structure is very different. They've done away with ambient and browser.

I upgraded my project for another reason and now I cannot run a build machine since typings install does not do ambient and browser.

I am stuck building on my dev machine with has all that installed already.

**Comment by filipesilva** [comment]
Using a CDN to get some packages is possible using SystemJS, but you'll have to check details for it in the SystemJS docs.

This project is still using typings 0.8. You can update your generated project yourself though, the CLI doesn't call anything typings related after `ng new`.

**Comment by rkralston** [comment]
We just added the *.d.ts files and upgraded typings. It is working well. Please close.

Upgrading to 1.3.0 typings was a snap. We have posted our steps. Someone else did the same thing a little differently.
