### ISSUE TITLE
`npm run build` fails for angular-cli

### ISSUE THREAD

**Issue by jot-hub** [angular/angular-cli#12424]
Following: https://www.npmjs.com/package/@angular/cli#development-hints-for-working-on-angular-cli to build angular-cli.

**~angular-cli [master ≡ +1 ~0 -0 !]> npm run build**
```
> @angular/devkit-repo@0.0.0 build ~\angular-cli
> npm run admin -- build


> @angular/devkit-repo@0.0.0 admin ~\angular-cli
> node ./bin/devkit-admin "build"

Error while running script "~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts":
TypeError: Cannot read property 'endsWith' of null
    at Function.Module._resolveFilename (~\angular-cli\lib\bootstrap-local.js:143:38)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..ts (~\angular-cli\lib\bootstrap-local.js:93:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Error while running script "~\angular-cli\packages\angular_devkit\core\src\json\schema\index.ts":
TypeError: Cannot read property 'endsWith' of null
    at Function.Module._resolveFilename (~\angular-cli\lib\bootstrap-local.js:143:38)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..ts (~\angular-cli\lib\bootstrap-local.js:93:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Error while running script "~\angular-cli\packages\angular_devkit\core\src\json\index.ts":
TypeError: Cannot read property 'endsWith' of null
    at Function.Module._resolveFilename (~\angular-cli\lib\bootstrap-local.js:143:38)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..ts (~\angular-cli\lib\bootstrap-local.js:93:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Error while running script "~\angular-cli\packages\angular_devkit\core\src\workspace\workspace.ts":
TypeError: Cannot read property 'endsWith' of null
    at Function.Module._resolveFilename (~\angular-cli\lib\bootstrap-local.js:143:38)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..ts (~\angular-cli\lib\bootstrap-local.js:93:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Error while running script "~\angular-cli\packages\angular_devkit\core\src\workspace\index.ts":
TypeError: Cannot read property 'endsWith' of null
    at Function.Module._resolveFilename (~\angular-cli\lib\bootstrap-local.js:143:38)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..ts (~\angular-cli\lib\bootstrap-local.js:93:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Error while running script "~\angular-cli\packages\angular_devkit\core\src\experimental.ts":
TypeError: Cannot read property 'endsWith' of null
    at Function.Module._resolveFilename (~\angular-cli\lib\bootstrap-local.js:143:38)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..ts (~\angular-cli\lib\bootstrap-local.js:93:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Error while running script "~\angular-cli\packages\angular_devkit\core\src\index.ts":
TypeError: Cannot read property 'endsWith' of null
    at Function.Module._resolveFilename (~\angular-cli\lib\bootstrap-local.js:143:38)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..ts (~\angular-cli\lib\bootstrap-local.js:93:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Error while running script "~\angular-cli\packages\angular_devkit\core\node\resolve.ts":
TypeError: Cannot read property 'endsWith' of null
    at Function.Module._resolveFilename (~\angular-cli\lib\bootstrap-local.js:143:38)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..ts (~\angular-cli\lib\bootstrap-local.js:93:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
~\angular-cli\lib\bootstrap-local.js:97
    throw err;
    ^

TypeError: Cannot read property 'endsWith' of null
    at Function.Module._resolveFilename (~\angular-cli\lib\bootstrap-local.js:143:38)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (~\angular-cli\packages\angular_devkit\core\src\json\schema\registry.ts:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.require.extensions..ts (~\angular-cli\lib\bootstrap-local.js:93:14)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/devkit-repo@0.0.0 admin: `node ./bin/devkit-admin "build"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular/devkit-repo@0.0.0 admin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~\AppData\Roaming\npm-cache\_logs\2018-10-01T17_24_23_154Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/devkit-repo@0.0.0 build: `npm run admin -- build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @angular/devkit-repo@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~\AppData\Roaming\npm-cache\_logs\2018-10-01T17_24_23_235Z-debug.log
```

**Comment by jot-hub** [comment]
is this related to defe0cca0685c5b0?

**Comment by alan-agius4** [comment]
Closing as it doesn't follow the template.
