### ISSUE TITLE
Requesting --help for ng commands fails with "Local workspace file ('angular.json') could not be found"

### ISSUE THREAD

**Issue by varadero** [angular/angular-cli#12454]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Windows 10
NodeJS 9.8.0
NPM 6.4.1
Angular CLI 6.1.3 and 6.2.4
```
Angular CLI: 6.2.4
Node: 9.8.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.4
@angular-devkit/core         0.8.4
@angular-devkit/schematics   0.8.4
@angular/cli                 6.2.4
@schematics/angular          0.8.4
@schematics/update           0.8.4
rxjs                         6.2.2
typescript                   2.9.2
```

### Repro steps

Go to arbitrary folder that doesn't contain angular cli application (specifically angular.json file) and execute  ```ng build --help```

### The log given by the failure

```
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\Svincho\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:44:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\Svincho\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:31:21)
    at BuildCommand._loadWorkspaceAndArchitect (C:\Users\Svincho\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:189:32)
    at BuildCommand.<anonymous> (C:\Users\Svincho\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:55:25)
    at Generator.next (<anonymous>)
    at C:\Users\Svincho\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Svincho\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:10:12)
    at BuildCommand.initialize (C:\Users\Svincho\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:54:16)
    at Object.<anonymous> (C:\Users\Svincho\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:101:23)
```

### Desired functionality

Help must be available regardless whether there is angular cli project in the current folder or not.

### Mention any other details that might be useful

```ng new --help``` does not produce error and gives help information.
```ng build --help``` in angular cli project folder gives help for the ```build``` command as expected.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
