### ISSUE TITLE
ng run project:server universal with custom environment not possible

### ISSUE THREAD

**Issue by templth** [angular/angular-cli#12472]
### Versions

```Angular CLI: 6.2.3
Node: 9.4.0
OS: linux x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.3
@angular-devkit/build-angular     0.8.3
@angular-devkit/build-optimizer   0.8.3
@angular-devkit/build-webpack     0.8.3
@angular-devkit/core              0.8.3
@angular-devkit/schematics        0.8.3
@angular/cdk                      6.4.7
@angular/cli                      6.2.3
@angular/flex-layout              6.0.0-beta.18
@ngtools/webpack                  6.2.3
@schematics/angular               0.8.3
@schematics/update                0.8.3
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
```

### Repro steps

I want to have a custom environment named `staging`. I updated the configuration in the `angular.json` file accordingly:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "myproject-website": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/myproject-website",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "staging": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.staging.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "myproject-website:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "myproject-website:build:production"
            },
            "staging": {
              "browserTarget": "myproject-website:build:staging"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "myproject-website:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/myproject-website-server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            },
            "staging": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.staging.ts"
                }
              ]
            }
          }
        }
      }
    },
    "myproject-website-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "myproject-website:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "myproject-website:serve:production"
            },
            "staging": {
              "devServerTarget": "myproject-website:serve:staging"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "myproject-website",
  "cli": {
    "defaultCollection": "@ngrx/schematics"
  }
}
```

The `environment.staging.ts` file is very simple:

```
export const environment = {
  production: true,
  env: 'staging'
};
```

I compiled my application using the following commands:

```
ng run myproject-website:build --output-path dist/browser/en --i18n-locale=en --configuration=staging --i18n-file=src/i18n/messages.en.xlf --i18n-format=xlf

ng run myproject-website:server --output-path dist/server/en --i18n-locale=en --configuration=staging --i18n-file=src/i18n/messages.en.xlf --i18n-format=xlf
```

and the server script with:

```
webpack --production --config webpack.server.config.js
```

### The log given by the failure

The application compiles successfully.

When trying to launch the server script with:

```
node ./dist/server.js
```

I got the following error:

```
/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:8121
        throw new Error('Cannot enable prod mode after platform setup.');
        ^

Error: Cannot enable prod mode after platform setup.
    at enableProdMode (/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:8121:15)
    at Module../src/main.server.ts (/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:147274:73)
    at __webpack_require__ (/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:146581:30)
    at Object.0 (/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:147289:18)
    at __webpack_require__ (/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:146581:30)
    at /home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:146645:18
    at Object.<anonymous> (/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:146648:10)
    at __webpack_require__ (/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:20:30)
    at Module.<anonymous> (/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:163:20)
    at __webpack_require__ (/home/templth/work/repositories/git/theglobetrotterturtle/myproject-website/dist/server.js:20:30)
```

I investiguated a bit the problem and it seems that there are the following calls when launching the server script:

```
enableProdMode();
enableProdMode();
isDevMode();
enableProdMode();
```

Notice that I don't call `isDevMode()` myself...

If I updated the isDevMode in the generated js file (from ts):

```
/**
 * Returns whether Angular is in development mode. After called once,
 * the value is locked and won't change any more.
 *
 * By default, this is true, unless a user calls `enableProdMode` before calling this.
 *
 * @experimental APIs related to application bootstrap are currently under review.
 */
function isDevMode() {
    //_runModeLocked = true; <------------
    return _devMode;
}
```

the server starts correctly and the environment variables are taken into account in the server rendering...

**Comment by alan-agius4** [comment]
Can you please share your `main.server.ts`?

**Comment by templth** [comment]
Sure!

Here it is:

```
import { enableProdMode } from '@angular/core';

import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

export { AppServerModule } from './app/app.server.module';
```

**Comment by alan-agius4** [comment]
You cannot perform `enableProdMode()` after the platform has been initialised. 

`enableProdMode` should happen in your `server.ts` and not in `main.server.ts`, as the later is too late. 

Your `main.server.ts`, should pretty much contain only:

```ts
export {AppServerModule} from './app/app.server.module';
```

**Comment by templth** [comment]
Yes, you're right! It fixed the problem. Thanks very much for your help!
