### ISSUE TITLE
Error: Cannot find module 'exists-sync' after updating 

### ISSUE THREAD

**Issue by stevefarwell** [angular/angular-cli#1248]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan Version 10.11.5

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
Node v4.0.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Followed the docs for Updating angular-cli

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest

rm -rf node_modules dist tmp
npm install --save-dev angular-cli@latest
ng init

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/steve/Documents/roundpoint/nowce/nowce-browser/sandbox/nowce-landing/node_modules/angular-cli/node_modules/ember-cli/lib/models/project.js:11:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------

> > Thanks! We'll be in touch soon.

**Comment by michaelchiche** [comment]
I have the same problem

**Comment by juampi** [comment]
See #1186 .

**Comment by stevefarwell** [comment]
I updated node from v4.0.0 to v6.2.2 and updated npm from version  2.14.2 to 3.9.5 (current versions),
deleted the node_modules from my project then did npm install followed by ng init, I was asked if I wanted to overwrite package.json, system-config.ts and a bunch of others which I said yes to all  and I was able to get running again. I did lose anything I had added Bootstrap, Sass etc. Thank goodness for source control. I manually merged my changes back in. Everything worked except for the routing. I followed the Dev guide for the new router stuff and finally got that working. 

generating routes is disabled, hopefully they get that fixed soon

**Comment by butters16** [comment]
Doing an extra npm install worked for me.

`ng new PROJECT_NAME`
`cd PROJECT_NAME`
`ng serve`
exists-sync failure

`npm install`
`ng serve`
success

**Comment by Josid88** [comment]
I just uninstalled node and npm and reinstalled on versions:
- node v6.2.2 
- npm to 3.10.2 

Same error displayed
`Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\dev\ng2\Heroes\node_modules\angular-cli\node_modul
es\ember-cli\lib\models\project.js:11:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)`

**Comment by dvh91** [comment]
Fixed that by going to 'node_modules/angular-cli' inside project and run 'npm install'
then run ng serve again.
