### ISSUE TITLE
BroccoliTypescriptCompiler failed with EMFILE: too many open files

### ISSUE THREAD

**Issue by mlisanke** [angular/angular-cli#1249]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

C:\Users\Mike\workspace\angular2-todo-app>ng version
angular-cli: 1.0.0-beta.8
node: 4.4.3
os: win32 x64`

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
following steps from [](https://www.sitepoint.com/angular-2-tutorial/?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning&utm_medium=email&utm_campaign=Versioning%20494&utm_content=Versioning%20494+Version+B+CID_7c7b0ea0b210e5f9c55799d12aee4d02&utm_source=CampaignMonitor%20SitePoint&utm_term=building%20an%20Angular%202%20CRUD%20app%20with%20Angular%20CLI
)

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`C:\Users\Mike\workspace\angular2-todo-app>ng test

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Built project successfully. Stored in "dist/".
\ BuildingThe Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EMFILE: too many open files, open 'C:\Users\Mike\workspace\angular2-todo-app\tmp\broccoli_type_script_compiler-in
put_base_path-98LCriq5.tmp\0\src\tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at BroccoliTypeScriptCompiler._loadTsConfig (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\
broccoli\broccoli-typescript.js:128:34)
    at BroccoliTypeScriptCompiler._createServiceHost (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli
\lib\broccoli\broccoli-typescript.js:163:25)
    at BroccoliTypeScriptCompiler.build (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli
\broccoli-typescript.js:41:12)
    at C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:
152:21
    at lib$rsvp$$internal$$tryCatch (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\bro
ccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modul
es\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\broc
coli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\broccoli-ca
ching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_module
s\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\Users\Mike\workspace\angular2-todo-app\node_modules
\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli\brocc
oli-typescript.js:27:10)
    at Angular2App._getTsTree (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli\angular2-
app.js:321:18)
    at Angular2App._buildTree (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli\angular2-
app.js:116:23)
    at new Angular2App (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli\angular2-app.js:
53:23)
    at module.exports (C:\Users\Mike\workspace\angular2-todo-app\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\Mike\workspace\angular2-todo-app\node_modules\ang
ular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_mo
dules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\angular-cli\node_modul
es\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_mod
ules\angular-cli\lib\tasks\build-watch.js:17:16)
    at C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\addon\ng2\commands\test.js:69:46
    at lib$rsvp$$internal$$tryCatch (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\ang
ular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modul
es\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\angu
lar-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\angular-cli
\node_modules\rsvp\dist\rsvp.js:1198:9)

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EMFILE: too many open files, open 'C:\Users\Mike\workspace\angular2-todo-app\tmp\broccoli_type_script_compiler-in
put_base_path-98LCriq5.tmp\0\src\tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at BroccoliTypeScriptCompiler._loadTsConfig (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\
broccoli\broccoli-typescript.js:128:34)
    at BroccoliTypeScriptCompiler._createServiceHost (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli
\lib\broccoli\broccoli-typescript.js:163:25)
    at BroccoliTypeScriptCompiler.build (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli
\broccoli-typescript.js:41:12)
    at C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:
152:21
    at lib$rsvp$$internal$$tryCatch (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\bro
ccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modul
es\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\broc
coli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\broccoli-ca
ching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_module
s\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\Users\Mike\workspace\angular2-todo-app\node_modules
\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli\brocc
oli-typescript.js:27:10)
    at Angular2App._getTsTree (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli\angular2-
app.js:321:18)
    at Angular2App._buildTree (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli\angular2-
app.js:116:23)
    at new Angular2App (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\lib\broccoli\angular2-app.js:
53:23)
    at module.exports (C:\Users\Mike\workspace\angular2-todo-app\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\Mike\workspace\angular2-todo-app\node_modules\ang
ular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_mo
dules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\angular-cli\node_modul
es\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_mod
ules\angular-cli\lib\tasks\build-watch.js:17:16)
    at C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\addon\ng2\commands\test.js:69:46
    at lib$rsvp$$internal$$tryCatch (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\ang
ular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modul
es\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\angu
lar-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Mike\workspace\angular2-todo-app\node_modules\angular-cli\node_modules\angular-cli
\node_modules\rsvp\dist\rsvp.js:1198:9)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by mlisanke** [comment]
This was at 1st ng test in following tutorial...

https://www.sitepoint.com/angular-2-tutorial/?utm_source=SitePoint&utm_medium=email&utm_campaign=Versioning&utm_medium=email&utm_campaign=Versioning%20494&utm_content=Versioning%20494+Version+B+CID_7c7b0ea0b210e5f9c55799d12aee4d02&utm_source=CampaignMonitor%20SitePoint&utm_term=building%20an%20Angular%202%20CRUD%20app%20with%20Angular%20CLI

**Comment by mlisanke** [comment]
BroccoliTypescriptCompiler failed with EMFILE: too many open files #864
 Closed	alexkibler opened this issue on May 20 · 9 comments

**Comment by filipesilva** [comment]
There is a bug currently in windows where the build system can reach the file limit. It's being tracked in https://github.com/angular/angular-cli/issues/977.
