### ISSUE TITLE
Building error for library when importing ngrx/store

### ISSUE THREAD

**Issue by djatrifork** [angular/angular-cli#12524]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```
Even though it might be me making a mistake, I just can't seems to find it.

### Command (mark with an `x`)
```
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
npm: 6.4.1
Angular CLI: 6.2.4
Node: 8.12.0
OS: darwin x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.4
@angular-devkit/build-angular      0.8.4
@angular-devkit/build-ng-packagr   0.8.4
@angular-devkit/build-optimizer    0.8.4
@angular-devkit/build-webpack      0.8.4
@angular-devkit/core               0.8.4
@angular-devkit/schematics         0.8.4
@angular/cdk                       6.4.7
@angular/cli                       6.2.4
@angular/material                  6.4.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.4
@schematics/angular                0.8.4
@schematics/update                 0.8.4
ng-packagr                         4.2.0
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.20.2

macOS Mojave
```

### Repro steps

Repo: https://github.com/djatrifork/clistorebuilderror
```
npm i
ng build
```

### The log given by the failure

```
Building Angular Package
Building entry point '@aau/spinner'
Compiling TypeScript sources through ngc

BUILD ERROR
src/aau/spinner/src/aau-spinner.ts(8,29): error TS2307: Cannot find module './lib/@ngrx/spinner.reducer'.

Error: src/aau/spinner/src/aau-spinner.ts(8,29): error TS2307: Cannot find module './lib/@ngrx/spinner.reducer'.

    at Object.<anonymous> (/Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at /Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at /Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

src/aau/spinner/src/aau-spinner.ts(8,29): error TS2307: Cannot find module './lib/@ngrx/spinner.reducer'.

Error: src/aau/spinner/src/aau-spinner.ts(8,29): error TS2307: Cannot find module './lib/@ngrx/spinner.reducer'.

    at Object.<anonymous> (/Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at /Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at /Users/dennisjakobsen/Arbejde/problem/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

### Desired functionality

Should build the library

### Mention any other details that might be useful

The file it complains about `src/aau/spinner/src/aau-spinner.ts` doesn't seems to exist.
If I run `tsc` from the library folder it generates the `out-tsc` folder. In the map file it mentions this file 
```
{"version":3,"file":"aau-spinner.js","sourceRoot":"","sources":["../../src/aau-spinner.ts"],"names":[],"mappings":""}
```
The name seems to be linked to the name in package.json. 
The file it's trying to import `'./lib/@ngrx/spinner.reducer'` isn't located in this directory, but in `'./lib/@ngrx/reducers/spinner.reducer'`.
If I don't include @ngrx/store in spinner.module.ts it compiles just fine. Therefore, I'm not sure if it's a CLI thing, a store thing, or just me making a mistake.
VS Code doesn't complain about wrong paths, and I'm able to click-navigate to all the files.

**Comment by alan-agius4** [comment]
As a quick workaround you can replace https://github.com/djatrifork/clistorebuilderror/blob/master/src/aau/spinner/src/lib/spinner.module.ts#L6

with 
```ts
import { reducers } from './@ngrx/reducers/index';
```

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI
