### ISSUE TITLE
Unexpected EOF error even after clean node.js re-install

### ISSUE THREAD

**Issue by xurnix** [angular/angular-cli#1257]
I got problem when installing angular-cli
`npm install -g angular-cli`

log below.

but I've successfully install other, such ionic
`npm install -g ionic@beta`

Solution I've tried:

npm cache clean
npm uninstall -g angular-cli
run command in administrator
delete %NPMPATH%/node_modules
update npm & node.js
clean re-install node.js
some other solution that I forgot

when trying above solution, npm give different error
sometimes its error: z_buff_...something
or unpack tar error
or else

(sorry no log for other error, since I've done a clean re-install)

any suggestion?
thanks

> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**windows 8**

2. Versions. Please run `ng --version`. If there's nothing outputted, please
 **node v4.4.6**, no `ng --version` since its installation fail 

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`86669 verbose fstream_class Extract
86670 verbose stack Error: unexpected eof
86670 verbose stack     at decorate (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\fstream\lib\abstract.js:67:36)
86670 verbose stack     at Extract.Abstract.error (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\fstream\lib\abstract.js:61:12)
86670 verbose stack     at Extract._streamEnd (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\extract.js:91:35)
86670 verbose stack     at BlockStream.<anonymous> (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:51:8)
86670 verbose stack     at emitNone (events.js:67:13)
86670 verbose stack     at BlockStream.emit (events.js:166:7)
86670 verbose stack     at BlockStream._emitChunk (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\block-stream\block-stream.js:203:10)
86670 verbose stack     at BlockStream.resume (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\block-stream\block-stream.js:58:15)
86670 verbose stack     at Extract.Reader.resume (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\fstream\lib\reader.js:249:34)
86670 verbose stack     at Entry.<anonymous> (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:261:8)
86671 verbose fstream_stack Extract._streamEnd (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\extract.js:91:35)
86671 verbose fstream_stack BlockStream.<anonymous> (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:51:8)
86671 verbose fstream_stack emitNone (events.js:67:13)
86671 verbose fstream_stack BlockStream.emit (events.js:166:7)
86671 verbose fstream_stack BlockStream._emitChunk (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\block-stream\block-stream.js:203:10)
86671 verbose fstream_stack BlockStream.resume (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\block-stream\block-stream.js:58:15)
86671 verbose fstream_stack Extract.Reader.resume (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\fstream\lib\reader.js:249:34)
86671 verbose fstream_stack Entry.<anonymous> (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:261:8)
86672 verbose cwd C:\WINDOWS\system32
86673 error Windows_NT 6.3.9600
86674 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gogon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
86675 error node v4.4.6
86676 error npm  v3.10.2
86677 error unexpected eof
`

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by xurnix** [comment]
after `npm uninstall -g angular-cli`
and 'npm cache clean`

now angular-cli successfully installed,

it fail before. maybe it work after clean re-install node.js
