### ISSUE TITLE
Could not determine a single project for the 'serve' target.

### ISSUE THREAD

**Issue by xtrrdnryprgrmmr** [angular/angular-cli#12594]
When i run ng serve command , i take error in below.(PS:I use jhipster with angular 6)

Could not determine a single project for the 'serve' target.
Error: Could not determine a single project for the 'serve' target.
    at ServeCommand.getProjectNamesByTarget (C:\Users\pc\complexdemo\node_modules\@angular\cli\models\architect-command.js:184:19)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (C:\Users\pc\complexdemo\node_modules\@angular\cli\models\architect-command.js:58:43)
    at MergeMapSubscriber._tryNext (C:\Users\pc\complexdemo\node_modules\rxjs\internal\operators\mergeMap.js:122:27)
    at MergeMapSubscriber._next (C:\Users\pc\complexdemo\node_modules\rxjs\internal\operators\mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\pc\complexdemo\node_modules\rxjs\internal\Subscriber.js:103:18)
    at TapSubscriber._next (C:\Users\pc\complexdemo\node_modules\rxjs\internal\operators\tap.js:109:26)
    at TapSubscriber.Subscriber.next (C:\Users\pc\complexdemo\node_modules\rxjs\internal\Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (C:\Users\pc\complexdemo\node_modules\rxjs\internal\operators\mergeMap.js:141:26)
    at InnerSubscriber._next (C:\Users\pc\complexdemo\node_modules\rxjs\internal\InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (C:\Users\pc\complexdemo\node_modules\rxjs\internal\Subscriber.js:103:18)

**Comment by alan-agius4** [comment]
Closing as it doesn’t follow the template

**Comment by xtrrdnryprgrmmr** [comment]
next time i will follow the template ,sorry
