### ISSUE TITLE
@schematics(`schematic` schematics fail to run unit test with error `no such file or directory`)

### ISSUE THREAD

**Issue by AhsanAyaz** [angular/angular-cli#12605]
PS: in short, this issue is similar to [#860](https://github.com/angular/devkit/issues/860) from the old devkit repo. [#860](https://github.com/angular/devkit/issues/860) was for `blank` schematic, this one is for the `schematic` schematics.

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

`node --version` v8.11.1
`npm --version` 6.1.0
`ng --version` 1.6.8
### Repro steps

```bash
schematics scematic --name ngx-schem
cd ngx-schem
npm run test
```

### The log given by the failure

```bash
> tsc -p tsconfig.json

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/path/to/project/node_modules/fsevents/node_modules/needle/test/keys/ssl.cert'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/path/to/project/node_modules/fsevents/node_modules/needle/test/helpers.js:9:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

### Desired functionality

Should run tests successfully.

**Comment by AhsanAyaz** [comment]
@alan-agius4 I'm using the latest version of CLI. I.e. `7.0.0-rc.3`
The issue still persists. :)


```bash
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.8
Node: 8.11.1
OS: darwin x64
Angular: undefined
...


@angular-devkit/core: 7.0.0-rc.3
@angular-devkit/schematics: 7.0.0-rc.3
typescript: 2.9.2
webpack: error
```

Please correct me if the above details are contradicting with my statements.
