### ISSUE TITLE
ng serve build error - Broccoli Plugin [Funnel] failed

### ISSUE THREAD

**Issue by vorugantia** [angular/angular-cli#1262]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux (but I'm running Bash on Ubuntu image on Windows 10. Shouldn't make a difference, though. More info [here](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows).)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

angular-cli: 0.0.39
node: 6.2.2
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Created with the CLI but on a different computer (OS X)

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Here is the console log:

$ ng serve
(node:8809) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
File: /mnt/c/Users/arjun_000/github/gamma-sky/src
The Broccoli Plugin: [Funnel] failed with:
Error: watch /mnt/c/Users/arjun_000/github/gamma-sky/src EPERM
    at exports._errnoException (util.js:1007:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at NodeWatcher.watchdir (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at new Funnel (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/lib/broccoli/angular2-app.js:73:7)
    at new Angular2App (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/lib/broccoli/angular2-app.js:31:41)
    at module.exports (/mnt/c/Users/arjun_000/github/gamma-sky/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Here is the log on localhost:4200 in browser:

Build error

The Broccoli Plugin: [Funnel] failed with:
Error: watch /mnt/c/Users/arjun_000/github/gamma-sky/src EPERM
    at exports._errnoException (util.js:1007:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at NodeWatcher.watchdir (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at new Funnel (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/lib/broccoli/angular2-app.js:73:7)
    at new Angular2App (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/lib/broccoli/angular2-app.js:31:41)
    at module.exports (/mnt/c/Users/arjun_000/github/gamma-sky/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

5. Mention any other details that might be useful.

I also tried to run `ng build`, but npm isn't writing certain files in my `node_modules` folder. Here's the console log for this error:

`
127.0.0.1 - - [01/Jul/2016 15:18:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2016 15:18:16] "GET /dist/ HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2016 15:18:16] code 404, message File not found
127.0.0.1 - - [01/Jul/2016 15:18:16] "GET /vendor/es6-shim/es6-shim.js HTTP/1.1" 404 -
127.0.0.1 - - [01/Jul/2016 15:18:16] code 404, message File not found
127.0.0.1 - - [01/Jul/2016 15:18:16] "GET /vendor/reflect-metadata/Reflect.js HTTP/1.1" 404 -
127.0.0.1 - - [01/Jul/2016 15:18:16] code 404, message File not found
127.0.0.1 - - [01/Jul/2016 15:18:16] "GET /vendor/systemjs/dist/system.src.js HTTP/1.1" 404 -
127.0.0.1 - - [01/Jul/2016 15:18:16] code 404, message File not found
127.0.0.1 - - [01/Jul/2016 15:18:16] "GET /vendor/zone.js/dist/zone.js HTTP/1.1" 404 -
`

Any idea how to fix this? Thanks

**Comment by pradeeprajr93** [comment]
facing same error :(

**Comment by WALR** [comment]
I had the same problem, is solved with:

```
sudo npm install -g ember-cli --save
sudo ng serve 
```

**Comment by filipesilva** [comment]
This issue has been solved in more recent versions of Angular CLI. You're using a fairly old version (0.0.39), so the solution is to upgrade.

**Comment by vorugantia** [comment]
I updated to angular-cli version 1.0.0-beta.8 and also installed ember-cli globally, but unfortunately neither worked. I still receive the same exact issue. Is there any other workaround?
