### ISSUE TITLE
ng serve gives dart-sass error

### ISSUE THREAD

**Issue by WEBhicham** [angular/angular-cli#12696]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node -v
v10.12.0

npm -v
6.4.1
```
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.0.2
Node: 10.12.0
OS: win32 x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.2
@angular-devkit/build-angular     0.10.2
@angular-devkit/build-optimizer   0.10.2
@angular-devkit/build-webpack     0.10.2
@angular-devkit/core              7.0.2
@angular-devkit/schematics        7.0.2
@angular/cli                      7.0.2
@ngtools/webpack                  7.0.2
@schematics/angular               7.0.2
@schematics/update                0.10.2
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```
Windows 10

### Repro steps
1) ng n newapp
2) cd newapp
3) ng serve -o

### The log given by the failure

```
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-10-22T16:35:25.432Z
Hash: 5d1313a151e7c3604e19
Time: 9570ms
chunk {main} main.js, main.js.map (main) 13 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 228 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.8 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.69 MB [initial] [rendered]

ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Dart Sass version 1.0.0-beta.2 is incompatible with ^1.3.0.
    at getRenderFuncFromSassImpl (C:\Users\hicham\Documents\newapp\node_modules\sass-loader\lib\loader.js:103:19)
    at Object.sassLoader (C:\Users\hicham\Documents\newapp\node_modules\sass-loader\lib\loader.js:46:20)
i ｢wdm｣: Failed to compile.
```

### Desired functionality

A fix I suppose? 

### Mention any other details that might be useful

I upgraded my cli with running
npm i -g @angular/cli

**Comment by clydin** [comment]
`Error: Dart Sass version 1.0.0-beta.2 is incompatible with ^1.3.0.`

 If you intend to use dart-sass then you need 1.30+ as the error indicates.  If not, uninstall it.

**Comment by WEBhicham** [comment]
What? Then why are you installing it for me>?
I ONLY ran
ng n newapp
cd newapp
ng serve -o

Why is you default app giving me an error?

**Comment by clydin** [comment]
The CLI does not install `dart-sass`.  It uses it if it has been manually installed.  Which it appears has been done on your system (most likely some time ago as `1.0.0-beta.2` is over a year old).
