### ISSUE TITLE
[BUG] Problem installing angular@cli

### ISSUE THREAD

**Issue by aguadotzn** [angular/angular-cli#12855]
## Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

## Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ X] config
- [ ] help
- [ ] version
- [ ] doc
```

## Versions

MACOSX version
**Mojave (10.04)**
node --version
**v11.1.0**
npm -version
**6.4.1**

```   Angular CLI: 7.0.4
Node: 11.1.0
OS: darwin x64
Angular: 
... 

Package Version
------------------------------------------------------
@angular-devkit/architect    <error>
@angular-devkit/core         7.0.4
@angular-devkit/schematics   7.0.4
@schematics/angular          7.0.4
@schematics/update           <error>
rxjs                         6.3.3
typescript                   3.1.3
```

## Repro steps

I'm trying to install angular@cli on my mac and is not working. I follow the instructions here in the github repository ton install it 

### The log given by the failure

```
> npm install -g @angular/cli

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.1.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/Users/xxx/.nvm/versions/node/v11.1.0/bin/node" "/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/xxx/.nvm/versions/node/v11.1.0/bin/node /Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command "/Users/xxx/.nvm/versions/node/v11.1.0/bin/node" "/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents
node-pre-gyp ERR! node -v v11.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/xxx/.nvm/versions/node/v11.1.0/bin/node /Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/Users/xxx/.nvm/versions/node/v11.1.0/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @angular/cli@7.0.4
added 268 packages from 205 contributors in 42.752s
```

### Desired functionality

The cli correcly installed

### Mention any other details that might be useful
No more comments

**Comment by alan-agius4** [comment]
Closing as it was answered above. Thanks @wvanderdeijl.

**Comment by aguadotzn** [comment]
Thanks for the fast reply!
