### ISSUE TITLE
ProgressPlugin breaks with webpack 4.25.* due to incorrect option colors

### ISSUE THREAD

**Issue by mdasberg** [angular/angular-cli#12866]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [*] build
- [*] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps

npm install
npm run build / serve

### The log given by the failure

Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

ValidationError: Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

### Desired functionality

In [common.ts#L147](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L147) the ProgressPlugin is called with parameter colors. This does not meet the schema which is validated [ProgressPlugin.js#L90](https://github.com/webpack/webpack/blob/master/lib/ProgressPlugin.js#L90)

**Comment by JordySwinnenPXL** [comment]
Having the same issue when a making fresh project.

### Repro steps
ng new [project-name]
npm install && ng serve --open --prod

### Expected result
Should open new window with fresh project opened

### Result
```
λ ng serve -o
Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

ValidationError: Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

    at validateOptions (..\project-name\node_modules\schema-utils\src\validateOptions.js:31:11)
    at new ProgressPlugin (..\project-name\node_modules\webpack\lib\ProgressPlugin.js:90:3)
    at Object.getCommonConfig (..\project-name\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\common.js:123:27)
    at BrowserBuilder.buildWebpackConfig (..\project-name\node_modules\@angular-devkit\build-angular\src\browser\index.js:74:31)
    at DevServerBuilder.buildWebpackConfig (..\project-name\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:111:46)
    at MergeMapSubscriber.check_port_1.checkPort.pipe.operators_1.concatMap [as project] (..\project-name\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:38:40)
    at MergeMapSubscriber._tryNext (..\project-name\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (..\project-name\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (..\project-name\node_modules\rxjs\internal\Subscriber.js:64:18)
    at TapSubscriber._next (..\project-name\node_modules\rxjs\internal\operators\tap.js:62:26)
    at TapSubscriber.Subscriber.next (..\project-name\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (..\project-name\node_modules\rxjs\internal\operators\mergeMap.js:84:26)
    at InnerSubscriber._next (..\project-name\node_modules\rxjs\internal\InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (..\project-name\node_modules\rxjs\internal\Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (..\project-name\node_modules\rxjs\internal\observable\forkJoin.js:79:25)
    at InnerSubscriber._complete (..\project-name\node_modules\rxjs\internal\InnerSubscriber.js:32:21)
```

### Version
```
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.2.5
Node: 10.13.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.5
@angular-devkit/core         0.8.5
@angular-devkit/schematics   0.8.5
@schematics/angular          0.8.5
@schematics/update           0.8.5
rxjs                         6.2.2
typescript                   2.9.2
```

```
npm -v
6.4.1
```

**Comment by shabbir-dhangot** [comment]
Having same issue while fresh npm install. 

    Progress Plugin Invalid Options

    options['colors'] is an invalid additional property
    options should pass "instanceof" keyword validation
    options should match exactly one schema in oneOf

    ValidationError: Progress Plugin Invalid Options

    options['colors'] is an invalid additional property
    options should pass "instanceof" keyword validation
    options should match exactly one schema in oneOf

    at validateOptions (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/schema-utils/src/validateOptions.js:31:11)
    at new ProgressPlugin (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/webpack/lib/ProgressPlugin.js:90:3)
    at Object.getCommonConfig (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js:123:27)
    at BrowserBuilder.buildWebpackConfig (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/src/browser/index.js:74:31)
    at MergeMapSubscriber.rxjs_1.of.pipe.operators_1.concatMap [as project] (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/src/browser/index.js:31:38)
    at MergeMapSubscriber._tryNext (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:65:27)
    at MergeMapSubscriber._next (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at TapSubscriber._next (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/tap.js:62:26)
    at TapSubscriber.Subscriber.next (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:84:26)
    at InnerSubscriber._next (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/observable/forkJoin.js:79:25)
    at InnerSubscriber._complete (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:32:21)
    at InnerSubscriber.Subscriber.complete (/media/shabbir/Projects/SVN/production/hub/trunk/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:76:18)

**Comment by Lak89** [comment]
Having same with when creating a fresh project by command **ng new project _name**
Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

ValidationError: Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

    at validateOptions

**Comment by rayoreher** [comment]
i have the same problem. after create a new project using angular console.

`Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

ValidationError: Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

    at validateOptions (C:\dev\NGFullCalendar\node_modules\schema-utils\src\validateOptions.js:31:11)
    at new ProgressPlugin (C:\dev\NGFullCalendar\node_modules\webpack\lib\ProgressPlugin.js:90:3)
    at Object.getCommonConfig (C:\dev\NGFullCalendar\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\common.js:123:27)
    at BrowserBuilder.buildWebpackConfig (C:\dev\NGFullCalendar\node_modules\@angular-devkit\build-angular\src\browser\index.js:74:31)
    at DevServerBuilder.buildWebpackConfig (C:\dev\NGFullCalendar\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:111:46)
    at MergeMapSubscriber.check_port_1.checkPort.pipe.operators_1.concatMap [as project] (C:\dev\NGFullCalendar\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:38:40)
    at MergeMapSubscriber._tryNext (C:\dev\NGFullCalendar\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (C:\dev\NGFullCalendar\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (C:\dev\NGFullCalendar\node_modules\rxjs\internal\Subscriber.js:64:18)
    at TapSubscriber._next (C:\dev\NGFullCalendar\node_modules\rxjs\internal\operators\tap.js:62:26)
    at TapSubscriber.Subscriber.next (C:\dev\NGFullCalendar\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (C:\dev\NGFullCalendar\node_modules\rxjs\internal\operators\mergeMap.js:84:26)
    at InnerSubscriber._next (C:\dev\NGFullCalendar\node_modules\rxjs\internal\InnerSubscriber.js:25:21)
    at InnerSubscriber.Subscriber.next (C:\dev\NGFullCalendar\node_modules\rxjs\internal\Subscriber.js:64:18)
    at ForkJoinSubscriber.notifyComplete (C:\dev\NGFullCalendar\node_modules\rxjs\internal\observable\forkJoin.js:79:25)
    at InnerSubscriber._complete (C:\dev\NGFullCalendar\node_modules\rxjs\internal\InnerSubscriber.js:32:21)
PS C:\dev\NGFullCalendar>`

**Comment by gstylianou** [comment]
I have the same issue but only in Ubuntu 16.04. On Windows 10 it works just fine.
Using Node 8.x

**Comment by wilsonferro** [comment]
This problem **does not happen when I do npm install on Windows 10**. But on my **MacBook the problem really does occur**, just as reported above.

I am having to use Windows for now to be able to run my projects in Angular 6. I do not know how to solve this problem and I do not know why it is occurring only on Mac but in Windows not ...

**Comment by JordySwinnenPXL** [comment]
> I have the same issue but only in Ubuntu 16.04. On Windows 10 it works just fine.
> Using Node 8.x

Windows 10 user here. Using Node 10 LTS

**Comment by genyklemberg** [comment]
make ng update

**Comment by ayush-bhandari** [comment]
I had the same issue on Ubuntu 18.10, Node 10.8.0, NPM 6.2.0 and Angular CLI 6.2.6.

Fixed it with removing colors option on this file:
/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js
on Line: 123

Changed this:
extraPlugins.push(new ProgressPlugin({ profile: buildOptions.verbose, colors: true }));
to:
extraPlugins.push(new ProgressPlugin({ profile: buildOptions.verbose }));

Hope this help. Cheers.

**Comment by carlgik4** [comment]
Can be fixed temporarily by adding this line to package.json

```
"devDependencies":{
...
"webpack": "4.24.0"
}
```

**Comment by gstylianou** [comment]
> Can be fixed temporarily by adding this line to package.json
> 
> ```
> "devDependencies":{
> ...
> "webpack": "4.24.0"
> }
> ```

This worked for me.

**Comment by malkovitc** [comment]
> I had the same issue on Ubuntu 18.10, Node 10.8.0, NPM 6.2.0 and Angular CLI 6.2.6.
> 
> Fixed it with removing colors option on this file:
> /node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js
> on Line: 123
> 
> Changed this:
> extraPlugins.push(new ProgressPlugin({ profile: buildOptions.verbose, colors: true }));
> to:
> extraPlugins.push(new ProgressPlugin({ profile: buildOptions.verbose }));
> 
> Hope this help. Cheers.

Its works! Thanks!

**Comment by ameeyakumardas007** [comment]
> Can be fixed temporarily by adding this line to package.json
> 
> ```
> "devDependencies":{
> ...
> "webpack": "4.24.0"
> }
> ```
> then
> `npm install`

This worked for me as well! Thank you!

**Comment by JordySwinnenPXL** [comment]
> Can be fixed temporarily by adding this line to package.json
> 
> ```
> "devDependencies":{
> ...
> "webpack": "4.24.0"
> }
> ```
> then
> `npm install`

Worked for me! Thanks.
Deleted node_modules, then ran `npm cache clean --force && npm install && npm install --open --prod`

**Comment by chukjustin2000** [comment]
> Can be fixed temporarily by adding this line to package.json
> 
> ```
> "devDependencies":{
> ...
> "webpack": "4.24.0"
> }
> ```
> then
> `npm install`



> Can be fixed temporarily by adding this line to package.json
> 
> ```
> "devDependencies":{
> ...
> "webpack": "4.24.0"
> }
> ```
> then
> `npm install`
This worked for me too. Thanks

**Comment by chukjustin2000** [comment]
> Can be fixed temporarily by adding this line to package.json
> 
> ```
> "devDependencies":{
> ...
> "webpack": "4.24.0"
> }
> ```
> then
> `npm install`

This worked for me. Thanks

**Comment by rdhelms** [comment]
Looks like the validation logic along with that `validateOptions` call in ProgressPlugin, was just added to webpack@4.25.0 here:
https://github.com/webpack/webpack/commit/aa8cb0fab74160caca59e1cfdd0758c0346313b0#diff-5d04086b4365820a456acec22b899956R86

**Comment by hasanfalizada** [comment]
`ng update --all` did the work!

**Comment by ThiagoMarques** [comment]
> "webpack": "4.24.0"

Worked for me! thanks!!

**Comment by NanaDarko** [comment]
> Can be fixed temporarily by adding this line to package.json
> 
> ```
> "devDependencies":{
> ...
> "webpack": "4.24.0"
> }
> ```
> then
> `npm install`

Worked for me...

**Comment by eago** [comment]
> `ng update --all` did the work!

works like a charm

**Comment by filipesilva** [comment]
Heya, we have a fix incoming in https://github.com/angular/angular-cli/pull/12870. As far as I can tell, this only affects 6.2.x. Neither 6.1.x nor 7.x should be affected.

**Comment by guillermosnipe** [comment]
> I had the same issue on Ubuntu 18.10, Node 10.8.0, NPM 6.2.0 and Angular CLI 6.2.6.
> 
> Fixed it with removing colors option on this file:
> /node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js
> on Line: 123
> 
> Changed this:
> extraPlugins.push(new ProgressPlugin({ profile: buildOptions.verbose, colors: true }));
> to:
> extraPlugins.push(new ProgressPlugin({ profile: buildOptions.verbose }));
> 
> Hope this help. Cheers.

It works! Thanks a lot :)

**Comment by alexeagle** [comment]
Fixed in https://github.com/angular/angular-cli/releases/tag/v6.2.7

**Comment by pavedwave** [comment]
`Fixed it with removing colors option on this file:
/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js
on Line: 123

Changed this:
extraPlugins.push(new ProgressPlugin({ profile: buildOptions.verbose, colors: true }));
to:
extraPlugins.push(new ProgressPlugin({ profile: buildOptions.verbose }));`

This worked for me as well -- thanks!

**Comment by florian-badaluma** [comment]
Updating to Angular CLI 6.2.7 fixed it for me. 

> "webpack": "4.24.0"

Did the job also for me.

**Comment by emw-ghertner** [comment]
> ng update --all did the work!

Worked for me as well.

**Comment by renancunha** [comment]
> "webpack": "4.24.0"

worked for me! =) Thanks!

**Comment by deepatripathi** [comment]
I am facing same issue. None of the above solutions working for me . Any other suggestions ?

**Comment by awerlang** [comment]
`@angular/cli@6.2.7` alone didn't make it, had to upgrade one more:

```
    "@angular-devkit/build-angular": "0.10.6",
    "@angular/cli": "6.2.7",
```

**Comment by iamwillpowell** [comment]
Another workaround is `ng serve --progress=false` until you can update angular-cli

**Comment by CheeseZhao** [comment]
> I am facing same issue. None of the above solutions working for me . Any other suggestions ?
> try do it :`npm uninstall webapck`,
 then Can be fixed temporarily by adding this line to package.json

```
"devDependencies":{
...
"webpack": "4.24.0"
}
```
then
`npm install`

**Comment by bamossza** [comment]
Same problem with me (`Angular 6.1.10 and Angular Cli 6.2.7`)
Remove `package-lock.json` and `npm cache clean --force && npm install --force`
Worked for me :)

**Comment by Gorniv** [comment]
update from
```
    "@angular-devkit/build-angular": "0.8.4",
```
to
```
    "@angular-devkit/build-angular": "0.11.0",
```

**Comment by IniJr** [comment]
ng update @angular/cli worked for me
