### ISSUE TITLE
ng make-this-awesome Cannot find module 'angular-cli/lib/utilities/string'

### ISSUE THREAD

**Issue by haburka** [angular/angular-cli#1287]
Using angular cli 0.1.0, ng make-this-awesome leaves an error:

Cannot find module 'angular-cli/lib/utilities/string'

  Error: Cannot find module 'angular-cli/lib/utilities/string'

    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Class.Command.extend.run (/home/rob/jsr-website/ic-platform/web/icp-frontend/node_modules/angular-cli/addon/ng2/commands/easter-egg.ts:13:31)
    at Class.<anonymous> (/home/rob/jsr-website/ic-platform/web/icp-frontend/node_modules/angular-cli/lib/models/command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (/home/rob/jsr-website/ic-platform/web/icp-frontend/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/rob/jsr-website/ic-platform/web/icp-frontend/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/home/rob/jsr-website/ic-platform/web/icp-frontend/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/home/rob/jsr-website/ic-platform/web/icp-frontend/node_modules/rsvp/dist/rsvp.js:1198:9)

Any workarounds to make my repository awesome?

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/725.
