### ISSUE TITLE
Error: ENOTDIR: not a directory, rmdir '/projectDir/dist/symlinkDir'

### ISSUE THREAD

**Issue by mko** [angular/angular-cli#12882]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
    "@angular-devkit/build-angular": "0.10.4",
    "@angular/cli": "7.0.4",
    "@angular/compiler-cli": "7.0.2",
```
Tested on Node versions `8.9.4`, `8.11.1`, and `10.0.0`.

### Repro steps
1. Add a symlinked folder into `projectDir/dist`. For example, put a symlink from one `git` repository's folder (i.e. `projectDir`) to another `git` repository's public assets folder (i.e. `symlinkDir`). The resultant folder structure should be `projectDir/dist/symlinkDir`.
2. Run `ng build --output-path=dist`.
3. Observe failure when `build` attempts to remove `symlinkDir` which is not an actual directory but is a symlink instead.

### The log given by the failure
```
ENOTDIR: not a directory, rmdir '/projectDir/dist/symlinkDir'
Error: ENOTDIR: not a directory, rmdir '/projectDir/dist/symlinkDir'
    at Object.fs.rmdirSync (fs.js:846:18)
    at Observable.rxjs_1.Observable [as _subscribe] (/projectDir/node_modules/@angular-devkit/core/node/host.js:188:28)
    at Observable._trySubscribe (/projectDir/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/projectDir/node_modules/rxjs/internal/Observable.js:30:22)
    at /projectDir/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/projectDir/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (/projectDir/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (/projectDir/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
    at MergeMapSubscriber._next (/projectDir/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/projectDir/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/projectDir/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/projectDir/node_modules/rxjs/internal/Subscriber.js:67:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/projectDir/node_modules/@angular-devkit/core/node/host.js:263:21)
    at Observable._trySubscribe (/projectDir/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/projectDir/node_modules/rxjs/internal/Observable.js:30:22)
    at MapOperator.call (/projectDir/node_modules/rxjs/internal/operators/map.js:32:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngproject@0.0.0 start: `ng build --watch --output-path=dist`
npm ERR! Exit status 1
```

### Desired functionality
The `symlinkDir` symlink should be detected as a file pointer instead of a directory and either deleted or skipped (likely deleted correctly unless something is set in config). Either way, it shouldn't error out when it comes along.

### Mention any other details that might be useful
It appears that when a symlinked directory is marked by Angular CLI for deletion and gets checked for `isDirectory` ( https://github.com/angular/angular-cli/blob/db78228fc4880374076129d21d84248937cd9269/packages/angular_devkit/core/node/host.ts#L265 ), when the check is performed in the virtual host implementation, it's currently implemented to follow symlinks, as it uses `this._delegate.stat` not `this._delegate.lstat` here: https://github.com/angular/angular-cli/blob/db78228fc4880374076129d21d84248937cd9269/packages/angular_devkit/core/src/virtual-fs/host/sync.ts#L96 -- at the very least, before the `rmdirSync` call, the `delete` code should perform a `lstat` check to ensure that the directory is actually a directory and not a symlinked directory.

I'm not sure if this was intentional, but there likely should be some mechanism in the virtual host to properly identify symlinks. This is likely an edge case and may not be worth the testing burden as most users expect the `dist` folder to be wiped out and no one creating symlinks inside of it, but there are realities of complex architectures that might need this functionality. We're looking for a workaround in the meantime.

A reasonable compromise implementation might be to provide a `followSymlinks` configuration setting in `angular.json` that will use `stat` on `isDirectory` calls if `true` and `lstat` if `false`.

**Comment by santoshyadavdev** [comment]
Hey @kyliau, I will try to work on it.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
