### ISSUE TITLE
ng serve build error - Broccoli Plugin [Funnel] failed

### ISSUE THREAD

**Issue by vorugantia** [angular/angular-cli#1292]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux (I'm running Bash on Ubuntu on Windows 10)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

```
angular-cli: 1.0.0-beta.8
node: 6.2.2
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Created with the CLI but on a different computer (OS X)

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Error in console:

```
(node:384) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: /mnt/c/Users/arjun_000/github/gamma-sky/src
The Broccoli Plugin: [Funnel] failed with:
Error: watch /mnt/c/Users/arjun_000/github/gamma-sky/src EPERM
    at exports._errnoException (util.js:1007:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at NodeWatcher.watchdir (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/angular-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/lib/broccoli/angular2-app.js:84:7)
    at new Angular2App (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (/mnt/c/Users/arjun_000/github/gamma-sky/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Error at localhost:4200 in browser:

```
Build error
The Broccoli Plugin: [Funnel] failed with:

Error: watch /mnt/c/Users/arjun_000/github/gamma-sky/src EPERM
    at exports._errnoException (util.js:1007:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at NodeWatcher.watchdir (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/lib/broccoli/angular2-app.js:84:7)
    at new Angular2App (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (/mnt/c/Users/arjun_000/github/gamma-sky/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/mnt/c/Users/arjun_000/github/gamma-sky/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

5. Mention any other details that might be useful.

I've tried these to fix the issue and they haven't worked:

- Updated angular-cli to the latest version by following all instructions on angular-cli Github page (initially, I had the problem when I was on version 0.0.39)

- ```npm install -g ember-cli --save```

- ```ng build``` and running a Python server

Any ideas? Thanks!

>--------------------------------------------------------------

**Comment by bschlosser** [comment]
Have you checked your filesystem permissions?
`Error: watch /mnt/c/Users/arjun_000/github/gamma-sky/src EPERM`
The error indicates that there is a permission error accessing your `src` directory

**Comment by jkuri** [comment]
Yes, this is a permission issue. `chmod -R 744 src/` should solve this.

**Comment by jeremyfry** [comment]
Not sure if this solved it for the original poster, but I'm having the same issue with proper permissions. Ubuntu Bash
angular-cli 1.0.0beta10

`File: /home/jfry/game-backlog/src
The Broccoli Plugin: [Funnel] failed with:
Error: watch /home/jfry/game-backlog/src EPERM
    at exports._errnoException (util.js:1012:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at NodeWatcher.watchdir (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /home/jfry/game-backlog/node_modules/angular-cli/node_modules/angular-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/jfry/game-backlog/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at new Funnel (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/home/jfry/game-backlog/node_modules/angular-cli/lib/broccoli/angular2-app.js:92:7)
    at new Angular2App (/home/jfry/game-backlog/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (/home/jfry/game-backlog/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /home/jfry/game-backlog/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/jfry/game-backlog/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/jfry/game-backlog/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

`jfry@DESKTOP-BKSHD8G:~/game-backlog$ ls -l ./src/
total 20
drwxr--r-- 2 jfry jfry    0 Jul 23 16:02 app
-rwxr--r-- 1 jfry jfry 5430 Jul 23 16:02 favicon.ico
-rwxr--r-- 1 jfry jfry  672 Jul 23 16:02 index.html
-rwxr--r-- 1 jfry jfry  242 Jul 23 16:02 main.ts
-rwxr--r-- 1 jfry jfry 1843 Jul 23 16:02 system-config.ts
-rwxr--r-- 1 jfry jfry  456 Jul 23 16:02 tsconfig.json
-rwxr--r-- 1 jfry jfry  259 Jul 23 16:02 typings.d.ts`
