### ISSUE TITLE
angular-cli beta ng serve "unexpected identifier" error

### ISSUE THREAD

**Issue by kristiannotari** [angular/angular-cli#12991]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
node:  v6.14.4
npm:   3.10.10
ng:    1.0.0-beta.19-3
macOs: Mojave 10.14.1
```

### Repro steps

My package.json: 
```json
{
  "name": "worldwideranch",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor",
    "build": "postcss --use autoprefixer -r src/**/*.css && ng build",
    "build-prod": "postcss --use autoprefixer -r src/**/*.css && ng build --prod --env=prod",
    "deploy": "postcss --use autoprefixer -r src/**/*.css && ng build && firebase deploy",
    "deploy-prod": "postcss --use autoprefixer -r src/**/*.css && ng build --prod --env=prod && firebase deploy"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/router": "3.2.3",
    "@types/node": "^6.0.59",
    "angular2-infinite-scroll": "^0.2.8",
    "angular2-swiper": "^0.8.1",
    "angularfire2": "^2.0.0-beta.7-pre",
    "codelyzer": "^2.0.0-beta.4",
    "core-js": "^2.4.1",
    "firebase": "^3.6.3",
    "ng2-translate": "^4.2.0",
    "rxjs": "^5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "tslint": "^4.3.1",
    "typescript": "~2.0.10",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.3",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.19-3",
    "autoprefixer": "^9.3.1",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "postcss-cli": "^6.0.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "2.0.10",
    "webdriver-manager": "10.2.5"
  }
}

```

I cloned a repo which has always worked the way it should. I ran `npm install` on it, then tried to run `npm run start` (which calls `ng serve`) and it fails with the error logged (see next section). The only thing changing from my previous tests on this repo (possibly) is the node and npm versions (I don't remember which one I was using, it was like 1 year ago).

### The log given by the failure

**console log (after command)**
```
npm run start

> worldwideranch@0.0.0 start /Users/kristian/Progetti/worldwideranch
> ng serve

Unexpected identifier
/Users/kristian/Progetti/worldwideranch/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:218
    async _createOrUpdateProgram() {
          ^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kristian/Progetti/worldwideranch/node_modules/@ngtools/webpack/src/index.js:13:10)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/models/webpack-build-typescript.js:5:17)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/models/webpack-config.js:2:34)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/tasks/build-webpack.js:6:24)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/commands/build.js:3:23)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (/Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/addon/index.js:21:16)
    at /Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (/Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/lib/models/project.js:391:15)
    at Project.eachAddonCommand (/Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/lib/models/project.js:426:30)
    at module.exports (/Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/Users/kristian/Progetti/worldwideranch/node_modules/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/Users/kristian/Progetti/worldwideranch/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/kristian/Progetti/worldwideranch/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/kristian/Progetti/worldwideranch/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/kristian/Progetti/worldwideranch/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

**npm log (file)**
see attached file [npm-debug.log](https://github.com/angular/angular-cli/files/2594727/npm-debug.log)

### Desired functionality

I would like to have the `ng serve` command working as expected.

### Mention any other details that might be useful

I'm using angular-cli locally, installed via npm as dev-dependency.

I know this is very old version of angular cli (and of angular). But I tried angular when it was at that version and I always kept to the same. It has always worked the right way until now.

I didn't find anything related to "unexpected identifier" (which seems strange to me, like an error I should not having... maybe my mistake somewhere) but can't find a way to solve it.

A strange thing happens when I try to install angular-cli (same version as mentioned in package.json) globally. I can't use `ng` as a global command in the console, because it can't find it. Seems like npm is misconfigured / badly installed but don't know if could be related to this. However it runs the `ng serve` locally, giving the above error.

Thanks for any reply :)

**Comment by alan-agius4** [comment]
Hi, `1.0.0-beta.19-3` is no longer supported, at the moment the LTS version is `6.0.0`.

Please update to the latest version of `@angular/cli`.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by kristiannotari** [comment]
Sorry for bothering you again but I have done the following with success but still encounter an issue:

- cleaned my environment (removed node and npm, my repo)
- installed latest LTS version of node (with npm)
- installed the 6.2.7 version of @angular/cli both globally and in my repo package json (dev dep)
- tried `ng update @angular/cli` in order to obtain the new needed angular.json file (instead of angular-cli.json)
- tried `ng serve` but it tells me to get Angular 5.0.0 or higher.

```
This version of CLI is only compatible with Angular version 5.0.0 or higher.

Please visit the link below to find instructions on how to update Angular.
https://angular-update-guide.firebaseapp.com/
```

There's still a way to ng serve a repo which uses Angular 2.2.3?
