### ISSUE TITLE
ENOSPC error after ng serve

### ISSUE THREAD

**Issue by t8g** [angular/angular-cli#130]
Linux with node 5.3.0 (and plenty of free disk space ;) )
Got this stack

```
Build successful - 1857ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
DiffingTSCompiler                             | 1769ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
DiffingTSCompiler (1)                         | 1769ms              

fs.js:1315
    throw error;
    ^

Error: watch /home/t8g/devs/talc/tata/node_modules/angular-cli/node_modules/ember-cli/node_modules/bower/node_modules/update-notifier/node_modules/string-length/node_modules ENOSPC
    at exports._errnoException (util.js:855:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at NodeWatcher.watchdir (/home/t8g/devs/talc/tata/node_modules/angular-cli/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/t8g/devs/talc/tata/node_modules/angular-cli/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:351:12)
    at emitTwo (events.js:87:13)
    at Walker.emit (events.js:172:7)
    at /home/t8g/devs/talc/tata/node_modules/angular-cli/node_modules/ember-cli/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by brombomb** [comment]
Ran into a similar issue.  It was due to using up the maximum number of file watchers on my system.  A good reference I found: http://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached

Specifically mine was caused by powerline daemon using a few and then NodeWatcher trying to use the rest.  Setting this to a larger number as linked above fixed it for me.

**Comment by t8g** [comment]
Thanks.
It works !

**Comment by stefanhuber** [comment]
I had the same problem on Ubuntu 14.04. The referenced solution also worked for me! Thx!

**Comment by MasterKale** [comment]
Does anyone know how to make the new `max_user_watches` value stick? I'm having to do this every time I restart my machine, despite my running the following `echo` command as per the solution:

`echo 524288 | sudo tee -a /proc/sys/fs/inotify/max_user_watches`
