### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with: Cannot find module 'rxjs/observable'

### ISSUE THREAD

**Issue by lakinoheat** [angular/angular-cli#1306]
**The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:**
Error: Typescript found the following errors:
  /root/test/tmp/broccoli_type_script_compiler-input_base_path-gDo7y1vA.tmp/0/src/app/dispatch/dispatch.component.ts (4, 31): **Cannot find module 'rxjs/observable'.**
  /root/test/tmp/broccoli_type_script_compiler-input_base_path-gDo7y1vA.tmp/0/src/app/services/dropdown/dropdown.service.ts (7, 31): **Cannot find module 'rxjs/observable'.**
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/root/test/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/root/test/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /root/test/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/root/test/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/root/test/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/root/test/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/root/test/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**The broccoli plugin was instantiated at:**
    at BroccoliTypeScriptCompiler.Plugin (/root/test/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/root/test/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/root/test/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (/root/test/node_modules/angular-cli/lib/broccoli/angular2-app.js:321:18)
    at Angular2App._buildTree (/root/test/node_modules/angular-cli/lib/broccoli/angular2-app.js:116:23)
    at new Angular2App (/root/test/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/root/test/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/root/test/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/root/test/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/root/test/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/root/test/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /root/test/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/root/test/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/root/test/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /root/test/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/root/test/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

**Am using Ubuntu 14.04 node 4.4.7**

**Comment by jimulle** [comment]
I had experienced some similar issues with our jenkins build server... turned out it was a case issue:

`import { Observable } from  'rxjs/observable';`
should be
`import { Observable } from  'rxjs/Observable';` 

We did not see the issue on our windows machines or in OSX on a mac, but on the linux build server it threw the error.

**Comment by lakinoheat** [comment]
fixed by changing case of 'rxjs/observable' to 'rxjs/Observable'

**Comment by alxolr** [comment]
For me worked When I did

`import { Obsevable } from 'rxjs/Rx'`;
