### ISSUE TITLE
build --aot fails inlining resources in 7.x

### ISSUE THREAD

**Issue by no-more** [angular/angular-cli#13070]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
node -v
v10.13.0
```

```
npm -v
6.4.0
```

```
yarn -v
1.12.3
```

```
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.1.0
Node: 10.13.0
OS: win32 x64
Angular: 7.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.0
@angular-devkit/build-angular      0.11.0
@angular-devkit/build-ng-packagr   0.11.0
@angular-devkit/build-optimizer    0.11.0
@angular-devkit/build-webpack      0.11.0
@angular-devkit/core               7.1.0
@angular-devkit/schematics         7.1.0
@angular/flex-layout               7.0.0-beta.19
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.0
@schematics/angular                7.1.0
@schematics/update                 0.11.0
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1
```

### Repro steps

When I run `nb build subApplicationName --aot` I have the following error if I use `templateUrl` or `styleUrls` in ANY of my components. I have no issue as long as I use `template` and `styles` only.

### The log given by the failure

```
ERROR in : Error: Cannot handle async resource. angularCompilerOptions.enableResourceInlining requires all resources to be statically resolvable.
    at Object.get (S:\syscea\node_modules\@angular\compiler-cli\src\transformers\inline_resources.js:33:31)
    at S:\syscea\node_modules\@angular\compiler-cli\src\transformers\inline_resources.js:261:43
    at Array.forEach (<anonymous>)
    at updateComponentProperties (S:\syscea\node_modules\@angular\compiler-cli\src\transformers\inline_resources.js:232:33)
    at updateDecorator (S:\syscea\node_modules\@angular\compiler-cli\src\transformers\inline_resources.js:120:28)
    at S:\syscea\node_modules\@angular\compiler-cli\src\transformers\inline_resources.js:95:32
    at Object.visitNodes (S:\syscea\node_modules\typescript\lib\typescript.js:62256:48)
    at visitor (S:\syscea\node_modules\@angular\compiler-cli\src\transformers\inline_resources.js:93:40)
    at visitNodes (S:\syscea\node_modules\typescript\lib\typescript.js:62256:48)
    at visitLexicalEnvironment (S:\syscea\node_modules\typescript\lib\typescript.js:62289:22)
    at Object.visitEachChild (S:\syscea\node_modules\typescript\lib\typescript.js:62593:54)
    at S:\syscea\node_modules\@angular\compiler-cli\src\transformers\inline_resources.js:105:23
    at S:\syscea\node_modules\typescript\lib\typescript.js:1354:86
    at reduceLeft (S:\syscea\node_modules\typescript\lib\typescript.js:1066:30)
    at S:\syscea\node_modules\typescript\lib\typescript.js:1354:42
    at transformRoot (S:\syscea\node_modules\typescript\lib\typescript.js:79271:82)
```

### Desired functionality

It would be great to have the name (and path) of the file that generate an error. In this particular case all the files are concerned but it took me hours to find out what was causing the issue as I had to test several files before resigning to update all the files for debugging.

### Mention any other details that might be useful

I didn't had this issue with angular 6.x but as the migration process was quite long (and includes other changes) the issue might not be directly related to angular v7.x

**Comment by no-more** [comment]
After switching back to angular 6.x AOT compilation works once again.

But I can't tell if this is due to angular-cli or angular.

**Comment by clydin** [comment]
Do you have `enableResourceInlining` within the application's `tsconfig`?

**Comment by clydin** [comment]
That option is only intended for libraries and should not be enabled for applications.
An application in JIT mode will not be run through the Angular compiler (the source of the error) as it is only needed in AOT mode.

**Comment by no-more** [comment]
Thanks a lot it works now.
Strangely this option was not an issue in 6.x
