### ISSUE TITLE
angular-cli 7.1.0 run ng new app has error

### ISSUE THREAD

**Issue by mela93** [angular/angular-cli#13085]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
➜  ~ node --version
v8.9.4
➜  ~ npm --version
5.6.0
➜  ~ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.0
Node: 8.9.4
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.11.0
@angular-devkit/core         7.1.0
@angular-devkit/schematics   7.1.0
@schematics/angular          7.1.0
@schematics/update           0.11.0
rxjs                         6.3.3
typescript                   3.1.6

macOS Mojave
```

### Repro steps
1. ng new Test1-FrontEnd
then show this:
```
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Unexpected end of JSON input while parsing near '...ry.npmjs.org/engine.i'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/name/.npm/_logs/2018-11-29T06_15_19_069Z-debug.log
Package install failed, see above.
```

### The log given by the failure
```
4228 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ry.npmjs.org/engine.i'
4228 verbose stack     at JSON.parse (<anonymous>)
4228 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
4228 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
4228 verbose stack     at <anonymous>
4228 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
4229 verbose cwd /Users/name/Desktop/Project/Test1-FrontEnd
4230 verbose Darwin 18.2.0
4231 verbose argv "/usr/local/Cellar/node/9.4.0/bin/node" "/usr/local/bin/npm" "i"
4232 verbose node v8.9.4
4233 verbose npm  v5.6.0
4234 error Unexpected end of JSON input while parsing near '...ry.npmjs.org/engine.i'
4235 verbose exit [ 1, true ]
```

**Comment by mela93** [comment]
solved try:
`npm cache clean --force`

**Comment by Jatin-8898** [comment]
Tried clearing cache and again reinstalling 
But Didnt worked
