### ISSUE TITLE
ng serve crashes after second save angular-cli v6.2.8

### ISSUE THREAD

**Issue by house-md** [angular/angular-cli#13161]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
NPM: 6.4.1
Angular CLI: 6.2.8
Node: 11.3.0
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.8
@angular/cdk                      6.4.7
@angular/cli                      6.2.8
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@ngtools/webpack                  6.2.5
@schematics/angular               0.8.8
@schematics/update                0.8.8
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.20.2

### Repro steps
first build after ng serve --aot runs successfully but second build after change crashes with error

### The log given by the failure
** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **

Date: 2018-12-10T11:33:03.111Z
Hash: 7ea248c1d20c235a6a52
Time: 109289ms
chunk {app-02-core-advisor-advisor-module-ngfactory} app-02-core-advisor-advisor-module-ngfactory.js, app-02-core-advisor-advisor-module-ngfactory.js.map (app-02-core-advisor-advisor-module-ngfactory) 663 kB  [rendered]
chunk {app-02-core-clientele-client-module-ngfactory} app-02-core-clientele-client-module-ngfactory.js, app-02-core-clientele-client-module-ngfactory.js.map (app-02-core-clientele-client-module-ngfactory) 309 kB  [rendered]
chunk {app-02-core-offer-offer-module-ngfactory} app-02-core-offer-offer-module-ngfactory.js, app-02-core-offer-offer-module-ngfactory.js.map (app-02-core-offer-offer-module-ngfactory) 38.8 kB  [rendered]
chunk {app-02-core-portal-product-selection-product-selection-module-ngfactory} app-02-core-portal-product-selection-product-selection-module-ngfactory.js, app-02-core-portal-product-selection-product-selection-module-ngfactory.js.map (app-02-core-portal-product-selection-product-selection-module-ngfactory) 41.3 kB  [rendered]
chunk {common} common.js, common.js.map (common) 19.2 kB  [rendered]
chunk {default~app-02-core-advisor-advisor-module-ngfactory~app-02-core-clientele-client-module-ngfactory~e~6ad69d25} default~app-02-core-advisor-advisor-module-ngfactory~app-02-core-clientele-client-module-ngfactory~e~6ad69d25.js, default~app-02-core-advisor-advisor-module-ngfactory~app-02-core-clientele-client-module-ngfactory~e~6ad69d25.js.map (default~ap
p-02-core-advisor-advisor-module-ngfactory~app-02-core-clientele-client-module-ngfactory~e~6ad69d25) 39.4 kB  [rendered]
chunk {default~app-02-core-clientele-client-module-ngfactory~edit-client-edit-module-ngfactory~edit-vehicle~666d5666} default~app-02-core-clientele-client-module-ngfactory~edit-client-edit-module-ngfactory~edit-vehicle~666d5666.js, default~app-02-core-clientele-client-module-ngfactory~edit-client-edit-module-ngfactory~edit-vehicle~666d5666.js.map (default~ap
p-02-core-clientele-client-module-ngfactory~edit-client-edit-module-ngfactory~edit-vehicle~666d5666) 21.1 kB  [rendered]
chunk {edit-client-edit-module-ngfactory} edit-client-edit-module-ngfactory.js, edit-client-edit-module-ngfactory.js.map (edit-client-edit-module-ngfactory) 310 kB  [rendered]
chunk {edit-vehicle-offer-vehicle-offer-edit-module-ngfactory} edit-vehicle-offer-vehicle-offer-edit-module-ngfactory.js, edit-vehicle-offer-vehicle-offer-edit-module-ngfactory.js.map (edit-vehicle-offer-vehicle-offer-edit-module-ngfactory) 2.32 MB  [rendered]
chunk {list-client-list-module-ngfactory} list-client-list-module-ngfactory.js, list-client-list-module-ngfactory.js.map (list-client-list-module-ngfactory) 110 kB  [rendered]
chunk {list-offer-list-module-ngfactory} list-offer-list-module-ngfactory.js, list-offer-list-module-ngfactory.js.map (list-offer-list-module-ngfactory) 237 kB  [rendered]
chunk {main} main.js, main.js.map (main) 1.09 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 10.2 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 327 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 519 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 9.41 MB [initial] [rendered]
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
C:\Users\dosta\Projects\verzuz\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:92
                                        throw data[0];
                                        ^

Error: ENOENT: no such file or directory, stat 'C:\Users\dosta\Projects\verzuz\src\app\01-layout\layout\layout.component.ngfactory.js'
    at Object.statSync (fs.js:874:3)
    at Object.statSync (C:\Users\dosta\Projects\verzuz\node_modules\graceful-fs\polyfills.js:297:22)
    at Storage.provideSync (C:\Users\dosta\Projects\verzuz\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.statSync (C:\Users\dosta\Projects\verzuz\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:251:28)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\Users\dosta\Projects\verzuz\node_modules\@ngtools\webpack\src\webpack-input-host.js:70:52)
    at Observable._trySubscribe (C:\Users\dosta\Projects\verzuz\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:43:25)
    at Observable.subscribe (C:\Users\dosta\Projects\verzuz\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:29:22)
    at MapOperator.call (C:\Users\dosta\Projects\verzuz\node_modules\@ngtools\webpack\node_modules\rxjs\internal\operators\map.js:29:23)
    at Observable.subscribe (C:\Users\dosta\Projects\verzuz\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:24:22)
    at SyncDelegateHost._doSyncCall (C:\Users\dosta\Projects\verzuz\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:22:20)
    at SyncDelegateHost.exists (C:\Users\dosta\Projects\verzuz\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:61:21)
    at WebpackCompilerHost.fileExists (C:\Users\dosta\Projects\verzuz\node_modules\@ngtools\webpack\src\compiler_host.js:195:44)
    at VirtualFileSystemDecorator._statSync (C:\Users\dosta\Projects\verzuz\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:24:39)
    at VirtualFileSystemDecorator.statSync (C:\Users\dosta\Projects\verzuz\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:60:29)
    at virtualFilesStats._virtualInputFileSystem.getVirtualFilesPaths.map (C:\Users\dosta\Projects\verzuz\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:123:54)
    at Array.map (<anonymous>)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue might be obsolete due to changes in the recent releases Version 6 is currently in LTS. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
