### ISSUE TITLE
allowJs:true fails when building library

### ISSUE THREAD

**Issue by ckddbs** [angular/angular-cli#13365]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.1.4
Node: 8.11.3
OS: darwin x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.4
@angular-devkit/build-angular      0.11.4
@angular-devkit/build-ng-packagr   0.11.4
@angular-devkit/build-optimizer    0.11.4
@angular-devkit/build-webpack      0.11.4
@angular-devkit/core               7.1.4
@angular-devkit/schematics         7.1.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.4
@schematics/angular                7.1.4
@schematics/update                 0.11.4
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1

### Repro steps
1. ng new app-test
2. ng generate lib-test
3. edit projects/lib-test/tsconfig.lib.json
4. ng build lib-test
{
"extends": "../../tsconfig.json",
"compilerOptions": {
"outDir": "../../out-tsc/lib",
"target": "es2015",
"module": "es2015",
"moduleResolution": "node",
"allowJs": true,
"declaration": false,
"sourceMap": true,
"inlineSources": true,
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"importHelpers": true,
"types": [],
"lib": [
"dom",
"es2018"
]
},
"angularCompilerOptions": {
"annotateForClosureCompiler": true,
"skipTemplateCodegen": true,
"strictMetadataEmit": true,
"fullTemplateTypeCheck": true,
"strictInjectionParameters": true,
"enableResourceInlining": true
},
"exclude": [
"src/test.ts",
"**/*.spec.ts"
]
}

### The log given by the failure
Error: error TS5053: Option 'allowJs' cannot be specified with option 'declaration'.

    at Object. (/.../node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next ()
    at /.../node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise ()
    at __awaiter (/.../node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/.../node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object. (/.../node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next ()
    at /.../node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise ()

**Comment by ckddbs** [comment]
In Angular app, it works importing and using .JS files in .TS file without allowJs option. However, in Angular library, it throws an error while building library. The error is .JS file cannot be found. How can I build Angular library including .JS files?

**Comment by alan-agius4** [comment]
Applications and libraries follow two different build pipelines. 

Also using `.js` with and without using allowJs is different in an application. When using allowJs javascript will be transpiled by the compiler. While when not using it will be just read.

In library at the moment, there’s is not effective way to you a js file, unless it’s a separate node package.
