### ISSUE TITLE
Build error message on Windows when build to UNC path

### ISSUE THREAD

**Issue by guidoffm** [angular/angular-cli#1344]
Version: angular-cli@1.0.0-beta.9
Windows 10

Build succeeds but ugly message appears:
"No asset files found in the path provided"

Example:
ng b -prod -o \\infcsr34004\InfcBoardV4$\
(node:12768) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Built project successfully. Stored in "\\infcsr34004\InfcBoardV4$\".
No asset files found in the path provided: \\infcsr34004\InfcBoardV4$\
Error: No asset files found in the path provided: \\infcsr34004\InfcBoardV4$\
    at Class.module.exports.Task.extend.validateAssetPath (C:\FrontendBootstrap\node_modules\angular-cli\node_modules\angular-cli\lib\models\asset-size-printer.js:71:13)
    at Class.<anonymous> (C:\FrontendBootstrap\node_modules\angular-cli\node_modules\angular-cli\lib\models\asset-size-printer.js:22:14)
    at lib$rsvp$$internal$$tryCatch (C:\FrontendBootstrap\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\FrontendBootstrap\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at C:\FrontendBootstrap\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:331:11
    at lib$rsvp$asap$$flush (C:\FrontendBootstrap\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.
