### ISSUE TITLE
Including CommonModule causes build to break

### ISSUE THREAD

**Issue by trickeyone** [angular/angular-cli#13440]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

macOS High Sierra Version 10.13.6 (17G65)
```
$ node --version
v11.6.0
$ npm --version
6.5.0
$ yarn --version
1.13.0
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.2.1
Node: 11.6.0
OS: darwin x64
Angular: 7.0.0
... common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.7
@angular-devkit/build-angular      0.10.7
@angular-devkit/build-ng-packagr   0.10.7
@angular-devkit/build-optimizer    0.10.7
@angular-devkit/build-webpack      0.10.7
@angular-devkit/core               7.0.7
@angular-devkit/schematics         7.2.1
@angular/cli                       7.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.7
@schematics/angular                7.2.1
@schematics/update                 0.12.1
ng-packagr                         4.5.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1
```

### The log given by the failure

```
$ yarn build
yarn run v1.13.0
$ ng build --prod
Building Angular Package

BUILD ERROR
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at /path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:15519:31
    at Array.forEach (<anonymous>)
    at removeSummaryDuplicates (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:15518:15)
    at TemplateParser.tryParseHtml (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:14935:33)
    at TemplateParser.tryParse (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:14927:25)
    at TemplateParser.parse (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:14908:31)
    at AotCompiler._parseTemplate (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:22299:47)
    at AotCompiler._createTypeCheckBlock (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:22046:27)
    at /path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:22014:31
    at Array.forEach (<anonymous>)

Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at /path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:15519:31
    at Array.forEach (<anonymous>)
    at removeSummaryDuplicates (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:15518:15)
    at TemplateParser.tryParseHtml (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:14935:33)
    at TemplateParser.tryParse (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:14927:25)
    at TemplateParser.parse (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:14908:31)
    at AotCompiler._parseTemplate (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:22299:47)
    at AotCompiler._createTypeCheckBlock (/path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:22046:27)
    at /path/to/project/node_modules/@angular/compiler/bundles/compiler.umd.js:22014:31
    at Array.forEach (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Desired functionality

It's a very basic setup. I've spent 4 days trying to figure out what the problem is, but all I can tell is that it comes from CommonModule being imported into the module. If I remove that, everything builds fine. In the real-world usage, the components are more complex, but I've been able to create an example in the following repo: https://github.com/trickeyone/angular-error-test

It consists of a single component and a single module. The example doesn't have any tests or anything, but the original project that I encountered the issue in has a demo/tests/etc. The demo builds fine. The tests run fine. It's only when I go to build the library that the error happens.

**Comment by alan-agius4** [comment]
Updating to ng-packagr version 4.6.0 fixes the problem.

**Comment by trickeyone** [comment]
Cool. It was just released, and does indeed fix the error. Thanks!
