### ISSUE TITLE
ng serve : provided host could not be bound.

### ISSUE THREAD

**Issue by imrohitM** [angular/angular-cli#13478]
I have created a angular project on an Instance(linux) on AWS EC2.When i tried **

> ''ng serve --host 13.233.11.155"
 
- This Error was thrown :

**Provided host 13.233.11.155 could NOT be bound. Please provide a different host address or hostname
Error: Provided host 13.233.11.155 could NOT be bound. Please provide a different host address or hostname
    at /usr/documents/Test/angularTest/angular-test/node_modules/portfinder/lib/portfinder.js:168:27
    at /usr/documents/Test/angularTest/angular-test/node_modules/async/lib/async.js:52:16
    at /usr/documents/Test/angularTest/angular-test/node_modules/async/lib/async.js:264:21
    at /usr/documents/Test/angularTest/angular-test/node_modules/async/lib/async.js:44:16
    at /usr/documents/Test/angularTest/angular-test/node_modules/portfinder/lib/portfinder.js:146:16
    at Server.onError (/usr/documents/Test/angularTest/angular-test/node_modules/portfinder/lib/portfinder.js:52:14)
    at Object.onceWrapper (events.js:276:13)
    at Server.emit (events.js:188:13)
    at emitErrorNT (net.js:1281:8)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)** 

I've the latest version of node, npm.  13.233.11.155 is the public IP of the instance.
Any help is appreciated.
Thanks

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
