### ISSUE TITLE
Typescript Error only in JIT

### ISSUE THREAD

**Issue by GerritK** [angular/angular-cli#13471]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Node: v10.15.0
NPM: 6.6.0
NG: 
Angular CLI: 7.2.2
Node: 10.15.0
OS: win32 x64
Angular: 7.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.2.2
@angular/cli                      7.2.2
@ngtools/webpack                  7.2.2
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4
OS: Windows 10 64bit
```

### Repro steps
ng build or ng serve with jit compilation

### The log given by the failure
```
ERROR in : Error: Debug Failure. Unexpected node.
Node PrefixUnaryExpression was unexpected.
    at serializeTypeNode (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:67332:45)
    at serializeTypeOfNode (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:67212:28)
    at addOldTypeMetadata (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:67128:92)
    at addTypeMetadata (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:67122:17)
    at transformAllDecoratorsOfDeclaration (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:66957:13)
    at generateClassElementDecorationExpression (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:67004:40)
    at generateClassElementDecorationExpressions (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:66984:34)
    at addClassElementDecorationStatements (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:66969:44)
    at visitClassDeclaration (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:66279:13)
    at visitTypeScript (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:66110:28)
    at visitorWorker (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:65894:24)
    at sourceElementVisitorWorker (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:65923:28)
    at saveStateAndInvoke (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:65832:27)
    at sourceElementVisitor (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:65908:20)
    at visitNodes (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:63441:48)
    at Object.visitLexicalEnvironment (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:63474:22)
    at visitSourceFile (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:66199:53)
    at saveStateAndInvoke (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:65832:27)
    at transformSourceFile (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:65815:27)
    at transformSourceFileOrBundle (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:65795:20)
    at X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:1390:86
    at reduceLeft (X:\IdeaProjects\my-app\node_modules\typescript\lib\typescript.js:1102:30)
```

### Desired functionality
This error should not occur, it think. In AOT compilation all works great.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
