### ISSUE TITLE
npm run e2e is failing on a new fresh project

### ISSUE THREAD

**Issue by bhaidar** [angular/angular-cli#13506]
# 🐞 Bug report

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No

### Description

I create a new project with the Angular CLI and then try to run `npm run e2e` it fails! I have `chromedriver` in the PATH on my windows machine.

## 🔬 Minimal Reproduction

Just create a new project with the ng command and then run `npm run e2e`.

## 🔥 Exception or Error
<pre><code>
$ npm run e2e

> angular-e2e-tutorial@0.0.0 e2e D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial
> ng e2e

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2019-01-23T12:03:54.255Z
Hash: 5f1a9925682e0be3b754
Time: 11781ms
chunk {main} main.js, main.js.map (main) 40.3 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.8 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.01 MB [initial] [rendered]
i ｢wdm｣: Compiled successfully.
[14:03:55] I/update - chromedriver: file exists D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\webdriver-manager\selenium\chromedriver_2.45.zip
[14:03:55] I/update - chromedriver: unzipping chromedriver_2.45.zip
[14:03:55] I/update - chromedriver: chromedriver_2.45.exe up to date
[14:03:56] I/launcher - Running 1 instances of WebDriver
[14:03:56] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:61535/devtools/browser/6db47b40-a9fd-4d8a-b601-6aecee172399
[14:04:58] E/launcher - unknown error: unable to discover open pages
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17134 x86_64)
[14:04:58] E/launcher - WebDriverError: unknown error: unable to discover open pages
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 10.0.17134 x86_64)
    at Object.checkLegacyResponse (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at Direct.getNewDriver (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\protractor\built\driverProviders\direct.js:77:33)
    at Runner.createBrowser (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\q\q.js:834:54)
    at D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\q\q.js:796:13)
    at D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\q\q.js:556:49
    at runSingle (D:\Projects\Playground\angular-e2e-testing\angular-e2e-tutorial\node_modules\q\q.js:137:13)
[14:04:58] E/launcher - Process exited with error code 199
An unexpected error occurred: undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-e2e-tutorial@0.0.0 e2e: `ng e2e`
</code></pre>

## 🌍 Environment
<pre><code>
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.2.2
Node: 10.14.1
OS: win32 x64
Angular: 7.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.2.2
@ngtools/webpack                  7.2.2
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4
</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. 

I suggest you try to find/file your issue here: https://bugs.chromium.org/p/chromedriver
