### ISSUE TITLE
ng serve subsequent build throws error

### ISSUE THREAD

**Issue by surajpoddar16** [angular/angular-cli#13570]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: .7.0.4.

### Description

While running ng serve I added a new component in a git branch(lets call it `test`) and changed back to dev branch, the project was rebuilt perfectly, after this every alternate branch change to `test` branch results in build failure.

## 🔬 Minimal Reproduction

- With Angular CLI version 7.2.4, create a new project
- In a seperate terminal run `npm run start`
- Create a new branch named test
- Run command ng g c test
- Commit the changes
- Switch back to master, the project should rebuild without error
- Now switch to test branch again, the build should fail
- If the build succeeds try switching back and forth again

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/app/test/test.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/surajpoddar/Desktop/work/misc/ng-test/src/app/test/test.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/surajpoddar/Desktop/work/misc/ng-test/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:752:23)
    at plugin.done.then (/Users/surajpoddar/Desktop/work/misc/ng-test/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### Also getting this error in some cases

Cannot read property 'externalModuleIndicator' of undefined
    at Object.isExternalModule (/Users/surajpoddar/Desktop/work/hevo/hevo-ui/node_modules/typescript/lib/typescript.js:16637:21)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.2.4
Node: 10.13.0
OS: darwin x64
Angular: 7.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cli                      7.2.4
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4
</code></pre>

**Anything else relevant?**

**Comment by surajpoddar16** [comment]
Guys, any update on this? Was anyone able to reproduce this?

**Comment by alan-agius4** [comment]
@surajpoddar16, yes, I was able to reproduce this.

**Comment by surajpoddar16** [comment]
@alan-agius4 I think this related to CachedFileInputSystem. the cached files are not cleared on branch change.

`Error: ENOENT: no such file or directory, open '/Users/surajpoddar/Desktop/work/hevo/hevo-ui/src/app/workflow/service/recent-workflow.resolver.ts'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Storage.provideSync (/Users/surajpoddar/Desktop/work/hevo/hevo-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)`

**Comment by surajpoddar16** [comment]
@alan-agius4 Any update on this?

**Comment by emimarz** [comment]
this fill my error logs... please, fix it

**Comment by surajpoddar16** [comment]
Hey guys, just checking to know if there is any workaround this?
