### ISSUE TITLE
Building Library after GIT clone failed

### ISSUE THREAD

**Issue by 4i-helpynet** [angular/angular-cli#13585]
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Working Angular project commit&push-ed to GIT
Angular library build isn't work when the angular project cloned from GIT

## 🔬 Minimal Reproduction
1 PC1: Create new angular project,
2 PC1: Create new angular library with workspace
3 PC1: Create new angular application using the library created before
4 PC1: Commit & push to github
5 PC2: Clone repo pushed before
6 PC2 Try to build library

## 🔥 Exception or Error
<pre><code>
Building Angular Package
Building entry point '[[library name]]'
Compiling TypeScript sources through ngc

BUILD ERROR
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at [[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:21259:31
    at Array.forEach (<anonymous>)
    at removeSummaryDuplicates ([[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:21258:15)
    at TemplateParser.tryParseHtml ([[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:20674:38)
    at TemplateParser.tryParse ([[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:20667:25)
    at TemplateParser.parse ([[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:20648:31)
    at AotCompiler._parseTemplate ([[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:24135:47)
    at AotCompiler._createTypeCheckBlock ([[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:23882:27)
    at [[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:23851:31
    at Array.forEach (<anonymous>)
    at [[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:23844:53
    at Array.forEach (<anonymous>)
    at AotCompiler._createNgFactoryStub ([[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:23823:28)
    at AotCompiler.emitTypeCheckStub ([[PROJECT DIR]]\node_modules\@angular\compiler\bundles\compiler.umd.js:23791:22)
    at [[PROJECT DIR]]\node_modules\@angular\compiler-cli\src\transformers\program.js:656:54
    at Array.forEach (<anonymous>)

Compilation failed. Watching for file changes...
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.0
Node: 9.8.0
OS: win32 x64
Angular: 7.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.0
@angular-devkit/build-angular      0.13.0
@angular-devkit/build-ng-packagr   0.13.0
@angular-devkit/build-optimizer    0.13.0
@angular-devkit/build-webpack      0.13.0
@angular-devkit/core               7.3.0
@angular-devkit/schematics         7.3.0
@angular/cli                       7.3.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.0
@schematics/angular                7.3.0
@schematics/update                 0.13.0
ng-packagr                         4.7.0
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0
</code></pre>

**Comment by rhino5oh** [comment]
Angular requires Node.js version 8.x or 10.x according to [this](https://angular.io/guide/quickstart#prerequisites), and it looks like you have node 9.  try changing your node version first and see if that helps

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.

Can you kindly share a reproduction?

Thanks

**Comment by 4i-helpynet** [comment]
Hi all

Upgrade to Node.js 10.15.1 fixed the problem,

Thank you
