### ISSUE TITLE
ng build fails for angular routing injection 

### ISSUE THREAD

**Issue by lamaan** [angular/angular-cli#1360]
> ## Please provide us with the following information:
> 1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10
2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
v5.6.0
1. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   build an app based on the documentation for angular 2 router  currently version 3.0.0-beta.2 and then do an ng build.
2. The log given by the failure. Normally this include a stack trace and some
   more information.

[local path]/app/MyApp/tmp/broccoli_type_script_compiler-input_base_path-lmMYbBnp.tmp/0/src/app/word-definitions/word-definitions.component.spec.ts (17, 21): Supplied parameters do not match any signature of call target.
    at BroccoliTypeScriptCompiler._doIncrementalBuild ([local path]\app\MyApp\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build ([local path]\app\MyApp\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at [local path]\app\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch ([local path]\app\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback ([local path]\app\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish ([local path]\app\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush ([local path]\app\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin ([local path]\app\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor]([local path]appMyAppnode_modulesangular-clinode_modulesbroccoli-caching-writerindex.js:21:10)
    at BroccoliTypeScriptCompiler ([local path]\app\MyApp\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:26:49)
    at Angular2App._getTsTree ([local path]\app\MyApp\node_modules\angular-cli\lib\broccoli\angular2-app.js:321:18)
    at Angular2App._buildTree ([local path]\app\MyApp\node_modules\angular-cli\lib\broccoli\angular2-app.js:116:23)
    at new Angular2App ([local path]\app\MyApp\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports ([local path]\app\MyApp\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder ([local path]\app\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init ([local path]\app\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class ([local path]\app\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run ([local path]\app\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at [local path]\app\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch ([local path]\app\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback ([local path]\app\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish ([local path]\app\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush ([local path]\app\MyApp\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
5. Mention any other details that might be useful.

> ---

the application runs fine with ng serve. But it won't build. Removing the injection in the constructor fixes the build but breaks the app

 constructor( private route:ActivatedRoute
    ) {}

routing docs being followed are https://angular.io/docs/ts/latest/guide/router.html

> > Thanks! We'll be in touch soon.

**Comment by baruchvlz** [comment]
I'm getting the same error.

**Versions**
```
angular-cli: 1.0.0-beta.8
node: 6.2.0
os: darwin x64
```

**Error Stack**
```
Build failed.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/baruchvelez/Development/ng2/dynamicforms/tmp/broccoli_type_script_compiler-input_base_path-d9byHu9n.tmp/0/src/app/character-lookup/character-lookup.component.spec.ts (17, 21): Supplied parameters do not match any signature of call target.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/lib/broccoli/angular2-app.js:321:18)
    at Angular2App._buildTree (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/lib/broccoli/angular2-app.js:116:23)
    at new Angular2App (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/baruchvelez/Development/ng2/dynamicforms/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at /Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/angular-cli/lib/commands/build.js:32:24
    at lib$rsvp$$internal$$tryCatch (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/baruchvelez/Development/ng2/dynamicforms/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Line 17, Column 21 of `src/app/character-lookup/character-lookup.component.spec.ts`**
```javascript
export class CharacterLookupComponent implements OnInit {
```
[Complete file](https://github.com/baruchvlz/ng2-dynamic-forms/blob/dev/src/app/character-lookup/character-lookup.component.ts)

[app.routes.ts](https://github.com/baruchvlz/ng2-dynamic-forms/blob/dev/src/app/app.routes.ts)

**Comment by filipesilva** [comment]
Can you give me a repo where this problem exists so I can debug? 

`src/app/word-definitions/word-definitions.component.spec.ts (17, 21): Supplied parameters do not match any signature of call target.` seems a run of the mill TS error to me but I can be wrong.

**Comment by Brocco** [comment]
This issue is outdated and based upon the old build system, closing.
