### ISSUE TITLE
Build fails when building library which contains a library with pipes

### ISSUE THREAD

**Issue by Jonnyprof** [angular/angular-cli#13641]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
I don't think so.

### Description
When building a library that contains another library **which is paced in yarn workspaces**(symlinks to dist folder) the build fails.
There are no errors if the other library is different than pipe (component, directive, etc).

## 🔬 Minimal Reproduction
I've created a repository with very simple libraries to reproduce the problem. It has the reproduction steps in readme file. https://github.com/Jonnyprof/libraryPipes
I've published @example-libs libraries in npmjs repository to help with the process.

## 🔥 Exception or Error
<pre><code>
BUILD ERROR
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at /media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:21259:31
    at Array.forEach (<anonymous>)
    at removeSummaryDuplicates (/media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:21258:15)
    at TemplateParser.tryParseHtml (/media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:20675:33)
    at TemplateParser.tryParse (/media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:20667:25)
    at TemplateParser.parse (/media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:20648:31)
    at AotCompiler._parseTemplate (/media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:24135:47)
    at AotCompiler._createTypeCheckBlock (/media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:23882:27)
    at /media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:23850:31
    at Array.forEach (<anonymous>)
    at /media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:23844:53
    at Array.forEach (<anonymous>)
    at AotCompiler._createNgFactoryStub (/media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:23823:28)
    at AotCompiler.emitTypeCheckStub (/media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler/bundles/compiler.umd.js:23791:22)
    at /media/john/Mes/Webs/proves/libraryPipes/node_modules/@angular/compiler-cli/src/transformers/program.js:656:54
    at Array.forEach (<anonymous>)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.0
Node: 11.5.0
OS: linux x64
Angular: 7.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.0
@angular-devkit/build-angular      0.13.0
@angular-devkit/build-ng-packagr   0.13.0
@angular-devkit/build-optimizer    0.13.0
@angular-devkit/build-webpack      0.13.0
@angular-devkit/core               7.3.0
@angular-devkit/schematics         7.3.0
@angular/cli                       7.3.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.0
@schematics/angular                7.3.0
@schematics/update                 0.13.0
ng-packagr                         4.7.0
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0
</code></pre>

**Anything else relevant?**
I've spent a lot of time debugging but I have only guesses. I think that the error is related with getting summary from summaryCache, because sometimes it looks for `node_modules/@example-lib/uppercase-pipe` and other for `dist/libs/uppercase-pipe`.

Sorry for my english! :P

**Comment by alan-agius4** [comment]
Hi, my 2 cents would be that you need to enable `preserveSymlinks` in the root tsconfig.

Can you give it a shot?

**Comment by Jonnyprof** [comment]
@alan-agius4 I owe you 2 cents, it worked, thanks!
I've tried preverveSymlinks before, but it seems that in the wrong way. I don't understand, I remember that the error changed but it not work.
I use yarn workspaces to test my libraries before publish, there is no problem with local development.

Thanks a lot!
