### ISSUE TITLE
'npm ci' crashes 'ng build --watch'

### ISSUE THREAD

**Issue by mengzhen94** [angular/angular-cli#13661]
Hello, I am running into an issue that if I have `ng build --watch` running, run `npm ci` will crash `ng build --watch` intermittently with an error 
```
error: ENOENT: no such file or directory, lstat 'node_modules'
    at Object.realpathSync (fs.js:1480:7)
    at compiler.hooks.contextModuleFactory.tap.cmf (node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:465:48)
    at SyncHook.eval [as call] (eval at create node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Compiler.createContextModuleFactory (node_modules/webpack/lib/Compiler.js:519:35)
    at Compiler.newCompilationParams (node_modules/webpack/lib/Compiler.js:526:31)
    at Compiler.compile (node_modules/webpack/lib/Compiler.js:533:23)
    at compiler.hooks.watchRun.callAsync.err (node_modules/webpack/lib/Watching.js:76:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at Watching._go (node_modules/webpack/lib/Watching.js:40:32)
    at Watching._invalidate (node_modules/webpack/lib/Watching.js:165:9)
    at watcher.compiler.watchFileSystem.watch (node_modules/webpack/lib/Watching.js:136:10)
    at newCallback node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:125:13)
    at Watchpack.watcher.once (node_modules/webpack/lib/node/NodeWatchFileSystem.js:59:4)
    at Object.onceWrapper (events.js:273:13)
    at Watchpack.emit (events.js:182:13)
    at Watchpack._onTimeout (node_modules/watchpack/lib/watchpack.js:144:7)
```

I assume this is because `npm ci` automatically removed existing node_modules and `ng build --watch` is watching node_modules. I tried adding 
```
 "exclude": [
    "node_modules"
  ]
```
to `tsconfig.json` but no luck.

Is there anyway to exclude node_modules from `ng build --watch`? Or any idea how to avoid crashing? Thanks

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
