### ISSUE TITLE
ng g component <new component> causes build error

### ISSUE THREAD

**Issue by cmwebby** [angular/angular-cli#1381]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

**Windows 10**

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
**angular-cli: 1.0.0-beta.9
node: 4.4.5
os: win32 x64**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

1.  Create app using angular cli 
2. Create a component using ng g component <new component>
3. run ng serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  C:/xampp/htdocs/calculator/tmp/broccoli_type_script_compiler-input_base_path-BXGoK2lM.tmp/0/src/app/calculator/calcula
tor.component.spec.ts (5, 10): Module '"C:/xampp/htdocs/calculator/node_modules/@angular/core/testing"' has no exported
mng 'addProviders'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\xampp\htdocs\calculator\node_modules\angular-cli\lib\broccoli\
broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (C:\xampp\htdocs\calculator\node_modules\angular-cli\lib\broccoli\broccoli-types
cript.js:43:10)
    at C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:
1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\rsvp\dist\rs
vp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1
019:11)
    at lib$rsvp$asap$$flush (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\broccoli-plug
in\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\xampp\htdocs\calculator\node_modules\angular-cli\no
de_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\xampp\htdocs\calculator\node_modules\angular-cli\lib\broccoli\broccoli-typescript.
js:27:10)
    at Angular2App._getTsTree (C:\xampp\htdocs\calculator\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (C:\xampp\htdocs\calculator\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (C:\xampp\htdocs\calculator\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\xampp\htdocs\calculator\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_m
odules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\angular-c
li\lib\models\builder.js:89:10)
    at new Class (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\angular-cl
i\lib\tasks\serve.js:15:19)
    at C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:
1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\rsvp\dist\rs
vp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1
019:11)
    at lib$rsvp$asap$$flush (C:\xampp\htdocs\calculator\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)`

5. Mention any other details that might be useful.
> I use visual code as an editor and in the new component's spec.ts 'addProviders' states it has no exported member "addProviders".
> I have reinstalled angular-cli using npm but still have this issue
> > Thanks! We'll be in touch soon.

**Comment by stefanaerts** [comment]
?

**Comment by stefanaerts** [comment]
no solution and closed?
