### ISSUE TITLE
ng serve error

### ISSUE THREAD

**Issue by lyminster** [angular/angular-cli#1382]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.9
node: 6.2.2
os: win32 x64

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
Error: Typescript found the following errors:
  D:/Project/angular2/tmp/broccoli_type_script_compiler-input_base_path-FsnqS7zH.tmp/0/src/app/login/login.component.spec.ts (17, 21): Supplied parameters do not match any signature of call target.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (D:\Project\angular2\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (D:\Project\angular2\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at D:\Project\angular2\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\Project\angular2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\Project\angular2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\Project\angular2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\Project\angular2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (D:\Project\angular2\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\Project\angular2\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\Project\angular2\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (D:\Project\angular2\node_modules\angular-cli\lib\broccoli\angular2-app.js:329:18)
    at Angular2App._buildTree (D:\Project\angular2\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (D:\Project\angular2\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\Project\angular2\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\Project\angular2\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\Project\angular2\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (D:\Project\angular2\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\Project\angular2\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at D:\Project\angular2\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\Project\angular2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\Project\angular2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\Project\angular2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\Project\angular2\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

when i run ng serve yesterday its fine but after i restart my com and want to ng serve again it shows this error
any thing happen?

its error on part login.component.spec.ts

```
describe('Component: Login', () => {
  it('should create an instance', () => {
    let component = new LoginComponent();    <<-- this part show an error say that***
    expect(component).toBeTruthy();
  });
});
```

***[ts] Supplied parameters do not match any signature of call target.
(alias) new LoginComponent(_router: Router): LoginComponent
import LoginComponent

**Comment by rcorzogutierrez** [comment]
on part login.component.spec.ts

`let component = new LoginComponent();`

to this:

`let component = LoginComponent`

**Comment by lyminster** [comment]
@rcorzogutierrez 
thanks man that solve my problem
