### ISSUE TITLE
Type definitions cause "TypeError: Cannot read property 'text' of undefined" every other build w/ @ngtools/webpack

### ISSUE THREAD

**Issue by snemvalts** [angular/angular-cli#13832]
# 🐞 Bug report

### Description
Building a hybrid Angular/AngularJS app using `@ngtools/webpack`. First build succeeds. Every other rebuild from then fails, with an obscure Typescript error provided below.

Editing the typescript source to log relevant parameters shows that `@types/angular` is at fault. Removing `@types/angular` (and making lots of changes to codebase) solves the issue.
## 🔬 Minimal Reproduction

Clone [this repo](https://github.com/snemvalts/ngtools-webpack-repo). `npm install` and `npm start`. Edit main.ts. Error should show

## 🔥 Exception or Error
<pre><code>
ERROR in : TypeError: Cannot read property 'text' of undefined
    at getErrorSpanForNode (/Users/xxx/node_modules/typescript/lib/typescript.js:8914:40)
    at createDiagnosticForNodeInSourceFile (/Users/xxx/node_modules/typescript/lib/typescript.js:8835:20)
    at Object.createDiagnosticForNode (/Users/xxx/node_modules/typescript/lib/typescript.js:8826:16)
    at error (/Users/xxx/node_modules/typescript/lib/typescript.js:31423:22)
    at resolveExternalModule (/Users/xxx/node_modules/typescript/lib/typescript.js:32796:17)
    at resolveExternalModuleNameWorker (/Users/xxx/node_modules/typescript/lib/typescript.js:32785:19)
    at Object.getExternalModuleFileFromDeclaration (/Users/xxx/node_modules/typescript/lib/typescript.js:57575:32)
    at tryGetModuleNameFromDeclaration (/Users/xxx/node_modules/typescript/lib/typescript.js:63124:50)
    at Object.getExternalModuleNameLiteral (/Users/xxx/node_modules/typescript/lib/typescript.js:63088:20)
    at createRequireCall (/Users/xxx/node_modules/typescript/lib/typescript.js:77166:33)
    at visitExportDeclaration (/Users/xxx/node_modules/typescript/lib/typescript.js:77228:45)
    at sourceElementVisitor (/Users/xxx/node_modules/typescript/lib/typescript.js:76876:28)
    at Object.visitNodes (/Users/xxx/node_modules/typescript/lib/typescript.js:63441:48)
    at transformCommonJSModule (/Users/xxx/node_modules/typescript/lib/typescript.js:76594:40)
    at transformSourceFile (/Users/xxx/node_modules/typescript/lib/typescript.js:76568:27)
    at transformSourceFileOrBundle (/Users/xxx/node_modules/typescript/lib/typescript.js:65021:57)
    at /Users/xxx/node_modules/typescript/lib/typescript.js:1390:86
    at reduceLeft (/Users/xxx/node_modules/typescript/lib/typescript.js:1102:30)
    at /Users/xxx/node_modules/typescript/lib/typescript.js:1390:42
    at transformRoot (/Users/xxx/node_modules/typescript/lib/typescript.js:81154:82)
    at Object.map (/Users/xxx/node_modules/typescript/lib/typescript.js:429:29)
    at Object.transformNodes (/Users/xxx/node_modules/typescript/lib/typescript.js:81141:30)
    at emitJsFileOrBundle (/Users/xxx/node_modules/typescript/lib/typescript.js:81497:32)
    at emitSourceFileOrBundle (/Users/xxx/node_modules/typescript/lib/typescript.js:81465:13)
    at forEachEmittedFile (/Users/xxx/node_modules/typescript/lib/typescript.js:81373:30)
    at Object.emitFiles (/Users/xxx/node_modules/typescript/lib/typescript.js:81454:9)
    at emitWorker (/Users/xxx/node_modules/typescript/lib/typescript.js:86927:33)
    at /Users/xxx/node_modules/typescript/lib/typescript.js:86887:66
    at runWithCancellationToken (/Users/xxx/node_modules/typescript/lib/typescript.js:86979:24)
    at Object.emit (/Users/xxx/node_modules/typescript/lib/typescript.js:86887:20)
    at defaultEmitCallback (/Users/xxx/node_modules/@angular/compiler-cli/src/transformers/program.js:67:24)
    at AngularCompilerProgram._emitRender2 (/Users/xxx/node_modules/@angular/compiler-cli/src/transformers/program.js:388:34)
    at AngularCompilerProgram.emit (/Users/xxx/node_modules/@angular/compiler-cli/src/transformers/program.js:212:22)
    at AngularCompilerPlugin._emit (/Users/xxx/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:873:49)
    at AngularCompilerPlugin._update (/Users/xxx/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:676:50)
    at anonymous
</code></pre>

## 🌍 Your Environment
<pre><code>"@ngtools/webpack": "7.3.4",
"@types/angular": "1.5.8",
"angular": "1.5.8",
</code></pre>

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
