### ISSUE TITLE
ng-e2e add force Flag to continue protractor test even if spec fails

### ISSUE THREAD

**Issue by CoolM8** [angular/angular-cli#13847]
# 🚀 Feature request

### Command (mark with an `x`)
`ng e2e --force`

### Description
`ng e2e --force` should continue protractor tests even if a spec fails.

### Describe the solution you'd like
Add --force flag to `ng e2e`, the same way it was done or `ng update`:  #10149

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
Hi, I have looked into this and this is seems that specs continue to run after a failure.

```

  workspace-project App
    × should display message
      - Expected 'Welcome to app-layout-new-next!' to equal 'Welcome to app-layout2-new-next!'.
          at UserContext.<anonymous> (C:\git\cli-repos\app-layout-new-next\e2e\src\app.e2e-spec.ts:13:33)
          at new ManagedPromise (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:1077:7)
          at ControlFlow.promise (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:2505:12)
          at TaskQueue.execute_ (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:3084:14)
          at TaskQueue.executeNext_ (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:3067:27)
          at asyncRun (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:2974:25)
          at C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:668:7
    × should display any message
      - Expected 'Welcome to app-layout-new-next!' to equal 'Welcome to app-layout2-new-next!'.
          at UserContext.<anonymous> (C:\git\cli-repos\app-layout-new-next\e2e\src\app.e2e-spec.ts:18:33)
          at new ManagedPromise (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:1077:7)
          at ControlFlow.promise (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:2505:12)
          at TaskQueue.execute_ (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:3084:14)
          at TaskQueue.executeNext_ (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:3067:27)
          at asyncRun (C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:2974:25)
          at C:\git\cli-repos\app-layout-new-next\node_modules\selenium-webdriver\lib\promise.js:668:7
    √ should display welcome message
```

**Comment by CoolM8** [comment]
We have multiple protractor configs that we run. Let's say: 'web', 'ios', 'android'
If any test fails in 'web' config the other configs are not run anymore. 
`protractor run --force` would solve this issue, but this does not work with 'angular e2e'. 
The following ipmlementation would solve our problem: #13648

**Comment by alan-agius4** [comment]
Hi, I think this is quite a specific use case were you want to treat specs failure as non fatal error and for this case I think you can use an npm script you can achieve this, 

Example:

```cmd
ng e2e --configuration web & ng e2e --configuration ios
```

If the first one exits with a non zero error code, it should still continue to execute the other part of the script.

I suggest that for the moment, we leave this outside of the scope of the CLI as adding more code require more maintenance and only implement this if we see that more CLI consumers need this behaviour.

Thank you for your understanding.
