### ISSUE TITLE
TemplateUrl --Mobile?

### ISSUE THREAD

**Issue by BenevidesLecontes** [angular/angular-cli#1391]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MacOS Sierra

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   angular-cli: 1.0.0-beta.10
node: 6.3.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
  ng new foo --mobile

4. The log given by the failure. Normally this include a stack trace and some
   more information.

➜  foo git:(master) ✗ ng init
(node:29448) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
installing ng2
? Overwrite README.md? Yes, overwrite
? Overwrite src/app/app.component.ts? No, skip
? Overwrite src/favicon.ico? Yes, overwrite
? Overwrite src/index.html? No, skip
? Overwrite src/main.ts? No, skip
? Overwrite src/system-config.ts? No, skip
? Overwrite src/tsconfig.json? No, skip
? Overwrite src/typings.d.ts? No, skip
? Overwrite angular-cli-build.js? No, skip
? Overwrite angular-cli.json? No, skip
? Overwrite .gitignore? Yes, overwrite
? Overwrite package.json? No, skip
? Overwrite typings.json? No, skip
  identical .editorconfig
  overwrite README.md
  identical src/app/app.component.css
  identical src/app/app.component.html
  identical src/app/app.component.spec.ts
  skip src/app/app.component.ts
  identical src/app/environment.ts
  identical src/app/index.ts
  identical src/app/shared/index.ts
  overwrite src/favicon.ico
  skip src/index.html
  skip src/main.ts
  skip src/system-config.ts
  skip src/tsconfig.json
  skip src/typings.d.ts
  skip angular-cli-build.js
  skip angular-cli.json
  identical config/environment.dev.ts
  identical config/environment.js
  identical config/environment.prod.ts
  identical config/karma-test-shim.js
  identical config/karma.conf.js
  identical config/protractor.conf.js
  identical e2e/app.e2e-spec.ts
  identical e2e/app.po.ts
  identical e2e/tsconfig.json
  identical e2e/typings.d.ts
  overwrite .gitignore
  skip package.json
  identical public/.npmignore
  identical tslint.json
  skip typings.json
⠏ Installing packages for tooling via npmtypings WARN deprecated 7/20/2016: "registry:dt/node#6.0.0+20160709114037" is deprecated (updated, replaced or removed)
⠙ Installing packages for tooling via npm
├── es6-shim (global)
├── node (global)
├── angular-protractor (global dev)
├── jasmine (global dev)
└── selenium-webdriver (global dev)

Installed packages for tooling via npm.
➜  foo git:(master) ✗ ng serve
(node:29635) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: Command failed: node /Users/benevideschissanga/foo/node_modules/angular2-broccoli-prerender/dist/child_proc.js  --sourceHtml=/Users/benevideschissanga/foo/tmp/app_shell_plugin-input_base_path-PTmdVh4j.tmp/0/index.html --optionsPath=/Users/benevideschissanga/foo/tmp/app_shell_plugin-input_base_path-PTmdVh4j.tmp/0/main-app-shell --outputIndexPath=/Users/benevideschissanga/foo/tmp/app_shell_plugin-output_path-nbl3xxBk.tmp/index.html
DEPRECATION WARNING: `document` is no longer supported and will be removed in next release. Please use `template`
DEPRECATION WARNING: `Bootloader#serializeApplication` arguments has changed.Please use an `AppConfig` interface {providers: Array<any>, directives: Array<any>, template?: string}
EXCEPTION: Failed to load /Users/benevideschissanga/foo/tmp/broccoli_type_script_compiler-cache_path-tQa7ofvE.tmp/src/app/weather/weather.component.html
Failed to load /Users/benevideschissanga/foo/tmp/broccoli_type_script_compiler-cache_path-tQa7ofvE.tmp/src/app/weather/weather.component.html

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

The broccoli plugin was instantiated at:
    at AppShellPlugin.Plugin (/Users/benevideschissanga/foo/node_modules/broccoli-plugin/index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (/Users/benevideschissanga/foo/node_modules/broccoli-caching-writer/index.js:18:10)
    at new AppShellPlugin (/Users/benevideschissanga/foo/node_modules/angular2-broccoli-prerender/dist/prerender.js:15:16)
    at Angular2App._buildTree (/Users/benevideschissanga/foo/node_modules/angular-cli/lib/broccoli/angular2-app.js:154:48)
    at new Angular2App (/Users/benevideschissanga/foo/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/benevideschissanga/foo/angular-cli-build.js:10:12)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/benevideschissanga/foo/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/benevideschissanga/foo/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/benevideschissanga/foo/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/benevideschissanga/foo/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/benevideschissanga/foo/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/benevideschissanga/foo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/benevideschissanga/foo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/benevideschissanga/foo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/benevideschissanga/foo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

^C%                                                                                     ➜  foo git:(master) ✗ ng --version
(node:30702) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.10
node: 6.3.0
os: darwin x64
➜  foo git:(master) ✗
5. Mention any other details that might be useful.
> ---------------------------------------------------------------
Why i can't use templateUrls anymore on mobile app?

**Comment by szechyjs** [comment]
did you ever resolve this?

**Comment by BenevidesLecontes** [comment]
@szechyjs i don't. I Switched to seed and use nativescript because this issue.
