### ISSUE TITLE
"ng new demo" fails to get local issuer certificate for typings

### ISSUE THREAD

**Issue by Jumonji** [angular/angular-cli#1397]
Windows 7 Enterprise SP1

c:\>ng --version
(node:10916) fs: re-evaluating native module sources is not supported.
angular-cli: 1.0.0-beta.10
node: 6.2.0
os: win32 x64

3. Repro steps. 
c:\bit9prog\dev\nodecode>ng new demo
(node:14172) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
installing ng2
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\environment.ts
  create src\app\index.ts
  create src\app\shared\index.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\system-config.ts
  create src\tsconfig.json
  create src\typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config\environment.dev.ts
  create config\environment.js
  create config\environment.prod.ts
  create config\karma-test-shim.js
  create config\karma.conf.js
  create config\protractor.conf.js
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create e2e\typings.d.ts
  create .gitignore
  create package.json
  create public\.npmignore
  create tslint.json
  create typings.json
Successfully initialized git.
\ Installing packages for tooling via npmtypings ERR! message Unable to connect to "https://api.typings.org/entries/dt/selenium-webdriver/ta
gs/2.44.0%2B20160317120654"
typings ERR! caused by unable to get local issuer certificate

typings ERR! cwd c:\bit9prog\dev\nodecode\demo
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\bit9prog\\dev\\nodejs\\node.exe" "c:\\bit9prog\\dev\\nodecode\\demo\\node_modules\\typings\\dist\\bin.js" "install
"
typings ERR! node -v v6.2.0
typings ERR! typings -v 1.3.1
typings ERR! code EUNAVAILABLE

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
demo@0.0.0 postinstall: `typings install`
Exit status 1
Error: demo@0.0.0 postinstall: `typings install`
Exit status 1
    at EventEmitter.<anonymous> (C:\bit9prog\dev\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\utils\lifecycle.js:242:16
)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (C:\bit9prog\dev\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\utils\spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
4. The log given by the failure. Normally this include a stack trace and some
   more information.
 N/A

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
 
I tried installing typings manually, no help.

**Comment by Jumonji** [comment]
new version of typings, 1.3.2, fixes this issue.
