### ISSUE TITLE
Cannot find module @angular-devkit/core - clean build

### ISSUE THREAD

**Issue by jhdev8** [angular/angular-cli#13991]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.2.4

### Description

 After upgrading to @angular/cli@7.3.6, I am unable to create a new project using `ng new my-app`.  The error message is "

Error: Cannot find module '@angular-devkit/core'"

## 🔬 Minimal Reproduction

<pre><code>
$ ng new my-app
</code></pre>

## 🔥 Exception or Error
<pre><code>

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/x/.npm-global/lib/node_modules/@angular/cli/lib/init.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

</code></pre>

## 🌍 Your Environment
ng version outputs the same exception above.  angular/cli is 7.3.6
<pre><code>

</code></pre>

**Anything else relevant?**

Ubuntu 16.04.6 LTS

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
