### ISSUE TITLE
Error: ENOENT: no such file or directory error when deleting files with `ng build --watch`

### ISSUE THREAD

**Issue by arobinson** [angular/angular-cli#14060]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Just adopting Angular CLI, so this is not known

### Description
We are using Angular CLI in a bit of a non-standard way. We have a core product but have "extensions" to our software packaged separately. I'm using the lazy module (via `loadChildren`) support to be able to do subsequent builds. So our workflow is currently to start the `ng build` in watch mode with a custom configuration, and then add or remove modules to a lazy route file. The idea is that we may have thousands of extensions that are loaded dynamically by the client, so we only build them on demand. This is hard with webpack.

The problem I am experiencing is that after deleting these modules, webpack is still looking for them. 

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

1. Create an Angular application with one lazy route module with no routes (see below)
2. Start `ng build --watch` 
3. Add in a new module file into the source directory (say module A)
4. Reference the module from the lazy route module using `loadChildren`
5. Wait for the build to pick up the changes
6. Delete the module and remove it from the lazy route module
7. Add a different new module file and add it to the lazy route module (say module B)

During the compilation of the new module, the error above occurs. At this point, it is trying to still build module A even though it was removed from the file system.

Note that I'm using watch mode as building with AOT is too slow starting each time (~1 minute on a single build vs. ~15 seconds with an incremental watch build, which will not meet our KPIs). 

## 🔥 Exception or Error
<pre><code>

Error: ENOENT: no such file or directory, open '/Users/andrew/development/work/client/nw-client/src/pathtomyapp.module.ngfactory.js'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Storage.provideSync (/Users/andrew/development/work/client/nw-client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (/Users/andrew/development/work/client/nw-client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/andrew/development/work/client/nw-client/node_modules/@ngtools/webpack/src/webpack-input-host.js:35:51)
    at Observable._trySubscribe (/Users/andrew/development/work/client/nw-client/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/andrew/development/work/client/nw-client/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/Users/andrew/development/work/client/nw-client/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.read (/Users/andrew/development/work/client/nw-client/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (/Users/andrew/development/work/client/nw-client/node_modules/@ngtools/webpack/src/compiler_host.js:125:44)
    at VirtualFileSystemDecorator.readFile (/Users/andrew/development/work/client/nw-client/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:39:54)
    at processResource (/Users/andrew/development/work/client/nw-client/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/Users/andrew/development/work/client/nw-client/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at iteratePitchingLoaders (/Users/andrew/development/work/client/nw-client/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/andrew/development/work/client/nw-client/node_modules/loader-runner/lib/LoaderRunner.js:176:18
    at loadLoader (/Users/andrew/development/work/client/nw-client/node_modules/loader-runner/lib/loadLoader.js:47:3)

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.4
Node: 10.14.1
OS: darwin x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.4
@angular-devkit/build-angular     0.13.4
@angular-devkit/build-optimizer   0.13.4
@angular-devkit/build-webpack     0.13.4
@angular-devkit/core              7.3.4
@angular-devkit/schematics        7.3.4
@angular/cli                      7.3.4
@ngtools/webpack                  7.3.4
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by arobinson** [comment]
Example lazy-route module that I modify for every extension I want to build:
```import { NgModule } from '@angular/core';
import { SharedModule } from '../../shared/shared.module';

import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

export const genAppRoutes: Routes = [
  // Begin gen-apps
  {
    path: 'genapp_NWTControlsAdvListNWTControls1554228639535Module',
    loadChildren: '../../../genapp/toolsdev/+_base/base/+nwtcontrolsadvlistnwtcontrols1554228639535/nwtcontrolsadvlistnwtcontrols1554228639535.module#NWTControlsAdvListNWTControls1554228639535Module'
  },
  // End gen-apps
];

export const genAppRouting: ModuleWithProviders = RouterModule.forChild(genAppRoutes);

@NgModule({
  imports: [SharedModule, genAppRouting],
  declarations: [],
  exports: [],
  providers: []
})
export class GenAppsLazyModule {}
```

**Comment by arobinson** [comment]
A sample application to reproduce the problem has been uploaded to github:
https://github.com/arobinson/AngularCLIBug14060

Follow the steps in the README to reproduce the issue

**Comment by filipesilva** [comment]
This might have to do with how we add the lazy module dependencies to webpack: https://github.com/angular/angular-cli/blob/3d25d4cb1bce1ede2f2208dbb309a57e58a51d56/packages/ngtools/webpack/src/angular_compiler_plugin.ts#L714-L767

It's probably added but never removed as a dependency.

In Angular 8 we started favoring dynamic imports over the string syntax. You can read more about it in [here](https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27), in the `Route Configurations use Dynamic Imports` section.

Can you have a try with those and see if it addresses your use case? Dynamic imports are understood directly by webpack so I think that could help.

**Comment by dgp1130** [comment]
Recommendation here is to use dynamic imports instead of a string.

Closing due to lack of activity, please re-open if this is still an ongoing issue.
