### ISSUE TITLE
ng build -prod and ng test --build false fails

### ISSUE THREAD

**Issue by francisoud** [angular/angular-cli#1410]
I run a CI tool with the following command to build the final product:
ng build -prod
ng test --build false --watch false

build: false => because I want the optimized version to be deployed
watch: false because of issue #977 

Logs:
```
21 07 2016 10:57:45.266:WARN [web-server]: 404: /base/dist/vendor/@angular/core/testing.js
21 07 2016 10:57:45.267:WARN [web-server]: 404: /base/dist/vendor/@angular/platform-browser-dynamic/testing.js
Missing error handler on `socket`.
```

`karma-test-shim.js` lines 40 & 41 contains:
    System.import('@angular/core/testing'),
    System.import('@angular/platform-browser-dynamic/testing')

But @angular is packaged in main.js with ng build -prod 

### Steps to reproduce

```
ng new myapp
myapp> npm install
myapp> ng build -prod
myapp> ng test --build false --watch false
```

```
Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

21 07 2016 10:57:44.106:WARN [watcher]: Pattern "C:/tmp/myapp/dist/vendor/systemjs/dist/system-polyfills.js" does not match any file.
21 07 2016 10:57:44.108:WARN [watcher]: Pattern "C:/tmp/myapp/dist/vendor/zone.js/dist/async-test.js" does not match any file.
21 07 2016 10:57:44.110:WARN [watcher]: Pattern "C:/tmp/myapp/dist/vendor/zone.js/dist/fake-async-test.js" does not match any file.
21 07 2016 10:57:44.148:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
21 07 2016 10:57:44.160:INFO [launcher]: Starting browser Chrome
21 07 2016 10:57:45.128:INFO [Chrome 51.0.2704 (Windows 7 0.0.0)]: Connected on socket /#RXhnR8uuqkB_LPgFAAAA with id 34798801
21 07 2016 10:57:45.266:WARN [web-server]: 404: /base/dist/vendor/@angular/core/testing.js
21 07 2016 10:57:45.267:WARN [web-server]: 404: /base/dist/vendor/@angular/platform-browser-dynamic/testing.js
Missing error handler on `socket`.
TypeError: (msg || "").replace is not a function
    at C:\tmp\myapp\node_modules\karma\lib\reporter.js:45:23
    at onBrowserError (C:\tmp\myapp\node_modules\karma\lib\reporters\base.js:58:60)
    at .<anonymous> (C:\tmp\myapp\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at onKarmaError (C:\tmp\myapp\node_modules\karma\lib\browser.js:95:13)
    at Socket.<anonymous> (C:\tmp\myapp\node_modules\karma\lib\events.js:13:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Socket.onevent (C:\tmp\myapp\node_modules\karma\node_modules\socket.io\lib\socket.js:335:8)
    at Socket.onpacket (C:\tmp\myapp\node_modules\karma\node_modules\socket.io\lib\socket.js:295:12)
    at Client.ondecoded (C:\tmp\myapp\node_modules\karma\node_modules\socket.io\lib\client.js:193:14)
    at Decoder.Emitter.emit (C:\tmp\myapp\node_modules\karma\node_modules\socket.io\node_modules\socket.io-parser\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (C:\tmp\myapp\node_modules\karma\node_modules\socket.io\node_modules\socket.io-parser\index.js:247:12)
    at Client.ondata (C:\tmp\myapp\node_modules\karma\node_modules\socket.io\lib\client.js:175:18)
    at emitOne (events.js:96:13)
21 07 2016 10:57:47.276:WARN [Chrome 51.0.2704 (Windows 7 0.0.0)]: Disconnected (1 times)
```

```
C:\tmp\myapp>tree dist
C:\TMP\MYAPP\DIST
├───app
└───vendor
    ├───es6-shim
    ├───reflect-metadata
    │   ├───test
    │   │   └───reflect
    │   └───typings
    ├───systemjs
    │   └───dist
    └───zone.js
        └───dist
```

### Version
```
>ng --version
angular-cli: 1.0.0-beta.8
node: 6.2.1
os: win32 x64
```

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.

**Comment by rukeshj** [comment]
Hi @filipesilva , I still face the same issue . My Karma window opens but I don't get the desired outcome. 
Please find my output . Some help is really appreciated.

`11 10 2016 17:09:28.897:INFO [karma]: Karma v1.3.0 server started at http://loca
lhost:9876/
11 10 2016 17:09:28.913:INFO [launcher]: Launching browser Chrome with unlimited
 concurrency
11 10 2016 17:09:28.959:INFO [launcher]: Starting browser Chrome
11 10 2016 17:09:35.287:INFO [Chrome 53.0.2785 (Windows 7 0.0.0)]: Connected on
socket /#8Q7ubFoB7Cb-ZE9fAAAA with id 48827969
11 10 2016 17:09:35.949:WARN [web-server]: 404: /base/node_modules/@angular/core
/testing.js
11 10 2016 17:09:35.958:WARN [web-server]: 404: /base/node_modules/@angular/plat
form-browser-dynamic/testing.js
Chrome 53.0.2785 (Windows 7 0.0.0) ERROR
  {
    "originalErr": {}
  }

Chrome 53.0.2785 (Windows 7 0.0.0) ERROR
  {
    "originalErr": {}
  }`

**Comment by filipesilva** [comment]
@rukeshj please open a new issue with a detailed description of the problem you face.
