### ISSUE TITLE
Service dependency injection fails on ng serve

### ISSUE THREAD

**Issue by vorugantia** [angular/angular-cli#1411]
OS:     Windows 10

Versions:

angular-cli: 1.0.0-beta.10
node: 6.3.0
os: win32 x64
<br>

I'm using a dependency injection in Angular 2 to inject a service to a component. Here's the code:

`./app/source-display/source-display.component.ts`:

    import { Component, OnInit } from '@angular/core';
    import { CatalogService } from '../catalog.service';
    
    
    @Component({
      moduleId: module.id,
      selector: 'app-source-display',
      providers: [CatalogService],
      templateUrl: 'source-display.component.html',
      styleUrls: ['source-display.component.css']
    })
    export class SourceDisplayComponent implements OnInit {
      active_source_id: number;
      sources: any;
    
      constructor(catalogService: CatalogService) {
          this.active_source_id = 1;
          this.sources = catalogService.getCatalog();
      }
    
      ngOnInit() {
        //   active_source_id = 0;
      }
      
    }

<br>
`./app/catalog.service.ts`:

    import { Injectable } from '@angular/core';
    
    @Injectable()
    export class CatalogService {
    
      constructor() {}
    
      getCatalog() {
          return {
              0: {name: 'Source 0'},
              1: {name: 'Source 1'},
          }
      }
    
    }

<br>
I'm also putting my `CatalogService` in the boostrap function in my main.ts file.

Here is the error message I get from running `ng serve` (and also clearing /tmp/):

    The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
    Error: Typescript found the following errors:
      C:/Users/arjun_000/github/slippy-astro-images/ng2-catdisplay/tmp/broccoli_type_script_compiler-input_base_path-soAy8zVZ.tmp/0/src/app/source-display/source-display.component.spec.ts (10, 21): Supplied parameters do not match any signature of call target.
      C:/Users/arjun_000/github/slippy-astro-images/ng2-catdisplay/tmp/broccoli_type_script_compiler-input_base_path-soAy8zVZ.tmp/0/src/app/source-display/source-display.component.ts (18, 12): Property '_catalogService' does not exist on type 'SourceDisplayComponent'.
        at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
        at BroccoliTypeScriptCompiler.build (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
        at C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
        at lib$rsvp$$internal$$tryCatch (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
        at lib$rsvp$$internal$$invokeCallback (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
        at lib$rsvp$$internal$$publish (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
        at lib$rsvp$asap$$flush (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)
    
    The broccoli plugin was instantiated at:
        at BroccoliTypeScriptCompiler.Plugin (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
        at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
        at BroccoliTypeScriptCompiler (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
        at Angular2App._getTsTree (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
        at Angular2App._buildTree (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
        at new Angular2App (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
        at module.exports (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\angular-cli-build.js:10:10)
        at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
        at Class.module.exports.Task.extend.init (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
        at new Class (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
        at Class.module.exports.Task.extend.run (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
        at C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
        at lib$rsvp$$internal$$tryCatch (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
        at lib$rsvp$$internal$$invokeCallback (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
        at lib$rsvp$$internal$$publish (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
        at lib$rsvp$asap$$flush (C:\Users\arjun_000\github\slippy-astro-images\ng2-catdisplay\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
<br>
I've noticed something strange: The code doesn't work as is, but if I comment out this section from the component --

      constructor(catalogService: CatalogService) {
          this.active_source_id = 1;
          this.sources = catalogService.getCatalog();
      }

-- and then run `ng serve` (which builds the app successfully), and then un-comment out the section, the app now refreshes works the way I want it to. 

I'm not sure what I have to do to solve this. Any ideas?

**Comment by vorugantia** [comment]
I asked this on stackoverflow and got an answer there:

http://stackoverflow.com/questions/38512861/angular-2-service-dependency-injection-fails-using-angular-cli-and-ng-serve

I just commented out the .spec.ts for now.
