### ISSUE TITLE
Setting delcaration to true in tsconfig causes build to fail

### ISSUE THREAD

**Issue by Sedwardsacc** [angular/angular-cli#1414]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 8

> ---------------------------------------------------------------
2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

Node v6.1.0

> ---------------------------------------------------------------
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

I have an app which when built with declaration set to false, builds just fine. Once I set it to true, the build fails. I need the declaration files as this project is actually consumed from a parent application. The app was created using a recent version of the CLI (I did this yesterday, tried setting the value to true today)

4. The log given by the failure. Normally this include a stack trace and some
   more information.

> Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, scandir 'C:\AiDev\AiWeb\ng2-modules\Al
locator\tmp\funnel-input_base_path-vxhqtreq.tmp\0\src'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at _walkSync (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\angular-cli\
node_modules\walk-sync\index.js:59:18)
    at Function.entries (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\angul
ar-cli\node_modules\walk-sync\index.js:40:10)
    at Funnel.processFilters (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\
angular-cli\node_modules\broccoli-funnel\index.js:233:26)
    at Funnel.build (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\angular-c
li\node_modules\broccoli-funnel\index.js:172:10)
    at C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\angular-cli\node_module
s\broccoli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (C:\AiDev\AiWeb\ng2-modules\Allocator\node_m
odules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\AiDev\AiWeb\ng2-modules\Allocator\
node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\AiDev\AiWeb\ng2-modules\Allocator\node_mo
dules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\a
ngular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\angular-
cli\node_modules\broccoli-plugin\index.js:10:31)
    at new Funnel (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\angular-cli
\node_modules\broccoli-funnel\index.js:44:10)
    at Angular2App._getTsTree (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules
\angular-cli\lib\broccoli\angular2-app.js:340:14)
    at Angular2App._buildTree (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules
\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\angula
r-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\AiDev\AiWeb\ng2-modules\Allocator\angular-cli-build.js
:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\AiDev\AiWeb\ng2
-modules\Allocator\node_modules\angular-cli\node_modules\angular-cli\lib\models\
builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\AiDev\AiWeb\ng2-modules\Allocat
or\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10
)
    at new Class (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\angular-cli\
node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\AiDev\AiWeb\ng2-modules\Allocato
r\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\angular-cli\node_module
s\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (C:\AiDev\AiWeb\ng2-modules\Allocator\node_m
odules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\AiDev\AiWeb\ng2-modules\Allocator\
node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\AiDev\AiWeb\ng2-modules\Allocator\node_mo
dules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\AiDev\AiWeb\ng2-modules\Allocator\node_modules\a
ngular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------

I have a similar project that was created with an older version of the CLI, that one builds just fine with declaration set to true.

> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.
