### ISSUE TITLE
"@angular/core/testing" has no exported mng 'addProviders' in generated service test

### ISSUE THREAD

**Issue by jonniedarko** [angular/angular-cli#1422]
1. OS : `OS X El Capitan`
2. Versions:
```
angular-cli: 1.0.0-beta.10
node: 6.3.0
os: darwin x64
```
3. Repro steps: 
  App created with ng-cli, Generated new Service using the command ` ng g service services/auth`
 This generated the spec file `auth.service.spec.ts`
```js
/* tslint:disable:no-unused-variable */
import { addProviders, async, inject } from '@angular/core/testing';
import { AuthService } from './auth.service';

describe('Service: Auth', () => {
  beforeEach(() => {
    addProviders([AuthService]);
  });

  it('should ...',
    inject([AuthService],
      (service: AuthService) => {
        expect(service).toBeTruthy();
      }));
});
```
 
4. The log given by the failure. 

```
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/john/WebstormProjects/ngConsole/tmp/broccoli_type_script_compiler-input_base_path-6noeTh3K.tmp/0/src/app/services/auth.service.spec.ts (3, 10): Module '"/Users/john/WebstormProjects/ngConsole/node_modules/@angular/core/testing"' has no exported mng 'addProviders'.
  /Users/john/WebstormProjects/ngConsole/tmp/broccoli_type_script_compiler-input_base_path-6noeTh3K.tmp/0/src/app/services/auth.service.spec.ts (12, 5): Argument of type 'Function' is not assignable to parameter of type '(done: DoneFn) => void'.
  Type 'Function' provides no match for the signature '(done: DoneFn): void'
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/lib/broccoli/angular2-app.js:331:18)
    at Angular2App._buildTree (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/lib/broccoli/angular2-app.js:124:23)
    at new Angular2App (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/john/WebstormProjects/ngConsole/angular-cli-build.js:54:12)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/john/WebstormProjects/ngConsole/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

```

**Comment by jonniedarko** [comment]
I just realised I needed to update to rc.4 - no longer an issue
