### ISSUE TITLE
Option validation not showing errors

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#14269]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.x

### Description

 
When using unknown options in `angular.json`, errors are not shown correctly.

## 🔬 Minimal Reproduction
```
npm install -g @angular/cli@8.0.0-beta.18
ng new validation-proj
cd validation-proj
# edit `angular.json` and change `outputPath` to `notOutputPath`
ng build
```

## 🔥 Exception or Error
```
D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\util\hostReportError.js:4
    setTimeout(function () { throw err; });
                             ^

Error: Options did not validate.[object Object]
    at MapSubscriber.registry.compile.pipe.operators_1.map.result [as project] (D:\sandbox\es2015-forwardref\node_modules\@angular-devkit\architect\src\architect.js:39:31)
    at MapSubscriber._next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\operators\map.js:49:35)
    at MapSubscriber.Subscriber.next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MapSubscriber._next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\operators\map.js:55:26)
    at MapSubscriber.Subscriber.next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\operators\switchMap.js:86:26)
    at InnerSubscriber._next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\Subscriber.js:66:18)
    at D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\operators\switchMap.js:65:54)
    at SwitchMapSubscriber._next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\operators\switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (D:\sandbox\es2015-forwardref\node_modules\rxjs\internal\Subscriber.js:66:18)
```

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**
This error reporting seems to come from https://github.com/angular/angular-cli/blob/0f9de92dcb8833cfdf6bfad832a9cf281ac27d3d/packages/angular_devkit/architect/src/architect.ts#L286
cc @istiti

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/14274 fixed the error message. It still shows a stack trace though, and shouldn't.
