### ISSUE TITLE
Broccoli Less Plugin

### ISSUE THREAD

**Issue by cdurieux** [angular/angular-cli#1427]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Linux & Mac OSX (Sierra)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.10
node: 6.3.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Updated to angular-cli beta10. Ran ng init.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49154
Serving on http://localhost:4200/
File: input (136)
The Broccoli Plugin: [LESSPlugin] failed with:
undefined

The broccoli plugin was instantiated at:
    at LESSPlugin.Plugin (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at LESSPlugin.CachingWriter [as constructor] (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at new LESSPlugin (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/lib/broccoli/angular-broccoli-less.js:21:12)
    at Object.exports.makeBroccoliTree (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/lib/broccoli/angular-broccoli-less.js:52:12)
    at Angular2App._buildTree (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/lib/broccoli/angular2-app.js:134:27)
    at new Angular2App (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/cdurieux/Node/Fn-Portal2/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/cdurieux/Node/Fn-Portal2/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

Workaround : Replaced line :     
for (const suffix of ['sass', 'less', 'stylus', 'compass']) {
by
for (const suffix of ['sass', 'stylus', 'compass']) {
and generating my css with less manually.

Bug appear since i upgraded to beta10.

**Comment by cdurieux** [comment]
Could be probably merged with #873

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.
