### ISSUE TITLE
`ng update --next` issues for @angular-devkit/build-angular with `0.800.0-rc.2`

### ISSUE THREAD

**Issue by damienwebdev** [angular/angular-cli#14338]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes.

### Description
I was attempting to update https://github.com/damienwebdev/angular-fontawesome to support Angular 8.0.0-rc.2. I was successfully able to update via `ng update --next` but got an error about the `app-shell` builder (which I'm not even using) when attempting to run my tests.

## 🔬 Minimal Reproduction
1. Clone (this repo)[https://github.com/damienwebdev/angular-fontawesome]
2. `yarn install`
3. `yarn test`

## 🔥 Exception or Error
```bash
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/damien/code/angular-fontawesome/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
```

## 🌍 Your Environment
```bash
@angular-devkit/architect         0.800.0-rc.2
@angular-devkit/build-angular     0.800.0-rc.2
@angular-devkit/build-optimizer   0.800.0-rc.2
@angular-devkit/build-webpack     0.800.0-rc.2
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/json-schema              1.1.0
@ngtools/webpack                  8.0.0-rc.2
@schematics/angular               7.3.8
@schematics/update                0.13.8
ng-packagr                        5.1.0
rxjs                              6.5.1
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by damienwebdev** [comment]
I missed updating @angular/cli.

**Comment by PrathyushaRecherla** [comment]
Hi.. I am using Angular CLI 7.3.8 version. I got this error. Schema validation failed with the following errors: Data path ".builders['app-shell'] should have required property 'class'.


Angular CLI: 7.3.8
Node: 8.12.0
OS: win32 x64
Angular: 7.2.13
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/compiler-cli             7.2.12
@ngtools/webpack                  8.0.0
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.30.0

**Comment by ekhoroshun** [comment]
Same issue here. Updating from Angular 6 - Angular 7
"dependencies": {
 "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.15",
    "@angular/compiler": "^7.2.15",
    "@angular/core": "^7.2.15",
    "@angular/forms": "^7.2.15",
    "@angular/http": "^7.2.15",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "^7.2.15",
    "@angular/platform-browser-dynamic": "^7.2.15",
    "@angular/platform-server": "^7.2.15",
    "@angular/router": "^7.2.15",
    "bootstrap-sass": "3.4.1",
    "core-js": "^3.1.3",
    "hammerjs": "2.0.8",
    "http-proxy-agent": "^2.1.0",
    "https-proxy-agent": "^2.2.1",
    "intl": "1.2.5",
    "moment": "^2.24.0",
    "ng2-translate": "~5.0.0",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",
    "tslib": "^1.9.3",
    "typings": "^2.1.1",
    "web-animations-js": "github:angular/web-animations-js#release_pr208",
    "zone.js": "^0.9.1"
}
 "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.0",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/language-service": "^7.2.15",
    "@types/google.analytics": "0.0.39",
    "@types/jasmine": "^3.3.13",
    "@types/node": "^12.0.3",
    "codelyzer": "^5.0.1",
    "enhanced-resolve": "4.1.0",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "2.0.5",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "^5.4.2",
    "replace-in-file": "4.1.0",
    "ts-node": "^7.0.1",
    "tslint": "^5.16.0",
    "typescript": "3.4.5"
}

**Comment by danielkolesnik** [comment]
**Same issue using** `angular/cli: ~6.2.1`
When I'm trying to deploy the updated project into the server there is a subtask `npm audit fix` and as the result `@angular-devkit/build-angular` switch it's version from `~0.7.0` to `^0.800.1` and after that, I've got 
`Errors: Data path “.builders['app-shell']” should have required property 'class'`

**Comment by IRCraziestTaxi** [comment]
Anybody going to chime in on what causes this and how to fix it? Kinda holding me up.

**Comment by ToxicToast** [comment]
Is there a fix yet?

**Comment by poojajadhav122** [comment]
- 

1. 

- [ ] @
Duplicate of #

**Comment by CJ42** [comment]
Change the version of your @angular-devkit/build-angular": from "^0.800.1" to "^0.12.4".

Normally, this will fix the issue. See this answer on StackOverflow 
: https://stackoverflow.com/a/56624167/8245387

**Comment by BruneXX** [comment]
Hello there! is there a fix for that? I'm experiencing the same issue here..

**Comment by BruneXX** [comment]
Solution of @CJ42 worked for me :)
