### ISSUE TITLE
Jasmine Typings Error

### ISSUE THREAD

**Issue by saurabhvyas** [angular/angular-cli#1438]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Win 10 64 bit

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

Cool. I am pasting below
angular-cli: 1.0.0-beta.10
node: 5.12.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
e:\ionic2\learning\LMS>ng new orangeclassroom
installing ng2
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\environment.ts
  create src\app\index.ts
  create src\app\shared\index.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\system-config.ts
  create src\tsconfig.json
  create src\typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config\environment.dev.ts
  create config\environment.js
  create config\environment.prod.ts
  create config\karma-test-shim.js
  create config\karma.conf.js
  create config\protractor.conf.js
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create e2e\typings.d.ts
  create .gitignore
  create package.json
  create public\.npmignore
  create tslint.json
  create typings.json
Successfully initialized git.
/ Installing packages for tooling via npmtypings ERR! message Unable to read typings for "jasmine". You should check the entry paths in "jasmine.d.ts" are up to date
typings ERR! caused by unexpected end of file

typings ERR! cwd e:\ionic2\learning\LMS\orangeclassroom
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "e:\\ionic2\\learning\\LMS\\orangeclassroom\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v5.12.0
typings ERR! typings -v 1.3.1

-  ERR!Installing packages for tooling via npm If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
orangeclassroom@0.0.0 postinstall: `typings install`
Exit status 1
Error: orangeclassroom@0.0.0 postinstall: `typings install`
Exit status 1
    at EventEmitter.<anonymous> (C:\Users\saurabhorange\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\utils\lifecycle.js:242:16)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at ChildProcess.<anonymous> (C:\Users\saurabhorange\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\utils\spawn.js:40:14)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

e:\ionic2\learning\LMS>
```

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

Sure :)

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.

**Comment by AhmedMZawi** [comment]
try --- npm install typings
