### ISSUE TITLE
Build error with Broccoli Plugin using a Docker Container

### ISSUE THREAD

**Issue by adam2k** [angular/angular-cli#1445]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX 10.11.5 El Capitan 15 inch mid 2015 (running a docker container using Linux 4.4.15-moby)

2. Node Version

v6.3.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

I forked this project from the angular 2 material repo that uses the Angular CLI repo.  I made changes to my dev files, but I did not make any changes to the Angular CLI code.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

I can build and run the project using the command: 
The package builds running
    
    npm install
    ng serve

When I build in a docker container using the same commands everything looks to run smoothly and the container builds, but when I run the app and check on my localhost I run into this error:

    Error: EACCES: permission denied, mkdir '/app/tmp/broccoli_merge_trees-output_path-qSkgskNy.tmp'
      at Error (native)
      at Object.fs.mkdirSync (fs.js:922:18)
      at Object.createDirSync (/app/node_modules/mktemp/lib/mktemp.js:114:10)
      at makeTmpDir (/app/node_modules/quick-temp/index.js:45:17)
      at Object.makeOrReuse (/app/node_modules/quick-temp/index.js:21:22)
      at new ReadCompat (/app/node_modules/broccoli-plugin/read_compat.js:17:13)
      at BroccoliMergeTrees.Plugin._initializeReadCompat (/app/node_modules/broccoli-plugin/index.js:130:22)
      at BroccoliMergeTrees.Plugin.read (/app/node_modules/broccoli-plugin/index.js:110:12)
      at /app/node_modules/angular-cli/node_modules/ember-cli-broccoli/lib/builder.js:107:23
      at lib$rsvp$$internal$$tryCatch (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
      at lib$rsvp$$internal$$invokeCallback (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
      at /app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
      at lib$rsvp$asap$$flush (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

    The broccoli plugin was instantiated at: 
      at BroccoliMergeTrees.Plugin (/app/node_modules/broccoli-plugin/index.js:7:31)
      at new BroccoliMergeTrees (/app/node_modules/broccoli-merge-trees/index.js:30:10)
      at module.exports (/app/angular-cli-build.js:26:10)
      at Class.module.exports.Task.extend.setupBroccoliBuilder (/app/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
      at Class.module.exports.Task.extend.init (/app/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
      at new Class (/app/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
      at Class.module.exports.Task.extend.run (/app/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
      at /app/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
      at lib$rsvp$$internal$$tryCatch (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
      at lib$rsvp$$internal$$invokeCallback (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
      at /app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
      at lib$rsvp$asap$$flush (/app/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

5. Mention any other details that might be useful.

I originally posted about this issue in the Angular2-material repo, but they closed the issue and redirected me here.  [https://github.com/angular/material2/issues/900](https://github.com/angular/material2/issues/900)

I've even tried running

    chmod 777 -R /app/tmp/

to see if that would remove the permission errors, but it did not.

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.
