### ISSUE TITLE
"Expression form not supported" when using static "this" with ternary operator

### ISSUE THREAD

**Issue by cfinlinson** [angular/angular-cli#14511]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 
Not that I'm aware of.

### Description

Compilation fails when using `this` with the ternary operator in a static method.

## 🔬 Minimal Reproduction
1. ng new cli-test
2. cd cli-test
3. ng g library test-lib
4. Change test-lib.service.ts to this:
```
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TestLibService {
  public static add ( a: number, b: number ): number {
      return a + b;
  }

  public static addAll ( values: number[] ): number {
    return values.length ? values.slice ( 1 ).reduce ( this.add, values[ 0 ] ) : 0;
  }
}
```
5. ng run test-lib:build

The error can be resolved by replacing `this` with `TestLibService` or by using an if block instead of the ternary operator.
## 🔥 Exception or Error
<pre><code>
BUILD ERROR
C:/workspace/projects/cli-test/projects/test-lib/src/lib/test-lib.service.ts:3:1: Error encountered in metadata generated for exported symbol 'TestLibService':
 C:/workspace/projects/cli-test/projects/test-lib/src/lib/test-lib.service.ts:18:56: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":17,"character":55}
Error: C:/workspace/projects/cli-test/projects/test-lib/src/lib/test-lib.service.ts:3:1: Error encountered in metadata generated for exported symbol 'TestLibService':
 C:/workspace/projects/cli-test/projects/test-lib/src/lib/test-lib.service.ts:18:56: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":17,"character":55}
    at Object.getOwnPropertyNames.forEach.name (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\metadata\collector.js:648:31)
    at Array.forEach (<anonymous>)
    at validateMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\metadata\collector.js:636:46)
    at MetadataCollector.getMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\metadata\collector.js:492:21)
    at MetadataCache.getMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\transformers\metadata_cache.js:59:43)
    at Object.getSourceFileMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:110:55)
    at Object.readMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\transformers\metadata_reader.js:45:39)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:466:38)
    at StaticSymbolResolver.getModuleMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler\bundles\compiler.umd.js:23164:49)
    at StaticSymbolResolver._createSymbolsOf (C:\workspace\projects\cli-test\node_modules\@angular\compiler\bundles\compiler.umd.js:22955:33)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.2.4
Node: 10.15.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.4
@angular-devkit/build-angular      0.12.4
@angular-devkit/build-ng-packagr   0.12.4
@angular-devkit/build-optimizer    0.12.4
@angular-devkit/build-webpack      0.12.4
@angular-devkit/core               7.2.4
@angular-devkit/schematics         7.2.4
@angular/cli                       7.2.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.4
@schematics/angular                7.2.4
@schematics/update                 0.12.4
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.28.4
</code></pre>

**Comment by alan-agius4** [comment]
Hi, I'm sorry, but this issue is not caused by Angular CLI. Compiler issues should be logged here: https://github.com/angular/angular

Thanks

**Comment by maxbechtold** [comment]
Follow up: https://github.com/angular/angular/issues/30699
