### ISSUE TITLE
ng serve with schema validation error

### ISSUE THREAD

**Issue by Qlenglet** [angular/angular-cli#14564]
Hello everybody,

I am facing an issue with the command ng serve. I have a following error :
 `Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/home/quentin/Téléchargements/quentin/AngularAmplify/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:55:14)`

My angular.json file is like this : 

> {
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 5,
  "newProjectRoot": "projects",
  "projects": {
    "Gene": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets"
            ],
            "styles": [
              "src/assets/scss/style.scss",
              "node_modules/videogular2/fonts/videogular.css",
              "node_modules/angular-instantsearch/bundles/instantsearch.min.css",
              "node_modules/angular-instantsearch/bundles/instantsearch-theme-algolia.min.css",
              "node_modules/ngx-toastr/toastr.css",
              "node_modules/quill/dist/quill.snow.css",
              "node_modules/leaflet/dist/leaflet.css",
              "node_modules/angular-calendar/css/angular-calendar.css",
              "node_modules/@swimlane/ngx-datatable/release/index.css",
              "node_modules/@swimlane/ngx-datatable/release/themes/material.css",
              "node_modules/@swimlane/ngx-datatable/assets/icons.css",
              "node_modules/nvd3/build/nv.d3.css",
              "node_modules/font-awesome/css/font-awesome.css",
              "node_modules/cryptocoins-icons/webfont/cryptocoins.css",
              "src/assets/fonts/data-table/icons.css",
              "node_modules/dragula/dist/dragula.css",
          "node_modules/angular-tree-component/dist/angular-tree-component.css",
              "node_modules/nouislider/distribute/nouislider.min.css",
              "node_modules/slick-carousel/slick/slick.scss",
              "node_modules/slick-carousel/slick/slick-theme.scss",
              "node_modules/ngx-bar-rating/themes/br-default-theme.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/slick-carousel/slick/slick.min.js",
              "node_modules/hammerjs/hammer.js",
              "node_modules/sortablejs/Sortable.js",
              "node_modules/chart.js/dist/Chart.bundle.min.js",
              "node_modules/easy-pie-chart/dist/easypiechart.js"
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": true,
              "buildOptimizer": false,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "Gene:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "Gene:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "Gene:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/slick-carousel/slick/slick.min.js",
              "node_modules/hammerjs/hammer.js",
              "node_modules/sortablejs/Sortable.js",
              "node_modules/chart.js/dist/Chart.bundle.min.js",
              "node_modules/easy-pie-chart/dist/easypiechart.js",
            ],
            "styles": [
              "src/assets/scss/style.scss",
              "node_modules/videogular2/fonts/videogular.css",
              "node_modules/angular-instantsearch/bundles/instantsearch.min.css",
              "node_modules/angular-instantsearch/bundles/instantsearch-theme-algolia.min.css",
              "node_modules/ngx-toastr/toastr.css",
              "node_modules/quill/dist/quill.snow.css",
              "node_modules/leaflet/dist/leaflet.css",
              "node_modules/angular-calendar/css/angular-calendar.css",
              "node_modules/@swimlane/ngx-datatable/release/index.css",
              "node_modules/@swimlane/ngx-datatable/release/themes/material.css",
              "node_modules/@swimlane/ngx-datatable/assets/icons.css",
              "node_modules/nvd3/build/nv.d3.css",
              "node_modules/font-awesome/css/font-awesome.css",
              "node_modules/cryptocoins-icons/webfont/cryptocoins.css",
              "src/assets/fonts/data-table/icons.css",
              "node_modules/dragula/dist/dragula.css",
              "node_modules/angular-tree-component/dist/angular-tree-component.css",
              "node_modules/nouislider/distribute/nouislider.min.css",
              "node_modules/slick-carousel/slick/slick.scss",
              "node_modules/slick-carousel/slick/slick-theme.scss",
              "node_modules/ngx-bar-rating/themes/br-default-theme.css"
            ],
            "assets": [
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": []
          }
        }
      }
    },
    "Gene-e2e": {
      "root": "",
      "sourceRoot": "e2e",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "Gene:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "e2e/tsconfig.e2e.json"
            ],
            "exclude": []
          }
        }
      }
    }
  },
  "defaultProject": "Gene",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "ms",
      "styleext": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "ms"
    }
  }
}

Can you help me ?

Thanks a lot

**Comment by istiti** [comment]
Can you please use template issue to fill bug?
If you have bug/need help you should follow https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#submit-issue  to report it .

**Comment by LWASALAW** [comment]
you only need to upgrade your Angular to the current version 8 using : **ng update @angular/cli @angular/core**
