### ISSUE TITLE
Angular CLI v8 fail run to build, serve and update

### ISSUE THREAD

**Issue by Kynson** [angular/angular-cli#14624]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.1.3

### Description

 
The above 3 commands `ng serve`, `ng update`, `ng build` all failed with the same error `Cannot find module './path'` after update to angular v8.0.0

## 🔥 Exception or Error
`ng update`:
<pre><code>
> ng update
Using package manager: 'npm'
Collecting installed dependencies...
Found 41 dependencies.
Cannot find module './path'
Require stack:
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/virtual-fs/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@schematics/update/update/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/utilities/json-schema.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/command-runner.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
Error: Cannot find module './path'
Require stack:
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/virtual-fs/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@schematics/update/update/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/utilities/json-schema.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/command-runner.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/virtual-fs/index.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
</code></pre>

`ng serve`:
<pre><code>
> ng serve
Cannot find module './path'
Require stack:
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/virtual-fs/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/architect/src/architect.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/architect/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/architect-command.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/commands/build-impl.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/utilities/json-schema.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/command-runner.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
Error: Cannot find module './path'
Require stack:
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/virtual-fs/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/architect/src/architect.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/architect/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/architect-command.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/commands/build-impl.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/utilities/json-schema.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/command-runner.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/virtual-fs/index.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
</code></pre>

`ng build`: 
<pre><code>
> ng build
Cannot find module './path'
Require stack:
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/virtual-fs/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/architect/src/architect.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/architect/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/architect-command.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/commands/build-impl.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/utilities/json-schema.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/command-runner.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
Error: Cannot find module './path'
Require stack:
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/virtual-fs/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/architect/src/architect.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/architect/src/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/architect-command.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/commands/build-impl.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/utilities/json-schema.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/models/command-runner.js
- /Users/ky/Documents/Programme/myproject/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/lib/init.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/virtual-fs/index.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ky/Documents/Programme/myproject/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.0
Node: 12.3.1
OS: darwin x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/.DS_Store                <error>
@angular/fire                     5.2.0
@angular/language-service 2       <error>
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

N/A

**Comment by Kynson** [comment]
Fixed with reinstall the core package
