### ISSUE TITLE
Sass can't import regular .css files

### ISSUE THREAD

**Issue by andyford** [angular/angular-cli#1462]
1) OS:  Mac OSX 10.11.5 El Capitan

2) Versions:
angular-cli: 1.0.0-beta.9
node: 4.4.7
os: darwin x64

package.json:

```
{
  "name": "my-project",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "postinstall": "typings install",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.4",
    "angular2-in-memory-web-api": "0.0.14",
    "core-js": "^2.4.0",
    "es6-shim": "0.35.1",
    "moment": "^2.14.1",
    "ng2-bootstrap": "^1.0.17",
    "ng2-select": "^1.0.3",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "underscore": "1.8.3",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "angular-cli": "1.0.0-beta.9",
    "codelyzer": "0.0.20",
    "ember-cli-inject-live-reload": "1.4.0",
    "faker": "^3.1.0",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "node-sass": "3.8.0",
    "protractor": "3.3.0",
    "ts-node": "0.5.5",
    "tslint": "3.11.0",
    "typescript": "1.8.10",
    "typings": "0.8.1"
  }
}
```

3) Repro steps.
app was created using the CLI.
I have a style.scss file at the root of the src dir.
style.scss successfully imports other .scss files from src/assets/stylesheets (using no file extension in the import statements) like so:

@import 'assets/stylesheets/vendor/tether/tether';
@import 'assets/stylesheets/functions';
@import 'assets/stylesheets/vars';
@import 'assets/stylesheets/mixins';

all files are .scss files except the 'tether' file is 'tether.css' which throws errors as if the file is not found. If I simply rename the tether.css file to tether.scss, then it works. Note that the importing of .css files (without extension) is a core feature of sass.

4) failure log

```
$ ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: /Users/awf/Documents/projects/my-project/tmp/sassplugin-input_base_path-gvZTPqkY.tmp/0/src/style.scss (12)
The Broccoli Plugin: [SASSPlugin] failed with:
Error: File to import not found or unreadable: assets/stylesheets/vendor/tether/tether
Parent style sheet: /Users/awf/Documents/projects/my-project/tmp/sassplugin-input_base_path-gvZTPqkY.tmp/0/src/style.scss
    at Object.module.exports.renderSync (/Users/awf/Documents/projects/my-project/node_modules/node-sass/lib/index.js:420:22)
    at SASSPlugin.compile (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/lib/broccoli/angular-broccoli-sass.js:52:25)
    at /Users/awf/Documents/projects/my-project/node_modules/angular-cli/lib/broccoli/angular-broccoli-sass.js:32:14
    at Array.forEach (native)
    at SASSPlugin.build (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/lib/broccoli/angular-broccoli-sass.js:28:22)
    at /Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at SASSPlugin.Plugin (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at SASSPlugin.CachingWriter [as constructor] (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at new SASSPlugin (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/lib/broccoli/angular-broccoli-sass.js:20:12)
    at Object.Plugin.build.exports.makeBroccoliTree (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/lib/broccoli/angular-broccoli-sass.js:72:12)
    at Angular2App._buildTree (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/lib/broccoli/angular2-app.js:133:27)
    at new Angular2App (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/awf/Documents/projects/my-project/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/awf/Documents/projects/my-project/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.
