### ISSUE TITLE
emitWarnings coverage threshold breaks architect build

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#14621]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] test
```

### Is this a regression?
Yes

### Description
Adding `emitWarning` to istanbul reporter breaks the build

## 🔬 Minimal Reproduction
ng new my-app (works)
add a threshold to `karma.conf.js: (works)
```
thresholds: {
        statements: 80
      }
```

set `emitWarning` to false

```
thresholds: {
        emitWarning: false,
        statements: 80
      }
```
`ng test --code-coverage` // fails

## 🔥 Exception or Error
<pre><code>
31 05 2019 14:57:30.903:ERROR [karma-server]: TypeError: Cannot read property 'pct' of undefined
    at /usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:10:35
    at Array.forEach (<anonymous>)
    at checkThresholds (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:9:27)
    at createReport (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:157:31)
    at /usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:220:9
    at Array.forEach (<anonymous>)
    at BrowserCollection.forEach (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/karma/lib/browser_collection.js:84:26)
    at CoverageIstanbulReporter.onRunComplete (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/karma-coverage-istanbul-reporter/src/reporter.js:219:16)
    at Server.<anonymous> (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/karma/lib/events.js:40:26)
    at Server.emit (events.js:201:15)
    at Timeout._onTimeout (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/karma/lib/executor.js:53:22)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Cannot read property 'success' of undefined
TypeError: Cannot read property 'success' of undefined
    at TestCommand.runSingleTarget (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/@angular/cli/models/architect-command.js:199:27)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at TestCommand.runArchitectTarget (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/@angular/cli/models/architect-command.js:211:31)
    at TestCommand.validateAndRun (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/@angular/cli/models/command.js:137:28)
    at Object.runCommand (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/@angular/cli/models/command-runner.js:178:24)
    at default_1 (/usr/local/google/home/stephenfluin/workspace/test/coverage/node_modules/@angular/cli/lib/cli/index.js:32:31)

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.1
Node: 12.2.0
OS: linux x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
Trying to test coverage failures failing `ng test`

**Comment by alan-agius4** [comment]
Related also to: https://github.com/angular/angular-cli/issues/14118

**Comment by alan-agius4** [comment]
@StephenFluin, I just took a look at this and the problems seems to be that the below is not a valid configuration. I suggest that you open an issue with karma-coverage-istanbul-reporter that they should handle this more gracefully or by emitting a warning.

```js
thresholds: {
  emitWarning: false,
  statements: 80
}
```

A valid configuration is 
```
thresholds: {
  emitWarning: false,
  global: {
     statements: 80
  }
}
```

More details: https://github.com/mattlewis92/karma-coverage-istanbul-reporter#configuration

**Comment by oppikar** [comment]
@alan-agius4 

We do actually in our project have pretty much the same issue. We also found out, that it correctly builds if we simply delete all "thresholds". But in fact I also am not sure, what the error in our configuration should be. Do you have any idea about this?

`      thresholds: {
        emitWarning: false,
        // thresholds per file
        each: {
          statements: 0, /* covered by lines already */
          lines: 100,
          branches: 100,
          functions: 100,
          overrides: {
            '**/xyz.service.ts': {
              lines: 79,
              branches: 49,
            },
            '**/zyx.service.ts': {
              branches: 74,
              functions: 83,
            }, ...`

There are to follow several other overridden files.
Thanks in advantage!
Cheers, Shawn
