### ISSUE TITLE
Angular-cli 6.1 - AOT - Internal error: The name i is already defined

### ISSUE THREAD

**Issue by fabiohsalmeida** [angular/angular-cli#14663]
# Angular-cli 6.1 - AOT - Internal error: Name i is already defined

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes, the previous version in which this bug was not present was: 5.2.0

### Description
I'm trying to run the ng serve --aot and the following error are running out (stack on the Exception or Error topic): Error: Internal Error: The name i is already defined in scope to be [object Object]

## 🔬 Minimal Reproduction
<code>ng serve --aot</code>

## 🔥 Exception or Error
<pre><code>
ERROR in : Error: Internal Error: The name i is already defined in scope to be [object Object]
    at error (\node_modules\@angular\compiler\bundles\compiler.umd.js:1095:15)
    at BindingScope.set (\node_modules\@angular\compiler\bundles\compiler.umd.js:19612:17)
    at TemplateDefinitionBuilder.buildTemplateFunction (\node_modules\@angular\compiler\bundles\compiler.umd.js:18911:40)
    at TemplateDefinitionBuilder.visitTemplate (\node_modules\@angular\compiler\bundles\compiler.umd.js:19402:56)
    at Template.visit (\node_modules\@angular\compiler\bundles\compiler.umd.js:18364:72)
    at visitAll$1 (\node_modules\@angular\compiler\bundles\compiler.umd.js:18416:40)
    at TemplateDefinitionBuilder.visitElement (\node_modules\@angular\compiler\bundles\compiler.umd.js:19353:17)
    at Element.visit (\node_modules\@angular\compiler\bundles\compiler.umd.js:18350:71)
    at visitAll$1 (\node_modules\@angular\compiler\bundles\compiler.umd.js:18416:40)
    at TemplateDefinitionBuilder.visitElement (\node_modules\@angular\compiler\bundles\compiler.umd.js:19353:17)
    at Element.visit (\node_modules\@angular\compiler\bundles\compiler.umd.js:18350:71)
    at visitAll$1 (\node_modules\@angular\compiler\bundles\compiler.umd.js:18416:40)
    at TemplateDefinitionBuilder.buildTemplateFunction (\node_modules\@angular\compiler\bundles\compiler.umd.js:18934:13)
    at TemplateDefinitionBuilder.visitTemplate (\node_modules\@angular\compiler\bundles\compiler.umd.js:19402:56)
    at Template.visit (\node_modules\@angular\compiler\bundles\compiler.umd.js:18364:72)
    at visitAll$1 (\node_modules\@angular\compiler\bundles\compiler.umd.js:18416:40)
</code></pre>

## 🌍 Your Environment
<pre>     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.1.0
Node: 10.15.0
OS: win32 x64
Angular: 6.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.0
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.0.22
@angular-devkit/schematics        0.0.42
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.0
@schematics/schematics            0.0.11
@schematics/update                0.7.0
rxjs                              6.5.2
typescript                        2.9.2
webpack                           4.31.0<code>
</code></pre>

**Anything else relevant?**
I already tried to update version to last revision (6.1.10) and I also tried to uninstall and install again the angular/cli dependency, both approaches resulted in the same error.

**Comment by alan-agius4** [comment]
Hi, does this happen on Angular CLI version 8?

If the problem persists after upgrading, please open a new issue, provide a **simple repository** reproducing the problem, and describe the difference between the expected and current behavior.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
