### ISSUE TITLE
Error on open mobile app

### ISSUE THREAD

**Issue by rlbarreto** [angular/angular-cli#1469]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux Lubuntu 15.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 6.3.1
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
`ng new NAME --mobile` and then `cd NAME` and `ng serve`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /home/rafael/projetos/fisio-front-mob/tmp/broccoli_type_script_compiler-input_base_path-QUfxRj64.tmp/0/src/typings.d.ts (6, 13): Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'NodeModule', but here has type '{ id: string; }'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/lib/broccoli/angular2-app.js:331:18)
    at Angular2App._buildTree (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/lib/broccoli/angular2-app.js:124:23)
    at new Angular2App (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/home/rafael/projetos/fisio-front-mob/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/rafael/projetos/fisio-front-mob/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.
