### ISSUE TITLE
error on ng new with angular 8.0.2

### ISSUE THREAD

**Issue by salfonseca** [angular/angular-cli#14762]
# 🐞 Bug report

- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I don't think so, version 7.x works fine in my environment, never got this error before.


### Description

after executing the command: ng new projectname got this:

CREATE web/README.md (1020 bytes)
CREATE web/.editorconfig (246 bytes)
CREATE web/.gitignore (629 bytes)
CREATE web/angular.json (3489 bytes)
CREATE web/package.json (1276 bytes)
CREATE web/tsconfig.json (438 bytes)
CREATE web/tslint.json (1985 bytes)
CREATE web/browserslist (429 bytes)
CREATE web/karma.conf.js (1015 bytes)
CREATE web/tsconfig.app.json (210 bytes)
CREATE web/tsconfig.spec.json (270 bytes)
CREATE web/src/favicon.ico (5430 bytes)
CREATE web/src/index.html (290 bytes)
CREATE web/src/main.ts (372 bytes)
CREATE web/src/polyfills.ts (2838 bytes)
CREATE web/src/styles.scss (80 bytes)
CREATE web/src/test.ts (642 bytes)
CREATE web/src/assets/.gitkeep (0 bytes)
CREATE web/src/environments/environment.prod.ts (51 bytes)
CREATE web/src/environments/environment.ts (662 bytes)
CREATE web/src/app/app-routing.module.ts (245 bytes)
CREATE web/src/app/app.module.ts (393 bytes)
CREATE web/src/app/app.component.scss (0 bytes)
CREATE web/src/app/app.component.html (1152 bytes)
CREATE web/src/app/app.component.spec.ts (1086 bytes)
CREATE web/src/app/app.component.ts (208 bytes)
CREATE web/e2e/protractor.conf.js (810 bytes)
CREATE web/e2e/tsconfig.json (214 bytes)
CREATE web/e2e/src/app.e2e-spec.ts (632 bytes)
CREATE web/e2e/src/app.po.ts (251 bytes)
npm ERR! Unexpected end of JSON input while parsing near '...ependencies":{"coffee'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user-folder/.npm/_logs/2019-06-13T15_23_56_038Z-debug.log


## 🔬 Minimal Reproduction
ng new projectname
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS

also tried with default options an got the same error (hitting enter twice)


## 🔥 Exception or Error
in the file /home/user-folder/.npm/_logs/2019-06-13T15_23_56_038Z-debug.log
I can see:
2220 silly saveTree ├── @types/node@8.9.5
2220 silly saveTree ├── codelyzer@5.1.0
2220 silly saveTree ├── jasmine-core@3.4.0
2220 silly saveTree ├── jasmine-spec-reporter@4.2.1
2220 silly saveTree ├── karma-chrome-launcher@2.2.0
2220 silly saveTree ├── karma-coverage-istanbul-reporter@2.0.5
2220 silly saveTree ├── karma-jasmine-html-reporter@1.4.2
2220 silly saveTree ├── karma-jasmine@2.0.1
2220 silly saveTree ├── karma@4.1.0
2220 silly saveTree ├── protractor@5.4.2
2220 silly saveTree ├── rxjs@6.4.0
2220 silly saveTree ├── ts-node@7.0.1
2220 silly saveTree ├── tslib@1.10.0
2220 silly saveTree ├── tslint@5.15.0
2220 silly saveTree ├── typescript@3.4.5
2220 silly saveTree └── zone.js@0.9.1
2221 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ependencies":{"coffee'
2221 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ependencies":{"coffee'
2221 verbose stack     at JSON.parse (<anonymous>)
2221 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
2221 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
2221 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:89:5)
2221 verbose stack From previous event:
2221 verbose stack     at fetchPackument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:52:7)
2221 verbose stack     at packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:20:10)
2221 verbose stack     at getManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:22:10)
2221 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:13:10)
2221 verbose stack     at Object.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/index.js:17:12)
2221 verbose stack     at Object.Fetcher#manifest [as manifest] (/usr/local/lib/node_modules/npm/node_modules/genfun/lib/genfun.js:15:38)
2221 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetch.js:23:18)
2221 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/manifest.js:24:12
2221 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
2221 verbose stack From previous event:
2221 verbose stack     at _inflight (/usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
2221 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
2221 verbose stack     at processImmediate (internal/timers.js:439:21)
2221 verbose stack From previous event:
2221 verbose stack     at inflight (/usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:14:40)
2221 verbose stack     at Object.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/manifest.js:22:10)
2221 verbose stack     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:58:10)
2221 verbose stack     at limited (/usr/local/lib/node_modules/npm/node_modules/call-limit/call-limit.js:29:10)
2221 verbose stack     at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:590:5)
2221 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:516:5
2221 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
2221 verbose stack     at Array.forEach (<anonymous>)
2221 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
2221 verbose stack     at Array.forEach (<anonymous>)
2221 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
2221 verbose stack     at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:514:3)
2221 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
2221 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
2221 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
2221 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:404:5
2221 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
2221 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:459:21
2221 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/and-add-parent-to-errors.js:8:24
2222 verbose cwd /home/user-folder/somepath/projectname/web
2223 verbose Linux 4.19.0-kali5-amd64
2224 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "--quiet"
2225 verbose node v12.4.0
2226 verbose npm  v6.9.0
2227 error Unexpected end of JSON input while parsing near '...ependencies":{"coffee'
2228 verbose exit [ 1, true ]

[2019-06-13T15_23_56_038Z-debug.log](https://github.com/angular/angular-cli/files/3287121/2019-06-13T15_23_56_038Z-debug.log)


## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.2
Node: 12.4.0
OS: linux x64 (is a distribution based on Debian)
npm: 6.9.0

</code></pre>

also got the same error when try to upgrade an existing project from Angular CLI: 7.3.1 to 8.0.2 with: "ng update @angular/cli @angular/core"

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.


That said try using 
```
npm cache clean --force
```
