### ISSUE TITLE
`ng update @angular/material@6` install latest versions

### ISSUE THREAD

**Issue by ahasall** [angular/angular-cli#14781]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 No

### Description

[update.angular.io](https://update.angular.io/#5.2:6.0) recommends not to update across multiple major versions.
But when trying to update from Angular v5 to v6, `ng update @angular/material@6` updates the project to Angular v8.

## 🔬 Minimal Reproduction

I created [Github repo](https://github.com/ahasall/ng-update-v5-v6-repro) reproducing the issue:
```bash
git clone https://github.com/ahasall/ng-update-v5-v6-repro.git
cd ng-update-v5-v6-repro
yarn
ng update @angular/material@6
```
## 🔥 Exception or Error
First the Angular Material is updated from v5 to v5.
Then a TypeScript error that doesn't stop the update process appears:
<pre><code>

TypeError: Cannot read property 'flags' of undefined
    at Object.getBaseTypes (/Users/ahasall/Projects/Experimentation/my-app/node_modules/typescript/lib/typescript.js:31444:38)
    at CheckInheritanceWalker.visitClassDeclaration (/Users/ahasall/Projects/Experimentation/my-app/angular_material_schematics-ExbecO/update/rules/checkInheritanceRule.js:20:49)
    at CheckInheritanceWalker.SyntaxWalker.visitNode (/Users/ahasall/Projects/Experimentation/my-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:314:22)
    at /Users/ahasall/Projects/Experimentation/my-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/Users/ahasall/Projects/Experimentation/my-app/node_modules/typescript/lib/typescript.js:14809:30)
    at Object.forEachChild (/Users/ahasall/Projects/Experimentation/my-app/node_modules/typescript/lib/typescript.js:15035:24)
    at CheckInheritanceWalker.SyntaxWalker.walkChildren (/Users/ahasall/Projects/Experimentation/my-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at CheckInheritanceWalker.SyntaxWalker.visitSourceFile (/Users/ahasall/Projects/Experimentation/my-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:228:14)
    at CheckInheritanceWalker.SyntaxWalker.visitNode (/Users/ahasall/Projects/Experimentation/my-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:482:22)
    at CheckInheritanceWalker.SyntaxWalker.walk (/Users/ahasall/Projects/Experimentation/my-app/node_modules/tslint/lib/language/walker/syntaxWalker.js:24:14)
</code></pre>
Then `@angular/material` and `@angular/cdk` are updated to v8 against the recommendations of update.angular.io/.

## 🌍 Your Environment
<pre><code>

Angular CLI: 6.2.9
Node: 10.15.3
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cdk                      5.2.5
@angular/cli                      6.2.9
@angular/material                 5.2.5
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.5.2
typescript                        2.9.2
webpack                           4.16.4

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
Closing this in favor of #14980.   The underlying cause is the same and there is a larger set of information present there.
