### ISSUE TITLE
Not able to migrate from angular 4.4 to angular 8

### ISSUE THREAD

**Issue by kumaraditya1999** [angular/angular-cli#14965]
I was trying to migrate my project from angular 4.4 to angular 8. I followed the [documentation](https://update.angular.io/#4.4:8.0) but I am facing some issues. 
```
additional asset processing scripts-webpack-plugin✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/home/migration/node_modules/jsondiffpatch/public/build/jsondiffpatch-full.min.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Storage.provideSync (/home/migration/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (/home/migration/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/migration/node_modules/@ngtools/webpack/src/webpack-input-host.js:35:51)
    at Observable._trySubscribe (/home/migration/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/migration/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/home/migration/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.read (/home/migration/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (/home/migration/node_modules/@ngtools/webpack/src/compiler_host.js:129:44)
    at VirtualFileSystemDecorator.readFile (/home/migration/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:42:54)
    at Promise (/home/migration/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:69:49)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (/home/migration/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:68:24)
    at Array.map (<anonymous>)
    at hook (/home/migration/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/scripts-webpack-plugin.js:67:43)
```

I am not sure whether the above error is from webpack or jsondiffpatch or from manual error. I do checked the jsondiffpatch in the node_modules and I was not able to find the above file. Also isn't there an automated script to migrate angular projects, the current method seems to be too much time consuming and manual work.Thanks for your time

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by julianpoemp** [comment]
did you install jsondiffpatch for your app or is it a dependency from webpack? If you import scripts you need to set the scripts in angular.json as follows:
   
    "node_modules/<relative_part>"

there should be no "./" before node_modules.

Another way, less error-prone way could be to create a new angular project and move your old code to it. I did it for one of my past projects because it was easier than migrating after the documentation.

I recommended to update angular/cli as soon as new updated were released. It's easier to do small updates.

**Comment by kumaraditya1999** [comment]
No I installed it manually after it was failing. I am not facing this issue anymore. It sems that migrating directly from 4.4 to 8 was stupid thing and I might have done some mistake in between. Anyways, I did it again and now I am facing some different issue. Thanks for your valuable time :smile:  !!!
