### ISSUE TITLE
Could not find the implementation for builder @angular-devkit/build-angular:browser

### ISSUE THREAD

**Issue by yasiryc** [angular/angular-cli#15063]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.1.7

### Description

After using ng update to update from 6.1.7 to 8.1.0 i am not longer able to build the project. it gives me 
**An unhandled exception occurred: Could not find the implementation for builder @angular-devkit/build-angular:browser**

error. Here is complete error from angular error log

**[error] Error: Could not find the implementation for builder @angular-devkit/build-angular:browser
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (C:\Source\common-angular8-components\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:49:19)
    at BuildCommand.initialize (C:\Source\common-angular8-components\node_modules\@angular\cli\models\architect-command.js:135:55)
    at async BuildCommand.validateAndRun (C:\Source\common-angular8-components\node_modules\@angular\cli\models\command.js:124:9)
    at async Object.runCommand (C:\Source\common-angular8-components\node_modules\@angular\cli\models\command-runner.js:185:24)
    at async default_1 (C:\Source\common-angular8-components\node_modules\@angular\cli\lib\cli\index.js:50:31)**

## 🔬 Minimal Reproduction

ng build

## 🔥 Exception or Error
**[error] Error: Could not find the implementation for builder @angular-devkit/build-angular:browser
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (C:\Source\common-angular8-components\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:49:19)
    at BuildCommand.initialize (C:\Source\common-angular8-components\node_modules\@angular\cli\models\architect-command.js:135:55)
    at async BuildCommand.validateAndRun (C:\Source\common-angular8-components\node_modules\@angular\cli\models\command.js:124:9)
    at async Object.runCommand (C:\Source\common-angular8-components\node_modules\@angular\cli\models\command-runner.js:185:24)
    at async default_1 (C:\Source\common-angular8-components\node_modules\@angular\cli\lib\cli\index.js:50:31)**

## 🌍 Your Environment
<pre><code>

Here is current package.json dependenices.
</code>
  "dependencies": {
    "@angular/animations": "^8.1.0",
    "@angular/common": "^8.1.0",
    "@angular/compiler": "^8.1.0",
    "@angular/core": "^8.1.0",
    "@angular/forms": "^8.1.0",
    "@angular/platform-browser": "^8.1.0",
    "@angular/platform-browser-dynamic": "^8.1.0",
    "@angular/router": "^8.1.0",
    "core-js": "^2.6.9",
    "fullcalendar": "^3.10.0",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "node-sass": "^4.12.0",
    "rxjs": "^6.5.2",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.8.9",
    "@angular-devkit/build-ng-packagr": "^0.8.9",
    "@angular/cli": "^8.1.0",
    "@angular/compiler-cli": "^8.1.0",
    "@angular/language-service": "^8.1.0",
    "@types/jasmine": "^2.8.16",
    "@types/jasminewd2": "^2.0.6",
    "@types/jquery": "^3.3.30",
    "@types/node": "^10.14.12",
    "classlist.js": "^1.1.20150312",
    "codelyzer": "^4.5.0",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^3.1.4",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "ng-packagr": "^4.7.1",
    "protractor": "^5.4.2",
    "rimraf": "^2.6.3",
    "ts-node": "^7.0.1",
    "tsickle": "^0.32.1",
    "tslib": "^1.10.0",
    "tslint": "^5.18.0",
    "typescript": "~3.4.5"
  }
</pre>

**Anything else relevant?**

**Comment by mgechev** [comment]
You can try:

```
npm uninstall @angular-devkit/build-angular
npm install @angular-devkit/build-angular
ng update --all
```

Looks like you're using the old builders. In version 8 we update some of the internals of the CLI.

**Comment by alan-agius4** [comment]
Closing as the above answers solved the issue.

It is also important to highlight that one should update using `ng update @angular/cli`, which will update the above mentioned packages automaticlly amongst other changes in your workspace.
