### ISSUE TITLE
options: { ...options }, SyntaxError: Expected identifier, string or number

### ISSUE THREAD

**Issue by Jonasdero** [angular/angular-cli#15062]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
When trying to run ng lint, or other commands (ng test, ng build) it throws an error.

## 🔬 Minimal Reproduction
running commands like ng lint, ng test or ng build on a circleci environment

## 🔥 Exception or Error
<pre><code>
npm run lint

> project-vino@0.0.0 lint /home/circleci/project
> ng lint

/home/circleci/project/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/analytics/forwarder.js:24
            options: { ...options },
                       ^^^^

SyntaxError: Expected identifier, string or number
   at Script (vm.js:87:7)
   at createScript (vm.js:251:3)
   at runInThisContext (vm.js:303:3)
   at Module.prototype._compile (internal/modules/cjs/loader.js:656:3)
   at Module._extensions[.js] (internal/modules/cjs/loader.js:699:3)
   at Module.prototype.load (internal/modules/cjs/loader.js:598:3)
   at tryModuleLoad (internal/modules/cjs/loader.js:537:5)
   at Module._load (internal/modules/cjs/loader.js:529:3)
   at Module.prototype.require (internal/modules/cjs/loader.js:636:3)
   at require (internal/modules/cjs/helpers.js:20:7)
</code></pre>


## 🌍 Your Environment
<pre><code>
{
  "name": "project-vino",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "deploy-staging": "firebase deploy -P staging",
    "deploy-production": "firebase deploy -P production",
    "build": "ng build",
    "build:prod": "ng build --prod",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "test": "ng test",
    "test:prod": "ng test --watch=false",
    "coverage-report": "ng test --code-coverage --watch=true"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.1.1",
    "@angular/common": "~8.1.1",
    "@angular/compiler": "~8.1.1",
    "@angular/core": "~8.1.1",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "~8.1.1",
    "@angular/platform-browser": "~8.1.1",
    "@angular/platform-browser-dynamic": "~8.1.1",
    "@angular/router": "~8.1.1",
    "firebase": "^6.3.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.1",
    "@angular/cli": "~8.1.1",
    "@angular/compiler-cli": "~8.1.1",
    "@angular/language-service": "~8.1.1",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }}

</code></pre>

**Comment by mityakoval** [comment]
Getting the same error in prod build. Were you able to fix it?

**Comment by Serdji** [comment]
Good afternoon, colleagues. I have a similar situation. I'm afraid I will have to roll back to Angular 7

**Comment by Serdji** [comment]
Colleagues and my friends, I solved this problem by updating the node js on the server to version 10.16.0
