### ISSUE TITLE
ng serve crashes upon change

### ISSUE THREAD

**Issue by jcuervas** [angular/angular-cli#15114]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: ....

### Description
when serving an angular app, after any change made the watcher recompiles it and crashes

## 🔬 Minimal Reproduction
ng new testApp
ng serve
Make any change to any project file (just like a new line in app.component.hml)

## 🔥 Exception or Error
<pre><code>
`* Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
 98% after emitting SizeLimitsPlugin(node:18296) UnhandledPromiseRejectionWarning: Error [ERR_INSPECTOR_NOT_CONNECTED]: Session is not connected
    at Session.post (inspector.js:75:13)
    at Promise (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/debug/ProfilingPlugin.js:54:25)
    at new Promise (<anonymous>)
    at Profiler.sendCommand (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/debug/ProfilingPlugin.js:53:11)
    at Profiler.stopProfiling (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/debug/ProfilingPlugin.js:76:15)
    at Proxy.compiler.hooks.done.tapAsync (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/debug/ProfilingPlugin.js:209:21)
    at args (/home/jcuervas/projects/angular_test/test/node_modules/speed-measure-webpack-plugin/WrappedPlugin/index.js:40:16)
    at args (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/debug/ProfilingPlugin.js:394:11)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jcuervas/projects/angular_test/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:92:1)
    at Watching._done (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/Watching.js:97:28)
    at compiler.emitRecords.err (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/Watching.js:72:19)
    at Compiler.emitRecords (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/Compiler.js:449:39)
    at compiler.emitAssets.err (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/Watching.js:53:20)
    at hooks.afterEmit.callAsync.err (/home/jcuervas/projects/angular_test/test/node_modules/webpack/lib/Compiler.js:435:14)
    at _next0 (eval at create (/home/jcuervas/projects/angular_test/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at _err0 (eval at create (/home/jcuervas/projects/angular_test/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
(node:18296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.6
Node: 10.16.0
OS: linux x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**

My system is under ubuntu 19.04, 
just tested same under windows and bug is not happening, everything is alright

**Comment by filipesilva** [comment]
I tried following your steps in a new app and didn't see any of the errors you mentioned. Can you double check this happens with a brand new app in your machine? 

In the log you included it shows stuff about profiling which is not enabled by default for new apps, did you change any build options perhaps?

**Comment by jcuervas** [comment]
umm you gave me the hint. I enabled this env variable: NG_BUILD_PROFILING="true". Don't remember why.
After removing it the compiler is going ok.
Thanks
