### ISSUE TITLE
Angular-cli ng serve broccoli plugin error

### ISSUE THREAD

**Issue by tisotmarcelo** [angular/angular-cli#1517]
Hello guys, i got build error when i exec ng serve on my angular2 app, anyone can help me?, thanks.

Here,s the error log:

Build error

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  D:/MARCELO/AngularJS/Proyectos/a2todos/tmp/broccoli_type_script_compiler-input_base_path-i0PkvnzC.tmp/0/src/app/todos/todos.component.spec.ts (10, 21): Supplied parameters do not match any signature of call target.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:26:49)
    at Angular2App._getTsTree (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\MARCELO\AngularJS\Proyectos\a2todos\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\MARCELO\AngularJS\Proyectos\a2todos\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

**Comment by elpddev** [comment]
`todos.component.spec.ts (10, 21): Supplied parameters do not match any signature of call target.`
Maybe that is the culprit ?
Just thinking, did you add parameters to the constructor of todos.component ?

**Comment by sirajc** [comment]
Switch to latest .11-webpack version

**Comment by filipesilva** [comment]
The following error is correct: `todos.component.spec.ts (10, 21): Supplied parameters do not match any signature of call target.` Your unit test is not compiling because of an error.

You need to either update your tests after you change your components. Unit tests should fail when you change your components.
