### ISSUE TITLE
Error: ENOENT: no such file or directory, open './browser/index.html'

### ISSUE THREAD

**Issue by Murtaza-arif** [angular/angular-cli#15180]
-dev> npm run serve:ssr

> stvm@0.0.0 serve:ssr D:\Murtaza\projects\stvm\frontend\stvm-portal-dev
> node dist/server

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open './browser/index.html'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Module.<anonymous> (D:\Murtaza\projects\stvm\frontend\stvm-portal-dev\dist\server.js:114:19)
    at __webpack_require__ (D:\Murtaza\projects\stvm\frontend\stvm-portal-dev\dist\server.js:20:30)
    at D:\Murtaza\projects\stvm\frontend\stvm-portal-dev\dist\server.js:84:18
    at Object.<anonymous> (D:\Murtaza\projects\stvm\frontend\stvm-portal-dev\dist\server.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stvm@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stvm@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\win10\AppData\Roaming\npm-cache\_logs\2019-07-27T10_03_06_970Z-debug.log

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
