### ISSUE TITLE
webpack branch installs ver. 1.0.0-beta.2-mobile.4 in project

### ISSUE THREAD

**Issue by Blaugold** [angular/angular-cli#1528]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
(node:95661) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.2-mobile.4
node: 6.3.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Created using CLI. No changes were made.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
gabrielterwesten@Gabriels-MBP ~/D/s/ng-cli-test> ng test
(node:95665) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
⠋ BuildingNo angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
Error: No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/gabrielterwesten/Dev/sandbox/ng-cli-test/node_modules/angular-cli/lib/models/builder.js:57:13)
    at Class.module.exports.Task.extend.init (/Users/gabrielterwesten/Dev/sandbox/ng-cli-test/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/gabrielterwesten/Dev/sandbox/ng-cli-test/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/gabrielterwesten/Dev/sandbox/ng-cli-test/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at win.checkWindowsElevation.then (/Users/gabrielterwesten/Dev/sandbox/ng-cli-test/node_modules/angular-cli/addon/ng2/commands/test.js:63:30)
    at lib$rsvp$$internal$$tryCatch (/Users/gabrielterwesten/Dev/sandbox/ng-cli-test/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/gabrielterwesten/Dev/sandbox/ng-cli-test/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/gabrielterwesten/Dev/sandbox/ng-cli-test/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/gabrielterwesten/Dev/sandbox/ng-cli-test/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

5. Mention any other details that might be useful.
package.json specifies `"angular-cli": "^1.0.0-beta.11-webpack"`. Removing `^` in the semver spec and running `npm install` installs the correct version and fixes the issue.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by christophertrudel** [comment]
Can confirm step 5 fixes for me as well.

**Comment by jbeckton** [comment]
step 5 fixes the issue for that particular project. If you create a new project you have the same problem.

**Comment by jbeckton** [comment]
npm install -g angular-cli@latest installs angular-cli: 1.0.0-beta.2-mobile.4

**Comment by hansl** [comment]
Okay this is a semver failure. We'll fix and rerelease tomorrow as soon as possible.
