### ISSUE TITLE
Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`.

### ISSUE THREAD

**Issue by Kamczii** [angular/angular-cli#15367]
I have installed this package npm install --save @types/googlemaps

And after that while i wanted to ng serve im getting this error

> An unhandled exception occurred: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query.
> See "C:\Users\Kamil\AppData\Local\Temp\ng-MshjjW\angular-errors.log" for further details.

This is the file

```
[error] BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query.
    at unknownQuery (D:\Projekty\spots\spot-map\frontend\frontend\node_modules\browserslist\index.js:204:10)
    at D:\Projekty\spots\spot-map\frontend\frontend\node_modules\browserslist\index.js:296:11
    at Array.reduce (<anonymous>)
    at resolve (D:\Projekty\spots\spot-map\frontend\frontend\node_modules\browserslist\index.js:237:18)
    at browserslist (D:\Projekty\spots\spot-map\frontend\frontend\node_modules\browserslist\index.js:361:16)
    at new BuildBrowserFeatures (D:\Projekty\spots\spot-map\frontend\frontend\node_modules\@angular-devkit\build-angular\src\utils\build-browser-features.js:17:35)
    at generateWebpackConfig (D:\Projekty\spots\spot-map\frontend\frontend\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:24:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

Reinstall angular/cli didn't worked.

**Comment by alan-agius4** [comment]
Hi @Kamczii, can you please share your browserslist file?, From the error above, it seems that it's contents are invalid.

**Comment by deepakshrma** [comment]
Duplicate issue [https://github.com/angular/angular-cli/issues/5075]

**Comment by alan-agius4** [comment]
Can you try the following: https://github.com/angular/angular-cli/issues/3938#issuecomment-272633128

**Comment by alan-agius4** [comment]
Since no further details have been provided bu @Kamczii. I am assuming this has been solved. 

If not kindly open a new issue, thanks
