### ISSUE TITLE
ng serve doesn't recover from initial compilation error in AOT

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#15397]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No

### Description

When having a compilation error such as an invalid import and you run `ng serve --aot` after fixing the error you will get an unrecoverable error.

## 🔬 Minimal Reproduction
- Open `app.component.ts`
- Change `import { Component} from '@angular/core';` to `import { Component, wrong} from '@angular/core';`
- `ng serve --aot`
- remove the invalid import

## 🔥 Exception or Error

```
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\git\cli-repos\universal-ivy\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\git\cli-repos\universal-ivy\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:918:23)
    at plugin.done.then (C:\git\cli-repos\universal-ivy\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\git\cli-repos\universal-ivy\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\git\cli-repos\universal-ivy\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:918:23)
    at plugin.done.then (C:\git\cli-repos\universal-ivy\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.0-rc.0
Node: 10.10.0
OS: win32 x64
Angular: 8.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.0-rc.0
@angular-devkit/build-angular              0.803.0-rc.0
@angular-devkit/build-optimizer            0.803.0-rc.0
@angular-devkit/build-webpack              0.803.0-rc.0
@angular-devkit/core                       8.3.0-rc.0
@angular-devkit/schematics                 8.3.0-rc.0
@angular/cli                               8.3.0-rc.0
@ngtools/webpack                           8.3.0-rc.0
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.0-rc.0
@schematics/update                         0.803.0-rc.0
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2
</code></pre>

**Comment by alan-agius4** [comment]
Closing as this is being tracked https://github.com/angular/angular/issues/32214
