### ISSUE TITLE
v8.3.0, TypeError: logger.status is not a function

### ISSUE THREAD

**Issue by minhoryang** [angular/angular-cli#15426]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
```
-    "@angular-devkit/build-angular": "~0.802.2",
-    "@angular/cli": "~8.2.2",
-    "@angular/compiler-cli": "~8.2.0",
-    "@angular/language-service": "~8.2.0",
+    "@angular-devkit/build-angular": "~0.803.0",
+    "@angular/cli": "~8.3.0",
+    "@angular/compiler-cli": "~8.2.3",
+    "@angular/language-service": "~8.2.3",
```

### Description

 After `ng update @angular/cli`, then `ng start` broken.

## 🔬 Minimal Reproduction
check above.

## 🔥 Exception or Error
<pre><code>[error] TypeError: logger.status is not a function
    at defaultHandler (/my-app/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ProgressPlugin.js:18:10)
    at compiler.hooks.compilation.tap.compilation (/my-app/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/ProgressPlugin.js:176:5)
    at SyncHook.eval [as call] (eval at create (/my-app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/my-app/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/my-app/node_modules/webpack/lib/Compiler.js:614:26)
    at hooks.beforeCompile.callAsync.err (/my-app/node_modules/webpack/lib/Compiler.js:650:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/my-app/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/my-app/node_modules/webpack/lib/Compiler.js:645:28)
    at compiler.hooks.watchRun.callAsync.err (/my-app/node_modules/webpack/lib/Watching.js:77:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/my-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/my-app/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/my-app/node_modules/webpack/lib/Watching.js:41:32)
    at Watching.compiler.readRecords.err (/my-app/node_modules/webpack/lib/Watching.js:33:9)
    at Compiler.readRecords (/my-app/node_modules/webpack/lib/Compiler.js:512:11)
    at new Watching (/my-app/node_modules/webpack/lib/Watching.js:30:17)
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 8.3.0
Node: 10.16.3
OS: darwin x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/cdk                      8.1.3
@angular/cli                      8.3.0
@angular/material                 8.1.3
@angular/pwa                      0.803.0
@ngtools/webpack                  8.3.0
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0</code></pre>

**Anything else relevant?**

**Comment by minhoryang** [comment]
`@angular-devkit/build-angular     0.803.0` got `"webpack": "4.39.2"` (mis-matched with `ng version`)

**Comment by alan-agius4** [comment]
This seems to be a hoisting package hoisting issue. Which package manager are you using?

**Comment by minhoryang** [comment]
@alan-agius4 Thanks! Results:
```
$ npm prune
audited 46206 packages in 21.216s
found 0 vulnerabilities
```

**Comment by lppedd** [comment]
This happened to me too. You've multiple versions of Webpack.
Manually removing the `4.38`, `npm dedupe`ing end `npm install`ing fixed it.

**Comment by minhoryang** [comment]
After inspection,
https://github.com/webpack/webpack/blob/v4.39.2/lib/logging/Logger.js#L30
https://github.com/webpack/webpack/blob/v4.38.0/lib/logging/Logger.js#L30

**Comment by lppedd** [comment]
@minhoryang yeah, you're still using `4.38`.

**Comment by minhoryang** [comment]
@lppedd Yeah! you're right.
```
$ npm ls webpack
my-app@0.0.0 /my-app
├─┬ @angular-devkit/build-angular@0.803.0
│ └── webpack@4.39.2
└─┬ @storybook/angular@5.1.11
  ├─┬ @storybook/core@5.1.11
  │ ├─┬ corejs-upgrade-webpack-plugin@2.2.0
  │ │ └── webpack@4.38.0  deduped
  │ └── webpack@4.38.0  deduped
  └── webpack@4.38.0
```

**Comment by minhoryang** [comment]
Oh! `storybook/angular` got `webpack@4.38.0`!
I wasn't noticed that...

**Comment by lppedd** [comment]
@minhoryang just empty the `package-lock` (not delete, only empty), then delete `node_modules`, and then `npm i`

**Comment by minhoryang** [comment]
`@storybook/angular` only required `"webpack": "^4.33.0"` (`@storybook/core` too)

@lppedd Thanks!!!

Now I'm curious why I got this issue from where/when?
Which command do I need to use `npm install --save` for bypassing this issue?

**Comment by lppedd** [comment]
@minhoryang Honestly I think it's just that NPM isn't *that* smart with "duplicated" dependencies.  
I'm using Storybook too, but it would have been the same with any other module.

I think a good workaround is creating a bash `alias` for
```
rm -rf node_modules && npm i
```
