### ISSUE TITLE
CLI: 8.3.0 + iVY = ERROR in Error: Cannot assign to a reference or variable!

### ISSUE THREAD

**Issue by GlauberF** [angular/angular-cli#15432]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
I updated my CLI and enabled IVY, but when I'm building the error mentioned below.
I checked several things I found on the internet, example of the links below:

https://stackoverflow.com/questions/48021581/error-cannot-assign-to-a-reference-or-variable-angular-4

https://github.com/TrilonIO/aspnetcore-angular-universal/issues/293

And the problem, which is not pointing the location of the error, if there is error.
Because it started this only after updating the cli and activating ivy

## 🔥 Exception or Error
```
ERROR in Error: Cannot assign to a reference or variable!
    at _AstToIrVisitor.visitPropertyWrite (/var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:8412:31)
    at PropertyWrite.visit (/var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:7256:28)
    at convertActionBinding (/var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:8021:49)
    at prepareEventListenerParameters (/var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:16230:27)
    at /var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:17314:24
    at /var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:17095:71
    at /var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:16405:87
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (/var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:16405:60)
    at /var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:16963:60
    at /var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:16383:81
    at Array.forEach (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (/var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:16383:37)
    at /var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:16963:60
    at /var/www/html/pwa-vimbo/node_modules/@angular/compiler/bundles/compiler.umd.js:16383:81
    at Array.forEach (<anonymous>)
```

## 🌍 Your Environment
```javascript
Angular CLI: 8.3.0
Node: 10.15.3
OS: linux x64
Angular: 9.0.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.0
@angular-devkit/build-angular      0.803.0
@angular-devkit/build-optimizer    0.803.0
@angular-devkit/build-webpack      0.803.0
@angular-devkit/core               8.3.0
@angular-devkit/schematics         8.3.0
@angular/cdk                       8.1.3
@angular/cli                       8.3.0
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.1.3
@angular/material-moment-adapter   8.1.3
@ngtools/webpack                   8.3.0
@schematics/angular                8.3.0
@schematics/update                 0.803.0
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.39.2
```

**Comment by mgechev** [comment]
@GlauberF by any chance, can you share an isolated example where we can reproduce the problem?

**Comment by GlauberF** [comment]
@mgechev I have done several tests in recent days, it is related to activate IVY.
In my tests, I tested with the latest version of CLI plus IVy, gave this problem mentioned above.
So I went back to the previous versions I had, and left active only Ivy, gave the same problem.
in short it is something with Ivy and not with the CLI in fact, but I can't investigate further because the error does not show a way.
I went through the whole project looking for something, but I found nothing, because I follow the angular style guide.

Before popping the error, a warning appeared from a library, I don't know if it could have any relationship.

![Captura de Tela_selecionar área_20190826094825](https://user-images.githubusercontent.com/11314585/63691854-aec40c00-c7e6-11e9-94b4-7774b0069f49.png)

**Comment by desmofab** [comment]
Hi @GlauberF ,
same error here, caused by Ivy activation. I solved checking out template variable definition, in my case: `*ngIf="element.outstanding as partialCollect"`. This wuold give me that error. I think it depends on your code. Try to check if you have something similar in your code. Otherwise could be related to `[(ngModel)]` variable definiton that conflicts with a template variable.
Hope I was helpful :)

**Comment by GlauberF** [comment]
@desmofab I have analyzed the issue of ```[(ngModel)]``` and at no time does a variable definition conflict with a model variable.
I checked for something like you mentioned ```*ngIf =" element.outstanding as partialCollect "``` but I don't have anything like that either.
Look, I don't know where to look anymore and what's worse is that the cli doesn't tell me where the problem is.
@mgechev Any news on this?

**Comment by alan-agius4** [comment]
@GlauberF, without a reproduction it's pretty hard to investigate the issue. Maybe @alxhub have a better insight?

**Comment by GlauberF** [comment]
maybe some way to enable some deeper debugging when deploying ?

**Comment by alxhub** [comment]
The problem is here:

```
[(ngModel)]="adminUsername" #adminUsername="ngModel"
```

This doesn't work in Ivy - the banana-in-a-box syntax here is attempting to write to `adminUsername` which is a reference to the directive. I'm not sure what this code is trying to accomplish but I don't think it's doing what you want.

**Comment by alan-agius4** [comment]
@alxhub, can we print a better error message?

**Comment by GlauberF** [comment]
That's not my problem @alxhub  , see the image where I search for ngModel.
![Captura de Tela_selecionar área_20190905191412](https://user-images.githubusercontent.com/11314585/64387195-a1dac000-d011-11e9-92c4-b71093561f00.png)


@alan-agius4 It would be very interesting, because even I can not find any logic for this error, does not even point the file, very shallow the error and not objective.

**Comment by GlauberF** [comment]
I found the problem and the fault of the junior frontend, but all error reports with this message, none of them addressed the error I found.
I was discovered, why I put a console.log and found the name of the variable that was giving problem.

Now my question, why not the error message, since when I put console.log I discovered and went straight to the point of error

![Captura de Tela_selecionar área_20190909140807](https://user-images.githubusercontent.com/11314585/64551433-63901a00-d30b-11e9-963c-a68aa30646a7.png)
