### ISSUE TITLE
ng add issue while installing latest angular material version 

### ISSUE THREAD

**Issue by manjunath-nrh** [angular/angular-cli#15525]
ng add issue while installing latest angular material version 
 ng add @angular/material 

Error :

Installed packages for tooling via npm.
An unhandled exception occurred: Cannot find module '/node_modules/@angular/material/package.json'
See "/tmp/ng-vQ6COf/angular-errors.log" for further details.

But ng add @angular/material  is working fine with older  version ex : ng add @angular/material@6.2.1

and it is fine with  npm install --save @angular/material as well 

why it has issue with ng add ?

**Comment by alan-agius4** [comment]
Kindly provide all the required information that is requested In the issue template to gather with the contents of the log file.

Thanks

**Comment by manjunath-nrh** [comment]
Angular CLI: 8.3.3
Node: 11.12.0
Angular: 8.2.5

reproducing step
create new project and add angular material using ng add @angular/material

issue +1
An unhandled exception occurred: Cannot find module '/node_modules/@angular/material/package.json'
See "/tmp/ng-U0E914/angular-errors.log" for further details.

Error log +1

[error] Error: Cannot find module '/node_modules/@angular/material/package.json'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
at Function.Module._load (internal/modules/cjs/loader.js:575:25)
at Module.require (internal/modules/cjs/loader.js:705:19)
at require (internal/modules/cjs/helpers.js:14:16)
at NodeModulesEngineHost._resolveCollectionPath (/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:74:39)
at NodeModulesEngineHost.createCollectionDescription (/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:115:27)
at SchematicEngine._createCollectionDescription (/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
at SchematicEngine.createCollection (/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
at AddCommand.getCollection (/node_modules/@angular/cli/models/schematic-command.js:128:35)
at AddCommand.runSchematic (/node_modules/@angular/cli/models/schematic-command.js:291:50)
at AddCommand.executeSchematic (/node_modules/@angular/cli/commands/add-impl.js:148:31)
at AddCommand.run (/node_modules/@angular/cli/commands/add-impl.js:114:21)
at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by manjunath-nrh** [comment]
Hi
I think the issue with first time ... I tried it 3 to 4 times got the same issue by creating new project using ng new <appname> and I run ng add @angular/material only once...in this case the above issue was reproducible..but once again you hit --> ng add @angular/material the issue was gone.
