### ISSUE TITLE
angular-cli in Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by rexebin** [angular/angular-cli#1555]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.10
node: 5.12.0
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Nothing is changed.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
File: /home/rex/ng-cli/src
The Broccoli Plugin: [Funnel] failed with:
Error: watch /home/rex/ng-cli/src EPERM
    at exports._errnoException (util.js:893:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at NodeWatcher.watchdir (/home/rex/ng-cli/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/home/rex/ng-cli/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (/home/rex/ng-cli/node_modules/angular-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/rex/ng-cli/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at /home/rex/ng-cli/node_modules/angular-cli/node_modules/angular-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/home/rex/ng-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/rex/ng-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/rex/ng-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/rex/ng-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (/home/rex/ng-cli/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at new Funnel (/home/rex/ng-cli/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/home/rex/ng-cli/node_modules/angular-cli/lib/broccoli/angular2-app.js:92:7)
    at new Angular2App (/home/rex/ng-cli/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (/home/rex/ng-cli/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/rex/ng-cli/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/rex/ng-cli/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/rex/ng-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/rex/ng-cli/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /home/rex/ng-cli/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/rex/ng-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/rex/ng-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/rex/ng-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/rex/ng-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```

5. Mention any other details that might be useful.

Bash on Ubuntu on Windows, installed after windows 10 1607 update.

lsb_release -a:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
```
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by panic175** [comment]
I got the same error.

When I try installing this watchman-thing from [here](https://www.npmjs.com/package/fb-watchman). I got this message:

> Could not start watchman; falling back to NodeWatcher for file system events.
> Visit http://ember-cli.com/user-guide/#watchman for more info.

The rest is the same.

**Comment by rexebin** [comment]
I think it could be Bash On Ubuntu on Windows bug, it is beta afterall.

With dotnet core 1.0, I got some errors indicating localhost:5000 was used when there is nothing using it in bash. 

They could be related: not able to watch some address or ports in bash.

**Comment by bruno222** [comment]
+1

# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty


# ng --version
(node:2233) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.10
node: 6.2.2
os: linux x64

**Comment by erikfig** [comment]
+1

```
ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
File: ~/dev/01-em-producao/angular2/projeto/src
The Broccoli Plugin: [Funnel] failed with:
Error: watch ~/dev/01-em-producao/angular2/projeto/src EPERM
    at exports._errnoException (util.js:873:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at NodeWatcher.watchdir (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/sane/index.js:17:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at ~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/angular-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at ~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at new Funnel (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/lib/broccoli/angular2-app.js:92:7)
    at new Angular2App (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (~/dev/01-em-producao/angular2/projeto/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at ~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at ~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (~/dev/01-em-producao/angular2/projeto/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)


Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```

**Comment by bunglestink** [comment]
+1

    $ ng serve
    (node:829) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
    Could not start watchman; falling back to NodeWatcher for file system events.
    Visit http://ember-cli.com/user-guide/#watchman for more info.
    File: ~/Projects/ng-test/src
    The Broccoli Plugin: [Funnel] failed with:
    Error: watch ~/Projects/ng-test/src EPERM
        at exports._errnoException (util.js:1012:11)
        at FSWatcher.start (fs.js:1429:19)
        at Object.fs.watch (fs.js:1456:11)
        at NodeWatcher.watchdir (~/Projects/ng-test/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:144:20)
        at new NodeWatcher (~/Projects/ng-test/node_modules/angular-cli/node_modules/sane/src/node_watcher.js:45:8)
        at new sane (~/Projects/ng-test/node_modules/angular-cli/node_modules/sane/index.js:17:12)
        at EventEmitter.Watcher_addWatchDir [as addWatchDir] (~/Projects/ng-test/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
        at ~/Projects/ng-test/node_modules/angular-cli/node_modules/angular-cli-broccoli/lib/builder.js:95:35
        at lib$rsvp$$internal$$tryCatch (~/Projects/ng-test/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
        at lib$rsvp$$internal$$invokeCallback (~/Projects/ng-test/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
        at ~/Projects/ng-test/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
        at lib$rsvp$asap$$flush (~/Projects/ng-test/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)
    
    The broccoli plugin was instantiated at:
        at Funnel.Plugin (~/Projects/ng-test/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
        at new Funnel (~/Projects/ng-test/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
        at Angular2App._buildInputTree (~/Projects/ng-test/node_modules/angular-cli/lib/broccoli/angular2-app.js:92:7)
        at new Angular2App (~/Projects/ng-test/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
        at module.exports (~/Projects/ng-test/angular-cli-build.js:10:10)
        at Class.module.exports.Task.extend.setupBroccoliBuilder (~/Projects/ng-test/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
        at Class.module.exports.Task.extend.init (~/Projects/ng-test/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
        at new Class (~/Projects/ng-test/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
        at Class.module.exports.Task.extend.run (~/Projects/ng-test/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
        at ~/Projects/ng-test/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
        at lib$rsvp$$internal$$tryCatch (~/Projects/ng-test/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
        at lib$rsvp$$internal$$invokeCallback (~/Projects/ng-test/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
        at ~/Projects/ng-test/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
        at lib$rsvp$asap$$flush (~/Projects/ng-test/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)
    
    
    Livereload server on http://localhost:49152
    Serving on http://localhost:4200/

**Comment by jcoryarnold** [comment]
+1

**Comment by filipesilva** [comment]
BashOnWindows is known to have problems with following symlinks, and beta.10 works by creating a whole lot of symlinks. Thus it breaks.

Symlinks are no longer necessary on the webpack version (#1455). See https://github.com/angular/angular-cli#webpack-preview-release-update for update instructions.
