### ISSUE TITLE
ng build fails to remove the tmp folder using angular-cli@webpack

### ISSUE THREAD

**Issue by amreladawy** [angular/angular-cli#1557]
After upgrading to angular-cli@webpack, running `ng build` fails unless the `tmp` folder is manually deleted. 
1. OS?  
   Windows 7
2. Versions.  

```
angular-cli: 1.0.0-beta.11-webpack
node: 4.4.7
os: win32 x64
```
1. Reproduction steps. 
   Was this an app that wasn't created using the CLI?
   yes but with a previous version of cli
   What change did you do on your code? 
   I followed the instruction of upgrading to angular-cli@webpack
2. The log given by the failure.  

```
EEXIST: file already exists, mkdir 'D:\myapp\tmp'
Error: EEXIST: file already exists, mkdir 'D:\myapp\tmp'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at testCanSymlink (C:\Users\amr\AppData\Roaming\npm\node_modules\angular-cli\node_modules\symlink-or-copy\index.js:18:6)
    at Object.<anonymous> (C:\Users\amr\AppData\Roaming\npm\node_modules\angular-cli\node_modules\symlink-or-copy\index.js:9:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```
1.  Any other details that might be useful.

running `ng --version` and `ng serve`  give the same error as well

**Comment by marcelogft** [comment]
Same issue. 
 Windows: 8.1
 Node: 6.1.0
 NPM: 3.8.6

I need to manually delete the PROJECT/tmp folder before running ng serve.

**Comment by NogsMPLS** [comment]
Same, need to manually delete:

Windows 10
Node 6.3.1
npm 3.10.3

**Comment by filipesilva** [comment]
The webpack branch shouldn't need the `tmp` folder at all. Did you follow the update instructions and update both global AND local package?

**Comment by amreladawy** [comment]
Yes, I did. Whatever in this guide https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md

I even did that again now and got the same error.
Do you want to verify any other steps I should follow?

**Comment by filipesilva** [comment]
Really odd... can you manually verify if your local and global install have the right versions of the CLI? You can do this via `npm list -g --depth=0` for global and `npm list --depth=0` for local.

**Comment by amreladawy** [comment]
Here is the output for each command
```
$ npm list -g --depth=0
C:\Users\amr\AppData\Roaming\npm
+-- admin@0.0.0
+-- alshApp@0.0.1
+-- angular-cli@1.0.0-beta.11-webpack.2
+-- bower@1.7.9
+-- cordova@6.2.0
+-- cordova-icon@0.7.0
+-- cordova-splash@0.7.1
+-- eslint@2.11.1
+-- express-generator@4.13.1
+-- generator-ionic@0.8.0
+-- gradle@0.1.0
+-- grunt@1.0.1
+-- grunt-cli@1.2.0
+-- gulp@3.9.1
+-- gulp-cli@1.2.1
+-- ionic@2.0.0-beta.37
+-- jshint@2.9.2
+-- learnyounode@3.5.3
+-- minimatch@3.0.2
+-- nativescript@2.0.1
+-- next-update@1.2.2
+-- node-gyp@3.3.1
+-- npm@3.10.6
+-- nvmw@0.1.5
+-- phonegap@6.2.5
+-- react-native-cli@0.2.0
+-- tds@0.1.0
+-- tsc@1.20150623.0
+-- tsd@0.6.5
+-- typescript@1.8.10
+-- typings@1.3.2
`-- yo@1.8.3

npm ERR! peer dep missing: @angular/common@2.0.0-rc.4, required by ionic-angular@2.0.0-beta.11
npm ERR! peer dep missing: @angular/compiler@2.0.0-rc.4, required by ionic-angular@2.0.0-beta.11
npm ERR! peer dep missing: @angular/core@2.0.0-rc.4, required by ionic-angular@2.0.0-beta.11
npm ERR! peer dep missing: @angular/http@2.0.0-rc.4, required by ionic-angular@2.0.0-beta.11
npm ERR! peer dep missing: @angular/platform-browser@2.0.0-rc.4, required by ionic-angular@2.0.0-beta.11
npm ERR! peer dep missing: @angular/platform-browser-dynamic@2.0.0-rc.4, required by ionic-angular@2.0.0-beta.11
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6
npm ERR! missing: inherits@, required by fstream-npm@0.1.4
npm ERR! missing: npmlog@, required by npm-registry-client@0.2.27
npm ERR! missing: npmlog@, required by npm-registry-client@7.0.8

```


```
$ npm list --depth=0
admin@0.0.0 D:\myapp
+-- @angular/common@2.0.0-rc.4
+-- @angular/compiler@2.0.0-rc.4
+-- @angular/core@2.0.0-rc.4
+-- @angular/forms@0.2.0
+-- @angular/http@2.0.0-rc.4
+-- @angular/platform-browser@2.0.0-rc.4
+-- @angular/platform-browser-dynamic@2.0.0-rc.4
+-- @angular/router@3.0.0-beta.2
+-- @types/jasmine@2.2.31
+-- @types/protractor@1.5.16
+-- angular-cli@1.0.0-beta.11-webpack
+-- codelyzer@0.0.26
+-- core-js@2.4.1
+-- jasmine-core@2.4.1
+-- jasmine-spec-reporter@2.5.0
+-- karma@0.13.22
+-- karma-chrome-launcher@0.2.3
+-- karma-coverage@1.1.1
+-- karma-jasmine@0.3.8
+-- protractor@3.3.0
+-- reflect-metadata@0.1.3
+-- rxjs@5.0.0-beta.6
+-- ts-helpers@1.1.1
+-- ts-node@1.2.1
+-- tslint@3.13.0
+-- typescript@2.0.0
`-- zone.js@0.6.12

npm ERR! peer dep missing: webpack@^1.4.0, required by karma-webpack@1.7.0
```

I can see that angulat-cli is webpack version in both outputs

**Comment by filipesilva** [comment]
Right you are. Will investigate further.

**Comment by catull** [comment]
The problem was reported in August 2016, with 1.0.0-beta.11-webpack.
@amreladawy @marcelogft @NogsMPLS Is this still a problem?
Is it Windows-only?

**Comment by amreladawy** [comment]
It is not happening now 

 

> angular-cli: 1.0.0-beta.20-4
node: 6.9.1
os: win32 x64


I think this issue can be closed. Can we know wich release fixed this issue?

**Comment by marcelogft** [comment]
It's working fine now.
angular-cli: 1.0.0-beta.24
node: 6.1.0
os: win32 x64

Thx.

**Comment by Brocco** [comment]
@amreladawy & @marcelogft I'm glad this is now working for both of you, closing the issue.
