### ISSUE TITLE
The Broccoli Plugin: [LESSPlugin] failed wit

### ISSUE THREAD

**Issue by ulou** [angular/angular-cli#1559]
1.  os: win32 x64 (windows 7)
2.  angular-cli: 1.0.0-beta.9, node: 6.3.0
3.  After ng serve, app sometimes work, sometimes not.
```
`Build error

The Broccoli Plugin: [LESSPlugin] failed with:
undefined

The broccoli plugin was instantiated at: 
    at LESSPlugin.Plugin (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at LESSPlugin.CachingWriter [as constructor] (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at new LESSPlugin (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\lib\broccoli\angular-broccoli-less.js:21:12)
    at Object.exports.makeBroccoliTree (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\lib\broccoli\angular-broccoli-less.js:52:12)
    at Angular2App._buildTree (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\lib\broccoli\angular2-app.js:133:27)
    at new Angular2App (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\Users\john\Desktop\myproject\modules\frontend\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\john\Desktop\myproject\modules\frontend\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)`
```

 Apps worked without any error, after one day this error appears. I tried to install/update libraries.

**Comment by bafinneg** [comment]
Experiencing the same issue

1. os: mac osx 10.11.6
2. angular-cli: 1.0.0-beta.10, node: 6.3.0

Started appearing after adding a new component .ts / .html

**Comment by filipesilva** [comment]
We're moving our build system to webpack, which solves this issue. See https://github.com/angular/angular-cli#webpack-preview-release-update if you want to try it now.
