### ISSUE TITLE
Unexpected token error when following Readme.md setup instructions

### ISSUE THREAD

**Issue by bignis** [angular/angular-cli#156]
I'm on Windows 8 running these commands in PowerShell as Administrator mode.  Following the readme directions gives me an error originating from angular-cli-github-pages.

```
PS C:\Windows\system32> npm install -g angular-cli
npm WARN engine angular-cli@0.0.20: wanted: {"node":">= 4.1.0"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN deprecated lodash-node@2.4.1: This package is no longer maintained. See its readme for upgrade details.
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. ht
tps://github.com/chalk/supports-color
C:\Users\U0044975\AppData\Roaming\npm\ng -> C:\Users\U0044975\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
angular-cli@0.0.20 C:\Users\U0044975\AppData\Roaming\npm\node_modules\angular-cli
├── exit@0.1.2
├── symlink-or-copy@1.0.1 (copy-dereference@1.0.0)
├── resolve@1.1.7
├── silent-error@1.0.0 (debug@2.2.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.4, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── broccoli-concat@0.0.13 (js-string-escape@1.0.0, mkdirp@0.5.1, broccoli-kitchen-sink-helpers@0.2.9, glob@4.5.3, quick
-temp@0.1.5)
├── fs-extra@0.18.4 (jsonfile@2.2.3, graceful-fs@3.0.8, rimraf@2.5.1)
├── broccoli-funnel@1.0.1 (array-equal@1.0.0, blank-object@1.0.1, path-posix@1.0.0, fs-tree-diff@0.3.1, fast-ordered-set
@1.0.2, debug@2.2.0, walk-sync@0.2.6, minimatch@2.0.10, mkdirp@0.5.1, rimraf@2.5.1, broccoli-plugin@1.2.1)
├── broccoli-merge-trees@1.1.1 (fs-tree-diff@0.4.4, debug@2.2.0, fast-ordered-set@1.0.2, can-symlink@1.0.0, rimraf@2.5.1
, broccoli-plugin@1.2.1)
├── broccoli-writer@0.1.1 (rsvp@3.1.0, quick-temp@0.1.5)
├── lodash@3.10.1
├── typescript@1.7.5
├── broccoli@0.16.9 (broccoli-slow-trees@1.1.0, copy-dereference@1.0.0, promise-map-series@0.2.2, mime@1.3.4, commander@
2.9.0, findup-sync@0.2.1, broccoli-kitchen-sink-helpers@0.2.9, connect@3.4.1, rsvp@3.1.0, rimraf@2.5.1, quick-temp@0.1.5
, handlebars@4.0.5)
├── leek@0.0.19 (rsvp@3.1.0)
└── ember-cli@1.13.13 (ember-cli-is-package-missing@1.0.0, ember-cli-path-utils@1.0.0, ember-cli-test-info@1.0.0, ember-
cli-string-utils@1.0.0, clean-base-url@1.0.0, ember-cli-get-dependency-depth@1.0.0, ember-cli-normalize-entity-name@1.0.
0, escape-string-regexp@1.0.4, amd-name-resolver@0.0.2, fs-monitor-stack@1.1.0, is-git-url@0.2.3, pleasant-progress@1.1.
0, ember-cli-copy-dereference@1.0.0, isbinaryfile@2.0.4, promise-map-series@0.2.2, broccoli-source@1.1.0, exists-sync@0.
0.3, diff@1.4.0, through@2.3.8, node-modules-path@1.0.1, broccoli-viz@2.0.1, bower-endpoint-parser@0.2.2, walk-sync@0.1.
3, inflection@1.8.0, node-uuid@1.4.7, broccoli-sane-watcher@1.1.4, debug@2.2.0, nopt@3.0.6, readline2@0.1.1, chalk@1.1.0
, temp@0.8.1, http-proxy@1.13.0, findup@0.1.5, morgan@1.6.1, semver@4.3.6, glob@5.0.13, minimatch@2.0.10, rsvp@3.1.0, br
occoli-kitchen-sink-helpers@0.2.9, findup-sync@0.2.1, git-repo-info@1.1.2, cpr@0.4.2, sane@1.3.1, compression@1.6.1, yam
@0.0.18, configstore@1.2.1, ember-cli-preprocess-registry@1.1.0, broccoli-config-loader@1.0.0, quick-temp@0.1.3, portfin
der@0.4.0, fs-extra@0.22.1, broccoli-plugin@1.2.1, tiny-lr@0.2.0, broccoli-config-replace@1.1.1, merge-defaults@0.2.1, e
xpress@4.13.4, ember-router-generator@1.1.1, broccoli@0.16.8, bower-config@0.6.1, core-object@0.0.2, inquirer@0.5.1, mar
kdown-it@4.3.0, markdown-it-terminal@0.0.2, broccoli-sourcemap-concat@2.0.2, leek@0.0.18, testem@0.9.11, broccoli-babel-
transpiler@5.5.0, npm@2.14.10, bower@1.7.7)

PS C:\Windows\system32> cd \code

PS C:\code> ng new RegexByExample
warning: An ember-addon has attempted to override the core command "new". The addon command will be used as the overrid
ing was explicit.
DEPRECATION: Node v0.10.32 is no longer supported by Ember CLI. Please update to a more recent version of Node
undefined
version: 1.13.13
installing ng2
  create ember-cli-build.js
  create .gitignore
  create karma-test-shim.js
  create karma.conf.js
  create package.json
  create src\app\regex-by-example.html
  create src\app\regex-by-example.spec.ts
  create src\app\regex-by-example.ts
  create src\app.ts
  create src\favicon.ico
  create src\index.html
  create src\tsconfig.json
Installing packages for tooling via npm.WARN engine angular-cli@0.0.20: wanted: {"node":">= 4.1.0"} (current: {"node":"
.10.32","npm":"2.14.10"})
WARN engine angular-cli-github-pages@0.2.0: wanted: {"node":">= 4.1.0"} (current: {"node":"0.10.32","npm":"2.14.10"})
Installed packages for tooling via npm.
PS C:\code> cd .\RegexByExample
PS C:\code\RegexByExample> ls


    Directory: C:\code\RegexByExample


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         1/28/2016  12:00 PM            node_modules
d----         1/28/2016  11:59 AM            src
-a---         1/28/2016  11:59 AM        246 .gitignore
-a---         1/28/2016  11:59 AM        200 ember-cli-build.js
-a---         1/28/2016  11:59 AM       1282 karma-test-shim.js
-a---         1/28/2016  11:59 AM       1365 karma.conf.js
-a---         1/28/2016  11:59 AM        574 package.json

PS C:\code\RegexByExample> ng serve

C:\code\RegexByExample\node_modules\angular-cli-github-pages\lib\commands\deploy.js:50
     return runCommand('git status --porcelain', execOptions).then(stdout => {
                                                                           ^
Unexpected token >
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Class.module.exports.includedCommands (C:\code\RegexByExample\node_modules\angular-cli-github-pages\index.js:9:30
)
    at C:\code\RegexByExample\node_modules\angular-cli\node_modules\ember-cli\lib\models\project.js:393:61
    at Array.forEach (native)
    at Project.addonCommands (C:\code\RegexByExample\node_modules\angular-cli\node_modules\ember-cli\lib\models\project.
js:392:15)
PS C:\code\RegexByExample> ng build

C:\code\RegexByExample\node_modules\angular-cli-github-pages\lib\commands\deploy.js:50
     return runCommand('git status --porcelain', execOptions).then(stdout => {
                                                                           ^
Unexpected token >
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Class.module.exports.includedCommands (C:\code\RegexByExample\node_modules\angular-cli-github-pages\index.js:9:30
)
    at C:\code\RegexByExample\node_modules\angular-cli\node_modules\ember-cli\lib\models\project.js:393:61
    at Array.forEach (native)
    at Project.addonCommands (C:\code\RegexByExample\node_modules\angular-cli\node_modules\ember-cli\lib\models\project.
js:392:15)
PS C:\code\RegexByExample>
```

**Comment by bignis** [comment]
It occurred to me that maybe my Node version is too stale.

```
PS C:\code\RegexByExample> node -v
v0.10.32
```

So I installed the latest

```
PS C:\code\RegexByExample> node -v
v4.2.6
```

and all good now

```
PS C:\code\RegexByExample> ng serve
version: 1.13.13
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```

**Comment by filipesilva** [comment]
Glad you were able to sort it! If you run into other problems please let us
know.
