### ISSUE TITLE
Ivy build error - Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by jkyoutsey** [angular/angular-cli#15637]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [x ] build
- [x ] serve
```

### Is this a regression?
Did not happen pre-Ivy

### Description
On ng build or ng serve get a compilation error from TypeScript.

## 🔬 Minimal Reproduction
This is in a large, private application.  Can't reproduce because the error message doesn't reveal where in the code the problem is occurring.

## 🔥 Exception or Error
<pre><code>
ERROR in TypeError: Cannot read property 'kind' of undefined
    at isParameterPropertyDeclaration (/myApp/node_modules/typescript/lib/typescript.js:13412:88)
    at Object.filter (/myApp/node_modules/typescript/lib/typescript.js:476:25)
    at transformClassMembers (/myApp/node_modules/typescript/lib/typescript.js:70699:20)
    at createClassDeclarationHeadWithoutDecorators (/myApp/node_modules/typescript/lib/typescript.js:70551:110)
    at visitClassDeclaration (/myApp/node_modules/typescript/lib/typescript.js:70470:19)
    at visitTypeScript (/myApp/node_modules/typescript/lib/typescript.js:70318:28)
    at visitorWorker (/myApp/node_modules/typescript/lib/typescript.js:70113:24)
    at sourceElementVisitorWorker (/myApp/node_modules/typescript/lib/typescript.js:70138:28)
    at saveStateAndInvoke (/myApp/node_modules/typescript/lib/typescript.js:70051:27)
    at sourceElementVisitor (/myApp/node_modules/typescript/lib/typescript.js:70123:20)
    at visitNodes (/myApp/node_modules/typescript/lib/typescript.js:67637:48)
    at Object.visitLexicalEnvironment (/myApp/node_modules/typescript/lib/typescript.js:67670:22)
    at visitSourceFile (/myApp/node_modules/typescript/lib/typescript.js:70407:53)
    at saveStateAndInvoke (/myApp/node_modules/typescript/lib/typescript.js:70051:27)
    at transformSourceFile (/myApp/node_modules/typescript/lib/typescript.js:70033:27)
    at transformSourceFileOrBundle (/myApp/node_modules/typescript/lib/typescript.js:70013:20)
    at transformation (/myApp/node_modules/typescript/lib/typescript.js:85816:24)
    at transformRoot (/myApp/node_modules/typescript/lib/typescript.js:85836:82)
    at Object.map (/myApp/node_modules/typescript/lib/typescript.js:507:29)
    at Object.transformNodes (/myApp/node_modules/typescript/lib/typescript.js:85823:30)
    at emitJsFileOrBundle (/myApp/node_modules/typescript/lib/typescript.js:86329:32)
    at emitSourceFileOrBundle (/myApp/node_modules/typescript/lib/typescript.js:86282:13)
    at forEachEmittedFile (/myApp/node_modules/typescript/lib/typescript.js:86062:34)
    at Object.emitFiles (/myApp/node_modules/typescript/lib/typescript.js:86263:9)
    at emitWorker (/myApp/node_modules/typescript/lib/typescript.js:92213:33)
    at /myApp/node_modules/typescript/lib/typescript.js:92174:66
    at runWithCancellationToken (/myApp/node_modules/typescript/lib/typescript.js:92264:24)
    at Object.emit (/myApp/node_modules/typescript/lib/typescript.js:92174:20)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-next.5
Node: 10.16.0
OS: darwin x64
Angular: 9.0.0-next.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.5
@angular-devkit/build-angular     0.900.0-next.5
@angular-devkit/build-optimizer   0.900.0-next.5
@angular-devkit/build-webpack     0.900.0-next.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        9.0.0-next.5
@angular/cdk                      8.2.0
@angular/cli                      9.0.0-next.5
@angular/material                 8.2.0
@angular/pwa                      0.900.0-next.5
@ngtools/webpack                  9.0.0-next.5
@schematics/angular               9.0.0-next.5
@schematics/update                0.900.0-next.5
rxjs                              6.5.3
typescript                        3.6.3
webpack                           4.40.2
</code></pre>

**Comment by clydin** [comment]
TypeScript 3.6 is not yet supported.  Can you try downgrading to 3.5.x?

**Comment by jkyoutsey** [comment]
That was it, @clydin. Thank you!
