### ISSUE TITLE
Create a component after installation using the CLI breaks the application completely

### ISSUE THREAD

**Issue by iainplimmer** [angular/angular-cli#1564]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Mac OSX - El capitan

2. Versions. Please run `ng --version`. 

4.4.3

3. Repro steps. 

Create a new app with the CLI, type 'ng serve' then create a new component with 'ng g component my-header' you will find that the application no longer runs.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Build error

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/iainplimmer/git/IainPlimmer/tmp/broccoli_type_script_compiler-input_base_path-huodGnWg.tmp/0/src/app/my-header/my-header.component.spec.ts (5, 10): Module '"/Users/iainplimmer/git/IainPlimmer/node_modules/@angular/core/testing"' has no exported member 'addProviders'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/lib/broccoli/angular2-app.js:331:18)
    at Angular2App._buildTree (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/lib/broccoli/angular2-app.js:124:23)
    at new Angular2App (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/iainplimmer/git/IainPlimmer/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/iainplimmer/git/IainPlimmer/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by iainplimmer** [comment]
Unable to recreate after reinstallation
