### ISSUE TITLE
ng test hangs because of "TypeError: Cannot read property 'success' of undefined'"

### ISSUE THREAD

**Issue by rsryanstephen** [angular/angular-cli#15677]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 People have been experiencing this in CLI v7.3.7 upwards, but we don't know if the bug was introduced only by that version or before it. 

### Description

 A clear and concise description of the problem...
when running ng test in a local angular project, Chrome Browser for karma fails to launch, first providing the error: 
`Error: ENOENT: no such file or directory, open '[local project address]\node_modules\jquery\dist\jquery.min.js'`

We should not need to install jquery for angular testing surely?

Chrome then hangs while attempting to start, eventually throwing:
`ERROR [launcher]: Chrome failed 2 times (timeout). Giving up`

With the following flushed error:
`Cannot read property 'success' of undefined
TypeError: Cannot read property 'success' of undefined
    at TestCommand.runSingleTarget (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@angular\cli\models\packages\angular\cli\models\architect-command.ts:242:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

## 🔬 Minimal Reproduction

I can create my own reproduction repo when I get a chance, but for now you can use rcollette's reproduction [here](https://github.com/angular/angular-cli/issues/14118):

The basic reproduction steps are to use concurrently to run `ng test` and then `process.exit(1)` in another concurrently run task after the tests have started to run.

Please run `npm run demo` in this reproduction.
https://github.com/rcollette/ngcli-test-sigterm-demo

Keep in mind that the timeout in sigterm.js may need to be adjusted. On my machine 10s was enough time to get the tests started but before they finish.

## 🔥 Exception or Error
You can refer to the details of the exception in the first [report of this issue](https://github.com/angular/angular-cli/issues/14118), but I will also post mine here:
<pre><code>

ng test
 10% building 2/2 modules 0 active26 09 2019 05:07:54.148:WARN [karma]: No captured browser, open http://localhost:9876/
26 09 2019 05:07:54.201:INFO [karma-server]: Karma v4.3.0 server started at http://0.0.0.0:9876/
26 09 2019 05:07:54.202:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
26 09 2019 05:07:54.207:INFO [launcher]: Starting browser Chrome        92% additional asset processing scripts-webpack-plugin× ｢wdm｣: Error: ENOENT: no such file or directory, open 'C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\jquery\dist\jquery.min.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Storage.provideSync (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.readFileSync (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:259:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\webpack-input-host.ts:40:43)
    at Observable._trySubscribe (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@ngtools\webpack\node_modules\rxjs\src\internal\Observable.ts:224:19)
    at Observable.subscribe (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@ngtools\webpack\node_modules\rxjs\src\internal\Observable.ts:205:14)
    at SyncDelegateHost._doSyncCall (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@angular-devkit\core\src\virtual-fs\host\packages\angular_devkit\core\src\virtual-fs\host\sync.ts:40:16)
    at SyncDelegateHost.read (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@angular-devkit\core\src\virtual-fs\host\packages\angular_devkit\core\src\virtual-fs\host\sync.ts:71:17)
    at WebpackCompilerHost.readFileBuffer (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\compiler_host.ts:165:38)
    at VirtualFileSystemDecorator.readFile (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\virtual_file_system_decorator.ts:47:55)
    at Promise (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\packages\angular_devkit\build_angular\src\angular-cli-files\plugins\scripts-webpack-plugin.ts:115:39)
    at new Promise (<anonymous>)
    at scripts.map.fullPath (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\packages\angular_devkit\build_angular\src\angular-cli-files\plugins\scripts-webpack-plugin.ts:114:16)
    at Array.map (<anonymous>)
    at hook (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\packages\angular_devkit\build_angular\src\angular-cli-files\plugins\scripts-webpack-plugin.ts:113:37)
    at compilation.hooks.additionalAssets.tapAsync (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\packages\angular_devkit\build_angular\src\angular-cli-files\plugins\scripts-webpack-plugin.ts:49:44)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\webpack\lib\Compilation.js:1307:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\webpack\lib\Compilation.js:1244:27)
    at hooks.make.callAsync.err (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\webpack\lib\Compiler.js:624:17)
    at _done (eval at create (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err2 (eval at create (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:48:22)
    at _addModuleChain (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\webpack\lib\Compilation.js:1095:12)
    at processModuleDependencies.err (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\webpack\lib\Compilation.js:1007:9)
26 09 2019 05:08:54.209:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
26 09 2019 05:08:54.320:INFO [launcher]: Trying to start Chrome again (1/2).
26 09 2019 05:09:54.323:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
26 09 2019 05:09:54.429:INFO [launcher]: Trying to start Chrome again (2/2).
26 09 2019 05:10:54.432:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
26 09 2019 05:10:54.599:ERROR [launcher]: Chrome failed 2 times (timeout). Giving up.

Cannot read property 'success' of undefined
TypeError: Cannot read property 'success' of undefined
    at TestCommand.runSingleTarget (C:\Bitbucket2\exporter\homestead-exporter-exporterplus\node_modules\@angular\cli\models\packages\angular\cli\models\architect-command.ts:242:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.9
Node: 8.9.4
OS: win32 x64
Angular: 7.2.14
... animations, common, compiler, core, http, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/compiler-cli             7.2.15
@angular/forms                    7.2.15
@angular/language-service         7.2.13
@angular/material                 7.3.7
@angular/pwa                      0.12.4
@angular/service-worker           7.2.15
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by rsryanstephen** [comment]
Hi Alan,

I upgraded to Angular CLI 8.1 and the problem persists, perhaps I should
provide my own reproduction, rather than referring to rcollette's.. will
get to that soon.

**Comment by rsryanstephen** [comment]
I'm struggling to reproduce it in another project. It looks as though the initial error complains that jquery is missing.. which is very strange. 

So far `ng test` works in our project if jquery and bootstrap are installed, but not otherwise.
Still looking for what might be causing this.

**Comment by rsryanstephen** [comment]
Ok

**Comment by alan-agius4** [comment]
@rsryanstephen can you kindly provide a reproduction? thanks.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
