### ISSUE TITLE
Build error  The Broccoli Plugin: [Funnel] failed with

### ISSUE THREAD

**Issue by abdellatif05** [angular/angular-cli#1577]
NPM: 3.9.2
angular-cli: 1.0.0-beta.10
node: 6.2.0
os: linux x64

I am trying to put my application in production using "sudo ng serve", but i get this error:

Build error

The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory: typings
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at new Funnel (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/lib/broccoli/angular2-app.js:93:7)
    at new Angular2App (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (/home/toufa/workspaceEcommerce/dev/client/a2todos/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/toufa/workspaceEcommerce/dev/client/a2todos/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by filipesilva** [comment]
Seems like there was a problem with installing `typings`. Try running `npm run typings install`.

As a note, the webpack branch does not need `typings` anymore.

**Comment by archae0pteryx** [comment]
I'm getting an error that no script is installed when trying your method filipesilva

```
└─(12:25:53 on master ✹)──> npm run typings install                                                                                                 1 ↵ ──(Sun,Sep11)─┘
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/xenu/.nvm/versions/node/v6.5.0/bin/node" "/home/xenu/.nvm/versions/node/v6.5.0/bin/npm" "run" "typings" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! missing script: typing
```

I have also tried several other methods to no avail. . . (angular noob)
