### ISSUE TITLE
router compiling issue

### ISSUE THREAD

**Issue by Abubarrett** [angular/angular-cli#1584]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Max OsX - El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.9
node: 6.3.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
it was created with CLI

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Error: Typescript found the following errors:
  /Applications/MAMP/htdocs/heelum/tmp/broccoli_type_script_compiler-input_base_path-IazOFtA6.tmp/0/src/app/views/home/home.component.spec.ts (17, 21): Supplied parameters do not match any signature of call target.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/lib/broccoli/angular2-app.js:329:18)
    at Angular2App._buildTree (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/lib/broccoli/angular2-app.js:124:23)
    at new Angular2App (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Applications/MAMP/htdocs/heelum/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at /Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/angular-cli/lib/commands/build.js:32:24
    at lib$rsvp$$internal$$tryCatch (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Applications/MAMP/htdocs/heelum/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

5. Mention any other details that might be useful.

ok so I'm using a simple (click) event that waits a bit (timeout) and then routes to some other part of my app 

TimerWrapper.setTimeout(() => {
    this.router.navigate(['/trabajo']);
}, 1000);

the weird part is that IT DOES WORK but not the first time i input 'ng serve' into the terminal, it gives me that error, it is pretty much about the router, "Supplied parameters do not match any signature of call target." but if I remove the code in my constructor: constructor(private router: Router) and also of course the line "this.router.navigate(['/trabajo']);" and THEN run ng serve, the cli compiles it, once the compiler is running, I cmd+z my code back and then it does work perfectly fine, my only issue is of course i cant build my application becasue the first time it tries to compile, I get that error. I hope I explained the issue correctly, any help is apreciated, thank you very much!
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Abubarrett** [comment]
Edit: error got fixed when upgraded to beta 11 with webpack :)
