### ISSUE TITLE
AOT compilation failing with computed object properties 

### ISSUE THREAD

**Issue by peteboere** [angular/angular-cli#15848]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes 8.0.x AOT compiled without errors

### Description

Compiling AOT bundle fails following the log message:
Generating ES5 bundles for differential loading...

Break seems to be caused by computed properties. Works OK with JIT compile.

## 🔬 Minimal Reproduction

With a simple component the following computed property breaks the build:

<pre><code>@Component({
    selector: 'auth',
    templateUrl: 'component.html',
})
export class AuthComponent {

    error(error: any) {

        let {message='Some problem there was'} = error;

        const {active, inactive, unverified} = &lt;any&gt;{[error.message]: true};
        
        if (active || inactive || unverified) {
            message = `An account is already registered with this email. Please Log In`;
        }
    }
}
</code></pre>

## 🔥 Exception or Error
<pre><code>Generating ES5 bundles for differential loading...
An unhandled exception occurred: Cannot read property 'name' of undefined
> cat error.log
TypeError: Cannot read property 'name' of undefined
    at getObjectLiteralIndexInfo ([...]/test/node_modules/typescript/lib/typescript.js:49193:90)
    at createObjectLiteralType ([...]/test/node_modules/typescript/lib/typescript.js:49360:67)
    at checkObjectLiteral ([...]/test/node_modules/typescript/lib/typescript.js:49357:20)
    at checkExpressionWorker ([...]/test/node_modules/typescript/lib/typescript.js:53943:28)
    at checkExpression ([...]/test/node_modules/typescript/lib/typescript.js:53878:38)
    at checkExpressionCached ([...]/test/node_modules/typescript/lib/typescript.js:53617:38)
    at getTypeOfExpression ([...]/test/node_modules/typescript/lib/typescript.js:53855:28)
    at checkDeclarationInitializer ([...]/test/node_modules/typescript/lib/typescript.js:53628:24)
    at getTypeForVariableLikeDeclaration ([...]/test/node_modules/typescript/lib/typescript.js:36093:28)
    at getTypeForBindingElementParent ([...]/test/node_modules/typescript/lib/typescript.js:35828:61)
    at checkVariableLikeDeclaration ([...]/test/node_modules/typescript/lib/typescript.js:56088:34)
    at checkBindingElement ([...]/test/node_modules/typescript/lib/typescript.js:56223:20)
    at checkSourceElementWorker ([...]/test/node_modules/typescript/lib/typescript.js:58263:28)
    at checkSourceElement ([...]/test/node_modules/typescript/lib/typescript.js:58119:17)
    at Object.forEach ([...]/test/node_modules/typescript/lib/typescript.js:280:30)
    at checkVariableLikeDeclaration ([...]/test/node_modules/typescript/lib/typescript.js:56107:20)
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 8.3.9
Node: 10.16.0
OS: darwin x64
Angular: 8.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.9
@angular-devkit/build-angular     0.803.9
@angular-devkit/build-optimizer   0.803.9
@angular-devkit/build-webpack     0.803.9
@angular-devkit/core              8.3.9
@angular-devkit/schematics        8.3.9
@angular/cli                      8.3.9
@ngtools/webpack                  8.3.9
@schematics/angular               8.3.9
@schematics/update                0.803.9
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**
Build command:
<pre><code>ng build test --aot --build-optimizer --extract-css=false --extract-licenses=false --output-hashing=none --output-path='./dist' --prod --vendor-chunk=false
</code></pre>

**Comment by alan-agius4** [comment]
@peteboere looking at your code, the problematic part is the following;

```ts
  let {message='Some problem there was'} = error;
const {active, inactive, unverified} = <any>{[error.message]: true};
```

You are casing `{[error.message]: true}` to `any` and hence when doing the first ES2015 build TypeScript is ignoring what's on the right side. However during down-levelling or when build optimizer is run it is trying to resolve the properties `active`, `inactive` and `unverified`. which is failing because they cannot determine by statically analysing the code.

A safer way to write this code which doesn't require to bypass TSC typechecking and doesn't break during TypeScript's parsing would be something along;

```ts
  let {message='Some problem there was'} = error;
  if (['active', 'inactive', 'unverified'].includes(message)) {
      message = `An account is already registered with this email. Please Log In`;
  }
```

**Comment by peteboere** [comment]
@alan-agius4 Thanks, I have a workaround in place for our project.

This is still valid code though, works in 8.0.x and JIT compile.  My goal with this particular example wasn't type safety.  I was (perhaps incorrectly) expecting to be able to use the same technique in Typescript that I can with regular JS.

**Comment by alan-agius4** [comment]
Type-checking is still required in some parts during the build pipeline. Such as downleveling and build optimization (which are used during a prod build). Typescript doesn’t offer a way to disable this and thus this is not actionable by us.

While the above is indeed valid JS code, the transpilled version of it is not a valid input for TypeScript and will cause the TypeScript compiler to crash.

Seeing that there is a workaround which also offers better type safety I am going to close the issue.

Thanks.
