### ISSUE TITLE
Error: The 'ivy-ngcc' command was renamed to just 'ngcc'. Please update your usage.

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#15850]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
```

### Is this a regression?
Yes, worked with the previous .next release of Angular.

## 🔬 Minimal Reproduction
yarn global add @angular/cli@next
ng new my-app

## 🔥 Exception or Error
```Error: The 'ivy-ngcc' command was renamed to just 'ngcc'. Please update your usage.
    at Object.<anonymous> (/super/workspace/stephenfluin/my-app/node_modules/@angular/compiler-cli/ngcc/main-ivy-ngcc.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
Package install failed, see above.
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-next.9
Node: 12.12.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    <error>
@angular-devkit/core         9.0.0-next.9
@angular-devkit/schematics   9.0.0-next.9
@schematics/angular          <error>
@schematics/update           <error>
rxjs                         6.5.3

</code></pre>

**Comment by alan-agius4** [comment]
Fixed by https://github.com/angular/angular-cli/pull/15837
