### ISSUE TITLE
[schematics] Cannot read property 'schematic' of undefined

### ISSUE THREAD

**Issue by xxyyzz2050** [angular/angular-cli#15957]
I have made a simple schematics that executes 2 tasks: init, app

just to simplify the issue, the only thing that `init` does is to run `app` schematic several times (so I need to chain them), which actually does nothing and just returns the tree as it

 i.e: returns schematic("app",{}) 

but when I try to run `schematics .:init` I face the following error
```
TypeError: Cannot read property 'schematic' of undefined
```

collection.json
```
{
  "$schema": "../../../node_modules/@angular-devkit/schematics/collection-schema.json",
  "schematics": {
    "init": {
      "description": "init",
      "factory": "./#init"
    },
    "app": {
      "description": "app",
      "factory": "./#app"
    }
  }
}
```

index.js
```
const {
  schematic,
  branchAndMerge,
  chain,
  mergeWith,
  apply,
  url,
  template,
  move
} = require("@angular-devkit/schematics");

function init(options) {
  return (tree, context) => {
    var rules = chain([
      //  apply(url("./files"), [template(options), move("./app")]),
      schematic("app", {}) //without this line it works
    ]);

    //return mergeWith(rules); //also dosen't work
    return chain([branchAndMerge(chain([mergeWith(rules)]))]);
  };
}

function app(options) {
  console.log("====app===="); //not called !!!
  return (tree, context) => {
    return tree;
  };
}

exports.init = init;
exports.app = app;
```

error in details:
```
>schematics .:init

An error occured:
TypeError: Cannot read property 'schematic' of undefined
    at node_modules\@angular-devkit\schematics\src\rules\schematic.js:37:36
    at MergeMapSubscriber.pipe.operators_1.mergeMap.inputTree [as project] (node_modules\@angular-devkit\schematics\src\rules\call.js:74:24)
    at MergeMapSubscriber._tryNext (node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (node_modules\rxjs\internal\observable\scalar.js:6:20)
    at Observable._trySubscribe (node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (node_modules\rxjs\internal\Observable.js:30:22)
    at MergeMapOperator.call (node_modules\rxjs\internal\operators\mergeMap.js:39:23)
    at Observable.subscribe (node_modules\rxjs\internal\Observable.js:25:31)
```

**Comment by xxyyzz2050** [comment]
[solved]

    var rules = chain([
      mergeWith(apply(url("./files"), [template(options), move("./app")])),
      mergeWith(apply(url("./files"), [template(options), move("./app2")])),
      schematic("app", {}) 
    ]);

    return rules;
