### ISSUE TITLE
@angular-devkit/build-angular: 0.900.0-next.18 results in sass @import error

### ISSUE THREAD

**Issue by the-ult** [angular/angular-cli#15982]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
`"@angular-devkit/build-angular": "0.803.13"`

### Description
Running `npm run affected:build ..` results in sass partials not being found

## 🔬 Minimal Reproduction
Checkout: https://gitlab.com/ultimate-solutions/ultimate-nx-starter-workspace/tree/sample/angular-9-sass-partial-errors

```
npm run affected:build --  --parallel --prod --all
```

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/styles.scss
Module build failed (from /home/the_ult/dev/ult-starter-workspace/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from /home/the_ult/dev/ult-starter-workspace/node_modules/sass-loader/lib/loader.js):

@import 'theme.global'; 
       ^
      Can't find stylesheet to import.
  ╷
4 │ @import 'theme.global'; 
  │         ^^^^^^^^^^^^^^
  ╵
  stdin 4:9  root stylesheet
      in /home/the_ult/dev/ult-starter-workspace/apps/frontend-with-graphql/src/styles.scss (line 4, column 9)
    at /home/the_ult/dev/ult-starter-workspace/node_modules/webpack/lib/NormalModule.js:313:20
    at /home/the_ult/dev/ult-starter-workspace/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/the_ult/dev/ult-starter-workspace/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/the_ult/dev/ult-starter-workspace/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/the_ult/dev/ult-starter-workspace/node_modules/sass-loader/lib/loader.js:90:7
    at Function.call$2 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:54306:16)
    at _render_closure1.call$2 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:33504:12)
    at _RootZone.runBinary$3$3 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:19820:18)
    at _RootZone.runBinary$3 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:19824:19)
    at _FutureListener.handleError$1 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:18289:19)
    at _Future__propagateToListeners_handleError.call$0 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:18577:40)
    at Object._Future__propagateToListeners (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:3484:88)
    at _Future._completeError$2 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:18413:9)
    at _AsyncAwaitCompleter.completeError$2 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:17812:12)
    at Object._asyncRethrow (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:3240:17)
    at /home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:10541:20
    at _wrapJsFunctionForAsync_closure.$protected (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:3263:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:17833:12)
    at _awaitOnObject_closure0.call$2 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:17825:25)
    at _RootZone.runBinary$3$3 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:19820:18)
    at _RootZone.runBinary$3 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:19824:19)
    at _FutureListener.handleError$1 (/home/the_ult/dev/ult-starter-workspace/node_modules/sass/sass.dart.js:18289:19)
 @ multi ./src/styles.scss styles[0]
</code></pre>

`_theme.global.scss` is located in `libs/styles/src/lib/_theme.global.scss`

`angular.json`
```
"frontend-with-graphql"{
....
  "stylePreprocessorOptions": {
     "includePaths": ["libs/styles/src/lib"]
  },
...
}
```
`apps/frontend-with-graphql/src/lstyles.scss`
```
@import 'theme.global';
```

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-next.18
Node: 12.9.1
OS: linux x64
Angular: 9.0.0-next.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.3  # Shouldn't this be  0.900.0-next.18 as well?
@angular-devkit/build-angular     0.900.0-next.18
@angular-devkit/build-optimizer   0.900.0-next.18
@angular-devkit/build-webpack     0.900.0-next.18
@angular-devkit/core              9.0.0-next.18
@angular-devkit/schematics        8.3.3
@angular/cdk                      8.2.3
@angular/cli                      9.0.0-next.18
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-next.18
@schematics/angular               8.3.3
@schematics/update                0.900.0-next.18
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.39.2
-----------------------------------------------------------

"@nrwl/angular": "8.7.0",
"@nrwl/express": "8.7.0",
"@nrwl/cypress": "8.7.0",
"@nrwl/eslint-plugin-nx": "8.7.0",
"@nrwl/jest": "8.7.0",
"@nrwl/node": "8.7.0",
"@nrwl/workspace": "8.7.0",

</code></pre>

**Anything else relevant?**
Above error could be something to do with NX (as well), but the second error (@see comment below) seems to be a Angular CLI issue

- using `"sass": "1.23.1",` 
- Also without `"sass": "1.23.1",` results in the same error

@see https://github.com/angular/angular-cli/issues/15975#issuecomment-547641861

**Comment by clydin** [comment]
It does appear that this is very related to the other issue and has the same root cause.

**Comment by clydin** [comment]
There appears to be several issues involved in this situation.
* The `TypeError: compilation.getAsset is not a function` error will be resolved for the official Angular builders in the next RC.
* The mismatched versions appear to be a result of the version of nx used not yet supporting 9.0.  Once there is a version of nx with official support this should no longer present a problem.  If you continue to experience problems after an update of nx, please re-open issue.
