### ISSUE TITLE
Library schematic does not support path property

### ISSUE THREAD

**Issue by CobusKruger** [angular/angular-cli#16080]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [X] schematics
```

### Is this a regression?

Not as far as I know

### Description

I tried to create a schematic that generates an application and adds a library to it. However, the library schematic does not accept a path as parameter and it then attempts to create the library in the folder that contains the application. Specifically, it tries to read the `angular.json` file from the folder containing the application folder (e.g. the folder where the schematic is run).

## 🔬 Minimal Reproduction

A minimal reproduction may be found [in this repo](https://github.com/CobusKruger/AngularProjectMergeIssues).

It also addresses a problem I had when trying to work around this with `applyToSubtree`.

Here is the simplest description I could come up with.

Given this factory:

```typescript
export function createProject(_options: any): Rule {
  return (_tree: Tree, _context: SchematicContext) => {
    return chain([
      externalSchematic('@schematics/angular', 'ng-new', optionsNew),
      externalSchematic('@schematics/angular', 'library', optionsLib)
    ]);
  };
}
```

If you execute the schematic in a folder named `/parent/folder` and the app generates in a new folder named app (`/parent/folder/app`), the library schematic searches for the `angular.json` in `/parent/folder` instead of `/parent/folder/app`.

## 🔥 Exception or Error
```
An error occured:
Error: Unable to locate a workspace file for workspace path.
    at Object.readWorkspace (C:\dev\scratchpad\scaffolding-tests\node_modules\@angular-devkit\core\src\workspace\core.js:74:19)
    at async Object.getWorkspace (C:\dev\scratchpad\scaffolding-tests\node_modules\@schematics\angular\utility\workspace.js:51:27)
    at async C:\dev\scratchpad\scaffolding-tests\node_modules\@schematics\angular\library\index.js:153:27
```

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.1
Node: 12.12.0
OS: win32 x64
Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.1 (cli-only)
@angular-devkit/core         8.3.17
@angular-devkit/schematics   8.3.17
@schematics/angular          8.3.1 (cli-only)
@schematics/update           0.803.1 (cli-only)
rxjs                         6.4.0
typescript                   3.5.3
</code></pre>

**Comment by BrianMikinski** [comment]
I'm bumping into the same issue for any schematic dev work trying to use the Angular Schematics config getWorkspacePath method - they'r blowing up in test runs and dev work no matter what work arounds I try to implement

**Comment by ActJV** [comment]
+1

**Comment by d-koppenhagen** [comment]
Same here.
I think the problem is that after running `externalSchematic('@schematics/angular', 'ng-new', optionsNew)`, the workspace is just present as a virtual tree and not entered. So the next `Rule` can't determine that it's in a valid Angular workspace. Is there a way to tell the schematics, to either:
- enter the target workspace within the virtual representation and use this as new base
- save the changes made by `externalSchematic('@schematics/angular', 'ng-new', optionsNew)` from virtual tree to the file system and then run the next `Rule` afterwards?

**Comment by maguilarl** [comment]
I have the same problem, any update?
