### ISSUE TITLE
9.0.0 rc0,1 getting error spawnSync yarn ENOENT

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular-cli#16115]
command
ng add @angular/material
ng add @angular/pwa

error details
[error] Error: spawnSync yarn ENOENT
Package install failed, see above.
    at Object.installPackage (C:\keatkeat\projects\testd\node_modules\@angular\cli\tasks\install-package.js:39:15)
    at AddCommand.run (C:\keatkeat\projects\testd\node_modules\@angular\cli\commands\add-impl.js:141:31)
    at async AddCommand.validateAndRun (C:\keatkeat\projects\testd\node_modules\@angular\cli\models\command.js:134:28)
    at async Object.runCommand (C:\keatkeat\projects\testd\node_modules\@angular\cli\models\command-runner.js:201:24)
    at async default_1 (C:\keatkeat\projects\testd\node_modules\@angular\cli\lib\cli\index.js:54:31)

work perfect when I try version 8.3.18.

Can you please provide the output of ng version

Angular CLI: 9.0.0-rc.1
Node: 12.3.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.1
@angular-devkit/core         9.0.0-rc.1
@angular-devkit/schematics   9.0.0-rc.1
@schematics/angular          9.0.0-rc.1
@schematics/update           0.900.0-rc.1
rxjs                         6.5.3

**Comment by alan-agius4** [comment]
Should be fixed by https://github.com/angular/angular-cli/pull/16112

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?
