### ISSUE TITLE
Webpack returns an error when building app-shell on threejs example imports in angular

### ISSUE THREAD

**Issue by Matthbo** [angular/angular-cli#16175]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 I don't think so
Tested on 7, upgrade to 8 didn't fix it

### Description

 Building angular app-shell using <code>ng run my-app:app-shell</code> breaks when importing <code>{ OrbitControls } from 'three/examples/jsm/controls/OrbitControls';</code>

This error doesn't occur when using ng build [--prod] or ng serve

## 🔬 Minimal Reproduction

Create a new angular 7(!) project
```
npm i -g @angular/cli@7
ng new my-app --routing
```

Update package.json to use these packages
```
"dependencies": {
    "@agm/core": "^1.0.0",
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/platform-server": "~7.2.0",
    "@angular/pwa": "^0.12.4",
    "@angular/router": "~7.2.0",
    "@angular/service-worker": "~7.2.0",
    "@asymmetrik/ngx-leaflet": "^5.0.2",
    "core-js": "^2.6.10",
    "hammerjs": "^2.0.8",
    "leaflet": "^1.5.1",
    "ngx-material-timepicker": "^3.3.1",
    "rxjs": "~6.3.3",
    "stats.js": "^0.17.0",
    "three": "^0.109.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.9",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "~8.9.4",
    "@types/offscreencanvas": "^2019.6.0",
    "@types/stats.js": "^0.17.0",
    "@types/googlemaps": "^3.38.0",
    "@types/leaflet": "^1.5.5",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
```

Update src/tsconfig.app.json
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": [
      "offscreencanvas",
      "googlemaps"
    ]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

Install new dependencies, create the app-shell & component that uses ThreeJS
```
npm install
ng generate app-shell --client-project my-app --universal-project server-app
ng g c three --module app
```

Add ThreeComponent to routes in app-routing.module.ts
```
import { ThreeComponent } from './three/three.component';

const routes: Routes = [
  { path: '/three', component: ThreeComponent }
];
```

Update ThreeComponent
```
import { Component, OnInit, ViewChild, ElementRef, OnDestroy, AfterViewInit } from '@angular/core';

import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';

@Component({
  selector: 'app-three',
  templateUrl: './three.component.html',
  styleUrls: ['./three.component.scss']
})
export class ThreeComponent implements OnInit {

  public scene: THREE.Scene;
  public camera: THREE.PerspectiveCamera;
  private renderer: THREE.WebGLRenderer;
  public orbitControls: OrbitControls;
  private nextFrameId: number;
  private clock: THREE.Clock;

  constructor() {
    // Renderer
    this.renderer = new THREE.WebGLRenderer({
      antialias: true,
      logarithmicDepthBuffer: false,
    });
    this.renderer.gammaOutput = true;
    this.renderer.setSize(1280, 720);
    this.renderer.setPixelRatio( window.devicePixelRatio );
    
    // Camera
    this.camera = new THREE.PerspectiveCamera(50, 1280/720, 0.01, 200);
    this.camera.position.set(46, 30, -15);

    this.orbitControls = new OrbitControls(this.camera, this.renderer.domElement);
    this.orbitControls.enableDamping = true;
    this.orbitControls.dampingFactor = 0.05;
    this.orbitControls.target.set(22, 2, -34);
    this.orbitControls.enableKeys = false;
    this.orbitControls.update();
    
    // Scene
    this.scene = new THREE.Scene();

    // Clock for delta time
    this.clock = new THREE.Clock();

    // Lighting
    const ambientLight: THREE.AmbientLight = new THREE.AmbientLight(0xffffff, 1.0);
    this.scene.add(ambientLight);
  }

  ngOnInit() {
  }

  ngOnDestroy() {
    // Remove event listeners from orbit controls
    this.orbitControls.dispose();
    this.scene = undefined;
  }

}
```

Build the project with app-shell
```
ng run my-app:app-shell
```

## 🔥 Exception or Error
<pre><code>

Unexpected token {
D:\Projects\School\my-app\node_modules\three\examples\jsm\controls\OrbitControls.js:10
import {
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.three/examples/jsm/controls/OrbitControls (D:\Projects\School\my-app\dist\my-app-server\main.js:759:18)       at __webpack_require__ (D:\Projects\School\my-app\dist\my-app-server\main.js:20:30)
    at Module../src/app/three/three.component.ts (D:\Projects\School\my-app\dist\my-app-server\main.js:514:99)
    at __webpack_require__ (D:\Projects\School\my-app\dist\my-app-server\main.js:20:30)
    at Module../src/app/three/three.component.ngfactory.js (D:\Projects\School\my-app\dist\my-app-server\main.js:457:74)    at __webpack_require__ (D:\Projects\School\my-app\dist\my-app-server\main.js:20:30)
    at Module../src/app/app.server.module.ngfactory.js (D:\Projects\School\my-app\dist\my-app-server\main.js:358:90)        at __webpack_require__ (D:\Projects\School\my-app\dist\my-app-server\main.js:20:30)
    at Module../src/main.server.ts (D:\Projects\School\my-app\dist\my-app-server\main.js:598:90)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.9
Node: 10.17.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@angular/pwa                      0.12.4
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by filipesilva** [comment]
We should have this fixed in version 9. Can you try on latest RC release please?

**Comment by Matthbo** [comment]
Building app-shell using version 9 works
It looks like tsconfig.server.json now has `"module": "commonjs"` which I guess fixes the issue?

**Comment by Matthbo** [comment]
Correction, `"module": "commonjs"` didn't fix the issue

**Comment by alan-agius4** [comment]
In version 9, we set bundleDependencies to all by default with this, the es import statements will be change to webpack imports.

Setting the above mentioned setting might work in Angular 7 but it’s not guaranteed as it depends on your dependencies.

**Comment by Matthbo** [comment]
I set bundleDependencies to all, but now I get this error
```
Cannot read property 'subscribe' of undefined
TypeError: Cannot read property 'subscribe' of undefined
    at new ApplicationRef (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:84234:41)          at _createClass (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:87473:24)
    at initNgModule (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:87368:36)
    at new NgModuleRef_ (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:88095:13)            at createNgModuleRef (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:88084:16)           at Object.debugCreateNgModuleRef [as createNgModuleRef] (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:89915:16)
    at NgModuleFactory_.create (D:\Projects\School\project c\Front-end\dist\projectc-front-end-server\main.js:90619:29)     at D:\Projects\School\project c\Front-end\node_modules\@angular\core\bundles\core.umd.js:17810:47
    at ZoneDelegate.invoke (D:\Projects\School\project c\Front-end\node_modules\zone.js\dist\zone-node.js:391:26)           at Object.onInvoke (D:\Projects\School\project c\Front-end\node_modules\@angular\core\bundles\core.umd.js:17344:37)     at ZoneDelegate.invoke (D:\Projects\School\project c\Front-end\node_modules\zone.js\dist\zone-node.js:390:52)           at Zone.run (D:\Projects\School\project c\Front-end\node_modules\zone.js\dist\zone-node.js:150:43)
    at NgZone.run (D:\Projects\School\project c\Front-end\node_modules\@angular\core\bundles\core.umd.js:17258:32)          at PlatformRef.bootstrapModuleFactory (D:\Projects\School\project c\Front-end\node_modules\@angular\core\bundles\core.umd.js:17808:27)
    at renderModuleFactory (D:\Projects\School\project c\Front-end\node_modules\@angular\platform-server\bundles\platform-server.umd.js:1032:43)
``` 
Which is strange because `ng build` & `ng serve` works correctly, even `ng run my-app:server` works

**Comment by alan-agius4** [comment]
I think that was one of the issues that was solved in version 9.

**Comment by Matthbo** [comment]
I'll close this issue since there isn't a solid solution for angular 7
