### ISSUE TITLE
Error: unable to serve upgraded Angular 9.0.0-rc.2 app

### ISSUE THREAD

**Issue by Edouardbozon** [angular/angular-cli#16207]
Hi there :raised_hand_with_fingers_splayed: 

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, I'm able to serve the previous version Angular `8.2.14` and CLI `8.3.19`.

### Description

I would test my app against next version `9.0.0-rc.2`, so I ran the `update --next` command from the CLI. Then when I run the `serve` command the CLI instantly throws an error.

## 🔬 Minimal Reproduction

Here is the [PR](https://github.com/jscutlery/http-ext/pull/62) that bump Angular to `9.0.0-rc.2` and cause the error. The project is a monorepo but only the `sandbox` application is concerned by this issue. 

## 🔥 Exception or Error
Here is the stack trace output from the CLI:

```
[error] Error: Job name "..getProjectMetadata" does not exist.
    at Observable.rxjs_1.Observable [as _subscribe] (/home/edouard/work/http-ext/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/experimental/jobs/simple-scheduler.js:350:23)
    at Observable._trySubscribe (/home/edouard/work/http-ext/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/edouard/work/http-ext/node_modules/rxjs/internal/Observable.js:30:22)
    at Object.subscribeToResult (/home/edouard/work/http-ext/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)
    at SwitchMapSubscriber._innerSub (/home/edouard/work/http-ext/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/home/edouard/work/http-ext/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/home/edouard/work/http-ext/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/home/edouard/work/http-ext/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/home/edouard/work/http-ext/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/edouard/work/http-ext/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/edouard/work/http-ext/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/home/edouard/work/http-ext/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/edouard/work/http-ext/node_modules/rxjs/internal/Observable.js:30:22)
    at Object.subscribeToResult (/home/edouard/work/http-ext/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)
    at SwitchMapSubscriber._innerSub (/home/edouard/work/http-ext/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/home/edouard/work/http-ext/node_modules/rxjs/internal/operators/switchMap.js:55:14)
```
The stacktrace shows something weird `..getProjectMetadata`, but I have no idea why this path is broken. 

## 🌍 Your Environment

```
node v10.15.3
yarn 1.19.1
```

Note that I'm using Ubuntu.

**Comment by clydin** [comment]
The repository appears too be using `nx`.  However, the version of `nx` used appears to only support Angular CLI 8.x.

**Comment by Edouardbozon** [comment]
Hi @clydin, I opened the issue here because the error appears to come from the `@angular/cli` and as far as I know `nx` just call through the `serve` command from the `@angular/cli`. But if it's just related to `nx` this can be closed or transferred.

**Comment by filipesilva** [comment]
Last time I looked into this error message, the error came from `@angular/cli` because whatever was calling it was using an older version of the CLI libraries and providing context objects of the previous version. So when Angular CLI tries to use them, it fails and throws. I believe this should be fixed by using a version of Nx that is meant to work with Angular CLI version 9.
