### ISSUE TITLE
ng <command> --help does not work

### ISSUE THREAD

**Issue by KissBalazs** [angular/angular-cli#16241]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/cli

### Is this a regression?
not sure. 

### Description
Angular cli commands seems to be working, but the --help flag does not work in them in angular 8. It is suggested in the [documentation](https://angular.io/cli/generate) in [multiple places](https://angular.io/cli#basic-workflow) that it should. 

## 🔬 Minimal Reproduction
(`npm uninstall -g @angular/cli`)
`npm install -g @angular/cli@latest`
`ng generate --help`

## 🔥 Exception or Error
**`forest@forest:~$ ng generate --help`**
<pre>
An unhandled exception occurred: Unable to locate a workspace file for workspace path.
See "/tmp/ng-s4wanw/angular-errors.log" for further details.
</pre>
**`forest@forest:~$ cat /tmp/ng-MYDOue/angular-errors.log`**
<pre>
[error] Error: Unable to locate a workspace file for workspace path.
    at Object.readWorkspace (/home/forest/.nvm/versions/node/v12.3.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/core.js:74:19)
    at async GenerateCommand._loadWorkspace (/home/forest/.nvm/versions/node/v12.3.1/lib/node_modules/@angular/cli/models/schematic-command.js:442:35)
    at async GenerateCommand.initialize (/home/forest/.nvm/versions/node/v12.3.1/lib/node_modules/@angular/cli/models/schematic-command.js:40:9)
    at async GenerateCommand.initialize (/home/forest/.nvm/versions/node/v12.3.1/lib/node_modules/@angular/cli/commands/generate-impl.js:12:9)
    at async GenerateCommand.validateAndRun (/home/forest/.nvm/versions/node/v12.3.1/lib/node_modules/@angular/cli/models/command.js:124:9)
    at async Object.runCommand (/home/forest/.nvm/versions/node/v12.3.1/lib/node_modules/@angular/cli/models/command-runner.js:186:24)
    at async default_1 (/home/forest/.nvm/versions/node/v12.3.1/lib/node_modules/@angular/cli/lib/cli/index.js:54:31)forest@forest:~$ ^C

</pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.19
Node: 12.3.1
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.19
@angular-devkit/core         8.3.19
@angular-devkit/schematics   8.3.19
@schematics/angular          8.3.19
@schematics/update           0.803.19
rxjs                         6.4.0

</code></pre>

**Anything else relevant?**
-

**Comment by alan-agius4** [comment]
We should fix this 😊

**Comment by imrvasishtha** [comment]
Please try to update the docs also because it can create a problem for person like me who is new in angular. Thanks. [cli#basic-workflow](https://angular.io/cli#basic-workflow)

**Comment by kuncevic** [comment]
Oh I believe it is really confused people who just new to angular cli and might be a kinda blocker for some, so this `ng command --help` should just work

**Comment by kuncevic** [comment]
Oh I believe it is really confused people who just new to angular cli and might be a kinda blocker for some, so this `ng command --help` should just work

Here is the list of commands that does not work outside the angular project:

```
ng build --help
ng serve --help
ng test --help
ng e2e --help
ng generate --help
ng add --help
ng lint --help
ng xi18n --help
ng run --help
```

**Comment by kuncevic** [comment]
Oh I believe it is really confused people who just new to angular cli and might be a kinda blocker for some, so this `ng command --help` should just work

Here is the list of commands that does not work outside the angular project https://github.com/angular/angular-cli/issues/19057:

```
ng build --help
ng serve --help
ng test --help
ng e2e --help
ng generate --help
ng add --help
ng lint --help
ng xi18n --help
ng run --help
```
