### ISSUE TITLE
SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 76

### ISSUE THREAD

**Issue by Dok11** [angular/angular-cli#16265]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] e2e

### Description

Command `npm run e2e` doesnt work and throw error into a terminal.
Google Chrome showing for a split second and close immediately. After it terminal show error about chome sessions.

## 🔥 Exception or Error
<pre><code>
$ npm run e2e

> main@0.0.0 e2e \data\main
> ng e2e

[13:35:20] I/update - chromedriver: file exists \data\main\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_76.0.3809.12.zip
[13:35:20] I/update - chromedriver: unzipping chromedriver_76.0.3809.12.zip
[13:35:20] I/update - chromedriver: chromedriver_76.0.3809.12.exe up to date
i ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.37 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 393 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 362 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 764 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 5.32 MB [initial] [rendered]
Date: 2019-11-22T10:35:54.010Z - Hash: d29ac5b8be4de8a4a9c4 - Time: 28877ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Compiled successfully.
[13:35:54] I/launcher - Running 1 instances of WebDriver
[13:35:54] I/direct - Using ChromeDriver directly...
[13:35:55] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 76
  (Driver info: chromedriver=76.0.3809.12 (220b19a666554bdcac56dff9ffd44c300842c933-refs/branch-heads/3809@{#83}),platform=Windows NT 10.0.14393 x86_64)
[13:35:55] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 76
  (Driver info: chromedriver=76.0.3809.12 (220b19a666554bdcac56dff9ffd44c300842c933-refs/branch-heads/3809@{#83}),platform=Windows NT 10.0.14393 x86_64)
    at Object.checkLegacyResponse (\data\main\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (\data\main\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (\data\main\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (\data\main\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (\data\main\node_modules\selenium-webdriver\chrome.js:761:15)
    at Direct.getNewDriver (\data\main\node_modules\protractor\built\driverProviders\direct.js:77:33)
    at Runner.createBrowser (\data\main\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (\data\main\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (\data\main\node_modules\q\q.js:834:54)
    at \data\main\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (\data\main\node_modules\q\q.js:796:13)
    at \data\main\node_modules\q\q.js:556:49
    at runSingle (\data\main\node_modules\q\q.js:137:13)
[13:35:55] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! main@0.0.0 e2e: `ng e2e`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the main@0.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     \npm-cache\_logs\2019-11-22T10_35_56_110Z-debug.log
</code></pre>

## 🌍 Your Environment
<pre><code>
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.2.0
Node: 10.10.0
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.2.0
@angular/cdk                      8.1.4
@ngtools/webpack                  8.1.3
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.35.2
</code></pre>

**Anything else relevant?**

At this moment I dont know what I need to googling? Trouble with chrome, e2e, angular or proptractor? Which direction I should choose?

**Comment by alan-agius4** [comment]
Can you try to run `npx webdriver-manager clean` to remove all downloaded driver files from the directory before running `ng e2e`?

**Comment by Dok11** [comment]
```
$ npx webdriver-manager clean
[14:17:21] I/file_manager - removed chromedriver_76.0.3809.12.exe
[14:17:21] I/file_manager - removed chromedriver_76.0.3809.12.zip
[14:17:21] I/file_manager - removed chrome-response.xml
[14:17:21] I/file_manager - removed update-config.json
```

but error not changed.

**Comment by alan-agius4** [comment]
1. What's your Chrome version?
2. What's your `webdriver-manager` version? `npm ls webdriver-manager`

If you're Chrome version is greater than 76 you need `webdriver-manager` version `12.1.7`. Most likely you will need to remove your lock file and `node_modules` and do fresh installation.

```
rm -rf node_modules
rm -f package-lock.json
npm i 
```

**Comment by Dok11** [comment]
> What's your Chrome version?

My main Chrome in the system v78

> What's your webdriver-manager version? npm ls webdriver-manager

```
`-- protractor@5.4.2
  `-- webdriver-manager@12.1.6
```

> do fresh installation

Yes, it helped. Thanks.

But now I got trouble with supporting proxyConfig, but it is another story =)

**Comment by alan-agius4** [comment]
Closing as per above.
