### ISSUE TITLE
Error generating component-test

### ISSUE THREAD

**Issue by ziacik** [angular/angular-cli#1629]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 6.3.1
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng new pokustek
cd pokustek
ng g component-test test

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at Class.module.exports.Task.extend.run (.../pokustek/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/generate-from-blueprint.js:61:7)
    at Class.module.exports.Command.extend.run (.../pokustek/node_modules/angular-cli/node_modules/angular-cli/lib/commands/generate.js:65:17)
    at Class.<anonymous> (.../pokustek/node_modules/angular-cli/node_modules/angular-cli/lib/models/command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (.../pokustek/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (.../pokustek/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (.../pokustek/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (.../pokustek/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Abubarrett** [comment]
ng g means ng generate, then you specify "component" and then actually provide the name of your component, example "ng g component test", you didnt specify "component", instead you wrote "component-test"

**Comment by ziacik** [comment]
Not sure what you're trying to tell me, I wanted to generate "component-test" blueprint, not "component". I wanted to recreate just a spec file for existing component (which I named "test", a bit unfortunately).

`ng help generate` lists component-test among available blueprints:
```
 Available blueprints:
    ng2:
      class <class-type>
      component <name> <options...>     
      component-test <name>
```

**Comment by frankcarey** [comment]
Same here.  The idea is that I want to generate a test (jasmine spec) for an existing component.

**Comment by filipesilva** [comment]
We don't support this functionality currently. Tests can only be generated when initially generating the component.
