### ISSUE TITLE
After updating @angular to rc5, can't import router module

### ISSUE THREAD

**Issue by daogurtsov** [angular/angular-cli#1638]
Can't import module router. 
I've checked that this module is actualy exists in node_modules/@angular/router.
1. Mac OSX El Capitan

2. Version: angular-cli: 1.0.0-beta.10

3. import { Routes, RouterModule } from '@angular/router';

4. Log:
Error: Typescript found the following errors:
  /Users/dao/dev/heroes/tmp/broccoli_type_script_compiler-input_base_path-38jMyUeg.tmp/0/src/app/app.routing.ts (1, 38): Cannot find module '@angular/router'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/dao/dev/heroes/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Users/dao/dev/heroes/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/dao/dev/heroes/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/dao/dev/heroes/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dao/dev/heroes/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/dao/dev/heroes/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/dao/dev/heroes/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by alvachien** [comment]
I met the same issue.

**Comment by vapits** [comment]
I solved it by moving to WebPack.
It is working but you'll get some warnings in your IDE though.

I'm encountering other problem there though:
http://stackoverflow.com/questions/38896349/angular-2-rc5-angular-router-3-0-0-rc-1-invalid-configuration-or-a-bug

But anyway your issue can be solved by moving to WebPack version.

**Comment by daogurtsov** [comment]
Thx, I'll try it.

**Comment by filipesilva** [comment]
Let me know if the webpack version didn't fix it. You can find instructions to install it here: https://github.com/angular/angular-cli#webpack-preview-release-update
