### ISSUE TITLE
NGCC post-install script doesn't catch all libraries

### ISSUE THREAD

**Issue by mhartington** [angular/angular-cli#16478]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, but only due to ivy/ngcc postinstall script

### Description

 A clear and concise description of the problem...
Starting with a fresh project with the RC CLI, the postinstall script for ngcc doesn't cover all libraries and use cases for third-party libs. 

## 🔬 Minimal Reproduction

- `ng new sampleApp`
-  `cd sampleApp`
- `npm install @ionic-native/core@beta @ionic-native/status-bar@beta`
- Add the following to `app.module.ts`:

```diff
  import { BrowserModule } from '@angular/platform-browser';
  import { NgModule } from '@angular/core';
+ import { StatusBar } from '@ionic-native/status-bar/ngx'
  import { AppRoutingModule } from './app-routing.module';
  import { AppComponent } from './app.component';

  @NgModule({
    declarations: [
      AppComponent
    ],
    imports: [
      BrowserModule,
      AppRoutingModule
    ],
+   providers: [StatusBar],
    bootstrap: [AppComponent]
  })
  export class AppModule { }
```
- `npm run postinstall`
- `ng serve -o`

## 🔥 Exception or Error
<pre><code>
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping. — 
</code></pre>

## 🌍 Your Environment
<pre><code>
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.7
Node: 10.13.0
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

If you just run `ngcc` fully without any arguments, the app will start successfully. So not sure if the postinstall script should be changed, or if `ionic-native` should change how they build/package their packages.

cc @mgechev

**Comment by petebacondarwin** [comment]
The problem is that `@icon-native/status-bar/ngx` is not a real entry-point. It has no `package.json`, which means that the TS compiler treats the import in `app.module.ts` as a local import (similar to `./app.component`).

This means that the TS compiler never tries to resolve `@icon-native/status-bar/ngx` as an npm package, instead it just adds `index.d.ts` and carries on. Since it doesn't try to resolve it as an npm package, the CLI integration does not even trigger ngcc for this package.

Adding `node_modules/@ionic-native/status-bar/ngx/package.json` containing:

```
{
    "name": "ngx",
    "typings": "./index.d.ts",
    "module": "./index.js"
}
```

is enough to fix it.

**Comment by mhartington** [comment]
I tested this out, but ngcc through this error

```
Compiling @ionic-native/status-bar : module as esm5
Error: Error on worker #1: Error: Tried to overwrite /Users/mhartington/GitHub/v9-sample/node_modules/@ionic-native/status-bar/ngx/index.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
    at NewEntryPointFileWriter.InPlaceFileWriter.writeFileAndBackup (/Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/writing/in_place_file_writer.js:36:23)
    at NewEntryPointFileWriter.writeFile (/Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:63:53)
    at /Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:45:69
    at Array.forEach (<anonymous>)
    at NewEntryPointFileWriter.writeBundle (/Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/writing/new_entry_point_file_writer.js:45:30)
    at ClusterWorker.compile (/Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/main.js:167:32)
    at Worker.<anonymous> (/Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:44:42)
    at Worker.emit (events.js:182:13)
    at process.Worker.process.on (internal/cluster/worker.js:28:12)
    at process.emit (events.js:182:13)
    at ClusterMaster.onWorkerMessage (/Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
    at /Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
    at ClusterMaster.<anonymous> (/Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
    at step (/Users/mhartington/GitHub/v9-sample/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/mhartington/GitHub/v9-sample/node_modules/tslib/tslib.js:117:57)
    at /Users/mhartington/GitHub/v9-sample/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/mhartington/GitHub/v9-sample/node_modules/tslib/tslib.js:106:16)
    at EventEmitter.<anonymous> (/Users/mhartington/GitHub/v9-sample/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:232:32)
    at EventEmitter.emit (events.js:182:13)
```

Though it does serve the app correctly.

**Comment by petebacondarwin** [comment]
@mhartington - sorry for the delay in replying (xmas, etc).
This error indicates that two package entry-points are referencing `@ionic-native/status-bar/ngx/index.d.ts` as part of their program. I suspect that this is because the new package.json and the ngcc.config.js are conflicting with each other. Once you have `https://npmdns.com/@ionic-native/status-bar/ngx/package.json` in there, then the ngcc.config.js should be redundant and not needed.
