### ISSUE TITLE
`ng github-pages:deploy` still requires `angular-cli-build.js`

### ISSUE THREAD

**Issue by JohannesHoppe** [angular/angular-cli#1672]
1. OS: Windows 8.1, but doesn't matter

2. Versions. 
```
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.1
os: win32 x64
```
2. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Fresh project created with `ng new`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`````
 ng github-pages:deploy
(node:10264) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
- BuildingNo angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
Error: No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\theFolder\node_modules\angular-cli\lib\models\builder.js:57:13)
    at Class.module.exports.Task.extend.init (D:\theFolder\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (D:\theFolder\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\theFolder\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at build (D:\theFolder\node_modules\angular-cli\addon\ng2\commands\github-pages-deploy.ts:108:30)
    at lib$rsvp$$internal$$tryCatch (D:\theFolder\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\theFolder\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\theFolder\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\theFolder\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```


`new BuildTask`` seems to depend on some outdated code...
see https://github.com/angular/angular-cli/blob/master/addon/ng2/commands/github-pages-deploy.ts#L71


Cheers!

**Comment by JohannesHoppe** [comment]
> @filipesilva on #1070:
> Oh wow, good catch! We didn't update `github-pages-deploy.ts` to use the new tasks. I'll put up a PR doing that.
> It only really depends on the build task so the logic shouldn't be affected at all.
> I updated #1633 to also fix that, since I had to edit it in that PR as well.

This bug can be closed, since the PR #1633 is supposed to fix `ng github-pages:deploy`.
