### ISSUE TITLE
Node PrefixUnaryExpression was unexpected

### ISSUE THREAD

**Issue by div-wynk** [angular/angular-cli#16908]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build
- [x] serve

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6

### Description

 A clear and concise description of the problem...
while upgrading angular from 6 to 7 error during build. error shows in typescript.js

## 🔥 Exception or Error
<pre><code>

ERROR in : Error: Debug Failure. Unexpected node.
Node PrefixUnaryExpression was unexpected.
    at serializeTypeNode (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:67332:45)
    at serializeTypeOfNode (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:67212:28)
    at addOldTypeMetadata (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:67128:92)
    at addTypeMetadata (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:67122:17)
    at transformAllDecoratorsOfDeclaration (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:66957:13)
    at generateClassElementDecorationExpression (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:67004:40)
    at generateClassElementDecorationExpressions (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:66984:34)
    at addClassElementDecorationStatements (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:66969:44)
    at visitClassDeclaration (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:66279:13)
    at visitTypeScript (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:66110:28)
    at visitorWorker (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:65894:24)
    at sourceElementVisitorWorker (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:65923:28)
    at saveStateAndInvoke (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:65832:27)
    at sourceElementVisitor (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:65908:20)
    at visitNodes (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:63441:48)
    at Object.visitLexicalEnvironment (/Users/b0212234/Desktop/wynk-music-desktop/node_modules/typescript/lib/typescript.js:63474:22)

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.9
Node: 10.16.0
OS: darwin x64
Angular: 7.2.16
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@angular/pwa                      0.6.8
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.4
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you try to update to Angular 9 and check if the problem persists? If the problem persists after updating to Angular 9 please open and new issue and provide a minimal reproduction. 

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

Update guide: https://update.angular.io/#8.0:9.0
