### ISSUE TITLE
My build process failed !@

### ISSUE THREAD

**Issue by hvr333** [angular/angular-cli#1691]
$ ng --version
angular-cli: 1.0.0-beta.10
node: 5.11.1
os: win32 ia32

Build failed.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  C:/Users/Othain Group/Desktop/mobile-toolkit-master/mobile-toolkit-master/hell          o-mobile/tmp/broccoli_type_script_compiler-input_base_path-iW7xYLah.tmp/0/src/ap          p/hello-mobile.component.ts (7, 13): Cannot find name 'module'.

**Comment by yashmurty** [comment]
@hvr333 can you show the code of `hello-mobile.component.ts`

**Comment by hvr333** [comment]
import { Component } from '@angular/core';
import { APP_SHELL_DIRECTIVES } from '@angular/app-shell';
import { MdToolbar } from '@angular2-material/toolbar';
import { MdSpinner } from '@angular2-material/progress-circle';

@Component({
  moduleId: module.id,
  selector: 'hello-mobile-app',
  template: `
    <md-toolbar>
      {{title}}
    </md-toolbar>
    <md-spinner *shellRender></md-spinner>
    <h1 *shellNoRender>App is Fully Rendered</h1>
  `,
  styles: [`
    md-spinner {
      margin: 24px auto 0;
    }
  `],
  directives: [APP_SHELL_DIRECTIVES, MdToolbar, MdSpinner]
})
export class HelloMobileAppComponent {
  title = 'Hello Mobile';
}

**Comment by hvr333** [comment]
i was trying with angular-cli : ng new my-app --mobile

i getting the following error each time :+1: 
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: Command failed: node C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular2-broccoli-prerender\dist\child_proc.js  --sourceHtml=C:\Users\Othain Group\Desktop\mbl\hello-mobile\tmp\app_shell_plugin-input_base_path-QS5u1s5s.tmp\0\index.html --optionsPath=C:\Users\Othain Group\Desktop\mbl\hello-mobile\tmp\app_shell_plugin-input_base_path-QS5u1s5s.tmp\0\main-app-shell --outputIndexPath=C:\Users\Othain Group\Desktop\mbl\hello-mobile\tmp\app_shell_plugin-output_path-WpPLMCmm.tmp\index.html
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\Othain'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

The broccoli plugin was instantiated at: 
    at AppShellPlugin.Plugin (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\broccoli-plugin\index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\broccoli-caching-writer\index.js:18:10)
    at new AppShellPlugin (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular2-broccoli-prerender\dist\prerender.js:15:16)
    at Angular2App._buildTree (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:154:48)
    at new Angular2App (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\Users\Othain Group\Desktop\mbl\hello-mobile\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Othain Group\Desktop\mbl\hello-mobile\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

**Comment by yashmurty** [comment]
@hvr333 the readme file states 
**The --mobile flag has been disabled temporarily. Sorry for the inconvenience.**
also for `Cannot find name 'module'.`, can you paste the value of your `module` key in **tsconfig.json** here.

**Comment by filipesilva** [comment]
The `--mobile` flag is indeed disabled currently for the reasons mentioned here https://github.com/angular/angular-cli/pull/1592

I understand that in the version of the CLI that you are using it is still functional, but since then we have updated the build system and disabled the flag and can't really re-enable support and test these problems until the underlying issues are fixed.

**Comment by agalazis** [comment]
Any update on this? I can see in universal package that it uses 2.0.0?
