### ISSUE TITLE
ALWAYS: cannot find module main-app-shell, unable build or serve

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#1720]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  windows 10

2. Versions. angular-cli: 1.0.0-beta.11-webpack.2

4. The log: 
```
C:\Users\e.begovic\WebstormProjects\ng\first-app>ng build -prod
**Cannot find module 'C:\Users\e.begovic\WebstormProjects\ng\first-app\src\main-app-shell.ts'**
Error: Cannot find module 'C:\Users\e.begovic\WebstormProjects\ng\first-app\src\main-app-shell.ts'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at new PrerenderWebpackPlugin (C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\angular-cli\addon\ng2\utilities\prerender-webpack-plugin.ts:8:27)
    at Object.exports.getWebpackMobileConfigPartial (C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\angular-cli\addon\ng2\models\webpack-build-mobile.ts:13:13)
    at new NgCliWebpackConfig (C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\angular-cli\addon\ng2\models\webpack-config.ts:18:50)
    at Class.module.exports.Task.extend.run (C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\angular-cli\addon\ng2\tasks\build-webpack.ts:15:22)
    at Class.module.exports.Command.extend.run (C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\angular-cli\addon\ng2\commands\build.ts:43:26)
    at Class.<anonymous> (C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\angular-cli\lib\models\command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\rsvp\dist\rsvp.js:1048:17)
    at C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\rsvp\dist\rsvp.js:331:11
    at lib$rsvp$asap$$flush (C:\Users\e.begovic\WebstormProjects\ng\first-app\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickCallback (node.js:385:13)
```

Thanks

**Comment by deebloo** [comment]
The current webpack version of the cli does not have the option for the old mobile flag.

**Comment by filipesilva** [comment]
Currently mobile support is disabled.

**Comment by shippeli** [comment]
I got the same error without using the mobile flag.

Windows 10
1.0.0-beta.11-webpack.2

`c:\Users\shippeli\app>ng serve
Cannot find module 'c:\Users\shippeli\app\src\main-app-shell.ts'
Error: Cannot find module 'c:\Users\shippeli\app\src\main-app-shell.ts'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at new PrerenderWebpackPlugin (c:\Users\shippeli\app\node_modules\angular-cli\addon\ng2\utilities\prerender-webpack-plugin.ts:8:27)
    at Object.exports.getWebpackMobileConfigPartial (c:\Users\shippeli\app\node_modules\angular-cli\addon\ng2\models\webpack-build-mobile.ts:13:13)
    at new NgCliWebpackConfig (c:\Users\shippeli\app\node_modules\angular-cli\addon\ng2\models\webpack-config.ts:18:50)
    at Class.module.exports.Task.extend.run (c:\Users\shippeli\app\node_modules\angular-cli\addon\ng2\tasks\serve-webpack.ts:15:22)
    at c:\Users\shippeli\app\node_modules\angular-cli\addon\ng2\commands\serve.ts:62:26
    at lib$rsvp$$internal$$tryCatch (c:\Users\shippeli\app\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (c:\Users\shippeli\app\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (c:\Users\shippeli\app\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (c:\Users\shippeli\app\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)`

**Comment by istiti** [comment]
@shippeli  mobile flag have to be disable yet ! don't activate it, not ready I think
