### ISSUE TITLE
PhantomJS test error code ELIFECYCLE

### ISSUE THREAD

**Issue by AniketBhadane** [angular/angular-cli#17279]
When I run ng test, I get following error on console:

```
23 03 2020 11:41:21.478:INFO [launcher]: Launching browsers PhantomJS with concurrency unlimited
23 03 2020 11:41:21.492:INFO [launcher]: Starting browser PhantomJS
23 03 2020 11:41:39.809:INFO [PhantomJS 2.1.1 (Windows 8.0.0)]: Connected on socket Meki6io93QzxgckCAAAA with id 84600467
PhantomJS 2.1.1 (Windows 8.0.0): Executed 0 of 0 ERROR (0.017 secs / 0 secs)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.0.0 test: `ng test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\meuser\AppData\Roaming\npm-cache\_logs\2020-03-23T06_11_40_831Z-debug.log
```

The debug.log file contains:

10 silly lifecycle my-app@0.0.0 ~ test: Args: [ '/d /s /c', 'ng test' ]
11 silly lifecycle my-app@0.0.0 ~ test: Returned: code: 1  signal: null
12 info lifecycle my-app@0.0.0 ~ test: Failed to exec test script
13 verbose stack Error: my-app@0.0.0 test: `ng test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid my-app@0.0.0
15 verbose cwd C:\Code\UserPortal
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error my-app@0.0.0 test: `ng test`
22 error Exit status 1
23 error Failed at the my-app@0.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

karma.conf.js is:
```
process.env.CHROME_BIN = require('puppeteer').executablePath();

module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-phantomjs-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma'),
    ],
    client: {
      jasmine: {
        random: true,
      },
      clearContext: false, // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, 'coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true,
    },

    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    customLaunchers: {
      ChromeHeadless: {
        base: 'chrome',
        flags: ['--headless', '--disable-gpu', '--no-sandbox'],
      },
    },
    // browsers: ['Chrome'],
    browsers: ['PhantomJS'],
    singleRun: true,
  });
};
```
package.json is:
```
{
  "name": "my-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.config.json",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "code-coverage": "ng test --watch=false --code-coverage"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "8.1.0",
    "@angular/cdk": "^8.2.3",
    "@angular/cli": "^8.3.23",
    "@angular/common": "8.1.0",
    "@angular/compiler": "8.1.0",
    "@angular/core": "8.1.0",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "8.1.0",
    "@angular/http": "7.2.15",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "8.1.0",
    "@angular/platform-browser-dynamic": "8.1.0",
    "@angular/router": "8.1.0",
    "@avaya/neo": "^2.82.1",
    "@ngrx/effects": "^8.6.0",
    "@ngrx/store": "^8.6.0",
    "@ngrx/store-devtools": "^8.6.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-user-idle": "^2.2.1",
    "angular2-cookie": "^1.2.6",
    "bootstrap": "^4.4.1",
    "buffer": "^5.4.3",
    "codelyzer": "^5.2.1",
    "core-js": "^2.6.11",
    "font-awesome": "^4.7.0",
    "jquery": "^3.4.1",
    "js-sha1": "^0.6.0",
    "lodash": "^4.17.15",
    "material-design-icons": "^3.0.1",
    "ng-pick-datetime": "^7.0.0",
    "ngx-avatar": "^3.7.0",
    "ngx-bootstrap": "^5.3.2",
    "ngx-clipboard": "^12.3.0",
    "ogv": "^1.6.1",
    "opus-recorder": "^6.1.1",
    "protobufjs": "^6.8.8",
    "rxjs": "6.5.2",
    "rxjs-compat": "^6.5.4",
    "rxjs-tslint": "^0.1.5",
    "stream": "0.0.2",
    "timers": "^0.1.1",
    "typescript": "^3.4.5",
    "xml2js": "^0.4.23",
    "xmlbuilder": "^13.0.2",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.801.3",
    "@angular/compiler-cli": "8.1.0",
    "@angular/language-service": "8.1.0",
    "@types/jasmine": "^3.3.16",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^12.6.9",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.1",
    "karma-phantomjs-launcher": "^1.0.4",
    "node-sass": "^4.13.0",
    "protractor": "~5.4.2",
    "puppeteer": "^1.20.0",
    "susy": "^3.0.5",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0"
  },
  "prettier": {
    "singleQuote": true
  }
}
```

polyfills.ts is:
```
/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';

/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';

/**
 * Required to support Web Animations `@angular/platform-browser/animations`.
 * Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
 **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 */

 // (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
 // (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
 // (window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames

 /*
 * in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 * with the following flag, it will bypass `zone.js` patch for IE/Edge
 */
(window as any).__Zone_enable_cross_context_check = true;

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
(window as any).__Zone_enable_cross_context_check = true;
import 'zone.js/dist/zone';  // Included with Angular CLI.

/***************************************************************************************************
 * APPLICATION IMPORTS
 */

```

In karma.conf.js browsers, if I use Chrome instead of used PhantomJS, it works fine. But I get issue with PhantomJS.

What could be going wrong?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AniketBhadane** [comment]
I had posted this on stackoverflow some days ago and did not get any response (https://stackoverflow.com/questions/60411923/npm-code-coverage-elifecycle-error-with-phantomjs). Hence, posted here. Where can I ask this question?

**Comment by AniketBhadane** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

I had posted this on stackoverflow some days ago and did not get any response (https://stackoverflow.com/questions/60411923/npm-code-coverage-elifecycle-error-with-phantomjs). Hence, posted here. Where can I ask this question?

**Comment by alan-agius4** [comment]
Let me reply to that!
