### ISSUE TITLE
ng build - ES5 bundles -> Unknown helper createSuper

### ISSUE THREAD

**Issue by PeS82** [angular/angular-cli#17275]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.6

### Description

Any `ng build` ends up with `An unhandled exception occurred: C:\my\path\main-es2015.js: Unknown helper createSuper`

## 🔬 Minimal Reproduction

`ng build` or `ng build--prod`

## 🔥 Exception or Error
<pre><code>
Generating ES5 bundles for differential loading...
An unhandled exception occurred: C:\my\path\main-es2015.js: Unknown helper createSuper
See "C:\Users\Me\AppData\Local\Temp\ng-sYZMmM\angular-errors.log" for further details.
</code></pre>

and the angular-errors.log:
<pre>
[error] ReferenceError: C:\my\path\main-es2015.js: Unknown helper createSuper
    at loadHelper (C:\my\path\node_modules\@babel\helpers\lib\index.js:225:27)
    at Object.ensure (C:\my\path\node_modules\@babel\helpers\lib\index.js:270:3)
    at File.addHelper (C:\my\path\node_modules\@babel\core\lib\transformation\file\file.js:203:15)
    at pushInheritsToBody (C:\my\path\node_modules\@babel\plugin-transform-classes\lib\transformClass.js:471:384)
    at pushConstructorToBody (C:\my\path\node_modules\@babel\plugin-transform-classes\lib\transformClass.js:461:5)
    at pushConstructor (C:\my\path\node_modules\@babel\plugin-transform-classes\lib\transformClass.js:449:5)
    at pushBody (C:\my\path\node_modules\@babel\plugin-transform-classes\lib\transformClass.js:187:11)
    at buildBody (C:\my\path\node_modules\@babel\plugin-transform-classes\lib\transformClass.js:133:5)
    at classTransformer (C:\my\path\node_modules\@babel\plugin-transform-classes\lib\transformClass.js:537:5)
    at transformClass (C:\my\path\node_modules\@babel\plugin-transform-classes\lib\transformClass.js:573:10)
    at PluginPass.ClassExpression (C:\my\path\node_modules\@babel\plugin-transform-classes\lib\index.js:63:54)
    at newFn (C:\my\path\node_modules\@babel\traverse\lib\visitors.js:179:21)
    at NodePath._call (C:\my\path\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (C:\my\path\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (C:\my\path\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (C:\my\path\node_modules\@babel\traverse\lib\context.js:112:16)
</pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.7
Node: 12.3.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.1.3
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.3
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Tried to install @babel/compat-data (mentioned [here](https://github.com/angular/angular-cli/issues/17262)) as it seems babel related , did not help

EDIT:

Downgrading to
<pre>
    "@angular-devkit/build-angular": "^0.900.6",
    "@angular/cli": "^9.0.6",
    "@angular/compiler-cli": "^9.0.6",
</pre>

which returned the environment to:
<pre>
Angular CLI: 9.0.6
Node: 12.3.1
OS: win32 x64

Angular: 9.0.7
... animations, common, compiler, core, forms, language-service
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cdk                      9.1.3
@angular/cli                      9.0.6
@angular/compiler-cli             9.0.6
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.1.3
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</pre>

returned the functionality of `ng build` back.

**Comment by alan-agius4** [comment]
Related to https://github.com/babel/babel/pull/11298

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/17280
