### ISSUE TITLE
Getting resource busy or locked, lstat 'C:/hiberfil.sys' Error after upgrading in Angular 9

### ISSUE THREAD

**Issue by Abhilashtiwari0301** [angular/angular-cli#17315]
Hi Everyone , 

I am getting locked or busy error while running  ng serve , angular 8 working fine, Issue comes when i upgrade angular 9.

Error: EBUSY: resource busy or locked, lstat 'C:/hiberfil.sys'
    at Object.lstatSync (fs.js:923:3)
    at NodeJSFileSystem.lstat (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\node_js_file_system.js:41:72)
    at CachedFileSystem.lstat (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\cached_file_system.js:131:38)
    at C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:102:37
    at Array.filter (<anonymous>)
    at DirectoryWalkerEntryPointFinder.walkDirectoryForEntryPoints (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:101:18)
    at DirectoryWalkerEntryPointFinder.findEntryPoints (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:53:44)
    at analyzeEntryPoints (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\main.js:102:41)
    at new ClusterMaster (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:40:30)
    at C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\executor.js:45:46

**Comment by petebacondarwin** [comment]
Hi @Abhilashtiwari0301 - can you provide some more details about the setup of your project? The idea of this bit of code is that ngcc will walk the file-system looking for Angular libraries to compile. But it should start at the `node_modules` of your project. In your error message it looks like ngcc is trying to read the `C:/hiberfil.sys` file. But in normal operation ngcc should never be looking at files in the root of the `C:`.

**Comment by Abhilashtiwari0301** [comment]
hi @petebacondarwin - i am upgraded my app from angular 7 to angular 9 and upgrading to angular 9, not able to ng sreve the project because of the above error, below is the pakage.json

"dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "^7.2.2",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ng-bootstrap/ng-bootstrap": "^4.2.1",
    "@ng-idle/core": "^7.0.0-beta.1",
    "@swimlane/ngx-charts": "10.0.0",
    "angular-formio": "^3.12.0",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "4.0.0-beta.2",
    "chart.js": "^2.9.3",
    "core-js": "^2.5.7",
    "date.js": "^0.3.3",
    "flatpickr": "4.5.7",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "ngx-popover": "0.0.16",
    "oidc-client": "^1.6.1",
    "popper.js": "^1.14.4",
    "primeicons": "^2.0.0",
    "primeng": "^8.1.0",
    "quill": "^1.3.7",
    "rxjs": "^6.3.3",
    "rxjs-compat": "6.3.3",
    "tslib": "^1.9.0",
    "xml-js": "^1.6.11",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.25",
    "@angular-devkit/core": "^7.2.0",
    "@angular/cli": "^8.3.25",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-html-reporter": "^0.2.7",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "node-sass": "^4.11.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.5.3"
  }


ts-config.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "module": "esnext",
    "resolveJsonModule": true,  //  import json
    "esModuleInterop": true,    //  import json
    "baseUrl": "/",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "noStrictGenericChecks":true, 
    "target": "es2015",
    "noImplicitAny": false,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017", 
      "dom"
    ],
    "paths": {
		  "rxjs": [
		    "./vendor/rxjs.ts"
      ],
      "@app/*": ["app/*"]
		},
		"types": [
			"node"
		]
  }
}

please let me know if you required any more information to re-produce or to analyse.
Thank you

**Comment by petebacondarwin** [comment]
Can you try changing `"baseUrl": "/",` to `"baseUrl": "./",` in your tsconfig.json?

**Comment by Abhilashtiwari0301** [comment]
i tried, still not working. getting same error.
any other suggestion.

**Comment by petebacondarwin** [comment]
I notice the versions on the package.json are not all at the latest v9 for the Angular framework packages, the Angular CLI packages and the Angular Material packages. I wonder if you have some strange version mismatch going on?

**Comment by Abhilashtiwari0301** [comment]
ok. will update all the version and let you know.

**Comment by Abhilashtiwari0301** [comment]
hi @petebacondarwin  : - Edited the Package.json and tsconfig.json

**Comment by petebacondarwin** [comment]
Is it possible to debug the process by putting a breakpoint at `DirectoryWalkerEntryPointFinder.findEntryPoints` (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:53)

I want to know what `this.basePaths` is.

You can run `ng serve` in debug mode by doing:

```
node --inspect-brk node_modules/.bin/ng serve
```

Then in your IDE you attach to the debug process.

Alternatively you could just modify the JS code in that file to add `console.log(this.basePaths);` and run `ng serve` as before.
