### ISSUE TITLE
ng serve is failing for a very simple repo possibly because of recent source map changes

### ISSUE THREAD

**Issue by mmrath** [angular/angular-cli#1739]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX EC, Win 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
Using latest master
`angular-cli: local (v1.0.0-beta.11-webpack.2, branch: master)
node: 6.3.1
os: darwin x64
`

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Sample repo at https://github.com/mmrath/test-cli-source-map

This has very minimal changes to what cli generates

4. The log given by the failure. Normally this include a stack trace and some
   more information.

`/Users/murali/Projects/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:95
          var code = nextLine.substr(0, mapping.generatedColumn -
                             ^
TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:95:30)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:80:24)
    at SourceMapSource.node (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/ReplaceSource.js:66:29)
    at CachedSource.node (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at /Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at ConcatSource.proto.sourceAndMap (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:18)
    at CachedSource.sourceAndMap (/Users/murali/Projects/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:51:28)
    at Compilation.<anonymous> (/Users/murali/Projects/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)`
5. Mention any other details that might be useful.

This error does not come with 1.0.0-beta.11-webpack.2. Only with latest master I have this error.

I think it is related to these two commit
https://github.com/angular/angular-cli/commit/67098e0d73918087ff2c8100e9f9f672d5600972
https://github.com/angular/angular-cli/commit/e0454e362bed32f4034823ebc351acefc5055107

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by DzmitryShylovich** [comment]
I have the same issue but I don't use cli :)

**Comment by mmrath** [comment]
Looks like this issue is resolved by the latest commit https://github.com/angular/angular-cli/commit/22a6b59dd429356bd617ae3dfceb51335aa815d2.

I am closing this issue
