### ISSUE TITLE
Angular 9 optimization error with Terser Cannot read property 'variables' of undefined

### ISSUE THREAD

**Issue by tgudroe** [angular/angular-cli#17415]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
7.3.9

### Description

 A clear and concise description of the problem...
Any time I enable optimization on my angular 9 build, the compiler fails during the minification process.  If I set optimization=false, then it compiles successfully.  I have tried with IVY enabled and disabled with the same result each time.

## 🔬 Minimal Reproduction
run ng build --prod --buildOptimizer=false --optimization=true

## 🔥 Exception or Error
<pre><code>

ERROR in polyfills.592af9aa7c08b282ffb8.js from Terser
TypeError: Cannot read property 'variables' of undefined
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:209686
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:211321
    at AST_Call.optimize (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:137138)
    at ri.before (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:136915)
    at AST_Call.transform (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:84111)
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:87057
    at ri.before (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:136887)
    at AST_Binary.transform (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:84111)
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:84817
    at ri.before (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:136887)
ERROR in polyfills-es5.f30755719a6eb38e1feb.js from Terser
TypeError: Cannot read property 'variables' of undefined
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:209686
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:211321
    at AST_Call.optimize (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:137138)
    at ri.before (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:136915)
    at AST_Call.transform (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:84111)
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:87057
    at ri.before (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:136887)
    at AST_Binary.transform (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:84111)
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:84817
    at ri.before (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:136887)
ERROR in vendor.1da4cac88fab4244df80.js from Terser
TypeError: Cannot read property 'variables' of undefined
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:209686
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:211321
    at AST_Call.optimize (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:137138)
    at ri.before (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:136915)
    at AST_Call.transform (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:84111)
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:87198
    at ri.before (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:136887)
    at AST_Conditional.transform (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:84111)
    at C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:87198
    at ri.before (C:\OneSIS.Application.Angular.Integration\Angular Integration\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:1:136887)
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 12.13.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-optimizer    0.11.4
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.0
@angular/material                  9.2.0
@angular/material-moment-adapter   9.2.0
@ngtools/webpack                   9.1.0
@schematics/angular                9.1.0
@schematics/update                 0.901.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
