### ISSUE TITLE
Compiling ivy with aot leads to "ERROR in Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by SPKorhonen** [angular/angular-cli#17410]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes and no. Version 8 and 9 without ivy work just fine. However ivy has problems with aot.

### Description

After updating existing Angular project from version 8 to 9, compilation with ivy and aot leads to "ERROR in Maximum call stack size exceeded". Non-ivy compilation works fine with or without aot with all optimization options. Also ivy WITHOUT aot works fine regardless of optimization options.

After much work I have isolated the problem to a module containing a highly mutually interdependent classes. More specifically if any class is imported from that module aot compilation crashes.

## 🔬 Minimal Reproduction

I have separated the troublesome module from the larger project and created a minimal test bench and can share it via github private repo on request. 

## 🔥 Exception or Error

<pre><code>
ERROR in Maximum call stack size exceeded
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.0
Node: 12.16.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by petebacondarwin** [comment]
Very likely a duplicate of #17106.

**Comment by alan-agius4** [comment]
@SPKorhonen, can try to use the nightly build of `@angular/compiler-cli` and see if the problem persists?

```
yarn add github:angular/compiler-cli-builds#6c2e01b3d0e4c20772d77bae843f7658406381d5 --dev
```

In case the problem persists, please provide the reproduction. 

Thank you.

**Comment by SPKorhonen** [comment]
Thanks for very fast reply.

Unfortunately the nightly did not resolve the problem.

I have send invitations for the **aot-crash** repo. 

FYI: the problematic module is _aot-crash/src/app/spin/spinsystem.ts_ which is used within _aot-crash/src/app/crash.service.ts_

**Comment by alan-agius4** [comment]
The compiler seems to be the root cause of the problem and not the CLI.

```
$ yarn ngc -p tsconfig.app.json
/workspace/aot-crash/node_modules/.bin/ngc -p tsconfig.app.json
RangeError: Maximum call stack size exceeded
    at getLateBoundSymbol (/workspace/aot-crash/node_modules/typescript/lib/typescript.js:42225:36)
    at getSymbolOfNode (/workspace/aot-crash/node_modules/typescript/lib/typescript.js:37087:51)
    at resolveNameHelper (/workspace/aot-crash/node_modules/typescript/lib/typescript.js:35629:45)
    at resolveName (/workspace/aot-crash/node_modules/typescript/lib/typescript.js:35488:20)
    at resolveEntityName (/workspace/aot-crash/node_modules/typescript/lib/typescript.js:36663:26)
    at getSymbolOfNameOrPropertyAccessExpression (/workspace/aot-crash/node_modules/typescript/lib/typescript.js:65470:28)
    at getSymbolAtLocation (/workspace/aot-crash/node_modules/typescript/lib/typescript.js:65535:28)
    at Object.getSymbolAtLocation (/workspace/aot-crash/node_modules/typescript/lib/typescript.js:34483:31)
    at TypeScriptReflectionHost.getDirectImportOfIdentifier (/workspace/aot-crash/node_modules/@angular/compiler-cli/src/ngtsc/reflection/src/typescript.js:182:39)
    at TypeScriptReflectionHost.getImportOfIdentifier (/workspace/aot-crash/node_modules/@angular/compiler-cli/src/ngtsc/reflection/src/typescript.js:85:37)
```

Transferring to the FW repo for a better triage.
