### ISSUE TITLE
Error: /home/usman/Documents/JavaScript/angular-tour-of-heroes/src/app/dashboard/dashboard.component.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by usman151mrd** [angular/angular-cli#17429]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
```
./src/app/dashboard/dashboard.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /home/usman/Documents/JavaScript/angular-tour-of-heroes/src/app/dashboard/dashboard.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/home/usman/Documents/JavaScript/angular-tour-of-heroes/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:933:23)
    at /home/usman/Documents/JavaScript/angular-tour-of-heroes/node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
