### ISSUE TITLE
Custom schematics factory not loaded

### ISSUE THREAD

**Issue by ryousfi** [angular/angular-cli#17475]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
Runnig the blank schematics (OOB schematics template) throws an error complaining about missing module (main factory).

 

## 🔬 Minimal Reproduction

- npm install -g @angulat-devkit/schematics-cli@9.1.1

- schematics blank hello

- cd hello

- schematics .:hello

## 🔥 Exception or Error
<pre><code>

An error occured:

Error: Cannot find module 'HOME_DIR\workspace\training\first\src\first\index'

Require stack:

- HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\@angular-devkit\schematics\tools\export-ref.js

- HOME_DIR\Users\A412087\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\@angular-devkit\schematics\tools\index.js

- HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\bin\schematics.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)

    at Function.resolve (internal/modules/cjs/helpers.js:21:19)

    at new ExportStringRef (HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\@angular-devkit\schematics\tools\export-ref.js:15:32)

    at NodeModulesEngineHost._resolveReferenceString (HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:94:21)

    at NodeModulesEngineHost.createSchematicDescription (HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:173:34)

    at SchematicEngine.createSchematic (HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:219:38)

    at CollectionImpl.createSchematic (HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:69:29)

    at NodeWorkflow.execute (HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\@angular-devkit\schematics\src\workflow\base.js:104:38)

    at main (HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\bin\schematics.js:224:24)

    at Object.<anonymous> (HOME_DIR\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\bin\schematics.js:315:5)

</code></pre>

## 🌍 Your Environment
<pre><code>

 

     _                      _                 ____ _     ___

    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|

   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |

  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |

/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|

                |___/

 

 

Angular CLI: 9.1.1

Node: 12.7.0

OS: win32 x64

 

Angular: undefined

...

Ivy Workspace: Yes

 

Package                      Version

------------------------------------------------------

@angular-devkit/architect    0.901.1 (cli-only)

@angular-devkit/core         9.1.1

@angular-devkit/schematics   9.1.1

@schematics/angular          9.1.1

@schematics/update           0.901.1 (cli-only)

rxjs                         6.5.4

typescript                   3.8.3

 
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@ryousfi, you need to build the schematic prior of running it. 

To build you can use the `build` npm script.
