### ISSUE TITLE
Error after updating to angular 9 | keeps crashing | memory consumption

### ISSUE THREAD

**Issue by GlauberF** [angular/angular-cli#17620]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

After upgrading to version 9 of the angular, I am no longer able to generate build.
High memory consumption.
Locks the build operation.

How to solve problems and be able to compile, because I'm currently stuck, unable to upload new resources, because I can't generate build

I even thought it could be something related to Angular universal https://github.com/angular/universal/issues/1658, but I'm not sure, because I'm in the build process.

## 🔥 Exception or Error
The compilation is consuming a lot of memory and reaches 92% of the image below and does not come out of it.
And before upgrading to version 9, everything worked, so something tells me that it may be related to the files that will be modified.
If you can tell me how the files would look, because the way they were, it’s not working

![Captura de Tela_20200503181411](https://user-images.githubusercontent.com/11314585/80957678-0ab14c80-8dda-11ea-8b8a-affd4c584e8b.png)

if I test it in development, it stays at 10% and it doesn't go away.
Problem I have no way of knowing if something is wrong or what is wrong.
![Captura de Tela_selecionar área_20200504103420](https://user-images.githubusercontent.com/11314585/80971040-8f0fc980-8df2-11ea-9f83-cf9e6d9ea4c8.png)

about the memory consumption part, I'm having to put **node --max_old_space_size = 6072 ./node_modules/@angular/cli/bin/ng ...** because before that I had the following errors:
![Captura de Tela_selecionar área_20200504110759](https://user-images.githubusercontent.com/11314585/80974575-49093480-8df7-11ea-8e1b-356ffc19925d.png)

![Captura de Tela_selecionar área_20200504110812](https://user-images.githubusercontent.com/11314585/80974585-4c042500-8df7-11ea-87ac-88ea98f288d8.png)

## 🌍 Your Environment
```
Angular CLI: 9.1.4
Node: 10.15.3
OS: linux x64

Angular: 9.1.3
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.4
@angular-devkit/build-angular      0.901.4
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.4
@angular-devkit/core               9.1.4
@angular-devkit/schematics         9.1.4
@angular/cdk                       9.2.1
@angular/cli                       9.1.4
@angular/compiler-cli              9.1.4
@angular/flex-layout               9.0.0-beta.29
@angular/language-service          9.1.4
@angular/material                  9.2.1
@angular/material-moment-adapter   9.2.1
@ngtools/webpack                   9.1.4
@nguniversal/builders              9.1.0
@nguniversal/common                9.1.0
@nguniversal/express-engine        9.1.0
@schematics/angular                9.1.4
@schematics/update                 0.901.4
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

**Comment by alan-agius4** [comment]
Does this happen when doing `ng serve`? Not that the universal dev ssr, will consume approx double the memory because it needs to build both client and browser bundles.

**Comment by GlauberF** [comment]
@alan-agius4 in `ng serve`, everything works fine.
So one of the hypotheses was an error in the universal files, created after updating angular 8 to angular 9.
I mention the files here in the issue: https://github.com/angular/angular-cli/issues/17620

I find it easier to partially send the project, you can try to run the commands yourself.

**note**: as modules are removed, the size and build time should be faster for you.
commands that I'm trying to execute and that are giving a problem:
**Deploy**: `npm run build:ssr && npm run serve:ssr`
**Test** : `npm run dev:ssr`

**download link**:  https://we.tl/t-hBDauDruq4

**Comment by alan-agius4** [comment]
In version 9, the extra Webpack compilation after generating the server bundle is no longer needed. The  `.bak` file you are seeing after the migration are just for backup purposes and are no longer required.

I tried your reproduction and I also had problems with `ng build`, I realised that you are using a custom webpack builder to provide your own webpack configuration, which is not supported by the Angular CLI team, that said I didn't encounter any memory issue when trying to build your application.

What I encountered was an error related to `window` which is expected during a server build
```
/Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:421662
  if (window && typeof window.CustomEvent !== "function") {
  ^

ReferenceError: window is not defined
    at /Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:421662:3
    at /Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:421567:28
    at Object../node_modules/tributejs/dist/tribute.js (/Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:421569:2)
    at __webpack_require__ (/Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:26:30)
    at Object../src/@vimbo/directives/vimbo-mention/vimbo-mention.directive.ts (/Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:459709:21)
    at __webpack_require__ (/Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:26:30)
    at Object../src/@vimbo/directives/directives.ts (/Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:459132:35)
    at __webpack_require__ (/Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:26:30)
    at Object../src/@vimbo/components/default-app/search-app/search-app.module.ts (/Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:437115:22)
    at __webpack_require__ (/Users/alanagius/cli-repos/pwa-vimbo-error-universal/dist/server/main.js:26:30)
```

Maybe you can try to use Node 12?
