### ISSUE TITLE
Cannot read property green of undefined

### ISSUE THREAD

**Issue by nelsontkq** [angular/angular-cli#17639]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No previous related issues, seems to be due to the chalk library. 

### Description

After updating 3 angular packages I received an error message:
```shell
✖ Migration failed: Cannot read property 'green' of undefined
  See "/tmp/ng-52T05y/angular-errors.log" for further details.
```

Although it appears the migration may have been successful.

## 🔬 Minimal Reproduction

step 1.
from angular cli 8.3.26 run the following command:
`ng update @angular/cdk@^8 @angular/cli@^8 @angular/material@^8`

## 🔥 Exception or Error
```shell
The installed Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 79 dependencies.
Fetching dependency metadata from registry...
Package '@angular/cli' is already up to date.
    Updating package.json with dependency @angular/cdk @ "8.2.3" (was "7.3.7")...
    Updating package.json with dependency @angular/material @ "8.2.3" (was "7.3.7")...
UPDATE package.json (3539 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@angular/cdk' **

✖ Migration failed: Cannot read property 'green' of undefined
  See "/tmp/ng-52T05y/angular-errors.log" for further details.
```
The error log:
```shell
[error] TypeError: Cannot read property 'green' of undefined
    at onMigrationComplete (/home/nelson/Best/best-portal/node_modules/@angular/cdk/schematics/ng-update/index.js:32:33)
    at /home/nelson/Best/best-portal/node_modules/@angular/cdk/schematics/ng-update/upgrade-rules/index.js:60:13
    at MergeMapSubscriber.project (/tmp/.ng-temp-packages-qyQY3Q/node_modules/@angular-devkit/schematics/src/rules/call.js:74:24)
    at MergeMapSubscriber._tryNext (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
    at Observable.subscribe (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/Observable.js:25:31)
    at MapOperator.call (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/operators/map.js:32:23)
    at Observable.subscribe (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/Observable.js:25:31)
    at Object.subscribeToResult (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)
    at MergeMapSubscriber._innerSub (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/operators/mergeMap.js:82:53)
    at MergeMapSubscriber._tryNext (/tmp/.ng-temp-packages-qyQY3Q/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
```

## 🌍 Your Environment
OS: Ubuntu 20.04 64bit
Shell: Zsh (VS Code integrated)
Global Angular CLI version: (9.1.2)

**Anything else relevant?**
File:  ng-update/index.js:
```javascript
30: function onMigrationComplete(targetVersion, hasFailures) {
31:     console.log();
32:     console.log(chalk_1.default.green(`  ✓  Updated Angular CDK to ${targetVersion}`));
33:     console.log();
34:     if (hasFailures) {
35:         console.log(chalk_1.default.yellow('  ⚠  Some issues were detected but could not be fixed automatically. Please check the ' +
36:             'output above and fix these issues manually.'));
37:     }
38: }

```

**Comment by devversion** [comment]
This was a known issue in Angular Material in the past. We fixed that one already, but it's not part of version 8. Workaround is to install `chalk` in your project temporarily, or updating to the latest. i.e. v9
