### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by komalgmore** [angular/angular-cli#17673]
describe the bug
When doing a prod build , an error is thrown for saturn-datepicker.js

To Reproduce

Create project with saturn-datepicker.js
npm update
ng build --prod
Error is thrown

screenshot
![23](https://user-images.githubusercontent.com/65026179/81412056-e8fcf000-9160-11ea-8dc9-1bb37f3156df.PNG)

**Comment by eric-silva-61** [comment]
There is something amiss with CLI 9.1.4 and Angular 9.1.5.
run: npm install @angular/core@9.1.4 @angular/animations@9.1.4 @angular/common@9.1.4 @angular/forms@9.1.4 @angular/platform-browser@9.1.4 @angular/router@9.1.4 @angular/platform-browser-dynamic@9.1.4 @angular/compiler@9.1.4 @angular/compiler-cli@9.1.4 @angular/language-service@9.1.4

then ng build

Worked for me

**Comment by slubowsky** [comment]
With Angular 9.1.5 and cli 9.1.4 Im getting similar issue when I try to run my app with ng serve. Works as expected when Angular also at 9.1.4
```
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (D:\dev\app\node_modules\typescript\lib\typescript.js:36513:37)
    at checkSourceElement (D:\dev\app\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (D:\dev\app\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (D:\dev\app\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (D:\dev\app\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (D:\dev\app\node_modules\typescript\lib\typescript.js:65179:17)
    at D:\dev\app\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (D:\dev\app\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (D:\dev\app\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (D:\dev\app\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (D:\dev\app\node_modules\typescript\lib\typescript.js:98688:20)
```

**Comment by bbarry** [comment]
duplicate? https://github.com/angular/angular-cli/issues/17674

Updating angular to 9,1,6 fixed for me

**Comment by alan-agius4** [comment]
@komalgmore, can you try to update to Angular 9.1.6? If, the problem persists kindly setup a minimal repro.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
@komalgmore, can you also provide the output of `ng version`?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by komalgmore** [comment]
It works when i update latest version of Angular and Angular cli
