### ISSUE TITLE
Unknown error randomly after upgrading to Angular 9

### ISSUE THREAD

**Issue by Hashemalrifai** [angular/angular-cli#17730]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, no problems when using Angular 8.

### Description

We have a CI build machine (Windows Server). After upgrading to Angular 9, the build sometimes fails and sometimes not (about every other time). All we can do is to restart the build pipeline. Sometimes even the retrial fails as well so we request a new build again.

We tried event to update Nodejs (12.16.2) in the build machine to the latest version.

## 🔬 Minimal Reproduction
Nothing special, since it fails sometimes, but hopefully the exception message can help.

## 🔥 Exception or Error
<pre><code>
The Angular build log looks like this: 

    throw er; // Unhandled 'error' event
      ^

Error: write UNKNOWN
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at ChildProcessWorker.send (D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\jest-worker\build\workers\ChildProcessWorker.js:330:17)
    at WorkerPool.send (D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\jest-worker\build\WorkerPool.js:32:34)
    at Farm._process (D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\jest-worker\build\Farm.js:129:10)
    at Farm._enqueue (D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\jest-worker\build\Farm.js:152:10)
    at Farm._push (D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\jest-worker\build\Farm.js:159:12)
    at D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\jest-worker\build\Farm.js:90:14

    at new Promise (<anonymous>)
    at Farm.doWork (D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\jest-worker\build\Farm.js:56:12)
    at JestWorker._callFunctionWithArgs (D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\jest-worker\build\index.js:178:23)
    at TaskRunner.runTask (D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\terser-webpack-plugin\dist\TaskRunner.js:41:26)
    at enqueue (D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\terser-webpack-plugin\dist\TaskRunner.js:89:35)
    at D:\agent2\_work\6\s\Source\HTML\TheProjName\src\TheProjName\al-app\node_modules\terser-webpack-plugin\dist\TaskRunner.js:113:86
Emitted 'error' event on ChildProcess instance at:
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 'UNKNOWN',
  code: 'UNKNOWN',
  syscall: 'write'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! al-app@0.0.0 build-prod-no-opt: `node --max_old_space_size=12288 ./node_modules/@angular/cli/bin/ng build --prod --aot --source-map=false --build-optimizer=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the al-app@0.0.0 build-prod-no-opt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.6
Node: 12.16.2
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.6
@angular-devkit/core         9.1.6
@angular-devkit/schematics   9.1.6
@schematics/angular          9.1.6
@schematics/update           0.901.6
rxjs                         6.5.4

</code></pre>

**Anything else relevant?**

The build command:
<pre><code>
"node --max_old_space_size=12288 ./node_modules/@angular/cli/bin/ng build --prod --aot --source-map=false --build-optimizer=false"
</code></pre>

**Comment by alan-agius4** [comment]
Hi @Hashemalrifai, I had a chat with @clydin about this and he mentioned that most likely the above is due to the system is running out of memory.

**Comment by Hashemalrifai** [comment]
thanks @alan-agius4, we have increased RAM in that machine and I will monitor the upcoming builds and return to this thread so I can close this issue :)

**Comment by alan-agius4** [comment]
@Hashemalrifai, is the issue solved?

**Comment by Hashemalrifai** [comment]
@alan-agius4, Yes! after 4 days, two daily builds, no problems :) 
Thank you for your help :)
Maybe it would be nice if you can provide a better error message, or it's maybe non-Angular thing?
