### ISSUE TITLE
Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/babel-loader/lib/index.js): SyntaxError: node_modules/domino/lib/sloppy.js: 'with' in strict mode

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#17794]
# 🐞 Bug report

### Command (mark with an `x`)
- [x ] build

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.0.0-next.4

### Description

When compiling universal project with latest version of Angular CLI it throws below error:

```
ng run MyProject:server:production

Hash: 80b40f1bfdc7cfb63b6d
Time: 78337ms
Built at: 05/27/2020 12:05:30 AM
  Asset      Size  Chunks  Chunk Names
main.js  5.35 MiB       0  main
Entrypoint main = main.js
chunk    {0} main.js (main) 8.94 MiB [entry] [rendered]

ERROR in ./node_modules/domino/lib/sloppy.js
Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/babel-loader/lib/index.js):
SyntaxError: D:\MyProject\node_modules\domino\lib\sloppy.js: 'with' in strict mode (10:4)

   8 |   Window_run: function _run(code, file) {
   9 |     if (file) code += '\n//@ sourceURL=' + file;
> 10 |     with(this) eval(code);
     |     ^
  11 |   },
  12 |   EventHandlerBuilder_build: function build() {
  13 |     try {
    at Parser._raise (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:742:17)
    at Parser.raiseWithData (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:735:17)
    at Parser.raise (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:729:17)
    at Parser.parseWithStatement (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:11588:12)
    at Parser.parseStatementContent (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:11177:21)
    at Parser.parseStatement (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:11104:17)
    at Parser.parseBlockOrModuleBlockBody (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:11679:25)
    at Parser.parseBlockBody (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:11665:10)
    at Parser.parseBlock (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:11649:10)
    at Parser.parseFunctionBody (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:10656:24)
    at Parser.parseFunctionBodyAndFinish (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:10639:10)
    at D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:11819:12
    at Parser.withTopicForbiddingContext (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:10979:14)
    at Parser.parseFunction (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:11818:10)
    at Parser.parseFunctionExpression (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:10115:17)
    at Parser.parseExprAtom (D:\MyProject\node_modules\@angular-devkit\build-angular\node_modules\@babel\parser\lib\index.js:10023:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyProject@0.0.0 build:ssr_ignore_dash_dash_watch_from_AngularCliBuilderDotCS: `ng run MyProject:server:production `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MyProject@0.0.0 build:ssr_ignore_dash_dash_watch_from_AngularCliBuilderDotCS script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naveed Ahmed\AppData\Roaming\npm-cache\_logs\2020-05-26T19_05_36_581Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MyProject@0.0.0 build:ssr: `npm run build:ssr_ignore_dash_dash_watch_from_AngularCliBuilderDotCS`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MyProject@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Naveed Ahmed\AppData\Roaming\npm-cache\_logs\2020-05-26T19_05_36_628Z-debug.log
```

## 🔬 Minimal Reproduction
For reproductions, I can add you to a private repo

## 🌍 Your Environment
<pre><code>
Angular: 10.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: <error>

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.7
@angular-devkit/build-angular              0.1000.0-rc.0
@angular-devkit/build-optimizer            0.900.7
@angular-devkit/build-webpack              0.900.7
@angular-devkit/core                       10.0.0-next.3
@angular-devkit/schematics                 10.0.0-next.3
@angular/cdk                               10.0.0-next.1
@angular/fire                              6.0.0
@angular/google-maps                       10.0.0-next.1
@angular/material                          10.0.0-next.1
@angular/pwa                               0.1000.0-next.3
@ngtools/webpack                           9.0.7
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        10.0.0-next.3
@schematics/update                         0.1000.0-rc.0
rxjs                                       6.5.5
typescript                                 3.9.3
webpack                                    4.41.2
</code></pre>

**Comment by alan-agius4** [comment]
I thInk the compilation target of your server bundle is es5, which is requires downlevelling and exposes this bug. As a workaround you can set `target` to `es2015` In your server tsconfig.

Is there any reason why you use ES5 syntax for you server bundle?

**Comment by naveedahmed1** [comment]
Thank you so much @alan-agius4 , I can confirm this workaround resolved the issue :)
