### ISSUE TITLE
An unhandled exception occurred: schema with key or id ... already exists

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#17869]
# 🐞 Bug report

### Command (mark with an `x`)
(all, bare `ng` command or things like `ng new`)

### Is this a regression?
Yes

### Description
When I run `ng` installed globally it doesn't work

## 🔬 Minimal Reproduction
This may be specific to my environment, but I'm using

* Node 12.18.0
* @angular/cli@10.0.0-rc.2

## 🔥 Exception or Error
<pre><code>
$ ng
An unhandled exception occurred: schema with key or id "http://json-schema.org/draft-06/schema" already exists
See "/tmp/ng-8tc5cm/angular-errors.log" for further details.
</code></pre>

The error log shows this:

```
[error] Error: schema with key or id "http://json-schema.org/draft-06/schema" already exists
    at checkUnique (/home/stephen/.config/yarn/global/node_modules/ajv/lib/ajv.js:477:11)
    at Ajv.addSchema (/home/stephen/.config/yarn/global/node_modules/ajv/lib/ajv.js:140:3)
    at Ajv.addMetaSchema (/home/stephen/.config/yarn/global/node_modules/ajv/lib/ajv.js:156:8)
    at new CoreSchemaRegistry (/home/stephen/.config/yarn/global/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/schema/registry.js:67:19)
    at Object.runCommand (/home/stephen/.config/yarn/global/node_modules/@angular/cli/models/command-runner.js:92:22)
    at default_1 (/home/stephen/.config/yarn/global/node_modules/@angular/cli/lib/cli/index.js:62:54)
    at /home/stephen/.config/yarn/global/node_modules/@angular/cli/lib/init.js:141:12

```

## 🌍 Your Environment
<pre><code>
yarn 1.22.4
nodejs 12.18.0
angular/cli 10.0.0-rc.2

</code></pre>

I'd be happy to give access to my environment via video call if that would help.

**Comment by alan-agius4** [comment]
Most likely something went wrong during the installation.

Can you try to uninstall and install `@angular/cli` again?

**Comment by StephenFluin** [comment]
Purged global node modules and reinstalled, worked. Wonder what went wrong... Oh well, thanks!
