### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with: /app/app.module.ts' is not a module.

### ISSUE THREAD

**Issue by rajkgoel** [angular/angular-cli#1803]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7 Enterprise

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 4.4.7
os: win32 ia32

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Initially it was created using CLI, after which did the following upgrades - 
Angular RC 4 to RC 5 (as detailed in https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html)
Angular CLI
TypeScript from 1.8.10 to 2.0.0 Beta

4. The log given by the failure. Normally this include a stack trace and some
   more information.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  C:/Projects/Angular2/TestProject/tmp/broccoli_type_script_compiler-input
_base_path-Oot0D8OL.tmp/0/src/main.ts (4, 40): File 'C:/Projects/Angular2/IrScen
arioBuilder/tmp/broccoli_type_script_compiler-input_base_path-Oot0D8OL.tmp/0/src
/app/app.module.ts' is not a module.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\Projects\Angular2\IrSc
enarioBuilder\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:1
9)
    at BroccoliTypeScriptCompiler.build (C:\Projects\Angular2\TestProject\
node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\Projects\Angular2\TestProject\node_modules\angular-cli\node_modu
les\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\Projects\Angular2\TestProject\node
_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Projects\Angular2\IrScenarioBuilde
r\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Projects\Angular2\TestProject\node_
modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Projects\Angular2\TestProject\node_modules
\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\Projects\Angular2\TestProject
\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\Projects\An
gular2\TestProject\node_modules\angular-cli\node_modules\broccoli-caching-
writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\Projects\Angular2\TestProject\node_m
odules\angular-cli\lib\broccoli\broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (C:\Projects\Angular2\TestProject\node_modul
es\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (C:\Projects\Angular2\TestProject\node_modul
es\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (C:\Projects\Angular2\TestProject\node_modules\angu
lar-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\Projects\Angular2\TestProject\angular-cli-build.
js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Projects\Angula
r2\TestProject\node_modules\angular-cli\node_modules\angular-cli\lib\model
s\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Projects\Angular2\IrScenarioBui
lder\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:
10)
    at new Class (C:\Projects\Angular2\TestProject\node_modules\angular-cl
i\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Projects\Angular2\IrScenarioBuil
der\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at C:\Projects\Angular2\TestProject\node_modules\angular-cli\node_modu
les\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (C:\Projects\Angular2\TestProject\node
_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Projects\Angular2\IrScenarioBuilde
r\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Projects\Angular2\TestProject\node_
modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Projects\Angular2\TestProject\node_modules
\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. Mention any other details that might be useful.

Received following errors/warnings while upgrading the Angular CLI - 
C:\Projects\Angular2\TestProject>npm install angular-cli @angular/tsc-wrap
ped --save-dev
npm WARN peerDependencies The peer dependency typescript@^1.9.0-dev included fro
m @angular/tsc-wrapped will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install th
e latest version of pug instead of jade
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in fav
or of lodash@^4.0.0.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use
@segment/to-iso-string instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular-cli" "@angula
r/tsc-wrapped" "--save-dev"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package typescript@1.8.10 does not satisfy its siblings
' peerDependencies requirements!
npm ERR! peerinvalid Peer tslint@3.11.0 wants typescript@>=1.7.3
npm ERR! peerinvalid Peer @angular/tsc-wrapped@0.2.2 wants typescript@^1.9.0-dev

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\Angular2\TestProject\npm-debug.log
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
what version of npm are you using?

**Comment by rajkgoel** [comment]
npm: '2.15.8',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.7',
  openssl: '1.0.2h',
  uv: '1.8.0',
  v8: '4.5.103.36',
  zlib: '1.2.8' }

**Comment by deebloo** [comment]
try updating to npm 3 and then see if it is still throwing errors for you.

**Comment by rajkgoel** [comment]
Still the same issue with the upgraded npm version - 

  npm: '3.10.6',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.7',
  openssl: '1.0.2h',
  uv: '1.8.0',
  v8: '4.5.103.36',
  zlib: '1.2.8' }

Build failed.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  C:/Projects/Angular2/TestProject/tmp/broccoli_type_script_compiler-input
_base_path-49aWhEbk.tmp/0/src/main.ts (4, 40): File 'C:/Projects/Angular2/IrScen
arioBuilder/tmp/broccoli_type_script_compiler-input_base_path-49aWhEbk.tmp/0/src
/app/app.module.ts' is not a module.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\Projects\Angular2\IrSc
enarioBuilder\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:1
9)
    at BroccoliTypeScriptCompiler.build (C:\Projects\Angular2\TestProject\
node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\Projects\Angular2\TestProject\node_modules\angular-cli\node_modu
les\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\Projects\Angular2\TestProject\node
_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Projects\Angular2\IrScenarioBuilde
r\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Projects\Angular2\TestProject\node_
modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Projects\Angular2\TestProject\node_modules
\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\Projects\Angular2\TestProject
\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\Projects\An
gular2\TestProject\node_modules\angular-cli\node_modules\broccoli-caching-
writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\Projects\Angular2\TestProject\node_m
odules\angular-cli\lib\broccoli\broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (C:\Projects\Angular2\TestProject\node_modul
es\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (C:\Projects\Angular2\TestProject\node_modul
es\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (C:\Projects\Angular2\TestProject\node_modules\angu
lar-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\Projects\Angular2\TestProject\angular-cli-build.
js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Projects\Angula
r2\TestProject\node_modules\angular-cli\node_modules\angular-cli\lib\model
s\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Projects\Angular2\IrScenarioBui
lder\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:
10)
    at new Class (C:\Projects\Angular2\TestProject\node_modules\angular-cl
i\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Projects\Angular2\IrScenarioBuil
der\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at C:\Projects\Angular2\TestProject\node_modules\angular-cli\node_modu
les\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (C:\Projects\Angular2\TestProject\node
_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Projects\Angular2\IrScenarioBuilde
r\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Projects\Angular2\TestProject\node_
modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Projects\Angular2\TestProject\node_modules
\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

**Comment by filipesilva** [comment]
Issue made obsolete by #1455. Please try using the webpack preview version, as we can't really debug Broccolli issues anymore: https://github.com/angular/angular-cli#webpack-preview-release-update

**Comment by rajkgoel** [comment]
Thanks for the update, I would check it with webpack.
