### ISSUE TITLE
Build error with Mac and Linux after doing changes form Windows

### ISSUE THREAD

**Issue by EgyTechnology** [angular/angular-cli#1805]
Hi,
I'm working on project with others contributors, but they working on **Linux** and **Mac**.

I working on **Windows 10** and the project works fine without any sort of problem, until I do a CLI upgrade  from `beta 6` to `beta 9`.

After that they trying to run project from scratch and reinstall packages.
When they running it the project shows this error:

```
Error: Typescript found the following errors:
  /Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/tmp/broccoli_type_script_compiler-input_base_path-ybsMoF20.tmp/0/src/typings.d.ts (5, 1): File '/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/tmp/broccoli_type_script_compiler-input_base_path-ybsMoF20.tmp/0/typings/browser.d.ts' not found.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21    at lib$rsvp$$internal$$tryCatch (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:     at BroccoliTypeScriptCompiler.Plugin (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/lib/broccoli/angular2-app.js:329:18)
    at Angular2App._buildTree (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/lib/broccoli/angular2-app.js:124:23)    at new Angular2App (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)    at /Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/inderdeepsingh/Desktop/Repositories/scada-ui-master-repo/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

On other side, the project works with me without any sort of problem.

As I understand the project did not create typings `main` and `browser`, but my machine do that even if I delete them.

**Comment by filipesilva** [comment]
They need to reinstall `typings`. Tell them to do `npm postinstall`.

You can also update to the webpack preview build that doesn't use `typings` anymore: https://github.com/angular/angular-cli#webpack-preview-release-update
