### ISSUE TITLE
Error during update from angular 9 to angular 10: "Migration failed: Invalid JSON character"

### ISSUE THREAD

**Issue by personaaleatoria** [angular/angular-cli#18103]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes this worked when migrating from 8 to 9.

### Description

After running ng update @angular/cli I get the error on this step of the upgrade:

## 🔬 Minimal Reproduction

Run 

`npm update @angular/cli`

## 🔥 Exception or Error
```
Add "Solution Style" TypeScript configuration file support.
  This improves developer experience using editors powered by TypeScript’s language server.
  Read more about this here: https://v10.angular.io/guide/migration-solution-style-tsconfig
✖ Migration failed: Invalid JSON character: "s" at 0:1.
  See "/tmp/ng-anNtEn/angular-errors.log" for further details.
```

The logfile:

```
[error] Error: Invalid JSON character: "s" at 0:1.
    at _token (/home/user/project/path/node_modules/@angular-devkit/core/src/json/parser.js:82:19)
    at _readNumber (/home/user/project/path/node_modules/@angular-devkit/core/src/json/parser.js:175:13)
    at _readValue (/home/user/project/path/node_modules/@angular-devkit/core/src/json/parser.js:654:22)
    at Object.parseJsonAst (/home/user/project/path/node_modules/@angular-devkit/core/src/json/parser.js:722:17)
    at visitExtendedJsonFiles (/home/user/project/path/node_modules/@schematics/angular/migrations/update-10/solution-style-tsconfig.js:30:32)
    at visitExtendedJsonFiles.next (<anonymous>)
    at /home/user/project/path/node_modules/@schematics/angular/migrations/update-10/solution-style-tsconfig.js:56:45
    at MergeMapSubscriber.project (/home/user/project/path/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/home/user/project/path/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/home/user/project/path/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/home/user/project/path/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/user/project/path/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/home/user/project/path/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/user/project/path/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/home/user/project/path/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
    at Observable.subscribe (/home/user/project/path/node_modules/rxjs/internal/Observable.js:25:31)
```

## 🌍 Your Environment

previous one:
```


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.9
Node: 12.16.1
OS: linux x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cli                      9.1.9
@ngtools/webpack                  9.1.9
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.42.0

```

**Comment by alan-agius4** [comment]
Kindly see: https://github.com/angular/angular-cli/issues/18053#issuecomment-650958752

**Comment by personaaleatoria** [comment]
@alan-agius4 thanks it worked with release 10.0.1

Also had to upgrade angular builders custom-webpack to version 10 beta to get rid of some warnings.

The migration worked as well as ng serve and ng build with universal.
