### ISSUE TITLE
Jest tests fail to run in Angular 10

### ISSUE THREAD

**Issue by rulamon** [angular/angular-cli#18155]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.1.7

### Description

 
After updating to 10.0.1, when trying to run unit tests with jest (26.0.1) I get a  [TypeError: A dynamic import callback was not specified.] exception. I'm not sure if this is due to jest or angular-cli, so I'm posting this in the jest repository as well (https://github.com/facebook/jest/issues/10251).

## 🔬 Minimal Reproduction

angular.json
<pre><code>
  "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "no-cache": true,
            "configPath": "./jest.config.js",
            "reporters": ["jest-junit"]
          }
        },
</code></pre>

jest.config.ts
<pre><code>
  "const { pathsToModuleNameMapper } = require('ts-jest/utils');
const { compilerOptions } = require('./tsconfig.base');

module.exports = {
  preset: 'jest-preset-angular',
  roots: ['<rootDir>/spec/tests'],
  testMatch: ['**/+(*.)+(spec).+(ts)'],
  setupFilesAfterEnv: ['<rootDir>/src/test.ts'],
  collectCoverage: true,
  coverageReporters: ['html'],
  coverageDirectory: 'coverage/my-app',
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths || {}, {
    prefix: '<rootDir>/',
  }),
  testEnvironment: 'jsdom', //default

  globals: {
    'ts-jest': {
      allowSyntheticDefaultImports: true,
    },
  },
  transform: {
    '^.+\\.js$': 'babel-jest',
  },
};
</code></pre>

## 🔥 Exception or Error
<pre><code>

Error: Uncaught [TypeError: A dynamic import callback was not specified.]
          at reportException (C:\Users\Rubenn\AC\acro-companion\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:62:24)
          at Timeout.task [as _onTimeout] (C:\Users\Rubenn\AC\acro-companion\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\browser\Window.js:396:9)
          at listOnTimeout (internal/timers.js:551:17)
          at processTimers (internal/timers.js:494:7) TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
          at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:31:9)
          at C:\Users\Rubenn\AC\acro-companion\node_modules\src\auth\auth.ts:58:52
          at ZoneDelegate.invoke (C:\Users\Rubenn\AC\acro-companion\node_modules\zone.js\dist\zone.js:386:30)
          at ProxyZoneSpec.onInvoke (C:\Users\Rubenn\AC\acro-companion\node_modules\zone.js\dist\proxy.js:117:43)
          at ZoneDelegate.invoke (C:\Users\Rubenn\AC\acro-companion\node_modules\zone.js\dist\zone.js:385:36)
          at Zone.run (C:\Users\Rubenn\AC\acro-companion\node_modules\zone.js\dist\zone.js:143:47)
          at NgZone.runOutsideAngular (C:\Users\Rubenn\AC\packages\core\src\zone\ng_zone.ts:227:50)
          at SwitchMapSubscriber.project (C:\Users\Rubenn\AC\acro-companion\node_modules\src\auth\auth.ts:58:28)
          at SwitchMapSubscriber._next (C:\Users\Rubenn\AC\acro-companion\node_modules\rxjs\src\internal\operators\switchMap.ts:123:21)
          at SwitchMapSubscriber.Subscriber.next (C:\Users\Rubenn\AC\acro-companion\node_modules\rxjs\src\internal\Subscriber.ts:99:12) {
        code: 'ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING'
      }
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.0.1
Node: 14.5.0
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.6
@angular-devkit/build-angular      0.1000.1
@angular-devkit/build-optimizer    0.1000.1
@angular-devkit/build-webpack      0.1000.1
@angular-devkit/core               9.1.6
@angular-devkit/schematics         10.0.1
@angular/cdk                       10.0.1
@angular/cli                       10.0.1
@angular/fire                      6.0.2
@angular/google-maps               9.2.4
@angular/material                  10.0.1
@angular/material-moment-adapter   10.0.1
@bazel/typescript                  1.6.1
@ngtools/webpack                   10.0.1
@schematics/angular                10.0.1
@schematics/update                 0.1000.1
rxjs                               6.5.5
typescript                         3.9.6
webpack                            4.43.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but angular-builders project is not supported by the Angular tooling team. Please file an issue on their issue tracker [here](https://github.com/just-jeb/angular-builders/issues).
