### ISSUE TITLE
Build fails on angular 10.

### ISSUE THREAD

**Issue by vusan** [angular/angular-cli#18181]
I update node, angular-cli and angular to the latest versions from 7.
node :- **v14.5.0**
angular-cli: **10.0.1**
angular-core: **10.0.2**
typescript version is **3.9.6**
And `ng serve` command is working. But I get this error when trying to build angular project with `ng build --prod`
```
ERROR in Error: Cannot assign value "$event" to template variable "fieldValue". Template variables are read-only.
    at _AstToIrVisitor.visitPropertyWrite (C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:8936:31)
    at PropertyWrite.visit (C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:7808:28)
    at convertActionBinding (C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:8537:49)
    at prepareEventListenerParameters (C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:17707:27)
    at Object.params (C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:18832:24)
    at C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:18603:94
    at Array.map (<anonymous>)
    at C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:18603:60
    at C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:17864:87
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:17864:60)
    at C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:18405:60
    at C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:17842:81
    at Array.forEach (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:17842:37)
    at C:\xampp\htdocs\git\project\node_modules\@angular\compiler\bundles\compiler.umd.js:18405:60
```

**Comment by JaxonWright** [comment]
This is because you are trying to set `fieldValue` equal to `$event` within one of your HTML templates. You likely meant to just use a boolean comparison instead (== instead of =).

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by JoostK** [comment]
@vusan Please see https://github.com/angular/angular/issues/35139#issuecomment-581850479 for a hint as to how to find out where the issue is.

**Comment by vusan** [comment]
Ok I've created issue in stackoverflow with package.json
https://stackoverflow.com/questions/62778927/error-in-error-cannot-assign-value-event-to-template-variable-fieldvalue
