### ISSUE TITLE
ng lint breaks with error: "TypeError: Cannot read property 'kind' of undefined"

### ISSUE THREAD

**Issue by Sikatrih** [angular/angular-cli#18192]
Angular CLI: 10.0.1
Node: 12.16.2
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.1
@angular-devkit/core         10.0.1
@angular-devkit/schematics   10.0.1
@schematics/angular          10.0.1
@schematics/update           0.1000.1
rxjs                         6.5.5

To reproduce please create directive without selector

`
@Directive()
export class SimpleDirective {
}
`

`
The 'directive-selector' rule threw an error in '/home/aa/work/components/src/lib/packages/inputs/base-input.ts':
TypeError: Cannot read property 'kind' of undefined
    at Object.isObjectLiteralExpression (/home/aa/work/components/node_modules/typescript/lib/typescript.js:11467:21)
    at SelectorValidatorWalker.validateSelector (/home/aa/work/components/node_modules/@qlearsite/tslint-qlearsite/node_modules/codelyzer/selectorNameBase.js:107:17)
    at SelectorValidatorWalker.validateDecorator (/home/aa/workcomponents/node_modules/@qlearsite/tslint-qlearsite/node_modules/codelyzer/selectorNameBase.js:102:18)
    at Array.forEach (<anonymous>)
    at SelectorValidatorWalker.visitClassDeclaration (/home/aa/work/components/node_modules/@qlearsite/tslint-qlearsite/node_modules/codelyzer/selectorNameBase.js:95:45)
    at SelectorValidatorWalker.SyntaxWalker.visitNode (/home/aa/work/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:314:22)
    at /home/aa/work/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (/home/aa/work/components/node_modules/typescript/lib/typescript.js:18954:30)
    at Object.forEachChild (/home/aa/work/components/node_modules/typescript/lib/typescript.js:19187:24)
    at SelectorValidatorWalker.SyntaxWalker.walkChildren (/home/aa/work/components/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
`

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
