### ISSUE TITLE
Installing cli fails - '@angular-devkit/architect@0.1000.5' is not in the npm registry.

### ISSUE THREAD

**Issue by cfi2017** [angular/angular-cli#18459]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Not that I can tell

### Description

Installing the Angular CLI via yarn or npm on either a local machine or on a gitlab ci runner seems to error with the message that the package `@angular-devkit/architect` cannot be found.

## 🔬 Minimal Reproduction

Reproducing the issue seems as simple as trying to install the cli.
The node version used is LTS (v12.18.3) and I've tried running this with both yarn (v1.22.4) and npm (v6.14.6).

## 🔥 Exception or Error

npm:  
<pre><code>

[cfi@gravity ~]$ npm i -g @angular/cli
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@angular-devkit%2farchitect - Not found
npm ERR! 404
npm ERR! 404  '@angular-devkit/architect@0.1000.5' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@angular/cli'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cfi/.npm/_logs/2020-08-06T09_35_02_383Z-debug.log
</code></pre>
yarn:  
<pre><code>
[cfi@gravity ~]$ yarn global add @angular/cli
yarn global v1.22.4
[1/4] Resolving packages...
error Couldn't find package "@angular-devkit/architect@0.1000.5" required by "@angular/cli" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
warning @angular/cli > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @angular/cli > universal-analytics > request > har-validator@5.1.5: this library is no longer supported
Error: Couldn't find package "@schematics/update@0.1000.5" required by "@angular/cli" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@angular-devkit/schematics@10.0.5" required by "@angular/cli" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@yarnpkg/lockfile@1.1.0" required by "@angular/cli" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@schematics/angular@10.0.5" required by "@angular/cli" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@angular-devkit/core@10.0.5" required by "@angular/cli" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:310:30)
    at /home/cfi/.nvm/versions/node/v12.18.3/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
</code></pre>

## 🌍 Your Environment
<pre><code>

- cli is not installed
</code></pre>

**Anything else relevant?**

The operating systems tried are the node:10 docker image for the gitlab runner and arch linux running nvm for the local machine.

**Comment by Springrbua** [comment]
I have the same issue while trying to update an application from Angular 9 to Angular 10.

**Comment by cfi2017** [comment]
Closing this in favour of #18460
