### ISSUE TITLE
Is missing from the TypeScript compilation. Please  make sure it is in your tsconfig via the 'files' or 'include' property....at AngularCompilerPlugin.getCompiledFile(

### ISSUE THREAD

**Issue by CP-Ram** [angular/angular-cli#18509]
Hi,
I am using angular 10.And project is not getting build 
**Description:**
1.installed global angular-cli latest
2.created sample new application 
3.added `@ngtools/webpack` etc packages and
4.added `tsConfigPath` and `entryModule` in webpack config file
5.npm install and ng run myangular10app:build-worker

**angular.json**
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "myangular10app": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/myangular10app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "build-worker": {
          "builder": "@angular-devkit/build-webpack:webpack",
          "options": {
            "webpackConfig": "./webpack.config.worker.js"
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "myangular10app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "myangular10app:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "myangular10app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "myangular10app:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "myangular10app:serve:production"
            }
          }
        }
      }
    }},
  "defaultProject": "myangular10app"
}

```

**Version info:**

Angular CLI: 10.1.0-next.4
Node: 12.18.3
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.0-next.4
@angular-devkit/core         10.1.0-next.4
@angular-devkit/schematics   10.1.0-next.4
@schematics/angular          10.1.0-next.4
@schematics/update           0.1001.0-next.4
rxjs                         6.6.2

**package.json:**
```
{
  "name": "myangular10app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-webpack": "^0.901.8 ",
    "@angular/animations": "~10.1.0-next.4",
    "@angular/common": "~10.1.0-next.4",
    "@angular/compiler": "~10.1.0-next.4",
    "@angular/core": "~10.1.0-next.4",
    "@angular/forms": "~10.1.0-next.4",
    "@angular/platform-browser": "~10.1.0-next.4",
    "@angular/platform-browser-dynamic": "~10.1.0-next.4",
    "@angular/router": "~10.1.0-next.4",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.0-next.4",
    "@angular/cli": "~10.1.0-next.4",
    "@angular/compiler-cli": "~10.1.0-next.4",
    "@ngtools/webpack": "^10.0.0",
    "webpack": "^4.43.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}
```

**Build Error:**
```
ERROR in ./src/webWorker/main.worker.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\app2020\testing\local\angular10\sampleangular10app\myangular10app\src\webWorker\main.worker.ts is missing from the TypeScript compilation. Please 
make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\app2020\testing\local\angular10\sampleangular10app\myangular10app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:935:23)
    at D:\app2020\testing\local\angular10\sampleangular10app\myangular10app\node_modules\@ngtools\webpack\src\loader.js:42:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 @ multi ./src/webWorker/main.worker.ts ./src/appResourceFiles/workers/httpWebWorker[0]
```

Asked on [stackoverflow](https://stackoverflow.com/questions/63365115/webpackis-missing-from-the-typescript-compilation-at-angularcompilerplugin),
reproducing sample app code [github](https://github.com/CP-Ram/ngtoolswebpacktestapp)

Is there anything else configuration i have to do?

**Comment by alan-agius4** [comment]
Hi @CP-Ram, 

Firstly you don't need to add an addition architect builder for the Web Worker, the browser builder (ng build) already handles that. See https://angular.io/guide/web-worker on how to generate a web worker using the CLI.

The problem here is that in your web worker tsconfig you are not including any files.

```ts
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
      "outDir": "../out-tsc/worker",
      "types": []
    },
    "include": [
      "src/webWorker/**/*.ts"
    ]
  }

```
