### ISSUE TITLE
--mobile component import

### ISSUE THREAD

**Issue by jordaofranca** [angular/angular-cli#1858]
I'm trying to import a new generated component to --mobile project and getting error from broccoli:

//app.component.ts

```
import { Component } from '@angular/core';
import { APP_SHELL_DIRECTIVES } from '@angular/app-shell';
import { FooComponent } from "./foo/foo.component";

@Component({
  moduleId: module.id,
  selector: 'app-root',
  template: `
  <app-foo></app-foo>
  `,
  styles: [],
  directives: [APP_SHELL_DIRECTIVES, FooComponent]
})
export class AppComponent {
  title = 'app works!';
}
```

//error from terminal

file changed app/app.component.ts
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: Command failed: node /home/jordao/code/halloween-go/node_modules/angular2-broccoli-prerender/dist/child_proc.js  --sourceHtml=/home/jordao/code/halloween-go/tmp/app_shell_plugin-input_base_path-MWsljrgh.tmp/0/index.html --optionsPath=/home/jordao/code/halloween-go/tmp/app_shell_plugin-input_base_path-MWsljrgh.tmp/0/main-app-shell --outputIndexPath=/home/jordao/code/halloween-go/tmp/app_shell_plugin-output_path-wKTE2SJZ.tmp/index.html
DEPRECATION WARNING: `document` is no longer supported and will be removed in next release. Please use `template`
DEPRECATION WARNING: `Bootloader#serializeApplication` arguments has changed.Please use an `AppConfig` interface {providers: Array<any>, directives: Array<any>, template?: string}
EXCEPTION: Failed to load /home/jordao/code/halloween-go/tmp/broccoli_type_script_compiler-cache_path-VBrh4nYV.tmp/src/app/foo/foo.component.html
Failed to load /home/jordao/code/halloween-go/tmp/broccoli_type_script_compiler-cache_path-VBrh4nYV.tmp/src/app/foo/foo.component.html

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

The broccoli plugin was instantiated at: 
    at AppShellPlugin.Plugin (/home/jordao/code/halloween-go/node_modules/broccoli-plugin/index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (/home/jordao/code/halloween-go/node_modules/broccoli-caching-writer/index.js:18:10)
    at new AppShellPlugin (/home/jordao/code/halloween-go/node_modules/angular2-broccoli-prerender/dist/prerender.js:15:16)
    at Angular2App._buildTree (/home/jordao/code/halloween-go/node_modules/angular-cli/lib/broccoli/angular2-app.js:154:48)
    at new Angular2App (/home/jordao/code/halloween-go/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/home/jordao/code/halloween-go/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/jordao/code/halloween-go/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/jordao/code/halloween-go/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/jordao/code/halloween-go/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/jordao/code/halloween-go/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /home/jordao/code/halloween-go/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/jordao/code/halloween-go/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jordao/code/halloween-go/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/jordao/code/halloween-go/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/jordao/code/halloween-go/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

**Comment by jordaofranca** [comment]
I think the error is caused by the new component are using templateUrls and html. When i change it to inline html it works. Why mobile is not getting html files in components?
