### ISSUE TITLE
Cannot read property 'hasInlines' of undefined

### ISSUE THREAD

**Issue by shyamal890** [angular/angular-cli#18612]
#18002 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.2.2

### Description
`ng build --prod` is giving the following error after upgrade to 10.0.12

## 🔥 Exception or Error
```
ERROR in TypeError: Cannot read property 'hasInlines' of undefined
    at TemplateTypeCheckerImpl.getDiagnosticsForFile (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\checker.js:123:28)
    at NgCompiler.getTemplateDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:487:106)
    at NgCompiler.getDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:141:97)
    at NgtscProgram.getNgSemanticDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@angular\compiler-cli\src\ngtsc\program.js:152:45)
    at checkDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@ngtools\webpack\src\diagnostics.js:47:27)
    at Object.gatherDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@ngtools\webpack\src\diagnostics.js:86:13)
    at AngularCompilerPlugin._emit (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:1081:54)
    at AngularCompilerPlugin._update (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:872:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## 🌍 Your Environment
```
Angular CLI: 10.0.7
Node: 10.16.1
OS: win32 x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cdk                      10.1.3
@angular/cli                      10.0.7
@angular/http                     7.2.16
@angular/material                 10.1.3
@ngtools/webpack                  10.0.7
@nguniversal/common               10.0.2
@nguniversal/express-engine       10.0.2
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0
```

**Comment by alan-agius4** [comment]
Seems like more of a compiler bug, transferring to the FW repo for a better triage. Although probably a reproduction would be needed.
