### ISSUE TITLE
[error] Error: Cannot find module '@angular/compiler-cli/src/tooling'

### ISSUE THREAD

**Issue by manel00** [angular/angular-cli#18645]
Came from install a Ionic 4 app from 1 year ago and it crashes but cannot understand why, how to deal with it? thank you

Node version: v12.18.3
NPM version: 6.14.8

`[error] Error: Cannot find module '@angular/compiler-cli/src/tooling'
Require stack:
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@ngtools/webpack/src/index.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/index.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/models/architect-command.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/commands/run-impl.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/utilities/json-schema.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/models/command-runner.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/lib/cli/index.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/lib/init.js
- /home/myuser/Documentos/Ionic_projects/xstories/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/myuser/Documentos/Ionic_projects/xstories/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/myuser/Documentos/Ionic_projects/xstories/node_modules/@ngtools/webpack/src/index.js:21:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
