### ISSUE TITLE
Guide on converting to Webpack? +ERRORS!

### ISSUE THREAD

**Issue by borntodesign** [angular/angular-cli#1893]
I have updated to:
1.0.0-beta.11-webpack.2

With regrets because now it seems I have to add a ton of modules everywhere I think and I cannot find good guides on how to do the conversion coming from an angular CLI perspective using the latest RC. 

Currently getting this error:

Uncaught Can't resolve all parameters for FeedComponent: (?).

No line number. No component reference. Not really specific at all.

I had actually finished my project for work and just wanted to use core-js for better IE support. I feel like I am at the beginning again. All I know is SystemJS.

**Comment by zsfarkas** [comment]
That was my first impression, too. But after a while it seems to be much cooler. It is much easier to include 3rd party libraries from node_modules folder. And it is way quicker than systemjs with broccoli. And you have angular2 RC5, as well.

Here are some [instructions](https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md).

**Comment by cuiliang** [comment]
try to import service directly from the source file defining the service (not index.ts which export service from other files).

**Comment by borntodesign** [comment]
@zsfarkas thats the guide I followed, however it seems webpack works quite differently from systemjs. For example I would have to: 

Include all the components in the bootstrap file?
Create feature modules?
Change change current imports to modules?
Typings seem to work differently?
Is it me or does the whole app not run if there is one error?

**Comment by borntodesign** [comment]
@cuiliang have you come across this error:

url_resolver.js:238 Uncaught TypeError: uri.match is not a function

**Comment by borntodesign** [comment]
I can't seem to set my app to use scss now either I get this:

ng set defaults.styleExt scss
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot read property 'serialize' of undefined
TypeError: Cannot read property 'serialize' of undefined
    at /Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:235:87
    at JsonSerializer.property (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/serializer.ts:100:9)
    at _loop_1 (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:235:32)
    at /Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:240:17
    at JsonSerializer.object (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/serializer.ts:88:9)
    at ObjectSchemaTreeNode.serialize (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:227:20)
    at /Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:231:92
    at JsonSerializer.property (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/serializer.ts:100:9)
    at _loop_1 (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:231:36)
    at /Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:240:17
    at JsonSerializer.object (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/serializer.ts:88:9)
    at ObjectSchemaTreeNode.serialize (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:227:20)
    at /Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:293:33
    at JsonSerializer.array (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/serializer.ts:107:9)
    at ArraySchemaTreeNode.serialize (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:291:20)
    at /Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:231:92
    at JsonSerializer.property (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/serializer.ts:100:9)
    at _loop_1 (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:231:36)
    at /Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:240:17
    at JsonSerializer.object (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/serializer.ts:88:9)
    at RootSchemaTreeNode.ObjectSchemaTreeNode.serialize (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-tree.ts:227:20)
    at GeneratedSchemaClass.SchemaClassBase.$$serialize (/Users/lorne/projects/hsi-magazine/node_modules/angular-cli/addon/ng2/models/json-schema/schema-class-factory.ts:141:25)

**Comment by aBitNomadic** [comment]
url_resolver.js:238 Uncaught TypeError: uri.match is not a function

Is the error you get when you have moduleID: module.id in your components. Remove this from all your components as its not needed in web pack and that will fix it.

Cannot read property 'serialize' of undefined

I see this type of error when my angular-cli.json file is missing fields. Check that you have all the fields for your version (i just ng init on a empty dir) and try to fix it. Also there was a update last night to webpack.8 which has support for the script and styles fields. You make want to upgrade to that.

**Comment by borntodesign** [comment]
@aBitNomadic The first error is gone but ng init shows my angular-cli.json is identical. I have tried and failed changing it manually ;)

**Comment by filipesilva** [comment]
Heya, we've added much more comprehensive instructions here for the latest release: https://github.com/angular/angular-cli#webpack-update
