### ISSUE TITLE
[Docs] Debug Angular CLI TS code

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#19050]
As per the instructions in article https://github.com/angular/angular-cli/blob/master/packages/angular/cli/README.md#debugging-with-vs-code , I was trying to debug angular CLI TS codebase. However, VSCode debugger errors out on startup

<img width="1381" alt="ng_debug" src="https://user-images.githubusercontent.com/13006107/95697295-43b4df00-0c0c-11eb-9e85-8eb6b2b77b3b.png">

```
Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:311
      throw err;
      ^

Error: Cannot find module '/Users/dev/work/tmp/angular-cli/node_modules/@angular-devkit/core/src/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/dev/work/tmp/angular-cli/dist/@angular/cli/utilities/config.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/dev/work/tmp/angular-cli/node_modules/@angular-devkit/core/package.json',
  requestPath: '@angular-devkit/core'
}
```

Also, the docs mention that one could add breakpoints to files under `dist/@angular` folder. Can we also add breakpoints to uncompiled TS code?

**Comment by alan-agius4** [comment]
Hi @prabh-62, 

Have you linked the built packages in your project (https://github.com/angular/angular-cli/blob/master/packages/angular/cli/README.md#working-with-master)? 

> Also, the docs mention that one could add breakpoints to files under dist/@angular folder. Can we also add breakpoints to uncompiled TS code?
Not with this type of testing

**Comment by prabh-62** [comment]
I tried `npm link` inside `dist/@angular/cli` folder and then `npm link @angular/cli` in the angular project. However, I kept getting the same error.

My intent is to debug TS code. Is it possible to debug typescript code with the VSCode debugger?
<img width="1386" alt="ng_ts_debug" src="https://user-images.githubusercontent.com/13006107/95776554-92a55780-0c92-11eb-80e7-1ecab39d96c4.png">

BTW, I am able to debug `ng` cli directly in the angular project from the node_modules **without git cloning** this repo. However, this is not what I am after.
<img width="1440" alt="ng_debug" src="https://user-images.githubusercontent.com/13006107/95777606-87ebc200-0c94-11eb-817a-90fe27e9e995.png">

**Comment by alan-agius4** [comment]
> My intent is to debug TS code. Is it possible to debug typescript code with the VSCode debugger?

Adding a breakpoint in the `.ts` sourcefile will not work, you need to add the breakpoints in the `.js` files.

**Comment by prabh-62** [comment]
I guess, then we can close this issue. It would still be interesting to know how one can contribute to angular CLI. I read the `CONTRIBUTING.md` file and the instructions weren't clear enough to dive into the codebase. Thanks for answering my questions and for responding to issues swiftly, Alan.
