### ISSUE TITLE
Can't use angular-cli at all typescript error everytime

### ISSUE THREAD

**Issue by giovapanasiti** [angular/angular-cli#1907]
I'm using OSX el capitain and i'm trying to install angular-cli. I'm not new to this, i've been using angular-cli from 2 months now on my ubuntu machine and everything was fine. Now I've installed this on my mac and no matter what i do i get the same error.

```
ng --version
/Users/giova-mbpro/node_modules/angular-cli/node_modules/typescript/lib/typescript.js:4274
});
^

SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/giova-mbpro/node_modules/angular-cli/lib/cli/index.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

My node version is: 4.5.0
My Typescript version is: 1.8.10

**Comment by giovapanasiti** [comment]
Sorry I'm a stupid, it works now I didn't have npm v3
