### ISSUE TITLE
MockBackend not working after update to *-beta.11-webpack.8

### ISSUE THREAD

**Issue by christiandreher** [angular/angular-cli#1914]
> **1.** OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 16.04

> **2.** Versions. Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.11-webpack.8
node: 6.3.1
os: linux x64

> **3.** Repro steps. Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

I had a project using \*-beta.10, which I updated manually to angular rc5. The app was created by angular-cli@1.0.0-beta.10 Yesterday I tried to update to \*-beta.11-webpack.8, and got a bunch of issues. I could eventually solve most of them, for example by removing all barrels and importing everything directly. But my unit tests don't work, at least not the ones that call a http service. I used a MockBackend to mimick the API. Before the update, everything worked as expected, but after the update, all those tests fail, complaining that *x* is not equal *y*, where *x* is the output of the **actual** API installed locally, and *y* the value I set for the MockBackend to respond (see below error message for example). So somehow my MockBackend returns are ignored

> **4.** The log given by the failure. Normally this include a stack trace and some more information.

```
Expected '0.1.0-alpha' to equal '"0.0.0"'.                                                                                                              
    at SafeSubscriber._next (webpack:///home/chris/workspace/my-webclient/src/app/shared/services/api/api.service.spec.ts:39:32 <- src/test.ts:28595:29)
    at SafeSubscriber.__tryOrUnsub (webpack:///home/chris/workspace/my-webclient/~/rxjs/Subscriber.js:225:0 <- src/test.ts:5725:16)
    at SafeSubscriber.next (webpack:///home/chris/workspace/my-webclient/~/rxjs/Subscriber.js:174:0 <- src/test.ts:5674:22)
    at Subscriber._next (webpack:///home/chris/workspace/my-webclient/~/rxjs/Subscriber.js:124:0 <- src/test.ts:5624:26)  
```

> **5.** Mention any other details that might be useful.

Here is what one of my tests looks like (excerpt for the above error message)

```typescript
import { addProviders, async, inject } from '@angular/core/testing';
import { HTTP_PROVIDERS, Response, ResponseOptions } from '@angular/http';
import { MockBackend } from '@angular/http/testing';

import { ApiService } from './api.service';

describe('Service: Api', () => {
    let service : ApiService;
    let mock : MockBackend;

    beforeEach(() => {
        addProviders([HTTP_PROVIDERS, MockBackend, ApiService]);
    });

    beforeEach(inject([ApiService, MockBackend], (apiService, mockBackend) => {
        service = apiService;
        mock = mockBackend;
    }));

    it('should initialize', () => {
        expect(service).toBeTruthy();
    });

    // This fails, returning actual values from my local API
    it('should fetch API version number', (done) => {
        let response = '"0.0.0"';
        let responseOptions = new ResponseOptions({body: response});

        mock.connections.subscribe(
            (c) => {
                console.log('mock connection called');
                c.mockRespond(new Response(responseOptions));
            }
        );

        service.getApiVersionNumber().subscribe(
            (version : string) => {
                expect(version).toEqual('"0.0.0"');
            },
            (error) => {
                fail(error);
            },
            () => {
                done();
            }
        );
    });

/** ... */
```

Note: the log 'mock connection called' will never be printed.

**Comment by christiandreher** [comment]
This was actually a issue in my code. I finally figured it out. The fix is to replace the first `beforeEach` definition in my code above with the following:

```typescript
    beforeEach(() => {
        addProviders([
            MockBackend,
            BaseRequestOptions,
            ApiService,
            provide(
                Http,
                {
                    useFactory: (backend, defaultOptions) => {
                        return new Http(backend, defaultOptions);
                    },
                    deps: [MockBackend, BaseRequestOptions]
                }
            )
        ]);
    });
```

I thought that it was a ng-cli@webpack issue since it worked before the way I had it above. Closing this now, and sorry for the inconvenience
