### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by cladera** [angular/angular-cli#1957]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OS
Mac OSX Yosemite

node.js
v4.2.4

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

1.0.0-beta.11-webpack.8

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
- npm uninstall angular-cli -g
- npm install angular-cli@webpack -g
- rm -rf node_modules tmp dist
- npm install angular-cli@webpack --save-dev
- ng build

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.require.extensions..ts (/opt/local/lib/node_modules/angular-cli/lib/bootstrap-local.js:30:14)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/cgcladera/Projects/ws-v4/webcastudio-wms/node_modules/angular-cli/addon/ng2/models/config.ts:7:16)
    at Module._compile (module.js:435:26)
    at Object.require.extensions..ts (/opt/local/lib/node_modules/angular-cli/lib/bootstrap-local.js:30:14)
```

**Comment by ghpabs** [comment]
You need to install Node 6.

**Comment by cladera** [comment]
Yeah, that's what I guessed. Will it be a requirement from now on?

**Comment by ghpabs** [comment]
I guess so. ES6 FTW.

**Comment by gelliott181** [comment]
With Node v6 LTS coming up in a month I'm all for bumping the required version up.

**Comment by alanjhonnes** [comment]
I managed to run it on node 4.4.7 by running "node --harmony node_modules/.bin/ng build" instead of "ng build". You can use that for any other command and pass parameters too.

Let me know if it worked for you.

**Comment by cladera** [comment]
Thanks @alanjhonnes, nice workaround I upgraded to node 6.5, though.

Once it was confirmed this issue is because Node's version, the issue derived to a question, "Will it be necessary upgrade node to 6.5 in order to use angular-cli?"

**Comment by filipesilva** [comment]
You shouldn't need node6 with the `beta.14`. We've moved to compiling everything beforehand.
