### ISSUE TITLE
"ng build --prod" fails with TypeError when NODE_ENV is set to "development"

### ISSUE THREAD

**Issue by j-a-h-i-r** [angular/angular-cli#19677]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Is this a regression?

 I am not sure. I have not encountered this error before.

### Description

I have added a script in `package.json` to generate dist files for production. 
```
{
  "scripts": {
    "build:prod": "ng build --prod --output-path dist"
  }
}
```

When I run `npm run build:prod`  and the `NODE_ENV` is set to `development` in the terminal, I get the following error,
```
Error: TypeError: Cannot read property 'kind' of undefined
    at D:\myproject\node_modules\typescript\lib\typescript.js:2562:166
    at assert (D:\myproject\node_modules\typescript\lib\typescript.js:2483:127)
    at Object.assertNode (D:\myproject\node_modules\typescript\lib\typescript.js:2562:17)
    at visitNode (D:\myproject\node_modules\typescript\lib\typescript.js:78336:18)
```

When I set `NODE_ENV` to anything other than `development`, it works fine.

## 🔬 Minimal Reproduction

Add the following to the `scripts` section of the `package.json` file,
```
"build:prod": "ng build --prod --output-path dist"
```

Set `NODE_ENV` to `development` and run the script. Run the following lines on powershell (I'm on windows 10).
```
$env:NODE_ENV="development"
npm run build:prod
```

## 🔥 Exception or Error
<pre><code>
Error: TypeError: Cannot read property 'kind' of undefined
    at D:\myproject\node_modules\typescript\lib\typescript.js:2562:166
    at assert (D:\myproject\node_modules\typescript\lib\typescript.js:2483:127)
    at Object.assertNode (D:\myproject\node_modules\typescript\lib\typescript.js:2562:17)
    at visitNode (D:\myproject\node_modules\typescript\lib\typescript.js:78336:18)
    at Object.visitEachChild (D:\myproject\node_modules\typescript\lib\typescript.js:78738:124)
    at visitor (D:\myproject\node_modules\@ngtools\webpack\src\transformers\make_transform.js:60:31)
    at visitNode (D:\myproject\node_modules\typescript\lib\typescript.js:78322:23)
    at Object.visitEachChild (D:\myproject\node_modules\typescript\lib\typescript.js:78736:172)
    at visitor (D:\myproject\node_modules\@ngtools\webpack\src\transformers\make_transform.js:60:31)
    at visitNodes (D:\myproject\node_modules\typescript\lib\typescript.js:78375:48)
    at visitLexicalEnvironment (D:\myproject\node_modules\typescript\lib\typescript.js:78415:22)
    at Object.visitEachChild (D:\myproject\node_modules\typescript\lib\typescript.js:78798:55)
    at visitor (D:\myproject\node_modules\@ngtools\webpack\src\transformers\make_transform.js:60:31)
    at Object.visitNode (D:\myproject\node_modules\typescript\lib\typescript.js:78322:23)
    at transformer (D:\myproject\node_modules\@ngtools\webpack\src\transformers\make_transform.js:67:31)
    at transformSourceFileOrBundle (D:\myproject\node_modules\typescript\lib\typescript.js:79477:57)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.0.5
Node: 14.15.0
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router   
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
