### ISSUE TITLE
How to make ng new use RC6 by default?

### ISSUE THREAD

**Issue by lednhatkhanh** [angular/angular-cli#1968]
`ng new` still create RC5 project, how to make it use RC6 instead?

**Comment by monojack** [comment]
The latest commits are not released on npm yet. If you've installed the cli with npm (`npm install -g angular-cli`) then you'd still be stuck on RC5.

If you'd like to tryout RC6 or any other features implemented before release you can:

1. `npm uninstall -g angular-cli`
2. clone this repo and run `npm link` to install the dependencies and link it to the global npm. _(makes a symlink to this folder inside the global `node_modules` folder)_

You can read more about it, in the docs, [here](https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli). Just remember to link your old projects with `npm link angular-cli` or use `--link-cli` flag when creating a new project to link to the new cli otherwise you'll be downloading and using another copy of it _(the npm version)_ inside your project's `node_modules`

**Comment by kjartanvalur** [comment]
I´m trying to do this but get the following errors

`ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'directoryExists' of undefined
    at Object.getAutomaticTypeDirectiveNames (C:\Data\PROGRAMS\angular-cli\node_modules\typescript\lib\typescript.js:43865:17)
    at State.loadTypesFromConfig (C:\Data\PROGRAMS\angular-cli\node_modules\awesome-typescript-loader\src\host.ts:150:36)
    at new State (C:\Data\PROGRAMS\angular-cli\node_modules\awesome-typescript-loader\src\host.ts:144:14)
    at Object.ensureInstance (C:\Data\PROGRAMS\angular-cli\node_modules\awesome-typescript-loader\src\instance.ts:150:19)
    at compiler (C:\Data\PROGRAMS\angular-cli\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (C:\Data\PROGRAMS\angular-cli\node_modules\awesome-typescript-loader\src\index.ts:18:18)
 @ multi main`

**Comment by Chabane** [comment]
@kjartanvalur I have the same error.

**Comment by nukuuk** [comment]
+1

**Comment by bjsawyer** [comment]
@monojack's method seems to be working properly now that master has been updated to use typescript@2.0.2 and awesome-typescript-loader@2.2.3 ( #1993).

**Comment by filipesilva** [comment]
Latest release (`beta.14`) uses Angular 2 final.
