### ISSUE TITLE
Serve fails(but build passes): Cannot read property 'visit' of undefined

### ISSUE THREAD

**Issue by sahilbabbar** [angular/angular-cli#19749]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: `v6.0.3`

### Description
While updating an Angular Library based on `v6.0.3` to `v11.0.6`, the following issue is encountered.

After updating d3 to `v6.2.0` and Angular to latest `v11.0.6`, getting the following error while doing `ng build --prod`. Earlier with d3 `v5.4.0` and Angular `v6.0.3`, everything was working fine.

## 🔬 Minimal Reproduction

It seems that `event` is being referred from the following code:
```
import * as d3 from 'd3';
// Save x,y cordinates on drag start.
this.originalX = d3.event.x;
this.originalY = d3.event.y;
d3.event.sourceEvent.stopPropagation();
```

After googling a bit, someone suggested to install `@types/d3` and then try; but after installing it, Webstorm starts to throw error on the usage of `d3.event`.

```
TS2339: Property 'event' does not exist on type 'typeof import("<path-to-project>/node_modules/@types/d3/index")'.
```

## 🔥 Exception or Error
<pre><code>
"export 'event' was not found in 'd3'
    at HarmonyImportSpecifierDependency._getErrors (<application-path>\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (<application-path>\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (<application-path>\node_modules\webpack\lib\Compilation.js:1463:22)
    at hooks.finishModules.callAsync.err (<application-path>\node_modules\webpack\lib\Compilation.js:1258:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<application-path>\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:53:1)
    at AsyncSeriesHook.lazyCompileHook (<application-path>\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (<application-path>\node_modules\webpack\lib\Compilation.js:1253:28)
    at hooks.make.callAsync.err (<application-path>\node_modules\webpack\lib\Compiler.js:672:17)
    at _done (eval at create (<application-path>\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err1 (eval at create (<application-path>\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:36:22)
    at _addModuleChain (<application-path>\node_modules\webpack\lib\Compilation.js:1185:12)
    at processModuleDependencies.err (<application-path>\node_modules\webpack\lib\Compilation.js:1097:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

Error: ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '<application-path>\src'
resolve 'core-js/es7/reflect' in '<application-path>\src'
  Parsed request is a module
  using description file: <application-path>\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/SB/Code/EGI/POCs/upgradingToAngularV11/emmui-v11
        using description file: <application-path>\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: <application-path>\package.json (relative path: ./core-js/es7/reflect)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\core-js\es7\reflect doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\core-js\es7\reflect.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\core-js\es7\reflect.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\core-js\es7\reflect.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\core-js\es7\reflect.js doesn't exist
            as directory
              <application-path>\core-js\es7\reflect doesn't exist
      <application-path>\src\node_modules doesn't exist or is not a directory
      <application-path>\POCs\upgradingToAngularV11\node_modules doesn't exist or is not a directory
      <application-path>\POCs\node_modules doesn't exist or is not a directory
      <directory-path>\node_modules doesn't exist or is not a directory
      C:\SB\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in <application-path>\node_modules
        using description file: <application-path>\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in <application-path>\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
          using description file: <application-path>\node_modules\core-js\package.json (relative path: ./es7/reflect)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\node_modules\core-js\es7\reflect doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\node_modules\core-js\es7\reflect.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\node_modules\core-js\es7\reflect.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\node_modules\core-js\es7\reflect.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              <application-path>\node_modules\core-js\es7\reflect.js doesn't exist
            as directory
              <application-path>\node_modules\core-js\es7\reflect doesn't exist
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          <application-path>\node_modules\core-js\es7\reflect doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          <application-path>\node_modules\core-js\es7\reflect.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
          <application-path>\node_modules\core-js\es7\reflect.tsx doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
          <application-path>\node_modules\core-js\es7\reflect.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          <application-path>\node_modules\core-js\es7\reflect.js doesn't exist
        as directory
          <application-path>\node_modules\core-js\es7\reflect doesn't exist
[<application-path>\core-js\es7\reflect]
[<application-path>\core-js\es7\reflect.ts]
[<application-path>\core-js\es7\reflect.tsx]
[<application-path>\core-js\es7\reflect.mjs]
[<application-path>\core-js\es7\reflect.js]
[<application-path>\src\node_modules]
[<application-path>\POCs\upgradingToAngularV11\node_modules]
[<application-path>\POCs\node_modules]
[<directory-path>\node_modules]
[C:\<folder>\node_modules]
[C:\node_modules]
[<application-path>\node_modules\package.json]
[<application-path>\node_modules\core-js\es7\reflect]
[<application-path>\node_modules\core-js\es7\reflect.ts]
[<application-path>\node_modules\core-js\es7\reflect.tsx]
[<application-path>\node_modules\core-js\es7\reflect.mjs]
[<application-path>\node_modules\core-js\es7\reflect.js]
[<application-path>\node_modules\core-js\es7\reflect\package.json]
[<application-path>\node_modules\core-js\es7\reflect]
[<application-path>\node_modules\core-js\es7\reflect.ts]
[<application-path>\node_modules\core-js\es7\reflect.tsx]
[<application-path>\node_modules\core-js\es7\reflect.mjs]
[<application-path>\node_modules\core-js\es7\reflect.js]
 @ ./src/polyfills.ts 40:0-29
 @ multi ./node_modules/@angular-devkit/build-angular/src/webpack/es5-polyfills.js ./src/polyfills.ts

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.6
Node: 10.15.0
OS: win32 x64

Angular: 11.0.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   0.1100.6
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@angular/cli                    11.0.6
@angular/http                   7.2.16
@schematics/angular             11.0.6
@schematics/update              0.1100.6
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by sahilbabbar** [comment]
Answered at https://github.com/d3/d3/issues/3457.
