### ISSUE TITLE
Building fails from the dist directory

### ISSUE THREAD

**Issue by danbraik** [angular/angular-cli#19855]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I think it's a minor bug.
When building with `ng build` from the 'dist', it fails. Maybe because the directory is deleted and then it makes non sense with current path.

## 🔬 Minimal Reproduction

```
ng new
# answer questions basically
mkdir -p myproject/dist/myproject
cd myproject/dist/myproject
ng build
```

## 🔥 Exception or Error
<pre><code>

<pre>internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^

Error: ENOENT: no such file or directory, uv_cwd
<font color="#555753">    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:128:26)</font>
    at process.cwd (/tmp/a/aa/node_modules/<u style="text-decoration-style:single">graceful-fs</u>/polyfills.js:10:19)
    at Yargs (/tmp/a/aa/node_modules/<u style="text-decoration-style:single">@angular</u>/compiler-cli/node_modules/<u style="text-decoration-style:single">yargs</u>/yargs.js:45:27)
    at Argv (/tmp/a/aa/node_modules/<u style="text-decoration-style:single">@angular</u>/compiler-cli/node_modules/<u style="text-decoration-style:single">yargs</u>/index.js:13:16)
    at Object.&lt;anonymous&gt; (/tmp/a/aa/node_modules/<u style="text-decoration-style:single">@angular</u>/compiler-cli/node_modules/<u style="text-decoration-style:single">yargs</u>/index.js:8:1)
<font color="#555753">    at Module._compile (internal/modules/cjs/loader.js:999:30)</font>
<font color="#555753">    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)</font>
<font color="#555753">    at Module.load (internal/modules/cjs/loader.js:863:32)</font>
<font color="#555753">    at Function.Module._load (internal/modules/cjs/loader.js:708:14)</font>
<font color="#555753">    at Module.require (internal/modules/cjs/loader.js:887:19)</font> {
  errno: <font color="#C4A000">-2</font>,
  code: <font color="#4E9A06">&apos;ENOENT&apos;</font>,
  syscall: <font color="#4E9A06">&apos;uv_cwd&apos;</font>
}
<font color="#EF2929"><b>An unhandled exception occurred: NGCC failed.</b></font>
<font color="#EF2929"><b>See &quot;/tmp/ng-ZpT6na/angular-errors.log&quot; for further details.</b></font>
</pre>
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.8
Node: 12.20.1
OS: linux x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. This is caused by Node.js crashes when `process.cwd()` is invoked after the CWD is deleted.

In general you should avoid running commands in directories which are going to be deleted.

Reproduction without Angular CLI
```
$ mkdir -p testing-cwd/dist
$ cd testing-cwd
$ echo "const cwd = require('path').resolve('./dist'); process.chdir(cwd); require('fs').rmdirSync(cwd); console.log(process.cwd());" >> index.js
$ node index.js


internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at Object.<anonymous> (/Users/alanagius/cli-reproductions/testing-cwd/index.js:1:118)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

```
