### ISSUE TITLE
Error when i am trying to run project 

### ISSUE THREAD

**Issue by mabdeen84** [angular/angular-cli#1988]
The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory: typings
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/angular-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31)
    at new Funnel (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/lib/broccoli/angular2-app.js:93:7)
    at new Angular2App (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/mabdeen/Dropbox/WS/TrainingManagement/Src/TrainingSolution/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by filipesilva** [comment]
`npm run typings` in the project should solve your issue. We don't support the version you're using anymore though, and encourage you to follow https://github.com/angular/angular-cli#webpack-update to update your project.
