### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'directoryExists' of undefined

### ISSUE THREAD

**Issue by aderbas** [angular/angular-cli#1997]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

 **Linux, Ubuntu 14.04**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

```
$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

**I had the error on a project and decided to create a new one for testing.** 
```
$ ng new apptest2
$ cd apptest2
$ ng build
```
**I have not changed anything.**

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
$ ng build
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
 10% building modules 6/12 modules 6 active ...de_modules/script-loader/addScript.jsTypeError: Cannot read property 'directoryExists' of undefined
    at Object.getAutomaticTypeDirectiveNames (/var/www/html/apptest2/node_modules/typescript/lib/typescript.js:43865:17)
    at State.loadTypesFromConfig (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/host.ts:150:36)
    at new State (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/host.ts:144:14)
    at Object.ensureInstance (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/instance.ts:150:19)
    at compiler (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/index.ts:18:18)
    at LOADER_EXECUTION (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:95:14)
    at runSyncOrAsync (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:96:4)
    at iterateNormalLoaders (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
    at iterateNormalLoaders (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:189:10)
    at /var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:204:3
    at Object.context.callback (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:87:13)
    at Object.module.exports (/var/www/html/apptest2/node_modules/angular2-template-loader/index.js:32:10)
    at LOADER_EXECUTION (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:95:14)
    at runSyncOrAsync (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:96:4)
    at iterateNormalLoaders (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
    at /var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:173:4
    at Storage.finished (/var/www/html/apptest2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /var/www/html/apptest2/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3) 'TypeError: Cannot read property \'directoryExists\' of undefined\n    at Object.getAutomaticTypeDirectiveNames (/var/www/html/apptest2/node_modules/typescript/lib/typescript.js:43865:17)\n    at State.loadTypesFromConfig (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/host.ts:150:36)\n    at new State (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/host.ts:144:14)\n    at Object.ensureInstance (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/instance.ts:150:19)\n    at compiler (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/index.ts:37:20)\n    at Object.loader (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/index.ts:18:18)\n    at LOADER_EXECUTION (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:95:14)\n    at runSyncOrAsync (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:96:4)\n    at iterateNormalLoaders (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:200:2)\n    at iterateNormalLoaders (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:189:10)\n    at /var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:204:3\n    at Object.context.callback (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:87:13)\n    at Object.module.exports (/var/www/html/apptest2/node_modules/angular2-template-loader/index.js:32:10)\n    at LOADER_EXECUTION (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:95:14)\n    at runSyncOrAsync (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:96:4)\n    at iterateNormalLoaders (/var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:200:2)\n    at /var/www/html/apptest2/node_modules/loader-runner/lib/LoaderRunner.js:173:4\n    at Storage.finished (/var/www/html/apptest2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)\n    at /var/www/html/apptest2/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)'
1044ms building modules                                                              
1ms sealing 
0ms optimizing 
0ms basic module optimization 
1ms module optimization 
0ms advanced module optimization 
2ms basic chunk optimization        
0ms chunk optimization 
0ms advanced chunk optimization 
1ms module and chunk tree optimization 
1ms module reviving 
0ms module order optimization 
1ms module id optimization 
2ms chunk reviving 
0ms chunk order optimization 
1ms chunk id optimization 
2ms hashing 
0ms module assets processing 
5ms chunk assets processing 
0ms additional chunk assets processing 
0ms recording 
0ms additional asset processing 
72ms chunk asset optimization
31ms asset optimization
6ms emitting 
Hash: bbc4834236db6d10b21a
Version: webpack 2.1.0-beta.21
Time: 1189ms
            Asset       Size  Chunks             Chunk Names
 styles.bundle.js      29 kB    0, 3  [emitted]  styles
scripts.bundle.js     128 kB    1, 3  [emitted]  scripts
   main.bundle.js  999 bytes    2, 3  [emitted]  main
        inline.js    5.53 kB       3  [emitted]  inline
       styles.map    37.5 kB    0, 3  [emitted]  styles
      scripts.map     150 kB    1, 3  [emitted]  scripts
         main.map   91 bytes    2, 3  [emitted]  main
       inline.map    5.59 kB       3  [emitted]  inline
       index.html  866 bytes          [emitted]  
assets/.npmignore    0 bytes          [emitted]  
chunk    {0} styles.bundle.js, styles.map (styles) 28.5 kB {3} [initial] [rendered]
chunk    {1} scripts.bundle.js, scripts.map (scripts) 128 kB {0} [initial] [rendered]
chunk    {2} main.bundle.js, main.map (main) 793 bytes {1} [initial] [rendered]
chunk    {3} inline.js, inline.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'directoryExists' of undefined
    at Object.getAutomaticTypeDirectiveNames (/var/www/html/apptest2/node_modules/typescript/lib/typescript.js:43865:17)
    at State.loadTypesFromConfig (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/host.ts:150:36)
    at new State (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/host.ts:144:14)
    at Object.ensureInstance (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/instance.ts:150:19)
    at compiler (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/var/www/html/apptest2/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  3.15 kB       0       
    chunk    {0} index.html 687 bytes [entry] [rendered]
```

- package.json:

```
{
  "name": "apptest2",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "core-js": "^2.4.0",
    "leaflet": "^0.7.7",
    "rxjs": "5.0.0-beta.11",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/leaflet": "^1.0.31",
    "angular-cli": "1.0.0-beta.11-webpack.8",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.3",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.0"
  }
}
```

**Comment by sholzmayer** [comment]
+1

**Comment by Ranfty** [comment]
+1

**Comment by osmanm786** [comment]
+1

**Comment by tomwanzek** [comment]
+1

**Comment by thlem** [comment]
+1 but not on my computer. I did the migration from RC4 to RC5 between monday and Wednesday (last week) and I did not have the issue.
My collegue just merge my work today and he starts to do the migration (npm install -g etc) and has this issue.

**Comment by JSMike** [comment]
I just started a new project based on the current master and received the same error upon `ng serve`

**Comment by JSMike** [comment]
Issue is with `awesome-typescript-loader`, i removed the ^ from the package.json to use version 2.2.1 specifically and now it's working

**Comment by danyel** [comment]
that didn't work for me

**Comment by fredrik-lundin** [comment]
+1

My package.json doesn't even include awesome-typescript-loader. Project created with, and still using angular-cli: 1.0.0-beta.11-webpack.8. 

Works on one PC: win 10, node 6.2.1, npm 3.10.7
Not on another PC: win 7, node 6.5.0, npm 3.10.3

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'directoryExists' of undefined
    at Object.getAutomaticTypeDirectiveNames (C:\git-repos\ang2-study-helper\node_modules\typescript\lib\typescript.js:43865:17)
    at State.loadTypesFromConfig (C:\git-repos\ang2-study-helper\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\host.ts:150:36)
    at new State (C:\git-repos\ang2-study-helper\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\host.ts:144:14)
    at Object.ensureInstance (C:\git-repos\ang2-study-helper\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\instance.ts:150:19)
    at compiler (C:\git-repos\ang2-study-helper\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (C:\git-repos\ang2-study-helper\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\index.ts:18:18)
 @ multi main

**Comment by aderbas** [comment]
@JSMike how I generate the bin file of the angular-cli with the change you made in package.json?
@fredrik-lundin This change was made in package.json of angular-cli, not in created project.

**Comment by JSMike** [comment]
@aderbas [See this article](https://www.gurustop.net/blog/2016/07/24/angular2-angularcli-load-cli-from-git-github-master-webpack) on cloning angular-cli, using `npm link` and `ng new <project-name> --link-cli`

**Comment by jianliao** [comment]
@fredrik-lundin You can just add "awesome-typescript-loader": "2.2.1" to your package.json.

**Comment by webartistkb** [comment]
"awesome-typescript-loader": "2.2.1" fixed it!!

**Comment by aderbas** [comment]
Yeah, fix here:
```
$ ng new foobar
$ cd foobar
$ npm install awesome-typescript-loader@2.2.1 --save-dev
$ ng serve
```
Thanks guys

**Comment by tomwanzek** [comment]
Thanks! Worked as a temporary (:wink:) fix on an existing project locally and propagated well to the related Travis test config.

**Comment by netmikey** [comment]
Dynamic transitive dependencies in action... :( why not avoid `^`'s and `~`'s in version declarations altogether?

**Comment by kylecordes** [comment]
As other has said, can we *please* not use ^? I just spotted a ^ on the way in (for TS ^2.0.2) and asked about it there. It seems like now is a good stop to proactively stop the breakage which has hit CLI several times over the last several months.

**Comment by don-bluelinegrid** [comment]
Hmm.  I have this exact issue, also using awesome-typescript-loader.  Was already using v2.2.1 when the issue showed up - I see the issue only on Linux, but the same build works fine on Mac OS X Unix.

So, presumably using v2.2.1 would not be a fix, since the error occurs with that version.

**Comment by splintercode** [comment]
Yeah just ran into this as well. Adding `"awesome-typescript-loader": "2.2.1"` to the devDependencies worked as a temp fix.

**Comment by waterscar** [comment]
Just adding 2.2.1 to dev didn't resolve the issue for me, however, then after removing `node_modules\.2.2.3@awesome-typescript-loader`, the error was gone.

Then I start over with a new project and try to find why 2.2.3 version was included using `npm ls`, ...and it turned out to be the angular-cli package itself. I'm new to npm so I'm not sure if I understood this correctly, it feels confusing that the cli was dependent on a lib that blocks itself from working normally.

![2016-09-07 3 19 41](https://cloud.githubusercontent.com/assets/769637/18303351/53c7ad16-750f-11e6-9046-c1ca200718ee.png)

**Comment by netmikey** [comment]
@waterscar That's the magic of dynamic transitive dependencies. angular-cli declares the dependency as `"awesome-typescript-loader": "^2.2.1",`, the `^` is what's important here. That means (in simplified terms): "Any version of the awesome-typescript-loader that looks like '2.x.x'". 

At the time the developers declared this dependency, version 2.2.1 was the current version and it worked. But what if the awesome-typescript-loader project publishes new versions 2.2.2 and 2.2.3? Anyone who `npm build`s his project from that point in time on will get the new 2.2.3 version, which in this case is either not backward compatible (enough) or has a bug.

Whatever it is, dynamic transitive dependencies are bad and we should stop using them.

**Comment by Toadskin** [comment]
The "awesome" fix resolved the issue of trying to access directoryExists on undefined but now there are a half dozen _"Type 'Type' is not generic"_ errors in config.d.ts, router.d.ts and router_state.d.ts:

**ERROR in [default] ...\node_modules\@angular\router\src\router.d.ts:216:35 
Type 'Type' is not generic.**

As you can tell it's a Windows machine in this case but otherwise the same RC5 with Typescript 2.0.0 etc.  

It's choking on nested generics:  

`export declare type LoadChildrenCallback = () => Type<any> | Promise<Type<any>> | Observable<Type<any>>;`

**Comment by matthiasbalke** [comment]
@Toadskin Did you try pinning `"typescript": "2.0.0"`? I had a lot of errors after generating the project, because a newer typescript version was choosen.

**Comment by RicardoVaranda** [comment]
+1

**Comment by Toadskin** [comment]
Adding awesome-typescript-loader pinned to 2.2.1 is a partial solution.  I found you must **a**) clear your  npm cache, **b**)  delete node_modules folder from your project,  **c**) remove ^ so you get the precise version you are asking for (2.2.2 versus 2.X.X).  

Even then you will get a slew of **ERR!** messages during npm install (clearly that must be remedied) but the subsequent ng build will succeed.   

BTW, the router error referenced above (Type "Type" is not generic) goes away when removing the caret from the @angular/router version.  

I wonder if semantic versioning has to be written off as a good idea that fails in practice, because there is no means of ensuring successive 1.X.X versions are compatible with previous 1.X.X versions.

**Comment by RicardoVaranda** [comment]
I've set awesome-typescript-loader to 2.2.1 without the ^ before doing an npm install on a fresh install of npm since in using docker container and this error is still present has anyone managed to fix it?

**Comment by pdelorme** [comment]
Just type this in your project :
`npm install awesome-typescript-loader@2.2.1`

**Comment by vkniazeu** [comment]
@pdelorme, this package should be a dev dependency, it's not needed for production. The line should be:
```
npm install awesome-typescript-loader@2.2.1 --save-dev
```

**Comment by filipesilva** [comment]
This has since been fixed, and should be present in beta.14+.

**Comment by zhang14725804** [comment]
Module build failed: TypeError: Cannot read property 'replace' of undefined
    at Object.Angular2HMRLoader


version：
Angular CLI: 8.0.2
Node: 10.16.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.2
@angular-devkit/core         8.0.2
@angular-devkit/schematics   8.0.2
@schematics/angular          8.0.2
@schematics/update           0.800.2
rxjs                         6.4.0

**Comment by zhang14725804** [comment]
"dependencies": {
    "@angular/animations": "~4.0.3",
    "@angular/common": "~4.0.3",
    "@angular/compiler": "~4.0.3",
    "@angular/core": "~4.0.3",
    "@angular/forms": "~4.0.3",
    "@angular/http": "~4.0.3",
    "@angular/platform-browser": "~4.0.3",
    "@angular/platform-browser-dynamic": "~4.0.3",
    "@angular/platform-server": "~4.0.3",
    "@angular/router": "~4.0.3",
    "@angularclass/conventions-loader": "^1.0.13",
    "@angularclass/hmr": "~1.2.2",
    "@angularclass/hmr-loader": "~3.0.2",
    "@types/jquery": "^2.0.34",
    "@types/snapsvg": "^0.4.28",
    "angular2-infinite-scroll": "^0.3.5",
    "angular2-toastr": "^1.0.6",
    "core-js": "^2.4.1",
    "echarts": "^3.7.1",
    "http-server": "^0.9.0",
    "ie-shim": "^0.1.0",
    "jquery": "^3.1.1",
    "ng2-dnd": "^4.0.2",
    "ng2-select": "^1.2.0",
    "ng2-validation": "^4.2.0",
    "ngx-bootstrap": "^1.9.3",
    "ngx-bootstrap-modal": "^1.1.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.0.2",
    "snapsvg": "^0.5.1",
    "zone.js": "~0.8.5"
  },
  "devDependencies": {
    "@angular/cli": "^1.1.1",
    "@angular/compiler-cli": "~4.0.3",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.45",
    "@types/node": "^7.0.13",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.6.28",
    "@types/webpack": "^2.2.15",
    "add-asset-html-webpack-plugin": "^1.0.2",
    "ag-grid": "^13.3.1",
    "ag-grid-angular": "^13.3.0",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.5.1",
    "awesome-typescript-loader": "3.1.2",
    "bootstrap-select": "^1.12.4",
    "codelyzer": "~2.1.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "echarts": "^3.7.1",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "~2.1.0",
    "file-loader": "^0.11.1",
    "find-root": "^1.0.0",
    "gh-pages": "^0.12.0",
    "html-webpack-plugin": "^2.28.0",
    "imports-loader": "^0.7.1",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "istanbul-instrumenter-loader": "2.0.0",
    "jasmine-core": "^2.5.2",
    "json-loader": "^0.5.4",
    "karma": "^1.6.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-remap-coverage": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "~2.0.3",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "~2.0.0",
    "ngx-echarts": "^1.2.4",
    "node-sass": "^4.12.0",
    "npm-run-all": "^4.0.2",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.2",
    "protractor": "^5.1.1",
    "raw-loader": "0.5.1",
    "rimraf": "~2.6.1",
    "sass-loader": "^6.0.7",
    "script-ext-html-webpack-plugin": "^1.7.1",
    "source-map-loader": "^0.2.1",
    "string-replace-loader": "~1.2.0",
    "style-loader": "^0.16.1",
    "to-string-loader": "^1.1.5",
    "ts-node": "^3.0.2",
    "tslib": "^1.6.1",
    "tslint": "~4.5.1",
    "tslint-loader": "^3.5.2",
    "typedoc": "^0.5.10",
    "typescript": "~2.2.2",
    "url-loader": "^0.5.8",
    "webpack": "~2.4.1",
    "webpack-dev-middleware": "^1.10.1",
    "webpack-dev-server": "~2.4.2",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-merge": "~4.1.0"
  }

**Comment by zhang14725804** [comment]
@aderbas @sholzmayer @Ranfty @danyel @osmanm786
