### ISSUE TITLE
Improve error message when an unknown environment is specified

### ISSUE THREAD

**Issue by netmikey** [angular/angular-cli#2002]
> ## Please provide us with the following information:
1. OS?  Mac OSX El Capitan
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:

```
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: darwin x64
```
1. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Run `npm run build -- -env=unknown` where `unknown` is a non-configured environment.
1. The log given by the failure. Normally this include a stack trace and some
   more information.

```
Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at Object.getWebpackCommonConfig (/proj/node_modules/angular-cli/addon/ng2/models/webpack-build-common.ts:128:80)
    at new NgCliWebpackConfig (/proj/node_modules/angular-cli/addon/ng2/models/webpack-config.ts:13:30)
    at Class.run (/proj/node_modules/angular-cli/addon/ng2/tasks/build-webpack.ts:16:22)
    at Class.run (/proj/node_modules/angular-cli/addon/ng2/commands/build.ts:49:26)
    at Class.<anonymous> (/proj/node_modules/angular-cli/lib/models/command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (/proj/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/proj/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/proj/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/proj/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
1. Mention any other details that might be useful.

... the issue was that the specified environment was unknown, but the error stack trace is very irritating.

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by n1try** [comment]
Couldn't get this working, even when specifying a correct (or even no) environment. Still getting the same error. Node version 6.5.0, angular-cli version 1.0.0-beta.11-webpack.8 on Windows 10.

**Comment by hansl** [comment]
Closing this as obsolete. We do show an error.
