### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with TSC 2.0

### ISSUE THREAD

**Issue by BartVDACodeware** [angular/angular-cli#2005]
1. OS  Windows 10.

2. Versions. 
angular-cli: 1.0.0-beta.10
node: 6.5.0
os: win32 x64

3. Repro steps. 

ng new MyApp
cd MyApp
npm install typescript@rc
ng serve

4. stack trace:
(node:24044) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/app.component.spec.ts (6, 1): Cannot find name 'describe'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/app.component.spec.ts (7, 3): Cannot find name 'beforeEach'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/app.component.spec.ts (11, 3): Cannot find name 'it'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/app.component.spec.ts (13, 7): Cannot find name 'expect'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/app.component.spec.ts (16, 3): Cannot find name 'it'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/app.component.spec.ts (18, 7): Cannot find name 'expect'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/app.component.ts (4, 13): Cannot find name 'module'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/shared/notfications.service.spec.ts (6, 1): Cannot find name 'describe'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/shared/notfications.service.spec.ts (7, 3): Cannot find name 'beforeEach'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/shared/notfications.service.spec.ts (11, 3): Cannot find name 'it'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/shared/notfications.service.spec.ts (14, 9): Cannot find name 'expect'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/shared/notifications.model.spec.ts (6, 1): Cannot find name 'describe'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/shared/notifications.model.spec.ts (7, 3): Cannot find name 'it'.
  D:/source/VSCode/TypeScriptProjectFromNGCLI/MyApp/tmp/broccoli_type_script_compiler-input_base_path-ISJwFjU4.tmp/0/src/app/shared/notifications.model.spec.ts (8, 5): Cannot find name 'expect'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\angular-cli-build.js:10:10)
    at Class.setupBroccoliBuilder (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.init (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.run (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\source\VSCode\TypeScriptProjectFromNGCLI\MyApp\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. the project run fine on typescript 1.8.0

**Comment by BartVDACodeware** [comment]
fixed by installing angular-cli@webpack https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md

**Comment by itamark** [comment]
The link in the correct tag (I think): [](https://github.com/angular/angular-cli/blob/v1.0.0-beta.11-webpack.2/WEBPACK_UPDATE.md)
