### ISSUE TITLE
ng serve Schema validation failed with the following errors:   Data path "" should NOT have additional properties(customWebpackConfig).

### ISSUE THREAD

**Issue by aliakbartalebi** [angular/angular-cli#20062]
Hi, I created a project and added tailwindcss in it and now I want to run it but I got an error
How do I fix this error?

```
PS E:\Learn\TestLearn\angular\TestTailwind\4\tailwind-angular> ng serve
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).
```
I put the project in the following path, please guide me.
https://github.com/aliakbartalebi/testTailwindcss

**Comment by alan-agius4** [comment]
`@angular-builders/custom-webpack` are not supported by the Angular tooling team. Please file an issue in their issue tracker.

**Comment by aliakbartalebi** [comment]
Thanks for your guidance, but I did not understand what you meant

**Comment by alan-agius4** [comment]
You are using a 3rd party package `@angular-builders/custom-webpack` to build your application. This is not supported by the Angular tooling team.

**Comment by aliakbartalebi** [comment]
What package should I install?
I did the following method but I encounter an error.

```
PS E:\Learn\TestLearn\angular\TestTailwind\4\tailwind-angular> npm i @angular-builders/dev-server -D
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1102.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-angular@0.1102.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-optimizer@0.1102.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-webpack@0.1102.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/core@11.2.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics@11.2.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular/cli@11.2.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@ngtools/webpack@11.2.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@schematics/angular@11.2.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@schematics/update@0.1102.0',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.3.0', npm: '7.5.4' }
npm WARN EBADENGINE }

up to date, audited 1661 packages in 14s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS E:\Learn\TestLearn\angular\TestTailwind\4\tailwind-angular> ng serve
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).
```
angular.json:

```
"serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "tailwind-angular:build",
            "customWebpackConfig": {
              "path": "webpack.config.js",
              "replaceDuplicatePlugins": true
            }
          },
          "configurations": {
            "production": {
              "browserTarget": "tailwind-angular:build:production"
            }
          }
        },
```

**Comment by aliakbartalebi** [comment]
I created a new project and proceeded as follows and encountered a new error.

`npm install -D tailwindcss`

```
npm i @tailwindcss/typography

npm i @tailwindcss/forms
```

Create a TailwindCSS configuration file in the workspace or project root.

tailwind.config.js:
```
module.exports = {
    prefix: '',
    purge: {
      content: [
        './src/**/*.{html,ts}',
      ]
    },
    darkMode: 'class', // or 'media' or 'class'
    theme: {
      extend: {},
    },
    variants: {
      extend: {},
    },
    plugins: [require('@tailwindcss/forms'),require('@tailwindcss/typography')],
};
```

styles.scss:
```
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```
app.component.html:
```
<button
  class="py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-400">Hello</button>
```
`ng serve`


```
PS E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest> ng serve
√ Browser application bundle generation complete.

Initial Chunk Files | Names         |    Size
main.js             | main          | 0 bytes
polyfills.js        | polyfills     | 0 bytes
runtime.js          | runtime       | 0 bytes
styles.js           | styles        | 0 bytes
vendor.js           | vendor        | 0 bytes

                    | Initial Total | 0 bytes

Build at: 2021-02-16T10:39:46.751Z - Hash: 9c81aec0c182c012bb21 - Time: 21257ms

Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module '@tailwindcss/typography'
Require stack:
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\tailwind.config.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\tailwindcss\lib\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\build-angular\src\webpack\configs\styles.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\build-angular\src\webpack\configs\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\build-angular\src\browser\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\architect\node\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\models\architect-command.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\commands\serve-impl.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\schematics\tools\export-ref.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\schematics\tools\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\utilities\json-schema.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\models\command-runner.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Aliakbar\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\Aliakbar\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\tailwind.config.js:15:45)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\tailwindcss\lib\index.js:76:107
    at E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\tailwindcss\lib\processTailwindFeatures.js:52:20
    at LazyResult.runOnRoot (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\postcss\lib\lazy-result.js:303:16)
    at LazyResult.runAsync (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\postcss\lib\lazy-result.js:355:26)
    at async Object.loader (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\postcss-loader\dist\index.js:95:14)
    at E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\webpack\lib\NormalModule.js:316:20
    at E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\postcss-loader\dist\index.js:104:7)

Error: ./src/app/app.component.scss
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module '@tailwindcss/typography'
Require stack:
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\tailwind.config.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\tailwindcss\lib\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\build-angular\src\webpack\configs\styles.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\build-angular\src\webpack\configs\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\build-angular\src\browser\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\architect\node\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\models\architect-command.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\commands\serve-impl.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\schematics\tools\export-ref.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular-devkit\schematics\tools\index.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\utilities\json-schema.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\models\command-runner.js
- E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Aliakbar\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\Aliakbar\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\tailwind.config.js:15:45)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\tailwindcss\lib\index.js:76:107
    at E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\tailwindcss\lib\processTailwindFeatures.js:52:20
    at LazyResult.runOnRoot (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\postcss\lib\lazy-result.js:303:16)
    at LazyResult.runAsync (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\postcss\lib\lazy-result.js:355:26)
    at async Object.loader (E:\Learn\TestLearn\angular\TestTailwind\5\tailwindTest\node_modules\postcss-loader\dist\index.js:95:14)



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
```
