### ISSUE TITLE
Angular CLI 11.2 add tailwind and use yarn will get error

### ISSUE THREAD

**Issue by pvt5r486** [angular/angular-cli#20073]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

I clone this [repo](https://github.com/devpato/angular-tailwindcss?fbclid=IwAR3Rq698LTja-OtrqqpAkI_LxJIO_mDzfU2SQ8u-G4x1LSy3ukW3gHj1qiA) and use `yarn`  then use `ng serve` will get some error.

But if I use `npm install` can success run `ng serve`.

Then I compare package-lock and yarn-lock found:

- package-lock used postcss 8.2.x
- yarn-lock used postcss 7.0.0

I try update yarn version to 1.22.5 , but had same problem.

## 🔬 Minimal Reproduction

1. clone [this repo](https://github.com/devpato/angular-tailwindcss?fbclid=IwAR3Rq698LTja-OtrqqpAkI_LxJIO_mDzfU2SQ8u-G4x1LSy3ukW3gHj1qiA)
2.  use `yarn`
3.  use `ng serve`

## 🔥 Exception or Error
<pre><code>
Error: ./src/app/app.component.scss
Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js):     
Error: PostCSS plugin postcss-nested requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (D:\GitHub\angular-tailwindcss\node_modules\postcss\lib\processor.js:167:15)
    at new Processor (D:\GitHub\angular-tailwindcss\node_modules\postcss\lib\processor.js:56:25)
    at postcss (D:\GitHub\angular-tailwindcss\node_modules\postcss\lib\postcss.js:55:10)
    at D:\GitHub\angular-tailwindcss\node_modules\tailwindcss\lib\util\parseObjectStyles.js:24:33
    at arrayMap (D:\GitHub\angular-tailwindcss\node_modules\lodash\lodash.js:639:23)
    at map (D:\GitHub\angular-tailwindcss\node_modules\lodash\lodash.js:9580:14)
    at Function.flatMap (D:\GitHub\angular-tailwindcss\node_modules\lodash\lodash.js:9283:26)
    at parseObjectStyles (D:\GitHub\angular-tailwindcss\node_modules\tailwindcss\lib\util\parseObjectStyles.js:23:26)
    at parseObjectStyles (D:\GitHub\angular-tailwindcss\node_modules\tailwindcss\lib\util\parseObjectStyles.js:20:12)
    at D:\GitHub\angular-tailwindcss\node_modules\tailwindcss\lib\util\processPlugins.js:37:123
    at arrayMap (D:\GitHub\angular-tailwindcss\node_modules\lodash\lodash.js:639:23)
    at map (D:\GitHub\angular-tailwindcss\node_modules\lodash\lodash.js:9580:14)
    at Function.flatMap (D:\GitHub\angular-tailwindcss\node_modules\lodash\lodash.js:9283:26)
    at parseStyles (D:\GitHub\angular-tailwindcss\node_modules\tailwindcss\lib\util\processPlugins.js:37:26)
1m    at addComponents (D:\GitHub\angular-tailwindcss\node_modules\tailwindcss\lib\util\processPlugins.js:131:18)
    at D:\GitHub\angular-tailwindcss\node_modules\tailwindcss\lib\plugins\container.js:101:5

Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js):
TypeError: getProcessedPlugins is not a function
    at D:\GitHub\angular-tailwindcss\node_modules\tailwindcss\lib\processTailwindFeatures.js:75:83
    at LazyResult.runOnRoot (D:\GitHub\angular-tailwindcss\node_modules\@angular-devkit\build-angular\node_modules\postcss\lib\lazy-result.js:303:16)
    at LazyResult.runAsync (D:\GitHub\angular-tailwindcss\node_modules\@angular-devkit\build-angular\node_modules\postcss\lib\lazy-result.js:355:26)
    at async Object.loader (D:\GitHub\angular-tailwindcss\node_modules\@angular-devkit\build-angular\node_modules\postcss-loader\dist\index.js:95:14)
    at D:\GitHub\angular-tailwindcss\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\GitHub\angular-tailwindcss\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\GitHub\angular-tailwindcss\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\GitHub\angular-tailwindcss\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (D:\GitHub\angular-tailwindcss\node_modules\@angular-devkit\build-angular\node_modules\postcss-loader\dist\index.js:104:7)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.0
Node: 14.15.5
OS: win32 x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.5
</code></pre>

**Comment by alan-agius4** [comment]
Hi @pvt5r486,

tailwindcss requires several peer dependencies which are not being installed in the project.

```
warning " > tailwindcss@2.0.3" has unmet peer dependency "autoprefixer@^10.0.2".
warning " > tailwindcss@2.0.3" has unmet peer dependency "postcss@^8.0.9".
```

More information on how to install Tailwinds can be found in their documentation https://tailwindcss.com/docs/installation#install-tailwind-via-npm

This works when using NPM, because of different module strategy between package managers.
