### ISSUE TITLE
Cannot find name 'NodeModule'.

### ISSUE THREAD

**Issue by rakibler** [angular/angular-cli#2009]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7 and OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
1.0.0-beta.10

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Cloned my repo, installed node_modules and typings, attempted to `ng serve`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
Error: Typescript found the following errors:
  C:/Users/rakibler/Projects/efiletest/tmp/broccoli_type_script_compiler-input_base_path-OzqpKZ0b.tmp/0/src/typings.d.ts (6, 21): Cannot find name 'NodeModule'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\Users\rakibler\Projects\efiletest\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (C:\Users\rakibler\Projects\efiletest\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\Users\rakibler\Projects\efiletest\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\Users\rakibler\Projects\efiletest\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\rakibler\Projects\efiletest\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\rakibler\Projects\efiletest\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\rakibler\Projects\efiletest\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

5. Mention any other details that might be useful.
Not sure why this is happening.  Our designer was having issues getting my app to run, so I cloned fresh and attempted to build it, and I'm getting this error. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rakibler** [comment]
Sorry, my fault.  I was missing the node typings.
