### ISSUE TITLE
`Error: Failed to find exported name of node` reported from pkg bundled by `ng-packagr`

### ISSUE THREAD

**Issue by JounQin** [angular/angular-cli#20119]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes, `@angular/compiler-cli@10.21` with `ng-packagr@10.1.2` works

### Description

 Unable to build any more...

## 🔬 Minimal Reproduction

https://github.com/JounQin/test/tree/angular

run `yarn start`

## 🔥 Exception or Error
<pre><code>

Compiling @alauda/common-snippet : es2015 as esm2015
Error: Error on worker #1: Error: Failed to find exported name of node (class UtilsModule {
}) in '/Users/JounQin/Workspaces/Local/test/node_modules/@alauda/common-snippet/fesm2015/alauda-common-snippet.js'.
    at Object.findExportedNameOfNode (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/find_export.js:36:19)
    at LogicalProjectStrategy.emit (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:233:38)
    at ReferenceEmitter.emit (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:249:31)
    at NgModuleDecoratorHandler._toR3Reference (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:416:31)
    at /Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:195:72
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:195:38)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
    at analyze (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:296:58)
    at ClusterMaster.onWorkerMessage (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/Users/JounQin/Workspaces/Local/test/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/JounQin/Workspaces/Local/test/node_modules/tslib/tslib.js:124:57)
    at /Users/JounQin/Workspaces/Local/test/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/JounQin/Workspaces/Local/test/node_modules/tslib/tslib.js:113:16)
    at EventEmitter.<anonymous> (/Users/JounQin/Workspaces/Local/test/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (events.js:314:20)
An unhandled exception occurred: NGCC failed.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.2.1
Node: 12.20.0
OS: darwin x64

Angular: 11.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.1
@angular-devkit/build-angular   0.1102.1
@angular-devkit/core            11.2.1
@angular-devkit/schematics      11.2.1
@angular/cdk                    11.2.1
@angular/cli                    11.2.1
@schematics/angular             11.2.1
@schematics/update              0.1102.1
rxjs                            6.6.3
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

**Comment by JounQin** [comment]
https://github.com/JounQin/test/runs/1958081848#step:5:31

**Comment by JounQin** [comment]
cc @alan-agius4

**Comment by alan-agius4** [comment]
Looks like an NGCC issue. Transferring to the FW repo.
