### ISSUE TITLE
angular 11 not building when tailwindcss is enabled

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/angular-cli#20176]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

`npm run  build` fails when tailwindcss is enabled

## 🔬 Minimal Reproduction

1. clone https://github.com/abdulkareemnalband/rent-receipt/tree/tailwind
1. checkout `tailwind` branch
1. run `npm install `
2. run `npm run build`
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.2
Node: 15.10.0
OS: win32 x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2
@angular-devkit/schematics      11.2.2
@angular/cli                    11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
rxjs                            6.5.4
typescript                      4.0.7
```

## 🔥 Exception or Error
<pre><code>
Error: ./src/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (D:\backup2\play\rent-recipt\node_modules\postcss\lib\processor.js:168:15)
    at new Processor (D:\backup2\play\rent-recipt\node_modules\postcss\lib\processor.js:52:25)
    at postcss (D:\backup2\play\rent-recipt\node_modules\postcss\lib\postcss.js:55:10)
    at D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\parseObjectStyles.js:24:33
    at arrayMap (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:653:23)
    at map (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:9622:14)
    at Function.flatMap (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:9325:26)
    at parseObjectStyles (D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\parseObjectStyles.js:23:26)
    at parseObjectStyles (D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\parseObjectStyles.js:20:12)
    at D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\processPlugins.js:37:123
    at arrayMap (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:653:23)
    at map (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:9622:14)
    at Function.flatMap (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:9325:26)
    at parseStyles (D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\processPlugins.js:37:26)
    at addComponents (D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\processPlugins.js:131:18)
    at D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\plugins\container.js:101:5
    at D:\backup2\play\rent-recipt\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\backup2\play\rent-recipt\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\backup2\play\rent-recipt\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\backup2\play\rent-recipt\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.loader (D:\backup2\play\rent-recipt\node_modules\postcss-loader\dist\index.js:104:7)
 @ multi ./src/styles.css styles[0]

Error: ./src/app/app.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: getProcessedPlugins is not a function
    at D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\processTailwindFeatures.js:75:83
    at LazyResult.runOnRoot (D:\backup2\play\rent-recipt\node_modules\@angular-devkit\build-angular\node_modules\postcss\lib\lazy-result.js:303:16)
    at LazyResult.runAsync (D:\backup2\play\rent-recipt\node_modules\@angular-devkit\build-angular\node_modules\postcss\lib\lazy-result.js:355:26)
    at async Object.loader (D:\backup2\play\rent-recipt\node_modules\postcss-loader\dist\index.js:95:14)

Error: ./src/styles.css (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/dist/cjs.js??ref--13-2!./src/styles.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (D:\backup2\play\rent-recipt\node_modules\postcss\lib\processor.js:168:15)
    at new Processor (D:\backup2\play\rent-recipt\node_modules\postcss\lib\processor.js:52:25)
    at postcss (D:\backup2\play\rent-recipt\node_modules\postcss\lib\postcss.js:55:10)
    at D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\parseObjectStyles.js:24:33
    at arrayMap (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:653:23)
    at map (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:9622:14)
    at Function.flatMap (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:9325:26)
    at parseObjectStyles (D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\parseObjectStyles.js:23:26)
    at parseObjectStyles (D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\parseObjectStyles.js:20:12)
    at D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\processPlugins.js:37:123
    at arrayMap (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:653:23)
    at map (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:9622:14)
    at Function.flatMap (D:\backup2\play\rent-recipt\node_modules\lodash\lodash.js:9325:26)
    at parseStyles (D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\processPlugins.js:37:26)
    at addComponents (D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\util\processPlugins.js:131:18)
    at D:\backup2\play\rent-recipt\node_modules\tailwindcss\lib\plugins\container.js:101:5

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**
I had update an angular 9 project to angular 10 then to 11

**Comment by alan-agius4** [comment]
The issue is caused because `tailwinds` has `autoprefixer` and `postcss` as peer dependencies. These however are not defined in projects `package.json`, which is resulting in `tailwinds` using the wrong version of `postcss`.

To fix the issue you need to install the mentioned depedencies
```
npm install -D tailwindcss postcss autoprefixer
```

See https://tailwindcss.com/docs/installation#install-tailwind-via-npm
