### ISSUE TITLE
Node PrefixUnaryExpression was unexpected.

### ISSUE THREAD

**Issue by sakshi-mishra123** [angular/angular-cli#20201]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

ERROR in : Error: Debug Failure. Unexpected node.
Node PrefixUnaryExpression was unexpected.
    at serializeTypeNode (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:65806:45)
    at serializeTypeOfNode (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:65688:28)
    at addOldTypeMetadata (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:65604:92)
    at addTypeMetadata (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:65598:17)
    at transformAllDecoratorsOfDeclaration (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:65433:13)
    at generateClassElementDecorationExpression (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:65480:40)
    at generateClassElementDecorationExpressions (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:65460:34)
    at addClassElementDecorationStatements (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:65445:44)
    at visitClassDeclaration (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:64757:13)
    at visitTypeScript (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:64588:28)
    at visitorWorker (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:64372:24)
    at sourceElementVisitorWorker (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:64401:28)
    at saveStateAndInvoke (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:64310:27)
    at sourceElementVisitor (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:64386:20)
    at visitNodes (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:62256:48)
    at Object.visitLexicalEnvironment (/home/shakshi/HLC/hlcapp/HLCAPP/appserver/hlc-app/node_modules/typescript/lib/typescript.js:62289:22)****

Please Anyone Help Me as i m facing this issue during npm start

**Comment by alan-agius4** [comment]
Kindly follow the issue template.
