### ISSUE TITLE
ReferenceError: packages is not defined

### ISSUE THREAD

**Issue by omeryounus** [angular/angular-cli#2043]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   Windows 10
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.10
node: 4.4.2
os: win32 ia32
1. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

When opening URL, I am getting this error in browser console.
1. The log given by the failure. Normally this include a stack trace and some
   more information.
   On Chrome browser I am getting following stack:
   
   ReferenceError: packages is not defined
         at materialComponents.forEach.name (http://localhost:4200/system-config.js:30:5)
         at Array.forEach (native)
         at eval (http://localhost:4200/system-config.js:29:20)
2. Mention any other details that might be useful.

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Do you still get this problem with `beta.14`?

**Comment by Brocco** [comment]
No activity on this issue and the build system has been changed since this issue was created.... closing.
