### ISSUE TITLE
fix: generating pipes throws an error

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular-cli#2049]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Max OSX Yosemite

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
ng version: 1.0.0-beta.11-webpack.8
node version: 6.5.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Running `ng g pipe foo` generates the needed files, but throws the following error

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
astUtils.addComponentToModule is not a function
TypeError: astUtils.addComponentToModule is not a function
    at Class.afterInstall (/Users/pascalprecht/projects/thoughtram/video-app/node_modules/angular-cli/addon/ng2/blueprints/pipe/index.js:55:18)
    at lib$rsvp$$internal$$tryCatch (/Users/pascalprecht/projects/thoughtram/video-app/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/pascalprecht/projects/thoughtram/video-app/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/pascalprecht/projects/thoughtram/video-app/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/pascalprecht/projects/thoughtram/video-app/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment]
Same happens for me for modules, using a --link-cli in sync with git master (b6a216536f4220d35dc221c7a312259a4772e98b at the time of test).

Inside the project, I run:

```
ng g module Customers
```

And then get:

```
installing module
  create src/app/customers/customers.module.ts
installing component
  create src/app/customers/customers.component.scss
  create src/app/customers/customers.component.html
  create src/app/customers/customers.component.spec.ts
  create src/app/customers/customers.component.ts
astUtils.addComponentToModule is not a function
TypeError: astUtils.addComponentToModule is not a function
    at Class.module.exports.afterInstall (/Users/Meligy/Code/temp/cli-tests/sample-project/node_modules/angular-cli/addon/ng2/blueprints/component/index.js:125:18)
    at tryCatch (/Users/Meligy/Code/temp/cli-tests/sample-project/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/Meligy/Code/temp/cli-tests/sample-project/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/Meligy/Code/temp/cli-tests/sample-project/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/Meligy/Code/temp/cli-tests/sample-project/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Meligy** [comment]
This seems fixed in the Angular 2 RC 7 update commit.

I went to the same project I had the problem with, ran `ng init --link-cli --style=scss`, and since it was a test project I let it override all files, then the following commands worked fine

```
ng g module Customers
```

```
ng g pipe foo
```

**Comment by jklegseth** [comment]
Same error creating component and app.module is not updated (obviously). Oddly, yesterday when creating modules the same way _did_ update app.module.

Max OSX Yosemite
ng version: 1.0.0-beta.11-webpack.8
node version: 6.5.0
Yes, app created using CLI

Steps:
`ng g c template-driven -is`

Error:
`
installing component
  create src/app/template-driven/template-driven.component.html
  create src/app/template-driven/template-driven.component.spec.ts
  create src/app/template-driven/template-driven.component.ts
astUtils.addComponentToModule is not a function
TypeError: astUtils.addComponentToModule is not a function
    at Class.afterInstall (/Users/juniorklegseth/Code/angular/forms/node_modules/angular-cli/addon/ng2/blueprints/component/index.js:125:18)
    at tryCatch (/Users/juniorklegseth/Code/angular/forms/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/juniorklegseth/Code/angular/forms/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/juniorklegseth/Code/angular/forms/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/juniorklegseth/Code/angular/forms/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by filipesilva** [comment]
Fixed starting `beta.15`.
