### ISSUE TITLE
ng updates fails behind proxy but npm works

### ISSUE THREAD

**Issue by plecos** [angular/angular-cli#20501]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

ng update behind my corporate proxy gives a 407 Authorized only error, but npm works correctly.  I have configured npm with both proxy and https-proxy values

## 🔬 Minimal Reproduction
ng update on my computer

## 🔥 Exception or Error
<pre><code>
An unhandled exception occurred: 407 AuthorizedOnly - GET http://registry.npmjs.org/@angular%2fcli
See "C:\Users\#####\AppData\Local\Temp\ng-PrTzqR\angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.6
Node: 14.16.0
OS: win32 x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cli                    11.2.6
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Anything else relevant?**
Output of log file mentioned in error:

<pre><code>
[error] Error: 407 AuthorizedOnly - GET http://registry.npmjs.org/@angular%2fcli
    at C:\Users\#####\source\repos\PMPRAngular\PMPRAngular\ClientApp\node_modules\npm-registry-fetch\check-response.js:123:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.fetchPackageManifest (C:\Users\#####\source\repos\PMPRAngular\PMPRAngular\ClientApp\node_modules\@angular\cli\utilities\package-metadata.js:166:22)
    at async UpdateCommand.checkCLILatestVersion (C:\Users\#####\source\repos\PMPRAngular\PMPRAngular\ClientApp\node_modules\@angular\cli\commands\update-impl.js:609:35)
    at async UpdateCommand.run (C:\Users\#####\source\repos\PMPRAngular\PMPRAngular\ClientApp\node_modules\@angular\cli\commands\update-impl.js:195:37)
    at async UpdateCommand.validateAndRun (C:\Users\#####\source\repos\PMPRAngular\PMPRAngular\ClientApp\node_modules\@angular\cli\models\command.js:139:28)
    at async Object.runCommand (C:\Users\#####\source\repos\PMPRAngular\PMPRAngular\ClientApp\node_modules\@angular\cli\models\command-runner.js:204:24)
    at async default_1 (C:\Users\#####\source\repos\PMPRAngular\PMPRAngular\ClientApp\node_modules\@angular\cli\lib\cli\index.js:80:31)
</code></pre>

Output of npm config list:

<pre><code>
; cli configs
metrics-registry = "http://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.11 node/v14.16.0 win32 x64"

; userconfig C:\Users\#####\.npmrc
@fortawesome:registry = ""
cache = "c:\\Users\\#####\\npm-cache"
https-proxy = "http://#####@#####:8080/"
prefix = "c:\\Users\\#####\\npm"
proxy = "http://#####@#####:8080/"
registry = "http://registry.npmjs.org/"
strict-ssl = false

; globalconfig c:\Users\#####\npm\etc\npmrc
cache = "c:\\Users\\#####\\npm-cache"
https-proxy = "http://#####@#####:8080/"
prefix = "c:\\Users\\#####\\npm"
proxy = "http://#####@#####:8080/"
registry = "http://registry.npmjs.org/"

; builtin config undefined

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\#####\source\repos\PMPRAngular\PMPRAngular\ClientApp
; HOME = C:\Users\#####
; "npm config ls -l" to show all defaults.
</code></pre>

**Comment by alan-agius4** [comment]
Can you try to run `ng update` with the `--verbose` argument please and provide the output?

**Comment by plecos** [comment]
> Can you try to run `ng update` with the `--verbose` argument please and provide the output?

<pre><code>
ng update --verbose
Locating potential npmrc files:
Trying 'C:\Program Files\nodejs\etc\npmrc'...not found.
Trying 'C:\Users\#####\.npmrc'...found.
Trying 'C:\Users\.npmrc'...not found.
Trying 'C:\Users\#####\.npmrc'...found.
Trying 'C:\Users\#####\source\.npmrc'...not found.
Trying 'C:\Users\#####\source\repos\.npmrc'...not found.
Trying 'C:\Users\#####\source\repos\ClientApp\.npmrc'...not found.
An unhandled exception occurred: 407 AuthorizedOnly - GET http://registry.npmjs.org/@angular%2fcli
See "C:\Users\#####\AppData\Local\Temp\ng-tSkvW8\angular-errors.log" for further details.
</code></pre>

**Comment by plecos** [comment]
@alan-agius4 is there anything else I can provide on this?

**Comment by alan-agius4** [comment]
@plecos, that should be enough. Will let you know if we need further information.

**Comment by alan-agius4** [comment]
Can you try to add `always-auth: true` in your `.npmrc`?

**Comment by alan-agius4** [comment]
@plecos is this still a problem in v12?

**Comment by lilsnow** [comment]
Following up, I was able to rename my .npmrc and do the upgrade with the connection to normal npm registry. I opened a ticket with the team in charge of artifactory at my company because previously I was able to do upgrades with no issue.

**Comment by amarth1982** [comment]
> Following up, I was able to rename my .npmrc and do the upgrade with the connection to normal npm registry. I opened a ticket with the team in charge of artifactory at my company because previously I was able to do upgrades with no issue.

I do face a similar issue

we use artifactory as well, all npm installation is good where as `ng update` is failing

**Comment by alan-agius4** [comment]
@amarth1982, which version of Angular CLI are you using?

**Comment by amarth1982** [comment]
> @amarth1982, which version of Angular CLI are you using?

using ng8 now, trying to upgrade it to ng12 as recommended by ng angular update guide.

Thanks

**Comment by alan-agius4** [comment]
Unfortunately, version 8 doesn’t download the latest version of the Angular CLI to perform the update. Therefore, you cannot avail it any fixes that have been done since version 8 in the update process.
