### ISSUE TITLE
An unhandled exception occurred: ENOENT: no such file or directory, lstat 'D:\My Laptop\Certifications\node_modules'

### ISSUE THREAD

**Issue by Kekay69** [angular/angular-cli#20533]
I have created from scratch two times the same project using VS Code and the latest version of Angular. When I close VS Code at the end of the day, then the next day when I open it and  try to run it by using ng serve, it takes time to return the following message: 
An unhandled exception occurred: ENOENT: no such file or directory, lstat 'D:\My Laptop\Certifications\node_modules'
See "C:\Users\Enrique\AppData\Local\Temp\ng-W43QHH\angular-errors.log" for further details.

Details:
```
[error] Error: ENOENT: no such file or directory, lstat 'D:\My Laptop\Certifications\node_modules'
    at Object.realpathSync (fs.js:1728:7)
    at D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\src\webpack\configs\styles.js:44:35
    at Array.forEach (<anonymous>)
    at Object.getStylesConfig (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\src\webpack\configs\styles.js:35:76)
    at D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:91:23
    at generateWebpackConfig (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:45:49)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async generateBrowserWebpackConfigFromContext (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:136:20)
    at async Object.generateI18nBrowserWebpackConfigFromContext (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:77:20)
    at async setup (D:\My Laptop\Certifications\food-blog-eog\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:87:47)
```
Any advice would be appreciated.

**Comment by alan-agius4** [comment]
The error indicates that `D:\My Laptop\Certifications\node_modules` is doesn't exists. Is that the case?

**Comment by Kekay69** [comment]
Hi Alan, No, it is not the case. When created the project (npm new <name of project> ) all the node_modules were included from the beginning.

**Comment by alan-agius4** [comment]
> Hi Alan, No, it is not the case. When created the project (npm new ) all the node_modules were included from the beginning.

What about when the error is shown? Node.JS is reporting that the directory cannot be found, so either there the directory is no longer there or something else is going on.

Can you also provide the output of `ng version` please?

**Comment by Kekay69** [comment]
Hi Alan,
PFA the SS of my HD with the CLI version
![ng--version](https://user-images.githubusercontent.com/5581028/114953093-84382400-9e0c-11eb-9ef0-9e3e523a1ac2.png)

**Comment by Kekay69** [comment]
Also here is the VS Code version
![VS-Code--v](https://user-images.githubusercontent.com/5581028/114954385-47b9f780-9e0f-11eb-8f89-a86953de0f4a.png)

**Comment by Kekay69** [comment]
This is the VS Code Erroring 
![VS Code Project Error](https://user-images.githubusercontent.com/5581028/114954917-653b9100-9e10-11eb-82d9-29ed87753fef.png)

**Comment by alan-agius4** [comment]
Hi @Kekay69, Unfortunately, this looks like something related to your enviorment which we cannot replicate. Please re-open the issue if we can find a way that we can replicate this.
