### ISSUE TITLE
Wrong Node.js version detected.

### ISSUE THREAD

**Issue by mdemiryurek** [angular/angular-cli#20611]
I am trying to build an angular project which works with Node.js v10.23.1. I have updated Node.js version to v10.23.1. Here are the installed versions on my computer.

Angular CLI: 11.2.2 Node: 10.23.1

When the build command running, I am getting the error below:

```
[13:56:20] Error in plugin "run-sequence(ng:build-angular)" Message:
    Command failed: cd XXX && ng build --deploy-url XXX Node.js version v10.6.0 detected. The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0. Please update your Node.js version or visit https://nodejs.org/ for additional instructions. Details:
    killed: false
    code: 3
    signal: null
    cmd: cd XXX && ng build --deploy-url XXX Stack: Error: Command failed: XXX && ng build --deploy-url XXX Node.js version v10.6.0 detected. The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0. Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5) Process terminated with code 1.
```

Please advice.

**Comment by mdemiryurek** [comment]
> The Angular CLI will retrieve the Node.js version directly from the executing Node.js instance. Please ensure that the active version of Node.js on the system is within the required support range. Depending on the installation methods, it is possible to have multiple versions of Node.js installed on the system.

Yes, you're right. I had multiple versions of Node.js but version v10.23.1 wasn't the active one.

I have uninstalled the Node.js then re-installed it using nvm. I also ran the command "nvm use 10.23.1".
