### ISSUE TITLE
ng build throwing `[error] TypeError: Cannot read property 'toLowerCase' of undefined`

### ISSUE THREAD

**Issue by stagefright5** [angular/angular-cli#20673]
# 🐞 bug report

## 🔥 Exception or Error
<pre><code>
[error] TypeError: Cannot read property 'toLowerCase' of undefined
    at $PROJECT_ROOT\styles.a7990a61a7ecede859a2.css:3506:1
    at hasInherit ($PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\canMerge.js:16:39)
    at Array.some (<anonymous>)
    at _default ($PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\canMerge.js:23:13)
    at $PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:234:33
    at mergeRules ($PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\mergeRules.js:44:11)
    at $PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:233:29
    at Array.forEach (<anonymous>)
    at Object.merge ($PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:231:7)
    at $PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\index.js:20:13
    at Array.forEach (<anonymous>)
    at $PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\index.js:18:23
    at $PROJECT_ROOT\node_modules\postcss\lib\container.js:115:18
    at $PROJECT_ROOT\node_modules\postcss\lib\container.js:74:18
    at Root.each ($PROJECT_ROOT\node_modules\postcss\lib\container.js:60:16)
    at Root.walk ($PROJECT_ROOT\node_modules\postcss\lib\container.js:71:17)
    at Root.walkRules ($PROJECT_ROOT\node_modules\postcss\lib\container.js:113:19)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.11
Node: 14.15.5
OS: win32 x64

Angular: 11.2.12
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1102.11
@angular-devkit/build-angular     0.1102.11
@angular-devkit/build-optimizer   0.1102.5
@angular-devkit/core              11.2.11
@angular-devkit/schematics        11.2.11
@angular/cdk                      11.2.11
@angular/cli                      11.2.11
@angular/flex-layout              11.0.0-beta.33
@angular/material                 11.2.11
@schematics/angular               11.2.11
@schematics/update                0.1102.11
rxjs                              6.6.7
typescript                        4.0.5
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

- I just upgraded the project to angular by running `ng update`. These are the changes:
![image](https://user-images.githubusercontent.com/15051871/116743831-1c422a00-aa17-11eb-8a50-fef46ece17db.png)

**Comment by stagefright5** [comment]
@alan-agius4, I reverted the angular to **just previous** version of `11.x.x` and I was able to successfully build the app.

Please let me know if you guys need _ANY_ additional information.

Thanks

**Comment by alan-agius4** [comment]
The reason for this is previously we had a dependency on CSSNano v4 which is no longer maintained and has a number of security issues.

 In the 12 and 11.2.11 we updated to use CSSNano 5.

**Comment by stagefright5** [comment]
Thanks for the update.
So, my only option is to wait for angular to wait for cssnano to release a fix, then release their fix. Got it.😄

**Comment by stagefright5** [comment]
The latest release still depends on `cssnano@5.0.1` but, this issue was fixed in `cssnano@5.0.2`. Is that scheduled?
I am asking this, because, I will not able to update angular unless this issue gets fixed.

Thanks

**Comment by stagefright5** [comment]
@clydin @filipesilva ,
I am afraid the issue still exists even after this supposed fix. Please let me know if you guys need any kind of logs or details.

**Comment by collindutter** [comment]
@stagefright5 I'm also experiencing this even after updating to @angular-devkit/build-angular@~0.1102.14 with cssnano@5.0.2. Removing `optimization: true` from my production build configuration resolves it, but that's not ideal.

Do you know the last version in which this wasn't a problem?

**Comment by stagefright5** [comment]
@collindutter , version `@angular-devkit/build-angular@0.1102.9` works fine for me
