### ISSUE TITLE
ng new throw error Schematic input does not validate against the Schema

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular-cli#20718]
# 🐞 Bug report

### Command (mark with an `x`)

- [ x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was angular 11

### Description

after upgrading global angular to 12.0.0-rc.2 to test the new Angular, I can't create new projects whatever I do

## 🔬 Minimal Reproduction
just try `ng new ng12 --defaults`

I also tried 
`ng new ng12 --routing --style=scss`
and only `ng new` and gave these answers

```
> ng new
? What name would you like to use for the new workspace and initial project? ng12
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss                ]
```
## 🔥 Exception or Error

<pre><code>
Schematic input does not validate against the Schema: {"styleext":"scss","name":"app","selector":"app-root","flat":true,"path":"/src/app","skipImport":true,"project":"ng12","skipTests":false,"style":"scss"}
Errors:

  Data path "" must NOT have additional properties(styleext).
</code></pre>

## 🌍 Your Environment

<pre><code>
> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.0-rc.2
Node: 14.16.1
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.0-rc.2 (cli-only)
@angular-devkit/core         12.0.0-rc.2 (cli-only)
@angular-devkit/schematics   12.0.0-rc.2 (cli-only)
@schematics/angular          12.0.0-rc.2 (cli-only)
</code></pre>

**Anything else relevant?**

no

**Comment by alan-agius4** [comment]
Do you a global Angular cli configuration by any chance?

It looks like you might have a old option present (styleext).

**Comment by robertIsaac** [comment]
@alan-agius4 how to check this out?
the only thing I can think I would have done is to make default style SCSS not CSS
but I don't even remember I have done it

**Comment by alan-agius4** [comment]
You can delete `.angular-config.json` which is under your home directory.

**Comment by robertIsaac** [comment]
running that command throw error
```
> ng config -g schematics undefined
An unhandled exception occurred: Invalid Path.
See "C:\Users\rober\AppData\Local\Temp\ng-Wfw3qF\angular-errors.log" for further details.
```

here is this file content
```
[error] Error: Invalid Path.
    at ConfigCommand.set (C:\Users\rober\AppData\Roaming\npm\node_modules\@angular\cli\commands\config-impl.js:126:19)
    at ConfigCommand.run (C:\Users\rober\AppData\Roaming\npm\node_modules\@angular\cli\commands\config-impl.js:95:25)
    at ConfigCommand.validateAndRun (C:\Users\rober\AppData\Roaming\npm\node_modules\@angular\cli\models\command.js:136:33)
    at async Object.runCommand (C:\Users\rober\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:205:24)
    at async default_1 (C:\Users\rober\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js:70:31)
```

**Comment by robertIsaac** [comment]
i tried to set it again to correct value using `ng config -g schematics.@schematics/angular:component.style "scss"` and then to remove it but nothing works
```
PS C:\Users\rober> ng config -g schematics.@schematics/angular:component.style undefined
Schema validation failed with the following errors:
  Data path "/schematics/@schematics~1angular:component/style" must be equal to one of the allowed values.
PS C:\Users\rober> ng config -g schematics.@schematics/angular:component.style undefined
Schema validation failed with the following errors:
  Data path "/schematics/@schematics~1angular:component/style" must be equal to one of the allowed values.
PS C:\Users\rober> ng config -g schematics.@schematics/angular:component undefined
Schema validation failed with the following errors:
  Data path "/schematics/@schematics~1angular:component" must be object.
PS C:\Users\rober> ng config -g schematics undefined
An unhandled exception occurred: Invalid Path.
See "C:\Users\rober\AppData\Local\Temp\ng-maVvwh\angular-errors.log" for further details.
```
