### ISSUE TITLE
@angular-devkit/build-angular 0.1102.11 not work error when use caniuse-lite 

### ISSUE THREAD

**Issue by lionel-meunier** [angular/angular-cli#20730]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: ....

### Description

When i use ``ng test --watch false --code-coverage``, i have error 👍 

``
An unhandled exception occurred: Cannot read property 'B' of undefined
See "/tmp/ng-Izy9Pn/angular-errors.log" for further details.
npm ERR! Test failed.  See above for more details.
``

In angular-error.log i have : 

``
[error] TypeError: Cannot read property 'B' of undefined
at Object.unpackFeature [as feature] (...\node_modules\caniuse-lite\dist\unpacker\feature.js:28:44)
at BuildBrowserFeatures.isFeatureSupported (...\node_modules\@angular-devkit\build-angular\src\utils\build-browser-features.js:45:37)
at BuildBrowserFeatures.isEs5SupportNeeded (...\node_modules\@angular-devkit\build-angular\src\utils\build-browser-features.js:31:22)
at Object.getCommonConfig (...\node_modules\@angular-devkit\build-angular\src\webpack\configs\common.js:85:38)
at ...\node_modules\@angular-devkit\build-angular\src\karma\index.js:27:19
at generateWebpackConfig (...\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:45:49)
at async Object.generateBrowserWebpackConfigFromContext (...\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:136:20)
at async initialize (...\node_modules\@angular-devkit\build-angular\src\karma\index.js:22:24)
``

## 🔬 Minimal Reproduction

In my package-lock.json i have

"@angular-devkit/architect": "0.1102.12",
"browserslist": "4.16.6",
"caniuse-lite": "1.0.30001225",

**Comment by alan-agius4** [comment]
Can you please provide the full output of `ng v`?

In addition can you try the following;
```
rm -rf node_modules package-lock.json
npm i
```

**Comment by tricodon** [comment]
I got the same error today -  with `ng build` - after generating a fresh angular project.

`
[error] TypeError: Cannot read property 'B' of undefined
    at Object.unpackFeature [as feature] (/Users/.../dev/angular-libraries/node_modules/caniuse-lite/dist/unpacker/feature.js:28:44)
    at BuildBrowserFeatures.isFeatureSupported (/Users/.../dev/angular-libraries/node_modules/@angular-devkit/build-angular/src/utils/build-browser-features.js:45:37)
    at BuildBrowserFeatures.isEs5SupportNeeded (/Users/.../dev/angular-libraries/node_modules/@angular-devkit/build-angular/src/utils/build-browser-features.js:31:22)
    at BuildBrowserFeatures.isDifferentialLoadingNeeded (/Users/.../dev/angular-libraries/node_modules/@angular-devkit/build-angular/src/utils/build-browser-features.js:25:41)
    at SwitchMapSubscriber.project (/Users/.../dev/angular-libraries/node_modules/@angular-devkit/build-angular/src/browser/index.js:116:66)
    at SwitchMapSubscriber._next (/Users/.../dev/angular-libraries/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/switchMap.js:47:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/.../dev/angular-libraries/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/.../dev/angular-libraries/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24

`

Angular CLI: 11.2.12
Node: 14.16.1
OS: darwin x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.12
@angular-devkit/build-angular   0.1102.12
@angular-devkit/core            11.2.12
@angular-devkit/schematics      11.2.12
@angular/cli                    11.2.12
@schematics/angular             11.2.12
@schematics/update              0.1102.12
rxjs                            6.6.7
typescript                      4.1.5

$ npm version
{
  'angular-libraries': '0.0.0',
  npm: '6.14.12',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.16.1',
  openssl: '1.1.1k',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.18',
  zlib: '1.2.11'
}

**Comment by angellapuente** [comment]
You can try with the last version of caniuse-lite: "npm i caniuse-lite@1.0.30001227"

**Comment by clydin** [comment]
It appears there were some errors in a recently published version of `caniuse-lite`.  The newly published version `1.0.30001227` appears to have corrected the issue.  Following the instructions above (https://github.com/angular/angular-cli/issues/20730#issuecomment-836500364), should force the newer version to be used in a project affected by this problem. If anyone is still encountering issues after following the instructions, please let us know.
