### ISSUE TITLE
Css Minimizer error Unclosed comment

### ISSUE THREAD

**Issue by kemsky** [angular/angular-cli#20867]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.0.0

### Description
Angular cli fails to build project

## 🔬 Minimal Reproduction

```css
:host .header-select /deep/ * {
    cursor: pointer;
}
```

## 🔥 Exception or Error

<pre><code>
header.component.css from Css Minimizer
Error: Unclosed comment
    at C:/Users/admin/Documents/Projects/ClientApp/src/app/main/header/header.component.css:114:1
    at Object.error (C:\Users\admin\Documents\Projects\ClientApp\node_modules\postcss-selector-parser\dist\parser.js:174:16)
    at unclosed (C:\Users\admin\Documents\Projects\ClientApp\node_modules\postcss-selector-parser\dist\tokenize.js:110:19)
    at tokenize (C:\Users\admin\Documents\Projects\ClientApp\node_modules\postcss-selector-parser\dist\tokenize.js:216:13)
    at new Parser (C:\Users\admin\Documents\Projects\ClientApp\node_modules\postcss-selector-parser\dist\parser.js:144:44)
    at Processor._root (C:\Users\admin\Documents\Projects\ClientApp\node_modules\postcss-selector-parser\dist\processor.js:53:18)
    at Processor._runSync (C:\Users\admin\Documents\Projects\ClientApp\node_modules\postcss-selector-parser\dist\processor.js:100:21)
    at Processor.processSync (C:\Users\admin\Documents\Projects\ClientApp\node_modules\postcss-selector-parser\dist\processor.js:197:23)
    at parseSelectors (C:\Users\admin\Documents\Projects\ClientApp\node_modules\css-minimizer-webpack-plugin\node_modules\postcss-unique-selectors\dist\index.js:17:56)
    at C:\Users\admin\Documents\Projects\ClientApp\node_modules\css-minimizer-webpack-plugin\node_modules\postcss-unique-selectors\dist\index.js:33:26
    at C:\Users\admin\Documents\Projects\ClientApp\node_modules\css-minimizer-webpack-plugin\node_modules\postcss\lib\container.js:115:18
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: yarn 1.22.5
OS: win32 x64

Angular: 12.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. 

See: https://github.com/cssnano/cssnano/issues/1114

**Comment by alan-agius4** [comment]
From https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

> The shadow-piercing descendant combinator is deprecated and support is being removed from major browsers and tools. As such we plan to drop support in Angular (for all 3 of /deep/, >>> and ::ng-deep). Until then ::ng-deep should be preferred for a broader compatibility with the tools.

In this case CSSNano (which is a tool) no longer supports this, also this selector doesn’t work on a number of major browsers including Chrome https://developers.google.com/web/updates/2017/10/remove-shadow-piercing

**Comment by kemsky** [comment]
@alan-agius4, I don't think that browser support is relevant here. See example:

```
.impersonate-stop ::ng-deep label {
    background-size: 16px 16px;
    user-select: none;
    padding: 0 32px 0 7px;
    display: block;
    height: 30px;
    cursor: pointer;
}
```

is converted to:

```css
.impersonate-stop[_ngcontent-xln-c218] label {
    background-size: 16px 16px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    padding: 0 32px 0 7px;
    display: block;
    height: 30px;
    cursor: pointer;
}
```

It simply removes selector dependencies.

**Comment by alan-agius4** [comment]
Oh you are right. The problem is that CSSNano though needs to support `/deep/` since the CSS is optimised prior to feeding it to the compiler which does the above transformation.

**Comment by petebacondarwin** [comment]
Does css-nano support `::ng-deep`? This is the recommended approach rather than `/deep/`.

**Comment by petebacondarwin** [comment]
According to [this](https://cssnano.co/playground#eyJpbnB1dCI6Ijpob3N0IC5oZWFkZXItc2VsZWN0IC9kZWVwLyAqIHtcbiAgICBjdXJzb3I6IHBvaW50ZXI7XG59IiwiY29uZmlnIjoiLy8gY3NzbmFubyBjb25maWdcbntcbiAgXCJwcmVzZXRcIiA6IFwibGl0ZVwiLCAvLyBvbmxpbmUgcGxheWdyb3VuZCBjYW4gdXNlIG9ubHkgdGhlIFwibGl0ZVwiIHByZXNldFxufVxuIn0=) css-nano does support `/deep/`.

I see from the stacktrace that

**Comment by kemsky** [comment]
@petebacondarwin, @alan-agius4, I've already migrated to `::ng-deep` and can confirm that it works.

**Comment by alan-agius4** [comment]
> According to [this](https://cssnano.co/playground#eyJpbnB1dCI6Ijpob3N0IC5oZWFkZXItc2VsZWN0IC9kZWVwLyAqIHtcbiAgICBjdXJzb3I6IHBvaW50ZXI7XG59IiwiY29uZmlnIjoiLy8gY3NzbmFubyBjb25maWdcbntcbiAgXCJwcmVzZXRcIiA6IFwibGl0ZVwiLCAvLyBvbmxpbmUgcGxheWdyb3VuZCBjYW4gdXNlIG9ubHkgdGhlIFwibGl0ZVwiIHByZXNldFxufVxuIn0=) css-nano does support `/deep/`.
> 
> I see from the stacktrace that the error is actually coming from `postcss-selector-parser`, but according to its website, this also supports `/deep/`: https://github.com/postcss/postcss-selector-parser/blob/master/API.md#parsercombinatorprops

We use the default preset which has some additional optimisations which doesn’t support `/deep/`.

**Comment by alan-agius4** [comment]
Transferring to the FW to create a migration
