### ISSUE TITLE
TypeError: MessagePort was found in message but not listed in transferList

### ISSUE THREAD

**Issue by njifares** [angular/angular-cli#20875]
# Bug Report

### Affected Package
 - @angular/devkit/build-angular

### Is this a regression?

Got the below error after updating to Angular 12

### Description
I've updated my project from v11.x to v12.x using `ng update`. When I run `ng serve` I got the below error:

<pre><code>
(node:44810) UnhandledPromiseRejectionWarning: TypeError: MessagePort was found in message but not listed in transferList
    at new Worker (internal/worker.js:144:17)
    at SassWorkerImplementation.createWorker (/Users/serafijnboelaert/Documents/tengu/code/tengu-platform-web/node_modules/@angular-devkit/build-angular/src/sass/sass-service.js:96:24)
    at SassWorkerImplementation.render (/Users/serafijnboelaert/Documents/tengu/code/tengu-platform-web/node_modules/@angular-devkit/build-angular/src/sass/sass-service.js:62:40)
    at Object.loader (/Users/serafijnboelaert/Documents/tengu/code/tengu-platform-web/node_modules/sass-loader/dist/index.js:46:3)
(node:44810) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 103)
</code></pre>

## Minimal Reproduction
Unfortunately I cannot reproduce the issue in a new project nor can I share the current code as it's confidential. I'm happy to provide more information when needed.

## Exception or Error
<pre><code>
(node:44810) UnhandledPromiseRejectionWarning: TypeError: MessagePort was found in message but not listed in transferList
    at new Worker (internal/worker.js:144:17)
    at SassWorkerImplementation.createWorker (/Users/serafijnboelaert/Documents/tengu/code/tengu-platform-web/node_modules/@angular-devkit/build-angular/src/sass/sass-service.js:96:24)
    at SassWorkerImplementation.render (/Users/serafijnboelaert/Documents/tengu/code/tengu-platform-web/node_modules/@angular-devkit/build-angular/src/sass/sass-service.js:62:40)
    at Object.loader (/Users/serafijnboelaert/Documents/tengu/code/tengu-platform-web/node_modules/sass-loader/dist/index.js:46:3)
(node:44810) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 103)
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.1
Node: 12.14.0
Package Manager: npm 6.14.8
OS: darwin x64

Angular: 12.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Comment by JoostK** [comment]
It looks like your NodeJS version is too old. A minimum of Node 12.20 is needed for v12.

**Comment by njifares** [comment]
@JoostK Confirmed. It's fixed with the node LTS (14) version

**Comment by exeptionerror** [comment]
[[Solved] UnhandledPromiseRejectionWarning: TypeError: MessagePort was found in message but not listed in transferList at new Worker](https://exerror.com/solved-unhandledpromiserejectionwarning-typeerror-messageport-was-found-in-message-but-not-listed-in-transferlist-at-new-worker/)

**Comment by KhizerRehan** [comment]
Thanks Upgrading to LTS node@v12.22.1 fixed this issue. :)
