### ISSUE TITLE
updating @angular/cli 12 to 12.0.1 fails using local ng

### ISSUE THREAD

**Issue by 9034725985** [angular/angular-cli#20907]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
12.0.0

### Description

 A clear and concise description of the problem...

Updating from 12.0,0 to 12.0.1 fails

## 🔬 Minimal Reproduction

[kushal@april87 angulartwelve]$ time yarn run ng update
yarn run v1.22.10
$ ng update
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
An unhandled exception occurred: Cannot locate bin for temporary package: @angular/cli.
See "/tmp/ng-hX6NSb/angular-errors.log" for further details.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

real    0m19.320s
user    0m7.691s
sys     0m1.243s
[kushal@april87 angulartwelve]$ cd ~/src/angular/angulartwelve/
[kushal@april87 angulartwelve]$ cd ~/src/angular/angulartwelve/; time ng update
Using package manager: 'yarn'
Collecting installed dependencies...
Found 35 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       12.0.0 -> 12.0.1         ng update @angular/cli

    There might be additional packages which don't provide 'ng update' capabilities that are outdated.
    You can update the additional packages by running the update command of your package manager.

real    0m13.665s
user    0m3.535s
sys     0m0.321s
[kushal@april87 angulartwelve]$

## 🔥 Exception or Error

<pre><code>

An unhandled exception occurred: Cannot locate bin for temporary package: @angular/cli.
</code></pre>

## 🌍 Your Environment

<pre><code>

Your global Angular CLI version (12.0.1) is greater than your local version (12.0.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: yarn 1.22.10
OS: linux x64

Angular: 12.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@angular/cli                    12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

Fedora 34, nvm node lts

$ cat /tmp/ng-hX6NSb/angular-errors.log
[error] Error: Cannot locate bin for temporary package: @angular/cli.
    at Object.runTempPackageBin (/home/kushal/src/angular/angulartwelve/node_modules/@angular/cli/utilities/install-package.js:116:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UpdateCommand.validateAndRun (/home/kushal/src/angular/angulartwelve/node_modules/@angular/cli/models/command.js:136:22)
    at async Object.runCommand (/home/kushal/src/angular/angulartwelve/node_modules/@angular/cli/models/command-runner.js:205:24)
    at async default_1 (/home/kushal/src/angular/angulartwelve/node_modules/@angular/cli/lib/cli/index.js:70:31)

ng update works outside

$ time ng update @angular/cli
Using package manager: 'yarn'
Collecting installed dependencies...
Found 35 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "12.0.1" (was "12.0.0")...
    Updating package.json with dependency @angular/cli @ "12.0.1" (was "12.0.0")...
  UPDATE package.json (1566 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/cli' **

▸ Remove invalid 'skipTests' option in '@schematics/angular:module' Angular schematic options.
  Migration completed.

real    1m14.091s
user    0m24.486s
sys     0m9.392s

**Comment by 9034725985** [comment]
was a bug in 12.0.0 https://github.com/angular/angular-cli/issues/20872#issuecomment-845184818
