### ISSUE TITLE
Angular 12: Production build Error: Expected a pseudo-class or pseudo-element

### ISSUE THREAD

**Issue by manzonif** [angular/angular-cli#20921]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

may be. Is something like [19561](https://github.com/angular/angular-cli/issues/19561)

### Description
after update to 12.0.1, production build process end with following "anonymous" error:

## 🔥 Exception or Error

<pre><code>
angular-resource-output-1.css - Error: angular-resource-output-1.css from Css Minimizer
Error: Expected a pseudo-class or pseudo-element.
    at D:\Expometals\Expometal\angular-resource-output-1.css:1:1
    at Root._error (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\parser.js:174:16)
    at Root.error (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\selectors\root.js:43:19)
    at Parser.error (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\parser.js:740:21)
    at Parser.expected (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\parser.js:1129:19)
    at Parser.pseudo (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\parser.js:875:19)
    at Parser.parse (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\parser.js:1080:14)
    at Parser.loop (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\parser.js:1039:12)
    at new Parser (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\parser.js:164:10)
    at Processor._root (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\processor.js:53:18)
    at Processor._runSync (D:\Expometals\Expometal\node_modules\postcss-selector-parser\dist\processor.js:100:21)
</code></pre>

## 🔬 Minimal Reproduction

Error log doesn't give any information about the file that cause error, so I don't have idea on how can reproduce it.

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.0.3
Node:  v14.16.0
OS: windows 10 x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/build-angular   12.0.1
@angular-devkit/build-optimizer": "~0.1200.1",
@angular/cli": "12.0.1",
@angular/compiler-cli": "12.0.1",
typescript                     4.2.4

</code></pre>

**Comment by manzonif** [comment]
Debugging build process I found the error:

```typescript
@Component({
  selector: 'mat-editor',
  template: '<ng-template></ng-template>',
  **styles: ['mat-editor: { display: block; }'],**
  host: {
    '[id]': 'id',
    '[attr.aria-describedby]': 'describedBy',
  },
  providers: [{ provide: MatFormFieldControl, useExisting: EditorComponent }]
})
```
That's why styleLint didn't report it.

**Comment by alan-agius4** [comment]
We should provide clear error message.
