### ISSUE TITLE
.An unhandled exception occurred: [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by fanguangjian** [angular/angular-cli#20955]
[error] Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/postcss/lib/postcss.js:55:10)
    at cssnanoPlugin (/Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/cssnano/dist/index.js:137:31)
    at output (/Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/@angular-devkit/build-angular/src/webpack/plugins/optimize-css-webpack-plugin.js:96:21)
    at new Promise (<anonymous>)
    at /Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/@angular-devkit/build-angular/src/webpack/plugins/optimize-css-webpack-plugin.js:93:38
    at Array.map (<anonymous>)
    at /Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/@angular-devkit/build-angular/src/webpack/plugins/optimize-css-webpack-plugin.js:59:18
    at /Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/@angular-devkit/build-angular/src/webpack/plugins/optimize-css-webpack-plugin.js:41:24
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:65:17)
    at AsyncSeriesHook.lazyCompileHook (/Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/webpack/lib/Compilation.js:1409:36
    at eval (eval at create (/Users/fangj/Desktop/Code/test/eiz-oms-advanced/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
