### ISSUE TITLE
Cannot serve project after upgrading to RC.7

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#2102]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
El caPITAN

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.11-webpack.8
node: 5.11.0
os: darwin x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Just run `npm start` or `ng serve` after upgrading.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
The "defaults.prefix" and "defaults.sourceDir" properties of angular-cli.json are deprecated in favor of "apps[0].root" and "apps[0].prefix". Please update in order to avoid errors in future versions of angular-cli.
The "defaults.prefix" and "defaults.sourceDir" properties of angular-cli.json are deprecated in favor of "apps[0].root" and "apps[0].prefix". Please update in order to avoid errors in future versions of angular-cli.
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.getWebpackCommonConfig (/Projects/Jexia/WebApp/node_modules/angular-cli/addon/ng2/models/webpack-build-common.ts:23:25)
    at new NgCliWebpackConfig (/Projects/Jexia/WebApp/node_modules/angular-cli/addon/ng2/models/webpack-config.ts:13:30)
    at Class.exports.default.Task.extend.run (/Projects/Jexia/WebApp/node_modules/angular-cli/addon/ng2/tasks/serve-webpack.ts:19:22)
    at /Projects/Jexia/WebApp/node_modules/angular-cli/addon/ng2/commands/serve.ts:84:26
    at tryCatch (/Projects/Jexia/WebApp/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:195:12)
    at invokeCallback (/Projects/Jexia/WebApp/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:210:13)
    at publish (/Projects/Jexia/WebApp/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:178:7)
    at flush (/Projects/Jexia/WebApp/node_modules/es6-promise/dist/lib/es6-promise/asap.js:94:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by deebloo** [comment]
@vapits it is an issue with your angular-cli.json file.

```The "defaults.prefix" and "defaults.sourceDir" properties of angular-cli.json are deprecated in favor of "apps[0].root" and "apps[0].prefix". Please update in order to avoid errors in future versions of angular-cli.```

**Comment by vapits** [comment]
I see @deebloo thx.
Is there a doc on how to fill some of the params? Example styles root etc?

**Comment by filipesilva** [comment]
Thanks @deebloo for the spot on debugging. We're going to have a much more detailed upgrade guide soon to address these config changes.

@vapits as far as I can tell, `provide` was removed in RC6: https://github.com/angular/angular/blob/master/CHANGELOG.md
> core: remove deprecated provider/bind API

You will need to change your code to not use it, mostly by transitioning to NgModules. See https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html for more info.

**Comment by vapits** [comment]
@filipesilva  thx, my bad :)
