### ISSUE TITLE
Karma config after RC6

### ISSUE THREAD

**Issue by ulou** [angular/angular-cli#2103]
1.  angular-cli: 1.0.0-beta.10
node: 6.3.0
os: win32 x64

After upgrading my project to rc6, my tests stop working. I know that karma conf got changed. I tried to figure it out, but its taking me so long. 

**karma.conf.js**
```
`module.exports = function (config) {

  config.set({
    basePath: '..',
    frameworks: ['jasmine'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher')
    ],

    customLaunchers: {
      // From the CLI. Not used here but interesting
      // chrome setup for travis CI using chromium
      Chrome_travis_ci: {
        base: 'Chrome',
        flags: ['--no-sandbox']
      },
      Chrome_without_security: {
        base: 'Chrome',
        flags: ['--disable-web-security']
      }

    },
    files: [
      // System.js for module loading
      'dist/vendor/systemjs/dist/system.src.js',

      // Polyfills
      'dist/vendor/core-js/client/shim.js',

      // Reflect and Zone.js
      'dist/vendor/reflect-metadata/Reflect.js',
      'dist/vendor/zone.js/dist/zone.js',
      'dist/vendor/zone.js/dist/long-stack-trace-zone.js',
      'dist/vendor/zone.js/dist/proxy.js',
      'dist/vendor/zone.js/dist/sync-test.js',
      'dist/vendor/zone.js/dist/jasmine-patch.js',
      'dist/vendor/zone.js/dist/async-test.js',
      'dist/vendor/zone.js/dist/fake-async-test.js',

      // RxJs.
      {pattern: 'dist/vendor/rxjs/**/*.js', included: false, watched: false},
      {pattern: 'dist/vendor/rxjs/**/*.js.map', included: false, watched: false},

      // Angular 2 itself and the testing library
      {pattern: 'dist/vendor/@angular/**/*.js', included: false, watched: false},
      {pattern: 'dist/vendor/@angular/**/*.js.map', included: false, watched: false},

      {pattern: 'system-config.js', included: false, watched: false},
      {pattern: 'config/karma-test-shim.js', included: true, watched: true},
    ],

    exclude: [
      // Vendor packages might include spec files. We don't want to use those.
      'dist/vendor/**/*.spec.js'
    ],
    preprocessors: {},
    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome', 'Chrome_without_security'],
    singleRun: false
  })
}
`
```
**karma-test-shim.js**
```
`// Test shim for Karma, needed to load files via SystemJS

/*global jasmine, __karma__, window*/
Error.stackTraceLimit = Infinity;
jasmine.DEFAULT_TIMEOUT_INTERVAL = 1000;

__karma__.loaded = function () {
};

var distPath = '/base/dist/';
var appPaths = ['app']; //Add all valid source code folders here

function isJsFile(path) {
  return path.slice(-3) == '.js';
}

function isSpecFile(path) {
  return path.slice(-8) == '.spec.js';
}

function isAppFile(path) {
  return isJsFile(path) && appPaths.some(function(appPath) {
      var fullAppPath = distPath + appPath + '/';
      return path.substr(0, fullAppPath.length) == fullAppPath;
    });
}

var allSpecFiles = Object.keys(window.__karma__.files)
  .filter(isSpecFile)
  .filter(isAppFile);

// Load our SystemJS configuration.
System.config({
  baseURL: distPath
});

System.import('system-config.js').then(function() {
  // Load and configure the TestComponentBuilder.
  return Promise.all([
    System.import('@angular/core/testing'),
    System.import('@angular/platform-browser-dynamic/testing')
  ]).then(function (providers) {
    var coreTesting = providers[0];
    var browserTesting = providers[1];
    coreTesting.TestBed.initTestEnvironment(
      browserTesting.BrowserDynamicTestingModule,
      browserTesting.platformBrowserDynamicTesting());
  });
}).then(function() {
  // Finally, load all spec files.
  // This will run the tests directly.
  return Promise.all(
    allSpecFiles.map(function (moduleName) {
      return System.import(moduleName);
    }));
}).then(__karma__.start, __karma__.error);
`
```

**Console output**
```
`> ng test --build false --browsers Chrome_without_security

(node:5264) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
14 09 2016 11:14:49.555:WARN [watcher]: Pattern "C:/Users/mkonczyk/Desktop/kdsp-manager/modules/frontend/dist/vendor/core-js/client/shim.js" does not match any file.
14 09 2016 11:14:51.300:WARN [watcher]: Pattern "C:/Users/mkonczyk/Desktop/kdsp-manager/modules/frontend/system-config.js" does not match any file.
14 09 2016 11:14:51.772:WARN [karma]: No captured browser, open http://localhost:9876/
14 09 2016 11:14:51.795:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
14 09 2016 11:14:51.811:INFO [launcher]: Starting browser Chrome
14 09 2016 11:14:53.845:INFO [Chrome 52.0.2743 (Windows 7 0.0.0)]: Connected on socket /#nur8CJ5WM9hurtnCAAAA with id 99730673
14 09 2016 11:14:54.106:WARN [web-server]: 404: /base/dist/system-config.js
Missing error handler on `socket`.
TypeError: (msg || "").replace is not a function
    at C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\karma\lib\reporter.js:45:23
    at onBrowserError (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\karma\lib\reporters\base.js:58:60)
    at .<anonymous> (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at onKarmaError (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\karma\lib\browser.js:95:13)
    at Socket.<anonymous> (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\karma\lib\events.js:13:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Socket.onevent (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\socket.io\lib\socket.js:335:8)
    at Socket.onpacket (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\socket.io\lib\socket.js:295:12)
    at Client.ondecoded (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\socket.io\lib\client.js:193:14)
    at Decoder.Emitter.emit (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\socket.io-parser\index.js:247:12)
    at Client.ondata (C:\Users\mkonczyk\Desktop\kdsp-manager\modules\frontend\node_modules\socket.io\lib\client.js:175:18)
    at emitOne (events.js:96:13)
14 09 2016 11:14:56.121:WARN [Chrome 52.0.2743 (Windows 7 0.0.0)]: Disconnected (1 times)`
```

maybe someone could help or share workings configs?

**Comment by deebloo** [comment]
take a look in the source code and you can find the config. don't be afraid to look at the source. 
https://github.com/angular/angular-cli/blob/master/packages/angular-cli/blueprints/ng2/files/karma.conf.js

**Comment by deebloo** [comment]
also I would investigate moving to the a angular-cli@weback release as that is the one that is being working on going forward and the one that will be the default release before long.

**Comment by ulou** [comment]
@deebloo at this moment I would like to avoid webpack, but thanks for help

**Comment by filipesilva** [comment]
@ulou RC6 introduced a lot of changes in how testing bundles are exposed, see https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes-1 for information about that.

https://github.com/angular/quickstart is probably the easiest up to date repo to check a final configuration.
