### ISSUE TITLE
Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js)

### ISSUE THREAD

**Issue by Whizfactor** [angular/angular-cli#21206]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Version 11

### Description

 A clear and concise description of the problem...

After serving my project, i noticed a the error log in the problem tab at the footer of visual studio code and the error at to do with my **main.ts** and **polyfills.ts**. I had ran **npm update -g** and then it updated and solved some update issues that **ng audit fix** couldn't fix but then after serving the project the error came. 

## 🔥 Exception or Error

<pre><code>

⠋ Generating browser application bundles...(node:1764) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'visit' of undefined
    at AstTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:81:24)     
    at AstTranslator.visitKeyedRead (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:150:66)
    at KeyedRead.visit (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler\bundles\compiler.umd.js:8336:28)
    at AstTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:81:24)     
    at Object.astToTypescript (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:56:27)      
    at TcbExpressionTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1909:33)
    at tcbExpression (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1897:27)       
    at TcbUnclaimedInputsOp.execute (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1010:32)
    at Scope.executeOp (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1561:26)     
    at Scope.render (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1468:22)        
(node:1764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 69)
⠙ Generating browser application bundles (phase: building)...(node:1764) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 69)
✔ Browser application bundle generation complete.

6 unchanged chunks

Build at: 2021-06-25T13:39:16.217Z - Hash: fe7982534f34a0e0698c - Time: 1248ms

./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:0&sockPath=/sockjs-node - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: Cannot read property 'visit' of undefined
    at AstTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:81:24)     
    at AstTranslator.visitKeyedRead (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:150:66)
    at KeyedRead.visit (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler\bundles\compiler.umd.js:8336:28)
    at AstTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:81:24)     
    at Object.astToTypescript (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:56:27)      
    at TcbExpressionTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1909:33)
    at tcbExpression (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1897:27)       
    at TcbUnclaimedInputsOp.execute (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1010:32)
    at Scope.executeOp (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1561:26)     
    at Scope.render (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1468:22)        

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: Cannot read property 'visit' of undefined
    at AstTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:81:24)
    at AstTranslator.visitKeyedRead (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:150:66)
    at KeyedRead.visit (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler\bundles\compiler.umd.js:8336:28)
    at AstTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:81:24)     
    at Object.astToTypescript (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:56:27)      
    at TcbExpressionTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1909:33)
    at tcbExpression (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1897:27)       
    at TcbUnclaimedInputsOp.execute (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1010:32)
    at Scope.executeOp (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1561:26)     
    at Scope.render (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1468:22)        

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: Cannot read property 'visit' of undefined
    at AstTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:81:24)     
    at AstTranslator.visitKeyedRead (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:150:66)
    at KeyedRead.visit (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler\bundles\compiler.umd.js:8336:28)
    at AstTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:81:24)     
    at Object.astToTypescript (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:56:27)      
    at TcbExpressionTranslator.translate (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1909:33)
    at tcbExpression (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1897:27)       
    at TcbUnclaimedInputsOp.execute (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1010:32)
    at Scope.executeOp (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1561:26)     
    at Scope.render (C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1468:22)  

</code></pre>

## 🌍 Your Environment

<pre><code>

Your global Angular CLI version (12.1.0) is greater than your local version (12.0.5). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.5
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.0
... animations, common, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.5
@angular/cli                    12.0.5
@angular/compiler               12.0.5
@angular/compiler-cli           12.1.0
@angular/localize               12.0.5
@nguniversal/builders           12.0.0
@nguniversal/express-engine     12.0.0
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

(C:\Users\USER\Samazu-Technology-Limited\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js)

**Comment by clydin** [comment]
From the version output, it appears the project has a mixture of 12.0.0, 12.0.5, and 12.1.0 Angular dependencies. The following in particular should be the same version:
```
@angular/compiler               12.0.5
@angular/compiler-cli           12.1.0
```
Can you try adjusting the `package.json` to synchronize the versions?  Alternatively, you can try running `ng update @angular/core @angular/cli @nguniversal/express-engine`.

**Comment by Whizfactor** [comment]
Thanks The Problem Is now sorted out @clydin. Thanks. Unto the next battle i go.
