### ISSUE TITLE
Running e2e gives UNABLE_TO_GET_ISSUER_CERT_LOCALLY error

### ISSUE THREAD

**Issue by spearsonwork** [angular/angular-cli#21303]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes 7.3.8 worked.

### Description
Running e2e gives UNABLE_TO_GET_ISSUER_CERT_LOCALLY error.
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Doesn't work from the beginning.
e.g.
ng new myapp
npm i 
ng e2e

## 🔥 Exception or Error

<pre><code>
[12:06:21] I/file_manager - creating folder C:\testapp\node_modules\protractor\node_modules\webdriver-manager\selenium
[12:06:21] I/config_source - curl -oC:\testapp\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Emitted 'error' event on Request instance at:
    at Request.onRequestError (C:\testing\testapp\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:327:22)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.1.1
Node: 14.15.4
Package Manager: npm 6.14.10
OS: win32 x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I suspect that this is probably caused by a custom network proxy that acts like man in the middle while downloading from external sources. Are you using a proxy?

See: https://github.com/nodejs/help/issues/979

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
