### ISSUE TITLE
ng fails on Version.assertPostWebpackVersion() on 1.0.0-beta.14

### ISSUE THREAD

**Issue by andrevmatos** [angular/angular-cli#2135]
1. OS?
Arch Linux with latest kernel and Node 6.5.0 through NVM

2. Versions:
angular-cli: 1.0.0-beta.14
node: 6.5.0
os: linux x64

3. Repro steps. 
Local installation, empty folder:
npm i angular-cli
./node_modules/.bin/ng init # fails

4. The log given by the failure.
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Function.Version.fromProject (/sec/Dev/Link/scripts/web_files_py/flask_ged/ng/node_modules/angular-cli/upgrade/version.js:87:31)
    at Function.Version.isPreWebpack (/sec/Dev/Link/scripts/web_files_py/flask_ged/ng/node_modules/angular-cli/upgrade/version.js:111:31)
    at Function.Version.assertPostWebpackVersion (/sec/Dev/Link/scripts/web_files_py/flask_ged/ng/node_modules/angular-cli/upgrade/version.js:97:18)
    at /sec/Dev/Link/scripts/web_files_py/flask_ged/ng/node_modules/angular-cli/bin/ng:25:15
    at /sec/Dev/Link/scripts/web_files_py/flask_ged/ng/node_modules/resolve/lib/async.js:44:21
    at ondir (/sec/Dev/Link/scripts/web_files_py/flask_ged/ng/node_modules/resolve/lib/async.js:187:31)
    at /sec/Dev/Link/scripts/web_files_py/flask_ged/ng/node_modules/resolve/lib/async.js:153:3

5. Mention any other details that might be useful.
Commenting out the line 25 on angular-cli/bin/ng makes everything work again.
This with the check Version.assertPostWebpackVersion(), was added on commit 21003b1dc359e5d32e493911ceb5b72966d4c0ad .

**Comment by Aorewen** [comment]
Same with both Windows 7 and Windows 8.1
node version : 6.5
npm version : 3.10.3

Steps : 

npm install -g angular-cli@latest
go in work directory
npm install angular-cli@latest
ng new

**Comment by bradygossett** [comment]
same on macOS

**Comment by alexverdaguer** [comment]
same here on Mac OS sierra with node 6.5.0

**Comment by iuliust** [comment]
same on Linux Mint with node 6.5

**Comment by Mattee** [comment]
Same here on Mac OSX Yosemite and Windows 10 with node 6.5.0.

**Comment by Aorewen** [comment]
any news or trick about this?

**Comment by hopefullToo** [comment]
Same on OS X El Capitan
node v6.6.0
npm 3.10.7

Installed latest version (*-beta.14)
tried ng --help
same error

**Comment by andrevmatos** [comment]
@Aorewen Simplest workaround to continue working in your project is comment line 25 of node_modules/angular-cli/bin/ng :
 // Version.assertPostWebpackVersion();
Until it is fixed properly.

**Comment by hopefullToo** [comment]
I just commented out line 25 on angular-cli/bin/ng .
but now ng hangs if I call ng --help
a new line is displayed and I can enter any text but n nothing happens.
I quit the call with ^C.

**Comment by alexverdaguer** [comment]
Updated node to v6.6.0 and now it works !

**Comment by JelF** [comment]
Persisted in v6.6.0 for me
```
➜  angular nvm exec 6.6.0 ng 
Running node v6.6.0 (npm v3.10.7)
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Function.Version.fromProject (/home/jelf/.nvm/versions/node/v6.6.0/lib/node_modules/angular-cli/upgrade/version.js:87:31)
    at Function.Version.isPreWebpack (/home/jelf/.nvm/versions/node/v6.6.0/lib/node_modules/angular-cli/upgrade/version.js:111:31)
    at Function.Version.assertPostWebpackVersion (/home/jelf/.nvm/versions/node/v6.6.0/lib/node_modules/angular-cli/upgrade/version.js:97:18)
    at /home/jelf/.nvm/versions/node/v6.6.0/lib/node_modules/angular-cli/bin/ng:25:15
    at /home/jelf/.nvm/versions/node/v6.6.0/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:44:21
    at ondir (/home/jelf/.nvm/versions/node/v6.6.0/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:187:31)
    at /home/jelf/.nvm/versions/node/v6.6.0/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:153:39
```

OS gentoo linux, angular-cli@1.0.0-beta.15

**Comment by programmerinprogress** [comment]
Same issue for me on node 6.6.0, windows 10, I just get the upgrade warning and I'm asking for the latest version of angular-cli, I've done about 5 re-install cycles now.

**Comment by caseyhoward** [comment]
I'm on a linux machine and this happens in one directory but not in another. Weird.

**Comment by caseyhoward** [comment]
Upon further review, I think I see the error:

https://github.com/angular/angular-cli/blob/master/packages/angular-cli/upgrade/version.ts#L79

That line should either check if the file exists or be moved into the try block below (line 82).

**Comment by JelF** [comment]
@caseyhoward can you make a diff?

**Comment by ValeryVS** [comment]
@caseyhoward 
No need for more try..catch
There is fix, wait for merging
#2178 
https://github.com/angular/angular-cli/pull/2178/files

Workaround: create blank angular-cli.json

**Comment by filipesilva** [comment]
@hansl can you have a look?

**Comment by davemo88** [comment]
+1

error on node 6.6.0, npm 3.10.3, osx 10.10.5

if i do touch angular-cli.json then the error changes to:

module.js:457
    throw err;
    ^

Error: Cannot find module 'ember-cli/lib/cli'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/david/node_modules/angular-cli/lib/cli/index.js:4:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by nlovett** [comment]
+1

[imho] this should work:

$ mkdir noglobal
$ cd noglobal
$ npm init -f
$ npm i -D angular-cli@latest
$ ./node_modules/.bin/ng init

**Comment by tobiasfi** [comment]
+1 👍 

Same error here.

Windows 10
Node 6.6.0
npm 3.10.2

**Comment by GabrielDumbrava** [comment]
Same with
Linux
node 6.7.0
npm 3.10.3
angular-cli 1.0.0-beta.16

**Comment by tobiasfi** [comment]
Strange strange strange:
I get the error in some directories and not in others!!!
I can not find out what distinquishes them, it does not appear to be the name or emptyness ... òO

**Comment by PhilippSoehnlein** [comment]
To me it looks like it's a thing about installing the CLI globally or not. It works for me, when I install it via `npm install --global angular-cli`, but doing it locally (`npm install angular-cli`) and calling it from my local `node_modules`-folder doesn't.

**Comment by tobiasfi** [comment]
I did install it globally and it did not work for me.

**Comment by jigfox** [comment]
Same here with macOS Sierra

node@6.6.0
npm@3.10.8
angular-cli@1.0.0-beta.16


if I run `ng --version` I get the following error:

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Function.Version.fromProject (/usr/local/lib/node_modules/angular-cli/upgrade/version.js:87:31)
    at Function.Version.isPreWebpack (/usr/local/lib/node_modules/angular-cli/upgrade/version.js:111:31)
    at Function.Version.assertPostWebpackVersion (/usr/local/lib/node_modules/angular-cli/upgrade/version.js:97:18)
    at /usr/local/lib/node_modules/angular-cli/bin/ng:25:15
    at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:44:21
    at ondir (/usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:187:31)
    at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:153:39

```

**Comment by matt-erhart** [comment]
Same here. ng -v only worked with an angular-cli.json in the pwd.
angular-cli: 1.0.0-beta.16
node: 6.7.0 (and 6.6.0)
os: win32 x64

**Comment by vadost** [comment]
Same on ubuntu 14.04, node v6.7.0, npm 3.10.3. Please help!

**Comment by NilsHolger** [comment]
angular-cli: 1.0.0 beta.16
ng build --prod
deploy to firebase dist folder
it was a mess, CSS and JS missing
now cli is broken
always get message
c:\Dev\angular2showcase>ng --v
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Function.Version.fromProject (C:\Users\Nils\AppData\Roaming\npm\node_modu
les\angular-cli\upgrade\version.js:87:31)
    at Function.Version.isPreWebpack (C:\Users\Nils\AppData\Roaming\npm\node_mod
ules\angular-cli\upgrade\version.js:111:31)
    at Function.Version.assertPostWebpackVersion (C:\Users\Nils\AppData\Roaming\
npm\node_modules\angular-cli\upgrade\version.js:97:18)
    at C:\Users\Nils\AppData\Roaming\npm\node_modules\angular-cli\bin\ng:25:15
    at C:\Users\Nils\AppData\Roaming\npm\node_modules\angular-cli\node_modules\r
esolve\lib\async.js:44:21
    at ondir (C:\Users\Nils\AppData\Roaming\npm\node_modules\angular-cli\node_mo
dules\resolve\lib\async.js:187:31)
    at C:\Users\Nils\AppData\Roaming\npm\node_modules\angular-cli\node_modules\r
esolve\lib\async.js:153:39

**Comment by zackarychapple** [comment]
I can confirm that this is happening on Mac when trying to bump from .15 to .16
```
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.16
node: 6.3.1
os: darwin x64
```

Failing with this error. 
```
Path must be a string. Received null
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at Class.exports.default.Task.extend.run (/Users/zchapple/code/wfa_ng2/node_modules/angular-cli/tasks/build-webpack-watch.js:14:26)
    at Class.Command.extend.run (/Users/zchapple/code/wfa_ng2/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/zchapple/code/wfa_ng2/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/Users/zchapple/code/wfa_ng2/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/zchapple/code/wfa_ng2/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/zchapple/code/wfa_ng2/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/zchapple/code/wfa_ng2/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by vadost** [comment]
Guys, who found a solution to this problem?

**Comment by datrinh** [comment]
Not sure if this is the same issue, but I'm getting this error:

```
Path must be a string. Received { source: 'environments/environment.ts',
  dev: 'environments/environment.ts',
  prod: 'environments/environment.prod.ts' }
```

Newly installed ng-cli with these version:
```
angular-cli: 1.0.0-beta.25.5
node: 6.7.0
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/material: 2.0.0-beta.1
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3
```

Barely did any coding. Added 4 components and one service, also angular/material and now this error is thrown when I run `ng serve`
