### ISSUE TITLE
Erratic Component Unit Test Failures since update to Beta.14 (ngDestroy)

### ISSUE THREAD

**Issue by tomwanzek** [angular/angular-cli#2157]
> Please provide us with the following information:
> ---------------------------------------------------------------

**(1.) OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)**

_Windows 10_

**(2.) Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:**

_angular-cli: 1.0.0-beta.14
node: 6.5.0
os: win32 x64_

**(3.) Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.**

I updated from angular-cli (webpack.8/RC.5) to cli versions webpack.9-4/RC.7 and now beta.14/Angular 2 v2.0.0. I followed standard update steps (Uninstall global cli, clean npm cache, install new global cli, run `ng init` on existing project). All was well from the perspective of `ng build` and `ng serve` working as expected (with --prod as well) :+1: 

When I ran `ng test`, I noticed several component unit tests failing, which passed before the update. There is also a new warning (see below). The original project uses attribute-selector components to render with D3 inside the component.

I tried narrowing down, where the error is caused, and it seems related to erratic behavior in the life cycle hooks of the components during testing. (So this may well be an Angular issue and not an issue of the cli setup?)

A minimal example to reproduce the error can be obtained as follows:
* create a new project
* install a D3 service using `npm install d3-ng2-service --save`
* add the service to the module providers using `providers = [ D3Service ]`
* add a component using `ng generate component d3-test`
* Change the component code to be the following:
```ts
// d3-test.component.ts
import { Component, ElementRef, OnDestroy, OnInit } from '@angular/core';

import { D3Service, D3, Selection } from 'd3-ng2-service';

@Component({
    selector: 'g[d3-test]',
    template: `<svg:g class="inner-group"></svg:g>`
})
export class D3TestComponent implements OnInit, OnDestroy {

    private d3: D3;
    private nativeElement: SVGGElement;
    private d3HostElement: Selection<SVGGElement, any, null, undefined>;
    private d3InnerGroup: Selection<SVGGElement, any, null, undefined>;
    constructor(elementRef: ElementRef, d3Service: D3Service) {
        this.d3 = d3Service.getD3();
        this.nativeElement = elementRef.nativeElement;
    }

    ngOnDestroy() {
        console.log('Called ngOnDestroy with nativeElement tagName: ', this.nativeElement.tagName);
        console.log('Called ngOnDestroy with d3 still defined: ', (this.d3) ? true : false);
        console.log('Called ngOnDestroy with d3HostElement: ', this.d3HostElement);
        console.log('Called ngOnDestroy with d3InnerGroup: ', this.d3InnerGroup);

        if (this.nativeElement && !this.d3HostElement.empty()) {
            this.d3HostElement.remove();
        }

    }

    ngOnInit() {
        console.log('Called ngOnInit with nativeElement tagName: ', this.nativeElement.tagName);
        let d3 = this.d3;
        if (this.nativeElement && this.nativeElement.tagName === 'g') {

            this.d3HostElement = d3.select<SVGGElement, any>(this.nativeElement);
            this.d3InnerGroup = this.d3HostElement.select<SVGGElement>('g.inner-group');
            this.d3InnerGroup
                .append<SVGRectElement>('rect')
                .attr('x', 0)
                .attr('y', 0)
                .attr('width', 200)
                .attr('height', 150)
                .style('fill', 'red');

            console.log('Called ngOnInit with d3HostElement: ', this.d3HostElement);
            console.log('Called ngOnInit with d3InnerGroup: ', this.d3InnerGroup);
        }
    }

}
```
* change the component unit test file to be the following:
```ts
/* tslint:disable:no-unused-variable */

// d3-test.component.spec.ts
import { TestBed, async } from '@angular/core/testing';
import { Component } from '@angular/core';

import { D3Service, D3, Selection } from 'd3-ng2-service';

import { D3TestComponent } from './d3-test.component';


@Component({
    selector: 'app-mock-parent',
    template: `<svg width="300" height="200"><g d3-test></g></svg>`
})
class MockParent {}

describe('Component: D3Test', () => {
    beforeEach(() => {
        TestBed.configureTestingModule({
            declarations: [
                MockParent,
                D3TestComponent
            ],
            providers: [
                D3Service
            ]
        });
    });

    it('should create the MockParent', async(() => {
        let fixture = TestBed.createComponent(MockParent);
        let app = fixture.debugElement.componentInstance;
        expect(app).toBeTruthy();
    }));

  it('should contain an "svg" element with dimensions 300x200', async(() => {
    let fixture = TestBed.createComponent(MockParent);
    fixture.detectChanges();
    let compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('svg')).toBeTruthy('svg element missing');
    expect(compiled.querySelector('svg').clientWidth).toBe(300);
    expect(compiled.querySelector('svg').clientHeight).toBe(200);
  }));

  it('should contain a "rect" element with dimensions 200x150', async(() => {
    let fixture = TestBed.createComponent(MockParent);
    fixture.detectChanges();
    let compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('rect')).toBeTruthy('rect element missing');
    expect(compiled.querySelector('rect').width.baseVal.value).toBe(200, 'wrong width');
    expect(compiled.querySelector('rect').height.baseVal.value).toBe(150, 'wrong height');
  }));


});
```

Running `ng test` with the code as above will fail and show the output below. Notice that, private members related to d3 selections are **all of a sudden** `undefined` in `ngOnDestroy() {...}`, whereas others are still  well-defined.

In the next section (4), I am including the karma log for the failed tests. It also shows the previously not seen two warnings related to `system_js_ng_module_factory_loader.js`

**(4.) The log given by the failure. Normally this include a stack trace and some
   more information.**

```
15 09 2016 21:19:14.554:WARN [karma]: No captured browser, open http://localhost:9876/

WARNING in ./src/app/d3-test/d3-test.component.spec.ts
[15, 7]: The name of the class MockParent should end with the suffix Component (https://goo.gl/5X1TE7)

 @ ./src \.spec\.ts
 @ ./src/test.ts

WARNING in ./src/app/d3-test/d3-test.component.ts
[6, 15]: The selector of the component "D3TestComponent" should have prefix "app" (https://goo.gl/cix8BY)
[6, 15]: The selector of the component "D3TestComponent" should be named kebab-case (https://goo.gl/mBg67Z)
[6, 15]: The selector of the component "D3TestComponent" should be used as element (https://goo.gl/llsqKR)

 @ ./src/app/d3-test/d3-test.component.spec.ts 15:26-56
 @ ./src \.spec\.ts
 @ ./src/test.ts

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
45:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
57:15 Critical dependency: the request of a dependency is an expression
15 09 2016 21:19:14.570:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
15 09 2016 21:19:14.570:INFO [launcher]: Launching browser Chrome with unlimited concurrency
15 09 2016 21:19:14.570:INFO [launcher]: Starting browser Chrome
15 09 2016 21:19:16.474:INFO [Chrome 52.0.2743 (Windows 10 0.0.0)]: Connected on socket /#HT2YkcK1KC2VFFXaAAAA with id 93609475
LOG: 'Called ngOnDestroy with nativeElement tagName: ', 'g'
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.226 secs)
LOG: 'Called ngOnDestroy with d3 still defined: ', true
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.226 secs)
LOG: 'Called ngOnDestroy with d3HostElement: ', undefined
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.226 secs)
LOG: 'Called ngOnDestroy with d3InnerGroup: ', undefined
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.226 secs)
LOG: 'Called ngOnInit with nativeElement tagName: ', 'g'
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.226 secs)
LOG: 'Called ngOnInit with d3HostElement: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.226 secs)
LOG: 'Called ngOnInit with d3InnerGroup: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.226 secs)
Chrome 52.0.2743 (Windows 10 0.0.0) Component: D3Test should contain an "svg" element with dimensions 300x200 FAILED
        Error: Error in ./MockParent class MockParent - inline template:0:30 caused by: Cannot read property 'empty' of undefined
        TypeError: Cannot read property 'empty' of undefined
            at D3TestComponent.ngOnDestroy (webpack:///c:/Users/TSR/vscode/testng2/src/app/d3-test/d3-test.component.ts:9:3595 <- src/test.ts:43575:3723)
            at DebugAppView._View_MockParent0.destroyInternal (MockParent.ngfactory.js:49:29)
            at DebugAppView.AppView.destroyLocal (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:204:0 <- src/test.ts:25191:14)
            at DebugAppView.destroyLocal (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:367:0 <- src/test.ts:25354:43)
            at DebugAppView.AppView._destroyRecurse (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:192:0 <- src/test.ts:25179:14)
            at DebugAppView.AppView._destroyRecurse (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:190:0 <- src/test.ts:25177:25)
            at DebugAppView.AppView.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:178:0 <- src/test.ts:25165:14)
            at ComponentRef_.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/component_factory.js:119:51 <- src/test.ts:14631:82)
            at ComponentFixture.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/bundles/core-testing.umd.js:344:0 <- src/test.ts:4159:35)
            at webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/bundles/core-testing.umd.js:1018:61 <- src/test.ts:4833:78
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 (1 FAILED) (0 secs / 0.27 secs)
Chrome 52.0.2743 (Windows 10 0.0.0) Component: D3Test should contain an "svg" element with dimensions 300x200 FAILED
        Error: Error in ./MockParent class MockParent - inline template:0:30 caused by: Cannot read property 'empty' of undefined
        TypeError: Cannot read property 'empty' of undefined
            at D3TestComponent.ngOnDestroy (webpack:///c:/Users/TSR/vscode/testng2/src/app/d3-test/d3-test.component.ts:9:3595 <- src/test.ts:43575:3723)
            at DebugAppView._View_MockParent0.destroyInternal (MockParent.ngfactory.js:49:29)
            at DebugAppView.AppView.destroyLocal (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:204:0 <- src/test.ts:25191:14)
            at DebugAppView.destroyLocal (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:367:0 <- src/test.ts:25354:43)
            at DebugAppView.AppView._destroyRecurse (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:192:0 <- src/test.ts:25179:14)
            at DebugAppView.AppView._destroyRecurse (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:190:0 <- src/test.ts:25177:25)
            at DebugAppView.AppView.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:178:0 <- src/test.ts:25165:14)
            at ComponentRef_.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/component_factory.js:119:51 <- src/test.ts:14631:82)
            at ComponentFixture.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/bundles/core-testing.umd.js:344:0 <- src/test.ts:4159:35)
            at webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/bundles/core-testing.umd.js:1018:61 <- src/test.tsLOG: 'Called ngOnDestroy with nativeElement tagName: ', 'g'
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 (1 FAILED) (0 secs / 0.27 secs)
LOG: 'Called ngOnDestroy with d3 still defined: ', true
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 (1 FAILED) (0 secs / 0.27 secs)
LOG: 'Called ngOnDestroy with d3HostElement: ', undefined
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 (1 FAILED) (0 secs / 0.27 secs)
LOG: 'Called ngOnDestroy with d3InnerGroup: ', undefined
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 (1 FAILED) (0 secs / 0.27 secs)
LOG: 'Called ngOnInit with nativeElement tagName: ', 'g'
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 (1 FAILED) (0 secs / 0.27 secs)
LOG: 'Called ngOnInit with d3HostElement: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 (1 FAILED) (0 secs / 0.27 secs)
LOG: 'Called ngOnInit with d3InnerGroup: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 (1 FAILED) (0 secs / 0.27 secs)
Chrome 52.0.2743 (Windows 10 0.0.0) Component: D3Test should contain a "rect" element with dimensions 200x150 FAILED
        Error: Error in ./MockParent class MockParent - inline template:0:30 caused by: Cannot read property 'empty' of undefined
        TypeError: Cannot read property 'empty' of undefined
            at D3TestComponent.ngOnDestroy (webpack:///c:/Users/TSR/vscode/testng2/src/app/d3-test/d3-test.component.ts:9:3595 <- src/test.ts:43575:3723)
            at DebugAppView._View_MockParent0.destroyInternal (MockParent.ngfactory.js:49:29)
            at DebugAppView.AppView.destroyLocal (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:204:0 <- src/test.ts:25191:14)
            at DebugAppView.destroyLocal (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:367:0 <- src/test.ts:25354:43)
            at DebugAppView.AppView._destroyRecurse (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:192:0 <- src/test.ts:25179:14)
            at DebugAppView.AppView._destroyRecurse (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:190:0 <- src/test.ts:25177:25)
            at DebugAppView.AppView.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:178:0 <- src/test.ts:25165:14)
            at ComponentRef_.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/component_factory.js:119:51 <- src/test.ts:14631:82)
            at ComponentFixture.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/bundles/core-testing.umd.js:344:0 <- src/test.ts:4159:35)
            at webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/bundles/core-testing.umd.js:1018:61 <- src/test.ts:4833:78
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 6 of 6 (2 FAILED) (0 secs / 0.301 secs)
Chrome 52.0.2743 (Windows 10 0.0.0) Component: D3Test should contain a "rect" element with dimensions 200x150 FAILED
        Error: Error in ./MockParent class MockParent - inline template:0:30 caused by: Cannot read property 'empty' of undefined
        TypeError: Cannot read property 'empty' of undefined
            at D3TestComponent.ngOnDestroy (webpack:///c:/Users/TSR/vscode/testng2/src/app/d3-test/d3-test.component.ts:9:3595 <- src/test.ts:43575:3723)
            at DebugAppView._View_MockParent0.destroyInternal (MockParent.ngfactory.js:49:29)
            at DebugAppView.AppView.destroyLocal (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:204:0 <- src/test.ts:25191:14)
            at DebugAppView.destroyLocal (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:367:0 <- src/test.ts:25354:43)
            at DebugAppView.AppView._destroyRecurse (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:192:0 <- src/test.ts:25179:14)
            at DebugAppView.AppView._destroyRecurse (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:190:0 <- src/test.ts:25177:25)
            at DebugAppView.AppView.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/view.js:178:0 <- src/test.ts:25165:14)
            at ComponentRef_.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/src/linker/component_factory.js:119:51 <- src/test.ts:14631:82)
            at ComponentFixture.destroy (webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/bundles/core-testing.umd.js:344:0 <- src/test.ts:4159:35)
            at webpack:///c:/Users/TSR/vscode/testng2/~/@angular/core/bundles/core-testing.umd.js:1018:61 <- src/test.tsChrome 52.0.2743 (Windows 10 0.0.0): Executed 6 of 6 (2 FAILED) (0.389 secs / 0.301 secs)
```

**(5.) Mention any other details that might be useful.**

Importantly, comparable code ran without issue under angular-cli webpack.8/RC.5. Comparable code still runs fine using `ng serve` under beta.14/Angular 2 v2.0.0. Scenarios where the test all of a sudden fails in `ngOnDestroy` include also a component where an interval timer created with D3 is stopped. And the private member timer is suddenly undefined.

Also, and this is where it gets very Schroedinger's cat-ish, if one changes **d3-test.component.ts** and comments out the _if_-statement in `ngOnDestroy() {...}`, leaving the `console,logs(...)` in place, i.e.:
```ts
...
    ngOnDestroy() {
        console.log('Called ngOnDestroy with nativeElement tagName: ', this.nativeElement.tagName);
        console.log('Called ngOnDestroy with d3 still defined: ', (this.d3) ? true : false);
        console.log('Called ngOnDestroy with d3HostElement: ', this.d3HostElement);
        console.log('Called ngOnDestroy with d3InnerGroup: ', this.d3InnerGroup);

        // if (this.nativeElement && !this.d3HostElement.empty()) {
        //     this.d3HostElement.remove();
        // }

    }
...
```
The test behavior changes to passing with the `undefined` issue disappearing as per the console.log output:
```
WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
45:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
57:15 Critical dependency: the request of a dependency is an expression
LOG: 'Called ngOnDestroy with nativeElement tagName: ', 'g'
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.197 secs)
LOG: 'Called ngOnDestroy with d3 still defined: ', true
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.197 secs)
LOG: 'Called ngOnDestroy with d3HostElement: ', undefined
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.197 secs)
LOG: 'Called ngOnDestroy with d3InnerGroup: ', undefined
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.197 secs)
LOG: 'Called ngOnInit with nativeElement tagName: ', 'g'
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.197 secs)
LOG: 'Called ngOnInit with d3HostElement: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.197 secs)
LOG: 'Called ngOnInit with d3InnerGroup: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 4 of 6 SUCCESS (0 secs / 0.197 secs)
LOG: 'Called ngOnDestroy with nativeElement tagName: ', 'g'
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 SUCCESS (0 secs / 0.235 secs)
LOG: 'Called ngOnDestroy with d3 still defined: ', true
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 SUCCESS (0 secs / 0.235 secs)
LOG: 'Called ngOnDestroy with d3HostElement: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 SUCCESS (0 secs / 0.235 secs)
LOG: 'Called ngOnDestroy with d3InnerGroup: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 SUCCESS (0 secs / 0.235 secs)
LOG: 'Called ngOnInit with nativeElement tagName: ', 'g'
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 SUCCESS (0 secs / 0.235 secs)
LOG: 'Called ngOnInit with d3HostElement: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 SUCCESS (0 secs / 0.235 secs)
LOG: 'Called ngOnInit with d3InnerGroup: ', Selection{_groups: [[...]], _parents: [null]}
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 5 of 6 SUCCESS (0 secs / 0.235 secs)
Chrome 52.0.2743 (Windows 10 0.0.0): Executed 6 of 6 SUCCESS (0.334 secs / 0.276 secs)
```
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tomwanzek** [comment]
As another reference, I have updated a more complete Angular 2/D3 Demo project to beta.14/Anuglar 2 v2.0.0. See here [d3-ng3-demo](https://github.com/tomwanzek/d3-ng2-demo).

The only way I get the unit tests to pass, is if I comment out the the code in `ngOnDestroy(){...}` of the respective D3-based components:
* [brush-zoom-2.component.ts](https://github.com/tomwanzek/d3-ng2-demo/blob/master/src/app/d3-demos/brush-zoom-2/brush-zoom-2.component.ts#L37)
* [drag-zoom-2.component.ts](https://github.com/tomwanzek/d3-ng2-demo/blob/master/src/app/d3-demos/drag-zoom-2/drag-zoom-2.component.ts#L51)
* [voronoi-spirals-3.component.ts](https://github.com/tomwanzek/d3-ng2-demo/blob/master/src/app/d3-demos/voronoi-spirals-3/voronoi-spirals-3.component.ts#L25)

**Comment by tomwanzek** [comment]
Identified code refactoring that removes the erratic behavior.
