### ISSUE TITLE
astUtils.addComponentToModule is not a function

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#2165]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.11-webpack.8
node: 5.11.0
os: darwin x64
```
Angular Version 2.0.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
`ng g component my-component`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
astUtils.addComponentToModule is not a function
TypeError: astUtils.addComponentToModule is not a function
    at Class.module.exports.files.fileList.afterInstall.options [as afterInstall] (/Projects/WebApp/node_modules/angular-cli/addon/ng2/blueprints/component/index.js:125:18)
    at tryCatch (/Projects/WebApp/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Projects/WebApp/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Projects/WebApp/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Projects/WebApp/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

5. Mention any other details that might be useful.<br>
Component is created but it is not added in `app.module.s` file.

**Comment by filipesilva** [comment]
Fixed in beta.14+.

**Comment by dcorns** [comment]
This also fixed the same error that was occurring in Fedora 24
