### ISSUE TITLE
Error when generating new route (Windows)

### ISSUE THREAD

**Issue by fursad** [angular/angular-cli#219]
I'm getting this error when trying to generate a new route. Am I missing something or is it a bug?

$ ng generate route hero
version: 1.13.13
installing route
  create app\routes\hero.js
  create app\templates\hero.hbs
ENOENT: no such file or directory, open 'C:\angular\test01\app\router.js'
Error: ENOENT: no such file or directory, open 'C:\angular\test01\app\router.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at writeRoute (C:\angulkar\test01\node_modules\angular-cli\node_modules\ember-cli\blueprints\route\index.js:116:19)
    at Class.updateRouter (C:\angulkar\test01\node_modules\angular-cli\node_modules\ember-cli\blueprints\route\index.js:95:5)
    at Class.module.exports.afterInstall (C:\angulkar\test01\node_modules\angular-cli\node_modules\ember-cli\blueprints\route\index.js:78:18)
    at lib$rsvp$$internal$$tryCatch (C:\angulkar\test01\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\angulkar\test01\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\angulkar\test01\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\angulkar\test01\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

**Comment by filipesilva** [comment]
Unfortunately we are late in cutting a new build. For this functionality to work, you need to be using the latest master.

See here for instructions: https://github.com/angular/angular-cli#working-with-master
