### ISSUE TITLE
:bugs: Angular CLI 12.2.7 wasm esbuild ng-packagr - The service is no longer running in stylesheet file

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular-cli#21903]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, this issue was not present in Angular CLI 12.2.6. This has something to do with that 1 ticket that was resolved for 12.2.7 about WASM.

### Description

All the information is here: https://github.com/nrwl/nx/issues/7128

## 🔬 Minimal Reproduction

I cannot reproduce this with just Angular CLI as every library and app build fine individually. It's when I build a project with Nx that this occurs, although it breaks in ng-packagr.

## 🔥 Exception or Error

2 different exceptions

<pre><code>
error	24-Sep-2021 16:25:02	runtime: nameOff 0x616b6361 out of range 0xd840 - 0x201ac5
error	24-Sep-2021 16:25:02	fatal error: runtime: name offset out of range
error	24-Sep-2021 16:25:02	
error	24-Sep-2021 16:25:02	goroutine 1 [running]:
error	24-Sep-2021 16:25:02	runtime.throw({0x83a95, 0x21})
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/panic.go:1198 +0x7 fp=0x46e858 sp=0x46e830 pc=0x12000007
error	24-Sep-2021 16:25:02	runtime.resolveNameOff(0xf228, 0x616b6361)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/type.go:195 +0x37 fp=0x46e8c0 sp=0x46e858 pc=0x134e0037
error	24-Sep-2021 16:25:02	runtime.name.pkgPath({0xf228})
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/type.go:511 +0x21 fp=0x46e8e8 sp=0x46e8c0 pc=0x13530021
error	24-Sep-2021 16:25:02	runtime.(*itab).init(0xc35858)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/iface.go:212 +0x1d fp=0x46e9a8 sp=0x46e8e8 pc=0x107a001d
error	24-Sep-2021 16:25:02	runtime.getitab(0x42b40, 0x4c9c0, 0x1)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/iface.go:75 +0x22 fp=0x46e9f0 sp=0x46e9a8 pc=0x10760022
error	24-Sep-2021 16:25:02	runtime.assertI2I2(0x42b40, {0xe74b8, 0x462210})
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/iface.go:467 +0x5 fp=0x46ea18 sp=0x46e9f0 pc=0x10870005
error	24-Sep-2021 16:25:02	math/rand.New(...)
error	24-Sep-2021 16:25:02		/usr/local/go/src/math/rand/rand.go:67
error	24-Sep-2021 16:25:02	math/rand.init()
error	24-Sep-2021 16:25:02		/usr/local/go/src/math/rand/rand.go:293 +0xe fp=0x46ea68 sp=0x46ea18 pc=0x1682000e
error	24-Sep-2021 16:25:02	runtime.doInit(0x2edca0)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:6498 +0x1e fp=0x46ebb0 sp=0x46ea68 pc=0x12a9001e
error	24-Sep-2021 16:25:02	runtime.doInit(0x2f20a0)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:6475 +0x9 fp=0x46ecf8 sp=0x46ebb0 pc=0x12a90009
error	24-Sep-2021 16:25:02	runtime.doInit(0x2f0d20)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:6475 +0x9 fp=0x46ee40 sp=0x46ecf8 pc=0x12a90009
error	24-Sep-2021 16:25:02	runtime.doInit(0x2f1900)
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:6475 +0x9 fp=0x46ef88 sp=0x46ee40 pc=0x12a90009
error	24-Sep-2021 16:25:02	runtime.main()
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/proc.go:238 +0x24 fp=0x46efe0 sp=0x46ef88 pc=0x121f0024
error	24-Sep-2021 16:25:02	runtime.goexit()
error	24-Sep-2021 16:25:02		/usr/local/go/src/runtime/asm_wasm.s:431 +0x1 fp=0x46efe8 sp=0x46efe0 pc=0x13d10001
</code></pre>

and

<pre><code>
> nx run booking-engine-ui-hotel-social-network-share:build:production 
Building Angular Package

------------------------------------------------------------------------------
Building entry point '@iko/booking-engine/ui-hotel-social-network-share'
------------------------------------------------------------------------------
RuntimeError: function signature mismatch
    at wasm-function[204]:0x2245a
    at wasm-function[2299]:0x265f31
    at wasm-function[2300]:0x26649d
    at wasm-function[703]:0xa0e31
    at wasm-function[703]:0xa0cae
    at wasm-function[1007]:0xdfc31
    at wasm-function[1005]:0xdfc04
    at global.Go.run (eval at <anonymous> (/Users/crash/git/iko-travel-spa/node_modules/ng-packagr/node_modules/esbuild-wasm/bin/esbuild:15:17), <anonymous>:595:23)
    at eval (eval at <anonymous> (/Users/crash/git/iko-travel-spa/node_modules/ng-packagr/node_modules/esbuild-wasm/bin/esbuild:15:17), <anonymous>:648:14)

The service was stopped in stylesheet file /Users/crash/git/iko-travel-spa/libs/booking-engine/ui-hotel-social-network-share/src/lib/components/share/social-network-share.component.scss.

The service is no longer running in stylesheet file /Users/crash/git/iko-travel-spa/libs/booking-engine/ui-hotel-social-network-share/src/lib/components/share/social-network-share.component.scss.
libs/booking-engine/ui-hotel-social-network-share/src/lib/components/share/social-network-share.component.ts:10:15 - error NG2008: Could not find stylesheet file './social-network-share.component.scss'.

10   styleUrls: ['./social-network-share.component.scss'],
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.9
Node: 12.22.6
Package Manager: yarn 1.22.11
OS: darwin x64

Angular: 12.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router
... service-worker, youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.9
@angular-devkit/build-angular   12.2.9
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.4
@angular/flex-layout            12.0.0-beta.35
@schematics/angular             12.2.9
ng-packagr                      12.2.2
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**
This error occurs both on my Mac and on our CI server (Ubuntu).

**Comment by alan-agius4** [comment]
Does this happen with ng-packagr version 12.2.1?

**Comment by alan-agius4** [comment]
@bjornharvold, do you have any feedback please?
