### ISSUE TITLE
Code Coverage with ng test results in compiler errors: Module build failed 

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#21988]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes

### Description

Enabling code coverage in a new angular 12 application results in compiler errors.

## 🔬 Minimal Reproduction

- `npx @angular/cli@12 new admin-console --routing --style css`
- `cd admin-console`
- Update `karma.conf.js`
	```js
	  module.exports = function (config) {
	    config.set({
	      //   ...
	      coverageReporter: {
	        // ...
	        reporters: [
	          { type: "html" },
	          { type: "text-summary" },
	          { type: "cobertura" }, // add cobertura
	        ],
	      },
	    });
	  };
	```
- Edit and overwrite `src/app/app.component.ts`
	```ts
	  @Component({
	    selector: 'app-root',
	    templateUrl: './app.component.html',
	    styleUrls: ['./app.component.css'],
	  })
	  export class AppComponent implements OnInit {
	    title = 'admin-console';
	  
	    ngOnInit() {
	      // this.customerForm = new FormGroup({
	      //   abbreviation: new FormControl('', {
	      //     asyncValidators: [
	      //       this.abbreviationValidator.validate.bind(this.abbreviationValidator),
	      //     ],
	      //   }),
	      // });
	    }
	  }
	```
- `yarn ng test --project admin-console --no-watch --code-coverage`

## 🔥 Exception or Error

<pre><code>
⠙ Generating browser application bundles (phase: building)...20 10 2021 18:43:21.570:INFO [karma-server]: Karma v6.3.5 server started at http://localhost:9876/
20 10 2021 18:43:21.573:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
20 10 2021 18:43:21.576:INFO [launcher]: Starting browser Chrome
✔ Browser application bundle generation complete.

./src/app/app.component.ts - Error: Module build failed (from ./node_modules/@jsdevtools/coverage-istanbul-loader/lib/index.js):
Error: /Users/prabh/dev/admin-console/src/app/app.component.ts: don't know how to turn this value into a node
    at valueToNode (/Users/prabh/dev/admin-console/node_modules/@babel/types/lib/converters/valueToNode.js:98:9)
    at Object.valueToNode (/Users/prabh/dev/admin-console/node_modules/@babel/types/lib/converters/valueToNode.js:92:58)
    at Object.exit (/Users/prabh/dev/admin-console/node_modules/istanbul-lib-instrument/dist/visitor.js:641:30)
    at PluginPass.exit (/Users/prabh/dev/admin-console/node_modules/istanbul-lib-instrument/dist/instrumenter.js:104:29)
    at newFn (/Users/prabh/dev/admin-console/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/prabh/dev/admin-console/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/prabh/dev/admin-console/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/prabh/dev/admin-console/node_modules/@babel/traverse/lib/path/context.js:99:8)
    at TraversalContext.visitQueue (/Users/prabh/dev/admin-console/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/Users/prabh/dev/admin-console/node_modules/@babel/traverse/lib/context.js:77:19)

error Command failed with exit code 1.
</code></pre>

<img width="1438" alt="angular_test_coverage_module_build_error_babel_types" src="https://user-images.githubusercontent.com/13006107/138182751-df4e17ca-e383-4c1c-974a-6dc922b46850.png">

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.10
Node: 16.11.1
Package Manager: yarn 1.22.17
OS: darwin x64

Angular: 12.2.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.10
@angular-devkit/build-angular   12.2.10
@angular-devkit/core            12.2.10
@angular-devkit/schematics      12.2.10
@angular/cli                    12.2.10
@schematics/angular             12.2.10
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by prabh-62** [comment]
Sorry, closing as duplicate of #21967
