### ISSUE TITLE
ng is failing on the help command

### ISSUE THREAD

**Issue by Heerschop** [angular/angular-cli#2199]
**My OS version is:**
Microsoft Windows 8.1 Enterprise
6.3.9600 N/A Build 9600

**The ng version is:**
angular-cli: 1.0.0-beta.14
node: 6.6.0
os: win32 x64

**My global module installes are (npm list -g --depth=0)**
C:\Program Files\nodejs
+-- angular-cli@1.0.0-beta.14
`-- npm@3.10.3

npm ERR! peer dep missing: webpack@1.x.x || 2.x.x || 2.x.x-beta, required by string-replace-loader@1.0.4

**When typing ng help this error is generated:**
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at C:\Users\Bas\AppData\Roaming\nvm\v6.6.0\node_modules\angular-cli\commands\help.js:28:33
    at Array.reduce (native)
    at Class.run (C:\Users\Bas\AppData\Roaming\nvm\v6.6.0\node_modules\angular-cli\commands\help.js:26:39)
    at Class.<anonymous> (C:\Users\Bas\AppData\Roaming\nvm\v6.6.0\node_modules\angular-cli\node_modules\angular-cli\lib\models\command.js:152:17)
    at tryCatch (C:\Users\Bas\AppData\Roaming\nvm\v6.6.0\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\-internal.js:215:12)
    at invokeCallback (C:\Users\Bas\AppData\Roaming\nvm\v6.6.0\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\-internal.js:230:13)
    at C:\Users\Bas\AppData\Roaming\nvm\v6.6.0\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\then.js:29:16
    at flush (C:\Users\Bas\AppData\Roaming\nvm\v6.6.0\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

When starting ng without any argument the help is showing, Other argument seem to be working.
I'm doing this from an empty directory and have tried re installing the cli and cleaning the npm cache

npm uninstall -g angular-cli
npm cache clean 
npm install -g angular-cli@1.0.0-beta.14

did not help.

**Comment by EvAlex** [comment]
Same for me. But `ng --help` works as expected

**Comment by Heerschop** [comment]
Wow great I was not expecting a workaround that quickly, thank you very much.
