### ISSUE TITLE
None of the commands are working inside an angular-cli project

### ISSUE THREAD

**Issue by cironunes** [angular/angular-cli#22]
Version tested: 832b83b6c8e81a3af40a5b35df4340bec5fcd081

# Steps to reproduce

1- Create an angular-cli project:
`
$ ng new test339
`

2- Step into it and try to run any of the commands:
`
$ cd test339
`
`
$ ng
`
# Result

```
/Users/cironunes/work/angular-cli/bin/ng:27
  cli({
  ^
TypeError: object is not a function
    at /Users/cironunes/work/angular-cli/bin/ng:27:3
    at /Users/cironunes/work/angular-cli/node_modules/resolve/lib/async.js:44:21
    at ondir (/Users/cironunes/work/angular-cli/node_modules/resolve/lib/async.js:187:31)
    at /Users/cironunes/work/angular-cli/node_modules/resolve/lib/async.js:153:39
    at onex (/Users/cironunes/work/angular-cli/node_modules/resolve/lib/async.js:93:22)
    at /Users/cironunes/work/angular-cli/node_modules/resolve/lib/async.js:24:18
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by rodyhaddad** [comment]
This is because the `angular-cli` npm package is not currently pointing to this repo.
I'll have to publish a new version of the package to overwrite it.

**Comment by rodyhaddad** [comment]
This is fixed now as I published the new version of `angular-cli` to npm.
