### ISSUE TITLE
gating Error: Cannot negate a statement, How to solve this

### ISSUE THREAD

**Issue by Nikhil12894** [angular/angular-cli#22066]
Error: Optimization error [main.59b656942b7d23accece.js]: Error: Cannot negate a statement
    at AST_ClassExpression.<anonymous> (/media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:13712:15)
    at AST_ClassExpression.negate (/media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:13769:21)
    at AST_Sequence.<anonymous> (/media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:13727:44)
    at AST_Sequence.negate (/media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:13769:21)
    at /media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:15272:34
    at AST_If.optimize (/media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:10899:19)
    at Compressor.before (/media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:10884:24)
    at AST_If.transform (/media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:5389:41)
    at /media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:5405:21
    at doit (/media/nalin/Work/WOrk/ANGULAR_ANR_PROJECT/hwChecklist/node_modules/terser/dist/bundle.min.js:110:23)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
