### ISSUE TITLE
12.2.9 -> 13.0.0: [error] Error: Cannot find module webpack-sources

### ISSUE THREAD

**Issue by spock123** [angular/angular-cli#22076]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Upgrading my project gives this error when trying to run:

`NODE_ENV=production ng build --configuration=test`

### Please provide the exception or error you saw

```true
[error] Error: Cannot find module 'webpack-sources'
Require stack:
- /Users/lrj/project/osb-sso/node_modules/license-webpack-plugin/dist/WebpackAssetManager.js
- /Users/lrj/project/osb-sso/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js
- /Users/lrj/project/osb-sso/node_modules/license-webpack-plugin/dist/index.js
- /Users/lrj/project/osb-sso/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js
- /Users/lrj/project/osb-sso/node_modules/@angular-devkit/build-angular/src/webpack/configs/index.js
- /Users/lrj/project/osb-sso/node_modules/@angular-devkit/build-angular/src/builders/browser/index.js
- /Users/lrj/project/osb-sso/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/lrj/project/osb-sso/node_modules/@angular-devkit/architect/node/index.js
- /Users/lrj/project/osb-sso/node_modules/@angular/cli/models/architect-command.js
- /Users/lrj/project/osb-sso/node_modules/@angular/cli/commands/build-impl.js
- /Users/lrj/project/osb-sso/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/lrj/project/osb-sso/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/lrj/project/osb-sso/node_modules/@angular/cli/utilities/json-schema.js
- /Users/lrj/project/osb-sso/node_modules/@angular/cli/models/command-runner.js
- /Users/lrj/project/osb-sso/node_modules/@angular/cli/lib/cli/index.js
- /Users/lrj/project/osb-sso/node_modules/@angular/cli/lib/init.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/lrj/project/osb-sso/node_modules/license-webpack-plugin/dist/WebpackAssetManager.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.0
Node: 14.17.0
Package Manager: npm 7.22.0
OS: darwin x64

Angular: 13.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.0
@angular-devkit/build-angular   13.0.0
@angular-devkit/core            13.0.0
@angular-devkit/schematics      13.0.0
@schematics/angular             13.0.0
rxjs                            6.6.7
typescript                      4.4.4
```

### Anything else?

Mac OS

Upgrade went well, errors occured during project start after upgrade.

**Comment by JoostK** [comment]
Have you tried removing node_modules and lockfiles?

**Comment by spock123** [comment]
@JoostK I have not, sorry. Will try now.

**Comment by spock123** [comment]
@JoostK That did the trick - feeling pretty stupid now.

Thanks a bunch :)
