### ISSUE TITLE
You cannot use the help command inside an angular-cli project.

### ISSUE THREAD

**Issue by moloch--** [angular/angular-cli#2209]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

```
➜  client git:(angular2) ✗ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.14
node: 6.5.0
os: darwin x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Run `ng help` inside an angular-cli project directory

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
➜  client git:(angular2) ✗ ng help
You cannot use the help command inside an angular-cli project.
```

**Comment by moloch--** [comment]
It appears to be broken outside of the project as well:

```
➜  frontend git:(angular2) ✗ ng help
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/angular-cli/commands/help.js:28:33
    at Array.reduce (native)
    at Class.run (/usr/local/lib/node_modules/angular-cli/commands/help.js:26:39)
    at Class.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by 17twenty** [comment]
```
$ ng help
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/angular-cli/commands/help.js:28:33
    at Array.reduce (native)
    at Class.Command.extend.run (/usr/local/lib/node_modules/angular-cli/commands/help.js:26:39)
    at Class.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

Same on Ubuntu 14.04.5 LTS

**Comment by filipesilva** [comment]
This should be fixed on `beta.16`, just tried to repro and it was working.
