### ISSUE TITLE
ng add @angular-eslint/schematics

### ISSUE THREAD

**Issue by sysmat** [angular/angular-cli#22111]
# 🐞 Bug report
```
❯ ng add @angular-eslint/schematics
Skipping installation: Package already installed
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID    
See "C:\Users\tomaz\AppData\Local\Temp\ng-lzlwRv\angular-errors.log" for further details.
```

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
I don't know

### Description

An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID    

## 🔥 Exception or Error

<pre><code>
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\tomaz\Documents\NetBeansProjects\GitLab_Arnes\portal-hub\upravljanje-domen\domain-reg-wc\frontend\node_modules\ajv\dist\compile\codegen\index.js:568:18)

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.0.1
Node: 14.15.4
Package Manager: npm 6.14.10
OS: win32 x64

Angular: 13.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
rxjs                            7.4.0
typescript                      4.4.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but angular-eslint is not supported by the Angular team.

Please contact the author(s) of the [angular-eslint](https://github.com/angular-eslint/angular-eslint) project or file an issue on their issue tracker.

**Comment by nagkumar** [comment]
It worked for me this way... i.e. through the update route.

`ng update @angular-eslint/schematics --allow-dirty --force
`
and then optionally say  

`ng add @angular-eslint/schematics
`
