### ISSUE TITLE
bug: Digest method not supported

### ISSUE THREAD

**Issue by khaledosman** [angular/angular-cli#22119]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v12

### Description

 A clear and concise description of the problem...
Running `ng build` or `ng serve` after upgrading to Angular v13, fails with an error saying Digest method not supported

## 🔬 Minimal Reproduction
https://github.com/khaledosman/angular-realworld-example-app

1. clone the sample repo
2. upgrade to angular v13: `npx @angular/cli@13 update @angular/core@13 @angular/cli@13`
3. try to start the app via `npm start` or `npm build`

## 🔥 Exception or Error
<pre><code>

(node:12345) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12345) UnhandledPromiseRejectionWarning: Error: Digest method not supported
    at new Hash (internal/crypto/hash.js:46:19)
    at Object.createHash (crypto.js:116:10)
    at BulkUpdateDecorator.hashFactory (/Users/khaledosman/Documents/github/angular-realworld-example-app/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/Users/khaledosman/Documents/github/angular-realworld-example-app/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/Users/khaledosman/Documents/github/angular-realworld-example-app/node_modules/webpack-sources/lib/RawSource.js:64:8)
    at NormalModule._initBuildHash (/Users/khaledosman/Documents/github/angular-realworld-example-app/node_modules/webpack/lib/NormalModule.js:868:17)
    at handleParseResult (/Users/khaledosman/Documents/github/angular-realworld-example-app/node_modules/webpack/lib/NormalModule.js:934:10)
    at /Users/khaledosman/Documents/github/angular-realworld-example-app/node_modules/webpack/lib/NormalModule.js:1026:4
    at processResult (/Users/khaledosman/Documents/github/angular-realworld-example-app/node_modules/webpack/lib/NormalModule.js:743:11)
    at /Users/khaledosman/Documents/github/angular-realworld-example-app/node_modules/webpack/lib/NormalModule.js:807:5

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 13.0.1
Node: 14.17.5
Package Manager: yarn 1.22.17
OS: darwin x64

Angular: 13.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            13.0.1
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Comment by clydin** [comment]
It appears that the following `resolutions` configuration in the projects `package.json` combined with the preexisting package lock file is causing an unsupported version of Webpack to be used.
```
  "resolutions": {
    "webpack": "^5.0.0"
  },
```
Removing the `resolutions` configuration should resolve the problem.  If this does not then also removing the package lock file (`yarn.lock`) may be necessary.
