### ISSUE TITLE
angular_devkit schematics must be boolean input validation error

### ISSUE THREAD

**Issue by jaredtfornida** [angular/angular-cli#22205]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
i dont know

### Description

I am trying to use the schematics cli to generate templates, since the templates are not for angular projects they are for broader use cases.

I am running into an issue when trying to use boolean values in the schematics cli. Whenever I try to pass a value for a boolean property it seems to interpret it as a string instead. "x-prompt" seems to handle it however I was wondering if there is a solution or work around that does not involve using any prompts.

 A clear and concise description of the problem...

Here is an example cli command that is failing for me.
schematics .:test-generate-file --name foo --transform=true

Error:
Error: Schematic input does not validate against the Schema: {"transform":"true","name":"foo"}
Errors:

  Data path "/transform" must be boolean.
    at MapSubscriber.project (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:30:27)
    at MapSubscriber._next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)

## 🔬 Minimal Reproduction

1. Create a schematic
schematics blank --name foo

2. Inside src/foo create a schema.json something like this:
{
  "$schema": "http://json-schema.org/schema",
  "$id": "foo",
  "title": "schema",
  "type": "object",
  "properties": {
    "name": {
      "description": "universal name",
      "type": "string",
      "$default": {
        "$source": "argv",
        "index": 0
      },
    },
    "transform": {
      "type": "boolean",
      "default": false
    }
  },
  "required": [
    "name"
  ],
  "additionalProperties": false
}

3. Then in the collection.json set a schema property inside foo
{
  "$schema": "../node_modules/@angular-devkit/schematics/collection-schema.json",
  "schematics": {
    "foo": {
      "description": "A blank schematic.",
      "factory": "./foo/index#foo",
      "schema": "foo/schema.json"
    }
  }
}

4. After that npm run build
5. Then finally run the schematic command to try to run it
schematics .:foo --name foo --transform=true

## 🔥 Exception or Error

<pre><code>
Error: Schematic input does not validate against the Schema: {"transform":"true","name":"foo"}
Errors:

  Data path "/transform" must be boolean.
    at MapSubscriber.project (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:30:27)
    at MapSubscriber._next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/home/tokuj/.nvm/versions/node/v14.15.5/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you try 

```
schematics .:foo --name foo --transform
```

**Comment by jaredtfornida** [comment]
oh wow that worked thank you for the fast response

**Comment by ducthang-vu** [comment]
> Can you try
> 
> ```
> schematics .:foo --name foo --transform
> ```

Hi, your solution seems to work only when the default value is false. If instead, the default value was true, that would not work. Am I wrong?

**Comment by jaredtfornida** [comment]
> > Can you try
> > ```
> > schematics .:foo --name foo --transform
> > ```
> 
> Hi, your solution seems to work only when the default value is false. If instead, the default value was true, that would not work. Am I wrong?

You are correct. Yesterday I found that if you want to set false flag you can do this:
`--no-transform`

**Comment by ducthang-vu** [comment]
> > > Can you try
> > > ```
> > > schematics .:foo --name foo --transform
> > > ```
> > 
> > 
> > Hi, your solution seems to work only when the default value is false. If instead, the default value was true, that would not work. Am I wrong?
> 
> You are correct. Yesterday I found that if you want to set false flag you can do this: `--no-transform`

Thank you!
