### ISSUE TITLE
Optimization error occurred to use angular.json that aot and optimization is true

### ISSUE THREAD

**Issue by s-kim-biz** [angular/angular-cli#22244]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

Thank you for angular development.
I want to report the bug when i update angular V10.2.5 to angular V12.2.11.
The log message below has been printed.

```
Error: Optimization error [main.f64dee5357f258a71c5a.js]: Error: Transform failed with 1 error:
main.f64dee5357f258a71c5a.js:124716:5: error: Expected identifier but found "="
    at failureErrorWithLog (/Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:1493:15)
    at /Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:1282:29
    at /Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

I try to solve this problem by updating the esbuild to the latest version (V0.14.0) but it does not work.
so, please let me know the solution of this problem.

### Please provide the exception or error you saw

```true
Error: Optimization error [main.f64dee5357f258a71c5a.js]: Error: Transform failed with 1 error:
main.f64dee5357f258a71c5a.js:124716:5: error: Expected identifier but found "="
    at failureErrorWithLog (/Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:1493:15)
    at /Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:1282:29
    at /Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/anonymous/my-angular-project/web/node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.11
Node: 14.17.1
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.2.11
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.11
@angular-devkit/build-angular   12.2.11
@angular-devkit/core            12.2.11
@angular-devkit/schematics      12.2.11
@schematics/angular             12.2.11
rxjs                            6.6.3
typescript                      4.3.5
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
@s-kim-biz, no we haven't seen anything similar.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by n8cunanan** [comment]
ran into the same exact issue, found a possible solution by updating the angular devkit like so: npm install --save-dev @angular-devkit/build-angular
