### ISSUE TITLE
Running migrations with polyfills set as an array

### ISSUE THREAD

**Issue by electrofLy** [angular/angular-cli#22313]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 

No.

### Description

 If you have defined polyfills as an array in your angular.json, running ng update migrations fails.

## 🔬 Minimal Reproduction

1. In angular.json set:

```
{
...
"polyfills": ["src/polyfills.ts"],
...
}
```

2. Run `npx @angular/cli@13 update @angular/core@13 @angular/cli@13` if you are on v12 or ` ng update @angular/cli --from 12 --to 13 --migrate-only` if you are on v13.

## 🔥 Exception or Error

<pre><code>[error] TypeError: fileName.substr is not a function
    at getScriptKindFromFileName (X:\frontend\node_modules\@schematics\angular\third_party\github.com\Microsoft\TypeScript\lib\typescript.js:20206:28)
    at Object.ensureScriptKind (X:\frontend\node_modules\@schematics\angular\third_party\github.com\Microsoft\TypeScript\lib\typescript.js:20202:30)
    at Object.parseSourceFile (X:\frontend\node_modules\@schematics\angular\third_party\github.com\Microsoft\TypeScript\lib\typescript.js:30455:29)
    at Object.createSourceFile (X:\frontend\node_modules\@schematics\angular\third_party\github.com\Microsoft\TypeScript\lib\typescript.js:30266:29)
    at X:\frontend\node_modules\@schematics\angular\migrations\update-13\drop-ie-polyfills.js:125:31
    at MergeMapSubscriber.project (X:\frontend\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)
    at MergeMapSubscriber._tryNext (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:67:27)
    at MergeMapSubscriber._next (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:30:22)
    at MergeMapOperator.call (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:37:23)
    at Observable.subscribe (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:25:31)
    at MergeMapOperator.call (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:37:23)
    at Observable.subscribe (X:\frontend\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Observable.js:25:31)
</code></pre>

## 🌍 Your Environment

<pre><code>  _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.4
Node: 14.15.5
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.13
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cdk                    12.2.11
@angular/cli                    13.0.4
@angular/google-maps            12.2.11
@angular/material               12.2.11
@schematics/angular             13.0.4
ng-packagr                      13.0.8
rxjs                            7.4.0
typescript                      4.4.4
webpack                         5.60.0

</code></pre>

**Anything else relevant?**

No.

**Comment by alan-agius4** [comment]
Hi @electrofLy,

Polyfills cannot be array. See: https://angular.io/cli/build

Are you using a custom builder?
