### ISSUE TITLE
[error] HookWebpackError: The service is no longer running

### ISSUE THREAD

**Issue by TheLillyleaf** [angular/angular-cli#22338]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure, First time trying build. 

### Description

When I try to run ng build, I get:
 an An unhandled exception occurred: The service is no longer running
 
 

## 🔬 Minimal Reproduction

ng new my-courses-lab3-studentid --minimal=true --skip-tests=true --inline-style=false --inline-template=false --strict=true --style=css --routing=true 

ng build

## 🔥 Exception or Error

<pre><code>
[error] HookWebpackError: The service is no longer running
    at makeWebpackError (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/webpack/lib/Compilation.js:3055:12
    at eval (eval at create (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:98:1)
-- inner error --
Error: The service is no longer running
    at /home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/esbuild-wasm/lib/main.js:1276:29
    at sendRequest (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/esbuild-wasm/lib/main.js:625:14)
    at start (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/esbuild-wasm/lib/main.js:1274:9)
    at Object.transform2 [as transform] (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/esbuild-wasm/lib/main.js:1324:5)
    at /home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/esbuild-wasm/lib/main.js:1920:55
    at new Promise (<anonymous>)
    at Object.transform (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/esbuild-wasm/lib/main.js:1920:14)
    at EsbuildExecutor.transform [as esbuildTransform] (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/esbuild-wasm/lib/main.js:1751:62)
    at EsbuildExecutor.transform (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/@angular-devkit/build-angular/src/webpack/plugins/esbuild-executor.js:119:21)
    at async /home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/laboration_3/my-courses-lab3-toli2003/node_modules/@angular-devkit/build-angular/src/webpack/plugins/css-optimizer-plugin.js:63:53

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.0
Node: 16.13.1
Package Manager: npm 
OS: linux x64

Angular: 13.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.0
@angular-devkit/build-angular   13.1.0
@angular-devkit/core            13.1.0
@angular-devkit/schematics      13.1.0
@schematics/angular             13.1.0
rxjs                            7.4.0
typescript                      4.4.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @TheLillyleaf, 

I tried to replicate this locally and I wasn't able. I also tried to [follow the code](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/plugins/esbuild-executor.ts) but I cannot spot anything that could cause this problem. 

By any chance are you using docker?

**Comment by TheLillyleaf** [comment]
Thanks, 

Not sure what docker is, sorry. 

Still very new to angular. 

Basically I have just started a new project and tried to build it directly using the cli.

**Comment by TheLillyleaf** [comment]
What more info can I leave btw?

**Comment by alan-agius4** [comment]
The `The service is no longer running` error is thrown by esbuild. 

From the stacks I noticed that the WASM version is used. I don't expect this to be used on Linux. For some reason the native esbuild binary installation failed which causes the WASM version to be used.

`The service is no longer running` indicates that something fatal is also happening in ESbuild when using the WASM version which is caused the service to be abruptly shutdown, on Linux this can be caused by the OOM Killer which is process that the kernel triggers when the system is critically low on memory.

**Comment by TheLillyleaf** [comment]
I tried updating esbuild, but the error isn't fixed. 

I should also add that I am installing the node_modules after I create the app, as they are not created by ng new. 

I've tried creating completely new projects and building them directly, but nothing seems to work.

**Comment by alan-agius4** [comment]
@TheLillyleaf, do you have sufficient availability memory? 

Also, can you please provide the npm install logs,

**Comment by TheLillyleaf** [comment]
Yeah, memory is fine, never breaking 40% usage. 


[2021-12-10T20_58_50_350Z-debug-0.log](https://github.com/angular/angular-cli/files/7695458/2021-12-10T20_58_50_350Z-debug-0.log)

**Comment by TheLillyleaf** [comment]
Tried to replicate it on a project which has an older version of Angular/cli and got a different error; 

<pre><code> 
└─(22:25:47 on main)──> ng build                                                                                                                                                             ──(Fri,Dec10)─┘
Your global Angular CLI version (13.1.0) is greater than your local version (13.0.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
⠼ Generating browser application bundles (phase: building)...node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Object.writeToStdin (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/project/toli2003-project/node_modules/esbuild-wasm/lib/main.js:1864:19)
    at sendRequest (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/project/toli2003-project/node_modules/esbuild-wasm/lib/main.js:637:14)
    at start (/home/tobiasliljeblad/Documents/programvaruteknik/webb2/coding/DT190G/project/toli2003-project/node_modules/esbuild-wasm/lib/main.js:1274:9)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
<pre/><code/>

**Comment by alan-agius4** [comment]
Can you try to re-install Node.JS? Tip: you can use NVM to install and manage your Node.Js versions.

**Comment by TheLillyleaf** [comment]
@alan-agius4 It worked! Thanks a million!!
