### ISSUE TITLE
ng update - NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/angular-cli#22391]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] doc
- [ ] config
- [ ] help
- [ ] version

### Is this a regression?

Not sure. 

### Description

Using below code in custom update schematics using [schematics npm package](https://www.npmjs.com/package/@schematics/update) fails with `NOT SUPPORTED: keyword "id", use "$id" for schema ID`

```
    return chain([
      externalSchematic('@schematics/update', 'update', {
        packages: [`@angular/cli`, `@angular/core`],
        from, // 12.2.7
        to: ngCorePackageVersion.replace('^', '') // 13.0.0
      }),
      ... // Other rules to run
    ]);
```

## 🔬 Minimal Reproduction

Use code mentioned in the description

## 🔥 Exception or Error

<pre><code>
An error occured:
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\vocabularies\core\id.js:6:15)     
    at keywordCode (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\validate\index.js:454:13) 
    at C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\codegen\index.js:439:13) 
    at CodeGen.block (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)    at iterateKeywords (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\codegen\index.js:439:13) 
    at CodeGen.block (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)    at schemaKeywords (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\validate\index.js:190:9    at CodeGen.code (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\codegen\index.js:439:13)                                                                                                               e\validate\index.js:128:
    at C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\validate\index.js:37:166                                                                                                                             js:70:9
    at CodeGen.code (C:\Users\machine-603\AppData\Roaming\npm\node_modules\@angular-devkit\schematics-cli\node_modules\ajv\dist\compile\codegen\index.js:439:13) odegen\index.js:439:13)     
</code></pre>

## 🌍 Your Environment

<pre><code>
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 13.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@angular/cli                    12.0.0
@schematics/angular             12.0.5
rxjs                            7.4.0
typescript                      4.5.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @iKrishnaSahu,

The API of `@schematics/update` was considered as private and experimental as it never reached a major version greater than 0.

It is also worth mentioned that this package was deleted and is no longer released.

**Comment by iKrishnaSahu** [comment]
@alan-agius4 Is there any other package provided by Angular to trigger ng update via schematics?
