### ISSUE TITLE
ng g @nrwl/angular:application failing while running using externalSchematic

### ISSUE THREAD

**Issue by sandeeppatidar30** [angular/angular-cli#22415]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

 Yes, the previous version in which this bug was not present was: ....

### Description

 ng g `@nrwl/angular:application` if i run it using `externalSchematic`.

## 🔬 Minimal Reproduction

1. Create a custom generator
2. Run ng g @nrwl/angular:application using externalSchematics

```ts
import { chain, externalSchematic, mergeWith, Rule, SchematicContext, template, Tree,  url } from '@angular-devkit/schematics';
   export default function(schema: Schema): Rule {
     return (host: Tree, context: SchematicContext) => {
   
       return chain([
         externalSchematic('@nrwl/angular', 'application', {
           name: 'myapp'
         })
       ])(host, context);
     };
   }
```
3. After running above generator e.g. `ng g @org/mylib:my-custom-generator`

## 🔥 Exception or Error

```

[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
   at findModule (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:81:11)
   at findModuleFromOptions (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:26:38)
   at C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\component\index.js:105:66
   at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
   at findModule (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:81:11)
   at findModuleFromOptions (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:26:38)
odule.
   at findModule (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:81:11)
   at findModuleFromOptions (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:26:38)
   at C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\component\index.js:105:66
   at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
   at findModule (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:81:11)
   at findModuleFromOptions (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:26:38)
   at C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schem
```

## 🌍 Your Environment

@angular-devkit/architect v0.1301.2
@angular-devkit/build-angular v13.1.2
@angular-devkit/schematics v13.1.2
@nrwl/angular v13.3.11
<img width="605" alt="nrwl" src="https://user-images.githubusercontent.com/31273891/146940998-d5761d7c-a6b0-4913-968f-0ea52da63d09.png">

**Comment by ennovum** [comment]
Hi. Any news about this one?

The following issue contains a complete code package to reproduce this:
https://github.com/nrwl/nx/issues/8253

It's worth mentioning here that the problem seems to only affect Windows based dev envs.

**Comment by alan-agius4** [comment]
Closing as this was an NX bug.

Please see https://github.com/nrwl/nx/issues/8253#issuecomment-1122234008
