### ISSUE TITLE
ng new doesn't work...

### ISSUE THREAD

**Issue by JimLynchCodes** [angular/angular-cli#22556]
Hi, I am very disappointed. Angular cli seems super busted... 😢

I am using node v17.4.0

Literally can't even scaffold a new project.

`ng new my-first-project` creates files but then blows up on `npm install`.

after going into the project and running `npm i --legacy-peer-deps` things, seems to install ok, but when I try to run with `ng serve` I just get this error:

```

10% building 3/3 modules 0 active(node:17567) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html
10% building 3/4 modules 1 active ....0.0.0:0/sockjs-node&sockPath=/sockjs-nodenode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/webpack/lib/NormalModule.js:412:16)
    at /Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/webpack/lib/NormalModule.js:444:10
    at /Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/webpack/lib/NormalModule.js:320:13
    at /Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/loader-runner/lib/LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (/Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:46:13)
    at processResource (/Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at runLoaders (/Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/webpack/lib/NormalModule.js:292:3)
    at NormalModule.build (/Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/webpack/lib/NormalModule.js:438:15)
    at Compilation.buildModule (/Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/webpack/lib/Compilation.js:702:10)
    at /Users/jim/Git-Projects/CryptoHydrants-CryptoHydrants-Browser-Frontend-v2/my-first-project/node_modules/webpack/lib/Compilation.js:944:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```

**Comment by alan-agius4** [comment]
@JimLynchCodes, can you please provide the output of `ng version`?

**Comment by alan-agius4** [comment]
Closing due to the lack of a communication.
