### ISSUE TITLE
angularv13 breaks build after bundling dependency

### ISSUE THREAD

**Issue by nitoloz** [angular/angular-cli#22588]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Described functionality worked fine in angular v12

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
- Create angular application with `angular-cli`
- Add `cal-heatmap` package to it (install it with yarn or npm)
- Go to `app.component.ts` and add `import * as CalHeatMapImpl from "cal-heatmap";` to import `cal-heatmap` in application

## 🔥 Exception or Error

<pre><code>
Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'document')
TypeError: Cannot read properties of undefined (reading 'document')
    at d3.js:8:1
    at Object.97718 (d3.js:9554:2)
    at __webpack_require__ (bootstrap:19:1)
    at Object.72510 (cal-heatmap.min.js:8:429)
    at __webpack_require__ (bootstrap:19:1)
    at Module.82265 (analytics-toolbar.component.ts:9:39)
    at __webpack_require__ (bootstrap:19:1)
    at Module.36395 (base-calendar-heatmap.component.ts:30:42)
    at __webpack_require__ (bootstrap:19:1)
    at Module.19697 (analytics-filters-filter.pipe.ts:6:40)
    at resolvePromise (zone.js:1213:1)
    at resolvePromise (zone.js:1167:1)
    at zone.js:1279:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25444:33)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:582:1)
</code></pre>
![image](https://user-images.githubusercontent.com/7154361/151380148-8690c6fb-fc51-48ae-9a1b-b211d253ed74.png)

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.1.4
Node: 16.13.0
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 13.1.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.1.4
@angular/cli                    13.1.4
@schematics/angular             13.1.4
rxjs                            7.5.2
typescript                      4.5.5
</code></pre>

tsConfig
<pre><code>
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "target": "es2015",
    "module": "es2020",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom",
      "es2018.promise"
    ],
 }
</code></pre>

**Anything else relevant?**
Worth noting that `cal-heatmap` is using quite old version of `d3.js v3`, but I still hope there is a way to make it work with angular v13.

The same bundle works fine with angular v12 or with v13 if I import `cal-heatmap` via CDN in `index.html`, so that it doesn't get bundled, so I suspect it's because of the bundling process.
This issue is also reported in [cal-heatmap github](https://github.com/wa0x6e/cal-heatmap/issues/274) with links to similar issues ([plotly1](https://github.com/plotly/angular-plotly.js/issues/75), [plotly2](https://github.com/plotly/angular-plotly.js/issues/89), and [SO](https://stackoverflow.com/questions/62696159/angular10-uncaught-typeerror-cannot-read-property-document-of-undefined-at)), but none of the answers there seem to be relevant.

**Comment by nitoloz** [comment]
Thanks a lot @alan-agius4, I was missing a bit with using `(globalThis as any)['CalHeatMap'];`, so this fixed the thing for me.
