### ISSUE TITLE
Missing typings directory

### ISSUE THREAD

**Issue by roggaioso** [angular/angular-cli#2278]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Win2012

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
node 6.4.0
npm 3.10.3

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
`ng new myapp`
`npm i -g typings`   (`typings install` failed)
when I run `ng serve` I get the error:

```
The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory: typings
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\bro
ccoli-sane-watcher\index.js:90:11)
    at E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\angular-cli-broccoli\lib\builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js: 1048:17)
    at E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:331:11
    at lib$rsvp$asap$$flush (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at new Funnel (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\broccoli-funnel\index.js:44:10)
    at Angular2App._buildInputTree (E:\apps\js\bdogo-web\node_modules\angular-cli\lib\broccoli\angular2-app.js:93:7)
    at new Angular2App (E:\apps\js\bdogo-web\node_modules\angular-cli\lib\broccoli\angular2-app.js:51:41)
    at module.exports (E:\apps\js\bdogo-web\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules
\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\angular-cli\lib
\models\builder.js:89:10)
    at new Class (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\angular-cli\lib\
tasks\serve.js:15:19)
    at E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:1
6)
    at lib$rsvp$$internal$$invokeCallback (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:
1048:17)
    at lib$rsvp$$internal$$publish (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11
)
    at lib$rsvp$asap$$flush (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

5. Mention any other details that might be useful.
Despite the message saying that the typings directory doesn't exist, the folder is in node_modules.

**Comment by roggaioso** [comment]
I updated Node.js (v6.6.0), recreated the application, but the problem persists. Remember that despite the message, the typings directory exists in the folder node_modules.

**Comment by roggaioso** [comment]
I runned `typings install dt~es6-promise dt~es6-collections --global --save` and the error changed.

```
Error: Typescript found the following errors:
  E:/apps/js/bdogo-web/tmp/broccoli_type_script_compiler-input_base_path-wVE0aUy1.tmp/0/src/app/app.component.spec.ts (6, 1): Cannot find name 'describe'.
  E:/apps/js/bdogo-web/tmp/broccoli_type_script_compiler-input_base_path-wVE0aUy1.tmp/0/src/app/app.component.spec.ts (7, 3): Cannot find name 'beforeEach'.
  E:/apps/js/bdogo-web/tmp/broccoli_type_script_compiler-input_base_path-wVE0aUy1.tmp/0/src/app/app.component.spec.ts (11, 3): Cannot find name 'it'.
  E:/apps/js/bdogo-web/tmp/broccoli_type_script_compiler-input_base_path-wVE0aUy1.tmp/0/src/app/app.component.spec.ts (13, 7): Cannot find name 'expect'.
  E:/apps/js/bdogo-web/tmp/broccoli_type_script_compiler-input_base_path-wVE0aUy1.tmp/0/src/app/app.component.spec.ts (16, 3): Cannot find name 'it'.
  E:/apps/js/bdogo-web/tmp/broccoli_type_script_compiler-input_base_path-wVE0aUy1.tmp/0/src/app/app.component.spec.ts (18, 7): Cannot find name 'expect'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (E:\apps\js\bdogo-web\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (E:\apps\js\bdogo-web\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (E:\apps\js\bdogo-web\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (E:\apps\js\bdogo-web\node_modules\angular-cli\lib\broccoli\angular2-app.js:331:18)
    at Angular2App._buildTree (E:\apps\js\bdogo-web\node_modules\angular-cli\lib\broccoli\angular2-app.js:124:23)
    at new Angular2App (E:\apps\js\bdogo-web\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (E:\apps\js\bdogo-web\angular-cli-build.js:10:10)
    at Class.setupBroccoliBuilder (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.init (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.run (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (E:\apps\js\bdogo-web\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

**Comment by roggaioso** [comment]
I updated the Angular (to RC6), updated the Anglular-CLI (beta-10 to beta-15, following [this link](https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14)), delete and recreated the project ..... ta da!
It worked!
