### ISSUE TITLE
Error: Transformation map 0 must have exactly one source file. after upgrading to v12

### ISSUE THREAD

**Issue by UchihaYuki** [angular/angular-cli#22838]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: angular v11

### Description

 A clear and concise description of the problem...
This is what I got after upgrading to angular v12 and run `ng serve`:
```
./node_modules/@apollo/client/cache/inmemory/fixPolyfills.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: Transformation map 0 must have exactly one source file.
Did you specify these with the most recent transformation maps first?
    at buildSourceMapTree (C:\Data\projects\iam\ngx-iam\node_modules\@ampproject\remapping\dist\remapping.umd.js:729:23)
    at Object.remapping [as default] (C:\Data\projects\iam\ngx-iam\node_modules\@ampproject\remapping\dist\remapping.umd.js:831:23)
    at Object.result (C:\Data\projects\iam\ngx-iam\node_modules\@angular-devkit\build-angular\src\babel\webpack-loader.js:165:43)
    at Object.<anonymous> (C:\Data\projects\iam\ngx-iam\node_modules\babel-loader\lib\index.js:211:43)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Data\projects\iam\ngx-iam\node_modules\babel-loader\lib\index.js:3:103)
    at _next (C:\Data\projects\iam\ngx-iam\node_modules\babel-loader\lib\index.js:5:194)
```

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.2.16       
Node: 16.13.1 (Unsupported)
Package Manager: npm 8.1.2 
OS: win32 x64

Angular: 12.2.16
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.16
@angular-devkit/build-angular   12.2.16
@angular-devkit/core            12.2.16
@angular-devkit/schematics      12.2.16
@schematics/angular             12.2.16
ng-packagr                      12.2.7
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by UchihaYuki** [comment]
>  Please update to the most recent Angular CLI version.
Do you mean I have to use angular v13?

**Comment by alan-agius4** [comment]
@UchihaYuki, yes currently 13.2.6.

**Comment by UchihaYuki** [comment]
Got it. Thank you!
