### ISSUE TITLE
[children] undefined

### ISSUE THREAD

**Issue by jeromflo** [angular/angular-cli#23035]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

With ng serve the application work, but when I use build, the application compile then in the browser give me the error.

## 🔬 Minimal Reproduction

I have two components, first.component.ts and second.component.ts:
In the first.component.ts have one router-outlet without name, but in the second.component.ts i have one router-outlet with name 
(<router-outlet name='content-body'></router-outlet>).
From the routing.module.ts I have this: 
routes = [

    {
      path: 'consultas', component: FirstComponent, canActivate: [LoginGuard, ConsultasGuard], children: [
        { path: '', outlet: 'content-body', component: SecondComponentA}
      ]
    },
    {
      path: 'terminos', component: FirstComponent, canActivate: [LoginGuard, TerminosGuard], children: [
        { path: '', outlet: 'content-body', component: SecondComponentB}
      ]
    },
    {
      path: 'formularioTazul', component: FirstComponent, canActivate: [LoginGuard, /* FormGurad*/], children: [
        { path: '', outlet: 'content-body', component: SecondComponentC}
      ]
    },
    { path: 'login', component: LoginComponent, canActivate: [/* TokenGuard, */] },
    { path: '', pathMatch: 'full', redirectTo: '/login' },
    { path: '**', component: ViewsUnknowComponent },

  ];

Note that have SecondComponent A, B, C that will be render and diferents between.

## 🔥 Exception or Error

TypeError: Cannot read properties of undefined (reading 'children')
    at T (router.js:2385:1)
    at v (router.js:2324:1)
    at mn.resetConfig (router.js:4476:1)
    at new mn (router.js:3998:1)
    at Object.useFactory (router.js:6064:1)
    at Object.r [as factory] (core.js:11541:1)
    at oD.hydrate (core.js:11457:1)
    at oD.get (core.js:11276:1)
    at ky (core.js:4770:1)
    at Object.Zn (core.js:4774:1)

## 🌍 Your Environment

Angular CLI: 12.2.10
Node: 14.17.6
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 12.2.16
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.17
@angular-devkit/build-angular   12.2.17
@angular-devkit/core            12.2.17
@angular-devkit/schematics      12.2.10
@angular/cdk                    12.2.13
@angular/cli                    12.2.10
@schematics/angular             12.2.10
typescript                      4.3.5

**Anything else relevant?**

**Comment by jeromflo** [comment]
Okey, I will close this issue. The error happened, because in the router, didn't put the routes.
I have 2 enviroments, develop and production, and have a sentence if else, where if(enviroment==='dev') put the routes of develop and the otherside put the routes of the client. And the client didn't put the routes. Literally comented. Really thanks and sorry for the lose time.
