### ISSUE TITLE
Failure to run Angular-CLI application

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#2310]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 x64

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Added code, and trying to serve the application using ng serve.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
zone.js:355 Unhandled Promise rejection: No provider for ElementRef! ; Zone: <root> ; Task: Promise.then ; Value: NoProviderError {_nativeError: Error: No provider for ElementRef!
    at NoProviderError.Error (native)
    at NoProviderError.Base…, keys: Array[1], injectors: Array[1]} Error: No provider for ElementRef!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (http://localhost:4200/main.bundle.js:6643:34)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4200/main.bundle.js:60889:16)
    at new NoProviderError (http://localhost:4200/main.bundle.js:60920:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/main.bundle.js:81525:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/main.bundle.js:81553:25)
    at ReflectiveInjector_._getByKey (http://localhost:4200/main.bundle.js:81516:25)
    at ReflectiveInjector_.get (http://localhost:4200/main.bundle.js:81325:21)
    at NgModuleInjector.AppModuleInjector.createInternal (AppModule.ngfactory.js:208:46)
    at NgModuleInjector.create (http://localhost:4200/main.bundle.js:61797:76)

5. Mention any other details that might be useful.
When I try to use Augury it states: 
This application is running in production mode and therefore cannot be debugged using Augury.
Please rebuild your application in debug mode or remove the call to enableProdMode().

but I am using ng serve without any additional parameters.  Any suggestions.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by cre8** [comment]
Have you added it to a service class? Because you can only to it in a component or a directive.

http://stackoverflow.com/questions/36495706/injecting-elementref-to-injecable-error

**Comment by daBishMan** [comment]
Thank you for your response, I am not using it in a service.   I am using it in one place only, and it is (@Directive).  I have the code commented out and I still get this error.

**Comment by daBishMan** [comment]
Additional info:

	zone.js:357 Error: Uncaught (in promise): Error: No provider for ElementRef!
    at resolvePromise (http://localhost:4200/main.bundle.js:103464:31)
    at http://localhost:4200/main.bundle.js:103500:17
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:103271:37)
    at Zone.runTask (http://localhost:4200/main.bundle.js:103171:47)
    at drainMicroTaskQueue (http://localhost:4200/main.bundle.js:103403:35)consoleError @ zone.js:357_loop_1 @ zone.js:382drainMicroTaskQueue @ zone.js:386
