### ISSUE TITLE
 throw new Error('"' + aSource + '" is not in the SourceMap.')

### ISSUE THREAD

**Issue by Emmanuel-Mariki** [angular/angular-cli#2319]
Ubuntu 16.04 LTS

angular-cli: 1.0.0-beta.15

Created a new app using angular-cli but ended up with below error after ng-serve 

Error: "/usr/local/lib/node_modules/angular-cli/node_modules/angular2-template-loader/index.js!/home/emma/sites/fire/src/app/app.component.ts" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704:13)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:133:40
    at Array.forEach (native)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:132:32)
    at SourceMapSource.node (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ReplaceSource.js:66:29)
    at CachedSource.node (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at ConcatSource.proto.sourceAndMap (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:18)
    at CachedSource.sourceAndMap (/usr/local/lib/node_modules/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:51:28)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
    at Array.map (native)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:84)
    at Array.forEach (native)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:42:11)
    at Compilation.applyPlugins (/usr/local/lib/node_modules/angular-cli/node_modules/tapable/lib/Tapable.js:25:14)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:611:10)
    at next (/usr/local/lib/node_modules/angular-cli/node_modules/tapable/lib/Tapable.js:81:11)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/ProgressPlugin.js:118:5)
    at Compilation.applyPluginsAsync (/usr/local/lib/node_modules/angular-cli/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:607:9)
    at next (/usr/local/lib/node_modules/angular-cli/node_modules/tapable/lib/Tapable.js:81:11)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/ProgressPlugin.js:114:5)
    at Compilation.applyPluginsAsync (/usr/local/lib/node_modules/angular-cli/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:603:8)
    at next (/usr/local/lib/node_modules/angular-cli/node_modules/tapable/lib/Tapable.js:81:11)
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/ProgressPlugin.js:110:5)
    at Compilation.applyPluginsAsync (/usr/local/lib/node_modules/angular-cli/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.seal (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:551:7)
    at Compiler.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compiler.js:436:15)
    at /usr/local/lib/node_modules/angular-cli/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:444:10)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:420:12
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:332:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:332:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:332:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:332:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:332:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:332:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:332:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:332:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:192:8)
    at Compilation.processModuleDependencies (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:177:7)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:314:12
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:124:4
    at Array.forEach (native)
    at callback (/usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:123:12)
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/Compilation.js:147:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/NormalModule.js:203:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/webpack/lib/NormalModule.js:158:10
    at /usr/local/lib/node_modules/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/usr/local/lib/node_modules/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at /usr/local/lib/node_modules/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.finished (/usr/local/lib/node_modules/angular-cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /usr/local/lib/node_modules/angular-cli/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

**Comment by KolevDarko** [comment]
I got the same error on Ubuntu 14.04
Solved it by running 'ng init' and choosing to override all of the config files and then running 'ng serve' again.

**Comment by Emmanuel-Mariki** [comment]
Thanks @KolevDarko  i managed to get it done using your approach

**Comment by thanatos11** [comment]
still have it on beta 17:

Envirnoment:
angular-cli: local (v1.0.0-beta.17, branch: master)
node: 6.6.0
os: linux x64
npm: 3.10.3

FULL error output:
Error: "/home/lamp/angular-cli/node_modules/angular2-template-loader/index.js!/var/www/accenture/accenture-app/src/app/profile/profile.module.ts" is not in the SourceMap.                     
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (/home/lamp/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:704:13)
    at /home/lamp/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:133:40
    at Array.forEach (native)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/home/lamp/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:132:32)
    at SourceMapSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ReplaceSource.js:66:29)
    at CachedSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at /home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at ConcatSource.proto.sourceAndMap (/home/lamp/angular-cli/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:18)
    at CachedSource.sourceAndMap (/home/lamp/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:51:28)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
    at Array.map (native)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:84)
    at Array.forEach (native)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:42:11)
    at Compilation.applyPlugins (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:25:14)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:616:10)
    at next (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:81:11)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/ProgressPlugin.js:118:5)
    at next (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:83:14)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:144:4)
    at Compilation.applyPluginsAsync (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:612:9)
    at next (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:81:11)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/ProgressPlugin.js:114:5)
    at Compilation.applyPluginsAsync (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:608:8)
    at next (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:81:11)
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/ProgressPlugin.js:110:5)
    at Compilation.applyPluginsAsync (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:85:13)
    at Compilation.seal (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:554:7)
    at Compiler.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/Compiler.js:468:16)
    at /home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:152:11
    at Compilation.<anonymous> (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:452:10)
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:423:12
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
    at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:192:8)
    at Compilation.processModuleDependencies (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:177:7)
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:317:12
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:124:4
    at Array.forEach (native)
    at callback (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:123:12)
    at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:147:10
    at /home/lamp/angular-cli/node_modules/webpack/lib/NormalModule.js:209:10
    at /home/lamp/angular-cli/node_modules/webpack/lib/NormalModule.js:164:10
    at /home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at iterateNormalLoaders (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:213:10)
    at /home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:228:3
    at runSyncOrAsync (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:125:11)
    at iterateNormalLoaders (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at iterateNormalLoaders (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:213:10)
    at /home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:228:3
    at context.callback (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at /home/lamp/angular-cli/node_modules/postcss-loader/index.js:67:13

I have tried everything; Any ideas?
