### ISSUE TITLE
ng autocomplete throws an error when launching terminal with Node 16

### ISSUE THREAD

**Issue by pavankjadda** [angular/angular-cli#23288]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] completion

### Is this a regression?
No. This is a new feature in Angular 14 CLI

### Description
I have Node 16.15.1 installed. After upgrading to Angular 14 and launching Terminal, I see below error

## 🔬 Minimal Reproduction
1. Set Node 16 as default version
2. Launch terminal on macOS
3. Make sure following script added to `.bash_profile`
    ```
    # Load Angular CLI autocompletion.
    source <(ng completion script)
    ```

## 🔥 Exception or Error

<pre><code>

MacBook:~ jaddap2$ node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:817:11)
    at Socket._write (node:net:829:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at SafeSubscriber._next (/Users/jaddap2/.nvm/versions/node/v16.15.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/cli-logger.js:52:20)
    at SafeSubscriber.__tryOrUnsub (/Users/jaddap2/.nvm/versions/node/v16.15.1/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/jaddap2/.nvm/versions/node/v16.15.1/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:143:22)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 14.0.0
Node: 16.15.1
Package Manager: npm 8.11.0 
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1400.0 (cli-only)
@angular-devkit/core         14.0.0 (cli-only)
@angular-devkit/schematics   14.0.0 (cli-only)
@schematics/angular          14.0.0 (cli-only)

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
What do you get when you run `ng completion script` directly in the terminal?

**Comment by pavankjadda** [comment]
> What do you get when you run `ng completion script` directly in the terminal?

I see below bash script
```
###-begin-ng-completions-###
#
# yargs command completion script
#
# Installation: ng completion >> ~/.bashrc
#    or ng completion >> ~/.bash_profile on OSX.
#
_ng_yargs_completions()
{
    local cur_word args type_list

    cur_word="${COMP_WORDS[COMP_CWORD]}"
    args=("${COMP_WORDS[@]}")

    # ask yargs to generate completions.
    type_list=$(ng --get-yargs-completions "${args[@]}")

    COMPREPLY=( $(compgen -W "${type_list}" -- ${cur_word}) )

    # if no match was found, fall back to filename completion
    if [ ${#COMPREPLY[@]} -eq 0 ]; then
      COMPREPLY=()
    fi

    return 0
}
complete -o bashdefault -o default -F _ng_yargs_completions ng
###-end-ng-completions-###

```
