### ISSUE TITLE
After upgrade from angular 13 to angular 14 - Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID 

### ISSUE THREAD

**Issue by MustafaElKhalifa** [angular/angular-cli#23444]
# 🐞 Bug report

- [x] build
- [x] serve

### Description

  I have an NX workspace that have all angular projects and after I upgraded to angular 14 I got that error and it was working with me perfectly in angular 13 

## 🔥 Exception or Error

<pre><code>

/Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/vocabularies/core/id.js:6
        throw new Error('NOT SUPPORTED: keyword "id", use "$id" for schema ID');
              ^
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/phpier/Code/ng14/node_modules/@angular-devkit/core/node_modules/ajv/dist/compile/codegen/index.js:568:18)
</code></pre>

## 🌍 Your Environment

<pre><code>

node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng serve --proxy-config proxy.conf.json /n

> nx run main-app:serve --proxy-config=proxy.conf.json
</code></pre>

**Comment by alan-agius4** [comment]
This is expected. 

Please file an issue with the author of the `serve` builder that you are using.

**Comment by MustafaElKhalifa** [comment]
ok good but the issue is related to @angular-devkit/core itself

**Comment by alan-agius4** [comment]
Indeed as `id` is no longer supported and this was one of the breaking changes in `@angular-devkit/core` version `13.0.0`. 

> @angular-devkit/core
With this change we drop support for the deprecated behaviour to transform id in schemas. Use $id instead.

Full changelog https://github.com/angular/angular-cli/releases/tag/13.0.0

**Comment by MustafaElKhalifa** [comment]
Thanks and much appreciated
