### ISSUE TITLE
Error building project using artifacts created from angular source code build

### ISSUE THREAD

**Issue by phalgunv** [angular/angular-cli#23527]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

In order to inestigate https://github.com/angular/angular/issues/13993, first I build angular-cli from source, then installed the tar balls and created a new angular project with it. This was done so that a new angular project is created with the correct dependencies.

Then I followed instructions at thttps://github.com/angular/angular/blob/main/docs/DEVELOPER.md
to copy angular build artifacts over to the newly created project using `yarn link`. Running "npm start" results in the above error. 

I manually updated the javascript bundle where the issue was found and replaced ExternalExpr as suggested in the error message below. When I ran `npm start` again, I did not get error for `ExternalExpr` but similar error for another named export. Is there anything I am missing?

### Please provide the exception or error you saw

```true
An unhandled exception occurred: Named export 'ExternalExpr' not found. The requested module '@angular/compiler' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@angular/compiler';
const { ExternalExpr, ExternalReference, WrappedNodeExpr } = pkg;
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.0-next.0
node: v14.17.0
```

**Comment by alan-agius4** [comment]
This is caused by symbolic links being resolved using their real path. 

You need to spawn the CLI using the following command
```
```
There are two problems here though

1) NGCC

**Comment by JoostK** [comment]
And the warnings indicate that there are pre-existing links. I can't tell from that warning where those links were created, but it may be that you'll first have to unlink from a different directory. It might also be that Yarn reports that warning if the link is already created from within the same directory, in which case the warning is a red-herring.

**Comment by alan-agius4** [comment]
This is caused by symbolic links being resolved using their real path. 

You need to spawn the CLI using [`node --preserve-symlinks`](https://nodejs.org/dist./v8.14.0/docs/api/cli.html#cli_preserve_symlinks)

```bash
node --preserve-symlinks node_modules/.bin/ng s
```

This would still cause the same error but this time in NGCC. We are spawning NGCC using a child process, which also requires the node option `--preserve-symlinks-main` to be passed but this gets a bit tricky because we cannot pass it from the command line since this would break the Angular CLI. Therefore, since Angular packages don't need to be NGCC'd you can bypass this by setting `BAZEL_TARGET` to a truthy value. 

Unix Systems
```
BAZEL_TARGET="1" node --preserve-symlinks node_modules/.bin/ng s
``` 

Windows 
```
set BAZEL_TARGET="1" && node --preserve-symlinks node_modules/.bin/ng s
```

**Comment by phalgunv** [comment]
I am assuming that I only need to start the dev server using the command provided, i.e. re-run step 12.

I see a different error now from node.js. The result is same when I run from cmd and git-bash.

`C:\code\github\test>set BAZEL_TARGET="1" && node --preserve-symlinks node_modules/.bin/ng s
C:\code\github\test\node_modules\.bin\ng:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
←[90m    at wrapSafe (internal/modules/cjs/loader.js:984:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1032:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:933:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:774:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m`

**Comment by alan-agius4** [comment]
Are you using powershell as your terminal by any chance?

Can you try the below;

```
set BAZEL_TARGET="1" && node --preserve-symlinks "node_modules/.bin/ng" s
```

**Comment by phalgunv** [comment]
I get the same error with `set BAZEL_TARGET="1" && node --preserve-symlinks "node_modules/.bin/ng" s`:

`C:\code\github\test>set BAZEL_TARGET="1" && node --preserve-symlinks "node_modules/.bin/ng" s
C:\code\github\test\node_modules\.bin\ng:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
←[90m    at wrapSafe (internal/modules/cjs/loader.js:984:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1032:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:933:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:774:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m`

Finally, `set BAZEL_TARGET="1" && node --preserve-symlinks node_modules/@angular/cli/lib/init.js s` worked like a charm! Thanks @alan-agius4 
`C:\code\github\test>set BAZEL_TARGET="1" && node --preserve-symlinks node_modules/@angular/cli/lib/init.js s
√ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   1.74 MB |
polyfills.js          | polyfills     | 315.33 kB |
styles.css, styles.js | styles        | 207.36 kB |
main.js               | main          |  48.30 kB |
runtime.js            | runtime       |   6.51 kB |

                      | Initial Total |   2.30 MB

Build at: 2022-07-08T23:35:27.526Z - Hash: 22eabbc2eb8b501b - Time: 8113ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


√ Compiled successfully.`

**Comment by alan-agius4** [comment]
> Does it mean the https://github.com/angular/angular/blob/main/docs/DEVELOPER.md#building needs to be updated?

Yes.
