### ISSUE TITLE
Cannot Get Package To Install (Windows 7 - Corporate Environment)

### ISSUE THREAD

**Issue by StephenRiosDev** [angular/angular-cli#2358]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7 (Corporate Environment)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

Could not get package to install
Node Version is 4.5.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Tried running the following commands:
npm install -g angular-cli
npm install -g -f angular-cli
npm --proxy "--sanitized--" install -g angular-cli
npm --proxy "--sanitized--" install -g -f angular-cli

4. The log given by the failure. Normally this include a stack trace and some
   more information.

This log has been sanitized for corporate compliance

```
C:\>npm --proxy "--sanitized--" install -g angular-c
li
npm WARN peerDependencies The peer dependency webpack@* included from html-webpa
ck-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.
assign.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130

> execSync@1.0.2 install C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\angul
ar-cli\node_modules\angular2-template-loader\node_modules\codecov\node_modules\e
xecSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn node-gyp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@
^4.0.0.

> node-sass@3.10.0 install C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\ang
ular-cli\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/
v3.10.0/win32-x64-46_binding.node
Binary downloaded and installed at C:\Users\--sanitized--\AppData\Roaming\npm\node_mod
ules\angular-cli\node_modules\node-sass\vendor\win32-x64-46\binding.node

> node-zopfli@1.4.0 install C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\an
gular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Releas
e/zopfli-v1.4.0-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.
5.0 (node-v46 ABI) (falling back to source compile with node-gyp)

C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compr
ession-webpack-plugin\node_modules\node-zopfli>if not defined npm_config_node_gy
p (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
odules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compr
ession-webpack-plugin\node_modules\node-zopfli>if not defined npm_config_node_gy
p (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
odules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users
\--sanitized--\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-w
ebpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.nod
e --module_name=zopfli --module_path=C:\Users\--sanitized--\AppData\Roaming\npm\node_m
odules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zop
fli\lib\binding\node-v46-win32-x64 )  else (node "" configure --fallback-to-buil
d --module=C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\angular-cli\node_mo
dules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-w
in32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\--sanitized--\AppData
\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\no
de_modules\node-zopfli\lib\binding\node-v46-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=C:\\Users\\--sanitized--\\AppData\\Roaming\\npm\\node_modu
les\\angular-cli\\node_modules\\compression-webpack-plugin\\node_modules\\node-z
opfli\\lib\\binding\\node-v46-win32-x64\\zopfli.node" "--module_name=zopfli" "--
module_path=C:\\Users\\--sanitized--\\AppData\\Roaming\\npm\\node_modules\\angular-cli
\\node_modules\\compression-webpack-plugin\\node_modules\\node-zopfli\\lib\\bind
ing\\node-v46-win32-x64"
gyp ERR! cwd C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\angular-cli\node_
modules\compression-webpack-plugin\node_modules\node-zopfli
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\angular-
cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding
\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpac
k-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\--sanitized--\AppDat
a\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\n
ode_modules\node-zopfli\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\--sanitized\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\compression
-webpack-plugin\\node_modules\\node-zopfli\\node_modules\\node-pre-gyp\\bin\\nod
e-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\angular-
cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\
--sanitized--\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-we
bpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node
 --module_name=zopfli --module_path=C:\Users\--sanitized--\AppData\Roaming\npm\node_mo
dules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopf
li\lib\binding\node-v46-win32-x64' (1)

> node-sass@3.10.0 postinstall C:\Users\--sanitized--\AppData\Roaming\npm\node_modules
\angular-cli\node_modules\node-sass
> node scripts/build.js

"C:\Users\--sanitized--\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node
-sass\vendor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.
npm WARN optional dep failed, continuing node-zopfli@1.4.0
C:\Users\--sanitized--\AppData\Roaming\npm\ng -> C:\Users\--sanitized--\AppData\Roaming\npm\
node_modules\angular-cli\bin\ng
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "--proxy" "--sanitized--" "install" "-g" "angular-cli"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its sibl
ings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1
.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta

npm ERR! peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2
.0.0-beta || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-b
eta

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>
```

5. Mention any other details that might be useful.

This machine is behind a proxy which blocks all HTTPS requests to domains not white-listed by the corporate network. Maybe this is the issue? If so can I run this with only HTTP requests?

**Comment by gelliott181** [comment]
Your error has the cause written right into it: `gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`

Install Python 2.7 and add it to your path, or set the PYTHON environment variable to your Python 2.7 installation directory.

**Comment by StephenRiosDev** [comment]
Upgraded version of NPM to 3+ after reading buried pre-req. Solved the issue.  Thank you very much.

**Comment by rstropek** [comment]
I had the same issue. Installing Python 2.7 and setting `PYTHON` environment variable helped. However, afterwards I got the following error:

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The W
indows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pa
ges or by right-clicking the solution and selecting "Retarget solution". [C:\Code\GitHub\javascript-samples\angular2\samples2\node_mod
ules\node-zopfli\build\zopfli.vcxproj]
```

I understand that I could now install the Windows SDK mentioned in the error message (although I am not 100% sure if it is possible to install the SDK 8.1 on a Windows 10 machine). However, I find it really hard that I am forced to install Python and a pretty large Windows SDK just to run Angular CLI on Windows 10 without errors.

Despite the error, Angular CLI works on my machine. Serve, build, e2e tests, everything runs fine. So for now I personally just ignore the error and hope that the hard prerequisites will be solved in the future.
