### ISSUE TITLE
@ngtools/webpack AngularWebpackPlugin error when going from Angular 12 to Angular 13

### ISSUE THREAD

**Issue by angulardev123** [angular/angular-cli#23637]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.2.16

### Description

I submitted a Stackoverflow [question](https://stackoverflow.com/questions/73087645/ngtools-webpack-angularwebpackplugin-error-when-going-from-angular-12-to-angula) last week but have received no answers.

I have a large Angular 12 application that uses Webpack 5.55.1, not the Angular CLI. When I tried to upgrade from Angular 12.2.16 and @ngtools/webpack 12.0.5 to Angular 13.3.11 and @ngtools/webpack 13.3.9 I get a webpack-cli error as shown below when trying to compile in 'production' mode. The app compiles fine in 'development' mode since it doesn't use the AOT compiler. I have included the 'production' webpack config as well. Is there anything I'm missing?

Webpack production configuration (webpack.prod.js):

<pre><code>
const AngularWebpackPlugin = require('@ngtools/webpack').AngularWebpackPlugin;
...

module:
    {
        rules:
            [                                       
                {
                    test: /\.[cm]?js$/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            cacheDirectory: true,
                            compact: false,
                            plugins: ['@angular/compiler-cli/linker/babel'],
                            },
                        },
                    },
                {
                    test: /\.[jt]sx?$/,
                    loader: '@ngtools/webpack',
                    include: [path.resolve(__dirname, "app")],
                    exclude: [path.resolve(__dirname, "node_modules")]                
                }
            ]
        },
        plugins:
            [                   
                new AngularWebpackPlugin({
                        tsconfig: './tsconfig.json'
                })
            ]
</code></pre>

## 🔥 Exception or Error

<pre><code>
TypeError: Invalid host defined options
    at eval (eval at initializeCompilerCli (D:\myapp\node_modules\@ngtools\webpack\src\ivy\plugin.js:532:40), <anonymous>:3:1)
    at AngularWebpackPlugin.initializeCompilerCli (D:\myapp\node_modules\@ngtools\webpack\src\ivy\plugin.js:532:95)
    at D:\myapp\node_modules\@ngtools\webpack\src\ivy\plugin.js:128:73
    at Hook.eval [as callAsync] (eval at create (D:\myapp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\myapp\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (D:\myapp\node_modules\webpack\lib\Compiler.js:1092:28)
    at D:\myapp\node_modules\webpack\lib\Compiler.js:517:12
    at Compiler.readRecords (D:\myapp\node_modules\webpack\lib\Compiler.js:929:11)
    at D:\myapp\node_modules\webpack\lib\Compiler.js:514:11
    at Hook.eval [as callAsync] (eval at create (D:\myapp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular: 13.3.11
@ngtools/webpack: 13.3.9
Node: 14.17.1
Webpack: 5.55.1
webpack-cli: 4.8.0

</code></pre>

**Anything else relevant?**

I'm using require to import the AngularWebpackPlugin, would this make a difference?  I see some examples use ES import statements.

**Comment by alan-agius4** [comment]
`Invalid host defined options` is a Node.JS error which in later versions the error itself has been improved to be more actionable. 

Can you try to update to Node to 16?

**Comment by angulardev123** [comment]
> `Invalid host defined options` is a Node.JS error which in later versions the error itself has been improved to be more actionable.
> 
> Can you try to update to Node to 16?

Here is the error when using Node 16.16.0:

<pre><code>
TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:372:5)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
    at eval (eval at initializeCompilerCli (D:\ForeSite\Trunk\Clients\OrionClient\OrionApp\node_modules\@ngtools\webpack\src\ivy\plugin.js:532:40), <anonymous>:3:1)
    at AngularWebpackPlugin.initializeCompilerCli (D:\ForeSite\Trunk\Clients\OrionClient\OrionApp\node_modules\@ngtools\webpack\src\ivy\plugin.js:532:95)
    at D:\ForeSite\Trunk\Clients\OrionClient\OrionApp\node_modules\@ngtools\webpack\src\ivy\plugin.js:128:73
    at Hook.eval [as callAsync] (eval at create (D:\ForeSite\Trunk\Clients\OrionClient\OrionApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\ForeSite\Trunk\Clients\OrionClient\OrionApp\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (D:\ForeSite\Trunk\Clients\OrionClient\OrionApp\node_modules\webpack\lib\Compiler.js:1092:28)
    at D:\ForeSite\Trunk\Clients\OrionClient\OrionApp\node_modules\webpack\lib\Watching.js:200:19
    at eval (eval at create (D:\ForeSite\Trunk\Clients\OrionClient\OrionApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1) {
  code: 'ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING'
}
</code></pre>

**Comment by angulardev123** [comment]
Updating to webpack 5.74.0 and webpack-cli 4.10.0 resolved the issue.
