### ISSUE TITLE
RxJS 8 support

### ISSUE THREAD

**Issue by e-oz** [angular/angular-cli#23729]
# 🚀 Feature request
Please modify the code to support RxJS version 8

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Right now I have this error when trying to use RxJS 8.0.0-alpha.4 (by overriding dependencies):

```
TypeError: (0 , rxjs_1.empty) is not a function
           at new Logger (/Users/oz/repos/scs/scs-workspace/node_modules/@angular-devkit/core/src/logger/logger.js:18:38)
           at new IndentLogger (/Users/oz/repos/scs/scs-workspace/node_modules/@angular-devkit/core/src/logger/indent.js:23:9)
           at createConsoleLogger (/Users/oz/repos/scs/scs-workspace/node_modules/@angular-devkit/core/node/cli-logger.js:17:20)
           at getLogger (/Users/oz/repos/scs/scs-workspace/node_modules/nx/src/adapter/ngcli-adapter.js:849:49)
           at getTargetLogger (/Users/oz/repos/scs/scs-workspace/node_modules/nx/src/adapter/ngcli-adapter.js:856:38)
           at Object.<anonymous> (/Users/oz/repos/scs/scs-workspace/node_modules/nx/src/adapter/ngcli-adapter.js:23:24)
           at Generator.next (<anonymous>)
           at /Users/oz/repos/scs/scs-workspace/node_modules/tslib/tslib.js:118:75
           at new Promise (<anonymous>)
           at Object.__awaiter (/Users/oz/repos/scs/scs-workspace/node_modules/tslib/tslib.js:114:16)
           at Object.scheduleTarget (/Users/oz/repos/scs/scs-workspace/node_modules/nx/src/adapter/ngcli-adapter.js:20:20)
           at /Users/oz/repos/scs/scs-workspace/node_modules/nx/src/command-line/run.js:123:112
           at Generator.next (<anonymous>)
           at fulfilled (/Users/oz/repos/scs/scs-workspace/node_modules/tslib/tslib.js:115:62)
           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Please consider modifying code (I hope it's not a big change) to make it work with RxJS 8.

**Comment by alan-agius4** [comment]
> Right now I have this error when trying to use RxJS 8.0.0-alpha.4 (by overriding dependencies):

What do you mean by overriding dependency?

**Comment by e-oz** [comment]
In package.json you can add `resolutions: { "rxjs": "8.0.0..."}` (for yarn, I think npm uses something like "overrides"). This way I found that angular/dev-kit is not quite ready for RxJS 8.

It's not a "bug report", not a complaint, I just thought that maybe it would be just a quick-fix for you - it's good to be ready for the next RxJS version :)

**Comment by e-oz** [comment]
Thank you! 🎉
