### ISSUE TITLE
[ng serve]: webpack-dev-middleware Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ramoncarreras** [angular/angular-cli#23844]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.1.3

### Description

After upgrading to angular 14.2.0 and serving the APP locally, I get the following error:

```
[webpack-dev-middleware] Error: ENOENT: no such file or directory, readdir '<project-directory>/test-app/dist/test-app/'
    at createError (<project-directory>/test-app/node_modules/memfs/lib/volume.js:128:17)
    at Volume.readdirBase (<project-directory>/test-app/node_modules/memfs/lib/volume.js:1415:19)
    at Immediate.<anonymous> (<project-directory>/test-app/node_modules/memfs/lib/volume.js:695:33)
    at processImmediate (node:internal/timers:466:21) {
  code: 'ENOENT'
}
```

### Minimal Reproduction

I created a minimal reproduction in the following repository:

https://github.com/ramoncarreras/angular-test-app

I have tried to minimize the issue as I could, sorry in advance (also see each commit).

In the README.md of the above repository there is a small description of the steps to follow.

The issue appears when I add the localize and the PWA official angular packages.

### Exception or Error

```text
[webpack-dev-middleware] Error: ENOENT: no such file or directory, readdir '<project-directory>/test-app/dist/test-app/'
    at createError (<project-directory>/test-app/node_modules/memfs/lib/volume.js:128:17)
    at Volume.readdirBase (<project-directory>/test-app/node_modules/memfs/lib/volume.js:1415:19)
    at Immediate.<anonymous> (<project-directory>/test-app/node_modules/memfs/lib/volume.js:695:33)
    at processImmediate (node:internal/timers:466:21) {
  code: 'ENOENT'
}
```
```


### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.1
Node: 16.14.0
Package Manager: npm 8.5.3 
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1402.1 (cli-only)
@angular-devkit/core         14.2.1 (cli-only)
@angular-devkit/schematics   14.2.1 (cli-only)
@schematics/angular          14.2.1 (cli-only)
```

### Anything else relevant?

I can build the app locally without any problem. The error only shows when executing the `ng serve` command.

Also, I was able to reproduce the error in Ubuntu 20.04.

**Comment by jornare** [comment]
Same, Windows 10

**Comment by Sergiobop** [comment]
I don't have the localize package, still happens.

**Comment by alan-agius4** [comment]
@Sergiobop, in that case you are experiencing a different issue, please file a new issue with a minimal reproduction. Thanks.

**Comment by Sergiobop** [comment]
@alan-agius4 I will do that when your patch is released if i still have the issue.
Thanks

**Comment by sundar-rajavelu** [comment]
Hi, This is still an open issue. The minimal reproduction provided by @ramoncarreras still holds good https://github.com/ramoncarreras/angular-test-app

**Comment by Sergiobop** [comment]
Downgrading to 14.1.3 solves the issue, i think is related to the service-worker

**Comment by DadvDadv** [comment]
Angular CLI: 14.2.1
Node: 18.8.0
Package Manager: npm 8.18.0
OS: win 10 x64

Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package Version
@angular-devkit/build-angular 14.2.1
@angular/cli 14.2.1
rxjs 7.5.6
typescript 4.8.2


=> Same error

**Comment by Sergiobop** [comment]
As we stated if this happens without the localize package and you said it's a different issue.. should this be reopened? 

Thanks @alan-agius4

**Comment by alan-agius4** [comment]
@Sergiobop, I looked into this a bit more and it seems that in some cases if there is an initial compilation error the original error is not shown and eventually the build crashes with the readdir error. Example, with this changes you mentioned the build should fail with`./src/polyfills.ts:4:0-32 - Error: Module not found: Error: Can't resolve '@angular/localize/init'. `

I have a [PR](https://github.com/angular/angular-cli/pull/23858) in flight to address this.

**Comment by sourav-bhar** [comment]
Following up on the cause for this error being a compilation error (as mentioned by @alan-agius4 above), one workaround for this issue is:
1) Run a production build -> it will throw the compilation error(s)
2) Fix the compilation erorr(s)
3) Serve the app locally

It should now work.

**Comment by fr20587** [comment]
Same Error
[webpack-dev-middleware] Error: ENOENT: no such file or directory, readdir

**Comment by fr20587** [comment]
<e> [webpack-dev-middleware] Error: ENOENT: no such file or directory, readdir '...\dist\aes\'
<e>     at createError (...\node_modules\memfs\lib\volume.js:128:17)
<e>     at Volume.readdirBase (...\node_modules\memfs\lib\volume.js:1415:19)
<e>     at Immediate.<anonymous> (...\node_modules\memfs\lib\volume.js:695:33)
<e>     at processImmediate (node:internal/timers:466:21) {
<e>   code

**Comment by julien-von-oetinger** [comment]
@sourav-bhar I have the same issue and I have tried to follow the steps you mentioned. The production build returns no error but when I do ng serve I get:
```
[webpack-dev-middleware] Error: ENOENT: no such file or directory, readdir '...\dist\apps\...\'
<e>     at createError (C:\Users\e0636834\Documents\repositories\greenmotion-frontend\node_modules\memfs\lib\volume.js:128:17)
<e>     at Volume.readdirBase (C:\Users\e0636834\Documents\repositories\greenmotion-frontend\node_modules\memfs\lib\volume.js:1415:19)
<e>     at Immediate.<anonymous> (C:\Users\e0636834\Documents\repositories\greenmotion-frontend\node_modules\memfs\lib\volume.js:695:33)
<e>     at processImmediate (node:internal/timers:466:21) {
<e>   code: 'ENOENT'
<e> }
```

**Comment by sourav-bhar** [comment]
> @sourav-bhar I have the same issue and I have tried to follow the steps you mentioned. The production build returns no error but when I do ng serve I get:
> 
> ```
> [webpack-dev-middleware] Error: ENOENT: no such file or directory, readdir '...\dist\apps\...\'
> <e>     at createError (...\node_modules\memfs\lib\volume.js:128:17)
> <e>     at Volume.readdirBase (...\node_modules\memfs\lib\volume.js:1415:19)
> <e>     at Immediate.<anonymous> (...\node_modules\memfs\lib\volume.js:695:33)
> <e>     at processImmediate (node:internal/timers:466:21) {
> <e>   code: 'ENOENT'
> <e> }
> ```

@julien-von-oetinger  – I'm not sure if this helps, but I also did a couple steps prior to running the prod build:

1. Deleted the "node_modules" folder and re-installed them again w/ `npm i`
2. Updated the globally installed angular cli to v14.2 with `sudo npm i -g @angular/cli` (on mac)
3. Cleaned the Angular build cache with `ng cache clean`

Then I proceeded with the production build. This threw a compilation error. After fixing the bug, the local serving bug disappeared. Hope this helps.

**Comment by julien-von-oetinger** [comment]
@sourav-bhar Thanks for your inputs ! Unfortunately it didn't solve the issue for me. I still have the same error and I got no error during production build.

**Comment by troncomputers** [comment]
Same error shows for me after `ng add @angular/pwa`

**Comment by julien-von-oetinger** [comment]
> Same error shows for me after `ng add @angular/pwa`
> 
> #edit If I set `"serviceWorker": false` in `angular.json` error is gone.

The only issue with this is that it will completely disable the service work when you run `ng serve` AND `ng build`. I don't think there is a way to enable this flag only when you build.

**Comment by troncomputers** [comment]
@julien-von-oetinger so it is an issue with service-worker/pwa? I need it to be disabled on `ng serve`, because I am not able to code, but ultimately I want pwa to work.

**Comment by julien-von-oetinger** [comment]
@troncomputers Yes I think it related to pwa. You can disable it in order to be able to work as a work around. But when you'll build your application, the worker will be disabled too. So I'm afraid we will have to wait for a fix from the Angular team for this issue. In the meantime I'm just setting the flag to false and then set if back to true before building in my CI/CD scripts.

**Comment by troncomputers** [comment]
@julien-von-oetinger or we could downgrade the angular to working version 🤔

**Comment by julien-von-oetinger** [comment]
@troncomputers sure that's probably the best option for now.

**Comment by fr20587** [comment]
The problem is that webpack cant find in which file and line is the code error, so I solved the problem seeking file by file the problem. This problem started after udpate all packeges with `npm-check-updates`

**Comment by troncomputers** [comment]
@fr20587 I did use `npm-check-update` when I start the project, but for me the error started to show after I install `@angular/pwa`

**Comment by alan-agius4** [comment]
The fix for this will be released later today in 14.2.1.

**Comment by troncomputers** [comment]
Update is available and I was able to enable `"serviceWorker": true,` ✌

**Comment by Ruslancic** [comment]
I had the same problem too, after updating to 14.2.2, everything disappeared!

P.S Every simple error on my project, triggering this error!
