### ISSUE TITLE
ng test webpack incorrect schema errors

### ISSUE THREAD

**Issue by jusefb** [angular/angular-cli#2401]
### OS?
Windows 10. 

### Versions.

```
angular-cli: 1.0.0-beta.16
node: 5.1.0
os: win32 x64
```

```
node v5.1.0
"webpack": "2.1.0-beta.25",
 "typescript": "2.0.0",
```

### Repro steps.

running command 'ng test'

### The log given by the failure.

```
{lamb} ng test
28 09 2016 23:04:59.225:ERROR [preprocess]: Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           tslint: ...
         }
       })
     }
 - configuration.module has an unknown property 'postLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.node.global should be a boolean.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\webpack\lib\webpack.js:16:9)
    at new Plugin (karma-webpack.js:63:18)
    at invoke (C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\di\lib\injector.js:75:15)
    at Array.instantiate (C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\di\lib\injector.js:59:20)
    at get (C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\di\lib\injector.js:48:43)
    at C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\di\lib\injector.js:71:14
    at Array.map (native)
    at Array.invoke (C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\di\lib\injector.js:70:31)
    at [object Object].get (C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\di\lib\injector.js:48:43)
    at instantiatePreprocessor (C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\karma\lib\preprocessor.js:55:20)
    at C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\karma\lib\preprocessor.js:106:17
    at Array.forEach (native)
    at C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\karma\lib\preprocessor.js:103:27
    at module.exports (C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\karma\node_modules\isbinaryfile\index.js:28:12)
    at C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\karma\lib\preprocessor.js:84:7
    at C:\Users\Jusef\Source\Repos\Sadie5\SadieApp\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
28 09 2016 23:04:59.257:WARN [karma]: No captured browser, open http://localhost:9876/
28 09 2016 23:04:59.265:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
28 09 2016 23:04:59.267:INFO [launcher]: Launching browser Chrome with unlimited concurrency
28 09 2016 23:04:59.268:ERROR [karma]: Found 1 load error
```

**Comment by spongessuck** [comment]
Is your local `angular-cli` installation up to date? I got this same error before I realized the local installation was still beta-14.

**Comment by jusefb** [comment]
running beta.16

**Comment by filipesilva** [comment]
@jusefb we had a period of time between versions when a wrong version of webpack could be installed due to semver. You should be able to just reinstall beta.16+ have that error will be gone.
