### ISSUE TITLE
ng build -w does not work 

### ISSUE THREAD

**Issue by goriunov** [angular/angular-cli#2409]
### OS?
> Mac OSX  El Capitan

### Versions.
> 
angular-cli: 1.0.0-beta.16
node: 6.5.0

$ ng build -w
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Path must be a string. Received null
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at Class.run (/Users/goriunov/Desktop/GitHub Repos/multiplayr-game/front-end/node_modules/angular-cli/tasks/build-webpack-watch.js:14:26)
    at Class.run (/Users/goriunov/Desktop/GitHub Repos/multiplayr-game/front-end/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/goriunov/Desktop/GitHub Repos/multiplayr-game/front-end/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/Users/goriunov/Desktop/GitHub Repos/multiplayr-game/front-end/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/goriunov/Desktop/GitHub Repos/multiplayr-game/front-end/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/goriunov/Desktop/GitHub Repos/multiplayr-game/front-end/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/goriunov/Desktop/GitHub Repos/multiplayr-game/front-end/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by softmodal** [comment]
I'm new to this project, but it looks like commandOptions.outputPath is getting removed somewhere along the way. I'm able to work around it in the meantime by explicitly setting the output-path flag:

ng build --w --output-path="dist"

**Comment by lucasvfventura** [comment]
This is the line in the file build-webpack-watch.js where the error occurs:
```javascript
rimraf.sync(path.resolve(project.root, runTaskOptions.outputPath));
```

In the file build-webpack we can see that the outputPath is set to the outDir of the angular-cli.json:
```javascript
var outputDir = runTaskOptions.outputPath || config_1.CliConfig.fromProject().config.apps[0].outDir;
```

So to fix this issue just add these three lines of code to build-webpack-watch.js:
```javascript
var config_1 = require('../models/config');
...
var outputDir = runTaskOptions.outputPath || config_1.CliConfig.fromProject().config.apps[0].outDir;
rimraf.sync(path.resolve(project.root, outputDir));
```

**Comment by filipesilva** [comment]
Dupe in https://github.com/angular/angular-cli/issues/2006
