### ISSUE TITLE
 Migration failed: Path "tsconfig.server.json" does not exist. 

### ISSUE THREAD

**Issue by troncomputers** [angular/angular-cli#24264]
### Command

update

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.10

### Description

```
× Migration failed: Path "tsconfig.server.json" does not exist.
  See "C:\Users\my_user_name\AppData\Local\Temp\ng-IY4opN\angular-errors.log" for further details.
```

### Minimal Reproduction

Update Angular from 14.2.10 to latest 15.0.0

### Exception or Error

```text
[error] Error: Path "tsconfig.server.json" does not exist.
    at HostTree.readText (C:\Users\my_user_name\AppData\Local\Temp\angular-cli-packages-ei8R4p\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:216:19)
    at new JSONFile (D:\PROJEKTY\BackupWeb\BackupWeb\ClientApp\node_modules\@schematics\angular\utility\json-file.js:23:34)
    at removeOrUpdateTarget (D:\PROJEKTY\BackupWeb\BackupWeb\ClientApp\node_modules\@schematics\angular\migrations\update-15\update-typescript-target.js:51:18)
    at D:\PROJEKTY\BackupWeb\BackupWeb\ClientApp\node_modules\@schematics\angular\migrations\update-15\update-typescript-target.js:41:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callRuleAsync (C:\Users\my_user_name\AppData\Local\Temp\angular-cli-packages-ei8R4p\node_modules\@angular-devkit\schematics\src\rules\call.js:78:18)
```
```


### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 15.0.0
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.6
typescript                      4.8.4
```
```


### Anything else relevant?

_No response_

**Comment by alan-agius4** [comment]
Looks like you have a referencing `tsconfig.server.json` in your `angular.json` but this does not exist. We should however change this to a warning.
