### ISSUE TITLE
ng test throws ReferenceError: global is not defined

### ISSUE THREAD

**Issue by nseni** [angular/angular-cli#24262]
### Command

test

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2

### Description

After upgrading to Angular v15, `ng test` has started throwing error `ReferenceError: global is not defined`

### Minimal Reproduction

I have a big project with many files and packages, so I'm not sure how to create a minimal reproduction. I tried to disable all my tests by replacing `describe` with `xdescribe`, it did not help. I do not use "afterAll", "afterEach", "beforeAll" in any of my tests.

### Exception or Error

```text
ng test --watch=false
√ Browser application bundle generation complete.
17 11 2022 11:47:27.238:INFO [karma-server]: Karma v6.4.1 server started at http://localhost:9876/
17 11 2022 11:47:27.241:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
17 11 2022 11:47:27.245:INFO [launcher]: Starting browser ChromeHeadless
17 11 2022 11:47:27.921:INFO [Chrome Headless 107.0.5304.107 (Windows 10)]: Connected on socket Q5h7nUdGp8NO1pj4AAAB with id 71975718
Chrome Headless 107.0.5304.107 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught ReferenceError: global is not defined
  ReferenceError: global is not defined
      at Object.45861 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/has-bigints/index.js:3:15)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.3 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/is-bigint/index.js:3:18)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.72086 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/which-boxed-primitive/index.js:7:16)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.15541 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/deep-equal/index.js:10:27)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.82347 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/aria-query/lib/elementRoleMap.js:7:41)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
Chrome Headless 107.0.5304.107 (Windows 10): Executed 0 of 0 ERROR (0 secs / 0 secs)
Chrome Headless 107.0.5304.107 (Windows 10) ERROR
  An error was thrown in afterAll
  Uncaught ReferenceError: global is not defined
  ReferenceError: global is not defined
      at Object.45861 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/has-bigints/index.js:3:15)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.3 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/is-bigint/index.js:3:18)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.72086 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/which-boxed-primitive/index.js:7:16)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.15541 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/deep-equal/index.js:10:27)
      at require (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.82347 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/aria-query/lib/elementRoleMap.js:7:41)
Chrome Headless 107.0.5304.107 (Windows 10): Executed 0 of 0 ERROR (0.01 secs / 0 secs)
```

### Your Environment

```text
Angular CLI: 15.0.0
Node: 18.12.0
Package Manager: npm 9.1.1
OS: win32 x64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else relevant?

`ng build` and `ng serve` run without errors.

tsconfig.json:
```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "lib": ["ES2022", "dom"],
    "module": "ES2022",
    "moduleResolution": "node",
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "strict": true,
    "strictNullChecks": false,
    "suppressImplicitAnyIndexErrors": true,
    "target": "ES2022",
    "typeRoots": ["node_modules/@types"],
    "useDefineForClassFields": false
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

tsconfig.spec.json:
```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "types": ["jasmine"]
  },
  "include": ["src/**/*.spec.ts", "src/**/*.d.ts"]
}
```

karma.conf.js
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage'),
      require('karma-chrome-launcher'),
      require('@angular-devkit/build-angular/plugins/karma'),
    ],
    client: {
      jasmine: {
        // you can add configuration options for Jasmine here
        // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
        // for example, you can disable the random execution with `random: false`
        // or set a specific seed with `seed: 4321`
      },
      clearContext: false, // leave Jasmine Spec Runner output visible in browser
    },
    jasmineHtmlReporter: {
      suppressAll: true, // removes the duplicated traces
    },
    coverageReporter: {
      dir: require('path').join(__dirname, './coverage/aui6'),
      subdir: '.',
      reporters: [{ type: 'html' }, { type: 'text-summary' }],
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadless'],
    customLaunchers: {
      ChromeHeadlessCI: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox', '--disable-gpu'],
      },
    },
    singleRun: false,
    restartOnFileChange: true,
  });
};
```

"test" config in angular.json:
```
"test": {
  "builder": "@angular-devkit/build-angular:karma",
  "options": {
    "polyfills": ["zone.js", "zone.js/testing"],
    "tsConfig": "tsconfig.spec.json",
    "karmaConfig": "karma.conf.js",
    "inlineStyleLanguage": "scss",
    "assets": [],
    "styles": [],
    "scripts": [],
  }
},
```

package.json:
```
{
  "name": "proj",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
  },
  "private": true,
  "dependencies": {
    "@angular-material-components/datetime-picker": "8.0.0",
    "@angular/animations": "15.0.0",
    "@angular/cdk": "15.0.0",
    "@angular/common": "15.0.0",
    "@angular/compiler": "15.0.0",
    "@angular/core": "15.0.0",
    "@angular/forms": "15.0.0",
    "@angular/material": "15.0.0",
    "@angular/platform-browser": "15.0.0",
    "@angular/platform-browser-dynamic": "15.0.0",
    "@angular/router": "15.0.0",
    "@juggle/resize-observer": "3.4.0",
    "@ngneat/transloco": "4.1.1",
    "@types/crypto-js": "4.1.1",
    "bootstrap": "5.2.2",
    "cropperjs": "1.5.12",
    "crypto-js": "4.1.1",
    "date-fns": "2.29.3",
    "deepmerge": "4.2.2",
    "echarts": "5.4.0",
    "fuse.js": "6.6.2",
    "mem": "9.0.2",
    "ng-dynamic-component": "10.5.1",
    "ngx-echarts": "14.0.0",
    "ngx-mat-select-search": "5.0.0",
    "resize-observer-polyfill": "1.5.1",
    "rxjs": "7.5.7",
    "tslib": "2.4.1",
    "zone.js": "0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "15.0.0",
    "@angular-eslint/builder": "14.2.0",
    "@angular-eslint/eslint-plugin": "14.2.0",
    "@angular-eslint/eslint-plugin-template": "14.2.0",
    "@angular-eslint/schematics": "14.2.0",
    "@angular-eslint/template-parser": "14.2.0",
    "@angular/cli": "15.0.0",
    "@angular/compiler-cli": "15.0.0",
    "@ngneat/spectator": "12.1.1",
    "@types/jasmine": "4.3.0",
    "@types/node": "18.11.9",
    "@typescript-eslint/eslint-plugin": "5.43.0",
    "@typescript-eslint/parser": "5.43.0",
    "eslint": "8.27.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-import-resolver-typescript": "3.5.2",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-rxjs": "5.0.2",
    "eslint-plugin-unicorn": "44.0.2",
    "jasmine-core": "4.5.0",
    "jasmine-spec-reporter": "7.0.0",
    "karma": "6.4.1",
    "karma-chrome-launcher": "3.1.1",
    "karma-coverage": "2.2.0",
    "karma-jasmine": "5.1.0",
    "karma-jasmine-html-reporter": "2.0.0",
    "lint-staged": "13.0.3",
    "prettier": "2.7.1",
    "prettier-plugin-organize-imports": "3.2.0",
    "ts-node": "10.9.1",
    "typescript": "4.8.4"
  },
  "lint-staged": {
    "*.{ts,js,json,scss,css,md,html}": [
      "eslint --ignore-path .eslintignore --fix",
      "prettier --write"
    ]
  }
}
```

File "src/test.ts" and "src/polyfills.ts" do not exist.
I have tried removing "karma.conf.js", it did not help.

**Comment by nseni** [comment]
I removed node_modules and package-lock.json. After I re-installed the packages the error was gone!
