### ISSUE TITLE
Cannot install angular-cli

### ISSUE THREAD

**Issue by smahanta** [angular/angular-cli#2431]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
Result of ng --version:
```
Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@ngtools\webpack\src\index.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\models\webpack-build-typescript.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\models\webpack-config.js:2:34)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\tasks\build-webpack.js:6:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\commands\build.js:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Class.module.exports.includedCommands (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\addon\index.js:20:16)
    at C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\models\project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\models\project.js:391:15)
    at Project.eachAddonCommand (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\models\project.js:426:30)
    at module.exports (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\cli\lookup-command.js:33:13)
    at CLI.<anonymous> (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\cli\cli.js:34:26)
    at tryCatch (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:2370:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```
Node version is 4.5.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I was just starting out with Angular2. So first installed node(4.5.0), then typescript(2.0.3),  npm(2.15.9) came bundled with node. Then tried to install angular-cli.

### The log given by the failure.
```
C:\Users\mahantas>npm install -g angular-cli
npm WARN peerDependencies The peer dependency webpack@* included from html-webpa
ck-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.
assign.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.

> execSync@1.0.2 install C:\Users\mahantas\AppData\Roaming\npm\node_modules\angu
lar-cli\node_modules\angular2-template-loader\node_modules\codecov\node_modules\
execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn node-gyp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue

> node-zopfli@2.0.1 install C:\Users\mahantas\AppData\Roaming\npm\node_modules\a
ngular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

[node-zopfli] Success: "C:\Users\mahantas\AppData\Roaming\npm\node_modules\angul
ar-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\bind
ing\node-v46-win32-x64\zopfli.node" is installed via remote
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@
^4.0.0.
-
> node-sass@3.10.0 install C:\Users\mahantas\AppData\Roaming\npm\node_modules\an
gular-cli\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/
v3.10.0/win32-x64-46_binding.node
Binary downloaded and installed at C:\Users\mahantas\AppData\Roaming\npm\node_mo
dules\angular-cli\node_modules\node-sass\vendor\win32-x64-46\binding.node

> node-sass@3.10.0 postinstall C:\Users\mahantas\AppData\Roaming\npm\node_module
s\angular-cli\node_modules\node-sass
> node scripts/build.js

"C:\Users\mahantas\AppData\Roaming\npm\node_modules\angular-cli\node_modules\nod
e-sass\vendor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.
C:\Users\mahantas\AppData\Roaming\npm\ng -> C:\Users\mahantas\AppData\Roaming\np
m\node_modules\angular-cli\bin\ng
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its sibl
ings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1
.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta

npm ERR! peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2
.0.0-beta || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-b
eta

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mahantas\npm-debug.log
```
### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rolandoldengarm** [comment]
You have to upgrade NPM to at least v3; v2 does not work.

**Comment by viperguynaz** [comment]
Same issue on Windows 10 with Node ver 6.7.0, npm ver 3.10.3, Typescript ver 2.0.3:

Error: Cannot find module 'reflect-metadata'

**Comment by filipesilva** [comment]
@smahanta your problem was that you were using `npm2` instead of `npm3`, as @rolandoldengarm said.

@viperguynaz see https://github.com/angular/angular-cli/issues/1782

**Comment by app-sparkler** [comment]
`npm unintstall -g angular-cli`
