### ISSUE TITLE
ng serve not reloading browser tab when has changes, SSR app on mac

### ISSUE THREAD

**Issue by emilalsgndr** [angular/angular-cli#24326]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

My angular app does not detect changes in one of my apps. I tried to change any files but none of them browser did not update. My other app which is Universal not installed works fine. Both apps running the same environment. When I run npm run dev:ssr browser detects changes and tries to reload but the loading stuck and it needs manually stop loading and refresh to get changes.

### Minimal Reproduction

Angular Universal installed. 
My device is macOS Monterey 12.0 Beta. 
Angular CLI: 14.2.9
Node: 16.10.0
Package Manager: npm 7.24.0 
OS: darwin x64

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.9
@angular-devkit/build-angular   14.2.9
@angular-devkit/core            14.2.9
@angular-devkit/schematics      14.2.9
@angular/cli                    14.2.9
@nguniversal/builders           14.2.2
@nguniversal/express-engine     14.2.2
@schematics/angular             14.2.9
rxjs                            7.5.7
typescript                      4.7.4

### Your Environment

```text
package.json
{
  "name": "renderer-frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "dev:ssr": "ng run renderer-frontend:serve-ssr",
    "serve:ssr": "node dist/renderer-frontend/server/main.js",
    "build:ssr": "ng build && ng run renderer-frontend:server",
    "prerender": "ng run renderer-frontend:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.2.0",
    "@angular/common": "^14.2.0",
    "@angular/compiler": "^14.2.0",
    "@angular/core": "^14.2.0",
    "@angular/forms": "^14.2.0",
    "@angular/platform-browser": "^14.2.0",
    "@angular/platform-browser-dynamic": "^14.2.0",
    "@angular/platform-server": "^14.2.0",
    "@angular/router": "^14.2.0",
    "@nguniversal/express-engine": "^14.2.2",
    "express": "^4.15.2",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.9",
    "@angular/cli": "~14.2.9",
    "@angular/compiler-cli": "^14.2.0",
    "@nguniversal/builders": "^14.2.2",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~4.0.0",
    "@types/node": "^14.15.0",
    "jasmine-core": "~4.3.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.7.2"
  }
}
```

**Comment by emilalsgndr** [comment]
Also i have webpack issue at ng serve, this is a browser issue and when i try to add new style file source to angular.json it not get changes, if i use npm run dev:ssr it get the style file
```
index.js:43 Uncaught TypeError: __webpack_require__.h is not a function
    at 1211 (index.js:43:58)
    at __webpack_require__ (bootstrap:19:1)
    at __webpack_exec__ (styles.scss?24a6:1:1)
    at styles.scss?24a6:1:1
    at webpackJsonpCallback (jsonp chunk loading:29:1)
    at styles.js:1:87
```

**Comment by emilalsgndr** [comment]
It's probably related some npm package version, when i need to move apps prod i need change my local env, it needs to be same with server, then i start using nvm, it starts after that changes
