### ISSUE TITLE
ERROR in Cannot read properties of undefined (reading 'flags')

### ISSUE THREAD

**Issue by guoxiaxing** [angular/angular-cli#24324]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

10.2.3

### Description

Fresh CLI generated project is throwing error below on build (ng serve)

### Minimal Reproduction

ng serve

### Exception or Error

```text
ERROR in Cannot read properties of undefined (reading 'flags')
angular-test/node_modules/@angular/compiler-cli/src/ngtsc/program.js:131
                    finally { if (e_2) throw e_2.error; }
                                       ^

TypeError: Cannot read properties of undefined (reading 'flags')
    at checkUnreachable (/angular-test/node_modules/typescript/lib/typescript.js:44543:31)
    at bindChildren (/angular-test/node_modules/typescript/lib/typescript.js:42088:17)
    at bind (/angular-test/node_modules/typescript/lib/typescript.js:43632:21)
    at bindSourceFile (/angular-test/node_modules/typescript/lib/typescript.js:41634:17)
    at Object.bindSourceFile (/angular-test/node_modules/typescript/lib/typescript.js:41570:9)
    at initializeTypeChecker (/angular-test/node_modules/typescript/lib/typescript.js:81834:20)
    at Object.createTypeChecker (/angular-test/node_modules/typescript/lib/typescript.js:45704:9)
    at getDiagnosticsProducingTypeChecker (/angular-test/node_modules/typescript/lib/typescript.js:110291:93)
    at /angular-test/node_modules/typescript/lib/typescript.js:110426:35
    at runWithCancellationToken (/angular-test/node_modules/typescript/lib/typescript.js:110396:24)
```

### Your Environment

```text
Angular CLI: 10.2.4
Node: 16.14.1
OS: darwin x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1002.3
@angular-devkit/build-angular      0.1002.4
@angular-devkit/build-ng-packagr   0.1002.4
@angular-devkit/core               10.2.4
@angular-devkit/schematics         10.2.4
@angular/cdk                       10.2.7
@angular/cli                       10.2.4
@schematics/angular                10.2.4
@schematics/update                 0.1002.4
ng-packagr                         10.1.2
typescript                         4.3.2
```

**Comment by alan-agius4** [comment]
Angular 10 is no longer supported.

Please use a more recent version of Angular.
