### ISSUE TITLE
FetchError: Invalid response body while trying to fetch https://repo.huaweicloud.com/repository/npm/@angular%2fcli

### ISSUE THREAD

**Issue by fantasy0v0** [angular/angular-cli#24351]
### Command

update

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

exec ng update

### Minimal Reproduction

ng update

### Exception or Error
```text
ng update
Using package manager: pnpm
Collecting installed dependencies...
Found 32 dependencies.
× Migration failed: Invalid response body while trying to fetch https://repo.huaweicloud.com/repository/npm/karma: 70610000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:614:

  See "C:\Users\fan\AppData\Local\Temp\ng-CdXZga\angular-errors.log" for further details.
```

```text
[error] FetchError: Invalid response body while trying to fetch https://repo.huaweicloud.com/repository/npm/@angular%2fcli: F0270000:error:0A000119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:614:

    at C:\Users\fan\AppData\Local\pnpm\global\5\.pnpm\minipass-fetch@3.0.0\node_modules\minipass-fetch\lib\body.js:170:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Response.json (C:\Users\fan\AppData\Local\pnpm\global\5\.pnpm\minipass-fetch@3.0.0\node_modules\minipass-fetch\lib\body.js:75:17)
    at async RegistryFetcher.packument (C:\Users\fan\AppData\Local\pnpm\global\5\.pnpm\pacote@15.0.6\node_modules\pacote\lib\registry.js:92:25)
    at async RegistryFetcher.manifest (C:\Users\fan\AppData\Local\pnpm\global\5\.pnpm\pacote@15.0.6\node_modules\pacote\lib\registry.js:116:23)
    at async fetchPackageManifest (C:\Users\fan\AppData\Local\pnpm\global\5\.pnpm\@angular+cli@15.0.1\node_modules\@angular\cli\src\utilities\package-metadata.js:219:22)
    at async UpdateCommandModule.checkCLIVersion (C:\Users\fan\AppData\Local\pnpm\global\5\.pnpm\@angular+cli@15.0.1\node_modules\@angular\cli\src\commands\update\cli.js:671:29)
    at async UpdateCommandModule.run (C:\Users\fan\AppData\Local\pnpm\global\5\.pnpm\@angular+cli@15.0.1\node_modules\@angular\cli\src\commands\update\cli.js:154:41)
    at async UpdateCommandModule.handler (C:\Users\fan\AppData\Local\pnpm\global\5\.pnpm\@angular+cli@15.0.1\node_modules\@angular\cli\src\command-builder\command-module.js:115:24)
```

### Your Environment

```text
Your global Angular CLI version (15.0.1) is greater than your local version (14.0.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.0.0
Node: 18.12.1 (Unsupported)
Package Manager: pnpm 7.17.1
OS: win32 x64

Angular: 14.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1500.1
@angular-devkit/build-angular     14.0.0
@angular-devkit/core              15.0.1
@angular-devkit/schematics        15.0.1
@angular/material-luxon-adapter   14.0.1
@schematics/angular               15.0.1
rxjs                              6.6.7
typescript                        4.7.3

Warning: The current version of Node (18.12.1) is not supported by Angular.
```

**Comment by alan-agius4** [comment]
Hi @fantasy0v0, 

This issue is not caused by Angular CLI. It looks like your custom NPM registry is returning an invalid response body.
