### ISSUE TITLE
Possible Angular DevKit and RXJS mismatch

### ISSUE THREAD

**Issue by robomike** [angular/angular-cli#24482]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

9

### Description

"node": "18.12.1",
    "npm": "8.19.2"

There seems to be a version mismatch; for some reason, the angular/devkit depends on rjxs 6.6.7 and installs that.  However, ng build and npm install fail with a schema exception error due to the SetTimeOut function in hostReportError.js  The full exception is listed below.,

### Minimal Reproduction

to reproduce.

Upgrade a project from an older version to 15.
run npm install or ng build

### Exception or Error

```text
Error: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(showCircularDependencies).
/home/robomike/code/heroku/swa2/swa-portal/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

SchemaValidationException [Error]: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(showCircularDependencies).
    at MapSubscriber.project (/home/robomike/code/heroku/swa2/swa-portal/node_modules/@angular-devkit/architect/src/architect.js:42:27)
    at MapSubscriber._next (/home/robomike/code/heroku/swa2/swa-portal/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/map.js:49:35)
    at Subscriber.next (/home/robomike/code/heroku/swa2/swa-portal/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/robomike/code/heroku/swa2/swa-portal/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/home/robomike/code/heroku/swa2/swa-portal/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at Subscriber.next (/home/robomike/code/heroku/swa2/swa-portal/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /home/robomike/code/heroku/swa2/swa-portal/node_modules/rxjs/dist/cjs/internal/observable/innerFrom.js:120:28 {
  errors: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: { additionalProperty: 'showCircularDependencies' },
      message: 'must NOT have additional properties'
    }
  ]
}
```

### Your Environment

```text
Angular CLI: 15.0.4
Node: 18.12.1
Package Manager: npm 8.19.2
OS: linux x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@angular/cdk                    15.0.3
@angular/material               15.0.3
@schematics/angular             15.0.4
typescript                      4.8.4
```

**Comment by robomike** [comment]
This solves this issue

[fix](https://stackoverflow.com/questions/69826552/terminal-error-schema-validation-failed-with-the-following-errors-data-path)
