### ISSUE TITLE
Error: astUtils.addComponentToModule is not a function when trying to generate a component.

### ISSUE THREAD

**Issue by guiassemany** [angular/angular-cli#2456]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.7.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I was just trying to create a component ( `ng g c hello-world` ) on a new app.

### The log given by the failure.
`installing component
  create src/app/hello-worlda/hello-worlda.component.css
  create src/app/hello-worlda/hello-worlda.component.html
  create src/app/hello-worlda/hello-worlda.component.spec.ts
  create src/app/hello-worlda/hello-worlda.component.ts
astUtils.addComponentToModule is not a function
TypeError: astUtils.addComponentToModule is not a function
    at Class.afterInstall (/Users/assemany/Development/angular2/angular2_hello_world/node_modules/angular-cli/addon/ng2/blueprints/component/index.js:125:18)
    at tryCatch (/Users/assemany/Development/angular2/angular2_hello_world/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/assemany/Development/angular2/angular2_hello_world/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/assemany/Development/angular2/angular2_hello_world/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/assemany/Development/angular2/angular2_hello_world/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

### Mention any other details that might be useful.
I've already tried to uninstall, clean cache, and re install it.
I saw that there are newer releases, but I dont know if I can use it because I need Webpack. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by guiassemany** [comment]
Nevermind! I've Just read the docs more carefully and I did:
`npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest`
Now it works without problems! Thank You Guys ;)
