### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by koutoftimer** [angular/angular-cli#2458]
### OS

```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

### Steps to reproduce

```
sudo apt-get install nodejs npm
sudo npm install -g n
sudo n lts
sudo npm install -g angular-cli
```

### The log given by the failure.

```
npm ERR! registry error parsing json
 
> node-zopfli@2.0.1 install /usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.1 and node@4.6.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/ruslan/.node-gyp/4.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/node-zopfli/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/node-zopfli/build'
make: *** No rule to make target '../.node-gyp/4.6.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/node-zopfli/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-38-generic
command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/angular-cli/node_modules/compression-webpa
ck-plugin/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/no
de-zopfli/lib/binding/node-v46-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/node-zopfli
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/angular-c
li/node_modules/compression-webpack-plugin/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/local/lib/node_modules/angular-cli/node_modules/compression-w
ebpack-plugin/node_modules/node-zopfli/lib/binding/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/node-zopfli/node_modules/node-pre-gyp/lib/util/compile.js:83:2
9)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.0-38-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/node-zopfli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-b
uild"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/node-zopfli
node-pre-gyp ERR! node -v v4.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/angular-cli/node_modules/compression-web
pack-plugin/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/local/lib/node_modules/angular-cli/node_modules/compression-webpack-plugin/node_modules/node
-zopfli/lib/binding/node-v46-linux-x64' (1)
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN optional dep failed, continuing node-zopfli@2.0.1
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
/
> node-sass@3.10.1 install /usr/local/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.1/linux-x64-46_binding.node
Binary downloaded and installed at /usr/local/lib/node_modules/angular-cli/node_modules/node-sass/vendor/linux-x64-46/binding.node

> node-sass@3.10.1 postinstall /usr/local/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/build.js

"/usr/local/lib/node_modules/angular-cli/node_modules/node-sass/vendor/linux-x64-46/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-beta

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

[npm-debug.log.zip](https://github.com/angular/angular-cli/files/504114/npm-debug.log.zip)

**Comment by codecausality** [comment]
I'm facing the same problem !
[npm-debug.log.txt](https://github.com/angular/angular-cli/files/504840/npm-debug.log.txt)

**Comment by JanStureNielsen** [comment]
@koutoftimer -- the GitHub issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

Update to Node 6: http://stackoverflow.com/questions/39812448/angular-cli-installation-failure

**Comment by koutoftimer** [comment]
@JanStureNielsen works for me, thx. @codeind what about you?

**Comment by ptomaszi** [comment]
I am having the same issue when try to execute the "ng install" command. For example I execute the following: "ng install jquery" and get the following error:

The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!

I am using Node 6 and NPM 3!

**Comment by koutoftimer** [comment]
@ptomaszi my question was about installing `angular-cli` package for nodejs. You are asking about using CLI, about its command `install`. From this position you can not have 
> the same issue

**Comment by koutoftimer** [comment]
Closing, [problem solved][1] with help of @JanStureNielsen 

   [1]: https://github.com/angular/angular-cli/issues/2458#issuecomment-250974532
