### ISSUE TITLE
angular cli beta 16 is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.

### ISSUE THREAD

**Issue by NilsHolger** [angular/angular-cli#2468]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0 -beta.16
NODE: 6.5
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Created with CLI

### The log given by the failure.
> Normally this include a stack trace and some more information.
zone.js:355Unhandled Promise rejection: Template parse errors:
Can't bind to 'app' since it isn't a known property of 'app-bodydetail'.
1. If 'app-bodydetail' is an Angular component and it has 'app' input, then verify that it is part of this module.
2. If 'app-bodydetail' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
</ul>

<app-bodydetail [ERROR ->][app] = "selectedApp"></app-bodydetail>"): BodyComponent@6:16 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'app' since it isn't a known property of 'app-bodydetail'.
1. If 'app-bodydetail' is an Angular component and it has 'app' input, then verify that it is part of this module.
2. If 'app-bodydetail' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
</ul>

<app-bodydetail [ERROR ->][app] = "selectedApp"></app-bodydetail>"): BodyComponent@6:16
    at TemplateParser.parse (http://localhost:4200/main.bundle.js:16968:19)
    at RuntimeCompiler._compileTemplate (http://localhost:4200/main.bundle.js:37047:51)
    at http://localhost:4200/main.bundle.js:36970:83
    at Set.forEach (native)
    at compile (http://localhost:4200/main.bundle.js:36970:47)
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:71628:28)
    at Zone.run (http://localhost:4200/main.bundle.js:71521:43)
    at http://localhost:4200/main.bundle.js:71887:57
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:71661:37)
    at Zone.runTask (http://localhost:4200/main.bundle.js:71561:47)

### Mention any other details that might be useful.
//@Input() functions

how to add If 'app-bodydetail' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by NilsHolger** [comment]
Problem resolved: remove  from body template.

**Comment by NilsHolger** [comment]
Problem resolved: remove <app-bodydetail [app] = "selectedApp"></app-bodydetail> from body template.
