### ISSUE TITLE
ng set throws exception

### ISSUE THREAD

**Issue by choeller** [angular/angular-cli#2479]
### OS?
>Linux Mint

### Versions.
> beta.16

### Repro steps.
> Calling `ng set defaults.styleExt scss` in a project generated by the CLI leads to the exception printed below

### The log given by the failure.
> ```
Cannot read property 'serialize' of undefined
TypeError: Cannot read property 'serialize' of undefined
    at /home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:238:87
    at JsonSerializer.property (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/serializer.js:100:9)
    at _loop_1 (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:238:32)
    at /home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:243:17
    at JsonSerializer.object (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/serializer.js:88:9)
    at ObjectSchemaTreeNode.serialize (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:227:20)
    at /home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:234:92
    at JsonSerializer.property (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/serializer.js:100:9)
    at _loop_1 (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:234:36)
    at /home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:243:17
    at JsonSerializer.object (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/serializer.js:88:9)
    at ObjectSchemaTreeNode.serialize (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:227:20)
    at /home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:296:33
    at JsonSerializer.array (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/serializer.js:107:9)
    at ArraySchemaTreeNode.serialize (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:294:20)
    at /home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:234:92
    at JsonSerializer.property (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/serializer.js:100:9)
    at _loop_1 (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:234:36)
    at /home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:243:17
    at JsonSerializer.object (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/serializer.js:88:9)
    at RootSchemaTreeNode.ObjectSchemaTreeNode.serialize (/home/christoph/.nvm/versions/node/v5.11.0/lib/node_modules/angular-cli/models/json-schema/schema-tree.js:227:
```
### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JanStureNielsen** [comment]
Dup of #1900
