### ISSUE TITLE
"npm init @angular myApp" does not work

### ISSUE THREAD

**Issue by lizhiyu-me** [angular/angular-cli#24842]
### Describe the problem that you experienced

below is the error message

PS E:\Practice> npm init @angular myApp
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-myApp - Not found
npm ERR! 404
npm ERR! 404  'create-myApp@*' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lizy1\AppData\Local\npm-cache\_logs\2023-03-10T16_20_24_752Z-debug-0.log

**Comment by abirchoudhury** [comment]
> Which version of npm are you using ?

I was just able to reproduce this, and my 
npm version is v9.6.1, 
node version v18.15.0. 

Here is the content of the log file:
```
0 verbose cli C:\Program Files (x86)\nodejs\node.exe C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@9.6.1
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 4ms
6 timing config:load:builtin Completed in 6ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:C:\Users\maindev\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\maindev\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:setEnvs Completed in 0ms
15 timing config:load Completed in 10ms
16 timing npm:load:configload Completed in 10ms
17 timing npm:load:mkdirpcache Completed in 1ms
18 timing npm:load:mkdirplogs Completed in 0ms
19 verbose title npm init AngularSpringMemeApp
20 verbose argv "init" "AngularSpringMemeApp"
21 timing npm:load:setTitle Completed in 1ms
22 timing config:load:flatten Completed in 4ms
23 timing npm:load:display Completed in 6ms
24 verbose logfile logs-max:10 dir:C:\Users\maindev\AppData\Local\npm-cache\_logs\2023-03-12T00_28_40_819Z-
25 verbose logfile C:\Users\maindev\AppData\Local\npm-cache\_logs\2023-03-12T00_28_40_819Z-debug-0.log
26 timing npm:load:logFile Completed in 3ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 23ms
30 silly logfile start cleaning logs, removing 2 files
31 timing arborist:ctor Completed in 0ms
32 silly logfile done cleaning log files
33 http fetch GET 404 https://registry.npmjs.org/create-AngularSpringMemeApp 436ms (cache skip)
34 http fetch GET 404 https://registry.npmjs.org/create-AngularSpringMemeApp 307ms (cache skip)
35 timing command:init Completed in 764ms
36 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/create-AngularSpringMemeApp - Not found
36 verbose stack     at C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\lib\check-response.js:95:15
36 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
36 verbose stack     at async RegistryFetcher.packument (C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:87:19)
36 verbose stack     at async RegistryFetcher.manifest (C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\registry.js:118:23)
36 verbose stack     at async getManifest (C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:30:22)
36 verbose stack     at async missingFromTree (C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:56:22)
36 verbose stack     at async C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:165:32
36 verbose stack     at async Promise.all (index 0)
36 verbose stack     at async exec (C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\node_modules\libnpmexec\lib\index.js:163:3)
36 verbose stack     at async Init.execCreate (C:\Users\maindev\AppData\Roaming\npm\node_modules\npm\lib\commands\init.js:134:5)
37 verbose statusCode 404
38 verbose pkgid create-AngularSpringMemeApp@*
39 verbose cwd C:\Users\maindev
40 verbose Windows_NT 10.0.22621
41 verbose node v18.15.0
42 verbose npm  v9.6.1
43 error code E404
44 error 404 Not Found - GET https://registry.npmjs.org/create-AngularSpringMemeApp - Not found
45 error 404
46 error 404  'create-AngularSpringMemeApp@*' is not in this registry.
47 error 404 This package name is not valid, because 
48 error 404  1. name can no longer contain capital letters
49 error 404
49 error 404 Note that you can also install from a
50 error 404 tarball, folder, http url, or git url.
51 verbose exit 1
52 timing npm Completed in 878ms
53 verbose code 1
54 error A complete log of this run can be found in:
54 error     C:\Users\maindev\AppData\Local\npm-cache\_logs\2023-03-12T00_28_40_819Z-debug-0.log
```

**Comment by lizhiyu-me** [comment]
> 
npm version 9.5.0
node version 18.15.0

**Comment by lizhiyu-me** [comment]
> Which version of npm are you using ?

npm version 9.5.0
node version 18.15.0

**Comment by alan-agius4** [comment]
This seems to be an issue with NPM 9. I suggest to file a new issue in the NPM issue tracker https://github.com/npm/cli/issues

**Comment by lizhiyu-me** [comment]
> This seems to be an issue with NPM 9. I suggest to file a new issue in the NPM issue tracker https://github.com/npm/cli/issues

ok, but it's in the https://angular.io/quick-start, not friendly to new user.

**Comment by alan-agius4** [comment]
This should no longer be an issue with NPM 9.6.2

**Comment by jimdevsvcs** [comment]
Documenting this for anyone else finding this issue and getting frustrated.

**Don't use PowerShell on windows to run the command `npm init @angular myApp`. Use the windows command prompt.**

I can still reproduce the reported issue in PowerShell 7.3.3 on two machines on Windows 11. Even downgrading NPM to 8.5.0 (the version specified as minimum in the "Your first Angular app")

Windows command prompt ran the command successfully on two different Win11 machines that I tried. That's both an existing machine and a brand new install that only had Node installed from the NodeJS website. 

I had no issues on Mac with homebrew used to install Node.

If others can reproduce this, I think the tutorial should get a note added to advise them to not use powershell.

Tagging @JeanMeche @alan-agius4 FYI in case this continues to pop up.
