### ISSUE TITLE
Error when running 'yarn' in angular-cli (15.x)

### ISSUE THREAD

**Issue by stnor** [angular/angular-cli#25046]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

```
% yarn       
➤ YN0000: ┌ Project validation
➤ YN0057: │ @angular/devkit-repo: The override for '**/ajv-formats/ajv' includes a glob pattern. Glob patterns have been removed since their behaviours don't match what you'd expect. Set the override to 'ajv-formats/ajv' instead.
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0014: │ sauce-connect-proxy@https://saucelabs.com/downloads/sc-4.8.1-linux.tar.gz: Only some patterns can be imported from legacy lockfiles (not "https://saucelabs.com/downloads/sc-4.8.1-linux.tar.gz#9c16682e4c9716734432789884f868212f95f563")
➤ YN0013: │ sauce-connect-proxy@https://saucelabs.com/downloads/sc-4.8.1-linux.tar.gz can't be found in the cache and will be fetched
➤ YN0013: │ @angular/ng-dev@https://github.com/angular/dev-infra-private-ng-dev-builds.git#commit=fa4d4694084d46886ca28fd09768a7df69b
➤ YN0013: │ @angular/build-tooling@https://github.com/angular/dev-infra-private-build-tooling-builds.git#commit=26fc36d66eb747768721c
➤ YN0061: │ protractor@npm:7.0.0 is deprecated: We have news to share - Protractor is deprecated and will reach end-of-life by Summer 2023. To learn more and find out about other options please refer to this post on the Angular blog. Thank you for using and contributing to Protractor. https://goo.gle/state-of-e2e-in-angular
➤ YN0061: │ popper.js@npm:1.16.1 is deprecated: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
➤ YN0032: │ nice-napi@npm:1.0.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @types/browserslist@npm:4.15.0 is deprecated: This is a stub types definition. browserslist provides its own type definitions, so you do not need this installed.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @bazel/typescript@npm:5.7.3 is deprecated: No longer maintained, https://github.com/aspect-build/rules_ts is the recommended replacement
➤ YN0032: │ node-addon-api@npm:3.2.1: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ request@npm:2.88.0 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ puppeteer@npm:18.2.1 is deprecated: < 19.4.0 is no longer supported
➤ YN0061: │ readdir-scoped-modules@npm:1.1.0 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ @npmcli/ci-detect@npm:2.0.0 is deprecated: this package has been deprecated, use `ci-info` instead
➤ YN0001: │ Error: sauce-connect-proxy@https://saucelabs.com/downloads/sc-4.8.1-linux.tar.gz: Manifest not found
    at Function.find (/Users/stnor/.yarn/releases/yarn-3.5.0.cjs:390:32033)
    at async /Users/stnor/.yarn/releases/yarn-3.5.0.cjs:601:11488
    at async Object.t0e (/Users/stnor/.yarn/releases/yarn-3.5.0.cjs:390:11001)
    at async HQ.resolve (/Users/stnor/.yarn/releases/yarn-3.5.0.cjs:601:11449)
    at async xf.resolve (/Users/stnor/.yarn/releases/yarn-3.5.0.cjs:391:1400)
    at async xf.resolve (/Users/stnor/.yarn/releases/yarn-3.5.0.cjs:391:1400)
    at async /Users/stnor/.yarn/releases/yarn-3.5.0.cjs:439:6341
    at async ff (/Users/stnor/.yarn/releases/yarn-3.5.0.cjs:390:11064)
    at async _ (/Users/stnor/.yarn/releases/yarn-3.5.0.cjs:439:6323)
➤ YN0000: └ Completed in 21s 935ms
```

### Minimal Reproduction

Check out the code
Run yarn.

### Exception or Error

```text
YN0001: │ Error: sauce-connect-proxy@https://saucelabs.com/downloads/sc-4.8.1-linux.tar.gz: Manifest not [found[](url)](url)
```

### Your Environment

```text
node v16.16.0
```

**Comment by stnor** [comment]
NVM: Had a yarn config in my home that was picked up...
