### ISSUE TITLE
ng serve fails with "Unexpected end of input" for hoek module

### ISSUE THREAD

**Issue by alcfeoh** [angular/angular-cli#2507]
### Versions.
Node: 4.6.0
NPM: 3.10.8

### Repro steps.
ng init, npm install, then ng serve fails

### The log given by the failure.
ng serve
Error parsing C:\Users\alaich\AppData\Roaming\npm\node_modules\angular-cli\node_
modules\hoek\package.json: Unexpected end of input
SyntaxError: Error parsing C:\Users\alaich\AppData\Roaming\npm\node_modules\angu
lar-cli\node_modules\hoek\package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:81:52)
    at tryPackage (module.js:91:13)
    at Function.Module._findPath (module.js:153:20)
    at Function.Module._resolveFilename (module.js:323:25)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\alaich\AppData\Roaming\npm\node_modules\angu
lar-cli\node_modules\boom\lib\index.js:4:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\alaich\AppData\Roaming\npm\node_modules\angu
lar-cli\node_modules\hawk\lib\index.js:3:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\alaich\AppData\Roaming\npm\node_modules\angu
lar-cli\node_modules\request\request.js:10:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\alaich\AppData\Roaming\npm\node_modules\angu
lar-cli\node_modules\request\index.js:145:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Leek._enqueue (C:\Users\alaich\AppData\Roaming\npm\node_modules\angular-c
li\node_modules\leek\lib\leek.js:60:30)
    at Leek.track (C:\Users\alaich\AppData\Roaming\npm\node_modules\angular-cli\
node_modules\leek\lib\leek.js:87:15)
    at Class.Command.validateAndRun (C:\code-repos\jim-project\node_modules\angu
lar-cli\lib\models\command.js:119:18)
    at C:\code-repos\jim-project\node_modules\angular-cli\lib\cli\cli.js:86:22
    at tryCatch (C:\code-repos\jim-project\node_modules\rsvp\dist\lib\rsvp\-inte
rnal.js:215:12)
    at invokeCallback (C:\code-repos\jim-project\node_modules\rsvp\dist\lib\rsvp
\-internal.js:230:13)
    at C:\code-repos\jim-project\node_modules\rsvp\dist\lib\rsvp\then.js:29:16
    at flush (C:\code-repos\jim-project\node_modules\rsvp\dist\lib\rsvp\asap.js:
85:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by gelliott181** [comment]
The first thing I would do is reinstall your CLI. Hoek is a little ways down the dependency tree, and it mostly looks like your installation has some corruption.

In addition, you purposely meant to do `ng init` (The command when you already have a project started) and not `ng new` (For a new project), correct?

**Comment by alcfeoh** [comment]
I did `ng init` on purpose, yes. I just reinstalled everything and it works. Thanks!
