### ISSUE TITLE
Migration failed No inputs where found in config file v15 to v16

### ISSUE THREAD

**Issue by tiberiuzuld** [angular/angular-cli#25158]
### Command

update

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.0.0

### Description

While updating the library to angular v16 the update command failed.

### Minimal Reproduction

Library: https://github.com/tiberiuzuld/angular-gridster2/tree/15.x
Update command that I run: ` ng update @angular/core @angular/cli @angular-eslint/schematics @angular/material`

### Exception or Error

```text
[error] Error: error TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["src/**/*.spec.ts","src/**/*.d.ts"]' and 'exclude' paths were '["./out-tsc/spec"]'.

    at parseTsconfigFile (D:\projects\angular-gridster2\node_modules\@angular\cdk\schematics\update-tool\utils\parse-tsconfig.js:41:15)
    at UpdateProject.createProgramFromTsconfig (D:\projects\angular-gridster2\node_modules\@angular\cdk\schematics\update-tool\index.js:178:63)
    at runMigrations (D:\projects\angular-gridster2\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:114:57)
    at D:\projects\angular-gridster2\node_modules\@angular\cdk\schematics\ng-update\devkit-migration-rule.js:88:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callRuleAsync (C:\Users\<user>\AppData\Local\Temp\angular-cli-packages-qzfFNs\node_modules\@angular-devkit\schematics\src\rules\call.js:77:18)
```
```


### Your Environment

```text
❯ ng version                                                                         

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.0.0
Node: 18.16.0
Package Manager: npm 9.6.6
OS: win32 x64
                                                               
Angular: 16.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core 
... forms, material, platform-browser, platform-browser-dynamic
... router                                                     

Package                         Version
---------------------------------------------------------      
@angular-devkit/architect       0.1600.0                       
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0                         
@schematics/angular             16.0.0                         
ng-packagr                      16.0.0
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by tiberiuzuld** [comment]
Hmm sorry seems the Angular CDK update fails found there an open issue
https://github.com/angular/components/issues/27055
