### ISSUE TITLE
Builder esbuild "Dnamic require of "./app.module-EYHES6TA.js" is not supported"

### ISSUE THREAD

**Issue by SebastianPodgajny** [angular/angular-cli#25229]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

After trying `@angular-devkit/build-angular:browser-esbuild` I have encountered this error 
```
Unhandled Promise rejection: Dynamic require of "./app.module-3ONOK62U.js" is not supported ; Zone: <root> ; Task: Promise.then ; Value: Error: Dynamic require of "./app.module-3ONOK62U.js" is not supported
    at chunk-4DNOTBYY.js:29:9
    at main.BDBW7TNM.js:15972:89
 ```
 
 source code
 ```ts
 const injector = Injector.create({
  name: 'WebApp bootstrap injector',
  providers,
});

injector.get(WebAppBootstrap).bootstrap(
  providers,
  import('./app/app.module').then(m => m.RtAppModule),
);
```
output
```js
var injector = Injector.create({
  name: "WebApp bootstrap injector",
  providers,
});
injector.get(WebAppBootstrap).bootstrap(
  providers,
  Promise.resolve()
    .then(() => __toESM(__require("./app.module-3ONOK62U.js")))
    .then((m) => m.RtAppModule)
);


```

### Minimal Reproduction

I can't reproduce it with new application, after creating new app using `ng g app` dynamic import works as expected and esbuild doesn't transform `import` into `require`

### Your Environment

```text
Angular CLI: 16.0.1
Node: 16.19.1
Package Manager: yarn 1.21.1
OS: darwin arm64

Angular: 16.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/build-webpack   0.1600.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@angular/cdk                    16.0.0
@ngtools/webpack                16.0.1
@schematics/angular             16.0.1
ng-packagr                      16.0.1
rxjs                            7.6.0
typescript                      5.0.4
webpack                         5.80.0
```

**Comment by alan-agius4** [comment]
@SebastianPodgajny, unfortunately without a reproduction it's hard to tell what is happening here.

**Comment by clydin** [comment]
This is most likely caused by a misconfigured TypeScript configuration for the application which could be causing TypeScript itself to downlevel the dynamic import expression.

**Comment by alan-agius4** [comment]
Closing due to the lack of a reproduction.
