### ISSUE TITLE
polyfills.js crashes with optimization:true and aot: false

### ISSUE THREAD

**Issue by anhallbe** [angular/angular-cli#25369]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15

### Description

After upgrading from 15 to 16, there is an error in `polyfills.js` which causes a crash and the application won't continue to load. This only happens with `"optimization": true` in the builder config (together with `"aot": false`).

The error appears to come from somewhere in `"@angular/compiler"` which for some reason is included in `polyfills.js` after the upgrade. This did not happen before the upgrade.

The error only happens when running the app after a production build with `ng build` or `ng serve --configuration production`.

### Minimal Reproduction

1. Check out [this repo](https://github.com/anhallbe/repro-poly)
2. Run `npm install`
3. Run `ng serve --configuration production`
4. Open http://localhost:4200 (F5 in vscode to start Chrome debugger)
5. Notice that the page is empty
6. Open the browser dev tools and notice the error in `polyfills.js`.

### Exception or Error

```text
Uncaught ReferenceError: Ir is not defined
    at 5988 (VM7 polyfills.js:53:104119)
    at r (runtime.js:1:133)
    at Ce (VM7 polyfills.js:53:293045)
    at VM7 polyfills.js:53:293087
    at a (runtime.js:1:3116)
    at Array.forEach (<anonymous>)
    at runtime.js:1:3273
    at runtime.js:1:3333
    at runtime.js:1:3337
```

### Your Environment

```text
Angular CLI: 16.0.4
Node: 18.16.0
Package Manager: npm 9.6.7
OS: darwin arm64

Angular: 16.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.4
@angular-devkit/build-angular   16.0.4
@angular-devkit/core            16.0.4
@angular-devkit/schematics      16.0.4
@angular/cdk                    16.0.3
@schematics/angular             16.0.4
ng-packagr                      16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else relevant?

When turning on source maps, it looks like `extends ExpressionBase` fails because `ExpressionBase` does not exist. However it does appear in the sourcemaps, just not in the running js:
<img width="680" alt="image" src="https://github.com/angular/angular-cli/assets/4991954/450ad164-4e6d-49f4-a4b9-06d9666d6790">

Also note that I have tried cleaning `.angular` and `node_modules` (with `npm ci`) between builds. Doesn't make any difference.

**UPDATE:** Added [repro code](https://github.com/anhallbe/repro-poly) after noticing that [the .browserslistrc in the project may be a clue as to the cause of the issue](https://github.com/angular/angular-cli/issues/25369#issuecomment-1589128296)

**Comment by anhallbe** [comment]
Update: I managed to reproduce it in a newly created Angular project (16.0.5), with the following addition to the build config:

```json
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "aot": false,
              "buildOptimizer": false,
              "extractLicenses": false,
              "outputHashing": "none",
              "optimization": true,
              "sourceMap": false,
              "vendorChunk": false
            },
```

...and crucially the following `.browserlistrc` (which is not included in newly created projects):

```
# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries

# You can see what browsers were selected by your queries by running:
#   npx browserslist

> 0.5%
last 2 versions
Firefox ESR
not dead
not IE 9-11 # For IE 9-11 support, remove 'not'.
```

With these changes, the problem can be seen when running the app with `ng serve --configuration production`.

When commenting or removing the `.browserlistrc` file, the problem goes away. Not sure if this is a solution, but at least it should give some hint as to what is the cause of the problem.
