### ISSUE TITLE
BUG: Angular 16.1.1 causing problem with babel during compilation

### ISSUE THREAD

**Issue by kukjevov** [angular/angular-cli#25414]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

After updating to angular 16.1.1 application will not compile anymore. Previous version 16.0.4 works just fine.

Minimal reproduction for non working version
`git clone https://github.com/kukjevov/ng-universal-demo`
`cd ng-universal-demo`
`git checkout 2.0`
`npm install --legacy-peer-deps`
`npm run build`

Minimal reproduction for working version
`git clone https://github.com/kukjevov/ng-universal-demo`
`cd ng-universal-demo`
`git checkout 1.0`
`npm install --legacy-peer-deps`
`npm run build`

### Please provide the exception or error you saw

```true
ERROR in ./node_modules/@anglr/notifications/es2020/src/components/notificationMessage/notificationMessage.component.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: D:\git\universal-demo\node_modules\@anglr\notifications\es2020\src\components\notificationMessage\notificationMessage.component.js: `column` must be greater than or equal to 0 (columns start at column 0)
    at exports.originalPositionFor (D:\git\universal-demo\node_modules\@jridgewell\trace-mapping\dist\trace-mapping.umd.js:402:23)
    at SourceMap.mark (D:\git\universal-demo\node_modules\@babel\generator\lib\source-map.js:57:65)
    at Buffer._mark (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:191:60)
    at Buffer._appendChar (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:135:12)
    at Buffer.appendChar (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:104:10)
    at Generator._appendChar (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:205:15)
    at Generator.tokenChar (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:126:10)
    at Generator.rightParens (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:81:10)
    at Generator.CallExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:196:8)
    at Buffer.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:249:5)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ExpressionStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:227:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printSequence (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:476:10)
    at Generator.BlockStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\base.js:51:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printAndIndentOnComments (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:423:10)
    at Generator.IfStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\statements.js:52:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printSequence (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:476:10)
    at Generator.BlockStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\base.js:51:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.FunctionExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\methods.js:109:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ObjectProperty (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\types.js:82:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printList (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:482:10)
    at Generator.ObjectExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\types.js:49:10)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.printJoin (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:404:12)
    at Generator.printList (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:482:10)
    at Generator.CallExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:195:8)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:159:7)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.AssignmentExpression (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:252:8)
    at Buffer.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\buffer.js:249:5)
    at Generator.exactSource (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:163:15)
    at Generator.print (D:\git\universal-demo\node_modules\@babel\generator\lib\printer.js:333:10)
    at Generator.ExpressionStatement (D:\git\universal-demo\node_modules\@babel\generator\lib\generators\expressions.js:227:8)
 @ ./node_modules/@anglr/notifications/es2020/src/index.js 4:0-79 4:0-79
 @ ./app/boot/app.component.ts 27:0-43 179:90-121
 @ ./app/boot/browser-app.module.ts 6:0-47 16:14-26
 @ ./app/main.browser.bootstrap.ts 11:0-61 16:45-61
 @ ./app/main.browser.ts 11:10-4
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 16.1.1
Node: v16.15.0
npm: 8.19.4
Windows: 10.0.19045
```

**Comment by kukjevov** [comment]
Well it looks like error which is some kind of combination with babel or something about source maps during transformation i also reported issue on babel, but i tried to "downgrade" babel and it still did not work.

https://github.com/babel/babel/issues/15712

**Comment by zehavibarak** [comment]
+1

**Comment by bohrasankalp** [comment]
+1

**Comment by kukjevov** [comment]
It is working, it was fixed by `babel` team.

set these as `devDependencies` version 7.22.7 solves the problem for me.

```
        "@babel/core": "7.22.7",
        "@babel/generator": "7.22.7",
```

@alan-agius4 is it possible to set this version also for `@angular-devkit/build-angular` as new dependency version ?
