### ISSUE TITLE
Error: Content and Map of this Source is not available (only size() is supported)

### ISSUE THREAD

**Issue by prajwalkpatil** [angular/angular-cli#25444]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I run my Angular(v16.1.1) project using ng serve -o, I get the following error sometimes(Not always). 
Can someone please clarify this issue. 
![Screenshot 2023-06-24 180939](https://github.com/angular/angular-cli/assets/32927982/506a3774-fd24-460a-8058-378ccdcba373)

Thanks a lot! 

### Minimal Reproduction

ng serve -o

### Exception or Error

```text
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   2.28 MB |
polyfills.js          | polyfills     | 332.98 kB |
styles.css, styles.js | styles        | 231.20 kB |
main.js               | main          | 141.80 kB |
runtime.js            | runtime       |   6.51 kB |

                      | Initial Total |   2.97 MB

Build at: 2023-06-24T12:38:47.643Z - Hash: f7daee3e3b8c4481 - Time: 7248ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


√ Compiled successfully.
C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack-sources\lib\SizeOnlySource.js:16
                return new Error(
                       ^

Error: Content and Map of this Source is not available (only size() is supported)
    at SizeOnlySource._error (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack-sources\lib\SizeOnlySource.js:16:10)
    at SizeOnlySource.buffer (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack-sources\lib\SizeOnlySource.js:30:14)
    at _isSourceEqual (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\util\source.js:21:51)
    at isSourceEqual (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\util\source.js:43:17)
    at Compilation.emitAsset (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\Compilation.js:4252:9)
    at C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\Compiler.js:566:28
    at C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\Compiler.js:1198:17
    at eval (eval at create (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
PS C:\Users\Prajwal Patil\Desktop\twitter\twitter> ng serve -o
⠦ Generating browser application bundles (phase: emitting)...C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack-sources\lib\SizeOnlySource.js:16
                return new Error(
                       ^

Error: Content and Map of this Source is not available (only size() is supported)
    at SizeOnlySource._error (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack-sources\lib\SizeOnlySource.js:16:10)
    at SizeOnlySource.buffer (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack-sources\lib\SizeOnlySource.js:30:14)
    at _isSourceEqual (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\util\source.js:21:51)
    at isSourceEqual (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\util\source.js:43:17)
    at Compilation.emitAsset (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\Compilation.js:4252:9)
    at C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\Compiler.js:566:28
    at C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\webpack\lib\Compiler.js:1198:17
    at eval (eval at create (C:\Users\Prajwal Patil\Desktop\twitter\twitter\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:13:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
```

### Your Environment

```text
Angular CLI: 16.1.1
Node: 16.17.0
Package Manager: npm 9.7.1
OS: win32 x64

Angular: 16.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.1
@angular-devkit/build-angular   16.1.1
@angular-devkit/core            16.1.1
@angular-devkit/schematics      16.1.1
@angular/cli                    16.1.1
@schematics/angular             16.1.1
rxjs                            7.8.1
typescript                      5.1.3
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by prajwalkpatil** [comment]
@alan-agius4 The problem is that, this problem occurs occasionally and not always. I made a new angular app for reproducing this error, the new app runs fine now.

**Comment by alan-agius4** [comment]
Unfortunately without a clear way to reproduce this we will be unable to investigate this issue any further.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.
