### ISSUE TITLE
compilerOptions error while using firebase and angularfire2

### ISSUE THREAD

**Issue by Valindo** [angular/angular-cli#2552]
***\* NG Live Development Server is running on http://localhost:4200. **
 10% building modules 3/7 modules 4 active ...ode_modules/style-loader/addStyles.jsTypeError: Cannot read property 'compilerOptions' of undefined
    at Object.parseJsonConfigFileContent (/Users/valindogodinho/Projects/angularfire/node_modules/typescript/lib/typescript.js:46762:72)
    at readConfigFile (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/instance.ts:335:33)
    at Object.ensureInstance (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/instance.ts:143:5)
    at compiler (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/index.ts:18:18)
    at LOADER_EXECUTION (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at iterateNormalLoaders (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:213:10)
    at /Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:228:3
    at Object.context.callback (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at Object.module.exports (/Users/valindogodinho/Projects/angularfire/node_modules/angular2-template-loader/index.js:32:10)
    at LOADER_EXECUTION (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at /Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at Storage.finished (/Users/valindogodinho/Projects/angularfire/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Users/valindogodinho/Projects/angularfire/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:445:3) 'TypeError: Cannot read property \'compilerOptions\' of undefined\n    at Object.parseJsonConfigFileContent (/Users/valindogodinho/Projects/angularfire/node_modules/typescript/lib/typescript.js:46762:72)\n    at readConfigFile (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/instance.ts:335:33)\n    at Object.ensureInstance (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/instance.ts:143:5)\n    at compiler (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/index.ts:37:20)\n    at Object.loader (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/index.ts:18:18)\n    at LOADER_EXECUTION (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at iterateNormalLoaders (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:213:10)\n    at /Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:228:3\n    at Object.context.callback (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:106:13)\n    at Object.module.exports (/Users/valindogodinho/Projects/angularfire/node_modules/angular2-template-loader/index.js:32:10)\n    at LOADER_EXECUTION (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at /Users/valindogodinho/Projects/angularfire/node_modules/loader-runner/lib/LoaderRunner.js:197:4\n    at Storage.finished (/Users/valindogodinho/Projects/angularfire/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)\n    at /Users/valindogodinho/Projects/angularfire/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:445:3)'
12870ms building modules  
2ms sealing 
0ms optimising 
0ms basic module optimisation 
3ms module optimisation 
0ms advanced module optimisation 
7ms basic chunk optimization  
1ms chunk optimisation 
0ms advanced chunk optimisation 
1ms module and chunk tree optimisation 
13ms module reviving
0ms module order optimisation 
3ms module id optimisation 
2ms chunk reviving 
0ms chunk order optimisation 
3ms chunk id optimisation 
7ms hashing 
0ms module assets processing 
19ms chunk assets processing
1ms additional chunk assets processing 
0ms recording 
0ms additional asset processing 
236ms chunk asset optimisation
47ms asset optimisation
8ms emitting 
Hash: 7f3e9c2e7f1c51cf17d9
Version: webpack 2.1.0-beta.22
Time: 13251ms
            Asset       Size  Chunks             Chunk Names
   main.bundle.js     244 kB    0, 2  [emitted]  main
 styles.bundle.js    10.2 kB    1, 2  [emitted]  styles
        inline.js    5.53 kB       2  [emitted]  inline
         main.map     300 kB    0, 2  [emitted]  main
       styles.map    14.2 kB    1, 2  [emitted]  styles
       inline.map    5.59 kB       2  [emitted]  inline
       index.html  478 bytes          [emitted]  
assets/.npmignore    0 bytes          [emitted]  

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'compilerOptions' of undefined
    at Object.parseJsonConfigFileContent (/Users/valindogodinho/Projects/angularfire/node_modules/typescript/lib/typescript.js:46762:72)
    at readConfigFile (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/instance.ts:335:33)
    at Object.ensureInstance (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/instance.ts:143:5)
    at compiler (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/valindogodinho/Projects/angularfire/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.81 kB       0  
webpack: bundle is now VALID.*\* 

So this is the error I get when I include angularfire2 and firebase
I've done the steps word to word on the angular-cli getting started, am I missing something? or Doing anything wrong? Please help :(

I am using Mac OS 10.11.6
running : 
node version v6.3.1
typescript version 2.0.3
typings version 1.3.3
angular cli `beta.16`

**Comment by Valindo** [comment]
Oh and I tired it on Ubuntu 16.0.4 and Windows 10

**Comment by DanielKucal** [comment]
I get similar errors in ./src/main.browser.ts, ./src/vendor,browser.ts and ./src/polyfills.browser.ts
My stack is angular2-webpack-starter (typescript 2.03),  node v5.11.1 on Win8.1

> Module build failed: TypeError: Cannot read property 'compilerOptions' of undefined
>     at Object.parseJsonConfigFileContent (node_modules\typescript\lib\typescript.js:46813:72)
>     at readConfigFile node_modules\awesome-typescript-loader\src\instance.ts:335:33)
>     at Object.ensureInstance (node_modules\awesome-typescript-loader\src\instance.ts:143:5)
>     at compiler (node_modules\awesome-typescript-loader\src\index.ts:37:20)
>     at Object.loader (node_modules\awesome-typescript-loader\src\index.ts:18:18)
>  @ multi main

**Comment by filipesilva** [comment]
@Valindo can you give me exact repro steps or a repo I can try?

**Comment by AldrichMascarenhas** [comment]
@filipesilva I believe it was this one we were having problems with. https://github.com/Valindo/test

**Comment by Valindo** [comment]
@filipesilva , Here are the steps I followed
1. Installed latest Version of CLI
2. Installed latest Version of typescript
3. Created new app using CLI
4. Added Firebase & angularfire2 via npm
5. Added Angularfire2 module in app.module.ts
6. Imported AngularFire in app.component.ts
7. Started the server via CLI

the repo to reproduce the error is here -> [https://github.com/Valindo/test](url)

**Comment by filipesilva** [comment]
Heya, I beleive this doesn't happen anymore. Let me know if it still does.

**Comment by GiuseppePiscopo** [comment]
Hi there. Just to mention that we just hit this today, for a tiny typo in *tsconfig.json*. At some point I had this:

```json
    ...
    "types": [
      "requirejs"
    ],
  },
  ...
```

with a wrong trailing comma after square bracket, instead of:

```json
    ...
    "types": [
      "requirejs"
    ]
  },
  ...
```

Just that caused a compile time error like:

```
Time: 886ms
   [0] ./src/main.browser.ts 766 bytes {0} [built] [failed] [1 error]
        factory:200ms building:586ms = 786ms
   [1] ./src/vendor-jit.ts 766 bytes {1} [built] [failed] [1 error]
        factory:85ms building:702ms = 787ms

ERROR in ./src/vendor-jit.ts
Module build failed: TypeError: Cannot read property 'compilerOptions' of undefined
    at Object.parseJsonConfigFileContent (D:\my-proj\node_modules\typescript\lib\typescript.js:69190:64)
    at readConfigFile (D:\my-proj\node_modules\awesome-typescript-loader\src\instance.ts:311:33)
    at Object.ensureInstance (D:\my-proj\node_modules\awesome-typescript-loader\src\instance.ts:95:9)
    at compiler (D:\my-proj\node_modules\awesome-typescript-loader\src\index.ts:47:22)
    at Object.loader (D:\my-proj\node_modules\awesome-typescript-loader\src\index.ts:16:18)

ERROR in ./src/main.browser.ts
Module build failed: TypeError: Cannot read property 'compilerOptions' of undefined
    at Object.parseJsonConfigFileContent (D:\my-proj\node_modules\typescript\lib\typescript.js:69190:64)
    at readConfigFile (D:\my-proj\node_modules\awesome-typescript-loader\src\instance.ts:311:33)
    at Object.ensureInstance (D:\my-proj\node_modules\awesome-typescript-loader\src\instance.ts:95:9)
    at compiler (D:\my-proj\node_modules\awesome-typescript-loader\src\index.ts:47:22)
    at Object.loader (D:\my-proj\node_modules\awesome-typescript-loader\src\index.ts:16:18)
```

HTH
