### ISSUE TITLE
ng build -w requires the -o option too?

### ISSUE THREAD

**Issue by DavideViolante** [angular/angular-cli#2555]
Version: angular-cli-beta.16

### Repro steps.
If I run "ng build" it works.
If I run "ng build -o dist -w" it works.
If I run "ng build -w" I get this error:
```
Path must be a string. Received null
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
    at Class.run (F:\Dave\Learning\Angular\Angular2-Full-Stack\node_modules\angular-cli\tasks\build-webpack-watch.js:14:26)
    at Class.run (F:\Dave\Learning\Angular\Angular2-Full-Stack\node_modules\angular-cli\commands\build.js:50:26)
    at Class.<anonymous> (F:\Dave\Learning\Angular\Angular2-Full-Stack\node_modules\angular-cli\lib\models\command.js:152:17)
    at tryCatch (F:\Dave\Learning\Angular\Angular2-Full-Stack\node_modules\rsvp\dist\lib\rsvp\-internal.js:215:12)
    at invokeCallback (F:\Dave\Learning\Angular\Angular2-Full-Stack\node_modules\rsvp\dist\lib\rsvp\-internal.js:230:13)
    at F:\Dave\Learning\Angular\Angular2-Full-Stack\node_modules\rsvp\dist\lib\rsvp\then.js:29:16
    at flush (F:\Dave\Learning\Angular\Angular2-Full-Stack\node_modules\rsvp\dist\lib\rsvp\asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Meligy** [comment]
It shouldn't. It's a big.

It's reported here https://github.com/angular/angular-cli/issues/2511, so for the sake of organisation this issue can be closed as duplicate, and you can subscribe to there other issue to be informed when it's fixed.

**Comment by DavideViolante** [comment]
Sorry, didn't see that. Closing, duplicate here: #2511

**Comment by filipesilva** [comment]
Closing as dupe https://github.com/angular/angular-cli/issues/2511
