### ISSUE TITLE
Dev server crashes with invalid scss

### ISSUE THREAD

**Issue by zip-fa** [angular/angular-cli#25580]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Dev server crashes without explanation when adding these lines of scss:

```
&__line {
    display: flex;
    gap: 0.8rem;

    &:not(:last-child) {
        margin-bottom: 1rem;
    }
}
```

I know it's invalid, but shouldn't we receive error instead of crash?

### Minimal Reproduction

add this to any .scss file in any component:

```
&__line {
    display: flex;
    gap: 0.8rem;

    &:not(:last-child) {
        margin-bottom: 1rem;
    }
}
```

### Exception or Error

```text
node:internal/event_target:916
  process.nextTick(() => { throw err; });
                           ^
TypeError [Error]: Cannot read properties of undefined (reading 'column')
    at convertSourceSpan (node_modules\@angular-devkit\build-angular\src\tools\sass\worker.js:146:30)
    at MessagePort.<anonymous> (node_modules\@angular-devkit\build-angular\src\tools\sass\worker.js:111:27)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
    at Worker.[kOnExit] (node:internal/worker:267:5)
    at Worker.<computed>.onexit (node:internal/worker:198:20)
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.1.3
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 16.1.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.3
@angular-devkit/build-angular   16.1.3
@angular-devkit/core            16.1.3
@angular-devkit/schematics      16.1.3
@nguniversal/builders           16.1.1
@nguniversal/express-engine     16.1.1
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JeanMeche** [comment]
Hi, this has already been reported in #25134

**Comment by TBillaa** [comment]
I am facing this issue when i upgraded my angular from 11 to 16 . 
    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.2.0
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 16.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1602.0
@angular-devkit/build-angular      16.2.0
@angular-devkit/core               16.2.0
@angular-devkit/schematics         16.2.0
@angular/flex-layout               11.0.0-beta.33
@angular/material                  16.1.7
@angular/material-moment-adapter   16.1.7
@schematics/angular                16.2.0
rxjs                               6.6.7
typescript                         4.9.5
zone.js                            0.13.1

my question is if i have 500 files with "&." in .scss files  should i change it everywhere . please help
