### ISSUE TITLE
Issue with custom-webpack configuration with ngx-build-plus builder when usging microsoft/signalR npm library

### ISSUE THREAD

**Issue by RaneeshTK** [angular/angular-cli#25613]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

I get error with module federation plugin with angular 16 when using microsoft/signalR package
The issue happened when upgraded to version 16

### Please provide the exception or error you saw

```true
localhost/:1 Uncaught TypeError: Failed to resolve module specifier "module". Relative references must start with either "/", "./", or "../".
main.ts:2 ChunkLoadError: Loading chunk src_bootstrap_ts failed.
(missing: http://localhost:4250/src_bootstrap_ts.js)
    at __webpack_require__.f.j (main.js:508:28)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (ensure chunk:5:1)
    at 4913 (main.ts:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at main.js:576:88
    at __webpack_require__.O (chunk loaded:23:1)
    at main.js:577:52
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.0
Node:18
OS: windows
```

**Comment by JoostK** [comment]
The Angular team does not support custom builders, please report this issue with the maintainers of `ngx-build-plus`.
