### ISSUE TITLE
'ng lint' fails with angular 2.0.2

### ISSUE THREAD

**Issue by vkniazeu** [angular/angular-cli#2567]
### OS?
> Windows 10 Pro

### Versions.
> angular-cli: 1.0.0-beta.15
node: 6.7.0
os: win32 x64
npm: 3.10.8

### Repro steps.
> Updated from angular 2.0.1 to 2.0.2, ts-node from 1.3.0 to 1.4.0
```ng lint``` fails with the following without listing any errors.
```
> tslint "src/**/*.ts"
Lint errors found in the listed files.
```
### The log given by the failure.
```npm-debug.log``` stack trace:
```
13 info lifecycle abc@0.1.0~lint: Failed to exec lint script
14 verbose stack Error: abc@0.1.0 lint: `tslint "src/**/*.ts"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\...\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\V...\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Mention any other details that might be useful.
Reverting to ```ts-node 1.3.0``` did not help. Still errors out.

**Comment by filipesilva** [comment]
@vkniazeu see https://github.com/angular/angular-cli/issues/867#issuecomment-252525046
