### ISSUE TITLE
AOT Error --- Can't find app.module

### ISSUE THREAD

**Issue by deebloo** [angular/angular-cli#2577]
### OS?

OSX - El Capitan
### Versions.

angular-cli: 1.0.0-beta.17
node: 6.7.0
### Repro steps.

-- Create a clean app with `ng new hello`
-- open src/app/index.ts
-- change line 2 from 

``` TS
export * from './app.module';
```

to 

``` TS
export { AppModule } from './app.module';
```

-- run `ng build --prod --aot`
### The log given by the failure.

ENOENT: no such file or directory, stat '/Users/dannyblue/Documents/projects/ls-dashboard/src/app/app.module'
Error: ENOENT: no such file or directory, stat '/Users/dannyblue/Documents/projects/ls-dashboard/src/app/app.module'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at _symbolImportLookup (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/@ngtools/webpack/src/entry_resolver.js:103:28)
    at Object.resolveEntryModuleFromMain (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/@ngtools/webpack/src/entry_resolver.js:148:18)
    at AotPlugin._setupOptions (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/@ngtools/webpack/src/plugin.js:105:77)
    at new AotPlugin (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/@ngtools/webpack/src/plugin.js:34:14)
    at Object.exports.getWebpackAotConfigPartial (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/models/webpack-build-typescript.js:57:13)
    at new NgCliWebpackConfig (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/models/webpack-config.js:18:42)
    at Class.run (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/tasks/build-webpack.js:17:22)
    at Class.run (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
### Mention any other details that might be useful.

AOT was working fine for me in beta.16
If I change it back to a wild card the app will compile but I have two libs being served from node_modules and while the app will compile I get runtime errors such as:

`Return type of public method from exported class has or is using name 'Observable' from external module "/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/rxjs/Observable" but cannot be named.`

Which also did not happen with beta.15. I will also point out that importing app module directly will also throw the same error at compile time.

``` TS
import { AppModule } from './app/app.module';
```

I am curious if this has something to do with now doing the AOT compilation with a virtual file system.

**Comment by DzmitryShylovich** [comment]
https://github.com/Microsoft/TypeScript/issues/9944

**Comment by deebloo** [comment]
@filipesilva  update. I also cannot go back to beta.16. If I install beta.16 specifically I now get. I am assuming this has to do with one of the internal packages updated for 17?

```bash
webpack_1.NgcWebpackPlugin is not a constructor
TypeError: webpack_1.NgcWebpackPlugin is not a constructor
    at Object.exports.getWebpackAotConfigPartial (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/models/webpack-build-typescript.js:50:13)
    at new NgCliWebpackConfig (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/models/webpack-config.js:18:42)
    at Class.run (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/tasks/build-webpack.js:17:22)
    at Class.run (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by filipesilva** [comment]
@deebloo nuke your local `node_modules`. Semver must have accepted the newer versions.

**Comment by deebloo** [comment]
@filipesilva already tried nuking and clearing the cache. something must be getting stuck somewhere hmmm

**Comment by filipesilva** [comment]
@deebloo local and global? I noticed that the `@ngtools/webpack` (the aot plugin) is just pointing at `latest`, so there might be a version problem in `beta.16`.

**Comment by deebloo** [comment]
@filipesilva yup local and global.

**Comment by jaykhimani** [comment]
Same happens with `ng build` as well.

**Comment by filipesilva** [comment]
@deebloo should be `@ngtools/webpack@1.0.0` I believe.

**Comment by Gamblt** [comment]
```@ngtools/webpack@1.0.0``` didn't help :( 
Error still appears...

**Comment by Gamblt** [comment]
@OnlyByGrace That's it! Works! Thanks a lot!!!

**Comment by filipesilva** [comment]
Another way to repro from https://github.com/angular/angular-cli/issues/2734#issuecomment-254088095

---

If i use index.ts (barel file) it works, if i import main module directly:

 import { MainModule } from './main/main.module'; 
it doesnt.

HOW TO SIMULATE:
1) create new app with ng new
2) change 
```
import { AppModule } from './app'; 
```
to
``` 
import { AppModule } from './app/app.module'; 
```
in main.ts

**Comment by nukuuk** [comment]
modifying the reference to index.ts didn't do the trick for me.  I am still getting (same as deebloo):

$ ng build -prod -aot
webpack_1.NgcWebpackPlugin is not a constructor
TypeError: webpack_1.NgcWebpackPlugin is not a constructor
    at Object.exports.getWebpackAotConfigPartial (C:\my-project\node_modules\angular-cli\models\webpack-build-typescript.js:50:13)
    at new NgCliWebpackConfig (C:\my-project\node_modules\angular-cli\models\webpack-config.js:18:42)
    at Class.exports.default.Task.extend.run (C:\my-project\node_modules\angular-cli\tasks\build-webpack.js:17:22)
    at Class.Command.extend.run (C:\my-project\node_modules\angular-cli\commands\build.js:50:26)
    at Class.<anonymous> (C:\my-project\node_modules\angular-cli\lib\models\command.js:152:17)
    at tryCatch (C:\my-project\node_modules\rsvp\dist\lib\rsvp\-internal.js:215:12)
    at invokeCallback (C:\my-project\node_modules\rsvp\dist\lib\rsvp\-internal.js:230:13)
    at C:\my-project\node_modules\rsvp\dist\lib\rsvp\then.js:29:16
    at flush (C:\my-project\node_modules\rsvp\dist\lib\rsvp\asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by elvirdolic** [comment]
We have the same issue. No matter how we import the main module

**Comment by a5hik** [comment]
Facing the same problem..!

**Comment by elvirdolic** [comment]
I have solved this issue by using the same app.module import logic as it is with a new ng cli project

**Comment by jaykhimani** [comment]
@elvirdolic what do yo mean by `using the same app.module import logic as it is with a new cli project`? Would like to give it a try.

**Comment by elvirdolic** [comment]
index.ts

export * from './app.component';
export * from './app.module';

main.ts

import './polyfills.ts';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { environment } from './environments/environment';
import { AppModule } from './app/';

if (environment.production) {
    enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule);


this worked. Before I imported the AppModule from /app/app.module and this
is not working at the moment

2016-11-03 14:55 GMT+01:00 Jay Khimani <notifications@github.com>:

**Comment by jaykhimani** [comment]
@elvirdolic ah nice. that worked. Thanks.

**Comment by elvirdolic** [comment]
I have read the comment and did the same but what I did was following: import { AppModule } from './app/index' and this is also not working 

strange!

**Comment by mrgoos** [comment]
Hi,
is it working for everyone? I have issues the same as described here.
This is from `main.ts`:
`import { AppModule } from './app/app.module';`
This is from `index.ts`:
`export * from './app.component';
export * from './app.module';`
And `--aot` is not working. Tried `ng serve --aot` and `ng serve --prod --aot`

Running `"version": "1.0.0-beta.19-3"`
Thanks.

**Comment by mrgoos** [comment]
It seems that it DOES work when I change this line in `main.ts`:
`import { AppModule } from './app';`
Is that a good thing to do?

I have other issues but it must be related to be AOT ready, I'm handling it but at least it's not shouting for errors right on the start.

**Comment by hansl** [comment]
Closing this as deprecated. This should be working now.

**Comment by 1cm** [comment]
main.ts > import { AppModule } from './app/app.module.js';

app.module.ts > import { AppComponent }  from './app.component.js';  

just add .js
