### ISSUE TITLE
Angular SSR cannot use ESM modules (reopen from 45062)

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular-cli#25813]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

it was mentioned in https://github.com/angular/angular/issues/45062#issuecomment-1462495085 that it should be fixed in Angular 16, using 16.2 still not working, but with different message

### Please provide a link to a minimal reproduction of the bug

https://github.com/robertIsaac/ng_ssr_esm

### Please provide the exception or error you saw

```true
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'C:\Users\aa.risaac\repos\ng_ssr_esm\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' fil
e extension.
    at 7310 (file:///C:/Users/aa.risaac/repos/ng_ssr_esm/dist/ng_ssr_esm/server/main.js:1:762644)
    at __webpack_require__ (file:///C:/Users/aa.risaac/repos/ng_ssr_esm/dist/ng_ssr_esm/server/main.js:1:2007834)
    at 8154 (file:///C:/Users/aa.risaac/repos/ng_ssr_esm/dist/ng_ssr_esm/server/main.js:1:1110376)
    at __webpack_require__ (file:///C:/Users/aa.risaac/repos/ng_ssr_esm/dist/ng_ssr_esm/server/main.js:1:2007834)
    at file:///C:/Users/aa.risaac/repos/ng_ssr_esm/dist/ng_ssr_esm/server/main.js:1:2010113
    at file:///C:/Users/aa.risaac/repos/ng_ssr_esm/dist/ng_ssr_esm/server/main.js:1:2010229
    at file:///C:/Users/aa.risaac/repos/ng_ssr_esm/dist/ng_ssr_esm/server/main.js:1:2330872
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.0
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.1
Node: 18.16.0
Package Manager: npm 9.7.1
OS: win32 x64

Angular: 16.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.1
@angular-devkit/build-angular   16.2.1
@angular-devkit/core            16.2.1
@angular-devkit/schematics      16.2.1
@angular/cli                    16.2.1
@nguniversal/builders           16.2.0
@nguniversal/express-engine     16.2.0
@schematics/angular             16.2.1
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by alan-agius4** [comment]
ESM is only supported when using the experimental `@angular-devkit/build-angular:application`  esbuild based builder.

**Comment by robertIsaac** [comment]
> ESM is only supported when using the experimental `@angular-devkit/build-angular:application` esbuild based builder. The webpack based builder only output CommonJS.

hi @alan-agius4 
it's still giving me an error, you can check the repo maybe I did something wrong

```
> ng-ssr-esm@0.0.0 serve:ssr
> node dist/ng_ssr_esm/main.server.mjs

file:///C:/Users/aa.risaac/repos/ng_ssr_esm/dist/ng_ssr_esm/main.server.mjs:424
  }`]});let t=e;return t})();var SB=[];var TB={providers:[_B(SB)]};var N6e={providers:[YI()]},CB=IM(TB,N6e);var k6e=()=>zM(EB,CB),$6=k6e;function R6e(){let t=(0,z6.default)(),e=DB(process.cwd(),"dist/n
g_ssr_esm/browser"),n=P6e(DB(e,"index.original.html"))?"index.original.html":"index";return t.engine("html",yP({bootstrap:$6})),t.set("view engine","html"),t.set("views",e),t.get("*.*",z6.default.stati
c(e,{maxAge:"1y"})),t.get("*",(r,i)=>{i.render(n,{req:r,providers:[{provide:S2,useValue:r.baseUrl}]})}),t}function L6e(){let t=process.env.PORT||4e3;R6e().listen(t,()=>{console.log(`Node Express server
 listening on http://localhost:${t}`)})}var AB=__non_webpack_require__.main,MB=AB&&AB.filename||"";(MB===__filename||MB.includes("iisnode"))&&L6e();var IB=$6;var CPe=IB;export{R6e as app,CPe as default
,AE as renderApplication,DE as renderModule,Dv as \u0275SERVER_CONTEXT};



                                               ^

ReferenceError: __non_webpack_require__ is not defined
    at file:///C:/Users/aa.risaac/repos/ng_ssr_esm/dist/ng_ssr_esm/main.server.mjs:424:651
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.0

Process finished with exit code 1
```

**Comment by alan-agius4** [comment]
@robertIsaac, it looks like you are still spawning the webpack based output. I have also updated the reproduction to fix some issues.

**Comment by robertIsaac** [comment]
> @robertIsaac, it looks like you are still spawning the webpack based output. I have also updated the reproduction to fix some issues.

@alan-agius4 I merged it trying it locally, but I think this part is ignoreed
```
              "ssr": {
                "entry": "server.ts"
              },
```
I added console.log at the top of the `main.server.ts` and `server.ts`, I only get `main.server.ts` one logged, then it just quit
```
PS C:\Users\aa.risaac\repos\ng_ssr_esm> node dist/ng_ssr_esm/main.server.mjs
main.server.ts
PS C:\Users\aa.risaac\repos\ng_ssr_esm> 
```

**Comment by robertIsaac** [comment]
I'm confused now, why do we need to provide both `main.server.ts` for the builder.server and `server.ts` for `builder.ssr.entry`
previously we only provided `server.ts` for builder.main
