### ISSUE TITLE
ngDoCheck gets stripped out when using minified bundles

### ISSUE THREAD

**Issue by asaph26** [angular/angular-cli#2588]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64

Upgrading to 1.0.0-beta.17 didn't help either.

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Using ng build --prod results in ngDoCheck is not a function. This is similar to the closed issue https://github.com/angular/angular/issues/6380

### The log given by the failure.
> Normally this include a stack trace and some more information.

```TypeError: self._class51_0_6.ngDoCheck is not a function
    at t._View_t0.detectChangesInternal (t.ngfactory.js:83:43)
    at t.detectChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5055)
    at t.detectViewChildrenChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5613)
    at t._View_t3.detectChangesInternal (t.ngfactory.js:1244:8)
    at t.detectChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5055)
    at t.detectContentChildrenChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5446)
    at t._View_t0.detectChangesInternal (t.ngfactory.js:316:8)
    at t.detectChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5055)
    at t.detectViewChildrenChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5613)
    at t._View_t0.detectChangesInternal (t.ngfactory.js:482:8)
    at t.detectChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5055)
    at t.detectViewChildrenChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5613)
    at t.detectChangesInternal (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5259)
    at t.detectChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5055)
    at t.detectContentChildrenChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5446)
    at t.detectChangesInternal (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5222)
    at t.detectChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5055)
    at t.detectViewChildrenChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5613)
    at t._View_t_Host0.detectChangesInternal (t_Host.ngfactory.js:30:8)
    at t.detectChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1780:5055)
    at t.detectChanges (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1226:1409)
    at http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:666:5293
    at Array.forEach (native)
    at e.tick (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:666:5264)
    at http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:666:3759
    at t.invoke (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1993:13741)
    at Object.onInvoke (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1822:739)
    at t.invoke (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1993:13692)
    at n.run (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1993:11128)
    at t.runInner (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1822:1144)
    at t.run (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:764:2230)
    at Object.next (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:666:3742)
    at e.object.i [as _next] (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:715:557)
    at e.__tryOrUnsub (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:92:6236)
    at e.next (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:92:5582)
    at e._next (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:92:4901)
    at e.next (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:92:4572)
    at e.next (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:197:8901)
    at e.emit (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:715:331)
    at t._checkStable (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:764:1131)
    at t.setMicrotask (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:764:532)
    at Object.onHasTask (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1822:854)
    at t.hasTask (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1993:14867)
    at t._updateTaskCount (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1993:15175)
    at t.invokeTask (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1993:14456)
    at n.runTask (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1993:11730)
    at o (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1993:8347)
    at XMLHttpRequest.invoke (http://localhost:4200/main.2bc6b93b0a81ee32eab8.bundle.js:1993:15523)```

### Mention any other details that might be useful.
* The project was created with an older version of the CLI and is built using the above mentioned version of the CLI
* The project uses Web components
* The development build works. The production build fails
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Using `beta.17` and the following class I was able to get `ngDoCheck` working in both `ng build` and `ng build --prod`:
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
  ngDoCheck() {
    console.log('hello')
  } 
}
```

angular/angular#6380 seems to have been fixed in `beta.16` of angular, what version are you using? And are you sure you're using both local AND global updated versions of the CLI?

**Comment by asaph26** [comment]
@filipesilva: Thank you for your reply.

I have tried the following

**Phase 1:**
* Cloned the master branch of angular-cli and linked it to both the global and local(as mentioned in the docs).
* Removed nods_modules folder completely and ran npm i again. Since I am using bower for Polymer components, did the same with bower as well.

I did a test with the example that you provided in a separate app and it seemed to work. 

**Phase 2:**
* Re-installed angular-cli to the beta.17 version and tried running the same project with no effect.
* Added the `ngDoCheck` method to the app component. The ngDoCheck method gets triggered but the app still fails. Attaching the screenshot for reference.

![consolelog](https://cloud.githubusercontent.com/assets/7847386/19247971/b2f89362-8f2d-11e6-9463-9ff6bc94f055.png)

If it helps I could grant you access to the github repo.

**Comment by filipesilva** [comment]
What version of `@angular/core` are you using?

**Comment by asaph26** [comment]
```
{
  "name": "goalie",
  "version": "0.1.4",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~2.0.0",
    "@angular/compiler": "~2.0.0",
    "@angular/core": "~2.0.0",
    "@angular/forms": "~2.0.0",
    "@angular/http": "~2.0.0",
    "@angular/platform-browser": "~2.0.0",
    "@angular/platform-browser-dynamic": "~2.0.0",
    "@angular/router": "~3.0.0",
    "@vaadin/angular2-polymer": "^1.0.0-beta5",
    "angularfire2": "^2.0.0-beta.5",
    "moment": "^2.15.1",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "^1.0.0-beta.17",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}
```

I can update the version of angular-core to be explicitly set to 2.0.2 and test it as well

**Comment by asaph26** [comment]
@filipesilva No changes after updating to 2.0.2 explicitly as well

**Comment by asaph26** [comment]
Tried on a new machine. That didn't work either. Is there anything that I can do to help figure out whats happening.

**Comment by asaph26** [comment]
@filipesilva After a lot of experimentation, figured the problem.
The actual problem was adding the web-components polyfills as a script in the cli config. I think this has something to do with the order that the scripts are loaded.

Moving that back again to the index.html solved the problem.

I am closing the issue. Maybe we should add something in the documentation.
