### ISSUE TITLE
Angular SSR - ReferenceError : window is not defined

### ISSUE THREAD

**Issue by nblaudez** [angular/angular-cli#25923]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I use Angular for my application. I'm able to build for web and ssr but i have this error when i run : npm run serve:ssr:

"ReferenceError: window is not defined"

### Minimal Reproduction

I have added this code in my server.ts

const mocks = require('mock-browser').delegates.AbstractBrowser;
const MockBrowser = mocks.MockBrowser;
const mock = new MockBrowser();
(global as any).document = mock.getDocument();
(global as any).navigator = mock.getNavigator();
(global as any).window = mock.getWindow();
(global as any).WebSocket = require('ws');
(global as any).XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
Does someone can help me ?

### Exception or Error

```text
ReferenceError: window is not defined
    at 18214 (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:5591033)
    at __webpack_require__ (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:6617819)
    at 12643 (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:5563889)
    at __webpack_require__ (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:6617819)
    at 20783 (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:3091734)
    at __webpack_require__ (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:6617819)
    at 30097 (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:694)
    at __webpack_require__ (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:6617819)
    at 96846 (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:39497)
    at __webpack_require__ (/home/nico/Private/tchat.cafe/front/dist/front/server/main.js:1:6617819)
```

### Your Environment

```text
Angular CLI: 16.0.6
Node: 20.3.0 (Unsupported)
Package Manager: npm 9.6.7
OS: linux x64

Angular: 16.2.3
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.1
@angular-devkit/build-angular   16.2.1
@angular-devkit/core            16.2.1
@angular-devkit/schematics      16.0.6
@angular/cdk                    16.2.2
@angular/cli                    16.0.6
@angular/material               16.2.2
@nguniversal/builders           16.2.0
@nguniversal/express-engine     16.2.0
@schematics/angular             16.0.6
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JeanMeche** [comment]
I see that you've opened a [StackOverflow](https://stackoverflow.com/questions/77200221/angular-ssr-window-is-not-defined), let's continue over there as this is a support request.
