### ISSUE TITLE
AOT -- entry module with default export

### ISSUE THREAD

**Issue by deebloo** [angular/angular-cli#2594]
### OS?
OSX - El Capitan

### Versions.
angular-cli: 1.0.0-beta.17
node: 6.7.0

### Repro steps.
-- Create a clean app with ```ng new hello```
-- open src/app/app.module
-- change
```TS
export class AppModule
```
to
```TS
export default class AppModule
```
-- open src/main.ts
-- change
```TS
import { AppModule } from './app';
``` 
to 
```TS
import AppModule from './app/app.module';;
```
-- run ```ng build --prod --aot```

### The log given by the failure.
Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at _symbolImportLookup (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/@ngtools/webpack/src/entry_resolver.js:90:44)
    at Object.resolveEntryModuleFromMain (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/@ngtools/webpack/src/entry_resolver.js:148:18)
    at AotPlugin._setupOptions (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/@ngtools/webpack/src/plugin.js:105:77)
    at new AotPlugin (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/@ngtools/webpack/src/plugin.js:34:14)
    at Object.exports.getWebpackAotConfigPartial (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/models/webpack-build-typescript.js:57:13)
    at new NgCliWebpackConfig (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/models/webpack-config.js:18:42)
    at Class.run (/Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/tasks/serve-webpack.js:19:22)
    at /Users/dannyblue/Documents/projects/ls-dashboard/node_modules/angular-cli/commands/serve.js:85:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Mention any other details that might be useful.
Not sure if this a valid bug since I am not sure if a default export is statically analyzable by the compiler. Figured I would at least file the bug with steps.

**Comment by rthewhite** [comment]
I'm not using default class any where inside my project and run into the same issue.

**Comment by deebloo** [comment]
@rthewhite can you give steps to reproduce?

**Comment by rthewhite** [comment]
@deebloo was running into this issue in my project and did a quick search through my source files for 'default class', with no results. Might be there is a dependency in my node_modules folder that's causing it. 

Will look into it tomorrow, strip parts and dependencies away in the application to see if i can get it working and can pin point what is causing the problem in my project.

**Comment by filipesilva** [comment]
Turns out this is actually a AoT compiler issue, see https://github.com/angular/angular/issues/11402 instead.
