### ISSUE TITLE
[ESBuild]  [error] RangeError: Set maximum size exceeded

### ISSUE THREAD

**Issue by spock123** [angular/angular-cli#26138]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17-next8 (I think)

### Description

Switching to Esbuild gives this error when trying to build:

[error] RangeError: Set maximum size exceeded

### Minimal Reproduction

`ng build`

### Your Environment

```text
Angular CLI: 17.0.0-rc.1
Node: 18.18.1
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.0-rc.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-date-fns-adapter
... platform-browser, platform-browser-dynamic, router
... service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.1
@angular-devkit/build-angular   17.0.0-rc.1
@angular-devkit/core            17.0.0-rc.1
@angular-devkit/schematics      17.0.0-rc.1
@angular/fire                   7.5.0
@schematics/angular             17.0.0-rc.1
rxjs                            7.5.7
typescript                      5.2.2
zone.js                         0.14.0
```

### Anything else relevant?

Angular.json:

```
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "version": 1,
    "cli": {
        "packageManager": "npm",
        "analytics": "ac59db6d-a680-408f-af50-2623fb62aeae"
    },
    "newProjectRoot": "projects",
    "projects": {
        "totti": {
            "projectType": "application",
            "schematics": {
                "@schematics/angular:component": {
                    "style": "scss",
                    "skipTests": true,
                    "standalone": true,
                    "changeDetection": "OnPush"
                },
                "@schematics/angular:class": {
                    "skipTests": true
                },
                "@schematics/angular:directive": {
                    "skipTests": true,
                    "standalone": true
                },
                "@schematics/angular:guard": {
                    "skipTests": true
                },
                "@schematics/angular:interceptor": {
                    "skipTests": true
                },
                "@schematics/angular:pipe": {
                    "skipTests": true,
                    "standalone": true
                },
                "@schematics/angular:resolver": {
                    "skipTests": true
                },
                "@schematics/angular:service": {
                    "skipTests": true
                }
            },
            "root": "",
            "sourceRoot": "src",
            "prefix": "app",
            "i18n": {
                "sourceLocale": "en-US",
                "locales": {
                    "da": {
                        "translation": "src/locale/messages.da.json"
                    },
                    "en": {
                        "translation": "src/locale/messages.en.json"
                    }
                }
            },
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser-esbuild",
                    "options": {
                        "allowedCommonJsDependencies": [],
                        "outputPath": "dist/totti/",
                        "index": "src/index.html",
                        "main": "src/main.ts",
                        "polyfills": ["zone.js"],
                        "tsConfig": "tsconfig.app.json",
                        "inlineStyleLanguage": "scss",
                        "styles": ["src/styles/index.scss"],
                        "assets": ["src/assets", "src/robots.txt", "src/manifest.json"],
                        "scripts": [],
                        "serviceWorker": true,
                        "ngswConfigPath": "ngsw-config.json",
                        "localize": true,
                        "i18nDuplicateTranslation": "ignore"
                    },
                    "configurations": {
                        "production": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.prod.ts"
                                },
                                {
                                    "replace": "src/app/shared/store/build-specifics/index.ts",
                                    "with": "src/app/shared/store/build-specifics/index.prod.ts"
                                }
                            ],
                            "outputHashing": "all",
                            "vendorChunk": false,
                            "buildOptimizer": true,
                            "serviceWorker": true,
                            "namedChunks": false
                        },
                        "localprod": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.localprod.ts"
                                }
                            ],
                            "outputHashing": "all"
                        },
                        "test": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.test.ts"
                                },
                                {
                                    "replace": "src/app/shared/store/build-specifics/index.ts",
                                    "with": "src/app/shared/store/build-specifics/index.prod.ts"
                                }
                            ],
                            "outputHashing": "all",
                            "vendorChunk": false,
                            "buildOptimizer": true,
                            "serviceWorker": true,
                            "namedChunks": false
                        },
                        "localtest": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.test.ts"
                                }
                            ],
                            "outputHashing": "all"
                        },
                        "development": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.dev.ts"
                                },
                                {
                                    "replace": "src/app/shared/store/build-specifics/index.ts",
                                    "with": "src/app/shared/store/build-specifics/index.prod.ts"
                                }
                            ],
                            "outputHashing": "all",
                            "sourceMap": true,
                            "vendorChunk": false,
                            "buildOptimizer": false,
                            "serviceWorker": true,
                            "namedChunks": false
                        },
                        "local": {
                            "buildOptimizer": false,
                            "optimization": false,
                            "sourceMap": true
                        },
                        "da": {
                            "localize": ["da"]
                        },
                        "en": {
                            "localize": ["en"]
                        }
                    },
                    "defaultConfiguration": "production"
                },
                "serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "configurations": {
                        "production": {
                            "buildTarget": "totti:build:production"
                        },
                        "localprod": {
                            "buildTarget": "totti:build:localprod"
                        },
                        "localtest": {
                            "buildTarget": "totti:build:localtest"
                        },
                        "test": {
                            "buildTarget": "totti:build:test"
                        },
                        "development": {
                            "buildTarget": "totti:build:development"
                        },
                        "local": {
                            "buildTarget": "totti:build:local,en"
                        },

                        "da": {
                            "buildTarget": "totti:build:local,da"
                        },
                        "en": {
                            "buildTarget": "totti:build:local,en"
                        }
                    },
                    "defaultConfiguration": "local"
                },
                "extract-i18n": {
                    "builder": "@angular-devkit/build-angular:extract-i18n",
                    "options": {
                        "buildTarget": "totti:build"
                    }
                },
                "test": {
                    "builder": "@angular-devkit/build-angular:karma",
                    "options": {
                        "polyfills": ["zone.js", "zone.js/testing"],
                        "tsConfig": "tsconfig.spec.json",
                        "inlineStyleLanguage": "scss",
                        "assets": ["src/favicon.ico", "src/assets", "src/manifest.json"],
                        "styles": ["src/styles/index.scss"],
                        "scripts": []
                    }
                },
                "deploy": {
                    "builder": "@angular/fire:deploy",
                    "options": {
                        "prerender": false,
                        "ssr": false,
                        "browserTarget": "totti:build:production",
                        "firebaseProject": "fastorder-dev",
                        "firebaseHostingSite": "fresto-totti-dev"
                    }
                }
            }
        }
    }
}

```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by spock123** [comment]
Hi @alan-agius4 , I'll try to strip down the project to see if I can generate a repro.

To add more info, I also tried adding "budgets" for builds but the error still occurred.

**Comment by spock123** [comment]
The full error message is:

```
An unhandled exception occurred: Set maximum size exceeded
See "/private/var/folders/fm/sdg8xwzx1bd78dgtf26l56b40000gn/T/ng-tGJvQK/angular-errors.log" for further details.
/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/architect/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
            throw err;
            ^

RangeError: Set maximum size exceeded
    at Set.add (<anonymous>)
    at visitor (/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/core/src/json/schema/registry.js:280:65)
    at _visitJsonRecursive (/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/core/src/json/schema/visitor.js:47:19)
    at /Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/core/src/json/schema/visitor.js:56:24
    at doInnerSub (/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/core/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)
    at outerNext (/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/core/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/core/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/core/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at Observable._subscribe (/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/core/node_modules/rxjs/dist/cjs/internal/observable/innerFrom.js:109:24)
    at Observable._trySubscribe (/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/core/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)

Node.js v18.18.1
ERROR: "build:dev-code" exited with 1.
ERROR: "build:dev" exited with 1.
```

**Comment by spock123** [comment]
@alan-agius4  I tried to make a repro, but when I stripped off the application code, it now compiled without errors.

So I guess I have to go back and strip off bit by bit to find the threshold for when the error is thrown. There are no large bundled files in the original build.

**Comment by clydin** [comment]
Does this happen before the build starts or after the build appears to finish?

**Comment by spock123** [comment]
@clydin  After the build has apparently finished. The build takes around 14 secs, then the process just appears to hang for around 20 seconds before the error message comes out.

There is nothing unusual about my structure @alan-agius4 , and I have been using all next-releases without issues. The only version I didn't use with esbuild was RC0 (possibly next8). Before that esbuild worked fine with same project.

**Comment by spock123** [comment]
Console when it happens - it appears the bundles are generated fine before the error occurs.. 


```
... other bundles removed for brevity
chunk-5O6S6MZC.js     | -                   |   1.05 kB |               623 bytes
chunk-WIXVRXUX.js     | index               | 605 bytes |               605 bytes
chunk-IPKIJE2V.js     | index               | 492 bytes |               492 bytes
chunk-DJ6WDPS3.js     | index               | 295 bytes |               295 bytes
chunk-XB7ZS24I.js     | -                   | 118 bytes |               118 bytes

Application bundle generation complete. [11.067 seconds]
An unhandled exception occurred: Set maximum size exceeded
See "/private/var/folders/fm/sdg8xwzx1bd78dgtf26l56b40000gn/T/ng-jD8b8N/angular-errors.log" for further details.
/Users/spock/projects/fresto/apps/totti/node_modules/@angular-devkit/architect/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
            throw err;
            ^

RangeError: Set maximum size exceeded
```

**Comment by spock123** [comment]
@clydin  Damn you're fast, I'm still iterating my repro here to find where it breaks :) .. impressive
