### ISSUE TITLE
application builder: I18nPluralPipe Missing locale data

### ISSUE THREAD

**Issue by zip-fa** [angular/angular-cli#26147]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v16 with webpack builder

### Description

Hi. I18nPluralPipe started to give errors without `registerLocaleData` call on application builder.
I attached two versions of angular.json in my repro-repo: webpack-based and with application builder - they behave differently.
Does angular include automatically locale data for each locale under the hood in webpack builder?

With explicit register of localeData, issue resolves:

```
import { registerLocaleData } from '@angular/common';

import localeUk from '@angular/common/locales/uk';

constructor() {
    registerLocaleData(localeUk);
  }
```

So my question is:
Should we load a bunch of locale datas (19 in my project) with esbuild-based builders and register them one-by-one?

### Minimal Reproduction

https://github.com/zip-fa/ng17-plural-bug

### Exception or Error

```text
ERROR RuntimeError: NG0701: Missing locale data for the locale "uk".
    at findLocaleData (\src\i18n\locale_data_api.ts:66:9)
    at getLocalePluralCase (\src\i18n\locale_data_api.ts:94:16)
    at NgLocaleLocalization.getPluralCategory (\packages\common\src\i18n\localization.ts:63:20)
    at getPluralCategory (C:\Users\ikpoc\packages\common\src\i18n\localization.ts:38:24)
    at I18nPluralPipe.transform (C:\Users\ikpoc\packages\common\src\pipes\i18n_plural_pipe.ts:54:17)
    at pureFunction2Internal (\src\render3\pure_function.ts:337:28)
    at Proxy.ɵɵpipeBind2 (\src\render3\pipe.ts:191:7)
    at ɵɵelementStart (C:\src\app\app.component.html:1:6)
    at executeTemplate (\src\render3\instructions\shared.ts:279:7)
    at refreshView (\src\render3\instructions\change_detection.ts:153:7) {
  code: 701
```

### Your Environment

```text
Angular CLI: 17.0.0-rc.1
Node: 18.18.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.1
@angular-devkit/build-angular   17.0.0-rc.1
@angular-devkit/core            17.0.0-rc.1
@angular-devkit/schematics      17.0.0-rc.1
@schematics/angular             17.0.0-rc.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.1
```

**Comment by alan-agius4** [comment]
Thanks for opening the issue.  Lucky this has already been fixed via https://github.com/angular/angular-cli/pull/26137
