### ISSUE TITLE
webpack plugin & AOT: Error: undefined, resolving symbol ApplicationModule 

### ISSUE THREAD

**Issue by dhardtke** [angular/angular-cli#2622]
### OS?
Windows 10

### Versions.
- typescript 2.0.3
- webpack 2.1.0-beta.25
- @angular/compiler-cli 0.6.4
- @angular/platform-server 2.0.2
- @ngtools/webpack 1.1.0

### Repro steps.
This is a repo that I created manually by following the quick start guide and then adding webpack.
For config files see below.

### The log given by the failure.
> webpack --config config/webpack.prod.js --progress --profile --bail
```
Error: undefined, resolving symbol ApplicationModule in C:/Users/nick/PHPStorm Projects/angular.hardtke.me/node_modules/@angular/core/src/application_module.d.ts
    at simplifyInContext (node_modules\@angular\compiler-cli\src\static_reflector.js:472:23)
    at StaticReflector.simplify (node_modules\@angular\compiler-cli\src\static_reflector.js:475:22)
    at StaticReflector.annotations (node_modules\@angular\compiler-cli\src\static_reflector.js:61:36)
    at _loop_1 (node_modules\@angular\compiler-cli\src\codegen.js:53:54)
    at CodeGenerator.readFileMetadata (node_modules\@angular\compiler-cli\src\codegen.js:66:13)
    at node_modules\@angular\compiler-cli\src\codegen.js:100:74
    at Array.map (native)
    at CodeGenerator.codegen (node_modules\@angular\compiler-cli\src\codegen.js:100:35)
    at AotPlugin._make (node_modules\@ngtools\webpack\src\plugin.js:189:43)
    at Compiler.<anonymous> (node_modules\@ngtools\webpack\src\plugin.js:154:75)
    at Compiler.applyPluginsParallel (node_modules\tapable\lib\Tapable.js:156:14)
    at Compiler.<anonymous> (node_modules\webpack\lib\Compiler.js:463:8)
    at Compiler.applyPluginsAsync (node_modules\tapable\lib\Tapable.js:73:70)
    at Compiler.compile (node_modules\webpack\lib\Compiler.js:456:7)
    at Compiler.<anonymous> (node_modules\webpack\lib\Compiler.js:219:10)
    at Compiler.readRecords (node_modules\webpack\lib\Compiler.js:367:10)
    at Compiler.<anonymous> (node_modules\webpack\lib\Compiler.js:216:9)
    at next (node_modules\tapable\lib\Tapable.js:81:11)
    at Compiler.<anonymous> (node_modules\webpack\lib\CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (node_modules\tapable\lib\Tapable.js:85:13)
    at Compiler.<anonymous> (node_modules\webpack\lib\Compiler.js:213:8)
    at next (node_modules\tapable\lib\Tapable.js:81:11)
    at Compiler.<anonymous> (node_modules\webpack\lib\node\NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (node_modules\tapable\lib\Tapable.js:85:13)
    at Compiler.run (node_modules\webpack\lib\Compiler.js:210:7)
    at processOptions (node_modules\webpack\bin\webpack.js:335:12)
    at Object.<anonymous> (node_modules\webpack\bin\webpack.js:339:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

### Mention any other details that might be useful.
tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "rootDir": "."
  },
  "angularCompilerOptions": {
    "entryModule": "app/app.module#AppModule"
  }
}
```
webpack.prod.js:
```js
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const helpers = require("./helpers");
const ContextReplacementPlugin = require("webpack/lib/ContextReplacementPlugin");
const AotPlugin = require("@ngtools/webpack/src/plugin").AotPlugin;

module.exports = {
    entry: {
        "app": "./app/main.ts"
    },

    resolve: {
        extensions: [".ts", ".js", ".json"],
        modules: [helpers.root("app"), "node_modules"]
    },

    module: {
        loaders: [
            {
                test:    /\.ts$/,
                loaders: ["@ngtools/webpack"] // "angular2-router-loader?aot=true&genDir=compiled"
            }
        ]
    },

    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: ["app", "vendor", "polyfills"]
        }),
        new ContextReplacementPlugin(
            // The (\\|\/) piece accounts for path separators in *nix and Windows
            /angular(\\|\/)core(\\|\/)(esm(\\|\/)src|src)(\\|\/)linker/,
            helpers.root("app") // location of your src
        ),
        new HtmlWebpackPlugin({
            template:       "./app/index.tpl.html",
            filename:       "../index.html",
            chunksSortMode: "dependency"
        }),
        new AotPlugin({
            tsConfigPath: "tsconfig.json",
            typeChecking: false
        })
    ]
};
```

Invoking `ngc` from the command line works properly, but I want to integrate AOT compiling into webpack for several reasons.

**Comment by filipesilva** [comment]
@dhardtke did you follow https://github.com/angular/angular-cli/blob/master/packages/webpack/README.md? You don't seem to have `entryModule` specified.

@Foxandxss have you ran into a similar problem?

**Comment by dhardtke** [comment]
I do have `entryModule` specified.
> `entryModule`. Optional if specified in `angularCompilerOptions`

I got it working by re-writing my webpack config, but I don't know which option was responsible for this.

**Comment by Foxandxss** [comment]
No, I am still in the investigating part so I haven't try that yet.

**Comment by filipesilva** [comment]
@dhardtke ah I see now. Hm... I can't help you too much now, but I can point you at how we use it currently and maybe that'll help: https://github.com/angular/angular-cli/blob/master/packages/angular-cli/models/webpack-build-typescript.ts

**Comment by dhardtke** [comment]
Like I said I got it working, I changed a few things in the webpack config and it's working now. Don't know what it was but for now I am closing this issue.

**Comment by qvazzler** [comment]
AoTPlugin is not working for me using webpack either. It does not generate the ngfactory files.

My webpack.config.aot.js
```
            new ngtools.AotPlugin({
                tsConfigPath: './tsconfig.aot.json',
                baseDir: path.resolve(__dirname, ''),
                //entryModule: "./app/www/starter/app/main#MainModule"
                entryModule: path.join(__dirname, 'app', 'www', 'starter', 'app', 'main') + '#MainModule'
            }),
...
        module: {
            rules: [
                {
                    test: /\.ts$/,
                    //exclude: [ /.*\.ngfactory\..*/ ],
                    use: ["@ngtools/webpack"],
                    //use: [ "awesome-typescript?tsconfig=tsconfig.aot.json", "angular2-template" ]
                },
```

my tsconfig.aot.json

```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    //Major, Same
    "sourceRoot": "app",
    "typeRoots": [ "./node_modules/@types" ],
    "types": [ "chrome", "jquery", "filewriter", "filesystem" ],
    //Minor, Same
    "declaration": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "pretty": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitUseStrict": false,
    "noFallthroughCasesInSwitch": true
  },
  "angularCompilerOptions": {
    "debug": true,
    "skipMetadataEmit": true
    //"genDir": "suchwow"
  },
  "compileOnSave": false,
  "files": [
    "typings/index.d.ts",
    "app/www/starter/app/bootstrap.aot.ts",
    "app/www/starter/app/main.ts"
  ],
  "exclude": [
    "node_modules",
    "modded_node_modules",
    "build"
  ]
}
```

Not sure what to do. ngc cli command works, but not the above..

I'm using `"@ngtools/webpack": "^1.1.0"`.
