### ISSUE TITLE
Confusing error reporting when a component isn't exported

### ISSUE THREAD

**Issue by edbzn** [angular/angular-cli#26233]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi, 

I'm using `@angular-devkit/build-angular@17.0.0-rc.3` and the application builder to serve my application. I noticed an error not properly reported when I was trying to import a component (not exported) into another component.

```ts
@Component({...}) 
class TestComp {} // No export

@Component({ imports: [TestComp], ... })
export class AnotherComp {}
```

This results in the following compilation error: 

```
✘ [ERROR] [object Object] [plugin angular-compiler]

  This error came from the "onStart" callback registered here:

    node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compiler-plugin.js:89:18:
      89 │             build.onStart(async () => {
         ╵                   ~~~~~~~

    at setup (xxx/node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compiler-plugin.js:89:19)
    at async handlePlugins (xxx/node_modules/esbuild/lib/main.js:1340:9)


✘ [ERROR] File 'xxx/src/main.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.


Application bundle generation failed. [1.568 seconds]
Watch mode enabled. Watching for file changes...
```

The reported error does not help to find the cause. 

### Minimal Reproduction

In the same file, declare 2 components, component A has no `export` keyword but is declared into component B's `imports` array.

### Your Environment

```text
Angular CLI: 17.0.0-rc.3
Node: 18.18.2
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 17.0.0-rc.2
... common, compiler, compiler-cli, core, forms
... platform-browser

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.3
@angular-devkit/build-angular   17.0.0-rc.3
@angular-devkit/core            17.0.0-rc.3
@angular-devkit/schematics      17.0.0-rc.3
@angular/cli                    17.0.0-rc.3
@angular/ssr                    17.0.0-rc.3
@schematics/angular             17.0.0-rc.3
rxjs                            7.4.0
typescript                      5.2.2
```

**Comment by clydin** [comment]
Can you provide a project with a minimal reproduction demonstrating the problem?
We are unfortunately unable to reproduce the problem as described.

**Comment by edbzn** [comment]
I'm not able to reproduce in a fresh new project, sorry for the noise. Closing.
