### ISSUE TITLE
Adding providers while vite dev server is running fails to rebuild

### ISSUE THREAD

**Issue by yharaskrik** [angular/angular-cli#26234]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When serving a fresh angular application with the application builder and adding something to the providers array in appConfig the server fails to rebuild (I am sure its not limited to the providers array thats just where I encountered it)

### Minimal Reproduction

https://github.com/yharaskrik/angular-17-ssr-application-builder

`yarn ng serve`

Add `provideStore()` into the appConfig

### Exception or Error

```text
Application bundle generation complete. [0.089 seconds]

Initial Chunk Files | Names | Raw Size
main.js             | main  | 33.98 kB | 

Unchanged output files: 2
Application bundle generation complete. [0.343 seconds]
Reloading client(s)...
6:00:29 AM [vite] Error when evaluating SSR module /@fs/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/rxjs/dist/cjs/index.js?v=22e4b6c6:
|- ReferenceError: exports is not defined
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/rxjs/dist/cjs/index.js?v=22e4b6c6:14:23)
    at instantiateModule (file:///Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)

6:00:29 AM [vite] Error when evaluating SSR module /@fs/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/@ngrx/store/fesm2022/ngrx-store.mjs?v=22e4b6c6: failed to import "/@fs/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/rxjs/dist/cjs/index.js?v=22e4b6c6"
|- ReferenceError: exports is not defined
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/rxjs/dist/cjs/index.js?v=22e4b6c6:14:23)
    at instantiateModule (file:///Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)

6:00:29 AM [vite] Error when evaluating SSR module /main.server.mjs: failed to import "/@fs/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/@ngrx/store/fesm2022/ngrx-store.mjs?v=22e4b6c6"
|- ReferenceError: exports is not defined
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/rxjs/dist/cjs/index.js?v=22e4b6c6:14:23)
    at instantiateModule (file:///Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)

6:00:29 AM [vite] Internal server error: exports is not defined
      at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/rxjs/dist/cjs/index.js?v=22e4b6c6:14:23)
      at instantiateModule (file:///Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:15)
```

### Your Environment

```text
Angular CLI: 17.0.0-rc.3
Node: 18.18.2
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.0-rc.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0-next.0+sha-fdee8b7
@angular-devkit/build-angular   17.1.0-next.0+sha-fdee8b7
@angular-devkit/core            17.0.0-rc.3
@angular-devkit/schematics      17.0.0-rc.3
@angular/cli                    17.0.0-rc.3
@angular/ssr                    17.0.0-rc.3
@schematics/angular             17.0.0-rc.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/26247
