### ISSUE TITLE
Fetching Firebase RemoteConfig with AngularFire breaks SSR

### ISSUE THREAD

**Issue by yharaskrik** [angular/angular-cli#26282]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Including RemoteConfig from AngularFire and then calling the fetchAndActivate method breaks the SSR server

### Minimal Reproduction

https://github.com/yharaskrik/angular-17-ssr-application-builder/tree/jaybell/compiler-wwarnings

### Exception or Error

```text
ERROR TypeError: Cannot read properties of null (reading 'settings')
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/@firebase/remote-config/dist/esm/index.esm2017.js:237:5)
    at Generator.next (<anonymous>)
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/chunk-OGTRFHQR.mjs:83:61)
    at ZoneAwarePromise (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/zone.js/fesm2015/zone-node.js:1345:17)
    at Module.__async (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/chunk-OGTRFHQR.mjs:67:10)
    at fetchConfig (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/@firebase/remote-config/dist/esm/index.esm2017.js:230:27)
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/@firebase/remote-config/dist/esm/index.esm2017.js:1171:1)
    at Generator.next (<anonymous>)
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/chunk-OGTRFHQR.mjs:83:61)
    at ZoneAwarePromise (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/zone.js/fesm2015/zone-node.js:1345:17)
ERROR TypeError: Cannot read properties of null (reading 'settings')
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/@firebase/remote-config/dist/esm/index.esm2017.js:237:5)
    at Generator.next (<anonymous>)
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/chunk-OGTRFHQR.mjs:83:61)
    at ZoneAwarePromise (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/zone.js/fesm2015/zone-node.js:1345:17)
    at Module.__async (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/chunk-OGTRFHQR.mjs:67:10)
    at fetchConfig (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/@firebase/remote-config/dist/esm/index.esm2017.js:230:27)
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/@firebase/remote-config/dist/esm/index.esm2017.js:1171:1)
    at Generator.next (<anonymous>)
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/chunk-OGTRFHQR.mjs:83:61)
    at ZoneAwarePromise (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/zone.js/fesm2015/zone-node.js:1345:17)
ERROR TypeError: Cannot read properties of null (reading 'settings')
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/@firebase/remote-config/dist/esm/index.esm2017.js:237:5)
    at Generator.next (<anonymous>)
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/chunk-OGTRFHQR.mjs:83:61)
    at ZoneAwarePromise (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/zone.js/fesm2015/zone-node.js:1345:17)
    at Module.__async (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/chunk-OGTRFHQR.mjs:67:10)
    at fetchConfig (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/@firebase/remote-config/dist/esm/index.esm2017.js:230:27)
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/@firebase/remote-config/dist/esm/index.esm2017.js:1171:1)
    at Generator.next (<anonymous>)
    at eval (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/chunk-OGTRFHQR.mjs:83:61)
    at ZoneAwarePromise (/Users/jaybell/WebstormProjects/angular-17-ssr-application-builder/.angular/vite-root/angular-17-ssr-application-builder/node_modules/zone.js/fesm2015/zone-node.js:1345:17)
```

### Your Environment

```text
Angular CLI: 17.0.0-rc.5
Node: 18.18.2
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.0-rc.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.5
@angular-devkit/build-angular   17.0.0-rc.5
@angular-devkit/core            17.0.0-rc.5
@angular-devkit/schematics      17.0.0-rc.3
@angular/cli                    17.0.0-rc.5
@angular/fire                   17.0.0-next.0
@angular/ssr                    17.0.0-rc.5
@schematics/angular             17.0.0-rc.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

In the demo repo it does not crash the server, just throws the error, in our repo the server crashes with native go errors related to esbuild

**Comment by alan-agius4** [comment]
@yharaskrik, looks like in the reproduction you have some missing files and I am unable to compile the app.

**Comment by yharaskrik** [comment]
> @yharaskrik, looks like in the reproduction you have some missing files and I am unable to compile the app.

Oh probably a firebase configuration, let me push that up for you, just an empty fireabse project anyway

**Comment by yharaskrik** [comment]
Pushed.

**Comment by alan-agius4** [comment]
This appears to be coming from Firebase as the config is being set to null internally as part of this check.

https://github.com/angular/angularfire/blob/1350920c37233b19864e4e5522878eb644a1e132/src/remote-config/remote-config.module.ts#L22

**Comment by yharaskrik** [comment]
> This appears to be coming from Firebase as the config is being set to null internally as part of this check.
> 
> https://github.com/angular/angularfire/blob/1350920c37233b19864e4e5522878eb644a1e132/src/remote-config/remote-config.module.ts#L22

So it is likely not supported in SSR and thats why it works on the client. So conditionally fetchAndActivate only in the browser then?

**Comment by alan-agius4** [comment]
Yes, likely. I suggest you fill an issue with firebase to see why node.js is not supported.
