### ISSUE TITLE
extract-i18n crashes with 'unknown Statement of type "ForOfStatement"' message using new application builder

### ISSUE THREAD

**Issue by wartab** [angular/angular-cli#26303]
### Command

extract-i18n

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Since moving to Angular 17 with `@angular-devkit/build-angular:application`, using `ng extract-i18n` fails with an error and crucially doesn't perform the translation extraction. 

**Note that the problem doesn't happen when using `ng serve` and `ng build`.**

We used to have this problem before occasionally, but removing newly added for-of loops in the TypeScript code was generally sufficient to address the problem. I tried to remove ALL for-of loops of the project, but this time, it wasn't sufficient. Note that using the old builder, even in Angular 17, it works.

### Minimal Reproduction

The project is fairly big and I can't reproduce it on a smaller scale project. I can privately provide our repository if needed.

### Exception or Error

```text
C:\Users\Vincent Lycoops\xxx>ng extract-i18n
/ Building...▲ [WARNING] Angular Material themes should be created from a map containing the keys "color", "typography", and "density". The color value should be a map containing the palette values for "primary", "accent", and "warn". See https://material.angular.io/guide/theming for more information. [plugin angular-sass]

    angular:styles/global:styles:1:8:
      1 │ @import 'src/styles/styles.scss';
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~



Initial Chunk Files     | Names         |  Raw Size
main.js                 | main          |  21.15 MB |
styles.css              | styles        | 273.84 kB |
polyfills.js            | polyfills     |  88.47 kB |
scripts.js              | scripts       |  63.94 kB |
chunk-5ZKAWRYO.js       | -             |   5.34 kB |
chunk-MLXQ3P24.js       | -             | 614 bytes |

                        | Initial Total |  21.58 MB

Lazy Chunk Files        | Names         |  Raw Size
index.es-CDPKYHKP.js    | index-es      | 396.07 kB |
html2canvas-DXYPLDCZ.js | html2canvas   | 389.95 kB |
purify-JD2LSLOT.js      | purify        |  50.28 kB |

Application bundle generation complete. [40.436 seconds]
An unhandled exception occurred: C:\Users\Vincent Lycoops\xxx\main.js: unknown Statement of type "ForOfStatement"
See "C:\Users\VINCEN~1\AppData\Local\Temp\ng-3h3yVc\angular-errors.log" for further details.
```

### Your Environment

```text
C:\Users\Vincent Lycoops\horus-mobile3>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.0
Node: 18.16.0
Package Manager: npm 9.6.4
OS: win32 x64

Angular: 17.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cdk                    17.0.0
@angular/cli                    17.0.0
@angular/material               17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

Happens on both Windows and Linux.

**Comment by JoostK** [comment]
Do you happen to have a stacktrace? Notice the `See "C:\Users\VINCEN~1\AppData\Local\Temp\ng-3h3yVc\angular-errors.log" for further details.`, which potentially contains more information.

This may be an issue in `@angular/localize`, but I cant' tell for certain without a repro.

**Comment by wartab** [comment]
My apologies, I meant to copy the file, too, but forgot
```
[error] Error: C:\Users\Vincent\xxx\main.js: unknown Statement of type "ForOfStatement"
    at Ep.explodeStatement (C:\Users\Vincent\xxx\node_modules\regenerator-transform\lib\emit.js:546:13)
    at C:\Users\Vincent\xxx\node_modules\regenerator-transform\lib\emit.js:310:12
    at Array.forEach (<anonymous>)
    at Ep.explodeStatement (C:\Users\Vincent\xxx\node_modules\regenerator-transform\lib\emit.js:309:22)
    at Ep.explode (C:\Users\Vincent\xxx\node_modules\regenerator-transform\lib\emit.js:273:40)
    at PluginPass.<anonymous> (C:\Users\Vincent\xxx\node_modules\regenerator-transform\lib\visit.js:98:17)
    at PluginPass.<anonymous> (C:\Users\Vincent\xxx\node_modules\regenerator-transform\lib\util.js:25:17)
    at newFn (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\visitors.js:159:14)
    at NodePath._call (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:46:20)
    at NodePath.call (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:36:17)
    at NodePath.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:90:8)
    at TraversalContext.visitQueue (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:107:19)
    at traverseNode (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitSingle (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\context.js:109:19)
    at traverseNode (C:\Users\Vincent\xxx\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
```

**Comment by wartab** [comment]
Regarding the reproduction, as stated above, I can privately provide the repository. Can't share it publicly, however, or my boss won't be happy :D

**Comment by JoostK** [comment]
Okay, that seems like the `regenerator-transform` Babel plugin is active and dealing with a for-of statement, which [apparently it doesn't support](https://github.com/facebook/regenerator/issues/229) since it assumes that those statements have _also_ been downleveled.

**Comment by wartab** [comment]
Wow, thanks for the insight. I see, the .babelrc file was added to our project after an update to Angular 9.1. I am not really sure why it's there and what it does and if it's still needed. It contains:
```
{
    "plugins": ["@babel/plugin-transform-regenerator"]
}
```

Removing it doesn't seem to break anything and extracting translations works again. Thanks a lot.
My assumption is that it's safe to close this issue, then, sorry for the time waste.
