### ISSUE TITLE
npm install -g angular-cli gives error: not found: git

### ISSUE THREAD

**Issue by RedFour** [angular/angular-cli#2633]
I was just trying to update to the latest cli. I ran the following and got this "not found: git" error. I've never encountered this error before. I'm using Windows 10, node v6.7.0, npm v3.10.8. I was using angular-cli beta 15 before this. 

I tried to fix the issue by installing git, but it still gave the same error message.

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest

```
npm install -g angular-cli
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  webpack/compression-webpack-plugin#7e55907cd54a2e91b96d25a660acc6a2a6453f54 resetting remote C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/webpack/compression-webpack-plugin.git C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe: undefined
npm ERR! git clone --template=C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/webpack/compression-webpack-plugin.git C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-ec76b2fe: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  webpack/compression-webpack-plugin#7e55907cd54a2e91b96d25a660acc6a2a6453f54 resetting remote C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/webpack/compression-webpack-plugin.git C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3: undefined
npm ERR! git clone --template=C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/webpack/compression-webpack-plugin.git C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-541c96f3: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  webpack/compression-webpack-plugin#7e55907cd54a2e91b96d25a660acc6a2a6453f54 resetting remote C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Users\Dan\AppData\Roaming\npm\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: undefined
npm ERR! git clone --template=C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\Dan\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: undefined
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GitHub\npm-debug.log
```

**Comment by Equinox** [comment]
Are you able to confirm Git's in your PATH, though?

Might work after a restart.

**Comment by RedFour** [comment]
I added git to my PATH, and the angular-cli install looks to be working now. 

Why do I need to manually install git now? I don't see it as part of the installation prerequisites. I was able to install angular-cli beta 15 fine before this.

**Comment by gelliott181** [comment]
Git is a requirement for NPM's `Git Repo as a Dependency` feature. We currently use this to pull an unreleased (On NPM) change (Webpack compression plugin, I believe). When that change is released to NPM git won't be needed again.
