### ISSUE TITLE
cannot run the default schematics project

### ISSUE THREAD

**Issue by its-dibo** [angular/angular-cli#26352]
### Command

other

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

cannot run the default schematics project

I just created a new schematics project
```
schematics blank --name=test
```
and then run it without any modifications
```
cd test
 schematics .:test
```
but this error is occured
```
Error: Cannot find module 'test/src/test/index'
```

### Minimal Reproduction

I created a [minimal reproduction](https://github.com/its-dibo/issue-schematics) with a detailed description

### Exception or Error

```text
`Error: Cannot find module 'test/src/test/index'`
```

### Your Environment

```text
node: v20.9.0
@angular-devkit/schematics-cli: latest (globally)
```

**Comment by its-dibo** [comment]
also tested on nodejs v18 with the same error
but with node v14 a new error is occured
```
/home/dibo/.nvm/versions/node/v14.21.3/lib/node_modules/@angular-devkit/schematics-cli/bin/schematics.js:449
    load ??= new Function('modulePath', `return import(modulePath);`);
         ^^^

SyntaxError: Unexpected token '??='
```

**Comment by its-dibo** [comment]
also, tested on windows with the same error

**Comment by JeanMeche** [comment]
Did you build the schematic before running it ? (`npm run build`)

**Comment by its-dibo** [comment]
> Did you build the schematic before running it

it worked, but when I made some smallchanges to tsconfig.json it doesn't work

1- in tsconfig, set `outDir` to "dist"
2- copy src/collection.json into dist/collection.json
3- replace `schematics .:test` with `schematics ./dist:test` or `cd dist && schematics .:test`

a new error occured
```
Error: Collection "test-schematics/dist" cannot be resolved.
    at NodeModulesEngineHost.resolve (node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:86:19)
    at NodeModulesEngineHost._resolveCollectionPath (node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:91:37)
    at NodeModulesEngineHost.createCollectionDescription (node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:116:27)
    at SchematicEngine._createCollectionDescription (node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:167:40)
    at SchematicEngine.createCollection (node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/src/engine/engine.js:160:43)
    at NodeWorkflow.execute (node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/src/workflow/base.js:107:41)
    at main (node_modules/@angular-devkit/schematics-cli/bin/schematics.js:298:14)
    at Object.<anonymous> (node_modules/@angular-devkit/schematics-cli/bin/schematics.js:426:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
```

**Comment by its-dibo** [comment]
> Did you build the schematic before running it ?

worked

as a reference, if anyone wants to output the build into a separate folder

1- set `outDir` in tsconfig.json into 'dist'
2- copy src/collection.json into dist/collection.json
3- modify the path of `schematics` prop in package.json to point to "./dist/collection.json" instead of "./src/collection.json`
4- replace `schematics .:test` with `schematics ./dist:test` or `cd dist && schematics .:test`
