### ISSUE TITLE
.module.ts" is not in the SourceMap.

### ISSUE THREAD

**Issue by thanatos11** [angular/angular-cli#2666]
still have it on beta 17:

Envirnoment:
angular-cli: local (v1.0.0-beta.17, branch: master)
node: 6.6.0
os: linux x64
npm: 3.10.3

FULL error output:
Error: "/home/lamp/angular-cli/node_modules/angular2-template-loader/index.js!/var/www/accenture/accenture-app/src/app/profile/profile.module.ts" is not in the SourceMap.

at SourceMapConsumer_sourceContentFor as sourceContentFor
at /home/lamp/angular-cli/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:133:40
at Array.forEach (native)
at Function.SourceNode_fromStringWithSourceMap as fromStringWithSourceMap
at SourceMapSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
at ReplaceSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ReplaceSource.js:66:29)
at CachedSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:12:23)
at /home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
at Array.map (native)
at ConcatSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
at /home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
at Array.map (native)
at ConcatSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
at /home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
at Array.map (native)
at ConcatSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
at /home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:40:49
at Array.map (native)
at ConcatSource.node (/home/lamp/angular-cli/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
at ConcatSource.proto.sourceAndMap (/home/lamp/angular-cli/node_modules/webpack-sources/lib/SourceAndMapMixin.js:28:18)
at CachedSource.sourceAndMap (/home/lamp/angular-cli/node_modules/webpack-sources/lib/CachedSource.js:51:28)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:57:32)
at Array.map (native)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:43:84)
at Array.forEach (native)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/SourceMapDevToolPlugin.js:42:11)
at Compilation.applyPlugins (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:25:14)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:616:10)
at next (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:81:11)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/ProgressPlugin.js:118:5)
at next (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:83:14)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:144:4)
at Compilation.applyPluginsAsync (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:85:13)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:612:9)
at next (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:81:11)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/ProgressPlugin.js:114:5)
at Compilation.applyPluginsAsync (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:85:13)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:608:8)
at next (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:81:11)
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/ProgressPlugin.js:110:5)
at Compilation.applyPluginsAsync (/home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:85:13)
at Compilation.seal (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:554:7)
at Compiler. (/home/lamp/angular-cli/node_modules/webpack/lib/Compiler.js:468:16)
at /home/lamp/angular-cli/node_modules/tapable/lib/Tapable.js:152:11
at Compilation. (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:452:10)
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:423:12
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at done (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:246:17)
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:44:16
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:335:10
at /home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:52:16
at Object.async.forEachOf.async.eachOf (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:236:30)
at Object.async.forEach.async.each (/home/lamp/angular-cli/node_modules/webpack/node_modules/async/lib/async.js:209:22)
at Compilation.addModuleDependencies (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:192:8)
at Compilation.processModuleDependencies (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:177:7)
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:317:12
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:124:4
at Array.forEach (native)
at callback (/home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:123:12)
at /home/lamp/angular-cli/node_modules/webpack/lib/Compilation.js:147:10
at /home/lamp/angular-cli/node_modules/webpack/lib/NormalModule.js:209:10
at /home/lamp/angular-cli/node_modules/webpack/lib/NormalModule.js:164:10
at /home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:365:3
at iterateNormalLoaders (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
at iterateNormalLoaders (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:213:10)
at /home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:228:3
at runSyncOrAsync (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:125:11)
at iterateNormalLoaders (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
at iterateNormalLoaders (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:213:10)
at /home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:228:3
at context.callback (/home/lamp/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
at /home/lamp/angular-cli/node_modules/postcss-loader/index.js:67:13

I have tried everything; Any ideas?

**Comment by JanStureNielsen** [comment]
@thanatos11 -- what are the steps to reproduce this?

**Comment by filipesilva** [comment]
@thanatos11 I'm going to need some repro steps for this issue.

**Comment by thanatos11** [comment]
Sorry, So the project I am working is saved on a bitrepo; 
1. the angular server is on an ubuntuX64 where i ahve first installed globally the node, npm and angular_cli from the repo with npm link; thus having the latest version;
2. in the project i have done the regular npm install; no errors;
3. made the npm link angular_cli;
4. made server with no issues; then made build with no problems; but when i ran the build --prod; it crashed;
Since then i have tried so many fixes, and the latest that works, is to use global npm install angular-cli, and the build will not copy any assets; if i use the npm link version will crash on prod;

**Comment by filipesilva** [comment]
There are several issues with using locally linked versions, you can read more about it https://github.com/angular/angular-cli/pull/2250#issuecomment-248792025.

We don't really support having a linked lib, it's mostly a development feature. My advice to you is to delete `node_modules`, reinstall all dependencies and not link anything.

If you still have problems you'll have to open a new issue with exact repro steps. If we can't repro the problem, we cannot debug or fix it.

**Comment by thanatos11** [comment]
Yes, solved by upgrading anguar-cli to latest versions
