### ISSUE TITLE
Angular CLI cannot exit ng serve or force quit with Ctrl + C. Cont. from 26413

### ISSUE THREAD

**Issue by estrellajm** [angular/angular-cli#26767]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

While running `ng serve` when I try to cancel the process with `ctrl + c,` nothing happens.
<img width="619" alt="284030043-9e547e7f-35a7-4098-894d-44ef78f1725b" src="https://github.com/angular/angular-cli/assets/7454322/78bae2ee-0f48-4001-8a31-7dbbd731bc0e">

This is still an issue as previously reported on https://github.com/angular/angular-cli/issues/26413. Rebooting my computer gave me temporary reprieve, but the minute I serve it and visit the page locally the issue persists

### Minimal Reproduction

1. I set NVM to use 20 (v20.9.0) as default with the following command nvm alias default 20
2. When I open a new terminal instance and run ng serve the angular project builds

I also get this issue when I am running Node 18, and the client is reloading

### Exception or Error

```text
ng s

Initial Chunk Files | Names         |  Raw Size
polyfills.js        | polyfills     |  82.71 kB | 
main.js             | main          |  23.26 kB | 
styles.css          | styles        |  96 bytes | 

                    | Initial Total | 106.07 kB

Application bundle generation complete. [2.461 seconds]
Watch mode enabled. Watching for file changes...
  ➜  Local:   http://localhost:4200/
^C^C⠋ Changes detected. Rebuilding...
Error: The service is no longer running
    at /Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1111:28
    at sendRequest (/Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:699:14)
    at triggerAnotherBuild (/Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1109:17)
    at /Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1119:15
    at ZoneAwarePromise (/Users/jestrella/Desktop/nutri-bol/node_modules/zone.js/fesm2015/zone-node.js:1342:21)
    at Object.rebuild (/Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1098:35)
    at #performBundle (/Users/jestrella/Desktop/nutri-bol/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:141:53)
    at BundlerContext.bundle (/Users/jestrella/Desktop/nutri-bol/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:120:49)
    at /Users/jestrella/Desktop/nutri-bol/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:61:28
    at Array.map (<anonymous>)
Error: The service is no longer running
    at /Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1111:28
    at sendRequest (/Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:699:14)
    at triggerAnotherBuild (/Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1109:17)
    at /Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1119:15
    at ZoneAwarePromise (/Users/jestrella/Desktop/nutri-bol/node_modules/zone.js/fesm2015/zone-node.js:1342:21)
    at Object.rebuild (/Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1098:35)
    at #performBundle (/Users/jestrella/Desktop/nutri-bol/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:141:53)
    at BundlerContext.bundle (/Users/jestrella/Desktop/nutri-bol/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:120:49)
    at /Users/jestrella/Desktop/nutri-bol/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:61:28
An unhandled exception occurred: The service is no longer running
See "/private/var/folders/hq/tyztmswd0ns4d89gyzvfcj2r0000gn/T/ng-8hPtyD/angular-errors.log" for further details.
/Users/jestrella/Desktop/nutri-bol/node_modules/zone.js/fesm2015/zone-node.js:177
                        throw error;
                        ^


Error: The service is no longer running
    at /Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1111:28
    at sendRequest (/Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:699:14)
    at triggerAnotherBuild (/Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1109:17)
    at /Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1119:15
    at ZoneAwarePromise (/Users/jestrella/Desktop/nutri-bol/node_modules/zone.js/fesm2015/zone-node.js:1342:21)
    at Object.rebuild (/Users/jestrella/Desktop/nutri-bol/node_modules/esbuild/lib/main.js:1098:35)
    at #performBundle (/Users/jestrella/Desktop/nutri-bol/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:141:53)
    at BundlerContext.bundle (/Users/jestrella/Desktop/nutri-bol/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:120:49)
    at /Users/jestrella/Desktop/nutri-bol/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:61:28
    at Array.map (<anonymous>)
```

### Your Environment

```text
Angular CLI: 17.0.8
Node: 20.9.0
Package Manager: yarn 1.22.21
OS: darwin arm64

Angular: 17.0.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.8
@angular-devkit/build-angular   17.0.8
@angular-devkit/core            17.0.8
@angular-devkit/schematics      17.0.8
@schematics/angular             17.0.8
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by estrellajm** [comment]
@alan-agius4 

Restarting my computer did not fix the issue permanently. It seemed like a temporary reprieve. 😕

**Comment by alan-agius4** [comment]
Do this happen when using the prerelease version `17.1.0`? 
You can try it out by using `ng update @angular/cli@next`

**Comment by alan-agius4** [comment]
Closing due to lack of feedback.

**Comment by estrellajm** [comment]
@alan-agius4 Sorry for the extremely late response, but I wanted to let you know that I am no longer experiencing the issue. I am running `v17.1.1`
