### ISSUE TITLE
Error: An unhandled exception occurred - The service was stopped [Angular CLI v17.0.8]

### ISSUE THREAD

**Issue by first-account** [angular/angular-cli#26771]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.10

### Description

I'm encountering the following error when attempting to run an Angular application using `ng serve`:

```plaintext
An unhandled exception occurred: The service was stopped
See "C:\Users\op\AppData\Local\Temp\ng-yxgjmu\angular-errors.log" for further details.

### Minimal Reproduction

ng new project
ng serve

### Exception or Error

```text
[error] Error: The service was stopped
    at C:\Users\op\Desktop\yes\node_modules\esbuild\lib\main.js:1111:28
    at responseCallbacks.<computed> (C:\Users\op\Desktop\yes\node_modules\esbuild\lib\main.js:703:9)
    at Socket.afterClose (C:\Users\op\Desktop\yes\node_modules\esbuild\lib\main.js:693:28)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.8
Node: 20.10.0
Package Manager: npm 10.2.5
OS: win32 x64

Angular: 17.0.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.8
@angular-devkit/build-angular   17.0.8
@angular-devkit/core            17.0.8
@angular-devkit/schematics      17.0.8
@schematics/angular             17.0.8
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

it worked on debian but not on windows 10 ltsc 2019 1809 (OS build 17763.1)

**Comment by alan-agius4** [comment]
Can you please check if this is still reproducible when using the prerelease version of 17.1.0? Can you update by updating using the below command.

```
ng update @angular/cli@next
```

**Comment by first-account** [comment]
it seems like it's an OS issue, just reinstalled windows and it works fine thanks.
