### ISSUE TITLE
ng init --mobile flag breaks builds

### ISSUE THREAD

**Issue by uitgewis** [angular/angular-cli#2679]
### OS?
OSX El Capitan

### Versions.
```
angular-cli: 1.0.0-beta.17
node: 6.3.0
os: darwin x64
```

### Repro steps.
```
$ ng init --mobile=true
$ ng serve
```

### The log given by the failure.
```
Unexpected token import
./src/main-app-shell.ts:1
(function (exports, require, module, __filename, __dirname) { import 'angular2-universal-polyfills';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at new PrerenderWebpackPlugin (./node_modules/angular-cli/utilities/prerender-webpack-plugin.js:8:27)
    at Object.exports.getWebpackMobileConfigPartial (./node_modules/angular-cli/models/webpack-build-mobile.js:20:13)
    at new NgCliWebpackConfig (./node_modules/angular-cli/models/webpack-config.js:21:42)
    at Class.exports.default.Task.extend.run (./node_modules/angular-cli/tasks/serve-webpack.js:19:22)
    at ./node_modules/angular-cli/commands/serve.js:85:26
    at process._tickCallback (internal/process/next_tick.js:103:
```

### Mention any other details that might be useful.
This works fine without the `--mobile` flag.

**Comment by deebloo** [comment]
I don't believe the --mobile flag is enabled currently.

https://github.com/angular/angular-cli#support-for-offline-applications

**Comment by uitgewis** [comment]
Oh okay, I didn't see that. I found the option with `ng --help` and tried it out.

**Comment by deebloo** [comment]
@uitgewis I don't think it should be. I do know it is not currently supported

**Comment by uitgewis** [comment]
All good. I suggest adding the same error seen here(https://github.com/angular/angular-cli/blob/master/packages/angular-cli/commands/new.ts#L58) to the `init` command as well. 

I can PR if in agreement?

**Comment by filipesilva** [comment]
@uitgewis I'd appreciate a PR for that, yes!
