### ISSUE TITLE
ng build fails with linked CLI starting version 1.0.0-beta.17

### ISSUE THREAD

**Issue by aecz** [angular/angular-cli#2681]
### OS?
> Windows 7

### Versions.
angular-cli: 1.0.0-beta.17
node: 6.5.0
os: win32 x64

### Repro steps.
```
npm i -g angular-cli@1.0.0-beta.17
ng new test-beta17 --skip-npm --link-cli
cd test-beta17
ng build
```
### The log given by the failure.
```
ERROR in ./src/main.ts
Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\typescript\lib\lib.es2015.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at State.readFile (C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\host.ts:321:19)
    at State.readFileAndAdd (C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\host.ts:325:25)
    at FileAnalyzer.checkDependencies (C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\deps.ts:43:28)
    at C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\host.ts:181:39
    at Array.forEach (native)
    at State.loadDefaultLib (C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\host.ts:179:29)
    at new State (C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\host.ts:143:14)
    at Object.ensureInstance (C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\instance.ts:150:19)
    at compiler (C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (C:\Users\aecz\AppData\Roaming\npm\node_modules\angular-cli\node_modules\awesome-typescript-loader\src\index.ts:18:18)
 @ multi main
```

### Mention any other details that might be useful.
Works fine with version 1.0.0-beta.16.
Might be related to the new TsConfigPathsPlugin introduced in beta.17.

**Comment by aecz** [comment]
Workaround/solution is to delete global angular-cli and reinstall it. Updating from beta16 does not work. It seems that NPM put the `tmp` module version 0.0.24 at the top and `can-symlink` needs 0.0.28. Please note `tmp` module also does not install inside `can-symlink` node_modules folder.
I think we can close this issue unless we want the update to work flawlessly. Im not sure if the update instructions recommend to uninstall previous angular-cli versions first. One way to fix it maybe is to set `tmp` module version to 0.0.28 in `angular-cli` package.json.

**Comment by Meligy** [comment]
Unfortunately this is a known issue at the moment, and document in the homepage.

Please read:
https://github.com/angular/angular-cli#updating-angular-cli

It says you need to run 2 cleanup steps:

```
npm uninstall -g angular-cli
npm cache clean
```

P.S.
If the docs instructions work, you may want to close this issue.

Cheers,
