### ISSUE TITLE
angular 2.1.0 release causes missing peer dependencies

### ISSUE THREAD

**Issue by ninj** [angular/angular-cli#2692]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX + Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
angular-cli: 1.0.0-beta.17
node: 6.7.0
os: darwin x64
```
### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

`ng init` in empty directory, then `npm ls`

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
[snip]
npm ERR! peer dep missing: @angular/common@2.1.0, required by @angular/platform-server@2.1.0
npm ERR! peer dep missing: @angular/compiler@2.1.0, required by @angular/platform-server@2.1.0
npm ERR! peer dep missing: @angular/core@2.1.0, required by @angular/platform-server@2.1.0
npm ERR! peer dep missing: @angular/platform-browser@2.1.0, required by @angular/platform-server@2.1.0
npm ERR! peer dep missing: @angular/platform-server@2.0.2, required by @angular/compiler-cli@0.6.4
```

### Mention any other details that might be useful.

I would hope generated projects would have resolvable dependencies so that `npm shrinkwrap`
 works out of the box.

I imagine there's a way to edit generated pom so that we can use use angular 2.1.0, I'm just not sure what it is...

package.json:
```
{
  "name": "ng-deps",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~2.0.0",
    "@angular/compiler": "~2.0.0",
    "@angular/core": "~2.0.0",
    "@angular/forms": "~2.0.0",
    "@angular/http": "~2.0.0",
    "@angular/platform-browser": "~2.0.0",
    "@angular/platform-browser-dynamic": "~2.0.0",
    "@angular/router": "~3.0.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.17",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}
```

**Comment by kylecordes** [comment]
When I edit package.json to use angular 2.1.0 (router 3.1.0), I get a **working result**, but some warning:

```
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/platform-server@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/core@2.0.2 but none was installed.
```

I'm sure there are things to figure out in terms of the right level of version tolerance for CLI. 2.1.0 shipped yesterday, as the first point minor version release following the exciting new versioning plan for Angular. I would guess that essentially every project in the Angular ecosystem (certainly including all of ours here) has the first opportunity to see how well it works, what sort of version tolerance we can get away with.

**Comment by ninj** [comment]
I'll take a guess with this - angular-cli requests compiler-cli like this:

```
    "@angular/compiler-cli": "^0.6.0",
```

however, compiler (and everything else) is requested like this:

```
    "@angular/compiler": "^2.0.0",
```

is there a reason that compilier-cli is restricted to the 0.6.x line?

**Comment by tinchou** [comment]
I updated `@angular/compiler-cli` to `2.1.0` and I get:

```
+-- UNMET PEER DEPENDENCY @angular/compiler-cli@2.1.0
+-- UNMET PEER DEPENDENCY typescript@2.0.3

npm ERR! peer dep missing: @angular/compiler-cli@^0.6.0, required by @ngtools/webpack@1.1.0
npm ERR! peer dep missing: typescript@2.0.2, required by @ngtools/webpack@1.1.0
```

In my dependencies I have:

```json
  "dependencies": {
    "@angular/compiler-cli": "2.1.0",
    "@ngtools/webpack": "1.1.0",
    "typescript": "2.0.3",
```

**Comment by Disk1of5** [comment]
Also having issues in Ubuntu 16.04 
  ├── UNMET PEER DEPENDENCY @angular/compiler@2.1.0
  ├─┬ @angular/compiler-cli@0.6.4 
  │ ├── minimist@1.2.0 
  │ └── reflect-metadata@0.1.8 
  ├── UNMET PEER DEPENDENCY @angular/core@2.1.0
  ├── @angular/platform-browser@2.1.0 
  ├── UNMET PEER DEPENDENCY @angular/platform-server@2.1.0

Thanks!

**Comment by Disk1of5** [comment]
Is there any way to do a npm install angular-cli    without version 2.1.0 ? can i force an install with a previous angular version?

**Comment by JanStureNielsen** [comment]
FWIW, I'm successfully running Angular 2.1.0 in a Angular CLI 1.0.0-beta.17 based project with a few npm warnings; here are my dependencies:

```
  "dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/router": "3.1.0",
    "@angular/material": "2.0.0-alpha.9-3",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "hammerjs": "2.0.8",
    "angular-cli": "1.0.0-beta.17",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.3"
  }

```

**Comment by ninj** [comment]
@JanStureNielsen - yes, the npm warnings are what we're interested in, even though the project should work.

Does `npm ls` run successfully in your project?

**Comment by Disk1of5** [comment]
I was able to resolve this by updating to nodeJS v6 in linux.. and then cache clean and reinstall.

**Comment by ashish173** [comment]
I think this is a possible duplicate for #1941 moreover the the last answer by @JohnMcGuinness fixed issues like this for me, 

reposting it here for convenience

```
npm uninstall -g angular-cli
npm cache clean
npm install -g node-gyp
npm install -g node-pre-gyp
npm install -g angular-cli
```

**Comment by keyduq** [comment]
I have the same issue on Ubuntu 16.04 running ```ng new```, and I already try what @ashish173 says, but still the same issue.

```ng --version```

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.17
node: 6.8.1
os: linux x64
```

```npm ls``` throws
```
npm ERR! peer dep missing: @angular/common@2.1.0, required by @angular/platform-server@2.1.0
npm ERR! peer dep missing: @angular/compiler@2.1.0, required by @angular/platform-server@2.1.0
npm ERR! peer dep missing: @angular/core@2.1.0, required by @angular/platform-server@2.1.0
npm ERR! peer dep missing: @angular/platform-browser@2.1.0, required by @angular/platform-server@2.1.0
npm ERR! peer dep missing: @angular/platform-server@2.0.2, required by @angular/compiler-cli@0.6.4
```
package.json
```
  "dependencies": {
    "@angular/common": "~2.0.0",
    "@angular/compiler": "~2.0.0",
    "@angular/core": "~2.0.0",
    "@angular/forms": "~2.0.0",
    "@angular/http": "~2.0.0",
    "@angular/platform-browser": "~2.0.0",
    "@angular/platform-browser-dynamic": "~2.0.0",
    "@angular/router": "~3.0.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.17",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
```

**Comment by JanStureNielsen** [comment]
@ninj -- `npm ls` shows similar errors:

```
npm ERR! peer dep missing: @angular/compiler@2.0.2, required by @angular/compiler-cli@0.6.4
npm ERR! peer dep missing: @angular/core@2.0.2, required by @angular/compiler-cli@0.6.4
npm ERR! peer dep missing: @angular/platform-server@2.0.2, required by @angular/compiler-cli@0.6.4
npm ERR! peer dep missing: typescript@2.0.2, required by @ngtools/webpack@1.1.0
```

**Comment by drasko** [comment]
```
drasko@Lenin:~/mainflux$ sudo npm install -g angular-cli
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm ERR! registry error parsing json
/usr/bin/ng -> /usr/lib/node_modules/angular-cli/bin/ng

> execSync@1.0.2 install /usr/lib/node_modules/angular-cli/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> node-zopfli@2.0.1 install /usr/lib/node_modules/angular-cli/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.1 and node@6.8.1 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.8.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/.node-gyp"
make: Entering directory '/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
make: *** No rule to make target '../.node-gyp/6.8.1/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/angular-cli/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.6.0-1-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/angular-cli/node_modules/node-zopfli
gyp ERR! node -v v6.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/angular-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.6.0-1-amd64
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/angular-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/angular-cli/node_modules/node-zopfli
node-pre-gyp ERR! node -v v6.8.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64' (1)

> node-sass@3.10.1 install /usr/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.1/linux-x64-48_binding.node
Binary downloaded and installed at /usr/lib/node_modules/angular-cli/node_modules/node-sass/vendor/linux-x64-48/binding.node

> node-sass@3.10.1 postinstall /usr/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/build.js

"/usr/lib/node_modules/angular-cli/node_modules/node-sass/vendor/linux-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
/usr/lib
└─┬ angular-cli@1.0.0-beta.17 
  ├─┬ @angular-cli/ast-tools@1.0.3 
  │ ├── rxjs@5.0.0-beta.11 
  │ └── typescript@2.0.0 
  ├── @angular-cli/base-href-webpack@1.0.2 
  ├── @angular/common@2.1.0 
  ├── UNMET PEER DEPENDENCY @angular/compiler@2.1.0
  ├─┬ @angular/compiler-cli@0.6.4 
  │ ├── minimist@1.2.0 
  │ └── reflect-metadata@0.1.8 
  ├── UNMET PEER DEPENDENCY @angular/core@2.1.0
  ├── @angular/platform-browser@2.1.0 
  ├── UNMET PEER DEPENDENCY @angular/platform-server@2.1.0
  ├─┬ @angular/tsc-wrapped@0.3.0 
  │ └─┬ tsickle@0.1.7 
  │   └─┬ source-map-support@0.3.3 
  │     └── source-map@0.1.32 
  ├── @ngtools/webpack@1.1.0 

...

  │   ├── lodash._arraycopy@3.0.0 
  │   ├── lodash._arrayeach@3.0.0 
  │   ├── lodash._getnative@3.9.1 
  │   ├── lodash.istypedarray@3.0.6 
  │   └── lodash.toplainobject@3.0.0 
  └── zone.js@0.6.25 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/angular-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/platform-server@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.1 (node_modules/angular-cli/node_modules/node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by castamir** [comment]
there are WARNs even for angular v2.0.2. To get rid of them, I had to add
```
    "@angular/platform-server": "2.0.x",           <--- 2.0.x series of angular
    "typescript": "2.0.2"                          <--- exact version of Typescript
```
NOTE: I prefer using `2.0.x` syntax over `~2.0.0` or `^2.0.0` which are not that easy to understand as `2.0.x`

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/2704 should fix this. More specifically, the `peerDependencies` changes on `packages/webpack/package.json`.

**Comment by skiabox** [comment]
Installing globally the latest angular-cli (beta-18) solved this problem for me.

**Comment by ninj** [comment]
@filipesilva confirmed fixed - thanks!

**Comment by rinoldit** [comment]
npm WARN @angular/core@2.4.8 requires a peer of rxjs@^5.0.1 but non
e was installed.

**Comment by sandeep540** [comment]
I am getting this error

```
D:\angular\firebase\apartment>npm install angularfire2 firebase --save
apartment@0.0.0 D:\angular\firebase\apartment
+-- angularfire2@4.0.0-rc.1
`-- firebase@4.1.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN angularfire2@4.0.0-rc.1 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN angularfire2@4.0.0-rc.1 requires a peer of @angular/compiler@^4.0.0 but none was installed.
npm WARN angularfire2@4.0.0-rc.1 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN angularfire2@4.0.0-rc.1 requires a peer of @angular/platform-browser@^4.0.0 but none was installed.
npm WARN angularfire2@4.0.0-rc.1 requires a peer of @angular/platform-browser-dynamic@^4.0.0 but none was installed.
```
