### ISSUE TITLE
Proxy cannot connect to target with client certificate authentication

### ISSUE THREAD

**Issue by SkiGeek82** [angular/angular-cli#2696]
> ## Please provide us with the following information:
### OS?

> Windows 10
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.17  
node: 4.1.2  
os: win32 x64
### Repro steps.

> The app was created using CLI. I would like to use the built in proxy functionality but my backend server requires client certificate validation and specifying the cert/key/cachain in the proxy config does not work.  

Repro by defining proxy.conf.json with a target that requires certificate authentication and specifying the target config similar to below

{
    "/api": {
        "target": {
            "host": "apidev.backend.com",
            "protocol": "https:",
            "key": "keypath",
            "cert": "certpath",
            "ca": "capath"
        },
        "changeOrigin": true,
        "secure": false
    }
}

I have successfully connected using a separate node server to run http-proxy
### The log given by the failure.

> Normally this include a stack trace and some more information.

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line  
    at Error (native)  
    at Object.createSecureContext (_tls_common.js:63:19)  
    at Object.exports.connect (_tls_wrap.js:955:21)  
    at Agent.createConnection (https.js:73:22)  
    at Agent.createSocket (_http_agent.js:174:16)  
    at Agent.addRequest (_http_agent.js:143:23)  
    at new ClientRequest (_http_client.js:133:16)  
    at Object.exports.request (http.js:31:10)  
    at Object.exports.request (https.js:163:15)  
    at Array.stream (C:{{myapppath}}\node_modules\http-proxy\lib\http-proxy\passes\web-incoming.js:111:74)  
    at ProxyServer.<anonymous> (C:{{myapppath}}\node_modules\http-proxy\lib\http-proxy\index.js:80:21)  
    at middleware (C:{{myapppath}}\node_modules\http-proxy-middleware\lib\index.js:41:19)  
    at C:{{myapppath}}\node_modules\webpack-dev-server\lib\Server.js:190:15  
    at Layer.handle [as handle_request](C:{{myapppath}}node_modulesexpresslibrouterlayer.js:95:5)  
    at trim_prefix (C:{{myapppath}}\node_modules\express\lib\router\index.js:312:13)  
    at C:{{myapppath}}\node_modules\express\lib\router\index.js:280:7  
    at Function.process_params (C:{{myapppath}}\node_modules\express\lib\router\index.js:330:12)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\index.js:271:10)  
    at goNext (C:{{myapppath}}\node_modules\webpack-dev-middleware\middleware.js:194:42)  
    at processRequest (C:{{myapppath}}\node_modules\webpack-dev-middleware\middleware.js:236:12)  
at ready (C:{{myapppath}}\node_modules\webpack-dev-middleware\middleware.js:138:21)  
    at webpackDevMiddleware (C:{{myapppath}}\node_modules\webpack-dev-middleware\middleware.js:221:3)  
    at Layer.handle [as handle_request](C:{{myapppath}}node_modulesexpresslibrouterlayer.js:95:5)  
    at trim_prefix (C:{{myapppath}}\node_modules\express\lib\router\index.js:312:13)  
    at C:{{myapppath}}\node_modules\express\lib\router\index.js:280:7  
    at Function.process_params (C:{{myapppath}}\node_modules\express\lib\router\index.js:330:12)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\index.js:271:10)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:121:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at Server.setContentHeaders (C:{{myapppath}}\node_modules\webpack-dev-server\lib\Server.js:303:2)  
    at Layer.handle [as handle_request](C:{{myapppath}}node_modulesexpresslibrouterlayer.js:95:5)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:131:13)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\route.js:125:14)  
    at Route.dispatch (C:{{myapppath}}\node_modules\express\lib\router\route.js:112:3)
at Layer.handle [as handle_request](C:{{myapppath}}node_modulesexpresslibrouterlayer.js:95:5)  
    at C:{{myapppath}}\node_modules\express\lib\router\index.js:277:22  
    at param (C:{{myapppath}}\node_modules\express\lib\router\index.js:349:14)  
    at param (C:{{myapppath}}\node_modules\express\lib\router\index.js:365:14)  
    at Function.process_params (C:{{myapppath}}\node_modules\express\lib\router\index.js:410:3)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\index.js:271:10)  
    at expressInit (C:{{myapppath}}\node_modules\express\lib\middleware\init.js:33:5)  
    at Layer.handle [as handle_request](C:{{myapppath}}node_modulesexpresslibrouterlayer.js:95:5)  
    at trim_prefix (C:{{myapppath}}\node_modules\express\lib\router\index.js:312:13)  
    at C:{{myapppath}}\node_modules\express\lib\router\index.js:280:7  
    at Function.process_params (C:{{myapppath}}\node_modules\express\lib\router\index.js:330:12)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\index.js:271:10)  
    at query (C:{{myapppath}}\node_modules\express\lib\middleware\query.js:44:5)  
    at Layer.handle [as handle_request](C:{{myapppath}}node_modulesexpresslibrouterlayer.js:95:5)  
    at trim_prefix (C:{{myapppath}}\node_modules\express\lib\router\index.js:312:13)  
    at C:{{myapppath}}\node_modules\express\lib\router\index.js:280:7  
    at Function.process_params (C:{{myapppath}}\node_modules\express\lib\router\index.js:330:12)  
    at next (C:{{myapppath}}\node_modules\express\lib\router\index.js:271:10)  
    at Function.handle (C:{{myapppath}}\node_modules\express\lib\router\index.js:176:3)  
    at EventEmitter.handle (C:{{myapppath}}\node_modules\express\lib\application.js:173:10)  
    at Server.app (C:{{myapppath}}\node_modules\express\lib\express.js:38:9)  
    at Server.new_handler (C:{{myapppath}}\node_modules\sockjs\lib\utils.js:89:20)  
    at emitTwo (events.js:87:13)  
    at Server.emit (events.js:172:7)  
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:521:12)  
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)       
### Mention any other details that might be useful.

proxy config has been tried both with cert as string array and with the cert path neither has worked:

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Heya, we've since added the following documention:
- proxy: https://github.com/angular/angular-cli/wiki/stories-proxy
- corporate proxy: https://github.com/angular/angular-cli/wiki/stories-using-corporate-proxy
- ng serve ssl-cert/key options: https://github.com/angular/angular-cli/wiki/serve

Let me know if your scenario still is not addressed.

**Comment by diealca** [comment]
To use client authentication is necessary to read the certs, for that use proxy.conf.js to configure the proxy and fs.readFileSync to read the files

const fs = require('fs');
const PROXY_CONFIG = {
  "/api/*": {
    "target":{
      "host": "host",
      "port": "port",
      "protocol": "https:",
      "key": fs.readFileSync('keypath'),
      "cert": fs.readFileSync('certpath'),
      "ca":fs.readFileSync('cachainpath')
      },
      "secure": false,
    "logLevel": "debug",
    "changeOrigin": true
  }
}

module.exports = PROXY_CONFIG;

**Comment by davidtim** [comment]
@diealca can you please help me, I tried your solution but it got:

> [HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]

**Comment by diealca** [comment]
@davidtim that message indicates that the proxy is started. Start to send requests to verify that it is working

**Comment by davidtim** [comment]
Yes thank you very for your solution.

Sent from Mail for Windows 10

**Comment by abhishek-mehrotra** [comment]
@diealca 
1)I believe the above sol is when we have a backend api server needing certificate and key. Is it true?
2) I have a backend server (third party and secure) which needs certificate and keys when I hit the post and get request from my angular gui. I don't want my gui to be secure. My angular set is dev.
Do I only need to set up proxy as above and provide the proxy option during NG serve? OR I would also need to provide key and cert option while doing NG serve?

**Comment by mlapeyre** [comment]
I could get a working ssl client authentication between the proxy and the target using the following **proxy.conf.js**, if it can help someone...
```
const fs = require('fs');
const PROXY_CONFIG = {
  "/api": {
    "target": {
      "host": "my-target-host",
      "port": "7777",
      "protocol": "https:",
      "pfx": fs.readFileSync('./certificates/administrator.p12'),
      "passphrase": 'password'
    },
    "secure": false,
    "logLevel": "debug",
    "changeOrigin": true
  }
};
module.exports = PROXY_CONFIG;
```
