### ISSUE TITLE
ng addon: EACCES error

### ISSUE THREAD

**Issue by cladera** [angular/angular-cli#2698]
### OS?
Mac OSX Yosemite

### Versions.
angular-cli: 1.0.0-beta.16
node: 6.5.0
os: darwin x64

### Repro steps.
The app was created using the CLI. I did no changes, brand new project. I only executed the command:

```
ng addon sample-addon
```

### The log given by the failure.
```
EACCES: permission denied, open '/opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/blueprints/addon/files/package.json'
Error: EACCES: permission denied, open '/opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/blueprints/addon/files/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Class.writeContentsToFile (/opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/blueprints/addon/index.js:175:6)
    at Class.generatePackageJson (/opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/blueprints/addon/index.js:50:25)
    at Class.files (/opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/blueprints/addon/index.js:101:10)
    at Class.Blueprint.install (/opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/blueprint.js:497:41)
    at Class.run (/opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/install-blueprint.js:56:24)
    at Class.run (/opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/commands/init.js:102:29)
    at /opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/commands/new.js:91:12
    at tryCatch (/opt/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/opt/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/opt/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/opt/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:82:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback **(internal/process/next_tick.js:98:9)**
```

**Comment by asaph26** [comment]
This is caused because the user executing the ng command does not have access to the `/opt/local/lib/node_modules/angular-cli/node_modules/angular-cli/blueprints/addon/files/package.json` file

There are several ways to fix this
1) If the user is a sudo user, using sudo works around this. the command becomes `sudo ng addon ...`

2) Changing the location of where global installs are located to a folder where the user has access. More info on this https://docs.npmjs.com/files/folders 

3) Changing the permissions in the opt/local/lib/node_modules to provide access to your user

**Comment by cladera** [comment]
Thank you @asaph26 

Actually I figured that out. But, as long the project has got a local cli install I fail to understand why using the global package for this specific command.

**Comment by gelliott181** [comment]
@cladera the global CLI is called any time you use `ng` alone. To use the local CLI you need to call `[ProjectRoot]\node_modules\.bin\ng` instead.

**Comment by filipesilva** [comment]
You have permission issues with npm on OSX, which is a common problem. See https://docs.npmjs.com/getting-started/fixing-npm-permissions
