### ISSUE TITLE
App serve with SSR ERROR m [Error]: NG04002: 'robots.txt'

### ISSUE THREAD

**Issue by armingdev** [angular/angular-cli#26983]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2

### Description

When I build an angular project with SSR (`ng build`), and then run it with the command `npm run serve:ssr:angular-bug`, each time when I open a link on the local host I get an error in node console:

```shell
ERROR m [Error]: NG04002: 'robots.txt'
```

This happens only when I open the link with Firefox Browser (Firefox Developer 123.0b2 (64-bit)). Opening localhost:4000 on Chrome or Safari doesn't trigger this error.

### Minimal Reproduction

- Create a new project with SSR using Angular CLI
- Build it with `ng build`
- Run serve command ` serve:ssr:angular-bug`. 

Then open the server link `http://localhost:4000`. The error will be shown in the node console.

Minimal repo to reproduce: [https://github.com/armingdev/angular-bug](https://github.com/armingdev/angular-bug)

### Exception or Error

```text
npm run serve:ssr:angular-bug

> angular-bug@0.0.0 serve:ssr:angular-bug
> node dist/angular-bug/server/server.mjs

Node Express server listening on http://localhost:4000
ERROR m [Error]: NG04002: 'robots.txt'
    at pc.noMatchError (file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:35:56595)
    at file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:35:57289
    at file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:4:16385
    at Ei._error (file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:4:5478)
    at Ei.error (file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:4:2583)
    at Ei._error (file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:4:2823)
    at Ei.error (file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:4:2583)
    at Ei._error (file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:4:2823)
    at Ei.error (file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:4:2583)
    at Ei._error (file:///Users/armingerina/Code/gamers.ba/angular-bug/dist/angular-bug/server/chunk-SNCOUTZD.mjs:4:2823) {
  code: 4002
}
```

### Your Environment

```text
MacOS:
Sonoma 14.3

Node Version:

node -v
v20.11.0


Angular Version:

ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.1.1
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

### Anything else relevant?

package.json:

```
{
  "name": "angular-bug",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "serve:ssr:angular-bug": "node dist/angular-bug/server/server.mjs"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.1.1",
    "@angular/common": "^17.1.1",
    "@angular/compiler": "^17.1.1",
    "@angular/core": "^17.1.1",
    "@angular/forms": "^17.1.1",
    "@angular/platform-browser": "^17.1.1",
    "@angular/platform-browser-dynamic": "^17.1.1",
    "@angular/platform-server": "^17.1.1",
    "@angular/router": "^17.1.1",
    "@angular/ssr": "^17.1.1",
    "express": "^4.18.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.1.1",
    "@angular/cli": "^17.1.1",
    "@angular/compiler-cli": "^17.1.1",
    "@types/express": "^4.17.17",
    "@types/jasmine": "~5.1.0",
    "@types/node": "^18.18.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.3.2"
  }
}
```

**Comment by JeanMeche** [comment]
Does your firefox request a `robots.txt` on everyweb site ? 
Do you have any extension that might do that ?

**Comment by armingdev** [comment]
> Does your firefox request a `robots.txt` on everyweb site ? Do you have any extension that might do that ?

It's happening even if I open this link in a private window, without any extensions. Also, this is not happening when I run a project with `ng serve`.

**Comment by atscott** [comment]
There’s nothing in Angular that specifically requests robots.txt. Your application routes do not have a fallback or configured response to this request path. Closing as expected and an issue outside of Angular.

**Comment by armingdev** [comment]
> There’s nothing in Angular that specifically requests robots.txt. Your application routes do not have a fallback or configured response to this request path. Closing as expected and an issue outside of Angular.

fallback route fixed it. Maybe this should be in docs also. Thanks
