### ISSUE TITLE
ng update - Migration failed: Unexpected token '﻿', "﻿{   "nam"... is not valid JSON

### ISSUE THREAD

**Issue by dapperdandev** [angular/angular-cli#27052]
### Command

update

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Unsure

### Description

`ng update @angular/core` fails from v17.0.8 to latest

### Minimal Reproduction

Attempt `ng update @angular/core` from a project on 17.0.8

### Exception or Error

```text
with the message:


Using package manager: npm
Collecting installed dependencies...
Found 126 dependencies.
Fetching dependency metadata from registry...
× Migration failed: Unexpected token '﻿', "﻿{
  "nam"... is not valid JSON
  See "C:\Users\danin\AppData\Local\Temp\ng-ckaJxh\angular-errors.log" for further details.
```

From log file:

```
[error] SyntaxError: Unexpected token '﻿', "﻿{
  "nam"... is not valid JSON
    at JSON.parse (<anonymous>)
    at _buildPackageInfo (C:\Users\danin\AppData\Roaming\fnm\node-versions\v20.9.0\installation\node_modules\@angular\cli\src\commands\update\schematic\index.js:429:30)
    at C:\Users\danin\AppData\Roaming\fnm\node-versions\v20.9.0\installation\node_modules\@angular\cli\src\commands\update\schematic\index.js:708:53
    at Map.forEach (<anonymous>)
    at C:\Users\danin\AppData\Roaming\fnm\node-versions\v20.9.0\installation\node_modules\@angular\cli\src\commands\update\schematic\index.js:707:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callRuleAsync (C:\Users\danin\AppData\Roaming\fnm\node-versions\v20.9.0\installation\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\rules\call.js:77:18)
```

### Your Environment

```text
CLI: 17.1.2
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1701.2 (cli-only)
@angular-devkit/core         17.1.2 (cli-only)
@angular-devkit/schematics   17.1.2 (cli-only)
@ngtools/webpack             17.0.9
@schematics/angular          17.1.2 (cli-only)
rxjs                         7.8.1
typescript                   5.2.2
webpack                      5.89.0
zone.js                      0.14.2
```

### Anything else relevant?

The first time I ran the command it seemed to start working. It updated the package.json and logged `installing dependencies`. I aborted the process with HOST + C. I thought that had potentially partially installed files and quit writing midstream. That would explain the `"nam" is not valid JSON` message. However, I get the exact same error on two different machines.

**Comment by dapperdandev** [comment]
The `@angular/*` packages should all come from the NPM registry. We do have XLTS as well for legacy AngularJS. It's a hybrid app.

I created a very simple angular.json manually, so I imagine that has something to do with it. On the other hand, generators and test work fine.

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "AppNgx": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "./AppNgx",
      "prefix": "kno2",
      "architect": {
        "test": {
          "builder": "@angular-devkit/build-angular:jest",
          "options": {
            "polyfills": [
              "zone.js",
              "zone.js/testing"
            ],
            "tsConfig": "tsconfig.spec.json"
          }
        }
      }
    }
  }
}
```

```
# .npmrc
@xlts.dev:registry=https://registry.xlts.dev/
//registry.xlts.dev/:_authToken=${XLTS_TOKEN}
//registry.xlts.dev/:always-auth=true
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

```json
{
  "name": "kno2fy-web",
  "description": "kno2fy.client",
  "readme": "../readme.md",
  "version": "1.0.0",
  "author": "Kno2, LLC",
  "license": "UNLICENSED",
  "private": true,
  "repository": {
    "type": "git",
    "url": "https://github.com/Kno2/kno2fy-web.git"
  },
  "scripts": {
    "start": "npm run start:web",
    "start:ngrok": "start powershell -c ngrok start auth0 && npm run start:web",
    "start:web": "webpack-dev-server --env IS_LOCAL=true --progress --color",
    "build": "webpack --env IS_LOCAL=true --progress --color",
    "build:ci": "webpack",
    "test": "ng test",
    "test:ng1": "karma start ./app/config/karma.conf.js --single-run",
    "test:ng1:ci": "karma start ./app/config/karma.conf.js --reporters junit --single-run --colors false",
    "test:ng1:w": "karma start ./app/config/karma.conf.js"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.8",
    "@angular/compiler-cli": "^17.0.8",
    "@babel/core": "^7.23.6",
    "@babel/plugin-transform-runtime": "^7.23.6",
    "@babel/preset-env": "^7.23.6",
    "@ngneat/spectator": "^16.0.0",
    "@ngtools/webpack": "^17.0.9",
    "@types/angular": "^1.8.4",
    "@types/angular-ui-router": "^1.1.44",
    "@types/jest": "^29.5.12",
    "@types/lodash": "4.14.177",
    "@types/node": "~12.12.6",
    "angular-mocks": "^1.7.5",
    "autoprefixer": "^8.6.5",
    "babel-loader": "^9.1.3",
    "babel-plugin-angularjs-annotate": "^0.10.0",
    "cheerio": "^1.0.0-rc.1",
    "copy-webpack-plugin": "^11.0.0",
    "css-loader": "^6.8.1",
    "css-minimizer-webpack-plugin": "^5.0.1",
    "debug": "^3.1.0",
    "html-loader": "^4.2.0",
    "html-webpack-plugin": "^5.5.4",
    "imports-loader": "^4.0.1",
    "is-docker": "^1.1.0",
    "jasmine-core": "^3.1.0",
    "jest": "^29.7.0",
    "jest-environment-jsdom": "^29.7.0",
    "karma": "^6.4.2",
    "karma-chrome-launcher": "^3.2.0",
    "karma-jasmine": "^5.1.0",
    "karma-junit-reporter": "^2.0.1",
    "karma-sourcemap-loader": "^0.4.0",
    "karma-spec-reporter": "^0.0.36",
    "karma-webpack": "^5.0.0",
    "karma-xml-reporter": "^0.1.4",
    "mini-css-extract-plugin": "^2.7.6",
    "ng-mocks": "^14.12.1",
    "ngtemplate-loader": "^2.1.0",
    "postcss-loader": "^7.3.3",
    "prettier": "^3.2.4",
    "sass-loader": "^13.3.2",
    "style-loader": "^3.3.3",
    "terser-webpack-plugin": "^5.3.9",
    "typescript": "~5.2.2",
    "webpack": "^5.89.0",
    "webpack-bundle-analyzer": "^4.10.1",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^4.15.1"
  },
  "dependencies": {
    "@angular/animations": "^17.0.8",
    "@angular/common": "^17.0.8",
    "@angular/compiler": "^17.0.8",
    "@angular/core": "^17.0.8",
    "@angular/forms": "^17.0.8",
    "@angular/platform-browser": "^17.0.8",
    "@angular/platform-browser-dynamic": "^17.0.8",
    "@angular/router": "^17.0.8",
    "@angular/upgrade": "^17.0.8",
    "@babel/runtime": "^7.23.6",
    "@kno2/ccdaview": "^1.0.11",
    "@kno2/ngx-pdf-viewer": "^2024.2.0",
    "@microsoft/applicationinsights-web": "^2.6.0",
    "@progress/kendo-theme-bootstrap": "^3.4.2",
    "@progress/kendo-ui": "^2017.1.118",
    "@types/minimatch": "^3.0.5",
    "@uirouter/angularjs": "1.0.30",
    "@uirouter/core": "6.0.8",
    "@webcomponents/custom-elements": "^1.5.0",
    "@webcomponents/shadydom": "^1.9.0",
    "angular": "npm:@xlts.dev/angular@^1.9.3",
    "angular-animate": "npm:@xlts.dev/angular-animate@^1.9.3",
    "angular-auth0": "^3.0.6",
    "angular-bootstrap-toggle": "^0.4.2",
    "angular-cache": "^3.2.4",
    "angular-chart.js": "^1.1.1",
    "angular-chosen-localytics": "^1.9.2",
    "angular-cookies": "npm:@xlts.dev/angular-cookies@^1.9.3",
    "angular-filter": "^0.5.17",
    "angular-flot": "~0.0.17",
    "angular-http-batcher": "^1.11.2",
    "angular-loader": "^1.8.3",
    "angular-sanitize": "npm:@xlts.dev/angular-sanitize@^1.9.3",
    "angular-spinner": "^1.0.1",
    "angular-touch": "npm:@xlts.dev/angular-touch@^1.9.3",
    "angular-ui-bootstrap": "https://github.com/kno2/bootstrap#90340ec325188f0d76ebeeddbba62f702af51cb9",
    "angular-ui-utils": "https://github.com/kno2/ui-utils#3f4fc0754a2067079fcf8c3dfbec0ffac76dbdf1",
    "angulartics": "^1.6.0",
    "angulartics-google-tag-manager": "^0.0.1",
    "auth0-js": "^9.23.3",
    "bootstrap": "^4.5.0",
    "bootstrap-chosen": "https://github.com/kno2/bootstrap-chosen#bd187f9eb77eb191b7437a99132229398dae6ce8",
    "chart.js": "^2.9.4",
    "chart.piecelabel.js": "^0.11.0",
    "clipboard": "^1.7.1",
    "components-font-awesome": "^4.7.0",
    "core-js": "^3.22.7",
    "daterangepicker": "^3.0.3",
    "dom-autoscroller": "^2.3.3",
    "dompurify": "^2.0.17",
    "dragula": "^3.7.2",
    "file-saver": "1.3.3",
    "Flot": "https://github.com/flot/flot#v0.8.3",
    "flot-aggregate": "https://github.com/kno2/flot-aggregate#16a36666a1af40944f35595bc92eac00b73010b6",
    "iscroll": "5.2.0",
    "jquery": "^3.5.1",
    "jquery-sparkline": "^2.4.0",
    "jquery-validation": "^1.19.5",
    "ladda": "^1.0.0",
    "launchdarkly-js-client-sdk": "^3.1.4",
    "lodash": "^4.17.21",
    "lodash-es": "^4.17.15",
    "moment": "^2.29.4",
    "ng-file-upload": "~9.1.2",
    "ng-idle": "^1.3.2",
    "ng-infinite-scroll": "^1.3.0",
    "ng-iscroll": "https://github.com/kno2/ng-iScroll#e22356fae88af1481f1f8e6531006add0ac524bc",
    "ng-tags-input": "^3.1.1",
    "ngclipboard": "^1.1.1",
    "ngx-bootstrap": "^12.0.0",
    "ngx-file-drop": "^16.0.0",
    "node-sass": "^9.0.0",
    "noty": "^2.4.0",
    "pdfjs-dist": "2.5.207",
    "pnotify": "3.2.0",
    "popper.js": "^1.14.6",
    "rxjs": "^7.8.1",
    "signalr": "^2.2.1",
    "socket.io-client": "^2.5.0",
    "ua-parser-js": "^0.7.36",
    "url-polyfill": "^1.0.13",
    "web-streams-polyfill": "^2.1.1",
    "zone.js": "~0.14.2"
  }
}
```
