### ISSUE TITLE
Getting error ReferenceError: fetch in server after deploy. 

### ISSUE THREAD

**Issue by laijuthomas** [angular/angular-cli#27262]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.11

### Description

I am getting an error ReferenceError: fetch is not defined while building and deploying my angular 17 app in server. While building the same app in my local machine and serving doesn't produce the same issue.

### Minimal Reproduction

ng build --configuration staging

### Exception or Error

```text
ReferenceError: fetch is not defined
    at new e (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-DPJU7YM5.mjs:3:13592)
    at Object.e.ɵfac [as factory] (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-DPJU7YM5.mjs:3:15810)
    at Cn.hydrate (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-VOQPDT5O.mjs:8:7010)
    at Cn.get (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-VOQPDT5O.mjs:8:6166)
    at Cm (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-VOQPDT5O.mjs:5:17498)
    at ae (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-VOQPDT5O.mjs:5:17575)
    at Object.r [as factory] (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-VOQPDT5O.mjs:8:7900)
    at Cn.hydrate (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-VOQPDT5O.mjs:8:7010)
    at Cn.get (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-VOQPDT5O.mjs:8:6166)
    at Cm (file:///var/www/capbargain-seed.fayastage.com/dist/server/chunk-VOQPDT5O.mjs:5:17498)
```

### Your Environment

```text
Angular CLI: 17.2.0
```

**Comment by alan-agius4** [comment]
Likley the problem is the node.js version of your server.

**Comment by laijuthomas** [comment]
> Likley the problem is the node.js version of your server.

both are node v20.11.1

**Comment by laijuthomas** [comment]
provideHttpClient(withFetch()) is causing issue in the server. If I import HttpClient anywhere, this issue occurs. Is there a way to resolve this issue?

**Comment by JeanMeche** [comment]
Where do you deploy your app ?

**Comment by laijuthomas** [comment]
> Where do you deploy your app ?

actually this was a node version issue in the server. The server which we use for building had node v20.11.1 but the one used for serving had a lower version. 

Thanks for the help
