### ISSUE TITLE
Cannot find module './models/config' Error: Cannot find module './models/config'

### ISSUE THREAD

**Issue by coderishu** [angular/angular-cli#2729]
> Please provide us with the following information:
> $ ng serve --port=4201
Cannot find module './models/config'

### OS?
> Windows  10. 

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version`  
ng-->$ ng --version
Cannot find module './models/config'
Error: Cannot find module './models/config'
node-->v6.6.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Nope it is using CLI i have remove angular/cli then did npm cache clean,then again i installed angular/cli.

### The log given by the failure.
> $ ng --version
Cannot find module './models/config'
Error: Cannot find module './models/config'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\cygwin64\home\ishu.mishra97\finalyear\frontpage-angular2-app-master\node_modules\angular-cli\addon\ng2\index.js:4:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

### Mention any other details that might be useful.

> Actually there is no folder or file related to this name ./model/config
> Thanks! We'll be in touch soon.

**Comment by JanStureNielsen** [comment]
@coderishu -- see http://stackoverflow.com/questions/39498978/cannot-find-module-models-config/39498979#39498979

**Comment by filipesilva** [comment]
^ what @JanStureNielsen said 💃
