### ISSUE TITLE
Replace usages of '@nguniversal/' packages with '@angular/ssr'. × Migration failed

### ISSUE THREAD

**Issue by manzonif** [angular/angular-cli#27463]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.10

### Description

When attempting to update from version 16.2.10 to version 17.3.4 using the command ng update @angular/core@17 @angular/cli@17, I encounter the following error message:

× Migration failed: Path "/src/express.tokens.ts" already exist.

### Minimal Reproduction

ng update @angular/core@17 @angular/cli@17

### Exception or Error

```text
[error] Error: Path "/src/express.tokens.ts" already exist.
    at HostTree.create (C:\Users\Fausto\AppData\Local\Temp\angular-cli-packages-KHr8dg\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:319:19)
    at D:\angular\node_modules\@schematics\angular\migrations\update-17\replace-nguniversal-engines.js:103:34
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callRuleAsync (C:\Users\Fausto\AppData\Local\Temp\angular-cli-packages-KHr8dg\node_modules\@angular-devkit\schematics\src\rules\call.js:77:18)
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.2.10
Node: 18.20.2
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 16.2.12
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1602.10
@angular-devkit/build-angular     16.2.10
@angular-devkit/build-optimizer   0.1302.1
@angular-devkit/core              16.2.10
@angular-devkit/schematics        16.2.8
@angular/cli                      16.2.10
@nguniversal/builders             16.2.0
@nguniversal/common               16.2.0
@nguniversal/express-engine       16.2.0
@schematics/angular               16.2.10
rxjs                              7.8.1
typescript                        5.4.5
zone.js                           0.14.4
```

**Comment by manzonif** [comment]
Hi,

I've identified the root cause of the issue. I have an additional version of server.ts named server-dev.ts, used for debugging purposes, which also includes ngExpressEngine. Consequently, during the update process, the script attempts to create the tokensFilePath twice.
