### ISSUE TITLE
Cannot run ng e2e inside Vagrant VM running on Windows

### ISSUE THREAD

**Issue by neilkyoung** [angular/angular-cli#2751]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10
Vagrant 1.8.1

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.17
node: 6.3.0
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
No Changes to code

### The log given by the failure.
> Normally this include a stack trace and some more information.

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

> angular-cli-test@0.0.0 pree2e /home/vagrant/frontend
> webdriver-manager update

[15:02:14] I/update - chromedriver: file exists /home/vagrant/frontend/node_modules/webdriver-manager/selenium/chromedriver_2.24linux64.zip
[15:02:14] I/update - chromedriver: unzipping chromedriver_2.24linux64.zip
[15:02:14] I/update - chromedriver: setting permissions to 0755 for /home/vagrant/frontend/node_modules/webdriver-manager/selenium/chromedriver_2.24
[15:02:14] I/update - chromedriver: v2.24 up to date
[15:02:14] I/update - selenium standalone: file exists /home/vagrant/frontend/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar
[15:02:14] I/update - selenium standalone: v2.53.1 up to date
[15:02:15] W/file_manager - geckodriver-v0.9.0-linux64.tar.gz expected length undefined, found 1237128
[15:02:15] W/file_manager - removing file: /home/vagrant/frontend/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0-linux64.tar.gz
[15:02:15] I/downloader - geckodriver: downloading version v0.9.0
[15:02:15] I/downloader - curl -o /home/vagrant/frontend/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0-linux64.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-linux64.tar.gz
[15:02:18] I/update - geckodriver: unzipping /home/vagrant/frontend/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0-linux64.tar.gz
[15:02:18] I/update - geckodriver: setting permissions to 0755 for /home/vagrant/frontend/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0

> angular-cli-test@0.0.0 e2e /home/vagrant/frontend
> protractor "./protractor.conf.js"

[15:02:18] I/direct - Using ChromeDriver directly...
[15:02:18] I/launcher - Running 1 instances of WebDriver
[15:02:19] E/launcher - Server terminated early with status 127
[15:02:19] E/launcher - Error: Server terminated early with status 127
    at Error (native)
    at /home/vagrant/frontend/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:242:20
    at ManagedPromise.invokeCallback_ (/home/vagrant/frontend/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/home/vagrant/frontend/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/home/vagrant/frontend/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/home/vagrant/frontend/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2775:27)
    at /home/vagrant/frontend/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/vagrant/frontend/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Driver (/home/vagrant/frontend/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/home/vagrant/frontend/node_modules/protractor/built/driverProviders/direct.js:68:26)
    at Runner.createBrowser (/home/vagrant/frontend/node_modules/protractor/built/runner.js:198:43)
    at /home/vagrant/frontend/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/home/vagrant/frontend/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/vagrant/frontend/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/vagrant/frontend/node_modules/q/q.js:796:13)
    at /home/vagrant/frontend/node_modules/q/q.js:556:49
    at runSingle (/home/vagrant/frontend/node_modules/q/q.js:137:13)
[15:02:19] E/launcher - Process exited with error code 199

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/nvm/versions/node/v6.3.0/bin/node" "/usr/local/nvm/versions/node/v6.3.0/bin/npm" "run" "e2e" "--" "./protractor.conf.js"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular-cli-test@0.0.0 e2e: `protractor "./protractor.conf.js"`
npm ERR! Exit status 199
npm ERR!
npm ERR! Failed at the angular-cli-test@0.0.0 e2e script 'protractor "./protractor.conf.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-cli-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor "./protractor.conf.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-cli-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-cli-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/frontend/npm-debug.log

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
I understand that the command you are running is `ng e2e`, but we just launch https://github.com/angular/protractor. I'd recommend you to open an issue there instead.
