### ISSUE TITLE
Creating unnecessary excessive chunks

### ISSUE THREAD

**Issue by ChristopherPHolder** [angular/angular-cli#27715]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

**Disclaimer**

This is not really a bug, as even if it worked differently with `webpack`, for `esbuild` this is normal. However, since the default bundler is now `esbuild` some would consider this a regression.

## Required chunks references in dynamic imported code get split in to separate chunks

When splitting code, esbuild does not seems to properly take into account what is already statically imported (thus "required") and does not need to be split into a separate chunk.

To illustrate this lets consider an example where we have the following 5 standalone components:

- `AppComponent` (The root component which is not lazy loaded)
- `Feature1Component` (A feature component lazy loaded via a dynamic import in the router)
- `Feature21Component` (A feature component lazy loaded via a dynamic import in the router)
- `Ui1Component` (A UI component imported statically, like a button)
- `Ui2Component` (A UI component imported statically, like a button)

### Chunks without Shared Components

If the `AppComponent` has a `RouterOutlet` which has separate paths `Feature1Component` and `Feature21Component` it will generate a chunk for the code shared between these components (lets call it Common Chunk). 

In this case the build output is: 

| Initial chunk files             | Names               | 
| --- | --- | 
| chunk-YIKH6UD4.js               | -  ("common")  | 
| main-V6UA4PHT.js                | main                |

| Lazy chunk files                | Names               |
| --- | --- | 
| feature-1.component-AQEBZKLJ.js | feature-1-component |
| feature-2.component-EH7EGWEP.js | feature-2-component |

And if `Feature1Component` imports  `Ui1Component` and  `Feature21Component` imports  `Ui2Component` then code from `Ui1Component` will be bundle in `Feature1Component` and the code from `Ui2Component` will be bundle in `Feature2Component`.

### Chunks with Shared Components

However, if the `AppComponent` also imports  `Ui1Component` and  `Ui2Component` this code is now shared and will be split into separate chunks.

Thus the build output will now be:

| Initial chunk files             | Names               | 
| --- | --- | 
| chunk-YIKH6UD4.js               | -  ("common")  | 
| main-V6UA4PHT.js                | main                |
| chunk-WKA4CZR7.js               | -  ("ui-1-component") |
| chunk-XCJUHD2B.js               | - ("ui-2-component") |

| Lazy chunk files                | Names               |
| --- | --- | 
| feature-1.component-AQEBZKLJ.js | feature-1-component |
| feature-2.component-EH7EGWEP.js | feature-2-component |

The issue is that `Ui1Component` and  `Ui2Component` are now statically imported in the `AppComponent`, and therefore belong in this common chunk. These chunks are statically imported in the "common" chunk and required for the application to bootstrap but are downloaded separately.

As they are always downloaded, splitting them does not seems to have a benefit, when `Feature1Component` or  `Feature2Component` imports them, the request is cached and it should not make a difference if it over imports. 

However, splitting them does have a downside, it increases the load time. Even tho in this example the consequences of a couple of extra chunks is meaningless in larger apps the consequence is very real.

If the application produces 100 or 200 initial chunks this will have a significant impact on the initial load time and LCP. 

![image](https://github.com/angular/angular-cli/assets/40126819/d8bedc9b-be77-47fc-b9ca-702e5522c110)

Even tho the a modern browser using http3 or http2 uses multiplexing it will still have an significant overhead downloading so many small chunks. We are currently calling this `the chunk gap`:

![image](https://github.com/angular/angular-cli/assets/40126819/6d8a96dc-9a8c-4877-a4f6-277514802047)

Additionally this issue will have a larger impact on older and slower devices. 

- [HTTP2 Support](https://caniuse.com/HTTP2)
- [HTTP3 Support](https://caniuse.com/HTTP3)

Additional example of performance impact: 

- https://github.com/angular/angular-cli/issues/27321

### Avoiding Code Splitting Shared Code

It seems possible to avoid additional chunking in some cases by using barrel files. 

For example if we create a barrel file that exports both `Ui1Component` and `Ui2Component` and only import them via that barrel file we are able to force `esbuild` to place the shared code into the "common" chunk. 

So using: 

```ts
// ./ui/index.ts

export * from './ui-1.component';
export * from './ui-2.component';
```

The build output will now be:

| Initial chunk files             | Names               | 
| --- | --- | 
| chunk-YIKH6UD4.js               | -  ("common")  | 
| main-V6UA4PHT.js                | main                |

| Lazy chunk files                | Names               |
| --- | --- | 
| feature-1.component-AQEBZKLJ.js | feature-1-component |
| feature-2.component-EH7EGWEP.js | feature-2-component |

**Note** 

In [`esbuild` architecture documentation](https://github.com/evanw/esbuild/blob/main/docs/architecture.md) it explains that:

> [code splitting](https://github.com/evanw/esbuild/blob/main/docs/architecture.md#code-splitting) is implemented as an advanced form of tree shaking.

This means that doing so will partially optout of tree shaking.

For example if we add a `Ui3Component` and a `Feature3Component`.

And we add the `Ui3Component` to the barrel file:

```ts
// ./ui/index.ts

export * from './ui-1.component';
export * from './ui-2.component';
export * from './ui-3.component';
```

If the `Ui3Component` is never imported anywhere it will not increase the initial bundle. 

However, if we reference the `Ui3Component` in `Feature3Component` (loading the `Feature3Component` in a lazy route), this will increase the initial bundle even if `Ui3Component` is not used in the `AppComponent`.

## Minimal Reproduction Repo

https://github.com/ChristopherPHolder/ng-esbuild-demo

### Exception or Error

```text
Shared Code Required in a root component or a root node of the node graph is bundle together.
```

### Your Environment

```text
Angular CLI: 17.3.5        
Node: 20.11.1              
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.3.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
ng-packagr                      17.3.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Comment by clydin** [comment]
Are you encountering a Core Web Vitals regression in a real world application?
If so, can you please provide the before and after metric values?
Measurements should ideally be taken from production or production-equivalent deployments. Server and/or hosting configuration can have a significant effect on the metrics.  The development server, especially, should not be used to evaluate loading performance as it is designed to optimize the edit/refresh cycle and not initial load.

Also, if possible, please consider using the latest version of Angular (currently 18.0). Earlier versions can potentially inject a large amount of `modulepreload` link elements into the generated index HTML especially in SSR cases which can lead to performance regressions.  The fix for this may be back-ported. However, preload generation can be disabled via configuration in these cases.  Also, there are numerous improvements in other areas from which the application may benefit by upgrading.

Regarding HTTP/2, any browser/device that does not have HTTP/2 will also not support running an Angular application that uses a supported major version of Angular as well as many unsupported versions.  Regardless of bundling strategy, HTTP/2 is an effective means to improving CWV metrics.

As to barrel file usage, these have long-term been a source of problems when attempting to optimizing code especially when interoperating correctly with potentially side effectful modules and/or top-level await usage.  Additionally, depending on what version of Angular was in use previously for the application, the AOT compiler itself may be involved as well. Older compiler versions rewrote component imports directly to the component implementation bypassing any intermediate re-imports. This has since been removed with one of the reasons being execution correctness. However, we are planning on some potential improvements in this area for the 18.x timeframe.  Barrel file usage also appears to be the main underlying cause for the issue as described above so such improvements may be an effective mitigation in this case.

**Comment by ChristopherPHolder** [comment]
> Are you encountering a Core Web Vitals regression in a production deployed application?

Yes, the regression is measured on a production environment. With Crux and other RUM data. 

> If so, can you please provide the before and after metric values?

In the worse case we have seems an approximate ~2 second regression on LCP. But please take into account that this is a large application with a lot of moving pieces. There are other factors there that are probably contributing to those numbers.

![image](https://github.com/angular/angular-cli/assets/40126819/c3560be7-30d0-4c51-b687-e8a568709a45)

Are other large applications experiencing these regressions?

The minimal reproduction i have build illustrates the issue but a that scale the impact will be hidden by variability. 

If its a question of proving the performance degradation I can scale the minimal reproduction, deploy it and run performance test on it.

What i would do is:
- Increase the bundle  UI components by adding random strings
- Increase the number of bundles using the same pattern
- Deploy App as Static Site on a CDN (likely S3 + CloudFront)
- Run multiple lighthouse test to compare results

I would be able to scale the minimal reproduction by increasing the bundle size of each component with random strings and 

> please consider using the latest version of Angular (currently 18.0)

I agree, using the latest supported version when possible is best.

Angular v18 was release 6 days ago on 2024-05-20.

The demo is using v17.3 and the real app is on v17.1. 

Currently v18 is not on the list of [Actively supported versions](https://angular.dev/reference/releases#actively-supported-versions)

> Regarding HTTP/2

We are using HTTP/3 

So i just wanted to mention that we are aware of the fact that if we where using HTTP/1 this change would have a massive negative impact on LCP. But we are indeed using HTTP/3

> As to barrel file usage

I am generally not a fan of barrel files. As mentioned in the issue, by doing that I might be removing some of the esbuild compilers ability to tree shake my code effectively.

> Barrel file usage also appears to be the main underlying cause for the issue as described above so such improvements may be an effective mitigation in this case.

I am not sure about that. The idea of strategically placing barrels files to optimize how the bundler chunks code seems off to me. It seems like it will be prone to errors and may produce harder to maintain code. 

That all being said using libs will produce barrel files, and so i do see how they can be necessary for some usages. But I don't think this is a valid solution for large scale applications. 

> Barrel file usage also appears to be the main underlying cause for the issue

I am using barrel files to opt out of the optimization here, i would say this is my hacky attempt to understand how this can be fixed.

I would say the issue is the way [esbuild currently handles code splitting](https://github.com/evanw/esbuild/blob/main/docs/architecture.md#code-splitting) and more specifically this statement: 

> > Note that the target of each dynamic import() expression is considered an additional entry point.

I have opened an[ issue on esbuild](https://github.com/evanw/esbuild/issues/3780) itself to discusses this and see if there is a potential solution there.

**Comment by sod** [comment]
Some people tried to get a [minChunkSize option into esbuild](https://github.com/evanw/esbuild/pull/3302), with no success yet, though.

**Comment by ChristopherPHolder** [comment]
@sod the solution is nice and it allows me to use a custom chunking strategy. But the issue i am facing when rebundling with rollup is that i loose the sourcemaps. 

if rollup produces sourcemaps it will produce them based on the chunks as an input which makes it not useful.

Do you know if there is a way i can tell rollup to merge the original sourcemaps instead of producing a completely new one?

**Comment by sod** [comment]
try https://github.com/maxdavidson/rollup-plugin-sourcemaps - can't confirm if it works, we don't use sourcemaps in production.

**Comment by dimeloper** [comment]
@sod can you please provide an example of how you made the rollup command work in combination with the sourcemaps plugin?

I tried `rollup --format es -d ./ -- main-2ZWZBTDC.js -p rollup-plugin-sourcemaps` but didn't work for me. Obviously I'm doing something wrong.

**Comment by sod** [comment]
We don't use sourcemaps in production.

**Comment by dimeloper** [comment]
I see, currently we are more or less blocked in my team and are not able to the application builder, since as you can see in the attached screenshot the esbuild version generates way too many JS requests, which cause a significant performance downgrade. 

![CleanShot 2024-07-09 at 13 32 51@2x](https://github.com/angular/angular-cli/assets/2801022/41ac47ef-2421-41ad-b4f6-d55e55497419)

The rollup command that  @sod kindly wrote in his comment removes ~60% of the chunks which is great 🎉  but it causes errors like this to our app in random places: 
```
Error: no ngModuleRef constructor found
    at chunk-UKEZH6HP-Djqkv2-u.js:246:4618
    at Generator.next (<anonymous>)
    at n (chunk-UKEZH6HP-Djqkv2-u.js:1:1248)
    at k.invoke (zone.js:368:26)
    at Object.onInvoke (chunk-UKEZH6HP-Djqkv2-u.js:9:52548)
    at k.invoke (zone.js:367:52)
    at se.run (zone.js:130:43)
    at zone.js:1260:36
    at k.invokeTask (zone.js:403:31)
    at Object.onInvokeTask (chunk-UKEZH6HP-Djqkv2-u.js:9:52359)
    at k.invokeTask (zone.js:402:36)
    at se.runTask (zone.js:174:47)
    at E (zone.js:582:35)
```

..which basically prevent some of our components from being loaded and makes some of its features unusable. I thought that maybe modifying the command to utilize the sourcemaps plugin might have some positive impact, but maybe I was just too desperate. Has anyone encountered a similar issue?

**Comment by ChristopherPHolder** [comment]
@dimeloper I suppose you issue is related to circular dependencies created by rollup. This is because of [you use](https://github.com/angular/angular-cli/pull/27953#issuecomment-2217363005) `minChunkSize` which is [still experimental](https://rollupjs.org/configuration-options/#output-experimentalminchunksize).

The issue with preventing these circular dependencies is not trivial. And i have had partial success on applications with 200 or so initial bundles but the solution was flacky. 

However achiving 1 initial bundle using manualChunks does work fine. 

I am still in the process of publishing it but you can copy the executor into you project and it should work. [Git Repo](https://github.com/ChristopherPHolder/ngx-build/)

If you have any issues with that solution let me know, I only have half or so of it in that repo.

**Comment by alan-agius4** [comment]
In version 18.1, we introduced an experimental chunk optimizer. Has anyone tried it? If so, what were the results?

For more context, please refer to this https://github.com/angular/angular-cli/pull/27953

**Comment by dimeloper** [comment]
Hey @alan-agius4 I had tried that optimiser in my case, feel free to check out the full thread in the Angular discord channel for more details: https://discord.com/channels/748677963142135818/1260214060830556211/1260535860131270691

Long story short, the results weren't really helpful in my case, I had to rework my app and fine tune the rollup post build script to achieve a sensible amount of chunks (we still have the rollup step in our pipelines).

**Comment by alan-agius4** [comment]
@dimeloper, you mentioned that the environment variables are being ignored. I'm not familiar with how `env-cmd` functions, but typically, environment variables need to have their values defined as strings.

**Comment by dimeloper** [comment]
@alan-agius4 ok but I tried it like `NG_BUILD_OPTIMIZE_CHUNKS=1` and like `NG_BUILD_OPTIMIZE_CHUNKS="1"` - how should I declare it instead, so as to to see it working? And is there a log message or something during the build process that I can see and confirm that the optimiser was enabled?

**Comment by sod** [comment]
The `NG_BUILD_OPTIMIZE_CHUNKS=1` is very nice and works as advertised. I'm probably going to use it, when we switch.

We are still stuck on webpack though, as I can't get the esbuild variant to perform as good. Webpack has some incredible features like:

1. Multiple initial "dependOn" chunks. This allows to extract parts of the code into another chunk that can be loaded first (similar to polyfills file) but with the trick, that the other chunks can reuse exports from it. This allows dependencies like tracking and errors tracking (like sentry) be loaded and executed first, while the browser is parsing the the 2 megabyte app. This saves a couple of two digit milliseconds
2. The custom webpack loader allowed to preload dependencies, so at the moment the app runs, everything is already in memory, allowing the app to render in a single swoop. The new es module style doesn't allow that, which causes the renderer to stop for every lazy chunk (like the route, the header, the footer).
3. The `() => import(/* webpackMode: "eager" */'./my-dependency')` pattern from webpack is quite powerful, as with this you could force it to be included in the initial chunk, but not yet executed. This reduces the burden on the browser as it doesn't have to execute parts of the app initially, but the code will be ready asap when needed without loading extra chunks.

(2) and (3) you kind of solved by partial hydration, but [that is not yet supported without zone.js](https://angular.dev/guide/hydration#custom-or-noop-zonejs-are-not-yet-supported), so we are sticking to webpack right now.

**Comment by dimeloper** [comment]
@alan-agius4 I tried it once again using your debugging hint. This is the output I am getting having the optimiser enabled:

```
DURATION[NG_READ_CONFIG]: 0.039898750s
DURATION[NG_READ_CONFIG]: 0.055066417s
DURATION[NG_CREATE_PROGRAM]: 4.416569292s
DURATION[NG_ANALYZE_PROGRAM]: 5.477037292s
DURATION[NG_FIND_AFFECTED]: 0.005789167s
DURATION[NG_EMIT_TS]: 12.525402208s
DURATION[NG_DIAGNOSTICS_TOTAL]: 2.308133416s
DURATION[NG_EMIT_JS*]: 822.466522754s [count: 1875; avg: 0.438648812s; min: 0.003237000s; max: 1.184354959s]
DURATION[NG_EMIT_JS*]: 822.466522754s [count: 1875; avg: 0.438648812s; min: 0.003237000s; max: 1.184354959s]
chunk-UDIDPQ7Z.js (1:49305): Use of eval in "chunk-UDIDPQ7Z.js" is strongly discouraged as it poses security risks and may cause issues with minification.
DURATION[OPTIMIZE_CHUNKS]: 7.984619542s
```

As seen in the last line, it looks like the optimiser is enabled.

However the amount of chunks remains unchanged (dist folder contains the normal build output and dist-optimized contains the one using the optimiser):
![CleanShot 2024-09-06 at 13 22 42](https://github.com/user-attachments/assets/28a4bb51-0686-4a3f-8e80-86a05fc89928)

Before switching to the application builder and ESBuild we used to have 326 chunks in total....

**Comment by alan-agius4** [comment]
@dimeloper, unfortunately without a reproduction it’s hard to tell why the chunks count remained the same.

**Comment by ChristopherPHolder** [comment]
@dimeloper 
Ran a quick test on using the setup for the environmental variable you provided and i see it did not work. The issue that its not present for the angular builder or at least not present at the right time. 

But there is an easy fix, instead of providing it to the executor using the define options simply create a .env file and set the env there.

**Comment by tobias-lippert** [comment]
@ChristopherPHolder Could you please elaborate on how you fixed it with the env file because for me it doesn't make a difference when I define it in an env file.

**Comment by slak44** [comment]
To add to this issue, I encountered situations where it's even more obvious how excessive the chunks are (angular 19.1).

For example, if I have a file with a string constant that's used in a few places in my app:
```typescript
export const MY_USEFUL_SHARED_CONSTANT = 'some-useful-text';
```

I get a chunk/module that looks like this:
```js
var e="some-useful-text";export{e as a};
```

Which I think is absolute nonsense, there is no reason not to inline it and get rid of the chunk entirely.
This should already be within the abilities of esbuild, since doing the exact same thing with a .json does actually inline the string (I am importing just the version field from package.json, and that doesn't generate a new module...)

**Comment by sod** [comment]
Found this issue today https://github.com/GoogleChrome/lighthouse/issues/16539. So those chunks may not necessarily ruin the performance for your customer, but lighthouse seems to punish you for every single javascript request as its mobile simulation adds it to the LCP and FCP metric, even if your SSR already returned visually complete DOM.

**Comment by DzmVasileusky** [comment]
+1 
We have 276 initial chunks and most of them are < 1kb ungzipped. This is crazy, server waiting time is growing with each next chunk.

**Comment by anuj-scanova** [comment]
This seems to be the reason for the downfall of Angular. After using Angular for 10+ years, starting from AngularJS, we are now switching to another framework just because of this issue. 
After the recent upgrade of the Angular version has experienced poor performance of the application and it is sad that no one is looking into this.
We have already tried other frameworks based on React, and they are doing great.

**Comment by imaksp** [comment]
Hi, `NG_BUILD_OPTIMIZE_CHUNKS` option has reduced raw size of initial bundle significantly (from 3.16MB to 1.28MB) in one of our app, it is also reducing total number of chunks (from 143 to 138) but it still has so many lazy chunks .  Hopefully new Rolldown experiment works and solves this issue related to esbuild and also the issue with dynamic import tree-shaking.

**Comment by ChristopherPHolder** [comment]
> `NG_BUILD_OPTIMIZE_CHUNKS` option has reduced raw size of initial bundle significantly (from 3.16MB to 1.28MB)

I highly doubt that, it not likely that you have a 3x reduction in bundle size. most likely there is an error in the computation of the new bundle cause it to ignore some of the bundles. How did you reach that conclusions?

**Comment by imaksp** [comment]
> > `NG_BUILD_OPTIMIZE_CHUNKS` option has reduced raw size of initial bundle significantly (from 3.16MB to 1.28MB)
> 
> I highly doubt that, it not likely that you have a 3x reduction in bundle size. most likely there is an error in the computation of the new bundle cause it to ignore some of the bundles. How did you reach that conclusions?

Hi, I don't have before screenshot currently but result is consistent across 3 of our  apps, it removes all chunks from initial bundle (keeps single main js file) and moves rest to lazy chunks, earlier initial bundle had many chunks (I think around 12 and around 115 lazy), this is build screenshot from one of our app (after adding this flag).

<img width="749" height="553" alt="Image" src="https://github.com/user-attachments/assets/5584881a-4970-48e8-8271-d2a081ebe903" />

**Comment by jsaguet** [comment]
I'm having issues with the chunk optimizer since version 20.2.0. It seems to be much less effective now that rolldown is used instead of rollup.

For example in my app, here is the number of generated js files per version (same application code)
| Version | NG_BUILD_OPTIMIZE_CHUNKS=0 | NG_BUILD_OPTIMIZE_CHUNKS=1 |
| ------------- | ------------- | -------------|
| 20.1 (rollup) | 448 | 241 |
| 20.2 (rolldown) | 449 | 442 |

Has anyone else experienced the same thing ?

**Comment by phpbg** [comment]
Same here: lots on <1kb chunks.
After some investigation, they seems to contains, for example:
 * one single pipe
 * one single service
 * one single enum
 * one single directive

This is a bit too much I think (at least for a single enum).

<img width="466" height="629" alt="Image" src="https://github.com/user-attachments/assets/448fea5a-641e-4f5c-8b61-e818cf14e1eb" />

**Comment by phpbg** [comment]
Previous similar issues were closed as won't fix: 
* https://github.com/angular/angular-cli/issues/27418
* https://github.com/angular/angular-cli/issues/26307

I am not sure if HTTP/2+ mitigates the high number of chunks. Indeed very small chunks defeats compression, so the whole transfer size may be higher.

I don't know very well rollup/rolldown, but there are flags to set a minimum chunk size, which would solve the issue I guess. It would be nice to allow such a configuration flag in `angular.json`: https://github.com/rolldown/rolldown/issues/4932

**Comment by phpbg** [comment]
Here are quick metrics from the same environment.
Note that due to internal enterprise constraints files are served over HTTP1.1.

# Before
<img width="744" height="602" alt="Image" src="https://github.com/user-attachments/assets/28b17303-920c-4c57-95cf-ba89a9bbc030" />
<img width="709" height="24" alt="Image" src="https://github.com/user-attachments/assets/0ed0853f-d28c-4ca9-a02b-386e19747079" />

# After
<img width="744" height="602" alt="Image" src="https://github.com/user-attachments/assets/c76d321f-ea08-4159-ade4-ada199248169" />
<img width="709" height="24" alt="Image" src="https://github.com/user-attachments/assets/a5913728-0ecf-461c-8e1f-b60966cbd327" />

# Results
* 10x requests
* degraded transfer size
* 2x DomContentLoaded event time
* 5x load event time
* LCP degradation
* FCP slightly improved 
* From a (subjective) user perspective: slower loading time

**Comment by al0xf** [comment]
You can see where the upgrade happened here on our Fastly dashboard showing total requests per day. Never mind any performance impact, there is also an impact on our bills...

<img width="2854" height="1362" alt="Image" src="https://github.com/user-attachments/assets/86ed0947-66a3-43c9-9fe1-9219d3796d06" />

**Comment by phpbg** [comment]
@alan-agius4 do you still need more info (tag "needs: more info")?

**Comment by PowerKiKi** [comment]
Could the Angular team clarify why `NG_BUILD_OPTIMIZE_CHUNKS` is still experimental (according to the recent #30765) ? what would be required before it becomes stable ? and whether there is a possibility that this might be the default behavior in the (far?) future ?

Also, out of curiosity, why is this implemented as env var, and not as an `angular.json` option ? and why all env vars seems to be entirely undocumented ? Grepping the source code I find ~60 things that might be env var and that might or might not be part of the public API... How are we supposed to discover those and know whether there are part of a public, stable, API ?

**Comment by imaksp** [comment]
Hi, it might be because [Rolldown](https://rolldown.rs/) is still in beta, but as per my testing it just removes chunks from initial bundle, it does not reduce total chunks (including lazy) by much.

**Comment by imaksp** [comment]
Some updated stats from one of our app (_@angular/build_ version 20.3.4):

Without rolldown optimization (_default_):
Total chunks count: **135**
Initial total: **3.38 MB**

With _NG_BUILD_OPTIMIZE_CHUNKS_:
Total chunks count: **99** (so its **working now** but it still has many _<1kB_ and _<2kb_ chunks)
Initial total: **3.46 MB** (no chunks in initial bundle - all 99 are lazy but main bundle size has increased)

**Comment by ChristopherPHolder** [comment]
I figure it would be worth adding this:

This is the impact of adding chunks. 

Basically i rendered an app and each route displays basically the same content but the content is split by being referenced in dynamic entries

<img width="611" height="384" alt="Image" src="https://github.com/user-attachments/assets/a79158ff-e887-424f-b21c-b5a7be562671" />


| Extra Chunks | LCP   | TEST Results |
|---------------|-------|--------------|
| STUB          | 1.611 | [250911_YiDcVG_5NC](https://www.webpagetest.org/result/250911_YiDcVG_5NC/) |
| 0             | 2.951 | [250911_YiDcRH_5NZ](https://www.webpagetest.org/result/250911_YiDcRH_5NZ/) |
| 20            | 3.241 | [250911_YiDcNG_5NN](https://www.webpagetest.org/result/250911_YiDcNG_5NN/) |
| 100           | 3.568 | [250911_YiDcSB_5NY](https://www.webpagetest.org/result/250911_YiDcSB_5NY/) |
| 250           | 4.370 | [250911_YiDcVG_5N](https://www.webpagetest.org/result/250911_YiDcVG_5N/) |
| 500           | 5.788 | [250911_YiDcAP_5NJ](https://www.webpagetest.org/result/250911_YiDcAP_5NJ/) |

**Comment by Azbesciak** [comment]
Is there any ETA to completely address that issue?
That does not look appealing, not to mention migrations are said to be seamless and rather improve the performance (as the whole esbuild migration was promising), whereas we have basic, rather not expected issues.

**Comment by sefatanam** [comment]
chunk after chunk, the horrible thing for me is now I can't see the imitator name from chrome devtool(network tab) instead showing chunks_ASDF, does anyone know how to get rid of it ?

<img width="1298" height="1474" alt="Image" src="https://github.com/user-attachments/assets/9e4e225d-0dc4-4609-9ecb-0034248fb168" />

**Comment by imaksp** [comment]
It seems ESBuild has issues with tree shaking too, it can't tree shake modern  [viem](https://viem.sh/) lib properly, so as a workaround we need to pull some of its sub-dependencies directly. 
only 4 functions _isAddress, formatUnits, getAddress, isAddressEqual_ were pulling `~200kB` raw in our initial bundle. barrel import did not fix it either (from Claude: the _viem/utils_ barrel drags in constants/abis, constants/contracts, errors/{rpc,abi,contract,transaction}, actions/public/call, parseTransaction, @noble/curves signing (secp256k1/weierstrass), and abitype)

Also it seems `NG_BUILD_CHUNKS_ROLLDOWN=1` has a reporting error, if we turn this on it significantly reduces Initial bundle size in build report , but actual diff was ~1% (for gzipped version)

**Comment by delagen** [comment]
Was ~1600 files, with NG_BUILD_CHUNKS_ROLLDOWN=1 now ~2400. Good optimization ;)

**Comment by eggsys** [comment]
is this issue got solve by upgrading Angular version ?

**Comment by ChristopherPHolder** [comment]
> is this issue got solve by upgrading Angular version ?

I dont think this is something that will get "fixed" as its not really a regression or a bug but a core decition in the bundler. 

I wrote an article about it in case you want to read more about it https://push-based.io/article/faster-builds-slower-applications-optimizing-angulars-bundle-output

Also we opensourced an experimental optimization that in most cases should work better then the default optimizer used in case someone wants to try it out we are open to feedback https://www.rx-angular.io/docs/packages/rebundle
