### ISSUE TITLE
[error] TypeError: Cannot read properties of undefined (reading 'code')

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular-cli#28003]
### Command

new

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

no idea

### Description

ng new is failing with a TypeError

### Minimal Reproduction

ng new demo

### Exception or Error

```text
[error] TypeError: Cannot read properties of undefined (reading 'code')
    at addFormats (/home/yadav/.config/yarn/global/node_modules/ajv-formats/dist/index.js:30:26)
    at formatsPlugin (/home/yadav/.config/yarn/global/node_modules/ajv-formats/dist/index.js:15:5)
    at new CoreSchemaRegistry (/home/yadav/.config/yarn/global/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/schema/registry.js:100:35)
    at new BaseWorkflow (/home/yadav/.config/yarn/global/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/workflow/base.js:47:30)
    at new NodeWorkflow (/home/yadav/.config/yarn/global/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/workflow/node-workflow.js:33:9)
    at NewCommandModule.getOrCreateWorkflowForBuilder (/home/yadav/.config/yarn/global/node_modules/@angular/cli/src/command-builder/schematics-command-module.js:74:16)
    at NewCommandModule.value (/home/yadav/.config/yarn/global/node_modules/@angular/cli/src/utilities/memoize.js:37:43)
    at NewCommandModule.getCollectionFromConfig (/home/yadav/.config/yarn/global/node_modules/@angular/cli/src/commands/new/cli.js:64:35)
    at async NewCommandModule.builder (/home/yadav/.config/yarn/global/node_modules/@angular/cli/src/commands/new/cli.js:32:15)
    at async runCommand (/home/yadav/.config/yarn/global/node_modules/@angular/cli/src/command-builder/command-runner.js:76:5)
```

### Your Environment

```text
$ node -v
v20.15.0
[Sat Jul 06 14:02:22][yadav@source]:~
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.0.7
Node: 20.15.0
Package Manager: yarn 1.22.22
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1800.7 (cli-only)
@angular-devkit/core         18.0.2 (cli-only)
@angular-devkit/schematics   18.0.7 (cli-only)
@schematics/angular          18.0.7 (cli-only)

System Info

Operating System: openSUSE Tumbleweed 20240704
KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.2
Kernel Version: 6.9.7-1-default (64-bit)
Graphics Platform: X11
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7A38
System Version: 8.0
```

**Comment by rajinder-yadav** [comment]
I reinstalled ng cli and the problem seems to have gone.
I  installed using npm this time rather than yarn, not sure it something get mixed up.
