### ISSUE TITLE
ng init does not create assets folder if it's missing

### ISSUE THREAD

**Issue by kaznovac** [angular/angular-cli#2813]
### OS?
Windows 10

### Versions.
angular-cli: 1.0.0-beta.18
node: 6.6.0
os: win32 x64

### Repro steps.
create an empty ng-cli project inplace
- `npm init`
- `npm install --save-dev angular-cli`
- `node_modules\.bin\ng init`

### The log given by the failure.
ENOENT: no such file or directory, stat 'c:\src\ng2\src\assets'
Error: ENOENT: no such file or directory, stat 'c:\src\ng2\src\assets'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at c:\src\ng2\node_modules\angular-cli\plugins\glob-copy-webpack-plugin.js:16:64
    at Array.map (native)
    at GlobCopyWebpackPlugin.apply (c:\src\ng2\node_modules\angular-cli\plugins\glob-copy-webpack-plugin.js:16:29)
    at Compiler.apply (c:\src\ng2\node_modules\tapable\lib\Tapable.js:233:16)
    at WebpackOptionsApply.process (c:\src\ng2\node_modules\webpack\lib\WebpackOptionsApply.js:59:18)
    at webpack (c:\src\ng2\node_modules\webpack\lib\webpack.js:28:48)
    at Class.run (c:\src\ng2\node_modules\angular-cli\tasks\build-webpack.js:20:31)
    at Class.run (c:\src\ng2\node_modules\angular-cli\commands\build.js:50:26)
    at Class.<anonymous> (c:\src\ng2\node_modules\angular-cli\lib\models\command.js:152:17)
    at tryCatch (c:\src\ng2\node_modules\rsvp\dist\lib\rsvp\-internal.js:215:12)
    at invokeCallback (c:\src\ng2\node_modules\rsvp\dist\lib\rsvp\-internal.js:230:13)
    at c:\src\ng2\node_modules\rsvp\dist\lib\rsvp\then.js:29:16
    at flush (c:\src\ng2\node_modules\rsvp\dist\lib\rsvp\asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

### Mention any other details that might be useful.
with global installation and `ng new` app works as expected

**Comment by ValerieEskens** [comment]
creating the assets folder manually fixed it for me... (not ideal though)

**Comment by filipesilva** [comment]
That was a limitation of having the entry as a string actually... Now it's an array, you can leave it empty if you want. Regardless, the folder or files won't be created for you if they don't exist, that bit is intentional.

**Comment by iyunusov** [comment]
Turns out, in my case I have accidentally moved assets directory from `angular-cli/src` to  `angular-cli/src/environments` by drag&drop in Atom. So make sure you have this directory created in `angular-cli/src` ;)
