### ISSUE TITLE
Not getting i18n to work

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular-cli#2814]
> ## Please provide us with the following information:
### OS?

Mac OS X Sierra
### Versions.

2.1.0 
### Repro steps.

Added one single i18n attribute to a paragraph tag on one of my components like so:

```
<p i18n="Test title|Test description">Welcome to i18n</p>
```
### The log given by the failure.

```
| => ./node_modules/.bin/ng-xi18n 
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts, resolving symbol AppModule in /Users/crash/git/traveliko/traveliko-spa-frontend/src/app/app.module.ts
    at simplifyInContext (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@angular/compiler-cli/src/static_reflector.js:469:23)
    at StaticReflector.simplify (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@angular/compiler-cli/src/static_reflector.js:472:22)
    at StaticReflector.annotations (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@angular/compiler-cli/src/static_reflector.js:61:36)
    at _loop_1 (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@angular/compiler-cli/src/extract_i18n.js:67:54)
    at Extractor.readFileMetadata (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@angular/compiler-cli/src/extract_i18n.js:80:13)
    at /Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@angular/compiler-cli/src/extract_i18n.js:87:74
    at Array.map (native)
    at Extractor.extract (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@angular/compiler-cli/src/extract_i18n.js:87:35)
    at extract (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@angular/compiler-cli/src/extract_i18n.js:16:35)
    at Object.main (/Users/crash/git/traveliko/traveliko-spa-frontend/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
Extraction failed
```
### Mention any other details that might be useful.

I am using module lazy loading.

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by jfmaeck** [comment]
Perhaps specifying the tsconfig.json might help?

```
./node_modules/.bin/ng-xi18n -p src/tsconfig.json
```

Or in package.json:
```
  ...
  "scripts": {
    "i18n": "ng-xi18n -p src/tsconfig.json"
  }
  ...
```

**Comment by bjornharvold** [comment]
Same error I'm afraid. I don't even know if this is an Angular CLI issue or if it is with Angular itself.

**Comment by spotnape** [comment]
I also have this error.

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/issues/2201
