### ISSUE TITLE
Simbols not supported on Dir

### ISSUE THREAD

**Issue by SebastianAviles** [angular/angular-cli#28158]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I tried to run NG SERVE on my app, when the app is in a folder with simbol, example c:\#Projects\App\, the app not work, throw error, This not happend if I delete the # from dir

![image](https://github.com/user-attachments/assets/d5b3bd34-8cce-4bc0-90f8-5ba15eac2eb5)

### Minimal Reproduction

new project on #named folder
ng serve

### Exception or Error

```text
Vite Error, /@fs/C:/?import#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_platform-browser.js?v=ad9c3d8d optimized info should be defined
Vite Error, /@fs/C:/?import#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_core.js?v=ad9c3d8d optimized info should be defined
Vite Error, /@fs/C:/?import#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_router.js?v=ad9c3d8d optimized info should be defined
Vite Error, /@fs/C:/?import#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_core.js?v=ad9c3d8d optimized info should be defined
Vite Error, /@fs/C:/?import#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_router.js?v=ad9c3d8d optimized info should be defined
Vite Error, /@fs/C:/?import#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_core.js?v=ad9c3d8d optimized info should be defined
7:59:25 p. m. [vite] Pre-transform error: The file does not exist at "C:/#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_core.js?v=ad9c3d8d" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.  
7:59:25 p. m. [vite] Pre-transform error: The file does not exist at "C:/#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_core.js?v=ad9c3d8d" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`. (x2)
7:59:25 p. m. [vite] Pre-transform error: The file does not exist at "C:/#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_core.js?v=ad9c3d8d" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`. (x3)
7:59:25 p. m. [vite] Pre-transform error: The file does not exist at "C:/#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_platform-browser.js?v=ad9c3d8d" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.
7:59:25 p. m. [vite] Pre-transform error: The file does not exist at "C:/#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_router.js?v=ad9c3d8d" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.
7:59:25 p. m. [vite] Pre-transform error: The file does not exist at "C:/#Proyectos/GayApp/Frontend/GayApp/.angular/cache/18.1.3/vite/deps/@angular_router.js?v=ad9c3d8d" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`. (x2)
7:59:25 p. m. [vite] Pre-transform error: EISDIR: illegal operation on a directory, read C:/
7:59:25 p. m. [vite] Internal server error: EISDIR: illegal operation on a directory, read C:/
      at async readFileHandle (node:internal/fs/promises:553:24)
      at async loadAndTransform (file:///C:/%23Proyectos/GayApp/Frontend/GayApp/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:52356:16)
7:59:27 p. m. [vite] Internal server error: EISDIR: illegal operation on a directory, read C:/
      at async readFileHandle (node:internal/fs/promises:553:24)
7:59:27 p. m. [vite] Internal server error: EISDIR: illegal operation on a directory, read C:/
      at async readFileHandle (node:internal/fs/promises:553:24)
      at async loadAndTransform (file:///C:/%23Proyectos/GayApp/Frontend/GayApp/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:52356:16)
      at async viteTransformMiddleware (file:///C:/%23Proyectos/GayApp/Frontend/GayApp/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:62168:24) (x2)
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.1.3
Node: 20.16.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 18.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.3
@angular-devkit/build-angular   18.1.3
@angular-devkit/core            18.1.3
@angular-devkit/schematics      18.1.3
@schematics/angular             18.1.3
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```

### Anything else relevant?

SO: Windows 11

**Comment by JoostK** [comment]
This is a Vite limitation (vitejs/vite#13123), as already hightlighted as a warning in your screenshot.

**Comment by SebastianAviles** [comment]
Ok, I hope some day Vite people fix that. :)
