### ISSUE TITLE
migration use-application-builder do not find src/main.ts

### ISSUE THREAD

**Issue by FGiesche** [angular/angular-cli#28151]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Can not run migration use-application-builder, file src/main.ts exists

### Minimal Reproduction

upgraded from angular 17.3.10 to 18.1.3, run ng update @angular/cli --name use-application-builder afterwards

![Capture](https://github.com/user-attachments/assets/e8cdde9d-100c-4d1d-99fd-5b2a1b309651)

### Exception or Error

```text
[error] Error: Path "src/main.ts" does not exist.
    at HostTree.readText (D:\git\fagi\AngularPortalTemplate\at.AngularPortalTemplate\ClientApp\node_modules\@angular-devkit\schematics\src\tree\host-tree.js:220:19)
    at getSourceFile (D:\git\fagi\AngularPortalTemplate\at.AngularPortalTemplate\ClientApp\node_modules\@schematics\angular\utility\standalone\util.js:55:26)
    at findBootstrapApplicationCall (D:\git\fagi\AngularPortalTemplate\at.AngularPortalTemplate\ClientApp\node_modules\@schematics\angular\utility\standalone\util.js:61:24)
    at isStandaloneApp (D:\git\fagi\AngularPortalTemplate\at.AngularPortalTemplate\ClientApp\node_modules\@schematics\angular\utility\ng-ast-utils.js:98:49)
    at D:\git\fagi\AngularPortalTemplate\at.AngularPortalTemplate\ClientApp\node_modules\@schematics\angular\ssr\index.js:281:65
    at async callRuleAsync (D:\git\fagi\AngularPortalTemplate\at.AngularPortalTemplate\ClientApp\node_modules\@angular-devkit\schematics\src\rules\call.js:77:18)
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.1.3
Node: 22.2.0
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.3
@angular-devkit/build-angular   18.1.3
@angular-devkit/core            18.1.3
@angular-devkit/schematics      18.1.3
@schematics/angular             18.1.3
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
