### ISSUE TITLE
BUG:  The document object is not available in this context after upgrading to 18.2.0-next.3

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#28166]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18.2.0-next.2

### Description

After upgrading from 18.2.0-next.2 to 18.2.0-next.3, the ng serve command is throwing below error:

```
ERROR RuntimeError: NG0210: The document object is not available in this context. Make sure the DOCUMENT injection token is provided.
    at getDocument (D:\MyProject\.angular\cache\18.2.0-next.3\vite\deps_ssr\chunk-O5CPOQCZ.js:6618:9)

```

### Minimal Reproduction

@alan-agius4 you can run `ng serve` on the private repo I shared with you for reproduction.

### Exception or Error

```text
ERROR RuntimeError: NG0210: The document object is not available in this context. Make sure the DOCUMENT injection token is provided.
    at getDocument (D:\MyProject\.angular\cache\18.2.0-next.3\vite\deps_ssr\chunk-O5CPOQCZ.js:6618:9)

```
```


### Your Environment

```text
Angular CLI: 18.2.0-next.3
Node: 20.12.2
Package Manager: npm 10.6.0
OS: win32 x64

Angular: 18.2.0-next.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, material, platform-browser
... platform-browser-dynamic, platform-server, pwa, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.0-next.3
@angular-devkit/build-angular   18.2.0-next.3
@angular-devkit/core            18.1.2
@angular-devkit/schematics      18.1.2
@angular/fire                   18.0.1
@schematics/angular             18.1.2
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.8
```

**Comment by naveedahmed1** [comment]
Thanks Alan for your prompt response, I am facing this in `18.2.0-next.3`, I think this is the most recent release, right?
