### ISSUE TITLE
Command `ng build` fails behind corporate proxy

### ISSUE THREAD

**Issue by Shemplo** [angular/angular-cli#28180]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have such stylesheets links (and nothing else more) in `index.html:`
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
```

In `angular.json` as schematics I use:
```
"schematics": {
    "@schematics/angular:component": {
        "style": "scss"
    }
}
```
and `@angular-devkit/build-angular:application` as builder

There is corporate proxy server with address `10.128.0.90:8080` for HTTP and HTTPS. I used to set up proxy configuration in linux and NPM:
```
export HTTP_PROXY=10.128.0.90:8080
export HTTPS_PROXY=10.128.0.90:8080
npm config set proxy http://10.128.0.90:8080
npm config set https-proxy https://10.128.0.90:8080
```
NPM works well

### Minimal Reproduction

* Command `ng build`

### Exception or Error

```text
An unhandled exception occurred: Invalid URL
See "/tmp/ng-Q1XcXA/angular-errors.log" for further details.

------------- angular-errors.log ---------------------------
[error] TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at new HttpsProxyAgent (/.../src/main/webapp/web-frontend/node_modules/https-proxy-agent/dist/index.js:54:50)
    at InlineFontsProcessor.getResponse (/.../src/main/webapp/web-frontend/node_modules/@angular/build/src/utils/index-file/inline-fonts.js:188:21)
    at InlineFontsProcessor.processURL (/.../src/main/webapp/web-frontend/node_modules/@angular/build/src/utils/index-file/inline-fonts.js:235:37)
    at InlineFontsProcessor.process (/.../main/webapp/web-frontend/node_modules/@angular/build/src/utils/index-file/inline-fonts.js:115:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IndexHtmlGenerator.runPlugins (/.../src/main/webapp/web-frontend/node_modules/@angular/build/src/utils/index-file/index-html-generator.js:60:28)
    at async IndexHtmlGenerator.process (/.../src/main/webapp/web-frontend/node_modules/@angular/build/src/utils/index-file/index-html-generator.js:44:19)
    at async executePostBundleSteps (/.../src/main/webapp/web-frontend/node_modules/@angular/build/src/builders/application/execute-post-bundle.js:48:62)
    at async executeBuild (/.../src/main/webapp/web-frontend/node_modules/@angular/build/src/builders/application/execute-build.js:113:24)
```

### Your Environment

```text
--------- result of `ng version` ---------------------------
Angular CLI: 18.1.2
Node: 20.16.0
Package Manager: npm 10.8.2
OS: linux x64

Angular: 18.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.2
@angular-devkit/build-angular   18.1.2
@angular-devkit/core            18.1.2
@angular-devkit/schematics      18.1.2
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             18.1.2
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```

### Anything else relevant?

When I tried to build same application on machine with direct access to the Internet, build finished successfully

**Comment by alan-agius4** [comment]
The issue is that both `HTTP_PROXY` and `HTTPS_PROXY` are missing the protocol part in their URLs, rendering them invalid.

**Comment by Shemplo** [comment]
You are right! Thanks for the help
