### ISSUE TITLE
The service was stopped

### ISSUE THREAD

**Issue by Ahmed-Elbadry99** [angular/angular-cli#28227]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

when i run server i got this message
An unhandled exception occurred: The service was stopped
See "C:\Users\AE6CA~1.ELB\AppData\Local\Temp\ng-51TnuX\angular-errors.log" for further details.

### Minimal Reproduction

ok

### Exception or Error

```text
[error] Error: The service was stopped
    at C:\Users\A.elbadry\AppData\Roaming\my-new-project\node_modules\esbuild\lib\main.js:993:26
    at responseCallbacks.<computed> (C:\Users\A.elbadry\AppData\Roaming\my-new-project\node_modules\esbuild\lib\main.js:622:9)
    at Socket.afterClose (C:\Users\A.elbadry\AppData\Roaming\my-new-project\node_modules\esbuild\lib\main.js:613:28)
    at Socket.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Your Environment

```text
Angular CLI: 18.2.0
Node: 22.0.0
Package Manager: npm 10.5.1
OS: win32 x64

Angular: 18.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.0
@angular-devkit/build-angular   18.2.0
@angular-devkit/core            18.2.0
@angular-devkit/schematics      18.2.0
@schematics/angular             18.2.0
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else relevant?

no

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Ahmed-Elbadry99** [comment]
every time i create new project i got this error

**Comment by alan-agius4** [comment]
In that case, it's likely something to do with the environment.

**Comment by sod** [comment]
We get this error:
```log
[error] Error: The service was stopped
    at [...]\node_modules\esbuild\lib\main.js:993:26
    ...
```
as well, when we abort `ng serve` mid build via `CTRL+c`. Happens since we upgraded to 18.2.0. Seems like `esbuild` is not a good citizen here and is confused when the cli is mid-shutdown and throws its own error. Maybe some parts of `esbuild` are disposed/stopped, but not all of it.

I could solve it locally by adding:

```
process.on('SIGINT', () => {
    esbuild_1.stop();
});
```

And the `esbuild.stop()` seems to fully terminate esbuild.

Maybe for you something else fails the error, but the real error doesn't surface because `esbuild` does still zombie around.

**Comment by sanketdeshmukh** [comment]
I'm facing simlar issue with Angular 17 ESbuild

**Comment by ThreatLockerNathanHolden** [comment]
Reporting the same issue with Angular cli and build v17.3.5 and Node.js v20.9.0.

In our case, the initial build completes successfully, the dev server runs on initial load, and then the esbuild error occurs after file changes are made during the rebuild.

```
[error] Error: The service was stopped
    at [...]\node_modules\esbuild\lib\main.js:1111:28
    at responseCallbacks.<computed> ([...]\node_modules\esbuild\lib\main.js:704:9)
    at Socket.afterClose ([...]\node_modules\esbuild\lib\main.js:694:28)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by blogcraft** [comment]
I have the same problem in Angular 18.1.4

```
An unhandled exception occurred: The service was stopped
See "C:\Users\XYZ\AppData\Local\Temp\ng-Tpr6IX\angular-errors.log" for further details.
```

```
[error] Error: The service was stopped
    at C:\Repos\MyApp\MyApp.Angular\node_modules\esbuild\lib\main.js:993:26
    at responseCallbacks.<computed> (C:\Repos\MyApp\MyApp.Angular\node_modules\esbuild\lib\main.js:622:9)
    at Socket.afterClose (C:\Repos\MyApp\MyApp.Angular\node_modules\esbuild\lib\main.js:613:28)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by deekshithreddychilakala** [comment]
Facing the same issue, using angular-cli v17.3.2, Node v20.17.0
The issue started coming up after upgrading system from windows 10 to windows 11. The project works fine on systems which are still on windows 10 but whoever has upgraded to windows 11 are facing this issue:

`[error] Error: The service was stopped
    at <path>\node_modules\esbuild\lib\main.js:1111:28
    at responseCallbacks.<computed> (<path>\node_modules\esbuild\lib\main.js:704:9)
    at Socket.afterClose (<path>\node_modules\esbuild\lib\main.js:694:28)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

**Comment by ImmaB** [comment]
I still have this issue with angular-cli v18.2.10 and Node v22.11.0 also under Windows 11. It happens randomly. When I run "npm start" it sometimes works and sometimes doesn't. My workaround right now is to just try again.

**Comment by ImmaB** [comment]
In Version 19 the error disappeared for me

**Comment by JPCodeCraft** [comment]
I got this error doing SSG with ng build for over 11K routes.

[error] Error: The service was stopped: write UNKNOWN

Angular 19.

**Comment by blogcraft** [comment]
Still happening in 19, less frequent, but still.

**Comment by filibertogeoni** [comment]
Same error here, running Angular 18. Serve crashes but not every time a change is made, it is quite random. Sometimes it's more often, sometimes less, so I tried increasing the --max-old-space-size but to no avail.

`[error] Error: The service was stopped
    at C:\Users\filib\Documents\Safe Aware\sdm_frontend\node_modules\esbuild\lib\main.js:993:26
    at responseCallbacks.<computed> (C:\Users\filib\Documents\Safe Aware\sdm_frontend\node_modules\esbuild\lib\main.js:622:9)
    at Socket.afterClose (C:\Users\filib\Documents\Safe Aware\sdm_frontend\node_modules\esbuild\lib\main.js:613:28)
    at Socket.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

**Comment by muberraduman** [comment]
I am having the same issue with Angular 19.2.0 and Node v20.12.1
The service was stopped
    at %project_directory%\node_modules\esbuild\lib\main.js:994:26
    at responseCallbacks.<computed> (%project_directory%\node_modules\esbuild\lib\main.js:623:9)
    at Socket.afterClose (%project_directory%\node_modules\esbuild\lib\main.js:614:28)
    at Socket.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by LSAfrika** [comment]
any solutions found tried it with 2 ng versions 19/18 on both node 20 and 18 seems the server can't fire up am supposed to start a project soon and its not working may have to go all the way back to ng 16 or 15 whichever decides to boot up

**Comment by JaroslavX** [comment]
I'm encountering the same issue with Angular 19 and Node v20.18. The development build succeeds only if the 'optimization' option is disabled. If I enable 'optimization', the build fails.

Currently, my workaround is:

- Use the legacy builder "@angular-devkit/build-angular:browser" with optimization enabled for production builds.
- Use "@angular-devkit/build-angular:application" with optimization disabled for development builds.

**Comment by GautamYadav19** [comment]
i also facing same issue is there any solution


Angular CLI: 18.2.12
Node: 20.18.1
Package Manager: npm 10.8.2
OS: win32 x64

![Image](https://github.com/user-attachments/assets/9464414a-cbec-4959-a5bf-59c2b862589a)
--------------------------------
I also try this
ng update @angular/cli@next

but it need node version 20.19 and angular 20

**Comment by alan-agius4** [comment]
The message "The service was stopped" is not a bug in the Angular CLI. It originates from esbuild and typically indicates that your system lacks sufficient resources to complete the build most likely, the OOM killer is terminating esbuild due to memory constraints.

Related: 
- https://github.com/evanw/esbuild/issues/3966
- https://github.com/evanw/esbuild/issues/320
