### ISSUE TITLE
URI malformed issue from @angular-devkit's dependency library Vite

### ISSUE THREAD

**Issue by satheesh-kumar-m** [angular/angular-cli#28436]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Just created new angular application(version - 17.3.9) using below command,
 **ng new url-test-app**
then start application using below command,
**npm start**
Now navigate to below URL,
**http://localhost:4200/**
Now just add new query param with value %_24Q3, for example,
**http://localhost:4200/?testParam=test%_24Q3**

We will get below issue, Please help to fix this issue.
Not able to handle this with angular error handler

```
URI malformed
    at decodeURI (<anonymous>)
    at viteTransformMiddleware (file:///D:/angular/url-test-app/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:63436:19)
    at call (file:///D:/angular/url-test-app/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:42750:7)
    at next (file:///D:/angular/url-test-app/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:42694:5)
    at viteHMRPingMiddleware (file:///D:/angular/url-test-app/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:64700:13)
    at call (file:///D:/angular/url-test-app/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:42750:7)
    at next (file:///D:/angular/url-test-app/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:42694:5)
    at next (file:///D:/angular/url-test-app/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:42672:14)
    at viteCachedTransformMiddleware (file:///D:/angular/url-test-app/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:63421:9)
    at call (file:///D:/angular/url-test-app/node_modules/vite/dist/node/chunks/dep-k5wXcrSr.js:42750:7
    ```

![image (4)](https://github.com/user-attachments/assets/3e24bf0f-f566-4b08-a549-be150e0929e3)

**Comment by JoostK** [comment]
What's the expectation here? `test%_24Q3` _is_ invalid.

**Comment by satheesh-kumar-m** [comment]
@JoostK 
We expect it do not break application.
It should work as issue is in query param only, and page should show content relate to the URL's path param

**Comment by JoostK** [comment]
A query parameter as part of an URL that is sent to server has to be parsed out as a separate query parameter, but the invalid percent encoding makes the entire URL invalid (at this point the query variable isn't a query variable yet). So an individual query parameter cannot be recognized as such.

You should be URL-encoding the values that are used as query variable.

**Comment by satheesh-kumar-m** [comment]
@JoostK 
I accept it is invalid URL.
Do we have possibility to handle this error in feature versions like below?
try {
return decodeURI(url);
} catch(e) {
return url.split('?')[0]
}

**Comment by alan-agius4** [comment]
The `decodeURI` method is called inside Vite, as such we do not have control over it.
