### ISSUE TITLE
bug: ng serve ignores packages from the browser field in package.json

### ISSUE THREAD

**Issue by mburger81** [angular/angular-cli#28563]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We build in the crypto space and for security we use libs like crypto package to en/de crypto serve communications or similar stuff. As you know those libraries are native in nodejs build in and does not support browser environment, so there we have to use polyfills for them like `crypto-browserify` and `stream-browserify`. With `webpack` we could create paths in the `tsconfig` file and everything worked great.

Unfortunately this is not working well for esbuild and there are already a few related bug which where just solved in part, also one from my side [#26901](https://github.com/angular/angular-cli/issues/26901)

The solution proposed here https://github.com/angular/angular-cli/issues/26901#issuecomment-1907045285 by @clydin worked great for production build but it didnt work for dev server as I and also `xkx-dev` pointed out here https://github.com/angular/angular-cli/issues/26901#issuecomment-1913624658

I have created an plain angular project with the real minimum requirements to run into a similar issue, which means the `stream` is not available on dev server.
But If I run exactly the same code as production build, everything is fine. So it looks like dev server ignores somehow libs/paths declared in the browser field of the package.json file

### Minimal Reproduction

Here the repository
https://github.com/mburger81/angular-crypto-esbuild

this is my browser field
 ```
"browser": {
    "crypto": "crypto-browserify",
    "stream": "stream-browserify",
    "os": "os-browserify",
    "https": "https-browserify",
    "http": "stream-http",
    "url": "url"
  }
```

And in the app.component.ts file I run a very simple example

```
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import * as crypto from 'crypto';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'angular-crypto-esbuild';

  key: Buffer;

  constructor() {
    this.key = crypto.createHash('sha256').update('token').digest();
    console.log('Key:', this.key);
  }
}
```

### Exception or Error

var Transform = require('stream').Transform;

Transform is undefined and this is the thrown exception

ERROR TypeError: Cannot read properties of undefined (reading 'call')
    at Hash.CipherBase (index.js:6:13)
    at new Hash (browser.js:9:8)
    at Object.createHash (browser.js:23:10)
    at new _AppComponent (app.component.ts:18:23)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (app.component.ts:20:3)
    at getNodeInjectable (core.mjs:5872:38)
    at createRootComponent (core.mjs:16402:31)
    at ComponentFactory.create (core.mjs:16259:21)
    at _ApplicationRef.bootstrap (core.mjs:31811:38)
    at core.mjs:33202:20

### Your Environment

Angular CLI: 18.2.7
Node: 20.17.0
Package Manager: npm 10.8.3
OS: darwin x64

Angular: 18.2.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.7
@angular-devkit/build-angular   18.2.7
@angular-devkit/core            18.2.7
@angular-devkit/schematics      18.2.7
@schematics/angular             18.2.7
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by mburger81** [comment]
@xkx-dev do you have ever found a solution for our issue
https://github.com/angular/angular-cli/issues/26901#issuecomment-1913624658
