### ISSUE TITLE
differences in behavior when using ng:serve, ng:build for cjs default lazy imports

### ISSUE THREAD

**Issue by stnor** [angular/angular-cli#28679]
### Command

build, serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

It works the same with webpack

### Description

I have some legacy code that uses default exports that needs to be loaded lazily. For example mathquill/jquery and Blockly. I also load some newer libraries such as mathjax v4 lazily.

When using `await import()`the code works using `ng serve`, when using `require()`the code works using `ng build`.

I cannot seem to find a solution/configuration/syntax that both works (the same) for `ng serve`and `ng build`. Right now I cannot use `ng serve`and use `ng build --watch` plus `http-server`.

I know that esbuild doesn't support dynamic imports when you use non-static strings, but these are straightforward imports.

I also read, and tried to understand the texts linked here:
https://stackoverflow.com/questions/75690800/esbuild-cjs-not-working-when-importing-the-default-of-an-hybrid-module

### Expected behavior
I would want `serve`and `build`to have the same behaviour for the same code or if that's not possible, to find one set of syntax and config that works in both.

### Minimal Reproduction

Small reproduction is here:
https://github.com/stnor/lazy-deps (ng new + some added deps + changes to app.component.ts with outputs information using console.log)

1. run `start`

console output:
```
await import type= object
app.component.ts:23 await import jQueryAwait= {fn: {…}, expando: 'jQuery37106325101847870058', isReady: false, extend: ƒ, error: ƒ, …}
app.component.ts:26 await import jQueryAwait.module= undefined
app.component.ts:21 ERROR Error: Dynamic require of "jquery" is not supported
    at main.js:5:9
    at _AppComponent.<anonymous> (app.component.ts:29:22)
    at Generator.next (<anonymous>)
    at fulfilled (main.js:11:24)
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:7045:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at ZoneImpl.run (zone.js:111:43)
    at zone.js:2538:40
    at _ZoneDelegate.invokeTask (zone.js:402:33)
```

2. run `watch` + `http-server` 

console output:
```
app.component.ts:22 await import type= object
app.component.ts:23 await import jQueryAwait= Module {Symbol(Symbol.toStringTag): 'Module'}
app.component.ts:26 await import jQueryAwait.module= undefined
app.component.ts:30 using require function ƒ (selector, context) {
        return new jQuery.fn.init(selector, context);
      }
```

### Exception or Error

Dynamic require of "xxx" is not supported

### Your Environment

Angular CLI: 18.2.9
Node: 20.11.1
Package Manager: yarn 1.22.22
OS: darwin arm64

Angular: 18.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.9
@angular-devkit/build-angular   18.2.9
@angular-devkit/core            18.2.9
@angular-devkit/schematics      18.2.9
@angular/cli                    18.2.9
@schematics/angular             18.2.9
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by stnor** [comment]
Many thanks @alan-agius4!
That solved most of the issues. Had to monkey-patch a few things with a couple of deps but it worked a lot better and I am now up and running with `ng:serve`too ❤️
