### ISSUE TITLE
ng build fails with: An error occurred while extracting routes.

### ISSUE THREAD

**Issue by json-derulo** [angular/angular-cli#28683]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

19.0.0-next.9

### Description

When running `ng build` on a freshly generated Angular 19 prerelease project, an error is thrown.

### Minimal Reproduction

- Run `npx @angular/cli@next new` and enable SSR
- Run `ng build`

### Exception or Error

```
✘ [ERROR] An error occurred while extracting routes.

Error: No handler function exported from /projects/ng19-test-proj/node_modules/@angular/build/src/utils/server-rendering/routes-extractor-worker.js
    at /projects/ng19-test-proj/node_modules/piscina/dist/worker.js:142:23
```

### Your Environment

Angular CLI: 19.0.0-next.12
Node: 20.18.0
Package Manager: npm 10.9.0
OS: darwin x64

Angular: 19.0.0-next.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-next.12
@angular-devkit/build-angular   19.0.0-next.12
@angular-devkit/core            19.0.0-next.12
@angular-devkit/schematics      19.0.0-next.12
@angular/cli                    19.0.0-next.12
@angular/ssr                    19.0.0-next.12
@schematics/angular             19.0.0-next.12
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0

**Comment by alan-agius4** [comment]
Hi @json-derulo, 

I am not able to reproduce the above error with the steps provided.
```
$ npx @angular/cli@next new ssr-test --ssr
Need to install the following packages:
@angular/cli@19.0.0-next.12
CREATE ssr-test/README.md (1478 bytes)
CREATE ssr-test/.editorconfig (314 bytes)
CREATE ssr-test/.gitignore (587 bytes)
CREATE ssr-test/angular.json (2753 bytes)
CREATE ssr-test/package.json (1363 bytes)
CREATE ssr-test/tsconfig.json (915 bytes)
CREATE ssr-test/tsconfig.app.json (489 bytes)
CREATE ssr-test/tsconfig.spec.json (434 bytes)
CREATE ssr-test/.vscode/extensions.json (130 bytes)
CREATE ssr-test/.vscode/launch.json (470 bytes)
CREATE ssr-test/.vscode/tasks.json (938 bytes)
CREATE ssr-test/src/main.ts (250 bytes)
CREATE ssr-test/src/index.html (293 bytes)
CREATE ssr-test/src/styles.css (80 bytes)
CREATE ssr-test/src/main.server.ts (264 bytes)
CREATE ssr-test/src/server.ts (1785 bytes)
CREATE ssr-test/src/app/app.component.css (0 bytes)
CREATE ssr-test/src/app/app.component.html (19903 bytes)
CREATE ssr-test/src/app/app.component.spec.ts (922 bytes)
CREATE ssr-test/src/app/app.component.ts (304 bytes)
CREATE ssr-test/src/app/app.config.ts (438 bytes)
CREATE ssr-test/src/app/app.routes.ts (77 bytes)
CREATE ssr-test/src/app/app.config.server.ts (505 bytes)
CREATE ssr-test/src/app/app.routes.server.ts (166 bytes)
CREATE ssr-test/public/favicon.ico (15086 bytes)
✔ Packages installed successfully.
    Successfully initialized git.

$ ng build
Browser bundles      
Initial chunk files   | Names            |  Raw size | Estimated transfer size
main-B62CN3HO.js      | main             | 235.21 kB |                64.37 kB
polyfills-FFHMD2TL.js | polyfills        |  34.52 kB |                11.28 kB
styles-5INURTSO.css   | styles           |   0 bytes |                 0 bytes

                      | Initial total    | 269.73 kB |                75.65 kB


Server bundles       
Initial chunk files   | Names            |  Raw size
chunk-3LUFOK6H.mjs    | -                | 851.12 kB |                        
server.mjs            | server           | 842.21 kB |                        
polyfills.server.mjs  | polyfills.server | 268.60 kB |                        
main.server.mjs       | main.server      |  18.65 kB |                        
chunk-PES6N7ZL.mjs    | -                |   3.37 kB |                        

Lazy chunk files      | Names            |  Raw size
chunk-G752ZPIS.mjs    | xhr2             |  12.06 kB |                        
chunk-FS7GGNWD.mjs    | xhr2             |  12.06 kB |                        

Prerendered 1 static route.
Application bundle generation complete. [11.851 seconds]

```

**Comment by json-derulo** [comment]
@alan-agius4 I copied the exact command you were using, still I'm getting the same error. Any chance that this is only happening on MacOS? Here is my full output:

```
Browser bundles      
Initial chunk files   | Names            |  Raw size | Estimated transfer size
main-B62CN3HO.js      | main             | 235.21 kB |                64.37 kB
polyfills-FFHMD2TL.js | polyfills        |  34.52 kB |                11.28 kB
styles-5INURTSO.css   | styles           |   0 bytes |                 0 bytes

                      | Initial total    | 269.73 kB |                75.65 kB


Server bundles       
Initial chunk files   | Names            |  Raw size
chunk-3LUFOK6H.mjs    | -                | 851.12 kB |                        
server.mjs            | server           | 842.21 kB |                        
polyfills.server.mjs  | polyfills.server | 268.60 kB |                        
main.server.mjs       | main.server      |  18.65 kB |                        
chunk-PES6N7ZL.mjs    | -                |   3.37 kB |                        

Lazy chunk files      | Names            |  Raw size
chunk-G752ZPIS.mjs    | xhr2             |  12.06 kB |                        
chunk-FS7GGNWD.mjs    | xhr2             |  12.06 kB |                        

Prerendered 0 static routes.
Application bundle generation failed. [25.262 seconds]

✘ [ERROR] An error occurred while extracting routes.

Error: No handler function exported from/projects/ssr-test/node_modules/@angular/build/src/utils/server-rendering/routes-extractor-worker.js
    at /projects/ssr-test/node_modules/piscina/dist/worker.js:142:23
```

**Comment by alan-agius4** [comment]
Umm… interesting @json-derulo, thanks for checking, I’ll take a look tomorrow.

**Comment by alan-agius4** [comment]
It turns out the issue is related to the Node.js version. It seems there have been subtle changes in the ESM loader hooks. I’ll have a fix ready soon
