### ISSUE TITLE
Can't use `new` or `init` - Unexpected token )

### ISSUE THREAD

**Issue by AlmogBaku** [angular/angular-cli#2878]
### OS?
MacOS Sierra 10.12.1

### Versions.
```
angular-cli: 1.0.0-beta.18
node: 3.3.1
os: darwin x64
```

```
npm: 3.10.9
```

### Repro steps.
Tried to create new project with `ng new my-app`

### The log given by the failure.
```
$ ng new a
Unexpected token )
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Blueprint.load (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/blueprint.js:1364:25)
    at Function.Blueprint.lookup (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/models/blueprint.js:1339:24)
    at Class.module.exports.Task.extend.run (/usr/local/lib/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/install-blueprint.js:53:33)
    at Class.Command.extend.run (/usr/local/lib/node_modules/angular-cli/commands/init.js:105:33)
    at tryCatch (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/usr/local/lib/node_modules/angular-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

**Comment by soulxy** [comment]
> Both the CLI and generated project have dependencies that require Node 4 or higher, together with NPM 3 or higher.

**Comment by AlmogBaku** [comment]
Thanks, upgrading node solved it
