### ISSUE TITLE
Build fails on Docker with app initializer that does http request

### ISSUE THREAD

**Issue by k-schneider** [angular/angular-cli#28999]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have an Angular v19 app that is failing within a docker build due to prerendering (even though I don't have any prerendered routes).  The build succeeds when ran directly on my Windows workstation.

### Minimal Reproduction

I have a really simple app configuration service/provider that exposes environment variables to the client:

```typescript
export const provideAppConfig = () =>
  provideAppInitializer(() => appConfigInitializer(inject(AppConfigService)));

function appConfigInitializer(appConfigService: AppConfigService) {
  return appConfigService.load();
}

@Injectable({
  providedIn: "root",
})
export class AppConfigService {
  private http = inject(HttpClient);
  value = signal<AppConfig>({});

  public async load(): Promise<void> {
    const config = await firstValueFrom(
      this.http.get<AppConfig>("/app-config"),
    );
    this.value.set(config);
  }

  public get(key: string): any {
    return this.value()[key];
  }
}

interface AppConfig {
  [key: string]: any;
}
```

And an express route that serves back json:

```typescript
const route = Router();

/**
 * Returns any public environment variables that start with PUBLIC_NG_ for use in the Angular app
 */
route.get("/app-config", (req, res) => {
  const config: Record<string, any> = {};
  Object.keys(process.env).forEach((key) => {
    if (key.startsWith("PUBLIC_NG_")) {
      config[key] = process.env[key];
    }
  });
  res.json(config);
});

export default route;
```

The Dockerfile for reference is:

```text
# Use Node.js for building the Angular SSR app
FROM node:22 AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm ci

# Copy all files and build the Angular SSR app
COPY . .
RUN npm run build

# Use a minimal Node.js image to run the SSR server
FROM node:22-alpine AS server

# Set the working directory
WORKDIR /app

# Copy the built app from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app

# Install serve to serve the SSR app
RUN npm install -g serve

# Expose the SSR server port
EXPOSE 4000

# Command to run the SSR server
CMD ["npm", "run", "serve:ssr"]
```

### Exception or Error

```text
0.233 > ng build
0.233
0.541 ❯ Building...
0.944 (node:20) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
0.944 (Use `node --trace-warnings ...` to show where the warning was created)
4.862 ERROR vt {
4.862   headers: e {
4.862     headers: Map(0) {},
4.862     normalizedNames: Map(0) {},
4.862     lazyInit: undefined,
4.862     lazyUpdate: null
4.862   },
4.862   status: 0,
4.862   statusText: 'Unknown Error',
4.862   url: 'http://localhost:37773/app-config',
4.862   ok: false,
4.862   type: undefined,
4.862   name: 'HttpErrorResponse',
4.862   message: 'Http failure response for http://localhost:37773/app-config: 0 undefined',
4.862   error: TypeError: fetch failed
4.862       at node:internal/deps/undici/undici:13178:13
4.862       at a.invoke (file:///app/.angular/prerender-root/6d2a3b7b-b719-4cf2-96bb-7b6c75bc01a4/polyfills.server.mjs:3:6715)
4.862       at l.run (file:///app/.angular/prerender-root/6d2a3b7b-b719-4cf2-96bb-7b6c75bc01a4/polyfills.server.mjs:3:1985)
4.862       at file:///app/.angular/prerender-root/6d2a3b7b-b719-4cf2-96bb-7b6c75bc01a4/polyfills.server.mjs:4:576
4.862       at a.invokeTask (file:///app/.angular/prerender-root/6d2a3b7b-b719-4cf2-96bb-7b6c75bc01a4/polyfills.server.mjs:3:7341)
4.862       at l.runTask (file:///app/.angular/prerender-root/6d2a3b7b-b719-4cf2-96bb-7b6c75bc01a4/polyfills.server.mjs:3:2628)
4.862       at R (file:///app/.angular/prerender-root/6d2a3b7b-b719-4cf2-96bb-7b6c75bc01a4/polyfills.server.mjs:3:9382)
4.862       at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
4.862     [cause]: Error: connect ECONNREFUSED 127.0.0.1:37773
4.862         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
4.862       errno: -111,
4.862       code: 'ECONNREFUSED',
4.862       syscall: 'connect',
4.862       address: '127.0.0.1',
4.862       port: 37773
4.862     }
4.862   }
4.862 }
```

### Your Environment

```text
Angular CLI: 19.0.2
Node: 20.18.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 19.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@angular/ssr                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else relevant?

If I put a try/catch around the http request and suppress the error the build succeeds.

**Comment by alan-agius4** [comment]
@k-schneider, can you verify the above patch? Thanks.

**Comment by k-schneider** [comment]
Sorry I'm just going to close this as it no longer seems to be an issue.  I bumped some packages and it disappeared.  I'll open a new issue if it crops back up.  Thanks.
