### ISSUE TITLE
Angular SSR 19.0.3 - index.server.html does not exist.

### ISSUE THREAD

**Issue by not-nemlig** [angular/angular-cli#29108]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Upgrading @angular/ssr to 19.0.3 causes the error. I can reproduce easily reproduce it.

Did some digging, and it might be related to this one? https://github.com/angular/angular-ssr-builds/commit/bdec7edc5ed396e9548e171fabb12191c7658922 

Note i don't use service workers.

## server.ts
```typescript
/* eslint-disable */
import 'zone.js/node';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import * as http from 'http';
import { AngularNodeAppEngine, createNodeRequestHandler, isMainModule, writeResponseToNodeResponse } from '@angular/ssr/node';
import express from 'express';
import { healthcheck } from './server/middlewares/healthcheck.middleware';
import router from './server/routes';
import serverTiming from 'server-timing';

import { NodeSDK } from '@opentelemetry/sdk-node';
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';
import { PeriodicExportingMetricReader } from '@opentelemetry/sdk-metrics';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-grpc';
import { OTLPMetricExporter } from '@opentelemetry/exporter-metrics-otlp-grpc';

const sdk = new NodeSDK({
  traceExporter: new OTLPTraceExporter({
    url: 'x',
    headers: {},
  }),
  metricReader: new PeriodicExportingMetricReader({
    exportIntervalMillis: 30000,
    exporter: new OTLPMetricExporter({
      url: 'x',
      headers: {},
      concurrencyLimit: 1,
    }),
  }),
  instrumentations: [getNodeAutoInstrumentations()],
});

sdk.start();

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const serverDistFolder = dirname(fileURLToPath(import.meta.url));
  const browserDistFolder = resolve(serverDistFolder, '../browser');

  const angularNodeAppEngine = new AngularNodeAppEngine();

  server.use(router);
  server.use(
    serverTiming({
      enabled: (req, res) => req.query.debug === 'true',
    })
  );

  const healthcheckServer = http.createServer(server);

  healthcheck(healthcheckServer);

  server.get(
    '**',
    express.static(browserDistFolder, {
      maxAge: '1y',
      index: 'index.html',
    })
  );

  // All regular routes use the Angular engine
  server.get('*', (req, res, next) => {
    res.startTime('SSR', 'Total SSR time');
    angularNodeAppEngine
      .handle(req, { server: 'express' })
      .then((response) => {
        if (response) {
          return writeResponseToNodeResponse(response, res);
        } else {
          res.endTime('SSR');
          return next();
        }
      })
      .catch(next);
  });

  return server;
}

const server = app();

if (isMainModule(import.meta.url)) {
  const port = process.env['PORT'] || 4000;
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

console.warn('Node Express server started');

// This exposes the RequestHandler
export const reqHandler = createNodeRequestHandler(server);
```

Something I'm missing?

### Please provide the exception or error you saw

```true
✘ [ERROR] An error occurred while extracting routes.

Error: Server asset 'index.server.html' does not exist.
    at ServerAssets.getServerAsset (/Users/not/WebstormProjects/frontends/.angular/prerender-root/b226fa15-5c2f-4b9b-81e1-146bc30cc3e5/node_modules/@angular/ssr/fesm2022/ssr.mjs:30:13)
    at ServerAssets.getIndexServerHtml (/Users/not/WebstormProjects/frontends/.angular/prerender-root/b226fa15-5c2f-4b9b-81e1-146bc30cc3e5/node_modules/@angular/ssr/fesm2022/ssr.mjs:50:17)
    at <anonymous> (/Users/not/WebstormProjects/frontends/.angular/prerender-root/b226fa15-5c2f-4b9b-81e1-146bc30cc3e5/node_modules/@angular/ssr/fesm2022/ssr.mjs:1052:55)
    at Generator.next (<anonymous>)
    at file:///Users/not/WebstormProjects/frontends/.angular/prerender-root/b226fa15-5c2f-4b9b-81e1-146bc30cc3e5/chunk-CZ5RRHY2.mjs:86:61
    at new ZoneAwarePromise (/Users/not/WebstormProjects/frontends/.angular/prerender-root/b226fa15-5c2f-4b9b-81e1-146bc30cc3e5/node_modules/zone.js/fesm2015/zone-node.js:1317:23)
    at __async (file:///Users/not/WebstormProjects/frontends/.angular/prerender-root/b226fa15-5c2f-4b9b-81e1-146bc30cc3e5/chunk-CZ5RRHY2.mjs:70:10)
    at extract (/Users/not/WebstormProjects/frontends/.angular/prerender-root/b226fa15-5c2f-4b9b-81e1-146bc30cc3e5/node_modules/@angular/ssr/fesm2022/ssr.mjs:1050:28)
    at extractRoutesAndCreateRouteTree (/Users/not/WebstormProjects/frontends/.angular/prerender-root/b226fa15-5c2f-4b9b-81e1-146bc30cc3e5/node_modules/@angular/ssr/fesm2022/ssr.mjs:1084:78)
    at extractRoutes (/Users/not/WebstormProjects/frontends/node_modules/@angular/build/src/utils/server-rendering/routes-extractor-worker.js:24:56)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 22.11.0
Package Manager: npm 10.9.0
OS: darwin arm64

Angular: 19.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.3
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cdk                    19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.14.8
```

**Comment by alan-agius4** [comment]
It's difficult to determine the root cause without a reproduction. What is set as your `index` in the `angular.json` file? Does this error also happen during `ng serve`?
