### ISSUE TITLE
[ERROR] The package "crypto" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]

### ISSUE THREAD

**Issue by spock123** [angular/angular-cli#29125]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After we have upgrade several different projects to NG19, we are getting this error, but ONLY in development mode!
The error does NOT show up when making a production build.
Our projects do not directly use crypto but some of the 3rd party modules probably do (and used to work without issues).

`[ERROR] The package "crypto" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]`

### Please provide the exception or error you saw

```true
Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
  ➜  Local:   http://localhost:4000/en
  ➜  Network: http://192.168.86.34:4000/en
  ➜  press h + enter to show help
✘ [ERROR] The package "crypto" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]

    node_modules/seedrandom/seedrandom.js:265:27:
      265 │       nodecrypto = require('crypto');
          ╵                            ~~~~~~~~

/Users/spock/projects/fresto/apps/nexus/node_modules/vite/node_modules/esbuild/lib/main.js:1472
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
node_modules/seedrandom/seedrandom.js:265:27: ERROR: [plugin: angular-browser-node-built-in] The package "crypto" wasn't found on the file system but is built into node.
    at failureErrorWithLog (/Users/spock/projects/fresto/apps/nexus/node_modules/vite/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/spock/projects/fresto/apps/nexus/node_modules/vite/node_modules/esbuild/lib/main.js:945:25
    at /Users/spock/projects/fresto/apps/nexus/node_modules/vite/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.18.0
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.4
Node: 20.18.0
Package Manager: npm 10.8.2
OS: darwin arm64

Angular: 19.0.4
... animations, build, cli, common, compiler, compiler-cli, core
... forms, localize, platform-browser, platform-browser-dynamic
... router, service-worker, ssr

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1900.4
@angular-devkit/core                 19.0.1
@angular-devkit/schematics           19.0.4
@angular/cdk                         19.0.3
@angular/google-maps                 19.0.3
@angular/material                    19.0.3
@angular/material-date-fns-adapter   19.0.3
@schematics/angular                  19.0.4
rxjs                                 7.8.1
typescript                           5.6.3
zone.js                              0.15.0
```

### Anything else?

Angular.json:

```
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "version": 1,
    "cli": {
        "packageManager": "npm",
        "analytics": "ac59db6d-a680-408f-af50-2623fb62aeae",
        "cache": {
            "enabled": true
        }
    },
    "newProjectRoot": "projects",
    "projects": {
        "nexus": {
            "projectType": "application",
            "schematics": {
                "@schematics/angular:component": {
                    "style": "scss",
                    "skipTests": true,
                    "standalone": true,
                    "changeDetection": "OnPush"
                },
                "@schematics/angular:class": {
                    "skipTests": true
                },
                "@schematics/angular:directive": {
                    "skipTests": true,
                    "standalone": true
                },
                "@schematics/angular:guard": {
                    "skipTests": true
                },
                "@schematics/angular:interceptor": {
                    "skipTests": true
                },
                "@schematics/angular:pipe": {
                    "skipTests": true,
                    "standalone": true
                },
                "@schematics/angular:resolver": {
                    "skipTests": true
                },
                "@schematics/angular:service": {
                    "skipTests": true
                }
            },
            "root": "",
            "sourceRoot": "src",
            "prefix": "app",
            "i18n": {
                "sourceLocale": "en-US",
                "locales": {
                    "da": {
                        "translation": "src/locale/messages.da.json"
                    },
                    "en": {
                        "translation": "src/locale/messages.en.json"
                    }
                }
            },
            "architect": {
                "build": {
                    "builder": "@angular/build:application",
                    "options": {
                        "allowedCommonJsDependencies": [
                            "mathjs",
                            "ngrx-store-localstorage",
                            "qrcode",
                            "file-saver"
                        ],

                        "outputPath": {
                            "base": "dist/nexus/"
                        },
                        "index": "src/index.html",
                        "polyfills": ["@angular/localize/init"],
                        "tsConfig": "tsconfig.app.json",
                        "inlineStyleLanguage": "scss",
                        "styles": ["src/styles/index.scss"],
                        "assets": ["src/assets", "src/robots.txt", "src/manifest.json"],
                        "scripts": [],
                        "serviceWorker": "ngsw-config.json",
                        "localize": true,
                        "i18nDuplicateTranslation": "ignore",

                        "preserveSymlinks": false,
                        "browser": "src/main.ts"
                    },
                    "configurations": {
                        "production": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.prod.ts"
                                },
                                {
                                    "replace": "src/app/shared/store/build-specifics/index.ts",
                                    "with": "src/app/shared/store/build-specifics/index.prod.ts"
                                }
                            ],
                            "outputHashing": "all",
                            "namedChunks": false
                        },
                        "localprod": {
                            "optimization": false,
                            "sourceMap": true,
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.localprod.ts"
                                }
                            ]
                        },

                        "test": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.test.ts"
                                },
                                {
                                    "replace": "src/app/features/core/site-protection/index.ts",
                                    "with": "src/app/features/core/site-protection/index.protected.ts"
                                }
                            ],
                            "outputHashing": "all",
                            "namedChunks": false
                        },
                        "localtest": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.localtest.ts"
                                }
                            ],
                            "localize": ["en"],
                            "outputHashing": "all"
                        },
                        "development": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.dev.ts"
                                },
                                {
                                    "replace": "src/app/shared/store/build-specifics/index.ts",
                                    "with": "src/app/shared/store/build-specifics/index.prod.ts"
                                },
                                {
                                    "replace": "src/app/features/core/site-protection/index.ts",
                                    "with": "src/app/features/core/site-protection/index.protected.ts"
                                }
                            ],
                            "outputHashing": "all",
                            "sourceMap": true,
                            "namedChunks": false
                        },
                        "local": {
                            "optimization": false,
                            "sourceMap": true,
                            "fileReplacements": []
                        },
                        "da": {
                            "localize": ["da"],
                            "baseHref": "/da/"
                        },
                        "en": {
                            "localize": ["en"],
                            "baseHref": "/en/"
                        }
                    },
                    "defaultConfiguration": "production"
                },
                "serve": {
                    "builder": "@angular/build:dev-server",
                    "configurations": {
                        "production": {
                            "buildTarget": "nexus:build:production"
                        },
                        "localprod": {
                            "buildTarget": "nexus:build:localprod"
                        },
                        "localtest": {
                            "buildTarget": "nexus:build:localtest"
                        },
                        "test": {
                            "buildTarget": "nexus:build:test"
                        },
                        "development": {
                            "buildTarget": "nexus:build:development"
                        },
                        "local": {
                            "buildTarget": "nexus:build:local,en"
                        },

                        "da": {
                            "buildTarget": "nexus:build:local,da"
                        },
                        "en": {
                            "buildTarget": "nexus:build:local,en"
                        }
                    },
                    "defaultConfiguration": "local"
                },
                "extract-i18n": {
                    "builder": "@angular/build:extract-i18n",
                    "options": {
                        "buildTarget": "nexus:build"
                    }
                },

                "deploy": {
                    "builder": "@angular/fire:deploy",
                    "options": {
                        "prerender": false,
                        "ssr": false,
                        "browserTarget": "nexus:build:production",
                        "firebaseProject": "fastorder-dev",
                        "firebaseHostingSite": "fresto-totti-dev"
                    }
                }
            }
        }
    }
}

```

**Comment by spock123** [comment]
@alan-agius4  thanks for pointing that out.

I just wanna say that I am getting this issue with @angular/cli 19.0.4, which is the latest version available afaik?

**Comment by alan-agius4** [comment]
Is `@angular/build` also on `19.0.5`?

**Comment by spock123** [comment]
@alan-agius4  BOOM!
That did it! We were on 19.0.4 and now on 19.0.5 it just works!

Amazing work, thank you so much!
