### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by vladyn** [angular/angular-cli#29146]
### Command

generate

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

I've uninstalled node, removed all the AppData npm and cache, installed it again, but no success.
This is with latest angular cli and angular 18 project. I think the project is not relevant as I'm not able to run any ng command anywhere. 

```
ng
fs.js:44
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:44:5
    at req_ (C:\Users\homeUser\AppData\Roaming\npm\node_modules\angular-cli\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\homeUser\AppData\Roaming\npm\node_modules\angular-cli\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\homeUser\AppData\Roaming\npm\node_modules\angular-cli\node_modules\yam\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)

Node.js v22.12.0
```

### Minimal Reproduction

Any ng command fails with the above error. 

### Exception or Error

```text
ng
fs.js:44
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:44:5
    at req_ (C:\Users\homeUser\AppData\Roaming\npm\node_modules\angular-cli\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\homeUser\AppData\Roaming\npm\node_modules\angular-cli\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\homeUser\AppData\Roaming\npm\node_modules\angular-cli\node_modules\yam\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)

Node.js v22.12.0
```

### Your Environment

```text
node 22
node 23 
angular cli latest 
angular 18
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
