### ISSUE TITLE
SSG allow loading static assets

### ISSUE THREAD

**Issue by AmitMY** [angular/angular-cli#29236]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

I am using [transloco](https://github.com/jsverse/transloco) for localization.
When building (used to be prerendering) now the build process tries to render the pages.
In doing so, it hits this loader, which loads a static asset (the language in question)
```ts
@Injectable({providedIn: 'root'})
export class HttpLoader implements TranslocoLoader {
  private http = inject(HttpClient);

  getTranslation(langPath: string): Observable<Translation> {
    return this.http.get<Translation>(`assets/i18n/${langPath}.json`);
  }
}
```
However, the HTTP request fails, since there seems to not be an http server involved in the SSG process.

If I run this in SSR, it also fails, but that is because it can't handle the path, and requires a full URL (http://localhost:4000/assets/...)

If I accept not having a server, I need to have a similar behavior to what I do during testing:
```ts
    if (isPlatformServer(this.platformId)) {
      const path = require('path');
      const filePath = path.join(__dirname, '..', '..', '..', assetPath);
      console.error('filePath', filePath);
      const fs = require('fs');

      const data = fs.readFileSync(filePath, 'utf8');
      return of(JSON.parse(data));
    }
```

But this relies on node modules, and the builder errors:
>   The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

Therefore, my issues are:

1. SSG should have some sort of way to load static assets. 
2. SSR should not need the full URL. somehow, it should understand that any path requested is under the same host as the REQUEST.

### Minimal Reproduction

1. Make a new app, with ssr and ssg (`"prerender": true`, "ssr": {"entry": "src/server.ts"}`)
2. under `src/assets` add `something.json`
3. in the `AppComponent`'s `ngOnInit` function, make `this.httpClient.get('/assets/something.json').subscribe()`
4. run `ng build --configuration=production`

### Exception or Error

```text
- SSG should have a way to load static assets
- SSR should be able to load assets using HTTP
```

### Your Environment

```text
Angular CLI: 19.0.6
Node: 22.0.0
Package Manager: npm 10.5.1
OS: darwin arm64

Angular: 19.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.6
@angular-devkit/build-angular   19.0.6
@angular-devkit/core            19.0.6
@angular-devkit/schematics      19.0.6
@angular/cdk                    19.0.4
@angular/cli                    19.0.6
@angular/material               19.0.4
@angular/ssr                    19.0.6
@schematics/angular             19.0.6
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else relevant?

In the old prerendering, it used to work.

**Comment by alan-agius4** [comment]
Load of assets when using SSG has been supported for some time now, Although you are required to use [`withFetch`](https://angular.dev/api/common/http/withFetch).

If the problem persists please provide a minimal runnable reproduction of the problem.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by AmitMY** [comment]
If I set up a new app:
<img width="832" alt="Image" src="https://github.com/user-attachments/assets/206b45e6-ef0d-462c-9e41-d1add6776370" />
Added `public/something.json` file with some content, , and added `provideHttpClient(withFetch())`, it indeed works.

```ts
  private http = inject(HttpClient);

  ngOnInit() {
    this.http.get('something.json').pipe(
      tap((res: any) => console.log("Success", res)),
      catchError((err: any) => {
        console.log("Error", err);
        return of(null);
      })
    ).subscribe();
  }
```

Indeed prints "success"

----

However, in my app, I am using `withFetch`
```ts
    provideHttpClient(withFetch(), withInterceptorsFromDi()),
```
But still it doesn't work:
```ts
Couldn't load translation file 'assets/i18n/en.json' dt {
  headers: e {
    headers: Map(0) {},
    normalizedNames: Map(0) {},
    lazyInit: undefined,
    lazyUpdate: null
  },
  status: 0,
  statusText: 'Unknown Error',
  url: 'assets/i18n/languages/en.json',
  ok: false,
  type: undefined,
  name: 'HttpErrorResponse',
  message: 'Http failure response for assets/i18n/languages/en.json: 0 undefined',
  error: TypeError: Invalid URL
```

**Comment by AmitMY** [comment]
Hi @alan-agius4 - any ideas on this?

**Comment by AmitMY** [comment]
@alan-agius4 Unfortuantely, after updating to the latest release, it is not yet solved.

My updates:
```ts
 @angular-devkit/architect          0.1900.6  →  0.1900.7
 @angular-devkit/build-angular        19.0.6  →    19.0.7
 @angular/animations                  19.0.5  →    19.0.6
 @angular/cdk                         19.0.4  →    19.0.5
 @angular/cli                         19.0.6  →    19.0.7
 @angular/common                      19.0.5  →    19.0.6
 @angular/compiler                    19.0.5  →    19.0.6
 @angular/compiler-cli                19.0.5  →    19.0.6
 @angular/core                        19.0.5  →    19.0.6
 @angular/forms                       19.0.5  →    19.0.6
 @angular/material                    19.0.4  →    19.0.5
 @angular/platform-browser            19.0.5  →    19.0.6
 @angular/platform-browser-dynamic    19.0.5  →    19.0.6
 @angular/platform-server             19.0.5  →    19.0.6
 @angular/router                      19.0.5  →    19.0.6
 @angular/service-worker              19.0.5  →    19.0.6
 @angular/ssr                         19.0.6  →    19.0.7
```

Error:
```ts
HttpErrorResponse {
  headers: _HttpHeaders {
    headers: Map(0) {},
    normalizedNames: Map(0) {},
    lazyInit: undefined,
    lazyUpdate: null
  },
  status: 0,
  statusText: 'Unknown Error',
  url: 'assets/i18n/countries/en.json',
  ok: false,
  type: undefined,
  name: 'HttpErrorResponse',
  message: 'Http failure response for assets/i18n/countries/en.json: 0 undefined',
  error: TypeError: Failed to parse URL from assets/i18n/countries/en.json
      at node:internal/deps/undici/undici:12500:13
      at _ZoneDelegate.invoke (/Users/amitmoryossef/dev/sign/translate/node_modules/zone.js/fesm2015/zone-node.js:369:28)
      at ZoneImpl.run (/Users/amitmoryossef/dev/sign/translate/node_modules/zone.js/fesm2015/zone-node.js:111:43)
      at eval (/Users/amitmoryossef/dev/sign/translate/node_modules/zone.js/fesm2015/zone-node.js:1221:40)
      at _ZoneDelegate.invokeTask (/Users/amitmoryossef/dev/sign/translate/node_modules/zone.js/fesm2015/zone-node.js:402:33)
      at ZoneImpl.runTask (/Users/amitmoryossef/dev/sign/translate/node_modules/zone.js/fesm2015/zone-node.js:159:47)
      at drainMicroTaskQueue (/Users/amitmoryossef/dev/sign/translate/node_modules/zone.js/fesm2015/zone-node.js:581:35) {
    [cause]: TypeError: Invalid URL
        at new URL (node:internal/url:804:36)
        at new Request (node:internal/deps/undici/undici:4839:25)
        at fetch (node:internal/deps/undici/undici:9651:25)
        at fetch (node:internal/deps/undici/undici:12498:10)
        at fetch (node:internal/bootstrap/web/exposed-window-or-worker:79:16)
        at eval (/Users/amitmoryossef/dev/sign/translate/node_modules/zone.js/fesm2015/zone-node.js:1472:40)
        at proto.<computed> (/Users/amitmoryossef/dev/sign/translate/node_modules/zone.js/fesm2015/zone-node.js:913:24)
        at _FetchBackend.FetchBackend.fetchImpl (/Users/amitmoryossef/dev/sign/translate/.angular/cache/19.0.7/sign-translate/vite/deps_ssr/chunk-YUNSYC3W.js:1233:41)
        at eval (/Users/amitmoryossef/dev/sign/translate/.angular/cache/19.0.7/sign-translate/vite/deps_ssr/chunk-YUNSYC3W.js:1249:71)
        at _ZoneDelegate.invoke (/Users/amitmoryossef/dev/sign/translate/node_modules/zone.js/fesm2015/zone-node.js:369:28) {
      code: 'ERR_INVALID_URL',
      input: 'assets/i18n/countries/en.json'
    }
  }
}
```

**Comment by alan-agius4** [comment]
I tried again your reproduction and I am not getting that error, I am seeing other error but these are legit as the file does not exist

```
ERROR HttpErrorResponse {
  headers: _HttpHeaders {
    headers: Map(0) {},
    normalizedNames: Map(0) {},
    lazyInit: undefined,
    lazyUpdate: null
  },
  status: 0,
  statusText: 'Unknown Error',
  url: '/licenses.json',
  ok: false,
  type: undefined,
  name: 'HttpErrorResponse',
  message: 'Http failure response for /licenses.json: 0 undefined',
  error: TypeError: Failed to parse URL from /licenses.json
      at node:internal/deps/undici/undici:13178:13
      at _ZoneDelegate.invoke (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/zone.js/fesm2015/zone-node.js:369:28)
      at ZoneImpl.run (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/zone.js/fesm2015/zone-node.js:111:43)
      at <anonymous> (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/zone.js/fesm2015/zone-node.js:1221:40)
      at _ZoneDelegate.invokeTask (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/zone.js/fesm2015/zone-node.js:402:33)
      at ZoneImpl.runTask (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/zone.js/fesm2015/zone-node.js:159:47)
      at drainMicroTaskQueue (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/zone.js/fesm2015/zone-node.js:581:35) {
    [cause]: TypeError: Invalid URL
        at new URL (node:internal/url:797:36)
        at new Request (node:internal/deps/undici/undici:9269:25)
        at fetch (node:internal/deps/undici/undici:9998:25)
        at fetch (node:internal/deps/undici/undici:13176:10)
        at fetch (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
        at patchedFetch (node_modules/@angular/build/src/utils/server-rendering/fetch-patch.js:40:20)
        at <anonymous> (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/zone.js/fesm2015/zone-node.js:1472:40)
        at proto.<computed> (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/zone.js/fesm2015/zone-node.js:913:24)
        at _FetchBackend.FetchBackend.fetchImpl (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/@angular/common/fesm2022/http.mjs:1584:41)
        at <anonymous> (.angular/prerender-root/0ededdec-950b-4f09-bb9e-894731c005fa/node_modules/@angular/common/fesm2022/http.mjs:1602:69) {
      code: 'ERR_INVALID_URL',
      input: '/licenses.json'
    }
  }
}
```

**Comment by AmitMY** [comment]
Interesting! You are correct, about that file.

`ng build` problem solved 🥳  (only `licenses.json` file missing)
`ng serve` now has the original problem 😢  (all files, including `assets` missing)

Much less critical than before, thank you!

**Comment by alan-agius4** [comment]
That is caused because `provideServerRendering()` is not invoked. 
See: https://github.com/sign/translate/blob/5d15b7910bd2d540d8b03e0691fc7959378c7807/src/app/app.config.server.ts#L6 these API will also fail on production servers.


I am actually surprised that you got this far without it.
