### ISSUE TITLE
Beta 19 ../upgrade/version not found

### ISSUE THREAD

**Issue by achimha** [angular/angular-cli#2934]
Just installed beta 19 and I get an error. Also tried deleting and reinstalling `angular-cli`:

```
$ node_modules/.bin/ng --version
module.js:471
    throw err;
    ^

Error: Cannot find module '../upgrade/version'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/foo/project/node_modules/angular-cli/bin/ng:11:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Looking at the distribution, it seems the compiled JavaScript is missing:
```
$ ls -l node_modules/angular-cli/upgrade/
total 16
-rw-r--r--  1 achimha  staff  4174 Oct 24 18:53 version.ts
```

**Comment by filipesilva** [comment]
We did have some trouble with the base `beta.19`, which is why we immediately release `beta.19-2`, which fixes the error you see there.

It's also the version marked as latest, so users trying to upgrade with `angular-cli@latest` should get the fixed one.
```
$ npm info angular-cli dist-tags
{ latest: '1.0.0-beta.19-2', experimental: '1.0.0-beta.19-2' }
```

**Comment by sgybas** [comment]
The other packages suffer from the same build issues, see #2941
