### ISSUE TITLE
CLI ng build --prod command

### ISSUE THREAD

**Issue by MaherSoua** [angular/angular-cli#2958]
### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.18
node: 6.9.1
os: win32 x64

### Repro steps.
Create command:
ng build --prod
It was an app wich is made with ng , but some classes created by hand, I worked on Heroes Details Routing tutorial part.

### The log given by the failure.
C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:1......
What I found weird, is that it is mentionning the  Igor Minar's Dev path (I think).

**Comment by Meligy** [comment]
Are you able to push a test repo or more specific repro steps please?

Something that others can repeat to see the error, you know.

Also, would be awesome if you could try with latest / current version. That is beta.19-3 at the time of writing.

**Comment by MaherSoua** [comment]
Hi, I am sorry I was wrong in fact when I use this command this will happen:
ng build --aot
Config : 
angular-cli: 1.0.0-beta.18
node: 6.9.1
os: win32 x64

and this is the error log (C:\Users\Dell\angular-work\my-site\ is my path but it is weird when we see the path of Igor Minar):

this.compiler.analyzeModules is not a function
TypeError: this.compiler.analyzeModules is not a function
    at CodeGenerator.codegen (**C:\Users\iminar\Dev\angular\**modules\@angular\compiler-cli\src\codegen.ts:125:45)
    at AotPlugin._make (C:\Users\Dell\angular-work\my-site\node_modules\@ngtools\webpack\src\plugin.js:186:43)
    at Compiler.<anonymous> (C:\Users\Dell\angular-work\my-site\node_modules\@ngtools\webpack\src\plugin.js:151:75)
    at Compiler.applyPluginsParallel (C:\Users\Dell\angular-work\my-site\node_modules\tapable\lib\Tapable.js:156:14)
    at Compiler.<anonymous> (C:\Users\Dell\angular-work\my-site\node_modules\webpack\lib\Compiler.js:463:8)
    at Compiler.applyPluginsAsync (C:\Users\Dell\angular-work\my-site\node_modules\tapable\lib\Tapable.js:73:70)
    at Compiler.compile (C:\Users\Dell\angular-work\my-site\node_modules\webpack\lib\Compiler.js:456:7)
    at Compiler.<anonymous> (C:\Users\Dell\angular-work\my-site\node_modules\webpack\lib\Compiler.js:219:10)
    at Compiler.readRecords (C:\Users\Dell\angular-work\my-site\node_modules\webpack\lib\Compiler.js:367:10)
    at Compiler.<anonymous> (C:\Users\Dell\angular-work\my-site\node_modules\webpack\lib\Compiler.js:216:9)
    at next (C:\Users\Dell\angular-work\my-site\node_modules\tapable\lib\Tapable.js:81:11)
    at Compiler.<anonymous> (C:\Users\Dell\angular-work\my-site\node_modules\webpack\lib\CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (C:\Users\Dell\angular-work\my-site\node_modules\tapable\lib\Tapable.js:85:13)
    at Compiler.<anonymous> (C:\Users\Dell\angular-work\my-site\node_modules\webpack\lib\Compiler.js:213:8)
    at next (C:\Users\Dell\angular-work\my-site\node_modules\tapable\lib\Tapable.js:81:11)
    at Compiler.<anonymous> (C:\Users\Dell\angular-work\my-site\node_modules\webpack\lib\node\NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (C:\Users\Dell\angular-work\my-site\node_modules\tapable\lib\Tapable.js:85:13)
    at Compiler.run (C:\Users\Dell\angular-work\my-site\node_modules\webpack\lib\Compiler.js:210:7)
    at C:\Users\Dell\angular-work\my-site\node_modules\angular-cli\tasks\build-webpack.js:26:29
    at Class.run (C:\Users\Dell\angular-work\my-site\node_modules\angular-cli\tasks\build-webpack.js:25:16)
    at Class.run (C:\Users\Dell\angular-work\my-site\node_modules\angular-cli\commands\build.js:50:26)
    at Class.<anonymous> (C:\Users\Dell\angular-work\my-site\node_modules\angular-cli\lib\models\command.js:152:17)
    at tryCatch (C:\Users\Dell\angular-work\my-site\node_modules\rsvp\dist\lib\rsvp\-internal.js:215:12)
    at invokeCallback (C:\Users\Dell\angular-work\my-site\node_modules\rsvp\dist\lib\rsvp\-internal.js:230:13)
    at C:\Users\Dell\angular-work\my-site\node_modules\rsvp\dist\lib\rsvp\then.js:29:16
    at flush (C:\Users\Dell\angular-work\my-site\node_modules\rsvp\dist\lib\rsvp\asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by filipesilva** [comment]
@MaherSoua it is indeed weird that you get that path. If I had to bet, this is related to a certain combination of versions of angular packages.

Can you try updating your CLI version, making a branch new project, and copying your source files into `src/app`? This should clear up any versioning problems.

**Comment by filipesilva** [comment]
Closing as fixed.
