### ISSUE TITLE
Can't bind to 'ngbCollapse' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by kgathi2** [angular/angular-cli#2980]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX El Capital

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.19-3
node: 6.8.1
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Added ng-bootstrap as specified on https://ng-bootstrap.github.io/ . Then added a component such as collapse or dropdown in the app.component. The application runs as expected, but i get error when i try to run `ng test`

### The log given by the failure.
> Normally this include a stack trace and some more information.

```bash
$ ng test
01 11 2016 22:28:49.243:WARN [karma]: No captured browser, open http://localhost:9876/
01 11 2016 22:28:49.254:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
01 11 2016 22:28:49.255:INFO [launcher]: Launching browser Chrome with unlimited concurrency
01 11 2016 22:28:49.276:INFO [launcher]: Starting browser Chrome
01 11 2016 22:28:50.976:INFO [Chrome 54.0.2840 (Mac OS X 10.11.6)]: Connected on socket /#pVnQMcqSFmRohboBAAAA with id 3667269
Chrome 54.0.2840 (Mac OS X 10.11.6) App: RelaySpa should create the app FAILED
	Can't bind to 'up' since it isn't a known property of 'li'. ("
	  </ul>
	  <ul class="nav navbar-nav anchor-bottom">
	    <li ngbDropdown [ERROR ->][up]="true" class="dropup">
	      <a class="has-notification" id="user-menu" ngbDropdownToggle>
	     "): AppComponent@13:20
	Can't bind to 'ngbCollapse' since it isn't a known property of 'div'. ("
	<!-- Organisation Switch Start -->
	<div [ERROR ->][ngbCollapse]="orgSwitchCollapsed" class="menu-popup col-md-3">
	  <div class="card">
	    <a class="bt"): AppComponent@62:5
	Can't bind to 'up' since it isn't a known property of 'div'. ("
	    <div class="col-xs-6 text-xs-right">
	      <div ngbDropdown [ERROR ->][up]="true" class="d-inline-block">
	        <button class="btn btn-outline-primary" id="dropdownMenu2"): AppComponent@105:23
	Error: Template parse errors:
	    at TemplateParser.parse (http://localhost:9876/_karma_webpack_/2.bundle.js:8415:19)
	    at RuntimeCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/2.bundle.js:17862:51)
	    at http://localhost:9876/_karma_webpack_/2.bundle.js:17767:83
	    at Set.forEach (native)
	    at compile (http://localhost:9876/_karma_webpack_/2.bundle.js:17767:47)
	    at RuntimeCompiler._compileComponents (http://localhost:9876/_karma_webpack_/2.bundle.js:17769:13)
	    at RuntimeCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/2.bundle.js:17676:37)
	    at RuntimeCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/2.bundle.js:17664:21)
	    at TestingCompilerImpl.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/2.bundle.js:23555:35)
	    at TestBed._initIfNeeded (webpack:///Users/gathitu/Developer/Projects/relay_spa/~/@angular/core/bundles/core-testing.umd.js:761:0 <- src/test.ts:3889:40)
Chrome 54.0.2840 (Mac OS X 10.11.6) App: RelaySpa should have as title 'app works!' FAILED
	Can't bind to 'up' since it isn't a known property of 'li'. ("
	  </ul>
	  <ul class="nav navbar-nav anchor-bottom">
	    <li ngbDropdown [ERROR ->][up]="true" class="dropup">
	      <a class="has-notification" id="user-menu" ngbDropdownToggle>
	     "): AppComponent@13:20
	Can't bind to 'ngbCollapse' since it isn't a known property of 'div'. ("
	<!-- Organisation Switch Start -->
	<div [ERROR ->][ngbCollapse]="orgSwitchCollapsed" class="menu-popup col-md-3">
	  <div class="card">
	    <a class="bt"): AppComponent@62:5
	Can't bind to 'up' since it isn't a known property of 'div'. ("
	    <div class="col-xs-6 text-xs-right">
	      <div ngbDropdown [ERROR ->][up]="true" class="d-inline-block">
	        <button class="btn btn-outline-primary" id="dropdownMenu2"): AppComponent@105:23
	Error: Template parse errors:
	    at TemplateParser.parse (http://localhost:9876/_karma_webpack_/2.bundle.js:8415:19)
	    at RuntimeCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/2.bundle.js:17862:51)
	    at http://localhost:9876/_karma_webpack_/2.bundle.js:17767:83
	    at Set.forEach (native)
	    at compile (http://localhost:9876/_karma_webpack_/2.bundle.js:17767:47)
	    at RuntimeCompiler._compileComponents (http://localhost:9876/_karma_webpack_/2.bundle.js:17769:13)
	    at RuntimeCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/2.bundle.js:17676:37)
	    at RuntimeCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/2.bundle.js:17664:21)
	    at TestingCompilerImpl.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/2.bundle.js:23555:35)
	    at TestBed._initIfNeeded (webpack:///Users/gathitu/Developer/Projects/relay_spa/~/@angular/core/bundles/core-testing.umd.js:761:0 <- src/test.ts:3889:40)
Chrome 54.0.2840 (Mac OS X 10.11.6) App: RelaySpa should render title in a h1 tag FAILED
	Can't bind to 'up' since it isn't a known property of 'li'. ("
	  </ul>
	  <ul class="nav navbar-nav anchor-bottom">
	    <li ngbDropdown [ERROR ->][up]="true" class="dropup">
	      <a class="has-notification" id="user-menu" ngbDropdownToggle>
	     "): AppComponent@13:20
	Can't bind to 'ngbCollapse' since it isn't a known property of 'div'. ("
	<!-- Organisation Switch Start -->
	<div [ERROR ->][ngbCollapse]="orgSwitchCollapsed" class="menu-popup col-md-3">
	  <div class="card">
	    <a class="bt"): AppComponent@62:5
	Can't bind to 'up' since it isn't a known property of 'div'. ("
	    <div class="col-xs-6 text-xs-right">
	      <div ngbDropdown [ERROR ->][up]="true" class="d-inline-block">
	        <button class="btn btn-outline-primary" id="dropdownMenu2"): AppComponent@105:23
	Error: Template parse errors:
	    at TemplateParser.parse (http://localhost:9876/_karma_webpack_/2.bundle.js:8415:19)
	    at RuntimeCompiler._compileTemplate (http://localhost:9876/_karma_webpack_/2.bundle.js:17862:51)
	    at http://localhost:9876/_karma_webpack_/2.bundle.js:17767:83
	    at Set.forEach (native)
	    at compile (http://localhost:9876/_karma_webpack_/2.bundle.js:17767:47)
	    at RuntimeCompiler._compileComponents (http://localhost:9876/_karma_webpack_/2.bundle.js:17769:13)
	    at RuntimeCompiler._compileModuleAndAllComponents (http://localhost:9876/_karma_webpack_/2.bundle.js:17676:37)
	    at RuntimeCompiler.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/2.bundle.js:17664:21)
	    at TestingCompilerImpl.compileModuleAndAllComponentsSync (http://localhost:9876/_karma_webpack_/2.bundle.js:23555:35)
	    at TestBed._initIfNeeded (webpack:///Users/gathitu/Developer/Projects/relay_spa/~/@angular/core/bundles/core-testing.umd.js:761:0 <- src/test.ts:3889:40)
Chrome 54.0.2840 (Mac OS X 10.11.6): Executed 3 of 3 (3 FAILED) ERROR (0.483 secs / 0.416 secs)
```
### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

The errors only occur when there is ng-bootstrap markup in the app.component.html. The test pass OK If i delete the modified html and return the default
```html
  <h1>
    {{title}}
  </h1>
```

**Comment by Meligy** [comment]
This is not an issue of the CLI.

When you write Angular 2 unit tests for components that use other components / directives, you are supposed to configure a test module, similar to how you configure the `AppModule` for the runnable application.

The default template for component test does not have this (it just goes `new AppComponent()`, which is enough for no dependencies), but it looks something like:

```
// ... test imports
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap';
import { CommonModule } from '@angular/common';



let comp:    AppComponent;
let fixture: ComponentFixture<AppComponent>;
let de:      DebugElement;
let el:      HTMLElement;

describe('BannerComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [ CommonModule, NgbDropdownModule.forRoot() ],
      declarations: [ AppComponent ], // declare the test component
    });

    fixture = TestBed.createComponent(AppComponent);

    comp = fixture.componentInstance; // AppComponent test instance

    // ...

  });

  // you it('', ...) tests here
});
```

Read more here: https://angular.io/docs/ts/latest/guide/testing.html#!#configure-testing-module

There's quite a bit to testing in Angular 2, but again, this is not Angular CLI specific, unless I'm missing something.

**Comment by kgathi2** [comment]
Thanks @Meligy That solved my issue.

**Comment by rjsteinert** [comment]
So we need to duplicate the imports from our modules into the spec files for our components? How about the standard component spec file imports the module which exports the component? Would that be a performance hit?
