### ISSUE TITLE
ng build --prod --output-path ../../ deletes current directory

### ISSUE THREAD

**Issue by gh0st** [angular/angular-cli#3024]
### OS
macOS Sierra 10.12.1

### Version
angular-cli: 1.0.0-beta.17
node: 4.5.0
os: darwin x64

### Reproduction Steps
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
This app was created using the CLI.

### Failure Log
```
thereaper:calabria chad$ ng build --prod --output-path ../../
Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ENOENT: no such file or directory, open '/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/angular-cli/lib/config/schema.json'
Error: ENOENT: no such file or directory, open '/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/angular-cli/lib/config/schema.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Function.CliConfig.fromJson (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/angular-cli/models/config/config.js:63:32)
    at Function.CliConfig.fromProject (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/angular-cli/models/config.js:43:39)
    at new NgCliWebpackConfig (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/angular-cli/models/webpack-config.js:12:41)
    at Class.exports.default.Task.extend.run (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/angular-cli/tasks/build-webpack.js:17:22)
    at Class.Command.extend.run (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/chad/Developer/pcp-calabria/public/vendor/calabria/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

### Other useful details
The folder structure  goes `pcp-calabria/public/vendor/calabria`. Calabria holds what was created by angular-cli. When I run `ng build --prod --output-path ../../` I want the build to go into `pcp-calabria/public/calabria` but instead everything in `pcp-calabria/public/vendor/calabria` gets deleted.

**Comment by filipesilva** [comment]
As a part of creating a build, everything in the output path is deleted so that there is no leftover files. This is intentional.

**Comment by RenaldasK** [comment]
Is there a way to override this? I have a case where the output folder contains some back-end files too, and I do not want them to be deleted.
