### ISSUE TITLE
Error proxy conf

### ISSUE THREAD

**Issue by GuillaumeUnice** [angular/angular-cli#3045]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux Ubuntu 16.04

### Versions.
> angular-cli: 1.0.0-beta.17
node: 6.9.1
os: linux x64

### Error
> When I try to run : ng serve --proxy proxy.conf.js
with the following proxy.conf.js
```
{
  "/user": {
    "target": "http://localhost:8080",
    "secure": false,
    "logLevel": "debug"
  }
}
```

### The log given by the failure.
> 
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Unexpected token :
/home/gborg/Bureau/jwt-spring-security-demo/src/main/resources/angularStatelessApp/proxy.conf.js:2
  "/user": {
         ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.run (/home/gborg/Bureau/jwt-spring-security-demo/src/main/resources/angularStatelessApp/node_modules/angular-cli/tasks/serve-webpack.js:32:31)
    at /home/gborg/Bureau/jwt-spring-security-demo/src/main/resources/angularStatelessApp/node_modules/angular-cli/commands/serve.js:85:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by deebloo** [comment]
@GuillaumeUnice can you try updating to the latest version (beta.19-3) and see if you still get this error?

**Comment by crain** [comment]
@GuillaumeUnice did you tried to rename from *.js to *.json? I don't know the internals but it could be that its being interpreted as js instead of json.

**Comment by GuillaumeUnice** [comment]
@crain thank you If anyone can update the readme for that?
`proxy proxy.conf.js => proxy proxy.conf.json`
