### ISSUE TITLE
prod build with --aot flag throws TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by areijngoudt** [angular/angular-cli#3046]
angular-cli 1.0.0-beta.19-3
OSX Sierra

When trying to build a prod version with AOT, the next error is outputted:

```
ng build --prod --aot

 10% building modules 3/3 modules 0 active[TypeError: Cannot read property 'replace' of null]
Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at ReflectorHost.getImportPath (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/reflector_host.ts:111:32)
    at ReflectorHost.reflectorHost.getImportPath (/Users/adreijngoudt/tfs/Proeftuin/MO.MiL.BeeldAnalyse/web/client/node_modules/@ngtools/webpack/src/reflector_host.js:13:27)
    at /Users/adreijngoudt/tfs/Proeftuin/MO.MiL.BeeldAnalyse/web/client/node_modules/@angular/compiler-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:15229:78
    at Map.forEach (native)
    at TypeScriptEmitter.emitStatements (/Users/adreijngoudt/tfs/Proeftuin/MO.MiL.BeeldAnalyse/web/client/node_modules/@angular/compiler-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:15226:41)
    at OfflineCompiler._codegenSourceModule (/Users/adreijngoudt/tfs/Proeftuin/MO.MiL.BeeldAnalyse/web/client/node_modules/@angular/compiler-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:12998:66)
    at /Users/adreijngoudt/tfs/Proeftuin/MO.MiL.BeeldAnalyse/web/client/node_modules/@angular/compiler-cli/node_modules/@angular/compiler/bundles/compiler.umd.js:12932:53
    at tryCatch (/Users/adreijngoudt/tfs/Proeftuin/MO.MiL.BeeldAnalyse/web/client/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:195:12)
    at invokeCallback (/Users/adreijngoudt/tfs/Proeftuin/MO.MiL.BeeldAnalyse/web/client/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:210:13)
    at publish (/Users/adreijngoudt/tfs/Proeftuin/MO.MiL.BeeldAnalyse/web/client/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:178:7)
    at flush (/Users/adreijngoudt/tfs/Proeftuin/MO.MiL.BeeldAnalyse/web/client/node_modules/es6-promise/dist/lib/es6-promise/asap.js:94:5)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by filipesilva** [comment]
I'm going to need some more specific repro steps to look into this issue.

**Comment by areijngoudt** [comment]
It's working with 1.0.0-beta-21 and angular2.3.0
