### ISSUE TITLE
ng github-pages:deploy outputs "No angular-cli-build.js found."

### ISSUE THREAD

**Issue by Pablocgdev** [angular/angular-cli#3076]
### OS?

Windows 7.

### Versions.

angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.7

### Repro steps.

Create app with angular CLI.
Create different componentes, services and pipes.
Deploy with ng serve, OK.
Commit, push to repo, OK.
ng github-pages:deploy : No angular-cli-build.js found.

### The log given by the failure.

`C:\dev-env\myproject>ng github-pages:deploy
- BuildingNo angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.m
d#user-content-brocfile-transition.
Error: No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#u
ser-content-brocfile-transition.
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\dev-env\myproject\node_modules\angular-cli\node_modules\angul
ar-cli\lib\models\builder.js:57:13)
    at Class.module.exports.Task.extend.init (C:\dev-env\myproject\node_modules\angular-cli\node_modules\angular-cli\lib\model
s\builder.js:89:10)
    at new Class (C:\dev-env\myproject\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.
js:18:12)
    at Class.module.exports.Task.extend.run (C:\dev-env\myproject\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\
build.js:15:19)
    at build (C:\dev-env\myproject\node_modules\angular-cli\addon\ng2\commands\github-pages-deploy.ts:108:30)
    at tryCatch (C:\dev-env\myproject\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\-inter
nal.js:215:12)
    at invokeCallback (C:\dev-env\myproject\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\
-internal.js:230:13)
    at publish (C:\dev-env\myproject\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\-intern
al.js:198:7)
    at flush (C:\dev-env\myproject\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\asap.js:8
5:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)`

### Mention any other details that might be useful.

I tried with node6 and every module up-to-date and still get the same error.

According to https://github.com/angular/angular-cli/pull/1633 this should be fixed but I still get the error.

**Comment by clydin** [comment]
You're using a fairly old version of the CLI.  beta.19-3 is the latest.

**Comment by filipesilva** [comment]
The problem is the old CLI version, yes. You should update to fix that problem.
