### ISSUE TITLE
module.path.startsWith is not a function when building with --aot flag

### ISSUE THREAD

**Issue by stochris** [angular/angular-cli#3087]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.19-3
node: 6.2.1
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
This was an app created with the cli, on version 0.17, then upgraded twice, once to 0.18, then to 0.19-3

### The log given by the failure.
> Normally this include a stack trace and some more information.
`module.path.startsWith is not a function
    at AotPlugin._resolveModule (C:\Users\Cristi\monitorizare-vot-ong\frontend\node_modules\@ngtools\webpack\src\plugin.js:216:25)
    at C:\Users\Cristi\monitorizare-vot-ong\frontend\node_modules\@ngtools\webpack\src\plugin.js:233:26
    at Array.map (native)
    at AotPlugin._processNgModule (C:\Users\Cristi\monitorizare-vot-ong\frontend\node_modules\@ngtools\webpack\src\plugin.js:232:35)
    at C:\Users\Cristi\monitorizare-vot-ong\frontend\node_modules\@ngtools\webpack\src\plugin.js:206:23
 10% building modules 7/7 modules 0 active`

Thanks a lot guys !

**Comment by filipesilva** [comment]
Can you provide some repro steps so I can see this error?

**Comment by stochris** [comment]
After I updated to beta-21, the probem no longer appears

**Comment by ruanfumin** [comment]
> Unhandled rejection TypeError: path.startsWith is not a function
    at Object.urlForHelper (/Users/ruanfumin/Documents/staticBlog/node_modules/hexo/lib/plugins/helper/url_for.js:6:31)
    at Object.eval [as tpl] (eval at precompile (/Users/ruanfumin/Documents/staticBlog/node_modules/swig-templates/lib/swig.js:537:13), <anonymous>:125:119)
    at compiled (/Users/ruanfumin/Documents/staticBlog/node_modules/swig-templates/lib/swig.js:664:18)
    at Object.eval [as tpl] (eval at precompile (/Users/ruanfumin/Documents/staticBlog/node_modules/swig-templates/lib/swig.js:537:13), <anonymous>:813:151)
    at compiled (/Users/ruanfumin/Documents/staticBlog/node_modules/swig-templates/lib/swig.js:664:18)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/ruanfumin/Documents/staticBlog/node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render (/Users/ruanfumin/Documents/staticBlog/node_modules/hexo/lib/theme/view.js:30:15)
    at route.set (/Users/ruanfumin/Documents/staticBlog/node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher (/Users/ruanfumin/Documents/staticBlog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/ruanfumin/Documents/staticBlog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/ruanfumin/Documents/staticBlog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:933:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
