### ISSUE TITLE
E/launcher - Process exited with error code 135

### ISSUE THREAD

**Issue by rmahen058** [angular/angular-cli#3089]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> MacOS Sierra

### Versions.
Node Version: v6.9.1
Protractor Version: 4.0.10
NPM Version: 3.10.8

I am unable to run the Protractor test because of the below error.

### The log given by the failure.
/usr/local/bin/node /usr/local/lib/node_modules/protractor/built/cli.js /Users/Rakesh/Documents/sampleProject-3/conf.js
[20:37:35] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[20:37:35] I/launcher - Running 1 instances of WebDriver
[20:37:35] E/launcher - Error code: 135
[20:37:35] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
[20:37:35] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:381:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From: Task: WebDriver.createSession()
    at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:198:43)
    at /usr/local/lib/node_modules/protractor/built/runner.js:285:30
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)
[20:37:35] E/launcher - Process exited with error code 135

Process finished with exit code 135 (interrupted by signal 7: SIGEMT)

### Mention any other details that might be useful.
I am trying to run the protractor test from my Mac machine. I get the above error, please help!!
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by webbywebb** [comment]
I'm experiencing the same problem with these versions:

MacOS El Capitan 10.11.6
Node 7.0.0
Protractor 4.0.11

**Comment by filipesilva** [comment]
I'm going to have to ask you to open this in the protractor issue tracker instead, as it's not something CLI specific: https://github.com/angular/protractor

**Comment by Ranjithsamalla** [comment]
im also facing the same issue 



 :\Protractor>protractor config.js
(node:3540) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[08:52:20] I/launcher - Running 1 instances of WebDriver
[08:52:20] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[08:52:21] E/launcher - Error code: 135
[08:52:21] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
[08:52:21] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:238:15)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\lenovo\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
[08:52:21] E/launcher - Process exited with error code 135
