### ISSUE TITLE
No bower.json present

### ISSUE THREAD

**Issue by diego-vieira** [angular/angular-cli#309]
Let me know if you need the full log running ng init with `--verbose`

Using `ng new app` doesn't throw any error, although no bower.json is created either.

OSX 10.11.3 
npm@3.8.1
node@v5.7.1

```
$ ng init
installing ng2
  create .clang-format
  create config/environment.js
  create e2e/app.e2e.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create angular-cli-build.js
  create .gitignore
  create karma-test-shim.js
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create src/app/backend.html
  create src/app/backend.spec.ts
  create src/app/backend.ts
  create src/app.ts
  create src/favicon.ico
  create src/index.html
  create src/tsconfig.json
  create src/typings.d.ts
  create tslint.json
  create typings.json

├── es6-shim (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

Installed packages for tooling via npm.
No bower.json present
Error: No bower.json present
    at createError (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/core/Project.js:49:19
    at /usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:1229:26
    at _fulfilled (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by filipesilva** [comment]
Thanks for bringing it up! A fix is incoming really soon.
