### ISSUE TITLE
Angular AOT compilation failing. compiler.AnimationParser is not a constructor

### ISSUE THREAD

**Issue by quiringk** [angular/angular-cli#3137]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Yes, this app was created without CLI. I don't think I have actually used CLI to do anything, but it ended up in my package.json when I was updating it with release candidates and Angular 2.0.0 etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

I am trying to use Angular AOT. When I tried to rollup, I was getting errors with ng2-bootstrap module not exporting. In one of the comment threads I saw something about needing the latest version of angular-cli. I installed angular-cli on the command line and now I am getting this error before rollup when trying to just trying to initiate AOT compilation...

`
TypeError: compiler.AnimationParser is not a constructor
    at Function.CodeGenerator.create (C:\Projects\NeilKellyClient4\node_modules\@angular\compiler-cli\src\codegen.js:108:400)
    at codegen (C:\Projects\NeilKellyClient4\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (C:\Projects\NeilKellyClient4\node_modules\@angular\tsc-wrapped\src\main.js:37:16)
    at Object.<anonymous> (C:\Projects\NeilKellyClient4\node_modules\@angular\compiler-cli\src\main.js:16:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Compilation failed
`

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by quiringk** [comment]
Nevermind I confused angular-cli with @angular/compiler-cli

**Comment by shybzzz** [comment]
I've just met very similar failure while aot compilation. can you give more info about how is this fixed
I'm running ngc -p my-aot-ts-config.json and my stack trace is following
TypeError: compiler.AnimationParser is not a constructor
    at Function.CodeGenerator.create (D:\Projects\Angular2SandBox\node_modules\@angular\compiler-cli\src\codegen.js:108:400)
    at codegen (D:\Projects\Angular2SandBox\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (D:\Projects\Angular2SandBox\node_modules\@angular\tsc-wrapped\src\main.js:37:16)
    at Object.<anonymous> (D:\Projects\Angular2SandBox\node_modules\@angular\compiler-cli\src\main.js:16:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Compilation failed

**Comment by estabij** [comment]
I also have that error:
> ngc -p release/tsconfig-aot.json

TypeError: compiler.AnimationParser is not a constructor
    at Function.CodeGenerator.create (/volumes1/workarea/Telematics/Jade/trunk/src/frontend/JadeDashboard/src/node_modules/@angular/compiler-cli/src/codegen.js:108:400)
    at codegen (/volumes1/workarea/Telematics/Jade/trunk/src/frontend/JadeDashboard/src/node_modules/@angular/compiler-cli/src/main.js:7:36)
    at Object.main (/volumes1/workarea/Telematics/Jade/trunk/src/frontend/JadeDashboard/src/node_modules/@angular/tsc-wrapped/src/main.js:37:16)
    at Object.<anonymous> (/volumes1/workarea/Telematics/Jade/trunk/src/frontend/JadeDashboard/src/node_modules/@angular/compiler-cli/src/main.js:16:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
Compilation failed

**Comment by quiringk** [comment]
@shybzzz @estabij  Yeah I had the error but it was with compiler-cli not angular-cli. (I'm not using Angular-cli for anything yet.) The way I got rid of it was using 2.2.0 for all the angular packages including compiler-cli. Then I don't know if this was necessary but I deleted the node_modules and then npm install to reload fresh everything and it worked.

**Comment by dicbrus** [comment]
update to version 2.2.1 solves the problem
