### ISSUE TITLE
ng build Aot not working

### ISSUE THREAD

**Issue by harilalinapp** [angular/angular-cli#3141]
When i run ng build -prod --aot i got this error.

> AuthModule is not an NgModule

My module is 

```
import { NgModule } from "@angular/core"

import { AuthRoutes } from "./auth.routes"
import { LoginComponent } from './login.component';
import { ReactiveFormsModule } from '@angular/forms';
import { CoreModule } from '../core.module';
import { MaterialModule } from '@angular/material';
import { SharedModule } from '../shared/shared.module';

@NgModule({
	declarations: [
		LoginComponent
	],
	imports: [AuthRoutes, MaterialModule, SharedModule, CoreModule, ReactiveFormsModule],
	providers: []
})
export class AuthModule { }
```

I couldn't figure out whats wrong with my module. I have been loading this as lazy loading

```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { LoginComponent } from './auth/login.component';
import { AuthGuard } from './auth/auth.guard';

const routes: Routes = [
	{
		path:'',
		redirectTo: '/login',
		pathMatch: 'full'
	},
	{
		path:'login',
		//component: LoginComponent
		loadChildren: 'app/auth/auth.module#AuthModule',
	}
];
export const RoutingModule = RouterModule.forRoot(routes, { useHash: true });
```
Angular cli : "1.0.0-beta.19-3",

**Comment by sclausen** [comment]
+1

**Comment by elvirdolic** [comment]
you have to put your routes in a module and import it 

see thread: https://github.com/angular/angular-cli/issues/2515#issuecomment-259658868

`import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { HomeComponent } from './home';

export const appRoutes: Routes = [
  {path: '', component: HomeComponent},
  {path: 'info', loadChildren: './info/info.module#InfoModule' },
];

@NgModule({
  imports: [
    RouterModule.forRoot(appRoutes)
  ],
  exports: [
    RouterModule
  ],
  providers: []
})
export class AppRoutingModule {}
`

**Comment by harilalinapp** [comment]
Hi,
It's solved my issue and i can run the 'ng serve --aot' now .
But other error showed up on browser.

```
error_handler.js:47 EXCEPTION: Uncaught (in promise): Error: Cannot find module 'app/auth/auth.module.ngfactory'.
Error: Cannot find module 'app/auth/auth.module.ngfactory'.
    at webpackEmptyContext (http://localhost:4200/main.bundle.js:61294:8)
    at SystemJsNgModuleLoader.loadFactory (http://localhost:4200/main.bundle.js:47921:40)
    at SystemJsNgModuleLoader.load (http://localhost:4200/main.bundle.js:47902:35)
    at RouterConfigLoader.loadModuleFactory (http://localhost:4200/main.bundle.js:10598:128)
    at RouterConfigLoader.load (http://localhost:4200/main.bundle.js:10590:81)
    at MergeMapSubscriber.project (http://localhost:4200/main.bundle.js:68460:111)
    at MergeMapSubscriber._tryNext (http://localhost:4200/main.bundle.js:12799:27)
    at MergeMapSubscriber._next (http://localhost:4200/main.bundle.js:12789:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:4200/main.bundle.js:2131:18)
    at ScalarObservable._subscribe (http://localhost:4200/main.bundle.js:59985:24)
```

I think it's not finding the lazy loaded module in AoT mode.

**Comment by achimha** [comment]
I get `AppModule` is not an NgModule with `--aot` but not without. The error information is extremely sparse, it's not the routing like described above.

How does one go about debugging this "is not an NgModule" error for the actual cause?

**Comment by harilalinapp** [comment]
After upgrading to : 1.0.0-beta.20-4 running 'ng serve --aot` shows another error
#0% compilingcompiler.AnimationParser is not a constructor
TypeError: compiler.AnimationParser is not a constructor
    at Function.CodeGenerator.create (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:141:9)
    at AotPlugin._make (/home/harilal/works/karisoft/project/karisoft/node_modules/@ngtools/webpack/src/plugin.js:189:54)
    at Compiler.<anonymous> (/home/harilal/works/karisoft/project/karisoft/node_modules/@ngtools/webpack/src/plugin.js:157:75)
    at Compiler.applyPluginsParallel (/home/harilal/works/karisoft/project/karisoft/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/home/harilal/works/karisoft/project/karisoft/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack/lib/Compiler.js:456:7)
    at Watching.<anonymous> (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack/lib/Compiler.js:46:17)
    at next (/home/harilal/works/karisoft/project/karisoft/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.invalidAsyncPlugin (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack-dev-middleware/middleware.js:119:3)
    at next (/home/harilal/works/karisoft/project/karisoft/node_modules/tapable/lib/Tapable.js:83:14)
    at Compiler.<anonymous> (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack/lib/CachePlugin.js:31:4)
    at Compiler.applyPluginsAsync (/home/harilal/works/karisoft/project/karisoft/node_modules/tapable/lib/Tapable.js:85:13)
    at Watching._go (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack/lib/Compiler.js:44:16)
    at Watching.<anonymous> (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack/lib/Compiler.js:36:8)
    at Compiler.readRecords (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack/lib/Compiler.js:367:10)
    at new Watching (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack/lib/Compiler.js:33:16)
    at Compiler.watch (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack/lib/Compiler.js:204:17)
    at module.exports (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack-dev-middleware/middleware.js:146:27)
    at new Server (/home/harilal/works/karisoft/project/karisoft/node_modules/webpack-dev-server/lib/Server.js:43:20)
    at Class.run (/home/harilal/works/karisoft/project/karisoft/node_modules/angular-cli/tasks/serve-webpack.js:74:22)
    at /home/harilal/works/karisoft/project/karisoft/node_modules/angular-cli/commands/serve.js:92:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by greengerong** [comment]
How  about this issue? 

I also meet same problem with lazy load module BlogAppModule :

    $ ng build --aot
    10% building modules 4/5 modules 1 active ...ar2/rebirth/src/styles/bootstrap.scssBlogAppModule is not an NgModule
    Error: BlogAppModule is not an NgModule
        at AotPlugin.getNgModuleMetadata (/Users/zxgerong/project/opensource/js/angular2/rebirth/node_modules/@ngtools/webpack/src/plugin.js:297:19)
        at AotPlugin._processNgModule (/Users/zxgerong/project/opensource/js/angular2/rebirth/node_modules/@ngtools/webpack/src/plugin.js:241:42)
        at _loop_1 (/Users/zxgerong/project/opensource/js/angular2/rebirth/node_modules/@ngtools/webpack/src/plugin.js:271:35)
        at AotPlugin._processNgModule (/Users/zxgerong/project/opensource/js/angular2/rebirth/node_modules/@ngtools/webpack/src/plugin.js:290:13)
        at /Users/zxgerong/project/opensource/js/angular2/rebirth/node_modules/@ngtools/webpack/src/plugin.js:217:39
        at tryCatch (/Users/zxgerong/project/opensource/js/angular2/rebirth/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:195:12)
        at invokeCallback (/Users/zxgerong/project/opensource/js/angular2/rebirth/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:210:13)
        at publish (/Users/zxgerong/project/opensource/js/angular2/rebirth/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:178:7)
        at flush (/Users/zxgerong/project/opensource/js/angular2/rebirth/node_modules/es6-promise/dist/lib/es6-promise/asap.js:94:5)
        at nextTickCallbackWith0Args (node.js:452:9)
        at process._tickCallback (node.js:381:13)

**Comment by unsafecode** [comment]
I also get this curious error, but only with a very specific setup: using angular2-router-loader and **not** putting the route config within the AppModule (then, change the router config at runtime), everything works (even if some routes don't load properly then).

On the other hand, if I put my lazy route in AppModule, I get the error.

**Comment by kentoj** [comment]
I am getting this problem even though I am not using AOT.

**Comment by antonybudianto** [comment]
same here

```
0% compilingError: AppModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (/Users/antony/Documents/Code/Web/angular-webpack-starter/node_modules/@ngtools/webpack/src/plugin.js:332:19)
    at AotPlugin._processNgModule (/Users/antony/Documents/Code/Web/angular-webpack-starter/node_modules/@ngtools/webpack/src/plugin.js:271:42)
    at /Users/antony/Documents/Code/Web/angular-webpack-starter/node_modules/@ngtools/webpack/src/plugin.js:242:39
```

reproduction [repo](https://github.com/antonybudianto/angular-webpack-starter), just update the package.json for ngtools and angular packages

**Comment by kentoj** [comment]
What fixed it for me temporarily was to downgrade to angular-cli@1.0.0-beta.21. I had to do that globally and in the local devDependencies for my project. Oddly enough the angular-cli version in angular-cli.json did not matter.

**Comment by bhshawon** [comment]
Same issue

**Comment by filipesilva** [comment]
Closing as obsolete.
