### ISSUE TITLE
ng init doesn't work when update

### ISSUE THREAD

**Issue by e-oz** [angular/angular-cli#3144]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
>  Mac OSX El Capitan

### Versions.
node: 6.9.0
ng-cli: 1.0.0-beta.17
npm: 3.10.8

### Repro steps.
Follow steps in "Update" doc then run "ng init"

### The log given by the failure.
No log, just response:
```
It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a simpler
workflow, a faster build and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14
```
And not, my ng-cli is not beta.14, I have never had beta.14 on my laptop.

**Comment by xtreemrage** [comment]
I have a similar issue:

### OS?
Windows 10

### Versions.
```javascript
angular-cli: 1.0.0-beta.20-4
node: 7.1.0
os: win32 x64
```

### Repro steps.
Follow steps in "Update" doc then run "ng init"

### The log given by the failure.
No log. it just sit there with the text `installing ng2`, I have left it alone for an hour, but that's more then enough. If I press `ctrl + c` to cancel it, I get the following error in the cmd:

```javascript
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.process.stderr.write (C:\ng2-app\node_modules\angular-cli\lib\cli\index.js:40:27)
    at Console.warn (console.js:51:16)
    at printErrorAndExit (C:\ng2-app\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:406:11)
    at process.emit (C:\ng2-app\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:419:16)
    at process._fatalException (bootstrap_node.js:292:26)
```

### Mention any other details that might be useful.
I have updated the global AND project angular-cli, from `beta.19` to `beta.20`.

**Comment by arfeifei** [comment]
Change NodeJs from 7.1.0 backto 6.9.1 it will work. but really want this issue could be fixed in next release

**Comment by xtreemrage** [comment]
It works now, node 7.2.0 and updated angular-cli to beta 21

**Comment by e-oz** [comment]
@arfeifei it's not duplicate, here is different error message.

**Comment by filipesilva** [comment]
@e-oz do you still get this?

**Comment by e-oz** [comment]
@filipesilva no
