### ISSUE TITLE
ng -v error reflect-metadata after update cli version beta.20-1

### ISSUE THREAD

**Issue by antonybudianto7** [angular/angular-cli#3148]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> ubuntu 14.04

### Versions.
angular-cli@1.0.0-beta.20-1
node 7.0.0
npm 3.10.9

### Repro steps.
update latest cli
```
npm rm -g angular-cli
npm i -g angular-cli
```
then 
```
ng -v
```

have done the same with npm cache clean, same error

### The log given by the failure.
```sh
$ ng -v
Cannot find module 'reflect-metadata'
Error: Cannot find module 'reflect-metadata'
```

### Mention any other details that might be useful.
Also when doing `npm ls -g --depth=0` shows
```sh
npm ERR! peer dep missing: @angular/compiler-cli@^2.1.0, required by @ngtools/webpack@1.1.7
npm ERR! peer dep missing: @angular/core@^2.0.0, required by @ngtools/webpack@1.1.7
npm ERR! peer dep missing: reflect-metadata@^0.1.8, required by @ngtools/webpack@1.1.7
```
didn't happen in previous version.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by antonybudianto7** [comment]
full stack traces
```sh
$ ng -v
Cannot find module 'reflect-metadata'
Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/node_modules/@ngtools/webpack/src/index.js:5:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/models/webpack-build-typescript.js:5:17)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/models/webpack-config.js:2:34)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/tasks/build-webpack.js:6:24)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/commands/build.js:3:23)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/addon/index.js:21:16)
    at /home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/angular-cli/lib/models/project.js:391:15)
    at Project.eachAddonCommand (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/angular-cli/lib/models/project.js:426:30)
    at module.exports (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/antony-budianto/.nvm/versions/node/v7.0.0/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by wanghaolu** [comment]
The same error.
![qq 20161116114528](https://cloud.githubusercontent.com/assets/9586655/20334066/3f742e1a-abf2-11e6-87b8-4ac132f5c2a7.png)

**Comment by splintercode** [comment]
Got the same error with same stack trace
angular-cli: v1.0.0-beta.20-1
OS: macOS Sierra
nodejs: 6.7.0

**Comment by b4youleap** [comment]
Can't even run ng version ... same error
angular-cli: v1.0.0-beta.20-1
OS: Windows 7 x64
nodejs: 5.12.0

**Comment by Mattpx** [comment]
Same here :(
angular-cli: v1.0.0-beta.20-1
OS: Mac os 10.10.1
nodejs: 7.0.0
npm: 3.10.9

**Comment by monfa-red** [comment]
"ng " doesn't run anymore!
event after installing it globally, can't event run "ng -v"!

angular-cli@1.0.0-beta.20-1
OS: Kubuntu 16.04
node: v6.9.1
npm: 3.10.8

**Comment by Evrins** [comment]
Same problem
angular-cli@1.0.0-beta.20-1
OS: Mac OS 10.12.1 (16B2555)
node: v7.1.0
npm: 4.0.2

**Comment by monfa-red** [comment]
A **temporary fix** that worked for me:
Add these to your `package.json` (change the version of `@angular/compiler-cli` to the exact same version you have for `@angular/core`)

```
 "@angular/compiler-cli": "2.2.0",
 "reflect-metadata": "^0.1.8"
```

And for running `ng ...`  don't use your global ` angular-cli ` , instead add it to your `package.json` and run it with npm (so it's gonna use your local angular-cli)

```
 "scripts": {
    ...
    "build-my-app": "ng build --prod --aot --xyz"
 },
```
and to run it
```
 npm run build-my-app
```

**Comment by koujala** [comment]
**I managed to get this working this way** 
npm i -g reflect-metadata 

However I installed angular-cli locally ( just like @monfa-red )
npm i angular-cli 

Followed by these
npm i reflect-metadata
npm i zone.js@^0.6.21
npm i -g rxjs@5.0.0-beta.12
npm i @angular/core
npm i @angular/compiler-cli
npm i @angular/compiler

Followed by **ng -v** 
angular-cli: 1.0.0-beta.20-1
node: 6.9.1
os: win32 x64

**Comment by Evrins** [comment]
solve this by rolling back to the last usable version 1.0.0-beta.19-3
npm i -g angular-cli@1.0.0-beta.19-3

**Comment by harilalinapp** [comment]
Same issue. I tried to update my application to 20-1 and its breaking. So i rolled back to 19-3
I think it's related to some dependency.

**Comment by hansl** [comment]
Looking into it. I'm going to release `20-2` soon. Stay tuned.

**Comment by hansl** [comment]
Beta `20-1` is released as `experimental`. Latest tag as been set back to `19-3` while we see if this one is good.

**Comment by hansl** [comment]
Alright this is fixed and published. Sorry all for the inconvenience.

**Comment by harilalinapp** [comment]
Is it the latest?

**Comment by tonymedrano** [comment]
Hi there, my experimental solution in Windows for now is:
-Got to directory: C:\Users\"Your User"\AppData\Roaming\npm\node_modules\angular-cli
- npm install reflect-metadata
- npm install portfinder

It´s working for me and apply for any platform if you can access the final path as above.
Hope this help.
