### ISSUE TITLE
compiler.AnimationParser is not a constructor

### ISSUE THREAD

**Issue by bendg25** [angular/angular-cli#3170]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX Sierra: 10.12.1 (16B2555)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

ng --version
angular-cli: 1.0.0-beta.20-4
node: 7.1.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

ng build --prod --aot
  0% compilingcompiler.AnimationParser is not a constructor
TypeError: compiler.AnimationParser is not a constructor
    at Function.CodeGenerator.create (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:141:9)
    at AotPlugin._make (/Users/bengill/development/flo/designer-ui/node_modules/@ngtools/webpack/src/plugin.js:189:54)
    at Compiler.<anonymous> (/Users/bengill/development/flo/designer-ui/node_modules/@ngtools/webpack/src/plugin.js:157:75)
    at Compiler.applyPluginsParallel (/Users/bengill/development/flo/designer-ui/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/Users/bengill/development/flo/designer-ui/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/Users/bengill/development/flo/designer-ui/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/Users/bengill/development/flo/designer-ui/node_modules/webpack/lib/Compiler.js:456:7)
    at Compiler.<anonymous> (/Users/bengill/development/flo/designer-ui/node_modules/webpack/lib/Compiler.js:219:10)
    at Compiler.readRecords (/Users/bengill/development/flo/designer-ui/node_modules/webpack/lib/Compiler.js:367:10)
    at Compiler.<anonymous> (/Users/bengill/development/flo/designer-ui/node_modules/webpack/lib/Compiler.js:216:9)
    at next (/Users/bengill/development/flo/designer-ui/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/Users/bengill/development/flo/designer-ui/node_modules/webpack/lib/CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (/Users/bengill/development/flo/designer-ui/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.<anonymous> (/Users/bengill/development/flo/designer-ui/node_modules/webpack/lib/Compiler.js:213:8)
    at next (/Users/bengill/development/flo/designer-ui/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/Users/bengill/development/flo/designer-ui/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (/Users/bengill/development/flo/designer-ui/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.run (/Users/bengill/development/flo/designer-ui/node_modules/webpack/lib/Compiler.js:210:7)
    at /Users/bengill/development/flo/designer-ui/node_modules/angular-cli/tasks/build-webpack.js:24:29
    at Class.run (/Users/bengill/development/flo/designer-ui/node_modules/angular-cli/tasks/build-webpack.js:23:16)
    at Class.run (/Users/bengill/development/flo/designer-ui/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/bengill/development/flo/designer-ui/node_modules/angular-cli/angular-cli/lib/models/command.js:152:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bendg25** [comment]
Upgrading to Angular 2.2.0 fixed this for me.
