### ISSUE TITLE
 UnhandledPromiseRejectionWarning with --aot and angular 2.2.1

### ISSUE THREAD

**Issue by alexbyk** [angular/angular-cli#3205]
angular-cli: 1.0.0-beta.20-4
node: 7.1.0
os: linux x64 (ubuntu 16.04)

--

After upgrading angular to 2.2.1 I can't  `--aot` (test and `ng serve` without aot works). I'm getting an error that either points to either scss files or (I tried to exclude css) nothing.

Here is the error
```
 19% building modules 79/79 modules 0 active(node:21391) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: AppModule is not an NgModule
(node:21391) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It doesn't show any usefull information. Maybe there is a bug in my project (or maybe not), but no chances to find it with this info.

The same project with angular 2.2.0 works ok. Also fresh empty projects work

**Comment by Destreyf** [comment]
@alexbyk i'd love to help you out with this but without additional information its a bit difficult.

I am currently running 2.2.1 in my project and `ng serve -aot` without issues, can you link/upload the repo or a skeleton of the app that causes this to happen, i'd love to see if i narrow down the underlying issue.

**Comment by alexbyk** [comment]
@Destreyf  As I said, a fresh projects work fine, mine doesn't. So I can't provide a minimal skeleton to reproduce a problem.
As far as I can see the only way to find a problem is to create a new project and move the code file by file and understand, which part of it causes an error.

I'll post results here when It's done. But doing this for every angular release isn't a fine experience at all :(

**Comment by Destreyf** [comment]
@alexbyk did you modify the tsconfig.json at all? how big is the project overall?  Maybe a copy of `app.module.ts`, `app.component.ts` and `main.ts` from the src directory would be enough to start looking into.

You could stick to 2.2.0 for time being in case its a deeper issue somewhere else.

**Comment by alexbyk** [comment]
I've update to the latest beta  `1.0.0-beta.21` and now I'm getting another error even on fresh new projects after `ncu -a; yarn install`
`
 0% compilingMetadata version mismatch for module /tmp/foo/node_modules/@angular/core/src/di/opaque_token.d.ts, found version 2, expected 1
Error: Metadata version mismatch for module /tmp/foo/node_modules/@angular/core/src/di/opaque_token.d.ts, found version 2, expected 1
    at StaticReflector.getModuleMetadata (/Users/chuckj/src/angular/modules/@angular/compiler-cli/src/static_reflector.ts:564:15)
    at /Users/chuckj/src/angular/modules/@angular/compiler-cli/src/codegen.ts:162:48
    at Array.forEach (native)
    at extractProgramSymbols (/Users/chuckj/src/angular/modules/@angular/compiler-cli/src/codegen.ts:159:8)
    at CodeGenerator.codegen (/Users/chuckj/src/angular/modules/@angular/compiler-cli/src/codegen.ts:69:9)
    at AotPlugin._make (/tmp/foo/node_modules/@ngtools/webpack/src/plugin.js:193:43)
    at Compiler.<anonymous> (/tmp/foo/node_modules/@ngtools/webpack/src/plugin.js:157:75)
    at Compiler.applyPluginsParallel (/tmp/foo/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/tmp/foo/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/tmp/foo/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/tmp/foo/node_modules/webpack/lib/Compiler.js:456:7)
    at Watching.<anonymous> (/tmp/foo/node_modules/webpack/lib/Compiler.js:46:17)
    at next (/tmp/foo/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.invalidAsyncPlugin (/tmp/foo/node_modules/webpack-dev-middleware/middleware.js:119:3)
    at next (/tmp/foo/node_modules/tapable/lib/Tapable.js:83:14)
    at Compiler.<anonymous> (/tmp/foo/node_modules/webpack/lib/CachePlugin.js:31:4)
    at Compiler.applyPluginsAsync (/tmp/foo/node_modules/tapable/lib/Tapable.js:85:13)
    at Watching._go (/tmp/foo/node_modules/webpack/lib/Compiler.js:44:16)
    at Watching.<anonymous> (/tmp/foo/node_modules/webpack/lib/Compiler.js:36:8)
    at Compiler.readRecords (/tmp/foo/node_modules/webpack/lib/Compiler.js:367:10)
    at new Watching (/tmp/foo/node_modules/webpack/lib/Compiler.js:33:16)
    at Compiler.watch (/tmp/foo/node_modules/webpack/lib/Compiler.js:204:17)
    at module.exports (/tmp/foo/node_modules/webpack-dev-middleware/middleware.js:146:27)
    at new Server (/tmp/foo/node_modules/webpack-dev-server/lib/Server.js:43:20)
    at Class.run (/tmp/foo/node_modules/angular-cli/tasks/serve-webpack.js:74:22)
    at /tmp/foo/node_modules/angular-cli/commands/serve.js:93:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
`
``

So, situation with beta-21
`ng serve` works with both latest and outdated (installed by default) packages
`ng serve --aot` works only with outdated packages and doesn't work with latest packages.

**Comment by alexbyk** [comment]
I'm closing this issue because I made a code refactoring, upgraded node and all packages - I can't tell what caused it for the first place. So for now it can be considered as resolved
