### ISSUE TITLE
Error: channel closed, timeout

### ISSUE THREAD

**Issue by paweloque** [angular/angular-cli#3222]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.20-1
node: 7.0.0
os: darwin x64
```

### Repro steps.
> I'm serving my application using `ng serve`. Afer one reload caused by code changes this problem occurs.

### The log given by the failure.
```Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at runChecker (/Users/pawel/workspace/helloclass-frontend/node_modules/awesome-typescript-loader/src/instance.ts:387:22)
    at invokeFunc (/Users/pawel/workspace/helloclass-frontend/node_modules/lodash/lodash.js:10335:23)
    at trailingEdge (/Users/pawel/workspace/helloclass-frontend/node_modules/lodash/lodash.js:10382:18)
    at Timeout.timerExpired [as _onTimeout] (/Users/pawel/workspace/helloclass-frontend/node_modules/lodash/lodash.js:10370:18)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Can you try with the latest version? We moved away from the loader that seems to have been causing you problems.

**Comment by filipesilva** [comment]
Closing as inactive.
