### ISSUE TITLE
NPM start failed when upgraded to 1.0.0-beta.21   

### ISSUE THREAD

**Issue by hantsy** [angular/angular-cli#3291]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10 64 bit

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
$ ng --version                  
angular-cli: 1.0.0-beta.21      
node: 7.1.0                     
os: win32 x64                   
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

```
npm install -g angular-cli@latest
ng new ng2-hello
cd ng2-hello
npm start <---this step failed.
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
hantsy@HANTSY-T540P E:\temp\ng2-hello
$ npm start

> ng2-hello@0.0.0 start E:\temp\ng2-hello
> ng serve                                                        40927ms building modules                               15ms ad05551ms 564ms asset 95% emitting[default] Checking started in a separate process...               153ms emittingevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.process.stderr.write (E:\temp\ng2-hello\node_modules\angular-cli\lib\cli\index.js:40:27)
    at Console.warn (console.js:51:16)
    at printErrorAndExit (E:\temp\ng2-hello\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:406:11)
    at process.emit (E:\temp\ng2-hello\node_modules\awesome-typescript-loader\node_modules\source-map-support\source-map-support.js:419:16)
    at process._fatalException (bootstrap_node.js:292:26)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ng2-hello@0.0.0 start: `ng serve`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the ng2-hello@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-hello package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with: npm ERR!     npm bugs ng2-hello
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-hello
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\temp\ng2-hello\npm-debug.log
```

**Comment by Nikki1993** [comment]
Regression in Nodejs, update to 7.2.0 This is not cli related

**Comment by hantsy** [comment]
Ok, just updated to NodeJS 7.2, it is disappeared.

Thanks, @Nikki1993
