### ISSUE TITLE
Cannot read property 'transitiveModules' of undefined (still occurring)

### ISSUE THREAD

**Issue by byrneb36** [angular/angular-cli#3303]
### Related Issues
[#2917](https://github.com/angular/angular-cli/issues/2917) (closed)
[#2931](https://github.com/angular/angular-cli/issues/2931) (closed)

### OS?
Ubuntu 14.04.05 LTS

### Versions.
angular-cli: 1.0.0-beta.21
node: 6.2.2
os: linux x64

### Repro steps.
Occurring only when running 'ng build -prod --aot'. 'ng build -prod' and 'ng build -dev' are working fine.

This is occurring in a commercial project I'm developing. I've tried to follow the project template generated by 'ng init' as closely as possible. I also followed the [steps in the readme](https://github.com/angular/angular-cli#updating-angular-cli) about how to upgrade to a new version of the CLI. 

### The log given by the failure.
  0% compilingCannot read property 'transitiveModules' of undefined
TypeError: Cannot read property 'transitiveModules' of undefined
    at addNgModule (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/@angular/compiler/bundles/compiler.umd.js:12949:26)
    at /home/my_username/Desktop/my_angular2_project/client/public/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)
    at OfflineCompiler.compileModules (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/@angular/compiler/bundles/compiler.umd.js:12775:20)
    at CodeGenerator.codegen (/Users/chuckj/src/angular/modules/@angular/compiler-cli/src/codegen.ts:71:26)
    at AotPlugin._make (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/@ngtools/webpack/src/plugin.js:186:43)
    at Compiler.<anonymous> (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/@ngtools/webpack/src/plugin.js:151:75)
    at Compiler.applyPluginsParallel (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/webpack/lib/Compiler.js:456:7)
    at Compiler.<anonymous> (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/webpack/lib/Compiler.js:219:10)
    at Compiler.readRecords (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/webpack/lib/Compiler.js:367:10)
    at Compiler.<anonymous> (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/webpack/lib/Compiler.js:216:9)
    at next (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/webpack/lib/CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.<anonymous> (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/webpack/lib/Compiler.js:213:8)
    at next (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.run (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/webpack/lib/Compiler.js:210:7)
    at /home/my_username/Desktop/my_angular2_project/client/public/node_modules/angular-cli/tasks/build-webpack.js:24:29
    at Class.exports.default.Task.extend.run (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/angular-cli/tasks/build-webpack.js:23:16)
    at Class.Command.extend.run (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/angular-cli/commands/build.js:51:26)
    at Class.<anonymous> (/home/my_username/Desktop/my_angular2_project/client/public/node_modules/angular-cli/angular-cli/lib/models/command.js:152:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Mention any other details that might be useful.
 "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/router": "3.2.1",
    "@ngtools/webpack": "1.1.2",
    "bootstrap": "^4.0.0-alpha.4",
    "clipboard": "^1.5.12",
    "core-js": "^2.4.1",
    "emojione": "^2.2.6",
    "ng2-sharebuttons": "^1.0.6",
    "rxjs": "5.0.0-beta.12",
    "socket.io": "^1.4.8",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.21",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2",
    "typings": "1.3.3"
  }

**Comment by filipesilva** [comment]
There isn't much I can say from the info thus far. If you can get me a simple repro I can investigate.

**Comment by filipesilva** [comment]
Closed as inactive.
