### ISSUE TITLE
 Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by feurjarx** [angular/angular-cli#3307]
### OS
> Linux user-desktop 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

### Versions.
ng version
angular-cli: 1.0.0-beta.21
node: 7.1.0
os: linux x64

### Repro steps.
ng g component components/beat-feed
 
### The log given by the failure.
ng g component components/beat-feed
installing component
  create src/app/components/beat-feed/beat-feed.component.scss
  create src/app/components/beat-feed/beat-feed.component.html
  create src/app/components/beat-feed/beat-feed.component.spec.ts
  create src/app/components/beat-feed/beat-feed.component.ts
Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at visit (/home/user/Projects/prwire/tools/@angular/tsc-wrapped/src/symbols.ts:34:54)
    at visitEachNode (/home/user/Projects/prwire/interface/node_modules/typescript/lib/typescript.js:12983:30)
    at Object.forEachChild (/home/user/Projects/prwire/interface/node_modules/typescript/lib/typescript.js:13143:24)
    at Symbols.buildImports (/home/user/Projects/prwire/tools/@angular/tsc-wrapped/src/symbols.ts:100:10)
    at Symbols.get [as symbols] (/home/user/Projects/prwire/tools/@angular/tsc-wrapped/src/symbols.ts:21:12)
    at Symbols.resolve (/home/user/Projects/prwire/tools/@angular/tsc-wrapped/src/symbols.ts:10:63)
    at /home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/src/ast-utils.js:104:36
    at FilterSubscriber._next (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:86:31)
    at FilterSubscriber.Subscriber.next (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Subscriber.ts:95:12)
    at MapSubscriber._next (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/map.ts:84:22)
    at MapSubscriber.Subscriber.next (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Subscriber.ts:95:12)
    at FilterSubscriber._next (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:92:24)
    at FilterSubscriber.Subscriber.next (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Subscriber.ts:95:12)
    at ReplaySubject._subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/ReplaySubject.ts:41:18)
    at ReplaySubject.Observable.subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:95:21)
    at Observable._subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at Observable.subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:95:21)
    at Observable._subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at FilterOperator.call (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:61:19)
    at Observable.subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at Observable._subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at MapOperator.call (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/map.ts:54:19)
    at Observable.subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at Observable._subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at FilterOperator.call (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:61:19)
    at Observable.subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at Observable._subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at FilterOperator.call (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:61:19)
    at Observable.subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at Observable._subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at MapOperator.call (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/map.ts:54:19)
    at Observable.subscribe (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at /home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/toPromise.ts:24:10
    at Observable.toPromise (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/toPromise.ts:22:10)
    at _addSymbolToNgModuleMetadata (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/src/ast-utils.js:135:10)
    at Object.addDeclarationToModule (/home/user/Projects/prwire/interface/node_modules/@angular-cli/ast-tools/src/ast-utils.js:230:12)
    at Class.afterInstall (/home/user/Projects/prwire/interface/node_modules/angular-cli/blueprints/component/index.js:147:18)
    at tryCatch (/home/user/Projects/prwire/interface/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/home/user/Projects/prwire/interface/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/home/user/Projects/prwire/interface/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/home/user/Projects/prwire/interface/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by redaikidoka** [comment]
Yep, got that too

angular-cli: 1.0.0-beta.19-3
node: 6.9.1
os: darwin x64
OS: **System Version: macOS 10.12.1 (16B2555)**
`ng g component components/framework-picker`

installing component
  create src/app/components/framework-picker/framework-picker.component.scss
  create src/app/components/framework-picker/framework-picker.component.html
  create src/app/components/framework-picker/framework-picker.component.spec.ts
  create src/app/components/framework-picker/framework-picker.component.ts
Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at visit (/Users/pol/Dev/coach/tools/@angular/tsc-wrapped/src/symbols.ts:34:54)
  at visitEachNode (/Users/pol/Dev/coach/rambutan/node_modules/typescript/lib/typescript.js:12983:30)
    at Object.forEachChild (/Users/pol/Dev/coach/rambutan/node_modules/typescript/lib/typescript.js:13143:24)
    at Symbols.buildImports (/Users/pol/Dev/coach/tools/@angular/tsc-wrapped/src/symbols.ts:100:10)
    at Symbols.get [as symbols] (/Users/pol/Dev/coach/tools/@angular/tsc-wrapped/src/symbols.ts:21:12)
    at Symbols.resolve (/Users/pol/Dev/coach/tools/@angular/tsc-wrapped/src/symbols.ts:10:63)
    at /Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/src/ast-utils.js:104:36
    at FilterSubscriber._next (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:86:31)
    at FilterSubscriber.Subscriber.next (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Subscriber.ts:95:12)
    at MapSubscriber._next (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/map.ts:84:22)
    at MapSubscriber.Subscriber.next (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Subscriber.ts:95:12)
    at FilterSubscriber._next (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:92:24)
    at FilterSubscriber.Subscriber.next (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Subscriber.ts:95:12)
    at ReplaySubject._subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/ReplaySubject.ts:41:18)
    at ReplaySubject.Observable.subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:95:21)
    at Observable._subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at Observable.subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:95:21)
    at Observable._subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at FilterOperator.call (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:61:19)
    at Observable.subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at Observable._subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at MapOperator.call (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/map.ts:54:19)
    at Observable.subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at Observable._subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at FilterOperator.call (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:61:19)
    at Observable.subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at Observable._subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at FilterOperator.call (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/filter.ts:61:19)
    at Observable.subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at Observable._subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:155:24)
    at MapOperator.call (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/map.ts:54:19)
    at Observable.subscribe (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/Observable.ts:93:16)
    at /Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/toPromise.ts:24:10
    at Observable.toPromise (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/node_modules/rxjs/src/operator/toPromise.ts:22:10)
    at _addSymbolToNgModuleMetadata (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/src/ast-utils.js:135:10)
    at Object.addDeclarationToModule (/Users/pol/Dev/coach/rambutan/node_modules/@angular-cli/ast-tools/src/ast-utils.js:230:12)
    at Class.afterInstall (/Users/pol/Dev/coach/rambutan/node_modules/angular-cli/blueprints/component/index.js:132:18)
    at tryCatch (/Users/pol/Dev/coach/rambutan/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/pol/Dev/coach/rambutan/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/pol/Dev/coach/rambutan/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/pol/Dev/coach/rambutan/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by thorsten** [comment]
Yes, happens on my system as well:

angular-cli: 1.0.0-beta.18
node: 7.0.0
os: darwin x64 (OS X 10.11.6)
TypeScript: 2.1.1

**Comment by elciomgdf** [comment]
here too

**Comment by fxcosta** [comment]
Here too:

node: 6.5.0
angular-cli: 1.0.0-beta.17
os: linux mint 17 x64

**Comment by andreykhr** [comment]
Me too:

node: 6.9.1
angular-cli: 1.0.0-beta.21
os: win32 x64

**Comment by rocklob** [comment]
Same here.

MacOS Sierra 
angular-cli: 1.0.0-beta.21
node: 6.8.1
os: darwin x64

**Comment by Meligy** [comment]
This should be fixed now in master.
