### ISSUE TITLE
e2e test keep failing because of "TypeError: ngtools.PathsPlugin is not a function"

### ISSUE THREAD

**Issue by changLiuUNSW** [angular/angular-cli#3357]
Always get following error: 
```
  Running `ng "test" "--single-run" "--no-progress"` [silent]...
  CWD: /tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project
Last step took 73.94s...
[Error: Running "ng test --single-run --no-progress" returned error code 1...
STDOUT:
ngtools.PathsPlugin is not a function
TypeError: ngtools.PathsPlugin is not a function
    at getWebpackTestConfig (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/models/webpack-build-test.js:63:9)
    at Object.keys.filter.map.map (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/plugins/karma.js:21:25)
    at Array.invoke (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/di/lib/injector.js:75:15)
    at null.get (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/di/lib/injector.js:48:43)
    at /tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at null.Server._start (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/karma/lib/server.js:142:21)
    at null.invoke (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/di/lib/injector.js:75:15)
    at null.Server.start (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/karma/lib/server.js:103:18)
    at /tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/tasks/test.js:33:25
    at initializePromise (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:244:5)
    at new Promise (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/promise.js:135:31)
    at Class.exports.default.Task.extend.run (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/tasks/test.js:15:16)
    at Class.TestCommand.extend.run (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/commands/test.js:31:25)
    at Class.<anonymous> (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:195:12)
    at invokeCallback (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:210:13)
    at /tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/then.js:24:16
    at flush (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/asap.js:94:5)
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
]
Test "tests/commands/new/new-routing" failed...
Running "ng test --single-run --no-progress" returned error code 1...
STDOUT:
ngtools.PathsPlugin is not a function
TypeError: ngtools.PathsPlugin is not a function
    at getWebpackTestConfig (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/models/webpack-build-test.js:63:9)
    at Object.keys.filter.map.map (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/plugins/karma.js:21:25)
    at Array.invoke (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/di/lib/injector.js:75:15)
    at null.get (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/di/lib/injector.js:48:43)
    at /tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at null.Server._start (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/karma/lib/server.js:142:21)
    at null.invoke (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/di/lib/injector.js:75:15)
    at null.Server.start (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/karma/lib/server.js:103:18)
    at /tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/tasks/test.js:33:25
    at initializePromise (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:244:5)
    at new Promise (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/promise.js:135:31)
    at Class.exports.default.Task.extend.run (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/tasks/test.js:15:16)
    at Class.TestCommand.extend.run (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/commands/test.js:31:25)
    at Class.<anonymous> (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/angular-cli/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:195:12)
    at invokeCallback (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:210:13)
    at /tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/then.js:24:16
    at flush (/tmp/angular-cli-e2e-116112-3742-1an2fus/routing-project/node_modules/es6-promise/dist/lib/es6-promise/asap.js:94:5)
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
```

https://travis-ci.org/angular/angular-cli/jobs/180732186
https://travis-ci.org/angular/angular-cli/jobs/180651819
https://travis-ci.org/angular/angular-cli/jobs/180666306

**Comment by hansl** [comment]
Experimental releases are to be used at your own risk.

**Comment by changLiuUNSW** [comment]
Hi @hansl
This error is the e2e test of angular-cli. Looks like all the new PRs failed because of this.....

**Comment by hansl** [comment]
Yes I'm looking at it, I saw that this morning.
