### ISSUE TITLE
Cannot find module 'typescript' when executing ng commands

### ISSUE THREAD

**Issue by saurav1005** [angular/angular-cli#3447]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 8

### Versions.
> getting error cannot find module 'typescript' when ng --version is executed

### Repro steps.
> Installed npm install -g angular-cli 

### The log given by the failure.
Cannot find module 'typescript'
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\nodejs_modules\node_modules\@angular\tsc-wrapped\s
rc\tsc.js:11:10)

### Mention any other details that might be useful.

node version - 6.3.1
npm version - 4.0.3
Have already validated that typescript module exists under angular-cli.

> Thanks! We'll be in touch soon.

**Comment by baruchvlz** [comment]
Do you have typescript installed globally ?

**Comment by saurav1005** [comment]
Yes, I have typescript available globally with below version details
>tsc --version
Version 2.0.10

**Comment by hansl** [comment]
The best I can tell you is to uninstall angular-cli globally, run `npm cache clean` and reinstall. Also, I did some cleanup for dependencies that might help in the next beta release. That should also fix some issues with yarn (not sure if that's what you used).

**Comment by luchillo17** [comment]
@hansl What about mine? i'm totally confused because it works on a Win 10 PC, but not in an Ubuntu 17.10:
![image](https://user-images.githubusercontent.com/9698639/33103062-eea7cada-ceed-11e7-8fba-b66eb7e28100.png)

*Btw:* That's the Yarn output, but same output from NPM@5

**Comment by luchillo17** [comment]
It can be seen that for some reason it's looking for **typescript** very far back in the folder structure, the weird thing is that i cloned the project, and it was OK in Win 10, but not in Ubuntu 17.10.

**Comment by mohyeid** [comment]
Mine totally runs fine in Windows 7, but I get the same error in linux machine. I can verify tsc runs fine. tsc -v: 2.4.2 and ng -v: 1.5.4. I still get tis error: 

Cannot find module 'typescript' from '/local/build/jenkins/.....'
Error: Cannot find module 'typescript' from '/local/build/jenkins/....'
    at Function.module.exports [as sync] (/local/build/jenkins/..../node_modules/resolve/lib/sync.js:40:15)
    at Object.requireProjectModule (/local/build/jenkins/..../node_modules/@angular/cli/utilities/require-project-module.js:6:28)
    at Object.readTsconfig (/local/build/jenkins/..../node_modules/@angular/cli/utilities/read-tsconfig.js:6:48)
    at new NgCliWebpackConfig (/local/build/jenkins/..../node_modules/@angular/cli/models/webpack-config.js:19:42)
    at Class.run (/local/build/jenkins/..../node_modules/@angular/cli/tasks/build.js:30:31)
    at Class.run (/local/build/jenkins/..../node_modules/@angular/cli/commands/build.js:216:26)
    at resolve (/local/build/jenkins/..../node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at Class.validateAndRun (/local/build/jenkins/..../node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/local/build/jenkins/..../node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)

Can someone help?

**Comment by ruben2079** [comment]
I have the same issue as you @luchillo17. How can I change the path. project is looking for typescript on the 'C:\' drive? How was this fixed?
