### ISSUE TITLE
Bug: generating services with PascalCase name results in errors

### ISSUE THREAD

**Issue by silhouette** [angular/angular-cli#350]
Working under Ubuntu 14.04 with node 5.9.1, npm  3.8.3, angular-cli 0.0.27. 

When I generate an app with ng new MyProject, change to the project folder and then add a service via:

ng g service TestService

a build fails afterwards, as the service in the spec file is incorrectly referenced as test-service. When I fix this, the build succeeds, but "ng test" fails with the following message:

WARN [web-server]: 404: /base/dist/app/services/TestService
Chrome 49.0.2623 (Linux 0.0.0) ERROR
  Error: XHR error (404 Not Found) loading .../dist/app/services/TestService
      at error (.../node_modules/systemjs/dist/system.src.js:1026:16)
      at XMLHttpRequest.xhr.onreadystatechange [as _onreadystatechange] (.../node_modules/systemjs/dist/system.src.js:1047:13)
      at ZoneDelegate.invokeTask (.../node_modules/angular2/bundles/angular2-polyfills.js:355:38)
      at Zone.runTask (.../node_modules/angular2/bundles/angular2-polyfills.js:254:48)
      at XMLHttpRequest.ZoneTask.invoke (.../node_modules/angular2/bundles/angular2-polyfills.js:422:34)

When I run the same with

ng g service test-service

everything works like it should.

**Comment by Brocco** [comment]
This was resolved as part of PR #401
The name being used was not of the correct format, it will be available in the next release.
