### ISSUE TITLE
[AOT] @ngtools/webpack throws 'Error: Cannot find module '@angular/tsc-wrapped/src/tsc'

### ISSUE THREAD

**Issue by jlabaj** [angular/angular-cli#3541]
"@angular/tsc-wrapped": "^0.3.0", dependency missing in @ngtools/webpack/package.json

**Comment by andrrrl** [comment]
Win7 64
node 6.9.2
npm 4.0.5

`ng help` shows this (and couldn't find an alternative way to install tsc-wrapped):
```
Cannot find module '@angular/tsc-wrapped/src/tsc'
Error: Cannot find module '@angular/tsc-wrapped/src/tsc'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\
angular-cli\node_modules\@ngtools\webpack\src\plugin.js:7:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\
angular-cli\node_modules\@ngtools\webpack\src\index.js:6:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\
angular-cli\models\webpack-build-typescript.js:3:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\
angular-cli\models\webpack-config.js:2:34)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\
angular-cli\tasks\build-webpack.js:6:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\
angular-cli\commands\build.js:3:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (C:\Users\avelazquez\AppData\Roaming\npm\node_modu
les\angular-cli\addon\index.js:21:16)
    at C:\Users\avelazquez\AppData\Roaming\npm\node_modules\angular-cli\angular-
cli\lib\models\project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (C:\Users\avelazquez\AppData\Roaming\npm\node_modul
es\angular-cli\angular-cli\lib\models\project.js:391:15)
    at Project.eachAddonCommand (C:\Users\avelazquez\AppData\Roaming\npm\node_mo
dules\angular-cli\angular-cli\lib\models\project.js:426:30)
    at module.exports (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\angu
lar-cli\angular-cli\lib\cli\lookup-command.js:33:13)
    at CLI.<anonymous> (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\ang
ular-cli\angular-cli\lib\cli\cli.js:34:26)
    at tryCatch (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\angular-cl
i\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\angu
lar-cli\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\angular-cli
\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (C:\Users\avelazquez\AppData\Roaming\npm\node_modules\angular-cli\n
ode_modules\rsvp\dist\rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by filipesilva** [comment]
This should be fixed now in latest, it happened due to a bad release.
