### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by GuillaumeUnice** [angular/angular-cli#360]
I am filing a bug.
OS.  Linux (Ubuntu 14.04 distribution)
2. Versions :
angular-cli: 0.0.28
node: 4.4.1
npm 3.8.3
os: linux x64

When I run ng serve --port 4201 --live-reload-port 49153 I have this following error :
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Cannot read property 'push' of undefined
TypeError: Cannot read property 'push' of undefined
    at addPathRecursive (/home/21307458/angularCli/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:21)
    at /home/21307458/angularCli/node_modules/angular-cli/lib/broccoli/angular2-app.js:57:9
    at Array.forEach (native)
    at addPathRecursive (/home/21307458/angularCli/node_modules/angular-cli/lib/broccoli/angular2-app.js:56:32)
    at Array.forEach (native)
    at Angular2App.toTree (/home/21307458/angularCli/node_modules/angular-cli/lib/broccoli/angular2-app.js:50:29)
    at module.exports (/home/21307458/angularCli/angular-cli-build.js:9:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/21307458/angularCli/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/21307458/angularCli/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/21307458/angularCli/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)

Thank for your help

**Comment by pierreboissinot** [comment]
Hi, there is already an open issue about that, I invite you to check that: issue #343

**Comment by filipesilva** [comment]
Heya, I'm closing this because as @pierreboissinot said, it is a duplicate. The other issue has loads more discussion in it.
