### ISSUE TITLE
A lot of errors after update to 22-1

### ISSUE THREAD

**Issue by sharok** [angular/angular-cli#3621]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
 Windows 10. 

### Versions.

angular-cli: 1.0.0-beta.22-1
node: 7.2.1
os: win32 x64

### Mention any other details that might be useful.
I have a very big application, all worked fine for 20-4 version. Today, I tried to update  to 22-1 version.
I know how to update. I did it before, all worked fine. But, now, on build I have a huge amount of errors(218 errors).
But, when I create app with help of `ng new` command all works fine.

Some errors are repeatable, so I post unique only:

Some errors contains `Subscription`, some errors contain `Observable`, 'Subject', 'Subscription'.
```
Uncaught Error: Module build failed: Error: C:/Projects/qwe/src/app/shared/layout/layout.service.ts (50,3): Return type of public method from exported class has or is using name 'Subscription' from external module "C:/Projects/qwe/node_modules/rxjs/Subscription" but cannot be named.)
    at _checkDiagnostics (C:\Projects\qwe\node_modules\@ngtools\webpack\src\loader.js:115:15)
    at C:\Projects\qwe\node_modules\@ngtools\webpack\src\loader.js:140:17
    at _checkDiagnostics (C:\Projects\qwe\node_modules\@ngtools\webpack\src\loader.js:115:15)
    at C:\Projects\qwe\node_modules\@ngtools\webpack\src\loader.js:140:17
    at Object.<anonymous> (http://localhost:4200/main.bundle.js:543:7)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.<anonymous> (http://localhost:4200/main.bundle.js:29:81)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.<anonymous> (http://localhost:4200/main.bundle.js:12908:84)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.<anonymous> (http://localhost:4200/main.bundle.js:12977:70)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.<anonymous> (http://localhost:4200/main.bundle.js:8002:64)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
```

I have errors for `jsdom`, `location` etc.
```
vendor.bundle.js:79373 ./~/jquery/lib/node-jquery.js
Module not found: Error: Can't resolve 'jsdom' in 'C:\Projects\qwe\node_modules\jquery\lib'
resolve 'jsdom' in 'C:\Projects\qwe\node_modules\jquery\lib'
  Parsed request is a module
  using description file: C:\Projects\qwe\node_modules\jquery\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Projects\qwe\node_modules\jquery\package.json (relative path: ./lib)
    resolve as module
      looking for modules in C:\Projects\qwe\src
        using description file: C:\Projects\qwe\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Projects\qwe\package.json (relative path: ./src)
          using description file: C:\Projects\qwe\package.json (relative path: ./src/jsdom)
            as directory
              C:\Projects\qwe\src\jsdom doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\src\jsdom doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\src\jsdom.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\src\jsdom.js doesn't exist
      looking for modules in C:\Projects\qwe\node_modules
        using description file: C:\Projects\qwe\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Projects\qwe\package.json (relative path: ./node_modules)
          using description file: C:\Projects\qwe\package.json (relative path: ./node_modules/jsdom)
            as directory
              C:\Projects\qwe\node_modules\jsdom doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\node_modules\jsdom doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\node_modules\jsdom.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\node_modules\jsdom.js doesn't exist
[C:\Projects\qwe\src\jsdom]
[C:\Projects\qwe\src\jsdom]
[C:\Projects\qwe\src\jsdom.ts]
[C:\Projects\qwe\src\jsdom.js]
[C:\Projects\qwe\node_modules\jsdom]
[C:\Projects\qwe\node_modules\jsdom]
[C:\Projects\qwe\node_modules\jsdom.ts]
[C:\Projects\qwe\node_modules\jsdom.js]
 @ ./~/jquery/lib/node-jquery.js 5:13-29
 @ ./src/polyfills.ts
 @ ./src/main.ts
 @ multi main
```

This error for all files where I have routing:
```
./src/app/app.routing.ts
Module build failed: Error: C:/Projects/qwe/src/app/app.routing.ts (71,14): Exported variable 'routing' has or is using name 'ModuleWithProviders' from external module "C:/Projects/qwe/node_modules/@angular/core/src/metadata/ng_module" but cannot be named.)
    at _checkDiagnostics (C:\Projects\qwe\node_modules\@ngtools\webpack\src\loader.js:115:15)
    at C:\Projects\qwe\node_modules\@ngtools\webpack\src\loader.js:140:17
 @ ./src/app/app.module.ts 13:0-40
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

And, of course, a lot of errors about module not found:
```
./src/app/shared/user-shared/login-info/login-info.component.ts
Module not found: Error: Can't resolve 'login-info.component.html' in 'C:\Projects\qwe\src\app\shared\user-shared\login-info'
resolve 'login-info.component.html' in 'C:\Projects\qwe\src\app\shared\user-shared\login-info'
  Parsed request is a module
  using description file: C:\Projects\qwe\package.json (relative path: ./src/app/shared/user-shared/login-info)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Projects\qwe\package.json (relative path: ./src/app/shared/user-shared/login-info)
    resolve as module
      looking for modules in C:\Projects\qwe\src
        using description file: C:\Projects\qwe\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Projects\qwe\package.json (relative path: ./src)
          using description file: C:\Projects\qwe\package.json (relative path: ./src/login-info.component.html)
            as directory
              C:\Projects\qwe\src\login-info.component.html doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\src\login-info.component.html doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\src\login-info.component.html.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\src\login-info.component.html.js doesn't exist
      looking for modules in C:\Projects\qwe\node_modules
        using description file: C:\Projects\qwe\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Projects\qwe\package.json (relative path: ./node_modules)
          using description file: C:\Projects\qwe\package.json (relative path: ./node_modules/login-info.component.html)
            as directory
              C:\Projects\qwe\node_modules\login-info.component.html doesn't exist
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\node_modules\login-info.component.html doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\node_modules\login-info.component.html.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\qwe\node_modules\login-info.component.html.js doesn't exist
[C:\Projects\qwe\src\login-info.component.html]
[C:\Projects\qwe\src\login-info.component.html]
[C:\Projects\qwe\src\login-info.component.html.ts]
[C:\Projects\qwe\src\login-info.component.html.js]
[C:\Projects\qwe\node_modules\login-info.component.html]
[C:\Projects\qwe\node_modules\login-info.component.html]
[C:\Projects\qwe\node_modules\login-info.component.html.ts]
[C:\Projects\qwe\node_modules\login-info.component.html.js]
 @ ./src/app/shared/user-shared/login-info/login-info.component.ts 30:22-58
 @ ./src/app/shared/user-shared/user-shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

**Comment by rosdi** [comment]
Does this help? http://stackoverflow.com/questions/40035976/how-to-configure-and-use-jquery-with-webpack

**Comment by sharok** [comment]
Yes, the same errors as in the question. But, I don't think it's possible to use  ProvidePlugin in cli.
Anyway, I solved it, just deleted `node_modules` and installed again.

**Comment by st-clair-clarke** [comment]
Revert your angular-cli to angular-cli@1.0.0-beta.21 following the instructions at [https://github.com/angular/angular-cli#updating-angular-cli](https://github.com/angular/angular-cli#updating-angular-cli)
