### ISSUE TITLE
@ngtools/webpack seems to pick up more files than it should

### ISSUE THREAD

**Issue by wesleycho** [angular/angular-cli#3637]
### OS?
Mac OSX El Capitan

### Versions.
Node 4.5.0, not using CLI directly (issue is specific to @ngtools/webpack & AoT compilation)

### Repro steps.
Add an AoT non-compliant module to the same directory as the entry module but not link it.

### The log given by the failure.
Stack trace
```
  0% compiling/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler-cli/src/static_reflector.js:475
                throw new Error(message);
                ^

Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppDevModule in /Users/wesley/dev/web/mf-trainer-arranger/src/app/app.dev.module.ts, resolving symbol AppDevModule in /Users/wesley/dev/web/mf-trainer-arranger/src/app/app.dev.module.ts
    at simplifyInContext (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler-cli/src/static_reflector.js:475:23)
    at StaticReflector.simplify (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler-cli/src/static_reflector.js:478:22)
    at StaticReflector.annotations (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler-cli/src/static_reflector.js:60:36)
    at NgModuleResolver.resolve (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler/bundles/compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler/bundles/compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler/bundles/compiler.umd.js:14636:23)
    at addNgModule (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler/bundles/compiler.umd.js:12944:43)
    at /Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler/bundles/compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler/bundles/compiler.umd.js:12956:28)
    at analyzeNgModules (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler/bundles/compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler/bundles/compiler.umd.js:12704:20)
    at OfflineCompiler.compileModules (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler/bundles/compiler.umd.js:12775:20)
    at CodeGenerator.codegen (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@angular/compiler-cli/src/codegen.js:58:30)
    at AotPlugin._make (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@ngtools/webpack/src/plugin.js:193:43)
    at Compiler.<anonymous> (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/@ngtools/webpack/src/plugin.js:157:75)
    at Compiler.applyPluginsParallel (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/tapable/lib/Tapable.js:156:14)
    at /Users/wesley/dev/web/mf-trainer-arranger/node_modules/webpack/lib/Compiler.js:468:8
    at Compiler.applyPluginsAsync (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/webpack/lib/Compiler.js:461:7)
    at /Users/wesley/dev/web/mf-trainer-arranger/node_modules/webpack/lib/Compiler.js:222:10
    at Compiler.readRecords (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/webpack/lib/Compiler.js:371:10)
    at /Users/wesley/dev/web/mf-trainer-arranger/node_modules/webpack/lib/Compiler.js:219:9
    at next (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/webpack/lib/CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/tapable/lib/Tapable.js:85:13)
    at /Users/wesley/dev/web/mf-trainer-arranger/node_modules/webpack/lib/Compiler.js:216:8
    at next (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (/Users/wesley/dev/web/mf-trainer-arranger/node_modules/tapable/lib/Tapable.js:85:13)
```

### Mention any other details that might be useful.
I have separate webpack configs for the dev, testing, and build environments, and am attempting to wire in AoT compilation into the build webpack config. `AppDevModule` is in a file `app.dev.module.ts` that is excluded in the `tsconfig.aot.json` I am using in this project, and `AppAotModule` is my entry module (which no linkage to `AppDevModule` in the file imports).

@ngtools/webpack will work properly if I use `includes` in `tsconfig.aot.json` (or whatever tsconfig the user specified), but it should already be able to use the specified `entryModule` as the included file to start with.

cc @robwormald

**Comment by filipesilva** [comment]
@hansl can you look at this one?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
