### ISSUE TITLE
stream:74 error when serving newly created app

### ISSUE THREAD

**Issue by nfdevil** [angular/angular-cli#3639]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
ng version
angular-cli: 1.0.0-beta.22-1 
node: 7.1.0    
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
ng new reduxtesting
cd ngreduxtesting
ng serve

### The log given by the failure.
> Normally this include a stack trace and some more information.
ng serve                                                       stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.process.stderr.write (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\lib\cli\index.js:40:27)
    at defaultHandler (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\ProgressPlugin.js:175:18)
    at Compiler.<anonymous> (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\ProgressPlugin.js:130:4)
    at Compiler.applyPlugins (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\tapable\lib\Tapable.js:25:14)
    at Watching._done (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compiler.js:92:17)
    at Watching.<anonymous> (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compiler.js:75:18)
    at Compiler.emitRecords (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compiler.js:347:37)
    at Watching.<anonymous> (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compiler.js:58:19)
    at C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compiler.js:340:11
    at next (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\tapable\lib\Tapable.js:102:11)
    at Compiler.<anonymous> (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@ngtools\webpack\src\plugin.js:171:13)
    at Compiler.applyPluginsAsyncSeries (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\tapable\lib\Tapable.js:106:13)
    at Compiler.afterEmit (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compiler.js:337:8)
    at Compiler.<anonymous> (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compiler.js:332:14)
    at C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\async\lib\async.js:236:30)
    at Object.async.forEach.async.each (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\node_modules\async\lib\async.js:209:22)
    at Compiler.emitFiles (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack\lib\Compiler.js:300:20)
    at Immediate.<anonymous> (C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:288:4)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

### Mention any other details that might be useful.
Installing the CLI gave some weird errors too that might have caused this:
npm install -g angular-cli
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\devil\AppData\Roaming\npm\ng -> C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\bin\ng

> execSync@1.0.2 install C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ Error: spawn node-gyp ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.

> node-zopfli@2.0.2 install C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

[node-zopfli] Success: "C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v51-win32-x64\zopfli.node" is installed via remote

> node-sass@3.13.1 install C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\devil\AppData\Roaming\npm-cache\node-sass\3.13.1\win32-x64-51_binding.node

> node-sass@3.13.1 postinstall C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\devil\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-51\binding.node
Testing binary
Binary is fine

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Heya can you try again with latest? I can't repro this myself and it seems like a weird install failure.

**Comment by udos86** [comment]
Should be fixed by upgrading to the lastet Node.js version

**Comment by filipesilva** [comment]
Closing as inactive.
