### ISSUE TITLE
App served with --aot throws error in DomRenderer (Angular Material docs site)

### ISSUE THREAD

**Issue by jelbourn** [angular/angular-cli#3647]
### OS?
OSX El Capitan

### Versions.
1.0.0-beta.22-1

### Repro steps.
* Clone https://github.com/angular/material.angular.io at ff9cf2e6b7596af331a96aba97fea39191034459
* `npm i`
* `ng serve --aot`
* Open the site, click the "DOCS" link at the top, and then click "Button"

### The log given by the failure.
```
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at flattenStyles (http://localhost:4200/vendor.bundle.js:22990:26)
    at new DomRenderer (http://localhost:4200/vendor.bundle.js:22769:24)
    at DomRootRenderer_.DomRootRenderer.renderComponent (http://localhost:4200/vendor.bundle.js:22727:24)
    at DebugDomRootRenderer.renderComponent (http://localhost:4200/vendor.bundle.js:48242:52)
    at ViewUtils.renderComponent (http://localhost:4200/vendor.bundle.js:548:31)
    at View_ComponentViewer0.AppView (http://localhost:4200/vendor.bundle.js:1839:39)
    at new View_ComponentViewer0 (http://localhost:4200/main.bundle.js:5819:16)
    at View_ComponentViewer_Host0.createInternal (http://localhost:4200/main.bundle.js:5789:27)
    at View_ComponentViewer_Host0.AppView.createHostView (http://localhost:4200/vendor.bundle.js:1870:21)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:1489:25)
```

Only happens on this route, the rest of the app seems okay.

**Comment by jeremymwells** [comment]
@jelbourn - is this still an issue? I don't see "DOCS" at the top, but when I click Components > Button, I do not see any errors.
![aoterror](https://cloud.githubusercontent.com/assets/5454876/21752023/00585b58-d59f-11e6-9866-27cce7830d9a.gif)

**Comment by jelbourn** [comment]
It was resolved in the subsequent CLI release.
