### ISSUE TITLE
Error on file changes:  Cannot read property 'reload' of undefined

### ISSUE THREAD

**Issue by RicardoVaranda** [angular/angular-cli#3702]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: darwin x64
@angular/common: 2.4.0
@angular/compiler: 2.4.0
@angular/core: 2.4.0
@angular/forms: 2.4.0
@angular/http: 2.4.0
@angular/platform-browser: 2.4.0
@angular/platform-browser-dynamic: 2.4.0
@angular/router: 3.3.1
@angular/compiler-cli: 2.4.1
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Make a change on your project while running it with ng serve, it tries to reload the page but gets this error.

### The log given by the failure.
> Normally this include a stack trace and some more information.
```
[WDS] App updated. Recompiling...
[WDS] App updated. Reloading...
Uncaught TypeError: Cannot read property 'reload' of undefined
    at reloadApp (http://10.26.3.138:4200/vendor.bundle.js:76281:16)
    at Object.ok (http://10.26.3.138:4200/vendor.bundle.js:76209:3)
    at SockJS.sock.onmessage (http://10.26.3.138:4200/vendor.bundle.js:120462:22)
    at SockJS.EventTarget.dispatchEvent (http://10.26.3.138:4200/vendor.bundle.js:75371:20)
    at http://10.26.3.138:4200/vendor.bundle.js:117887:16
    at Array.forEach (native)
    at SockJS._transportMessage (http://10.26.3.138:4200/vendor.bundle.js:117885:17)
    at WebSocketTransport.EventEmitter.emit (http://10.26.3.138:4200/vendor.bundle.js:6573:18)
    at WebSocketTransport.ws.onmessage (http://10.26.3.138:4200/vendor.bundle.js:119255:10)
    at WebSocket.wrapFn [as _onmessage] (http://10.26.3.138:4200/vendor.bundle.js:121616:29)
    at ZoneDelegate.invokeTask (http://10.26.3.138:4200/vendor.bundle.js:121002:35)
    at Zone.runTask (http://10.26.3.138:4200/vendor.bundle.js:120878:47)
    at WebSocket.ZoneTask.invoke (http://10.26.3.138:4200/vendor.bundle.js:121072:33)
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Couldn't repro with `ng serve` and some file changes. Also weird that you're getting an error from the vendor bundle. You might be using a lib that's also getting the webpack dev server reload events.
