### ISSUE TITLE
cannot find module 'typescript'

### ISSUE THREAD

**Issue by AlfieriChou** [angular/angular-cli#3754]
> Please provide us with the following information:
> ---------------------------------------------------------------
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\alfieri\AppData\Roaming\npm\node_modules\angular-cli\lib\bootstrap-local.js:6:12)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
win10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
I don't know how you installed your CLI but using bootstrap-local means you're use a local repo. We have different installation procedures for that. If you want to use the CLI, you have to install it from npm.
