### ISSUE TITLE
Bundling for lazy loading is broken: No module factory available

### ISSUE THREAD

**Issue by yfain** [angular/angular-cli#3793]
After upgrading CLI to beta.24 my app that uses lazy loaded module started giving me errors during ng serve:

 NG Live Development Server is running on http://lo 60% building modules 515/611 modules 96 active .../compiler/src/i18n/serializers/xtb.jsError: No module factory available for dependency type: ContextElementDependency
    at Compilation.addModuleDependencies (/Users/yfain11/Documents/Farata/_Training/courseware/angular2/handouts/12-hr-intro/unit2/router-samples/node_modules/webpack/lib/Compilation.js:188:20)
    at Compilation.processModuleDependencies (/Users/yfain11/Documents/Farata/_Training/courseware/angular2/handouts/12-hr-intro/unit2/router-samples/node_modules/webpack/lib/Compilation.js:177:7)
    at /Users/yfain11/Documents/Farata/_Training/courseware/angular2/handouts/12-hr-intro/unit2/router-samples/node_modules/webpack/lib/Compilation.js:317:12
    at /Users/yfain11/Documents/Farata/_Training/courseware/angular2/handouts/12-hr-intro/unit2/router-samples/node_modules/webpack/lib/Compilation.js:124:4
    at Array.forEach (native)
    at callback (/Users/yfain11/Documents/Farata/_Training/courseware/angular2/handouts/12-hr-intro/unit2/router-samples/node_modules/webpack/lib/Compilation.js:123:12)
    at /Users/yfain11/Documents/Farata/_Training/courseware/angular2/handouts/12-hr-intro/unit2/router-samples/node_modules/webpack/lib/Compilation.js:147:10
    at ContextModule.<anonymous> (/Users/yfain11/Documents/Farata/_Training/courseware/angular2/handouts/12-hr-intro/unit2/router-samples/node_modules/webpack/lib/ContextModule.js:93:3)
    at /Users/yfain11/Documents/angular-cli/packages/@ngtools/webpack/src/utils.ts:11:13
    at /Users/yfain11/Documents/angular-cli/packages/@ngtools/webpack/src/plugin.ts:196:124
    at ContextModule.resolveDependencies (/Users/yfain11/Documents/angular-cli/packages/@ngtools/webpack/src/utils.ts:5:9)
    at ContextModule.build (/Users/yfain11/Documents/Farata/_Training/courseware/angular2/handouts/12-hr-intro/unit2/router-samples/node_modules/webpack/lib/ContextModule.js:74:7)
    at Compilation.buildModule (/Users/yfain11/Documents/Farata/_Training/courseware/angular2/handouts/12-hr-intro/unit2/router-samples/node_modules/webpack/lib/Compilation.js:127:9)

===

I downgraded CLI to beta.22-1 in devDependencies in package.json. The error remained the same.
After downgrading to beta.21 the ng serve and the app work fine again.

**Comment by filipesilva** [comment]
I'm going to have to ask you to fill in the issue template, complete with repro steps. There just isn't much I can figure out just by looking at that log.

**Comment by yfain** [comment]
To reproduce, download this project:
https://github.com/Farata/angular2typescript/tree/master/chapter3/cli_version/router-samples

ng serve builds a simple app with the lazy loading of one module (LuxuryModule), and it runs fine. Currently it uses Angular CLI beta.21.  Change the version of Angular CLI to beta.24 in package.json and do npm install.

Try ng serve again, and you'll see this error.

**Comment by viltsu** [comment]
I had same issue to get it working I had to run it with `npm start` instead of `ng serve`

**Comment by retep007** [comment]
@viltsu this definitely isn't fix as npm start is just alias for ng serve, nothing more.

**Comment by ChrisProlls** [comment]
Same error for me. Any news ?

**Comment by yfain** [comment]
After reporting this issue I split the bootstrap code (main.ts) and the app.module.ts into separate files and this error was gone.

**Comment by RubensTen** [comment]
you can try

https://github.com/angular/angular-cli/issues/4246#issuecomment-369477979
