### ISSUE TITLE
Lazy load not working?

### ISSUE THREAD

**Issue by wpfeiffe** [angular/angular-cli#3851]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7 and/or  OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.24
node: 6.9.2
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

### Repro steps.
Created app with angular-cli, added 3 components.  Added router code/links to route between first two components that were imported directed, added code to perform lazy load module routing to third component.

### The log given by the failure.
```
error_handler.js:50 EXCEPTION: Uncaught (in promise): Error: Cannot find module './comp3/comp3.module'.
Error: Cannot find module './comp3/comp3.module'.
    at webpackEmptyContext (http://localhost:4200/main.bundle.js:77:8) [angular]
    at SystemJsNgModuleLoader.loadAndCompile (http://localhost:4200/vendor.bundle.js:80264:40) [angular]
    at SystemJsNgModuleLoader.load (http://localhost:4200/vendor.bundle.js:80252:60) [angular]
    at RouterConfigLoader.loadModuleFactory (http://localhost:4200/vendor.bundle.js:24849:128) [angular]
    at RouterConfigLoader.load (http://localhost:4200/vendor.bundle.js:24836:81) [angular]
    at MergeMapSubscriber.project (http://localhost:4200/vendor.bundle.js:84673:111) [angular]
    at MergeMapSubscriber._tryNext (http://localhost:4200/vendor.bundle.js:25052:27) [angular]
    at MergeMapSubscriber._next (http://localhost:4200/vendor.bundle.js:25042:18) [angular]
    at MergeMapSubscriber.Subscriber.next (http://localhost:4200/vendor.bundle.js:6885:18) [angular]
    at ScalarObservable._subscribe (http://localhost:4200/vendor.bundle.js:67576:24) [angular]
    at ScalarObservable.Observable.subscribe (http://localhost:4200/vendor.bundle.js:4855:27) [angular]
    at MergeMapOperator.call (http://localhost:4200/vendor.bundle.js:25017:23) [angular]
    at Observable.subscribe (http://localhost:4200/vendor.bundle.js:4852:22) [angular]
    at MergeMapOperator.call (http://localhost:4200/vendor.bundle.js:25017:23) [angular]

```

### Mention any other details that might be useful.
[Code is on Github](https://github.com/wpfeiffe/bpcs-ang-route-issue).  I also added [this issue to stackoverflow](http://stackoverflow.com/questions/41448358/angular-cli-router-lazy-loading).  

More info on this:  When I run the app, I can view the source in chrome devtools to see the webpack copy of the source.  In the angular-cli version, the comp3 folder is not present.  In the angular2-seed version, the comp3 folder IS present.  I noted that even though the comp3 folder shows in the webpack source in devtools, it is definitely lazy loaded when the comp3 link is clicked in the angular2-seed version.

**Comment by wpfeiffe** [comment]
Also ported this code to angular2-seed and it work with incident.

**Comment by conor-mac-aoidh** [comment]
@wpfeiffe I am seeing the exact same issue after upgrading to cli beta.24/angular 2.4.1. Previously my setup was working with beta.22 and angular 2.2.1

**Comment by wpfeiffe** [comment]
@conor-mac-aoidh Yeah I've seen this issue bounced out of the angular gitub repo issues as being a "support" issue.  I agree with that assessment and that is why I asked it on stackoverflow.  The question is, whose support issue is it, developer (me) or angular-cli repo?  Feels like an angular-cli/webpack thing to me, but I don't know enough about it to launch into investigation of it.

**Comment by feloy** [comment]
Are you using yarn?
I got a lot of different error msgs when upgraded to these versions, before I remove my yarn.lock file to upgrade dependencies.

**Comment by wpfeiffe** [comment]
Not using yarn.  Using the generated build from angular cli which I think
is just NPM.

**Comment by wpfeiffe** [comment]
[Solution is on Stackoverflow.](http://stackoverflow.com/questions/41448358/angular-cli-router-lazy-loading/41475419#41475419)  Please refer to that if you are having my same issue:
