### ISSUE TITLE
NG not found in WSL

### ISSUE THREAD

**Issue by sGerli** [angular/angular-cli#3944]
### OS?
Windows 10 using WSL

### Versions.
1.0.0-beta.24

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
1. Enable WSL in your windows installations.
2. Update Node and NPM
3. Run `npm install -g angular-cli`
4. Try running `ng help`

Then try:
5. Try a workaround for this `alias ng="/path/to/.npm-global/lib/node_modules/angular-cli/bin/ng"`
6. Run `ng help`
7. And we see our error `EINVAL: invalid argument, uv_interface_addresses`

### The log given by the failure.
```
EINVAL: invalid argument, uv_interface_addresses
Error: EINVAL: invalid argument, uv_interface_addresses
    at /mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/node_modules/portfinder/lib/portfinder.js:395:23
    at Object.<anonymous> (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/node_modules/portfinder/lib/portfinder.js:410:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/commands/serve.js:5:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/addon/index.js:22:16)
    at /mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/models/project.js:335:61
    at Array.forEach (native)
    at Project.addonCommands (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/models/project.js:334:15)
    at Project.eachAddonCommand (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/models/project.js:369:30)
    at module.exports (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/cli/cli.js:43:26)
    at tryCatch (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/mnt/c/Users/sGerli/.npm-global/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Mention any other details that might be useful.
In this project we found a workaround for a similar issue https://github.com/pebble-dev/rebble-store/issues/65 with WSL

**Comment by jemmaengz1202** [comment]
I have exactly the same issue,  with the same platform. 
There is no trouble with Windows cmd...

**Comment by sarunint** [comment]
This is a known issue in WSL. See Microsoft/BashOnWindows#1343 for more information.

It should be fixed when next version of Windows 10 is released.

**Comment by filipesilva** [comment]
Closed as answered by @sarunint
