### ISSUE TITLE
angular-cli.json project.version makes `ng build` fail when using Maven-like versioning with '-SNAPSHOT'

### ISSUE THREAD

**Issue by dfsabugal** [angular/angular-cli#3950]
When `project.version` property in `angular-cli.json` file contains a version number that includes a suffix like '-SNAPSHOT', used when following the convention used by Maven for a non-finished release, the `ng build` command fails with the following output:

```
/Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/upgrade/version.js:34
            ? this._version.match(/^(\d+)\.(\d+)(?:\.(\d+))?(?:-(alpha|beta|rc)\.(.*))?$/).slice(1)
                                                                                          ^

TypeError: Cannot read property 'slice' of null
    at Version._parse (/Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/upgrade/version.js:34:91)
    at Version.get [as major] (/Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/upgrade/version.js:43:40)
    at Function.Version.isPreWebpack (/Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/upgrade/version.js:142:24)
    at Function.Version.assertPostWebpackVersion (/Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/upgrade/version.js:126:18)
    at /Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/bin/ng:24:15
    at /Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:45:21
    at ondir (/Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:188:31)
    at /Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:154:39
    at onex (/Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:94:22)
    at /Users/dani/.nvm/versions/node/v6.9.2/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:25:18
```

### OS?
> Mac OSX El Capitan

### Versions.
> angular-cli: 1.0.0-beta.21
> node: 6.9.2
> os: darwin x64

### Repro steps.
> Set `project.version` property in `angular-cli.json` to something like '1.0.0-SNAPSHOT'
> Run `ng build`

**Comment by filipesilva** [comment]
Well that is meant to be the version of `angular-cli` itself, and it's expected to be parsed correctly according to the naming rules we have for the CLI. You shouldn't keep the internal version of your project there.
