### ISSUE TITLE
ng command failing with 'const' error

### ISSUE THREAD

**Issue by djneely** [angular/angular-cli#3971]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

I can't run this command due to the same error. But is the latest npm install -g angular-cli version from just now.

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

No. This is trying to create a project or run any 'ng' commands

### The log given by the failure.
> Normally this include a stack trace and some more information.

$ ng new new-app

/usr/local/lib/node_modules/angular-cli/bin/ng:7
const resolve = require('resolve');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
$ ng --version

/usr/local/lib/node_modules/angular-cli/bin/ng:7
const resolve = require('resolve');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

$ ng

/usr/local/lib/node_modules/angular-cli/bin/ng:7
const resolve = require('resolve');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
What Node version are you using?
4 or higher is required.

**Comment by djneely** [comment]
Thanks. Sure enough that was the issue. Thought I had it updated to the latest and greatest but brain fart on my part. Must have been one of my other workstations. Cheers!
