### ISSUE TITLE
Cannot find module '../upgrade/version' with b25

### ISSUE THREAD

**Issue by achimha** [angular/angular-cli#3988]
### OS?
OS X

### Versions.
angular-cli 1.0.0-beta.25 and angular 2.4.3.

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.

```
$ node_modules/.bin/ng --version
module.js:472
    throw err;
    ^

Error: Cannot find module '../upgrade/version'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/myuser/myproject/frontend/node_modules/angular-cli/bin/ng:9:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

I nuked `node_modules` to be sure, no difference. Going back to b24 solves the problem.

**Comment by Mr-Squirrel** [comment]
The beta.25 release is completely bricked. Try beta.25.5

**Comment by ciesielskico** [comment]
Upgrade to angular-cli 1.0.0-beta.25.5

**Comment by achimha** [comment]
Indeed, that fixes the problem, thanks. It is very unfortunate that npm's version pulling logic prefers the outdated package.
