### ISSUE TITLE
`ng build` fails, `unknown property 'performance'` in webpack loader configuration

### ISSUE THREAD

**Issue by CarreraPHP** [angular/angular-cli#3990]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

macOS Sierra

### Versions.

```

                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: local (v1.0.0-beta.25.5, branch: firebase-hosting)
node: 6.2.2
os: darwin x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

```

### Repro steps.

The project was create using beta24 and upgraded to beta25.5 using `ng init`. 

### The log given by the failure.

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'performance'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           performance: ...
         }
       })
     }
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'performance'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           performance: ...
         }
       })
     }
    at webpack (/Users/yogeshofit/Desktop/angular2/gitclone/angular-cli/node_modules/webpack/lib/webpack.js:16:9)
    at Class.exports.default.Task.extend.run (/Users/yogeshofit/Desktop/angular2/gitclone/angular-cli/packages/angular-cli/tasks/build-webpack.ts:21:31)
    at Class.buildRun (/Users/yogeshofit/Desktop/angular2/gitclone/angular-cli/packages/angular-cli/commands/build.run.ts:49:22)
    at Class.Command.extend.run (/Users/yogeshofit/Desktop/angular2/gitclone/angular-cli/packages/angular-cli/commands/build.ts:38:47)
    at Class.<anonymous> (/Users/yogeshofit/Desktop/angular2/gitclone/angular-cli/packages/angular-cli/ember-cli/lib/models/command.js:147:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Mention any other details that might be useful.

The project code is available @ [scaffolding-all](https://github.com/CarreraPHP/scaffolding-all/tree/master/web) and last working build can be found @ [scaffolding-all demo](https://scaffolding-all-fdb93.firebaseapp.com/) firebase hosting.

The build was working fine until my last `git pull` which i did today(few hours back) after beta25.5 was released for adding firebase hosting related npm scripts to my local fork. 

The last build was made around 10:00 AM ET, using `ng build --watch` and deployed to firebase hosting.

**Comment by cacogr** [comment]
It could also be related to https://github.com/angular/angular-cli/pull/3808/files

**Comment by filipesilva** [comment]
I know why this is. `webpack@2.2.0-rc.3` has this new property and we updated to it (like @cacogr) mentioned. 

I think what happened is that you did `ng init` but did not do `npm install`. It should have updated your deps since `v1.0.0-beta.25.5` has a pinned dep on `webpack@2.2.0-rc.3`.

You also seem to be running a linked `angular-cli` on a specific branch; in that case you need to update your deps on the linked repo.

**Comment by CarreraPHP** [comment]
removing the `node_modules` folder within the linked `angular-cli` and making a fresh `npm install` resolved the issue.
