### ISSUE TITLE
update to 26 fails on Linux Mint V18

### ISSUE THREAD

**Issue by DouglasWebster** [angular/angular-cli#4068]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Linux Mint 18 Cinnamon 64-bit

### Versions.
> angular-cli: 1.0.0-beta.25.5
node: 6.9.4
npm: 4.0.5
os: linux x64

### Repro steps.
> Updated to angular-cli beta 25.5 from beta 24 following the steps outlined in the update section of the documentation and tried ng new cli-test which failed with the message 
 **Cannot read property 'input' of null**

### The log given by the failure.
>TypeError: Cannot read property 'input' of null
    at ObjectSchemaTreeNode._set (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:335:132)
    at new ObjectSchemaTreeNode (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:319:14)
    at OneOfSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:232:24)
    at /home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:248:26
    at Array.map (native)
    at new OneOfSchemaTreeNode (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:247:48)
    at ArraySchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:232:24)
    at ArraySchemaTreeNode._set (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:422:39)
    at new ArraySchemaTreeNode (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:402:14)
    at ObjectSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:232:24)
    at ObjectSchemaTreeNode._set (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:335:47)
    at new ObjectSchemaTreeNode (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:319:14)
    at ArraySchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:232:24)
    at ArraySchemaTreeNode._set (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:422:39)
    at new ArraySchemaTreeNode (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:402:14)
    at RootSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:232:24)
    at RootSchemaTreeNode.ObjectSchemaTreeNode._set (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:335:47)
    at RootSchemaTreeNode.ObjectSchemaTreeNode [as constructor] (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:319:14)
    at new RootSchemaTreeNode (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-tree.js:466:16)
    at GeneratedSchemaClass.SchemaClassBase (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-class-factory.js:66:29)
    at new GeneratedSchemaClass (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-class-factory.js:165:20)
    at new CliConfig (/home/douglas/.npm-global/lib/node_modules/angular-cli/models/config/config.js:24:24)
    at Function.CliConfig.fromConfigPath (/home/douglas/.npm-global/lib/node_modules/angular-cli/models/config/config.js:97:16)
    at Function.CliConfig.fromProject (/home/douglas/.npm-global/lib/node_modules/angular-cli/models/config.js:45:44)
    at Class.config (/home/douglas/.npm-global/lib/node_modules/angular-cli/addon/index.js:11:77)
    at /home/douglas/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/models/project.js:178:27
    at Array.reduce (native)
    at Project.getAddonsConfig (/home/douglas/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/models/project.js:176:22)
    at Project.config (/home/douglas/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/models/project.js:158:17)
    at Class.Blueprint.install (/home/douglas/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/models/blueprint.js:498:32)
    at Class.run (/home/douglas/.npm-global/lib/node_modules/angular-cli/ember-cli/lib/tasks/install-blueprint.js:52:24)
    at Class.initRun (/home/douglas/.npm-global/lib/node_modules/angular-cli/commands/init.run.js:75:29)
    at Class.run (/home/douglas/.npm-global/lib/node_modules/angular-cli/commands/init.js:27:46)
    at tryCatch (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/douglas/.npm-global/lib/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

### Mention any other details that might be useful.
The directory cli-test is created but is empty.

I have also tried updating a project that was started when using angular-cli beta 21.  This project has been successfully updated through all the intervening betas up to beta 24 but now **ng init** fails with the same **Cannot read property 'input' of null** message however in this case the error log points to the local node_modules whereas the above log points to the global node_modules.  Also, no files in the project directory are altered.
> ---------------------------------------------------------------
> Thanks Douglas

**Comment by filipesilva** [comment]
This seems related to the `angular-cli.json` file. Can you try copying over a brand new `angular-cli.json` from a new project (use `--skip-npm` to not wait for npm installs).

If that fixes it, can you show me your previous `angular-cli.json` so we can see if we can figure out what caused it to break?

**Comment by DouglasWebster** [comment]
I cannot create a new project.  Trying to create a new project fails with the message and log output as detailed above.  All that the ng new command seems to do before the failure is create an empty directory with the name of the project.  As the directory is empty there is no angular-cli.json file to supply.

**Comment by DouglasWebster** [comment]
I have now tried the update to beta-26 and things are slightly different.  Where as angular-cli beta-25.5 
 would not create a new project, only an empty directory the angular-cli beta 26 will now create a new project.  However, trying to run anything other than ng lint gives an error.  All errors are **Cannot read property 'input' of null** and the log output given for ng build is

TypeError: Cannot read property 'input' of null
at ObjectSchemaTreeNode._set (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:347:132)
at new ObjectSchemaTreeNode (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:331:14)
at OneOfSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
at /mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:260:26
at Array.map (native)
at new OneOfSchemaTreeNode (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:259:48)
at ArraySchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
at ArraySchemaTreeNode._set (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:434:39)
at new ArraySchemaTreeNode (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:414:14)
at ObjectSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
at ObjectSchemaTreeNode._set (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:347:47)
at new ObjectSchemaTreeNode (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:331:14)
at ArraySchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
at ArraySchemaTreeNode._set (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:434:39)
at new ArraySchemaTreeNode (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:414:14)
at RootSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
at RootSchemaTreeNode.ObjectSchemaTreeNode._set (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:347:47)
at RootSchemaTreeNode.ObjectSchemaTreeNode [as constructor] (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:331:14)
at new RootSchemaTreeNode (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-tree.js:478:16)
at GeneratedSchemaClass.SchemaClassBase (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-class-factory.js:66:29)
at new GeneratedSchemaClass (/mnt/Data/DevPackages/cli-test/node_modules/@ngtools/json-schema/src/schema-class-factory.js:165:20)
at new CliConfig (/mnt/Data/DevPackages/cli-test/node_modules/angular-cli/models/config/config.js:24:24)
at Function.CliConfig.fromConfigPath (/mnt/Data/DevPackages/cli-test/node_modules/angular-cli/models/config/config.js:99:16)
at Function.CliConfig.fromProject (/mnt/Data/DevPackages/cli-test/node_modules/angular-cli/models/config.js:63:44)
at Class.run (/mnt/Data/DevPackages/cli-test/node_modules/angular-cli/tasks/build-webpack.js:14:73)
at Class.buildRun (/mnt/Data/DevPackages/cli-test/node_modules/angular-cli/commands/build.run.js:39:22)
at Class.run (/mnt/Data/DevPackages/cli-test/node_modules/angular-cli/commands/build.js:38:47)
at Class.<anonymous> (/mnt/Data/DevPackages/cli-test/node_modules/angular-cli/ember-cli/lib/models/command.js:147:17)
at process._tickCallback (internal/process/next_tick.js:103:7)

the error messages all seem the same until line 26 where they vary depending on the command issued.

**Comment by dustintheweb** [comment]
Previously working for beta 24 - confirming same issue for beta 25 & 26 on Heroku Ubuntu.

here is my log:

```
2017-01-21T12:31:06.481016+00:00 heroku[slug-compiler]: Slug compilation started
2017-01-21T12:31:06.481021+00:00 heroku[slug-compiler]: Slug compilation finished
2017-01-21T12:31:07.060474+00:00 heroku[web.1]: State changed from down to starting
2017-01-21T12:31:12.409645+00:00 heroku[web.1]: Starting process with command `npm start`
2017-01-21T12:31:14.728921+00:00 app[web.1]: 
2017-01-21T12:31:14.728941+00:00 app[web.1]: > npm run dist
2017-01-21T12:31:14.728940+00:00 app[web.1]: > redwood@0.0.1 start /app
2017-01-21T12:31:14.728942+00:00 app[web.1]: 
2017-01-21T12:31:15.254160+00:00 app[web.1]: 
2017-01-21T12:31:15.254177+00:00 app[web.1]: > redwood@0.0.1 dist /app
2017-01-21T12:31:15.254179+00:00 app[web.1]: 
2017-01-21T12:31:15.254179+00:00 app[web.1]: > export NODE_ENV=production && npm run server:set && npm run server:production
2017-01-21T12:31:15.760678+00:00 app[web.1]: 
2017-01-21T12:31:15.760698+00:00 app[web.1]: > redwood@0.0.1 server:set /app
2017-01-21T12:31:15.760700+00:00 app[web.1]: > tsc -p ./server && cp -a ./server/views/. ./dist/server/views && rm -rf ./.tmp
2017-01-21T12:31:15.760701+00:00 app[web.1]: 
2017-01-21T12:31:19.985316+00:00 app[web.1]: 
2017-01-21T12:31:19.985330+00:00 app[web.1]: > redwood@0.0.1 server:production /app
2017-01-21T12:31:19.985331+00:00 app[web.1]: > ng build --prod & node ./dist/server/server.js
2017-01-21T12:31:19.985332+00:00 app[web.1]: 
2017-01-21T12:31:21.002165+00:00 app[web.1]: from app.ts
2017-01-21T12:31:21.041908+00:00 app[web.1]: from routes.ts
2017-01-21T12:31:21.073038+00:00 app[web.1]: from server.ts
2017-01-21T12:31:21.083638+00:00 app[web.1]: Express server listening on 51592, in production mode
2017-01-21T12:31:21.393063+00:00 heroku[web.1]: State changed from starting to up
2017-01-21T12:31:21.432179+00:00 app[web.1]: MongoDB connected
2017-01-21T12:31:22.480661+00:00 app[web.1]: Cannot read property 'input' of null
**2017-01-21T12:31:22.481591+00:00 app[web.1]: TypeError: Cannot read property 'input' of null**
2017-01-21T12:31:22.481595+00:00 app[web.1]:     at Array.map (native)
2017-01-21T12:31:22.481593+00:00 app[web.1]:     at ObjectSchemaTreeNode._set (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:347:132)
2017-01-21T12:31:22.481598+00:00 app[web.1]:     at ObjectSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
2017-01-21T12:31:22.481593+00:00 app[web.1]:     at new ObjectSchemaTreeNode (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:331:14)
2017-01-21T12:31:22.481597+00:00 app[web.1]:     at ArraySchemaTreeNode._set (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:434:39)
2017-01-21T12:31:22.481594+00:00 app[web.1]:     at OneOfSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
2017-01-21T12:31:22.481596+00:00 app[web.1]:     at new OneOfSchemaTreeNode (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:259:48)
2017-01-21T12:31:22.481595+00:00 app[web.1]:     at /app/node_modules/@ngtools/json-schema/src/schema-tree.js:260:26
2017-01-21T12:31:22.481596+00:00 app[web.1]:     at ArraySchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
2017-01-21T12:31:22.481597+00:00 app[web.1]:     at new ArraySchemaTreeNode (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:414:14)
2017-01-21T12:31:22.481598+00:00 app[web.1]:     at ObjectSchemaTreeNode._set (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:347:47)
2017-01-21T12:31:22.481599+00:00 app[web.1]:     at new ObjectSchemaTreeNode (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:331:14)
2017-01-21T12:31:22.481599+00:00 app[web.1]:     at ArraySchemaTreeNode._set (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:434:39)
2017-01-21T12:31:22.481599+00:00 app[web.1]:     at ArraySchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
2017-01-21T12:31:22.481600+00:00 app[web.1]:     at new ArraySchemaTreeNode (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:414:14)
2017-01-21T12:31:22.481600+00:00 app[web.1]:     at RootSchemaTreeNode.NonLeafSchemaTreeNode._createChildProperty (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:244:24)
2017-01-21T12:31:22.481601+00:00 app[web.1]:     at RootSchemaTreeNode.ObjectSchemaTreeNode._set (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:347:47)
2017-01-21T12:31:22.481601+00:00 app[web.1]:     at RootSchemaTreeNode.ObjectSchemaTreeNode [as constructor] (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:331:14)
2017-01-21T12:31:22.481602+00:00 app[web.1]:     at new RootSchemaTreeNode (/app/node_modules/@ngtools/json-schema/src/schema-tree.js:478:16)
2017-01-21T12:31:22.481603+00:00 app[web.1]:     at new CliConfig (/app/node_modules/angular-cli/models/config/config.js:24:24)
2017-01-21T12:31:22.481606+00:00 app[web.1]:     at Class.run (/app/node_modules/angular-cli/commands/build.js:38:47)
2017-01-21T12:31:22.481602+00:00 app[web.1]:     at GeneratedSchemaClass.SchemaClassBase (/app/node_modules/@ngtools/json-schema/src/schema-class-factory.js:66:29)
2017-01-21T12:31:22.481602+00:00 app[web.1]:     at new GeneratedSchemaClass (/app/node_modules/@ngtools/json-schema/src/schema-class-factory.js:165:20)
2017-01-21T12:31:22.481603+00:00 app[web.1]:     at Function.CliConfig.fromConfigPath (/app/node_modules/angular-cli/models/config/config.js:99:16)
2017-01-21T12:31:22.481604+00:00 app[web.1]:     at Function.CliConfig.fromProject (/app/node_modules/angular-cli/models/config.js:63:44)
2017-01-21T12:31:22.481604+00:00 app[web.1]:     at Class.run (/app/node_modules/angular-cli/tasks/build-webpack.js:14:73)
2017-01-21T12:31:22.481604+00:00 app[web.1]:     at Class.buildRun (/app/node_modules/angular-cli/commands/build.run.js:39:22)
2017-01-21T12:31:22.481607+00:00 app[web.1]:     at Class.<anonymous> (/app/node_modules/angular-cli/ember-cli/lib/models/command.js:147:17)
2017-01-21T12:31:22.481607+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by DouglasWebster** [comment]
I have done a complete new install of Linux Mint 18.1 cinnamon, node 6.9.4 and npm 4.1.1 and so far everything looks O.K.  Will continue to reinstall software and let you know if there are any problems.

**Comment by filipesilva** [comment]
@DouglasWebster I'm sorry you had such a bad experience, I think it was mostly a dependency thing where there were broken dependencies in global npm. I'm not sure how it got to that state though.. :/

Let me know if you have more problems and I will reopen.

**Comment by shoaibuddin** [comment]
Production build fails with message "Cannot read property 'input' of null"

**Comment by dustintheweb** [comment]
looks like this has been verified as a bug - https://github.com/angular/angular-cli/issues/4207
