### ISSUE TITLE
ng init fails because of permissions and empties package.json

### ISSUE THREAD

**Issue by killrazor** [angular/angular-cli#4118]
### OS?
> Red Hat Enterprise Linux Server release 6.6 (Santiago)

### Versions.
> angular-cli: 1.0.0-beta.25.5
> node: 6.6.0
> os: linux x64

### Repro steps.
> updated CLI to 25.5 from 22.1 per instruction on the main page and ran `ng init` as the last step. As I finished reviewing changes I get this permission error:
>
>`EACCES: permission denied, open '/projectLocation/.gitignore'`
`Error: EACCES: permission denied, open '/projectLocation/.gitignore'`
>
>Find that indeed, the permissions for the file(s) are restricted. Update the permissions.
>
>Run `ng init` again.
>
> /projectLocation/node_modules/angular-cli/ember-cli/lib/models/project.js:598
      throw reason;
      ^
>SyntaxError: /projectLocation/package.json: Unexpected end of JSON input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:573:27)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Function.Project.getProjectRoot (/projectLocation/node_modules/angular-cli/ember-cli/lib/models/project.js:584:15)
    at module.exports (/projectLocation/node_modules/angular-cli/ember-cli/lib/cli/index.js:29:22)
    at module.exports (/projectLocation/node_modules/angular-cli/lib/cli/index.js:38:10)
    at /usr/local/lib/node_modules/angular-cli/bin/ng:103:5
    at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:45:21
    at ondir (/usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:188:31)
    at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:154:39
    at onex (/usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:94:22)
    at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:25:18
    at FSReqWrap.oncomplete (fs.js:123:15)

> It appears that the reason for the failure is that package.json is empty.

### The log given by the failure.
> See output above. There is no failure log.

### Mention any other details that might be useful.
> Work around is to `npm init`  to recreate a placeholder package.json or copy it from another location.
> I would hope that package.json would be built last so that failure won't overwrite the current values in the file with nothing.

**Comment by filipesilva** [comment]
We don't support `ng init` anymore.
