### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:

### ISSUE THREAD

**Issue by hedecan** [angular/angular-cli#414]
Hi,

I am experiencing the following error while running "ng serve" after adding a new component and adding a code in .ts file.

Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/mehmetaltuntas/testangular/tmp/broccoli_type_script_compiler-input_base_path-6Jy8Konh.tmp/0/src/client/app/testangular.ts (4, 9): Module '"/Users/mehmetaltuntas/testangular/tmp/broccoli_type_script_compiler-input_base_path-6Jy8Konh.tmp/0/src/client/app/hohome/hohome"' has no exported mng 'HomePage'.

Thanks

**Comment by jkuri** [comment]
Please run 'ng init' in your project.

**Comment by severin2** [comment]
This helped with a related problem also. I'm using
```
angular-cli: 0.0.30
node: 4.4.2
os: win32 ia32
```
And had issues in the ```ng build``` with the BroccoliTypeScriptCompiler finding the typings for angular/2core. using ```ng init``` and letting it overwrite the various build json files solved that problem also.

**Comment by hashmee** [comment]
Build failed.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/dispatchtrack/angular123/tmp/broccoli_type_script_compiler-input_base_path-RjNMMlhr.tmp/0/src/typings.d.ts (5, 1): File '/Users/dispatchtrack/angular123/tmp/broccoli_type_script_compiler-input_base_path-RjNMMlhr.tmp/0/typings/browser.d.ts' not found.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/angular2-app.js:321:18)
    at Angular2App._buildTree (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/angular2-app.js:116:23)
    at new Angular2App (/Users/dispatchtrack/angular123/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/dispatchtrack/angular123/angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at /Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/lib/commands/build.js:32:24
    at lib$rsvp$$internal$$tryCatch (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/dispatchtrack/angular123/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

**Comment by ibraback** [comment]
@jkuri : I tried everything but I still have the same problem, pls help.

**Comment by jkuri** [comment]
@ibraback can you paste your output please so I can investigate on your problem? thanks.

**Comment by kocicjelena** [comment]
npm install goes first.

**Comment by Saronet** [comment]
Run as admin. I found it helpful.
