### ISSUE TITLE
ng build fails with "No errors" 

### ISSUE THREAD

**Issue by Lopierdis** [angular/angular-cli#4266]
### OS?
> Windows 10

### Versions.
> angular-cli: 1.0.0-beta.25.5
node: 6.9.2

### Repro steps.
> App was created using angular-cli, I changed quite a bit, but the build failure actually occured when I tried pushing to heroku, the build still works on my computer, I tried copying the project to a different folder and running npm install and then the build failed there too.
I also tried creating an empty app using angular-cli it also fails to build that app as well!!

### The log given by the failure.
> No errors
Error: No errors
    at validate (C:\Projects\Typescript\meeet - Copy\node_modules\extract-text-webpack-plugin\schema\validator.js:10:9)
    at Function.ExtractTextPlugin.extract (C:\Projects\Typescript\meeet - Copy\node_modules\extract-text-webpack-plugin\index.js:188:3)
    at C:\Projects\Typescript\meeet - Copy\node_modules\angular-cli\models\webpack-build-utils.js:72:77
    at Array.map (native)
    at Object.makeCssLoaders (C:\Projects\Typescript\meeet - Copy\node_modules\angular-cli\models\webpack-build-utils.js:69:53)
    at Object.getWebpackCommonConfig (C:\Projects\Typescript\meeet - Copy\node_modules\angular-cli\models\webpack-build-common.js:77:65)
    at new NgCliWebpackConfig (C:\Projects\Typescript\meeet - Copy\node_modules\angular-cli\models\webpack-config.js:24:49)
    at Class.run (C:\Projects\Typescript\meeet - Copy\node_modules\angular-cli\tasks\build-webpack.js:20:22)
    at Class.buildRun (C:\Projects\Typescript\meeet - Copy\node_modules\angular-cli\commands\build.run.js:49:22)
    at Class.run (C:\Projects\Typescript\meeet - Copy\node_modules\angular-cli\commands\build.js:38:47)
    at Class.<anonymous> (C:\Projects\Typescript\meeet - Copy\node_modules\angular-cli\ember-cli\lib\models\command.js:147:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Mention any other details that might be useful.

> package.json:
{
  "name": "somename",
  "version": "0.0.0",
  "license": "MIT",
  "engines": {
    "node": "6.9.2",
    "npm": "3.10.9"
  },
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "node bin/server/server.js",
    "lint": "tslint \"src/server/**/*.ts\" --project src/server/tsconfig.json --type-check && tslint \"src/client/**/*.ts\" --project src/client/tsconfig.json --type-check",
    "postinstall": "node node_modules/gulp/bin/gulp.js build"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.3",
    "@angular/compiler": "^2.3.1",
    "@angular/compiler-cli": "^2.3.1",
    "@angular/core": "^2.4.3",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@types/core-js": "^0.9.35",
    "@types/express": "^4.0.34",
    "@types/jasmine": "2.5.38",
    "@types/materialize-css": "^0.97.33",
    "angular-cli": "1.0.0-beta.25.5",
    "angular2-materialize": "^6.4.0",
    "codelyzer": "~2.0.0-beta.1",
    "core-js": "^2.4.1",
    "express": "^4.14.0",
    "gulp": "^3.9.1",
    "gulp-exec": "^2.1.3",
    "gulp-shell": "^0.5.2",
    "gulp-sourcemaps": "^2.4.0",
    "gulp-typescript": "^3.1.4",
    "jquery": "^2.2.4",
    "materialize-css": "^0.97.8",
    "pg": "^6.1.2",
    "protractor": "~4.0.13",
    "reflect-metadata": "^0.1.9",
    "routing-controllers": "^0.6.9",
    "rxjs": "^5.0.3",
    "ts-helpers": "^1.1.1",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typeorm": "0.0.7",
    "typescript": "^2.1.5",
    "zone.js": "^0.6.26"
  }
}

**Comment by intellix** [comment]
Dupe of: https://github.com/angular/angular-cli/issues/4264

**Comment by Lopierdis** [comment]
Failed finding it with google, thanks!
