### ISSUE TITLE
ng --version issue

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/angular-cli#4332]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

linux opensuse 

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.28.3
node: 6.9.3
os: linux x64
...
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Just did a fresh install of my global cli (npm install -g @angular/cli).
Then execute ```ng --version``` outside a cli project folder

### The log given by the failure.
> Normally this include a stack trace and some more information.
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'command'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/ember-cli/lib/models/project.js:17:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

### Mention any other details that might be useful.
```ng --version``` works fine in a project folder where all the packages are installed (npm install)

**Comment by FallenRiteMonk** [comment]
works fine once updated to beta 29
