### ISSUE TITLE
@ngtools/webpack: Maximum call stack size exceeded with barrels

### ISSUE THREAD

**Issue by chrisfitz** [angular/angular-cli#4371]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
macOS Sierra

### Versions.
angular-cli: 1.0.0-beta.29
node: 6.9.0
os: darwin x64
@ngtools/webpack: 1.2.6

### Repro steps.

- Create a new project with `ng new project`
- Create a folder within the `src` directory with the following three files:

`example/foo.ts`:
```javascript
export const foo = 'bar';
```

`example/bar.ts`:
```javascript
import { foo } from './';

export const bar = foo;
```

`example/index.ts`:
```javascript
export * from './foo';
export * from './bar';
```

- Inside `app.component.ts`:
```javascript
import { Component } from '@angular/core';

import { bar } from '../example';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = bar;
}
```

- Start the server with `ng serve`
- Re-save `example/foo.ts` to force a re-compile

### The log given by the failure.
```shell
$ ng serve

** NG Live Development Server is running on http://localhost:4200. **
Hash: 54b2bb8b3e99430e6c40
Time: 7302ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 4.4 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.64 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
webpack: Compiling...
Hash: 1ab3af6524167dd699a4
Time: 544ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 222 kB {4} [initial]
chunk    {1} main.bundle.js, main.bundle.map (main) 539 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.64 MB [initial]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry]

ERROR in ./src/example/foo.ts
Module build failed: RangeError: Maximum call stack size exceeded
    at Array.filter (native)
    at _diagnoseDeps (/path/to/project/node_modules/@ngtools/webpack/src/loader.js:261:10)
    at /path/to/project/node_modules/@ngtools/webpack/src/loader.js:264:9
    at Array.forEach (native)
    at _diagnoseDeps (/path/to/project/node_modules/@ngtools/webpack/src/loader.js:262:10)
    at /path/to/project/node_modules/@ngtools/webpack/src/loader.js:264:9
    at Array.forEach (native)
    at _diagnoseDeps 
...
```

### Mention any other details that might be useful.

It only seems to trigger this when modifying a file that was re-exported within the barrel, so I'm guessing it's getting stuck in an infinite loop when fetching its dependencies as it will eventually find itself as a dependency.

**Comment by splintercode** [comment]
I think this is related to this issue as well. Similar error output https://github.com/angular/angular-cli/issues/4376
