### ISSUE TITLE
fs.js:640   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

### ISSUE THREAD

**Issue by huiqiangyang** [angular/angular-cli#4386]
> linux ubuntu OS
> node v6.9.5
> npm 3.10.10

> exception: 

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/yhq/pro1703/web/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at write (/opt/node/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/commit.js:14:6)
    at DestroyableTransform._transform (/opt/node/lib/node_modules/generator-jhipster/node_modules/mem-fs-editor/lib/actions/commit.js:43:7)
    at DestroyableTransform.Transform._read (/opt/node/lib/node_modules/generator-jhipster/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/opt/node/lib/node_modules/generator-jhipster/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/opt/node/lib/node_modules/generator-jhipster/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/opt/node/lib/node_modules/generator-jhipster/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/opt/node/lib/node_modules/generator-jhipster/node_modules/readable-stream/lib/_stream_writable.js:274:11)

```

**Comment by Akhilesh1189** [comment]
i am getting same issue

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

**Comment by huiqiangyang** [comment]
@Akhilesh1189  Your dir may be have "_" or others symbol, you only can use characters and numbers.

**Comment by ilmiawan** [comment]
I have also had this problem before, an this is caused by my proxy setting on windows.

**Comment by SmolinPavel** [comment]
Got the same problem

**Comment by shi-cong** [comment]
Got the same problem

**Comment by siempay** [comment]
Got the same problem

**Comment by Selman555** [comment]
Why isn't there a "mee too" filter github???
By the way:
Got the same problem

**Comment by AliBahramiEhsan** [comment]
Got the same problem

**Comment by MichaelSchmidt82** [comment]
Same.
Would you say these packages are getting harder to maintain due to changes in atom?

**Comment by ericel** [comment]
Any solution to this yet? trying to add universal to my app.
> node dist/server

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:dist\browser\index.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (D:dist\server.js:261209:21)
    at __webpack_require__ (D:dist\server.js:20:30)
    at Object.defineProperty.value (D:\websites\otenn\dist\server.js:63:18)
    at Object.<anonymous> (D:\dist\server.js:66:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

**Comment by rohitsgoudagaon** [comment]
Hi there.
I have written code in es6, and i want to convert it to es6.
I want babel on my machine. So i installed it via npm install --save babel-cli. And it gets installed on my projects node_modules directory. And then i did, cd ./node_modules/.bin. And typed command `babel-node /home/user/promise\ babel\ to\ conversion.js` . I thought it will convert the es6 to es5. But it throws error as,
`return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/rohit/.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.writeFileSync (fs.js:1356:33)
    at save (/home/rohit/.nvm/versions/node/v6.12.3/lib/node_modules/babel-cli/node_modules/babel-register/lib/cache.js:48:16)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Function.Module.runMain (module.js:606:11)
    at Object.<anonymous> (/home/rohit/.nvm/versions/node/v6.12.3/lib/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
`.

Please provide solution, so any next gen es code will transpiled to es5 by using locally installed babel  binary in ./node_modules/.bin

**Comment by rohitsgoudagaon** [comment]
But after `sudo chmod -R ugo+rw /home/rohit/.babel.json` this commnd, the code gets run and gives output that means it executed the program as usual as by doing it node index.js. Here i am expecting that, babel-node will convert my es6 code to es5. What i am missing.
And tried by `babel /home/rohit/Desktop/pract/promise\ babel\ to\ conversion.js`, this outputs the same code what we written, instead  of es5  version.

**Comment by gamunax** [comment]
I have the same problem

```
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\dist\browser\index.html'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (C:\xampp7.1\htdocs\otafront\dist\server.js:186515:19)
    at Object.module.exports (C:\xampp7.1\htdocs\otafront\dist\server.js:186547:30)
    at __webpack_require__ (C:\xampp7.1\htdocs\otafront\dist\server.js:20:30)
    at C:\xampp7.1\htdocs\otafront\dist\server.js:63:18
    at Object.<anonymous> (C:\xampp7.1\htdocs\otafront\dist\server.js:66:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

**Comment by EmilMoe** [comment]
Make sure you don't do versioning

```
// run versioning on production only
if (mix.inProduction()) {
    mix.version();
}
```

**Comment by SatishAwal** [comment]
Adding my app to universal led to this problem.
 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/user/zip2/dist/browser/index.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/home/user/zip2/dist/server.js:98:21)
    at __webpack_require__ (/home/user/zip2/dist/server.js:20:30)
    at /home/satish/Downloads/zip2/dist/server.js:63:18
    at Object.<anonymous> (/home/user/zip2/dist/server.js:66:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

**Comment by SatishAwal** [comment]
@mapsgeek  this is angular.cli.json file.Should I add another outDir or add to current outDir. 

[{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "crnew-universal"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist/browser",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "assets/scss/site-theme.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    },
    {
      "platform": "server",
      "root": "src",
      "outDir": "dist/server",
      "assets": [],
      "index": "index.html",
      "main": "main.server.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.server.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "scripts": [
       
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "component": {}
  }
}
]

**Comment by mapsgeek** [comment]
@SatishAwal there should be no [ ] in the start but this may depend on your setup of Universal
follow the setup in this article it works for me very well, i just got this error when i forgot to put my "outDir" as  "dist/browser".
[https://medium.com/@evertonrobertoauler/angular-5-universal-with-transfer-state-using-angular-cli-19fe1e1d352c](universal setup)

**Comment by 90arther** [comment]
I have the same problem. and I fixed it by updating my node.js from 8.11.x to 8.12.0

**Comment by tomvo** [comment]
I had the same problem when using laravel mix with the `laravel-mix-merge-manifest` plugin. The manifest got corrupted for some reason. Manually deleting it fixed the issue.

**Comment by jimmyww7710** [comment]
create a txt file, write:
 dist/electron.exe 
then name it : path.txt, 
put it at here: node_modules/electron-prebuilt.

solved in my case.
