### ISSUE TITLE
How to install the latest angular-cli?

### ISSUE THREAD

**Issue by zh-wowtv** [angular/angular-cli#4391]
I found the latest version in github is 1.0.0-beta.30. But it always show my version is 1.0.0-beta.28.3 when I try:

> sudo npm i -g angular-cli

What could be wrong? Thanks

**Comment by diicar** [comment]
npm install -g @angular/cli

**Comment by bogacg** [comment]
Docs need to be updated

**Comment by paumayr** [comment]
There is a pull request open for the docs: #4349

**Comment by grizzm0** [comment]
You can run these two snippets to upgrade from angular-cli to the new package @angular/cli.
```
npm uninstall -g angular-cli
npm cache clean
npm install -g @angular/cli@latest
```

```
rm -rf node_modules dist
npm uninstall --save-dev angular-cli@latest
npm install --save-dev @angular/cli@latest
npm install
ng update
```

**Comment by RicardoVaranda** [comment]
@grizzm0 Are you not a fan of ng init? 😛

**Comment by grizzm0** [comment]
@RicardoVaranda The README says ng update nowdays. ;) Pretty sure it used to say ng init tho.

**Comment by zh-wowtv** [comment]
Thanks. Previously I run: `npm i -g angular-cli`. I think this is the reason.

**Comment by RicardoVaranda** [comment]
I'll have to check it out properly, I like the way init makes the second part of your previous post much easier in my opinion I guess it's all a matter of preference :)

**Comment by itsnotvalid** [comment]
@RicardoVaranda you still need to install the new version of the global cli via the npm commands.

**Comment by RicardoVaranda** [comment]
Of course, if you read my last comment I simply stated it makes the second part easier, the first part is essential regardless of your choice on upgrade.

**Comment by elvirdolic** [comment]
After installing latest version I still have a angular-cli folder with two folders inside

- ast-tools
- base-href-webpack

is this as defined?

**Comment by bogacg** [comment]
@elvirdolic yes, I believe their definition still holds as reference 'angular-cli' therefore `angular-cli` folder gets created under `node_modules`. Probably they'll get correct references in next updates. For now it's normal.

**Comment by filipesilva** [comment]
Closing as answered.

**Comment by thavaselvama** [comment]
First You uninstall the old version of the CLI globally, cleared cache, and then installed the new version CLI globally, following these instructions:

npm uninstall -g angular-cli @angular/cli

npm cache clean

npm install -g @angular/cli@latest

**Comment by Mitali-Mahanta** [comment]
Can anybody help me.I am unable to install CLI.

**Comment by RicardoVaranda** [comment]
What problem are you facing @Mitali-Mahanta

**Comment by Mitali-Mahanta** [comment]
Now @angular/cli is working,i reinstall the nodejs latest version(v6.11.1).

**Comment by ZWTOKIO** [comment]
This can help you to update the package versions of package.json to the last version
https://www.npmjs.com/package/npm-check-updates

**Comment by karunakar1008** [comment]
https://github.com/angular/angular-cli#updating-angular-cli

**Comment by vishal2develop** [comment]
After updating , my terminal shows angular CLI: 1.5.0 .

Is this the latest ?

**Comment by kenji-1996** [comment]
@vishal2develop Yes, if youre ever unsure you can check at the release tab:
https://github.com/angular/angular-cli/releases

**Comment by rwmb** [comment]
@grizzm0 `npm uninstall -g angular-cli` missing the `@` at `angular-cli`.
Thanks for the help!

**Comment by hassaniftikhar** [comment]
Hey Guys,
Simple things here
I ran

npm install -g @angular/cli
ng new my-app
cd my-app
ng serve 

**ERROR in Error: No NgModule metadata found for 'AppModule'.**
    at NgModuleResolver.resolve (/Users/hassaniftikhar/RubymineProjects/angular-projects/my-app/node_modules/@angular/compiler/bundles/compiler.umd.js:20277:23)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/hassaniftikhar/RubymineProjects/angular-projects/my-app/node_modules/@angular/compiler/bundles/compiler.umd.js:15230:60)
    at visitLazyRoute (/Users/hassaniftikhar/RubymineProjects/angular-projects/my-app/node_modules/@angular/compiler/bundles/compiler.umd.js:31169:104)
    at AotCompiler.listLazyRoutes (/Users/hassaniftikhar/RubymineProjects/angular-projects/my-app/node_modules/@angular/compiler/bundles/compiler.umd.js:31137:20)
    at AngularCompilerProgram.listLazyRoutes (/Users/hassaniftikhar/RubymineProjects/angular-projects/my-app/node_modules/@angular/compiler-cli/src/transformers/program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/hassaniftikhar/RubymineProjects/angular-projects/my-app/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/Users/hassaniftikhar/RubymineProjects/angular-projects/my-app/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:248:66)
    at Promise.resolve.then.then (/Users/hassaniftikhar/RubymineProjects/angular-projects/my-app/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:565:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

clue less here

**Comment by rwmb** [comment]
@hassaniftikhar check the comment below
https://github.com/angular/angular-cli/issues/8798#issuecomment-355260025

**Comment by captainhook99999** [comment]
I've solved it after running following instructions!
npm install npm -g
npm install --save-dev @angular/cli@latest
npm install
npm start
