### ISSUE TITLE
ng serve - crash upon change

### ISSUE THREAD

**Issue by ravtakhar** [angular/angular-cli#448]
Upon changing one of my .ts files in my project my "ng serve" goes wack and I am forced shut it down and rerun the command.

`Cannot read property 'isDirectory' of undefined
TypeError: Cannot read property 'isDirectory' of undefined
    at isNotDirectory (H:\Code\Project\Client\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\server\livereload-server.js:24:19)
    at Array.filter (native)
    at Class.module.exports.Task.extend.didChange (H:\Code\Project\Client\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\server\livereload-server.js:140:10)
    at Class.<anonymous> (H:\Code\Project\Client\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\server\livereload-server.js:75:24)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.Watcher.triggerChange (H:\Code\Project\Client\node_modules\broccoli-sane-watcher\index.js:122:8)
    at lib$rsvp$$internal$$tryCatch (H:\Code\Project\Client\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (H:\Code\Project\Client\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (H:\Code\Project\Client\node_modules\rsvp\dist\rsvp.js:1019:11)`

This is the other error I keep getting:

```
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Trying to add a new entry to an already existing one: H:\Code\Project\Client\tmp\broccoli_type_script_compiler-input_base_path-kBpfF3ND.tmp\0\src\app\client.spec.ts
    at BroccoliTypeScriptCompiler._addNewFileEntry (H:\Code\Project\Client\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:212:13)
    at H:\Code\Project\Client\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:159:38
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doFullBuild (H:\Code\Project\Client\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:159:16)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (H:\Code\Project\Client\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:116:12)
    at BroccoliTypeScriptCompiler.build (H:\Code\Project\Client\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:45:12)
    at H:\Code\Project\Client\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (H:\Code\Project\Client\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (H:\Code\Project\Client\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (H:\Code\Project\Client\node_modules\rsvp\dist\rsvp.js:1019:11)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (H:\Code\Project\Client\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (H:\Code\Project\Client\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (H:\Code\Project\Client\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:25:35)
    at Angular2App.toTree (H:\Code\Project\Client\node_modules\angular-cli\lib\broccoli\angular2-app.js:67:16)
    at module.exports (H:\Code\Project\Client\angular-cli-build.js:9:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (H:\Code\Project\Client\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (H:\Code\Project\Client\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (H:\Code\Project\Client\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (H:\Code\Project\Client\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at H:\Code\Project\Client\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:70:22
```

**Comment by ravtakhar** [comment]
was not importing the following when creating my models:
`import {Component} from 'angular2/core';`
