### ISSUE TITLE
Getting error when using --aot

### ISSUE THREAD

**Issue by vforv** [angular/angular-cli#4483]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux Ubuntu 16.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.18
node: 6.9.4
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Created by angular-cli

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
sudo ng build --aot
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
  0% compilingError encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 100:25 in the original .ts file), resolving symbol AppModule in /home/amerbank-dash/src/app/app.module.ts
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 100:25 in the original .ts file), resolving symbol AppModule in /home/amerbank-dash/src/app/app.module.ts
    at simplifyInContext (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:534:15)
    at StaticReflector.simplify (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:538:18)
    at StaticReflector.annotations (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:94:28)
    at _loop_1 (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:77:48)
    at CodeGeneratorModuleCollector.readFileMetadata (/home/amerbank-dash/node_modules/@angular/compiler-cli/src/codegen.js:79:13)
    at /Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:51:56
    at Array.map (native)
    at CodeGeneratorModuleCollector.getModuleSymbols (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:51:33)
    at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:124:5)
    at AotPlugin._make (/home/amerbank-dash/node_modules/@ngtools/webpack/src/plugin.js:186:43)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/@ngtools/webpack/src/plugin.js:151:75)
    at Compiler.applyPluginsParallel (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:456:7)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:219:10)
    at Compiler.readRecords (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:367:10)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:216:9)
    at next (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:213:8)
    at next (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.run (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:210:7)
    at /home/amerbank-dash/node_modules/angular-cli/tasks/build-webpack.js:26:29
    at Class.run (/home/amerbank-dash/node_modules/angular-cli/tasks/build-webpack.js:25:16)
    at Class.run (/home/amerbank-dash/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/home/amerbank-dash/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/home/amerbank-dash/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/home/amerbank-dash/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/home/amerbank-dash/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/home/amerbank-dash/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Mention any other details that might be useful.

Something here makes problem I think:

```
{
            provide: Http,
            useFactory: (xhrBackend: XHRBackend, requestOptions: RequestOptions, router: Router, getToken: AuthTokenService) => new HttpInterceptorService(xhrBackend, requestOptions, router, getToken),
            deps: [XHRBackend, RequestOptions, Router, AuthTokenService]
}
```

That part is in `providers` in `app.module.ts` and it uses to create http interceptor because there is no way in angular cli to add it with terminal.

Also I here is some nice features which can be really useful if it have in angular-cli:

-Add http intreceptors with command line
-Create routing with command line
-Integrate Angular Universal to have some command like this for example `ng new AngularUniversalWithCli --au`
-Integrate NativeScript with Angular-cli there is already pkg: https://github.com/wwwalkerrun/nativescript-ngx-magic but it would be useful if there is command like this in angular-cli: `ng new AngularWithNativeScript --ns`

Anyway thanks for awsome tool. Keep doing great job!
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
@vforv export the function for useFactroy. (also the latest version is beta 30 so I would also recomend updating)

``` TS
export function interceptorFactory(xhrBackend: XHRBackend, requestOptions: RequestOptions, router: Router, getToken: AuthTokenService) {
     return new HttpInterceptorService(xhrBackend, requestOptions, router, getToken)
}
...
{
            provide: Http,
            useFactory: interceptorFactory,
            deps: [XHRBackend, RequestOptions, Router, AuthTokenService]
}
...
```

**Comment by vforv** [comment]
Thanks, it is look fixed but I get new error... Some problems with routes:

```
can't find symbol undefined exported from module /home/amerbank-dash/src/app/app.router.ts, resolving symbol AppModule in /home/amerbank-dash/src/app/app.module.ts, resolving symbol AppModule in /home/amerbank-dash/src/app/app.module.ts
Error: can't find symbol undefined exported from module /home/amerbank-dash/src/app/app.router.ts, resolving symbol AppModule in /home/amerbank-dash/src/app/app.module.ts, resolving symbol AppModule in /home/amerbank-dash/src/app/app.module.ts
    at simplifyInContext (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:534:15)
    at StaticReflector.simplify (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:538:18)
    at StaticReflector.annotations (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/static_reflector.ts:94:28)
    at _loop_1 (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:77:48)
    at CodeGeneratorModuleCollector.readFileMetadata (/home/amerbank-dash/node_modules/@angular/compiler-cli/src/codegen.js:79:13)
    at /Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:51:56
    at Array.map (native)
    at CodeGeneratorModuleCollector.getModuleSymbols (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:51:33)
    at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:124:5)
    at AotPlugin._make (/home/amerbank-dash/node_modules/@ngtools/webpack/src/plugin.js:186:43)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/@ngtools/webpack/src/plugin.js:151:75)
    at Compiler.applyPluginsParallel (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:156:14)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:463:8)
    at Compiler.applyPluginsAsync (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:73:70)
    at Compiler.compile (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:456:7)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:219:10)
    at Compiler.readRecords (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:367:10)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:216:9)
    at next (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:213:8)
    at next (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:81:11)
    at Compiler.<anonymous> (/home/amerbank-dash/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (/home/amerbank-dash/node_modules/tapable/lib/Tapable.js:85:13)
    at Compiler.run (/home/amerbank-dash/node_modules/webpack/lib/Compiler.js:210:7)
    at /home/amerbank-dash/node_modules/angular-cli/tasks/build-webpack.js:26:29
    at Class.run (/home/amerbank-dash/node_modules/angular-cli/tasks/build-webpack.js:25:16)
    at Class.run (/home/amerbank-dash/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/home/amerbank-dash/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/home/amerbank-dash/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/home/amerbank-dash/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/home/amerbank-dash/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/home/amerbank-dash/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)


```

Here is my routes file:


```
import {RouterModule} from '@angular/router';

import {LoginComponent} from './login/login.component';
import {RegisterComponent} from './register/register.component';
import {ActivateComponent} from './activate/activate.component';
import {BankComponent} from './bank/bank.component';
import {ForgotComponent} from './forgot/forgot.component';
import {RecoverComponent} from './recover/recover.component';
import {ShowbankComponent} from './showbank/showbank.component'; 
import {EditlenderComponent} from './editlender/editlender.component';
import {ShowlenderComponent} from './showlender/showlender.component';
import { BankmainComponent } from './bankmain/bankmain.component';
import { LendermainComponent} from './lendermain/lendermain.component';
import { DepartmentmainComponent } from './departmentmain/departmentmain.component';
import { ShowdepartmentComponent } from './showdepartment/showdepartment.component';

import {AuthTokenService} from './auth-token.service';

const routes = [
    {path: '', component: LoginComponent, as: 'login', useAsDefault:true},
    {path: 'register', component: RegisterComponent, as: 'register'},
    {path: 'forgot', component: ForgotComponent, as: 'forgot'},
    {path: 'recover/:code', component: RecoverComponent, as: 'recover'},
    {path: 'code/:code', component: ActivateComponent, as: 'activate'},
    {path: 'table', component: BankComponent, as: 'table', canActivate: [AuthTokenService]},
    {path: 'banks', component: BankmainComponent, as: 'banks', canActivate: [AuthTokenService]},
    {path: 'bank/:id', component: ShowbankComponent, as: 'showbank', canActivate: [AuthTokenService]},
    {path: 'edit/lender/:id', component: EditlenderComponent, as: 'editlender', canActivate: [AuthTokenService]},
    {path: 'show/lender/:id', component: ShowlenderComponent, as: 'showlender', canActivate: [AuthTokenService]},
    {path: 'lenders/:bankId', component: LendermainComponent, as: 'showlenders', canActivate: [AuthTokenService]},
    {path: 'departments/:bankId', component: DepartmentmainComponent, as: 'showdepartments', canActivate: [AuthTokenService]},
    {path: 'department/:departmentId/:bankId', component: ShowdepartmentComponent, as: 'showdepartment', canActivate: [AuthTokenService]}
];

export default RouterModule.forRoot(routes);
```

**Comment by deebloo** [comment]
try exporting everything and see if the error goes away

**Comment by filipesilva** [comment]
Heya, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

The CLI always runs statical analysis on code to ensure it will run when compiled with AOT. This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

A good resource on how to to debug these errors is https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts.
