### ISSUE TITLE
data['use'] should NOT have additional properties

### ISSUE THREAD

**Issue by idc1407** [angular/angular-cli#4520]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.

@angular/cli: local (v1.0.0-beta.30, branch: master)
node: 6.9.1
os: win32 x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.6

 
### The log given by the failure.
> ng serve
data['use'] should NOT have additional properties
Error: data['use'] should NOT have additional properties
    at validate (C:\work\jtest\angular-cli\node_modules\extract-text-webpack-plugin\schema\validator.js:11:9)
    at Function.ExtractTextPlugin.extract (C:\work\jtest\angular-cli\node_modules\extract-text-webpack-plugin\index.js:190:3)
    at rules.push.baseRules.map (C:\work\jtest\angular-cli\packages\@angular\cli\models\webpack-configs\styles.ts:80:73)
    at Array.map (native)
    at Object.getStylesConfig (C:\work\jtest\angular-cli\packages\@angular\cli\models\webpack-configs\styles.ts:79:33)
    at new NgCliWebpackConfig (C:\work\jtest\angular-cli\packages\@angular\cli\models\webpack-config.ts:18:31)
    at Class.run (C:\work\jtest\angular-cli\packages\@angular\cli\tasks\serve.ts:34:29)
    at checkExpressPort.then.then (C:\work\jtest\angular-cli\packages\@angular\cli\commands\serve.run.ts:21:22)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by filipesilva** [comment]
Fixed since.
