### ISSUE TITLE
fail to install!

### ISSUE THREAD

**Issue by calidion** [angular/angular-cli#4530]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
>Linux (Ubuntu 16.04).

### Versions.
@angular/cli: 1.0.0-beta.30
node: 6.9.5
os: linux x64

### Repro steps.
```
npm install -g @angular/cli
```

### The log given by the failure.

1.  dependency problems

```
  ├── UNMET PEER DEPENDENCY rxjs@^5.0.1
```

2. warnings

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/core@2.4.6 requires a peer of rxjs@^5.0.1 but none was installed.

```
3. ng help result

```
ng help
Cannot find module 'rxjs/symbol/observable'
Error: Cannot find module 'rxjs/symbol/observable'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at globalScope (/home/eric/.nvm/versions/node/v6.9.5/lib/node_modules/@angular/cli/node_modules/@angular/core/bundles/core.umd.js:7:85)
    at Object.<anonymous> (/home/eric/.nvm/versions/node/v6.9.5/lib/node_modules/@angular/cli/node_modules/@angular/core/bundles/core.umd.js:10:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

**Comment by darrenbrett** [comment]
Did you check to make sure you're meeting the requirements for NPM and Node versions?

**Comment by kevmando** [comment]
I have same issue with exact same config.
Ubuntu 16.04
node v6.9.5
npm 3.10.10

**Comment by nmongiya** [comment]
try npm install -g rxjs

**Comment by catull** [comment]
This works for me.

`ng install -g rxjs`
`ng install -g @angular/cli`
`ng help`

It prints out a lot of help texts, including the most recent addition: xi18n.

**Comment by filipesilva** [comment]
This was an unfortunate oversight in the last release. It's fixed in master and should be in the next release.
