### ISSUE TITLE
NG installation broken.

### ISSUE THREAD

**Issue by pcsgithubid** [angular/angular-cli#4606]
i have installed npm install -g @angular/cli using npm 3.6.0 and get below error from my mac

± |develop ✓| → ng -v
/.nvm/versions/node/v5.6.0/lib/node_modules/@angular/cli/models/config/config.js:15
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/ChandrasekharPasupuleti/.nvm/versions/node/v5.6.0/lib/node_modules/@angular/cli/models/config.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by hansl** [comment]
CLI requires node 6.9 or greater.
