### ISSUE TITLE
DI Error

### ISSUE THREAD

**Issue by martinop** [angular/angular-cli#4622]
### OS?
 Windows10

### Versions.
@angular/cli: 1.0.0-beta.31
node: 7.2.0
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

### Repro steps.
ng serve

### The log given by the failure.
Error: DI Error
    at NoProviderError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:816:33)
    at NoProviderError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:31581:16)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4200/vendor.bundle.js:63280:16)
    at new NoProviderError (http://localhost:4200/vendor.bundle.js:63342:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/vendor.bundle.js:88631:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor.bundle.js:88670:25)
    at ReflectiveInjector_._getByKey (http://localhost:4200/vendor.bundle.js:88602:25)
    at ReflectiveInjector_.get (http://localhost:4200/vendor.bundle.js:88471:21)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:364:154)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:384:164)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:617:50)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:64215:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4200/vendor.bundle.js:89406:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4200/vendor.bundle.js:89834:49)
    at ElementInjector.get (http://localhost:4200/vendor.bundle.js:88910:27)

### Mention any other details that might be useful.

I have a Shared Module that import in the App Module and LoginModule.

When I import the services inside the constructor, get the DI ERROR
![screenshot_18](https://cloud.githubusercontent.com/assets/10482079/22855548/b1d99fc6-f058-11e6-8ec6-c34dc07c6e38.png)
![screenshot_19](https://cloud.githubusercontent.com/assets/10482079/22855549/b3af23e8-f058-11e6-97d4-4d5692c0243d.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/10482079/22855554/cac9f292-f058-11e6-9f37-b79670d85de2.png)

**Comment by mattdistefano** [comment]
1. Are you sure your providers in `SharedModule` includes both the `APIService` and `UtilsService`?
2. Are you sure `AppModule` imports `SharedModule.forRoot()` and not just `SharedModule`?

**Comment by hansl** [comment]
This feels to me it's a problem with Angular itself, not the CLI. You should file an issue on http://github.com/angular/angular. I'm going to close this but if you think that it is a problem with the CLI just answer here.

**Comment by richardsengers** [comment]
I haven't figured out what exactly is causing this, but I did an upgrade to beta 31 from beta 26. In Beta 26 all was working fine, in Beta 31 this error pops up.
Angular version is 2.4.4 for both the Beta 26 and beta 31 so I would say the error has something to do with the cli

**Comment by StraightOuttaCrompton** [comment]
Did you submit the issue to http://github.com/angular/angular ?? I'm having a similar issue

**Comment by gtarun** [comment]
getting the similar issue on my angular2 app, but its not consistent and comes anonymously, any help ?
