### ISSUE TITLE
Problem to upgrade my project 

### ISSUE THREAD

**Issue by zhouhao27** [angular/angular-cli#4644]
My project was running well until I upgrade my angular-cli recently.

### OS?
> Mac OSX 10.12.3

Current project package.json:

```
"dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
```

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
@angular/cli: 1.0.0-beta.30
node: 7.5.0
os: darwin x64
@angular/common: 2.2.3
@angular/compiler: 2.2.3
@angular/core: 2.2.3
@angular/forms: 2.2.3
@angular/http: 2.2.3
@angular/platform-browser: 2.2.3
@angular/platform-browser-dynamic: 2.2.3
@angular/router: 3.2.3
@angular/compiler-cli: 2.2.3
```

### Repro steps.
> ng serve 

Got the following error message:

```
This version of CLI is only compatible with angular version 2.3.1 or better. Please
upgrade your angular version, e.g. by running:

npm install @angular/core@latest 

```

### Then I upgraded by: 

> npm install @angular/core@latest 

Got the follow message:

```
jsdemo@0.0.0 /Users/zhouhao/Projects/parse-live-query/ParseChat/angular-client
├── UNMET PEER DEPENDENCY @angular/compiler@2.2.3
├── UNMET PEER DEPENDENCY @angular/compiler-cli@2.2.3
├── UNMET PEER DEPENDENCY @angular/core@2.4.7 invalid
├─┬ angular-cli@1.0.0-beta.22-1
│ ├─┬ @angular-cli/ast-tools@1.0.16
│ │ └── @angular/tsc-wrapped@0.5.2 
│ ├── UNMET PEER DEPENDENCY @angular/core@2.2.3
│ ├── UNMET PEER DEPENDENCY @angular/tsc-wrapped@^0.5.0
│ ├── UNMET PEER DEPENDENCY tslint@3.15.1
│ └── UNMET PEER DEPENDENCY webpack@2.1.0-beta.25
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── UNMET PEER DEPENDENCY zone.js@0.6.26

```

### Run project again
> ng serve

Got the following error message:

> ERROR in ./src/main.ts
> Module build failed: TypeError: Cannot read property 'newLine' of undefined
>     at Object.getNewLineCharacter (/Users/Projects/parse-live-query/myapp/angular-client/node_modules/typescript/lib/typescript.js:8062:20)
>     at Object.createCompilerHost (/Users/Projects/parse-live-query/myapp/angular-client/node_modules/typescript/lib/typescript.js:44978:26)
>     at Object.ngcLoader (/Users/Projects/parse-live-query/myapp/angular-client/node_modules/@ngtools/webpack/src/loader.js:341:33)
>  @ multi webpack-dev-server/client?http://localhost:4200/ ./src/main.ts

Any idea? Thanks.

**Comment by delasteve** [comment]
We might want to make that message a bit clearer as `@angular/core` isn't the only package you will need to update. Try replacing your `package.json` with the following, where appropriate:

```json
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.31",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.0"
  }
}
```

**Comment by Brocco** [comment]
@zhouhao27 can you confirm that updating the `@angular` libs has worked for you?

**Comment by zhouhao27** [comment]
@Brocco Thanks. It's working fine now.

**Comment by riteshwaghela** [comment]
I am also getting  the same error. When I tried to install the above mentioned packages mentioned by @delasteve, I am getting  No compatible version found: angular-cli@1.0.0-beta.31. @zhouhao27 can you please confirm if you could install angular-cli successfully? Thanks.

**Comment by EdwardPayne** [comment]
I had the same problem but now when i run ng build och ng serve i get: 
"You have to be inside an angular-cli project in order to use the build command."

I am of course in my angular-cli project when I'm running this.

**Comment by smartHasmukh** [comment]
When I have tried to install `npm install @angular/core@latest` but it is doesn't installed. Please give me solutions.

```
angular-cli-production@0.0.0 /var/www/html/loyalty-dapp
├── UNMET PEER DEPENDENCY @angular/core@2.4.7 invalid
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── UNMET PEER DEPENDENCY zone.js@0.6.26

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/common@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/compiler@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/compiler-cli@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/core@2.4.7 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.7 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN @angular/forms@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/http@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/platform-browser@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @angular/router@3.2.1 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN @ngtools/webpack@1.1.6 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN angular-in-memory-web-api@0.1.17 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
npm WARN angular-in-memory-web-api@0.1.17 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/core@~2.2.0 but none was installed.


```

**Comment by melissamanjarres** [comment]
Hello @riteshwaghela did you find a solution to your problem? Thanks

**Comment by engrashid** [comment]
@delasteve  your package settings worked for me .

just had to replace "assets: "assets" to  "assets: [ "assets" ]  in angular-cli.json file
