### ISSUE TITLE
`ng e2e` cannot find `update-config.json`

### ISSUE THREAD

**Issue by rkrisztian** [angular/angular-cli#4660]
### OS?
Red Hat Enterprise Linux Workstation release 6.8 (Santiago)

### Versions.
```
@angular/cli: 1.0.0-beta.31
node: 6.9.4
os: linux x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7
```

### Repro steps.
Execute `ng e2e` on a project freshly generated with `ng new`.

### The log given by the failure.
```
** NG Live Development Server is running on http://localhost:4200. **
Hash: 048e31b3a64d7e6f2ae2                                                               
Time: 10764ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.map (polyfills) 147 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.map (main) 4.08 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.map (styles) 10 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.map (vendor) 2.62 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
[14:35:50] I/file_manager - creating folder /home/rkrisztian/projects/testProject/node_modules/protractor/node_modules/webdriver-manager/selenium
[14:35:51] I/downloader - curl -o /home/rkrisztian/projects/testProject/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.27.zip https://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
[14:35:52] I/update - chromedriver: unzipping chromedriver_2.27.zip
[14:35:52] I/update - chromedriver: setting permissions to 0755 for /home/rkrisztian/projects/testProject/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.27
[14:35:52] I/launcher - Running 1 instances of WebDriver
[14:35:52] I/direct - Using ChromeDriver directly...
[14:35:52] E/launcher - Server terminated early with status 1
[14:35:52] E/launcher - Error: Server terminated early with status 1
    at Error (native)
    at earlyTermination.catch.e (/home/rkrisztian/projects/testProject/node_modules/selenium-webdriver/remote/index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/rkrisztian/projects/testProject/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/home/rkrisztian/projects/testProject/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/home/rkrisztian/projects/testProject/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/home/rkrisztian/projects/testProject/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/home/rkrisztian/projects/testProject/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/home/rkrisztian/projects/testProject/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/rkrisztian/projects/testProject/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/rkrisztian/projects/testProject/node_modules/q/q.js:796:13)
    at /home/rkrisztian/projects/testProject/node_modules/q/q.js:556:49
    at runSingle (/home/rkrisztian/projects/testProject/node_modules/q/q.js:137:13)
    at flush (/home/rkrisztian/projects/testProject/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[14:35:52] E/launcher - Process exited with error code 199
```

### Mention any other details that might be useful.
(N/A)

**Comment by rkrisztian** [comment]
Sorry, duplicate of #4640.
