### ISSUE TITLE
ng completion not working (Error: Cannot find module './build.d')

### ISSUE THREAD

**Issue by delight** [angular/angular-cli#4664]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 14.04.5 LTS

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

ng completion
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at commandFiles.reduce (/home/use/.nvm/versions/node/v6.9.5/lib/node_modules/@angular/cli/commands/completion.js:46:33)
    at Array.reduce (native)
    at Class.run (/home/use/.nvm/versions/node/v6.9.5/lib/node_modules/@angular/cli/commands/completion.js:44:41)
    at Class.<anonymous> (/home/use/.nvm/versions/node/v6.9.5/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Mention any other details that might be useful.
all available options for ng completion (-a, -b, -z) result in the same error

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Murazaki** [comment]
Same error on Mac OS X Sierra 10.12.3

````
ng completion
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at commandFiles.reduce (/Users/murazaki/Dev/Web/MEAN/compo/web-angular-ts/node_modules/@angular/cli/commands/completion.js:46:33)
    at Array.reduce (native)
    at Class.run (/Users/murazaki/Dev/Web/MEAN/compo/web-angular-ts/node_modules/@angular/cli/commands/completion.js:44:41)
    at Class.<anonymous> (/Users/murazaki/Dev/Web/MEAN/compo/web-angular-ts/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
````

**Comment by tarlepp** [comment]
Same error here

```
@angular/cli: 1.0.0-beta.32.3
node: 7.2.1
os: linux x64
```

```
wunder@Code-VirtualBox:~/projects$ ng completion -b
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at commandFiles.reduce (/home/wunder/.nvm/versions/node/v7.2.1/lib/node_modules/@angular/cli/commands/completion.js:54:33)
    at Array.reduce (native)
    at Class.run (/home/wunder/.nvm/versions/node/v7.2.1/lib/node_modules/@angular/cli/commands/completion.js:52:41)
    at Class.<anonymous> (/home/wunder/.nvm/versions/node/v7.2.1/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by dave11mj** [comment]
Same error here

```
@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: darwin x64
```

```
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    ...
```

**Comment by delight** [comment]
error still present in 1.0.0-beta.32.3

**Comment by zbicin** [comment]
Same story on Windows using Git Bash (haven't checked in `cmd` though):

``` 
@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: win32 x64
 ```

```
$ ng completion
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at commandFiles.reduce (xxxxx\AppData\Roaming\npm\node_modules\@angular\cli\commands\completion.js:54:33)
    at Array.reduce (native)
    at Class.run (xxxxx\AppData\Roaming\npm\node_modules\@angular\cli\commands\completion.js:52:41)
    at Class.<anonymous> (xxxxx\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by pawmot** [comment]
Same here:

```
@angular/cli: 1.0.0-beta.32.3
node: 7.3.0
os: linux x64
```
```
Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at commandFiles.reduce (/home/pmotyl/.nvm/versions/node/v7.3.0/lib/node_modules/@angular/cli/commands/completion.js:54:33)
    at Array.reduce (native)
    at Class.run (/home/pmotyl/.nvm/versions/node/v7.3.0/lib/node_modules/@angular/cli/commands/completion.js:52:41)
    at Class.<anonymous> (/home/pmotyl/.nvm/versions/node/v7.3.0/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by d2chau** [comment]
This is also reproducible on: 1.0.0-beta.32.3
@angular/cli:
node: 7.4.0
OS: OSX Sierra 10.12.3

**Comment by prijindal** [comment]
Same Here

@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: linux x64

**Comment by Meligy** [comment]
Getting it in rc0 on Mac Sierra:

```
@angular/cli: 1.0.0-rc.0
node: 6.9.1
os: darwin x64
```

Installed globally via Yarn, if at all relevant.

**Comment by ovitrif** [comment]
Getting it in Ubuntu 16.04 x64
@angular/cli: 1.0.0-rc.0

**Comment by alexanderwende** [comment]
Same on MacOS Sierra 10.12.3:

@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: darwin x64

Cannot find module './build.d'
Error: Cannot find module './build.d'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at commandFiles.reduce (/Users/alex/.config/yarn/global/node_modules/@angular/cli/commands/completion.js:72:33)
    at Array.reduce (native)
    at Class.run (/Users/alex/.config/yarn/global/node_modules/@angular/cli/commands/completion.js:70:41)
    at Class.<anonymous> (/Users/alex/.config/yarn/global/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by doxasoft** [comment]
Same on Mac El Capitan

@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: darwin x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

**Comment by filipesilva** [comment]
This is a bug and I will look at it.

**Comment by comewalk** [comment]
@filipesilva I've already created a fix at #4972 included a test. Please see the PR. Thanks.

**Comment by filipesilva** [comment]
@comewalk oh thanks! I hadn't seen it and the test is much better than mine. I'll merge yours instead. Cheers!

**Comment by comewalk** [comment]
@filipesilva thanks!

**Comment by lobo-tuerto** [comment]
Hello guys,

This is still happening in:

```
@angular/cli: 1.0.0-rc.1
node: 7.7.2
os: linux x64
```

**Comment by dave11mj** [comment]
I think the code that fixes it hasn't being released. It was only merged 3 days ago, and rc.1 is being out for about a week.
