### ISSUE TITLE
angular cli error with empty repository

### ISSUE THREAD

**Issue by Malouke** [angular/angular-cli#4687]
> Please provide us with the following information:
> ---------------------------------------------------------------

###windows 7 ?

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### The log given by the failure.
Cannot read property 'input' of null
TypeError: Cannot read property 'input' of null
    at ObjectSchemaTreeNode._set (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:226:131)
    at new ObjectSchemaTreeNode (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:211:14)
    at OneOfSchemaTreeNode._createChildProperty (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:150:2
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-t
    at Array.map (native)
    at OneOfSchemaTreeNode (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:162:48)
    at ArraySchemaTreeNode._createChildProperty (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:150:2
    at ArraySchemaTreeNode._set (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:288:39)
    at new ArraySchemaTreeNode (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:269:14)
    at ObjectSchemaTreeNode._createChildProperty (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:150:
    at ObjectSchemaTreeNode._set (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:226:45)
    at new ObjectSchemaTreeNode (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:211:14)
    at ArraySchemaTreeNode._createChildProperty (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:150:2
    at ArraySchemaTreeNode._set (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:288:39)
    at new ArraySchemaTreeNode (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:269:14)
    at RootSchemaTreeNode._createChildProperty (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:150:26
    at RootSchemaTreeNode._set (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:226:45)
    at RootSchemaTreeNode.ObjectSchemaTreeNode (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:211:14
    at RootSchemaTreeNode (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-tree.js:309:9)
    at GeneratedSchemaClass.SchemaClassBase (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-class-factory.js:
    at GeneratedSchemaClass (C:\workspacecode\dashbord\client\front\node_modules\@ngtools\json-schema\src\schema-class-factory.js:140:13)
    at new CliConfig (C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\models\config\config.js:17:24)
    at Function.fromConfigPath (C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\models\config\config.js:80:16)
    at Function.fromProject (C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\models\config.js:57:46)
    at Object.<anonymous> (C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\commands\serve.js:11:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\addon\index.js:23:16)
    at C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\ember-cli\lib\models\project.js:326:61
    at Array.forEach (native)
    at Project.addonCommands (C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\ember-cli\lib\models\project.js:325:15)
    at Project.eachAddonCommand (C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\ember-cli\lib\models\project.js:360:30)
    at module.exports (C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\ember-cli\lib\cli\lookup-command.js:33:13)
    at CLI.<anonymous> (C:\workspacecode\dashbord\client\front\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:42:26)
    at tryCatch (C:\workspacecode\dashbord\client\front\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\workspacecode\dashbord\client\front\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\workspacecode\dashbord\client\front\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (C:\workspacecode\dashbord\client\front\node_modules\rsvp\dist\rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

###  the project it s empty i dont make any modification ????
which version stable ????
thank you

**Comment by RicardoVaranda** [comment]
Hi @Malouke would you be able to post the steps you did so I can try to reproduce this error.

**Comment by pascalschoeni** [comment]
The following helps for me:

1. Open schema.json, located under @angular/cli/lib/config/schema.json
2. Remove 
`,
                {
                  "type": "object",
                  "properties": {
                    "input": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": true
                }`
under styles (aka lines 83 - 91)

Maybe the parser is broken or changed? 

What is really interesting: If I create a new installation from scratch (in a docker container) it just works. I have no idea.

**Comment by filipesilva** [comment]
Closing as inactive.
