### ISSUE TITLE
Missing dependency on install angular-cli@0.33 : error on ng serve : Could not require 'angular-cli-build.js': Cannot find module 'glob'

### ISSUE THREAD

**Issue by choucry13** [angular/angular-cli#469]
1. OS. 
  Windows 7
2. Versions. 
angular-cli: 0.0.33
node: 5.10.1
os: win32 x64

3. Repro steps. When I updated my current version of angular-cli (v0.32) to (v0.33), I wanted to create a new app. After installation finish, I launch the commande `ng serve`.
4. The log given by the failure. 

D:\projects\PocNewBad\src\new-bad\aix\philou-app>ng serve
Could not require 'angular-cli-build.js': Cannot find module 'glob'
Error: Could not require 'angular-cli-build.js': Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\projects\PocNewBad\src\new-bad\aix\philou-app\node
_modules\angular-cli\lib\broccoli\angular2-app.js:3:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

5. Don't worry, I resolved the problem by installing glob package `npm install glob --save-dev`. My issue is just to ask to add a feature to install glob package ?

Sorry for my english 
Best regards.
Philippe.B

**Comment by cexbrayat** [comment]
I had the same issue (Mac OSX, angular-cli 0.0.33). Installing glob solved it too.

**Comment by choucry13** [comment]
Thank you :+1:
