### ISSUE TITLE
ng serve error message after fresh install

### ISSUE THREAD

**Issue by matt-newell** [angular/angular-cli#47]
/Users/mattnewell/Projects/NG2TEST/node_modules/angular-cli-github-pages/lib/commands/deploy.js:55
              (files) => RSVP.all(files.map((file) => fsCopy(path.join('dist',
                      ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Class.module.exports.includedCommands (/Users/mattnewell/Projects/NG2TEST/node_modules/angular-cli-github-pages/index.js:9:30)
    at /Users/mattnewell/Projects/NG2TEST/node_modules/angular-cli/node_modules/ember-cli/lib/models/project.js:393:61
    at Array.forEach (native)

**Comment by jaromirecek** [comment]
Same error on Windows 10.

**Comment by IgorMinar** [comment]
Please upgrade to node v4.
