### ISSUE TITLE
create a new project, and crash ng --version, build, serve

### ISSUE THREAD

**Issue by elioth010** [angular/angular-cli#4717]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OS: Debian 9.0 stretch

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

ng --version
angular-cli: 1.0.0-beta.21
node: 4.7.2
os: linux x64

 node --version
v4.7.2

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Create a new app with ng new, enter to project and type ng --version and show this error

### The log given by the failure.
> Normally this include a stack trace and some more information.
Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/@ngtools/webpack/src/index.js:5:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/models/webpack-build-typescript.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/models/webpack-config.js:2:34)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/tasks/build-webpack.js:6:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/commands/build.js:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Class.module.exports.includedCommands (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/addon/index.js:21:16)
    at /home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/angular-cli/lib/models/project.js:391:15)
    at Project.eachAddonCommand (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/angular-cli/lib/models/project.js:426:30)
    at module.exports (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/angular-cli/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/elioth010/Development/Workspaces/AngularWorkspace/View/node_modules/rsvp/dist/rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)

### Mention any other details that might be useful.
only in into folder created by ng new, inside type ng --version and show this error, don't build , don't serve, same error 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by heeyoun-song** [comment]
That's the same thing I've been through. Problem with

Node version issue.The same problem occurred when I was using 4.x.x.
 
Problems such as will not occur if they are not accurate but update with Node version 6.x.x.

**Comment by elioth010** [comment]
@heeyoun-song i have upgraded to node 6.9.5 and now works well thanks for your solution
