### ISSUE TITLE
ng build --prod fails

### ISSUE THREAD

**Issue by ukaaa** [angular/angular-cli#4739]
### OS?
Window 10

### Versions.
```
@angular/cli: 1.0.0-beta.30
node: 6.9.0
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/compiler-cli: 2.4.7

@typescript: ~2.0.3
```

### Repro steps.
I called `ng build --prod`. In dev environment it works fine.

### The log given by the failure.
```cmd
WARNING in ./src/$$_gendir/app/app.module.ngfactory.ts
959:29-46 "export 'version' (imported as 'import200') was not found in '../../environments/environment'

ERROR in ./~/angular2-logger/app/core/logger.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
    at Object.getTokenPosOfNode (C:\…\node_modules\typescript\lib\typescript.js:5692:71)
    at IdentifierObject.TokenOrIdentifierObject.getStart (C:\…\node_modules\typescript\lib\typescript.js:53623:23)
    at IdentifierObject.TokenOrIdentifierObject.getText (C:\…\node_modules\typescript\lib\typescript.js:53644:77)
    at refactor.findAstNodes.filter (C:\…\node_modules\@ngtools\webpack\src\loader.js:135:44)
    at Array.filter (native)
    at refactor.findAstNodes.forEach.node (C:\…\node_modules\@ngtools\webpack\src\loader.js:134:14)
    at Array.forEach (native)
    at _removeDecorators (C:\…\node_modules\@ngtools\webpack\src\loader.js:125:10)
    at Promise.resolve.then (C:\…\node_modules\@ngtools\webpack\src\loader.js:295:33)
 @ ./~/angular2-logger/core.js 6:9-37
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

### Mention any other details that might be useful.
It could be interesting to note that my environment files have an additional property called "version", and I refer to the dev environment explicitely in `angular-cli.json`.

```ts
// environment.dev.ts
const version = require('./deploy.json').version;
export const environment = {
  production: false,
  version
};
```

```ts
// environment.prod.ts
const version = require('./deploy.json').version;
export const environment = {
  production: true,
  version
};
```

```js
// angular-cli.json
"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.dev.ts", // <---
  "prod": "environments/environment.prod.ts"
}
```

**Comment by ukaaa** [comment]
Apologies, it seems related to [this](https://github.com/code-chunks/angular2-logger/issues/113).
