### ISSUE TITLE
ng serve error  Unexpected token {

### ISSUE THREAD

**Issue by nolafs** [angular/angular-cli#4783]
> Please provide us with the following information:
> ---------------------------------------------------------------

When I run ng serve, I get the following error:

Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/@ngtools/webpack/src/index.js:5:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/models/webpack-build-typescript.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/models/webpack-config.js:2:34)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/tasks/build-webpack.js:6:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/commands/build.js:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Class.module.exports.includedCommands (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/addon/index.js:21:16)
    at /Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/angular-cli/lib/models/project.js:392:61
    at Array.forEach (native)
    at Project.addonCommands (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/angular-cli/lib/models/project.js:391:15)
    at Project.eachAddonCommand (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/angular-cli/lib/models/project.js:426:30)
    at module.exports (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/angular-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/angular-cli/angular-cli/lib/cli/cli.js:34:26)
    at tryCatch (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Volumes/dev/HTML/phase_1/standmore_clinic/node_modules/rsvp/dist/rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
macOS Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.20-4
node: 4.5.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment]
This is a very old version of the CLI

My guess is that because the CLI has dependencies on other packages, which have evolved a lot, they probably became not backwards compatible with the old version of the CLI you have. Since this is beta software, backwards compatibility with older versions isn't much applied, especially a version that old. The current version is beta.32-3.

I suggest you update to the latest CLI and try again.

**Comment by filipesilva** [comment]
Yeah unfortunately we don't support older versions currently. You'll have to update.
