### ISSUE TITLE
ng test is looking for angular-cli.json not .angular-cli.json on angular-cli@1.0.0-beta.32.3

### ISSUE THREAD

**Issue by cjmosure** [angular/angular-cli#4800]
### OS?
Both Windows 10 & OS X El Capitan

### Versions.
@angular/cli: 1.0.0-beta.32.3
node: 7.5.0
os: darwin x64

### Repro steps.
Updated to 1.0.0-beta.32.3 from 1.0.0-beta.31

### The log given by the failure.
```
CJs-MBP:igce-web christophermosure$ ng test
Cannot find module '/Users/christophermosure/dev/igce-tool/igce-web/angular-cli.json'
Error: Cannot find module '/Users/christophermosure/dev/igce-tool/igce-web/angular-cli.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at init (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/@angular/cli/plugins/karma.js:19:28)
    at Array.invoke (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/di/lib/injector.js:75:15)
    at Injector.get (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/di/lib/injector.js:48:43)
    at /Users/christophermosure/dev/igce-tool/igce-web/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/karma/lib/server.js:103:18)
    at Promise (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/@angular/cli/tasks/test.js:34:25)
    at Class.run (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/@angular/cli/tasks/test.js:15:16)
    at Class.run (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/@angular/cli/commands/test.js:38:25)
    at Class.<anonymous> (/Users/christophermosure/dev/igce-tool/igce-web/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by cjmosure** [comment]
Sorry, had a wrong value in karma-config.js
