### ISSUE TITLE
beta.32-3: ng -v >>> Cannot read property 'glob' of null

### ISSUE THREAD

**Issue by ciesielskico** [angular/angular-cli#4807]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux Mint 18 x64

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

can't run ng --version

### Repro steps.

npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli
ng --version

### The log given by the failure.

```
ciesielskico@Alex-Mint ~ $ ng --version
Cannot read property 'glob' of null
TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:226:131)
    at new ObjectSchemaTreeNode (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:211:14)
    at OneOfSchemaTreeNode._createChildProperty (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:163:25)
    at Array.map (native)
    at OneOfSchemaTreeNode (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:162:48)
    at ArraySchemaTreeNode._createChildProperty (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at ArraySchemaTreeNode._set (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:288:39)
    at new ArraySchemaTreeNode (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:269:14)
    at ObjectSchemaTreeNode._createChildProperty (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at ObjectSchemaTreeNode._set (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:226:45)
    at new ObjectSchemaTreeNode (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:211:14)
    at ArraySchemaTreeNode._createChildProperty (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at ArraySchemaTreeNode._set (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:288:39)
    at new ArraySchemaTreeNode (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:269:14)
    at RootSchemaTreeNode._createChildProperty (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at RootSchemaTreeNode._set (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:226:45)
    at RootSchemaTreeNode.ObjectSchemaTreeNode (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:211:14)
    at RootSchemaTreeNode (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-tree.js:309:9)
    at GeneratedSchemaClass.SchemaClassBase (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-class-factory.js:52:29)
    at GeneratedSchemaClass (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/@ngtools/json-schema/src/schema-class-factory.js:140:13)
    at new CliConfig (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/models/config/config.js:17:24)
    at Function.fromConfigPath (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/models/config/config.js:80:16)
    at Function.fromProject (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/models/config.js:79:46)
    at Object.<anonymous> (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/commands/build.js:5:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/addon/index.js:22:16)
    at /home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/ember-cli/lib/models/project.js:287:61
    at Array.forEach (native)
    at Project.addonCommands (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/ember-cli/lib/models/project.js:286:15)
    at Project.eachAddonCommand (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/ember-cli/lib/models/project.js:321:30)
    at module.exports (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/ember-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:42:26)
    at tryCatch (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/ciesielskico/.npm-global/lib/node_modules/@angular/cli/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Mention any other details that might be useful.

`ng -new` doesn't run as well

`$ npm list -g | grep angular`

> ├─┬ @angular/cli@1.0.0-beta.32.3
> │ ├── @angular/compiler@2.4.7
> │ ├─┬ @angular/compiler-cli@2.4.7
> │ ├── @angular/core@2.4.7
> │ ├─┬ @angular/tsc-wrapped@0.5.2

`$ node -v`

> v6.9.5

`$ npm --version`

> v3.10.10

**Comment by ciesielskico** [comment]
Found the issue. I had an `angular-cli.json` file lying in my home directory, which most probably got picked up somehow when running `ng -v`. Deleted that file and it works now.
