### ISSUE TITLE
updating to latest version gives error in cli\modles\config.js

### ISSUE THREAD

**Issue by niwrA** [angular/angular-cli#4814]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
ng is broken after updating to the latest version using the instructions: 

npm uninstall -g angular-cli @angular/cli
npm cache clean
npm install -g @angular/cli@latest

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Just doing a fresh install on a different machine which I do occasionally to see if others can still install the package (so I don't forget to update package.json etc.)

### The log given by the failure.
> Normally this include a stack trace and some more information.
C:\Users\Arwin\AppData\Roaming\npm\node_modules\@angular\cli\models\config\config.js:15
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Arwin\AppData\Roaming\npm\node_modules\@angular\cli\models\config.js:2:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

### Mention any other details that might be useful.
I was on 1.0.0-beta.26, but this one already wasn't available anymore online, so this forced me to update everything. Is that really necessary?

EDIT: currently investigating if it's just the version of nodejs on this machine ... 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by niwrA** [comment]
I already found the issue - had to upgrade nodejs. So I'm guessing there were already changes active that required upgrading nodejs in this version, although the changelog implied this would be in a later version (if I read them correctly). 

Also, now that ng serve runs again, I notice this. I never had a "source" environment, so didn't think I needed to make the environmentSource change, but it requires me to now. .
