### ISSUE TITLE
ng serve (windows): cannot find tsconfig.json in client directory

### ISSUE THREAD

**Issue by ssougnez** [angular/angular-cli#483]
**Steps**

ng new T
cd T
ng serve

**Error**

ENOENT: no such file or directory, open 'C:\Users\ssougnez\Desktop\T\src\client\tsconfig.json'
Error: ENOENT: no such file or directory, open 'C:\Users\ssougnez\Desktop\T\src\client\tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Angular2App._getTsTree (C:\Users\ssougnez\Desktop\T\node_modules\angular-cli\lib\broccoli\angular2-app.js:276:34)
    at Angular2App._buildTree (C:\Users\ssougnez\Desktop\T\node_modules\angular-cli\lib\broccoli\angular2-app.js:84:23)
    at new Angular2App (C:\Users\ssougnez\Desktop\T\node_modules\angular-cli\lib\broccoli\angular2-app.js:40:23)
    at module.exports (C:\Users\ssougnez\Desktop\T\angular-cli-build.js:6:13)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\ssougnez\Desktop\T\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\ssougnez\Desktop\T\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\ssougnez\Desktop\T\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)

**Versions**

angular-cli: 0.0.33
node: 5.10.1
os: win32 x64

**Comment by PascalPrecht** [comment]
@ssougnez this is because the file structure in angular-cli has changed since `0.0.30` 

it's not `src/app` but `src/client/app`

**Comment by ssougnez** [comment]
euh, ok, thanks but... I guess this need to be fixed then ? (It's the first time I post an issue on github so I don't exactly know what's the policy here so apologize if I'm rude :-D)

**Comment by filipesilva** [comment]
That's one of the issues with the CLI being in early alpha, it's common enough to be breaking changed between versions.

There's two installs at play here, the local and the global, and you kinda need to update both (we're looking at giving the user a warning when these mismatch). The safest bet when updating a project is to globally install the new cli, make a blank new project and copy over whatever changes you see. 

It's a pain, but it's the best that can be done in alpha.

And you're not being rude at all, feedback is much appreciated :D

**Comment by neilhem** [comment]
According to version 0.0.39 when I scaffold a new via `ng new my-app` there is not client folder in app
