### ISSUE TITLE
appConfig.assets.forEach is not a function

### ISSUE THREAD

**Issue by trueflywood** [angular/angular-cli#4840]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
  Mac OSX ( El Capitan)

### Versions.
 @angular/cli: 1.0.0-beta.32 [1.5.10]
node: 7.4.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/upgrade: 2.4.8
@angular/cli: 1.0.0-beta.32
@angular/compiler-cli: 2.4.8

### Repro steps.
ng test

### The log given by the failure.

20 02 2017 11:37:16.707:DEBUG [plugin]: Loading inlined plugin (defining framework:jasmine).
20 02 2017 11:37:16.711:DEBUG [plugin]: Loading inlined plugin (defining reporter:kjhtml).
20 02 2017 11:37:16.712:DEBUG [plugin]: Loading inlined plugin (defining launcher:Chrome, launcher:ChromeCanary, launcher:Chromium, launcher:Dartium, test).
20 02 2017 11:37:16.712:DEBUG [plugin]: Loading inlined plugin (defining reporter:karma-remap-istanbul).
20 02 2017 11:37:16.712:DEBUG [plugin]: Loading inlined plugin (defining framework:@angular/cli, preprocessor:@angular/cli, webpackPlugin, preprocessor:webpack, middleware:webpackBlocker, preprocessor:sourcemap).
appConfig.assets.forEach is not a function
TypeError: appConfig.assets.forEach is not a function
    at init (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/@angular/cli/plugins/karma.js:32:22)
    at Array.invoke (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/di/lib/injector.js:75:15)
    at Injector.get (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/di/lib/injector.js:48:43)
    at /Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/karma/lib/server.js:103:18)
    at Promise (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/@angular/cli/tasks/test.js:34:25)
    at Class.run (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/@angular/cli/tasks/test.js:15:16)
    at Class.run (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/@angular/cli/commands/test.js:38:25)
    at Class.<anonymous> (/Users/flywood/Projects/smsconnect/Source/SMSConnect/Connect.UI/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by grizzm0** [comment]
Please read the changelog. As of beta 32 assets must be an array which was introduced somewhere around beta 24. The optional string type was kept for BC up until beta 32.

See: https://github.com/angular/angular-cli/blob/master/CHANGELOG.md

**Comment by filipesilva** [comment]
Closing as answered, thanks @grizzm0 !
