### ISSUE TITLE
Latest Release brakes angular-cli functionality (?)

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#485]
Node version: 5.10.1
npm version: 3.8.6
angular-cli version: 0.0.33
os: darwin x64

After the update to last release angular-cli for me is unusable.
I cannot even get the help options, the version create anything. always getting this:

```
Cannot find module 'symlink-or-copy'
Error: Cannot find module 'symlink-or-copy'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Projects/MyApp/node_modules/broccoli-merge-trees/index.js:4:25)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Any ideas?

**UPDATE**: I manage to solve it by manually installing (in my project) **broccoli-merge-trees** node module. It was already there as a dependency but didn't work for some reason.

I'm leaving this open for further investigation.

**Comment by vapits** [comment]
Another UPDATE:
I still can't use lots of commands.

For example: 
```
ng -v
```
gives me:
```
/Projects/MyApp/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/Users/vassilis/.config/configstore/ember-cli.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/Projects/MyApp/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/Projects/MyApp/node_modules/configstore/index.js:27:44)
    at clientId (/Projects/MyApp/node_modules/ember-cli/lib/cli/index.js:22:21)
    at module.exports (/Projects/MyApp/node_modules/ember-cli/lib/cli/index.js:65:19)
    at module.exports (/Projects/MyApp/node_modules/angular-cli/lib/cli/index.js:99:10)
    at /usr/local/lib/node_modules/angular-cli/bin/ng:36:5
    at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:44:21
```

But with `sudo` I get normally:
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
angular-cli: 0.0.33
node: 5.10.1
os: darwin x64
```

Now, I do realise that some permissions issue is this and MAYBE can be something with my filesystem but the thing is hat the only change was the upgrade from 0.0.31 to 0.0.33.

Also I created elsewhere (different pc) a new test project and I get exactly the same issues.

**Comment by filipesilva** [comment]
We do have a breaking bug in 0.0.33, but it's the missing glob dependency I believe. (https://github.com/angular/angular-cli/issues/469).

I'm not sure what the configstore issue is, but it seems to be a `ember-cli` dependency instead of `angular-cli`... which, together with the `broccoli-merge-trees` missing dependency and the sudo requirement makes me think it is either a permissions or a failed npm install issue because both of which can cause missing files inside of packages.

The best advice I can give is to check out https://docs.npmjs.com/getting-started/fixing-npm-permissions and also doing `npm cache clean`.
