### ISSUE TITLE
Fresh project gives error on ng serve

### ISSUE THREAD

**Issue by MaxMaes** [angular/angular-cli#4864]
### OS?
> Windows 10.

### Versions.
> ng --version

> @angular/cli: 1.0.0-beta.32.3
> node: 7.1.0
> os: win32 x64
> @angular/common: 2.4.8
> @angular/compiler: 2.4.8
> @angular/core: 2.4.8
> @angular/forms: 2.4.8
> @angular/http: 2.4.8
> @angular/platform-browser: 2.4.8
> @angular/platform-browser-dynamic: 2.4.8
> @angular/router: 3.4.8
> @angular/cli: 1.0.0-beta.32.3
> @angular/compiler-cli: 2.4.8

### Repro steps.
> npm install -g @angular/cli
> ng new someproject
> ng serve

### The log given by the failure.
> ng serve output:
```
ng serve
** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 4/5 modules 1 active ...lient\index.js?http://localhost:4200/(node:21524) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with geevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at defaultHandler (D:\Udemy\first-app\node_modules\webpack\lib\ProgressPlugin.js:175:18)
    at Compiler.<anonymous> (D:\Udemy\first-app\node_modules\webpack\lib\ProgressPlugin.js:130:4)
    at Compiler.applyPlugins (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:61:14)
    at Watching._done (D:\Udemy\first-app\node_modules\webpack\lib\Compiler.js:91:17)
    at onCompiled (D:\Udemy\first-app\node_modules\webpack\lib\Compiler.js:50:17)
    at D:\Udemy\first-app\node_modules\webpack\lib\Compiler.js:480:13
    at next (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:138:11)
    at Compiler.<anonymous> (D:\Udemy\first-app\node_modules\webpack\lib\CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:142:13)
    at D:\Udemy\first-app\node_modules\webpack\lib\Compiler.js:477:10
    at Compilation.applyPluginsAsyncSeries (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:131:46)
    at self.applyPluginsAsync.err (D:\Udemy\first-app\node_modules\webpack\lib\Compilation.js:640:19)
    at next (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.<anonymous> (D:\Udemy\first-app\node_modules\webpack\lib\ProgressPlugin.js:122:5)
    at Compilation.applyPluginsAsyncSeries (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:142:13)
    at self.applyPluginsAsync.err (D:\Udemy\first-app\node_modules\webpack\lib\Compilation.js:631:11)
    at next (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.<anonymous> (D:\Udemy\first-app\node_modules\webpack\lib\ProgressPlugin.js:118:5)
    at Compilation.applyPluginsAsyncSeries (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:142:13)
    at self.applyPluginsAsync.err (D:\Udemy\first-app\node_modules\webpack\lib\Compilation.js:626:10)
    at next (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.<anonymous> (D:\Udemy\first-app\node_modules\webpack\lib\ProgressPlugin.js:114:5)
    at next (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:140:14)
    at ExtractTextPlugin.<anonymous> (D:\Udemy\first-app\node_modules\extract-text-webpack-plugin\index.js:329:4)
    at Compilation.applyPluginsAsyncSeries (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:142:13)
    at sealPart2 (D:\Udemy\first-app\node_modules\webpack\lib\Compilation.js:622:9)
    at next (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.<anonymous> (D:\Udemy\first-app\node_modules\webpack\lib\ProgressPlugin.js:110:5)
    at next (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:140:14)
    at ExtractTextPlugin.<anonymous> (D:\Udemy\first-app\node_modules\extract-text-webpack-plugin\index.js:305:5)
    at D:\Udemy\first-app\node_modules\async\dist\async.js:359:16
    at iteratorCallback (D:\Udemy\first-app\node_modules\async\dist\async.js:935:13)
    at D:\Udemy\first-app\node_modules\async\dist\async.js:843:16
    at D:\Udemy\first-app\node_modules\extract-text-webpack-plugin\index.js:289:6
    at D:\Udemy\first-app\node_modules\async\dist\async.js:359:16
    at iteratorCallback (D:\Udemy\first-app\node_modules\async\dist\async.js:935:13)
    at D:\Udemy\first-app\node_modules\async\dist\async.js:843:16
    at D:\Udemy\first-app\node_modules\extract-text-webpack-plugin\index.js:286:13
    at D:\Udemy\first-app\node_modules\async\dist\async.js:3025:16
    at eachOfArrayLike (D:\Udemy\first-app\node_modules\async\dist\async.js:940:9)
    at eachOf (D:\Udemy\first-app\node_modules\async\dist\async.js:990:5)
    at Object.eachLimit (D:\Udemy\first-app\node_modules\async\dist\async.js:3089:3)
    at D:\Udemy\first-app\node_modules\extract-text-webpack-plugin\index.js:260:11
    at D:\Udemy\first-app\node_modules\async\dist\async.js:3025:16
    at eachOfArrayLike (D:\Udemy\first-app\node_modules\async\dist\async.js:940:9)
    at eachOf (D:\Udemy\first-app\node_modules\async\dist\async.js:990:5)
    at Object.eachLimit (D:\Udemy\first-app\node_modules\async\dist\async.js:3089:3)
    at ExtractTextPlugin.<anonymous> (D:\Udemy\first-app\node_modules\extract-text-webpack-plugin\index.js:257:10)
    at Compilation.applyPluginsAsyncSeries (D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:142:13)
    at Compilation.seal (D:\Udemy\first-app\node_modules\webpack\lib\Compilation.js:570:8)
    at D:\Udemy\first-app\node_modules\webpack\lib\Compiler.js:474:16
    at D:\Udemy\first-app\node_modules\tapable\lib\Tapable.js:225:11
    at _addModuleChain (D:\Udemy\first-app\node_modules\webpack\lib\Compilation.js:472:11)
    at processModuleDependencies.err (D:\Udemy\first-app\node_modules\webpack\lib\Compilation.js:443:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> This was a fresh install of the CLI and a new generated project, so I don't know what I could be doing wrong here :(
> I setup a Linux VM and everything works just fine there.

**Comment by MaxMaes** [comment]
Fixed it by updating my Node.JS from 7.1.0 to 7.5.0
