### ISSUE TITLE
Cannot find module 'glob' in newly generated project

### ISSUE THREAD

**Issue by cgmartin** [angular/angular-cli#492]
Seeing an issue with a newly generated project:
```
$ ng build
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
BuildingCould not require 'angular-cli-build.js': Cannot find module 'glob'
Error: Could not require 'angular-cli-build.js': Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/cmartin/tmp/ngclitest/node_modules/angular-cli/lib/broccoli/angular2-app.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Mac OSX El Capitan
Angular CLI Version: latest master e5237f2f4f2cd040d493e30b647ee7343d6938bc
Node: 4.4.2
NPM: 2.14.21

Repro steps:
```
$ git clone https://github.com/angular/angular-cli.git
$ cd angular-cli
$ git checkout e5237f2f4f2cd040d493e30b647ee7343d6938bc
$ npm i
$ npm link
$ cd /tmp
$ ng new ngclitest
$ cd ngclitest
$ ng test  # shows error
$ ng build # shows error
```

Workaround:
```
$ cd ngclitest # inside newly built project
$ npm i glob
$ ng test  # no error
$ ng build # no error
```

**Comment by Brocco** [comment]
`glob` was a dev dependency but has been moved to be a full dependency. This will be in the next release, you can find the correcting commit [here](https://github.com/angular/angular-cli/commit/9481790f3387edb38870c52d73338abfd105fae8)

**Comment by cgmartin** [comment]
I have that commit, but the error still seems to be occurring. 

It is as if `ng` is trying to import from the local working directory in the new project, rather than from angular-cli's installed dependencies.

**Comment by Brocco** [comment]
In your steps above you have this:

``` bash
$ git clone https://github.com/angular/angular-cli.git
$ cd angular-cli
$ git checkout e5237f2f4f2cd040d493e30b647ee7343d6938bc
$ npm i
$ npm link
$ cd /tmp
$ ng new ngclitest
$ cd ngclitest
$ ng test  # shows error
$ ng build # shows error
```

So you're using a local version of angular-cli, but you are not telling that repo to use that local version:
``` bash
$ git clone https://github.com/angular/angular-cli.git
$ cd angular-cli
$ git checkout e5237f2f4f2cd040d493e30b647ee7343d6938bc
$ npm i
$ npm link
$ cd /tmp
$ ng new ngclitest
$ cd ngclitest

# this is the step you're missing
$ npm link angular-cli
$ ng test  # shows error
$ ng build # shows error
```

**Comment by cgmartin** [comment]
Aha! I did not expect that the globally installed (linked) command would require from the local project dependency context. That seems odd to me, but thank you!

**Comment by cgmartin** [comment]
On second thought, I understand the convenience/utility of managing the version of angular-cli within each project by way of calling the globally installed `ng` bin. Carry on. :)
