### ISSUE TITLE
Importing internal project error

### ISSUE THREAD

**Issue by victorschinaider** [angular/angular-cli#4923]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Ubuntu 16.04

### Versions.
1.0.0-beta.30

### Repro steps.
Hi, guys.

Well, i'm developing a project with angular cli. So, there was a moment that we need to separate the project in a subproject (only with the models of project) to share with other project that will use the same classes. So, i created a new project in internal git...

**Folder of subproject:**
```
src 
test
index.ts ( content below )
index.js ( compiled file from index.ts )
index.d.ts (Typescript definition file)
...
```

**index.ts:** file that is importing some 'class' files of models.
```typescript
export * from './src/core';
export * from './src/models';
```

So, in the **main project**, we're putting in `package.json` the **git path** to the project, to import. So, when we give `npm install`, the sub-project is imported perfect, all right.

But, in a component, when we try to `import`...

```typescript
import {  ...  } from 'myproject'
``` 
In visual studio code, autocompletion shows all the classes, but when we're trying to use the class, angular is returning an error:

```
lang.js:130Angular is running in the development mode. Call enableProdMode() to enable the production mode.
[Violation] Long running JavaScript task took 388ms
error_handler.js:54 EXCEPTION: Uncaught (in promise): Error: Unexpected value 'StartPageModule' imported by the module 'VerbaModule'
Error: Unexpected value 'StartPageModule' imported by the module 'VerbaModule'
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7241:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75492:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6717:16)
    at http://localhost:4200/vendor.bundle.js:19864:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:19849:49)
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:55156:64)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:55116:52)
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:55082:21)
    at ModuleBoundCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:55548:31)
    at http://localhost:4200/vendor.bundle.js:83029:60
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6613:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:32190:37)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6612:32)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6409:43)
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
error_handler.js:60 Error: Uncaught (in promise): Error: Unexpected value 'StartPageModule' imported by the module 'VerbaModule'
Error: Unexpected value 'StartPageModule' imported by the module 'VerbaModule'
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7241:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75492:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6717:16)
    at http://localhost:4200/vendor.bundle.js:19864:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:19849:49)
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:55156:64)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:55116:52)
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:55082:21)
    at ModuleBoundCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:55548:31)
    at http://localhost:4200/vendor.bundle.js:83029:60
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6613:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:32190:37)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6612:32)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6409:43)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:6926:31) [angular]
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:6902:17) [angular]
    at http://localhost:4200/polyfills.bundle.js:6962:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:32181:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6645:36) [angular]
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6449:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:6812:35) [<root>]
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
zone.js:516 Unhandled Promise rejection: Unexpected value 'StartPageModule' imported by the module 'VerbaModule' ; Zone: angular ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Unexpected value 'StartPageModule' imported by the module 'VerbaModule'
    at SyntaxError.Zo…, _nativeError: ZoneAwareError, __zone_symbol__stack: "Error: Unexpected value 'StartPageModule' imported…ttp://localhost:4200/polyfills.bundle.js:6409:43)", __zone_symbol__message: "Unexpected value 'StartPageModule' imported by the module 'VerbaModule'"} Error: Unexpected value 'StartPageModule' imported by the module 'VerbaModule'
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7241:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75492:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6717:16)
    at http://localhost:4200/vendor.bundle.js:19864:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:19849:49)
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:55156:64)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:55116:52)
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:55082:21)
    at ModuleBoundCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:55548:31)
    at http://localhost:4200/vendor.bundle.js:83029:60
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6613:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:32190:37)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6612:32)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6409:43)
consoleError @ zone.js:516
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
zone.js:518 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: Unexpected value 'StartPageModule' imported by the module 'Verb…, rejection: SyntaxError, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask…}
consoleError @ zone.js:518
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
```

It's a strange message, because the 'modules' said in the log have no problems when we remove the import of the subproject. It's like the imported subproject is influencing theses modules.

- **Any one have an ideia to resolve this case?**
- **Is there a correct mode to create subprojects. like this. and import it?**

**Comment by victorschinaider** [comment]
Sorry for that, it was resolved.
The problem was with the name of the project/folder, that aren't the same.
