### ISSUE TITLE
run e2e throws er activeevents.js

### ISSUE THREAD

**Issue by ChuckDuncan47** [angular/angular-cli#4931]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
@angular/cli: 1.0.0-beta.32.3
node: 6.9.5
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Freshly created app... no additions or changes.
npm run start   ... success
npm run lint     ... no issues
npm run test    ... runs correctly
npm run e2e    ... error shown here
C:\CSWebNg>npm run e2e

> csweb-ng@0.0.0 e2e C:\CSWebNg
> ng e2e

** NG Live Development Server is running on http://localhost:4200. **
 10% building modules 3/3 modules 0 activeevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:4200
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! csweb-ng@0.0.0 e2e: `ng e2e`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csweb-ng@0.0.0 e2e script 'ng e2e'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the csweb-ng package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng e2e
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs csweb-ng
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls csweb-ng
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\CSWebNg\npm-debug.log

C:\CSWebNg>

### The log given by the failure.
> Normally this include a stack trace and some more information.
C:\CSWebNg>type npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle csweb-ng@0.0.0~pree2e: csweb-ng@0.0.0
6 silly lifecycle csweb-ng@0.0.0~pree2e: no script for pree2e, continuing
7 info lifecycle csweb-ng@0.0.0~e2e: csweb-ng@0.0.0
8 verbose lifecycle csweb-ng@0.0.0~e2e: unsafe-perm in lifecycle true
9 verbose lifecycle csweb-ng@0.0.0~e2e: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\CSWebNg\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files (x86)\WinMerge;C:\Users\chuck\AppData\Local\Microsoft\WindowsApps;C:\Users\chuck\AppData\Roaming\npm
10 verbose lifecycle csweb-ng@0.0.0~e2e: CWD: C:\CSWebNg
11 silly lifecycle csweb-ng@0.0.0~e2e: Args: [ '/d /s /c', 'ng e2e' ]
12 silly lifecycle csweb-ng@0.0.0~e2e: Returned: code: 1  signal: null
13 info lifecycle csweb-ng@0.0.0~e2e: Failed to exec e2e script
14 verbose stack Error: csweb-ng@0.0.0 e2e: `ng e2e`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid csweb-ng@0.0.0
16 verbose cwd C:\CSWebNg
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error csweb-ng@0.0.0 e2e: `ng e2e`
22 error Exit status 1
23 error Failed at the csweb-ng@0.0.0 e2e script 'ng e2e'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the csweb-ng package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng e2e
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs csweb-ng
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls csweb-ng
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

C:\CSWebNg>

### Mention any other details that might be useful.
Thanks for building such a fantastic tool .. I sincerely love it.
Chuck
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ChuckDuncan47** [comment]
MY ERROR ... I accidentally already had the port open in another browser.  My apologies .. I will close this now.
