### ISSUE TITLE
Uncaught (in promise): RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by angheladrianclaudiu** [angular/angular-cli#4935]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
>  1.0.0-beta.18

### Repro steps.
> I am using angular cli 1.0.0-beta.18 to build my project and I managed it to do so. However I have a problem when I try to add a component with a footer tag like this one below:

```
<footer class="bg-lightgray footer">
	This is a footer
</footer>
```

The code builds successfully, but when I load the application in the browser I encounter the following error:

### The log given by the failure.
> EXCEPTION: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Object.b (http://localhost:8080/main.0bb6247c680b7b4eb016.bundle.js:1135:2679)
    at Object.a (http://localhost:8080/main.0bb6247c680b7b4eb016.bundle.js:1660:322)
    at Object.ViewEncapsulation (http://localhost:8080/main.0bb6247c680b7b4eb016.bundle.js:1:3046)
    at t.createViewRoot (http://localhost:8080/main.0bb6247c680b7b4eb016.bundle.js:736:1926)
    at _View_t0.createInternal (/t/t/component.ngfactory.js:12:40)
    at _View_t0.t.create (http://localhost:8080/main.0bb6247c680b7b4eb016.bundle.js:1709:1281)
    at _View_t0.createInternal (/t/t/component.ngfactory.js:20:14)
    at _View_t0.t.create (http://localhost:8080/main.0bb6247c680b7b4eb016.bundle.js:1709:1281)
    at _View_t0.createInternal (/t/t/component.ngfactory.js:20:14)
    at _View_t0.t.create (http://localhost:8080/main.0bb6247c680b7b4eb016.bundle.js:1709:1281)

### This is my package.json content:

```
{
  "name": "myapp",
  "version": "1.0.0",
  "license": "CC",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
	"prod": "ng build -prod",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "bootstrap": "3.3.7",
    "jquery": "2.1.4",
	"flexslider": "2.6.3",
	"jquery.easing": "1.4.1",
	"magnific-popup": "1.1.0",
	"jquery-sticky": "1.0.4",
	"owl.carousel": "2.2.0",
	"parsleyjs": "2.6.2",
	"themify-icons": "1.0.0"
  },
  "devDependencies": {
    "@types/jasmine": "2.2.30",
    "@types/node": "6.0.42",
    "angular-cli": "1.0.0-beta.18",
    "codelyzer": "1.0.0-beta.1",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.0.2",
    "karma-remap-istanbul": "0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.3"
  }
}

```
### angular-cli.json
```
{
  "project": {
    "version": "1.0.0",
    "name": "eventpromoter-website"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "../webapp",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.css",
		"assets/styles/themify-icons.css",
		"../node_modules/flexslider/flexslider.css",
		"../node_modules/owl.carousel/dist/assets/owl.carousel.css",
		"../node_modules/owl.carousel/dist/assets/owl.theme.default.min.css",
		"../node_modules/magnific-popup/dist/magnific-popup.css",
        "assets/styles/styles.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
		"../node_modules/jquery.easing/jquery.easing.js",
		"../node_modules/jquery-sticky/jquery.sticky.js",
		"../node_modules/flexslider/jquery.flexslider.js",
		"../node_modules/owl.carousel/dist/owl.carousel.min.js",
		"../node_modules/magnific-popup/dist/jquery.magnific-popup.min.js",
		"../node_modules/bootstrap/dist/js/bootstrap.min.js",
		"../node_modules/parsleyjs/dist/parsley.min.js",
		"assets/js/app.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}

```
### tsconfig.json
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}

```
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
This seems like an Angular bug itself, and your CLI is really old. Please update to the latest Angular and CLI and try again. If you cannot update Angular itself, please file a bug on http://gitHub.com/angular/angular.
