### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by markrozencwajg** [angular/angular-cli#4940]
1) MacOS Sierra 10.12.3
2)
`@angular/cli: 1.0.0-beta.32.3 [1.0.0-beta.17]
node: 7.4.0
os: darwin x64
@angular/common: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler: 2.4.8
@angular/compiler-cli: 2.4.8
@angular/platform-server: 2.4.8
@ngtools/webpack: 1.2.4`

3) App was created using old cli angular-cli (I have taken the steps to upgrade including uninstalling globally, removing node_modules, etc)
Converting existing production Angular 2 application to compile using AOT using the following doc: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#bootstrap
I can successfully compile without errors now running `node_modules/.bin/ngc -p tsconfig-aot.json`
Trying to make this work with angular cli, recently upgraded packages and cli. Tried uninstalling, cleaning npm cache, uninstalling global packages, etc.
4)
`Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/node_modules/@angular/cli/node_modules/typescript/lib/typescript.js:14552:109)
    at parseSourceFileWorker (/node_modules/@angular/cli/node_modules/typescript/lib/typescript.js:14484:26)
    at Object.parseSourceFile (/node_modules/@angular/cli/node_modules/typescript/lib/typescript.js:14433:26)
    at Object.createSourceFile (/node_modules/@angular/cli/node_modules/typescript/lib/typescript.js:14288:29)
    at new TypeScriptFileRefactor (/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/refactor.js:30:35)
    at Object.resolveEntryModuleFromMain (/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/entry_resolver.js:104:20)
    at AotPlugin._setupOptions (/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:135:50)
    at new AotPlugin (/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:22:14)
    at _createAotPlugin (/node_modules/@angular/cli/models/webpack-configs/typescript.js:54:12)
    at Object.exports.getNonAotConfig (/node_modules/@angular/cli/models/webpack-configs/typescript.js:80:13)
    at new NgCliWebpackConfig (/node_modules/@angular/cli/models/webpack-config.js:24:37)
    at Class.run (/node_modules/@angular/cli/tasks/build.js:24:31)
    at Class.run (/node_modules/@angular/cli/commands/build.js:63:26)
    at Class.<anonymous> (/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

5)
angular-cli.json
`{
  "project": {
    "version": "1.0.0-beta.17",
    "name": ""
  },
  "apps": [
    {
      "root": "src",
      "outDir": "public",
      "assets": ["assets"],
      "index": "index.html",
      "main": "src/main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.qa.ts",
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "qa": "environments/environment.qa.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "sass",
    "prefixInterfaces": false
  }
}`
tsconfig-aot.json
`{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "outDir": "../dist/out-aot"
  },

  "files": [
    "app/app.module.ts",
    "main.ts"
  ],

  "angularCompilerOptions": {
   "genDir": "aot",
   "skipMetadataEmit" : true
 }
}
`
tsconfig.json
`{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}`
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by markrozencwajg** [comment]
Error in angular-cli.json in "main" path

**Comment by istiti** [comment]
@markrozencwajg same error how you solved ? i have no error in my .angular-cli.json file

**Comment by Schwobaland** [comment]
@istiti wrong main path here too - in case of ionic it should be`"main": "app/main.ts",`

**Comment by stephenad** [comment]
Hi Folks, getting the same error:

`Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:8887:109)
    at parseSourceFileWorker (C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:8817:26)
    at Object.parseSourceFile (C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:8776:26)
    at Object.createSourceFile (C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:8635:29
    at WebpackCompilerHost.getSourceFile (C:\wamp\www\public_cli\node_modules\@ngtools\webpack\src\compi
    at findSourceFile (C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:45687:29)
    at processSourceFile (C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:45618:27)
    at processRootFile (C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:45522:13)
    at C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:44987:60
    at Object.forEach (C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:1101:30)
    at Object.createProgram (C:\wamp\www\public_cli\node_modules\typescript\lib\typescript.js:44987:16)
    at AotPlugin._setupOptions (C:\wamp\www\public_cli\node_modules\@ngtools\webpack\src\plugin.js:138:2
    at new AotPlugin (C:\wamp\www\public_cli\node_modules\@ngtools\webpack\src\plugin.js:27:14)
    at Object.exports.getNonAotConfig (C:\wamp\www\public_cli\node_modules\angular-cli\models\webpack-co
    at new NgCliWebpackConfig (C:\wamp\www\public_cli\node_modules\angular-cli\models\webpack-config.js:
    at Class.run (C:\wamp\www\public_cli\node_modules\angular-cli\tasks\serve.js:31:29)
    at C:\wamp\www\public_cli\node_modules\angular-cli\commands\serve.run.js:22:22
    at process._tickCallback (internal/process/next_tick.js:109:7)`

angular-cli.json

`{
  "project": {
    "version": "1.0.0-beta.21",
    "name": "ngi-app"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
       "styles": [
        "styles.css"
        ],
      "scripts": [],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts",
        "e2e": "environments/environments.e2e.ts"        
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}`

package.json
`{
  "name": "ngi-app",
  "version": "2.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.3.1",
    "@angular/compiler": "2.3.1",
    "@angular/core": "2.3.1",
    "@angular/forms": "2.3.1",
    "@angular/http": "2.3.1",
    "@angular/platform-browser": "2.3.1",
    "@angular/platform-browser-dynamic": "2.3.1",
    "@angular/router": "3.3.1",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.22",
    "angular2-cookie": "^1.2.5",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.4.0",
    "core-js": "^2.4.1",
    "ng2-bs3-modal": "^0.10.4",
    "ng2-charts": "1.4.1",
    "ng2-file-upload": "1.1.4-2",
    "ng2-pagination": "1.0.1",
    "ng2-toastr": "1.3.2",
    "rxjs": "5.3.0",
    "ts-helpers": "^1.1.1",
    "ts-xlsx": "0.0.11",
    "zone.js": "0.7.2",    
    "swig": "1.4.2",
    "tls": "0.0.1",
    "uuid": "3.0.1",
    "winston": "2.3.1",
    "winston-daily-rotate-file": "1.4.6",
    "@types/file-saver": "0.0.1",
    "@types/jspdf": "1.1.31",
    "@types/lodash": "4.14.50",
    "@types/xlsx": "0.0.34",
    "angular-datatables": "2.3.0",
    "angular2-select": "1.0.0-beta.3",
    "angular2-toaster": "3.0.1",
    "aws-sdk": "2.46.0",
    "body-parser": "1.17.1",
    "child_process": "1.0.2",
    "cors": "2.8.3",
    "crypto": "0.0.3",
    "datatables.net": "1.10.13",
    "datatables.net-dt": "1.10.13",
    "exec": "0.2.1",
    "express": "4.15.2",
    "file-saver": "1.3.3",
    "fs": "0.0.1-security",
    "https": "1.0.0",
    "jquery": "3.2.1",
    "json2csv": "3.7.3",
    "jspdf": "1.3.3",
    "jspdf-autotable": "2.3.2",
    "lodash": "4.17.4",
    "moment": "2.18.1",
    "moment-timezone": "0.5.13",
    "multer": "1.3.0",
    "mysql": "2.13.0",
    "ng2-bootstrap": "1.6.1",
    "ng2-bs-dropdown": "0.7.0",
    "ng2-datepicker": "1.8.3",
    "ng2-slimscroll": "1.3.2",
    "ng2-validation": "3.9.1",
    "ng2-validators": "2.1.1",
    "node-cron": "1.1.3",
    "nodemailer": "4.0.1",
    "rand-token": "0.3.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.3.1",
    "@types/datatables.net": "1.10.1",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "2.0.41",
    "@types/moment": "2.13.0",
    "@types/moment-timezone": "0.2.34",
    "@types/node": "^6.0.42",
    "angular-2-dropdown-multiselect": "1.0.8",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.0.2",
    "karma-remap-istanbul": "0.2.1",
     "nodemon": "1.11.0",
    "protractor": "4.0.13",
    "ts-node": "1.2.1",
    "tslint": "4.3.0",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5",
    "webpack": "^3.4.1"   
  }
}`

Any advice appreciated

**Comment by stephenad** [comment]
Ok solved this issue, in my tsconfig.json

under ""files": [ I had a reference to the ng2-table.ts file that did not exist in the location specified"

Thanks
