### ISSUE TITLE
Error on ng serve

### ISSUE THREAD

**Issue by justtal** [angular/angular-cli#50]
Hey,

After ng new sample-project I ran ng serve and I get this error:

version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
2015-10-23 22:51 angular-cli[7740] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-10-23 22:51 angular-cli[7740] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-10-23 22:51 angular-cli[7740] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch EMFILE
    at exports._errnoException (util.js:837:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1222:26)

**Comment by justtal** [comment]
--- Update ---

After I reboot my mac the error gone.

**Comment by IgorMinar** [comment]
looks like a file descriptor issue or an issue with your `fsevents` package - did the compilation of `fsevents` during `npm install -g angular-cli` fail?

**Comment by pinalbhatt** [comment]
Installing watchman `brew install watchman`  resolved my "Could not find watchman, falling back to NodeWatcher for file system events." error but sill getting 
Could not require 'angular-cli-build.js': Cannot find module 'glob'
Error: Could not require 'angular-cli-build.js': Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pinal.bhatt/Projects/cli/newProj/node_modules/angular-cli/lib/broccoli/angular2-app.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by pinalbhatt** [comment]
install glob `npm install glob` solved the issue.

**Comment by Brocco** [comment]
This has been resolved with PR #473 and will be included in the next release.
