### ISSUE TITLE
ng generate enum throws error

### ISSUE THREAD

**Issue by jasedwards** [angular/angular-cli#5018]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.10.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8

### Repro steps.
run ng generate enum [name] 

### The log given by the failure.
TypeError: Cannot read property '0' of undefined
    at Object.getAppFromConfig (C:\code\Angular2\dashboards\node_modules\@angular\cli\utilities\app-utils.js:4:19)
    at Class.normalizeEntityName (C:\code\Angular2\dashboards\node_modules\@angular\cli\blueprints\enum\index.js:18:39)
    at Class.Blueprint._normalizeEntityName (C:\code\Angular2\dashboards\node_modules\@angular\cli\ember-cli\lib\models\blueprint.js:454:24)
    at Class.Blueprint.install (C:\code\Angular2\dashboards\node_modules\@angular\cli\ember-cli\lib\models\blueprint.js:513:8)
    at Class.run (C:\code\Angular2\dashboards\node_modules\@angular\cli\ember-cli\lib\tasks\generate-from-blueprint.js:59:49)
    at Class.run (C:\code\Angular2\dashboards\node_modules\@angular\cli\ember-cli\lib\commands\generate.js:71:17)
    at Class.<anonymous> (C:\code\Angular2\dashboards\node_modules\@angular\cli\ember-cli\lib\models\command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Mention any other details that might be useful.

ran this as admin in cmder, cmd and git bash with same results

**Comment by clydin** [comment]
did you provide a name as an argument?  It should require one.  If not, the error message should definitely be improved.

**Comment by waiholiu** [comment]
I'm getting the same error and I am running it with a name as an argument.

I think it's failing in the file packages/@angular/cli/utilities/app-utils.ts on line 4
let app = apps[0];
the apps variable is undefined, possibly because the packages/@angular/cli/lib/config/schema.json file has not configured enum properly.

Unfortunately I don't know enough how the cli works to be able to be able to offer a fix or to be more help.

**Comment by jasedwards** [comment]
Apologies.  I did provide a name.  I have updated my previous comment

**Comment by Brocco** [comment]
I will take a look at this, thanks for reporting.

**Comment by m-ghaoui** [comment]
+1
