### ISSUE TITLE
polyfills error on edge and ie11

### ISSUE THREAD

**Issue by lmsac** [angular/angular-cli#5086]
### OS?
Windows 10. 

### Versions.
```
@angular/cli: 1.0.0-rc.0
node: 6.10.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8
```

### Repro steps.
Browser polyfills in `polyfills.ts` were all uncommented, and were installed with npm following the instructions.
`ng serve` and `ng build` succeeded, and the app works with Chrome 46, but failed on Edge 25.10586.672.0 (EdgeHTML 13.10586) and IE 11.713.10586.0.

### The log given by the failure.
> Normally this include a stack trace and some more information.
```
Unhandled Promise rejection: Object doesn't support property or method 'push' ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Object doesn't support property or method 'push' TypeError: Object doesn't support property or method 'push'
   at g (http://localhost:4200/polyfills.bundle.js:5558:6172)
   at j (http://localhost:4200/polyfills.bundle.js:5558:7328)
   at g (http://localhost:4200/polyfills.bundle.js:5557:11362)
   at e (http://localhost:4200/polyfills.bundle.js:5557:10307)
   at b.convertEffectInput (http://localhost:4200/polyfills.bundle.js:5557:10509)
   at b.KeyframeEffect (http://localhost:4200/polyfills.bundle.js:5557:12873)
   at window.Element.prototype.animate (http://localhost:4200/polyfills.bundle.js:5557:15867)
   at window.Element.prototype.animate (http://localhost:4200/polyfills.bundle.js:5558:12401)
   at WebAnimationsPlayer.prototype._triggerWebAnimation (http://localhost:4200/vendor.bundle.js:127946:9)
   at WebAnimationsPlayer.prototype.init (http://localhost:4200/vendor.bundle.js:127930:9)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:85975:102)
   at Array.prototype.forEach (native code)
   at AnimationSequencePlayer.prototype.init (http://localhost:4200/vendor.bundle.js:85975:60)
   at AnimationSequencePlayer.prototype.play (http://localhost:4200/vendor.bundle.js:85995:13)
   at AnimationQueue.prototype._triggerAnimations (http://localhost:4200/vendor.bundle.js:85875:17)
polyfills.bundle.js (3671,13)
   "Unhandled Promise rejection:"
   "Object doesn't support property or method 'push'"
   "; Zone:"
   "<root>"
   "; Task:"
   "Promise.then"
   "; Value:"
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'push'",
      message: "Object doesn't support property or method 'push'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'push'
   at g (http://localhost:4200/polyfills.bundle.js:5558:6172)
   at j (http://localhost:4200/polyfills.bundle.js:5558:7328)
   at g (http://localhost:4200/polyfills.bundle.js:5557:11362)
   at e (http://localhost:4200/polyfills.bundle.js:5557:10307)
   at b.convertEffectInput (http://localhost:4200/polyfills.bundle.js:5557:10509)
   at b.KeyframeEffect (http://localhost:4200/polyfills.bundle.js:5557:12873)
   at window.Element.prototype.animate (http://localhost:4200/polyfills.bundle.js:5557:15867)
   at window.Element.prototype.animate (http://localhost:4200/polyfills.bundle.js:5558:12401)
   at WebAnimationsPlayer.prototype._triggerWebAnimation (http://localhost:4200/vendor.bundle.js:127946:9)
   at WebAnimationsPlayer.prototype.init (http://localhost:4200/vendor.bundle.js:127930:9)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:85975:102)
   at Array.prototype.forEach (native code)
   at AnimationSequencePlayer.prototype.init (http://localhost:4200/vendor.bundle.js:85975:60)
   at AnimationSequencePlayer.prototype.play (http://localhost:4200/vendor.bundle.js:85995:13)
   at AnimationQueue.prototype._triggerAnimations (http://localhost:4200/vendor.bundle.js:85875:17)"
   }
   "TypeError: Object doesn't support property or method 'push'
   at g (http://localhost:4200/polyfills.bundle.js:5558:6172)
   at j (http://localhost:4200/polyfills.bundle.js:5558:7328)
   at g (http://localhost:4200/polyfills.bundle.js:5557:11362)
   at e (http://localhost:4200/polyfills.bundle.js:5557:10307)
   at b.convertEffectInput (http://localhost:4200/polyfills.bundle.js:5557:10509)
   at b.KeyframeEffect (http://localhost:4200/polyfills.bundle.js:5557:12873)
   at window.Element.prototype.animate (http://localhost:4200/polyfills.bundle.js:5557:15867)
   at window.Element.prototype.animate (http://localhost:4200/polyfills.bundle.js:5558:12401)
   at WebAnimationsPlayer.prototype._triggerWebAnimation (http://localhost:4200/vendor.bundle.js:127946:9)
   at WebAnimationsPlayer.prototype.init (http://localhost:4200/vendor.bundle.js:127930:9)
   at Anonymous function (http://localhost:4200/vendor.bundle.js:85975:102)
   at Array.prototype.forEach (native code)
   at AnimationSequencePlayer.prototype.init (http://localhost:4200/vendor.bundle.js:85975:60)
   at AnimationSequencePlayer.prototype.play (http://localhost:4200/vendor.bundle.js:85995:13)
   at AnimationQueue.prototype._triggerAnimations (http://localhost:4200/vendor.bundle.js:85875:17)"
```

### Mention any other details that might be useful.
The app uses `@angular/material: 2.0.0-beta.2`. The error was thrown when mouse-over elements with tooltip, and the tooltip didn't hide when mouse-leave.

**Comment by filipesilva** [comment]
I think you should open this in https://github.com/angular/material2 repo. The CLI is just building your app, and the build itself was successful.
