### ISSUE TITLE
cannot run any ng command after installation 

### ISSUE THREAD

**Issue by i-am-dror** [angular/angular-cli#5092]
Drors-MacBook-Pro:management-ui dror$ ng
/usr/local/lib/node_modules/@angular/cli/bin/ng:94
  const hasOldDep = !!packageJsonProject.dependencies['angular-cli'];
                                                     ^

TypeError: Cannot read property 'angular-cli' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/bin/ng:94:54)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
macOS Sierra (10.12.3)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
node v7.5.0
npm 4.2.0

Drors-MacBook-Pro:management-ui dror$ ng --version
/usr/local/lib/node_modules/@angular/cli/bin/ng:94
  const hasOldDep = !!packageJsonProject.dependencies['angular-cli'];
                                                     ^

TypeError: Cannot read property 'angular-cli' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/bin/ng:94:54)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.
TypeError: Cannot read property 'angular-cli' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/bin/ng:94:54)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dertuerke** [comment]
same issue

**Comment by i-am-dror** [comment]
figured it out
I had to add dependencies & devDependencies to my package.json

**Comment by sporritt** [comment]
@i-am-dror to which package.json?  If this error occurs when you run `ng` does that not indicate an issue with Angular cli?

For me I get this error on a fresh install when i run `ng new`.  

#### OS

Mac El Capitan

#### Versions

```
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: darwin x64
@angular/compiler: 2.4.9
@angular/compiler-cli: 2.4.9
@angular/core: 2.4.9
@angular/tsc-wrapped: 0.5.2
@ngtools/json-schema: 1.0.5
@ngtools/webpack: 1.2.11
```

#### Log

```
ng new test

/usr/local/share/npm/lib/node_modules/@angular/cli/bin/ng:94
  const hasOldDep = !!packageJsonProject.dependencies['angular-cli'];
                                                     ^

TypeError: Cannot read property 'angular-cli' of undefined
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/@angular/cli/bin/ng:94:54)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
```

**Comment by sporritt** [comment]
...oh i see, right.  for anyone else who comes across this: `ng` looks for a `package.json` in the file system by recursively traversing up directories:

```
const packageJsonProjectPath = findUp('package.json', process.cwd(), true);
```

It doesn't _need_ to find one, but if it does find one, it checks to see if you're using an old version of Angular CLI so it can warn you.

In my case the `package.json` did not have a `dependencies` section, and the ng cli code looked like this:

```
const hasOldDep = !!packageJsonProject.dependencies['angular-cli'];
```

The code in Github now looks like this:

```
const deps = packageJsonProject['dependencies'] || {};
const hasOldDep = !!deps['angular-cli'];
```

so this error wont occur now.
