### ISSUE TITLE
Upgrade guide for rc.0 and e2e failure

### ISSUE THREAD

**Issue by czterocyty** [angular/angular-cli#5104]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Max OSX Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
$ ng --version
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8
@angular/platform-server: 2.4.8
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

According to migration guide: https://github.com/angular/angular-cli/wiki/stories-rc.0-update there is a step in E2E configuration:

> Then update protractor.conf.js to use the e2e config as well:
> 
> beforeLaunch: function() {
>  require('ts-node').register({
>    project: 'e2e'
>  });
> },

### The log given by the failure.
> Normally this include a stack trace and some more information.

When running ng e2e following error appeared:

```
TypeError: Cannot find a tsconfig.json file at the specified directory: e2e
    at resolveSync (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/tsconfig/src/tsconfig.ts:71:11)
    at Object.loadSync (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/tsconfig/src/tsconfig.ts:142:16)
    at readConfig (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/ts-node/src/index.ts:424:18)
    at load (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/ts-node/src/index.ts:192:20)
    at service (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/ts-node/src/index.ts:370:32)
    at Object.register (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/ts-node/src/index.ts:379:5)
    at beforeLaunch (/Users/adomanski/IdeaProjects/fax-webapp/protractor.conf.js:24:24)
    at q_1.Promise (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/protractor/lib/util.ts:48:39)
    at Function.promise (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/q/q.js:682:9)
    at Object.runFilenameOrFn_ (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/protractor/lib/util.ts:39:10)
    at Object.initFn [as init] (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/protractor/lib/launcher.ts:111:10)
    at promise.then (/Users/adomanski/IdeaProjects/fax-webapp/node_modules/@angular/cli/tasks/e2e.js:45:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Mention any other details that might be useful.

I had to change this to:

```
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
  },
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by royling** [comment]
duplicated with #5082

**Comment by sumitarora** [comment]
Updated docs: https://github.com/angular/angular-cli/wiki/stories-rc.0-update#protractorconfjs
