### ISSUE TITLE
Cannot use ng

### ISSUE THREAD

**Issue by rahulkumar66** [angular/angular-cli#5133]
> Please provide us with the following information:

### OS?
> Ubuntu 16.04

### Versions.
> node version v7.4.0

### Repro steps.
> ng command doesn't work even ng --help doesn't work.
I installed the latest cli using npm install -g @angular/cli and tried to serve been getting this error ever since, i even tried creating a new project using ng new myapp

### The log given by the failure.
> Parsing .angular-cli.json failed. Please make sure your .angular-cli.json is valid JSON. Error:
SyntaxError: Unexpected token < in JSON at position 0
InvalidConfigError: Parsing .angular-cli.json failed. Please make sure your .angular-cli.json is valid JSON. Error:
SyntaxError: Unexpected token < in JSON at position 0
    at Function.fromConfigPath (/usr/local/lib/node_modules/@angular/cli/models/config/config.js:71:19)
    at Function.fromGlobal (/usr/local/lib/node_modules/@angular/cli/models/config.js:37:46)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/commands/build.js:7:71)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Class.includedCommands (/usr/local/lib/node_modules/@angular/cli/addon/index.js:22:16)
    at /usr/local/lib/node_modules/@angular/cli/ember-cli/lib/models/project.js:287:61
    at Array.forEach (native)
    at Project.addonCommands (/usr/local/lib/node_modules/@angular/cli/ember-cli/lib/models/project.js:286:15)
    at Project.eachAddonCommand (/usr/local/lib/node_modules/@angular/cli/ember-cli/lib/models/project.js:321:30)
    at module.exports (/usr/local/lib/node_modules/@angular/cli/ember-cli/lib/cli/lookup-command.js:33:13)
    at CLI.<anonymous> (/usr/local/lib/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:46:26)
    at tryCatch (/usr/local/lib/node_modules/@angular/cli/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/usr/local/lib/node_modules/@angular/cli/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/usr/local/lib/node_modules/@angular/cli/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/usr/local/lib/node_modules/@angular/cli/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by MortimerCat** [comment]
The clue is in the error
```
Parsing .angular-cli.json failed. Please make sure your .angular-cli.json is valid JSON. Error:
SyntaxError: Unexpected token < in JSON at position 0
```
Have a look at your angular-cli.json  It should be JSON and not contain "<". It looks like you have some html accidentally pasted into it.

**Comment by rahulkumar66** [comment]
You don't understand there is no file angular-cli.json when executing ng new myapp even ng --version doesn't work

**Comment by clydin** [comment]
There can be a global config in your home directory.  Can you confirm its presence, or lack thereof?  Also please provide its contents if applicable.  Or if it does exist, simply try removing the offending file.

**Comment by rahulkumar66** [comment]
Thanks issue solved.
There was a angular-cli.json inside my home folder that was causing the issue.
