### ISSUE TITLE
Running "ng" causes "Unexpected token ..."

### ISSUE THREAD

**Issue by aplocher** [angular/angular-cli#5150]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?

Xubuntu Zesty 17.04 / 4.10.0 kernel

### Versions.

node --version: 5.8.0

### Repro steps.

Running "ng" or "ng new" or "ng --version" or any variation of "ng" causes the error

### The log given by the failure.

$ ng --version
/usr/local/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/schema-class-factory.js:48
    constructor(schema, value, ...fallbacks) {
                               ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/@ngtools/json-schema/src/index.js:3:30)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

### Mention any other details that might be useful.
Fresh install, first time playing with Angular 2, can't seem to use the CLI tool.  Thanks!

**Comment by hansl** [comment]
We only support Node 6.9 and above. The last version to support Node 4 was in `angular-cli`.

**Comment by ganhb** [comment]
It is work! Thank U very much

**Comment by Seankps** [comment]
@hansl I'm glad I found this so I could know that I needed to update node. I'm just curious why doesn't it throw an error saying node needs to be updated? If we know the minimum required Node version for ng, shouldn't ng also know and check for that?

**Comment by EmpeRoar** [comment]
Thanks. Update Node 4 to 6 fixed the issue

**Comment by sonamsdiwate1983** [comment]
I was also facing same issue. Thank you

**Comment by sankya** [comment]
D:\C Drive\Angular\ts-hello\main.ts:2
import { LikesComponent } from './like.component';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
