### ISSUE TITLE
ng generate enum is broken

### ISSUE THREAD

**Issue by FabienDehopre** [angular/angular-cli#5165]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10.

### Versions.
```
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: win32 x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8
```

### Repro steps.
`ng g enum models/enum-name`

### The log given by the failure.
```
installing enum
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at Object.getAppFromConfig (C:\Users\f.dehopre\devs\Portal\new\node_modules\@angular\cli\utilities\app-utils.js:4:19)
    at Class.normalizeEntityName (C:\Users\f.dehopre\devs\Portal\new\node_modules\@angular\cli\blueprints\enum\index.js:18:39)
    at Class.Blueprint._normalizeEntityName (C:\Users\f.dehopre\devs\Portal\new\node_modules\@angular\cli\ember-cli\lib\models\blueprint.js:454:24)
    at Class.Blueprint.install (C:\Users\f.dehopre\devs\Portal\new\node_modules\@angular\cli\ember-cli\lib\models\blueprint.js:513:8)
    at Class.run (C:\Users\f.dehopre\devs\Portal\new\node_modules\@angular\cli\ember-cli\lib\tasks\generate-from-blueprint.js:59:49)
    at Class.run (C:\Users\f.dehopre\devs\Portal\new\node_modules\@angular\cli\ember-cli\lib\commands\generate.js:71:17)
    at Class.<anonymous> (C:\Users\f.dehopre\devs\Portal\new\node_modules\@angular\cli\ember-cli\lib\models\command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by sumitarora** [comment]
@FabienDehopre Did you create new app or used it on an existing app created in previous version of CLI?

**Comment by FabienDehopre** [comment]
It's an app created with the RC0.

**Comment by cvharris** [comment]
Same here. App was ported to RC0 from earlier version but migrated according to docs

**Comment by filipesilva** [comment]
Uhm I just tried this myself, and it doesn't seem to happen on RC2. 
```
kamik@T460p MINGW64 /D/sandbox/master-project (master)
$ ng g enum models/enum-name
installing enum
  create src\app\models\enum-name.enum.ts
```

Are you still getting this? It might have been incidentally fixed.

**Comment by FabienDehopre** [comment]
Indeed, enums are generated correctly on RC2.

**Comment by sumitarora** [comment]
Closing as above comments.
