### ISSUE TITLE
Problem running "ng" after forking Angular CLI

### ISSUE THREAD

**Issue by JamieBenefex** [angular/angular-cli#5179]
### OS?
Windows 10

### Versions.
1.0.0-rc.0

### Repro steps.
1. Fork Angular CLI repo
2. `npm install https://github.com/{{private-repo}}/angular-cli.git -g`
3. Running `ng` in a command line produces an error

### The log given by the failure.
```
$ ng
module.js:514
    if (content.charCodeAt(0) === 35/*#*/ &&
                ^

TypeError: content.charCodeAt is not a function
    at Module._compile (module.js:514:17)
    at Object.require.extensions..ts (C:\Users\jamieread\AppData\Roaming\npm\node_modules\@angular\cli\lib\bootstrap-local.js:23:14)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jamieread\AppData\Roaming\npm\node_modules\@angular\cli\packages\@angular\cli\bin\ng:7:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by sumitarora** [comment]
@JamieBenefex you don't need to install it globally you can just use `npm link` in the directory you cloned and it should work. Make sure you uninstall any version you have previously installed globally. Check this: https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli

**Comment by filipesilva** [comment]
Closing as answered.

**Comment by bradringel** [comment]
I'm seeing this same issue after forking the cli project, and then using my forked repo as the value in package.json
