### ISSUE TITLE
Cannot read property 'create' of undefined when building with --prod or --aot

### ISSUE THREAD

**Issue by johnwalshuk** [angular/angular-cli#5181]
### Overview of the Issue
Application runs fine when running from `ng serve` and `ng build` but if i try `ng build --prod` or `ng build --prod --aot` then i an uncaught type error.

### OS?
Windows 10

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.9.2
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.9

### Repro steps.
Project was started in beta-22. I've read the upgrade instructions for rc.0 and implemented them.
As soon as the tag `--prod` or `--aot` is used I get the console log.

### The log given by the failure.
Uncaught TypeError: Cannot read property 'create' of undefined
    at vendor.8b35183….bundle.js:formatted:25358
    at t.invoke (polyfills.6f91569….bundle.js:36)
    at Object.onInvoke (vendor.8b35183….bundle.js:formatted:6924)
    at t.invoke (polyfills.6f91569….bundle.js:36)
    at e.run (polyfills.6f91569….bundle.js:36)
    at t.run (vendor.8b35183….bundle.js:formatted:6827)
    at e._bootstrapModuleFactoryWithZone (vendor.8b35183….bundle.js:formatted:25353)
    at e.bootstrapModuleFactory (vendor.8b35183….bundle.js:formatted:25345)
    at Object.Iksp (main.a726c89….bundle.js:1)
    at r (inline.6377e42….bundle.js:1)
    at Object.kke6 (main.a726c89….bundle.js:1)
    at r (inline.6377e42….bundle.js:1)
    at Object.x35b (main.a726c89….bundle.js:1)
    at r (inline.6377e42….bundle.js:1)
    at Object.0 (main.a726c89….bundle.js:1)

**Comment by leolorenzoluis** [comment]
What was your solution? I'm getting the same but different stack trace.

```
   at e.project (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:5:6015)
    at e._next (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:6:14080)
    at e.next (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:2:5283)
    at e.notifyNext (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:6:15660)
    at e._next (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:20:8698)
    at e.next (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:2:5283)
    at Object.r [as subscribeToResult] (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:12:10783)
    at e._innerSub (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:6:15388)
    at e._tryNext (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:6:15321)
    at e._next (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:6:15144)
    at e.next (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:2:5283)
    at http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:15:6867
    at t.invoke (http://localhost:3000/polyfills.0831a14565bc151aa4f1.bundle.js:2:27404)
    at Object.onInvoke (http://localhost:3000/vendor.880d5d1f9e87d63acc75.bundle.js:3:3884)
    at t.invoke (http://localhost:3000/polyfills.0831a14565bc151aa4f1.bundle.js:2:27344)
```

**Comment by ctrl-brk** [comment]
I had something similar. Try to delete the entire node_modules folder and run npm install again.

**Comment by johnwalshuk** [comment]
It was `platformBrowserDynamic().bootstrapModule(XX);`, I just created a new project from the CLI and checked out each file to ensure it matches the latest cli generation. I followed the change doc's but it was best to just generate a new project and compare side-by-side. Hope that helps

**Comment by mautrok** [comment]
> I had something similar. Try to delete the entire node_modules folder and run npm install again

I had try, same results, and i tried to compare my package.json with a new (working) project, but nothing, is it possible to know what's the real problem?

**Comment by shurvirmori** [comment]
I also have same problem, but no solution found till. :cry:  :unamused: 

```
Uncaught TypeError: Cannot read property 'create' of undefined
    at vendor.dc3218a….bundle.js:1
    at e.invoke (polyfills.8eba0ab….bundle.js:1)
    at Object.onInvoke (vendor.dc3218a….bundle.js:1)
    at e.invoke (polyfills.8eba0ab….bundle.js:1)
    at r.run (polyfills.8eba0ab….bundle.js:1)
    at e.run (vendor.dc3218a….bundle.js:1)
    at t._bootstrapModuleFactoryWithZone (vendor.dc3218a….bundle.js:1)
    at t.bootstrapModuleFactory (vendor.dc3218a….bundle.js:1)
    at Object.cDNt (main.8407c32….bundle.js:1)
    at n (inline.dfd4ad8….bundle.js:1)
```

**Comment by molikh** [comment]
@johnwalshuk  thanks my problem fixed with this change

**Comment by frontalnh** [comment]
i found a solution!!

the code
"platformBrowserDynamic().bootstrapModule(AppModule);"
was wrote twice in both file main.ts and app.module.ts

just delete "platformBrowserDynamic().bootstrapModule(AppModule);" in the app.module.ts file!

**Comment by tiberiumihai** [comment]
I defined basepath in my environment files and used it for translations like this:
```
...
useFactory: (http: HttpClient) => new TranslateHttpLoader(http, environment.basepath + 'assets/i18n/', '.json'),
...
```
I change it to:
```
const BASE_PATH = environment.basepath;

...
useFactory: (http: HttpClient) => new TranslateHttpLoader(http, BASE_HREF + 'assets/i18n/', '.json'),
...
```
and is working fine now.

**Comment by Amadeo** [comment]
> module

Thank you!!! That solved my problem!!!!

**Comment by prakasa-tkpd** [comment]
> const BASE_HREF = environment.basepath;

what a relation between defining `const BASE_HREF = environment.basepath;` and undefined create error ?
