### ISSUE TITLE
Error: Cannot find module '../../../utilities/find-up'

### ISSUE THREAD

**Issue by alxhotel** [angular/angular-cli#5187]
### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux Ubuntu 16.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```module.js:471
    throw err;
    ^

Error: Cannot find module '../../../utilities/find-up'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/alex/node_modules/@angular/cli/packages/@angular/cli/ember-cli/lib/models/project.js:8:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

For `node --version`:

```
v6.10.0
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Install the last version of `angular-cli`: `v1.0.0-rc.0`

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
module.js:471
    throw err;
    ^

Error: Cannot find module '../../../utilities/find-up'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/alex/node_modules/@angular/cli/packages/@angular/cli/ember-cli/lib/models/project.js:8:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by sumitarora** [comment]
@alxhotel Did you follow the updating guide? https://github.com/angular/angular-cli#updating-angular-cli

**Comment by alxhotel** [comment]
@sumitarora Yep. Same error.

**Comment by filipesilva** [comment]
It really looks like you have a broken install somewhere. I can't reproduce this myself either.

**Comment by alxhotel** [comment]
Running this command fixed my problem:

```
rm -rf ~/node_modules/@angular
```

**Comment by crunchypencil** [comment]
Nope. I've been getting this error consistently. Reinstalled Node. Reinstalled Angular CLI
Windows 10
