### ISSUE TITLE
live reload breaks webpack when using typings (in lazy loaded module)

### ISSUE THREAD

**Issue by emreavsar** [angular/angular-cli#5266]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
El Capitan

### Versions.
@angular/cli: 1.0.0-rc.0

### Repro steps.
Add typings to the project as follows:
package.json:
```
{
  "scripts": {
    ...
    "install": "typings install"
  }
...
  dependencies: {
...
    "typings": "^2.1.0",
...
  }
}
```

typings.json:
```
{
  "globalDependencies": {
    "typings": "github:t4deon/FHIR-STU3-TS-Typings/typings.d.ts#e36b4cf4bb07734b97ea8d14893f7747fd990438"
  }
}
```

src/tsconfig.app.json:
```
...
{
  "files": [
    "../typings/index.d.ts"
  ]
}
```

Then (regardless wether the typings are used in the project or not):

 1. start the app with `ng serve` -> 👍  works
2. go into a lazy loaded module's code and just drop some new lines somewhere, so that livereload kicks in
3. face the error 👎 
4. Do the same change in code inside a **non lazy loaded module** does not reproduce this problem.

### The log given by the failure.
```
Failed to compile.
./src/app/home/signup/personal-gln-form/personal-gln-form.component.ts
Module build failed: Error
    at WebpackCompilerHost.populateWebpackResolver (/Users/emre/projects/eviprev-it/eviprev-dossier-frontend/node_modules/@ngtools/webpack/src/compiler_host.js:135:51)
    at _donePromise.Promise.resolve.then.then.then.then (/Users/emre/projects/eviprev-it/eviprev-dossier-frontend/node_modules/@ngtools/webpack/src/plugin.js:327:32)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/home/signup/signup.module.ts 17:0-91
 @ ./src async
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Mention any other details that might be useful.

1. I cannot use the @types npm repo, since the typings are not registered there, so I need to install by `typings install`
2. Initial issue and discussions were made here: https://github.com/angular/angular-cli/issues/4326

**Comment by emreavsar** [comment]
One more note:
Working with `@types` works, but the typings I use are not in the npm repo, search: https://microsoft.github.io/TypeSearch/)

**Comment by Darshan-popin** [comment]
Same here i'm using node v6.10.0 , @emreavsar  any workarounds you have found ??

**Comment by MyracleDesign** [comment]
There is no activity here since February, let's close this issue for now and re-open if needed.

**Comment by MyracleDesign** [comment]
Could you give some feedback if this problem is still an issue?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
