### ISSUE TITLE
i18n - Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by sudha-tup** [angular/angular-cli#5286]
Hello, I tried to create a sample application and implement ng18n following the steps in https://angular.io/docs/ts/latest/cookbook/i18n.html#. But I get an error when trying to create the translation source file.

**OS**
Windows 7

- @angular/cli: 1.0.0-rc.1
- node: 6.10.0
- os: win32 x64
- @angular/common: 2.4.9
- @angular/compiler: 2.4.9
- @angular/compiler-cli: 2.4.9
- @angular/core: 2.4.9
- @angular/forms: 2.4.9
- @angular/http: 2.4.9
- @angular/platform-browser: 2.4.9
- @angular/platform-browser-dynamic: 2.4.9
- @angular/platform-server: 2.4.9
- @angular/router: 3.4.9
- @angular/cli: 1.0.0-rc.1

$ npm -v
4.3.0

**### Repro steps**

1. Created a new application using CLI –> ng new hello-i18n
2. Add i18n attribute to text. I replaced `<h1>{{title}}</h1>` with `<h1 i18n="User welcome|An introduction header for this sample">Hello i18n!</h1>` in app.component.html. This is per the instruction in the Angular Docs page.
3. Updated semver for the below devdependencies, to get latest versions, and did npm update. Looks like all the packages got installed in node_modules

- Typescript			~2.0.0 --> ^2.0.0
- Tslint				~4.4.2 --> ^4.4.2
- ts-node				~2.0.0 --> ^2.0.0
- karma				~1.4.1 --> ^1.4.1
- codelyzer			~2.0.0 --> ^2.0.0
- @types/node			~6.0.60 --> ^7.0.0
- @types/jasmine		~2.5.38 --> ^2.5.38

4. npm ls --depth=0 shows no errors
5. Installed a couple of dependencies using command - npm install @angular/compiler-cli @angular/platform-server –save. This is per the instruction in the Angular Docs page.
6. npm ls --depth=0 shows no errors, npm ls -g --depth=0 shows no errors
7. Executed command per Angular docs page – “./node_modules/.bin/ng-xi18n”  (Note: If the tsconfig.json  file is located somewhere other than in root folder, you must identify the path to it with the -p option. CLI created the tsconfig.json  file for me in root)
8. Got error: Error: Error encountered resolving symbol values statically. Calling function 'NoOpAnimationDriver'
9. Per https://github.com/angular/angular-cli/issues/3868, added "exclude": [ "test.ts" ] to tsconfig.json
10. Error: Error encountered resolving symbol values statically. Expression form not supported (position 18:4 in the original .ts file), resolving symbol AppModule in C:/Users/skandasamy/GitWorkspace/hello-i18n/node_modules/@angular/cli/blueprints/ng/files/__path__/app/app.module.ts
    at positionalError (C:\Users\skandasamy\GitWorkspace\hello-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25944:39)
    at simplifyInContext (C:\Users\skandasamy\GitWorkspace\hello-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25781:31)
    at StaticReflector.simplify (C:\Users\skandasamy\GitWorkspace\hello-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25795:17)
    at StaticReflector.annotations (C:\Users\skandasamy\GitWorkspace\hello-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25291:64)
    at NgModuleResolver.resolve (C:\Users\skandasamy\GitWorkspace\hello-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:17771:86)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\skandasamy\GitWorkspace\hello-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:18272:64)
    at addNgModule (C:\Users\skandasamy\GitWorkspace\hello-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25053:62)
    at C:\Users\skandasamy\GitWorkspace\hello-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25064:18
    at Array.forEach (native)
    at _createNgModules (C:\Users\skandasamy\GitWorkspace\hello-i18n\node_modules\@angular\compiler\bundles\compiler.umd.js:25063:30)
Extraction failed

**Comment by sudha-tup** [comment]
I was able to resolve the above issue by pointing to the path of the tsconfig.app.json file. Angular docs mentions that we need to point to the path of the tsconfig.json file. But I see two files being generated - tsconfig.json and tsconfig.app.json. And if I provide the path option, and point to the tsconfig.app.json file, it works.

Command used: ./node_modules/.bin/ng-xi18n -p src/tsconfig.app.json
