### ISSUE TITLE
ng build doesn't work when bootstrapping with UpgradeAdapter 

### ISSUE THREAD

**Issue by gt11879** [angular/angular-cli#5303]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/compiler-cli: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/platform-server: 2.4.5
@angular/router: 3.4.5
@angular/tsc-wrapped: 0.5.2
@angular/upgrade: 2.4.5
@angular/cli: 1.0.0-rc.1

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
1. Quickstart app downloaded
2. in main.ts bootstrapping using ngUpgrade instead of platformBrowserDynamic
3. run ng build

### The log given by the failure.
> Normally this include a stack trace and some more information.

C:\projects\Rounding\Rounding.Mobile.Web\www>ng build
Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
Error: Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.
    at Object.resolveEntryModuleFromMain (C:\projects\Rounding\Rounding.Mobile.Web\www\node_modules\@ngtools\webpack\src\entry_resolver.js:118:15)
    at AotPlugin._setupOptions (C:\projects\Rounding\Rounding.Mobile.Web\www\node_modules\@ngtools\webpack\src\plugin.js:138:50)
    at new AotPlugin (C:\projects\Rounding\Rounding.Mobile.Web\www\node_modules\@ngtools\webpack\src\plugin.js:23:14)
    at _createAotPlugin (C:\projects\Rounding\Rounding.Mobile.Web\www\node_modules\@angular\cli\models\webpack-configs\typescript.js:55:12)
    at Object.exports.getNonAotConfig (C:\projects\Rounding\Rounding.Mobile.Web\www\node_modules\@angular\cli\models\webpack-configs\typescript.js:70:19)
    at NgCliWebpackConfig.buildConfig (C:\projects\Rounding\Rounding.Mobile.Web\www\node_modules\@angular\cli\models\webpack-config.js:27:37)
    at Class.run (C:\projects\Rounding\Rounding.Mobile.Web\www\node_modules\@angular\cli\tasks\build.js:26:92)
    at Class.run (C:\projects\Rounding\Rounding.Mobile.Web\www\node_modules\@angular\cli\commands\build.js:143:26)
    at Class.<anonymous> (C:\projects\Rounding\Rounding.Mobile.Web\www\node_modules\@angular\cli\ember-cli\lib\models\command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by scottlepp** [comment]
@gt11879 add this to the bottom of main.ts for a workaround. It appears the build process validates/scans for platformBrowserDynamic but never uses it.

@NgModule({
  declarations: [],
  imports: [],
  providers: [],
  bootstrap: []
})
export class BlankModule {
}

const load = false;
if (load) {
  platformBrowserDynamic().bootstrapModule(BlankModule);
}

**Comment by filipesilva** [comment]
I added an example of a working hybrid app in https://github.com/angular/angular-cli/issues/6124.

**Comment by scottlepp** [comment]
@filipesilva thanks for your example, but it doesn't use the UpgradeAdapter as defined here (you're using the Upgrade Module).  https://angular.io/docs/ts/latest/api/upgrade/index/UpgradeAdapter-class.html

**Comment by filipesilva** [comment]
That documentation is actually in flux, which `upgrade/static` soon becoming the recommended way.
