### ISSUE TITLE
ng serve -prod failing

### ISSUE THREAD

**Issue by Jonatthu** [angular/angular-cli#5307]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 and Mac OSX Yosemite

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here: 
```
@angular/cli: 1.0.0-rc.1
node: 6.9.2
os: win32 x64
@angular/common: 4.0.0-rc.2
@angular/compiler: 4.0.0-rc.2
@angular/core: 4.0.0-rc.2
@angular/forms: 4.0.0-rc.2
@angular/http: 4.0.0-rc.2
@angular/platform-browser: 4.0.0-rc.2
@angular/platform-browser-dynamic: 4.0.0-rc.2
@angular/router: 4.0.0-rc.2
@angular/flex-layout: 2.0.0-rc.1
@angular/material: 2.0.0-beta.2
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 4.0.0-rc.2
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
ng serve -prod

### The log given by the failure.
> Normally this include a stack trace and some more information.
```
** NG Live Development Server is running on http://localhost:4200 **
 20% building modules 87/87 modules 0 activeTemplate parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[ERROR ->]<template><div class="mat-autocomplete-panel" role="listbox" [id]="id" [ngClass]="_getClassList()" #p"): MdAutocomplete@0:0
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("<cdk-focus-trap>[ERROR ->]<template cdkPortalHost></template></cdk-focus-trap>"): MdDialogContainer@0:16
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[ERROR ->]<template><div class="mat-menu-panel" [ngClass]="_classList" (keydown)="_keyManager.onKeydown($event)"): MdMenu@0:0
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("span> </span><span class="mat-select-arrow"></span> <span class="mat-select-underline"></span></div>[ERROR ->]<template cdk-connected-overlay [origin]="origin" [open]="panelOpen" hasBackdrop (backdropClick)="clo"): MdSelect@0:511
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[ERROR ->]<template cdkPortalHost></template>"): MdSnackBarContainer@0:0
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("[ERROR ->]<template><ng-content></ng-content></template>"): MdTab@0:0
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("]="selectedIndex == i" [disabled]="tab.disabled" (click)="tabHeader.focusIndex = selectedIndex = i">[ERROR ->]<template [ngIf]="tab.templateLabel"><template [cdkPortalHost]="tab.templateLabel"></template></templ"): MdTabGroup@0:531
The <template> element is deprecated. Use <ng-template> instead ("b.disabled" (click)="tabHeader.focusIndex = selectedIndex = i"><template [ngIf]="tab.templateLabel">[ERROR ->]<template [cdkPortalHost]="tab.templateLabel"></template></template><template [ngIf]="!tab.templateLa"): MdTabGroup@0:568
The <template> element is deprecated. Use <ng-template> instead ("late [ngIf]="tab.templateLabel"><template [cdkPortalHost]="tab.templateLabel"></template></template>[ERROR ->]<template [ngIf]="!tab.templateLabel">{{tab.textLabel}}</template></div></md-tab-header><div class="m"): MdTabGroup@0:636
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("eTab.start)="_onTranslateTabStarted($event)" (@translateTab.done)="_onTranslateTabComplete($event)">[ERROR ->]<template cdkPortalHost></template></div>"): MdTabBody@0:205
 86% hashingcrypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\dependencies\HarmonyExportImportedSpecifierDependency.js:144:8)
    at C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\Module.js:162:41)
    at NormalModule.updateHash (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\NormalModule.js:327:30)
    at modules.forEach.m (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\Chunk.js:253:16)
    at Compilation.createHash (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\Compilation.js:1121:10)
    at sealPart2 (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\Compilation.js:605:9)
    at next (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.<anonymous> (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\ProgressPlugin.js:110:5)
    at next (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\tapable\lib\Tapable.js:140:14)
    at ExtractTextPlugin.<anonymous> (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\extract-text-webpack-plugin\index.js:305:5)
    at C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\async\dist\async.js:359:16
    at iteratorCallback (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\async\dist\async.js:935:13)
    at C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\async\dist\async.js:843:16
    at C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\extract-text-webpack-plugin\index.js:289:6
    at C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\async\dist\async.js:359:16
    at iteratorCallback (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\async\dist\async.js:935:13)
    at C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\async\dist\async.js:843:16
    at C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\extract-text-webpack-plugin\index.js:279:9
    at rebuilding.forEach.cb (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\Compilation.js:495:29)
    at Array.forEach (native)
    at callback (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\Compilation.js:495:15)
    at processModuleDependencies (C:\Users\jnungaray\Source\Repos\Mapwords\Mapwords\Mapwords.App\Client\node_modules\webpack\lib\Compilation.js:514:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
Is this failing for the warnings ?
Because this is the material2 package from angular and I can not modify it

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Jonatthu** [comment]
My bad, Was a bad import on my index.ts but there was no clear error message
