### ISSUE TITLE
EPIPE errors when running ng e2e

### ISSUE THREAD

**Issue by burkel24** [angular/angular-cli#5313]
> Please provide us with the following information:
> ---------------------------------------------------------------

My protractor specs intermittently fail with `Error: EPIPE write EPIPE`

### OS?
OS X 10.12.3

### Versions.
@angular/cli: 1.0.0-rc.0
node: 7.2.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.8
protractor: 5.1.1

### Repro steps.
- run `ng e2e --proxy-config proxy.conf.json`
- Steps 'randomly' fail

proxy.conf.json:
```
{
  "/api": {
    "target": "http://localhost:3000",
    "secure": false
  }
}
```

protractor.conf.js:
```
// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

/*global jasmine */
const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e'
    });
  },
  onPrepare() {
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  }
};
```

### The log given by the failure.
```
[16:34:07] E/launcher - Error: EPIPE write EPIPE
    at ClientRequest.<anonymous> (/Users/<user>/prog/website/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:346:10)
    at onwrite (_stream_writable.js:364:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:471:13)
    at Socket._destroy (net.js:512:3)
    at WriteWrap.afterWrite (net.js:806:10)
From: Task: WebDriver.findElements(By(css selector, pretty-checkbox[name="contract-checkbox"]))
    at Driver.schedule (/Users/<user>/prog/website/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at Driver.findElements (/Users/user>/prog/website/node_modules/selenium-webdriver/lib/webdriver.js:1057:22)
    at ptor.waitForAngular.then (/Users/<user>/prog/website/node_modules/protractor/lib/element.ts:166:36)
    at ManagedPromise.invokeCallback_ (/Users/<user>/prog/website/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/Users/<user>/prog/website/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/Users/<user>/prog/website/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/Users/<user>/prog/website/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /Users/<user>/prog/website/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
[16:34:07] E/launcher - Process exited with error code 199
```

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Please open this in https://github.com/angular/protractor instead. We use protractor but this isn't the right place to file problems with it.
