### ISSUE TITLE
ngc is not generating the WHOLE library

### ISSUE THREAD

**Issue by alvaro9210** [angular/angular-cli#5412]
### OS?
MacOS Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.26
node: 6.9.0
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/compiler-cli: 2.4.9
@ngtools/webpack: 1.2.13
```

### Repro steps.
ProjectA (carbonldp-panel): a bunch of modules exporting components, when compiled using ngc it generates the ngfactory and the dist folder (metadata.json and d.ts files) correctly. See: 
![qmeoyv](https://cloud.githubusercontent.com/assets/4240006/23885293/b054bbe4-0837-11e7-9f1e-b8e436143a3d.jpg)

ProjectB (carbonldp-workbench): The main project. It uses ProjectA as a `npm install`ed node dependency. When compiled, the compiler finishes but it doesn’t compile COMPLETELY the files from ProjectA (carbonldp-panel) See: 
![7rmlfa](https://cloud.githubusercontent.com/assets/4240006/23885313/cbe35a0a-0837-11e7-8fd6-b10657b4ccb2.jpg)

When trying to bundle the main project ProjectA Webpack throws the obvious message:
```
48% building modules 548/864 modules 316 active ...es/@angular/common/src/pipes/index.jsModuleNotFoundError: Module not found: Error: Can't resolve '/Users/base/carbonldp-workbench/compiled/node_modules/carbonldp-panel/my-apps/my-apps.module.ngfactory.ts' in '/Users/base/carbonldp-workbench/compiled'
```

### The log given by the failure.
```
48% building modules 548/864 modules 316 active ...es/@angular/common/src/pipes/index.jsModuleNotFoundError: Module not found: Error: Can't resolve '/Users/base22/Carbon/carbonldp-workbench/compiled/node_modules/carbonldp-panel/my-apps/my-apps.module.ngfactory.ts' in '/Users/base22/Carbon/carbonldp-workbench/compiled'
    at factoryCallback (/Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/lib/Compilation.js:259:39)
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/lib/NormalModuleFactory.js:126:20
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/node_modules/async/dist/async.js:3694:9
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/node_modules/async/dist/async.js:933:13)
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/node_modules/async/dist/async.js:843:16
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/node_modules/async/dist/async.js:3691:13
    at apply (/Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/node_modules/async/dist/async.js:21:25)
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/node_modules/async/dist/async.js:56:12
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/webpack/lib/NormalModuleFactory.js:121:22
    at onResolved (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/base22/Carbon/carbonldp-workbench/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/tapable/lib/Tapable.js:283:15
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
    at loggingCallbackWrapper (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/base22/Carbon/carbonldp-workbench/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /Users/base22/Carbon/carbonldp-workbench/node_modules/tapable/lib/Tapable.js:283:15
    at innerCallback (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
    at loggingCallbackWrapper (/Users/base22/Carbon/carbonldp-workbench/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
```

### Mention any other details that might be useful.
The tsconfig.json of ProjectA has these options:
```json
"angularCompilerOptions": {
	"genDir": "compiled",
	"skipTemplateCodegen": true
}
```
Also:
In ProjectA(carbonldp-panel), I did the following:

1.  Add the "skipTemplateCodegen": true to the angularCompilerOptions in tsconfig.json
2. Run ./node_modules/.bin/ngc -p tsconfig.json

In ProjectB(carbonldp-workbench):
1. `npm install`ed the ProjectB. See the packaged dependency: 
![zj2nua](https://cloud.githubusercontent.com/assets/4240006/23885286/a7adc508-0837-11e7-95d0-d89b6ad343ec.jpg)

2. Run `./node_modules/.bin/ngc -p tsconfig.json`

But the result is the same… it’s not generating ALL the files of ProjectB (carbobldp-panel)

Also:
The module erroring the project is being used with lazy loading like this:
```typescript
{
	path: "my-apps",
	loadChildren: "carbonldp-panel/my-apps/my-apps.module#MyAppsModule",
},
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Can you provide a simple repo highlighting this problem? 

I'm also not sure if this is a bug with the CLI or if it's a problem in your library packaging. Have you tried compiling your project without the CLI?

**Comment by filipesilva** [comment]
Closing as inactive.
