### ISSUE TITLE
Unable to Generate Component, View Encapsulation Undefined

### ISSUE THREAD

**Issue by Ckearns1210** [angular/angular-cli#5511]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.0.0-rc.2
node: 7.6.0
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.10
```

### Repro steps.
```
Run ng generate component [component name]
```

### The log given by the failure.
```
ReferenceError: viewEncapsulation is not defined (Error in blueprint template: /Users/Daily/dev/Shortcut-CLI/node_modules/@angular/cli/blueprints/component/files/__path__/__name__.component.ts)
    at eval (eval at <anonymous> (/Users/Daily/dev/Shortcut-CLI/node_modules/@angular/cli/node_modules/lodash/template.js:224:12), <anonymous>:9:5)
    at processTemplate (/Users/Daily/dev/Shortcut-CLI/node_modules/@angular/cli/ember-cli/lib/models/file-info.js:20:36)
    at /Users/Daily/dev/Shortcut-CLI/node_modules/@angular/cli/ember-cli/lib/models/file-info.js:97:20
    at tryCatch (/Users/Daily/dev/Shortcut-CLI/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/Daily/dev/Shortcut-CLI/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/Daily/dev/Shortcut-CLI/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/Users/Daily/dev/Shortcut-CLI/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
### Desired functionality.
```
Would like it to generate a component template.
```

### Mention any other details that might be useful.
Haven't been able to create a component in a new project due to error, have tried adding these lines to angular.cli.json: 
```
   "defaults": {
    "styleExt": "scss",
    "viewEncapsulation": "Emulated",
    "changeDetection": "Default"
  }
```
with no success.

**Comment by delasteve** [comment]
This should do the trick...

```json
"defaults": {
  "styleExt": "scss",
  "component": {
    "viewEncapsulation": "Emulated",
    "changeDetection": "Default"
  }
}
```

**Comment by Ckearns1210** [comment]
@delasteve that worked, thanks.
