### ISSUE TITLE
Bug: ng lint internal crash with Angular 4 rc5

### ISSUE THREAD

**Issue by eddy-geek** [angular/angular-cli#5520]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0-rc.0
node: 6.9.5
os: linux x64
**angular 4.0.0-rc.5**

### Repro steps.
I **couldn't reproduce** with `ng new ngcli-ng4 --ng4`. So feel free to close if the stack is not enough to investigate or if you feel like this is specific to my setup.

### The log given by the failure.
```
TypeError: this._staticSymbolCache.get is not a function
    at CompileMetadataResolver.getGeneratedClass (.../node_modules/@angular/compiler/bundles/compiler.umd.js:13295:48)
    at CompileMetadataResolver.getComponentViewClass (.../node_modules/@angular/compiler/bundles/compiler.umd.js:13306:25)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (.../node_modules/@angular/compiler/bundles/compiler.umd.js:13529:73)
    at CompileMetadataResolver._getEntryComponentMetadata (.../node_modules/@angular/compiler/bundles/compiler.umd.js:14156:49)
    at .../node_modules/@angular/compiler/bundles/compiler.umd.js:13731:57
    at Array.map (native)
    at CompileMetadataResolver.getNgModuleMetadata (.../node_modules/@angular/compiler/bundles/compiler.umd.js:13731:22)
    at addNgModule (.../node_modules/@angular/compiler/bundles/compiler.umd.js:22069:62)
    at .../node_modules/@angular/compiler/bundles/compiler.umd.js:22080:18
    at Array.forEach (native)
    at _createNgModules (.../node_modules/@angular/compiler/bundles/compiler.umd.js:22079:30)
    at Object.analyzeNgModules (.../node_modules/@angular/compiler/bundles/compiler.umd.js:21954:18)
    at ContextSymbols.getAnalyzedModules (.../node_modules/ngast/ngast.bundle.js:2284:35)
    at ContextSymbols.getModules (.../node_modules/ngast/ngast.bundle.js:2201:14)
    at ContextSymbols.getContextSummary (.../node_modules/ngast/ngast.bundle.js:2244:27)
    at ProjectSymbols.getLazyLoadedContexts (.../node_modules/ngast/ngast.bundle.js:2425:40)
    at Object.exports.parseTemplate (.../node_modules/codelyzer/angular/templates/contextAwareTemplateParser.js:21:35)
    at Ng2Walker.visitNg2Component (.../node_modules/codelyzer/angular/ng2Walker.js:119:64)
    at Ng2Walker.visitClassDeclaration (.../node_modules/codelyzer/angular/ng2Walker.js:50:18)
    at Ng2Walker.SyntaxWalker.visitNode (.../node_modules/tslint/lib/language/walker/syntaxWalker.js:311:22)
    at .../node_modules/tslint/lib/language/walker/syntaxWalker.js:530:63
    at visitEachNode (.../node_modules/typescript/lib/typescript.js:14209:30)
    at Object.forEachChild (.../node_modules/typescript/lib/typescript.js:14382:24)
    at Ng2Walker.SyntaxWalker.walkChildren (.../node_modules/tslint/lib/language/walker/syntaxWalker.js:530:12)
    at Ng2Walker.SyntaxWalker.visitSourceFile (.../node_modules/tslint/lib/language/walker/syntaxWalker.js:225:14)
    at Ng2Walker.SyntaxWalker.visitNode (.../node_modules/tslint/lib/language/walker/syntaxWalker.js:476:22)
    at Ng2Walker.SyntaxWalker.walk (.../node_modules/tslint/lib/language/walker/syntaxWalker.js:24:14)
    at Rule.AbstractRule.applyWithWalker (.../node_modules/tslint/lib/language/rule/abstractRule.js:50:16)
    at Rule.applyWithProgram (.../node_modules/codelyzer/noAccessMissingMemberRule.js:139:21)
    at Linter.applyRule (.../node_modules/tslint/lib/linter.js:138:37)
    at Linter.lint (.../node_modules/tslint/lib/linter.js:106:41)
    at files.forEach (.../node_modules/@angular/cli/tasks/lint.js:41:24)
    at Array.forEach (native)
    at lintConfigs.forEach (.../node_modules/@angular/cli/tasks/lint.js:34:19)
    at Array.forEach (native)
    at Class.run (.../node_modules/@angular/cli/tasks/lint.js:27:14)
    at Class.run (.../node_modules/@angular/cli/commands/lint.js:39:25)
    at Class.<anonymous> (.../node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
Multiple times, then at the end: `All files pass linting.` but I doubt it actually parsed the files...

### Desired functionality.
no crash.

### Mention any other details that might be useful.
`ng serve` and `ng test` work fine on the same project.

I am opening this because I feel like this is related to recent Angular 4 `RendererTypeV2 → RendererType2` rename in angular 4.0.0-rc.5 as per https://github.com/angular/angular/pull/14998

**Comment by sumitarora** [comment]
@eddy-geek Is it still issue with updated version of `Angular CLI`

**Comment by eddy-geek** [comment]
More recent versions are currently broken for me so I can't say, will try again with next rc

**Comment by eddy-geek** [comment]
I now get this error on ng lint (with and without `--type-check`)

```
Cannot read property '1' of undefined
TypeError: Cannot read property '1' of undefined
    at Rule.SelectorRule [as constructor] (.../node_modules/codelyzer/selectorNameBase.js:21:25)
    at new Rule (.../node_modules/codelyzer/directiveSelectorRule.js:16:47)
    at Object.loadRules (.../node_modules/tslint/lib/ruleLoader.js:47:32)
    at Linter.getEnabledRules (.../node_modules/tslint/lib/linter.js:184:44)
    at Linter.lint (.../node_modules/tslint/lib/linter.js:81:33)
    at files.forEach (.../node_modules/@angular/cli/tasks/lint.js:37:24)
    at Array.forEach (native)
    at lintConfigs.map (.../node_modules/@angular/cli/tasks/lint.js:30:19)
    at Array.map (native)
    at Class.run (.../node_modules/@angular/cli/tasks/lint.js:21:14)
```

Not sure if it deserves its own issue yet
