### ISSUE TITLE
Angular feature module: component export test fail

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular-cli#5657]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.1
os: darwin x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

### Repro steps.
1. Create new project using `ng new`
2. Create new module using `ng generate module test`
3. Create new component using `ng generate component test`
4. By now you should have component and module. Component TestComponent should be declared in TestModule like `declarations: [TestComponent]` and TestModule should be imported in AppModule
5. In TestModule export TestComponent like `exports: [TestComponent]`
6. Add `<app-test></app-test>` in app.component.html
7. Run ng serve - All good
8. Run ng test - ERROR: 'app-test' is not a known element

### The log given by the failure.
```        1. If 'app-test' is an Angular component, then verify that it is part of this module.
        2. If 'app-test' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<app-test></app-test>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (webpack:///~/@angular/compiler/@angular/compiler.es5.js:1503:21 <- src/test.ts:26389:34) [ProxyZone]
            at TemplateParser.Array.concat.TemplateParser.parse (webpack:///~/@angular/compiler/@angular/compiler.es5.js:11512:0 <- src/test.ts:36398:19) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler._compileTemplate (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25195:0 <- src/test.ts:50081:39) [ProxyZone]
            at webpack:///~/@angular/compiler/@angular/compiler.es5.js:25119:47 <- src/test.ts:50005:62 [ProxyZone]
            at Set.forEach (native) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler._compileComponents (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25119:0 <- src/test.ts:50005:19) [ProxyZone]
            at createResult (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25025:0 <- src/test.ts:49911:19) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler._compileModuleAndAllComponents (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25029:0 <- src/test.ts:49915:40) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler.compileModuleAndAllComponentsSync (webpack:///~/@angular/compiler/@angular/compiler.es5.js:24972:0 <- src/test.ts:49858:21) [ProxyZone]
            at TestingCompilerImpl.Array.concat.TestingCompilerImpl.compileModuleAndAllComponentsSync (webpack:///~/@angular/compiler/@angular/compiler/testing.es5.js:478:0 <- src/test.ts:52380:31
) [ProxyZone]
            at TestBed.Array.concat.TestBed._initIfNeeded (webpack:///~/@angular/core/@angular/core/testing.es5.js:704:0 <- src/test.ts:15209:36) [ProxyZone]
            at TestBed.Array.concat.TestBed.createComponent (webpack:///~/@angular/core/@angular/core/testing.es5.js:787:0 <- src/test.ts:15292:14) [ProxyZone]
            at Function.Array.concat.TestBed.createComponent (webpack:///~/@angular/core/@angular/core/testing.es5.js:609:0 <- src/test.ts:15114:29) [ProxyZone]
            at Object.<anonymous> (webpack:///src/app/app.component.spec.ts:27:28 <- src/test.ts:50734:41) [ProxyZone]
Chrome 56.0.2924 (Mac OS X 10.12.3): Executed 3 of 4 (3 FAILED) (0 secs / 0.105 secs)
Chrome 56.0.2924 (Mac OS X 10.12.3) AppComponent should render title in a h1 tag FAILED
        'app-test' is not a known element:
        1. If 'app-test' is an Angular component, then verify that it is part of this module.
        2. If 'app-test' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<app-test></app-test>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
        'app-test' is not a known element:
        1. If 'app-test' is an Angular component, then verify that it is part of this module.
        2. If 'app-test' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<app-test></app-test>"): ng:///DynamicTestModule/AppComponent.html@4:0
            at syntaxError (webpack:///~/@angular/compiler/@angular/compiler.es5.js:1503:21 <- src/test.ts:26389:34) [ProxyZone]
            at TemplateParser.Array.concat.TemplateParser.parse (webpack:///~/@angular/compiler/@angular/compiler.es5.js:11512:0 <- src/test.ts:36398:19) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler._compileTemplate (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25195:0 <- src/test.ts:50081:39) [ProxyZone]
            at webpack:///~/@angular/compiler/@angular/compiler.es5.js:25119:47 <- src/test.ts:50005:62 [ProxyZone]
            at Set.forEach (native) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler._compileComponents (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25119:0 <- src/test.ts:50005:19) [ProxyZone]
            at createResult (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25025:0 <- src/test.ts:49911:19) [ProxyZone]
            at AsyncTestZoneSpec.Array.concat.AsyncTestZoneSpec.onInvoke (webpack:///~/zone.js/dist/async-test.js:49:0 <- src/test.ts:51071:39) [ProxyZone]
            at ProxyZoneSpec.Array.concat.ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:76:0 <- src/test.ts:51759:39) [ProxyZone]
            at Zone.run (webpack:///~/zone.js/dist/zone.js:125:0 <- src/polyfills.ts:1280:43) [ProxyZone => ProxyZone]
            at webpack:///~/zone.js/dist/zone.js:760:0 <- src/polyfills.ts:1915:57 [ProxyZone]
        Error: Uncaught (in promise): Error: Template parse errors:
            at resolvePromise (webpack:///~/zone.js/dist/zone.js:712:0 <- src/polyfills.ts:1867:31) [ProxyZone]
            at resolvePromise (webpack:///~/zone.js/dist/zone.js:683:0 <- src/polyfills.ts:1838:17) [ProxyZone]
            at webpack:///~/zone.js/dist/zone.js:760:0 <- src/polyfills.ts:1915:17 [ProxyZone]
            at ProxyZoneSpec.Array.concat.ProxyZoneSpec.onInvokeTask (webpack:///~/zone.js/dist/proxy.js:103:0 <- src/test.ts:51786:39) [ProxyZone]
            at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:397:0 <- src/polyfills.ts:1552:36) [ProxyZone]
            at Zone.runTask (webpack:///~/zone.js/dist/zone.js:165:0 <- src/polyfills.ts:1320:47) [<root> => ProxyZone]
            at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:593:0 <- src/polyfills.ts:1748:35) [<root>]
        'app-test' is not a known element:
        1. If 'app-test' is an Angular component, then verify that it is part of this module.
        2. If 'app-test' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        </h1>
        [ERROR ->]<app-test></app-test>"): ng:///DynamicTestModule/AppComponent.html@4:0
        Error: Template parse errors:
            at syntaxError (webpack:///~/@angular/compiler/@angular/compiler.es5.js:1503:21 <- src/test.ts:26389:34) [ProxyZone]
            at TemplateParser.Array.concat.TemplateParser.parse (webpack:///~/@angular/compiler/@angular/compiler.es5.js:11512:0 <- src/test.ts:36398:19) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler._compileTemplate (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25195:0 <- src/test.ts:50081:39) [ProxyZone]
            at webpack:///~/@angular/compiler/@angular/compiler.es5.js:25119:47 <- src/test.ts:50005:62 [ProxyZone]
            at Set.forEach (native) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler._compileComponents (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25119:0 <- src/test.ts:50005:19) [ProxyZone]
            at createResult (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25025:0 <- src/test.ts:49911:19) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler._compileModuleAndAllComponents (webpack:///~/@angular/compiler/@angular/compiler.es5.js:25029:0 <- src/test.ts:49915:40) [ProxyZone]
            at JitCompiler.Array.concat.JitCompiler.compileModuleAndAllComponentsSync (webpack:///~/@angular/compiler/@angular/compiler.es5.js:24972:0 <- src/test.ts:49858:21) [ProxyZone]
            at TestingCompilerImpl.Array.concat.TestingCompilerImpl.compileModuleAndAllComponentsSync (webpack:///~/@angular/compiler/@angular/compiler/testing.es5.js:478:0 <- src/test.ts:52380:31
) [ProxyZone]
            at TestBed.Array.concat.TestBed._initIfNeeded (webpack:///~/@angular/core/@angular/core/testing.es5.js:704:0 <- src/test.ts:15209:36) [ProxyZone]
            at TestBed.Array.concat.TestBed.createComponent (webpack:///~/@angular/core/@angular/core/testing.es5.js:787:0 <- src/test.ts:15292:14) [ProxyZone]
            at Function.Array.concat.TestBed.createComponent (webpack:///~/@angular/core/@angular/core/testing.es5.js:609:0 <- src/test.ts:15114:29) [ProxyZone]
Chrome 56.0.2924 (Mac OS X 10.12.3): Executed 4 of 4 (3 FAILED) (0.299 secs / 0.152 secs)
```

### Mention any other details that might be useful.
I am using yarn - shouldn't make any difference

**Comment by delasteve** [comment]
Thanks for the report, but this isn't a CLI issue. You will need to set up your `TestBed` so that it knows about your `TestComponent`. 

You can find more information in the testing guide, here: https://angular.io/docs/ts/latest/guide/testing.html#!#stub-component.
