### ISSUE TITLE
Upgrading 1.0.0-rc.2 to 1.0.0 breaks Karma tests

### ISSUE THREAD

**Issue by johnRambo2k14** [angular/angular-cli#5719]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

1.0.0-rc.2 to 1.0.0

### Repro steps.

Upgrade

### The log given by the failure.

```node
28 03 2017 17:29:11.378:ERROR [karma]: Error: C:/Users/Rambo/Documents/aithex/src/app/login/login.service.ts (5,23): Cannot find name 'localStorage'.,C:/Users/Rambo/Documents/aithex/src/app/login/login-modal/login-modal.component.ts (25,9): Cannot find name 'localStorage'.
C:/Users/Rambo/Documents/aithex/src/app/login/login-modal/login-modal.component.ts (26,9): Cannot find name 'localStorage'.
C:/Users/Rambo/Documents/aithex/src/app/login/login-modal/login-modal.component.ts (35,13): Cannot find name 'localStorage'.
C:/Users/Rambo/Documents/aithex/src/app/login/login-modal/login-modal.component.ts (36,13): Cannot find name 'localStorage'.,C:/Users/Rambo/Documents/aithex/src/app/chatlio/chatlio.component.ts (3,33): Cannot find name 'Window'.
C:/Users/Rambo/Documents/aithex/src/app/chatlio/chatlio.component.ts (22,30): Cannot find name 'window'.
C:/Users/Rambo/Documents/aithex/src/app/chatlio/chatlio.component.ts (29,21): Cannot find name 'document'.
C:/Users/Rambo/Documents/aithex/src/app/chatlio/chatlio.component.ts (38,23): Cannot find name 'document'.
C:/Users/Rambo/Documents/aithex/src/app/chatlio/chatlio.component.ts (39,23): Cannot find name 'document'.
    at Compiler.compiler.plugin (C:\Users\Rambo\Documents\aithex\node_modules\@angular\cli\plugins\karma-webpack-throw-error.js:10:23)
    at Compiler.applyPlugins (C:\Users\Rambo\Documents\aithex\node_modules\tapable\lib\Tapable.js:61:14)
    at Watching._done (C:\Users\Rambo\Documents\aithex\node_modules\webpack\lib\Compiler.js:91:17)
    at onCompiled (C:\Users\Rambo\Documents\aithex\node_modules\webpack\lib\Compiler.js:50:17)
    at C:\Users\Rambo\Documents\aithex\node_modules\webpack\lib\Compiler.js:480:13
    at next (C:\Users\Rambo\Documents\aithex\node_modules\tapable\lib\Tapable.js:138:11)
    at Compiler.<anonymous> (C:\Users\Rambo\Documents\aithex\node_modules\webpack\lib\CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (C:\Users\Rambo\Documents\aithex\node_modules\tapable\lib\Tapable.js:142:13)
    at C:\Users\Rambo\Documents\aithex\node_modules\webpack\lib\Compiler.js:477:10
    at Compilation.applyPluginsAsyncSeries (C:\Users\Rambo\Documents\aithex\node_modules\tapable\lib\Tapable.js:131:46)
    at self.applyPluginsAsync.err (C:\Users\Rambo\Documents\aithex\node_modules\webpack\lib\Compilation.js:640:19)
    at next (C:\Users\Rambo\Documents\aithex\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.<anonymous> (C:\Users\Rambo\Documents\aithex\node_modules\webpack\lib\ProgressPlugin.js:122:5)
    at Compilation.applyPluginsAsyncSeries (C:\Users\Rambo\Documents\aithex\node_modules\tapable\lib\Tapable.js:142:13)
    at self.applyPluginsAsync.err (C:\Users\Rambo\Documents\aithex\node_modules\webpack\lib\Compilation.js:631:11)
    at next (C:\Users\Rambo\Documents\aithex\node_modules\tapable\lib\Tapable.js:138:11)
```

### Mention any other details that might be useful.

Basically the `tsconfig.app.json` and `tsconfig.spec.json` changed, which causes those issues. The quickest way to fix this is re-scaffold the project. Or use the new tsconfigs

Essentially its because the `tsconfig` is missing the `node` types.

**Comment by pfrandsen** [comment]
I am seeing the same compile error (Cannot find name 'window') - it is both in rc.4 and the 1.0.0release. App runs fine but the tests wont run.

**Comment by pfrandsen** [comment]
Adding "dom" to tsconfig.spec.json solves the issue:

```javascript
"lib": [
      "es2016",
      "dom"
    ]
```
Was:
```javascript
"lib": [
      "es2016"
    ]
```

**Comment by filipesilva** [comment]
Closing as answered by @pfrandsen, thanks!
