### ISSUE TITLE
ReferenceError: viewEncapsulation is not defined 

### ISSUE THREAD

**Issue by georgeedwards** [angular/angular-cli#5742]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Versions.
```
@angular/cli: 1.0.0
node: 6.10.1
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/material: 2.0.0-alpha.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10
```

### Repro steps.
I simply run `ng generate component test` in an existing and previously functional repo.

### The log given by the failure.
```
ReferenceError: viewEncapsulation is not defined (Error in blueprint template: C:\Users\George\Source\Repos\Coty%20Monitoring%20System\node_modules\@angular\cli\blueprints\component\files\__path__\__name__.component.ts)
    at eval (eval at <anonymous> (C:\Users\George\Source\Repos\Coty%20Monitoring%20System\node_modules\@angular\cli\node_modules\lodash\template.js:224:12), <anonymous>:9:5)
    at processTemplate (C:\Users\George\Source\Repos\Coty%20Monitoring%20System\node_modules\@angular\cli\ember-cli\lib\models\file-info.js:20:36)
    at C:\Users\George\Source\Repos\Coty%20Monitoring%20System\node_modules\@angular\cli\ember-cli\lib\models\file-info.js:97:20
    at tryCatch (C:\Users\George\Source\Repos\Coty%20Monitoring%20System\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (C:\Users\George\Source\Repos\Coty%20Monitoring%20System\node_modules\rsvp\dist\rsvp.js:554:13)
    at publish (C:\Users\George\Source\Repos\Coty%20Monitoring%20System\node_modules\rsvp\dist\rsvp.js:522:7)
    at flush (C:\Users\George\Source\Repos\Coty%20Monitoring%20System\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Desired functionality.
The function to work correctly

### Mention any other details that might be useful.
Windows 10 

As mentioned in other issues, I tried adding:
```
"viewEncapsulation": "Emulated",
"changeDetection": "Default"
```
to the defaults section of the `angular-cli.json` file but it made no difference.

**Comment by RicardoVaranda** [comment]
Hi @georgeedwards,

This error seems to be similar to the one mentioned on: https://github.com/angular/angular-cli/issues/4832

Do you by some chance have lodash or any external libraries installed?

**Comment by georgeedwards** [comment]
@RicardoVaranda Not globally, but I do in the project repo. The generate command seems to work fine in other directories. 

I only have lodash as a child dependency of something else, it isn't specified in my package.json

**Comment by aswathkk** [comment]
Hi @georgeedwards,
I got the same error
deleting `node_modules\@angular\cli\node_modules\lodash` directory did the fix

**Comment by sumitarora** [comment]
Closing this being tracked on this issue https://github.com/angular/angular-cli/issues/4832
