### ISSUE TITLE
"tsc: Cannot find module" results in "TypeError: Data must be a string or a buffer"

### ISSUE THREAD

**Issue by dherges** [angular/angular-cli#5756]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1
```

### Repro steps.

Faulty source code:
```ts
export * from './non-existing-typescript-module';
```

`tsc` reports an error that the module cannot be resolved (e.g. error message in VSCode is shown as):

```
[ts]: Cannot find module './non-existing-typescript-module'
```

`ng build` fails with `TypeError: Data must be a string or a buffer`

This error message leaves humans wonderings (question marks all over my face and in my head) what causes the compilation to fail. The error message makes it hard to debug and fix the root cause.

(If the export from non-existing module is removed in the buggy source code, both `tsc` and `ng` compile w/o errors, of course!)

### The log given by the failure.

```
$ ng build
 86% hashingcrypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (<ng-app>\node_modules\webpack\lib\dependencies\HarmonyExportImportedSpecifierDependency.js:144:8)
    at <ng-app>\node_modules\webpack\lib\DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (<ng-app>\node_modules\webpack\lib\DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (<ng-app>\node_modules\webpack\lib\Module.js:162:41)
    at NormalModule.updateHash (<ng-app>\node_modules\webpack\lib\NormalModule.js:327:30)
    at modules.forEach.m (<ng-app>\node_modules\webpack\lib\Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (<ng-app>\node_modules\webpack\lib\Chunk.js:253:16)
    at Compilation.createHash (<ng-app>\node_modules\webpack\lib\Compilation.js:1121:10)
    at sealPart2 (<ng-app>\node_modules\webpack\lib\Compilation.js:605:9)
    at next (<ng-app>\node_modules\tapable\lib\Tapable.js:138:11)
    at Compilation.<anonymous> (<ng-app>\node_modules\webpack\lib\ProgressPlugin.js:110:5)
    at next (<ng-app>\node_modules\tapable\lib\Tapable.js:140:14)
```

### Desired functionality.

Please provide a better error message.

**Comment by dherges** [comment]
seems to be related to barrels if `'non-existing-typescript-module'` points to a barrel at `non-existing-typescript-module/index.ts`

**Comment by Toub** [comment]
Related to https://github.com/webpack/webpack/issues/4072

**Comment by filipesilva** [comment]
According to webpack/webpack#4072, webpack@2.3.0 and up has this fixed, it's mostly a matter of updating the version we use.

**Comment by clydin** [comment]
Tested with latest CLI and the proper error message is now reported:
```
ERROR in src/xyz.ts(1,15): error TS2307: Cannot find module './non-existing-typescript-module'.
```
