### ISSUE TITLE
Error related to rules 'no-access-missing-member' and 'templates-use-public'

### ISSUE THREAD

**Issue by Yura13** [angular/angular-cli#5758]
### Bug Report 
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.0
npm: 3.10.10
os: Windows 10

`package.json`:
```
    "@angular/animations": "4.0.1",
    "@angular/common": "4.0.1",
    "@angular/compiler": "4.0.1",
    "@angular/core": "4.0.1",
    "@angular/forms": "4.0.1",
    "@angular/http": "4.0.1",
    "@angular/platform-browser": "4.0.1",
    "@angular/platform-browser-dynamic": "4.0.1",
    "@angular/router": "4.0.1",
    "core-js": "2.4.1",
    "primeng": "4.0.0-rc.2",
    "rxjs": "5.2.0",
    "zone.js": "0.8.5"
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "4.0.1",
    "@types/node": "7.0.12",
    "codelyzer": "3.0.0-beta.4",
    "ts-node": "3.0.2",
    "tslint": "4.5.1",
    "typescript": "2.2.2"
```

### Repro steps.
If you run `ng lint` in a console you will see next warnings: 
```
Warning: The 'use-life-cycle-interface' rule requires type checking
Warning: The 'no-access-missing-member' rule requires type checking
Warning: The 'templates-use-public' rule requires type checking
```
I have the error when running `ng lint --type-check` (`tslint --type-check --project src/tsconfig.app.json`). 

### The log given by the failure.
```
Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23308:54)
    at simplifyCall (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23114:24)
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23296:48)
    at simplifyInContext (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23321:24)
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23157:36)
    at simplifyInContext (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23321:24)
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23279:48)
    at simplify (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23139:56)
    at simplifyInContext (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23321:24)
    at recordedSimplifyInContext (C:\VisualStudioProjects\migrateNG4\node_modules\@angular\compiler\bundles\compiler.umd.js:23334:24) 'node_modules/@angular/core/core.d.ts'
```

### Mention any other details that might be useful.
`tslint.json` configuration - default generated by angular-cli 1.0.0
When I remove  "no-access-missing-member": true and "templates-use-public": true from `tslint.json` tslint running without any errors.

**Comment by clydin** [comment]
The default codelyzer version is ~2.0.0.  The 3.0.0 beta has breaking changes and has not been integrated into the CLI at this time. However, from looking at the changelog, it should work with type checking enabled.  Does the error occur with a completely default project (with codelyzer 3.0.0-beta.4)?

**Comment by Yura13** [comment]
This error not reproduced with a default project.
But when I run `ng build --aot --prod` I have such errors:
- ERROR in ng:... Property 'show' is private and only accessible within class 'TabComponent'.
- ERROR in ng:... Property 'emptyMessage' does not exist on type 'TabComponent'.
So errors relate to rules of codelyzer.

**Comment by clydin** [comment]
Those are AOT build errors.  Linting is not run during a build.

Also, `--prod` includes `--aot` by default, so you don't need to specify it separately (unless you want to turn it off with `--no-aot`).

**Comment by Yura13** [comment]
It will great if codelyzer v.3.0.0 integrate into the CLI as soon as possible. It will solve the failing build in production.

**Comment by filipesilva** [comment]
Closing as answered by @clydin, thanks!
