### ISSUE TITLE
Cannot Read Property 'glob' of null error

### ISSUE THREAD

**Issue by emrekara37** [angular/angular-cli#5808]
![screenshot_3](https://cloud.githubusercontent.com/assets/17519791/24612952/738cf1dc-188f-11e7-9119-b77ae032ed74.png)

**Comment by Malouke** [comment]
you have to install glob

**Comment by emrekara37** [comment]
@Malouke  How do I install

**Comment by monaka** [comment]
@emrekara37 same here and found this comment. https://github.com/angular/angular-cli/issues/5580#issuecomment-288865297
I'm waiting for the next release now.

**Comment by emrekara37** [comment]
@monaka  
When will the new version be released

**Comment by Malouke** [comment]
hi emrekara 
i think by this command npm install --save glob 
the problem it s not clear with angular cli.

**Comment by emrekara37** [comment]
@Malouke  glob is install but again error

**Comment by Malouke** [comment]
ok ,
if you  allow me can I  give another adivice work with github of angular-cli instead  try to install it.
you can link with npm all steps are discribe under github of angular .

**Comment by emrekara37** [comment]
@Malouke  
How to install GitHub repository for angular-cli

**Comment by Malouke** [comment]
git clone https://github.com/angular/angular-cli.git
cd angular-cli
npm link

**Comment by monaka** [comment]
@emrekara37 I don't know when 1.0.1 will be released as I'm just a user. ;-)

**Comment by filipesilva** [comment]
#5580 was released with `1.0.0`, this issue sounds like something different.

@emrekara37 you seem to have an old app inside your `app45` folder. Can you show me your `angular-cli.json` file?

**Comment by monaka** [comment]
I'm not @emrekara37 but have similar issue.
Actually I'm running Deis but it uses buildpacks provided by Heroku.
Here is my package.json and the log on `git push`.

```
{
  "name": "pizzeria",
  "private": true,
  "version": "0.0.1",
  "description": "User console for PizzaFactory Camino",
  "main": "server.js",
  "scripts": {
    "ng": "ng",
    "start:dev": "ng serve",
    "start": "node server.js",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ng build --base-href=/tavola --prod"
  },
  "private": true,
  "dependencies": {
    "body-parser": "^1.17.0",
    "compression": "^1.6.2",
    "express": "^4.14.1",
    "express-session": "^1.15.1",
    "morgan": "^1.8.1",
    "passport": "^0.3.2",
    "passport-azure-ad": "^3.0.4",
    "serve-static": "^1.12.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
```

```
-----> Restoring cache...
       Done!
-----> Node.js app detected

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_ENV=development
       NODE_MODULES_CACHE=true

-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)

       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 7.9.0...
       Using default npm version: 4.2.0

-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)

-----> Building dependencies
       Installing node modules (package.json)

       > pizzeria@0.0.1 postinstall /tmp/build
       > ng build --base-href=/tavola --prod

       Cannot read property 'glob' of null
       TypeError: Cannot read property 'glob' of null
       at ObjectSchemaTreeNode._set (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:224:131)
       at new ObjectSchemaTreeNode (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:209:14)
       at OneOfSchemaTreeNode._createChildProperty (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
       at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:161:25)
       at Array.map (native)
       at OneOfSchemaTreeNode (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:160:48)
       at ArraySchemaTreeNode._createChildProperty (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)
       at ArraySchemaTreeNode._set (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:286:39)
       at new ArraySchemaTreeNode (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:267:14)
       at ObjectSchemaTreeNode._createChildProperty (/tmp/build/node_modules/@ngtools/json-schema/src/schema-tree.js:148:26)

       npm ERR! Linux 4.10.4-coreos-r1
       npm ERR! argv "/tmp/build/.heroku/node/bin/node" "/tmp/build/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build/.npmrc"
       npm ERR! node v7.9.0
       npm ERR! npm  v4.2.0
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! pizzeria@0.0.1 postinstall: `ng build --base-href=/tavola --prod`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the pizzeria@0.0.1 postinstall script 'ng build --base-href=/tavola --prod'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the pizzeria package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     ng build --base-href=/tavola --prod
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs pizzeria
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls pizzeria
       npm ERR! There is likely additional logging output above.

       npm ERR! Please include the following file with any support request:
       npm ERR!     /app/.npm/_logs/2017-04-17T07_57_35_704Z-debug.log

-----> Build failed
```

**Comment by monaka** [comment]
ping? Is more simplified example required?

**Comment by lafama** [comment]
anyone with a fix for this? Am trying to deploy my app on dokku using a similar setup as @monaka

**Comment by kruczjak** [comment]
Hi, I know that it's a bit hacky, but it works correctly (as workaround of course).

`scripts` part of my`package.json`:

```
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "heroku-postbuild": "HOME=/ ./node_modules/@angular/cli/bin/ng build -prod -aot"
  },
```

Key thing is `HOME=/`. https://github.com/angular/angular-cli/issues/4207#issuecomment-277840301

**Comment by lafama** [comment]
Works perfectly @kruczjak . Your a life saver 👍

**Comment by monaka** [comment]
I also checked that my build was passed with the patch based @kruczjak 's information.
I become to implement my application with it for now. Thanks @kruczjak.
And I hope this issue will be fixed on the next release.

**Comment by balr404** [comment]
I have tried the following option to resolve the issue
Steps to resolve the issue

$ pwd
it shows —> /Users/YourName /*** That is your Home path***/
Execute the below command to display the hidden files

$ defaults write com.apple.Finder AppleShowAllFiles true
$ killall Finder
After executing the above command you will see the hidden files.
if “.angular-cli.json” file exist under “/Users/yourname” (i.e Home Path) then remove “.angular-cli.json” file.

then navigate to your application path and try execute ‘ng’ command.

**Comment by filipesilva** [comment]
I'm going to reopen https://github.com/angular/angular-cli/issues/4207, it has a lot more context about this type of problem.

**Comment by kirillgroshkov** [comment]
@kruczjak your fix helped me!!
