### ISSUE TITLE
e2e fails when using firefox

### ISSUE THREAD

**Issue by Waterstraal** [angular/angular-cli#5820]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
@angular/cli: 1.0.0
node: 6.9.4
os: win32 x64

Windows 7

### Repro steps.
- Run `ng new angular-cli-firefox-e2e-test`
- Update `protractor.conf.js`: set `browsername` to `firefox`
- Run `ng e2e`

### The log given by the failure.

```
** NG Live Development Server is running on http://localhost:49159 **
Hash: 0af19760eb30dd0be722
Time: 22495ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 3.69 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 9.77 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.37 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
webpack: Compiled successfully.
[11:02:14] I/update - chromedriver: file exists C:\Sandboxes\Research\angular-cli-require-test\node_modules\webdriver-manager\selenium\chromedriver_2.29.zip
[11:02:14] I/update - chromedriver: unzipping chromedriver_2.29.zip
[11:02:14] I/update - chromedriver: chromedriver_2.29.exe up to date
[11:02:15] I/launcher - Running 1 instances of WebDriver
[11:02:15] I/direct - Using FirefoxDriver directly...
[11:02:15] E/direct - Error code: 135
[11:02:15] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[11:02:15] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
    at IError (C:\Sandboxes\Research\angular-cli-require-test\node_modules\protractor\lib\exitCodes.ts:7:1)
    at ProtractorError (C:\Sandboxes\Research\angular-cli-require-test\node_modules\protractor\lib\exitCodes.ts:20:5)
    at BrowserError (C:\Sandboxes\Research\angular-cli-require-test\node_modules\protractor\lib\exitCodes.ts:67:5)
    at Direct.getNewDriver (C:\Sandboxes\Research\angular-cli-require-test\node_modules\protractor\lib\driverProviders\direct.ts:99:17)
    at Runner.createBrowser (C:\Sandboxes\Research\angular-cli-require-test\node_modules\protractor\lib\runner.ts:225:39)
    at q.then.then (C:\Sandboxes\Research\angular-cli-require-test\node_modules\protractor\lib\runner.ts:391:27)
    at _fulfilled (C:\Sandboxes\Research\angular-cli-require-test\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Sandboxes\Research\angular-cli-require-test\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Sandboxes\Research\angular-cli-require-test\node_modules\q\q.js:796:13)
    at C:\Sandboxes\Research\angular-cli-require-test\node_modules\q\q.js:556:49
    at runSingle (C:\Sandboxes\Research\angular-cli-require-test\node_modules\q\q.js:137:13)
    at flush (C:\Sandboxes\Research\angular-cli-require-test\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[11:02:15] E/launcher - Process exited with error code 135
```

### Desired functionality.
The e2e test should be able to run on firefox

**Comment by britvik** [comment]
Got same error. Chrome works just fine, but Firefox fails.

**Comment by filipesilva** [comment]
I think this happens because we only update the chrome webdriver by default. It should work if you run `webdriver-manager update` as the error message suggests. 

The easiest way of doing it is by setting a npm script and running it (`npm run webdriver`):
```
  "scripts": {
    // ...
    "webdriver": "webdriver-manager update"
  },
```

Maybe we could detect this automatically but can't really think of an optimal way of doing that.

**Comment by britvik** [comment]
Ok updating manager helped, although I swear I did that before and it did not help :).
Now FF starts, but I get this error instead:
`Unable to parse new session response: {"value": {"sessionId":"ae447386-eb72-4964-aca4-5441a8b6e319","value"
:{"XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","acceptSslCerts":false,"appBuildId":"20170125094131","browserName":"firefox",
"browserVersion":"51.0.1","command_id":1,"count":1,"platform":"WINDOWS_NT","platformName":"windows_nt","platformVersion":"10.0","pr
ocessId":12148,"proxy":{},"raisesAccessibilityExceptions":false,"rotatable":false,"specificationLevel":0,"takesElementScreenshot":t
rue,"takesScreenshot":true,"version":"51.0.1"}}}
`

**Comment by andre-gois** [comment]
Same problem here. Running protractor 5.1.1 and Firefox 52.0.2 (64-bit)

**Comment by mftaha** [comment]
Updating webdriver manager didn't work for me.

**Comment by nbuso** [comment]
@filipesilva can you consider to add a pree2e step to keep the scripts easier? is it feasible?

**Comment by pchorus** [comment]
@britvik I have the same problem using Protractor 5.1.0 and Firefox Version 53.0 (64-bit) on macOS Sierra 10.12..4

**Comment by mleu** [comment]
Firefox with `directConnect: true` currently does not work due to angular/protractor#4253

**Comment by filipesilva** [comment]
Closing in favor of angular/protractor#4253.
