### ISSUE TITLE
prod build fails when using UpgradeAdapter

### ISSUE THREAD

**Issue by scottlepp** [angular/angular-cli#5882]
- [x ] bug report 

### Versions.
@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/upgrade: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
1.  Follow the Angular docs for using the UpgradeAdapter
2.  Try to use ng build --prod from that example
3.  Open the index.html produced and see error on the console.

### The log given by the failure.
vendor.49a60f1….bundle.js:370 Error: Unexpected value 't' imported by the module 'class0'. Please add a @NgModule annotation.
    at y (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2483)
    at f (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:460:3458)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7411
    at Array.forEach (native)
    at t.Uk0N.t.getNgModuleMetadata (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7018)
    at t.Uk0N.t._loadModules (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57851)
    at t.Uk0N.t._compileModuleAndComponents (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57405)
    at t.Uk0N.t.compileModuleAsync (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:56718)
    at e._bootstrapModuleWithZone (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:12905)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:389:14099
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9879)
    at Object.onInvoke (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:8039)
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9819)
    at e.run (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:5091)
    at http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2128 "Error: Unexpected value 't' imported by the module 'class0'. Please add a @NgModule annotation.
    at y (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2483)
    at f (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:460:3458)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7411
    at Array.forEach (native)
    at t.Uk0N.t.getNgModuleMetadata (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7018)
    at t.Uk0N.t._loadModules (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57851)
    at t.Uk0N.t._compileModuleAndComponents (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57405)
    at t.Uk0N.t.compileModuleAsync (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:56718)
    at e._bootstrapModuleWithZone (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:12905)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:389:14099
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9879)
    at Object.onInvoke (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:8039)
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9819)
    at e.run (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:5091)
    at http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2128"
polyfills.0ff5189….bundle.js:36 Unhandled Promise rejection: Unexpected value 't' imported by the module 'class0'. Please add a @NgModule annotation. ; Zone: <root> ; Task: Promise.then ; Value: Error: Unexpected value 't' imported by the module 'class0'. Please add a @NgModule annotation.
    at y (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2483)
    at f (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:460:3458)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7411
    at Array.forEach (native)
    at t.Uk0N.t.getNgModuleMetadata (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7018)
    at t.Uk0N.t._loadModules (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57851)
    at t.Uk0N.t._compileModuleAndComponents (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57405)
    at t.Uk0N.t.compileModuleAsync (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:56718)
    at e._bootstrapModuleWithZone (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:12905)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:389:14099
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9879)
    at Object.onInvoke (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:8039)
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9819)
    at e.run (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:5091)
    at http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2128 Error: Unexpected value 't' imported by the module 'class0'. Please add a @NgModule annotation.
    at y (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2483)
    at f (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:460:3458)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7411
    at Array.forEach (native)
    at t.Uk0N.t.getNgModuleMetadata (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7018)
    at t.Uk0N.t._loadModules (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57851)
    at t.Uk0N.t._compileModuleAndComponents (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57405)
    at t.Uk0N.t.compileModuleAsync (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:56718)
    at e._bootstrapModuleWithZone (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:12905)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:389:14099
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9879)
    at Object.onInvoke (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:8039)
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9819)
    at e.run (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:5091)
    at http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2128
polyfills.0ff5189….bundle.js:36 Error: Uncaught (in promise): Error: Unexpected value 't' imported by the module 'class0'. Please add a @NgModule annotation.
Error: Unexpected value 't' imported by the module 'class0'. Please add a @NgModule annotation.
    at y (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2483)
    at f (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:460:3458)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7411
    at Array.forEach (native)
    at t.Uk0N.t.getNgModuleMetadata (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7018)
    at t.Uk0N.t._loadModules (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57851)
    at t.Uk0N.t._compileModuleAndComponents (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57405)
    at t.Uk0N.t.compileModuleAsync (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:56718)
    at e._bootstrapModuleWithZone (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:12905)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:389:14099
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9879)
    at Object.onInvoke (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:8039)
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9819)
    at e.run (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:5091)
    at http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2128
    at y (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2483)
    at f (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:460:3458)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7411
    at Array.forEach (native)
    at t.Uk0N.t.getNgModuleMetadata (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:572:7018)
    at t.Uk0N.t._loadModules (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57851)
    at t.Uk0N.t._compileModuleAndComponents (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:57405)
    at t.Uk0N.t.compileModuleAsync (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:593:56718)
    at e._bootstrapModuleWithZone (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:12905)
    at http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:389:14099
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9879)
    at Object.onInvoke (http://localhost:63342/manage-ui/dist/vendor.49a60f1ec9f7b0d49ed2.bundle.js:316:8039)
    at t.invoke (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:9819)
    at e.run (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:5091)
    at http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2128
    at y (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2483)
    at l (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:1605)
    at http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:2159
    at t.invokeTask (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:10563)
    at e.runTask (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:5740)
    at a (http://localhost:63342/manage-ui/dist/polyfills.0ff51893bf8b41bfcd3f.bundle.js:36:667)

### Desired functionality.
Produce a working production build.

### Mention any other details that might be useful.
The dev build works with this workaround:  https://github.com/angular/angular-cli/issues/5303#issuecomment-292644305

**Comment by filipesilva** [comment]
Heya, can you provide a simple reproduction that I can follow to see this issue? Preferably a very basic repo with the minimum set of changes.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.
