### ISSUE TITLE
Cannot read property "glob" of null angular cli

### ISSUE THREAD

**Issue by Malouke** [angular/angular-cli#5900]
node version  :  v7.8.0
npm version :4.2.0 
windows 7  pro 64 bits 
angular cli  install  like describe on github   npm install -g @angular/cli

i get the following error  : 
Cannot read property 'glob' of null
TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (C:\workspacecode\dashbord\client\node_modules\@ngtools\json-schema\src\schema-tree.js:224:131)
    at new ObjectSchemaTreeNode (C:\workspacecode\dashbord\client\node_modules\@ngtools\json-schema\src\schema-tree.js:209:14)
    at OneOfSchemaTreeNode._createChildProperty (C:\workspacecode\dashbord\client\node_modules\@ngtools\json-schema\src\schema-tree.js:148:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (C:\workspacecode\dashbord\client\node_modules\@ngtools\json-schema\src\schema-tree.js:161:25)
    at Array.map (native)
    at OneOfSchemaTreeNode (C:\workspacecode\dashbord\client\node_modules\@ngtools\json-schema\src\schema-tree.js:160:48)
    at ArraySchemaTreeNode._createChildProperty (C:\workspacecode\dashbord\client\node_modules\@ngtools\json-schema\src\schema-tree.js:148:26)
    at ArraySchemaTreeNode._set (C:\workspacecode\dashbord\client\node_modules\@ngtools\json-schema\src\schema-tree.js:286:39)
    at new ArraySchemaTreeNode (C:\workspacecode\dashbord\client\node_modules\@ngtools\json-schema\src\schema-tree.js:267:14)
    at ObjectSchemaTreeNode._createChildProperty (C:\workspacecode\dashbord\client\node_modules\@ngtools\json-schema\src\schema-tree.js:148:26)

Why ??? 
i miss somthing or some packages ???????

**Comment by alan-agius4** [comment]
Closing as it doesn't follow template.
