### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by areijngoudt** [angular/angular-cli#5912]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.0
node: 6.10.0
os: darwin x64
@angular/animations: 4.0.1
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

### Repro steps.
in an existing project:
ng generate module +cedent/contract/contract-detail/section-matrix
ng generate component section-matrix -export true -module +cedent/contract/contract-detail/section-matrix

the new component is installed in 
`src/app/section-matrix` 
instead of 
`src/app/+cedent/contract/contract-detail/section-matrix`

and the error is thrown.

### The log given by the failure.
EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Class.afterInstall (/Users/adreijngoudt/bitbucket/codex1_mvp/web/client/node_modules/@angular/cli/blueprints/component/index.js:209:34)
    at tryCatch (/Users/adreijngoudt/bitbucket/codex1_mvp/web/client/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/adreijngoudt/bitbucket/codex1_mvp/web/client/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/adreijngoudt/bitbucket/codex1_mvp/web/client/node_modules/rsvp/dist/rsvp.js:522:7)
    at flush (/Users/adreijngoudt/bitbucket/codex1_mvp/web/client/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

**Comment by davidlandais** [comment]
Try with : +cedent/contract/contract-detail/section-matrix/section-matrix.module.ts
I had the same error. It seems that you need to provide the module file name to update.
