### ISSUE TITLE
getting error on ng serve 

### ISSUE THREAD

**Issue by ietuday** [angular/angular-cli#5956]
After npm install, when i fired ng serve,it shows following error :

The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/home/uday/Project/angular2-rss-reader-tutorial-master/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/uday/Project/angular2-rss-reader-tutorial-master/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by sbyoon90** [comment]
I think you check this guide line 
https://github.com/angular/angular-cli/wiki/stories-1.0-update

**Comment by JanStureNielsen** [comment]
See http://stackoverflow.com/questions/43351136/the-angular-compiler-cli-package-was-not-properly-installed

**Comment by filipesilva** [comment]
I think @sbyoon90 and @JanStureNielsen cover it pretty well, cheers!
