### ISSUE TITLE
angular-cli cmd ng new app failing in config.js:16 constructor

### ISSUE THREAD

**Issue by hudaR** [angular/angular-cli#6015]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

macOS -> El Capitan
```
$ node --version
v4.2.6
$ npm --version
2.14.12
```

### Repro steps.

All I did was the following:
```
mkdir mywork
npm install -g @angular/cli
ng new my-app
```

### The log given by the failure.

huda$ ng new my-app
/Users/huda/.nvm/versions/node/v4.2.6/lib/node_modules/@angular/cli/models/config/config.js:16
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/huda/.nvm/versions/node/v4.2.6/lib/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

### Desired functionality.

please fix this issue, i wanted to use angular cli. thanks

### Mention any other details that might be useful.

N/A

**Comment by sumitarora** [comment]
@hudaR Seems like you are using old versions of node and npm. Can you update node to 6.x and npm 3.x and check.

**Comment by hudaR** [comment]
@sumitarora thank you - that resolved the issue
