### ISSUE TITLE
Error when running `ng lint --type-check` with Angular 4.0.2

### ISSUE THREAD

**Issue by tsvetomir** [angular/angular-cli#6021]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Versions.
```
@angular/cli: 1.0.0
node: 6.10.1
os: linux x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
```

### Repro steps.
```
ng new lint-test && cd lint-test
ng lint --type-check
```

### The log given by the failure.
```
TypeError: this.symbolResolver.getSymbolByModule is not a function
    at StaticReflector.findDeclaration (/tmp/angular402/node_modules/@angular/compiler/bundles/compiler.umd.js:22794:63)
    at StaticReflector.initializeConversionMap (/tmp/angular402/node_modules/@angular/compiler/bundles/compiler.umd.js:23012:36)
    at new StaticReflector (/tmp/angular402/node_modules/@angular/compiler/bundles/compiler.umd.js:22741:14)
    at ContextSymbols.init (/tmp/angular402/node_modules/ngast/ngast.bundle.js:2479:26)
    at new ContextSymbols (/tmp/angular402/node_modules/ngast/ngast.bundle.js:2340:14)
    at ProjectSymbols.getRootContext (/tmp/angular402/node_modules/ngast/ngast.bundle.js:2558:28)
    at ProjectSymbols.getLazyLoadedContexts (/tmp/angular402/node_modules/ngast/ngast.bundle.js:2573:18)
    at Object.exports.parseTemplate (/tmp/angular402/node_modules/codelyzer/angular/templates/contextAwareTemplateParser.js:21:35)
    at Ng2Walker.visitNg2Component (/tmp/angular402/node_modules/codelyzer/angular/ng2Walker.js:119:64)
    at Ng2Walker.visitClassDeclaration (/tmp/angular402/node_modules/codelyzer/angular/ng2Walker.js:50:18)
[... snip ...]
All files pass linting.
```

### Desired functionality.
The lint should pass with an empty project.

### Mention any other details that might be useful.
Downgrading to 4.0.1 resolves this issue.
CC-ing @mgechev since the call stack includes Codelyzer

**Comment by tsvetomir** [comment]
Closing the issue as it does not occur unless Codelyzer is updated to 3.0.0-beta.4
Something I missed in the original report, oops!
