### ISSUE TITLE
TypeError: Reflect.apply: argument is not an array or array-like object

### ISSUE THREAD

**Issue by seipekm** [angular/angular-cli#6041]
i will create a new project and get this ERROR
With:
ng new "Project"

Node.js Version: 7.9.0
NPM: 4.5.0

TypeError: Reflect.apply: argument is not an array or array-like object
   at ensureStackTrace (Unknown script code:234:9)
   at stackGetter (Unknown script code:244:9)
   at NotFoundError (C:\Users\marti\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\project.js:561:3)
   at handleFindupError (C:\Users\marti\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\project.js:603:3)
   at findupPath (C:\Users\marti\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\project.js:598:5)
   at Project.closestSync (C:\Users\marti\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\project.js:495:5)
   at Project.projectOrnullProject (C:\Users\marti\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\project.js:525:5)
   at module.exports (C:\Users\marti\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\cli\index.js:40:3)
   at module.exports (C:\Users\marti\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js:37:3)
   at Anonymous function (C:\Users\marti\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng:185:5)

**Comment by seipekm** [comment]
i found the Problem
two Node PATH
