### ISSUE TITLE
Template parse errors:

### ISSUE THREAD

**Issue by imranmali** [angular/angular-cli#6130]
I'm getting the following error while running the angular application. It was working fine on the earlier version then I freshly installed the angular-cli verison and now project stopped working.

### Versions.

Output from: `ng --version`.
@angular/cli: 1.0.0-rc.2
node: 6.10.2
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.10

package.json file 
{
  "name": "my-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.22",
    "@ngx-translate/core": "^6.0.0",
    "@ngx-translate/http-loader": "0.0.3",
    "@types/underscore": "^1.8.0",
    "core-js": "^2.4.1",
    "ng-lightning": "^1.3.0",
    "ng2-toasty": "^4.0.0",
    "rxjs": "^5.1.0",
    "typedjson-npm": "^0.1.7",
    "underscore": "^1.8.3",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.2",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.0.0"
  }
}

Error: Uncaught (in promise): Error: Template parse errors:
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" [ERROR ->]let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template ["): NgbHighlight@0:37
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" let-part [ERROR ->]let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template [ngIf]="!i"): NgbHighlight@0:46
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("rOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span>[ERROR ->]<ng-template [ngIf]="!isOdd">{{part}}</ng-template></ng-template>"): NgbHighlight@0:124
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template ngFor [ngForOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightC"): NgbHighlight@0:0
Error: Template parse errors:
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" [ERROR ->]let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template ["): NgbHighlight@0:37
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" let-part [ERROR ->]let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template [ngIf]="!i"): NgbHighlight@0:46
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("rOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span>[ERROR ->]<ng-template [ngIf]="!isOdd">{{part}}</ng-template></ng-template>"): NgbHighlight@0:124
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template ngFor [ngForOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightC"): NgbHighlight@0:0
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3374:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:78723:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6239:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:20606:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:55464:68)
    at http://localhost:4200/vendor.bundle.js:55347:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:55347:19)
    at createResult (http://localhost:4200/vendor.bundle.js:55229:19)
    at ZoneDelegate.webpackJsonp.789.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2716:26)
    at Zone.webpackJsonp.789.Zone.run (http://localhost:4200/polyfills.bundle.js:2508:43)
    at http://localhost:4200/polyfills.bundle.js:3095:57
    at ZoneDelegate.webpackJsonp.789.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2749:31)
    at Zone.webpackJsonp.789.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2548:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2928:35)
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3374:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:78723:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6239:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:20606:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:55464:68)
    at http://localhost:4200/vendor.bundle.js:55347:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:55347:19)
    at createResult (http://localhost:4200/vendor.bundle.js:55229:19)
    at ZoneDelegate.webpackJsonp.789.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2716:26)
    at Zone.webpackJsonp.789.Zone.run (http://localhost:4200/polyfills.bundle.js:2508:43)
    at http://localhost:4200/polyfills.bundle.js:3095:57
    at ZoneDelegate.webpackJsonp.789.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2749:31)
    at Zone.webpackJsonp.789.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2548:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2928:35)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3047:31) [<root>]
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3018:17) [<root>]
    at http://localhost:4200/polyfills.bundle.js:3095:17 [<root>]
    at Zone.webpackJsonp.789.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2548:47) [<root> => <root>]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2928:35) [<root>]
    at <anonymous> [<root>]

**Comment by grizzm0** [comment]
ng-template is an angular 4 component while it looks like you're using angular 2.4.

The error seems to come from ng-bootstrap which have bumped their angular version to use angular4 and hence the new ng-template component instead of the angular2 template component.

**Comment by imranmali** [comment]
I really appreciate your reply. I've fixed this issue. It was because of ng-bootstrap library

**Comment by Confidence7** [comment]
can you help, what did you do to the library

**Comment by imranmali** [comment]
Now i'm not using ng-bootstrap library, coz some of the module are not compatible with angular4.

**Comment by smohsin0** [comment]
change "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.22", 
to
            "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.22",
this will exactly get alpha.22

**Comment by Confidence7** [comment]
Not helping

**Comment by Confidence7** [comment]
Do i hv to reinstall the packages

**Comment by grizzm0** [comment]
Yes. Change nuke your node_modules and try install again after locking the version.
