### ISSUE TITLE
Webpack Compiles Successfully After Upgrade to Angular 4, But Getting New Errors in the Console

### ISSUE THREAD

**Issue by darrenbrett** [angular/angular-cli#6146]
My dev environment:
MacBook Air, OS #X El Capitan 10.11.6
NPM: 4.6.1
Node: 7.4.0
CLI: 4.1.0

After running the serecommended commands to upgrade from Angular 2 to 4:

`npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save `

... my app boots up, in that I get all green and the terminal message "webpack: Compiled successfully." 

However, the app stops before loading to the screen. And in the console I now see these 2 errors:

> ERROR TypeError: Cannot set property 'addEventListener' of undefined

> zone.js:522 Unhandled Promise rejection: Cannot set property 'addEventListener' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'addEventListener' of undefined

**Comment by clydin** [comment]
zone.js is outdated and should be causing a peer dependency warning.  Try updating to the latest version.  Also check for any other peer dependency warnings and correct as necessary.

**Comment by darrenbrett** [comment]
I thought that, by definition, dependency "warnings", as opposed to dependency "errors, wouldn't actually cause an app to error out. Not true?

**Comment by clydin** [comment]
They should generally be avoided.  They mean a package expects a certain version to exist.  Generally because certain functionality or fixes are necessary.  Sometimes a package will have an overly strict peer dependency or the functionality your project is using won't be affected.  So sometimes it's not an issue but generally requires further research to ensure everything will work.

**Comment by darrenbrett** [comment]
I have now updated dependencies in my package.json file - I no longer have any warnings. The issue still persists. My package.json now looks like this:

```
{
  "name": "cli-abc",
  "version": "0.0.1",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "build": "ng build",
    "start": "ng serve --proxy-config proxy.conf.json",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.0",
    "@angular/common": "^4.1.0",
    "@angular/compiler": "^4.1.0",
    "@angular/core": "^4.1.0",
    "@angular/forms": "^4.1.0",
    "@angular/http": "^4.1.0",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.1.0",
    "@angular/platform-browser-dynamic": "^4.1.0",
    "@angular/platform-server": "^4.1.0",
    "@angular/router": "^4.1.0",
    "@ng-idle/core": "^2.0.0-beta.8",
    "@ng-idle/keepalive": "^2.0.0-beta.8",
    "@ngtools/webpack": "^1.2.4",
    "@types/socket.io": "^1.4.27",
    "@types/socket.io-client": "^1.4.29",
    "angular-in-memory-web-api": "0.3.1",
    "angular2-chartjs": "0.2.0",
    "angular2-markdown": "^1.3.5",
    "angular2-moment": "^1.2.0",
    "ngx-perfect-scrollbar": "4.0.0",
    "chart.js": "^2.4.0",
    "core-js": "^2.4.1",
    "mydatepicker": "^1.9.7",
    "ngx-pagination": "3.0.0",
    "rxjs": "^5.1.0",
    "ts-helpers": "^1.1.1",
    "zone.js":"0.8.9"
  },
  "devDependencies": {
    "@angular/cli": "1.0.1",
    "@angular/compiler-cli": "^4.1.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.3.2"
  }
}
```
The zoneJS error I'm getting looks like this in the source:

```
        if (rejection) {
            console.error('Unhandled Promise rejection:', rejection instanceof Error ? rejection.message : rejection, '; Zone:', e.zone.name, '; Task:', e.task && e.task.source, '; Value:', rejection, rejection instanceof Error ? rejection.stack : undefined);
        }
        console.error(e);
    }
```

**Comment by darrenbrett** [comment]
More detailed error report:

> ERROR TypeError: Cannot set property 'addEventListener' of undefined
>     at EventHandlerExtender (http://localhost:4200/main.bundle.js:358:27)
>     at Function.EventHandler.bind (http://localhost:4200/main.bundle.js:71:30)
>     at createClass (http://localhost:4200/vendor.bundle.js:11006:41)
>     at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:10832:37)
>     at createViewNodes (http://localhost:4200/vendor.bundle.js:12182:49)
>     at createRootView (http://localhost:4200/vendor.bundle.js:12087:5)
>     at callWithDebugContext (http://localhost:4200/vendor.bundle.js:13218:42)
>     at Object.debugCreateRootView [as createRootView] (http://localhost:4200/vendor.bundle.js:12679:12)
>     at ComponentFactory_.create (http://localhost:4200/vendor.bundle.js:10023:46)
>     at ComponentFactoryBoundToModule.create (http://localhost:4200/vendor.bundle.js:3638:29)
>     at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:5220:57)
>     at http://localhost:4200/vendor.bundle.js:5007:79
>     at Array.forEach (native)
>     at PlatformRef_._moduleDoBootstrap (http://localhost:4200/vendor.bundle.js:5007:42)
>     at http://localhost:4200/vendor.bundle.js:4969:27
> View_AppComponent_Host_0 @ AppComponent_Host.html:1
> proxyClass @ compiler.es5.js:14091
> DebugContext_.logError @ core.es5.js:12947
> ErrorHandler.handleError @ core.es5.js:1144
> (anonymous) @ core.es5.js:4660
> webpackJsonp.1416.ZoneDelegate.invoke @ zone.js:365
> onInvoke @ core.es5.js:4125
> webpackJsonp.1416.ZoneDelegate.invoke @ zone.js:364
> webpackJsonp.1416.Zone.run @ zone.js:125
> (anonymous) @ zone.js:758
> webpackJsonp.1416.ZoneDelegate.invokeTask @ zone.js:398
> onInvokeTask @ core.es5.js:4116
> webpackJsonp.1416.ZoneDelegate.invokeTask @ zone.js:397
> webpackJsonp.1416.Zone.runTask @ zone.js:165
> drainMicroTaskQueue @ zone.js:591
> AppComponent_Host.html:1 ERROR CONTEXT DebugContext_ {view: Object, nodeIndex: 1, nodeDef: Object, elDef: Object, elView: Object}
> View_AppComponent_Host_0 @ AppComponent_Host.html:1
> proxyClass @ compiler.es5.js:14091
> DebugContext_.logError @ core.es5.js:12947
> ErrorHandler.handleError @ core.es5.js:1149
> (anonymous) @ core.es5.js:4660
> webpackJsonp.1416.ZoneDelegate.invoke @ zone.js:365
> onInvoke @ core.es5.js:4125
> webpackJsonp.1416.ZoneDelegate.invoke @ zone.js:364
> webpackJsonp.1416.Zone.run @ zone.js:125
> (anonymous) @ zone.js:758
> webpackJsonp.1416.ZoneDelegate.invokeTask @ zone.js:398
> onInvokeTask @ core.es5.js:4116
> webpackJsonp.1416.ZoneDelegate.invokeTask @ zone.js:397
> webpackJsonp.1416.Zone.runTask @ zone.js:165
> drainMicroTaskQueue @ zone.js:591
> zone.js:567 Unhandled Promise rejection: Cannot set property 'addEventListener' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'addEventListener' of undefined
>     at EventHandlerExtender (http://localhost:4200/main.bundle.js:358:27)
>     at Function.EventHandler.bind (http://localhost:4200/main.bundle.js:71:30)
>     at createClass (http://localhost:4200/vendor.bundle.js:11006:41)
>     at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:10832:37)
>     at createViewNodes (http://localhost:4200/vendor.bundle.js:12182:49)
>     at createRootView (http://localhost:4200/vendor.bundle.js:12087:5)
>     at callWithDebugContext (http://localhost:4200/vendor.bundle.js:13218:42)
>     at Object.debugCreateRootView [as createRootView] (http://localhost:4200/vendor.bundle.js:12679:12)
>     at ComponentFactory_.create (http://localhost:4200/vendor.bundle.js:10023:46)
>     at ComponentFactoryBoundToModule.create (http://localhost:4200/vendor.bundle.js:3638:29)
>     at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:5220:57)
>     at http://localhost:4200/vendor.bundle.js:5007:79
>     at Array.forEach (native)
>     at PlatformRef_._moduleDoBootstrap (http://localhost:4200/vendor.bundle.js:5007:42)
>     at http://localhost:4200/vendor.bundle.js:4969:27 TypeError: Cannot set property 'addEventListener' of undefined
>     at EventHandlerExtender (http://localhost:4200/main.bundle.js:358:27)
>     at Function.EventHandler.bind (http://localhost:4200/main.bundle.js:71:30)
>     at createClass (http://localhost:4200/vendor.bundle.js:11006:41)
>     at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:10832:37)
>     at createViewNodes (http://localhost:4200/vendor.bundle.js:12182:49)
>     at createRootView (http://localhost:4200/vendor.bundle.js:12087:5)
>     at callWithDebugContext (http://localhost:4200/vendor.bundle.js:13218:42)
>     at Object.debugCreateRootView [as createRootView] (http://localhost:4200/vendor.bundle.js:12679:12)
>     at ComponentFactory_.create (http://localhost:4200/vendor.bundle.js:10023:46)
>     at ComponentFactoryBoundToModule.create (http://localhost:4200/vendor.bundle.js:3638:29)
>     at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:5220:57)
>     at http://localhost:4200/vendor.bundle.js:5007:79
>     at Array.forEach (native)
>     at PlatformRef_._moduleDoBootstrap (http://localhost:4200/vendor.bundle.js:5007:42)
>     at http://localhost:4200/vendor.bundle.js:4969:27
> consoleError @ zone.js:567
> handleUnhandledRejection @ zone.js:572
> _loop_1 @ zone.js:607
> drainMicroTaskQueue @ zone.js:611
> zone.js:569 Error: Uncaught (in promise): TypeError: Cannot set property 'addEventListener' of undefined
> TypeError: Cannot set property 'addEventListener' of undefined
>     at EventHandlerExtender (http://localhost:4200/main.bundle.js:358:27)
>     at Function.EventHandler.bind (http://localhost:4200/main.bundle.js:71:30)
>     at createClass (http://localhost:4200/vendor.bundle.js:11006:41)
>     at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:10832:37)
>     at createViewNodes (http://localhost:4200/vendor.bundle.js:12182:49)
>     at createRootView (http://localhost:4200/vendor.bundle.js:12087:5)
>     at callWithDebugContext (http://localhost:4200/vendor.bundle.js:13218:42)
>     at Object.debugCreateRootView [as createRootView] (http://localhost:4200/vendor.bundle.js:12679:12)
>     at ComponentFactory_.create (http://localhost:4200/vendor.bundle.js:10023:46)
>     at ComponentFactoryBoundToModule.create (http://localhost:4200/vendor.bundle.js:3638:29)
>     at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:5220:57)
>     at http://localhost:4200/vendor.bundle.js:5007:79
>     at Array.forEach (native)
>     at PlatformRef_._moduleDoBootstrap (http://localhost:4200/vendor.bundle.js:5007:42)
>     at http://localhost:4200/vendor.bundle.js:4969:27
>     at EventHandlerExtender (http://localhost:4200/main.bundle.js:358:27)
>     at Function.EventHandler.bind (http://localhost:4200/main.bundle.js:71:30)
>     at createClass (http://localhost:4200/vendor.bundle.js:11006:41)
>     at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:10832:37)
>     at createViewNodes (http://localhost:4200/vendor.bundle.js:12182:49)
>     at createRootView (http://localhost:4200/vendor.bundle.js:12087:5)
>     at callWithDebugContext (http://localhost:4200/vendor.bundle.js:13218:42)
>     at Object.debugCreateRootView [as createRootView] (http://localhost:4200/vendor.bundle.js:12679:12)
>     at ComponentFactory_.create (http://localhost:4200/vendor.bundle.js:10023:46)
>     at ComponentFactoryBoundToModule.create (http://localhost:4200/vendor.bundle.js:3638:29)
>     at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:5220:57)
>     at http://localhost:4200/vendor.bundle.js:5007:79
>     at Array.forEach (native)
>     at PlatformRef_._moduleDoBootstrap (http://localhost:4200/vendor.bundle.js:5007:42)
>     at http://localhost:4200/vendor.bundle.js:4969:27
>     at resolvePromise (http://localhost:4200/polyfills.bundle.js:935:31) [<root>]
>     at http://localhost:4200/polyfills.bundle.js:861:17 [<root>]
>     at http://localhost:4200/polyfills.bundle.js:877:33 [<root>]
>     at http://localhost:4200/polyfills.bundle.js:983:57 [<root>]
>     at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:816:35) [<root>]
>     at <anonymous> [<root>]

**Comment by filipesilva** [comment]
If you can provide a simple repro of the problems you are having, we can investigate. As is, your runtime error can be caused by a myriad of factors and there's no way to know what's really happening.
