### ISSUE TITLE
SyntaxError: Use of const in strict mode. Const CliConfig

### ISSUE THREAD

**Issue by Ben10Formis** [angular/angular-cli#6187]
Running off ng serve I am getting the below error.

C:\Users\pc\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng:7
const CliConfig = require('../models/config').CliConfig;

SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by ddimaria** [comment]
What is your version of node? `node -v`

**Comment by Ben10Formis** [comment]
node version 0.10.35 and npm version 3.10.10

**Comment by filipesilva** [comment]
For CLI use we do require node 6.9.0 as minimum: https://github.com/angular/angular-cli#prerequisites
