### ISSUE TITLE
Cannot read property 'sourceDir' of undefined

### ISSUE THREAD

**Issue by ruwhan** [angular/angular-cli#619]
I am filing a bug.

1. OS. Mac OSX El Capitan.

2. Versions:
```
angular-cli: 0.0.37
node: 5.1.0
os: darwin x64
```

3. Repro steps: 
Just run `ng serve`

4. Error logs:
```
 Cannot read property 'sourceDir' of undefined
TypeError: Cannot read property 'sourceDir' of undefined
    at new Angular2App (/Users/ruwhan/Projects/dfci/test-portal/node_modules/angular-cli/lib/broccoli/angular2-app.js:30:40)
    at module.exports (/Users/ruwhan/Projects/dfci/test-portal/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/ruwhan/Projects/dfci/test-portal/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/ruwhan/Projects/dfci/test-portal/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/ruwhan/Projects/dfci/test-portal/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/ruwhan/Projects/dfci/test-portal/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/ruwhan/Projects/dfci/test-portal/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/ruwhan/Projects/dfci/test-portal/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/ruwhan/Projects/dfci/test-portal/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/ruwhan/Projects/dfci/test-portal/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/ruwhan/Projects/dfci/test-portal/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```

**Comment by metric152** [comment]
I ran into this earlier today
https://github.com/angular/angular-cli/issues/616
Found the fixes for it.

**Comment by hansl** [comment]
Your `angular-cli-build.js` should pass an object as option to Angular2App. That object can be empty, but normally should include a `vendorNpmFiles` because we don't provide one for you anymore.

I'll leave this open as an issue that if no options object is passed in we should at least fail properly.

**Comment by nicolaveritas** [comment]
I think it is a bit confusing, from the docs seems that 
```
ng new project
cd project
ng serve
```
should just run

**Comment by AhmedAlgonsel** [comment]
I have the same issue also
I use win 10 
64bit

**Comment by zeljko-bulatovic** [comment]
@AhmedAlgonsel change angular-cli.json to be like:
{
  "routes": [],
  "defaults": {
      "sourceDir": "src/client"
  }
}

Kind regards

**Comment by kamilshahzad** [comment]
i am facing same problem did all what is mentioned above but not resolved.

**Comment by damiendube** [comment]
I've create the file angular-cli.json to be like:
{
"routes": [],
"defaults": {
"sourceDir": "src"
}
}

And after that, I was able to run "ng serve", but this is not a fix. It is a workaround! 
The issue is still present in angular-cli@1.0.0-beta.9, I suggest to re-open this issue until we fix the underling issue.
