### ISSUE TITLE
Generating component into module has a case-sensitive inconsistency

### ISSUE THREAD

**Issue by ShinDarth** [angular/angular-cli#6287]
### Bug Report or Feature Request (mark with an `x`)

- [x] bug report -> please search issues before submitting
- [ ] feature request

### Versions.

@angular/cli: 1.0.3
node: 6.10.3
os: linux x64
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.2

### Repro steps.

- Generate a module with an uppercase initial letter, e.g. ``Assignment3``
- Try to generate a component with the same name, putting it into the module

### The log given by the failure.

```➜  ng-exercises git:(master) ng g module Assignment3
installing module
  create src/app/assignment3/assignment3.module.ts
➜  ng-exercises git:(master) ✗ ng g component --module Assignment3 Assignment3
installing component
EEXIST: file already exists, mkdir '/home/francesco/sources/ng-exercises/src/app/assignment3'
Error: EEXIST: file already exists, mkdir '/home/francesco/sources/ng-exercises/src/app/assignment3'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at parts.reduce (/home/francesco/sources/ng-exercises/node_modules/@angular/cli/utilities/dynamic-path-parser.js:39:16)
    at Array.reduce (native)
    at Object.dynamicPathParser (/home/francesco/sources/ng-exercises/node_modules/@angular/cli/utilities/dynamic-path-parser.js:24:31)
    at buildFullPath (/home/francesco/sources/ng-exercises/node_modules/@angular/cli/utilities/resolve-module-file.js:34:46)
    at Object.resolveModulePath (/home/francesco/sources/ng-exercises/node_modules/@angular/cli/utilities/resolve-module-file.js:25:26)
    at Class.beforeInstall (/home/francesco/sources/ng-exercises/node_modules/@angular/cli/blueprints/component/index.js:107:39)
    at tryCatch (/home/francesco/sources/ng-exercises/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/home/francesco/sources/ng-exercises/node_modules/rsvp/dist/rsvp.js:554:13)
➜  ng-exercises git:(master) ✗ ng g component Assignment3 --module assignment3
installing component
  create src/app/assignment3/assignment3.component.css
  create src/app/assignment3/assignment3.component.html
  create src/app/assignment3/assignment3.component.spec.ts
  create src/app/assignment3/assignment3.component.ts
  update src/app/assignment3/assignment3.module.ts
```

### Desired functionality.

The problem is that it works fine when generating the Component using ``--module assignment3`` but it doesn't work when trying ``--module Assignment3``, which is inconsistent since the component was generated using``ng  module Assignment3``

### Mention any other details that might be useful.

I guess the log result is pretty self-describing, no additional details needed.

**Comment by sumitarora** [comment]
@ShinDarth Is It happening on a new project? I tried to replicate same on a brand new project and seems to be working fine. Which operating system are you on?

**Comment by ShinDarth** [comment]
yes it's a new project, my operating system is Ubuntu 16.04 - 64 bit
