### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed

### ISSUE THREAD

**Issue by Napster2210** [angular/angular-cli#632]
Hello,
I am getting an error while execute the "ng serve" command:
Which is as follow:
Build error

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, symlink 'D:\Angular2\test1\tmp\broccoli_type_script_compiler-cache_path-H5fVKWHY.tmp\src\app\environment.js.map' -> 'D:\Angular2\test1\tmp\broccoli_type_script_compiler-output_path-UW4qCiAZ.tmp\src\app\environment.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at BroccoliTypeScriptCompiler._outputFile (D:\Angular2\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
    at D:\Angular2\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18
    at Array.forEach (native)
    at D:\Angular2\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (D:\Angular2\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (D:\Angular2\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at D:\Angular2\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\Angular2\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\Angular2\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\Angular2\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\Angular2\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (D:\Angular2\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\Angular2\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\Angular2\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (D:\Angular2\test1\node_modules\angular-cli\lib\broccoli\angular2-app.js:280:18)
    at Angular2App._buildTree (D:\Angular2\test1\node_modules\angular-cli\lib\broccoli\angular2-app.js:101:23)
    at new Angular2App (D:\Angular2\test1\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (D:\Angular2\test1\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\Angular2\test1\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\Angular2\test1\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (D:\Angular2\test1\node_modules\angular-cli\node_modules\ember-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\Angular2\test1\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at D:\Angular2\test1\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\Angular2\test1\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\Angular2\test1\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\Angular2\test1\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\Angular2\test1\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

Node Version : v4.4.2
npm Version : 3.8.2
angular-cli info:

{ name: 'angular-cli',
  time:
   { modified: '2016-05-04T16:29:23.054Z',
     created: '2014-10-07T04:34:38.078Z',
     '1.0.0': '2014-10-07T04:34:38.078Z',
     '0.0.0': '2014-10-11T11:38:24.914Z',
     '0.0.1': '2015-08-03T17:12:04.553Z',
     '0.0.2': '2015-10-18T17:46:40.146Z',
     '0.0.3': '2015-10-18T21:42:52.445Z',
     '0.0.4': '2015-10-19T01:14:13.216Z',
     '0.0.5': '2015-10-19T09:14:01.712Z',
     '0.0.6': '2015-10-19T09:36:51.644Z',
     '0.0.7': '2015-10-19T11:48:24.233Z',
     '0.0.8': '2015-10-19T11:51:59.318Z',
     '0.0.9': '2015-10-19T21:18:13.725Z',
     '0.0.10': '2015-10-19T22:18:13.091Z',
     '0.0.11': '2015-11-03T05:03:06.345Z',
     '0.0.12': '2015-11-15T10:10:48.551Z',
     '0.0.13': '2015-12-04T17:16:43.662Z',
     '0.0.14': '2015-12-05T01:40:39.377Z',
     '0.0.15': '2015-12-05T05:50:59.226Z',
     '0.0.16': '2015-12-10T12:23:28.722Z',
     '0.0.17': '2015-12-14T19:37:08.400Z',
     '0.0.18': '2015-12-15T12:51:47.990Z',
     '0.0.19': '2015-12-15T18:23:33.077Z',
     '0.0.20': '2015-12-15T20:39:55.357Z',
     '0.0.22': '2016-02-20T00:36:56.908Z',
     '0.0.23': '2016-02-20T01:44:13.897Z',
     '0.0.24': '2016-02-25T17:41:20.619Z',
     '0.0.25': '2016-03-10T02:10:05.410Z',
     '0.0.26': '2016-03-23T00:39:46.402Z',
     '0.0.27': '2016-03-23T22:05:56.538Z',
     '0.0.28': '2016-03-28T22:39:45.766Z',
     '0.0.29': '2016-03-30T18:10:47.060Z',
     '0.0.30': '2016-04-06T22:27:32.015Z',
     '0.0.31': '2016-04-11T18:20:32.677Z',
     '0.0.33': '2016-04-19T22:31:48.209Z',
     '0.0.34': '2016-04-26T17:56:20.524Z',
     '0.0.37': '2016-05-03T18:49:21.731Z',
     '0.0.39': '2016-05-04T16:29:23.054Z' },
  maintainers:
   [ 'angularcore <angular-core+npm@google.com>',
     'rodyhaddad <npm@rodyhaddad.com>' ],
  description: 'CLI tool for Angular',
  versions:
   [ '0.0.0',
     '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.0.6',
     '0.0.7',
     '0.0.8',
     '0.0.9',
     '0.0.10',
     '0.0.11',
     '0.0.12',
     '0.0.13',
     '0.0.14',
     '0.0.15',
     '0.0.16',
     '0.0.17',
     '0.0.18',
     '0.0.19',
     '0.0.20',
     '0.0.22',
     '0.0.23',
     '0.0.24',
     '0.0.25',
     '0.0.26',
     '0.0.27',
     '0.0.28',
     '0.0.29',
     '0.0.30',
     '0.0.31',
     '0.0.33',
     '0.0.34',
     '0.0.37',
     '0.0.39' ],
  'dist-tags': { latest: '0.0.39' },
  readmeFilename: 'README.md',
  homepage: 'https://github.com/angular/angular-cli',
  keywords: [],
  repository:
   { type: 'git',
     url: 'git+https://github.com/angular/angular-cli.git' },
  author: 'Angular Authors',
  bugs: { url: 'https://github.com/angular/angular-cli/issues' },
  license: 'MIT',
  contributors:
   [ 'Rody Haddad <npm@rodyhaddad.com> (http://rodyhaddad.com/)',
     'Igor Minar <igor@angularjs.org>' ],
  users: { altrim: true, seachange: true },
  version: '0.0.39',
  main: 'lib/cli/index.js',
  trackingCode: 'UA-8594346-19',
  bin: { ng: './bin/ng' },
  scripts: { test: 'node tests/runner', lint: 'eslint .' },
  engines: { node: '>= 4.1.0' },
  dependencies:
   { broccoli: '^1.0.0-beta.7',
     'broccoli-caching-writer': '^2.2.1',
     'broccoli-concat': '^2.2.0',
     'broccoli-funnel': '^1.0.1',
     'broccoli-merge-trees': '^1.1.1',
     'broccoli-source': '^1.1.0',
     'broccoli-writer': '^0.1.1',
     chalk: '^1.1.3',
     'ember-cli': '2.5.0',
     'ember-cli-string-utils': '^1.0.0',
     exit: '^0.1.2',
     'fs-extra': '^0.30.0',
     glob: '^7.0.3',
     leek: '0.0.21',
     lodash: '^4.11.1',
     opn: '4.0.1',
     resolve: '^1.1.7',
     shelljs: '^0.7.0',
     'silent-error': '^1.0.0',
     'symlink-or-copy': '^1.0.3',
     'systemjs-builder': '^0.15.16',
     typescript: '^1.8.10',
     typings: '^0.8.1' },
  'ember-addon': { paths: [ './addon/ng2/' ] },
  devDependencies:
   { chai: '^3.5.0',
     'clang-format': '^1.0.38',
     eslint: '^2.8.0',
     'exists-sync': '0.0.3',
     minimatch: '^3.0.0',
     mocha: '^2.4.5',
     'mock-fs': '^3.8.0',
     'object-assign': '^4.0.1',
     rewire: '^2.5.1',
     sinon: '^1.17.3',
     through: '^2.3.8',
     tslint: '^3.8.1',
     'walk-sync': '^0.2.6' },
  gitHead: '8a15f90ccc6783196069325cd9249326424275b0',
  dist:
   { shasum: '89f55716f31a6e517f6404a6fd7f360292c893ed',
     tarball: 'https://registry.npmjs.org/angular-cli/-/angular-cli-0.0.39.tgz'
},
  directories: {} }

Can you please help me out?

Thanx in advance.

**Comment by CosticaPuntaru** [comment]
same here, os windows 10

**Comment by dpsthree** [comment]
+1 Windows 10, node 5.10.1

**Comment by dpsthree** [comment]
Running as admin fixed this for me.

**Comment by Napster2210** [comment]
Thanx @dpsthree . By running in admin mode its worked for me.

**Comment by hashmee** [comment]
same error not working on my mac

**Comment by Napster2210** [comment]
@hasmee, open your terminal using admin rights and then try to run commands again

**Comment by hashmee** [comment]
yeah done it but bit differently 
just passed the file or dir permissions to configstore directory made my ng serve east 
thankyou @Napster2210

**Comment by filipesilva** [comment]
On the latest version (beta.8) we've fixed the need for admin mode.
