### ISSUE TITLE
node_modules/caniuse-db/data.json: Unexpected end of JSON input

### ISSUE THREAD

**Issue by changalberto** [angular/angular-cli#6398]
Getting error while trying to serve the project with the latest cli 1.04
```
ng serve
/Users/[username]/Downloads/project/node_modules/caniuse-db/data.json: Unexpected end of JSON input
SyntaxError: /Users/[username]/Downloads/project/node_modules/caniuse-db/data.json: Unexpected end of JSON input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/[username]/Downloads/project/node_modules/browserslist/index.js:5:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/[username]/Downloads/project/node_modules/autoprefixer/lib/autoprefixer.js:5:18)
```

**Comment by changalberto** [comment]
Disregard. This was due to download corruption... Had to yarn cache clean and reinstall it.
