### ISSUE TITLE
ng generate, adding package.json checks

### ISSUE THREAD

**Issue by glebmachine** [angular/angular-cli#6413]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.4
node: 6.9.2
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.4
@angular/compiler-cli: 4.1.0
@angular/service-worker: 1.0.0-beta.11
```

### Repro steps.
Generate new project
Remove ```name``` from ```package.json```

### The log given by the failure.
```
: ng g module demo
installing module
Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at decamelize (/Users/glebmikheev/dokuro/prj/ccff/node_modules/ember-cli-string-utils/index.js:26:13)
    at Object.dasherize (/Users/glebmikheev/dokuro/prj/ccff/node_modules/ember-cli-string-utils/index.js:51:11)
    at Class.<anonymous> (/Users/glebmikheev/dokuro/prj/ccff/node_modules/@angular/cli/ember-cli/lib/models/blueprint.js:861:42)
    at tryCatch (/Users/glebmikheev/dokuro/prj/ccff/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/glebmikheev/dokuro/prj/ccff/node_modules/rsvp/dist/rsvp.js:554:13)
    at /Users/glebmikheev/dokuro/prj/ccff/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/Users/glebmikheev/dokuro/prj/ccff/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Desired functionality.
Please, add few checks into cli.

**Comment by glebmachine** [comment]
❤️
