### ISSUE TITLE
@angular/cli 1.0.5 crashes on localhost:4200 if module_2 imports module_1 in @NgModule

### ISSUE THREAD

**Issue by XaodDaSlayer** [angular/angular-cli#6456]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.0.5
node: 7.4.0
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.5
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.5
@angular/compiler-cli: 4.1.3

### Repro steps.
I have two projects created with angular-cli (let's call them module_1 and module_2)
module_2 depends on module_1

module_1 declares:
`@NgModule(
...
)
export class EngAppModule {
...
}`

module_2 declares:
`@NgModule({
...
  imports: [
    EngAppModule
  ],
...
})
export class AppModule {
...
}`

commands:
npm link (from module_1 folder)
npm link module_1 (from module_2 folder)
ng serve (from module_2 folder)
login on localhost:4200

### The log given by the failure.
Uncaught Error: Unexpected value 'EngAppModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:4200/vendor.bundle.js:30261:34)
    at http://localhost:4200/vendor.bundle.js:43215:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:43198:49)
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:54351:66)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:54310:52)
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:54272:23)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:5222:25)
    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:5208:21)
    at Object.<anonymous> (http://localhost:4200/main.bundle.js:79083:124)

### Mention any other details that might be useful.
Error on any angular-cli version greater than 1.0.3 (that is, same bug on versions 1.0.4 and 1.1.0-rc.1)

**Comment by clydin** [comment]
Please see the [documentation here](https://github.com/angular/angular-cli/wiki/stories-linked-library) for information pertaining to the use of linked libraries during development.

**Comment by sumitarora** [comment]
Closing as above.
