### ISSUE TITLE
easter egg command is broken

### ISSUE THREAD

**Issue by spboyer** [angular/angular-cli#649]
Don't want to give it away...
```
Cannot find module 'angular-cli/lib/utilities/string'
Error: Cannot find module 'angular-cli/lib/utilities/string'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Class.Command.extend.run (/Users/shayneboyer/projects/myngapp/node_modules/angular-cli/addon/ng2/commands/easter-egg.ts:13:31)
    at Class.<anonymous> (/Users/shayneboyer/projects/myngapp/node_modules/angular-cli/node_modules/angular-cli/lib/models/command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (/Users/shayneboyer/projects/myngapp/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/shayneboyer/projects/myngapp/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/shayneboyer/projects/myngapp/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/shayneboyer/projects/myngapp/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by hansl** [comment]
We should test that one. We'll fix it.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/725/
