### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed at ComponentFixture

### ISSUE THREAD

**Issue by deerawan** [angular/angular-cli#654]
## OS
Max OSX El Capitan

## Angular CLI Version
angular-cli: 0.0.39
node: 4.1.2
os: darwin x64

## Reproduce Steps
1. Run `ng new sample-app`
2. Go to the root folder. Run `ng serve`
3. Run `ng g directive my-new-directive`
4. It will show the error

```
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/deerawan/Work/Sites/practice/test-angular2-part2/tmp/broccoli_type_script_compiler-input_base_path-5VgJxx5Y.tmp/0/src/app/my-new-directive.directive.spec.ts (25, 58): Generic type 'ComponentFixture<T>' requires 1 type argument(s).
```

## Possible Cause
it should be ComponentFixture<any> for directive spec js

## Action
I can create PR for this one. 😄

**Comment by n1alloc** [comment]
Guys, having the same problem, what steps do I need to take to resolve?

**Comment by iamkdev** [comment]
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, symlink .........

Solution ?

**Comment by Meistercoach83** [comment]
@iamkdev are you developing on a windows machine? then try to run the command with admin rights

**Comment by Dhakshan** [comment]
Error: Typescript found the following errors:
  C:/xampp/htdocs/projects/do/angular-cli/do/tmp/broccoli_type_script_compiler-input_base_path-xSfzIzkc.tmp/0/src/app/directive/parallax.directive.spec.ts (25, 58): Generic type 'ComponentFixture<T>' requires 1 type argument(s).
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:115:19)
    at BroccoliTypeScriptCompiler.build (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:149:21
    at tryCatch (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:18:10)
    at BroccoliTypeScriptCompiler (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:26:49)
    at Angular2App._getTsTree (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\lib\broccoli\angular2-app.js:280:18)
    at Angular2App._buildTree (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\lib\broccoli\angular2-app.js:101:23)
    at new Angular2App (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (C:\xampp\htdocs\projects\do\angular-cli\do\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\ember-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at tryCatch (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (C:\xampp\htdocs\projects\do\angular-cli\do\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2373:5)

**Comment by Dhakshan** [comment]
I am getting this error with angular-cli. Also running in administrator mode.

**Comment by iamkdev** [comment]
It fixed for me but I forget what I exactly deed.
I think I did `npm cache clean`
