### ISSUE TITLE
 SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by RaZzitx** [angular/angular-cli#6573]
IM TRYING TO GET THE HASH OF MY CSGO WEBSITE BUT THIS STILL DONT WORKING HOW CAN I FIX THAT:
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Server.init (/var/www/html/Bot/BOT/node_modules/socket.io/node_modules/engine.io/lib/server.js:119:16)
    at new Server (/var/www/html/Bot/BOT/node_modules/socket.io/node_modules/engine.io/lib/server.js:65:8)
    at Function.attach (/var/www/html/Bot/BOT/node_modules/socket.io/node_modules/engine.io/lib/engine.io.js:123:16)
    at /var/www/html/Bot/BOT/node_modules/socket.io/lib/index.js:258:23

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
