### ISSUE TITLE
--host 0.0.0.0 does not work (related to webpack)

### ISSUE THREAD

**Issue by gyuho** [angular/angular-cli#6576]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
./node_modules/.bin/ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.6
node: 6.10.0
os: darwin x64
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/compiler-cli: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/animations: 4.0.3
@angular/router: 4.0.3
@angular/tsc-wrapped: 4.0.3
@angular/upgrade: 4.0.3
@angular/cli: 1.0.6
@angular/material: 2.0.0-beta.6
```

### Repro steps.

I am using Angular 2 + Angular CLI, which depends on webpack. According to https://github.com/webpack/webpack-dev-server/issues/882, `--host 0.0.0.0` does not work anymore, however Angular CLI still recommends this, as far as I know (https://github.com/angular/angular-cli/issues/2587#issuecomment-252586913). So there seems to be no way to set `--host` with public IP.

### The log given by the failure.

```
yarn start-prod v0.24.5
$ ng serve --prod --host 104.196.246.116 --proxy-config proxy.config.json
Provided host 104.196.246.116 could NOT be bound. Please provide a different host address or hostname
Error: Provided host 104.196.246.116 could NOT be bound. Please provide a different host address or hostname
    at /project/node_modules/portfinder/lib/portfinder.js:139:27
    at /project/node_modules/async/lib/async.js:52:16
    at /project/node_modules/async/lib/async.js:264:21
    at /project/node_modules/async/lib/async.js:44:16
    at /project/node_modules/portfinder/lib/portfinder.js:117:16
    at Server.onError (/project/node_modules/portfinder/lib/portfinder.js:54:14)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error Command failed with exit code 1.
```

### Desired functionality.

Angular CLI should allow serve on public IP host.

### Mention any other details that might be useful.

~I think this only happens in production mode~ (happens in both modes).

Is there any workaround?

Thanks in advance!

**Comment by gyuho** [comment]
Upgrading to https://github.com/angular/angular-cli/releases/tag/v1.2.0-beta.0 resolved it :)
