### ISSUE TITLE
ng test for a newly generated prj - throws error

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#660]
Windows 10.

Generated new project. Build works, serve too. NG TEST gives me this:

____________________________________________

Built project successfully. Stored in "dist/".

Build successful - 2090ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
BroccoliTypeScriptCompiler                    | 963ms
vendor                                        | 754ms
SASSPlugin                                    | 137ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
BroccoliTypeScriptCompiler (1)                | 963ms
vendor (1)                                    | 754ms
Funnel (9)                                    | 146ms (16 ms)
SASSPlugin (1)                                | 137ms

06 05 2016 20:40:40.702:WARN [karma]: No captured browser, open http://localhost:9876/
06 05 2016 20:40:40.719:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
06 05 2016 20:40:40.724:INFO [launcher]: Starting browser Chrome
06 05 2016 20:40:41.681:INFO [Chrome 50.0.2661 (Windows 10 0.0.0)]: Connected on socket /#ThBerYRjb-DWwojsAAAA with id 45303651
Missing error handler on `socket`.
**TypeError: (msg || "").replace is not a function**
    at D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\lib\reporter.js:45:23
    at onBrowserError (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\lib\reporters\base.js:58:60)
    at null.<anonymous> (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at onKarmaError (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\lib\browser.js:95:13)
    at Socket.<anonymous> (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\lib\events.js:13:22)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Socket.onevent (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\node_modules\socket.io\lib\socket.js:335:8)
    at Socket.onpacket (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\node_modules\socket.io\lib\socket.js:295:12)
    at Client.ondecoded (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\node_modules\socket.io\lib\client.js:193:14)
    at Decoder.Emitter.emit (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\node_modules\socket.io\node_modules\socket.io-parser\node_modules\component-emitter\index.js:134:20)
    at Decoder.add (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\node_modules\socket.io\node_modules\socket.io-parser\index.js:247:12)
    at Client.ondata (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\node_modules\socket.io\lib\client.js:175:18)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Socket.onPacket (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\node_modules\socket.io\node_modules\engine.io\lib\socket.js:101:14)
    at emitOne (events.js:90:13)
    at WebSocket.emit (events.js:182:7)
    at WebSocket.Transport.onPacket (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\node_modules\socket.io\node_modules\engine.io\lib\transport.js:104:8)
    at WebSocket.Transport.onData (D:\Documents\Visual Studio 2015\Projects\NewsNotifier\node_modules\karma\node_modules\socket.io\node_modules\engine.io\lib\transport.js:115:8)
06 05 2016 20:40:44.730:WARN [Chrome 50.0.2661 (Windows 10 0.0.0)]: Disconnected (1 times)

**Comment by alvipeo** [comment]
Nevermind, fixed by upgrading to the latest CLI.
