### ISSUE TITLE
Cannot find module 'webpack/lib/node/NodeTemplatePlugin' using cli 1.1.1

### ISSUE THREAD

**Issue by qwert789** [angular/angular-cli#6641]
## OS?
@angular/cli: 1.1.1
node: 8.0.0
os: win32 x64 (Windows 10)
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3

## Repro steps:
1. Install node 8 & @angular/cli: 1.1.1
2. ng new demo
3. npm start

## Failure message:
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\ng413\demo\node_modules\html-webpack-plugin\lib\compiler.js:11:26)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\ng413\demo\node_modules\html-webpack-plugin\index.js:7:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

**Comment by Markus-Ende** [comment]
Same here on Linux Mint 18 Sarah

**Comment by thefill** [comment]
@Markus-Ende solution worked for me. Thx!

**Comment by toddwseattle** [comment]
this worked for me as well.  might be nice to see a note in the 'upgrading section'.

**Comment by GuissiMedAli** [comment]
how to delete the package lock ?

**Comment by MoxxNull** [comment]
@Markus-Ende  That did the trick, thank you!

**Comment by treeder** [comment]
Could someone explain why we need to delete the lock file?

**Comment by jkyoutsey** [comment]
I've deleted my lock file and I still get the error.  Every time you do an npm install it's going to add the lock file back.

**Comment by klaascuvelier** [comment]
I have this same issue with angular-cli@1.2.0, but only on our test server, not locally.

I'm not a fan of removing the package-lock file. 
Adding webpack as dev-dependency worked for m (got the idea here https://github.com/webpack/webpack/issues/2060). It's not optimal either, but it seems okay is a temporary fix.

**Comment by piernik** [comment]
Had the same problem - installing `npm i webpack --save-dev` sloved it

**Comment by nulllpointer** [comment]
Thanks, this solved the issue!!!!

**Comment by Markus-Ende** [comment]
@treeder the package-lock prevented a new webpack version to be installed (it's like the former npm-shrinkwrap). The version defined in the package-lock file beats the version defined in package.json, so `npm i` just reinstalled the old webpack files. Deleting the package-lock and then running  `npm i` creates a whole new package-lock file with the latest package versions according to package.json. If you just want to refresh webpack, you can just directly install it via `npm i webpack --save-dev`as @piernik said. Directly installing a package always refreshs the package-lock.

For further documentation about the package-lock see [the npm lockfiles documentation on docs.npmjs.com](https://docs.npmjs.com/files/package-locks)

**Comment by goeranhomberg** [comment]
> npm i webpack --save-dev
worked for me. Thx for the hint 👍

**Comment by dev-niiaddy** [comment]
@Markus-Ende thank you. You saved my life... I almost went nuts

**Comment by Feyrr007** [comment]
npm i webpack --save-dev
Workded for me too. Thanks so much!

**Comment by aniruddhadas9** [comment]
below 2 steps worked for me.

1. delete `node_module` and `package-lock.json`
2. install the node modules by `npm i`

**Comment by MateuszKita** [comment]
If somebody will have next issue - _"Cannot read property 'thisCompilation' of undefined"_ after
`npm i webpack --save-dev` or deleting _package-lock.json_ and reinstalling _node_modules_
please try 
```
npm remove webpack
npm install webpack@3.11.0
```

**Comment by SerkanSipahi** [comment]
after removing the `package-lock.json` it worked for me, thank you :)

**Comment by satvik1986** [comment]
Angular Live Development Server is listening on localhost:4300, open your browser on http://localhost:4300/ **
 65% building modules 466/507 modules 41 active …modules\core-js\modules\_string-html.js× ｢wdm｣: Error: No module factory available for dependency type: ContextElementDependency
    at addDependency (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:407:12)
    at iterationOfArrayCallback (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:88:3)
    at addDependenciesBlock (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:423:5)
    at iterationOfArrayCallback (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:88:3)
    at addDependenciesBlock (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:426:5)
    at Compilation.processModuleDependencies (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:434:4)
    at afterBuild (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:556:15)
    at buildModule.err (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:600:11)
    at callback (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:358:35)
    at module.build.error (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:394:12)
    at resolveDependencies (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ContextModule.js:233:4)
    at ContextModule.result.resolveDependencies (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:476:25)
    at ContextModule.build (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ContextModule.js:158:8)
    at Compilation.buildModule (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:362:10)
    at factory.create (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compilation.js:583:14)
    at hooks.afterResolve.callAsync (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\ContextModuleFactory.js:150:16)
D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\neo-async\async.js:14
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\neo-async\async.js:14:11)
    at D:\Working\JainConnection\Dev\JainConnectionWebSite\node_modules\neo-async\async.js:2805:7
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by HuangHongRui** [comment]
> npm i webpack --save-dev
worked for me. 3Q 👍

**Comment by MsaadAl** [comment]
The error you're all facing is only because webpack version, the latest update v4 has a lot of issue, the solution you need is just reinstall webpack again with 3.12.0 and it will work. This version cause a lot of error, and this is the solution I solve the error with. and it works now perfect. I hope that help

**Comment by michaelcmundo** [comment]
I got the same issue and I tried webpack@3.12.0 but still got that error. But I got this warning when install older version.

npm i webpack@3.12.0 --save-dev
npm WARN @ngtools/webpack@7.0.6 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by aaa123eee** [comment]
got same, update to 7.2 helps to me

**Comment by ishandutta2007** [comment]
@piernik 's solution didn't solve it for me,
This did:
```
npm remove webpack
npm install webpack@3.11.0
```
My `@angular is 5.0.5` and `@angular/cli is 1.6.4`
