### ISSUE TITLE
Error after installing npm libraries after upgrading to npm 5

### ISSUE THREAD

**Issue by YonatanKra** [angular/angular-cli#6642]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.0.4
node: 7.0.0
os: win32 x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.4
@angular/compiler-cli: 4.1.3

### Repro steps.

Create a new project. Install @angular/material or @angular-redux/store:
`npm install --save redux @angular-redux/store` or `npm install --save @angular/material`.
Then try to rerun `ng serve`

### The log given by the failure.

```
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (\WebstormProjects\test-project\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (\WebstormProjects\test-project\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
```
### Desired functionality.

I'd expect that after the `npm installs` the project would work with the new libs.

### Mention any other details that might be useful.

It used to work in the past. The only change I can think of is the upgrade to `npm 5`.
I've fixed it by manually installing `@angular` and `rxjs`, `zone.js` and `core-js`.

**Comment by intellix** [comment]
Check your package-lock.json, is it there?

**Comment by YonatanKra** [comment]
yes it is

On 11 Jun 2017 12:49, "Dominic Watson" <notifications@github.com> wrote:

Check your package-lock.json, is it there?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angular-cli/issues/6642#issuecomment-307617660>,
or mute the thread

**Comment by cedvdb** [comment]
This might help https://stackoverflow.com/a/44368377/4299560

**Comment by YonatanKra** [comment]
Works like a charm. Thanks :)
