### ISSUE TITLE
Error: Cannot find module '../models/config'

### ISSUE THREAD

**Issue by msnhari** [angular/angular-cli#6643]
After installing Angular-CLI this is the error it get when I use ng 

C:\Users\username>ng init
module.js:471
    throw err;
    ^

Error: Cannot find module '../models/config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng:7:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Win 10
node -v : v6.10.2
npm -v: 3.10.10

**Comment by gioragutt** [comment]
@msnhari please edit your issue to follow the [issue template](https://github.com/angular/angular-cli/blob/master/.github/ISSUE_TEMPLATE.md).

And on the topic, use `ng new` instead of `ng init` for app creation. F.E:
```
cd /path/to/repos/folder
ng new my-new-proj
cd my-new-proj
ng serve
```

I recommend running `ng help new` to look at all available options for `ng new`. Good luck!

**Comment by Brocco** [comment]
The `init` command has been removed, please use `ng new` to create new projects as stated by @gioragutt above.
