### ISSUE TITLE
Universal angular error in webpack

### ISSUE THREAD

**Issue by maphi88** [angular/angular-cli#6658]
Out of no where my application stopped running

This is my package.json
```
{
  "name": "maphisha",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ung serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ung test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/platform-server": "2.2.3",
    "@angular/router": "3.2.3",
    "angular-2-local-storage": "^1.0.1",
    "angular2-cookie": "^1.2.6",
    "angular2-express-engine": "2.1.0-rc.1",
    "angular2-platform-node": "2.1.0-rc.1",
    "angular2-universal": "2.1.0-rc.1",
    "angular2-universal-polyfills": "2.1.0-rc.1",
    "chart.js": "^2.6.0",
    "compression": "1.6.2",
    "core-js": "^2.4.1",
    "express": "^4.14.0",
    "ng-lazyload-image": "^3.1.1",
    "ng2-charts": "^1.6.0",
    "ng2-flatpickr": "^0.1.14",
    "ng2-img-cropper": "^0.8.8",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.3",
    "@types/body-parser": "0.0.29",
    "@types/compression": "0.0.29",
    "@types/cookie-parser": "^1.3.29",
    "@types/express": "^4.0.29",
    "@types/express-serve-static-core": "^4.0.29",
    "@types/jasmine": "2.5.38",
    "@types/mime": "0.0.28",
    "@types/node": "^6.0.42",
    "@types/serve-static": "^1.7.27",
    "angular-router-loader": "^0.6.0",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.0.2",
    "typescript": "~2.0.3",
    "universal-cli": "1.0.0-alpha.universal.3"
  }
}
```
The Error I am getting
** Universal-cli Development Server is running on http://localhost:4200. **
 70% building modules 891/891 modules 0 active/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/@ngtools/webpack/src/plugin.js:157
                _this.done.then(function () {
@ngtools/webpack/src/plugin.js:157
                _this.done.then(function () {
                          ^

TypeError: Cannot read property 'then' of null
    at ContextModuleFactory.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/@ngtools/webpack/src/plugin.js:157:27)
    at ContextModuleFactory.applyPluginsAsyncWaterfall (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/tapable/lib/Tapable.js:208:13)
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/ContextModuleFactory.js:82:11
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/async/lib/async.js:726:13
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/async/lib/async.js:236:30)
    at _parallel (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/async/lib/async.js:731:9)
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/ContextModuleFactory.js:64:9
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/tapable/lib/Tapable.js:204:11
    at ContextModuleFactory.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/@ngtools/webpack/src/plugin.js:151:24)
    at ContextModuleFactory.applyPluginsAsyncWaterfall (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/tapable/lib/Tapable.js:208:13)
    at ContextModuleFactory.create (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/ContextModuleFactory.js:26:7)
    at async.forEach._this (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/Compilation.js:211:11)
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/Compilation.js:192:8)
    at Compilation.processModuleDependencies (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/Compilation.js:177:7)
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/Compilation.js:317:12
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/Compilation.js:124:4
    at Array.forEach (native)
    at callback (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/Compilation.js:123:12)
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/Compilation.js:147:10
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/NormalModule.js:209:10
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/webpack/lib/NormalModule.js:164:10
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at Storage.finished (/Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /Applications/XAMPP/xamppfiles/htdocs/angular2_website/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)

**Comment by rrundle** [comment]
I got the exact same error out of nowhere today :(. Have a pretty identical package.json to you. 

I tried deleting node modules and running npm install... no dice.

**Comment by rrundle** [comment]
@maphi88 are you trying to run a node module on the client? This was my problem. Double check that you aren't running any node modules in a client-side file.

**Comment by Brocco** [comment]
@maphi88 it appears you're using `universal-cli` please create your issue on that repo... https://github.com/devCrossNet/universal-cli
