### ISSUE TITLE
 "./node_modules/.bin/ng-xi18n"  doesn't work properly

### ISSUE THREAD

**Issue by Tryptich** [angular/angular-cli#6663]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
node: 6.10.0   
Windows (7/8/10).

### Repro steps.
 "./node_modules/.bin/ng-xi18n"

### The log given by the failure.
$ "./node_modules/.bin/ng-xi18n"                                                                                                                                                                              

> Error:  Illegal  state: symbol without members expected, but got {"filePath":"C:/dev/appvotion/workspace/lekiosque-web/src/app/constant-util.ts","name":"ConstantUtil","members":["PRIMARY_ENTRY"]}.            
    at StaticSymbol.assertNoMembers (C:\dev\appvotion\workspace\lekiosque-web\node_modules\@angular\compiler\bundles\compiler.umd.js:700:19)                                                                  
    at AotSummaryResolver.resolveSummary (C:\dev\appvotion\workspace\lekiosque-web\node_modules\@angular\compiler\bundles\compiler.umd.js:25554:22)                                                           
    at CompileMetadataResolver._loadSummary (C:\dev\appvotion\workspace\lekiosque-web\node_modules\@angular\compiler\bundles\compiler.umd.js:15100:66)                                                        
    at CompileMetadataResolver._getEntryComponentMetadata (C:\dev\appvotion\workspace\lekiosque-web\node_modules\@angular\compiler\bundles\compiler.umd.js:15917:49)                                          
    at C:\dev\appvotion\workspace\lekiosque-web\node_modules\@angular\compiler\bundles\compiler.umd.js:15899:48                                                                                               
    at Array.forEach (native)                                                                                                                                                                                 
    at CompileMetadataResolver._getEntryComponentsFromProvider (C:\dev\appvotion\workspace\lekiosque-web\node_modules\@angular\compiler\bundles\compiler.umd.js:15898:30)                                     
    at C:\dev\appvotion\workspace\lekiosque-web\node_modules\@angular\compiler\bundles\compiler.umd.js:15862:83                                                                                               
    at Array.forEach (native)                                                                                                                                                                                 
    at CompileMetadataResolver._getProvidersMetadata (C:\dev\appvotion\workspace\lekiosque-web\node_modules\@angular\compiler\bundles\compiler.umd.js:15825:19)                                               
Extraction failed                                                                                                                         

### Desired functionality.
how to fix that ?
### Mention any other details that might be useful.                  
@angular/cli: 1.0.3                                                                                                                                                                   
@angular/animations: 4.2.2                                                
@angular/common: 4.2.2                                                    
@angular/compiler: 4.2.2                                                  
@angular/compiler-cli: 4.2.2                                              
@angular/core: 4.2.2                                                      
@angular/forms: 4.2.2                                                     
@angular/http: 4.2.2                                                      
@angular/material: 2.0.0-beta.6                                           
@angular/platform-browser: 4.2.2                                          
@angular/platform-browser-dynamic: 4.2.2                                  
@angular/platform-server: 4.2.2                                           
@angular/router: 4.2.2                                                    
@angular/cli: 1.0.3                                                       
  I have a file constant-util where i declare all my global var as static.      
[https://github.com/angular/angular/issues/16477](16477)

**Comment by Tryptich** [comment]
@ocombe pls can you also fixe trouble which happening during extraction due to sass ?

**Comment by ocombe** [comment]
If you use the cli you should not call ng-xi18n yourself from within the node_modules folder, exactly for your problem: the ng-xi18n cli tool doesn't understand sass, and things like that.
You should use "ng xi18n", see this story from the docs: https://github.com/angular/angular-cli/wiki/stories-internationalization

**Comment by Tryptich** [comment]
thanks
