### ISSUE TITLE
Changing the module to system and specifying an outile causes duplicate file error on build

### ISSUE THREAD

**Issue by elliot-j** [angular/angular-cli#671]
After creating a new project and changing  the `module `to system and specifying an `outfile` in the app tsconfig, I get an an error saying that the file specified by `outfile` file already exists.

Platform details
windows 10
npm v 3.8.3

tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "system",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "outDir": "../dist/",
    "outFile": "my-lib.js",
    "rootDir": ".",
    "target": "es5",
  },

  "files": [
    "main.ts",
    "typings.d.ts"
  ]
}

```
Error logged to console
```
Build failed.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EEXIST: file already exists, symlink 'C:\dev\repos\my-lib\tmp\broccoli_type_script_compiler-cache_path-zsLv0ymW.tmp\my-lib.js' -> 'C:\dev\repos\my-lib\tmp\broccoli_type_script_compiler-output_path-nFXX6WIf.tmp\my-lib.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at BroccoliTypeScriptCompiler._outputFile (C:\dev\repos\my-lib\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
    at C:\dev\repos\my-lib\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18
    at Array.forEach (native)
    at C:\dev\repos\my-lib\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\dev\repos\my-lib\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (C:\dev\repos\my-lib\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\dev\repos\my-lib\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (C:\dev\repos\my-lib\node_modules\angular-cli\lib\broccoli\angular2-app.js:280:18)
    at Angular2App._buildTree (C:\dev\repos\my-lib\node_modules\angular-cli\lib\broccoli\angular2-app.js:101:23)
    at new Angular2App (C:\dev\repos\my-lib\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (C:\dev\repos\my-lib\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\dev\repos\my-lib\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
]
```

**Comment by hansl** [comment]
It's a known issue with System modules, which is why we moved to commonjs format.
