### ISSUE TITLE
Error: Debug Failure. False expression: Output generation failed

### ISSUE THREAD

**Issue by madhur** [angular/angular-cli#6736]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.0
node: 7.5.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

### Repro steps.
This can be reproduced by adding primeng into your project. https://github.com/primefaces/primeng

Do not use `npm` command to add. But instead add the library as the source code.

### The log given by the failure.
```
ERROR in ./src/app/shared/primeng/components/dropdown/dropdown.d.ts
Module build failed: Error: Debug Failure. False expression: Output generation failed
    at Object.assert (/Users/madhur/workspace/onedirect-publish-ui/node_modules/typescript/lib/typescript.js:3329:23)
    at Object.transpileModule (/Users/madhur/workspace/onedirect-publish-ui/node_modules/typescript/lib/typescript.js:80449:18)
    at TypeScriptFileRefactor.transpile (/Users/madhur/workspace/onedirect-publish-ui/node_modules/@ngtools/webpack/src/refactor.js:161:27)
    at Promise.resolve.then.then.then.then (/Users/madhur/workspace/onedirect-publish-ui/node_modules/@ngtools/webpack/src/loader.js:378:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./src/app/shared/shared.module.ts 12:0-74
 @ ./src/app/pages/schedule/schedule.module.ts
 @ ./src async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:4201 webpack/hot/dev-server ./src/main.ts
```

**Comment by filipesilva** [comment]
You might want to open a bug in `https://github.com/primefaces/primeng` instead, it sounds like they have a problem with their `d.ts` files.
