### ISSUE TITLE
running 'npm install' get the ERROR: events.js:160       throw er; // Unhandled 'error' event       ^  Error: unexpected end of file     at Zlib._handle.onerror (zlib.js:370:17)

### ISSUE THREAD

**Issue by huberyh** [angular/angular-cli#6747]
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
- ms@0.6.2 node_modules/conditional/node_modules/debug/node_modules/ms
- debug@2.1.1 node_modules/conditional/node_modules/debug
- ms@0.6.2 node_modules/conditional/node_modules/debug/node_modules/ms/node_modules/conditional/node_modules/debug/node_modules/ms
- debug@2.1.1 node_modules/conditional/node_modules/debug/node_modules/ms/node_modules/conditional/node_modules/debug
- es6-promise@4.1.0 node_modules/es6-promisify/node_modules/es6-promise
- conditional@5.3.0 node_modules/conditional
- conditional@5.2.0 node_modules/conditional/node_modules/debug/node_modules/ms/node_modules/conditional
- es6-promisify@5.0.0 node_modules/es6-promisify
- optional-js@1.2.1 node_modules/optional-js
HealthPocket@26.0.0 /Users/huberyh/Workspace/hiiStore
└── shortTermQuote@11.5.0  (git+https://093763137b5cb07575024640672ee81c801b15ec:x-oauth-basic@github.com/healthpocket/stmQuoteEngine.git#47357b3dfdbad9d09434e773515925688c3d7c8e)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! mongodb-prebuilt@5.0.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mongodb-prebuilt@5.0.8 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongodb-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mongodb-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mongodb-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/huberyh/Workspace/hiiStore/npm-debug.log
```
Does someone have idea of this?

**Comment by filipesilva** [comment]
This is either a problem in your npm install or on the library mentioned on that error log. Sorry I can't be of more help.
