### ISSUE TITLE
Projectname with Dot breaks CLI (especially e2e tests )

### ISSUE THREAD

**Issue by CanKattwinkel** [angular/angular-cli#6767]
### Bug Report or Feature Request (mark with an `x`)
- [X] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
 ```
   _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.3
node: 7.7.3
os: linux x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/service-worker: 1.0.0-beta.16
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4
```

### Repro steps.
```
ng new test.de
./node_modules/.bin/ngc 
```

### The log given by the failure.

```
Error at /home/user/test.de/e2e/app.po.ts:3:18: '{' expected.
Error at /home/user/test.de/e2e/app.po.ts:3:19: Cannot find name 'DePage'.
Error at /home/user/test.de/e2e/app.po.ts:3:26: ';' expected.
Error at /home/user/test.de/e2e/app.po.ts:4:3: Cannot find name 'navigateTo'.
Error at /home/user/test.de/e2e/app.po.ts:4:16: ';' expected.
Error at /home/user/test.de/e2e/app.po.ts:8:3: Cannot find name 'getParagraphText'.
Error at /home/user/test.de/e2e/app.po.ts:8:3: Unreachable code detected.
Error at /home/user/test.de/e2e/app.po.ts:8:22: ';' expected.
Error at /home/user/test.de/e2e/app.e2e-spec.ts:1:14: ',' expected.
Error at /home/user/test.de/e2e/app.e2e-spec.ts:1:15: Module '"/home/user/test.de/e2e/app.po"' has no exported member 'DePage'.
Error at /home/user/test.de/e2e/app.e2e-spec.ts:4:13: Cannot find namespace 'Test'.
Error at /home/user/test.de/e2e/app.e2e-spec.ts:7:21: Property 'DePage' does not exist on type 'typeof Test'.

```

### What happens.
If you enter a project name with a dot (e.g. "test.de") this will break code generation for e2e tests. Take a loot at the invalid class name `Test.DePage` in this file:

**e2e/app.po.ts** 
```
import { browser, by, element } from 'protractor';

export class Test.DePage {
  navigateTo() {
    return browser.get('/');
  }

  getParagraphText() {
    return element(by.css('app-root h1')).getText();
  }
}

```

Either Angular CLI should throw an error for invalid project name or the e2e class name should be created differently.

**Comment by filipesilva** [comment]
This is a bug with characters we allow as project names. We should fix the way those classnames are generated.
