### ISSUE TITLE
Adding file to root directory breaks broccoli

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#677]
When I added this file `myApp/server/app.js`  broccoli stopped compiling.  moving the file/folder in the `src` directory it resumed building. However this makes the file get compiled to the dist directory which is not ideal. 

```
lat-zchapple:wfa_ng2 zchapple$ ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot find module '/code/newWfaNG2/wfa_ng2/server'
Error: Cannot find module '/code/newWfaNG2/wfa_ng2/server'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Project.require (/code/newWfaNG2/wfa_ng2/node_modules/angular-cli/node_modules/angular-cli/lib/models/project.js:280:12)
    at Class.module.exports.Task.extend.processAppMiddlewares (/code/newWfaNG2/wfa_ng2/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/server/express-server.js:115:33)
    at Class.<anonymous> (/code/newWfaNG2/wfa_ng2/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/server/express-server.js:220:21)
    at lib$rsvp$$internal$$tryCatch (/code/newWfaNG2/wfa_ng2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/code/newWfaNG2/wfa_ng2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /code/newWfaNG2/wfa_ng2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/code/newWfaNG2/wfa_ng2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
lat-zchapple:wfa_ng2 zchapple$ ng serve
```

**Comment by mmgdort** [comment]
It's a Ubuntu issue, solution here http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
`

**Comment by lhcpig** [comment]
rename the server directory to solve it

**Comment by filipesilva** [comment]
@zackarychapple does this still happen?

**Comment by filipesilva** [comment]
If this still happens, please post here with repro steps so we can reopen the issue.
