### ISSUE TITLE
ng test - no source files in Chrome

### ISSUE THREAD

**Issue by alastair-todd** [angular/angular-cli#6785]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.1.3
node: 6.9.4
os: win32 x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.1.3
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4

### Repro steps.
run `ng test`

### Desired functionality.
step through test code in chrome tools using the Karma DEBUG button

### Mention any other details that might be useful.
There are no longer any source files, previously we had a webpack folder with all the source files.

This no longer exists.

**Comment by alastair-todd** [comment]
OK the --sourcemaps flag was added to ng test

Why not --nosourcemaps instead??

**Comment by kpaxton** [comment]
Also having this same issue. --sourcemap doesn't do anything and the sourcemaps when executing an```ng test``` command are not in the build at all.

**Comment by CodeAndWeb** [comment]
Same here. Getting complete useless call stacks from the tests. Can be reproduced using 

    ng new test

Add

    expect(true).toBeFalsy();

to **app.component.spec.ts**

Run test

    > ng test --sourcemaps
	03 07 2017 09:08:50.443:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
	03 07 2017 09:08:50.444:INFO [launcher]: Launching browser Chrome with unlimited concurrency
	03 07 2017 09:08:50.450:INFO [launcher]: Starting browser Chrome
	03 07 2017 09:08:56.950:WARN [karma]: No captured browser, open http://localhost:9876/
	03 07 2017 09:08:57.146:INFO [Chrome 59.0.3071 (Mac OS X 10.12.5)]: Connected on socket pH6eC5Jxj55VuuFtAAAA with id 376460
	Chrome 59.0.3071 (Mac OS X 10.12.5) AppComponent should render title in a h1 tag FAILED
		Expected true to be falsy.
		    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:96:22)
		    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2801:26)
		    at AsyncTestZoneSpec.webpackJsonp.../../../../zone.js/dist/async-test.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:2643:39)
		    at ProxyZoneSpec.webpackJsonp.../../../../zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3406:39)
	Chrome 59.0.3071 (Mac OS X 10.12.5): Executed 3 of 3 (1 FAILED) (0 secs / 0.185 secs)
	Chrome 59.0.3071 (Mac OS X 10.12.5) AppComponent should render title in a h1 tag FAILED
		Expected true to be falsy.
		    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:96:22)
		    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2801:26)
		    at AsyncTestZoneSpec.webpackJsonp.../../../../zone.js/dist/async-test.js.AsyncTestZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/vendor.bundle.js:2643:39)
	Chrome 59.0.3071 (Mac OS X 10.12.5): Executed 3 of 3 (1 FAILED) (0.205 secs / 0.185 secs)

**Comment by filipesilva** [comment]
Related to #6737, fixed by https://github.com/angular/angular-cli/pull/6862.

**Comment by filipesilva** [comment]
The source map tracing in console is being tracked in https://github.com/angular/angular-cli/issues/6583.
