### ISSUE TITLE
ng --prod does not work in production

### ISSUE THREAD

**Issue by adriano-fonseca** [angular/angular-cli#6893]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.2.0
node: 8.1.3
os: linux x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.2.0
@angular/compiler-cli: 4.2.4
```

### Repro steps.
I ran build this on jenkins. With the follow command:

`ng build --prod --base-href  ../angular/`

### The log given by the failure.

I dont' have any errors when a build the application, but when I try to access any part of application I get this:

```
vendor.e4c0e8b….bundle.js:1 ERROR Error: Uncaught (in promise): TypeError: e.ɵcrt is not a function
TypeError: e.ɵcrt is not a function
    at Object.iHEw (3.27e39f3….chunk.js:1)
    at r (inline.df588c1….bundle.js:1)
    at Object.MuQX (3.27e39f3….chunk.js:1)
    at r (inline.df588c1….bundle.js:1)
    at main.e1ffd67….bundle.js:1
    at t.invoke (polyfills.8dbe283….bundle.js:1)
    at Object.onInvoke (vendor.e4c0e8b….bundle.js:1)
    at t.invoke (polyfills.8dbe283….bundle.js:1)
    at r.run (polyfills.8dbe283….bundle.js:1)
    at polyfills.8dbe283….bundle.js:1
    at Object.iHEw (3.27e39f3….chunk.js:1)
    at r (inline.df588c1….bundle.js:1)
    at Object.MuQX (3.27e39f3….chunk.js:1)
    at r (inline.df588c1….bundle.js:1)
    at main.e1ffd67….bundle.js:1
    at t.invoke (polyfills.8dbe283….bundle.js:1)
    at Object.onInvoke (vendor.e4c0e8b….bundle.js:1)
    at t.invoke (polyfills.8dbe283….bundle.js:1)
    at r.run (polyfills.8dbe283….bundle.js:1)
    at polyfills.8dbe283….bundle.js:1
    at u (polyfills.8dbe283….bundle.js:1)
    at u (polyfills.8dbe283….bundle.js:1)
    at polyfills.8dbe283….bundle.js:1
    at t.invokeTask (polyfills.8dbe283….bundle.js:1)
    at Object.onInvokeTask (vendor.e4c0e8b….bundle.js:1)
    at t.invokeTask (polyfills.8dbe283….bundle.js:1)
    at r.runTask (polyfills.8dbe283….bundle.js:1)
    at o (polyfills.8dbe283….bundle.js:1)
    at <anonymous>

```

### Desired functionality.

I have Angular as frontend and this build is deployed inside my webapp folder in a jboss-6.4, everything works fine locally. However, when I try the same build in my jenkins to build this to development server or production I had the above error.  I  would like to have this working as works locally.

### Mention any other details that might be useful.

I am using lazy load to my routes. 

**tsconfig.json**

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}

```

I have tried this same build using --aot false, trying workaround it:

`ng build --prod --aot false --base-href  ../angular/`

Again no erros on build, but when I try to access the application I get the follow error:

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Parser Error: Unexpected token Lexer Error: Unexpected character [Â] at column 17 in expression [closed ? false :Â (lazy ? selected : true)] at column 18 in [closed ? false :Â (lazy ? selected : true)] in ng:///t/t.html@2:59 (".display]="selected ? 'block' : 'none'" 
            role="tabpanel" [attr.aria-hidden]="!selected" [ERROR ->]*ngIf="closed ? false :Â (lazy ? selected : true)">
            <ng-content></ng-content>
        </d"): ng:///t/t.html@2:59
Parser Error: Lexer Error: Unexpected character [Â] at column 17 in expression [closed ? false :Â (lazy ? selected : true)] at column 18 in [closed ? false :Â (lazy ? selected : true)] in ng:///t/t.html@2:59 (".display]="selected ? 'block' : 'none'" 
            role="tabpanel" [attr.aria-hidden]="!selected" [ERROR ->]*ngIf="closed ? false :Â (lazy ? selected : true)">
            <ng-content></ng-content>
        </d"): ng:///t/t.html@2:59
Error: Template parse errors:
Parser Error: Unexpected token Lexer Error: Unexpected character [Â] at column 17 in expression [closed ? false :Â (lazy ? selected : true)] at column 18 in [closed ? false :Â (lazy ? selected : true)] in ng:///t/t.html@2:59 (".display]="selected ? 'block' : 'none'" 
            role="tabpanel" [attr.aria-hidden]="!selected" [ERROR ->]*ngIf="closed ? false :Â (lazy ? selected : true)">
            <ng-content></ng-content>
        </d"): ng:///t/t.html@2:59
Parser Error: Lexer Error: Unexpected character [Â] at column 17 in expression [closed ? false :Â (lazy ? selected : true)] at column 18 in [closed ? false :Â (lazy ? selected : true)] in ng:///t/t.html@2:59 (".display]="selected ? 'block' : 'none'" 
            role="tabpanel" [attr.aria-hidden]="!selected" [ERROR ->]*ngIf="closed ? false :Â (lazy ? selected : true)">
            <ng-content></ng-content>
        </d"): ng:///t/t.html@2:59
    at g (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:936776)
    at t.parse (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1111534)
    at t._compileTemplate (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1282479)
    at https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1280740
    at Set.forEach (native)
    at t._compileComponents (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1280711)
    at https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1278388
    at Object.then (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:988850)
    at t._compileModuleAndComponents (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1278340)
    at t.compileModuleAsync (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1277109)
    at g (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:936776)
    at t.parse (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1111534)
    at t._compileTemplate (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1282479)
    at https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1280740
    at Set.forEach (native)
    at t._compileComponents (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1280711)
    at https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1278388
    at Object.then (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:988850)
    at t._compileModuleAndComponents (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1278340)
    at t.compileModuleAsync (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:1277109)
    at u (https://secweb.des.intra.rs.gov.br/ise/angular/polyfills.8dbe2833530b97e02433.bundle.js:1:40293)
    at u (https://secweb.des.intra.rs.gov.br/ise/angular/polyfills.8dbe2833530b97e02433.bundle.js:1:39979)
    at https://secweb.des.intra.rs.gov.br/ise/angular/polyfills.8dbe2833530b97e02433.bundle.js:1:40825
    at t.invokeTask (https://secweb.des.intra.rs.gov.br/ise/angular/polyfills.8dbe2833530b97e02433.bundle.js:1:36725)
    at Object.onInvokeTask (https://secweb.des.intra.rs.gov.br/ise/angular/vendor.ae51d4885decf5f337bc.bundle.js:1:89644)
    at t.invokeTask (https://secweb.des.intra.rs.gov.br/ise/angular/polyfills.8dbe2833530b97e02433.bundle.js:1:36646)
    at r.runTask (https://secweb.des.intra.rs.gov.br/ise/angular/polyfills.8dbe2833530b97e02433.bundle.js:1:31901)
    at o (https://secweb.des.intra.rs.gov.br/ise/angular/polyfills.8dbe2833530b97e02433.bundle.js:1:28961)
    at <anonymous>

```

Without the '--prod' option, everything works as fine as in my local environment.

**Comment by adriano-antonio** [comment]
I had a similar problem

**Comment by hansl** [comment]
@adriano-fonseca can you share your project or make a github repo to reproduce this? Our tests use Travis and CircleCI, but I would assume it's not Jenkins' fault and more a matter of environment.

Do you use i18n of any sort?

**Comment by adriano-fonseca** [comment]
Hello @hansl I create this repository https://github.com/adriano-fonseca/iseApp,  any further help, please let me know.

**Comment by adriano-fonseca** [comment]
@hansl  I found the follow import being used in one component.

import { Message } from "@angular/compiler/src/i18n/i18n_ast";

**Comment by jigneshpatel4u** [comment]
We are also facing the exact error. Any resolution?

**Comment by jigneshpatel4u** [comment]
Any fix yet for the issues?

**Comment by adriano-fonseca** [comment]
Hello @jigneshpatel4u and @hansl, the issue persists, Today I tryed to update angular-cli to version 1.2.7, because I have read that there were happened some changes in way that the symbolic links are threaten. However, without success. Currently, I have gone to production without uglyfication and minification, for more than one month, which brings me some performance impact and of course some sucurity concerns, because the application logic's are clear to read. I have googled it, and there are more programmers facing the same, that is quite serious issue and don't see that being faced as so.

**Comment by adriano-fonseca** [comment]
Hello Guys that was tough... but finally I figured out what was happening, Actually it is not issue in angular-cli. What was happenening was that I have a Apache Server as a proxy to my Jboss Web Server (where my angular build was hosted) in order to provide https to application and a given configuration in this server was screw up the reponse headers. When everything works fine, I mean accessing the application bypassing the apache I had something like this:

Accept-Ranges:bytes
Connection:keep-alive
Content-Length:836
Content-Type:text/html
Date:Thu, 10 Aug 2017 20:49:08 GMT

However,  when I hit the application through the Apache I got something like this:

Connection: close
Date:Thu, 10 Aug 2017 20:49:47 GMT
ETag:W/"836-1502389410000"
Server:Apache
Request Headers

This behavior was kind masking the real problem, even when I check the file's charset in both cases I got utf-8, but I realize that the size was suddenly different, so I compare the files and could see some different characters inside, which was probably leading to the Unexpected character [Â], when I try to use the --aot false. Anyway, thank you for the help and @hansl please close the issue.

**Comment by felixosle** [comment]
Hi Adriano,
Please, can you show specifically what you did to solve it?
Did you change the configuration in apache?

Thank you so much

**Comment by seekheart** [comment]
@adriano-fonseca I too am curious as to what you did to solve it. Can you sure the Apache/JBOSS configs?

**Comment by rinami** [comment]
For those that landed here looking for a resolution just be aware that the root cause seems to be that the browser is not processing the angular js files with UTF-8 encoding. So this may be an issue with headers not specifying content-type (as mentioned in this thread) or could also be an issue with the web server not encoding the payload correctly.
