### ISSUE TITLE
ng cli commands doesn't work on windows

### ISSUE THREAD

**Issue by WagnerMoreira** [angular/angular-cli#6895]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report
- [ ] feature request
```

### Versions.
```
angular-cli: 1.0.0-beta.28.3
node: 6.11.0
os: win32 x64 (win10)
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/compiler-cli: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/cli: 1.0.5
```

### Repro steps.
ng serve, ng help

### The log given by the failure.
```
$ ng help
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (C:\Users\wagner\AppData\Roaming\npm\node_modules\angular-cli\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\wagner\AppData\Roaming\npm\node_modules\angular-cli\models\webpack-configs\typescript.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\wagner\AppData\Roaming\npm\node_modules\angular-cli\models\webpack-configs\index.js:9:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\wagner\AppData\Roaming\npm\node_modules\angular-cli\models\webpack-config.js:4:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\wagner\AppData\Roaming\npm\node_modules\angular-cli\tasks\build.js:6:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\wagner\AppData\Roaming\npm\node_modules\angular-cli\commands\build.run.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\wagner\AppData\Roaming\npm\node_modules\angular-cli\commands\help.js:29:33
    at Array.reduce (native)
    at Class.run (C:\Users\wagner\AppData\Roaming\npm\node_modules\angular-cli\commands\help.js:27:39)
    at Class.<anonymous> (C:\Users\wagner\AppData\Roaming\npm\node_modules\angular-cli\ember-cli\lib\models\command.js:134:17)
```

```
$ ng serve
You have to be inside an angular-cli project in order to use the serve command.
```

### Desired functionality.
it should be working... none of ng commands are working

### Mention any other details that might be useful.

**Comment by alerat** [comment]
try uninstalling angular-cli as shown in the documentation : https://github.com/angular/angular-cli#updating-angular-cli

**Comment by WagnerMoreira** [comment]
@alerat thanks, it works!

**Comment by fletchsod-developer** [comment]
Can you close this open ticket since you said it works now.  Thanks.
