### ISSUE TITLE
Unexpected Token --Angular Error

### ISSUE THREAD

**Issue by saybinem** [angular/angular-cli#6904]
**npm --version = 4.2.0
angular/cli: 1.0.1
node: 7.9.0**

/usr/local/lib/node_modules/@angular/cli/models/config/config.js:16
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by Zarepheth** [comment]
I'm seeing the same error:
**@angular/cli: 1.2.0
node: v8.1.3
npm: 5.0.3**

```
{project root path}\node_modules\@angular\cli\models\config\config.js:17
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> ({project root path}\node_modules\@angular\cli\models\config.js:3:18)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
```
where `{project root path}` is the root path to my project.

**Comment by saybinem** [comment]
Fixed it when try to update node version using sudo. When you check it with sudo you will know linux uses old 4.x.x version uninstall and reinstall using 'sudo'.Version must be 6.9 or above

**Comment by Brocco** [comment]
Closing as it appears you have found a resolution.
