### ISSUE TITLE
Angular CLI + nwjs modules

### ISSUE THREAD

**Issue by BrunoAMSilva** [angular/angular-cli#691]
I'm getting an error building in the production environment. It seems angular-cli is trying to include a file that doesn't exist. Somewhere in my code I have a printer service that I use to interact with NWJS.

```
if (require && typeof require == 'function') {
    this._printer = require('printer');
    this._util = require('util');
}
```

However, angular cli appears to be trying to include those files even though they are injected at runtime by NWJS.

MacOS X El Cap
angular-cli 0.0.39
node 5.8.0
npm 3.8.6

The app was created with Angular-CLI from the ground up. The dev build works just fine, I suppose this has something to do with the bundling that's done in the prod build.

```
Build failed.
The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for printer at file:///Users/u007241/OneDrive/Work/Testes/jOne/tmp/bundle_plugin-input_base_path-VUbIoGE5.tmp/0/printer
	Loading app/core/printer.service.js
	Error: ENOENT: no such file or directory, open '/Users/u007241/OneDrive/Work/Testes/jOne/tmp/bundle_plugin-input_base_path-VUbIoGE5.tmp/0/printer'
    at Error (native)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BundlePlugin (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/lib/broccoli/angular-broccoli-bundle.js:10:36)
    at Angular2App._getBundleTree (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/lib/broccoli/angular2-app.js:375:55)
    at Angular2App._buildTree (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/lib/broccoli/angular2-app.js:137:21)
    at new Angular2App (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/lib/broccoli/angular2-app.js:42:23)
    at module.exports (/Users/u007241/OneDrive/Work/Testes/jOne/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at /Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/angular-cli/lib/commands/build.js:32:24
    at lib$rsvp$$internal$$tryCatch (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/u007241/OneDrive/Work/Testes/jOne/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by hansl** [comment]
We use `SystemJs` which might want to include those files in as dependencies. You can use `System.import(...)` instead of `require()`, or map those files to something else in teh system-config.
