### ISSUE TITLE
The "@angular/compiler-cli" package was not properly installed.

### ISSUE THREAD

**Issue by qlaffont** [angular/angular-cli#6940]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
λ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.0
node: 8.1.3
os: win32 x64
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0
@angular/compiler-cli: error
```

### Repro steps.
Update old project by ncu command
```
 npm update && ng build --watch true
```

### The log given by the failure.
```
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (D:\Projects\Gamubs\gamubs-backend\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Projects\Gamubs\gamubs-backend\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

### Mention any other details that might be useful.
package.json : 
```
{
  "name": "project-backend",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "dev": "concurrently \"ng build --watch true\" \"nodemon server.js\" \"gulp dev\""
  },
  "dependencies": {
    "@angular/common": "^4.2.6",
    "@angular/compiler": "^4.2.6",
    "@angular/core": "^4.2.6",
    "@angular/forms": "^4.2.6",
    "@angular/http": "^4.2.6",
    "@angular/platform-browser": "^4.2.6",
    "@angular/platform-browser-dynamic": "^4.2.6",
    "@angular/router": "^4.2.6",
    "angular2-jwt": "^0.2.3",
    "body-parser": "^1.17.2",
    "concurrently": "^3.5.0",
    "core-js": "^2.4.1",
    "express": "^4.15.3",
    "express-promise": "^0.4.0",
    "fs": "0.0.1-security",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "jsonwebtoken": "^7.4.1",
    "mongoose": "^4.11.1",
    "mongoose-paginate": "^5.0.3",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.0",
    "@angular/compiler-cli": "^4.2.6",
    "@types/jasmine": "2.5.53",
    "@types/node": "~8.0.10",
    "codelyzer": "~3.1.2",
    "jasmine-core": "~2.6.4",
    "jasmine-spec-reporter": "~4.1.1",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "typescript": "~2.4.1"
  }
}

```

**Comment by qlaffont** [comment]
I don't know why but after complete remove of node_modules now it's work --",(I have tried 2 times before, and now it's work)
