### ISSUE TITLE
ng serve is broken after installing angular-switchery

### ISSUE THREAD

**Issue by stevermeister** [angular/angular-cli#6961]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.0
node: 6.9.4
os: darwin x64
@angular/animations: error
@angular/common: error
@angular/compiler: error
@angular/core: error
@angular/forms: error
@angular/http: error
@angular/platform-browser: error
@angular/platform-browser-dynamic: error
@angular/router: error
@angular/cli: error
@angular/compiler-cli: error
@angular/language-service: error
@ngtools/webpack: 1.5.1

npm 5.2.0

macOS Sierra

### Repro steps.
```
ng new myapp
cd myapp
ng serve                  ----   works
npm install angular-switchery
ng serve                   ----   does not work anymore
```

### The log given by the failure.
```
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/Users/stevermeister/workspace/research/swttt/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/stevermeister/workspace/research/swttt/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

### Mention any other details that might be useful.

**[angular-switchery](https://github.com/stevermeister/angular-switchery)** package was created with help of **[angular-librarian](https://github.com/gonzofish/angular-librarian)** tool

**Comment by gonzofish** [comment]
Were there any other steps that you did? I'm trying to reproduce (to make sure [angular-librarian](https://github.com/gonzofish/angular-librarian) isn't at fault) and following the outlined steps had no problem running `ng serve`

**Comment by gonzofish** [comment]
I realized I was on 1.1.1 and upgraded the CLI...have the same problem. Did the CLI change how it manages packages for a project when running `ng new`?

**Comment by clydin** [comment]
This may or may not be the issue but after quickly looking over the library, the Angular related dependencies should be setup as peer dependencies. (https://github.com/stevermeister/angular-switchery/blob/master/package.json#L80) Also, only the directly used packages should be mentioned.

**Comment by gonzofish** [comment]
Nice suggestion, @clydin, let me see what happens if i do that

**Comment by filipesilva** [comment]
This definitely is a problem with peer deps. By having them as dependencies instead, you are getting duplicates. You can check this with `npm ls @angular/core` (and others).
