### ISSUE TITLE
ng generate component [name] fails with 'undefined' in cli 1.2.1

### ISSUE THREAD

**Issue by systemNEO** [angular/angular-cli#6963]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.2.1
node: 6.10.3
os: win32 x64 (Windows 10)
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.2.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3

### Repro steps.

1. open command line tool
2. type `ng generate component quick-run`

### The log given by the failure.

D:\Entwicklung\anarchy-companion\src\app\sr5\sr5-home>ng generate component quick-run
installing component
  create src\app\sr5\sr5-home\quick-run\quick-run.component.css
Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at FileInfo.render (D:\Entwicklung\anarchy-companion\node_modules\@angular\cli\ember-cli\lib\models\file-info.js:103:9)
    at Class.Blueprint._writeFile (D:\Entwicklung\anarchy-companion\node_modules\@angular\cli\ember-cli\lib\models\blueprint.js:383:44)
    at Class.write (D:\Entwicklung\anarchy-companion\node_modules\@angular\cli\ember-cli\lib\models\blueprint.js:395:17)
    at Class.Blueprint._commit (D:\Entwicklung\anarchy-companion\node_modules\@angular\cli\ember-cli\lib\models\blueprint.js:436:19)
    at D:\Entwicklung\anarchy-companion\node_modules\rsvp\dist\rsvp.js:2170:20
    at tryCatch (D:\Entwicklung\anarchy-companion\node_modules\rsvp\dist\rsvp.js:539:12)
    at invokeCallback (D:\Entwicklung\anarchy-companion\node_modules\rsvp\dist\rsvp.js:554:13)
    at D:\Entwicklung\anarchy-companion\node_modules\rsvp\dist\rsvp.js:629:16
    at flush (D:\Entwicklung\anarchy-companion\node_modules\rsvp\dist\rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)

### Desired functionality.

Creates a component named QuickRun.

### Mention any other details that might be useful.

After update from angular cli 1.1.0 to 1.2.1

**Comment by Torakage** [comment]
I receive a similar error after upgrading from cli 1.1.0 to 1.2.1

Using: Angular 4.2.6

C:\\...\ca-app>ng g component [any]

Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at blueprint.blueprints.find (C:\\...\ca-app\node_modules\@angular\cli\commands\generate.js:60:58)
    at Array.find (native)
    at Class.beforeRun (C:\\...\ca-app\node_modules\@angular\cli\commands\generate.js:60:43)
    at Promise.resolve.then (C:\\...\ca-app\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:153:24)
    at tryCatch (C:\\...\ca-app\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (C:\\...\ca-app\node_modules\rsvp\dist\rsvp.js:538:13)
    at C:\\...\ca-app\node_modules\rsvp\dist\rsvp.js:606:14
    at flush (C:\\...\ca-app\node_modules\rsvp\dist\rsvp.js:2400:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by wnodom** [comment]
I had the same issue in a 1.2.0 project, but it went away after I upgrade to 1.2.1. I followed the update instructions on the CLI homepage, including completely uninstalling the global CLI, cleaning the npm cache, removing the local node_modules directory, etc.:

https://github.com/angular/angular-cli#updating-angular-cli

Perhaps there's something left over from an earlier version that's still causing trouble?

**Comment by systemNEO** [comment]
I have updated nodejs from 6.x to v8.1.4, updated npm to latest version 5.3.0 and reinstalled angular-cli as described on github and now it works.

> @angular/cli: 1.2.1
> node: 8.1.4
> os: win32 x64
> @angular/animations: 4.1.3
> @angular/common: 4.1.3
> @angular/compiler: 4.1.3
> @angular/core: 4.1.3
> @angular/forms: 4.1.3
> @angular/http: 4.1.3
> @angular/platform-browser: 4.1.3
> @angular/platform-browser-dynamic: 4.1.3
> @angular/router: 4.1.3
> @angular/cli: 1.2.1
> @angular/compiler-cli: 4.1.3
> @angular/language-service: 4.1.3

Now it works for me. 

Is there a problem with nodejs v6.11.1 LTS?

@Torakage Do you still have problems or can i close the ticket?

**Comment by Torakage** [comment]
@systemNEO I think I had error when removing old directories (or forgot to run rmdir). Walking through the upgrade process again fixed the problem.

**Comment by dradel** [comment]
Same problem here

Version: "@angular/cli": "1.2.3"

command: ng g module downloading
The log given by the failure:
   installing module
   create src\app\downloading\downloading.module.ts 
   Cannot read property 'then' of undefined
   TypeError: Cannot read property 'then' of undefined

**Comment by filipesilva** [comment]
This sounds like an update problem like @wnodom suggested. Following the upgrade procedure should help.
