### ISSUE TITLE
jquery validation engine in  angular 2 issues

### ISSUE THREAD

**Issue by Midhilaj** [angular/angular-cli#6974]
i am using angular 2
i included jquery validation engine required files in index.html file
<script src="assets/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="assets/jquery.validationEngine.js" type="text/javascript"></script>
    <script src="assets/jquery.validationEngine-en.js" type="text/javascript"></script>
    <link rel="stylesheet" href="assets/validationEngine.jquery.css">
and in my ts file i called   
                   $(document).ready(function() {
                     (<any>$("#idofurform")).validationEngine();               
                    });
and when it run it showing issues
### Versions.
 
angular-cli: 1.0.0-beta.28.3
node: 7.6.0
os: linux x64
 npm --version
5.0.4
 

### Repro steps.
jquery validation engine in angular 2 not working 

### The log given by the failure.
jQuery.Deferred exception: __WEBPACK_IMPORTED_MODULE_3_jquery__(...).validationEngine is not a function TypeError: __WEBPACK_IMPORTED_MODULE_3_jquery__(...).validationEngine is not a function
    at HTMLDocument.<anonymous> (http://localhost:4208/main.bundle.js:814:65)
    at mightThrow (http://localhost:4208/vendor.bundle.js:81407:29)
    at process (http://localhost:4208/vendor.bundle.js:81475:12)
    at ZoneDelegate.invokeTask (http://localhost:4208/polyfills.bundle.js:6288:31)
    at Zone.runTask (http://localhost:4208/polyfills.bundle.js:6087:47)
    at ZoneTask.invoke (http://localhost:4208/polyfills.bundle.js:6341:38)
    at data.args.(anonymous function) (http://localhost:4208/polyfills.bundle.js:7502:29) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3860
process @ jquery.js:3655
ZoneDelegate.invokeTask @ zone.js:367
Zone.runTask @ zone.js:166
ZoneTask.invoke @ zone.js:420
data.args.(anonymous function) @ zone.js:1581
zone.js:170 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_3_jquery__(...).validationEngine is not a function
    at HTMLDocument.<anonymous> (http://localhost:4208/main.bundle.js:814:65)
    at mightThrow (http://localhost:4208/vendor.bundle.js:81407:29)
    at process (http://localhost:4208/vendor.bundle.js:81475:12)
    at ZoneDelegate.invokeTask (http://localhost:4208/polyfills.bundle.js:6288:31)
    at Zone.runTask (http://localhost:4208/polyfills.bundle.js:6087:47)
    at ZoneTask.invoke (http://localhost:4208/polyfills.bundle.js:6341:38)
    at data.args.(anonymous function) (http://localhost:4208/polyfills.bundle.js:7502:29)

### Desired functionality.
jquery validation engine in angular 2

**Comment by Midhilaj** [comment]
solved by changing
`$(document).ready(function() {
($("#idofurform")).validationEngine();
});`
to
` (<any>$(document)).ready(function() {
                     (<any>$("#idofurform")).validationEngine();       
                         
                    });`
