### ISSUE TITLE
Cannot run project after I move to 1.2.1

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#6976]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular: 4.2.6
@angular/cli: 1.2.1
Node: LTS 6.11.1
nmp: 5.2.0
```

### Error
```
> ng serve

module.js:471
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Project/node_modules/@angular/cli/ember-cli/lib/models/project.js:10:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
Any ideas?

UPDATE:
I revert back to `1.2.0` and now I'm experiencing the same issue :(
Nothing else has changed to the project.

**Comment by vapits** [comment]
Fix:
1. Remove `node_modules`
2. Clean npm cache `npm cache clean` and veriry
3. Do `npm install` again

It works.
