### ISSUE TITLE
angular cli dev dependency

### ISSUE THREAD

**Issue by Thrillz** [angular/angular-cli#6979]
### Bug Report or Feature Request (mark with an `x`)
```The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (C:\Users\vic_t\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\vic_t\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.2.1
node: 6.11.1
os: win32 x64

### Repro steps.
ng new my-app
cd my-app
ng serve

### The log given by the failure.

$ ng serve
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (C:\Users\vic_t\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\vic_t\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

### Mention any other details that might be useful.

if i do " npm install -g --save-dev @angular/cli@latest"
it serves. but without doing this angular won't serve the project

**Comment by bbearche** [comment]
Having the same issue.

**Comment by kroeder** [comment]
In my setup I have a seperate project for all my devDeps 
Until today I was able to seperate all @angular devDeps into this project except angular/cli

If you have the same setup as me, add @angular/compiler-cli back to your project and don't seperate it into a subproject - my app is running again.

I hope this is not getting a standard (forcing people to put all devDeps into their project)
In our environment we got n-apps, all running in a big solution - to keep track of all devDeps per app is a maintenance nightmare...

**Comment by bmercier-manakin** [comment]
I have the same issue with those versions:

Versions.

@angular/cli: 1.2.1
npm: 5.0.3
node: 8.1.2
os: Linux 16.04

**Comment by filipesilva** [comment]
`@angular/compiler-cli` is required for Angular CLI to properly work, and you should add it to your `dependencies` or `devDependencies`. I'm sorry but this isn't optional.
