### ISSUE TITLE
AOT: loaderUtils.getOptions is not a function

### ISSUE THREAD

**Issue by achimha** [angular/angular-cli#6994]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.3.0-beta.1
node: 8.1.4
os: linux x64
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
@angular/cli: 1.3.0-beta.1
@angular/compiler-cli: 4.3.0

### Repro steps.
Updated to Angular 4.3.0 and angular-cli 1.2.1 or 1.3.0-beta.1, nuked node_modules, same dependency versions as latest angular-cli scaffold.

### The log given by the failure.
```
ERROR in Child compilation failed:
Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/var/www/myproject/frontend/node_modules/postcss-loader/index.js:46:30):
TypeError: loaderUtils.getOptions is not a function

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/var/www/myproject/frontend/src'
 @ ./src/main.ts 20:0-74
 @ multi ./src/main.ts

ERROR in ./src/styles.scss
Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/var/www/myproject/frontend/node_modules/postcss-loader/index.js:46:30)
 @ multi ./src/styles.scss ./node_modules/font-awesome/css/font-awesome.css ./node_modules/@swimlane/ngx-datatable/release/assets/icons.css

ERROR in ./node_modules/font-awesome/css/font-awesome.css
Module build failed: ModuleBuildError: Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/var/www/myproject/frontend/node_modules/postcss-loader/index.js:46:30)
    at runLoaders (/var/www/myproject/frontend/node_modules/@angular/cli/node_modules/webpack/lib/NormalModule.js:193:19)
    at /var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at /var/www/myproject/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:62:14
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

ERROR in ./node_modules/@swimlane/ngx-datatable/release/assets/icons.css
Module build failed: ModuleBuildError: Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/var/www/myproject/frontend/node_modules/postcss-loader/index.js:46:30)
    at runLoaders (/var/www/myproject/frontend/node_modules/@angular/cli/node_modules/webpack/lib/NormalModule.js:193:19)
    at /var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at /var/www/myproject/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:62:14
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

ERROR in ./src/styles.scss
Module build failed: ModuleBuildError: Module build failed: TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/var/www/myproject/frontend/node_modules/postcss-loader/index.js:46:30)
    at runLoaders (/var/www/myproject/frontend/node_modules/@angular/cli/node_modules/webpack/lib/NormalModule.js:193:19)
    at /var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/var/www/myproject/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/var/www/myproject/frontend/node_modules/@angular/cli/node_modules/sass-loader/lib/loader.js:79:9)
    at Object.<anonymous> (/var/www/myproject/frontend/node_modules/@angular/cli/node_modules/async/dist/async.js:2244:31)
    at Object.callback (/var/www/myproject/frontend/node_modules/@angular/cli/node_modules/async/dist/async.js:906:16)
    at options.success (/var/www/myproject/frontend/node_modules/node-sass/lib/index.js:308:32)
```

**Comment by achimha** [comment]
`postcss-loader` is at 1.3.3
`loader-utils` are at 0.2.16

**Comment by achimha** [comment]
The problem is solved by adding

`"loader-utils": "^1.0.2"`

to my main `package.json`. The old version 0.2.16 was pulled in by one of the packages I depend on. Now the question is -- why does this impact angular-cli?

**Comment by filipesilva** [comment]
It seems `postcss-loader` had a problem with it. I haven't seen this error around so it was probably fixed in a patch version on their side, or perhaps we updated it meanwhile. Let me know if you still get it.

**Comment by incinirate** [comment]
I'm experiencing this error even with adding `"loader-utils": "^1.0.2"` to the main `package.json`, but only on linux, with windows it works perfectly fine..

**Comment by huineng** [comment]
i had the problem this morning after updating some packages, but got it solved by installing 
 "loader-utils": "^1.1.0",

**Comment by amazingankur** [comment]
I am facing the same problem.
Added "loader-utils": "^1.1.0", to package.json as well.
Still getting the below error:
ERROR in ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css
    Module build failed: TypeError: loaderUtils.getOptions is not a function

I am working with ASP.Net Core 2 and Angular 5 version and did following changes:
 **new webpack.ContextReplacementPlugin(/\@angular(\\|\/)core(\\|\/)esm5/, path.join(__dirname, './ClientApp')), // Workaround for https://github.com/angular/angular/issues/20357 //Changes to webpack.config.vendor.js**
webpack.config.js file
**const AotPlugin = require('@ngtools/webpack').AngularCompilerPlugin;
module: {
    rules: [
        { test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/, [...]
[..]**
**const AotPlugin = require('@ngtools/webpack').AngularCompilerPlugin;**

Running below command and getting the error:
> node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js

Stuck here. Need suggestions/advice to move forward.

**Comment by anz1e** [comment]
I have the same issue as @amazingankur and it seems that when I install loader-utils ''1.1.0'' and look at the index.js file it doesn´t have getOptions in its exports. If I manually add it then it works, but this can´t be a long-term solution. Anyone know why getOptions is not included in the latest version of loader-utils when installed via npm install?

**Comment by jasonmarsell** [comment]
As follow-up to the two posts above by @amazingankur and @anz1e ...I fixed the errors by running an `npm install loader-utils@latest` command at the root level directory of my project. Re-ran the Webpack refresh with no errors.
