### ISSUE TITLE
Generate Component fails

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#703]
I setup a new project and get:

```
c:\temp\app1d>ng generate component comp1
installing component
Cannot read property 'sourceDir' of undefined
TypeError: Cannot read property 'sourceDir' of undefined
    at dynamicPathParser (c:\temp\app1d\node_modules\angular-cli\addon\ng2\utilities\dynamic-path-parser.js:7:52)
    at Class.module.exports.normalizeEntityName (c:\temp\app1d\node_modules\angular-cli\addon\ng2\blueprints\component\index.js:21:22)
    at Class.Blueprint._normalizeEntityName (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\models\blueprint.js:447:24)
    at Class.Blueprint.install (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\models\blueprint.js:508:8)
    at Class.module.exports.Task.extend.run (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\generate-from-blueprint.js:60:49)
    at Class.module.exports.Command.extend.run (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\commands\generate.js:65:17)
    at Class.<anonymous> (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\models\command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:331:11
```

**Comment by doczoidberg** [comment]
same problem with `ng serve`

```
c:\temp\app1d>ng generate component comp1
installing component
Cannot read property 'sourceDir' of undefined
TypeError: Cannot read property 'sourceDir' of undefined
    at dynamicPathParser (c:\temp\app1d\node_modules\angular-cli\addon\ng2\utilities\dynamic-path-parser.js:7:52)
    at Class.module.exports.normalizeEntityName (c:\temp\app1d\node_modules\angular-cli\addon\ng2\blueprints\component\index.js:21:22)
    at Class.Blueprint._normalizeEntityName (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\models\blueprint.js:447:24)
    at Class.Blueprint.install (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\models\blueprint.js:508:8)
    at Class.module.exports.Task.extend.run (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\generate-from-blueprint.js:60:49)
    at Class.module.exports.Command.extend.run (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\commands\generate.js:65:17)
    at Class.<anonymous> (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\lib\models\command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at c:\temp\app1d\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:331:11
```

**Comment by doczoidberg** [comment]
angular-cli: 0.0.31
node: 4.4.2
os: win32 x64
