### ISSUE TITLE
Cannot find module 'rsvp'

### ISSUE THREAD

**Issue by Czulu** [angular/angular-cli#7049]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
mac os sierra 10.12.5
ng -v : Your global Angular CLI version (1.2.1) is greater than your local
version (1.1.1). The local Angular CLI version is used.
node -v : v6.10.0
npm -v : v5.0.3

### Repro steps.
any ng command yelds same error

### The log given by the failure.
Your global Angular CLI version (1.2.1) is greater than your local
version (1.1.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
module.js:471
    throw err;
    ^

Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/miquido/onkyo-store-web/node_modules/@angular/cli/ember-cli/lib/ext/promise.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

### Mention any other details that might be useful.
Initially i was having issue solved here https://github.com/angular/angular-cli/issues/503, but after i create alias for ng then I'm getting above error, and attempts to apply existing solutions for current problem didn't worked.

**Comment by filipesilva** [comment]
It sounds like your dependencies weren't installed correctly. I know `npm` had some bugs with the earlier 5.x version, you might want to try npm4 or the latest npm 5.x.
