### ISSUE TITLE
ng-xi18n fails with webpack less import

### ISSUE THREAD

**Issue by 0mpurdy** [angular/angular-cli#7054]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.2.1
node: 7.10.0
os: darwin x64
@angular/cli: 1.2.1
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/compiler-cli: 4.3.0
@angular/core: 4.3.0
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/platform-server: 4.3.0
@angular/router: 4.3.0
```

### Repro steps.

 - Create a project with a global less file (e.g. colour variables)
 - Reference file using webpack resolver e.g. `@import "~assets/css/colours"`
  + See the [relevant less loader documentation](https://github.com/webpack-contrib/less-loader#imports)

I created a [sample repo here](https://github.com/0mpurdy/less-reference-bug) that demonstrates the problem

### The log given by the failure.

```
$ npm run i18n -- --i18nFormat=xlf

> less-reference-bug@0.0.0 i18n /Users/username/dev/angular/less-reference-bug
> ng-xi18n "--i18nFormat=xlf"

Error: Compilation failed. Resource file not found: /Users/username/dev/angular/less-reference-bug/src/app/~assets/css/colours
    at ModuleResolutionHostAdapter.readResource (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler-cli/src/compiler_host.js:387:19)
    at CompilerHost.loadResource (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler-cli/src/compiler_host.js:250:33)
    at Object.get (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:27389:103)
    at DirectiveNormalizer._fetch (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:14105:43)
    at /Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:14221:68
    at Array.map (native)
    at DirectiveNormalizer._loadMissingExternalStylesheets (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:14221:14)
    at /Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:14224:26
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
Extraction failed

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/username/.nvm/versions/node/v7.10.0/bin/node" "/Users/username/.nvm/versions/node/v7.10.0/bin/npm" "run" "i18n" "--" "--i18nFormat=xlf"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! less-reference-bug@0.0.0 i18n: `ng-xi18n "--i18nFormat=xlf"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the less-reference-bug@0.0.0 i18n script 'ng-xi18n "--i18nFormat=xlf"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the less-reference-bug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng-xi18n "--i18nFormat=xlf"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs less-reference-bug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls less-reference-bug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/username/.npm/_logs/2017-07-19T18_56_25_092Z-debug.log
```

### Desired functionality.

I'd like to be able to use the webpack resolver to remove relative links to static theme variables. (So that I can move modules or components without having to count nesting and get the right number of `../`)
Does it even need to look at the css/less?

### Mention any other details that might be useful.

Thanks for your time :)

**Comment by clydin** [comment]
The "ng-xi18n" is part of @angular/compiler-cli. For @angular/cli based projects use the the CLI's "xi18n" command. See here for further details: https://github.com/angular/angular-cli/wiki/xi18n

**Comment by 0mpurdy** [comment]
@clydin yes I have already tried that - for ease of use I have created an npm command `"i18n": "ng-xi18n"` (which I think is shown in the log about line 4 `> ng-xi18n "--i18nFormat=xlf"`)

here is the output with the command called directly as well:

```
$ ./node_modules/.bin/ng-xi18n --i18nFormat=xlf
Error: Compilation failed. Resource file not found: /Users/username/dev/angular/less-reference-bug/src/app/~assets/css/colours
    at ModuleResolutionHostAdapter.readResource (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler-cli/src/compiler_host.js:387:19)
    at CompilerHost.loadResource (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler-cli/src/compiler_host.js:250:33)
    at Object.get (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:27389:103)
    at DirectiveNormalizer._fetch (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:14105:43)
    at /Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:14221:68
    at Array.map (native)
    at DirectiveNormalizer._loadMissingExternalStylesheets (/Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:14221:14)
    at /Users/username/dev/angular/less-reference-bug/node_modules/@angular/compiler/bundles/compiler.umd.js:14224:26
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
Extraction failed
```

**Comment by 0mpurdy** [comment]
My mistake, I misread your comment - you are totally correct it's working now thanks! :)
