### ISSUE TITLE
he "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module 'rxjs/symbol/observable'

### ISSUE THREAD

**Issue by Thugkitty** [angular/angular-cli#7075]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### The log given by the failure.

As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module 'rxjs/symbol/observable'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module 'rxjs/symbol/observable'
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/models/webpack-configs/typescript.js:3:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/models/webpack-configs/index.js:9:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/models/webpack-config.js:4:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/tasks/serve.js:11:24)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/commands/serve.run.js:6:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Class.run (/usr/local/lib/node_modules/angular-cli/commands/serve.js:67:16)
    at Class.<anonymous> (/usr/local/lib/node_modules/angular-cli/ember-cli/lib/models/command.js:134:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

### Desired functionality.

Learning to use angular/cli

**Comment by wulfsberg** [comment]
Every time I get some variation of this, I end up blowing away my node_modules and reinstalling. It is not optimal, but it has solved the problem for me every time. But it makes me wonder if it is an Angular/CLI issue, or a npm issue

**Comment by Thugkitty** [comment]
How do i delete the node_models?

**Comment by tobiashoeft** [comment]
I've got the same problem.

**Comment by CraigWarford** [comment]
I have the same problem.  I also tried removing node_modules, but with the latest angular and angular-cli, everything will not reinstall correctly.  If I run npm install by itself, I end up with unmet dependencies for @angular/common, /core, /http and /platform-browser (which want rxjs^5.0.1, and 5.4.2 is installed by npm).  If I manually install all of the unmet dependencies, then run ng serve, it tells me @angular/compiler-cli is not properly installed.  Running npm install on that (and @angular/compiler) does not fix the problem.  Also, if I run npm install after all of that, it causes the unmet dependencies with /common, /core, /http and /platform-browser to return, and I'm back to where I started.

Everything was working fine about a week ago while still on 4.2.1.  But I can't even go back to that one, even if I lock the old versions of everything in place.  It's broken pretty bad.  My CI build is now stuck in the mud, and won't run, because it can't construct the node_modules either with my old versions or the new.  It's getting so that we're going to have to start checking node_modules into git, just to be sure changes don't break everything and grind work to a halt for multiple days.

I guess my next step will be to try and rebuild from the latest CLI project, run the app generator, move all my app code into it, and see if that works.  If we can't keep it running any better, though, we'll have to dump CLI altogether.  Can't afford the work stoppage that happens even when no changes to the modules have been made.

**Comment by Thugkitty** [comment]
How does this work on windows? Same errors?

**Comment by filipesilva** [comment]
My experience is the same as @wulfsberg : if you delete the `node_modules` folder (should be inside your project, at the root) and reinstall (`npm install`) these problems go away. This is common for both Windows/OSX/Linux.

But bear in mind that you are using an old and unsupported version of Angular CLI as shown by the error message. You can find instructions on how to update in https://github.com/angular/angular-cli#updating-angular-cli.

**Comment by filipesilva** [comment]
@CraigWarford you should look into lockfiles. Either https://yarnpkg.com/lang/en/ or npm5 will produce lockfiles by default. Without a lockfile you just have no guarantee the same versions of packages are installed. If I had to bet your problem is caused by a npm proxy you are using, that has some unmatched versions of libraries installed.

If you get peer dependency warnings when doing a npm install after removing node modules, you really have to fix it otherwise you're bound to get problems. Make sure all your `@angular/*` (except the CLI) are at the same version and pay close attention to the peer dependency error messages.

**Comment by CraigWarford** [comment]
Thanks @filipesilva, I actually discovered that the issue was due to a symlink folder being used. Upon inspection of the npm install output, there was one package that would not install on the symlink, which I believe was acorn.  I did open a separate issue and close that out with the full info: #7173
