### ISSUE TITLE
absolute paths of helper classes fails in docker image but not local

### ISSUE THREAD

**Issue by neridonk** [angular/angular-cli#7120]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
1.2

### Repro steps.
1. Create a project with a simple.component
2. Create a folder in src named test (or anything) and a Helper.ts class
3. Use it in your simple-component.spec.ts
4.  weboaks/node-karma-protractor-chrome as docker image and run ng test 

### The log given by the failure.
`Cannot find module 'test/Helper'`... 
and
...
 Can't resolve 'test/Helper' in 'simple'
    at Compiler.compiler.plugin (node_modules/@angular/cli/plugins/karma-webpack-throw-error.js:10:23)
    at Compiler.applyPlugins (/builds/leitung/jikan/src/Frontend/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/builds/leitung/jikan/src/Frontend/node_modules/webpack/lib/Compiler.js:92:17)
    at onCompiled (/builds/leitung/jikan/src/Frontend/node_modules/webpack/lib/Compiler.js:51:17)
    at /builds/leitung/jikan/src/Frontend/node_modules/webpack/lib/Compiler.js:494:13

### Mention any other details that might be useful.
docker image :  weboaks/node-karma-protractor-chrome

**Comment by neridonk** [comment]
Ok source control bug of VStudio
