### ISSUE TITLE
@ngtools/webpack's is not verbose (enough)

### ISSUE THREAD

**Issue by dhardtke** [angular/angular-cli#7126]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
I don't know if it is intentional that @ngtools/webpack is not really verbose when it comes to compile errors in the application. I have the case that I get the output below when I compile my application, yet `ngc -p tsconfig-aot.json` runs perfectly fine. After running `ngc` I can then compile my app properly using webpack with @ngtools/webpack.

I really have no proper way of debugging other than just removing several parts of my application and trying to compile it afterwards.

### Versions.
node --version
v8.1.0
yarn --version
0.27.5
@ngtools/webpack: 1.5.3
webpack: 3.3.0

Windows 10 (latest), 64 Bit

### Repro steps.
---

### The log given by the failure.
```
ModuleNotFoundError: Module not found: Error: Can't resolve '../compiled/app/app.module.ngfactory' in 'C:\client\app'
    at factoryCallback (C:\client\node_modules\webpack\lib\Compilation.js:264:39)
    at factory (C:\client\node_modules\webpack\lib\NormalModuleFactory.js:247:20)
    at resolver (C:\client\node_modules\webpack\lib\NormalModuleFactory.js:65:21)
    at asyncLib.parallel (C:\client\node_modules\webpack\lib\NormalModuleFactory.js:138:21)
    at C:\client\node_modules\async\dist\async.js:3861:9
    at C:\client\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\client\node_modules\async\dist\async.js:996:13)
    at C:\client\node_modules\async\dist\async.js:906:16
    at C:\client\node_modules\async\dist\async.js:3858:13
    at resolvers.normal.resolve (C:\client\node_modules\webpack\lib\NormalModuleFactory.js:130:23)
    at onError (C:\client\node_modules\enhanced-resolve\lib\Resolver.js:65:10)
    at loggingCallbackWrapper (C:\client\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (C:\client\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (C:\client\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (C:\client\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\client\node_modules\tapable\lib\Tapable.js:234:11)
    at C:\client\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (C:\client\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (C:\client\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (C:\client\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (C:\client\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\client\node_modules\tapable\lib\Tapable.js:234:11)
    at innerCallback (C:\client\node_modules\enhanced-resolve\lib\Resolver.js:144:11)
    at loggingCallbackWrapper (C:\client\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\client\node_modules\tapable\lib\Tapable.js:231:35)
    at resolver.doResolve.createInnerCallback (C:\client\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (C:\client\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (C:\client\node_modules\enhanced-resolve\lib\Resolver.js:168:10)
    at loggingCallbackWrapper (C:\client\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (C:\client\node_modules\tapable\lib\Tapable.js:234:11)
resolve '../compiled/app/app.module.ngfactory' in 'C:\client\app'
  using description file: C:\client\package.json (relative path: ./app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\client\package.json (relative path: ./app)
    using description file: C:\client\package.json (relative path: ./compiled/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\client\compiled\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\client\compiled\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\client\compiled\app\app.module.ngfactory.js doesn't exist
      as directory
        C:\client\compiled\app\app.module.ngfactory doesn't exist
```

### Desired functionality.
I would like to get at least some info about what is going wrong. Setting webpack's verbose flag (on the CLI) or using the `LoaderOptionsPlugin` with `verbose: true` doesn't change anything.

### Mention any other details that might be useful.
Sry, it's not an OSS project :(

**Comment by dhardtke** [comment]
Just saw this issue: https://github.com/angular/angular-cli/issues/7113

Seems to be why the build failed - anyway: My issue then is more a feature request, really. Is there a way to add some output to ngtools/webpack's internals?

**Comment by enjoiful** [comment]
Absolutely this needs to be supported.  Its maddening to try and figure out which part of my code broke AOT -- and the only way to do it is to incrementally removing parts of my app.

**Comment by dhardtke** [comment]
Closing this as I just saw #6918

**Comment by PachowStudios** [comment]
@dhardtke See my comment here for a workaround https://github.com/angular/angular-cli/issues/6918#issuecomment-323810736
