### ISSUE TITLE
"allowJs" in tsconfig.json or tsconfig.app.json throws "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by zhaider** [angular/angular-cli#7315]
**angular/cli 1.2.7**

**tsconfig.json looks like**
{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "baseUrl": "src",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "allowJs": true,
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2016",
            "dom"
        ]
    }
}
**tsconfig.app.json is**
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "outDir": "../out-tsc/app",
        "module": "es2015",
        "allowJs": true,
        "baseUrl": "",
        "types": []
    },
    "exclude": [
        "test.ts",
        "**/*.spec.ts"
    ]
}

**ng serve/build both throw this error**

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:15457:109)
    at parseSourceFileWorker (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:15389:26)
    at Object.parseSourceFile (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:15338:26)
    at Object.createSourceFile (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:15192:29)
    at WebpackCompilerHost.getSourceFile (C:\src\CRSP\crsp-app\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\compiler_host.js:210:27)
    at findSourceFile (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:67909:29)
    at processSourceFile (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:67840:27)
    at C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:67950:17
    at Object.forEach (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:1449:30)
    at processReferencedFiles (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:67948:16)
    at findSourceFile (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:67933:21)
    at processSourceFile (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:67840:27)
    at processRootFile (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:67728:13)
    at C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:67018:60
    at Object.forEach (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:1449:30)
    at Object.createProgram (C:\src\CRSP\crsp-app\node_modules\typescript\lib\typescript.js:67018:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crsp-app@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crsp-app@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zhaider** [comment]
This issue is resolved now. 
Had to run TS compiler manually with --allowJs flag then figured out that one of the JQuery file was missing. Surprised that file was NOT referenced anywhere in the project. May be some 3rd party controls had hooks with it.

**Comment by compleatguru** [comment]
@zhaider, how do you run TS compiler manually? Is it together with ng serve?

**Comment by zhaider** [comment]
Please checkout
https://stackoverflow.com/questions/33535879/how-to-run-typescript-files-from-command-line
