### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed

### ISSUE THREAD

**Issue by st-clair-clarke** [angular/angular-cli#732]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS 10. 

2. Versions. 
angular-cli: 1.0.0-beta.1
node: 5.10.1
os: win32 x64

3. Repro steps. 
ng build

4. The log given by the failure. 

J:\workspace\epimss\angular2\ts\my-project>ng build

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Build failed.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, symlink 'J:\workspace\epimss\angular2\ts\my-project\tmp\broccoli_type_script_c
ompiler-cache_path-UPdAwLpe.tmp\src\app\environment.js.map' -> 'J:\workspace\epimss\angular2\ts\my-project\tmp\brocco
li_type_script_compiler-output_path-RoutTdDi.tmp\src\app\environment.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at BroccoliTypeScriptCompiler._outputFile (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\li
b\broccoli\broccoli-typescript.js:206:8)
    at J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18

    at Array.forEach (native)
    at J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30

    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (J:\workspace\epimss\angular2\ts\my-project\node_modules\angula
r-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\lib\broc
coli\broccoli-typescript.js:43:10)
    at J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_modules\broccoli-caching-writer\index
.js:152:21
    at lib$rsvp$$internal$$tryCatch (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_modules
\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_m
odules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_modules\
broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_modules\broccol
i-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_mo
dules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (J:\workspace\epimss\angular2\ts\my-project\node_mod
ules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\lib\broccoli\b
roccoli-typescript.js:26:49)
    at Angular2App._getTsTree (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\lib\broccoli\angul
ar2-app.js:280:18)
    at Angular2App._buildTree (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\lib\broccoli\angul
ar2-app.js:101:23)
    at new Angular2App (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\lib\broccoli\angular2-app
.js:42:23)
    at module.exports (J:\workspace\epimss\angular2\ts\my-project\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (J:\workspace\epimss\angular2\ts\my-project\node_modules
\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\nod
e_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_modules\angular-cli\node_m
odules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node
_modules\angular-cli\lib\tasks\build.js:15:19)
    at J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_modules\angular-cli\lib\commands\buil
d.js:32:24
    at lib$rsvp$$internal$$tryCatch (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_modules
\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_m
odules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_modules\
angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (J:\workspace\epimss\angular2\ts\my-project\node_modules\angular-cli\node_modules\angular
-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by chriscamicas** [comment]
Same here (Running without elevated rights)
but it builds with an elevated prompt

**Comment by hansl** [comment]
Because BroccoliFunnel uses symlinks by default, we need administrative rights on Windows. You can update your policies to include the creation symbolic links for non administrative people, and it would work.

**Comment by st-clair-clarke** [comment]
@hansl I am the administrator of my computer. How do I update these policies you mentioned.

**Comment by gkalpak** [comment]
There is an outline [here][1]. Note, that if you are an administrator (and UAC is enabled), you still need to run as administrator even if you have enabled the policy.

[1]: http://ember-cli.com/user-guide/#symlinks-on-windows
