### ISSUE TITLE
es6-shim doesn't satisfy peer dependency (pre-release)

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular-cli#733]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX

2. Versions. Please run `ng --version`. If there's nothing outputted, please

1.0.0-beta.2-mobile@next

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

`ng new --mobile my-app`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
The package es6-shim@0.33.13 does not satisfy its siblings' peerDependencies requirements!
Error: The package es6-shim@0.33.13 does not satisfy its siblings' peerDependencies requirements!
    at angular-cli/node_modules/npm/lib/install.js:125:32
    at angular-cli/node_modules/npm/lib/install.js:268:7
    at angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
    at angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (angular-cli/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (angular-cli/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (angular-cli/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at angular-cli/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
```

5. Mention any other details that might be useful.

Whoever introduced this bug should be FIREDDDDDD

**Comment by jeffbcross** [comment]
Also universal currently has a hard dependency on router-deprecated.
