### ISSUE TITLE
Cannot find module 'magic-string'

### ISSUE THREAD

**Issue by florinbardosi** [angular/angular-cli#7336]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.0
node: 8.1.2
os: darwin x64
@angular/animations: 4.3.3
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/platform-server: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.3.0
@angular/compiler-cli: 4.3.3
@angular/language-service: 4.3.3

 macOS Sierra

### Repro steps.

Running ng serve an error is thrown

### The log given by the failure.

Cannot find module 'magic-string'
Error: Cannot find module 'magic-string'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/florinbardosi/Projects/GitLab/Swisscom/SwisscomTVWebRnB/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/refactor.js:7:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/florinbardosi/Projects/GitLab/Swisscom/SwisscomTVWebRnB/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/entry_resolver.js:6:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

**Comment by austinthedeveloper** [comment]
Did you update to the new version using `npm udpdate`? I ran into this same issue but fixed it by running the "Update Local project package" commands:

```
rm -rf node_modules dist # use rmdir /S/Q node_modules dist in Windows Command Prompt; use rm -r -fo node_modules,dist in Windows PowerShell
npm install --save-dev @angular/cli@latest
npm install
```

**Comment by florinbardosi** [comment]
I've tried and now it's working. Thanks
