### ISSUE TITLE
ng build fails to copy to dist folder with folder names shorter than 5 characters

### ISSUE THREAD

**Issue by OasisLiveForever** [angular/angular-cli#734]
**1. OS**
Windows 10 Enterprise 64 bit

**2. Versions**
angular-cli: 1.0.0-beta.1
node: 6.1.0

**3. Repro steps.**
- Create an app with angular-cli
- Create i18n folder under app src\app\assets
- Launch ng build

**4. Log**
Build failed.
EPERM: operation not permitted, unlink 'E:\projects\test angular\dist\app\assets'
Error: EPERM: operation not permitted, unlink 'E:\projects\test angular\dist\app\assets'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1083:18)
    at TreeSync.<anonymous> (E:\projects\test angular\node_modules\angular-cli\node_modules\angular-cli\node_modules\tree-sync\index.js:71:21)
    at Array.forEach (native)
    at TreeSync.sync (E:\projects\test angular\node_modules\angular-cli\node_modules\angular-cli\node_modules\tree-sync\index.js:50:14)
    at Class.module.exports.Task.extend.copyToOutputPath (E:\projects\test angular\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:124:10)
    at E:\projects\test angular\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:132:21
    at lib$rsvp$$internal$$tryCatch (E:\projects\test angular\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (E:\projects\test angular\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at E:\projects\test angular\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:331:11
    at lib$rsvp$asap$$flush (E:\projects\test angular\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**5. More details**
It seems ng build fails with folder names shorter than 5 characters.

**Comment by DevVersion** [comment]
Did you run your CMD with Administrator Permissions?

**Comment by OasisLiveForever** [comment]
Yes, I run CMD with Administrator permissions. If I rename the folder from i18n to i18n2, ng build works correctly.

**Comment by sgbeal** [comment]
@OasisLiveForever our project has several short names ('core', 'mock', etc) and we don't have this problem.

**Comment by OasisLiveForever** [comment]
@sgbeal This morning I tried to clean manually dist folder before building and now everything works fine. I let you know if I found a way to systematically reproduce the problem.

**Comment by hansl** [comment]
Thanks, this is odd. If you find a way, please file a bug with repro steps.

**Comment by sgbeal** [comment]
A _TINY LITTLE HINT_ about where it could _possibly_ be happening is all i'm asking for. The error _clearly_ comes from code outside our project, but is clearly triggered by "something" in our project (which, i reiterate, builds and runs fine without the -prod flag in all angular-cli versions, and _with_ the -prod flag in versions 0.0.34 and older, so the bug is _obviously_ somewhere outside our code). The message is absolutely useless and precludes any chance of even beginning to find where the problem is.

**Comment by hansl** [comment]
It might also be coming from Broccoli, or Ember CLI, which we use extensively in our build system.

Seems to be a permission thing. Maybe your user created some files with some permission (you built once using a different user?) and the build system didn't have the permissions needed to overwrite those files?

**Comment by sgbeal** [comment]
This is all under ./tmp, which your build process creates. i regularly delete ./tmp (several times per day) because i don't like that so many files are left lying around in there. This is a single-user system and terminals are only run with admin permissions (because npm doesn't work without that). We're all at an utter loss.
