### ISSUE TITLE
Universal - No provider for n!

### ISSUE THREAD

**Issue by dottodot** [angular/angular-cli#7442]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.3.1
node: 6.11.1
os: darwin x64
@angular/animations: 4.3.5
@angular/cli: 1.3.1
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/compiler-cli: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/platform-server: 4.3.5
@angular/router: 4.3.5
@angular/service-worker: 1.0.0-beta.16
@angular/language-service: 4.3.5

The client version of my app works fine but for server side it gives the following error, which gives me very little information on what the problem is and I'm running out of ideas
```
Error: No provider for n!
    at Error (native)
    at injectionError (/node_modules/@angular/core/bundles/core.umd.js:1201:90)
    at noProviderError (/node_modules/@angular/core/bundles/core.umd.js:1239:12)
    at ReflectiveInjector_._throwOrNull (/node_modules/@angular/core/bundles/core.umd.js:2681:19)
    at ReflectiveInjector_._getByKeyDefault (/node_modules/@angular/core/bundles/core.umd.js:2720:25)
    at ReflectiveInjector_._getByKey (/node_modules/@angular/core/bundles/core.umd.js:2652:25)
    at ReflectiveInjector_.get (/node_modules/@angular/core/bundles/core.umd.js:2521:21)
    at resolveNgModuleDep (/node_modules/@angular/core/bundles/core.umd.js:9508:25)
    at NgModuleRef_.get (/node_modules/@angular/core/bundles/core.umd.js:10596:16)
    at resolveDep (/node_modules/@angular/core/bundles/core.umd.js:11099:45)
    at createClass (/node_modules/@angular/core/bundles/core.umd.js:10963:32)
    at createDirectiveInstance (/node_modules/@angular/core/bundles/core.umd.js:10783:37)
    at createViewNodes (/node_modules/@angular/core/bundles/core.umd.js:12219:49)
    at createRootView (/node_modules/@angular/core/bundles/core.umd.js:12114:5)
    at Object.createProdRootView [as createRootView] (/node_modules/@angular/core/bundles/core.umd.js:12799:12)
    at ComponentFactory_.create (/node_modules/@angular/core/bundles/core.umd.js:9891:46)
```

**Comment by dottodot** [comment]
I had missed adding `"baseUrl": "./",` in my tsconfig.server.json which seem to have fixed it along with `There are multiple modules with names that only differ in casing.` errors.
