### ISSUE TITLE
Issues with sass. Seems like brocolli compile files in own order

### ISSUE THREAD

**Issue by Arth95** [angular/angular-cli#745]
Windows 8.1

angular-cli: 0.0.39
node: 5.3.0
os: win32 x64

I downloaded Bulma sass framework. I wanted to play with it and with Angular 2, so I installed node-sass, changed projectname-component.css to *.sass and imported bulma.sass(main file of this framework). When i hit ng serve it throwed this error:

```
Build failed.
File: F:/angular2/Booky/tmp/sassplugin-input_base_path-QX0A44e3.tmp/0/src/app/styles/bulma/sass/base/generic.sass (2)
The Broccoli Plugin: [SASSPlugin] failed with:
Error: Undefined variable: "$body-background".
    at Object.module.exports.renderSync (F:\angular2\Booky\node_modules\node-sass\lib\index.js:418:22)
    at SASSPlugin.compile (F:\angular2\Booky\node_modules\angular-cli\lib\broccoli\angular-broccoli-sass.js:48:25)
    at F:\angular2\Booky\node_modules\angular-cli\lib\broccoli\angular-broccoli-sass.js:29:12
    at Array.forEach (native)
    at SASSPlugin.build (F:\angular2\Booky\node_modules\angular-cli\lib\broccoli\angular-broccoli-sass.js:27:22)
    at F:\angular2\Booky\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (F:\angular2\Booky\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (F:\angular2\Booky\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (F:\angular2\Booky\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (F:\angular2\Booky\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

The broccoli plugin was instantiated at:
    at SASSPlugin.Plugin (F:\angular2\Booky\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at SASSPlugin.CachingWriter [as constructor] (F:\angular2\Booky\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at new SASSPlugin (F:\angular2\Booky\node_modules\angular-cli\lib\broccoli\angular-broccoli-sass.js:20:12)
    at Object.Plugin.build.exports.makeBroccoliTree (F:\angular2\Booky\node_modules\angular-cli\lib\broccoli\angular-broccoli-sass.js:68:12)
    at Angular2App._buildTree (F:\angular2\Booky\node_modules\angular-cli\lib\broccoli\angular2-app.js:110:27)
    at new Angular2App (F:\angular2\Booky\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (F:\angular2\Booky\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (F:\angular2\Booky\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (F:\angular2\Booky\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (F:\angular2\Booky\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (F:\angular2\Booky\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at F:\angular2\Booky\node_modules\angular-cli\node_modules\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (F:\angular2\Booky\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (F:\angular2\Booky\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (F:\angular2\Booky\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (F:\angular2\Booky\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

What can cause this problem?

**Comment by hansl** [comment]
You might want to specify sass compiler options with an include path, like so:

```javascript
  var angularAppTree = new Angular2App(defaults, {
    sassCompiler: {
      includePaths: [
        'src/core/style'
      ]
    },
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/*.js',
      'es6-shim/es6-shim.js',
      'reflect-metadata/*.js',
      'rxjs/**/*.js',
      '@angular/**/*.js',
    ]
  });
```

**Comment by stellasoft-will** [comment]
i have tried this and it did not work, i have added the 

sassCompiler: {
      includePaths: [
        'src/core/style'
      ]
    },

to my angular-cli-build.js, any ideas?
