### ISSUE TITLE
1.3.1. Error running install script for optional dependency: "\\node_modules\\node-sass:

### ISSUE THREAD

**Issue by kuncevic** [angular/angular-cli#7451]
```
- [ x] bug report -> please search issues before submitting
```

### Versions.
@angular/cli: 1.3.1
node: 8.4.0
os: win32 x64
@angular/animations: 4.3.4
@angular/common: 4.3.4
@angular/compiler: 4.3.4
@angular/core: 4.3.4
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.3.4
@angular/http: 4.3.4
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.3.4
@angular/platform-browser-dynamic: 4.3.4
@angular/router: 4.3.4
@angular/cli: 1.3.1
@angular/compiler-cli: 4.3.4

### Repro steps.
`yarn add @angular/cli@1.3.1`

### The log given by the failure.

[1/1] ⠄ node-sass: gyp ERR! not ok
[-/1] ⠄ waiting...
warning Error running install script for optional dependency: "c:\\Projects\\node_modules\\node-sass: Command failed.\nExit code: 1\nCommand: C:\\Windows\\system32\\cmd.exe\nArguments: /d /s /c node scripts/build.js\nDirectory: c:\\Projects\\node_modules\\node-sass\nOutput:\nBuilding: C:\\Program Files\\nodejs\\node.exe c:\\Projects\\node_modules\\node-gyp\\bin\\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=\ngyp info it worked if it ends with ok\ngyp verb cli [ 'C:\\\\Program Files\\\\nodejs\\\\node.exe',\ngyp verb cli   'c:\\\\Projects\\\\Source\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js',\ngyp verb cli   'rebuild',\ngyp verb cli   '--verbose',\ngyp verb cli   '--libsass_ext=',\ngyp verb cli   '--libsass_cflags=',\ngyp verb cli   '--libsass_ldflags=',\ngyp verb cli   '--libsass_library=' ]\ngyp info using node-gyp@3.6.0\ngyp info using node@8.4.0 | win32 | x64\ngyp verb command rebuild []\ngyp verb command clean []\ngyp verb clean removing \"build\" directory\ngyp verb command configure []\ngyp verb check python checking for Python executable \"python2\" in the PATH\ngyp verb `which` failed Error: not found: python2\ngyp verb `which` failed     at getNotFoundError (c:\\Projects\\node_modules\\which\\which.js:13:12)\ngyp verb `which` failed     at F (c:\\Projects\\node_modules\\which\\which.js:68:19)\ngyp verb `which` failed     at E (c:\\Projects\\node_modules\\which\\which.js:80:29)\ngyp verb `which` failed     at c:\\Projects\\node_modules\\which\\which.js:89:16\ngyp verb `which` failed     at c:\\Projects\\node_modules\\isexe\\index.js:42:5\ngyp verb `which` failed     at c:\\Projects\\node_modules\\isexe\\windows.js:36:5\ngyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)\ngyp verb `which` failed  python2 { Error: not found: python2\ngyp verb `which` failed     at getNotFoundError (c:\\Projects\\node_modules\\which\\which.js:13:12)\ngyp verb `which` failed     at F (c:\\Projects\\node_modules\\which\\which.js:68:19)\ngyp verb `which` failed     at E (c:\\Projects\\node_modules\\which\\which.js:80:29)\ngyp verb `which` failed     at c:\\Projects\\node_modules\\which\\which.js:89:16\ngyp verb `which` failed     at c:\\Projects\\node_modules\\isexe\\index.js:42:5\ngyp verb `which` failed     at c:\\Projects\\node_modules\\isexe\\windows.js:36:5\ngyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }\ngyp verb check python checking for Python executable \"python\" in the PATH\ngyp verb `which` succeeded python C:\\tools\\Python27\\python.EXE\ngyp verb check python version `C:\\tools\\Python27\\python.EXE -c \"import platform; print(platform.python_version());\"` returned: \"2.7.13\\r\\n\"\ngyp verb get node dir no --target version specified, falling back to host node version: 8.4.0\ngyp verb command install [ '8.4.0' ]\ngyp verb install input version string \"8.4.0\"\ngyp verb install installing version: 8.4.0\ngyp verb install --ensure was passed, so won't reinstall if already installed\ngyp verb install version is already installed, need to check \"installVersion\"\ngyp verb got \"installVersion\" 9\ngyp verb needs \"installVersion\" 9\ngyp verb install version is good\ngyp verb get node dir target node version installed: 8.4.0\ngyp verb build dir attempting to create \"build\" dir: c:\\Projects\\node_modules\\node-sass\\build\ngyp verb build dir \"build\" dir needed to be created? c:\\Projects\\node_modules\\node-sass\\build\ngyp verb Not using VS2017: Could not use PowerShell to find VS2017\ngyp verb build/config.gypi creating config file\ngyp verb build/config.gypi writing out config file: c:\\Projects\\node_modules\\node-sass\\build\\config.gypi\ngyp verb config.gypi checking for gypi file: c:\\Projects\\node_modules\\node-sass\\config.gypi\ngyp verb common.gypi checking for gypi file: c:\\Projects\\node_modules\\node-sass\\common.gypi\ngyp verb gyp gyp format was not specified; forcing \"msvs\"\ngyp info spawn C:\\tools\\Python27\\python.EXE\ngyp info spawn args [ 'c:\\\\Projects\\\\Source\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'msvs',\ngyp info spawn args   '-G',\ngyp info spawn args
'msvs_version=auto',\ngyp info spawn args   '-I',\ngyp info spawn args   'c:\\\\Projects\\\\Source\\\\node_modules\\\\node-sass\\\\build\\\\config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'c:\\\\Projects\\\\Source\\\\node_modules\\\\node-gyp\\\\addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   'C:\\\\Users\\\\a\\\\.node-gyp\\\\8.4.0\\\\include\\\\node\\\\common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\a\\\\.node-gyp\\\\8.4.0',\ngyp info spawn args   '-Dnode_gyp_dir=c:\\\\Projects\\\\Source\\\\node_modules\\\\node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=c:\\\\Projects\\\\Source\\\\node_modules\\\\node-sass',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'c:\\\\Projects\\\\Source\\\\node_modules\\\\node-sass\\\\build',\ngyp info spawn args   '-Goutput_dir=.' ]\ngyp verb command build []\ngyp verb build type Release\ngyp verb architecture x64\ngyp verb node dev dir C:\\Users\\a\\.node-gyp\\8.4.0\ngyp verb found first Solution file build/binding.sln\ngyp verb could not find \"msbuild.exe\" in PATH - finding location in registry \ngyp verb \"Release\" dir needed to be created? null\ngyp verb copying \"node.lib\" for x64 C:\\Users\\a\\.node-gyp\\8.4.0\\Release\\node.lib\ngyp info spawn C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe\ngyp info spawn args [ 'build/binding.sln',\ngyp info spawn args   '/nologo',\ngyp info spawn args   '/p:Configuration=Release;Platform=x64' ]\nBuilding the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.\r\nBuild started 08/21/2017 12:32:56.\r\nProject \"c:\\Projects\\node_modules\\node-sass\\build\\binding.sln\" on node 1 (default targets).\r\nValidateSolutionConfiguration:\r\n  Building solution configuration \"Release|x64\".\r\nProject \"c:\\Projects\\node_modules\\node-sass\\build\\binding.sln\" (1) is building \"c:\\Projects\\node_modules\\node-sass\\build\\binding.vcxproj.metaproj\" (2) on node 1 (default targets).\r\nProject \"c:\\Projects\\node_modules\\node-sass\\build\\binding.vcxproj.metaproj\" (2) is building \"c:\\Projects\\node_modules\\node-sass\\build\\src\\libsass.vcxproj\" (3) on node 1 (default targets).\r\nc:\\Projects\\node_modules\\node-sass\\build\\src\\libsass.vcxproj(20,3): error MSB4019: The imported project \"c:\\Microsoft.Cpp.Default.props\" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.\r\nDone Building Project \"c:\\Projects\\node_modules\\node-sass\\build\\src\\libsass.vcxproj\" (default targets) -- FAILED.\r\nDone Building Project \"c:\\Projects\\node_modules\\node-sass\\build\\binding.vcxproj.metaproj\" (default targets) -- FAILED.\r\nDone Building Project \"c:\\Projects\\node_modules\\node-sass\\build\\binding.sln\" (default targets) -- FAILED.\r\n\r\nBuild FAILED.\r\n\r\n\"c:\\Projects\\node_modules\\node-sass\\build\\binding.sln\" (default target) (1) ->\r\n\"c:\\Projects\\node_modules\\node-sass\\build\\binding.vcxproj.metaproj\" (default target) (2) ->\r\n\"c:\\Projects\\node_modules\\node-sass\\build\\src\\libsass.vcxproj\" (default target) (3) ->\r\n  c:\\Projects\\node_modules\\node-sass\\build\\src\\libsass.vcxproj(20,3): error MSB4019: The imported project \"c:\\Microsoft.Cpp.Default.props\" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.\r\n\r\n    0 Warning(s)\r\n    1 Error(s)\r\n\r\nTime Elapsed 00:00:00.13\r\ngyp ERR! build error \ngyp ERR! stack Error: `C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\msbuild.exe` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onExit (c:\\Projects\\node_modules\\node-gyp\\lib\\build.js:285:23)\ngyp ERR! stack     at emitTwo (events.js:125:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:213:7)success Saved lockfile.

### Desired functionality.
`yarn add @angular/cli@1.3.1` should install the package successfully.

### Mention any other details that might be useful.
Just was switching to the new `@angular/cli@1.3.1` and got this issue with node-sass not getting properly installed.
I was trying to fight that issue for quite a while by switching to different node versions, cleaning up the yarn cache, etc. but didn't help.  Currently just switched back to `@angular/cli@1.3.0` which is works just fine.

**Comment by kuncevic** [comment]
Just noticed that `package.json`  wasn't being properly updated. After fixing that all seams to be looking good.
removed:
```
-"karma-phantomjs-launcher": "^1.0.4",
-"karma-remap-istanbul": "0.2.2",
```
updated:
```
+"@types/jasmine": "~2.5.53",
+"karma": "~1.7.0",
+"karma-chrome-launcher": "~2.1.1",
+"karma-coverage-istanbul-reporter": "^1.2.1",
+"protractor": "~5.1.2",
+"ts-node": "~3.2.0",
+"tslint": "~5.3.2",
```
added:
```
++"@types/jasminewd2": "~2.0.2",
```
But I want to keep an eye on that for some more time.
