### ISSUE TITLE
Cannot read property 'Private' of undefined

### ISSUE THREAD

**Issue by rania-bel-arbi** [angular/angular-cli#7456]
C:\Users\spot-info\Desktop\site-pawo\site>ng serve
The "@angular/compiler-cli" package was not properly installed. Error: TypeError: Cannot read property 'Private' of undefined
Error: The "@angular/compiler-cli" package was not properly installed. Error: TypeError: Cannot read property 'Private' of undefined
    at Object.<anonymous> (C:\Users\spot-info\Desktop\site-pawo\site\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\spot-info\Desktop\site-pawo\site\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by hansl** [comment]
Please follow the issue template.

Also, it seems the error is `The "@angular/compiler-cli" package was not properly installed.`, which points to a problem on your side, in your installation. There's nothing we can do if that's the case. Maybe try to provide us with a github repo that reproduce the error? thanks!
