### ISSUE TITLE
@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler

### ISSUE THREAD

**Issue by omanigaming** [angular/angular-cli#7503]
I can not run ng serve!!

### Versions.

"@angular/cli: 1.3.2
node: 8.4.0
os: win32 x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: error
@angular/compiler-cli: error
@angular/language-service: error"

### Repro steps.

The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler'
    at Object.<anonymous> (C:\Users\mohammecd\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\mohammecd\AppData\Roaming\npm\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)

**Comment by Brocco** [comment]
npm installations sometimes do not complete successfully, please delete the `node_modules` folder and reinstall via `npm install`

If this issue persists, please open a new issue (and reference this issue).

**Comment by santiagodesimoni26** [comment]
i've got this error:
 The "@angular/compiler-cli" package was not properly installed. Error:nnot find module '@angular/compiler-cli'
    at Object.CompilerCliIsSupported (C:\Users\santi\AppData\Roaming\ndules\@angular\cli\node_modules\@ngtools\webpack\src\ngtools_api.js:25
    at new AotPlugin (C:\Users\santi\AppData\Roaming\npm\node_modules\li\node_modules\@ngtools\webpack\src\plugin.js:28:23)
    at _createAotPlugin (C:\Users\santi\AppData\Roaming\npm\node_modulr\cli\models\webpack-configs\typescript.js:92:16)
    at Object.getNonAotConfig (C:\Users\santi\AppData\Roaming\npm\nodeangular\cli\models\webpack-configs\typescript.js:100:19)
    at NgCliWebpackConfig.buildConfig (C:\Users\santi\AppData\Roaming\odules\@angular\cli\models\webpack-config.js:41:37)
    at Class.run (C:\Users\santi\AppData\Roaming\npm\node_modules\@angasks\serve.js:71:98)
    at check_port_1.checkPort.then.port (C:\Users\santi\AppData\Roamin_modules\@angular\cli\commands\serve.js:123:26)
when i y use ng serve  my package json dependencies are : 


 "@angular/cli": "~1.7.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3",
    "uglifyjs-webpack-plugin": "^1.0.0-rc.0"
