### ISSUE TITLE
fix(mobile): AppShellPlugin for Broccoli failed systematically on rebuild

### ISSUE THREAD

**Issue by pkamdem** [angular/angular-cli#752]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX - El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
angular-cli: 1.0.0-beta.2-mobile
node: 6.1.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

- ng new demo-mobile --mobile --prefix dm
- npm start
- Ensure the browser displays title 'demo-mobile works!'
- Change title property on DemoMobileAppComponent to 'demo-mobile works! :)'

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
Build successful - 2243ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
BroccoliTypeScriptCompiler                    | 881ms               
ServiceWorkerPlugin                           | 782ms               
vendor                                        | 325ms               
AppShellPlugin                                | 170ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
BroccoliTypeScriptCompiler (1)                | 881ms               
ServiceWorkerPlugin (1)                       | 782ms               
vendor (1)                                    | 325ms               
AppShellPlugin (1)                            | 170ms               

file changed app/demo-mobile.component.ts
The Broccoli Plugin: [AppShellPlugin] failed with:
Error: There can be only one platform. Destroy the previous one to create a new one.
    at new BaseException (/Users/Philippe/Desktop/demo-mobile/node_modules/@angular/core/src/facade/exceptions.js:17:23)
    at Object.createPlatform (/Users/Philippe/Desktop/demo-mobile/node_modules/@angular/core/src/application_ref.js:36:15)
    at Bootloader.platform (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-universal/dist/node/bootloader.js:48:23)
    at new Bootloader (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-universal/dist/node/bootloader.js:16:33)
    at Function.Bootloader.create (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-universal/dist/node/bootloader.js:23:16)
    at AppShellPlugin.build (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-broccoli-prerender/dist/prerender.js:26:58)
    at /Users/Philippe/Desktop/demo-mobile/node_modules/angular2-broccoli-prerender/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-broccoli-prerender/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-broccoli-prerender/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-broccoli-prerender/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-broccoli-prerender/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at AppShellPlugin.Plugin (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-broccoli-prerender/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at AppShellPlugin.CachingWriter [as constructor] (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-broccoli-prerender/node_modules/broccoli-caching-writer/index.js:21:10)
    at new AppShellPlugin (/Users/Philippe/Desktop/demo-mobile/node_modules/angular2-broccoli-prerender/dist/prerender.js:15:16)
    at Angular2App._buildTree (/Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/lib/broccoli/angular2-app.js:153:48)
    at new Angular2App (/Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/Philippe/Desktop/demo-mobile/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/Philippe/Desktop/demo-mobile/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by hansl** [comment]
The mobile story is heavily under construction; please use either `latest` or `beta` releases. Mobile will be part of latest as soon as it's available and properly tested.
