### ISSUE TITLE
ng new projectname not working

### ISSUE THREAD

**Issue by jt-helsinki** [angular/angular-cli#7558]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.0-rc.2
node: 8.2.1
os: darwin x64

### Repro steps.

`npm uninstall -g @angular/cli`
`npm install -g @angular/cli@1.4.0-rc.2`
`ng new testproj`

### The log given by the failure.

```
ENOENT: no such file or directory, stat '/Users/auser/Documents/workspace/old/GH_DTS/tmp/broccoli_merge_trees-input_base_path-9MXMMyhj.tmp/0'
Error: ENOENT: no such file or directory, stat '/Users/auser/Documents/workspace/old/GH_DTS/tmp/broccoli_merge_trees-input_base_path-9MXMMyhj.tmp/0'
    at Object.fs.statSync (fs.js:954:11)
    at FileSystemHost.isDirectory (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/file-system-host.js:20:21)
    at recurse (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/tree/filesystem.js:33:26)
    at recurse (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/tree/filesystem.js:34:21)
    at recurse (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/tree/filesystem.js:34:21)
    at recurse (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/tree/filesystem.js:34:21)
    at recurse (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/tree/filesystem.js:34:21)
    at FileSystemTree._recursiveFileList (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/tree/filesystem.js:41:9)
    at FileSystemTree (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/tree/filesystem.js:17:14)
    at Class.run (/usr/local/lib/node_modules/@angular/cli/tasks/schematic-run.js:29:49)
```

### Mention any other details that might be useful.

Previous 1.3 versions work.

**Comment by clydin** [comment]
This should no longer be an issue with the latest CLI version (currently 1.6.7).  If the issue still persists with the latest CLI, please re-open the issue.
