### ISSUE TITLE
@angular/cli 1.3.0 bug on windows

### ISSUE THREAD

**Issue by damoqiongqiu** [angular/angular-cli#7580]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request



```

### Versions.

fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'E:\Test\myproj111\node_modules\_@angular_platform-browser@4.3.6@@angular\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at licensePlugin.readPackageJson (E:\Test\myproj111\node_modules\_license-webpack-plugin@0.5.1@license-webpack-plugin\index.js:26:19)
    at licensePlugin.getModuleInfo (E:\Test\myproj111\node_modules\_license-webpack-plugin@0.5.1@license-webpack-plugin\index.js:30:28)
    at licensePlugin.<anonymous> (E:\Test\myproj111\node_modules\_license-webpack-plugin@0.5.1@license-webpack-plugin\index.js:81:31)
    at Array.filter (native)
    at licensePlugin.writeModuleInfo (E:\Test\myproj111\node_modules\_license-webpack-plugin@0.5.1@license-webpack-plugin\index.js:77:8)
    at licensePlugin.gatherModuleInfo (E:\Test\myproj111\node_modules\_license-webpack-plugin@0.5.1@license-webpack-plugin\index.js:117:10)
    at licensePlugin.<anonymous> (E:\Test\myproj111\node_modules\_license-webpack-plugin@0.5.1@license-webpack-plugin\index.js:233:12)
    at Compiler.applyPlugins (E:\Test\myproj111\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:61:14)
    at Watching._done (E:\Test\myproj111\node_modules\_webpack@3.4.1@webpack\lib\Compiler.js:104:17)
    at compiler.emitRecords.err (E:\Test\myproj111\node_modules\_webpack@3.4.1@webpack\lib\Compiler.js:78:19)
    at Compiler.emitRecords (E:\Test\myproj111\node_modules\_webpack@3.4.1@webpack\lib\Compiler.js:375:38)
    at compiler.emitAssets.err (E:\Test\myproj111\node_modules\_webpack@3.4.1@webpack\lib\Compiler.js:61:20)
    at applyPluginsAsyncSeries1.err (E:\Test\myproj111\node_modules\_webpack@3.4.1@webpack\lib\Compiler.js:368:12)

**Comment by filipesilva** [comment]
Heya, please fully fill in the issue template, including a reproduction of the issue. Without these details it is very hard to investigate.
