### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by plagued911** [angular/angular-cli#7597]
Please help I am very new

root@[hidden]:/home/bot# node site.js
/home/bot/node_modules/log4js/lib/log4js.js:25
const debug = require('debug')('log4js:main');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bot/site.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by trotyl** [comment]
> Both the CLI and generated project have dependencies that require Node 6.9.0 or higher, together with NPM 3 or higher.

**Comment by filipesilva** [comment]
Heya, like @trotyl mentioned you'll need to have node 6.9.0 and npm 3 or more installed to use the CLI. If you install them your error should go away.

**Comment by plagued911** [comment]
how do i install node 6.9.0 and npm specifically like whats the command i put in putty?

**Comment by filipesilva** [comment]
@plagued911 it really depends on what system you are on. Check instructions on https://nodejs.org/en/.

**Comment by Bliizzer10** [comment]
I also need help with this :) 

MYCODE: 


/home/bot/node_modules/log4js/lib/log4js.js:25
const debug = require('debug')('log4js:main');
^^^^^

Can u help me there i user a VPS server and i already install node js :) 


Full code:


/home/bot/node_modules/log4js/lib/log4js.js:25
const debug = require('debug')('log4js:main');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/bot/site.js:2:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by TonsQ** [comment]
@filipesilva actually that doesn't work i have tried it but it doesn't change anything 
t
