### ISSUE TITLE
update to laster version --prod not work.

### ISSUE THREAD

**Issue by cipchk** [angular/angular-cli#7637]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Versions.

@angular/cli: 1.4.1
node: 6.11.3
os: win32 x64
npm: 5.3.0

### Repro steps.

```bash
ng new ng-demo -si
cnpm install
cnpm install --save ng-zorro-antd
ng build --prod
```

the `app.module.ts`:

```typescript
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgZorroAntdModule } from "ng-zorro-antd";

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    NgZorroAntdModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### The log given by the failure.

```
PS C:\Users\asdf\Desktop\work\demo\ng-demo> ng build --prod
 95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open 'C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_@angular_animations@4.3.6@@angular\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at LicenseExtractor.readPackageJson (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_license-webpack-plugin@1.0.0@license-webpack-plugin\dist\LicenseExtractor.js:121:23)
    at LicenseExtractor.parsePackage (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_license-webpack-plugin@1.0.0@license-webpack-plugin\dist\LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_license-webpack-plugin@1.0.0@license-webpack-plugin\dist\ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_license-webpack-plugin@1.0.0@license-webpack-plugin\dist\ModuleProcessor.js:21:21)
    at moduleCallback (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_license-webpack-plugin@1.0.0@license-webpack-plugin\dist\LicenseWebpackPlugin.js:80:61)
    at SortableSet.forEach (native)
    at Chunk.forEachModule (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_webpack@3.5.6@webpack\lib\Chunk.js:159:17)
    at C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_license-webpack-plugin@1.0.0@license-webpack-plugin\dist\LicenseWebpackPlugin.js:88:27
    at Array.forEach (native)
    at Compiler.<anonymous> (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_license-webpack-plugin@1.0.0@license-webpack-plugin\dist\LicenseWebpackPlugin.js:65:32)
    at next (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:204:14)
    at C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_html-webpack-plugin@2.30.1@html-webpack-plugin\index.js:204:9
    at PassThroughHandlerContext.finallyHandler (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_bluebird@3.5.0@bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_bluebird@3.5.0@bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_bluebird@3.5.0@bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_bluebird@3.5.0@bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_bluebird@3.5.0@bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_bluebird@3.5.0@bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\asdf\Desktop\work\demo\ng-demo\node_modules\_bluebird@3.5.0@bluebird\js\release\async.js:133:16)
```

### Mention any other details that might be useful.

and this `ng build --prod --extract-licenses=false` command is work.

**Comment by mygu** [comment]
I have the same issue!

**Comment by jkrot** [comment]
@cipchk can you explain why you closed this and point to the duplicate issue I am having the same problem.
