### ISSUE TITLE
npm test error - Can not load "webpack"!

### ISSUE THREAD

**Issue by martynbiz** [angular/angular-cli#7651]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
angular-cli: 1.0.0-beta.28.3
node: 6.11.0
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/compiler-cli: 2.4.10
```

### Repro steps.

```
ng new myproject
cd myproject
npm test
```

### The log given by the failure.

```
$ npm test

> myproject@0.0.0 test /Users/mb102/Sites/myproject
> ng test

As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

11 09 2017 10:05:53.990:WARN [watcher]: Pattern "/Users/mb102/Sites/myproject/src/assets/**" does not match any file.
11 09 2017 10:05:54.158:ERROR [preprocess]: Can not load "webpack"!
  TypeError: Cannot read property 'plugin' of undefined
    at PathsPlugin.apply (/Users/mb102/Sites/myproject/node_modules/@ngtools/webpack/src/paths-plugin.js:75:18)
    at Resolver.apply (/Users/mb102/Sites/myproject/node_modules/tapable/lib/Tapable.js:375:16)
    at /Users/mb102/Sites/myproject/node_modules/enhanced-resolve/lib/ResolverFactory.js:249:12
    at Array.forEach (native)
    at Object.exports.createResolver (/Users/mb102/Sites/myproject/node_modules/enhanced-resolve/lib/ResolverFactory.js:248:10)
    at WebpackOptionsApply.process (/Users/mb102/Sites/myproject/node_modules/webpack/lib/WebpackOptionsApply.js:282:46)
    at webpack (/Users/mb102/Sites/myproject/node_modules/webpack/lib/webpack.js:36:48)
    at new Plugin (/Users/mb102/Sites/myproject/node_modules/karma-webpack/lib/karma-webpack.js:63:18)
    at invoke (/Users/mb102/Sites/myproject/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/mb102/Sites/myproject/node_modules/di/lib/injector.js:59:20)
    at get (/Users/mb102/Sites/myproject/node_modules/di/lib/injector.js:48:43)
    at /Users/mb102/Sites/myproject/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/Users/mb102/Sites/myproject/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/Users/mb102/Sites/myproject/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/mb102/Sites/myproject/node_modules/karma/lib/preprocessor.js:55:20)
    at /Users/mb102/Sites/myproject/node_modules/karma/lib/preprocessor.js:106:17
    at Array.forEach (native)
    at /Users/mb102/Sites/myproject/node_modules/karma/lib/preprocessor.js:103:27
    at module.exports (/Users/mb102/Sites/myproject/node_modules/karma/node_modules/isbinaryfile/index.js:28:12)
    at /Users/mb102/Sites/myproject/node_modules/karma/lib/preprocessor.js:84:7
    at /Users/mb102/Sites/myproject/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
11 09 2017 10:05:54.163:WARN [karma]: No captured browser, open http://localhost:9876/
11 09 2017 10:05:54.170:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
11 09 2017 10:05:54.170:INFO [launcher]: Launching browser Chrome with unlimited concurrency
11 09 2017 10:05:54.171:ERROR [karma]: Found 1 load error
```

### Desired functionality.

This doesn't happen when I git clone the quickstart app:

```
git clone https://github.com/angular/quickstart.git myproject
cd myproject
npm install
npm test
```

### Mention any other details that might be useful.

I have tried to manually install both "karma-webpack" and then "webpack" but I still see this error.

**Comment by Brocco** [comment]
The quickstart is not a CLI-based project, please create this issue on that repo.

**Comment by martynbiz** [comment]
I didn't say I was using quickstart, I said "This (bug) doesn't happen when I git clone the quickstart app", **I'm using CLI tool when the bug does occur**, not quickstart, as stated in "Repro steps" above.

**Comment by MarkRidgway** [comment]
@Brocco this is very much a CLI issue. A fresh clone of the CLI is producing this error for me on a few systems.

**Comment by flooose** [comment]
This is still an issue with the `ng new` command and happens whether I use `yarn test`, `ng test`, or `karma start`:

```
$ ng --version
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".


                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.28.3
node: 8.9.3
os: linux x64
12:19:45 Projects 7286 $ ng new brokentests
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

installing ng2
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/app.module.ts
  create src/assets/.gitkeep
  create src/environments/environment.prod.ts
  create src/environments/environment.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/polyfills.ts
  create src/styles.css
  create src/test.ts
  create src/tsconfig.json
  create angular-cli.json
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tslint.json
Successfully initialized git.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Project 'brokentests' successfully created.
12:20:24 Projects 7287 $ cd brokentests/
12:20:28 brokentests 7288 (master) $ yarn test
yarn run v1.3.2
$ ng test
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

04 03 2018 12:20:32.775:WARN [watcher]: Pattern "/home/chris/Projects/brokentests/src/assets/**" does not match any file.
04 03 2018 12:20:32.831:ERROR [preprocess]: Can not load "webpack"!
  TypeError: Cannot read property 'plugin' of undefined
    at PathsPlugin.apply (/home/chris/Projects/brokentests/node_modules/@ngtools/webpack/src/paths-plugin.js:139:19)
    at Resolver.apply (/home/chris/Projects/brokentests/node_modules/tapable/lib/Tapable.js:375:16)
    at /home/chris/Projects/brokentests/node_modules/enhanced-resolve/lib/ResolverFactory.js:249:12
    at Array.forEach (<anonymous>)
    at Object.exports.createResolver (/home/chris/Projects/brokentests/node_modules/enhanced-resolve/lib/ResolverFactory.js:24
8:10)                                                                                                                        
    at WebpackOptionsApply.process (/home/chris/Projects/brokentests/node_modules/webpack/lib/WebpackOptionsApply.js:282:46)
    at webpack (/home/chris/Projects/brokentests/node_modules/webpack/lib/webpack.js:36:48)
    at Plugin (/home/chris/Projects/brokentests/node_modules/karma-webpack/lib/karma-webpack.js:63:18)
    at invoke (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:59:20)
    at get (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:48:43)
    at /home/chris/Projects/brokentests/node_modules/di/lib/injector.js:71:14
    at Array.map (<anonymous>)
    at Array.invoke (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/home/chris/Projects/brokentests/node_modules/karma/lib/preprocessor.js:55:20)
    at /home/chris/Projects/brokentests/node_modules/karma/lib/preprocessor.js:106:17
    at Array.forEach (<anonymous>)
    at /home/chris/Projects/brokentests/node_modules/karma/lib/preprocessor.js:103:27
    at module.exports (/home/chris/Projects/brokentests/node_modules/karma/node_modules/isbinaryfile/index.js:28:12)
    at /home/chris/Projects/brokentests/node_modules/karma/lib/preprocessor.js:84:7
    at /home/chris/Projects/brokentests/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
04 03 2018 12:20:32.835:WARN [karma]: No captured browser, open http://localhost:9876/
04 03 2018 12:20:32.840:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
04 03 2018 12:20:32.840:INFO [launcher]: Launching browser Chrome with unlimited concurrency
04 03 2018 12:20:32.841:ERROR [karma]: Found 1 load error
Done in 1.29s.
12:20:32 brokentests 7288 (master) $ ng test
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

04 03 2018 12:20:36.944:WARN [watcher]: Pattern "/home/chris/Projects/brokentests/src/assets/**" does not match any file.
04 03 2018 12:20:37.001:ERROR [preprocess]: Can not load "webpack"!
  TypeError: Cannot read property 'plugin' of undefined
    at PathsPlugin.apply (/home/chris/Projects/brokentests/node_modules/@ngtools/webpack/src/paths-plugin.js:139:19)
    at Resolver.apply (/home/chris/Projects/brokentests/node_modules/tapable/lib/Tapable.js:375:16)
    at /home/chris/Projects/brokentests/node_modules/enhanced-resolve/lib/ResolverFactory.js:249:12
    at Array.forEach (<anonymous>)
    at Object.exports.createResolver (/home/chris/Projects/brokentests/node_modules/enhanced-resolve/lib/ResolverFactory.js:24
8:10)                                                                                                                        
    at WebpackOptionsApply.process (/home/chris/Projects/brokentests/node_modules/webpack/lib/WebpackOptionsApply.js:282:46)
    at webpack (/home/chris/Projects/brokentests/node_modules/webpack/lib/webpack.js:36:48)
    at Plugin (/home/chris/Projects/brokentests/node_modules/karma-webpack/lib/karma-webpack.js:63:18)
    at invoke (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:59:20)
    at get (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:48:43)
    at /home/chris/Projects/brokentests/node_modules/di/lib/injector.js:71:14
    at Array.map (<anonymous>)
    at Array.invoke (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/home/chris/Projects/brokentests/node_modules/karma/lib/preprocessor.js:55:20)
    at /home/chris/Projects/brokentests/node_modules/karma/lib/preprocessor.js:106:17
    at Array.forEach (<anonymous>)
    at /home/chris/Projects/brokentests/node_modules/karma/lib/preprocessor.js:103:27
    at module.exports (/home/chris/Projects/brokentests/node_modules/karma/node_modules/isbinaryfile/index.js:28:12)
    at /home/chris/Projects/brokentests/node_modules/karma/lib/preprocessor.js:84:7
    at /home/chris/Projects/brokentests/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
04 03 2018 12:20:37.005:WARN [karma]: No captured browser, open http://localhost:9876/
04 03 2018 12:20:37.010:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
04 03 2018 12:20:37.010:INFO [launcher]: Launching browser Chrome with unlimited concurrency
04 03 2018 12:20:37.011:ERROR [karma]: Found 1 load error
12:20:37 brokentests 7288 (master) $ karma start
04 03 2018 12:20:41.793:WARN [watcher]: Pattern "/home/chris/Projects/brokentests/src/assets/**" does not match any file.
04 03 2018 12:20:41.849:ERROR [preprocess]: Can not load "webpack"!
  TypeError: Cannot read property 'plugin' of undefined
    at PathsPlugin.apply (/home/chris/Projects/brokentests/node_modules/@ngtools/webpack/src/paths-plugin.js:139:19)
    at Resolver.apply (/home/chris/Projects/brokentests/node_modules/tapable/lib/Tapable.js:375:16)
    at /home/chris/Projects/brokentests/node_modules/enhanced-resolve/lib/ResolverFactory.js:249:12
    at Array.forEach (<anonymous>)
    at Object.exports.createResolver (/home/chris/Projects/brokentests/node_modules/enhanced-resolve/lib/ResolverFactory.js:24
8:10)                                                                                                                        
    at WebpackOptionsApply.process (/home/chris/Projects/brokentests/node_modules/webpack/lib/WebpackOptionsApply.js:282:46)
    at webpack (/home/chris/Projects/brokentests/node_modules/webpack/lib/webpack.js:36:48)
    at Plugin (/home/chris/Projects/brokentests/node_modules/karma-webpack/lib/karma-webpack.js:63:18)
    at invoke (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:59:20)
    at get (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:48:43)
    at /home/chris/Projects/brokentests/node_modules/di/lib/injector.js:71:14
    at Array.map (<anonymous>)
    at Array.invoke (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/home/chris/Projects/brokentests/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/home/chris/Projects/brokentests/node_modules/karma/lib/preprocessor.js:55:20)
04 03 2018 12:20:41.854:WARN [karma]: No captured browser, open http://localhost:9876/
04 03 2018 12:20:41.863:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
04 03 2018 12:20:41.863:INFO [launcher]: Launching browser Chrome with unlimited concurrency
04 03 2018 12:20:41.864:ERROR [karma]: Found 1 load error
```

Explicitly adding `webpack` andd `karma-webpack` to the dev-dependencies didn't help either.

Is there a fix for this on the way?
