### ISSUE TITLE
Cannot read property 'sourceDir' of undefined when running ng serve. . ng-version:0.0.39, os:linux x64

### ISSUE THREAD

**Issue by tchoulihan** [angular/angular-cli#767]
Generated a new project from scratch, now `ng serve` doesn't work with this version of angular. 
```
~/git/chat-practice-ui$ ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Cannot read property 'sourceDir' of undefined
TypeError: Cannot read property 'sourceDir' of undefined
    at new Angular2App (/home/tyler/git/chat-practice-ui/node_modules/angular-cli/lib/broccoli/angular2-app.js:30:40)
    at module.exports (/home/tyler/git/chat-practice-ui/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/tyler/git/chat-practice-ui/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/tyler/git/chat-practice-ui/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/tyler/git/chat-practice-ui/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/tyler/git/chat-practice-ui/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /home/tyler/git/chat-practice-ui/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/tyler/git/chat-practice-ui/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/tyler/git/chat-practice-ui/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/tyler/git/chat-practice-ui/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/tyler/git/chat-practice-ui/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
```
ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 0.0.39
node: 5.11.0
os: linux x64
```

**Comment by pkamdem** [comment]
@tchoulihan 

Update your global CLI package to the latest v1.0.0-beta.1 and try again if it still occurs.
``npm i angular-cli -g``

**Comment by tchoulihan** [comment]
Its kinda weird, the message I get when I run this command is:
`angular-cli@1.0.0-beta.1 `

But my angular version is still
```sh
ng --version
(node:27022) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 0.0.39
node: 6.0.0
os: linux x64
```

It still doesn't work.

**Comment by pkamdem** [comment]
``npm r angular-cli -g`` then ``npm i angular-cli -g`` ?

**Comment by tchoulihan** [comment]
That fixed it! Thanks a ton @pkamdem .
