### ISSUE TITLE
Schematics collection references aren't working

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#7687]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report
```

### Versions
@angular/cli: 1.4.1
node: 8.4.0
os: linux x64

### Repro Setup
`yarn global add @angular/cli stephen-schematics-playground`

(It appears schematics must be installed globally or I get an error `Error: Unknown collection "stephen-schematics-playground".`)

### Trial 1
_(In a project that isn't an Angular project yet)_

`ng g noop -c stephen-schematics-playground`

**Observed behavior:**
```
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at Class.run (/usr/local/google/home/stephenfluin/.config/yarn/global/node_modules/@angular/cli/commands/generate.js:109:63)
    at resolve (/usr/local/google/home/stephenfluin/.config/yarn/global/node_modules/@angular/cli/ember-cli/lib/models/command.js:273:20)
    at Promise (<anonymous>)
    at Class.validateAndRun (/usr/local/google/home/stephenfluin/.config/yarn/global/node_modules/@angular/cli/ember-cli/lib/models/command.js:251:12)
    at Promise.resolve.then.then (/usr/local/google/home/stephenfluin/.config/yarn/global/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:154:24)
    at <anonymous>
```

**Expected Behavior**
No-op schematic is run.

### Trial 2
`ng new -c stephen-schematics-playground newapp`

**Observed Behavior**
@schematics/angular's application scaffold is run

**Expected Behavior**
My noop application scaffold is run

### Trial 3
`ng g noop -c stephen-schematics-playground`

**Observed Behavior**
```
Unknown collection "stephen-schematics-playground".
Error: Unknown collection "stephen-schematics-playground".
    at SchematicEngine.createCollection (/usr/local/google/home/stephenfluin/workspace/test/woers/node_modules/@angular-devkit/schematics/src/engine/engine.js:45:19)
    at Object.getCollection (/usr/local/google/home/stephenfluin/workspace/test/woers/node_modules/@angular/cli/utilities/schematics.js:32:31)
    at Class.run (/usr/local/google/home/stephenfluin/workspace/test/woers/node_modules/@angular/cli/tasks/schematic-get-options.js:11:41)
    at Class.beforeRun (/usr/local/google/home/stephenfluin/workspace/test/woers/node_modules/@angular/cli/commands/generate.js:89:31)
    at Promise.resolve.then (/usr/local/google/home/stephenfluin/workspace/test/woers/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:150:24)
    at <anonymous>
```

**Expected Behavior**
My noop schematic is run

**Comment by Brocco** [comment]
**Trial 1**
```
ng g noop -c stephen-schematics-playground
```
Running `generate` (even via `g`) the assumption is that you will pass two required parameters...
- The name of the schematic (formerly blueprint)
- The name of the item being generated
you have passed the name of the schematic but not the name of the item to generate, hence the error trying to call `split` on an undefined value.
This error is quite confusing and will be addressed.

**Trial 2**
```
ng new -c stephen-schematics-playground newapp
```
You are telling the CLI to use the collection you supplied, but that collection does not define a schematic named `application` which is the default schematic name to look for in a collection for the `new` command.
If you would like to use your collection (for your super-fancy noop schematic 😜) you will need to expose an `application` schematic. This can be a schematic you define, or the one from `@schematics/angular` that you have exposed via your collection.

**Trial 3**
I need to dig through this one some more, but it may be related to your schematic library being installed globally and not locally.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
