### ISSUE TITLE
warning raised if targeting es2015

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#7689]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.5.0-beta.0
node: 8.5.0
os: linux x64
@angular/animations: 5.0.0-beta.7
@angular/common: 5.0.0-beta.7
@angular/compiler: 5.0.0-beta.7
@angular/core: 5.0.0-beta.7
@angular/forms: 5.0.0-beta.7
@angular/http: 5.0.0-beta.7
@angular/platform-browser: 5.0.0-beta.7
@angular/platform-browser-dynamic: 5.0.0-beta.7
@angular/router: 5.0.0-beta.7
@angular/cli: 1.5.0-beta.0
@angular/compiler-cli: 5.0.0-beta.7
@angular/language-service: 5.0.0-beta.7
typescript: 2.5.2

### Repro steps.
ng new demo
update target in tsconfig.json to 'es2015'
ng build

### The log given by the failure.
```
WARNING in ./node_modules/@angular/core/esm15/index.js
5132:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/home/sander/Documenten/test/demo/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
    at Compilation.reportDependencyErrorsAndWarnings (/home/sander/Documenten/test/demo/node_modules/webpack/lib/Compilation.js:694:24)
    at Compilation.finish (/home/sander/Documenten/test/demo/node_modules/webpack/lib/Compilation.js:552:9)
    at applyPluginsParallel.err (/home/sander/Documenten/test/demo/node_modules/webpack/lib/Compiler.js:512:17)
    at /home/sander/Documenten/test/demo/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/sander/Documenten/test/demo/node_modules/webpack/lib/Compilation.js:498:11)
    at processModuleDependencies.err (/home/sander/Documenten/test/demo/node_modules/webpack/lib/Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
### Desired functionality.
clear the warning, it's pushing essential information out of the view!

**Comment by filipesilva** [comment]
This likely means that lazy routes are not working properly under es2015 with Angular version 5 as well.

**Comment by rtm** [comment]
> 5132:15-36 Critical dependency: the request of a dependency is an expression

But I get this when targeting es5, and with no lazy routes involved.

What does it mean? What is the dependency involved here? What is the "request of a dependency"?
