### ISSUE TITLE
ng serve seems to have an issue running

### ISSUE THREAD

**Issue by jonnyroc** [angular/angular-cli#769]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

2. Versions. 
angular-cli: 1.0.0-beta.1
node: 6.1.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

step 1: ng new my-app
step 2: cd my-app
step 3: ng serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, symlink 'D:\AngularAttack\testcli\tmp\broccoli_type_script_compiler-cache_path-y0xxfggg.tmp\src\app\environment.js.map' -> 'D:\AngularAttack\testcli\tmp\broccoli_type_script_compiler-output_path-6fXX61GD.tmp\src\app\environment.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1048:18)
    at BroccoliTypeScriptCompiler._outputFile (D:\AngularAttack\testcli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
    at output.outputFiles.forEach.o (D:\AngularAttack\testcli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18)
    at Array.forEach (native)
    at pathsToEmit.forEach.tsFilePath (D:\AngularAttack\testcli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30)
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (D:\AngularAttack\testcli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (D:\AngularAttack\testcli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\AngularAttack\testcli\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (D:\AngularAttack\testcli\node_modules\angular-cli\lib\broccoli\angular2-app.js:280:18)
    at Angular2App._buildTree (D:\AngularAttack\testcli\node_modules\angular-cli\lib\broccoli\angular2-app.js:101:23)
    at new Angular2App (D:\AngularAttack\testcli\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (D:\AngularAttack\testcli\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\AngularAttack\testcli\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. Mention any other details that might be useful.
> I tried it on a different machine last evening and it was all working, so I was planning on using this for Angular Attack. and this morning (about 2 hours back) when I installed cli on my personal machine and tried to set up my project and serve it started crashing.

So it seems like something changed in the past ~10 hours

**Comment by jonnyroc** [comment]
Issue solved. Just needed to run the command prompt in "Run As Administrator" mode
