### ISSUE TITLE
cannot run ng new on Win7

### ISSUE THREAD

**Issue by tirthaguha** [angular/angular-cli#7720]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
C:\XXX\YYY\ZZZ>npm --v
3.7.3

C:\XXX\YYY\ZZZ>node -v
v5.9.1

C:\XXX\YYY\ZZZ>ng --version
C:\Users\liewouriewrporqo\AppData\Roaming\npm\node_modules\@angular\cli\models\config\config.js:17
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\liewouriewrporqo\AppData\Roaming\npm\node_modules\@angular\cli\models\config.js:3:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
WIN7


```
### Repro steps.
```
npm install -g @angular/cli
ng new test-project
```

### The log given by the failure.
```

C:\XXX\YYY\ZZZ>ng new test-project
C:\Users\liewouriewrporqo\AppData\Roaming\npm\node_modules\@angular\cli\models\config\config.js:17
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\liewouriewrporqo\AppData\Roaming\npm\node_modules\@angular\cli\models\config.js:3:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)


```

### Desired functionality.

- What is the usecase?
- Trying out Angular for the first time. Didn't like it before, doesn't look like it loves me either. Marionette had been a steady support all along. May Be i'll go back to Marionette. 

### Mention any other details that might be useful.
NA

**Comment by tirthaguha** [comment]
Closing.. Didn't read through, you have a Hard dependancy on node 6.9+
