### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by ashishdoneriya** [angular/angular-cli#7754]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.2
node: 8.1.2
os: linux x64

### Repro steps.
1. npm install
2, ng build, and then the the error occurs

### The log given by the failure.
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/impadmin/projects/locator/node_modules/@angular/cli/plugins/named-lazy-chunks-webpack-plugin.js:9:51)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/impadmin/projects/locator/node_modules/@angular/cli/models/webpack-configs/common.js:6:44)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

### Desired functionality.
At least it should start building the project.

**Comment by Brocco** [comment]
Can you please create a reproduction of this issue either via a git repo (preferred) or via the steps to recreate the issue?

The steps provided are not enough information go off of to determine what is going on.

**Comment by john-landgrave** [comment]
@ashishdoneriya 

I got this same error when upgrading from ng4 and the problem was that I'm using a WSL workaround, which involves npm installing in a different place and copying files over, and when I rsync'd over the files to my project I forgot the `--delete` switch, so there was a webpack sitting in `@angular/cli/node_modules` which was old and didn't have the NameChunksPlugin for the NamedLazyChunksPlugin to subclass.

If you happen to be in the same situation I was, hope this helps: even though I realize that that's a long shot!
