### ISSUE TITLE
Build error - The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with

### ISSUE THREAD

**Issue by ranbuch** [angular/angular-cli#776]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS - Windows 10.

2. Versions:
angular-cli: 1.0.0-beta.1
node: 4.4.1
os: win32 ia32

3. Here's what I've done:
npm install -g angular-cli
ng
ng new ng_test
cd ng_test
ng serve

4. log:
Build error

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, symlink 'C:\Users\ranbu\Documents\dev\ng_test\tmp\broccoli_type_script_compiler-cache_path-gsJuqMJK.tmp\src\app\environment.js.map' -> 'C:\Users\ranbu\Documents\dev\ng_test\tmp\broccoli_type_script_compiler-output_path-Bivnrro5.tmp\src\app\environment.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at BroccoliTypeScriptCompiler._outputFile (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
    at C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18
    at Array.forEach (native)
    at C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:10)
    at Angular2App._getTsTree (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\lib\broccoli\angular2-app.js:280:18)
    at Angular2App._buildTree (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\lib\broccoli\angular2-app.js:101:23)
    at new Angular2App (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (C:\Users\ranbu\Documents\dev\ng_test\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\ember-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\ranbu\Documents\dev\ng_test\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. I just installed it, created a new app and served it :(

ng-conf 2016 was epic!

**Comment by pkamdem** [comment]
@ranbuch 
You need to run your Command Prompt as Admin. Please refer to https://github.com/angular/angular-cli/issues/641

**Comment by UvaPrakash** [comment]
@ranbuch 
Run the Command Prompt as Admin
![image](https://cloud.githubusercontent.com/assets/12572715/15274683/49203966-1ad6-11e6-8d68-634713880e24.png)

**Comment by ranbuch** [comment]
Works like a charm. I must have missed that:

> On Windows you need to run the build and serve commands with Admin permissions, otherwise the performance is not good.

Thank you.

**Comment by n1alloc** [comment]
Guys, having the same problem (Broccoli Typescript Compiler Error) except using OSX, not Windows.
What are the steps to fix this bug?

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/905 should allow non-admin user usage.

**Comment by n1alloc** [comment]
Hi filipesilva, I still have the same problem, how should I resolve this bug?

**Comment by filipesilva** [comment]
Can you open a new issue with a copy of the error log? There are a few
different cases for Broccoli Typescript Compiler Error
