### ISSUE TITLE
Cannot use 'in' operator to search for 'providers' in undefined

### ISSUE THREAD

**Issue by abalad** [angular/angular-cli#7764]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.2
node: 7.10.0
os: win32 x64
@angular/animations: 4.4.1
@angular/common: 4.4.1
@angular/compiler: 4.4.1
@angular/core: 4.4.1
@angular/forms: 4.4.1
@angular/http: 4.4.1
@angular/platform-browser: 4.4.1
@angular/platform-browser-dynamic: 4.4.1
@angular/router: 4.4.1
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.1
@angular/language-service: 4.4.1
typescript: 2.3.4

### The log given by the failure.
`ERROR in TypeError: Cannot use 'in' operator to search for 'providers' in undefined`
```
    at D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:111:70
    at Array.filter (native)
    at _extractLazyRoutesFromStaticModule (D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:111:29)
    at D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\Labs\Truly-UI\Maicon\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (D:\Labs\Truly-UI\Maicon\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\Labs\Truly-UI\Maicon\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by wallace41290** [comment]
Having the exact same problem, anyone figure something out?

**Comment by abalad** [comment]
I found a solution for my case by doing what was described here.
https://github.com/TemainfoSistemas/truly-ui/issues/67

**Comment by wallace41290** [comment]
I took out the only barrel file I had and adjusted my imports directly to the files and I am still getting the same error

`ERROR in TypeError: Cannot use 'in' operator to search for 'providers' in undefined
    at /Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:111:70
    at Array.filter (native)
    at _extractLazyRoutesFromStaticModule (/Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:111:29)
    at /Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at /Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at /Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at /Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/will/Workspace/mtna-ng-seed/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/will/Workspace/mtna-ng-seed/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/will/Workspace/mtna-ng-seed/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)`

**Comment by Brocco** [comment]
Can someone please provide some code and/or steps to reproduce? A stack trace without context is not very helpful.  Thanks!

**Comment by wallace41290** [comment]
For my case I had my own component library as a dependency and it had a bad import in a module.

**Comment by balteo** [comment]
I am getting the same error with ng cli 1.5.0.rc0.

If it is indeed an issue with an import, then the error message should be more explicit about what the error is.

@wallace41290 : can you please post details about what the bad import was?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
