### ISSUE TITLE
brand new project , then ng build --prod   fails

### ISSUE THREAD

**Issue by getmonyinfo** [angular/angular-cli#7771]
### Versions.
`ng --version`

@angular/cli: 1.4.2
node: 6.11.3
os: darwin x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

### Repro steps.

```bash
ng n demote
cd demote && npm install
ng build --prod
```

### The log given by the failure.
```javascript
 95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open '/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_@angular_core@4.4.3@@angular/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at LicenseExtractor.readPackageJson (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_license-webpack-plugin@1.0.1@license-webpack-plugin/dist/LicenseExtractor.js:121:23)
    at LicenseExtractor.parsePackage (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_license-webpack-plugin@1.0.1@license-webpack-plugin/dist/LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_license-webpack-plugin@1.0.1@license-webpack-plugin/dist/ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_license-webpack-plugin@1.0.1@license-webpack-plugin/dist/ModuleProcessor.js:21:21)
    at moduleCallback (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_license-webpack-plugin@1.0.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:80:61)
    at SortableSet.forEach (native)
    at Chunk.forEachModule (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_webpack@3.5.6@webpack/lib/Chunk.js:159:17)
    at /Users/a/Downloads/Angular-Routing-master/demote/node_modules/_license-webpack-plugin@1.0.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:88:27
    at Array.forEach (native)
    at Compiler.<anonymous> (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_license-webpack-plugin@1.0.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:65:32)
    at next (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_tapable@0.2.8@tapable/lib/Tapable.js:204:14)
    at /Users/a/Downloads/Angular-Routing-master/demote/node_modules/_html-webpack-plugin@2.30.1@html-webpack-plugin/index.js:204:9
    at PassThroughHandlerContext.finallyHandler (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_bluebird@3.5.0@bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_bluebird@3.5.0@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/a/Downloads/Angular-Routing-master/demote/node_modules/_bluebird@3.5.0@bluebird/js/release/async.js:133:16)
```

**Comment by fusi0011** [comment]
i have such a problem.  the reason is to use cnpm install.
1. remove node_module folder
2. use npm install
