### ISSUE TITLE
Build error  The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:

### ISSUE THREAD

**Issue by kamilshahzad** [angular/angular-cli#782]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Win 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
node: 6.1.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc
i just Create new app and using
ng new pro.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Build error

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  C:/Users/kamil/ng2/pro5/tmp/broccoli_type_script_compiler-input_base_path-SPob0I1X.tmp/0/src/main.ts (3, 10): Module '"C:/Users/kamil/ng2/pro5/tmp/broccoli_type_script_compiler-input_base_path-SPob0I1X.tmp/0/src/app"' has no exported member 'Pro5AppComponent'.
  C:/Users/kamil/ng2/pro5/tmp/broccoli_type_script_compiler-input_base_path-SPob0I1X.tmp/0/src/main.ts (3, 28): Module '"C:/Users/kamil/ng2/pro5/tmp/broccoli_type_script_compiler-input_base_path-SPob0I1X.tmp/0/src/app"' has no exported member 'environment'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:115:19)
    at BroccoliTypeScriptCompiler.build (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\lib\broccoli\angular2-app.js:280:18)
    at Angular2App._buildTree (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\lib\broccoli\angular2-app.js:101:23)
    at new Angular2App (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (C:\Users\kamil\ng2\pro5\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\ember-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\kamil\ng2\pro5\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by ryancrosser** [comment]
I came across this issue after getting the following using angular-cli on a new project. I was able to get around it by running Command Prompt and Git Bash as Administrator.

1. 
angular-cli: 1.0.0-beta.1
node: 6.0.0
os: win32 x64

2. 
Brand new angular-cli install using ng new test1

3. 

```
(node:6840) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, symlink 'C:\Users\Ryan Crosser\projects\test1\tmp\broccoli_type_script_compiler-cache_path-hMwXIPh7.tmp\src\app\environment.js.map' -> 'C:\Users\Ryan Crosser\projects\test1\tmp\broccoli_type_script_compiler-output_path-hLgD6L4V.tmp\src\app\environment.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:1048:18)
    at BroccoliTypeScriptCompiler._outputFile (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
    at output.outputFiles.forEach.o (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18)
    at Array.forEach (native)
    at pathsToEmit.forEach.tsFilePath (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30)
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\lib\broccoli\angular2-app.js:280:18)
    at Angular2App._buildTree (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\lib\broccoli\angular2-app.js:101:23)
    at new Angular2App (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\lib\broccoli\angular2-app.js:42:23)
    at module.exports (C:\Users\Ryan Crosser\projects\test1\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\Ryan Crosser\projects\test1\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
```

**Comment by pkamdem** [comment]
@kamilshahzad You need to run your Command Prompt as Admin. Please refer to the CLI [known issues](https://github.com/angular/angular-cli#known-issues)

**Comment by kamilshahzad** [comment]
I am running CLI as admin and still facing this issue

**Comment by kamilshahzad** [comment]
Now facing Cannot read property sourcedir of undefined

although i tried 
https://github.com/hansl/angular-cli/commit/ff66eca9eb717e1dace86bf9e3813d5b0abef9c9
but yesterday it was resolved somehow now again same error as well when i resolve this then i will receive 
Build error The Broccoli Plugin: [BroccoliTypeScriptCompiler] 
Please be specific of how to resolve it or upload some new updates. Most of my developers are facing same issue in windows 10.

**Comment by pkamdem** [comment]
@kamilshahzad 

What is your CLI version?

**Comment by kamilshahzad** [comment]
cli version is 0.0.39
i downgrade node to 4.4.4
also downgrade npm 2.15
now facing same errors
cannot read property sourcedir of undefined

**Comment by Aidurber** [comment]
@kamilshahzad Add `sourceDir` to your angular-cli.json:

Here is my angular-cli.json file:
```
{
  "routes": [],
  "defaults": {
    "sourceDir": "src/client"
  }
}

```

**Comment by kamilshahzad** [comment]
{

  "routes": [],
  "defaults": {
    "sourceDir": "src/client"
  },
  "project": {
    "version": "<%= version %>",
    "name": "<%= htmlComponentName %>"
  },
  "apps": [
    {"main": "<%= sourceDir %>/main.ts", "tsconfig": "<%= sourceDir %>/tsconfig.json"}
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "config/protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "config/karma.conf.js"
    }
  }
  
}

I updated this but still same issue

**Comment by DrLeeroyPhD** [comment]
I'm having the same issue. The bash gets hung up and upon going to port 4200, I receive the same message as @kamilshahzad

**Comment by Brocco** [comment]
@kamilshahzad you are using an outdated version of the CLI, the current version is beta 5 (available via npm). Please update and re-generate your project.

**Comment by LiamBowie** [comment]
I'm using angular-cli v1.0.0-beta.5 and running ng serve as an admin and I'm still getting this error.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/905 should allow non-admin user usage.
