### ISSUE TITLE
ng serve gives error when running on new project.

### ISSUE THREAD

**Issue by lgLindstrom** [angular/angular-cli#7825]
- [ x ] bug report -> please search issues before submitting
- [ ] feature request

### Versions.
angular-cli: 1.0.0-beta.28.3
npm: '5.0.0'

### Repro steps.
from command line.
> ng new unitTest
> cd unitTest
> ng test

### The log given by the failure.
from terminal window.

As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

25 09 2017 19:14:11.917:WARN [watcher]: Pattern "C:\HostedProjects\test\unitTest\src\assets/**" does not match any file.
25 09 2017 19:14:12.024:ERROR [preprocess]: Can not load "webpack"!
  TypeError: Cannot read property 'plugin' of undefined
    at PathsPlugin.apply (C:\HostedProjects\test\unitTest\node_modules\@ngtools\webpack\src\paths-plugin.js:75:18)
    at Resolver.apply (C:\HostedProjects\test\unitTest\node_modules\tapable\lib\Tapable.js:375:16)
    at C:\HostedProjects\test\unitTest\node_modules\enhanced-resolve\lib\ResolverFactory.js:249:12
    at Array.forEach (native)
    at Object.exports.createResolver (C:\HostedProjects\test\unitTest\node_modules\enhanced-resolve\lib\ResolverFactory.
js:248:10)
    at WebpackOptionsApply.process (C:\HostedProjects\test\unitTest\node_modules\webpack\lib\WebpackOptionsApply.js:282:
46)
    at webpack (C:\HostedProjects\test\unitTest\node_modules\webpack\lib\webpack.js:36:48)
    at new Plugin (C:\HostedProjects\test\unitTest\node_modules\karma-webpack\lib\karma-webpack.js:63:18)
    at invoke (C:\HostedProjects\test\unitTest\node_modules\di\lib\injector.js:75:15)
    at Array.instantiate (C:\HostedProjects\test\unitTest\node_modules\di\lib\injector.js:59:20)
    at get (C:\HostedProjects\test\unitTest\node_modules\di\lib\injector.js:48:43)
    at C:\HostedProjects\test\unitTest\node_modules\di\lib\injector.js:71:14
    at Array.map (native)
    at Array.invoke (C:\HostedProjects\test\unitTest\node_modules\di\lib\injector.js:70:31)
    at Injector.get (C:\HostedProjects\test\unitTest\node_modules\di\lib\injector.js:48:43)
    at instantiatePreprocessor (C:\HostedProjects\test\unitTest\node_modules\karma\lib\preprocessor.js:55:20)
    at C:\HostedProjects\test\unitTest\node_modules\karma\lib\preprocessor.js:106:17
    at Array.forEach (native)
    at C:\HostedProjects\test\unitTest\node_modules\karma\lib\preprocessor.js:103:27
    at module.exports (C:\HostedProjects\test\unitTest\node_modules\karma\node_modules\isbinaryfile\index.js:28:12)
    at C:\HostedProjects\test\unitTest\node_modules\karma\lib\preprocessor.js:84:7
    at C:\HostedProjects\test\unitTest\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:490:3)
25 09 2017 19:14:12.026:WARN [karma]: No captured browser, open http://localhost:9876/
25 09 2017 19:14:12.042:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
25 09 2017 19:14:12.042:INFO [launcher]: Launching browser Chrome with unlimited concurrency
25 09 2017 19:14:12.042:ERROR [karma]: Found 1 load error

### Desired functionality.
Test should be run.

### Mention any other details that might be useful.
ng serve works as expected.

**Comment by filipesilva** [comment]
Heya, you are using a very old unsupported version of the CLI. You should update the the latest one. 

If you have an existing project you can use https://github.com/angular/angular-cli/wiki/stories-1.0-update. Making a new project is also easy.
