### ISSUE TITLE
Cannot read property 'sourceDir' of undefined

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#783]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
> ng --version
angular-cli: 1.0.0-beta.1
node: 4.4.3
os: win32 ia32

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

I've upgraded from 0.0.x to 1.0.0 rc1. I've run ng init. I get the error when running ng build

4. The log given by the failure. Normally this include a stack trace and some
   more information.

- BuildingCannot read property 'sourceDir' of undefined
TypeError: Cannot read property 'sourceDir' of undefined
    at new Angular2App (C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\angular-cli\lib\broccoli\angular2-app.js:30:40)
    at module.exports (C:\Projects\prj_client\project.Web.Client\Dev\src\client\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\angular-cli\lib\tasks\build.js:15:19)
    at C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\angular-cli\lib\commands\build.js:32:24
    at lib$rsvp$$internal$$tryCatch (C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Projects\prj_client\project.Web.Client\Dev\src\client\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by rolandoldengarm** [comment]
Ah... Just see this issue. 
https://github.com/angular/angular-cli/issues/619

The fix (replace .json file) worked.
