### ISSUE TITLE
Angular-cli 1.4.3 gives warning on clean install node: 8.6.0

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#7858]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

@angular/cli: 1.4.3
node: 8.6.0
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.3
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

### Repro steps.

Clean installation
npm install -g @angular/cli
ng new app
cd app
ng serve

### The log given by the failure.

WARNING in .../app/node_modules/@angular/compiler/@angular/compiler.es5.js
(Emitted value instead of an instance of Error) Cannot find source file 'compiler.es5.ts': Error: Can't resolve './compiler.es5.ts' in '...\app\node_modules\@angular\compiler\@angular'
NonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file 'compiler.es5.ts': Error: Can't resolve './compiler.es5.ts' in '...\app\node_modules\@angular\compiler\@angular'
    at emitWarning (...\app\node_modules\webpack\lib\NormalModule.js:117:16)
    at ...\app\node_modules\source-map-loader\index.js:65:7
    at onError (...\app\node_modules\enhanced-resolve\lib\Resolver.js:65:10)
    at loggingCallbackWrapper (...\app\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (...\app\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (...\app\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (...\app\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (...\app\node_modules\tapable\lib\Tapable.js:252:11)
    at ...\app\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (...\app\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (...\app\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (...\app\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (...\app\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (...\app\node_modules\tapable\lib\Tapable.js:252:11)
    at innerCallback (...\app\node_modules\enhanced-resolve\lib\Resolver.js:144:11)
    at loggingCallbackWrapper (...\app\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (...\app\node_modules\tapable\lib\Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (...\app\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (...\app\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (...\app\node_modules\enhanced-resolve\lib\Resolver.js:168:10)
    at loggingCallbackWrapper (...\app\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (...\app\node_modules\tapable\lib\Tapable.js:252:11)
 @ .../app/node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js 7:0-72
 @ .../app/src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by alan-agius4** [comment]
Hi, Angular CLI version 1 is no longer supported. The current LTS is version 6.

Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
