### ISSUE TITLE
error Unexpected end of JSON input while parsing near

### ISSUE THREAD

**Issue by jannanlo** [angular/angular-cli#7863]
### Bug logs
```
1838 silly resolveWithNewModule normalize-path@2.1.1 checking installable status
1839 http fetch GET 200 https://registry.npmjs.org/micromatch 836195ms
1840 silly fetchPackageMetaData error for micromatch@^2.1.5 Unexpected end of JSON input while parsing near '..."^2.0.1","kind-of":"^'
1841 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."^2.0.1","kind-of":"^'
1841 verbose stack     at JSON.parse (<anonymous>)
1841 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
1841 verbose stack     at consumeBody.call.then.buffer (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
1841 verbose stack     at <anonymous>
1841 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
1842 verbose cwd /
1843 verbose Linux 3.10.0-514.el7.x86_64
1844 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "angular-cli"
1845 verbose node v8.6.0
1846 verbose npm  v5.4.2
1847 error Unexpected end of JSON input while parsing near '..."^2.0.1","kind-of":"^'
1848 verbose exit [ 1, true ]

```

### Versions.

node v8.6.0
npm  v5.4.2

### Repro steps.

The error occurred when I run npm install -g angular-cli

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.

**Comment by vivekodela** [comment]
If you are using windows, these may solve your issue,

-  Delete temp folder on OS level (temp in run) 

-  Delete temp folder on Application level(%temp% in run)

**Comment by Jasim123** [comment]
Thanks @vivekodela ...this solved my issue
