### ISSUE TITLE
Angular CLI Installation Error

### ISSUE THREAD

**Issue by prashSutar** [angular/angular-cli#7865]
I am using npm version 3.10.10, when I try to install angular-cli (npm install -g @angular/cli) it will only creating "npm-debug" file in folder.  
[npm-debug.log](https://github.com/angular/angular-cli/files/1340412/npm-debug.log)

**Comment by kiplphp78** [comment]
I am getting same issue

**Comment by filipesilva** [comment]
Heya, I went through the log you posted and the error seems to be this:
```
92427 verbose stack Error: uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
92427 verbose stack spawn C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin ENOENT
92427 verbose stack     at exports._errnoException (util.js:1020:11)
92427 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
92427 verbose stack     at onErrorNT (internal/child_process.js:376:16)
92427 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
92427 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
92428 verbose pkgid uglifyjs-webpack-plugin@0.4.6
92429 verbose cwd C:\Users\admin\Desktop\centralogic\angular-clone
92430 error Windows_NT 6.1.7601
92431 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
92432 error node v6.11.3
92433 error npm  v3.10.10
92434 error file C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin
92435 error path C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin
92436 error code ELIFECYCLE
92437 error errno ENOENT
92438 error syscall spawn C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin
92439 error uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
92439 error spawn C:\Windows\system32\cmd.exe;C:\Program Files\MongoDB\Server\3.4\bin ENOENT
92440 error Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
92440 error Make sure you have the latest version of node.js and npm installed.
92440 error If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
92440 error not with npm itself.
92440 error Tell the author that this fails on your system:
92440 error     node lib/post_install.js
92440 error You can get information on how to open an issue for this project with:
92440 error     npm bugs uglifyjs-webpack-plugin
92440 error Or if that isn't available, you can get their info via:
92440 error     npm owner ls uglifyjs-webpack-plugin
92440 error There is likely additional logging output above.
92441 verbose exit [ 1, true ]
```

It seems to be something with your MongoDB install and the `uglifyjs-webpack-plugin@0.4.6` package. Perhpas node from there is causing problems?

You should open an issue at their repository: https://github.com/webpack-contrib/uglifyjs-webpack-plugin
