### ISSUE TITLE
SIGINT cannot kill `ng serve` process

### ISSUE THREAD

**Issue by Quramy** [angular/angular-cli#7875]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.5.0-beta.2
node: 8.1.3
os: darwin x64
@angular/animations: 5.0.0-rc.0
@angular/common: 5.0.0-rc.0
@angular/compiler: 5.0.0-rc.0
@angular/core: 5.0.0-rc.0
@angular/forms: 5.0.0-rc.0
@angular/http: 5.0.0-rc.0
@angular/platform-browser: 5.0.0-rc.0
@angular/platform-browser-dynamic: 5.0.0-rc.0
@angular/router: 5.0.0-rc.0
@angular/cli: 1.5.0-beta.2
@angular/compiler-cli: 5.0.0-rc.0
@angular/language-service: 5.0.0-rc.0
typescript: 2.5.3
```

### Repro steps.

1. Create new project via `ng new`, and change directory.
1. Start to watch via `ng serve --aot`
1. Open `src/app/app.component.html` in editor. 
1. Edit and save HTML.
   - An error `TypeError: Cannot read property 'substr' of undefined` is thrown.
1. Undo and save the html.
   - Another error `ERROR in Error [ERR_IPC_CHANNEL_CLOSED]: channel closed` is thrown.

Finally, I've tried to kill the `serve` process by pressing `CTRL + C`, however I could not...

### The log given by the failure.

```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-09-29T02:43:04.621Z
Hash: 59665e998fd654932305
Time: 6567ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 25.2 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 217 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.3 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 1.37 MB [initial] [rendered]

webpack: Compiled successfully.
webpack: Compiling...
 10% building modules 1/1 modules 0 activeCould not resolve module '@angular/core' relative to file undefined
/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@angular/compiler/bundles/compiler.umd.js:31203
            throw error;
            ^

TypeError: Cannot read property 'substr' of undefined
    at Object.getDirectoryPath (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/typescript/lib/typescript.js:2763:20)
    at Object.resolveModuleName (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/typescript/lib/typescript.js:21953:38)
    at TsCompilerAotCompilerTypeCheckHostAdapter.resolveModuleName (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:100:21)
    at TsCompilerAotCompilerTypeCheckHostAdapter.moduleNameToFileName (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:134:29)
    at StaticSymbolResolver.resolveModule (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@angular/compiler/bundles/compiler.umd.js:31273:30)
    at StaticSymbolResolver.getSymbolByModule (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@angular/compiler/bundles/compiler.umd.js:31254:46)
    at StaticReflector.findDeclaration (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@angular/compiler/bundles/compiler.umd.js:29723:63)
    at StaticReflector.initializeConversionMap (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@angular/compiler/bundles/compiler.umd.js:29988:36)
    at new StaticReflector (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@angular/compiler/bundles/compiler.umd.js:29673:14)
    at Object.createAotCompiler (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@angular/compiler/bundles/compiler.umd.js:31496:44)
Date: 2017-09-29T02:43:17.575Z
Hash: 776351af06baa5e40028
Time: 1420ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry]
chunk {main} main.bundle.js, main.bundle.js.map (main) 25.2 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 217 kB {inline} [initial]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.3 kB {inline} [initial]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 1.37 MB [initial]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2017-09-29T02:43:21.618Z
Hash: c26b21dd749f561f937b
Time: 101ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry]
chunk {main} main.bundle.js, main.bundle.js.map (main) 27.2 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 217 kB {inline} [initial]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.3 kB {inline} [initial]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 1.37 MB [initial]

ERROR in Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:557:16)
    at AngularCompilerPlugin._updateForkedTypeChecker (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:320:34)
    at AngularCompilerPlugin._createOrUpdateProgram (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:206:18)
    at Promise.resolve.then.then (/Users/yosuke/workspaces/javascript/ng-meetup1010/v5demo-witch-cli-beta/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:490:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

webpack: Failed to compile.
```

**Comment by sheikalthaf** [comment]
Facing this in official build.
```
Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 ia32
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

fix this asap. delaying the development

**Comment by hansl** [comment]
This should have been fixed a long time ago. If this still happens please create a new issue so we can follow up.
