### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined  (steam trading bot)

### ISSUE THREAD

**Issue by BlackJack03** [angular/angular-cli#7893]
Hi, i'm just started out the coding of a steam trading bot, and i got stuck, when the program got a bug when i wanted it to start up TF2, and idle there. When i start the bot, it boots  up, and gets into tf2, and quits imediatly. The error codes are here:

succesfully logged on.
C:\Users\BlackJack\Desktop\Random shit\bot\node_modules\steam-user\components\messages.js:231
        this._handlers[handlerName].call(this, body, cb);
                                                     ^

TypeError: Cannot read property 'call' of undefined
    at SteamUser._handleMessage (C:\Users\BlackJack\Desktop\Random shit\bot\node_modules\steam-user\components\messages.js:231:29)
    at emitThree (events.js:116:13)
    at CMClient.emit (events.js:194:7)
    at CMClient._netMsgReceived (C:\Users\BlackJack\Desktop\Random shit\bot\node_modules\steam-client\lib\cm_client.js:323:8)
    at CMClient.handlers.(anonymous function) (C:\Users\BlackJack\Desktop\Random shit\bot\node_modules\steam-client\lib\cm_client.js:603:8)
    at CMClient._netMsgReceived (C:\Users\BlackJack\Desktop\Random shit\bot\node_modules\steam-client\lib\cm_client.js:305:24)
    at emitOne (events.js:96:13)
    at TCPConnection.emit (events.js:188:7)
    at TCPConnection._readPacket (C:\Users\BlackJack\Desktop\Random shit\bot\node_modules\steam-client\lib\tcp_connection.js:179:7)
    at emitNone (events.js:86:13)
![botissue](https://user-images.githubusercontent.com/32419543/31048244-ab2e6c48-a619-11e7-8929-6e9dbb9d2f25.png)

If ANYBODY can help me, please write ^^

**Comment by Brocco** [comment]
I believe you may have created this issue on the wrong repo as there does not seem to be anything Angular CLI related in your issue.
