### ISSUE TITLE
Unable to perform ng server

### ISSUE THREAD

**Issue by fahdsaeed** [angular/angular-cli#7900]
### Bug Report or Feature Request (mark with an `x`)
Error encountered resolving symbol values statically. Could not resolve angular2-select relative to /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts.,

@angular/cli: 1.4.4

ERROR in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts (5,30): Cannot find module 'angular2-select'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve angular2-select relative to /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts., resolving symbol DashboardModule in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts, resolving symbol DashboardModule in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts
    at Error (native)
    at syntaxError (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

webpack: Failed to compile.

### Repro steps.
 ./ng serve

**Comment by fahdsaeed** [comment]
I see another issue as this 
https://www.screencast.com/t/DPrzXxTzgCDj

Can any one help
?

**Comment by almothafar** [comment]
I see issues like this as well https://github.com/shlomiassaf/ngx-modialog/issues/400 
https://github.com/shlomiassaf/ngx-modialog/issues/399 

Seems a lot of 3rd parties affected, is there breaking changes?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
