### ISSUE TITLE
LAZY_MODULE_MAP not working in 1.5.0

### ISSUE THREAD

**Issue by dottodot** [angular/angular-cli#7901]
In v1.4.4 LAZY_MODULE_MAP works fine for Universal but in 1.5.0-beta.2 I get the following error

```
ERROR { Error: Uncaught (in promise): Error: ./home/home.module#HomeModule did not exist in the MODULE_MAP
Error: ./home/home.module#HomeModule did not exist in the MODULE_MAP
    at ModuleMapNgFactoryLoader.load (/node_modules/@nguniversal/module-map-ngfactory-loader/src/module-map-ngfactory-loader.js:20:19)
    at RouterConfigLoader.loadModuleFactory (/node_modules/@angular/router/bundles/router.umd.js:4481:72)
    at RouterConfigLoader.load (/node_modules/@angular/router/bundles/router.umd.js:4461:52)
    at MergeMapSubscriber.project (/node_modules/@angular/router/bundles/router.umd.js:2016:74)
    at MergeMapSubscriber._tryNext (/node_modules/rxjs/operator/mergeMap.js:120:27)
    at MergeMapSubscriber._next (/node_modules/rxjs/operator/mergeMap.js:110:18)
    at MergeMapSubscriber.Subscriber.next (/node_modules/rxjs/Subscriber.js:89:18)
    at ScalarObservable._subscribe (/node_modules/rxjs/observable/ScalarObservable.js:49:24)
    at ScalarObservable.Observable._trySubscribe (/node_modules/rxjs/Observable.js:171:25)
    at ScalarObservable.Observable.subscribe (/node_modules/rxjs/Observable.js:159:65)
    at MergeMapOperator.call (/node_modules/rxjs/operator/mergeMap.js:85:23)
    at Observable.subscribe (/node_modules/rxjs/Observable.js:156:22)
    at MergeMapOperator.call (/node_modules/rxjs/operator/mergeMap.js:85:23)
    at Observable.subscribe (/node_modules/rxjs/Observable.js:156:22)
    at CatchOperator.call (/node_modules/rxjs/operator/catch.js:79:23)
    at Observable.subscribe (/node_modules/rxjs/Observable.js:156:22)
    at resolvePromise (/node_modules/zone.js/dist/zone-node.js:795:31)
    at resolvePromise (/node_modules/zone.js/dist/zone-node.js:766:17)
    at /node_modules/zone.js/dist/zone-node.js:844:17
    at ZoneDelegate.invokeTask (/node_modules/zone.js/dist/zone-node.js:425:31)
    at Object.onInvokeTask (/node_modules/@angular/core/bundles/core.umd.js:4656:33)
    at ZoneDelegate.invokeTask (/node_modules/zone.js/dist/zone-node.js:424:36)
    at Zone.runTask (/node_modules/zone.js/dist/zone-node.js:192:47)
    at drainMicroTaskQueue (/node_modules/zone.js/dist/zone-node.js:602:35)
    at ZoneTask.invokeTask (/node_modules/zone.js/dist/zone-node.js:503:21)
    at ZoneTask.invoke (/node_modules/zone.js/dist/zone-node.js:488:48)
    at data.args.(anonymous function) (/node_modules/zone.js/dist/zone-node.js:1075:25)
    at FSReqWrap.oncomplete (fs.js:153:21)
```

**Comment by dottodot** [comment]
Any idea when this might be fixed. I'm a little bit stuck now, as using some of the angular v5 features and my build fails using 1.4.5 and I can't get universal working with 1.5.0-beta.4

**Comment by dottodot** [comment]
Still broken in 1.5.0-rc.0

**Comment by EmilsWebbod** [comment]
I changed the file 
node_modules/@nguniversal/module-map-ngfactory-loader/module-map-ngfactory-loader.js
And added this in function ModuleMapNgFactoryLoader.prototype.load

```
loadChildrenString = loadChildrenString.split('#')
          .map((x, i) => i === 0 ? x + '.ngfactory#' : x + 'NgFactory')
          .reduce((n, o) => n + o, '');
```

This fixed the problem temporarily. It seems that the map is saved as ngFactory but the loader is looking for unfactorized modules.

**Comment by dottodot** [comment]
@EmilsWebbod thanks, that works, should keep me going until a proper fix is sorted.

**Comment by Toxicable** [comment]
Just came across this issue, investigating, will update when we find out what's up
