### ISSUE TITLE
ng serve fails with  Cannot find module 'clone'

### ISSUE THREAD

**Issue by DaveSharman** [angular/angular-cli#7957]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

windows 10 x64

PS F:\WebDev\primeNG\test-proj> ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.5
node: 8.6.0
os: win32 x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4
PS F:\WebDev\primeNG\test-proj>

Notes:  
    I uninstalled and freshly downloaded node.js and installed it.   
    Angular-cli  was freshly installed via npm and installed globally

### Repro steps.

ng new test-proj
cd test-proj
ng serve

### The log given by the failure.

PS F:\WebDev\primeNG> cd test-proj
PS F:\WebDev\primeNG\test-proj> ng serve
Cannot find module 'clone'
Error: Cannot find module 'clone'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\WebDev\primeNG\test-proj\node_modules\color\index.js:2:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\WebDev\primeNG\test-proj\node_modules\colormin\dist\index.js:5:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
PS F:\WebDev\primeNG\test-proj>

**Comment by DaveSharman** [comment]
corrupt npm cache.   Removing node.js deleting the cache folder from \appdata\roaming and reinstalling fixed the issue.
