### ISSUE TITLE
ng build --prod --aot failed

### ISSUE THREAD

**Issue by chenwenhao1992** [angular/angular-cli#7958]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.5
node: 6.11.4
os: darwin x64
@angular/animations: 4.2.4
@angular/common: 4.2.4
@angular/compiler: 4.2.4
@angular/core: 4.2.4
@angular/forms: 4.2.4
@angular/http: 4.2.4
@angular/platform-browser: 4.2.4
@angular/platform-browser-dynamic: 4.2.4
@angular/router: 4.2.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.2.4
@angular/language-service: 4.2.4
typescript: 2.3.4
node v6.11.4

### Repro steps.
step 1.
npm install 

step 2.
use "ng serve"
it's worked!

step 3.
use  "ng build --prod --aot" 
build failed.
but 
when i use "ng build --aot" it's working!

### The log given by the failure.
95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open '/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_@angular_core@4.2.4@@angular/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at LicenseExtractor.readPackageJson (/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_license-webpack-plugin@1.1.0@license-webpack-plugin/dist/LicenseExtractor.js:124:23)
    at LicenseExtractor.parsePackage (/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_license-webpack-plugin@1.1.0@license-webpack-plugin/dist/LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_license-webpack-plugin@1.1.0@license-webpack-plugin/dist/ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_license-webpack-plugin@1.1.0@license-webpack-plugin/dist/ModuleProcessor.js:21:21)
    at moduleCallback (/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_license-webpack-plugin@1.1.0@license-webpack-plugin/dist/LicenseWebpackPlugin.js:80:61)
    at SortableSet.forEach (native)
    at Chunk.forEachModule (/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_webpack@3.6.0@webpack/lib/Chunk.js:159:17)
    at /Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_license-webpack-plugin@1.1.0@license-webpack-plugin/dist/LicenseWebpackPlugin.js:89:27
    at Array.forEach (native)
    at Compiler.<anonymous> (/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_license-webpack-plugin@1.1.0@license-webpack-plugin/dist/LicenseWebpackPlugin.js:65:32)
    at next (/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_tapable@0.2.8@tapable/lib/Tapable.js:204:14)
    at /Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_html-webpack-plugin@2.30.1@html-webpack-plugin/index.js:204:9
    at PassThroughHandlerContext.finallyHandler (/Users/Alex/Documents/Work/gitStore/rx-store/node_modules/_bluebird@3.5.1@bluebird/js/release/finally.js:56:23)

Desired functionality.

AOT build should work.

**Comment by huyinghuan** [comment]
I got the same error

**Comment by hansl** [comment]
Hi @chenwenhao1992,

Can you provide more information?  I cannot reproduce this by creating a new project.

Did you `npm link` any local pacakges?  It seems like you might have `rx-store` linked, but I can't tell.

**Comment by lixiaocong** [comment]
I got the same problem
`
Unhandled rejection Error: ENOENT: no such file or directory, open '/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_@angular_core@5.0.0@@angular/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at LicenseExtractor.readPackageJson (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseExtractor.js:124:23)
    at LicenseExtractor.parsePackage (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/ModuleProcessor.js:21:21)
    at moduleCallback (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:80:61)
    at Set.forEach (<anonymous>)
    at Chunk.forEachModule (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_webpack@3.8.1@webpack/lib/Chunk.js:159:17)
    at /home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:89:27
    at Array.forEach (<anonymous>)
    at Compiler.<anonymous> (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_license-webpack-plugin@1.1.1@license-webpack-plugin/dist/LicenseWebpackPlugin.js:65:32)
    at next (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_tapable@0.2.8@tapable/lib/Tapable.js:204:14)
    at /home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_html-webpack-plugin@2.30.1@html-webpack-plugin/index.js:204:9
    at PassThroughHandlerContext.finallyHandler (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_bluebird@3.5.1@bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/home/lixiaocong/IdeaProjects/lxcCMS/admin/node_modules/_bluebird@3.5.1@bluebird/js/release/util.js:16:23)
`

**Comment by ziet** [comment]
I got it too
I copy package.json from app rootpath to '/node_modules/_@angular_core@5.0.3@@angular' and it build ok, i cant figure out why, misuse of try..catch?

**Comment by ltyisangel** [comment]
I got it too.
When ng build --aot --prod, it said 
"95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open 'H:\work\angular\worksheet\node_modules\_@angular_core@4.4.1@@angular\package.json'
".
But I used command "ng build --aot --env=prod", it run OK.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
