### ISSUE TITLE
'ng new' fails

### ISSUE THREAD

**Issue by theChrisMarsh** [angular/angular-cli#7984]
### Versions
```
@angular/cli — 1.4.5
node — 7.2.1
npm — 5.4.2
os — win32 x64 (Windows 10)
```

### Repro Steps
```
ng new sample-app
```

### The log given by the failure
```
C:\Development>ng new sample-app
The command "new" has an option without the required type and name fields.
Error: The command "new" has an option without the required type and name fields.
    at Class.validateOption (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:377:13)
    at Array.map (native)
    at Class.registerOptions (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:163:27)
    at getOptionsTask.run.then (C:\Users\username\AppData\Roaming\npm\node_modules\@angular\cli\commands\new.js:95:18)
```

### Other details that might be useful

I have used npm to uninstall @angular/cli and reinstall it globally.
Other commands also fail with the same error. For example `ng g component some-new-component` also throws the error:
```
The command "generate" has an option without the required type and name fields.
```

**Comment by A-lxe** [comment]
Getting this too. On a fresh install of node/npm.
```
@angular/cli — 1.4.5
node — 6.11.4
npm — 3.10.10
os — Windows 10 x64
```

**Comment by awsaunier** [comment]
I have the same problem after uninstalling and reinstalling  to the latest version using npm.

**Comment by zinzinday** [comment]
```
stdout@desktop-94847:/data/nodejs/angular4$ ng generate component my-new-component
The command "generate" has an option without the required type and name fields.
Error: The command "generate" has an option without the required type and name fields.
    at Class.validateOption (/data/nodejs/angular4/node_modules/@angular/cli/ember-cli/lib/models/command.js:377:13)
    at Array.map (<anonymous>)
    at Class.registerOptions (/data/nodejs/angular4/node_modules/@angular/cli/ember-cli/lib/models/command.js:163:27)
    at getOptionsTask.run.then (/data/nodejs/angular4/node_modules/@angular/cli/commands/generate.js:98:18)
    at <anonymous>
```
I have the same problem

**Comment by cfcortes** [comment]
I am having the same problem

The command "new" has an option without the required type and name fields.
Error: The command "new" has an option without the required type and name fields.
    at Class.validateOption (/node_modules/@angular/cli/ember-cli/lib/models/command.js:377:13)
    at Array.map (native)
    at Class.registerOptions (/node_modules/@angular/cli/ember-cli/lib/models/command.js:163:27)
    at getOptionsTask.run.then (/node_modules/@angular/cli/commands/new.js:95:18)

**Comment by GaboSantyCosta** [comment]
I have the same problem

@angular/cli: 1.4.5
node: 6.11.4
os: win32 x64
npm: 5.4.2

The command "new" has an option without the required type and name fields.
Error: The command "new" has an option without the required type and name fields.
at Class.validateOption (/node_modules/@angular/cli/ember-cli/lib/models/command.js:377:13)
at Array.map (native)
at Class.registerOptions (/node_modules/@angular/cli/ember-cli/lib/models/command.js:163:27)
at getOptionsTask.run.then (/node_modules/@angular/cli/commands/new.js:95:18)

**Comment by jameskbride** [comment]
Same here with new:
```
@angular/cli — 1.4.5
node — 8.6.0
npm — 5.3.0
os — MacOS Sierra (10.12.6)
```

```
20:44 $ ng new static
The command "new" has an option without the required type and name fields.
Error: The command "new" has an option without the required type and name fields.
    at Class.validateOption (/Users/jameskbride/.config/yarn/global/node_modules/@angular/cli/ember-cli/lib/models/command.js:377:13)
    at Array.map (<anonymous>)
    at Class.registerOptions (/Users/jameskbride/.config/yarn/global/node_modules/@angular/cli/ember-cli/lib/models/command.js:163:27)
    at getOptionsTask.run.then (/Users/jameskbride/.config/yarn/global/node_modules/@angular/cli/commands/new.js:95:18)
    at <anonymous>
```

**Comment by puppycock** [comment]
Getting the same error on a fresh installation.

`C:\Dropbox\Nodejs>ng new Angular
The command "new" has an option without the required type and name fields.
Error: The command "new" has an option without the required type and name fields.
    at Class.validateOption (C:\Users\TRABAJO\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:377:13)
    at Array.map (native)
    at Class.registerOptions (C:\Users\TRABAJO\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:163:27)
    at getOptionsTask.run.then (C:\Users\TRABAJO\AppData\Roaming\npm\node_modules\@angular\cli\commands\new.js:95:18)`

**Comment by leotheloser** [comment]
I am also experiencing the issue. Freshly installed CLI.
```
The command "new" has an option without the required type and name fields.
Error: The command "new" has an option without the required type and name fields.
    at Class.validateOption (/usr/local/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:377:13)
    at Array.map (<anonymous>)
    at Class.registerOptions (/usr/local/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:163:27)
    at getOptionsTask.run.then (/usr/local/lib/node_modules/@angular/cli/commands/new.js:95:18)
    at <anonymous>
```

**Comment by noeazar** [comment]
The command "generate" has an option without the required type and name fields.
Error: The command "generate" has an option without the required type and name fields.

**Comment by icarnaghan** [comment]
I have the same issue:

@angular/cli - 1.4.5
node - 8.6.0
npm - 5.3.0
OS - MacOS Sierra 10.12.6

`The command "new" has an option without the required type and name fields.
Error: The command "new" has an option without the required type and name fields.
    at Class.validateOption (/usr/local/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:377:13)
    at Array.map (<anonymous>)
    at Class.registerOptions (/usr/local/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:163:27)
    at getOptionsTask.run.then (/usr/local/lib/node_modules/@angular/cli/commands/new.js:95:18)
    at <anonymous>`

**Comment by Casebash** [comment]
I have the same problem

@angular/cli - 8.6.0
node - 1.4.5
npm - 5.3.0
OS - MacOS High Sierra 10.13

Error: The command "new" has an option without the required type and name fields.
    at Class.validateOption (/Users/chris/.nvm/versions/node/v8.6.0/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:377:13)
    at Array.map (<anonymous>)
    at Class.registerOptions (/Users/chris/.nvm/versions/node/v8.6.0/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:163:27)
    at getOptionsTask.run.then (/Users/chris/.nvm/versions/node/v8.6.0/lib/node_modules/@angular/cli/commands/new.js:95:18)
    at <anonymous>

**Comment by Shravanthy** [comment]
I have the same problem as well

node - v6.11.4
npm - 3.10.10
@angular/cli - 1.4.5
os - win32 x64


>ng new testdemo

The command "new" has an option without the required type and name fields.
Error: The command "new" has an option without the required type and name fields.
    at Class.validateOption (C:\Users\shmoorth\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:377:13)
    at Array.map (native)
    at Class.registerOptions (C:\Users\shmoorth\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:163:27)
    at getOptionsTask.run.then (C:\Users\shmoorth\AppData\Roaming\npm\node_modules\@angular\cli\commands\new.js:95:18)

**Comment by skitto0307** [comment]
Same
I have the same problem.  I had to install 1.3.2 to be able to use the command "new" again.

@angular/cli: 1.4.5
node: 6.11.4
os: win32 x64
npm: 5.4.2

**Comment by delasteve** [comment]
Just spoke with @hansl - he reverted the last commit to github.com/angular/devkit. I just tested after reinstalling the CLI and everything is back to working.

**Comment by joewimmer** [comment]
Yup. worked for me now.   Thanks @delasteve and @hansl

**Comment by jameskbride** [comment]
@delasteve Uninstalled `@angular/cli` and reinstalled (on the assumption that devkit has been updataed).  Back in business now.  Thanks!

**Comment by GaboSantyCosta** [comment]
the problem was solved!

now run

npm uninstall -g @angular/cli
npm cache clean
# if npm version is > 5 then use `npm cache verify` to avoid errors (or to avoid using --force)
npm install -g @angular/cli@latest

**Comment by leotheloser** [comment]
@delasteve all working now! Cheers ::))

**Comment by hansl** [comment]
Fixed by reverting the faulty PR. We'll need to be more careful when untangling the Schematics from the CLI. Closing this as fixed.

**Comment by Shravanthy** [comment]
Working fine for me now. Thank you @delasteve and @hansl

**Comment by skitto0307** [comment]
Working! Thank You

**Comment by shadowmint** [comment]
Is depending on ~0.0.x for devkit (https://github.com/angular/angular-cli/blob/master/package.json#L45) the right move?

Since this means any changes to devkit get rolled out to existing cli versions arbitrarily on the next `npm install`, I expect this kind of breakage will happen relatively often.

If the cli is depending on 'latest' from upstream packages, having any kind of cli release tags becomes somewhat meaningless.

**Comment by puppycock** [comment]
Working now, thanks.

**Comment by Rmsilva1** [comment]
I still have the same error

**Comment by zinzinday** [comment]
i can create project via ng new project-name but can not to generate component and another :)

**Comment by gsknbabu** [comment]
I still not able to get. Same error is coming.

**Comment by aJ5fa1JGN1FatBw6Fa0md5RrVBEk2G** [comment]
I have a possible solution.

Either upgrade from Node 6 to Node 8 or, downgrade to Angular 1.4.2.

This error happens under:
Node 6 with Angular 1.4.3
Node 6 with Angular 1.4.4
Node 6 with Angular 1.4.5

However Node 8 with Angular 1.4.5, works.
Node 6 with Angular 1.4.2 works.

**Comment by gsknbabu** [comment]
Working fine now. Thanks.

**Comment by awsaunier** [comment]
I updated to node 8 and it is now working for me.

**Comment by leetharris** [comment]
I'm still getting this error even with Node 8 and by installing 1.4.2 manually from NPM. 

Windows 10

**Comment by ragavanrajan** [comment]
me too getting the same error. completely removed the node and verified the package.
