### ISSUE TITLE
cannot use in operator to search for providers in null

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#8025]
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
@angular/cli: 1.4.5
node: 6.11.0
os: win32 x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4

```

### Repro steps.
run ng s or ng build

### The log given by the failure.

```
ERROR in TypeError: Cannot use 'in' operator to search for 'providers' in null
    at C:\Users\iii\WebstormProjects\iii\node_modules\@angular\compiler-cli\src\ngtools_impl.js:111:73
    at Array.filter (native)
    at _extractLazyRoutesFromStaticModule (C:\Users\iii\WebstormProjects\iii\node_modules\@angular\compiler-cli\src\ngtools_impl.js:111:29)
    at C:\Users\iii\WebstormProjects\iii\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (C:\Users\iii\WebstormProjects\iii\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at includeLazyRouteAndSubRoutes (C:\Users\iii\WebstormProjects\iii\node_modules\@angular\compiler-cli\src\ngtools_impl.js:66:25)
    at Array.reduce (native)
    at includeLazyRouteAndSubRoutes (C:\Users\iii\WebstormProjects\iii\node_modules\@angular\compiler-cli\src\ngtools_impl.js:67:26)
    at Array.reduce (native)
    at Object.listLazyRoutesOfModule (C:\Users\iii\WebstormProjects\iii\node_modules\@angular\compiler-cli\src\ngtools_impl.js:54:36)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\iii\WebstormProjects\iii\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\iii\WebstormProjects\iii\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\iii\WebstormProjects\iii\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

### Mention any other details that might be useful.
i remove 1.4.6 locally and install 1.4.5  but same problem,
my friend have same project with last version and it build, weird

**Comment by istiti** [comment]
a little **GIF** in action 

![ngs](https://user-images.githubusercontent.com/2789203/31498341-f31cc7d8-af61-11e7-8cb5-1958e7924b8f.gif)


cc @filipesilva

**Comment by istiti** [comment]
Solved (cli not helps me)  to find error, this is very annoying.

I import a thing like 
`import MySuperLib from 'my-super-lib';`
 so without `{ }`

When write like this it works : 
`import { MySuperLib  }from 'my-super-lib';`

I have nothing in my webstorm and cli didn't tell me where is error. Is possible to notice us where imports aren't correct to find because by chance and hazard I find, I could lost whole day to find :( 

you can close issue (or keep it to indicate better  to users in console which file's dammaged)

**Comment by istiti** [comment]
nice this is already fixed !! Im happy 😬
