### ISSUE TITLE
Prod build fails with exception

### ISSUE THREAD

**Issue by Gamester2097** [angular/angular-cli#8040]
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

# Error Description

Unfortunately I cannot build prod anymore. ng serve and debug build works perfectly. Yesterday I upgraded to 4.4.4 (that's when the issues started) but went back. I have no idea what to do. Maybe it's a module I have installed?

**OS**

Windows 10 Pro

**Versions**.
@angular/cli: 1.4.6
node: 8.2.1
os: win32 x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.3.3
@angular/compiler: 4.3.3
@angular/compiler-cli: 4.3.3
@angular/core: 4.3.3
@angular/forms: 4.3.3
@angular/http: 4.3.3
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.3.3
@angular/platform-browser-dynamic: 4.3.3
@angular/platform-server: 4.3.3
@angular/router: 4.3.3
@angular/cli: 1.4.6
typescript: 2.3.4

# npm Version:

{ inspinia: '2.7.1',
  npm: '5.3.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  node: '8.2.1',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.13.1',
  v8: '5.8.283.41',
  zlib: '1.2.11' }


# ### The log given by the failure.
C:\Development\LMCRM\LM_CRM\WebFrontEnd>ng build --prod
 11% building modules 13/20 modules 7 active ...nts\glyphicons-halflings-regular.woffTemplate parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///C:/Development/LMCRM/LM_CRM/WebFrontEnd/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0            95% emittingUnhandled rejection TypeError: Cannot read property 'length' of undefined
    at Object.size (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\webpack-concat-plugin\index.js:127:39)
    at obj.assets.compilationAssets.map.asset (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\webpack\lib\Stats.js:258:38)
    at Array.map (native)
    at Stats.toJson (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\webpack\lib\Stats.js:255:35)
    at Compiler.<anonymous> (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\html-webpack-plugin\index.js:68:44)
    at next (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\tapable\lib\Tapable.js:204:14)
    at Compiler.compiler.plugin (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\webpack\lib\ProgressPlugin.js:128:5)
    at next (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\tapable\lib\Tapable.js:204:14)
    at callback (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\dist\index.js:71:17)
    at PassThroughHandlerContext.finallyHandler (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\node_modules\bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Development\LMCRM\LM_CRM\WebFrontEnd\node_modules\copy-webpack-plugin\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)



Here's my angular-cli.json:

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "inspinia"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.css",
        "../node_modules/font-awesome/css/font-awesome.css",
        "../node_modules/animate.css/animate.min.css",
        "styles.scss",
        "assets/styles/datatables.min.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/metismenu/dist/metisMenu.js",
        "../node_modules/jquery-sparkline/jquery.sparkline.js",
        "../vendor/pace/pace.min.js",
        "assets/js/dthelper.js",
        "assets/js/datatables.min.js"        
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

**Comment by RicardoVaranda** [comment]
Hi @Gamester2097  , Could you provide us with a minimal repo of this issue, when analyzing your error code it seems like your problem is caused due to a deprecated element name: 

```The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">```

**Comment by Gamester2097** [comment]
Hi @RicardoVaranda!

Thanks for your reply. Unfortunately I couldn't reproduce the issue in any test project.
Though meanwhile I was able to fix it in my productive project by doing the following steps:

- reinstalled angular/cli (not sure in necessary)
- Deleted the node_modules folder physically
- npm cache clear --force
- npm install

This did the trick for me.
 
Sorry that I can't provide further repo for debugging.

BTW: The depcrecated element is in the ngx-bootstrap module.
