### ISSUE TITLE
Report file errors on loader

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#8058]
Currently compilation errors get reported in the entry points (`polyfills.ts`, `main.ts`) and for the compilation itself afterwards:

```
ERROR in ./src/polyfills.ts
Module build failed: Error: TypeScript compilation failed.
    at plugin.done.then (/Users/iminar/tmp/regression-test-project/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/loader.js:479:27)
 @ multi ./src/polyfills.ts
ERROR in ./src/main.ts
Module build failed: Error: TypeScript compilation failed.
    at plugin.done.then (/Users/iminar/tmp/regression-test-project/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/loader.js:479:27)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ multi ./src/main.ts
ERROR in Error: Unexpected value 'MdIconModule in /Users/iminar/tmp/regression-test-project/node_modules/@angular/material/material.d.ts' imported by the module 'AppModule in /Users/iminar/tmp/regression-test-project/src/app/app.module.ts'. Please add a @NgModule annotation.
```

We should instead report errors for a given file on the file loader, and the rest of these errors in the compilation.

**Comment by bjohnson-va** [comment]
Is there a workaround for this?

**Comment by Stradivario** [comment]
I have the same problem and it come from no where... in about 10 minutes my builds where passing and after one css change and re-build application i cannot build production no more...

**Comment by istiti** [comment]
can't work, im stressed, im scared, this is urgent

all my module are telling : 
```
Module build failed: Error: C:\Users\eee\WebstormProjects\iii\src\app\societe\societe
.module.ts is not part of the compilation. Please make sure it is in your tsconfig via
the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\eee\WebstormProjects\iii\node_
modules\@ngtools\webpack\src\angular_compiler_plugin.js:693:23)
    at plugin.done.then (C:\Users\eee\WebstormProjects\iii\node_modules\@ngtools\webp
ack\src\loader.js:467:39)
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

```
but I don't know what I need to change in my [tsconfig.json](https://gist.github.com/istiti/c533f83a227cf74e681938adc0c052cb)  and in my [tsconfig.app.json](https://gist.github.com/istiti/0696f6ff8454c4138c9b2f987dbdb0d5)

**Comment by bjohnson-va** [comment]
@istit I believe you can just roll back to 1.4.7 if you need to keep working

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/8203
