### ISSUE TITLE
error while running angular4 application

### ISSUE THREAD

**Issue by arjunpawar1** [angular/angular-cli#8060]
I have an angular4 application in which I have imported private modules I had created and published in an NPM registry (these are also individual angular4 apps). Now, when I am trying to start the application I am getting the error. (P.S. I am able to run the application successfully If I comment the Pvt. module imports and uncomment it only after the app is successfully built)

`
ERROR in Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported
. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/sinopia/test/gtest/
node_modules/@netapp/flash-advisor-ui/node_modules/@angular/core/core.d.ts, resolving symbol AppModule in C:/sinopia/test/gtest/node_modu
les/@netapp/flash-advisor-ui/src/app/app.module.ts, resolving symbol AppModule in C:/sinopia/test/gtest/node_modules/@netapp/flash-adviso
r-ui/src/app/app.module.ts
    at Error (native)
    at syntaxError (C:\sinopia\test\gtest\node_modules\@angular\compiler\bundles\compiler.umd.js:1513:34)
    at simplifyInContext (C:\sinopia\test\gtest\node_modules\@angular\compiler\bundles\compiler.umd.js:23802:23)
    at StaticReflector.simplify (C:\sinopia\test\gtest\node_modules\@angular\compiler\bundles\compiler.umd.js:23814:13)
    at StaticReflector.annotations (C:\sinopia\test\gtest\node_modules\@angular\compiler\bundles\compiler.umd.js:23263:41)
    at _getNgModuleMetadata (C:\sinopia\test\gtest\node_modules\@angular\compiler-cli\src\ngtools_impl.js:126:31)
    at _extractLazyRoutesFromStaticModule (C:\sinopia\test\gtest\node_modules\@angular\compiler-cli\src\ngtools_impl.js:101:26)
    at C:\sinopia\test\gtest\node_modules\@angular\compiler-cli\src\ngtools_impl.js:117:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (C:\sinopia\test\gtest\node_modules\@angular\compiler-cli\src\ngtools_impl.js:116:10)
    at Object.listLazyRoutesOfModule (C:\sinopia\test\gtest\node_modules\@angular\compiler-cli\src\ngtools_impl.js:52:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\sinopia\test\gtest\node_modules\@angular\compiler-cli\src\ngtools_api.js:79:3
9)
    at AotPlugin._getLazyRoutesFromNgtools (C:\sinopia\test\gtest\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\sinopia\test\gtest\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)
webpack: Failed to compile.
`

**Comment by filipesilva** [comment]
Hello, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

Angular CLI always runs *some* statical analysis, even on JIT mode, in order to discover lazy-loaded routes.
This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Below are good resources on how to to debug these errors:
- https://angular.io/guide/metadata
- https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60
- https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts

If your problem still persists, it might be a bug with the Angular Compiler itself.
In that case, please open an issue in https://github.com/angular/angular.
