### ISSUE TITLE
Can't run e2e tests - server terminated early

### ISSUE THREAD

**Issue by herzinger** [angular/angular-cli#8073]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [   ] feature request
```

### Versions.
```bash
$ ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.7
node: 6.11.3
os: linux x64
@angular/animations: 4.4.5
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.5
@angular/compiler: 4.4.5
@angular/core: 4.4.5
@angular/forms: 4.4.5
@angular/http: 4.4.5
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.5
@angular/platform-browser-dynamic: 4.4.5
@angular/platform-server: 4.4.5
@angular/router: 4.4.5
@angular/cli: 1.4.7
@angular/compiler-cli: 4.4.5
@angular/language-service: 4.4.5
typescript: 2.3.4
```
**Obs:** 
os says `linux x64` but it's actually the WSL (Bash on Ubuntu on Windows). The host os is Windows 10 (Insiders Preview 1709)

### Repro steps.
I tried starting a clean project in another directory, with the same results. So I guess:

```bash
$ ng set --global packageManager=yarn
$ ng new --style=scss --routing
$ ng e2e
```

### The log given by the failure.
```bash
$ ng e2e
** NG Live Development Server is listening on localhost:49152, open your browser on http://localhost:49152/ **
Date: 2017-10-17T00:40:54.581Z
Hash: 562fcb0b1a64fe32f228
Time: 27858ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 4.74 MB {inline} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 217 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 122 kB {inline} [initial] [rendered]

webpack: Compiled successfully.
[00:40:54] I/file_manager - creating folder /mnt/c/Users/henri/workspace/ng-lejour/node_modules/webdriver-manager/selenium
[00:41:32] I/update - chromedriver: unzipping chromedriver_2.33.zip
[00:41:33] I/update - chromedriver: setting permissions to 0755 for /mnt/c/Users/henri/workspace/ng-lejour/node_modules/webdriver-manager/selenium/chromedriver_2.33
[00:41:33] I/launcher - Running 1 instances of WebDriver
[00:41:33] I/direct - Using ChromeDriver directly...
[00:41:33] E/launcher - Server terminated early with status 127
[00:41:33] E/launcher - Error: Server terminated early with status 127
    at Error (native)
    at earlyTermination.catch.e (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/selenium-webdriver/remote/index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/protractor/node_modules/q/q.js:796:13)
    at /mnt/c/Users/henri/workspace/ng-lejour/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/mnt/c/Users/henri/workspace/ng-lejour/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[00:41:33] E/launcher - Process exited with error code 199
```

### Desired functionality.
Run e2e tests.

### Mention any other details that might be useful.
It's in a private repo on gitlab, but there's not much stuff there yet anyway, so I can give you access if needed. Also, the same error happened in gitlab's ci/cd. I hadn't write any tests yet, it was there that I got to see the problem first. This is my configuration file for that:

```yml
image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - master
  script:
    - npm install
    - ng test --browsers=ChromeHeadless -sr --progress=false
    - npm run ng e2e --serve=false
    - npm run ng build --progress false --prod --aot --base-href ng-lejour-stage.surge.sh
    - ./node_modules/.bin/surge -p dist/ --domain ng-lejour-stage.surge.sh

```

**Comment by filipesilva** [comment]
Does this happen outside of WSL? That sort of errors is usually due to the environment. You have to setup chrome and your tests properly for that to work. You might have done that for karma with `--browsers=ChromeHeadless` but you still need to do it for Protractor.

See https://github.com/angular/angular-cli/wiki/stories-continuous-integration for some guidance without using `ChromeHeadless`. Using chrome headless requires specific configuration as well: https://github.com/angular/protractor/blob/master/docs/browser-setup.md#using-headless-chrome. 

CI configuration differs wildly between CI provider so there isn't much help I can reasonably provide. But I can tell you it's usually hard and frustrating to debug problems with chrome on CI, so don't be surprised if it takes a bit of time. As long as it runs in your local environment (non-WSL, because that doesn't have a screen and also needs to be configured like a CI basically), then you should be able to configure CI to make it work.

Also worth mentioning is that in your CI, flags are not being used in `npm run` commands. You need to do `npm run scriptname -- --flag --flagtwo`, with the double dashes, to send those args into the command. So `npm run ng e2e --serve=false` is instead `npm run ng e2e -- --serve=false` - which won't work, because your app won't be served and thus there is nothing for protractor to connect to.

**Comment by wahab054** [comment]
@herzinger Were you able to fix this?

**Comment by herzinger** [comment]
@wahab054 sorry, it was so long ago I don't remember anything about that
