### ISSUE TITLE
Having issuses trying to run Angular on my computer.

### ISSUE THREAD

**Issue by Superman795** [angular/angular-cli#8147]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
@angular/cli: 1.4.9
node: 6.11.4
npm: 3.10.10
os: win32 x64

### Repro steps.
I was following the Angular Quick Start guide : https://angular.io/guide/quickstart
Followed and carried out all the steps and when I tried to enter ng serve -o, I was given the error log.

### The log given by the failure.
C:\Users\Rajan\my-app>ng serve -o
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (C:\Users\Rajan\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Rajan\AppData\Roaming\npm\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19) 

### Desired functionality.
I just want Angular to work on my computer as I want to develop apps.

### Mention any other details that might be useful.
![screenshot 11](https://user-images.githubusercontent.com/30099438/31873828-0e044486-b809-11e7-8e3d-f5170f339cd5.png)

**Comment by Superman795** [comment]
I searched google for the answer and found out that you need to uninstall the node_modules folder and re-install it with npm install.
to uninstall node_modules : npm install rimraf -g 
to reinstall: npm install

this resolved everything.
