### ISSUE TITLE
@angular@5.0.0-rc.3 and @angular/cli 1.5.0-beta.3 ERROR in TypeError: this.compiler.listLazyRoutes is not a function 

### ISSUE THREAD

**Issue by Stradivario** [angular/angular-cli#8166]
Hello there after updating to beta-3 cli i have the following error when i try to build 

```
ng build --aot --prod
```

```
ERROR in TypeError: this.compiler.listLazyRoutes is not a function
```

Full stacktrace
```
Date: 2017-10-24T13:34:14.826Z
Hash: 627bcc0447c626bbf583
Time: 7639ms
chunk {0} styles.6836259b7c89f232e1e8.bundle.css (styles) 55.5 kB {3} [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes {3} [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.9fb4e836276006143c8d.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in TypeError: this.compiler.listLazyRoutes is not a function
    at AngularCompilerProgram.listLazyRoutes (/x/x/x/x/repos/private/store/client/node_modules/@angular/compiler-cli/src/transformers/program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/x/x/x/x/repos/private/store/client/node_modules/@angular/compiler-cli/src/ngtools_api.js:36:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/x/x/x/work/repos/private/store/client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:231:66)
    at Promise.resolve.then (/x/x/x/work/repos/private/store/client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:483:46)
    at process._tickCallback (internal/process/next_tick.js:109:7)
rampage@rampage-ThinkStation-D20:~/x/x/x/private/store/client$ ^C
rampage@rampage-ThinkStation-D20:~/x/x/x/private/store/client$
```

Any workarounds ?

**Comment by Stradivario** [comment]
I updated to angular@5.0.0-rc.5 everything is wokring now :) 
I assume that i need to wait untill full 5 is released and not write such a issues because it is not relevant to the current situation.
