### ISSUE TITLE
1.5.0-rc.4 release broken

### ISSUE THREAD

**Issue by brandom** [angular/angular-cli#8202]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0-rc.4
Node: 8.8.0
OS: darwin x64
```

### Repro steps.
npm i -g @angular/cli@1.5.0-rc.4
ng --version

### The log given by the failure.
``` js
/path/@angular/cli/upgrade/version.js:12
const { bold, red, yellow } = chalk_1.default;
        ^

TypeError: Cannot destructure property `bold` of 'undefined' or 'null'.
    at Object.<anonymous> (/path/@angular/cli/upgrade/version.js:12:39)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/@angular/cli/commands/build.js:4:19)
    at Module._compile (module.js:612:30)
```

### Desired functionality.
Output version.

### Mention any other details that might be useful.
Same error generated for all cli commands. `ng --version` works outside of CLI project.

**Comment by hansl** [comment]
hey @brandom 

Could you try nuking your node_modules and reinstalling? See if that helps.

**Comment by leocaseiro** [comment]
I've fixed installing `chalk`

`npm install chalk@latest --save-dev`

Thanks guys!

**Comment by intellix** [comment]
had this myself after an `npm i @angular/cli@next` but fixed it after deleting `package-lock.json` and reinstalling. My lock was depending on chalk 2.1.0 but afterwards it was 2.3.0 and worked
