### ISSUE TITLE
Unable to install angular cli

### ISSUE THREAD

**Issue by sauravpandit** [angular/angular-cli#8258]
I am trying to install angular cli in my local machine.

Please find the node and npm version below
XBBLJHP@DA5H7QY0NV1 MINGW64 /c/Data/CODE/NODE
$ npm -v
**5.5.1**

XBBLJHP@DA5H7QY0NV1 MINGW64 /c/Data/CODE/NODE
$ node -v
**v8.1.3**

 npm install -g @angular/cli --verbose

I am getting the following error
---------------------------------------------------------
```
npm verb type range
npm verb stack @schematics/angular: No matching version found for @schematics/angular@~0.0.46
npm verb stack     at pickManifest (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\npm-pick-manifest\index.js:61:11)
npm verb stack     at fetchPackument.then.packument (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:51:18)
npm verb stack     at tryCatcher (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm verb stack     at Async._drainQueue (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm verb stack     at Async._drainQueues (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (C:\Users\xbbljhp\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at runCallback (timers.js:800:20)
npm verb stack     at tryOnImmediate (timers.js:762:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
npm verb cwd C:\Data\CODE\NODE
npm verb Windows_NT 6.1.7601
```
................
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @schematics/angular@~0.0.46
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@angular/cli'
npm ERR! notarget
```
---------------------------------------------------------
Can someone help me to fix this issue.

**Comment by sauravpandit** [comment]
Any reply on this?

**Comment by sauravpandit** [comment]
I have tried to install schematics/angular and got it install without any issue
```
npm i -g @schematics/angular
C:\Data>npm i -g @schematics/angular
npm WARN @schematics/angular@0.0.45 requires a peer of @angular-devkit/schematics@0.0.33 but none is installed. You must install peer dependencies yourself.

+ @schematics/angular@0.0.45
added 1 package in 1.235s
```
But if I try to install angular cli, It is throwing me same error.  I am not sure why schematics/angular is still not getting available to angular cli.

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
