### ISSUE TITLE
@ngtools/webpack "readConfiguration is not a function"

### ISSUE THREAD

**Issue by MitchTalmadge** [angular/angular-cli#8287]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
@angular/cli: 1.1.1
node: 6.9.1
os: win32 x64
@angular/animations: 5.0.0
@angular/common: 5.0.0
@angular/compiler: 5.0.0
@angular/core: 5.0.0
@angular/forms: 5.0.0
@angular/http: 5.0.0
@angular/platform-browser: 5.0.0
@angular/platform-browser-dynamic: 5.0.0
@angular/router: 5.0.0
@angular/compiler-cli: 4.4.6
@ngtools/webpack: 1.8.0
```

Windows 10 x64

### Repro steps.

I am trying to build with this command: 

`webpack --config webpack/webpack.production.config.js -p --progress`

You can find my repository here: https://github.com/MitchTalmadge/Portfolio

Relevant links: 
- Webpack Configs (dev and prod inherit from common): https://github.com/MitchTalmadge/Portfolio/tree/master/web/webpack
- package.json: https://github.com/MitchTalmadge/Portfolio/blob/master/web/package.json
- tsconfig.json: https://github.com/MitchTalmadge/Portfolio/blob/master/web/tsconfig.json
- Angular code: https://github.com/MitchTalmadge/Portfolio/tree/master/web/src

### The log given by the failure.

```
D:\Media\Programming\Personal\IntelliJ Projects\Portfolio\web\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:88
        const config = ngtools_api_1.readConfiguration(this._tsConfigPath);
                                     ^

TypeError: ngtools_api_1.readConfiguration is not a function
    at AngularCompilerPlugin._setupOptions (D:\Media\Programming\Personal\IntelliJ Projects\Portfolio\web\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:88:38)
    at new AngularCompilerPlugin (D:\Media\Programming\Personal\IntelliJ Projects\Portfolio\web\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:43:14)
    at Object.<anonymous> (D:\Media\Programming\Personal\IntelliJ Projects\Portfolio\web\webpack\webpack.production.config.js:18:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (D:\Media\Programming\Personal\IntelliJ Projects\Portfolio\web\node_modules\webpack\bin\convert-argv.js:97:18)
    at D:\Media\Programming\Personal\IntelliJ Projects\Portfolio\web\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (native)
    at module.exports (D:\Media\Programming\Personal\IntelliJ Projects\Portfolio\web\node_modules\webpack\bin\convert-argv.js:102:15)
    at yargs.parse (D:\Media\Programming\Personal\IntelliJ Projects\Portfolio\web\node_modules\webpack\bin\webpack.js:171:41)
    at Object.Yargs.self.parse (D:\Media\Programming\Personal\IntelliJ Projects\Portfolio\web\node_modules\webpack\node_modules\yargs\yargs.js:533:18)
```

### Desired functionality.

It should build.

**Comment by filipesilva** [comment]
You need to use `@angular/compiler-cli: 5.0.0`, but you are using `@angular/compiler-cli: 4.4.6`. Once you update it should be working.

**Comment by MitchTalmadge** [comment]
Oops! Thanks a bunch :)
