### ISSUE TITLE
ng test -> karma; missing "test"-key:value in .angular-cli.json leads to very misleading error

### ISSUE THREAD

**Issue by maks187** [angular/angular-cli#8299]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions.

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.9
node: 6.11.0
os: win32 x64
@angular/animations: 4.4.6
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/material: 2.0.0-beta.12
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.9
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

### Repro steps.

Later integration of Karma test into agular-cli environment and forgotten test-key-value in .angular-cli.json leads to an very hard to find error.
ng test
outputs the error:

### The log given by the failure.

Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at Object.getTestConfig (C:\xxxx\node_modules\@angular\cli\models\webpack-configs\test.js:43:24)
    at WebpackTestConfig.buildConfig (C:\xxxx\node_modules\@angular\cli\models\webpack-test-config.js:16:31)
    at init (C:\xxxx\node_modules\@angular\cli\plugins\karma.js:95:94)
    at Array.invoke (C:\xxxx\node_modules\di\lib\injector.js:75:15)
    at Injector.get (C:\xxxx\node_modules\di\lib\injector.js:48:43)
    at C:\xxxx\node_modules\karma\lib\server.js:143:20
    at Array.forEach (native)
    at Server._start (C:\xxxx\node_modules\karma\lib\server.js:142:21)
    at Injector.invoke (C:\xxxx\node_modules\di\lib\injector.js:75:15)
    at Server.start (C:\xxxx\node_modules\karma\lib\server.js:103:18)
    at Promise (C:\xxxx\node_modules\@angular\cli\tasks\test.js:41:25)
    at Class.run (C:\xxxx\node_modules\@angular\cli\tasks\test.js:20:16)
    at Class.run (C:\xxxx\node_modules\@angular\cli\commands\test.js:109:25)
    at resolve (C:\xxxx\node_modules\@angular\cli\ember-cli\lib\models\command.js:261:20)

### Desired functionality.

An error which shows what is really missing.
so====>
...
"polyfills": "polyfills.ts",
----> "test": "test.ts", <-----
"tsconfig": "../tsconfig.json",
...

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
