### ISSUE TITLE
ng serve not working with custom --source-dir

### ISSUE THREAD

**Issue by dragonflypl** [angular/angular-cli#8305]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

```
Angular CLI: 1.5.0
Node: 8.4.0
OS: win32 x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.

`ng new fooGui --prefix foo --style scss --routing true --skip-git true --source-dir src/main/client`

`cd fooGui`

`npm start`

### The log given by the failure.

```
> foo-gui@0.0.0 start C:\Users\drago\fooGui
> ng serve

ENOENT: no such file or directory, stat 'C:\Users\drago\fooGui\src\main\client\tsconfig.app.json'
Error: ENOENT: no such file or directory, stat 'C:\Users\drago\fooGui\src\main\client\tsconfig.app.json'
    at Object.fs.statSync (fs.js:954:11)
    at AngularCompilerPlugin._setupOptions (C:\Users\drago\fooGui\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:78:16)
    at new AngularCompilerPlugin (C:\Users\drago\fooGui\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:43:14)
    at _createAotPlugin (C:\Users\drago\fooGui\node_modules\@angular\cli\models\webpack-configs\typescript.js:77:16)
    at Object.getNonAotConfig (C:\Users\drago\fooGui\node_modules\@angular\cli\models\webpack-configs\typescript.js:100:19)
    at NgCliWebpackConfig.buildConfig (C:\Users\drago\fooGui\node_modules\@angular\cli\models\webpack-config.js:33:37)
    at Class.run (C:\Users\drago\fooGui\node_modules\@angular\cli\tasks\serve.js:71:98)
    at check_port_1.checkPort.then.port (C:\Users\drago\fooGui\node_modules\@angular\cli\commands\serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! foo-gui@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foo-gui@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\drago\AppData\Roaming\npm-cache\_logs\2017-11-02T16_51_22_936Z-debug.log
```

### Desired functionality.

`ng serve` should simply work.

**Comment by Brocco** [comment]
Please share your `.angular-cli.json` file.

**Comment by dragonflypl** [comment]
I didn't change `.angular-cli.json` file, it has default generated content.

**Comment by dragonflypl** [comment]
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "foo-gui"
  },
  "apps": [
    {
      "root": "src/main/client",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "foo",
      "styles": [
        "styles.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/main/client/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/main/client/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "component": {}
  }
}
```

**Comment by loiane** [comment]
When source dir is specified, only `app` folder is being created inside the custom dir. 

From terminal (CLI 1.5.0):
```
ng new angular-project --source-dir=src/client --minimal --style=scss
  create angular-project/.angular-cli.json (1630 bytes)
  create angular-project/.gitignore (516 bytes)
  create angular-project/src/assets/.gitkeep (0 bytes)
  create angular-project/src/environments/environment.prod.ts (51 bytes)
  create angular-project/src/environments/environment.ts (387 bytes)
  create angular-project/src/index.html (316 bytes)
  create angular-project/src/main.ts (370 bytes)
  create angular-project/src/polyfills.ts (2667 bytes)
  create angular-project/src/styles.scss (80 bytes)
  create angular-project/src/tsconfig.app.json (211 bytes)
  create angular-project/src/typings.d.ts (104 bytes)
  create angular-project/package.json (851 bytes)
  create angular-project/tsconfig.json (363 bytes)
  create angular-project/src/client/app/app.module.ts (314 bytes)
  create angular-project/src/client/app/app.component.ts (1363 bytes)
```

In previous versions, these files were also being generated under the custom directory:

```
 create angular-project/src/client/assets/.gitkeep (0 bytes)
  create angular-project/src/client/environments/environment.prod.ts (51 bytes)
  create angular-project/src/client/environments/environment.ts (387 bytes)
  create angular-project/src/client/index.html (316 bytes)
  create angular-project/src/client/main.ts (370 bytes)
  create angular-project/src/client/polyfills.ts (2667 bytes)
  create angular-project/src/client/styles.scss (80 bytes)
  create angular-project/src/client/tsconfig.app.json (211 bytes)
  create angular-project/src/client/typings.d.ts (104 bytes)
```

Workaround:

Move files above to the custom directory, open `tsconfig.app.json` and fix the relative path for `"extends": "../../tsconfig.json"` and `"outDir"`
