### ISSUE TITLE
Error: write EPIPE occurs in ng serve

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular-cli#8355]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
Angular CLI: 1.5.0
Node: 8.9.0
OS: win32 ia32
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.
ng serve
This bug has occurred when any file changes. it doesn't occur frequently

### The log given by the failure.
```
ERROR in Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at ChildProcess.target._send (internal/child_process.js:702:20)
    at ChildProcess.target.send (internal/child_process.js:586:19)
    at AngularCompilerPlugin._updateForkedTypeChecker (C:\Users\Sheik Althaf\Documents\angular\butterflySchool\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:370:34)
    at Promise.resolve.then (C:\Users\Sheik Althaf\Documents\angular\butterflySchool\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:208:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Desired functionality.
breaks the ng serve

**Comment by stefanKuijers** [comment]
Same here but for me it happens very frequently. 
Steps to reproduce:
```ng new myApp```
```ng serve --open```
and change any file. 

```Angular CLI: 1.5.0
Node: 8.0.0
OS: win32 ia32
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.4.2
webpack: 3.8.1
```

Same error:
```
ERROR in Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.target._send (internal/child_process.js:665:20)
    at ChildProcess.target.send (internal/child_process.js:549:19)
    at AngularCompilerPlugin._updateForkedTypeChecker (D:\dev\angular-cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:370:34)
    at Promise.resolve.then (D:\dev\angular-cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:208:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

webpack: Failed to compile.
```

**Comment by stefanKuijers** [comment]
Could it be related to https://github.com/nodejs/node/issues/947
?

**Comment by stefanKuijers** [comment]
I updated my node to v8.9.1 and I don;'t have the problem any more. 

Fixed for me!

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/8090 together with https://github.com/angular/angular-cli/pull/8646 should have fixed this problem generally.
