### ISSUE TITLE
I cannot Install Angular CLI

### ISSUE THREAD

**Issue by ApreciaDrive** [angular/angular-cli#8415]
### OS

Windows 8

### Versions.

npm -v
5.5.1
node -v
v8.9.1

### Repro steps.

``
ng --version
``

### The log given by the failure.

``
$ ng --version
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest"

module.js:538
    throw err;
    ^

Error: Cannot find module './_object-create'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Kamo\node_modules\core-js\library\modules\_iter-create.js:2:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

``

### Mention any other details that might be useful.

I have tried uninstalling and installing everything. I have tried to run cmd with admin privileges still nothing.

**Comment by JinsPeter** [comment]
I just have windows 10. And I got it all fine. 
Is it getting installed globally? Or is it just dev dependencies. Try installing globally and see the issue persists.

**Comment by Brocco** [comment]
This seems like an installation issue. Please try the steps @JinsPeter suggested.

If that works, please close the issue.

If that does not work, please post your package.json file from your project.

**Comment by ApreciaDrive** [comment]
After so many trial it ended up installing and working.
