### ISSUE TITLE
Minimist reference throwing error on NGC build

### ISSUE THREAD

**Issue by eestein** [angular/angular-cli#8436]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
eestein@SteinMac sdk-front (master) $ ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.0
Node: 7.7.3
OS: darwin x64
Angular: 5.0.1
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps.
Create a lib project and run ngc

gulp ngc task:

```
gulp.task('ngc', function () {
    return ngc({
        project: `${tmpFolder}/tsconfig.es5.json`
    })
        .then((exitCode) => {
            if (exitCode === 1) {
                throw new Error('Compiler error');
            }
        });
});
```

### The log given by the failure.
```
[10:18:41] TypeError: args.indexOf is not a function
    at module.exports (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/minimist/index.js:44:14)
    at readNgcCommandLineAndConfiguration (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/@angular/compiler-cli/src/main.js:66:41)
    at main (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/@angular/compiler-cli/src/main.js:21:24)
    at Gulp.<anonymous> (/Users/eestein/Documents/dev/dacasa/sdk-front/gulpfile.js:47:12)
    at module.exports (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/run-sequence/index.js:75:5)
ERROR: args.indexOf is not a function
```

### Desired functionality.
Run build with no error

### Mention any other details that might be useful.

minimist code:
```
    var notFlags = [];

    if (args.indexOf('--') !== -1) {                   // line throwing error
        notFlags = args.slice(args.indexOf('--')+1);
        args = args.slice(0, args.indexOf('--'));
    }
```
compiler-cli code:

```
function readNgcCommandLineAndConfiguration(args) {
    var options = {};
    var parsedArgs = require('minimist')(args);                  // line throwing error
```

**Comment by SublimeProphets** [comment]
I have exactly the same issue

**Comment by clydin** [comment]
`ngc` is managed from the main angular repository (https://github.com/angular/angular).
As to the issue, `args` is supposed to be a string array of the command line arguments (https://github.com/angular/angular/blob/master/packages/compiler-cli/src/main.ts#L162).

**Comment by eestein** [comment]
@clydin I just opened an issue there. As per your comment, I don't follow... you're saying this behavior is intended or that it should be a string while it is not?

Thanks

**Comment by clydin** [comment]
The code above is passing an object as a parameter to a function that expects an array of strings. Throwing an error is both expected and intentional.

**Comment by eestein** [comment]
Fix was provided by @Zaljin

https://github.com/angular/angular/issues/20342#issuecomment-343574764
