### ISSUE TITLE
AOT build breaks core-js; TypeError: Cannot read property 'subscribe' of undefined 

### ISSUE THREAD

**Issue by khaledosman** [angular/angular-cli#8441]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.0
Node: 9.0.0
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.6.1
webpack: 3.8.1

```

### Repro steps.
1) here's my package.json file
 ```
 "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.2",
    "@swimlane/ngx-datatable": "^11.0.0",
    "angular2-moment": "^1.7.0",
    "bootstrap": "^4.0.0-alpha.6",
    "core-js": "^2.5.0",
    "font-awesome": "^4.7.0",
    "fuse.js": "^3.0.5",
    "ngx-infinite-scroll": "^0.6.1",
    "primeng": "^5.0.0-rc.0",
    "rxjs": "^5.4.3",
    "zone.js": "^0.8.17"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "^2.5.54",
    "@types/node": "~8.0.25",
    "codelyzer": "~4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.2.0",
    "ts-node": "~3.3.0",
    "tslint": "~5.8.0",
    "typescript": "=2.6.1"
  }
```
2) ng build --prod
3) serve the app

### The log given by the failure.
```
core.js:1350 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'subscribe' of undefined
TypeError: Cannot read property 'subscribe' of undefined
    at createDirectiveInstance (core.js:12015)
    at createViewNodes (core.js:13449)
    at callViewAction (core.js:13881)
    at execComponentViewsAction (core.js:13790)
    at createViewNodes (core.js:13477)
    at callViewAction (core.js:13881)
    at execComponentViewsAction (core.js:13790)
    at createViewNodes (core.js:13477)
    at createRootView (core.js:13339)
    at callWithDebugContext (core.js:14740)
    at createDirectiveInstance (core.js:12015)
    at createViewNodes (core.js:13449)
    at callViewAction (core.js:13881)
    at execComponentViewsAction (core.js:13790)
    at createViewNodes (core.js:13477)
    at callViewAction (core.js:13881)
    at execComponentViewsAction (core.js:13790)
    at createViewNodes (core.js:13477)
    at createRootView (core.js:13339)
    at callWithDebugContext (core.js:14740)
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at zone.js:873
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4620)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at <anonymous>
```

### Desired functionality.
looks like AOT build removes required dependencies, same build works when I run
ng build --prod --aot=false

**Comment by AFriemann** [comment]
Same thing happens for me with `ng serve -aot` and `ng build -aot` 

```
"dependencies": {
    "@angular/animations": "^5.0.2",
    "@angular/common": "^5.0.2",
    "@angular/compiler": "^5.0.2",
    "@angular/core": "^5.0.2",
    "@angular/forms": "^5.0.2",
    "@angular/http": "^5.0.2",
    "@angular/platform-browser": "^5.0.2",
    "@angular/platform-browser-dynamic": "^5.0.2",
    "@angular/router": "^5.0.2",
    "@angular/flex-layout": "2.0.0-beta.10-4905443",
    "@angular/cdk": "5.0.0-rc0",
    "@angular/material": "5.0.0-rc0",
    "@swimlane/ngx-datatable": "11.0.3",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14",
    "primeng": "4.2.1",
    "font-awesome": "4.7.0",
    "fuzzy-search": "2.0.0",
    "web-animations-js": "~2.3.1",
    "moment": "2.19.2",
    "moment-timezone": "0.5.14",
    "angular2-moment": "1.7.0",
    "browser-locale": "1.0.3",
    "material-design-icons": "3.0.1"
  },
  "devDependencies": {
    "@angular/cli": "1.5.2",
    "@angular/compiler-cli": "^5.0.2",
    "@angular/language-service": "^5.0.2",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "@types/web-animations-js": "~2.2.5",
    "@types/moment-timezone": "0.5.0",
    "typescript": "~2.6.1",
    "codelyzer": "~4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0"
  }
```


```
Unhandled Promise rejection: Cannot read property 'subscribe' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'subscribe' of undefined
    at createDirectiveInstance (core.js:12015)
    at createViewNodes (core.js:13449)
    at callViewAction (core.js:13881)
    at execComponentViewsAction (core.js:13790)
    at createViewNodes (core.js:13477)
    at callViewAction (core.js:13881)
    at execComponentViewsAction (core.js:13790)
    at createViewNodes (core.js:13477)
    at createRootView (core.js:13339)
    at callWithDebugContext (core.js:14740) TypeError: Cannot read property 'subscribe' of undefined
    at createDirectiveInstance (http://localhost/vendor.bundle.js:92058:96)
    at createViewNodes (http://localhost/vendor.bundle.js:93492:53)
    at callViewAction (http://localhost/vendor.bundle.js:93924:13)
    at execComponentViewsAction (http://localhost/vendor.bundle.js:93833:13)
    at createViewNodes (http://localhost/vendor.bundle.js:93520:5)
    at callViewAction (http://localhost/vendor.bundle.js:93924:13)
    at execComponentViewsAction (http://localhost/vendor.bundle.js:93833:13)
    at createViewNodes (http://localhost/vendor.bundle.js:93520:5)
    at createRootView (http://localhost/vendor.bundle.js:93382:5)
    at callWithDebugContext (http://localhost/vendor.bundle.js:94783:42)
```

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by HDaghash** [comment]
Hey guys 
any update for this issue ?

**Comment by alan-agius4** [comment]
Closing as no re-production was provided.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
