### ISSUE TITLE
ERROR TypeError: Cannot set property 'AppComponent_41' of null

### ISSUE THREAD

**Issue by mitorski** [angular/angular-cli#8467]
Hello society,

after use ng new and ng serve / npm start

i get this error, on clear app, without any line of my code. 

TypeError: Cannot set property 'AppComponent_41' of null
    at viewDef (webpack-internal:///../../../core/esm5/core.js:13397:170)
    at View_AppComponent_Host_0 (ng:///AppModule/AppComponent_Host.ngfactory.js:5:10)
    at resolveDefinition (webpack-internal:///../../../core/esm5/core.js:10045:17)
    at ComponentFactory_.create (webpack-internal:///../../../core/esm5/core.js:11153:40)
    at ApplicationRef.bootstrap (webpack-internal:///../../../core/esm5/core.js:5928:57)
    at Array.forEach (native)
    at PlatformRef._moduleDoBootstrap (webpack-internal:///../../../core/esm5/core.js:5655:44)
    at eval (webpack-internal:///../../../core/esm5/core.js:5576:27)
    at Object.onInvoke (webpack-internal:///../../../core/esm5/core.js:4824:33)
    at Zone.run (webpack-internal:///../../../../zone.js/dist/zone.js:142:43)

Angular CLI: 1.5.0
Node: 7.10.0
OS: linux x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1

What is wrong with it? I didn't see possibility to make any error here.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by mgechev** [comment]
Closing due to inactivity. Feel free to open a new issue if this is still reproducible.
