### ISSUE TITLE
ngtools/webpack: TypeError: Cannot set property writeFile of #<WebpackCompilerHost> which has only a getter

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular-cli#8473]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.
Angular CLI: 1.5.0
Node: 8.9.1
OS: darwin x64
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular-devkit/build-optimizer: 0.0.32
@ngtools/webpack: 1.8.0
typescript: 2.6.1
webpack-dev-middleware: 1.12.0
webpack-dev-server: 2.9.4
webpack-dll-bundles-plugin: 1.0.0-beta.5
webpack-merge: 4.1.0
webpack: 3.8.1

### The log given by the failure.
```
TypeError: Cannot set property writeFile of #<WebpackCompilerHost> which has only a getter
    at createSyntheticIndexHost (/Users/shlassaf/Desktop/Cisco/personal/__NPM_LIB__/ngx-modialog/packages/compiler-cli/src/metadata/bundle_index_host.ts:45:20)
    at Object.createBundleIndexHost (/Users/shlassaf/Desktop/Cisco/personal/__NPM_LIB__/ngx-modialog/packages/compiler-cli/src/metadata/bundle_index_host.ts:87:10)
    at new AngularCompilerProgram (/Users/shlassaf/Desktop/Cisco/personal/__NPM_LIB__/ngx-modialog/packages/compiler-cli/src/transformers/program.ts:78:13)
    at Object.createProgram (/Users/shlassaf/Desktop/Cisco/personal/__NPM_LIB__/ngx-modialog/packages/compiler-cli/src/transformers/program.ts:664:10)
    at Object.createProgram (/Users/shlassaf/Desktop/Cisco/personal/__NPM_LIB__/ngx-modialog/packages/compiler-cli/src/ngtools_api2.ts:135:10)
    at Promise.resolve.then (/Users/shlassaf/Desktop/Cisco/personal/__NPM_LIB__/ngx-modialog/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:220:47)
    at <anonymous>

```

When building to a flat file this exception is thrown.

The error happens [here](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/metadata/bundle_index_host.ts#L45) where this property has a getter only which is gotten from `delegate`.

`delegate` originated by ngtools/webpack with a `get` [accessor only](https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/compiler_host.ts#L268-L275).

**Comment by shlomiassaf** [comment]
@Brocco @hansl I opened this bug but frankly, I don't see any reason why one would want to create a flat module file with `@ngtools/webpack` its not the tool for that job...

Maybe a proper message should be in place

**Comment by yogeshgadge** [comment]
I am not trying to create any flat file or anything.

I am getting this error on 'ng build` by purely upgrading to angular-cli `1.5.4`

**Comment by yogeshgadge** [comment]
Seems like

`@ngtools/webpack` has ` get writeFile()` and `@angular/compiler-cli` inside `bundle_index_host.js` is trying to overwrite this read only property.

> ```
>     // This is due to typescript CompilerHost interface being weird on writeFile. This shuts down
>     // typings in WebStorm.
>     get writeFile() {
>         return (fileName, data, _writeByteOrderMark, _onError, _sourceFiles) => {
>             fileName = this.resolve(fileName);
>             this._setFileContent(fileName, data);
>         };
>     }
> ```

 `bundle_index_host.js`
> ```
> newHost.writeFile =
>         function (fileName, data, writeByteOrderMark, onError, sourceFiles) {
>             delegate.writeFile(fileName, data, writeByteOrderMark, onError, sourceFiles);
>             if (fileName.match(DTS) && sourceFiles && sourceFiles.length == 1 &&
>                 path.normalize(sourceFiles[0].fileName) == normalSyntheticIndexName) {
>                 // If we are writing the synthetic index, write the metadata along side.
>                 var metadataName = fileName.replace(DTS, '.metadata.json');
>                 fs.writeFileSync(metadataName, indexMetadata, { encoding: 'utf8' });
>             }
>         };
> ```

**Comment by yogeshgadge** [comment]
My environment

```
$ ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.4
Node: 8.4.0
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0-rc.2
@angular/cli: 1.5.4
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.0-rc.2
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.6.2
webpack: 3.8.1

```
