### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by shiliangL** [angular/angular-cli#8511]
I don't know why, i just init my project and run : ng serve 

TypeError: Cannot read property 'config' of null
    at Class.run (/Users/liangl/Angular/NG4-Day/node_modules/@angular/cli/tasks/serve.js:51:63)
    at check_port_1.checkPort.then.port (/Users/liangweishi/Angular/NG4-Day/node_modules/@angular/cli/commands/serve.js:123:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)

![image](https://user-images.githubusercontent.com/24687496/32890738-ff8098c8-cb0a-11e7-94e7-8f04243df4d5.png)

**Comment by shiliangL** [comment]
I'm sorry,I found my mistake

https://stackoverflow.com/questions/43665038/angular-cli-cannot-read-property-config-of-null
