### ISSUE TITLE
ng serve crashes after second save angular-cli 1.5.0

### ISSUE THREAD

**Issue by chandanch** [angular/angular-cli#8522]
### Versions
```
Angular CLI: 1.5.0
Node: 6.11.2
OS: win32 ia32
Angular: 5.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1

```

### Repro steps

* Step 1
update to angular-cli 1.5.0
* Step 2
run the application using `ng serve`
* Step 3
make changes and save the file. repeat this step again. observe the error on terminal and on browser console window where the application is opened

### Observed behavior

The following error is thrown on the browser console and on terminal:

```ERROR in Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:554:16)
    at AngularCompilerPlugin._updateForkedTypeChecker (G:\projects\FIVE-STAR\node_modules\@ngtools\webpack\src\angular_compiler_plugin
.js:370:34)
    at Promise.resolve.then (G:\projects\FIVE-STAR\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:208:22)
    at process._tickCallback (internal/process/next_tick.js:109:7)```

```

### Desired behavior

This error is occurring after upgrading to 1.5.0.  The `ng serve` should detect changes and should serve seamlessly without any error.

**Comment by hansl** [comment]
@filipesilva Seems related to the many `child_process` dying issues we had.

**Comment by filipesilva** [comment]
@chandanch can you try with 1.5.4 please? We had a problem with a hardcoded memory limit in https://github.com/angular/angular-cli/pull/8306 that's fixed by now.

**Comment by chandanch** [comment]
@filipesilva I just upgraded to 1.6.0-beta.2 and it no longer crashes.

**Comment by chandanch** [comment]
@filipesilva I just upgraded to 1.6.0-rc.0 and it is not crashing anymore.

**Comment by pmeems** [comment]
I updated today from v6.0.8 to v6.2.4 and I have this issue again.
On every other save the CLI crashes.

My upgrade:
![image](https://user-images.githubusercontent.com/12067729/46790835-15137d80-cd40-11e8-91d6-d4edb3ee37cc.png)

The NPM debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle myApp@0.0.2~prestart: myApp@0.0.2
6 info lifecycle myApp@0.0.2~start: myApp@0.0.2
7 verbose lifecycle myApp@0.0.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle myApp@0.0.2~start: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\dev\myApp\Src\myApp\node_modules\.bin;C:\Perl64\site\bin;C:\Perl64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Common Files\Adobe\AGL;C:\Program Files (x86)\GDAL-b\;J:\Akkerweb.Shared\GDALv2\;J:\Weather\GDALv212-64b\;D:\Program Files (x86)\Mono-3.2.3\bin\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\dev\SysInternals\;C:\Program Files (x86)\Topoprogram\Common;d:\Program Files\doxygen\bin;D:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files\dotnet\;C:\WINDOWS\System32\OpenSSH\;D:\Program Files\nodejs\;C:\Program Files (x86)\IncrediBuild;C:\Program Files (x86)\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Common Files\Adobe\AGL;D:\Program Files (x86)\Mono-3.2.3\bin\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\Program Files\Git\cmd;C:\Program Files (x86)\Topoprogram\Common;
9 verbose lifecycle myApp@0.0.2~start: CWD: D:\dev\myApp\Src\myApp
10 silly lifecycle myApp@0.0.2~start: Args: [ '/d /s /c', 'ng serve --aot --port 4250' ]
11 silly lifecycle myApp@0.0.2~start: Returned: code: 1  signal: null
12 info lifecycle myApp@0.0.2~start: Failed to exec start script
13 verbose stack Error: myApp@0.0.2 start: `ng serve --aot --port 4250`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid myApp@0.0.2
15 verbose cwd D:\dev\myApp\Src\myApp
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error myApp@0.0.2 start: `ng serve --aot --port 4250`
22 error Exit status 1
23 error Failed at the myApp@0.0.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by filipesilva** [comment]
@pmeems can you open a new issue with a reproduction please?

**Comment by pmeems** [comment]
I've created https://github.com/angular/angular-cli/issues/12553
