### ISSUE TITLE
Compiled with warnings

### ISSUE THREAD

**Issue by sayeko** [angular/angular-cli#8523]
### Versions
```
Angular CLI: 1.5.0
Node: 7.6.0
OS: win32

```

### Repro steps
ng serve --prod

### Observed behavior
app/app.module.ngfactory.js
81:9657-9672 "export 'AuthConfigs' (imported as 'i33') was not found in './config/auth.config'
    at HarmonyImportSpecifierDependency._getErrors (webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (node_modules\webpack\lib\Compiler.js:506:17)
    at node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ src/app/app.module.ngfactory.js
 @ src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 src/main.ts

### Desired behavior
Compiled with no warning,
It also no compile all the providers from different module I change my project from angular 4 to angular 5 with angular cli 1.5

**Comment by hansl** [comment]
This seems like a warning shown from `ngc`. Could you try to run `$(npm bin)/ngc -p src/tsconfig.app.json`?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
