### ISSUE TITLE
Error at ng e2e on raspberry pi

### ISSUE THREAD

**Issue by wurmrobert** [angular/angular-cli#8548]
Hy. 

I have problems running my e2e tests on a raspberry pi. I use the image  (Debian Jessie with raspberry pi desktop, Kernel Version 4.9) from the official raspberry download site.

After creating a new project with CLI Version 1.5.2:

`ng new some-project`

and run:

`ng e2e`

i get this error:

```
pi@bm-rasp-2:~/Documents/some-project $ ng e2e
** NG Live Development Server is listening on localhost:49152, open your browser on http://localhost:49152/ **
Date: 2017-11-19T12:30:49.031Z                                                          
Hash: 56daaa30edebcfdf01d8
Time: 45818ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 8.47 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 199 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.3 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.61 MB [initial] [rendered]
(node:11165) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

webpack: Compiled successfully.
[12:30:49] I/file_manager - creating folder /home/pi/Documents/some-project/node_modules/protractor/node_modules/webdriver-manager/selenium
[12:30:55] I/update - chromedriver: unzipping chromedriver_2.33.zip
[12:30:57] I/update - chromedriver: setting permissions to 0755 for /home/pi/Documents/some-project/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.33
[12:30:57] I/launcher - Running 1 instances of WebDriver
[12:30:57] I/direct - Using ChromeDriver directly...
[12:30:57] E/launcher - Server terminated early with status 2
[12:30:57] E/launcher - Error: Server terminated early with status 2
    at earlyTermination.catch.e (/home/pi/Documents/some-project/node_modules/selenium-webdriver/remote/index.js:252:52)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/pi/Documents/some-project/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/home/pi/Documents/some-project/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/home/pi/Documents/some-project/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/home/pi/Documents/some-project/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/home/pi/Documents/some-project/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/home/pi/Documents/some-project/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/pi/Documents/some-project/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/pi/Documents/some-project/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/pi/Documents/some-project/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/home/pi/Documents/some-project/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/home/pi/Documents/some-project/node_modules/protractor/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[12:30:57] E/launcher - Process exited with error code 199
```

It would be really cool if some one can help me :)

**Comment by hansl** [comment]
Hi @wurmrobert.

This seems like an error for either the WebDriver or the Protractor teams. I don't have a RPi with me here at work, so I cannot investigate, but I don't believe there's anything Angular CLI specific that we can do. I went ahead and created an issue on the Protractor repo, you can find it here: 

You can find their supported list of platforms for Selenium here (old one): http://docs.seleniumhq.org/docs/01_introducing_selenium.jsp#selenium-1-0-and-selenium-rc

I'm going to keep this issue open for now, but will mark it close if the Protractor fixes it.

Could you run `$(npm bin)/protractor`? You might need to run `$(npm bin)/webdriver-manager update` first (or maybe not).

**Comment by filipesilva** [comment]
Is Chrome installed and up to date? These type of errors are almost always Chrome related.

**Comment by wurmrobert** [comment]
@hansl Running `$(npm bin)/protractor` triggers the error. Running `$(npm bin)/webdriver-manager update` didn't´t changed anything.

@filipesilva I use the Chromium Browser Version 60.0.3112.89 and is up to date. 

Thank´s for helping me.

**Comment by hansl** [comment]
This is an issue with Protractor. I suggest you go to their repository and file an issue there. You can run protractor with the Angular CLI and reproduce the error.
