### ISSUE TITLE
Add possibility to move tsconfig.json (angular-cli.json)

### ISSUE THREAD

**Issue by serhiisol** [angular/angular-cli#862]
So basically I have problems with editor like VSCode.
It expects to have tsconfig.json at the project root directory.
And it seems like CLI skips **angular-cli.json** **tsconfig** option
When I did that I've got next problem: 

1. Mac OSX El Capitan
2. 
    angular-cli: 1.0.0-beta.4
    node: 5.7.1
    os: darwin x64
3.
    1. Move tsconfig.json to the project root directory
    2. change angular-cli.json file
    3. change configuration of tsconfig.json

4.
```
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: ENOENT: no such file or directory, open '/Users/serhiysolonko/Development/Projects/WebApp/tmp/broccoli_type_script_compiler-input_base_path-jNRnmJYp.tmp/0/src/tsconfig.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at BroccoliTypeScriptCompiler._loadTsConfig (/Users/serhiysolonko/Development/Projects/WebApp/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:123:34)
    at BroccoliTypeScriptCompiler._createServiceHost (/Users/serhiysolonko/Development/Projects/WebApp/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:158:25)
    at BroccoliTypeScriptCompiler.build (/Users/serhiysolonko/Development/Projects/WebApp/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:41:12)
    at /Users/serhiysolonko/Development/Projects/WebApp/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/serhiysolonko/Development/Projects/WebApp/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/serhiysolonko/Development/Projects/WebApp/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/serhiysolonko/Development/Projects/WebApp/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/serhiysolonko/Development/Projects/WebApp/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

5.
![screen shot 2016-05-20 at 12 57 45 pm](https://cloud.githubusercontent.com/assets/8107129/15425725/90fec6e6-1e8a-11e6-989f-b76125eba36e.png)

**Comment by filipesilva** [comment]
Do you still have this? I'm running VSCode on CLI projects and it seems to be fine. I'll reopen if it still happens to you.

**Comment by SergeySolonko** [comment]
@filipesilva moving **tsconfig.json** seems not working for me. 

1) I pulled code, master branch
2) made ```sudo npm link``` from repository folder 
3) ```npm link angular-cli``` from project folder.
4) changed ```angular-cli.json``` ```apps[].tsconfig``` option
4) ran ```ng serve```

Stack trace is the same.

Should I do something specific ?

**Comment by filipesilva** [comment]
Right you are, the location of `tsconfig.json` in `angular-cli.json` isn't being used in the build system: https://github.com/angular/angular-cli/blob/master/lib/broccoli/angular2-app.js#L320

**Comment by bang88** [comment]
Any updates ?

**Comment by samirthebti** [comment]
Any help ? !!

**Comment by serhiiso** [comment]
@filipesilva but there's an option in angular-cli.json:
```
"apps": [
    {
      "main": "src/main.ts",
      "tsconfig": "src/tsconfig.json",
      "mobile": false
    }
  ]
```

**Comment by filipesilva** [comment]
I don't think we'll be implementing this option as presented any time soon. Moving the tsconfig has serious implications in project compilation and it really should be at the root of the app.

It's perfectly valid to have a tsconfig at any depth of a project as well, and a project can have several tsconfig files. That makes me think that the problem might be related to the editor rather than the project.

There might also be other editor issues that manifest the way you are showing, for instance https://github.com/Microsoft/vscode/issues/9232 (I suffer from this one myself).
