### ISSUE TITLE
`ngc` doesn't support the correct SASS/SCSS import syntax

### ISSUE THREAD

**Issue by elliotleelewis** [angular/angular-cli#8622]
### Versions
```
Angular CLI: 1.5.4
Node: 8.9.0
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped
@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.5.3
webpack: 3.8.1

```

### Repro steps
* Create a `test.scss` file and add it to the `styleUrls` array attribute of an Angular component's decorator.
* Try and import another `scss` file (I.E. `~bootstrap/scss/variables` will import the Bootstrap 4 variables)
* Run `ngc` and point it to the component with the `scss` `styleUrl` added.

### Observed behavior
Compilation fails completely.
```
Error: Compilation failed. Resource file not found: C:/Users/elliotleelewis/Projects/angular-test/src/app/~bootstrap/scss/variables
    at ModuleResolutionHostAdapter.readResource (C:\Users\elliotleelewis\Projects\angular-test\node_modules\@angular\compiler-cli\src\compiler_host.js:386:19)
    at CompilerHost.loadResource (C:\Users\elliotleelewis\Projects\angular-test\node_modules\@angular\compiler-cli\src\compiler_host.js:249:33)
    at Object.get (C:\Users\elliotleelewis\Projects\angular-test\node_modules\@angular\compiler\bundles\compiler.umd.js:25788:107)
    at DirectiveNormalizer._fetch (C:\Users\elliotleelewis\Projects\angular-test\node_modules\@angular\compiler\bundles\compiler.umd.js:14114:43)
    at C:\Users\elliotleelewis\Projects\angular-test\node_modules\@angular\compiler\bundles\compiler.umd.js:14236:68
    at Array.map (<anonymous>)
    at DirectiveNormalizer._loadMissingExternalStylesheets (C:\Users\elliotleelewis\Projects\angular-test\node_modules\@angular\compiler\bundles\compiler.umd.js:14236:14)
    at C:\Users\elliotleelewis\Projects\angular-test\node_modules\@angular\compiler\bundles\compiler.umd.js:14239:26
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Desired behavior
Imports are loaded correctly.

**Comment by filipesilva** [comment]
Heya, this isn't the right repo to report `ngc` errors. It is published on npm under `@angular/compiler-cli`, whose repository is https://github.com/angular/angular.

But the problem you are facing is by design: `ngc` doesn't have support for anything but `.html` or `.css`.

In the CLI we use private APIs to add this support in a webpack context. The recommended general usage is to compile your CSS before using `ngc`.

You can open a feature request on https://github.com/angular/angular, but this seems to already be reported under https://github.com/angular/angular/issues/11897.

**Comment by bogacg** [comment]
@elliotleelewis Probably you've found the solution, in case anyone else falls in here for same problem here are the steps to solve:

**.angular-cli.json**
```
```

**Comment by chrillewoodz** [comment]
But compiling the SASS is impossible if they only contain variables, mixins etc. I just want to use them in the SASS file to get a certain value. What should I do?
