### ISSUE TITLE
npm serve --o problem

### ISSUE THREAD

**Issue by Itay-Arad** [angular/angular-cli#8635]
I back to my project after two weeks and I get this after I try to open my project.
any helps??

module.js:538
    throw err;
    ^

Error: Cannot find module 'rxjs/add/operator/map'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\itay\Desktop\quickstart\node_modules\@angular-devkit\core\src\logger\indent
.js:10:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by istiti** [comment]
you mean `ng serve` ? can you please run **npm install**  again (remove package.lock/node_modules folder) before

**Comment by filipesilva** [comment]
Yeah I think this is a install problem like @istiti mentioned. Running those steps should help.

**Comment by alan-agius4** [comment]
Closing as no feedback provided
