### ISSUE TITLE
ERROR in Error [ERR_IPC_CHANNEL_CLOSED]: channel closed

### ISSUE THREAD

**Issue by Sibiraj-S** [angular/angular-cli#8645]
### Versions
```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.4
Node: 8.9.1
OS: linux x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1

```

### Repro steps
I have no idea why this comes. There seems to be no error in the code. It compiles and runs perfectly, but after some time I get this. 

### Observed behavior
```
ERROR in Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at AngularCompilerPlugin._updateForkedTypeChecker (/home/sibiraj/Documents/myapp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:361:34)
    at Promise.resolve.then (/home/sibiraj/Documents/myapp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:209:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by Sibiraj-S** [comment]
closing as it is already open in #8331
