### ISSUE TITLE
No provider for RouterOutletMap

### ISSUE THREAD

**Issue by jimguistwite** [angular/angular-cli#871]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

ElCap

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 0.0.39
node: 4.0.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

ng new foo
ng generate route about
ng serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.

browser_adapter.js:86 EXCEPTION: Error in http://localhost:4200/app/foo.component.html:4:0
browser_adapter.js:77 EXCEPTION: Error in http://localhost:4200/app/foo.component.html:4:0
browser_adapter.js:77 ORIGINAL EXCEPTION: No provider for RouterOutletMap!
BrowserDomAdapter.logError	@	browser_adapter.js:77
browser_adapter.js:77 ORIGINAL STACKTRACE:
BrowserDomAdapter.logError	@	browser_adapter.js:77
browser_adapter.js:77 Error: DI Exception
    at NoProviderError.BaseException [as constructor] (exceptions.js:17)
    at NoProviderError.AbstractProviderError [as constructor] (reflective_exceptions.js:39)
    at new NoProviderError (reflective_exceptions.js:75)
    at ReflectiveInjector_._throwOrNull (reflective_injector.js:776)
    at ReflectiveInjector_._getByKeyDefault (reflective_injector.js:804)
    at ReflectiveInjector_._getByKey (reflective_injector.js:767)
    at ReflectiveInjector_.get (reflective_injector.js:576)
    at ElementInjector.get (element_injector.js:23)
    at DebugAppView._View_FooAppComponent0.createInternal (FooAppComponent.template.js:24)
    at DebugAppView.AppView.create (view.js:66)
browser_adapter.js:77 ERROR CONTEXT:
browser_adapter.js:77 
DebugContext
browser_adapter.js:86 EXCEPTION: Error in http://localhost:4200/app/foo.component.html:4:0
browser_adapter.js:77 EXCEPTION: Error in http://localhost:4200/app/foo.component.html:4:0
browser_adapter.js:77 ORIGINAL EXCEPTION: No provider for RouterOutletMap!
browser_adapter.js:77 ORIGINAL STACKTRACE:
browser_adapter.js:77 Error: DI Exception
    at NoProviderError.BaseException [as constructor] (exceptions.js:17)
    at NoProviderError.AbstractProviderError [as constructor] (reflective_exceptions.js:39)
    at new NoProviderError (reflective_exceptions.js:75)
    at ReflectiveInjector_._throwOrNull (reflective_injector.js:776)
    at ReflectiveInjector_._getByKeyDefault (reflective_injector.js:804)
    at ReflectiveInjector_._getByKey (reflective_injector.js:767)
    at ReflectiveInjector_.get (reflective_injector.js:576)
    at ElementInjector.get (element_injector.js:23)
    at DebugAppView._View_FooAppComponent0.createInternal (FooAppComponent.template.js:24)
    at DebugAppView.AppView.create (view.js:66)
browser_adapter.js:77 ERROR CONTEXT:
browser_adapter.js:77 
DebugContext
browser_adapter.js:86 EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in http://localhost:4200/app/foo.component.html:4:0
ORIGINAL EXCEPTION: No provider for RouterOutletMap!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:4200/vendor/@angular/core/src/facade/exceptions.js:17:23)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4200/vendor/@angular/core/src/di/reflective_exceptions.js:39:16)
    at new NoProviderError (http://localhost:4200/vendor/@angular/core/src/di/reflective_exceptions.js:75:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:776:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:804:25)
    at ReflectiveInjector_._getByKey (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:767:25)
    at ReflectiveInjector_.get (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:576:21)
    at ElementInjector.get (http://localhost:4200/vendor/@angular/core/src/linker/element_injector.js:23:48)
    at DebugAppView._View_FooAppComponent0.createInternal (FooAppComponent.template.js:24:70)
    at DebugAppView.AppView.create (http://localhost:4200/vendor/@angular/core/src/linker/view.js:66:21)
ERROR CONTEXT:
[object Object]
﻿

**Comment by jimguistwite** [comment]
To work around the issue, manually added the following to my component:
  providers: [ROUTER_PROVIDERS]

**Comment by hansl** [comment]
Try upgrading to the latest version (1.0.0-beta.5). Cheers.
