### ISSUE TITLE
Error encountered resolving symbol values statically. Expression form not supported (position 3:33 in the original .ts file)

### ISSUE THREAD

**Issue by jvkiran** [angular/angular-cli#8742]
In app.routes, we specified a function isMobile(), which returns boolean value, based on device,
lets say if mobile device returns true, desktop returns false, 

I used isMobile() fun as ternary operator for loading compoents

Ex: { path: 'invitations', component: (isMobile()? MobileHomePageComponent : HomePageComponent) }

so following error occurs.

ERROR in Error: Error encountered resolving symbol values statically. Expression form not supported (position 3:33 in the original .ts file), resolving symbol isMobile in /home/gtcoder/Sites/cardlove-api/ng-cardlove/src/app/helpers/isMobile.ts, resolving symbol appRoutes in /home/gtcoder/Sites/cardlove-api/ng-cardlove/src/app/app.routes.ts, resolving symbol appRoutes in /home/gtcoder/Sites/cardlove-api/ng-cardlove/src/app/app.routes.ts, resolving symbol AppModule in /home/gtcoder/Sites/cardlove-api/ng-cardlove/src/app/app.module.ts, resolving symbol AppModule in /home/gtcoder/Sites/cardlove-api/ng-cardlove/src/app/app.module.ts
    at positionalError (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@angular/compiler/bundles/compiler.umd.js:25104:35)
    at simplifyInContext (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@angular/compiler/bundles/compiler.umd.js:24947:27)
    at StaticReflector.simplify (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@angular/compiler/bundles/compiler.umd.js:24961:13)
    at StaticReflector.annotations (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@angular/compiler/bundles/compiler.umd.js:24391:41)
    at _getNgModuleMetadata (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/gtcoder/Sites/cardlove-api/ng-cardlove/node_modules/@ngtools/webpack/src/plugin.js:443:24)

project version

@angular/cli: 1.4.2
node: 7.10.1
os: linux x64
@angular/animations: 4.3.6
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6
@angular/http: 4.3.6
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.4.2
@angular/compiler-cli: 4.3.6
typescript: 2.3.2

**Comment by clydin** [comment]
Hello, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

Angular CLI always runs *some* statical analysis, even on JIT mode, in order to discover lazy-loaded routes.
This may cause a large number of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Below are good resources on how to to debug these errors:
- https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60
- https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts

If your problem still persists, it might be a bug with the Angular Compiler itself.
In that case, please open an issue in https://github.com/angular/angular.
