### ISSUE TITLE
Cannot read property 'glob' of null

### ISSUE THREAD

**Issue by chetanbncoe** [angular/angular-cli#8795]
### Versions: Linux fedora 25

@angular/cli: 1.1.1

### Repro steps
```
error:

TypeError: Cannot read property 'glob' of null
    at ObjectSchemaTreeNode._set (/home/chetan/angular/wms28/node_modules/@ngtools/json-schema/src/schema-tree.js:226:131)
    at new ObjectSchemaTreeNode (/home/chetan/angular/wms28/node_modules/@ngtools/json-schema/src/schema-tree.js:211:14)
    at OneOfSchemaTreeNode._createChildProperty (/home/chetan/angular/wms28/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at OneOfSchemaTreeNode._typesPrototype.schema.oneOf.map (/home/chetan/angular/wms28/node_modules/@ngtools/json-schema/src/schema-tree.js:163:25)
    at Array.map (native)
    at OneOfSchemaTreeNode (/home/chetan/angular/wms28/node_modules/@ngtools/json-schema/src/schema-tree.js:162:48)
    at ArraySchemaTreeNode._createChildProperty (/home/chetan/angular/wms28/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
    at ArraySchemaTreeNode._set (/home/chetan/angular/wms28/node_modules/@ngtools/json-schema/src/schema-tree.js:288:39)
    at new ArraySchemaTreeNode (/home/chetan/angular/wms28/node_modules/@ngtools/json-schema/src/schema-tree.js:269:14)
    at ObjectSchemaTreeNode._createChildProperty (/home/chetan/angular/wms28/node_modules/@ngtools/json-schema/src/schema-tree.js:150:26)
```

### Observed behavior

on command npm start i got above error.
when i start through root user..it's works
so kindly help.

**Comment by Brocco** [comment]
Are you able to share your project or provide a sample repo that shows this behavior?

This version of the CLI is almost 6 months old, are you able to update your project to the latest version of the CLI?

**Comment by magentall** [comment]
verify that u own the directrory (" chown groupe:user directory " on ubuntu) and try root launch for the ng (sudo)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
