### ISSUE TITLE
Confusing error when route's matcher is not exported

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular-cli#8801]
### Versions
```
Angular CLI: 1.5.0
Node: 8.2.1
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular/platform-server: 5.0.0-rc.8
@angular/service-worker: 1.0.0-beta.16
@angular-devkit/build-optimizer: 0.0.31
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps

Use a matcher which is not an exported function.

```
// dummy matcher
function matcher() { return null }

const routes = [
  { matcher, loadChildren: 'a/valid/path#GoesHere' }
]
```

### Observed behavior
```
ERROR in TypeError: Cannot read property 'loadChildren' of undefined
    at _collectLoadChildren (.../node_modules/@angular/compiler/bundles/compiler.umd.js:28561:20)
    at listLazyRoutes (.../node_modules/@angular/compiler/bundles/compiler.umd.js:28536:49)
    at visitLazyRoute (.../node_modules/@angular/compiler/bundles/compiler.umd.js:29937:47)
    at AotCompiler.listLazyRoutes (.../node_modules/@angular/compiler/bundles/compiler.umd.js:29905:20)
    at AngularCompilerProgram.listLazyRoutes (.../node_modules/@angular/compiler-cli/src/transformers/program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (.../node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (.../node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:246:66)
    at Promise.resolve.then.then (.../node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:542:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

### Desired behavior

A non-cryptic error message, like the usual AOT one about "consider replacing lambda with an exported function" or whatever it was.

**Comment by Brocco** [comment]
I believe this error message has been improved in version 1.6.

@hansl Can you please confirm?

**Comment by arlowhite** [comment]
@Brocco I updated to 1.6.5 and still get the same error when using `matcher` in a lazy-loaded route module.

```
ERROR in TypeError: Cannot read property 'loadChildren' of undefined
    at _collectLoadChildren (/home/whitea/Code/boost_dashboard/node_modules/@angular/compiler/bundles/compiler.umd.js:29027:21)
    at listLazyRoutes (/home/whitea/Code/boost_dashboard/node_modules/@angular/compiler/bundles/compiler.umd.js:29002:49)
    at visitLazyRoute (/home/whitea/Code/boost_dashboard/node_modules/@angular/compiler/bundles/compiler.umd.js:31169:47)
    at visitLazyRoute (/home/whitea/Code/boost_dashboard/node_modules/@angular/compiler/bundles/compiler.umd.js:31173:17)
    at AotCompiler.listLazyRoutes (/home/whitea/Code/boost_dashboard/node_modules/@angular/compiler/bundles/compiler.umd.js:31137:20)
    at AngularCompilerProgram.listLazyRoutes (/home/whitea/Code/boost_dashboard/node_modules/@angular/compiler-cli/src/transformers/program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/whitea/Code/boost_dashboard/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/home/whitea/Code/boost_dashboard/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:248:66)
    at Promise.resolve.then.then (/home/whitea/Code/boost_dashboard/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:565:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by arlowhite** [comment]
@lazarljubenovic exporting my `UrlMatcher` function fixed the error, thanks!

**Comment by waterplea** [comment]
Spent quit a lot of time removing one thing after another after another today, until I finally realized it was happening because I did not export my matcher.

**Comment by FDIM** [comment]
Issue still stands for angular cli 7.2.1
