### ISSUE TITLE
Need Help. Error while yarn start.

### ISSUE THREAD

**Issue by mritunjaygoutam12** [angular/angular-cli#8803]
### Versions
```
<!--
`ng --version`:
Angular CLI: 1.6.0
Node: 6.12.1
OS: linux x64
Angular: 
-->
```
### ERROR 
```
WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js
[1] 54:11-36 Critical dependency: the request of a dependency is an expression
[1]     at ImportLazyContextDependency.getWarnings (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
[1]     at Compilation.reportDependencyErrorsAndWarnings (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compilation.js:677:24)
[1]     at Compilation.finish (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compilation.js:535:9)
[1]     at applyPluginsParallel.err (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compiler.js:512:17)
[1]     at /home/mohit/Rocket.Chat.PWA/node_modules/tapable/lib/Tapable.js:289:11
[1]     at _addModuleChain (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compilation.js:481:11)
[1]     at processModuleDependencies.err (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compilation.js:452:13)
[1]     at _combinedTickCallback (internal/process/next_tick.js:73:7)
[1]     at process._tickCallback (internal/process/next_tick.js:104:9)
[1] 
[1] WARNING in ./node_modules/ionic-angular/util/ng-module-loader.js
[1] 69:11-36 Critical dependency: the request of a dependency is an expression
[1]     at ImportLazyContextDependency.getWarnings (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
[1]     at Compilation.reportDependencyErrorsAndWarnings (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compilation.js:677:24)
[1]     at Compilation.finish (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compilation.js:535:9)
[1]     at applyPluginsParallel.err (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compiler.js:512:17)
[1]     at /home/mohit/Rocket.Chat.PWA/node_modules/tapable/lib/Tapable.js:289:11
[1]     at _addModuleChain (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compilation.js:481:11)
[1]     at processModuleDependencies.err (/home/mohit/Rocket.Chat.PWA/node_modules/webpack/lib/Compilation.js:452:13)
[1]     at _combinedTickCallback (internal/process/next_tick.js:73:7)
[1]     at process._tickCallback (internal/process/next_tick.js:104:9)
[1] 
[1] webpack: Compiled with warnings.

```

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
