### ISSUE TITLE
Error ng-build or ng-serve

### ISSUE THREAD

**Issue by neutron92** [angular/angular-cli#8815]
RROR in Error: Metadata version mismatch for module /home/ubuntu/workspace/******/node_modules/@ng-bootstrap/ng-bootstrap/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/ubuntu/workspace/******/src/app/app.module.ts, resolving symbol AppModule in /home/ubuntu/workspace/******/src/app/app.module.ts, resolving symbol AppModule in /home/ubuntu/workspace/******/src/app/app.module.ts

**Comment by neutron92** [comment]
ERROR in Error: Metadata version mismatch for module /home/ubuntu/workspace/******/node_modules/@ng-bootstrap/ng-bootstrap/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/ubuntu/workspace/******/src/app/app.module.ts, resolving symbol AppModule in /home/ubuntu/workspace/******/src/app/app.module.ts, resolving symbol AppModule in /home/ubuntu/workspace/***********/src/app/app.module.ts
    at Error (native)
    at syntaxError (/home/ubuntu/workspace/******/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/ubuntu/workspace/******/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/home/ubuntu/workspace/******/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/home/ubuntu/workspace/******/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/home/ubuntu/workspace/******/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/ubuntu/workspace/******/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/ubuntu/workspace/******/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/ubuntu/workspace/******/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/ubuntu/workspace/******/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/ubuntu/workspace/******/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by Brocco** [comment]
Please either update this issue or create a new issue following the new issue template. This will allow us to triage and resolve your issues/requests quickly. 

Please ensure to include information about your project that will allow the team to recreate your issue.

Thank you!
