### ISSUE TITLE
New ng project fails tests

### ISSUE THREAD

**Issue by lebsral** [angular/angular-cli#8818]
### Versions
```
Angular CLI: 1.6.0
Node: 8.9.3
OS: darwin x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps
ng new globe
cd globe
ng test

### Observed behavior
```
$ ng test
 10% building modules 1/1 modules 0 active09 12 2017 13:36:01.555:WARN [karma]: No captured browser, open http://localhost:9876/
09 12 2017 13:36:01.563:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
09 12 2017 13:36:01.563:INFO [launcher]: Launching browser Chrome with unlimited concurrency
09 12 2017 13:36:01.569:INFO [launcher]: Starting browser Chrome
09 12 2017 13:36:06.655:WARN [karma]: No captured browser, open http://localhost:9876/  
09 12 2017 13:36:08.746:INFO [Chrome 40.0.2214 (Mac OS X 10.12.6)]: Connected on socket nELkFE6CyE-rhZc9AAAA with id 37702350
Chrome 40.0.2214 (Mac OS X 10.12.6) AppComponent should create the app FAILED
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34103:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:260:1)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:341:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:960:1)
	    at Function.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:776:18)
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34092:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:243:26)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:328:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed._initIfNeeded Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:973:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed.createComponent Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:1125:1)
Chrome 40.0.2214 (Mac OS X 10.12.6): Executed 1 of 3 (1 FAILED) (0 secs / 0.024 secs)
Chrome 40.0.2214 (Mac OS X 10.12.6) AppComponent should create the app FAILED
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34103:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:260:1)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:341:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:960:1)
	    at Function.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:776:18)
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34092:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:243:26)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:328:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed._initIfNeeded Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:973:1)
Chrome 40.0.2214 (Mac OS X 10.12.6) AppComponent should have as title 'app' FAILED
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34103:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:260:1)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:341:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:960:1)
	    at Function.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:776:18)
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34092:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:243:26)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:328:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed._initIfNeeded Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:973:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed.createComponent Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:1125:1)
Chrome 40.0.2214 (Mac OS X 10.12.6): Executed 2 of 3 (2 FAILED) (0 secs / 0.049 secs)
Chrome 40.0.2214 (Mac OS X 10.12.6) AppComponent should have as title 'app' FAILED
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34103:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:260:1)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:341:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:960:1)
	    at Function.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:776:18)
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34092:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:243:26)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:328:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed._initIfNeeded Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:973:1)
Chrome 40.0.2214 (Mac OS X 10.12.6) AppComponent should render title in a h1 tag FAILED
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34103:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:260:1)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:341:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:960:1)
	    at Function.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:776:18)
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34092:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:243:26)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:328:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed._initIfNeeded Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:973:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed.createComponent Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:1125:1)
Chrome 40.0.2214 (Mac OS X 10.12.6): Executed 3 of 3 (3 FAILED) (0 secs / 0.062 secs)
Chrome 40.0.2214 (Mac OS X 10.12.6) AppComponent should render title in a h1 tag FAILED
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34103:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:260:1)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsAsync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:341:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:960:1)
	    at Function.webpackJsonp.../../../core/esm5/testing.js.TestBed.compileComponents Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:776:18)
	Failed: undefined is not a function
	TypeError: undefined is not a function
	    at dedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15978:1)
	    at flattenAndDedupeArray Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15987:1)
	    at CompileMetadataResolver.webpackJsonp.../../../compiler/esm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:15189:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._loadModules Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34226:58)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34204:1)
	    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/compiler/esm5/compiler.js:34092:1)
	    at CompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/platform-browser-dynamic.js:243:26)
	    at TestingCompilerImpl.webpackJsonp.../../../platform-browser-dynamic/esm5/testing.js.TestingCompilerImpl.compileModuleAndAllComponentsSync Users/lars/mycode/globe/node_modules/@angular/platform-browser-dynamic/esm5/testing.js:328:1)
	    at TestBed.webpackJsonp.../../../core/esm5/testing.js.TestBed._initIfNeeded Users/lars/mycode/globe/node_modules/@angular/core/esm5/testing.js:973:1)
Chrome 40.0.2214 (Mac OS X 10.12.6): Executed 3 of 3 (3 FAILED) ERROR (0.169 secs / 0.062 secs)
```

### Desired behavior
Tests that pass out of the box

### Mention any other details that might be useful (optional)
Other commands like ng build and ng serve work just fine.
I've tried reinstalling cli, reinstalled node, removed all of npm and reinstalled it again, and updated xcode.  Then created a new project and had the same results.

**Comment by Brocco** [comment]
This looks like you had some issues during npm install... can you please delete your node_modules and re-run `ng test`?

If this works, please close the issue.
If this does not work, please share the project's repo on github.

**Comment by lebsral** [comment]
Deleting node_modules and lock file and doing npm i gives the output below.  Which is starting to smell like xcode.

```
$ npm i

> fsevents@1.1.3 install /Users/lars/mycode/globe/node_modules/fsevents
> node install

[fsevents] Success: "/Users/lars/mycode/globe/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.7.2 install /Users/lars/mycode/globe/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/lars/.npm/node-sass/4.7.2/darwin-x64-57_binding.node

> phantomjs-prebuilt@2.1.16 install /Users/lars/mycode/globe/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/q3/2p8p47mj6_70b5dm2lcqjqg80000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/lars/mycode/globe/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/q3/2p8p47mj6_70b5dm2lcqjqg80000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1513047429349/phantomjs-2.1.1-macosx -> /Users/lars/mycode/globe/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/lars/mycode/globe/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/lars/mycode/globe/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall /Users/lars/mycode/globe/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/lars/mycode/globe/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @schematics/angular@0.1.10 requires a peer of @angular-devkit/schematics@0.0.40 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/schematics@0.0.10 requires a peer of @angular-devkit/schematics@0.0.40 but none is installed. You must install peer dependencies yourself.

added 1166 packages in 25.137s
```

**Comment by lebsral** [comment]
I'll reopen with a solution if it ends up being cli related.
