### ISSUE TITLE
Angular Cli 1.6.0 does not download Rxjs dependency

### ISSUE THREAD

**Issue by prasadmamidi7** [angular/angular-cli#8835]
Angular CLI 1.6.0 does not download Rxjs dependency
### Versions
```


Angular CLI: 1.6.0
Node: 8.9.2
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.6.2
webpack: 3.10.0

```

### Repro steps
-  Install NPM
- npm install -g @angular/cli@1.6.0
- create a ng app using ng command
- ng build --prod

### Observed behavior
```
Error: Cannot find module 'rxjs/add/operator/map'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (xxxxxxxxxx\xxxxx\xxxxx\node_modules\@angular-devkit\core\src\logger\indent.js:10:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

```

**Comment by arjunyel** [comment]
Import should be: import { map } from 'rxjs/operators';

https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md

**Comment by Brocco** [comment]
If this is a project you've done development on as @arjunyel suggested, follow the suggestions above.

If this is a brand new project, I suggest you reinstall your dependencies by deleting the node_modules folder and running `npm install`

If this issue is still present, please post the repo to github, including a link here. If this solves your issue, please close this issue.
