### ISSUE TITLE
ERROR in Error: Illegal state: symbol without members expected

### ISSUE THREAD

**Issue by PascalTemel** [angular/angular-cli#8837]
### Versions
```
Angular CLI: 1.6.0
Node: 8.4.0
OS: linux x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.6.0
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.5.3
webpack: 3.7.1
```

### Repro steps
Running `ng serve --aot` in our angular-cli project and modifying files after compilation is complete
Unfortunately I cannot provide a plunkr or reproduction project since this happens in my company's production app.

### Observed behavior
```
ERROR in Error: Illegal state: symbol without members expected, but got {"filePath":"/home/ptemel/GUICLI/node_modules/tslint/lib/index.d.ts","name":"Rules","members":["AbstractRule"]}.
    at StaticSymbol.assertNoMembers (/home/ptemel/GUICLI/node_modules/@angular/compiler/bundles/compiler.umd.js:1444:19)
    at AotSummaryResolver.resolveSummary (/home/ptemel/GUICLI/node_modules/@angular/compiler/bundles/compiler.umd.js:32640:22)
    at StaticReflector.annotations (/home/ptemel/GUICLI/node_modules/@angular/compiler/bundles/compiler.umd.js:31570:69)
    at DirectiveResolver.isDirective (/home/ptemel/GUICLI/node_modules/@angular/compiler/bundles/compiler.umd.js:3552:61)
    at CompileMetadataResolver.isDirective (/home/ptemel/GUICLI/node_modules/@angular/compiler/bundles/compiler.umd.js:15122:37)
    at /home/ptemel/GUICLI/node_modules/@angular/compiler/bundles/compiler.umd.js:31203:38
    at Array.forEach (<anonymous>)
    at analyzeFile (/home/ptemel/GUICLI/node_modules/@angular/compiler/bundles/compiler.umd.js:31195:53)
    at AotCompiler._analyzeFile (/home/ptemel/GUICLI/node_modules/@angular/compiler/bundles/compiler.umd.js:30396:17)
    at AotCompiler.findGeneratedFileNames (/home/ptemel/GUICLI/node_modules/@angular/compiler/bundles/compiler.umd.js:30412:42)
    at Object.findGeneratedFileNames (/home/ptemel/GUICLI/node_modules/@angular/compiler-cli/src/transformers/program.js:393:82)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (/home/ptemel/GUICLI/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:337:55)
    at findSourceFile (/home/ptemel/GUICLI/node_modules/typescript/lib/typescript.js:70782:29)
    at args (/home/ptemel/GUICLI/node_modules/typescript/lib/typescript.js:70719:85)
    at getSourceFileFromReferenceWorker (/home/ptemel/GUICLI/node_modules/typescript/lib/typescript.js:70692:34)
    at processSourceFile (/home/ptemel/GUICLI/node_modules/typescript/lib/typescript.js:70719:13)
    at processRootFile (/home/ptemel/GUICLI/node_modules/typescript/lib/typescript.js:70573:13)
    at /home/ptemel/GUICLI/node_modules/typescript/lib/typescript.js:69765:60
    at Object.forEach (/home/ptemel/GUICLI/node_modules/typescript/lib/typescript.js:1500:30)
    at Object.createProgram (/home/ptemel/GUICLI/node_modules/typescript/lib/typescript.js:69765:16)
    at AngularCompilerProgram._createProgramWithBasicStubs (/home/ptemel/GUICLI/node_modules/@angular/compiler-cli/src/transformers/program.js:431:29)
    at /home/ptemel/GUICLI/node_modules/@angular/compiler-cli/src/transformers/program.js:143:28
```

### Desired behavior
This error should not occour

### Mention any other details that might be useful (optional)
This does not happen consistently, which makes this so hard to debug for me. Sometimes it recompiles fine without any errors, but usually the error is thrown. Usually the first `ng serve --aot` run will compile fine and then sometimes it continues with another compilation process which throws the error, even though no files were changed.

**Comment by PascalTemel** [comment]
I was able to resolve this issue by deleting custom tslint rule files that were present in the project's directory. However, I would still like to know why this error only happens occasionally. This seems like a bug to me.

**Comment by tiaguinho** [comment]
I had similar errors when I was using CLI 1.x. After I update my projects to Angular 7, this errors never happened again.

Can you confirm @PascalTemel ?
