### ISSUE TITLE
WARNING in ./node_modules/@angular/core/esm5/core.js

### ISSUE THREAD

**Issue by ileler** [angular/angular-cli#8857]
### Versions
```
$ ng -v
_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ â³ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.5.4
Node: 6.10.0
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.8.1

```

### Repro steps

* ng new 
* npm i
* `vi .angular-cli.json` append:
```
"defaults": {
    "styleExt": "css",
    "component": {
    },
    "build": {
      "preserveSymlinks": true
    }
  }
```
* npm start

### Observed behavior
```
$ cnpm start

> ng-test@0.0.0 start U:\u~u\a0a\ws\tl\publisher\ng-test
> ng serve

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-12-13T06:10:56.140Z
Hash: f7b2ab3cfa04b46f8e22
Time: 20619ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 22.1 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 574 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 35.9 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 7.24 MB [initial] [rendered]

WARNING in ./node_modules/@angular/core/esm5/core.js
6586:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compilation.js:703:24)
    at Compilation.finish (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compiler.js:506:17)
    at I:\a0a\ws\tl\publisher\ng-test\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:289:11
    at _addModuleChain (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/@angular/core/esm5/core.js
6606:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compilation.js:703:24)
    at Compilation.finish (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compiler.js:506:17)
    at I:\a0a\ws\tl\publisher\ng-test\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:289:11
    at _addModuleChain (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (I:\a0a\ws\tl\publisher\ng-test\node_modules\_webpack@3.8.1@webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Compiled with warnings.
```

### Desired behavior

https://github.com/angular/angular/issues/11580#issuecomment-246880731
https://github.com/angular/angular/issues/20357

**Comment by clydin** [comment]
The CLI has been updated significantly since version 1.5.4.  The current stable version is 8.3.5.  If this problem is still being encountered with the current version, please consider opening a new issue with updated details.
