### ISSUE TITLE
ng build -prod error

### ISSUE THREAD

**Issue by xiaohuoni** [angular/angular-cli#8859]
Angular CLI: 1.5.3
Node: 8.9.1
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0
@angular/cli: 1.5.3
: 0.0.35
: 0.0.22
: 0.0.41
: 1.1.0
: 1.8.3
: 0.1.10
: 0.0.10
typescript: 2.4.2
webpack: 3.8.1

npm use cnpm

run ng build -prod error

error ：
95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open 'D:\td-share-ng\node_modules_@angular_core@5.1.0@@angular\package.json'
at Object.fs.openSync (fs.js:646:18)
at Object.fs.readFileSync (fs.js:551:33)
at LicenseExtractor.readPackageJson (D:\td-share-ng\node_modules_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:124:23)
at LicenseExtractor.parsePackage (D:\td-share-ng\node_modules_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:21:32)
at ModuleProcessor.processPackage (D:\td-share-ng\node_modules_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:24:46)
at ModuleProcessor.processFile (D:\td-share-ng\node_modules_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:21:21)
at moduleCallback (D:\td-share-ng\node_modules_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:80:61)
at Set.forEach ()
at Chunk.forEachModule (D:\td-share-ng\node_modules_webpack@3.8.1@webpack\lib\Chunk.js:159:17)
at D:\td-share-ng\node_modules_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:89:27
at Array.forEach ()
at Compiler. (D:\td-share-ng\node_modules_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:65:32)
at next (D:\td-share-ng\node_modules_tapable@0.2.8@tapable\lib\Tapable.js:204:14)
at D:\td-share-ng\node_modules_html-webpack-plugin@2.30.1@html-webpack-plugin\index.js:204:9
at PassThroughHandlerContext.finallyHandler (D:\td-share-ng\node_modules_bluebird@3.5.1@bluebird\js\release\finally.js:56:23)
at PassThroughHandlerContext.tryCatcher (D:\td-share-ng\node_modules_bluebird@3.5.1@bluebird\js\release\util.js:16:23)

Can't visit stackoverflow in China ，Thanks！

**Comment by Brocco** [comment]
I believe this issue has been resolved in a later version. Can you please update to the latest version of the CLI (currently 1.6.1) and retry.

This seems like a support issue, if you're unable to access stackoverflow, you could try to get some help via gitter.

**Comment by xiaohuoni** [comment]
thank you
