### ISSUE TITLE
can't server project

### ISSUE THREAD

**Issue by houssemzaier** [angular/angular-cli#886]
> Here is the  following informations:
> ---------------------------------------------------------------
1. OS?  Windows   10. 

2. ng --version
angular-cli: 1.0.0-beta.5
node: 5.10.1
os: win32 x64

3. Just used the serve command after new command. 

4. The log given by the failure.;
D:\projects\angular2\MRIGUEL\starter-template\public\xccc (master) (xccc@0.0.0)
λ ng serve

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: EPERM: operation not permitted, symlink 'D:\projects\angular2\MRIGUEL\starter-template\public\xccc\tmp\broccoli_type_script_compiler-cache_path-ItOQSrV5.tmp\src\app\environment.js.map' -> 'D:\projects\angular2\MRIGUEL\starter-template\public\xccc\tmp\broccoli_type_script_compiler-output_path-AfkAbBhc.tmp\src\app\environment.js.map'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at BroccoliTypeScriptCompiler._outputFile (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:206:8)
    at D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:108:18
    at Array.forEach (native)
    at D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:107:30
    at Array.forEach (native)
    at BroccoliTypeScriptCompiler._doIncrementalBuild (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:93:19)
    at BroccoliTypeScriptCompiler.build (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:26:49)
    at Angular2App._getTsTree (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\lib\broccoli\angular2-app.js:321:18)
    at Angular2App._buildTree (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\lib\broccoli\angular2-app.js:116:23)
    at new Angular2App (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (D:\projects\angular2\MRIGUEL\starter-template\public\xccc\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. just  to try the cli angular2 tool, I need to build my apps and generate js files to host them on firebase. 
Any help please ...

**Comment by delasteve** [comment]
Could you post your `tsconfig.json` and `angular-cli-build.json`?

**Comment by monojack** [comment]
Hey! You are serving without elevated rights. Basically, you need to run `ng serve` from inside a command prompt with admin privileges otherwise it fails on windows.
For more info, refer to #641

**Comment by houssemzaier** [comment]
Thank you all for helping me ,
I had to Run the Command Prompt as Admin !
now this works all good. 
thanks again

**Comment by reflexdemon** [comment]
@monojack I dont have admin rights on my workstation. I am waiting for #905 to be merged.
