### ISSUE TITLE
ng commands fail, with EPREM error message

### ISSUE THREAD

**Issue by PHuhn** [angular/angular-cli#8893]
### Versions
All ng commands fail including ng --version 
From my package.json:

> "@angular/cli": "^1.6.1",

My package.json is as follows:

> {
>   "name": "net-incident",
>   "version": "0.0.1",
>   "license": "MIT",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "build": "ng build",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "^5.1.1",
>     "@angular/cli": "^1.6.1",
>     "@angular/common": "^5.1.1",
>     "@angular/compiler": "^5.1.1",
>     "@angular/compiler-cli": "^5.1.1",
>     "@angular/core": "^5.1.1",
>     "@angular/forms": "^5.1.1",
>     "@angular/http": "^5.1.1",
>     "@angular/platform-browser": "^5.1.1",
>     "@angular/platform-browser-dynamic": "^5.1.1",
>     "@angular/platform-server": "^5.1.1",
>     "@angular/router": "^5.1.1",
>     "core-js": "^2.4.1",
>     "font-awesome": "^4.7.0",
>     "rxjs": "^5.5.5",
>     "webpack": "^3.10.0",
>     "zone.js": "^0.8.18"
>   },
>   "devDependencies": {
>     "@angular/language-service": "^5.1.0",
>     "@types/jasmine": "~2.5.53",
>     "@types/jasminewd2": "~2.0.2",
>     "@types/node": "~6.0.60",
>     "codelyzer": "~3.0.1",
>     "jasmine-core": "~2.6.2",
>     "jasmine-spec-reporter": "~4.1.0",
>     "karma": "~1.7.0",
>     "karma-chrome-launcher": "~2.1.1",
>     "karma-cli": "~1.0.1",
>     "karma-coverage-istanbul-reporter": "^1.2.1",
>     "karma-jasmine": "^1.1.1",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "primeng": "^5.0.2",
>     "protractor": "~5.1.2",
>     "ts-node": "~3.0.4",
>     "tslint": "~5.3.2",
>     "typescript": "^2.6.2"
>   }
> }
> 

### Repro steps
This was done on a Windows 10 computer.
I had a functioning CLI project.  I did an **_npm update_** and now all ng commands the following all fail with the same message:
> ng serve
> ng build
> ng test
> ng lint
> ng --version

The error message is the following:

> C:\Dat\Nsg\L\Web\Ng\net-incident>ng --version
> fs.js:1649
>       binding.lstat(baseLong);
>               ^
> 
> Error: EPERM: operation not permitted, lstat 'C:\Users\Phillip'
>     at Object.realpathSync (fs.js:1649:15)
>     at toRealPath (module.js:156:13)
>     at Function.Module._findPath (module.js:205:22)
>     at Function.Module._resolveFilename (module.js:534:25)
>     at Function.Module._load (module.js:466:25)
>     at Function.Module.runMain (module.js:676:10)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3

### Observed behavior
The line 

>   Error: EPERM: operation not permitted, lstat 'C:\Users\Phillip'

indicates it is looking in another user account that it does not have permissions to.

### Desired behavior
I would like to run my test and server locally.

### Mention any other details that might be useful (optional)
I am running
**ng serve**
from the other account and that works.  But I can't see the output as I develop.

**Comment by PHuhn** [comment]
I found it.  The %PATH% variable had a hard coded appdata\roaming\npm path.  I changed it to %USERPROFILE%, and reopened the command prompt and it was fine.
