### ISSUE TITLE
ng build fails when using mongoDb

### ISSUE THREAD

**Issue by sdeniaud33** [angular/angular-cli#8969]
Hi, I can't manage to make MongoDb work with an Angular App. As soon as I had refs to mongodb in my package.json + npm install + add anything related to Mongo in the code the ng build starts to fail.
I first have warnings, sth like : 
```
WARNING in ./node_modules/require_optional/index.js
82:18-42 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\Perso\dev\testAngular\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)

```

then an error : (see below for full stack trace)
```
ERROR in ./node_modules/require_optional/node_modules/resolve-from/index.js
Module not found: Error: Can't resolve 'module' in 'C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\resolve-from'
resolve 'module' in 'C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\resolve-from'

```
### Versions

```
Angular CLI: 1.6.2
Node: 6.9.1
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

- create an Angular app : ng new testAngular
- check the app : ng serve -> everything is OK
- update the package.json to reference mongoDb : 

 
```
{
 	"name": "test-angular",
 	"version": "0.0.0",
 	"license": "MIT",
 	"scripts": {
		"ng": "ng",
		"start": "ng serve",
		"build": "ng build --prod",
		"test": "ng test",
		"lint": "ng lint",
		"e2e": "ng e2e"
	},
	"private": true,
	"dependencies": {
		"@angular/animations": "^5.0.0",
		"@angular/common": "^5.0.0",
		"@angular/compiler": "^5.0.0",
		"@angular/core": "^5.0.0",
		"@angular/forms": "^5.0.0",
		"@angular/http": "^5.0.0",
		"@types/mongodb": "^2.2.17",
		"@angular/platform-browser": "^5.0.0",
		"@angular/platform-browser-dynamic": "^5.0.0",
		"@angular/router": "^5.0.0",
		"core-js": "^2.4.1",
		"rxjs": "^5.5.2",
		"zone.js": "^0.8.14"
	},
	"devDependencies": {
		"@angular/cli": "1.6.2",
		"@angular/compiler-cli": "^5.0.0",
		"@angular/language-service": "^5.0.0",
		"@types/jasmine": "~2.5.53",
		"@types/jasminewd2": "~2.0.2",
		"@types/node": "~6.0.60",
		"codelyzer": "^4.0.1",
		"jasmine-core": "~2.6.2",
		"jasmine-spec-reporter": "~4.1.0",
		"karma": "~1.7.0",
		"mongodb": "^3.0.0-rc0",
		"karma-chrome-launcher": "~2.1.1",
		"karma-cli": "~1.0.1",
		"karma-coverage-istanbul-reporter": "^1.2.1",
		"karma-jasmine": "~1.1.0",
		"karma-jasmine-html-reporter": "^0.2.2",
		"protractor": "~5.1.2",
		"ts-node": "~3.2.0",
		"tslint": "~5.7.0",
		"typescript": "~2.4.2"
	}
}

```

- Run npm install
- Add a reference to Mongo in the code, for instance in the src\main.ts file : 

```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { MongoClient, Db } from 'mongodb';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

MongoClient.connect("mongodb://localhost:27017", function (err: any, client: Db) {
	console.log("Connected");
});
```
- run ng build (or ng serve)

### Observed behavior
The Angular application can no longer be built : full output is : 

```
C:\Perso\dev\testAngular>ng build
Date: 2017-12-22T08:52:29.477Z
Hash: 0e0d83c317b0de9d6afd
Time: 8004ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 8.81 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 199 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.4 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.89 MB [initial] [rendered]

WARNING in ./node_modules/require_optional/index.js
82:18-42 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\Perso\dev\testAngular\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\Perso\dev\testAngular\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./node_modules/require_optional/index.js
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/require_optional/index.js
90:20-44 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\Perso\dev\testAngular\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\Perso\dev\testAngular\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./node_modules/require_optional/index.js
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/require_optional/index.js
97:35-67 Critical dependency: the request of a dependency is an expression
    at RequireResolveContextDependency.getWarnings (C:\Perso\dev\testAngular\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compiler.js:502:17)
    at C:\Perso\dev\testAngular\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Perso\dev\testAngular\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./node_modules/require_optional/index.js
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ ./src/main.ts
 @ multi ./src/main.ts

ERROR in ./node_modules/require_optional/node_modules/resolve-from/index.js
Module not found: Error: Can't resolve 'module' in 'C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\resolve-from'
resolve 'module' in 'C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\resolve-from'
  Parsed request is a module
  using description file: C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\resolve-from\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\resolve-from\package.json (relative path: .)
    resolve as module
      C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\resolve-from\node_modules doesn't exist or is not a directory
      C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\node_modules doesn't exist or is not a directory
      C:\Perso\dev\testAngular\node_modules\node_modules doesn't exist or is not a directory
      C:\Perso\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Perso\dev\testAngular\node_modules\require_optional\node_modules
        using description file: C:\Perso\dev\testAngular\node_modules\require_optional\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Perso\dev\testAngular\node_modules\require_optional\package.json (relative path: ./node_modules)
          using description file: C:\Perso\dev\testAngular\node_modules\require_optional\package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\module doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\module.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\module.js doesn't exist
            as directory
              C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\module doesn't exist
      looking for modules in C:\Perso\dev\testAngular\node_modules
        using description file: C:\Perso\dev\testAngular\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Perso\dev\testAngular\package.json (relative path: ./node_modules)
          using description file: C:\Perso\dev\testAngular\package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\node_modules\module doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\node_modules\module.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\node_modules\module.js doesn't exist
            as directory
              C:\Perso\dev\testAngular\node_modules\module doesn't exist
      looking for modules in C:\Perso\dev\node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          C:\Perso\dev\node_modules\module doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
          C:\Perso\dev\node_modules\module.ts doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          C:\Perso\dev\node_modules\module.js doesn't exist
        as directory
          C:\Perso\dev\node_modules\module doesn't exist
      looking for modules in C:\Perso\dev\testAngular\node_modules
        using description file: C:\Perso\dev\testAngular\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Perso\dev\testAngular\package.json (relative path: ./node_modules)
          using description file: C:\Perso\dev\testAngular\package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\node_modules\module doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\node_modules\module.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\node_modules\module.js doesn't exist
            as directory
              C:\Perso\dev\testAngular\node_modules\module doesn't exist
      looking for modules in C:\Perso\dev\testAngular\src
        using description file: C:\Perso\dev\testAngular\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Perso\dev\testAngular\package.json (relative path: ./src)
          using description file: C:\Perso\dev\testAngular\package.json (relative path: ./src/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\src\module doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\src\module.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\src\module.js doesn't exist
            as directory
              C:\Perso\dev\testAngular\src\module doesn't exist
      looking for modules in C:\Perso\dev\testAngular\src
        using description file: C:\Perso\dev\testAngular\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\Perso\dev\testAngular\package.json (relative path: ./src)
          using description file: C:\Perso\dev\testAngular\package.json (relative path: ./src/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\src\module doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\src\module.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Perso\dev\testAngular\src\module.js doesn't exist
            as directory
              C:\Perso\dev\testAngular\src\module doesn't exist
[C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\resolve-from\node_modules]
[C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\node_modules]
[C:\Perso\dev\testAngular\node_modules\node_modules]
[C:\Perso\node_modules]
[C:\node_modules]
[C:\Perso\dev\node_modules\package.json]
[C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\module]
[C:\Perso\dev\testAngular\node_modules\module]
[C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\module.ts]
[C:\Perso\dev\testAngular\node_modules\module.ts]
[C:\Perso\dev\node_modules\module\package.json]
[C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\module.js]
[C:\Perso\dev\testAngular\node_modules\module.js]
[C:\Perso\dev\node_modules\module]
[C:\Perso\dev\testAngular\node_modules\require_optional\node_modules\module]
[C:\Perso\dev\testAngular\node_modules\module]
[C:\Perso\dev\node_modules\module.ts]
[C:\Perso\dev\node_modules\module.js]
[C:\Perso\dev\node_modules\module]
[C:\Perso\dev\testAngular\node_modules\module]
[C:\Perso\dev\testAngular\node_modules\module.ts]
[C:\Perso\dev\testAngular\node_modules\module.js]
[C:\Perso\dev\testAngular\node_modules\module]
[C:\Perso\dev\testAngular\src\module]
[C:\Perso\dev\testAngular\src\module.ts]
[C:\Perso\dev\testAngular\src\module.js]
[C:\Perso\dev\testAngular\src\module]
[C:\Perso\dev\testAngular\src\module]
[C:\Perso\dev\testAngular\src\module.ts]
[C:\Perso\dev\testAngular\src\module.js]
[C:\Perso\dev\testAngular\src\module]
 @ ./node_modules/require_optional/node_modules/resolve-from/index.js 3:13-30
 @ ./node_modules/require_optional/index.js
 @ ./node_modules/mongodb-core/index.js
 @ ./node_modules/mongodb/index.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```

### Desired behavior
Just to have an application that builds :) 

### Mention any other details that might be useful (optional)
I have tested with many versions of mongoDb but I always have the same problem.

**Comment by sdeniaud33** [comment]
Sorry, I understood my mistake ... every thing in Angular runs on client side... mongoDb must be used on server side.
Once again, sorry for that, I'm new to Angular and don't understand well the client/server frontier.
