### ISSUE TITLE
angular/cli 1.6.2,I can't start my server :Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

### ISSUE THREAD

**Issue by xiaomoinfo** [angular/angular-cli#8980]
### Versions
```
Angular CLI: 1.6.2
Node: 8.9.0
OS: win32 x64
```

### Repro steps
step1: when I execute the command `npm install`
step2:  `ng serve`

### Observed behavior
```
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\IdeaProject\ocjp-exam-system\node_modules\html-webpack-plugin\lib\compiler.js:11:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\IdeaProject\ocjp-exam-system\node_modules\html-webpack-plugin\index.js:7:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

### Desired behavior
What should I do?

**Comment by xiaomoinfo** [comment]
@fanorenantsoa angular version's problem.  you can use angular-cli to create a new project, you will fix this problem

**Comment by fanorenantsoa** [comment]
thank you
