### ISSUE TITLE
Lazy loaded modules are not rendered on server

### ISSUE THREAD

**Issue by linux-nerd** [angular/angular-cli#8995]
### Versions
```
Angular CLI: 1.6.2
Node: 6.9.1
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

- I have defined below routes in app-routing.module.ts

```
const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'contact', loadChildren: 'app/contact/contact.module#ContactModule' },
  { path: 'pricing', loadChildren: 'app/pricing/pricing.module#PricingModule' }
];
```

- Contact and Pricing has its own module with routes. For example
```
const routes: Routes = [
  { path: '', component: ContactComponent, pathMatch: 'full' }
];
```

- Npm commands to build the app - 
```
{
"build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
"serve:ssr": "node dist/server.js",
"build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-hashing=false",
"webpack:server": "webpack --config webpack.server.config.js --progress --colors"
}
```

- server.ts and webpack.server.config.js is taken from [angular-cli ssr story](https://github.com/angular/angular-cli/wiki/stories-universal-rendering)

### Observed behavior

- Getting error ERROR { Error: Uncaught (in promise): Error: Cannot find module 'app/pricing/pricing.module.ngfactory'.

- Stack trace
```
ERROR { Error: Uncaught (in promise): Error: Cannot find module 'app/pricing/pricing.module.ngfactory'.
Error: Cannot find module 'app/pricing/pricing.module.ngfactory'.
    at F:\WS\inked-publishing\inked-publishing\dist\server.js:58556:9
    at ZoneDelegate.invoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:106728:26)
    at Object.onInvoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:6555:33)
    at ZoneDelegate.invoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:106727:32)
    at Zone.run (F:\WS\inked-publishing\inked-publishing\dist\server.js:106478:43)
    at F:\WS\inked-publishing\inked-publishing\dist\server.js:107209:57
    at ZoneDelegate.invokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106761:31)
    at Object.onInvokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:6546:33)
    at ZoneDelegate.invokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106760:36)
    at Zone.runTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106528:47)
    at resolvePromise (F:\WS\inked-publishing\inked-publishing\dist\server.js:107160:31)
    at resolvePromise (F:\WS\inked-publishing\inked-publishing\dist\server.js:107131:17)
    at F:\WS\inked-publishing\inked-publishing\dist\server.js:107209:17
    at ZoneDelegate.invokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106761:31)
    at Object.onInvokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:6546:33)
    at ZoneDelegate.invokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106760:36)
    at Zone.runTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106528:47)
    at drainMicroTaskQueue (F:\WS\inked-publishing\inked-publishing\dist\server.js:106938:35)
    at ZoneTask.invokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106839:21)
    at Server.ZoneTask.invoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:106824:48)
  rejection:
   { Error: Cannot find module 'app/pricing/pricing.module.ngfactory'.
       at F:\WS\inked-publishing\inked-publishing\dist\server.js:58556:9
       at ZoneDelegate.invoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:106728:26)
       at Object.onInvoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:6555:33)
       at ZoneDelegate.invoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:106727:32)
       at Zone.run (F:\WS\inked-publishing\inked-publishing\dist\server.js:106478:43)
       at F:\WS\inked-publishing\inked-publishing\dist\server.js:107209:57
       at ZoneDelegate.invokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106761:31)
       at Object.onInvokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:6546:33)
       at ZoneDelegate.invokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106760:36)
       at Zone.runTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106528:47)
     __zone_symbol__currentTask:
      ZoneTask {
        _zone: [Object],
        runCount: 0,
        _zoneDelegates: null,
        _state: 'notScheduled',
        type: 'microTask',
        source: 'Promise.then',
        data: undefined,
        scheduleFn: undefined,
        cancelFn: null,
        callback: [Function],
        invoke: [Function] } },
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      { Error: Cannot find module 'app/pricing/pricing.module.ngfactory'.
          at F:\WS\inked-publishing\inked-publishing\dist\server.js:58556:9
          at ZoneDelegate.invoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:106728:26)
          at Object.onInvoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:6555:33)
          at ZoneDelegate.invoke (F:\WS\inked-publishing\inked-publishing\dist\server.js:106727:32)
          at Zone.run (F:\WS\inked-publishing\inked-publishing\dist\server.js:106478:43)
          at F:\WS\inked-publishing\inked-publishing\dist\server.js:107209:57
          at ZoneDelegate.invokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106761:31)
          at Object.onInvokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:6546:33)
          at ZoneDelegate.invokeTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106760:36)
          at Zone.runTask (F:\WS\inked-publishing\inked-publishing\dist\server.js:106528:47) __zone_symbol__currentTask: [Object] } },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [Object],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Object],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Object],
        _invokeZS: [Object],
        _invokeDlgt: [Object],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [Object],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [Object],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [Object],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [Object],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [Object],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
```

### Desired behavior
Lazy loaded modules should be rendered on the server.

**Comment by linux-nerd** [comment]
@Brocco   Is there any update or workaround on this?

**Comment by tomrainedotcom** [comment]
Has there been any word on this, I have the exact same issue.

**Comment by linux-nerd** [comment]
@tomrainedotcom Not yet.

**Comment by dneeleman** [comment]
Anything?

**Comment by alan-agius4** [comment]
Lazy loaded module should be generated at server when using Universal. 
In fact in the starter kit there are lazy paths: https://github.com/angular/universal-starter

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
