### ISSUE TITLE
[AppShell] Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by MrCroft** [angular/angular-cli#9048]
### Versions
```
Angular CLI: 1.6.3
Node: 8.9.3
OS: win32 x64
Angular: 5.1.2
```

### Repro steps
Sample repo here: https://github.com/MrCroft/ng-app-shell (just run `ng build --prod`)
I've stumbled upon this bug when I've tried to add AppShell to an existing Universal project (not included in the sample repo).
First I've tried to use the existing Universal app as the app shell, but it throws: "NullInjectorError: No provider for InjectionToken MODULE_MAP!" on build.
So (already having tsconfig.server, app.server.module and main.server), I've created a 3rd app to use for the app shell, adding another set of files:
```
tsconfig.shell.json
app.shell.module.ts
main.shell.ts
```
Of course, following the name convention, I wanted the class name in `app.shell.module.ts` to be `AppShellModule`.
But, at build time, that threw the error `Cannot read property 'create' of undefined`.

```
Cannot read property 'create' of undefined
TypeError: Cannot read property 'create' of undefined
    at D:\www\my-app-shell\node_modules\@angular\core\bundles\core.umd.js:5531:78
    at ZoneDelegate.invoke (D:\www\my-app-shell\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (D:\www\my-app-shell\node_modules\@angular\core\bundles\core.umd.js:4792:33)
    at ZoneDelegate.invoke (D:\www\my-app-shell\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\www\my-app-shell\node_modules\zone.js\dist\zone-node.js:138:43)
    at NgZone.run (D:\www\my-app-shell\node_modules\@angular\core\bundles\core.umd.js:4609:69)
    at PlatformRef.bootstrapModuleFactory (D:\www\my-app-shell\node_modules\@angular\core\bundles\core.umd.js:5529:23)
    at renderModuleFactory (D:\www\my-app-shell\node_modules\@angular\platform-server\bundles\platform-server.umd.js:1809:39)
    at Class.run (D:\www\my-app-shell\node_modules\@angular\cli\tasks\render-universal.js:19:16)
    at buildPromise.then.then (D:\www\my-app-shell\node_modules\@angular\cli\commands\build.js:267:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Observed behavior
Changing the class name in `app.shell.module.ts` from **AppShellModule** to **AppServerModule** (and also changed that in `tsconfig.shell.json` and in the `main.shell.ts` import), made the error go away.

### Desired behavior
The CLI shouldn't have any problems with our class names, as long as all imports match properly.

**Comment by Brocco** [comment]
When you create your app-shell you can use these two options:

`rootModuleFileName` to set the file name
and
`rootModuleClassName` to set the class name

Is that what you're using to create your app shell? If not, please include your steps for reproduction.

**Comment by MrCroft** [comment]
Initially I added it myself (manually creating the files and editing `.angular-cli.json`).
But here is how to reproduce it in a few quick steps, only with the CLI:

1. **ng new shell-test --routing**
2. **ng g universal** shell **--out-dir** dist-shell **--main** main.shell.ts **--tsconfig-file-name** tsconfig.shell **--root-module-file-name** app.shell.module.ts **--root-module-class-name** AppShellModule
3. **ng g app-shell** name-does-not-seem-to-matter **--client-app** 0 **--universal-app** 1 **--out-dir** dist-shell **--main** main.shell.ts **--tsconfig-file-name** tsconfig.shell **--root-module-file-name** app.shell.module.ts **--root-module-class-name** AppShellModule
4. **npm install** (since the CLI added `@angular/platform-server` at step 2)
5. **ng build --prod**
```
Cannot read property 'create' of undefined
TypeError: Cannot read property 'create' of undefined
    at C:\wamp64\www\shell-test\node_modules\@angular\core\bundles\core.umd.js:5531:78
    at ZoneDelegate.invoke (C:\wamp64\www\shell-test\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (C:\wamp64\www\shell-test\node_modules\@angular\core\bundles\core.umd.js:4792:33)
    at ZoneDelegate.invoke (C:\wamp64\www\shell-test\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (C:\wamp64\www\shell-test\node_modules\zone.js\dist\zone-node.js:138:43)
    at NgZone.run (C:\wamp64\www\shell-test\node_modules\@angular\core\bundles\core.umd.js:4609:69)
    at PlatformRef.bootstrapModuleFactory (C:\wamp64\www\shell-test\node_modules\@angular\core\bundles\core.umd.js:5529:23)
    at renderModuleFactory (C:\wamp64\www\shell-test\node_modules\@angular\platform-server\bundles\platform-server.umd.js:1809:39)
    at Class.run (C:\wamp64\www\shell-test\node_modules\@angular\cli\tasks\render-universal.js:19:16)
    at buildPromise.then.then (C:\wamp64\www\shell-test\node_modules\@angular\cli\commands\build.js:267:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
6. Edit `app.shell.module.ts`, `main.shell.ts` and `tsconfig.shell.json` to change the `AppShellModule` class name and references to it, from `AppShellModule` to `AppServerModule`.
7. Now try `ng build --prod` again. It works!


The reason I didn't use the defaults is because I already had a Universal app for full server-side rendering. And trying to use that app for the app shell threw `NullInjectorError: No provider for InjectionToken MODULE_MAP!` on build. And, out of curiosity, I've removed the `ModuleMapLoaderModule` import from `app.server.module.ts` and it still threw other errors simply because I import stuff from express, since express is needed for "real" redirects, status codes, treating cookies server-side etc.

**Comment by filipesilva** [comment]
Is this still a problem with the latest versions of Angular and CLI?

**Comment by alan-agius4** [comment]
Closing as no further feedback was provided by the issue author.

Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
