### ISSUE TITLE
I cannot get e2e tests running, and ng e2e gives 0 feedback of errors.

### ISSUE THREAD

**Issue by NullVoxPopuli** [angular/angular-cli#906]
> Please provide us with the following information:
> ---------------------------------------------------------------

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```

2. Versions. Please run `ng --version`
```
ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.2-mobile.3
node: 5.10.1
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Yes. and I have no idea why this isn't working. I even generated a new angular-cli project, and I just keep running in to problems. The blank angular-cli project had `ng e2e` run (failed, but it at least ran the tests).

I'm using:
- angular master
- angular-cli master
- angular/protractor master

all via npm install <github url>

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
 $ ng e2e
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

> app0.0.0 pree2e /path
> webdriver-manager update

Updating selenium standalone to version 2.53.0
downloading https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar...
Updating chromedriver to version 2.21
downloading https://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip...
selenium-server-standalone-2.53.0.jar downloaded to /..../node_modules/protractor/selenium/selenium-server-standalone-2.53.0.jar
chromedriver_2.21linux64.zip downloaded to /..../node_modules/protractor/selenium/chromedriver_2.21linux64.zip

> app@0.0.0 e2e /path
> protractor "config/protractor.conf.js"


Some end-to-end tests failed, see above.
```

```
$ protractor config/protractor.conf.js
module.js:341
    throw err;
    ^

Error: Cannot find module '../built/cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/..../node_modules/protractor/bin/protractor:5:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

```

**Comment by NullVoxPopuli** [comment]
correction, angular/angular won't install from master today. see: https://github.com/angular/angular/issues/8815

my package.json lists:
```
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "angular-cli": "^1.0.0-beta.5",
```

**Comment by filipesilva** [comment]
Heya @NullVoxPopuli, can you run `npm run protractor -- config/protractor.conf.js` and tell me the result?

**Comment by NullVoxPopuli** [comment]
I didn't have protractor in my package.json, so I just ran this:

`protractor config/protractor.conf.js`

I got this error:
```
$ protractor config/protractor.conf.js
module.js:341
    throw err;
    ^

Error: Cannot find module '../built/cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/webdev/ClientDevelopment/ATI/Portal.Librarian/node_modules/protractor/bin/protractor:5:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

However, @etkirsch was able to 'fix' the repository, by just copying all our code into a new `ng new` project.

Here is the diff between the two commits:

```
-- a/package.json
+++ b/package.json
@@ -29,21 +29,20 @@
   },
   "devDependencies": {
     "angular-cli": "^1.0.0-beta.5",
-    "broccoli-funnel": "1.0.1",
     "broccoli-render-template": "0.0.3",
-    "clang-format": "^1.0.35",
+    "codelyzer": "0.0.19",
     "ember-cli-inject-live-reload": "^1.4.0",
-    "jade": "^1.11.0",
     "jasmine-core": "^2.4.1",
     "jasmine-spec-reporter": "^2.4.0",
     "karma": "^0.13.15",
     "karma-chrome-launcher": "^0.2.3",
     "karma-jasmine": "^0.3.8",
-    "node-sass": "3.5.3",
-    "protractor": "git+https://github.com/angular/protractor.git",
+    "protractor": "^3.3.0",
     "ts-node": "^0.5.5",
     "tslint": "^3.6.0",
     "typescript": "^1.8.10",
-    "typings": "^0.8.1"
+    "typings": "^0.8.1",
+    "jade": "^1.11.0",
+    "node-sass": "3.5.3"
   }
 }
```

deleted repoRoot/karma.conf.js
deleted repoRoot/kerma-test-shim.js

```
--- a/config/protractor.conf.js
+++ b/config/protractor.conf.js
@@ -9,6 +9,7 @@ exports.config = {
   capabilities: {
     browserName: 'chrome',
   },
+  chromeOnly: true,
   directConnect: true,
   baseUrl: 'http://localhost:4200/',
   framework: 'jasmine',
```

```
--- a/angular-cli.json
+++ b/angular-cli.json
@@ -1,6 +1,6 @@
 {
   "project": {
-    "version": "1.0.0-beta.2-mobile.3",
+    "version": "1.0.0-beta.5",
     "name": "Portal.Librarian"
   },
```

So, it could have just been a configuration / dependency version issue.

**Comment by etkirsch** [comment]
I think it was an issue with an earlier version of angular-cli. As @NullVoxPopuli mentioned, when we updated angular-cli to the most recent version and ran `ng new`, everything worked in the new app.

**Comment by filipesilva** [comment]
Glad to hear it's up and running again. There's a lot of updated between versions at the moment and we're still lacking changelogs, but we're working on them.

**Comment by Blasz** [comment]
Part of this issue is that `ng e2e` shouldn't swallow errors, similar to [ng lint](https://github.com/angular/angular-cli/issues/867#issuecomment-224345882). I'd say they'd probably be handled the same?

As a starting point, would it be possible to document how `ng` runs the npm scripts as well, i.e. what arguments they use, as they contain debugging info.

Something like:

> ng e2e
> Runs: npm run e2e -- config/protractor.conf.js

**Comment by christiandreher** [comment]
@Blasz I think it would be a bad idea for a `ng` command to internally run a `npm run` command, since it could be overwritten by an end user, who then wonders why the `ng x` command is broken. Better call `./node_modules/x/bin/whatever --your-params` etc...
