### ISSUE TITLE
Tried installing under powershell. The install seems to work but npm serve throws a bad error.

### ISSUE THREAD

**Issue by foxjazz** [angular/angular-cli#910]
> Please provide us with the following information:
> ---------------------------------------------------------------
windows 10

instructions from 
https://playcode.org/routing-in-angular-2-rc-1/

Bad errors on npm serve command

**Comment by neilhem** [comment]
On windows you should run `ng serve` in powershell running as administrator

**Comment by filipesilva** [comment]
@foxjazz I need some more details about what errors you get. Can you post a console log here?

**Comment by bobslaede** [comment]
It doesn't work on my Windows (8) either. 

````POWERSHELL
PS C:\projects\angular2-test-1> ng serve
(node:5892) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please up
date it to a more recent version.
Cannot read property 'sourceDir' of undefined
TypeError: Cannot read property 'sourceDir' of undefined
    at new Angular2App (C:\projects\angular2-test-1\node_modules\angular-cli\lib\broccoli\angular2-app.js:30:40)
    at module.exports (C:\projects\angular2-test-1\angular-cli-build.js:6:13)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\projects\angular2-test-1\node_modules\angular-cli\node_
modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\projects\angular2-test-1\node_modules\angular-cli\node_modules\angular-
cli\lib\models\builder.js:89:10)
    at new Class (C:\projects\angular2-test-1\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object
\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\projects\angular2-test-1\node_modules\angular-cli\node_modules\angular-c
li\lib\tasks\serve.js:15:19)
    at C:\projects\angular2-test-1\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\projects\angular2-test-1\node_modules\angular-cli\node_modules\angular-cli\node_
modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\projects\angular2-test-1\node_modules\angular-cli\node_modules\angular-cli
\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\projects\angular2-test-1\node_modules\angular-cli\node_modules\angular-cli\node_m
odules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\projects\angular2-test-1\node_modules\angular-cli\node_modules\angular-cli\node_modules\
rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
PS C:\projects\angular2-test-1>
````

**Comment by filipesilva** [comment]
@bobslaede is that a new project, or are you trying to update a project? 

There are a lot of breaking changes between versions at the moment so it's likely that a project created with an older version of `angular-cli` doesn't work with the newest version.

My advise is to create a new project and move your user code to it.

**Comment by bobslaede** [comment]
Totally new.

**Comment by erdnax123** [comment]
same problem:
`ng new my-project`
`cd my project`
`ng serve`

> (node:21008) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

`npm list graceful-fs > dep.txt`

[dep.txt](https://github.com/angular/angular-cli/files/284190/dep.txt)

line 24 **gracefule-fs@3.0.8**

**Comment by filipesilva** [comment]
@erdnax123 the graceful-fs error is one of the sub-dependencies, and shouldn't affect normal functioning of the CLI.

@bobslaede what version of the CLI do you have installed?

**Comment by bobslaede** [comment]
@filipesilva I had installed the newest, but it was apparently installed in multiple locations, because of windows, and I was using and older version. Cleaning my C:\Program Files\nodejs directory, and reinstalling nodejs, and angular-cli helped.

**Comment by filipesilva** [comment]
Yeah there's a global install and a local install, and if their versions mismatch sometimes there are issues. Glad to hear it's sorted though!
