### ISSUE TITLE
HMR steps from wiki throws linter warning

### ISSUE THREAD

**Issue by admosity** [angular/angular-cli#9161]
The current hmr steps listed in the wiki is using a deprecated form of `injector.get`:
https://github.com/angular/angular/blob/b3eb1db6dd57a0820cfc94af5460ceb3fea20610/packages/core/src/di/injector.ts#L61-L65

I could not find any way to include the `ApplicationRef` other than the way described in the wiki: https://github.com/angular/angular-cli/wiki/stories-configure-hmr. Not sure if angular needs to provide this token or there's another way to do this.

### Versions
```
Angular CLI: 1.6.3
Node: 8.7.0
OS: darwin x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... tsc-wrapped

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* Create new project
* Follow steps for enabling hmr
* Run `ng lint`

### Observed behavior
```
> ng lint                                                                                                                                                                             

WARNING: /path/to/project/src/hmr.ts[24, 54]: get is deprecated: from v4.0.0 use Type<T> or InjectionToken<T>

Lint warnings found in the listed files.
```

### Desired behavior
`ng lint` should not throw any warnings with the provided hmr code. 

### Mention any other details that might be useful (optional)
Code used for hmr.ts:
```typescript
import { NgModuleRef, ApplicationRef } from '@angular/core';
import { createNewHosts } from '@angularclass/hmr';

export const hmrBootstrap = (module: any, bootstrap: () => Promise<NgModuleRef<any>>) => {
  let ngModule: NgModuleRef<any>;
  module.hot.accept();
  bootstrap().then(mod => ngModule = mod);
  module.hot.dispose(() => {
    if (!ngModule) {
      console.log('[HMR] APPLICATION STATE UNSTABLE - Forcing browser reload.');
      window.location.reload();
    }
    const appRef: ApplicationRef = ngModule.injector.get(ApplicationRef);
    const elements = appRef.components.map(c => c.location.nativeElement);
    const makeVisible = createNewHosts(elements);
    ngModule.destroy();
    makeVisible();
  });
};
```

**Comment by seanmcintyre** [comment]
when was `injector.get` deprecated?

**Comment by seanmcintyre** [comment]
@admosity are you only receiving warnings? Running with HMR completely fails for me: 

```
ERROR in TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/****/node_modules/typescript/lib/typescript.js:13411:110)
    at parseSourceFileWorker (/****/node_modules/typescript/lib/typescript.js:13343:26)
    at Object.parseSourceFile (/****/node_modules/typescript/lib/typescript.js:13269:26)
    at Object.createSourceFile (/****/node_modules/typescript/lib/typescript.js:13110:29)
    at VirtualFileStats.getSourceFile (/****/node_modules/@ngtools/webpack/src/compiler_host.js:67:35)
    at WebpackCompilerHost.getSourceFile (/****/node_modules/@ngtools/webpack/src/compiler_host.js:206:38)
    at findSourceFile (/****/node_modules/typescript/lib/typescript.js:73056:29)
    at processImportedModules (/****/node_modules/typescript/lib/typescript.js:73228:25)
    at findSourceFile (/****/node_modules/typescript/lib/typescript.js:73104:17)
    at args (/****/node_modules/typescript/lib/typescript.js:72993:85)
    at getSourceFileFromReferenceWorker (/****/node_modules/typescript/lib/typescript.js:72966:34)
    at processSourceFile (/****/node_modules/typescript/lib/typescript.js:72993:13)
    at processRootFile (/****/node_modules/typescript/lib/typescript.js:72848:13)
    at /****/node_modules/typescript/lib/typescript.js:72006:60
    at Object.forEach (/****/node_modules/typescript/lib/typescript.js:1526:30)
    at Object.createProgram (/****/node_modules/typescript/lib/typescript.js:72006:16)
```

**Comment by admosity** [comment]
@seanmcintyre a form of it has been deprecated since the beginning of 4.0.0:
https://github.com/angular/angular/blob/b3eb1db6dd57a0820cfc94af5460ceb3fea20610/packages/core/src/di/injector.ts#L61-L65

I did have some issues setting up the project with HMR and with something about not finding a certain file. You might want to check your tsconfig and it's finding the files. This looks like it may not be finding the files correctly.

**Comment by admosity** [comment]
@seanmcintyre looks like your issue is directly related to #5053

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
