### ISSUE TITLE
Generating an Angular component with no name should throw proper error message

### ISSUE THREAD

**Issue by cRAN-cg** [angular/angular-cli#9175]
### Versions
```
@angular/cli: 1.4.1
node: 8.9.1
os: win32 x64
@angular/animations: 4.4.6                                                                                              @angular/common: 4.4.6                                                                                                  @angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6                                                                                @angular/router: 4.4.6
@angular/cli: 1.4.1
@angular/compiler-cli: 4.4.6                                                                                            @angular/language-service: 4.4.6
typescript: 2.3.4 
```

### Repro steps

* create a new project with the angular-cli
> ``` ng new test-sample ``` 
> ``` cd test-sample```
* try creating any angular component without providing any (proper) name
>``` ng g component ```

### Observed behavior
```
Cannot read property 'split' of undefined                                                                      
TypeError: Cannot read property 'split' of undefined
        at Class.run (C:\Users\cran-cg\test-sample\test-sample\node_modules\@angular\cli\commands\generate.js:109:64)           	
	at resolve (C:\Users\cran-cg\test-sample\test-sample\node_modules\@angular\cli\ember-cli\lib\models\command.js:273:20)
	at new Promise (<anonymous>)                                                                                  
        at Class.validateAndRun (C:\Users\cran-cg\test-sample\test-sample\node_modules\@angular\cli\ember-cli\lib\models\command.js:251:12)                                                                                         
        at Promise.resolve.then.then (C:\Users\cran-cg\test-sample\test-sample\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:154:24)                                                                                      
        at <anonymous>
```

### Desired behavior
* A proper,valid error message should have been printed out to the user

**Comment by cRAN-cg** [comment]
I would like to work on it.

**Comment by cRAN-cg** [comment]
I would like to work on it.

**Comment by Brocco** [comment]
Sounds good, if you have questions, please ping me.

**Comment by cRAN-cg** [comment]
Thanks for letting me 👍  
I was planning to make a constant list of all the [blueprint elements available](https://github.com/angular/angular-cli/wiki/generate) to be used with the `generate` command. Wanted to know if the list is latest.

**Comment by cRAN-cg** [comment]
@Brocco I have asked you for some advise on the PR thread itself, will request you to look at it
