### ISSUE TITLE
Build & Serve error when using -prod

### ISSUE THREAD

**Issue by neckaros** [angular/angular-cli#920]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Win 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
angular-cli: 1.0.0-beta.5
node: 4.4.4
os: win32 x64

angular material version:
"@angular2-material/button": "^2.0.0-alpha.4",
    "@angular2-material/core": "^2.0.0-alpha.4",
    "@angular2-material/sidenav": "^2.0.0-alpha.4",
    "@angular2-material/toolbar": "^2.0.0-alpha.4",

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
added some angular material modules

4. The log given by the failure. Normally this include a stack trace and some
   more information.

when build or serve with '-prod' (no error without using -prod)
`Build error

The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for vendor/@angular2-material/toolbar/toolbar.js at file:///c:/Devs/Web/redseat/tmp/bundle_plugin-input_base_path-LFVewzQm.tmp/0/vendor/@angular2-material/toolbar/toolbar.js
	Loading app/redseat.component.js
	Loading app/index.js
	Loading main.js
	Error: ENOENT: no such file or directory, open 'c:\Devs\Web\redseat\tmp\bundle_plugin-input_base_path-LFVewzQm.tmp\0\vendor\@angular2-material\toolbar\toolbar.js.map'
    at Error (native)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BundlePlugin (c:\Devs\Web\redseat\node_modules\angular-cli\lib\broccoli\angular-broccoli-bundle.js:11:10)
    at Angular2App._getBundleTree (c:\Devs\Web\redseat\node_modules\angular-cli\lib\broccoli\angular2-app.js:421:22)
    at Angular2App._buildTree (c:\Devs\Web\redseat\node_modules\angular-cli\lib\broccoli\angular2-app.js:159:21)
    at new Angular2App (c:\Devs\Web\redseat\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (c:\Devs\Web\redseat\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\ember-cli\lib\models\builder.js:89:10)
    at new Class (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\ember-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\ember-cli\lib\tasks\serve.js:15:19)
    at c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\ember-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (c:\Devs\Web\redseat\node_modules\angular-cli\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1198:9)`

5. Mention any other details that might be useful.

running cmd as admin

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by JSMike** [comment]
When you added the Material2 modules, did you update the angular-cli-build.js file and the system.config.ts file per https://github.com/angular/angular-cli/wiki/3rd-party-libs

**Comment by spboyer** [comment]
I get this when running `ng serve --environment=production` on a brand new app generated. `--environment=development` works fine.

Error
```
The Broccoli Plugin: [BundlePlugin] failed with:
Error on fetch for main.js at file:///Users/boyes013/projects/spboyer/a2-settings/using-environment/tmp/bundle_plugin-input_base_path-HK3YWDOt.tmp/0/main.js
	Error: ENOENT: no such file or directory, open '/Users/boyes013/projects/spboyer/a2-settings/using-environment/tmp/bundle_plugin-input_base_path-HK3YWDOt.tmp/0/main.js.map'
    at Error (native)

The broccoli plugin was instantiated at: 
    at BundlePlugin.Plugin (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BundlePlugin.CachingWriter [as constructor] (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BundlePlugin (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/lib/broccoli/angular-broccoli-bundle.js:11:10)
    at Angular2App._getBundleTree (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/lib/broccoli/angular2-app.js:375:55)
    at Angular2App._buildTree (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/lib/broccoli/angular2-app.js:137:21)
    at new Angular2App (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/lib/broccoli/angular2-app.js:42:23)
    at module.exports (/Users/boyes013/projects/spboyer/a2-settings/using-environment/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/boyes013/projects/spboyer/a2-settings/using-environment/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

```

**Comment by spboyer** [comment]
```
angular-cli: 0.0.39
node: 4.4.0
os: darwin x64
```

**Comment by neckaros** [comment]
@JSMike Yes (and working great when not prod):

angular-cli-build.js
```
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      **'@angular2-material/**/*.js'**
    ]
  });
};
```
system-config.ts
```
/** Map relative paths to URLs. */
const map:any = {
  '@angular2-material': 'vendor/@angular2-material'
};

/** User packages configuration. */
const packages:any = {
  '@angular2-material/core': {
    format: 'cjs',
    defaultExtension: 'js',
    main: 'core.js'
  },
  '@angular2-material/toolbar': {
    format: 'cjs',
    defaultExtension: 'js',
    main: 'toolbar.js'
  },
  
  '@angular2-material/sidenav': {
    format: 'cjs',
    defaultExtension: 'js',
    main: 'sidenav.js'
  },
  '@angular2-material/card': {
    format: 'cjs',
    defaultExtension: 'js',
    main: 'card.js'
  },
  '@angular2-material/button': {
    format: 'cjs',
    defaultExtension: 'js',
    main: 'button.js'
  },
   '@angular2-material/icon': {
    format: 'cjs',
    defaultExtension: 'js',
    main: 'icon.js'
  },
  
  // And so on...
};
```

**Comment by hansl** [comment]
> `angular-cli: 0.0.39`

@spboyer could you upgrade to the latest version? This normally happens because your _project_ `node_modules` isn't up to date.

**Comment by spboyer** [comment]
@hansl - had a collision with the two versions, installed new version `angular-cli@latest`

```
angular-cli: 1.0.0-beta.5
node: 4.4.0
os: darwin x64
```
 run npm install on project generated with 0.0.39 and then run `ng --version` returns

```
angular-cli: 0.0.39
node: 4.4.0
os: darwin x64
```

FIX:  generate new project copy package.json to old project make meta changes (project name etc) and `npm install` issue resolved. 

`ng s -prod` works. My portion is closed.

**Comment by JSMike** [comment]
@neckaros 

`      '@angular2-material/**/*.js'`
should be
`      '@angular2-material/**/*.+(js|js.map)'`

I'm personally not having issues with ng serve -prod in windows 10 with material. Note: my node version is a bit old, 4.2.4

**Comment by JSMike** [comment]
@neckaros 

This is the part that's weird to me: `file:///c:/Devs/Web/redseat/tmp/bundle_plugin-input_base_path-LFVewzQm.tmp/0/vendor/@angular2-material/toolbar/toolbar.js`

I'm not sure why it's trying to access some temp directory/vendor, it should be trying to access {project_root}/dist/vendor

**Comment by neckaros** [comment]
@JSMike thanks it make sense following the other lib but it did not say so in the wiki:
https://github.com/angular/angular-cli/wiki/3rd-party-libs
```
vendorNpmFiles: [
      '@angular2-material/**/*.js'
    ]
```
Production build/serve works now

**Comment by neckaros** [comment]
Contrary to the cli wiki i also used Kara way of doing the import (in her sample from IO) in system.config:

```
const materialPkgs:string[] = [
  'core',
  'toolbar',
  'icon',
  'button',
  'sidenav',
  'list',
  'card',
  'input',
];

materialPkgs.forEach((pkg) => {
  packages[`@angular2-material/${pkg}`] = {main: `${pkg}.js`};
});
```
Work as well but seems cleaner

**Comment by filipesilva** [comment]
I think the wiki might need to be updated for the material bits. I just updated the momentjs section but didn't touch the rest.

**Comment by filipesilva** [comment]
This issue has been made obsolete via #1455.
