### ISSUE TITLE
Bug with "@import '~any/lib.css'" in v1.6.4 and later

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular-cli#9272]
### Versions
```
Angular CLI: 1.6.4
Node: 8.9.4
OS: linux x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

```bash
ng new tmp --minimal
cd tmp
yarn add font-awesome
echo "@import '~font-awesome/css/font-awesome.min.css';" > src/styles.css
ng serve
```

### Observed behavior
```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./src/styles.css
Module build failed: Error: Can't resolve '~font-awesome/css/font-awesome.min.css' in '/var/repos/tmp/src'
    at onError (/var/repos/tmp/node_modules/enhanced-resolve/lib/Resolver.js:61:15)
    at loggingCallbackWrapper (/var/repos/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/var/repos/tmp/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/var/repos/tmp/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/var/repos/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/var/repos/tmp/node_modules/tapable/lib/Tapable.js:252:11)
    at /var/repos/tmp/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/var/repos/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/var/repos/tmp/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/var/repos/tmp/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/var/repos/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/var/repos/tmp/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/var/repos/tmp/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/var/repos/tmp/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/var/repos/tmp/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/var/repos/tmp/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
 @ ./src/styles.css 4:14-138
 @ multi ./src/styles.css
```

### Problem disappears

If we do the following problem disappears:

```bash
yarn add @angular/cli@1.6.3
ng serve
```

The problem seems to apply to [many open issues](https://github.com/angular/angular-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+enhanced-resolve) beginning with @angular/cli@ >= 1.6.4

**Comment by KostyaTretyak** [comment]
In `@angular/cli@1.6.5` resolved this problem.
