### ISSUE TITLE
angular-cli 1.6.5 can't run 'ng serve'

### ISSUE THREAD

**Issue by gogobook** [angular/angular-cli#9285]
```
$ npm -v
5.6.0
$ node -v
v8.9.4
```
Error code
```
$ ng serve
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.CompilerCliIsSupported (/usr/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/ngtools_api.js:25:15)
    at new AotPlugin (/usr/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:29:23)
    at _createAotPlugin (/usr/lib/node_modules/@angular/cli/models/webpack-configs/typescript.js:92:16)
    at Object.getNonAotConfig (/usr/lib/node_modules/@angular/cli/models/webpack-configs/typescript.js:100:19)
    at NgCliWebpackConfig.buildConfig (/usr/lib/node_modules/@angular/cli/models/webpack-config.js:37:37)
    at Class.run (/usr/lib/node_modules/@angular/cli/tasks/serve.js:71:98)
    at check_port_1.checkPort.then.port (/usr/lib/node_modules/@angular/cli/commands/serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by gogobook** [comment]
If no run "npm link @angular/cli", "ng serve" will be fine.
