### ISSUE TITLE
Angular 1.4.9 : Cannot read property 'NullLogger' of undefined

### ISSUE THREAD

**Issue by ulans2017** [angular/angular-cli#9303]
Angular/cli  4 - 1.4.9

Output from: `ng --version`.
@angular/cli: 1.4.9
node: 8.9.4
os: win32 x64
Windows 10 - ver 1709(16299)
### Repro steps

* Step 1
**$ npm install -g @angular/cli@1.4.9**

C:\Users\Owner\AppData\Roaming\npm\ng -> C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN @angular-devkit/schematics@0.0.51 requires a peer of @angular-devkit/core@0.0.28 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/angular@0.0.49 requires a peer of @angular-devkit/schematics@0.0.34 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@1.4.9
added 59 packages, removed 351 packages, updated 29 packages and moved 10 packages in 80.908s

* Step 2
**$ ng new ang4test**

Cannot read property 'NullLogger' of undefined
TypeError: Cannot read property 'NullLogger' of undefined
    at SchematicEngine.createContext (C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:64:39)
    at SchematicImpl.call (C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\schematic.js:35:38)
    at Promise (C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\tasks\schematic-run.js:72:23)
    at new Promise (<anonymous>)
    at Class.run (C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\tasks\schematic-run.js:71:16)
    at Class.run (C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\tasks\init.js:71:33)
    at Class.run (C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\commands\new.js:133:25)
    at resolve (C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (C:\Users\Owner\AppData\Roaming\npm\node_modules\@angular\cli\ember-cli\lib\models\command.js:240:12)
* Step 3

### Observed behavior
```
All outputs shown above

```

### Desired behavior
I expected new project to be made.

### Mention any other details that might be useful (optional)
I've tried to install before many times. Installed and uninstalled, cleaned cache, but failed.

**Comment by clydin** [comment]
Can you try with 1.4.10?

**Comment by ulans2017** [comment]
Thank you for your reply. I cleaned cache by force and installed 1.4.10.  
Installed successfully and had no errors. Issue resolved.

**Comment by ksoni-mobiquity** [comment]
Cannot read property 'NullLogger' of undefined
TypeError: Cannot read property 'NullLogger' of undefined
    at SchematicEngine.createContext (/Users/ksoni/Documents/kamal/angular-forms/node_modules/@angular-devkit/schematics/src/engine/engine.js:64:38)
    at SchematicImpl.call (/Users/ksoni/Documents/kamal/angular-forms/node_modules/@angular-devkit/schematics/src/engine/schematic.js:35:38)
    at Promise (/Users/ksoni/Documents/kamal/angular-forms/node_modules/@angular/cli/tasks/schematic-run.js:77:23)
    at Class.run (/Users/ksoni/Documents/kamal/angular-forms/node_modules/@angular/cli/tasks/schematic-run.js:76:16)
    at Class.run (/Users/ksoni/Documents/kamal/angular-forms/node_modules/@angular/cli/commands/generate.js:138:33)
    at resolve (/Users/ksoni/Documents/kamal/angular-forms/node_modules/@angular/cli/ember-cli/lib/models/command.js:273:20)
    at Class.validateAndRun (/Users/ksoni/Documents/kamal/angular-forms/node_modules/@angular/cli/ember-cli/lib/models/command.js:251:12)
    at Promise.resolve.then.then (/Users/ksoni/Documents/kamal/angular-forms/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:154:24)


issue while using ng generate component my-new-component

**Comment by ksoni-mobiquity** [comment]
@angular/cli: 1.4.1
node: 6.11.2
os: darwin x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.1
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4

**Comment by ulans2017** [comment]
I just followed to suggestion and installed version 1.4.10
Please install uninstall all versions and clear cache, and after install:
ng install -g @angular/cli@1.4.10

**Comment by NadGu** [comment]
Just a question: why is this error occurring in cli versions older then 1.4.10?

**Comment by asmith2306** [comment]
Also seeing this issue:

ng g component MyComponent
Your global Angular CLI version (1.6.5) is greater than your local
version (1.4.1). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
Cannot read property 'NullLogger' of undefined
TypeError: Cannot read property 'NullLogger' of undefined
    at SchematicEngine.createContext (/home/alan/NetBeansProjects/ums-gui-trunk/ums-gui-webapp/src/main/angular/node_modules/@angular-devkit/schematics/src/engine/engine.js:64:38)
    at SchematicImpl.call (/home/alan/NetBeansProjects/ums-gui-trunk/ums-gui-webapp/src/main/angular/node_modules/@angular-devkit/schematics/src/engine/schematic.js:35:38)
    at Promise (/home/alan/NetBeansProjects/ums-gui-trunk/ums-gui-webapp/src/main/angular/node_modules/@angular/cli/tasks/schematic-run.js:77:23)
    at Class.run (/home/alan/NetBeansProjects/ums-gui-trunk/ums-gui-webapp/src/main/angular/node_modules/@angular/cli/tasks/schematic-run.js:76:16)
    at Class.run (/home/alan/NetBeansProjects/ums-gui-trunk/ums-gui-webapp/src/main/angular/node_modules/@angular/cli/commands/generate.js:138:33)
    at resolve (/home/alan/NetBeansProjects/ums-gui-trunk/ums-gui-webapp/src/main/angular/node_modules/@angular/cli/ember-cli/lib/models/command.js:273:20)
    at Class.validateAndRun (/home/alan/NetBeansProjects/ums-gui-trunk/ums-gui-webapp/src/main/angular/node_modules/@angular/cli/ember-cli/lib/models/command.js:251:12)
    at Promise.resolve.then.then (/home/alan/NetBeansProjects/ums-gui-trunk/ums-gui-webapp/src/main/angular/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:154:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by gurpreetcigs** [comment]
I m getting the same error tried to update the angular cli to latest one but still getting the same

**Comment by timcreative** [comment]
Me too. "@angular/cli": "1.6.4"

**Comment by albertotorresfoltyn** [comment]
definitely angular sucks... sorry for posting this... but this can't happen in two platforms today in 2018...

**Comment by mpituley** [comment]
Had the same issue today. Upgraded to angular-cli 1.7.0 both globally and for the project and the issue is fixed.

**Comment by ProgrammingFuad** [comment]
Wow I guess It wasn't just happening to me.

**Comment by hazeeb** [comment]
The same error had happened to me, when 
`@angular/cli: 1.4.8`
`node: 8.10.0`

After upgrading the angular CLI, `ng new newapp `worked fine.

`@angular/cli: 1.7.3`
`node:8.10.0`

**Comment by srinivas444** [comment]
I also faced the same issue but resolved by following this steps they will help you.

npm uninstall -g @angular/cli
npm uninstall --save-dev @angular/cli
npm cache clean
npm install -g @angular/cli@latest
npm install --save-dev @angular/cli@latest

it worked for me.

**Comment by srinivas444** [comment]
I also faced the same issue but resolved by following this steps they will help you.

npm uninstall -g @angular/cli
npm uninstall --save-dev @angular/cli
npm cache clean
npm install -g @angular/cli@latest
npm install --save-dev @angular/cli@latest

it worked for me.

**Comment by HARSINH2DEC** [comment]
@srinivas444  these steps worked for me . thanks

**Comment by noor07** [comment]
@ulans2017 
its=> npm install -g @angular/cli@1.4.10
Not => ng install -g @angular/cli@1.4.10

**Comment by gustavomts** [comment]
@srinivas444 worked for me, but only with 1.4.10 version.

**Comment by alishannb** [comment]
> I also faced the same issue but resolved by following this steps they will help you.
> 
> npm uninstall -g @angular/cli
> npm uninstall --save-dev @angular/cli
> npm cache clean
> npm install -g @angular/cli@latest
> npm install --save-dev @angular/cli@latest
> 
> it worked for me.

if ` npm cache clean` gives you error then use --force flag as following.

 **`npm cache clean --force`**

**Comment by ViolinBrush** [comment]
how to remove cache from the pc? so as to create new project?

**Comment by rbrisita** [comment]
Why are broken versions listed as available to install? This would save developers a lot of time if they were not or at least listed as broken.

**Comment by jkosanovic** [comment]
Surprised to have run into this issue.  Just following the tutorial on Angular.IO and run into this first off the bat. Trying AliShan's steps right now.

**Comment by Menuka5** [comment]
> I also faced the same issue but resolved by following these steps they will help you.
> 
> npm uninstall -g @angular/cli
> npm uninstall --save-dev @angular/cli
> npm cache clean
> npm install -g @angular/cli@latest
> npm install --save-dev @angular/cli@latest
> 
> it worked for me.



> I just followed to suggestion and installed version 1.4.10
> Please first uninstall all versions and clear the cache, and after install:
> ng install -g @angular/cli@1.4.10

The last command should be `npm install -g @angular/cli@1.4.10` right? because ng command didn't seem to work
