### ISSUE TITLE
[SSR] --bundle-dependencies=all produces an error on the compiled main.bundle.js

### ISSUE THREAD

**Issue by wtubog** [angular/angular-cli#9312]
### Versions
```
Angular CLI: 1.6.5
Node: 7.7.4
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps
I have the following build script

ng build --prod --aot --build-optimizer --environment test --op dist-app && ng build --prod --app 1 --environment test --output-hashing=none --bundle-dependencies all

### Observed behavior
It bundles all the dependencies because I noticed that the main.bundle.js > 1MB ... however when I run the server via  `node server.js` it produces the following error:

```
C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e){for(var n in e)t[n]=e[n]}(exports,function(t){var e={};function n(i){if(e[i])return e[i].exports;var l=e[i]={i:i,l:!1,exports:{}};return t[i].call(l.exports,l,l.exports,n),l.l=!0,l.exports}return n.m=t,n.c=e,n.d=function(t,e,i){n.o(t,e)||Object.defineProperty(t,e,{configurable:!1,enumerable:!0,get:i})},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s=0)}({"+DIC":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0});var i=n("AP4T"),l=n("TS1d");i.Observable.prototype.mergeMap=l.mergeMap,i.Observable.prototype.flatMap=l.mergeMap},"+d3/":function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),n("01ER"),e.ModToggle=function(){function t(){}return Object.defineProperty(t.pr

TypeError: i.ɵcrt is not a function
    at Object.gou4 (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:709451)
    at n (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:220)
    at Object.n8xs (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:835269)
    at n (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:220)
    at Object.N9i+ (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:398451)
    at n (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:220)
    at Object.0 (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:13056)
    at n (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:220)
    at t.+DIC.Object.defineProperty.value (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:568)
    at Object.<anonymous> (C:\Users\user1\Documents\angular-projects\gma-psst\dist-server\main.bundle.js:1:577)
```

### Mention any other details that might be useful (optional)

Here's the complete requires of my server file:

```
require('zone.js/dist/zone-node');
require('reflect-metadata');

const express = require('express');
const path = require('path');
// const server = express();
const ngUniversal = require('@nguniversal/express-engine');
const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');

const  { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('../dist-server/main.bundle');
const httpAppPort = process.env.NODE_ENV == 'production' ? 80 : 8081;
```

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
