### ISSUE TITLE
~ in package.json occurs error during re-install of CLI@1.5.2

### ISSUE THREAD

**Issue by willi84** [angular/angular-cli#9315]
### Versions
```
Angular CLI: 1.5.2
Node: 8.9.1
OS: linux x64

```

### Repro steps

* `npm install -g @angular/cli@1.5.2`
* `npm -g ls --depth=0`  (shows error)
* `ng -v` (shows error)

### Observed behavior
When I try to re-install CLI version 1.5.2 today, it runs into an error. It seems compared with my old installation, that the minor version fo the dependencies occur this issue.

Error `of npm -g ls --depth=0`
```
npm ERR! peer dep missing: @angular-devkit/core@0.0.28, required by @angular-devkit/schematics@0.0.51
npm ERR! peer dep missing: @angular-devkit/core@0.0.28, required by @schematics/angular@0.1.16

```

Error of `ng -v` 
```
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest"

module.js:538
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/.nvm/versions/node/v8.9.1/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/src/tree/virtual.js:10:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

### Desired behavior
I would suggest not to use ~ in package.json 's dependencies.

**Comment by hansl** [comment]
We fixed that with a subsequent 1.5.x release. Please try upgrading your CLI to the latest 1.6.4 and see if that solves it.

Closing this as fixed.
