### ISSUE TITLE
error in rxjs/opreator

### ISSUE THREAD

**Issue by MansoorJafari** [angular/angular-cli#9323]
Hi
after run this command 'ng -g component test'
give me this error

`

Error: Cannot find module 'rxjs/operators'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/project/node_modules/@angular-devkit/core/src/logger/indent.js:10:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

`

please help.

**Comment by hansl** [comment]
Looks like you haven't installed a compatible version of `rxjs` in your project. You should take a look at your `node_modules` and your `package.json` files.

If it's a different issue please file a new issue with an example project we can look at. I'm closing this as answered.
