### ISSUE TITLE
Error resolving npm modules after I type 'ng s'

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular-cli#9332]
### Versions

```sh
Angular CLI: 1.6.5
Node: 9.3.0
OS: darwin x64
Angular: undefined
```

### Repro steps

I just upgraded the cli and it's broken my project, I am getting errors when I type, `ng s`.

```pre
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/dm-css/css/dm.min.css
Module build failed: Error: Can't resolve '/node_modules/normalize.css/normalize.css' in '/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/dm-css/css'
    at onError (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/Resolver.js:61:15)
    at loggingCallbackWrapper (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/tapable/lib/Tapable.js:252:11)
    at /Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/Users/yadav/dev/projects/dm-css/website/dynomightcss/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
 @ ./node_modules/dm-css/css/dm.min.css 4:14-118
 @ multi ./src/assets/font-awesome-4.7.0/css/font-awesome.min.css ./node_modules/highlight.js/styles/default.css ./node_modules/normalize.css/normalize.css ./node_modules/dm-css/css/dm.min.css ./src/styles.scss
```

I am using the following `.angular-cli.json` file:

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "dynomightcss"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "",
      "styles": [
        "./assets/font-awesome-4.7.0/css/font-awesome.min.css",
        "../node_modules/highlight.js/styles/default.css",
        "../node_modules/normalize.css/normalize.css",
        "../node_modules/dm-css/css/dm.min.css",
        "styles.scss"
      ],
      "scripts": [
        "../node_modules/highlight.js/lib/highlight.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "component": {}
  }
}
```

**Comment by rajinder-yadav** [comment]
I have verified that the dependency module `normalize.css` is there. Also I have verified that NPM module `dm-css` works outside of an angular-cli generated project using a basic static website!

My angular project is now in a state that I can no longer build and run it.

**Comment by rajinder-yadav** [comment]
I was able to correct the problem on my end by making a fix to module `dm-css`.
