### ISSUE TITLE
option '-sd .' makes the error saying: The Broccoli Plugin: [Funnel] failed with: Error: ENAMETOOLONG: name too long, scandir

### ISSUE THREAD

**Issue by jin-chong** [angular/angular-cli#936]
1). OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX El Capitan

2). Versions. Please run `ng --version`. If there's nothing outputted, please
angular-cli: 1.0.0-beta.5
node: 4.4.3
os: darwin x64

3). Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Option '-sd .' makes the error saying: The Broccoli Plugin: [Funnel] failed with: Error: ENAMETOOLONG: name too long, scandir....

I've run ng with the following options on empty directory 'client'
~/prj/ar-survey2/client$  ng init -n arsvy -sd . --style cass
~/prj/ar-survey2/client$  ng serve
Then it shows error like the log on 4

4). The log given by the failure. Normally this include a stack trace and some
   more information.

The Broccoli Plugin: [Funnel] failed with:
Error: ENAMETOOLONG: name too long, scandir '/Users/jin/prj/ar-survey2/client/tmp/funnel-input_base_path-aGJIsWBr.tmp/0//tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/tmp/broccoli_merge_trees-input_base_path-W5G2W4pp.tmp/0/node_modules/angular-cli/node_modules/angular-cli/node_modules/broccoli-babel-transpiler/node_modules/babel-core/node_modules/regenerator/node_modules/defs/node_modules/yargs/node_modules/cliui/node_modules/center-align/node_modules/align-text/node_modules/kind-of/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:66:20)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)
    at _walkSync (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/walk-sync/index.js:76:32)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._getAssetsTree (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/lib/broccoli/angular2-app.js:374:12)
    at Angular2App._buildTree (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/lib/broccoli/angular2-app.js:115:26)
    at new Angular2App (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/jin/prj/ar-survey2/client/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/jin/prj/ar-survey2/client/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)

**Comment by filipesilva** [comment]
I tried reproducing in windows and couldn't get the same output:

```
filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/dev/testing
$ mkdir client

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/dev/testing
$ cd client

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/dev/testing/client
$ ng init -n arsvy -sd client --style sass
installing ng2
  create .clang-format
  create .editorconfig
  create client\app\arsvy.component.sass
  create client\app\arsvy.component.html
  create client\app\arsvy.component.spec.ts
  create client\app\arsvy.component.ts
  create client\app\environment.ts
  create client\app\index.ts
  create client\app\shared\index.ts
  create client\favicon.ico
  create client\index.html
  create client\main.ts
  create client\system-config.ts
  create client\tsconfig.json
  create client\typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config\environment.dev.ts
  create config\environment.js
  create config\environment.prod.ts
  create config\karma-test-shim.js
  create config\karma.conf.js
  create config\protractor.conf.js
  create e2e\app.e2e.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create e2e\typings.d.ts
  create .gitignore
  create package.json
  create public\.npmignore
  create tslint.json
  create typings.json
- Installing packages for tooling via npm
├── es6-shim (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

Installed packages for tooling via npm.

filipe.silva@DESKTOP-7ND6T3R MINGW64 /E/dev/testing/client
$ ng serve
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 1678ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
vendor                                        | 874ms
BroccoliTypeScriptCompiler                    | 640ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
vendor (1)                                    | 874ms
BroccoliTypeScriptCompiler (1)                | 640ms
```

Can you perhaps provide me with a repo I can clone which exhibits this issue?

**Comment by jin-chong** [comment]
Hi filipesilva ,

Thanks you for your reply.
So sorry, I found there was something wrong with my posting. :(  It's my bad.

I did with '-sd .' instead of '-sd client'.

To sum up,
~/prj/ar-survey2/client$ ng init -n arsvy -sd . --style cass
~/prj/ar-survey2/client$ ng serve

Then I got error.

**Comment by filipesilva** [comment]
Ah that makes sense, that probably generated a very weird and broken folder structure. Glad to hear it's solved!

**Comment by filipesilva** [comment]
To be clear though, you really must provide a folder name to the `-sd` argument, it cannot be `.`.

**Comment by jin-chong** [comment]
Hi filipesilva ,
Thank you for your reply.
I see, I will give folder name on '-sd' rather than '.'.
As a full stack developer, I wanted to put server and client under same project folder.  I tried to structure folders like below:

MyProject ----
     |---server
     |--node_modules : this is for server and gulp
     |--client
            |--config
            |--app
            |--node_modules: this is for client
......

But if angular-cli doesn't not allow that, I won't try it.
Thank you a lot for your support and confirmation.
Jin.

**Comment by filipesilva** [comment]
The CLI doesn't have configuration for folders as you described, no. The best alternative I can come up with is for you to do `-sd client`, which will create `src/client/app`, and you manually create `src/server`. This way both would share the same `node_modules` though.

**Comment by jin-chong** [comment]
Thanks for your advice.  I will try your suggestion.
