### ISSUE TITLE
e2e fails

### ISSUE THREAD

**Issue by gh0st** [angular/angular-cli#9391]
### Versions
```
@angular/cli: 1.4.9
node: 6.11.1
os: win32 x64
@angular/animations: 4.4.2
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/compiler-cli: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.6
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/platform-server: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.4.9
typescript: 2.5.2
```

### Repro steps

* ng e2e

### Observed behavior
```
D:\Developer\project>ng e2e
Your global Angular CLI version (1.6.4) is greater than your local
version (1.4.9). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is listening on localhost:49155, open your browser on http://localhost:49155/ **
Date: 2018-01-25T23:19:06.039Z
Hash: 2e9dc3e24348a186ce97
Time: 19715ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 5.36 MB {inline} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 503 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 351 kB {inline} [initial] [rendered]

webpack: Compiled successfully.
[15:19:06] I/direct - Using ChromeDriver directly...
[15:19:06] I/launcher - Running 1 instances of WebDriver
[15:19:06] I/update - chromedriver: file exists D:\Developer\project\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.26win32.zip
[15:19:06] I/update - chromedriver: unzipping chromedriver_2.26win32.zip
[15:19:06] E/launcher - EPERM: operation not permitted, rename 'D:\Developer\project\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver.exe' -> 'D:\Developer\project\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.26.exe'
[15:19:06] E/launcher - Error: EPERM: operation not permitted, rename 'D:\Developer\project\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver.exe' -> 'D:\Developer\project\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.26.exe'
    at Error (native)
    at Object.fs.renameSync (fs.js:810:18)
    at unzip (D:\Developer\project\node_modules\protractor\node_modules\webdriver-manager\lib\cmds\update.ts:229:6)
    at D:\Developer\project\node_modules\protractor\node_modules\webdriver-manager\lib\cmds\update.ts:199:7
    at _fulfilled (D:\Developer\project\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\Developer\project\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\Developer\project\node_modules\protractor\node_modules\q\q.js:796:13)
    at D:\Developer\project\node_modules\protractor\node_modules\q\q.js:604:44
    at runSingle (D:\Developer\project\node_modules\protractor\node_modules\q\q.js:137:13)
    at flush (D:\Developer\project\node_modules\protractor\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[15:19:06] E/launcher - Process exited with error code 199
```

### Desired behavior
Run end to end tests.

**Comment by filipesilva** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the http://www.protractortest.org/#/ project or file an issue on their issue tracker.
