### ISSUE TITLE
running "ng test" fails with error   "EMFILE: too many open files"

### ISSUE THREAD

**Issue by girishla** [angular/angular-cli#941]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Windows 7**

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
angular-cli: 1.0.0-beta.5
node: 4.4.2
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

vanilla app created using cli. No customisations.,

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Error: EMFILE: too many open files, open 'C:\working\esl\node_modules\@angular\core\src\di.d.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at CustomLanguageServiceHost.getScriptSnapshot (C:\working\esl\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:392:44)
    at HostCache.createEntry (C:\working\esl\node_modules\typescript\lib\typescript.js:48033:44)
    at HostCache.getOrCreateEntry (C:\working\esl\node_modules\typescript\lib\typescript.js:48056:25)
    at Object.getOrCreateSourceFile [as getSourceFile] (C:\working\esl\node_modules\typescript\lib\typescript.js:48956:53)
    at findSourceFile (C:\working\esl\node_modules\typescript\lib\typescript.js:40307:29)
    at processImportedModules (C:\working\esl\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (C:\working\esl\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (C:\working\esl\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (C:\working\esl\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (C:\working\esl\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (C:\working\esl\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (C:\working\esl\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (C:\working\esl\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (C:\working\esl\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (C:\working\esl\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (C:\working\esl\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (C:\working\esl\node_modules\typescript\lib\typescript.js:40352:17)
    at processImportedModules (C:\working\esl\node_modules\typescript\lib\typescript.js:40388:44)
    at findSourceFile (C:\working\esl\node_modules\typescript\lib\typescript.js:40352:17)

The broccoli plugin was instantiated at:
    at BroccoliTypeScriptCompiler.Plugin (C:\working\esl\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (C:\working\esl\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:21:10)
    at BroccoliTypeScriptCompiler (C:\working\esl\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:31:10)
    at Angular2App._getTsTree (C:\working\esl\node_modules\angular-cli\lib\broccoli\angular2-app.js:321:18)
    at Angular2App._buildTree (C:\working\esl\node_modules\angular-cli\lib\broccoli\angular2-app.js:116:23)
    at new Angular2App (C:\working\esl\node_modules\angular-cli\lib\broccoli\angular2-app.js:53:23)
    at module.exports (C:\working\esl\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\working\esl\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\working\esl\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\working\esl\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\working\esl\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\build-watch.js:17:16)
    at C:\working\esl\node_modules\angular-cli\addon\ng2\commands\test.js:69:46
    at lib$rsvp$$internal$$tryCatch (C:\working\esl\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\working\esl\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\working\esl\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\working\esl\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by girishla** [comment]
closing as it probably is duplicate of #864
