### ISSUE TITLE
Problem installing angular-cli on Windows 7

### ISSUE THREAD

**Issue by dargoan** [angular/angular-cli#942]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.5
node: 5.10.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I tried to do : npm install -g angular-cli.
I waited more than 20 minutes for the installation of "packages for tooling via npm". So, i killed the process.
Then, when i tried to do ng serve, i had the following (see Q4).

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Livereload server on http://localhost:49155
Serving on http://localhost:4200/
The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory: typings
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angula
r-cli\node_modules\broccoli-sane-watcher\index.js:90:11)
    at C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modules\angular-cli-broccoli\lib\builder
.js:95:35
    at lib$rsvp$$internal$$tryCatch (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modules\rs
vp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modu
les\rsvp\dist\rsvp.js:1048:17)
    at C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:331:11
    at lib$rsvp$asap$$flush (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\
rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\broccoli-funnel\node_modules\broccoli-plug
in\index.js:7:31)
    at new Funnel (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\broccoli-funnel\index.js:44:10)
    at Angular2App._buildInputTree (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\lib\broccoli\angular2-app.js:85:7)
    at new Angular2App (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\lib\broccoli\angular2-app.js:51:41)
    at module.exports (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\an
gular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\lib\mo
dels\builder.js:89:10)
    at new Class (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modules\core-object\core-obje
ct.js:18:12)
    at Class.module.exports.Task.extend.run (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\lib\tas
ks\serve.js:15:19)
    at C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modules\rs
vp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modu
les\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsv
p\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\documents\S087837\Documents\Working\gitrepo\angular-cli\onepiece\node_modules\angular-cli\node_modules\angular-cli\node_modules\rsvp\dist\
rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.
Thank you

**Comment by deebloo** [comment]
it doesn't look like you dependencies finishing installing

**Comment by dargoan** [comment]
Allright, should i try again from scratch? I'll try from home (maybe there are some issues with authentication proxy from work).

**Comment by deebloo** [comment]
@dargoan I would start there yeah.

**Comment by filipesilva** [comment]
I agree, it sounds like there might have been an issue in installing the npm dependencies for the project. Doing `ng new` usually takes a couple of minutes, but it should never be more than 5 in worst case scenario.

You can also try doing a more granular approach:

```
ng new project --skip-npm
cd project
npm install
```
