### ISSUE TITLE
Cannot find module 'uglifyjs-webpack-plugin'

### ISSUE THREAD

**Issue by adamdport** [angular/angular-cli#9431]
### Versions
```
Angular CLI: 1.6.6
Node: 8.9.3
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.6
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
```

### Repro steps

* Update @angular/cli to 1.6.6
* run `ng serve`

### Observed behavior
```
$ ng serve
Cannot find module 'uglifyjs-webpack-plugin'
Error: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\repos\myRepo\node_modules\@angular\cli\models\webpack-configs\production.js:13:24)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\repos\myRepo\node_modules\@angular\cli\models\webpack-configs\index.js:9:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

### Mention any other details that might be useful (optional)
Updating to 1.6.6 gives me an error. 1.6.5 works fine. I tried updating all of the @angular suite to 1.6.6 but the problem remains, `Cannot find module 'uglifyjs-webpack-plugin'`.

Is this a bug? How can I go about debugging it? I've tried `npm cache verify` before `npm install` after wiping out `node_modules` and my `package-lock.json` to no avail. I'm using npm v5.5.1.

**Comment by cfremgen** [comment]
https://github.com/angular/angular-cli/issues/9428

**Comment by adamdport** [comment]
#9428 is a duplicate of #9427, and I couldn't find **either** of them before making this issue because they're closed. I guess I'll close this too as there seems to be a resolution there...
