### ISSUE TITLE
ng lint: The specified path does not exist: 'e2e/tsconfig.e2e.json'

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#9487]
### Versions
```
Angular CLI: 1.6.7
Node: 9.5.0
OS: linux x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.1.1
@angular/cli: 1.6.7
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.1.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack-dashboard: 1.1.1
webpack: 3.10.0
Done in 0.34s.
```

### Repro steps
* Remove e2e folder
* run `ng lint`

### Observed behavior
```
error TS5058: The specified path does not exist: 'e2e/tsconfig.e2e.json'.

FatalError: error TS5058: The specified path does not exist: 'e2e/tsconfig.e2e.json'.

    at new FatalError (/home/maxime/Documents/code/some-project/node_modules/tslint/lib/error.js:27:28)
    at Function.Linter.createProgram (/home/maxime/Documents/code/some-project/node_modules/tslint/lib/linter.js:55:19)
    at lintConfigs.map (/home/maxime/Documents/code/some-project/node_modules/@angular/cli/tasks/lint.js:42:34)
    at Array.map (<anonymous>)
    at Class.run (/home/maxime/Documents/code/some-project/node_modules/@angular/cli/tasks/lint.js:39:14)
    at Class.run (/home/maxime/Documents/code/some-project/node_modules/@angular/cli/commands/lint.js:46:25)
    at resolve (/home/maxime/Documents/code/some-project/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
    at Class.validateAndRun (/home/maxime/Documents/code/some-project/node_modules/@angular/cli/ember-cli/lib/models/command.js:240:12)
    at Promise.resolve.then.then (/home/maxime/Documents/code/some-project/node_modules/@angular/cli/ember-cli/lib/cli/cli.js:140:24)
error Command failed with exit code 1.
```

### Desired behavior
If I don't have the `e2e` folder or `e2e/tsconfig.e2e.json` file, I expect `ng lint` not to crash.

**Comment by clydin** [comment]
The `e2e` folder was deleted but there's still a reference to it in the project's `.angular-cli.json` file.
All references to the deleted folder should be removed as well.  ([relevant schematic section](https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/__dot__angular-cli.json#L48))
