### ISSUE TITLE
use 'ng new' created, after that, got an error when create a new component by 'ng g c ...' 

### ISSUE THREAD

**Issue by franksongca** [angular/angular-cli#9491]
### Versions
@angular/cli": "1.6.3

### Repro steps
* Step 1: ng new projectname
* Step 2: cd projectname
* Step 3: ng n c components/aaa

### Observed behavior
Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\git_work\testUi01\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by clydin** [comment]
Please upgrade to the latest patch release (1.6.7 currently) both globally and locally in the project exhibiting the issue.  If the issue still persists, please re-open the issue.
