### ISSUE TITLE
cannot upgrade angular-cli

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular-cli#9513]
windows 7
node v9.3.0
npm 5.6.0
angular-cli: 1.0.0-beta.28.3
node: 9.3.0
os: win32 x64
@angular/animations: 5.2.0
@angular/common: 5.2.0
@angular/compiler: 5.2.0
@angular/core: 5.2.0
@angular/forms: 5.2.0
@angular/http: 5.2.0
@angular/platform-browser: 5.2.0
@angular/platform-browser-dynamic: 5.2.0
@angular/router: 5.2.0
@angular/cli: 1.6.3
@angular/compiler-cli: 5.2.0
@angular/language-service: 5.2.0

my project use to build but not anymore

I referred to this
https://stackoverflow.com/questions/41403810/how-to-upgrade-angular-2-version-in-angular-cli-project

on attempt to upgrade angular-cli

i receive this

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\widgets>ng init
As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

installing ng2
C:\apache-tomcat-9.0.0.M17\webapps\ROOT\widgets\node_modules\isbinaryfile\index.js:12
      if (err || !stat.isFile()) return cb(err, false);
                                        ^

TypeError: cb is not a function
    at C:\apache-tomcat-9.0.0.M17\webapps\ROOT\widgets\node_modules\isbinaryfile\index.js:12:41
    at FSReqWrap.oncomplete (fs.js:166:21)

C:\apache-tomcat-9.0.0.M17\webapps\ROOT\widgets>

**Comment by nhhockeyplayer** [comment]
Ok this was caused by a previously lingering angular-cli package

the type signature changed to @angular/cli

solution

npm uninstall angular-cli
npm i @angular/cli
