### ISSUE TITLE
Why  i am not able to create component through cli

### ISSUE THREAD

**Issue by vaibhavmish** [angular/angular-cli#9532]
Output from: `ng --version`.
@angular/cli: 1.4.5
node: 6.11.1
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4
-->
```

### steps
ng g c shopping

### Observed behavior:
Cannot read property 'NullLogger' of undefined
TypeError: Cannot read property 'NullLogger' of undefined
    at SchematicEngine.createContext (C:\db\project\node_modules\@angular-devkit\schematics\src\engine\engine.js:75:38)
    at SchematicImpl.call (C:\db\project\node_modules\@angular-devkit\schematics\src\engine\schematic.js:35:38)
    at Promise (C:\db\project\node_modules\@angular\cli\tasks\schematic-run.js:77:23)
    at Class.run (C:\db\project\node_modules\@angular\cli\tasks\schematic-run.js:76:16)
    at Class.run (C:\db\project\node_modules\@angular\cli\commands\generate.js:149:33)
    at resolve (C:\db\project\node_modules\@angular\cli\ember-cli\lib\models\command.js:261:20)
    at Class.validateAndRun (C:\db\project\node_modules\@angular\cli\ember-cli\lib\models\command.js:240:12)
    at Promise.resolve.then.then (C:\db\project\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:140:24)


### Desired behavior
I expected to create a new component named as "shopping"


### i cleaned cache..uninstalled angular..installed it again but getting the same error.

**Comment by vaibhavmish** [comment]
if you ever encounter this  follow 3 steps 
uninstall angular
clean cache
reinstall angular
run  npm install --save @angular/cli@latest

run all these commands in admin.
