### ISSUE TITLE
ng test gives error on new install

### ISSUE THREAD

**Issue by rsaenen** [angular/angular-cli#9549]
### Versions
```bash
Angular CLI: 1.6.7
Node: 8.9.4
npm: 5.6.0
OS: linux x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps
* ng new my-project
* cd my-project
* ng test

### Observed behavior
```bash
10% building modules 1/1 modules 0 active08 02 2018 12:08:11.887:WARN [karma]: No captured browser, open http://localhost:9876/
08 02 2018 12:08:11.900:INFO [karma]: Front-end scripts not present. Compiling...
 95% emitting08 02 2018 12:08:22.565:ERROR [karma]: TypeError: Cannot read property 'apply' of undefined
    at /home/rsaenen/git/ng-val/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:70:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Desired behavior
Can run test.

### Mention any other details that might be useful (optional)
Tried with the latest node 9.5.0 and the LTS, got the same issue.

**Comment by tsvetomir** [comment]
It fails with `ng-build` as well:

```
 95% emitting/tmp/angular-aot/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40
		callbacks[i](err, result);
		            ^

TypeError: callbacks[i] is not a function
    at Storage.finished (/tmp/angular-aot/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /tmp/angular-aot/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /tmp/angular-aot/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
```

node v8.9.4
npm 5.6.0

**Comment by rsaenen** [comment]
Duplicate of #9550
