### ISSUE TITLE
WARNINGS running `ng serve` after upgrade to 1.6.8 from 1.6.1

### ISSUE THREAD

**Issue by TENDesign** [angular/angular-cli#9565]
I upgraded my angular-cli globally and locally, as well upgraded all of my angular packages on this project. After completing this, I am now seeing this warning when running `ng serve`. This problem did not exist prior to upgrading from 1.6.1 to 1.6.8

### Versions
```
Angular CLI: 1.6.8
Node: 9.2.0
OS: linux x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.2.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

* ng serve

### Observed behavior
```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-08T16:38:58.581Z
Hash: 1185ae70228b087719b1
Time: 15681ms
chunk {account.module} account.module.chunk.js () 10.3 kB  [rendered]
chunk {common} common.chunk.js (common) 283 kB  [rendered]
chunk {contact.module} contact.module.chunk.js () 126 kB  [rendered]
chunk {dashboard.module} dashboard.module.chunk.js () 3.83 MB  [rendered]
chunk {emails.module} emails.module.chunk.js () 10.2 kB  [rendered]
chunk {firm.module} firm.module.chunk.js () 9.93 kB  [rendered]
chunk {funnel.module} funnel.module.chunk.js () 101 kB  [rendered]
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {login.module} login.module.chunk.js () 10.8 kB  [rendered]
chunk {main} main.bundle.js (main) 197 kB [initial] [rendered]
chunk {media.module} media.module.chunk.js () 10.1 kB  [rendered]
chunk {pitch.module} pitch.module.chunk.js () 61.5 kB  [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 556 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 819 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 13.1 MB [initial] [rendered]

WARNING in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/scss/styles.scss
(Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5684:7: Can not find grid areas: sidebar, breadcrumb, content
NonErrorEmittedError: (Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5684:7: Can not find grid areas: sidebar, breadcrumb, content
    at Object.emitWarning (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/webpack/lib/NormalModule.js:117:16)
    at result.warnings.forEach (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:49)
    at Array.forEach (<anonymous>)
    at postcss.process.then (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:27)
    at <anonymous>
 @ ./src/scss/styles.scss 4:14-200
 @ multi ./node_modules/font-awesome/scss/font-awesome.scss ./src/scss/styles.scss

WARNING in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/scss/styles.scss
(Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5725:7: Can not find grid areas: header, one, two
NonErrorEmittedError: (Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5725:7: Can not find grid areas: header, one, two
    at Object.emitWarning (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/webpack/lib/NormalModule.js:117:16)
    at result.warnings.forEach (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:49)
    at Array.forEach (<anonymous>)
    at postcss.process.then (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:27)
    at <anonymous>
 @ ./src/scss/styles.scss 4:14-200
 @ multi ./node_modules/font-awesome/scss/font-awesome.scss ./src/scss/styles.scss

WARNING in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/scss/styles.scss
(Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5736:9: Can not find grid areas: title, middle, utility
NonErrorEmittedError: (Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5736:9: Can not find grid areas: title, middle, utility
    at Object.emitWarning (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/webpack/lib/NormalModule.js:117:16)
    at result.warnings.forEach (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:49)
    at Array.forEach (<anonymous>)
    at postcss.process.then (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:27)
    at <anonymous>
 @ ./src/scss/styles.scss 4:14-200
 @ multi ./node_modules/font-awesome/scss/font-awesome.scss ./src/scss/styles.scss

WARNING in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/scss/styles.scss
(Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5764:7: Can not find grid areas: header, one, two, three, four, five, six, seven
NonErrorEmittedError: (Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5764:7: Can not find grid areas: header, one, two, three, four, five, six, seven
    at Object.emitWarning (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/webpack/lib/NormalModule.js:117:16)
    at result.warnings.forEach (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:49)
    at Array.forEach (<anonymous>)
    at postcss.process.then (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:27)
    at <anonymous>
 @ ./src/scss/styles.scss 4:14-200
 @ multi ./node_modules/font-awesome/scss/font-awesome.scss ./src/scss/styles.scss

WARNING in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/scss/styles.scss
(Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5820:9: Can not find grid areas: title, middle, utility
NonErrorEmittedError: (Emitted value instead of an instance of Error) autoprefixer: /mnt/c/Development/propelpr/Propel/src/main/client/src/scss/styles.scss:5820:9: Can not find grid areas: title, middle, utility
    at Object.emitWarning (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/webpack/lib/NormalModule.js:117:16)
    at result.warnings.forEach (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:49)
    at Array.forEach (<anonymous>)
    at postcss.process.then (/mnt/c/Development/propelpr/Propel/src/main/client/node_modules/postcss-loader/lib/index.js:149:27)
    at <anonymous>
 @ ./src/scss/styles.scss 4:14-200
 @ multi ./node_modules/font-awesome/scss/font-awesome.scss ./src/scss/styles.scss
```

**Comment by TENDesign** [comment]
I just did some digging on this. If I remove all my sass references using css grid, it builds without errors. could this possibly be a webpack issue?

**Comment by TENDesign** [comment]
Just curious if there was any movement on this. It is not effecting my build as the scss is still transpiling correctly, however it is pretty annoying!

**Comment by bhanukumar04** [comment]
+1

**Comment by JesseZomer** [comment]
+1

**Comment by niklas-dahl** [comment]
same issue here, using `/* autoprefixer: off */` at the top of every scss file that uses grid layout as a workaround for now..

**Comment by niklas-dahl** [comment]
maby related, after updating I'm also getting autoprefixer warnings about a library css file:
```
WARNING in ./src/styles.scss
(Emitted value instead of an instance of Error) autoprefixer: /builds/<project root>/node_modules/intro.js/minified/introjs.min.css:1:615: Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`.
NonErrorEmittedError: (Emitted value instead of an instance of Error) autoprefixer: /builds/<project root>/node_modules/intro.js/minified/introjs.min.css:1:615: Gradient has outdated direction syntax. Replace `cover` to `farthest-corner`.
    at Object.emitWarning (/builds/<project root>/node_modules/webpack/lib/NormalModule.js:117:16)
    at result.warnings.forEach (/builds/<project root>/node_modules/postcss-loader/lib/index.js:149:49)
    at Array.forEach (<anonymous>)
    at postcss.process.then (/builds/<project root>/node_modules/postcss-loader/lib/index.js:149:27)
    at <anonymous>
 @ multi ./src/styles.scss
```
I'm importing this file via `@import '../node_modules/intro.js/minified/introjs.min.css';` in `styles.scss`.
very annoying since I cant change that file..
