### ISSUE TITLE
Lazy loading doesn't work with the custom root path in .angular-cli.json

### ISSUE THREAD

**Issue by NiKlimenko** [angular/angular-cli#9590]
### Versions
```
Angular CLI: 1.6.4
Windows 10.
```

### Repro steps
* Create a simple Angular project via Angular CLI with the changed root directory in the .angular-cli.json
* Create another one component with the module
* Add a new module to app-routing.module.ts as lazy route

### Observed behavior
```
With custom root: "root": "./src/demo-app/src"
Routing: {path: 'button', loadChildren: 'app/button-demo/button-demo.module#ButtonDemoModule'}

Error:
ERROR in Error: Could not resolve module app/button-demo/button-demo.module relative to F:/project/src/demo-app/src/app/app-routing.module.ts 
at StaticSymbolResolver.getSymbolByModule (F:\project\node_modules\@angular\compiler\bundles\compiler.umd.js:29765:30) 
at StaticReflector.resolveExternalReference (F:\project\node_modules\@angular\compiler\bundles\compiler.umd.js:31610:62) 
at parseLazyRoute (F:\project\node_modules\@angular\compiler\bundles\compiler.umd.js:29049:55) 
at listLazyRoutes (F:\project\node_modules\@angular\compiler\bundles\compiler.umd.js:29011:36) 
at visitLazyRoute (F:\project\node_modules\@angular\compiler\bundles\compiler.umd.js:31175:47) 
at AotCompiler.listLazyRoutes (F:\project\node_modules\@angular\compiler\bundles\compiler.umd.js:31143:20) 
at AngularCompilerProgram.listLazyRoutes (F:\project\node_modules\@angular\compiler-cli\src\transformers\program.js:156:30) 
at Function.NgTools_InternalApi_NG_2.listLazyRoutes (F:\project\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36) 
at AngularCompilerPlugin._getLazyRoutesFromNgtools (F:\project\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:248:66) 
at Promise.resolve.then.then (F:\project\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:571:50) 
at <anonymous> 
at process._tickCallback (internal/process/next_tick.js:160:7)
```

### Desired behavior

Related issue:  #9198

**Comment by hansl** [comment]
Hi @NiKlimenko 

Could you provide a repository that has this issue?

**Comment by NiKlimenko** [comment]
Well, with 'src/app/button-demo/button-demo.module#ButtonDemoModule' seems to work, sorry about the noise.
