### ISSUE TITLE
Cannot find module 'read-cache'

### ISSUE THREAD

**Issue by olufemioyedepo** [angular/angular-cli#9591]
I Just updated my angular cli to the latest and when i run ng-serve on my project, i get this "Cannot find module 'read-cache' "

**Comment by olufemioyedepo** [comment]
Here's the full stack tracce

Error: Cannot find module 'read-cache'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator.HP-PAVILION\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\postcss-import\lib\load-content.js:3:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator.HP-PAVILION\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\postcss-import\index.js:11:21)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

**Comment by ddimaria** [comment]
Did you run `npm cache clean`?

**Comment by olufemioyedepo** [comment]
Yes I did. I even ran npm cache verify

**Comment by olufemioyedepo** [comment]
Yes I did. I even ran npm cache verify

**Comment by Brocco** [comment]
This seems like an issue with your npm installation. Please try deleting your `package-lock.json` as well your `node_modules` folder.

If the issue persists please open a new issue following the issue template to ensure all relevant information is captured.

Thanks!

**Comment by olufemioyedepo** [comment]
i followed your instructions and ran `npm install`. Everything is fine now. Thanks @Brocco
