### ISSUE TITLE
@angular/cli: 1.6.8 bug with windows 10

### ISSUE THREAD

**Issue by amwwgjj** [angular/angular-cli#9594]
PS D:\TypeScriptWork\myproj> ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.8
Node: 7.9.0
OS: win32 x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
PS D:\TypeScriptWork\myproj> ng server --prod
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open 'D:\TypeScriptWork\myproj\node_modules\_@angular_core@5.2.4@@angular\package.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at LicenseExtractor.readPackageJson (D:\TypeScriptWork\myproj\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:124:23)
    at LicenseExtractor.parsePackage (D:\TypeScriptWork\myproj\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (D:\TypeScriptWork\myproj\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (D:\TypeScriptWork\myproj\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:21:21)
    at moduleCallback (D:\TypeScriptWork\myproj\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:80:61)
    at Set.forEach (native)
    at Chunk.forEachModule (D:\TypeScriptWork\myproj\node_modules\_webpack@3.10.0@webpack\lib\Chunk.js:159:17)
    at D:\TypeScriptWork\myproj\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:89:27
    at Array.forEach (native)
    at Compiler.<anonymous> (D:\TypeScriptWork\myproj\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:65:32)
    at next (D:\TypeScriptWork\myproj\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:204:14)
    at D:\TypeScriptWork\myproj\node_modules\_html-webpack-plugin@2.30.1@html-webpack-plugin\index.js:204:9
    at PassThroughHandlerContext.finallyHandler (D:\TypeScriptWork\myproj\node_modules\_bluebird@3.5.1@bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (D:\TypeScriptWork\myproj\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)

**Comment by clydin** [comment]
Duplicate of #7958.  Please follow that issue and provide any additional information for the exhibited problem.
