### ISSUE TITLE
cannot find module './utils/escape' error

### ISSUE THREAD

**Issue by marvinrusinek** [angular/angular-cli#9599]
Hi, I installed a package ng2-go-top-button and am no longer need to use it. I'm not sure why I'm getting this error message (see below). Please can you help me to fix this problem ASAP. Thank you SO much.

**UPDATE2:**  installed copy-webpack-plugin and 'node-forge', now I'm getting error:
 ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/bootstrap/dist/c
ss/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser major
    at error (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\node_modules\autoprefixer\node_modules\browserslist\index.js:37:11)
    at Function.browserslist.checkName (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\node_modules\autoprefixer\node_modules\browserslist\index.js:320:18)
    at Function.select (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\node_modules\autoprefixer\node_modules\browserslist\index.js:438:37)
    at C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\node_modules\autoprefixer\node_modules\browserslist\index.js:207:41
    at Array.forEach (native)
    at browserslist (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\node_modules\autoprefixer\node_modules\browserslist\index.js:196:13)
    at Browsers.parse (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\node_modules\autoprefixer\lib\browsers.js:44:14)
    at new Browsers (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\node_modules\autoprefixer\lib\browsers.js:39:28)
    at loadPrefixes (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\node_modules\autoprefixer\lib\autoprefixer.js:56:18)
    at plugin (C:\Users\multi\Desktop\portfolioWeb\node_modules\@angular\cli\node_modules\autoprefixer\lib\autoprefixer.js:62:18)
    at LazyResult.run (C:\Users\multi\Desktop\portfolioWeb\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:277:20)
    at LazyResult.asyncTick (C:\Users\multi\Desktop\portfolioWeb\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:192:32)
    at LazyResult.asyncTick (C:\Users\multi\Desktop\portfolioWeb\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:204:22)
    at processing.Promise.then._this2.processed (C:\Users\multi\Desktop\portfolioWeb\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:231:20)
    at LazyResult.async (C:\Users\multi\Desktop\portfolioWeb\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:228:27)
    at LazyResult.then (C:\Users\multi\Desktop\portfolioWeb\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:134:21)
 @ ./node_modules/bootstrap/dist/css/bootstrap.min.css 4:14-131
 @ multi ./node_modules/foundation-sites/dist/css/foundation.min.css ./node_modules/bootstrap/dist/css/bootstrap.min.css ./node_modules/font-awesome/css/font-awesome.min.css ./
src/styles/fontawesome-all.min.css ./src/styles/ionicons.min.css ./src/styles/animate.css ./src/styles/styles.scss
ERROR in node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305: Module '"C:/Users/multi/Desktop/portfolioWeb/node_modules/@angular/cor
e/core"' has no exported member 'OpaqueToken'.

**UPDATED:** I ran the following command to remove the package, but I'm still getting the same error.
npm uninstall --save-dev ng2-go-top-button

I also tried installing yarn and got this error at the bottom of my yarn logfile:
yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: EPERM: operation not permitted, open 'C:\Users\multi\Desktop\portfolioWeb\node_modules\core-js\modules\_an-object.js'
      at Error (native)

---------------------------------------
ng serve --port=5200
Your global Angular CLI version (1.6.3) is greater than your local
version (1.5.5). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
Cannot find module './utils/escape'
Error: Cannot find module './utils/escape'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\multi\Desktop\portfolioWeb\node_modules\copy-webpack-plugin\dist\preProcessPattern.js:16:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\multi\Desktop\portfolioWeb\node_modules\copy-webpack-plugin\dist\index.js:7:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by clydin** [comment]
The `Unknown browser major` issue is described in this issue: https://github.com/angular/angular-cli/issues/9288 and is solved in the upcoming version 1.7.0
