### ISSUE TITLE
I'm getting error "ERROR in Error: Error encountered resolving symbol values statically. Reference to a non-exported function (position 49:10 in the original .ts file), resolving symbol AppModule in" while i'm working in Model-driven form or Reactive Form #1

### ISSUE THREAD

**Issue by kveeresh49** [angular/angular-cli#9603]
[angular-2.zip](https://github.com/angular/angular-cli/files/1716352/angular-2.zip)
I'm getting error "ERROR in Error: Error encountered resolving symbol values statically. Reference to a non-exported function (position 49:10 in the original .ts file), resolving symbol AppModule in" while i'm working in Model-driven form or Reactive Form
--ERROR in Error: Error encountered resolving symbol values statically. Reference to a non-exported function (position 49:10 in the original .ts file), resolving symbol AppModule in C:/Users/veereshbk/Desktop/angular-project-events/events-app/new-event-app/src/app/app.module.ts
at positionalError (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@angular\compiler\bundles\compiler.umd.js:25134:35)
at simplifyInContext (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@angular\compiler\bundles\compiler.umd.js:24977:27)
at StaticReflector.simplify (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@angular\compiler\bundles\compiler.umd.js:24991:13)
at StaticReflector.annotations (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@angular\compiler\bundles\compiler.umd.js:24418:41)
at _getNgModuleMetadata (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@angular\compiler-cli\src\ngtools_impl.js:138:31)
at _extractLazyRoutesFromStaticModule (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@angular\compiler-cli\src\ngtools_impl.js:109:26)
at Object.listLazyRoutesOfModule (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@angular\compiler-cli\src\ngtools_impl.js:53:22)
at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@angular\compiler-cli\src\ngtools_api.js:91:39)
at AotPlugin._getLazyRoutesFromNgtools (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@ngtools\webpack\src\plugin.js:212:44)
at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\veereshbk\Desktop\angular-project-events\events-app\new-event-app\node_modules@ngtools\webpack\src\plugin.js:448:24)
at process._tickCallback (internal/process/next_tick.js:103:7)
[app.zip](https://github.com/kveeresh49/angular-apppveeresh/files/1716316/app.zip

)
[app.zip](https://github.com/angular/angular-cli/files/1716347/app.zip)

I'm attached Z.p file also pls help me :) thanks

**Comment by kveeresh49** [comment]
[app.zip](https://github.com/angular/angular-cli/files/1719307/app.zip)

**Comment by filipesilva** [comment]
Hello, errors like `Error encountered resolving symbol values statically` mean that there has been some problem in statically analyzing your app.

Angular CLI always runs *some* statical analysis, even on JIT mode, in order to discover lazy-loaded routes.
This may cause a lot of static analysis errors to surface when importing your project into the CLI, or upgrading for older versions where we didn't run this kind of analysis.

Below are good resources on how to to debug these errors:
- https://angular.io/guide/metadata
- https://gist.github.com/chuckjaz/65dcc2fd5f4f5463e492ed0cb93bca60
- https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts

If your problem still persists, it might be a bug with the Angular Compiler itself.
In that case, please open an issue in https://github.com/angular/angular.
