### ISSUE TITLE
Server side rendering: TypeError: e is not a function. Angular Universal

### ISSUE THREAD

**Issue by ruimartins21** [angular/angular-cli#9675]
### Versions
```
Angular CLI: 1.5.0
Node: 7.9.0
OS: darwin x64
Angular: 4.3.6
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router
... tsc-wrapped

@angular/animations: 4.4.1
@angular/cli: 1.5.0
@angular/platform-server: 4.0.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.1
typescript: 2.2.2
webpack: 3.8.1

in macOS (Sierra)
```

### Repro steps
I'm trying to put universal angular in my application.
When I run the command (npm run build: ssr && npm run serve: ssr) it gives an error in compiling the server files.

The error that appears is as follows:
```
TypeError: e is not a function
    at /Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:629375
    at Object.OO5C (/Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:652270)
    at l (/Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:149)
    at Object.cDNS (/Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:838819)
    at l (/Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:149)
    at Object.gOWB (/Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:975243)
    at l (/Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:149)
    at Object.mPuX (/Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:1277800)
    at l (/Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:149)
    at Object.Zq8w (/Users/ruimartins/Desktop/Projects/angular/ecommerce/dist/server.js:123217:745657)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ecommerce@0.0.0 serve:ssr: node dist/server
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ecommerce@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ruimartins/.npm/_logs/2018-02-18T14_42_54_072Z-debug.log
```

this is my **app.server.module.ts**
```
import {NgModule} from '@angular/core';
import {ServerModule} from '@angular/platform-server';
import {ModuleMapLoaderModule} from '@nguniversal/module-map-ngfactory-loader';

import {AppModule} from './app.module';
import {AppComponent} from './app.component';

@NgModule({
    imports: [
        AppModule,
        ServerModule,
        ModuleMapLoaderModule
    ],
    bootstrap: [AppComponent],
})
export class AppServerModule {}

```

this is my **webpack.server.config.js**
```
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: {server: './server.ts'},
    resolve: {extensions: ['.js', '.ts']},
    target: 'node',
    // this makes sure we include node_modules and other 3rd party libraries
    externals: [/(node_modules|main\..*\.js)/],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: '[name].js'
    },
    module: {
        rules: [
            {test: /\.ts$/, loader: 'ts-loader'}
        ]
    },
    plugins: [
        // Temporary Fix for issue: https://github.com/angular/angular/issues/11580
        // for "WARNING Critical dependency: the request of a dependency is an expression"
        new webpack.ContextReplacementPlugin(
            /(.+)?angular(\\|\/)core(.+)?/,
            path.join(__dirname, 'src'), // location of your src
            {} // a map of your routes
        ),
        new webpack.ContextReplacementPlugin(
            /(.+)?express(\\|\/)(.+)?/,
            path.join(__dirname, 'src'),
            {}
        ),
        new webpack.DefinePlugin({
            window: undefined,
            document: undefined,
            $: undefined,
            jQuery: undefined,
            e: undefined,
            location: JSON.stringify({
                protocol: 'http',
                host: 'localhost',
            })
        })
    ]
}
```

### Desired behavior
I'm trying to implement universal angular, everything I did in my project in relation to this was following this link:

[https://github.com/angular/angular-cli/wiki/stories-universal-rendering](url)

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by ruimartins21** [comment]
Hi, @filipesilva 
The error that was happening was due to having jquery plugins in the project. So the way I solved it was to replace these plugins with others that did the same task. And in the end solved. 
My tip is, avoid even using jquery plugins in the angular.

Thank you so much for answering my question.
