### ISSUE TITLE
Change the location of tsconfig.app.json

### ISSUE THREAD

**Issue by dulcetti** [angular/angular-cli#9758]
Hello guys. I can change the location of files tsconfig.app.json and tsconfig.spec.json? I want to put these files inside `src/config` folder. But qhen i try, the Terminal show me an error.

### Versions
```
Windows 10
NPM 5.6.0
Node 6.11.4
NG 5.2
```

### Repro steps
* Put the file `tsconfig.app.json` inside config folder
* Change the location of `tsconfig.json` inside `extends` into tsconfig.app.json
* Run the start of project

### Observed behavior
Return the error:
```
ERROR in TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\typescript\lib\typescript.js:12619:109)
    at parseSourceFileWorker (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\typescript\lib\typescript.js:12551:26)
    at Object.parseSourceFile (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\typescript\lib\typescript.js:12477:26)
    at Object.createSourceFile (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\typescript\lib\typescript.js:12318:29)
    at new TypeScriptFileRefactor (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\@ngtools\webpack\src\refactor.js:79:35)
    at Object.resolveEntryModuleFromMain (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\@ngtools\webpack\src\entry_resolver.js:108:20)
    at Promise.resolve.then.then (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:255:54)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

My file `tsconfig.app.json`:
```js
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": "../../out-tsc/app",
        "baseUrl": "../",
        "module": "es2015",
        "types": []
    },
    "exclude": [
        "test.ts",
        "../**/*.spec.ts"
    ]
}
```

### Desired behavior
Regards.

**Comment by jotatoledo** [comment]
Changes should be reflectd in .`angular-cli.json` too most likely.

**Comment by filipesilva** [comment]
You would need to both change the locations in `.angular-cli.json` and to adjust the files/include/exclude fields in the tsconfigs. A tsconfig by default includes all files in its own folder and below. If you change you change the folder you are also changing what files it can be used for.

See http://www.typescriptlang.org/docs/handbook/tsconfig-json.html for more information.

**Comment by dulcetti** [comment]
@filipesilva Was a problem with Webpack. Thanks.

**Comment by shiamalon** [comment]
@dulcetti How did you solve it? having the exact same issue

**Comment by dulcetti** [comment]
@shiamalon Hi. My problem was resolved changing the follow code:
```
"hostReplacementPaths": {
    "environments\\environment.ts": "environments\\environment.ts"
},
```
To this:
```
"hostReplacementPaths": {
    "..\\environments\\environment.ts": "..\\environments\\environment.ts"
},
```
Regards.

**Comment by dulcetti** [comment]
@shiamalon ah, of course, on the `webpack.config.js`
