### ISSUE TITLE
mask CSS property breaks production build

### ISSUE THREAD

**Issue by piotrkabacinski** [angular/angular-cli#9769]
### Versions
```
Angular CLI: 1.6.8
Node: 8.9.4
npm: 5.6.0
OS: darwin x64
```

### Repro steps
Use [mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) property in *.scss file, example: `.foo { mask: url('~/../src/assets/images/spinner.svg'); }` and run build with production flag (`ng build --prod`). Prefixed property `-webkit-mask` causes same error.

### Observed behavior
Processed is stopped by Type error:
```
TypeError: error.setMessage is not a function
    at LazyResult.handleError (/Users/<path>/node_modules/postcss/lib/lazy-result.js:165:23)
    at /Users/<path>/node_modules/postcss/lib/lazy-result.js:199:27
    at <anonymous>
(node:4202) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: err.showSourceCode is not a function
(node:4202) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Build without production flag (`ng build`) doesn't cause this error.

### Desired behavior
Proper compiling process.

### Mention any other details that might be useful (optional)
If this issue is more related to PostCSS (6.0.19) dependency than Angular Cli Webpack configuration file please close it.

**Comment by piotrkabacinski** [comment]
Noticed this problem is caused by PostCSS and *.svg files in more cases (as well as using as a background-image). [This](https://github.com/canonical-websites/www.ubuntu.com/issues/2430#issuecomment-352907648) comment seems to be a reason of this.
