### ISSUE TITLE
no such file or directory, open '......node_modules\_@angular_core@5.2.6@@angular\package.json' when I use 'ng b -prod'

### ISSUE THREAD

**Issue by StarkL** [angular/angular-cli#9773]
### Versions

```
Angular CLI: 1.7.1
Node: 8.9.0
OS: win32 x64
Angular: 5.2.6
npm: 5.5.1
windows10
```

### Repro steps
```
step1: 
ng new test01 -style=scss --skip-install

step2: 
cd test01
cnpm i

step3:
ng b -prod
```

### Observed behavior
```
Unhandled rejection Error: ENOENT: no such file or directory, open 'D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_@angular_core@5.2.6@@angular\package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at LicenseExtractor.readPackageJson (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:124:23)
    at LicenseExtractor.parsePackage (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:21:21)
    at moduleCallback (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:80:61)
    at Set.forEach (<anonymous>)
    at Chunk.forEachModule (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_webpack@3.11.0@webpack\lib\Chunk.js:159:17)
    at D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:89:27
    at Array.forEach (<anonymous>)
    at Compiler.<anonymous> (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:65:32)
    at next (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:204:14)
    at D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_html-webpack-plugin@2.30.1@html-webpack-plugin\index.js:204:9
    at PassThroughHandlerContext.finallyHandler (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_bluebird@3.5.1@bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (D:\document\IT\pf-Nokia\2-demo\Angular4.x\写个简单的页面\pftest3\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)

```

### Desired behavior
```
Date: 2018-02-26T08:27:31.950Z
Hash: 040672432e4099d45c52
Time: 4800ms
chunk {0} polyfills.bf95165a1d5098766b92.bundle.js (polyfills) 59.4 kB [initial] [rendered]
chunk {1} main.4a642c0911995669d538.bundle.js (main) 239 kB [initial] [rendered]
chunk {2} styles.ac89bfdd6de82636b768.bundle.css (styles) 0 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]
```

### Mention any other details that might be useful (optional)
Every thing is normal three days ago.
But when I use 'ng new test01 -style=scss --skip-install' to create my project,
it will give me an Error like that after 'ng b -prod'.

Why?
How can I fix it?

**Comment by StarkL** [comment]
ok！

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by StarkL** [comment]
I don't know if I'm understand your meaning exactly.
I created a ng-program named 'repro-app' include the problem locally, then push it to [my github profile](https://github.com/StarkL/Angular-cli-repro-app).

Is it?

**Comment by mgechev** [comment]
@StarkL can you still reproduce the problem with the latest CLI?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)
