### ISSUE TITLE
running ng serve --o causes No NgModule metadata found for 'AppModule' 

### ISSUE THREAD

**Issue by patter59** [angular/angular-cli#9798]
### Versions
Angular CLI: 1.7.1
Node: 6.9.2
OS: win32 x64
Angular:

### Repro steps

I was simply following along with the angular Heroes tutorial from google. 
https://angular.io/tutorial
specifically the getting started portion 

npm install -g @angular/cli
ng new my-app
cd my-app
ng serve --open

### Observed behavior

**C:\Users\pattersongh\my-app>ng serve --o**
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-27T14:52:12.548Z
Hash: f7fb7162ff3849453a28
Time: 2349ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.94 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 41.5 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 853 kB [initial] [rendered]

ERROR in Error: **No NgModule metadata found for 'AppModule'.**
    at NgModuleResolver.resolve (C:\Users\pattersongh\my-app\node_modules\@angular\compiler\bundles\compiler.umd.js:20249:23)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\pattersongh\my-app\node_modules\@angular\compiler\bundles\compiler.umd.js:15218:60)
    at visitLazyRoute (C:\Users\pattersongh\my-app\node_modules\@angular\compiler\bundles\compiler.umd.js:31063:104)
    at AotCompiler.listLazyRoutes (C:\Users\pattersongh\my-app\node_modules\@angular\compiler\bundles\compiler.umd.js:31031:20)
    at AngularCompilerProgram.listLazyRoutes (C:\Users\pattersongh\my-app\node_modules\@angular\compiler-cli\src\transformers\program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\pattersongh\my-app\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (C:\Users\pattersongh\my-app\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:263:66)
    at Promise.resolve.then.then (C:\Users\pattersongh\my-app\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:583:50)
    at process._tickCallback (internal/process/next_tick.js:103:7)

webpack: Failed to compile.

### Desired behavior
i would like the web app to compile successfully

**Comment by filipesilva** [comment]
Heya, do you have the repro that you were using up somewhere? If you could put it up it would be very helpful. That's a very odd error to have on the tutorial.

**Comment by patter59** [comment]
i resolved the issue by modifying a .ts file and saving it
