### ISSUE TITLE
Failed Compile  Project Angular5 with the Angular CLI and GitHub Pages

### ISSUE THREAD

**Issue by LuiSanchez33** [angular/angular-cli#9833]
### Versions

Angular CLI: 1.6.8
Node: 8.9.1
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

### Repro steps

* Step 1 : git remote add origin https://github.com/LuiSanchez33/comics.git
* Step 2 : git push origin master -- force 
* Step 3: npm install -g gh-pages
* Step 4: ng build --prod --base-href /comics/   # ****FAIL !!!****

### Observed behavior

ERROR in ./node_modules/bootstrap/dist/css/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser major
    at error (D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:37:11)
    at Function.browserslist.checkName (D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:320:18)
    at Function.select (D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:438:37)
    at D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:207:41
    at Array.forEach (<anonymous>)
    at browserslist (D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:196:13)
    at D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\dist\index.js:261:51
    at LazyResult.run (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:277:20)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:192:32)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
 @ multi ./src/styles.css ./node_modules/bootstrap/dist/css/bootstrap.min.css
ERROR in ./node_modules/bootstrap/dist/css/bootstrap.min.css
Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser major
    at error (D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:37:11)
    at Function.browserslist.checkName (D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:320:18)
    at Function.select (D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:438:37)
    at D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:207:41
    at Array.forEach (<anonymous>)
    at browserslist (D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\node_modules\browserslist\index.js:196:13)
    at D:\Angular5\2. Comic\heroes-app\node_modules\postcss-merge-rules\dist\index.js:261:51
    at LazyResult.run (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:277:20)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:192:32)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at LazyResult.asyncTick (D:\Angular5\2. Comic\heroes-app\node_modules\postcss\lib\lazy-result.js:204:22)
    at runLoaders (D:\Angular5\2. Comic\heroes-app\node_modules\webpack\lib\NormalModule.js:195:19)
    at D:\Angular5\2. Comic\heroes-app\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at D:\Angular5\2. Comic\heroes-app\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (D:\Angular5\2. Comic\heroes-app\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (D:\Angular5\2. Comic\heroes-app\node_modules\postcss-loader\lib\index.js:196:71)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/bootstrap/dist/css/bootstrap.min.css
 @ multi ./src/styles.css ./node_modules/bootstrap/dist/css/bootstrap.min.css

### Desired behavior
I hope compile my app in github pages and can run on this website.

### Mention any other details that might be useful (optional)
file : angular-cli.json 

"styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],
      "scripts": [
        "../node_modules/popper.js/dist/umd/popper.js",
        "../node_modules/jquery/dist/jquery.slim.js",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js"
      ],

Thanks in advance!
Luis

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, the reproduction provided is no longer available.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
