### ISSUE TITLE
Module build failed error when run ' ng build prod'

### ISSUE THREAD

**Issue by hjnp** [angular/angular-cli#9842]
### Versions
```
Angular CLI: 1.6.8
Node: 8.9.4
OS: linux x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cli: 1.6.8
angular-devkit/build-optimizer: 0.0.42
angular-devkit/core: 0.0.29
angular-devkit/schematics: 0.0.52
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.8
schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

```

### Repro steps
Sorry can't put this public
The only erro is using this module: 
- https://github.com/maiyaporn/angular2-wizard
### Observed behavior
```
npm run build

> forms-app@0.0.0 build /home/bd/Desktop/yarilabs/zyper_github/forms-app
> ng build --prod

 15% building modules 45/63 modules 18 active ...de_modules/rxjs/_esm5/operator/map.jsNode#moveTo was deprecated. Use Container#append.
Date: 2018-03-01T18:59:33.768Z
Hash: ac2b2d9cf4426802b526
Time: 26001ms
chunk {0} polyfills.f20484b2fa4642e0dca8.bundle.js (polyfills) 59.4 kB [initial] [rendered]
chunk {1} main.26dea4c8d8dffdb027a0.bundle.js (main) 394 kB [initial] [rendered]
chunk {2} styles.145710231fe3a3b7370c.bundle.css (styles) 181 kB [initial] [rendered]
chunk {3} inline.9c537eabd1c558cdea90.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in ./node_modules/angular2-wizard/src/wizard-step.component.ngfactory.ts
Module build failed: Error: /home/bd/Desktop/yarilabs/zyper_github/forms-app/node_modules/angular2-wizard/src/wizard-step.component.ngfactory.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/bd/Desktop/yarilabs/zyper_github/forms-app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:663:23)
    at plugin.done.then (/home/bd/Desktop/yarilabs/zyper_github/forms-app/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./src/app/forms/become-a-fan/become-a-fan.component.ngfactory.js 14:0-99
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/angular2-wizard/src/wizard.component.ngfactory.ts
Module build failed: Error: /home/bd/Desktop/yarilabs/zyper_github/forms-app/node_modules/angular2-wizard/src/wizard.component.ngfactory.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/bd/Desktop/yarilabs/zyper_github/forms-app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:663:23)
    at plugin.done.then (/home/bd/Desktop/yarilabs/zyper_github/forms-app/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./src/app/forms/become-a-fan/become-a-fan.component.ngfactory.js 12:0-94
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forms-app@0.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forms-app@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bd/.npm/_logs/2018-03-01T18_59_33_810Z-debug.log
```

### Mention any other details that might be useful (optional)
When i run this 
`ng serve`  the app compiles and show without errors! its OK!
But on `ng build --prod` 
Fail !

i Try to add the follow lines for this angular component on this file: 
* tsconfig.json
   -> 
  "include": [
    "src/**/*",
    "node_modules/angular2-wizard/dist/index.d.ts",
  ]
But not working as well. Why this compile on ng serve and not on prod build ? Anyone can help with this ?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
