### ISSUE TITLE
problem with karma tests after cli 1.7.2

### ISSUE THREAD

**Issue by davidkarlsen** [angular/angular-cli#9850]
### Versions
```
Angular CLI: 1.7.2
Node: 9.6.1
OS: linux x64
Angular: 
...
```

### Repro steps
* Step 1
Have classes:
```
import {Injectable} from '@angular/core';
import {MatSnackBar, MatSnackBarRef} from '@angular/material';
import {MessageComponent} from '../_core/message/message.component';
import {MessageType} from '../models/message.type';

@Injectable()
export class MessageService {
    constructor(private snackBar: MatSnackBar) {
    }

    public submit(messageKey: string, messageType: MessageType): MatSnackBarRef<MessageComponent> {
      let panelClass;

      switch(messageType) {
        case MessageType.ERROR: {
          panelClass = 'feedback-error';
          break;
        }
        case MessageType.SUCCESS: {
          panelClass = 'feedback-success';
          break;
        }
        case MessageType.HINT: {
          panelClass = 'feedback-hint';
          break;
        }
        case MessageType.WARNING: {
          panelClass = 'feedback-warning';
          break;
        }
      }
      return this.snackBar.openFromComponent(MessageComponent, {
        data: {
          messageKey: messageKey,
          messageType: messageType,
        },
        duration: 10000,
        panelClass: panelClass
      });
    }

}

```
```
import {Component, Inject} from '@angular/core';
import {MAT_SNACK_BAR_DATA} from '@angular/material';
import {MessageType} from 'app/models/message.type';

/**
 * Component for system-feedback messages using
 * <a href="https://material.angular.io/components/snack-bar/overview>Material SnackBar</a>
 */
@Component({
  selector: 'jfr-message',
  templateUrl: './message.component.html'
})
export class MessageComponent {
  constructor(@Inject(MAT_SNACK_BAR_DATA) public data: any) {
    switch (data.messageType) {
      case MessageType.SUCCESS: {
        data.icon = 'check-circle';
        break;
      }
      case MessageType.ERROR: {
        data.icon = 'error';
        break;
      }
      case MessageType.HINT: {
        data.icon = 'lightbulb outline';
        break;
      }
      case MessageType.WARNING: {
        data.icon = 'warning';
        break;
      }
      default: {
        data.icon = 'check-circle';
        break;
      }
    }
  }
}

```
* Step 2
Have a karma-test which invokes the service.

### Observed behavior
```
 <system-out>
    <![CDATA[Chrome 64.0.3282 (Mac OS X 10.13.3) ERROR: 'Unhandled Promise rejection:', 'Found the synthetic listener @state.done. Please include either "BrowserAnimationsModule" or "NoopAn
imationsModule" in your application.', '; Zone:', 'ProxyZone', '; Task:', 'Promise.then', '; Value:', Error{ngDebugContext: DebugContext_{view: Object{def: ..., parent: ..., viewContainerPa
rent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}, nodeIndex: 0, nodeDef: Obje
ct{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matche
dQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..
., ngContent: ...}, elDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., c
hildMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., prov
ider: ..., text: ..., query: ..., ngContent: ...}, elView: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., 
root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}}, ngErrorLogger: function () { ... }}, 'Error: Found the synthetic listener @state.done. Please include either "B
rowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/esm5/platform-browser.js:3005:1)
    at DefaultDomRenderer2.webpackJsonp../node_modules/@angular/platform-browser/esm5/platform-browser.js.DefaultDomRenderer2.listen (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/esm5/platform-browser.js:2989:1)
    at DebugRenderer2.webpackJsonp../node_modules/@angular/core/esm5/core.js.DebugRenderer2.listen (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:15433:1)
    at listenToElementOutputs (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:10576:56)
    at createViewNodes (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:13709:1)
    at createRootView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:13631:1)
    at callWithDebugContext (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:15056:26)
    at Object.debugCreateRootView [as createRootView] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:14339:1)
    at ComponentFactory_.webpackJsonp../node_modules/@angular/core/esm5/core.js.ComponentFactory_.create (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:11236:26)
    at ComponentFactoryBoundToModule.webpackJsonp../node_modules/@angular/core/esm5/core.js.ComponentFactoryBoundToModule.create (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:4023:1)
    at DomPortalOutlet.webpackJsonp../node_modules/@angular/cdk/esm5/portal.es5.js.DomPortalOutlet.attachComponentPortal (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/cdk/esm5/portal.es5.js:402:1)
    at DomPortalOutlet.webpackJsonp../node_modules/@angular/cdk/esm5/portal.es5.js.BasePortalOutlet.attach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/cdk/esm5/portal.es5.js:284:1)
    at OverlayRef.webpackJsonp../node_modules/@angular/cdk/esm5/overlay.es5.js.OverlayRef.attach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/cdk/esm5/overlay.es5.js:655:26)
    at MatSnackBar.webpackJsonp../node_modules/@angular/material/esm5/snack-bar.es5.js.MatSnackBar._attachSnackBarContainer (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/material/esm5/snack-bar.es5.js:709:26)
    at MatSnackBar.webpackJsonp../node_modules/@angular/material/esm5/snack-bar.es5.js.MatSnackBar._attach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/material/esm5/snack-bar.es5.js:729:26)
    at MatSnackBar.webpackJsonp../node_modules/@angular/material/esm5/snack-bar.es5.js.MatSnackBar.openFromComponent (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/material/esm5/snack-bar.es5.js:620:26)
    at MessageService.webpackJsonp../src/app/services/message.service.ts.MessageService.submit (http://localhost:9876/_karma_webpack_/webpack:/src/app/services/message.service.ts:12:28)
    at http://localhost:9876/_karma_webpack_/webpack:/src/app/customer/add/add-customer.component.ts:58:31
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
    at ProxyZoneSpec.webpackJsonp../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:79:1)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:387:1)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:138:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:858:1
 at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:421:1)
    at ProxyZoneSpec.webpackJsonp../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:103:1)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:420:1)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:188:1)
    at drainMicroTaskQueue (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:595:1)
    at <anonymous>'
,Chrome 64.0.3282 (Mac OS X 10.13.3) ERROR: 'Http failure response for http://localhost:9876/assets/countries.json: 404 Not Found'

]]>
  </system-out>
  <system-err/>

```

### Desired behavior
Test should pass as before the cli upgrade.

### Mention any other details that might be useful (optional)
No difference when upgrading from angular 5.2.6 og 5.2.7
package.json:
```
"dependencies": {
    "@angular/animations": "^5.2.7",
    "@angular/cdk": "^5.2.3",
    "@angular/common": "^5.2.7",
    "@angular/compiler": "^5.2.7",
    "@angular/core": "^5.2.7",
    "@angular/flex-layout": "^5.0.0-beta.13",
    "@angular/forms": "^5.2.7",
    "@angular/http": "^5.2.7",
    "@angular/material": "^5.2.3",
    "@angular/platform-browser": "^5.2.7",
    "@angular/platform-browser-dynamic": "^5.2.7",
    "@angular/platform-server": "^5.2.7",
    "@angular/router": "^5.2.7",
    "@evryfs/angular-material-theme": "1.0.2",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^2.0.1",
    "@types/content-disposition": "^0.5.2",
    "content-disposition": "^0.5.2",
    "core-js": "^2.5.3",
    "file-saver": "^1.3.3",
    "hammerjs": "^2.0.8",
    "i18n-iso-countries": "^3.6.1",
    "lodash": "^4.17.5",
    "ng-bootstrap": "^1.6.3",
    "ng-http-loader": "^0.7.1",
    "ngx-country-picker": "^1.2.0",
    "ngx-logger": "^2.0.0",
    "ngx-permissions": "^4.0.0",
    "ngx-webstorage": "^2.0.0",
    "rxjs": "^5.5.6",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.8.20"
  },
```

Wrongly reported in https://github.com/angular/angular/issues/22523 initially

**Comment by davidkarlsen** [comment]
This went away when I cleaned up my tests a bit - so might not be a cli bug as such - but definitively 1.7.1 -> 1.7.2 made it trigger

**Comment by filipesilva** [comment]
Closing as it doesn't seem to happen anymore.
