### ISSUE TITLE
Error in ng serve -No NgModule metadata found for 'AppModule'.

### ISSUE THREAD

**Issue by LallerNeha** [angular/angular-cli#9872]
# **Version**
Angular CLI: 1.5.2
Node: 6.3.1
OS: linux x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.2
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.2
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.8.1

# **Repro steps**
- ng serve
# **Observed behavior**

ERROR in Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (/var/www/html/edtech/protal-fe/node_modules/@angular/compiler/bundles/compiler.umd.js:20285:23)
    at CompileMetadataResolver.getNgModuleMetadata (/var/www/html/edtech/protal-fe/node_modules/@angular/compiler/bundles/compiler.umd.js:15238:60)
    at visitLazyRoute (/var/www/html/edtech/protal-fe/node_modules/@angular/compiler/bundles/compiler.umd.js:31176:104)
    at AotCompiler.listLazyRoutes (/var/www/html/edtech/protal-fe/node_modules/@angular/compiler/bundles/compiler.umd.js:31144:20)
    at AngularCompilerProgram.listLazyRoutes (/var/www/html/edtech/protal-fe/node_modules/@angular/compiler-cli/src/transformers/program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/var/www/html/edtech/protal-fe/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/var/www/html/edtech/protal-fe/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:246:66)
    at Promise.resolve.then.then (/var/www/html/edtech/protal-fe/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:537:50)
    at process._tickCallback (internal/process/next_tick.js:103:7)

# **Desired behavior**
I would like the web app to compile successfully

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
