### ISSUE TITLE
fresh install fail

### ISSUE THREAD

**Issue by emimarz** [angular/angular-cli#9917]
hi there,

I never install this app, this is the first install and it fails

I run this command
```
npm install -g @angular/cli
npm WARN engine @angular/cli@1.7.3: wanted: {"node":">= 6.9.0","npm":">= 3.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
npm WARN engine circular-dependency-plugin@4.4.0: wanted: {"node":">=6.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
npm WARN engine @angular-devkit/core@0.3.2: wanted: {"node":">= 6.9.0","npm":">= 3.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
npm WARN engine @angular-devkit/schematics@0.3.2: wanted: {"node":">= 6.9.0","npm":">= 3.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
npm WARN engine @ngtools/json-schema@1.2.0: wanted: {"node":">= 4.1.0","npm":">= 3.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
npm WARN engine @schematics/package-update@0.3.2: wanted: {"node":">= 6.9.0","npm":">= 3.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
npm WARN engine @angular-devkit/build-optimizer@0.3.2: wanted: {"node":">= 6.9.0","npm":">= 3.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
npm WARN engine @schematics/angular@0.3.2: wanted: {"node":">= 6.9.0","npm":">= 3.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
npm WARN engine @ngtools/webpack@1.10.2: wanted: {"node":">= 6.9.0","npm":">= 3.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
npm WARN optional dep failed, continuing fsevents@1.1.3
npm WARN optional dep failed, continuing fsevents@1.1.3
npm WARN optional dep failed, continuing fsevents@1.1.3
 
> uglifyjs-webpack-plugin@0.4.6 postinstall /home/oneuser/.nvm/versions/node/v4.8.3/lib/node_modules/@angular/cli/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

-
> node-sass@4.7.2 install /home/oneuser/.nvm/versions/node/v4.8.3/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-46_binding.node
Download complete
Binary saved to /home/oneuser/.nvm/versions/node/v4.8.3/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux-x64-46/binding.node
Caching binary to /home/oneuser/.npm/node-sass/4.7.2/linux-x64-46_binding.node
 
> node-sass@4.7.2 postinstall /home/oneuser/.nvm/versions/node/v4.8.3/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Binary found at /home/oneuser/.nvm/versions/node/v4.8.3/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux-x64-46/binding.node
Testing binary
Binary is fine
/home/oneuser/.nvm/versions/node/v4.8.3/bin/ng -> /home/oneuser/.nvm/versions/node/v4.8.3/lib/node_modules/@angular/cli/bin/ng
@angular/cli@1.7.3 /home/oneuser/.nvm/versions/node/v4.8.3/lib/node_modules/@angular/cli
âââ ember-cli-string-utils@1.1.0
âââ raw-loader@0.5.1
âââ circular-dependency-plugin@4.4.0
âââ karma-source-map-support@1.2.0
âââ semver@5.5.0
âââ core-object@3.1.5
âââ webpack-merge@4.1.2
âââ node-modules-path@1.0.1
âââ denodeify@1.2.1
âââ opn@5.1.0 (is-wsl@1.1.0)
âââ @ngtools/json-schema@1.2.0
âââ loader-utils@1.1.0 (big.js@3.2.0, emojis-list@2.1.0, json5@0.5.1)
âââ less-loader@4.1.0 (pify@3.0.0, clone@2.1.1)
âââ @schematics/package-update@0.3.2 (semver-intersect@1.3.1)
âââ webpack-dev-middleware@1.12.2 (path-is-absolute@1.0.1, time-stamp@2.0.0, range-parser@1.2.0, mime@1.6.0)
âââ minimatch@3.0.4 (brace-expansion@1.1.11)
âââ glob@7.1.2 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0)
âââ postcss-import@11.1.0 (postcss-value-parser@3.3.0, read-cache@1.0.0)
âââ nopt@4.0.1 (abbrev@1.1.1, osenv@0.1.5)
âââ source-map-support@0.4.18 (source-map@0.5.7)
âââ silent-error@1.1.0 (debug@2.6.9)
âââ license-webpack-plugin@1.2.3 (ejs@2.5.7)
âââ webpack-sources@1.1.0 (source-list-map@2.0.0, source-map@0.6.1)
âââ memory-fs@0.4.1 (errno@0.1.7, readable-stream@2.3.5)
âââ portfinder@1.0.13 (async@1.5.2, debug@2.6.9, mkdirp@0.5.1)
âââ chalk@2.2.2 (escape-string-regexp@1.0.5, supports-color@4.5.0, ansi-styles@3.2.1)
âââ stylus-loader@3.0.2 (lodash.clonedeep@4.5.0, when@3.6.4)
âââ file-loader@1.1.11 (schema-utils@0.4.5)
âââ fs-extra@4.0.3 (universalify@0.1.1, jsonfile@4.0.0, graceful-fs@4.1.11)
âââ webpack-subresource-integrity@1.0.4 (webpack-core@0.6.9)
âââ resolve@1.5.0 (path-parse@1.0.5)
âââ postcss@6.0.19 (supports-color@5.3.0, source-map@0.6.1, chalk@2.3.2)
âââ postcss-url@7.3.1 (mime@1.6.0, mkdirp@0.5.1, xxhashjs@0.2.2)
âââ @angular-devkit/schematics@0.3.2
âââ ajv@6.2.1 (fast-deep-equal@1.1.0, json-schema-traverse@0.3.1, fast-json-stable-stringify@2.0.0)
âââ cache-loader@1.2.2 (mkdirp@0.5.1, schema-utils@0.4.5, neo-async@2.5.0)
âââ sass-loader@6.0.7 (lodash.tail@4.1.1, pify@3.0.0, clone-deep@2.0.2, neo-async@2.5.0)
âââ clean-css@4.1.11 (source-map@0.5.7)
âââ uglifyjs-webpack-plugin@1.2.2 (serialize-javascript@1.4.0, source-map@0.6.1, schema-utils@0.4.5, uglify-es@3.3.9, worker-farm@1.6.0, find-cache-dir@1.0.0, cacache@10.0.4)
âââ copy-webpack-plugin@4.4.3 (serialize-javascript@1.4.0, is-glob@4.0.0, p-limit@1.2.0, globby@7.1.1, find-cache-dir@1.0.0, cacache@10.0.4)
âââ @ngtools/webpack@1.10.2 (tree-kill@1.2.0, source-map@0.5.7, magic-string@0.22.4, enhanced-resolve@3.4.1)
âââ style-loader@0.19.1 (schema-utils@0.3.0)
âââ url-loader@0.6.2 (mime@1.6.0, schema-utils@0.3.0)
âââ extract-text-webpack-plugin@3.0.2 (async@2.6.0, schema-utils@0.3.0)
âââ postcss-loader@2.1.1 (schema-utils@0.4.5, postcss-load-config@1.2.0)
âââ webpack-dev-server@2.11.2 (killable@1.0.0, connect-history-api-fallback@1.5.0, ansi-html@0.0.7, html-entities@1.2.1, ip@1.1.5, strip-ansi@3.0.1, supports-color@5.3.0, debug@3.1.0, loglevel@1.6.1, del@3.0.0, compression@1.7.2, bonjour@3.5.0, import-local@1.0.0, express@4.16.2, selfsigned@1.10.2, internal-ip@1.2.0, sockjs@0.3.19, array-includes@3.0.3, http-proxy-middleware@0.17.4, yargs@6.6.0, serve-index@1.9.1, spdy@3.4.7, sockjs-client@1.1.4, chokidar@2.0.2)
âââ stylus@0.54.5 (css-parse@1.7.0, debug@3.1.0, glob@7.0.6, mkdirp@0.5.1, source-map@0.1.43, sax@0.5.8)
âââ @angular-devkit/core@0.3.2 (source-map@0.5.7, chokidar@1.7.0, ajv@5.5.2)
âââ html-webpack-plugin@2.30.1 (toposort@1.0.6, loader-utils@0.2.17, bluebird@3.5.1, html-minifier@3.5.10, pretty-error@2.1.1)
âââ @schematics/angular@0.3.2 (typescript@2.6.2)
âââ @angular-devkit/build-optimizer@0.3.2 (source-map@0.5.7, typescript@2.6.2)
âââ autoprefixer@7.2.6 (normalize-range@0.1.2, num2fraction@1.2.2, postcss-value-parser@3.3.0, browserslist@2.11.3, caniuse-lite@1.0.30000813)
âââ node-sass@4.7.2 (get-stdin@4.0.1, lodash.assign@4.2.0, lodash.clonedeep@4.5.0, lodash.mergewith@4.6.1, async-foreach@0.1.3, in-publish@2.0.0, gaze@1.1.2, chalk@1.1.3, mkdirp@0.5.1, cross-spawn@3.0.1, nan@2.9.2, true-case-path@1.0.2, stdout-stream@1.4.0, npmlog@4.1.2, meow@3.7.0, sass-graph@2.2.4, request@2.79.0, node-gyp@3.6.2)
âââ lodash@4.17.5
âââ less@2.7.3 (graceful-fs@4.1.11, mime@1.6.0, image-size@0.5.5, source-map@0.5.7, errno@0.1.7, mkdirp@0.5.1, promise@7.3.1, request@2.81.0)
âââ webpack@3.11.0 (tapable@0.2.8, json-loader@0.5.7, loader-runner@2.3.0, interpret@1.1.0, json5@0.5.1, supports-color@4.5.0, acorn@5.5.3, source-map@0.5.7, ajv-keywords@3.1.0, mkdirp@0.5.1, enhanced-resolve@3.4.1, acorn-dynamic-import@2.0.2, async@2.6.0, yargs@8.0.2, uglifyjs-webpack-plugin@0.4.6, watchpack@1.5.0, node-libs-browser@2.1.0, escope@3.6.0)
âââ istanbul-instrumenter-loader@3.0.0 (convert-source-map@1.5.1, schema-utils@0.3.0, istanbul-lib-instrument@1.9.2)
âââ common-tags@1.7.2 (babel-runtime@6.26.0)
âââ rxjs@5.5.6 (symbol-observable@1.0.1)
```

```
ng help
/home/oneuser/.nvm/versions/node/v4.8.3/lib/node_modules/@angular/cli/models/config/config.js:17
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/oneuser/.nvm/versions/node/v4.8.3/lib/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

### Observed behavior
```
no work
```

### Desired behavior
```
work
```

### Mention any other details that might be useful (optional)
```
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.89-1 x86_64 GNU/Linux
```

**Comment by clydin** [comment]
From the log output:
```
npm WARN engine @angular/cli@1.7.3: wanted: {"node":">= 6.9.0","npm":">= 3.0.0"} (current: {"node":"4.8.3","npm":"2.15.11"})
```
The system appears to have node version 4.8.3; whereas the package requires >=6.9.0.  As per the project [README](https://github.com/angular/angular-cli#prerequisites), the required node version is currently 6.9.0 or higher.

**Comment by emimarz** [comment]
it is the first install so must have a warning or maybe you can not install, update nodejs greater version or something like that

it give me a warn not an error and that is wrong
