### ISSUE TITLE
Grid css

### ISSUE THREAD

**Issue by Patrick-Kan** [angular/angular-cli#9924]
ng build throw warning when playing with display: grid : 

> WARNING in ./src/app/product-setup/detail-entry/detail-entry.component.css
> (Emitted value instead of an instance of Error) autoprefixer: C:\Source\visionesell\ngcli\src\app\product-setup\detail-entry\detail-entry.component.css:60:9: Can not find grid areas: pmodel, pname, pweight, punit, pprice, pdiscount, pstart, pend, pgst, prelated, psave
> NonErrorEmittedError: (Emitted value instead of an instance of Error) autoprefixer: C:\Source\visionesell\ngcli\src\app\product-setup\detail-entry\detail-entry.component.css:60:9: Can not find grid areas: pmodel, pname, pweight, punit, pprice, pdiscount, pstart, pend, pgst, prelated, psave
>     at Object.emitWarning (C:\Source\visionesell\ngcli\node_modules\webpack\lib\NormalModule.js:117:16)
>     at result.warnings.forEach (C:\Source\visionesell\ngcli\node_modules\postcss-loader\lib\index.js:148:49)
>     at Array.forEach (<anonymous>)
>     at postcss.process.then (C:\Source\visionesell\ngcli\node_modules\postcss-loader\lib\index.js:148:27)
>     at <anonymous>
>  @ ./src/app/product-setup/detail-entry/detail-entry.component.ts 221:21-60
>  @ ./src/app/product-setup/product-setup.module.ts
>  @ ./src/$$_lazy_route_resource lazy
>  @ ./node_modules/@angular/core/esm5/core.js
>  @ ./src/main.ts
>  @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

css file :
.mat-form-field.mat-form-field {
    width: 100%;
 }
.gprodform {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-gap: 10px;
    grid-template-areas:
    "pmodel pmodel pmodel"
    "pname pname pname"
    "pweight pweight pweight"
    "punit punit punit"
    "pprice pprice pprice"
    "pdiscount pdiscount pdiscount"
    "pstart pstart pstart"
    "pend pend pend"
    "pgst pgst pgst"
    "prelated prelated prelated"
    "psave psave psave";
}

.gmodel {
    grid-area: pmodel;
}
.gname {
    grid-area: pname;
}
.gweight {
   grid-area: pweight;
}
.gunit {
    grid-area: punit;
}
.gprice {
    grid-area: pprice;
}
.gdiscount {
    grid-area: pdiscount;
}
.gdstart {
    grid-area: pstart;
}
.gdend {
    grid-area: pend;
}
.ggst {
    grid-area: pgst;
}
.grelated {
    grid-area: prelated;
}
.gsave {
    grid-area: psave;
}

@media (min-width: 1100px) {
    .gprodform {
        grid-template-areas:
        "pmodel pmodel pmodel"
        "pname pname pname"
        "pweight punit pprice"
        "pdiscount pstart pend"
        "pgst pgst pgst"
        "prelated . ."
        ". . psave";
    }
}

### Versions
Angular CLI 1.6.8`

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
