### ISSUE TITLE
ng new command not working for creating project

### ISSUE THREAD

**Issue by Anandks1993** [angular/angular-cli#9925]
### Versions
```
Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
```

### Repro steps
* ng new first-app

### Observed behavior
```
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://npmjs.registry.org/@types%2fjasmine failed, reason: getaddrinfo ENOTFOUND npmjs.registry.org npmjs.registry.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anand\AppData\Roaming\npm-cache\_logs\2018-03-10T10_28_09_269Z-debug.log
Error: Package install failed, see above.
Package install failed, see above.
```

### Desired behavior
I expect a new folder named first-app created in the desired location.

### Mention any other details that might be useful (optional)
I checked in my laptop for proxt settings and it is disabled.

**Comment by alejandromartincruz** [comment]
Same with me.

**## Versions**

> Angular CLI: 1.7.3
> Node: 8.9.4
> OS: OSX 10.13.3

**## Repro steps**

ng new first-app

## **Observed behavior**

```
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
events.js:183░░░░░░⸩ ⠦ extract:karma-coverage-istanbul-reporter: sill extract pac-proxy-agent@1.1.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
events.js:183░░░░░░⸩ ⠸ extract:xml2js: sill extract xml2js@0.4.19
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/tslint-33a9505a/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/codelyzer-a77ba81e/noOutputOnPrefixRule.d.ts'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/codelyzer-a77ba81e/noOutputOnPrefixRule.js'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/codelyzer-a77ba81e/noOutputRenameRule.d.ts'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/codelyzer-a77ba81e/noOutputRenameRule.js'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/codelyzer-a77ba81e/noUnusedCssRule.d.ts'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/codelyzer-a77ba81e/noUnusedCssRule.js'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/karma-jasmine-html-reporter-d76dd930/screenshots/reporter_2.png'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/json2.js'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/node_boot.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/example'
WARN tar ENOENT: no such file or directory, lstat '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/example'
WARN tar ENOENT: no such file or directory, lstat '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/example'
WARN tar ENOENT: no such file or directory, lstat '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/example'
WARN tar ENOENT: no such file or directory, lstat '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/example'
WARN tar ENOENT: no such file or directory, lstat '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/example'
WARN tar ENOENT: no such file or directory, lstat '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/example'
WARN tar ENOENT: no such file or directory, lstat '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/example'
WARN tar ENOENT: no such file or directory, open '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/jasmine-core-987b1e47/lib/jasmine-core/jasmine.css'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request@2.75.0 (node_modules/loggly/node_modules/request):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/request-f04995aa'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: get-uri@2.0.1 (node_modules/get-uri):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into '/Users/alex/Documents/proyectos/rollotest/node_modules/.staging/get-uri-f94623e6'

npm ERR! cancel after 1 retries!
```

**## Desired behavior**

I expect a new folder named first-app created in the desired location.

**Comment by juninhocruzg3** [comment]
Same with me too. I've this bug on Debian and on my node container in Docker.

## Versions

Angular CLI: 1.7.3
Node: 9.4.0
OS: Debian GNU/Linux 9 (stretch) 64-bit
## Repro steps

ng new first-app --style=sass

Observed behavior

npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end

## Desired behavior

I expect a new folder named first-app created in the desired location.

**Comment by annandr12** [comment]
Same with me too.
#### Versions
> Angular CLI: 1.7.4
> Node: 9.11.1
> OS: darwin x64

#### Repro steps
* ng new my-app

#### Observed behavior
```
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: slack-node@0.2.0 (node_modules/slack-node):
npm WARN network SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/slack-node/-/slack-node-0.2.0.tgz failed, reason: read ETIMEDOUT
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optionator@0.8.2 (node_modules/optionator):
npm WARN network SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz failed, reason: read ETIMEDOUT
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: prelude-ls@1.1.2 (node_modules/prelude-ls):
npm WARN network SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz failed, reason: read ETIMEDOUT

npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/semver-dsl/-/semver-dsl-1.0.1.tgz failed, reason: read ETIMEDOUT
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bannandr/.npm/_logs/2018-04-08T22_04_38_410Z-debug.log
Error: Package install failed, see above.
Package install failed, see above.
```

#### Desired behavior
I expect a new folder named my-app created in the desired location.

**Comment by Anandks1993** [comment]
Does anyone found a workaround or solution?. If so, please share here. Thank you.

**Comment by Anandks1993** [comment]
I tried the same as the following comment suggests https://github.com/npm/npm/issues/7945#issuecomment-357167879 and it did work for me.

**Note:** I haven't set any proxy behind my network.
