### ISSUE TITLE
ng serve throws an error. because Angular dependency is not being installed.

### ISSUE THREAD

**Issue by prog-rajkamal** [angular/angular-cli#9926]
### Versions
Angular CLI: 1.6.1
Node: 8.6.0
OS: win32 x64
Angular: 5.2.8

### Repro steps

1. ng new myproj
2. ng serve 

### Observed behavior

Cli throws error:

module.js:529
    throw err;
    ^
```
Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Raj\Work\mediaware\Code\ui\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```
### Desired behavior

ng serve should work correctly

### Mention any other details that might be useful (optional)

Issue is due to dependency `@angular-devkit/core` is not being installed.

when i try to install `@angular-devkit/core` (via yarn),  I get error that `@angular-devkit/core` (v0.4.5) requires node >= v8.9.0

WorkAround:  `yarn add @angular-devkit/core@0.3`

I have not verified this issue with npm.

**Comment by clydin** [comment]
The CLI has been updated significantly since version 1.6.1.  The current stable version is 8.3.5.  If this problem is still being encountered with the current version, please consider opening a new issue with updated details.
