### ISSUE TITLE
[6.0.0-beta.6] ng serve --aot=true throws error

### ISSUE THREAD

**Issue by benneq** [angular/angular-cli#9991]
### Versions
```
Angular CLI: 6.0.0-beta.6
Node: 9.7.1
OS: darwin x64
Angular: 6.0.0-beta.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router
```

### Repro steps

* npm install -g @angular/cli@next
* set `es2015` in `tsconfig.json`
* use (required because of `es2015`) `--aot=true` with `ng serve`

### Observed behavior
```
$ ng serve --aot
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties (aot).
Error: Schema validation failed with the following errors:
  Data path "" should NOT have additional properties (aot).
    at MergeMapSubscriber.registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/benneq/Development/ng6/node_modules/@angular-devkit/architect/src/architect.js:218:39)
    at MergeMapSubscriber._tryNext (/Users/benneq/Development/ng6/node_modules/rxjs/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/Users/benneq/Development/ng6/node_modules/rxjs/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/benneq/Development/ng6/node_modules/rxjs/Subscriber.js:90:18)
    at MergeMapSubscriber.notifyNext (/Users/benneq/Development/ng6/node_modules/rxjs/operators/mergeMap.js:145:30)
    at InnerSubscriber._next (/Users/benneq/Development/ng6/node_modules/rxjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/Users/benneq/Development/ng6/node_modules/rxjs/Subscriber.js:90:18)
    at MapSubscriber._next (/Users/benneq/Development/ng6/node_modules/rxjs/operators/map.js:85:26)
    at MapSubscriber.Subscriber.next (/Users/benneq/Development/ng6/node_modules/rxjs/Subscriber.js:90:18)
    at SwitchMapSubscriber.notifyNext (/Users/benneq/Development/ng6/node_modules/rxjs/operators/switchMap.js:126:30)
```

### Desired behavior
`aot` should work with `ng serve`, because else `es2015` will not work.

**Comment by AlQuraian** [comment]
Possible duplicate of #9994

**Comment by benneq** [comment]
Why is my issue a duplicate, if it was there before #9994 :D
But yes, seems to be the same issue: Serve / Dev Properties are broken.

**Comment by AlQuraian** [comment]
@benneq sorry I didn't pay attention to this. I'm just trying to help :)
Check my reply in the other issue it might help you till this gets fixed

**Comment by benneq** [comment]
I'll close this issue, and will add a comment to the other one.

**Comment by etsuo** [comment]
Hey sorry about that @benneq! I had searched the issues here before opening my issue, but didn't find this in my results.

**Comment by speige** [comment]
+1
