### ISSUE TITLE
Configuration 'proxy.config.json' could not be found in project with cli version 6.0.0-beta.6

### ISSUE THREAD

**Issue by ymcnicoll** [angular/angular-cli#9999]
When serving content using ng serve -pc proxy.config.json 

I get a error message like the following:

Configuration 'proxy.config.json' could not be found in project.
Error: Configuration 'proxy.config.json' could not be found in project.
    at Architect.getTarget (d:\Projects\components\lob\node_modules\@angular-devkit\architect\src\architect.js:114:23)
    at MergeMapSubscriber.architect.loadWorkspaceFromJson.pipe.operators_1.concatMap [as project] (d:\Projects\components\lob\node_modules\@angular\cli\models\architect-command.js:56:45)
    at MergeMapSubscriber._tryNext (d:\Projects\components\lob\node_modules\rxjs\operators\mergeMap.js:122:27)
    at MergeMapSubscriber._next (d:\Projects\components\lob\node_modules\rxjs\operators\mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (d:\Projects\components\lob\node_modules\rxjs\Subscriber.js:90:18)
    at MergeMapSubscriber.notifyNext (d:\Projects\components\lob\node_modules\rxjs\operators\mergeMap.js:145:30)
    at InnerSubscriber._next (d:\Projects\components\lob\node_modules\rxjs\InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (d:\Projects\components\lob\node_modules\rxjs\Subscriber.js:90:18)
    at Object.subscribeToResult (d:\Projects\components\lob\node_modules\rxjs\util\subscribeToResult.js:17:25)
    at MergeMapSubscriber._innerSub (d:\Projects\components\lob\node_modules\rxjs\operators\mergeMap.js:132:38)

but with version 6.0.0-beta.4 it all works fine.

### Versions
6.0.0-beta.6

**Comment by euangoddard** [comment]
I have also seen this issue after upgrading. If I move the `proxy.conf.json` file into `src` it works. I'd rather keep it in the root directory though if possible.

**Comment by rtaft** [comment]
issue seems to be that you can no longer use -pc, use --proxy-config

**Comment by clydin** [comment]
Yes.  CLI v6 now follows more standardized option parsing.  `-pc` is the equivalent of `-p -c`.  A note in the changelog should probably be added to mention this change.

**Comment by stallurikinect** [comment]
Follow the below steps, it helped me

i)create proxy.conf.json file under your project root instead of src folder
ii) add this exactly in package.json under scripts   "start": "ng serve --proxy-config proxy.conf.json"
iii)do "npm start" instead of "ng serve"

**Comment by zbagley** [comment]
Oof. Thank you @rtaft Makes sense cause the standardization, but didn't even think about it since I've used --pc for every project.

@clydin A note for the 'update.angular.io' would be useful.

**Comment by fott1** [comment]
Changing `ng serve --proxy-config proxy.conf.js` to `ng serve --proxy-config=proxy.conf.js`, solved my issue. _NOTE: i use .js not .json file_

**Comment by sushobitha** [comment]
> Changing `ng serve --proxy-config proxy.conf.js` to `ng serve --proxy-config=proxy.conf.js`, solved my issue. _NOTE: i use .js not .json file_

ng serve --proxy-config=proxy.conf.json  it worked! Thanks

**Comment by ChristianDanielMezieres** [comment]
step 2
rename your folder " proxy.config.json " to " proxy.config.json "
---------------------------------------- then -------------------
step 3 
change the path in " package.json " the line with " ng serve nproxy.conf.json --open " with " ng serve --proxy-config proxy.conf.json -o "

then you can run " yarn dev "

**Comment by mgechev** [comment]
@sushobitha thanks for sharing!
